### ISSUE TITLE
couldnt make it work

### ISSUE THREAD

**Issue by washaqq** [artf/grapesjs#1]
hi, 
i followed the instructions of installation here is the error log i get;

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@3.3.12
3 info using node@v5.5.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle grapesjs@0.1.0~prebuild: grapesjs@0.1.0
6 silly lifecycle grapesjs@0.1.0~prebuild: no script for prebuild, continuing
7 info lifecycle grapesjs@0.1.0~build: grapesjs@0.1.0
8 verbose lifecycle grapesjs@0.1.0~build: unsafe-perm in lifecycle true
9 verbose lifecycle grapesjs@0.1.0~build: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\[UserName]\Documents\GitHub\grapesjs\node_modules\.bin;C:\Windows\system32;C:\Windows;C:\Windows\system32\wbem;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Microsoft\Web Platform Installer;C:\Program Files\Microsoft SQL Server\120\Tools\Binn;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit;C:\Program Files\Microsoft SQL Server\110\Tools\Binn;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Users\[UserName]\AppData\Roaming\npm
10 verbose lifecycle grapesjs@0.1.0~build: CWD: C:\Users\[UserName]\Documents\GitHub\grapesjs
11 silly lifecycle grapesjs@0.1.0~build: Args: [ '/d /s /c', 'grunt build' ]
12 silly lifecycle grapesjs@0.1.0~build: Returned: code: 6  signal: null
13 info lifecycle grapesjs@0.1.0~build: Failed to exec build script
14 verbose stack Error: grapesjs@0.1.0 build: `grunt build`
14 verbose stack Exit status 6
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at EventEmitter.emit (events.js:185:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at ChildProcess.emit (events.js:185:7)
14 verbose stack     at maybeClose (internal/child_process.js:821:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid grapesjs@0.1.0
16 verbose cwd C:\Users\[UserName]\Documents\GitHub\grapesjs
17 error Windows_NT 6.1.7601
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
19 error node v5.5.0
20 error npm  v3.3.12
21 error code ELIFECYCLE
22 error grapesjs@0.1.0 build: `grunt build`
22 error Exit status 6
23 error Failed at the grapesjs@0.1.0 build script 'grunt build'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the grapesjs package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     grunt build
23 error You can get their info via:
23 error     npm owner ls grapesjs
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by washaqq** [comment]
here is another attempt:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@3.3.12
3 info using node@v5.5.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle grapesjs@0.1.0~prebuild: grapesjs@0.1.0
6 silly lifecycle grapesjs@0.1.0~prebuild: no script for prebuild, continuing
7 info lifecycle grapesjs@0.1.0~build: grapesjs@0.1.0
8 verbose lifecycle grapesjs@0.1.0~build: unsafe-perm in lifecycle true
9 verbose lifecycle grapesjs@0.1.0~build: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\[UserName]\Desktop\GrapesJs\node_modules\.bin;C:\Windows\system32;C:\Windows;C:\Windows\system32\wbem;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Microsoft\Web Platform Installer;C:\Program Files\Microsoft SQL Server\120\Tools\Binn;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit;C:\Program Files\Microsoft SQL Server\110\Tools\Binn;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Users\[UserName]\AppData\Roaming\npm
10 verbose lifecycle grapesjs@0.1.0~build: CWD: C:\Users\[UserName]\Desktop\GrapesJs
11 silly lifecycle grapesjs@0.1.0~build: Args: [ '/d /s /c', 'grunt build' ]
12 silly lifecycle grapesjs@0.1.0~build: Returned: code: 6  signal: null
13 info lifecycle grapesjs@0.1.0~build: Failed to exec build script
14 verbose stack Error: grapesjs@0.1.0 build: `grunt build`
14 verbose stack Exit status 6
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at EventEmitter.emit (events.js:185:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at ChildProcess.emit (events.js:185:7)
14 verbose stack     at maybeClose (internal/child_process.js:821:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid grapesjs@0.1.0
16 verbose cwd C:\Users\[UserName]\Desktop\GrapesJs
17 error Windows_NT 6.1.7601
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
19 error node v5.5.0
20 error npm  v3.3.12
21 error code ELIFECYCLE
22 error grapesjs@0.1.0 build: `grunt build`
22 error Exit status 6
23 error Failed at the grapesjs@0.1.0 build script 'grunt build'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the grapesjs package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     grunt build
23 error You can get their info via:
23 error     npm owner ls grapesjs
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by artf** [comment]
Seems like you are stuck at `npm run build` which requires Grunt.
I suggest to try to install Grunt globally first, so run `npm install -g grunt-cli` and then retry `npm run build`

**Comment by washaqq** [comment]
hi,

before i try to run it i read installation part and did all of you
mentioned before, it was the errors i get.

regards.

2016-02-08 21:27 GMT+02:00 Artur Arseniev <notifications@github.com>:
