### ISSUE TITLE
Suggestion - Undo Button

### ISSUE THREAD

**Issue by 2braincells2go** [artf/grapesjs#10]
Great project! Already have plans to use this in the classroom.

Something I noticed while trying was lack of undo button/function or step back (or am I missing it?). Accidentally deleted top section and no way to get it back.

Also, maybe a "clear and start new project". Cannot start new project with reload...

Thanks much for sharing this excellent tool. I am betting the my classroom will get a lot of use out of it!

**Comment by artf** [comment]
Thanks @2braincells2go  for your kind words, I really appreciate this and glad you find it useful.
Anyway, you can use CTRL/CMD + Z to undo and CTRL/CMD + SHIFT + Z to redo

**Comment by 2braincells2go** [comment]
Thanks for reply. Unfortunate that does not work for us. We use Windows and Ctrl+Z normally provides undo, but not on Grapejs.

**Comment by artf** [comment]
Mmm sounds like a bug, I've tried quickly with firefox on my old win7 and it works.
Can you tell me which is your SO and browser and eventually could you try with an other browser.
Thanks.

**Comment by 2braincells2go** [comment]
Getting mixed results. Using Win 10 and Chrome Version 48.0.2564.116 m. Got it to step back one time but no more. Would not "redo".

Did try on FF and worked for a few steps back then stopped. Could not get it to work again. Very possible it is Win 10. 

Using your demo for these tests. Cannot get good install on local machine so no way to test their. This is another issue and will try that again later. Report results in another issue if fails. Never got it to install correctly at Heroku.

**Comment by shayin** [comment]
why send me this mail? 



hxx.xuan@qq.com
 
From: Artur Arseniev
Date: 2016-02-22 20:13
To: artf/grapesjs
Subject: Re: [grapesjs] Suggestion - Undo Button (#10)
Mmm sounds like a bug, I've tried quickly with firefox on my old win7 and it works.
Can you tell me which is your SO and browser and eventually could you try with an other browser.
Thanks.

**Comment by artf** [comment]
@2braincells2go Can you post the log in case of error?
Check also this #9

**Comment by artf** [comment]
Sorry @2braincells2go forgot to update this issue. 
You should see now the buttons you've requested
![schermata 2016-08-05 alle 14 16 51](https://cloud.githubusercontent.com/assets/11614725/17436474/82ab4442-5b17-11e6-9f9f-da2385b8c35a.png)

**Comment by 2braincells2go** [comment]
Great job on GrapeJS Art! Thanks for update.
