### ISSUE TITLE
[Question/Bug] how to show plain text as trait

### ISSUE THREAD

**Issue by sublimekaushik** [artf/grapesjs#1000]
I want to show plain text within the trait under the setting button.
![trait_img](https://user-images.githubusercontent.com/16155284/38253141-83ea16fa-3773-11e8-8c87-bf47de99d399.png)

In the above image 'Configuration_Type' I want to show as plain text. How can I achieve this?

**Comment by Piterden** [comment]
Try to
```js
traits: [
  {
    type: 'hidden',
    label: 'Type',
  },
],
```
And then use CSS to hide what you don't need.

**Comment by sublimekaushik** [comment]
Thanks. It worked.
