### ISSUE TITLE
Please help me in integrating grapesjs with graphQL

### ISSUE THREAD

**Issue by tejaravi** [artf/grapesjs#1002]
Hi Guys,

Can you help me out on how to query urlStore, urlLoad instead of using rest api call, we need to use graphQL.
In GraphQL we will have only one global end point URL, but to save/retrieve the data we need to use the graphQuery Language, like:
 (here we are using Angular integrated with apollo to work with graphQL) onInit we are querying and subscribing to the response.
ngOnInit() {
    this.apollo.watchQuery({
      query: gql `
  query getGrapesContent {
  getGrapes(id:"Z3JhcGVzOjE=") {
    Name
    Html
    Css
  }
}
`;
    }).valueChanges.subscribe((response) => {
      // 5
      this.Html = response.data.Html;
      this.Css = response.data.Css;
     });

  }
}

Can you help us how can we use this logic with grapesJs.

**Comment by artf** [comment]
Try to implement a custom Storage Manager https://github.com/artf/grapesjs/wiki/API-Storage-Manager#add
