### ISSUE TITLE
[FEATURE REQUEST] Enhance "draggable" attribute of components in order to allow excluding certain components when wildcard "*" is set for draggable components

### ISSUE THREAD

**Issue by gabrigcl** [artf/grapesjs#1004]
Hi. I wish to enhance "draggable" attribute of components in order to allow excluding certain components when wildcard "*" is set for draggable components. For example, according to my case:

I need the "video" and "image" component to be draggable on every component, except the "my_custom_component". My suggestion is to add a new attribute "draggable_excluding" or to enable two fields in "draggable" attribute as an object: 
      `draggable: {
            components: c, //c typeof string or array
            exclude: e //e typeof string or array
         }`

Thanks in advance.

**Comment by artf** [comment]
You mean something like `draggable: "*:not(your-component)"`?

**Comment by gabrigcl** [comment]
Yes, I liked your thinking!

**Comment by artf** [comment]
Inside `draggable` and `droppable` properties you can pass any CSS-like query string so it's already possible
