### ISSUE TITLE
[Question] Richtext editor for trait

### ISSUE THREAD

**Issue by krunal039** [artf/grapesjs#1009]
Is there way to have richtext box for trait. We want to user to insert rich text for trait and not sure how can we do it. We have below use case.

There would be mutliple picture on page and once user mouse hover it will display some rich text and we want  create component so admin can easily create page with above feature but not sure how can we allow

**Comment by Piterden** [comment]
But traits actually, are attributes of an element. For what purpose you need to use RTE there.

**Comment by krunal039** [comment]
We need user to add rich text with image and rich text is only visible when
image mouse hover and user can drag and drop multiple image with rich text.

**Comment by Piterden** [comment]
You don't need a RTE-trait. Why user can't use RTE in inline mode?

**Comment by krunal039** [comment]
We can but RTE content is only been shown on mouseover and not sure how can we achieve inline RTE?

**Comment by artf** [comment]
@krunal039 if you want an RTE trait, [create a custom one](https://github.com/artf/grapesjs/wiki/Traits#define-new-trait-type) and initialize it (eg. CKEditor) in `getInputEl`
