### ISSUE TITLE
[Question] Does grapejs provide variable selection in the UI

### ISSUE THREAD

**Issue by pg1671** [artf/grapesjs#1011]
I have just come across grapejs and it looks amazing but I cannot find good information on how to manage variables.

Is there are a way to give grapejs a list of allowed variables so the user can insert them easily through the UI when creating a template (editing text) or do they have to just type in the variable syntax where they need it, or am I expected to extend grapejs to add this functionality?

I could not see this feature in either of the demos and cannot see it mentioned in the documentation though I assumed it would be a fundamental feature.

thanks.

**Comment by artf** [comment]
There is no such a built-in feature but you can easily extend grapesjs for it.
If you're looking for the usage of variables during the text editing [this snippet](https://github.com/artf/grapesjs/issues/481#issuecomment-342282125) might help you.

You can also make use of [Blocks](https://github.com/artf/grapesjs/wiki/Blocks) to create draggable variables, eg:
```js
editor.BlockManager.add('my-var-block', {
  label: 'Simple variable',
  content: '{{ SOME_VAR_EXAMPLE }}',
});
```
or even mixing them with custom [Components](https://github.com/artf/grapesjs/wiki/Components) to display variables differently inside the canvas. Quick example https://jsfiddle.net/jhf0rsbj/
