### ISSUE TITLE
Is it possible to export the html content with data attributes in editor?

### ISSUE THREAD

**Issue by anand-gopinath** [artf/grapesjs#1012]
@artf Is it possible to export the html content with  `data attributes` in order reuse? 

We discussed about this on earlier , on How to pass `data attributes ` in a model

<img width="914" alt="screen shot 2018-04-06 at 4 07 48 pm" src="https://user-images.githubusercontent.com/25955939/38417119-c0af0b02-39b4-11e8-8606-4fb2bf2f13ab.png"> and i got your response.

I followed this and now Is it possible to get those those data-attributes should be appended in the htlm while exporting like below?
![ff](https://user-images.githubusercontent.com/25955939/38420046-31736800-39c0-11e8-91fe-464ec815a1dc.png)

**Comment by anand-gopinath** [comment]
@artf - Could you please take a look...

**Comment by artf** [comment]
No @anand-gopinath, `data-gjs-*` attributes are only for import purpose
