### ISSUE TITLE
[Question] making preview mode remember if visibility mode should be restored or not

### ISSUE THREAD

**Issue by tommedema** [artf/grapesjs#1014]
Currently when you enable preview mode and then disable it again, it always turns on visibility mode, even if visibility mode was turned off. This can be rather annoying.

I would like to create a PR to fix this, but could use your advice because I'm not completely following how you would do this properly in the way you use backbone.

At `commands/view/Preview.js` you have the following logic in the `stop` function:

<img width="385" alt="screen shot 2018-04-06 at 4 24 34 pm" src="https://user-images.githubusercontent.com/331833/38448138-05a23d7c-39b7-11e8-8ef2-418b429960b5.png">

Now, line 54 should become conditional. Something like:

```
    if (editor.visibilityMode()) {
        editor.runCommand('sw-visibility');
    }
```

How would you implement this `visibilityMode` boolean? Would this be part of the components model?

**Comment by tommedema** [comment]
@artf I can probably do it if I can ask some questions here along the way. I'm still getting used to Backbone. Where would you put that `Commands` object?

Could you elaborate more on this?

> I'd like also to move the runCommand/stopCommand logic from Editor and put it inside new Commands.run/stop methods (just to make it a more organized).

**Comment by artf** [comment]
For `Commands` I mean the [Commands module](https://github.com/artf/grapesjs/blob/dev/src/commands/index.js)

> Could you elaborate more on this?

I'd like, for example, moving [this `Editor. runCommand ` logic](https://github.com/artf/grapesjs/blob/dev/src/editor/index.js#L437-L443) inside the [Commands module](https://github.com/artf/grapesjs/blob/dev/src/commands/index.js), so in the `Editor` we will get:
```js
    runCommand(id, options = {}) {
      return em.get('Commands').runCommand(id, options);
    },
```

**Comment by artf** [comment]
Released https://github.com/artf/grapesjs/releases/tag/v0.14.27
Now you can track the state of a command
```js
const cm = editor.Commands;
cm.run('preview');
cm.isActive('preview'); // -> true
cm.stop('preview');
cm.isActive('preview'); // -> false

// Get all active commands
cm.getActive();
```
