### ISSUE TITLE
[Question] Where are the built in properties defined?

### ISSUE THREAD

**Issue by andresmgsl** [artf/grapesjs#1015]
Hey artf, really nice tool. 

I'm customizing it and i need to do some adjustment.

Thanks

**Comment by artf** [comment]
Hi Andres, if you're talking about Component's properties you will find them [here](https://github.com/artf/grapesjs/blob/dev/src/dom_components/model/Component.js#L28)

**Comment by andresmgsl** [comment]
Thank you for your answer, I did not refer to those but to [these](https://github.com/artf/grapesjs/wiki/Built-in-properties), but I could already notice that they are native CSS properties. I have another doubt but I will open a new problem to touch it in detail.
