### ISSUE TITLE
[Question] Button staying pressed after running command

### ISSUE THREAD

**Issue by johndc7** [artf/grapesjs#1016]
Is there any way to keep a button from staying pressed after the command completes?

Been looking through the documentation and didn't see anything regarding this

**Comment by artf** [comment]
The button instance is passed as a second argument if the command is executed from a button, so you can disable it in this way
```js
run(editor, sender) {
	sender && sender.set('active', false);
	...
},
stop(editor, sender) {
	...
},
```
