### ISSUE TITLE
[Question] Change default panel for Block Manager and Style Manager

### ISSUE THREAD

**Issue by andresmgsl** [artf/grapesjs#1018]
Hi again Artf, 

I was reviewing the files that you defined with the [basic commands](https://github.com/artf/grapesjs/tree/dev/src/commands/view) (such as opening the style manager) and I have a question about it. Is it possible to modify the default panel name in which the **Block Manager** and **Style Manager** are opened? As we can see [here](https://github.com/artf/grapesjs/blob/cfde1c1413bac0642523049fccf4c978c78271c5/src/commands/view/OpenBlocks.js#L8) and [here](https://github.com/artf/grapesjs/blob/cfde1c1413bac0642523049fccf4c978c78271c5/src/commands/view/OpenStyleManager.js#L41) the names of the panels are hard-coded and they are also the same, which means that by default both belong to the same panel. I found several ways to achieve what I want but since my knowledge about this tool is still very basic, I would like to know what would be the path you would take.

Thanks for read.

**Comment by artf** [comment]
Well yeah, those panels are designed that way just to create the "tab effect", you can add a new command with the **same id** and implement your logic. I also suggest  to have a look at how to create a [fully custom panels](https://codepen.io/artf/full/MQpZPj/)
