### ISSUE TITLE
[Issue] Body Background color does not change second time.

### ISSUE THREAD

**Issue by fsaiyedOB** [artf/grapesjs#1019]
Hey,
I'm using Grapes@0.14.6.

I'm having an issue with `body` CSS stylings.

My scenario:

I'm opening a blank file from local file system. I changed `body` background color to `#ff0000` and saved the file. File is saved properly with css as of `body{background-color:#ff0000}` when I opened that file in text editor locally.

**But** when I opend that same file in GrapesJS editor again, now my code shows `body{background-color: rgb(255,0,0)}` . And when I update body color to `#00ff00` then a new body style is defined above the `body{background-color: rgb(255,0,0)}` with `body{background-color:#00ff00}` and my body backgroud color remains same old to `rgb(255,0,0)` as it overrides the new value of `#00ff00`. 

How to resolve?

Also `body{margin:0}` is added everytime automatically. How to prevent?

**Comment by fsaiyedOB** [comment]
Maybe related to #552

**Comment by artf** [comment]
Hey thanks Faizan, as you already realized, we aware of this issue, therefore I close this one and suggest you to follow it there (subscribe to it)
