### ISSUE TITLE
Auto scroll while dragging 

### ISSUE THREAD

**Issue by vankyy26** [artf/grapesjs#102]
1 thing I'm thinking for. Right now when I use the editor on my 15,9-inch laptop the editor cannot fit inside the view screen. When I scroll down and pick a block from these at the bottom isn't possible to put it on a place while dragging because the window won't auto scroll above. So is it possible to auto move/scroll the page while dragging? Otherwise, I must put the block at the bottom and then move it to the desired place after manual scroll. I'm using the touchpad - no mouse. :)
![2017-06-03](https://cloud.githubusercontent.com/assets/10697327/26744846/656cff8a-47f0-11e7-8847-8e30e892ca27.png)

**Comment by artf** [comment]
thanks @vankyy26 for pointing this out. I added the request to the roadmap
