### ISSUE TITLE
[QUESTIONS/BUG?] Non local connexion

### ISSUE THREAD

**Issue by Blendman974** [artf/grapesjs#1020]
Using latest version with my ubuntu laptop. Node is installed, "npm start" is working but I can't manage to acces grapesjs from another computer, node server seems to be accepting only local connexion. Is there a way to fix this ? And is there a way I can change the port on wich it's running (8080) ?

**Comment by artf** [comment]
We're using [webpack-dev-server](https://github.com/webpack/webpack-dev-server) as a development server therefore you can use any of its options, eg.
```sh
npm start -- --port 8088
```
