### ISSUE TITLE
[QUESTION] Style Manager sectors

### ISSUE THREAD

**Issue by FrciSmrci** [artf/grapesjs#1021]
Hey @artf ,

due to the lack of documentation I have a hard time figuring out, how to add component settings (traits ) to the Style Manager panel section as you did in the [demo]( http://grapesjs.com/demo.html ).

Could you please give me a hint how to implement this? I think that the demo project code if open sourced would come real handy when it comes to understanding of the grapesjs as a whole.

Thank you in advance. 

Have a great day. :)

**Comment by artf** [comment]
>  I think that the demo project code if open sourced would come real handy when it comes to understanding of the grapesjs as a whole.

It is indeed, the whole site is open sourced, you just have to switch the branch https://github.com/artf/grapesjs/tree/gh-pages :)
BTW the part you were looking for
https://github.com/artf/grapesjs/blob/gh-pages/demo.html#L1394-L1415
