### ISSUE TITLE
[BUG] Drag and drop blocks are not working in IE Browser

### ISSUE THREAD

**Issue by suthars** [artf/grapesjs#1022]
Hi,

There is some bug related to "Drag and drop blocks are  not working in IE Browser ",
I didn't get better solution regarding this issue.

Also there is no method to reinitialize the grapes editor.
Here is my below script:

 grapesjs.init({
                container: '#gjs',
                plugins: ['gjs-blocks-basic'],
                components: newscontent,
                storageManager: {
                  autosave: false,
                  setStepsBeforeSave: 1,
                  type: 'remote'
                },
                assetManager: {
                  assets: assetArr,
                  upload: 1,
                  dropzone: 0,
                  uploadText:"Upload image here",
                  openAssetsOnDrop: 0,
                  modalTitle: 'Select Image',
                  autoAdd: 1,
                  handleAdd: (textFromInput) => {
                     console.log(textFromInput);
         },

Please help me out of this issue.

**Comment by artf** [comment]
Fixed here #768 will be available in the next release
