### ISSUE TITLE
GrapeJS can't render HTML code

### ISSUE THREAD

**Issue by phucphanJaneto** [artf/grapesjs#1026]
Hi,

I intergrated GrapesJS to my application (asp.net MVC) and it works but sometimes GrapesJS can't render HTML. 

First, I clone html from another URL and add this html to GrapesJS. This works correctly. 
Second, I get html from GrapesJS  editor and save this to file. 
Final, I refresh page and load content in this file and add this html string to GrapesJS. Sometimes I get the error message and GrapesJS editor is empty
![image](https://user-images.githubusercontent.com/37202364/38545207-bb393c5c-3cd3-11e8-9289-47fb8e70d06d.png)

Html string in attached filles. 
[20907.zip](https://github.com/artf/grapesjs/files/1893739/20907.zip)

**Comment by artf** [comment]
Seems like you're doing something wrong when saving/loading the template, look at the error, it's trying to use `":{"s` as an attribute
