### ISSUE TITLE
Newbie Questions and Ideas

### ISSUE THREAD

**Issue by kosirm** [artf/grapesjs#1027]
First of all sorry because I'm using Issues as a help forum.

I **REALLY**  need some tutorials, examples, etc. If you need help, I'm willing to spend some time on this. For example GitBook or something similar. Wiki is great, but not really what I'm looking for. I believe that there is a ton of examples already on GitHub, but scattered around issues etc. 
This is a short list of examples/questions I'm interested in: 

- How to save sections/blocks /components (for example to GitHub)?
- How to load remote sections/blocks (for example from GitHub)?
- What is the exact relationship between components, blocks, and sections?
- Learning resources for newcomers. What frameworks should I learn to understand and extend grapesjs?
- Explain project directory structure? What is where?
- How to load custom CSS at runtime? From GitHub?
- How to save HTML/CSS separately?

My suggestion is to make an open list of examples, which are needed for the community to grow. I don't think this is such a hard task but would greatly help developers who come from other platforms.

**Comment by chapterjason** [comment]
> How to save sections/blocks /components (for example to GitHub)?

https://github.com/artf/grapesjs/wiki#storeload-data
https://github.com/artf/grapesjs/wiki/API-Storage-Manager

> How to load remote sections/blocks (for example from GitHub)?

https://github.com/artf/grapesjs/wiki#storeload-data
https://github.com/artf/grapesjs/wiki/API-Storage-Manager

> What is the exact relationship between components, blocks, and sections?

https://github.com/artf/grapesjs/wiki/Blocks
https://github.com/artf/grapesjs/wiki/Components

What are sections?

> Learning resources for newcomers. What frameworks should I learn to understand and extend grapesjs?

All used dependencies are listed here https://github.com/artf/grapesjs/blob/dev/package.json they all should have their own docs. Mainly I would say `Backbone` and JavaScript itself.

> Explain project directory structure? What is where?

After some days working with this project I figured out that every directory is a module with the views and models. More about views and models you can get at Backbone

> How to load custom CSS at runtime? From GitHub?

https://github.com/artf/grapesjs/wiki/API-Editor#setstyle
Loading css file directly I'm currently unsure.

> How to save HTML/CSS separately?

https://github.com/artf/grapesjs/wiki#storeload-data
https://github.com/artf/grapesjs/wiki/API-Storage-Manager

They are save separately, please read the docs (wiki).

**Comment by kosirm** [comment]
@chapterjason thank you so much for your time!
So exhaustive answer I really did not expect 😃 
Thanks again! 🥇

**Comment by adelliinaa** [comment]
Is there any tutorial on how to integrate customised components into the GrapeJS framework?
