### ISSUE TITLE
dragging text elements does not drop them correctly

### ISSUE THREAD

**Issue by Chinese1904** [artf/grapesjs#103]
First off, I just came across this, and this is probably the best/nicest open source tool I have ever seen! I am completely in love with this!

The very little time I had looking at it, I realized that there is a issue (not sure if it is known) dragging text elements in the demo page. (Chrome 58, Firefox 53) 

You are not able to drag the "Web" section in between the "Template" and "Builder" sections. 

Thanks for this :-)

**Comment by artf** [comment]
thanks @Chinese1904 for your kind words, really appreciate :)
Anyway, seems like it's related to the float property of those components, I'll try to investigate better

**Comment by rgcarrasqueira** [comment]
If it helps, I got the same error. I'm attaching a screenshot with the error

![screen shot 2017-07-04 at 13 40 07](https://user-images.githubusercontent.com/97540/27838057-84753fc8-60be-11e7-9bf6-443812f64f5e.png)

**Comment by artf** [comment]
thanks @rgcarrasqueira but I think your problem is due to another issue with the last version, I'll fix it for the next release

**Comment by bassouma21001** [comment]
@artf  When is the new version
I have the same problem

**Comment by artf** [comment]
This actually should be closed already... @bassouma21001 can you elaborate your issue please?
