### ISSUE TITLE
[BUG]: When IDs are used, it's not possible to update or remove a style

### ISSUE THREAD

**Issue by nojacko** [artf/grapesjs#1033]
## Steps to reproduce
0. https://jsfiddle.net/1cjjr02p/
0. Click the text in editor, change background colour.
0. Export CSS. You'll see both new and original colours exist in an order that prevents the new colour being used.

```
/* CSS: Output (minus some irrelevant bits) */
#c318{
  background-color:#000000;             /* New colour **/
}
#c318{
  background-color:rgb(152, 77, 77);     /* Original colour **/
}

/* CSS: Expected */
#c318{
  background-color: #000000;     /* New colour **/
}
````

3.. Using same jsfilddle, it's not possible to remove CSS attribute.

This is similar to #552 #986 but the issue is only present when IDs are used. Classes are cool.

**Comment by nojacko** [comment]
To elaborate a little, it seems to be when you apply styles to a box it adds the ID. When you export that and reload it to Grapes the problem happens.

**Comment by artf** [comment]
Related to #932
Use `avoidInlineStyle: true`
