### ISSUE TITLE
[Bug] Devices with a percentage width not supported

### ISSUE THREAD

**Issue by dsgh** [artf/grapesjs#1037]
version: 0.14.8

### Steps to reproduce the bug

- Use the [grapesjs-blocks-bootstrap4](https://github.com/z1lk/grapesjs-blocks-bootstrap4) plugin.
- Use the `index.html` example there - Keep the default devices (which include one defined as `100%`)
- Add any block with classes (eg `Container`)
- Click that added block in the editor canvas.
- This results in an error: `Uncaught DOMException: Failed to execute 'querySelectorAll' on 'Element': '#gjs-css-rules-100%' is not a valid selector.`

### Screenshot

![error](https://user-images.githubusercontent.com/52310/38692889-1e366dde-3e7d-11e8-9cd9-dd1799f5fcf2.png)

**Comment by maxtacco** [comment]
This is probably related to https://github.com/artf/grapesjs/issues/896. I guess the logic should be adjusted to handle different types of units, i.e px, em, % etc.
