### ISSUE TITLE
[Question] Should I always save the CSS? (and other questions)

### ISSUE THREAD

**Issue by leobeal** [artf/grapesjs#1043]
First, thanks a lot for this! It's an amazing piece of software.

I've been playing around with grapesjs, and few questions popped up, would appreciate if you guys could help me.

1. For my use case, I would not want to save the css, I would prefer have it already defined and let my users just play around with the existent options. Although, I've seen that, let's say, when inserting a map, a new specific class is created for that element, so I would need to export the css as well.
any recommendation on this? Should I always save the css as well?

2. I could find the base blocks for some elements in the examples provided (webpage demo and newsletter demo, thanks!) but I could not find where the **grids** are set. 
I would like to avoid the grid resize (not sure why it's even allowed :) ) Any way to do that?

3. When using the `grapesjs-blocks-basic` I was able to set the wanted blocks, now I am using the `gjs-preset-webpage` the bellow does not seem to work 
```
pluginsOpts: {
    'gjs-preset-webpage': {
    blocks: ['column1', 'column2', 'column3', 'column3-7', 'text', 'image']
    }
 },
```

thanks again!

**Comment by artf** [comment]
> For my use case, I would not want to save the css, I would prefer have it already defined and let my users just play around with the existent options. Although, I've seen that, let's say, when inserting a map, a new specific class is created for that element, so I would need to export the css as well.
any recommendation on this? Should I always save the css as well?

So this mean you don't want the user to apply styles on components, in that case just hide the style panel

> I could find the base blocks for some elements in the examples provided (webpage demo and newsletter demo, thanks!) but I could not find where the grids are set.
I would like to avoid the grid resize (not sure why it's even allowed :) ) Any way to do that?

Grids are from [grapesjs-blocks-basic](https://github.com/artf/grapesjs-blocks-basic) and you can find their implmentation [here](https://github.com/artf/grapesjs-blocks-basic/blob/master/src/blocks.js#L107-L120)

> When using the grapesjs-blocks-basic I was able to set the wanted blocks, now I am using the gjs-preset-webpage the bellow does not seem to work

Check better the [options](https://github.com/artf/grapesjs-preset-webpage#options), you have to pass them via `blocksBasicOpts` key
