### ISSUE TITLE
change src for image element in model

### ISSUE THREAD

**Issue by adib18** [artf/grapesjs#1044]
hello
when a image block drop to editor i hide the default asset manager and display my custom asset manager:
```
editor.on('canvas:drop', function (e,result) {
            if(result.attributes.type == 'image'){
                modal.close();
                jQuery('div.my_custom_asset_manager').show();
            }
        });
```
fot this i have no problem.but when a image select on my custom asset manager i change src from image element in the editor with jquery.

`jQuery('iframe').contents().find('img.in_editor').attr('src','custom_url');`
but when move the image element in the editor from a block to another block src attribute removed.I search and find out when change src with jquery only view changed but model must change for image element.now i want to know how i can change src for image element in model.
thanks

**Comment by artf** [comment]
Correct your custom asset manager implementation, it's not reliable (eg. if the user double click on the image you'll still see the default one) #491

**Comment by Stejsi** [comment]
Hello,
i am used this solution, and it works, but now i am not able to asset background-image in Style Manager. 
It use custom function spreadUrl(), but i dont know how to call it without modify Grapesjs core. 
Thanks for help!
