### ISSUE TITLE
[Question] checked value is not as per expected

### ISSUE THREAD

**Issue by HarshOB** [artf/grapesjs#1048]
I have visited grapes live demo and found out that there can be two ways to create checkbox.

As you can see if I checked **required** checkbox then it will generate only **required** in attribute and if I checked **checked** then it will generate **checked="checked"** as an attribute.

what is the way to generate cheched="checked".
![screenshot from 2018-04-16 18-20-59](https://user-images.githubusercontent.com/28950214/38810076-4a04c2c0-41a3-11e8-8290-1250037854be.png)

**Comment by artf** [comment]
Released a new [grapesjs-plugin-forms](https://github.com/artf/grapesjs-plugin-forms) version with the [fix](https://github.com/artf/grapesjs-plugin-forms/commit/f8f10f42672992657530697e3ed43fba7f539086)
