### ISSUE TITLE
[BUG] Can not modify inner text of a DIV

### ISSUE THREAD

**Issue by indikaanu83** [artf/grapesjs#1055]
Hi,

I'm using the latest version (grapesjs - 0.14.9). I have loaded an external HTML code to the editor. Then I tried to edit text within a DIV. But it is not allowing me. 

Try importing the below code to the Newsletter demo. You'll see that you can't edit the text.

```
<div id="iq64wx">You can not edit me :P
   <br/>
   <br/>
  Try editing me as well.
   <br/>
   <br/>
  nope
   <br/>
   <img src="http://via.placeholder.com/350x150" width="312" height="61" alt="" border="0"/>
   <br/>
   Name Surname 
</div>
```

If you remove the image tag and import it again, then it works!. Any help would be much appriciated 

Thanks
Anuradha

**Comment by tommedema** [comment]
This is due to https://github.com/artf/grapesjs/issues/1013

**Comment by artf** [comment]
@indikaanu83 subscribe to #1013 if you want to be notified when the issue is solved

**Comment by indikaanu83** [comment]
Oky Will. thanks Artur.
