### ISSUE TITLE
[Question]: Load html content from a file dynamically

### ISSUE THREAD

**Issue by rohanreddyg** [artf/grapesjs#1059]
Hi,
I need to load content from a html file from server onto editor after or while initializing editor. How this can be implemented?
HTML will have regular html content i.e HTML tag, script tags, css links and body content which needs to be loaded into editor.

StoreManager api documentation is limited and looks like default load looks for a specific JSON structure with separate html, css as data.

Thanks in advance.

**Comment by artf** [comment]
> StoreManager api documentation is limited and looks like default load looks for a specific JSON structure with separate html, css as data.

Because this is the right way of loading template data, but if this is the first time you load a template you can place all the HTML inside `html` key instead of `components` (by leaving it empty) and the editor will use it

**Comment by rohanreddyg** [comment]
Sorry to ask again... how to set to html key? any sample code? editor.setHtml is not working.

**Comment by suresh5** [comment]
> > StoreManager api documentation is limited and looks like default load looks for a specific JSON structure with separate html, css as data.
> 
> Because this is the right way of loading template data, but if this is the first time you load a template you can place all the HTML inside `html` key instead of `components` (by leaving it empty) and the editor will use it

can you give me simple example with basic html in json reponse ?

**Comment by artf** [comment]
@suresh5 can you please avoid making requests on closed issues...
