### ISSUE TITLE
How we can show countdown traits

### ISSUE THREAD

**Issue by Deepak813** [artf/grapesjs#1061]
Hi artf,

Please let us know how we get the countdown elements in edit mode means when we set the template html using editor.setComponents(templateHTML); 
then when we click on countdown element it displays the id and title fields not the Endzone and endText fields.
I have tried a lot with setting model type as datetime-local but still not succeed.

Please let us know resolve this.

**Comment by artf** [comment]
`editor.addComponents('<div data-gjs-type="countdown"></div>')`

You can create a custom template by relying on `data-js` identifiers
```js
editor.addComponents(`<div data-gjs-type="countdown">
	<span data-js="countdown">
		Days: <span data-js="countdown-day"></span>
		Hours: <span data-js="countdown-hour"></span>
		Minutes: <span data-js="countdown-minute"></span>
		Seconds: <span data-js="countdown-second"></span>
	</span>
	<span data-js="countdown-endtext">
	</span>
</div>`);
```
