### ISSUE TITLE
Change the colour and thickness of hover. Also I want different hover colours for different elements.

### ISSUE THREAD

**Issue by perfect-coders** [artf/grapesjs#1063]
Hi @artf , hands raised for this awesome product.  I am trying to change the hover colour on hovering elements.  I am also trying to give different colours and width to hovers on hovering different elements.
Please help me to get this done.
Thanks in Advance.

**Comment by chapterjason** [comment]
You can change the `state` for an element in the `style-manager` and then change the `color` and all the other properties.
![image](https://user-images.githubusercontent.com/1337562/39211389-b88b9084-480b-11e8-8cdd-d2983b5e38ee.png)

The editor will save then the properties associated to their state in css with all the `#test:hover { ... }` selectors.

**Comment by perfect-coders** [comment]
@chapterjason - Thanks for the reply. but this didn't solve my problem. I don't want user to select element and change the states. I want to change the colours, thickness permanently for the whole editor. Means it doesn't depend on the user. I want to change it for the editor permanently.
