### ISSUE TITLE
[Question] Editor only meant to be fullscreen?

### ISSUE THREAD

**Issue by bigd213** [artf/grapesjs#1064]
I have successfully contained **div id="gjs"** inside of another div container so that it would not take up the full screen.  I am doing this so that my own navigation bars can be show above and to the left of the grapesjs editor.

I have tweaked the **height: '100%'** value and found that to help, but I could not find a value for width.

I have found that the color picker is now running off the right side of the screen and before I go any further, wanted to see if there is a recommended best practice for NOT using the grapejs editor in fullscreen mode?

**Comment by bigd213** [comment]
Thanks - My question was answered with the **width** option.

**Comment by artf** [comment]
@chapterjason Seems like it doesn't handle issues closed by OP 😬 https://github.com/probot/no-response/issues/16

**Comment by thanhpd56** [comment]
@bigd213 Hi, i'm facing the problem like you when put editor inside layout with left navigation menu. How did you solve it?

**Comment by bigd213** [comment]
I have not yet finished the project, so I do not have a solution yet.
