### ISSUE TITLE
[QUESTION] Get content with inline CSS

### ISSUE THREAD

**Issue by JulyanoF** [artf/grapesjs#1066]
I've been looking for some explanation and I found that some email clients blocks CSS...

I would like to know if is there some way to get editor's html with all css inline, like `<div style="color:red; max-width: 100px"></div>` instead of classes

**Comment by chapterjason** [comment]
Hey,

There are some ways to do this.
Read [this](https://github.com/artf/grapesjs/issues/546) to get a solution to use [Juice](https://github.com/Automattic/juice)

For some more details I would read more in the docs about the storage-manager.

Please use the search functionality next time.

Cheer!
