### ISSUE TITLE
[BUG] - Grapesjs become null when allow script

### ISSUE THREAD

**Issue by phucphanJaneto** [artf/grapesjs#1067]
Hi @artf 

I initialized grapesjs without allow script. I imported html string from the attachment (template.zip) and Grapesjs can show it correctly

But when I allow script by `allowScripts: 1` in init code and imported the above html string. Grapesjs doesn't show any and I can't use any grapesjs. 

![image](https://user-images.githubusercontent.com/37202364/39227201-91ead3e2-4881-11e8-9528-61b04869bf88.png)

[template.zip](https://github.com/artf/grapesjs/files/1945509/template.zip)

**Comment by artf** [comment]
Can you provide a live demo on jsfiddle?

**Comment by phucphanJaneto** [comment]
Hi, @artf 

Sorry for late reply.  Here you are: https://jsfiddle.net/oq58jk1p/6/

Currently, I comment the line "allowScript: 1" in the jsfiddle. When you test please open this again. 

Thanks.

**Comment by artf** [comment]
Your demo doesn't help, you should create something minimal which indicates the issue, not just a copy-paste of your project (let's be respectful with the time of others)
