### ISSUE TITLE
[QUESTION] Image insert blocked

### ISSUE THREAD

**Issue by AboyobamX** [artf/grapesjs#1070]
I'm trying to build a website with grapesjs and now i'm facing the problem, that i can't insert any image from my PC.
When i try to upload an image the following information appears:

![bildschirmfoto 2018-04-25 um 14 35 33](https://user-images.githubusercontent.com/38724928/39246163-0bd3bff2-4896-11e8-8a92-a14cc5093269.png)

Does anybody know how to fix this problem?

Thanks for the help!
AboyobamX

**Comment by artf** [comment]
The demo uses Filestack's free plan therefore when the limit is reached the plugin is blocked (it resets each month). Moreover, the demo is designed to show GrapesJS's features and not as a service to create websites
