### ISSUE TITLE
Change the colours, thickness of hover permanently for the whole editor.

### ISSUE THREAD

**Issue by perfect-coders** [artf/grapesjs#1071]
@artf  - I don't want user to select element and change the states. I want to change the colours, thickness permanently for the whole editor by default. Means it doesn't depend on the user or any element. I want to change it for the editor permanently.

**Comment by chapterjason** [comment]
You can find all the styles for the editor in the following directory https://github.com/artf/grapesjs/tree/dev/src/styles/scss *Note: it's scss not css*

I you want to find out the css selectors directly, you can use the browser developer tools. If you have found your selectors you want to change, create a file write your overridings an load them after you load the editor. That should work.

Example: https://jsfiddle.net/3bprucnv/3/
