### ISSUE TITLE
Cannot add a new css rule if an element that is using it is not present in the html

### ISSUE THREAD

**Issue by andsnake** [artf/grapesjs#1072]
HI, i'm using the latest build and i have the issue as described in the title. 

I am editing html and css separately. 
I have noticed that when editing the css, if i try to add a new class, not used by any of the elements in the canvas yet, after saving, that css class is removed, 

if instead i go and create a dummy div, assign i.e class ="test", and then go and add the .test{color="red"} rule to the css, the css change is retained correctly. 

here is a JS Fiddle you can play with to see the behaviour. https://jsfiddle.net/d64sc5g4/

is this normal behaviour or a bug?

**Comment by artf** [comment]
Yes, it's a normal behavior, the editor optimizes the exported code, but in the next release you'll find a new [`keepUnusedStyles`](https://github.com/artf/grapesjs/issues/1053) option, which allows you to skip this optimization
