### ISSUE TITLE
How we can remove the selected component html

### ISSUE THREAD

**Issue by Deepak813** [artf/grapesjs#1077]
Hi artf,

Please let us know how we can remove the selected component html like 
I have one button html and when i selected that "gjs-comp-selected" class is appended
<button class="add_col_btn gjs-comp-selected" id="ir9j">Add New Column</button>

I want to remove this button html and replace with new content on particular event.
Please help us to know how we can remove the selected component.

**Comment by artf** [comment]
You can do something like this
```js
const component = editor.getSelected();
const coll = component.collection;
const at = coll.indexOf(component);
coll.remove(component);
return coll.add('<div>New content</div>', { at });
```

**Comment by Deepak813** [comment]
Hi artf,

Thanks for the message and provided code is working fine.

**Comment by mararn1618** [comment]
This has helped me a lot with programatically removing components and I just want to add some example code in Typescript for further reference.

### Typescript Example: Dynamically remove components
All components are removed that ..
* .. have a tagname = exampletag
* .. have an attribute = exampleattr

```
  /**
   * Removes all components from editor, that have a tag 'exampletag' and contain an attribute 'exampleattr'.
   */
  clearComponentsFromEditor(): void {

    let allComponents  = this.editor.getComponents();
    let componentsToBeRemoved = allComponents.filter(
      componentModel => (
        componentModel.attributes['tagName'] == 'exampletag' && null != componentModel.attributes.attributes['exampleattr'])  )
    );
    
    for(let comp of componentsToBeRemoved) {
      if(null != comp && null != comp.collection)
        comp.collection.remove(comp);
    }
  }
```
