### ISSUE TITLE
add custom date time picker for countdown

### ISSUE THREAD

**Issue by kuldeepcis** [artf/grapesjs#1078]
For countdown we would like to add our custom datetime picker not just the html one.We tried adding click event in its trait this way 
traits: [{
                            label: "Start",
                            name: "startfrom",
                            changeProp: 1,
                            type: n.dateInputType,
                            events:{
                            		click:"handleClick",
							       },
							       handleClick:function(e){alert('here')},
                        }

but this doesn't work.Can you please help with it.
can you please provide the unminified version of grapesjs-preset-webpage.min.js?

**Comment by nojacko** [comment]
Source codes:
* https://github.com/artf/grapesjs-preset-webpage
* https://github.com/artf/grapesjs-component-countdown

**Comment by artf** [comment]
@kuldeepcis please take a look at how to create [custom Traits](https://github.com/artf/grapesjs/wiki/Traits)

**Comment by kuldeepcis** [comment]
can you please provide the unminified version of grapesjs-preset-webpage.min.js?
