### ISSUE TITLE
Safari - TypeError: Attempted to assign to readonly property.

### ISSUE THREAD

**Issue by justvinz** [artf/grapesjs#108]
I get `TypeError: Attempted to assign to readonly property.` js error when I try to drag components from the side.

<img width="1026" alt="screenshot 2017-06-15 12 47 53" src="https://user-images.githubusercontent.com/5318794/27178068-10c85a14-51c9-11e7-900b-2b222056ad46.png">

**Comment by artf** [comment]
thanks @justvinz the last release should fix the issue, let me know if have any other problem
