### ISSUE TITLE
[BUG] - removePanel does not remove panels

### ISSUE THREAD

**Issue by mmeeeooowww** [artf/grapesjs#1081]
I'm trying to remove a panel. The function returns the panel the first time I run `removePanel` and then returns undefined if I run it again. It's worth noting that the panel is no longer returned when getting all panels, however it is still visible and functional. In my case I'm trying to remove the device selection buttons at the top left of the demo page but I did try to remove "options" and "views" as well with the same result.

Expected behavior:
Executing `editor.Panels.removePanel('devices-c');` should remove the device selection panel.

Current behavior:
Executing `editor.Panels.removePanel('devices-c');` _does not_ remove the device selection panel.

![image](https://user-images.githubusercontent.com/33463827/39554942-4080d802-4e3b-11e8-818f-4f118ba9f49c.png)

**Comment by artf** [comment]
I'll add a listener on this too
