### ISSUE TITLE
import template 

### ISSUE THREAD

**Issue by pintor-mato** [artf/grapesjs#1083]
Hi . I have a json string like this '{ "assets": "[{\"type\":\"image\",\"src\":\"./img/team1.jpg\",\"unitDim\":\"px\",\"height\":0,\"width\":0}]", "css": "* { box-sizing: border-box; } body {margin: 0;}", "styles": "[]", "html": "",
  "components": "[]"}'. Now I want to import it.

**Comment by artf** [comment]
Honestly, I'd recommend following the flow with the storage manager, but in any way, you could achieve it in this way:
```js
const obj = var tt = JSON.parse(yourJsonString);
editor.setComponents(obj.components);
editor. setStyle(obj.styles);
```
