### ISSUE TITLE
How to remove toolbar icons

### ISSUE THREAD

**Issue by Deepak813** [artf/grapesjs#1090]
Hi artf,

Please let me know how we can remove the toolbar icons like when user click on image element then I don't want delete icon or other icons.

Help us to resolve this.

Regards,
Deepak Walia

**Comment by artf** [comment]
`.gjs-toolbar { display: none }`

**Comment by Deepak813** [comment]
Hi artf,

Thanks for the message.

I just want to hide the particular icon of the toolbar not the complete the toolbar.Like in complete toolbar i want to hide the delete icon, rest of the icons are same.
