### ISSUE TITLE
Hello, I am a novice. How can I run it?

### ISSUE THREAD

**Issue by ancientry** [artf/grapesjs#1093]
How much is the 1: development environment and how to configure it;
2:grapesjs DEMO.HTML of the official website. How do I run locally?

**Comment by ancientry** [comment]
![image](https://user-images.githubusercontent.com/11289708/39745610-521a57a2-52da-11e8-8893-b3e6830e3b6d.png)

**Comment by artf** [comment]
You have to run `npm i` first
https://github.com/artf/grapesjs#development

The demo branch is here https://github.com/artf/grapesjs/tree/gh-pages
