### ISSUE TITLE
[FEATURE REQUEST] Support rendering layouts which are not part of the editable content

### ISSUE THREAD

**Issue by dsgh** [artf/grapesjs#1096]
Basically my use case is that I want to show a whole page - with header, menu(s) and footer - in the editor canvas, but only allow the user to edit the actual content of it. The reasoning behind this is so that the users can see the page as close as it will be to the "end product".

I've been able to accomplish something like this by rendering the full page into the wrapper, using the `fromElement` option, and taking care to set `highlightable`, `badgable` and all the other such attributes to `false` on the elements belonging to the layout, but still this is not ideal as:

1. The root node in the "Layer Manager" is still the body, which is then un-expandable as the elements directly below it are marked as non-layerable. What I'm looking for here is that the root of the Layer Manager be the "content" element.

2. When viewing/exporting code, the code for the whole page is shown. What I'm looking for is to have only the code related to the "content" element appear.

@artf Is this something that makes sense as a feature? I'm ready to start working on a PR for it. Should this be implemented as an option that specifies a css selector for the element that should be the "actual editable portion"? If so, what should the option be called? `rootNode`, `subcontainer`, `wrapper`, `subwrapper`, `contentElement`, `contentWrapper`? Or, if not a config option, then there could be a documented default behaviour. For example: if one of the elements of the initial html content (when using `fromElement`) has an id of, say, `gjs-root-node`, then the behaviour described above is applied accordingly. Thoughts?

**Comment by artf** [comment]
For the point `1` you can pass this to your init options:
```js
...
layerManager: {
	showWrapper: 0,
},
```
Point `2`, what about something like a custom `placeholder` component which just overwrites `toHtml` method in the model definiton
```js
model: ...
	{
		toHTML() {
			return '';
		}
	},
```

**Comment by artf** [comment]
Hey @dsgh, did you manage to accomplish your task?

**Comment by dsgh** [comment]
@artf These past few days I've been busy working on other extensions to grapesjs that we're also needing. Thank you for your suggestions here - I'll investigate more about the `showWrapper` option, and I think your suggestion for point 2 is spot on! I should have thought of doing that.

I'll return to this later this month, and report back - if you want to close this issue in the meantime, feel free to do that, as I'm fairly confident I'll be able to solve it without any changes to grapesjs.

Thanks

**Comment by artf** [comment]
Great, thanks Duarte, let me know then if you get issues

**Comment by dsgh** [comment]
Hi @artf I'm back at this, and things are not as clear as I thought.

For point 1, what does the `showWrapper` option actually do? I'm not seeing any difference.

For point 2, do you mean this would be a component that users would have to drag on to the page? That's not the intended behaviour, the idea would be for the layout of the page to always be there (not through a user's choice or required action). Otherwise, were you suggesting that I pre-render something like a `<div class="placeholder">...</div>` wrapping everything, and then having the custom placeholder component 'recognizing' that through `isComponent`? I've done that, also with a custom `toHTML`, but the editor canvas just reflects what was pre-rendered, not what the custom `toHTML` returns. I'm not clear on what the relation needs to be here between the html that was pre-rendered into the canvas and the toHTML() results.

In any of these previous cases, the suggested custom placeholder element would appear in the Layer Manager, right? Which is also not intended - this should be transparent to the user.

I also realized now that, instead of my feature suggestion at the top, this could maybe be implemented if I could somehow override the `toHTML` of the wrapper component (the one named "Body" in the Layer Manager) - I tried overriding it from a plugin but didn't find a way to do it.

Thoughts? Perhaps I've misunderstood your suggestions? Thanks

**Comment by dsgh** [comment]
@artf Thank you so much for taking the time to explain this!

Regarding point 1: I now see what it does, thanks.

Regarding point 2: your demo was really helpful, I've replicated it with a notable difference which might be useful for other readers of this issue: I've added a 'content-wrapper' component type with a `toHTML` that renders children directly (no self element), and with properties as follows: `{ badgable: false, copyable: false, draggable: false, highlightable: false, layerable: true, name: 'Wrapper', removable: false, stylable: false }`. This way users can drag blocks over to this element, given that the grapesjs wrapper had to be set as `droppable: false` so that users don't drop above or below the placeholder elements 👍

However, this example doesn't cover the complete case that I'm interested in - which I think should be quite a common case(?) - My intended structure is a bit like so:
```
<div class="header">...</div>
<div class="content-wrapper">
  <div class="side-menu">...</div>
  <div class="content-area">... users will add content here ...</div>
</div>
<div class="footer">...</footer>
```

That is, the 'content-area' is not at the top-level, or in other words, the "placeholder" elements are not neatly all siblings of the 'content-area'. I'm trying to think how I could work in something like this, but I'm not sure how to do it (in a way such that the layer manager only shows elements from the 'content-area'). Do you know a way? Or would grapesjs need to be changed?

**Comment by artf** [comment]
Ok so if I get it right the only issue now is with Layers, right? You'd like to see the `content-area` as a root of Layers, correct? In that case, it's not yet possible but definitely, it's something we can implement

**Comment by dsgh** [comment]
@artf Exactly - I can try my hand at a PR for it. Should this be implemented as an option that specifies a css selector for the root element, say something like `layerManager: { root: '#my-root' }`? Or, if not a config option, then there could be a documented default behaviour, say something like: the element which has an id of `gjs-root-node` would be the root. Thoughts?

**Comment by abozhinov** [comment]
When you make load() this feature don't work.
