### ISSUE TITLE
how to use plugins

### ISSUE THREAD

**Issue by ionic666** [artf/grapesjs#1098]
when i import grapes-plugin-export,there is a warnning,please help me
![qq20180509-153455](https://user-images.githubusercontent.com/36065691/39801706-b0c97890-539e-11e8-8f27-f1e3be2977b0.png)

![qq20180509-145448](https://user-images.githubusercontent.com/36065691/39800036-10c4efb4-5399-11e8-9377-7a9b5675290b.png)
![qq20180509-145504](https://user-images.githubusercontent.com/36065691/39800038-110bb0d4-5399-11e8-8fa5-82019033be59.png)

**Comment by artf** [comment]
`gis-plugin-export` -> `gjs-plugin-export`

**Comment by ionic666** [comment]
@artf hi,gis-plugin-export - > gjs-plugin-export,what this means?i use this plugin in vue.js,but always show "Plugin gjs-plugin-export not found"
