### ISSUE TITLE
Where is the complete code of http://grapesjs.com/demo.html home page downloaded?

### ISSUE THREAD

**Issue by ancientry** [artf/grapesjs#1099]
There is a big difference between the download code and the operation. Where is the complete demo code for the official website?

**Comment by ancientry** [comment]
There is a big difference between the download code and the operation. Where is the complete demo code for the official website?

**Comment by cjpollard** [comment]
https://github.com/artf/grapesjs/tree/gh-pages

**Comment by kuldeepcis** [comment]
https://github.com/artf/grapesjs/blob/gh-pages/demo.html
