### ISSUE TITLE
What if I want to paste plain text without style?

### ISSUE THREAD

**Issue by jay0319** [artf/grapesjs#110]

**Comment by jay0319** [comment]
$('[contenteditable="true"]').on("paste", function(e) {
    e.preventDefault();
    var text =  e.originalEvent.clipboardData.getData('text');   
   document.execCommand("insertText", false, text);
});

I can insert this code to anywhere?

**Comment by artf** [comment]
First of all, editable elements are generated dynamically so you have to delegate the event and then you have to catch events inside the iframe of grapesjs, I think something like this should work:

```js
var iframeBody = editor.Canvas.getBody();
$(iframeBody).on("paste", '[contenteditable="true"]', function(e) {
  e.preventDefault();
  var text = e.originalEvent.clipboardData.getData('text');
  console.log('text to past: ', text);
  e.target.ownerDocument.execCommand("insertText", false, text);
});
```

**Comment by jay0319** [comment]
artf thank you for your reply, this can work i got it.

**Comment by Moikapy** [comment]
This works but when I undo the paste and then paste the text back in it duplicates the pasted item.

**Comment by Moikapy** [comment]
I added this code to the same file i keep my grapes config and it worked.
