### ISSUE TITLE
apply css property for mobile/tablet view

### ISSUE THREAD

**Issue by kuldeepcis** [artf/grapesjs#1101]
Hello @artf ,

https://jsfiddle.net/66cnd2t4/3/
This is the fiddle for the map issue
when you drag a map and add it then in dimensions you will see width auto and its label is in pink which shows it user defined means i have passed it in components style block as such
, _("map") && i.add("map", {
                        label: n.labelMap,
                        category: n.category,
                        attributes: {
                            class: "fa fa-map-o"
                        },
                        content: {
                            type: "map",
                            style: {
                                height: "350px",
                                 width: "auto"
                            }
                        }
                    })
but when you change it to mobile view the label is not in pink ,means the user defined property is not being applied.We wants it to be applied for mobile and tablet view as well

**Comment by artf** [comment]
First of all, next time use this https://jsfiddle.net/szLp8h4n as a starting point for your fiddles, without all the stuff not regarding the issue.
To make properties defined on other devices you have to set the CSS on that media query:
```js
@media (max-width: 992px){
  .your-map-class{
    ...
  }
}
@media (max-width: 480px){
  .your-map-class{
    ...
  }
}
```
