### ISSUE TITLE
How to hide the particular icon of the toolbar

### ISSUE THREAD

**Issue by Deepak813** [artf/grapesjs#1103]
Hi artf,

Thanks for the message and help #1090.

I just want to hide the particular icon of the toolbar not the complete the toolbar as you provided #1090.Like in complete toolbar i want to hide the delete icon when user click on image or like other element, keep the rest of the icons same.

**Comment by artf** [comment]
As you see @Deepak813 those icons have classes too so you can use the same technique
![schermata 2018-05-13 alle 12 34 34](https://user-images.githubusercontent.com/11614725/39966324-3d2d73b4-56aa-11e8-995b-18063f05078a.png)
