### ISSUE TITLE
[Bug] Color trait can't setup property after 0.14.9

### ISSUE THREAD

**Issue by Nuzsk** [artf/grapesjs#1104]
After v0.14.9 color trait can't setup component property when user press "OK" on colorpicker form.

Live:
- v0.14.9 https://jsfiddle.net/Lqm7ouze/ (testprop is undefined)
- v0.14.6 https://jsfiddle.net/Lqm7ouze/1/ (testprop contain hex colorcode)

Screenshots:
- https://ctrlv.cz/en/M7lg
- https://ctrlv.cz/en/ltPo

This problem is also present in 0.14.15.

**Comment by jdodsoncollins** [comment]
@artf I'm seeing this behavior still if you could take a look, on latest release. Reverting to v 0.14.6 solves it.
