### ISSUE TITLE
add class in existing element

### ISSUE THREAD

**Issue by kuldeepcis** [artf/grapesjs#1105]
Hello 

[previous issue](https://github.com/artf/grapesjs/issues/1101)

can you please let me know how can add a new class on map element?

I don't want add class manually on element through setting on right side.

A single class added on every map element automatically.

please guide me.
Thanks in advance.

**Comment by artf** [comment]
You can define them easily inside [Blocks](https://github.com/artf/grapesjs/wiki/Blocks)
