### ISSUE TITLE
[QUESTION] Column blocks not droppable in canvas

### ISSUE THREAD

**Issue by FrciSmrci** [artf/grapesjs#1109]
Morning @artf :) 

I'm experiencing an similar problem to [this issue](https://github.com/artf/grapesjs/issues/297).

I can't drop any block (text, image, etc.) inside the column block from canvas. When I try to drop it inside layers it works normally, here is a [short detailed screen recording](https://drive.google.com/open?id=1w_k97fkvK6OwWHYeCLBjJcwR0857ONLr) of the problem with a visible html structure. Do you have any idea how to fix this issue?

Thanks in advance.

**Comment by artf** [comment]
Hi @FrciSmrci honestly, I don't understand what is going on and can't reproduce it with the current demo. Did you customize those blocks somehow? From which preset/plugin do you get them? Are you able to reproduce it via jsfiddle? Your grapesjs version?

**Comment by FrciSmrci** [comment]
Hey @artf , 

figured out what was going on today, but forgot to close the issue in the euphoria. 😄 

The classes from GrapesJS and Bootstrap were colliding, took me some time to realise that, because it worked when trying the same in layers. 

Great job on the stylePrefix option in basic blocks, it fixed my problem. I was thinking that maybe it would be a good idea defaulting it to a key like gjs-. What do you think? 

Have a great day!

**Comment by artf** [comment]
> I was thinking that maybe it would be a good idea defaulting it to a key like gjs-. What do you think?

Yeah, probably that would prevent scenarios like this 😬 PRs are welcome :)

**Comment by milapshah15** [comment]
@FrciSmrci How did you fix the issue? I am facing the same issue.

Warm regards
Milap

**Comment by FrciSmrci** [comment]
Hey @milapshah15 ,

I added a style prefix like this` blocksBasicOpts: {
            stylePrefix: 'ch-'
          },` into the grapesJS initialisation.

I did create a pull request on the repo setting the default style prefix to -gjs if none is provided, hopefully will prevent scenarios like this in the future. 

Have a great day!

**Comment by milapshah15** [comment]
@FrciSmrci It is still not working for me.How did you find that this is the cause?

For me, all other blocks are working like text, image, link etc except the one which related to layouts.

Warm regards
Milap

**Comment by FrciSmrci** [comment]
Hey @milapshah15 , which plugin do you use? I used [grapesjs preset webpage](https://github.com/artf/grapesjs-preset-webpage), it may have a somewhat different structure of configuration, here is an example.  `grapesjs.init({
      container: '#gjs',
      plugins: ['gjs-preset-webpage'],
      pluginsOpts: {
        'gjs-preset-webpage': {
          blocksBasicOpts: {
            blocks: ['link-block', 'quote', 'image', 'video', 'text', 'column1', 'column2', 'column3'],
            stylePrefix: 'ch-'
          }}}});` 

I found out that the bootstraps class "row" I included was "fighting" with grapesjs "row" class. Here is the [pull request](https://github.com/artf/grapesjs-blocks-basic/pull/8) I created, but it wasn't merged yet.

Have a great day!

**Comment by milapshah15** [comment]
Yeah I just figured that display: flex;
		justify-content: flex-start;
		align-items: stretch;
		flex-wrap: nowrap;
		padding-top: 10px;
		padding-right: 10px;
		padding-bottom: 10px;
		padding-left: 10px;

This thing was not added in the row class.

**Comment by milapshah15** [comment]
@FrciSmrci 

Its working now.Thanks a ton and yes it was indeed tricky.

Warm regards
Milap
