### ISSUE TITLE
[Question]How to add a new event to asset images

### ISSUE THREAD

**Issue by IceCrystal0k** [artf/grapesjs#1112]
Hello,
is there a way to add a new event to the AssetImageView, something like 'onRemove'.
I overwritten the addAsset function from asset manager ->AssetsView to display a new icon and add a new event, but the new event doesn't trigger. 
I read other issues and i seen that i could overwrite open-assets, but don't really need that since it does most of what i want.

This is the code i used: [code](https://pastebin.com/jqaEW5QU)

**Comment by artf** [comment]
Use [Assets API](https://github.com/artf/grapesjs/wiki/Assets#extend-asset-types)
