### ISSUE TITLE
[BUG] Custom HTML output not firing on reload

### ISSUE THREAD

**Issue by Lethrir** [artf/grapesjs#1114]
I am using the toHtml and isComponent properties for a custom component to allow for custom HTML output. This appears to be working when the element is first dropped on the canvas but when the page is refreshed the element is present but does not return the custom HTML.

Grape Version: 0.14.15
Browser: Chrome 66.0.3359.139 (Official Build) (64-bit)

I've put together the following sample which reproduces the issue: https://jsfiddle.net/zbL1ehz2/

Reproduction steps:
Drag a 'Foo Block' to the canvas
Click the 'View code' button
Output will be 'FOO' which is the expected result
Refresh the page - Canvas should reload with the Foo Block already inserted
Click the 'View code' button
Output will be 

```
<div class="foo">Foo
</div>
```

which is not the expected result

**Comment by artf** [comment]
You should put your custom components in a plugin and it will work
