### ISSUE TITLE
[BUG] core:canvas-clear removes CSS Composer Styles

### ISSUE THREAD

**Issue by Lethrir** [artf/grapesjs#1115]
I am using the core:canvas-clear command assigned to a button but when this is pressed, the styles setup through the CSS Composer are also being removed.

Grape Version: 0.14.15
Browser: Chrome 66.0.3359.139 (Official Build) (64-bit)

I have setup a script to recreate this at https://jsfiddle.net/pzacf7zg/

Reproduction steps:
Drag a 'Foo Block' to the canvas
Observer that the block is styled
Click the Trash icon to clear the canvas
Drag a new 'Foo Block' to the canvas
Observe that the styling is not applied this time
Refresh the page
Observe that the previously un-styled element has become styled

**Comment by artf** [comment]
Hi @Lethrir as you can see [this is the command](https://github.com/artf/grapesjs/blob/dev/src/commands/index.js#L207-L210) and the behavour is totally intended. This also shows you how ridiculously the command is, so you can create your own via [Commands API](https://github.com/artf/grapesjs/wiki/API-Commands)
```js
editor.Commands.add('clear-html', () => editor.DomComponents.clear() );
```
I'd also suggest to create blocks with their own styles, just to keep thing modular and independent
```js
blockManager.add('foo-block', {
	label: 'Foo Block',
	content: `<div class="foo">Foo</div>
		<style>
			.foo {
				...
			}
		</style>`
});
```
