### ISSUE TITLE
Property gradient is not working

### ISSUE THREAD

**Issue by perfect-coders** [artf/grapesjs#1116]
Hi @artf.  I have used the GrapesJS Style Gradient plugin and do the same as it is suggested. But it is not making the gradient in the settings. I am giving like that
{
      name: 'Gradient',
      property: 'background-image',
      type: 'gradient',
      defaults: 'none'
    }

Also When I added the "artf/grapesjs-style-gradient" plugin through grapes method like this
plugins: [ 'gjs-style-gradient'], 
pluginsOpts: {
                'gjs-style-gradient': {
                      colorPicker: 'default',
                      grapickOpts: {
                                      min: 1,
                                      max: 99,
                                  }    
                },                

It is showing the error :- Plugin gjs-style-gradient not found

**Comment by artf** [comment]
> Plugin gjs-style-gradient not found

Are you sure you've imported it correctly?

**Comment by perfect-coders** [comment]
This is how the gradient property is coming.

![screenshot from 2018-05-18 19 22 10](https://user-images.githubusercontent.com/31913865/40238500-f81eb46a-5ad0-11e8-94c3-c5730ad7634b.png)

And this is how I am doing
 /* Page Settings */
                              {
                                name : 'Page Settings',
                                open : true,
                                buildProps : ['background-color','background','background-repeat','background-size','background-position', 'background-attachment'],
                                properties : [
                                        {
                                          name: 'Gradient',
                                          property: 'background-image',
                                          type: 'gradient',
                                          defaults: 'none'
                                        },
                                        {
                                        property : 'background-color',
                                        name: 'Background Color', 
                                        },
                                        {
                                            property : 'background',
                                            name: 'Background Image', 
                                        },
                                        {
                                        property : 'background-size',
                                        name: 'Sizing', 
                                        },
                                        {
                                        property : 'background-position',
                                        name: 'Alignment', 
                                        },
                                        {
                                        property : 'background-repeat',
                                        name: 'Repeat', 
                                        },
                                        {
                                        property : 'background-attachment',
                                        name: 'Attachment', 
                                        },
                                    ]
                              },

**Comment by artf** [comment]
Your fiddle doesn't work (you didn't setup it correctly), btw [this is the demo](https://codepen.io/artf/pen/bYwdQG), it uses the latest version and it works as expected
