### ISSUE TITLE
External Elements can drag and drop in canvas?

### ISSUE THREAD

**Issue by UmairAfzalUAT** [artf/grapesjs#1117]
Hi Artf
Actually there is no issue. we are using grapesjs in a different way. We are not using header and sidebars of grapesjs we are performing its functionalities buy our own triggers like undo redo preview etc. Is there any way i can add my own component panel having headings, images, Gallery, Videos, Vectors, Shapes etc and drag and drop own elements in GrapesJs canvas?
![webbuilder](https://user-images.githubusercontent.com/38519246/40122405-2b888ed8-593d-11e8-8935-6e71df33a375.png)

**Comment by artf** [comment]
Hi Umar,
GrapesJS supports native HTML5 Drag&Drop, therefore you are able to drop ANY kind of draggable resources (not only from the browser)
![html5-dnd](https://user-images.githubusercontent.com/11614725/40207066-e5d80c3c-5a32-11e8-8f36-6e380b0aad11.gif)

You can also extend it's capabilities by using [`canvas:*`](https://github.com/artf/grapesjs/wiki/API-Editor#canvas) events, like `canvas:dragdata` which allows you to define what Components to use on specific `dataTransfer` type (eg. by default the editor accepts images and texts, you can make it understand also stuff like video and music files)

BTW you're not forced to use the whole GrapesJS UI, you can configure it to use only the Canvas and Blocks (which is just really handy). Just take a look at this example https://codepen.io/artf/full/MQpZPj/

**Comment by UmairAfzalUAT** [comment]
Hi Artf,
Thanks for help i got that and using drag and drop in the same way. you have done the great job (Y).
BTW what about designer mode is that available?

**Comment by artf** [comment]
> BTW what about designer mode is that available?

Not yet, I'm having hard times to implement new features due to my limited spare time

**Comment by UmairAfzalUAT** [comment]
I am working on relative and absolute both will let you know when done.
