### ISSUE TITLE
[Question] Generate dynamic identifier in Block

### ISSUE THREAD

**Issue by cgatian** [artf/grapesjs#1118]
Im looking to create a block that when dropped will generate two components and these components would share some unique identifier between each other. If I dropped a second block to the canvas a second identifier would be used.

```
    blockManager.add('combined', {
      label: 'combined',
      category: 'Workflow',
      content:  `<gg-list bind-id="SOMEID"></gg-list><gg-label bind-id="SOMEID"></gg-label>`,
    });
```

I believe you could do this by creating your own component, but then you loose the ability resize/edit each individual component within he components `content` property.

Any help would be appreciated. Thank you.

**Comment by artf** [comment]
You can make use of this event
```js
editor.on('canvas:drop', (dataTransfer, component) => {
	if (component.getEl().tagName === 'GG-LIST'){
		...
	}
});
```

**Comment by cgatian** [comment]
@artf Thank you for the reply! OK I was second guessing this approach, good to get some feedback on this. Just to follow up I dont believe there's a way to detect which block was actually dropped during the event, correct?

**Comment by artf** [comment]
> Just to follow up I dont believe there's a way to detect which block was actually dropped during the event, correct? 

The `component` it's just the first one of your list, if you wrap your 2 elements inside another div that one will be the dropped `component`

**Comment by cgatian** [comment]
OK yes I can see how that would work. However, when I wrap my components in other component they are not recursively parsed as a component and the block is then treated as one. 
So the following pseudo definition:
```
{
block: my-block
component: my-block-component
}
```
```
{
type: my-block-component 
content: `<component-a></component-a><component-b></component-b>`
}
```
If `component-a` and `component-b` are not treated as individual components.  Am I missing a configuration setting to recursively parse the content of components as components?

**Comment by artf** [comment]
You mean something like this? https://jsfiddle.net/0m46y1fL
