### ISSUE TITLE
RTE doesn't work with <p> elements sometimes

### ISSUE THREAD

**Issue by vankyy26** [artf/grapesjs#112]
The 'p' element from the picture cannot be edited anymore. I can only delete it and add fresh Text block. The issue appeared when I placed 'a' element with the RTE link button. Then i removed the 'a' but the 'p' element isn't editable anymore which is strange. I see the blank 'a' is still there, you can see that in the second picture. I think similar issue appeared when I imported HTML of an old template which was containing elements inside 'p' tags.

![pelem](https://user-images.githubusercontent.com/10697327/27354341-e895cd56-560f-11e7-85e9-4023069b1601.PNG)
![phtml](https://user-images.githubusercontent.com/10697327/27354346-eaab54f8-560f-11e7-9b9c-7b6cdb13f77c.PNG)

**Comment by artf** [comment]
If you import HTML you should check this [issue](https://github.com/artf/grapesjs-plugin-ckeditor/issues/2)
