### ISSUE TITLE
[BUG] - <Tbody> inside <Table>

### ISSUE THREAD

**Issue by alimajed93** [artf/grapesjs#1121]
Hi @artf ,

I created a new component with `tagName = 'table'`. When selected and one option of its toolbar I also created is clicked, a new modal opens, and when the user submits, some content should be added to the block. I am using `editor.getSelected().get('components').add(HtmlCode)`, where HTML code always starts with `<tbody><tr><td>`. My issue is that those tags are being omitted. So the final result is `<table>[Rest of the HTML code]` instead of `<table><tbody><tr><td>[Rest of the HTML code]`.

I think it is because tbody is only draggable inside a table? But as I mentioned, the component is already a table. If `<tbody><tr><td>` are replaced by a `<div>` per example, everything works as expected.

Any idea How to solve this issue?

Thank you!

**Comment by artf** [comment]
I think this happens because when you add the HtmlCode is parsed by the browser outside of the table scope and therefore it strips your tags. Try to skip the parser by passing a component object:
```js
// And instead of adding <tbody> I'd prefer to set a new one as you might end adding 2 of them 
editor.getSelected().components({
	tagName: 'tbody',
	components: {
		tagName: 'tr',
		components: {
			tagName: 'td',
			components: '[Rest of the HTML code]'
		}
	}
});
```
