### ISSUE TITLE
[Feature request] Support RTL

### ISSUE THREAD

**Issue by hadifarnoud** [artf/grapesjs#1122]
GrapeJS does not support right to left languages. Arabic, Persian, and Hebrew are a few RTL languages. 

Please add RTL support or if there is a workaround for now, do let me know.

**Comment by artf** [comment]
You just need to add CSS `direction` property in your Style Manager (check the [getting started](https://github.com/artf/grapesjs/wiki#style-manager))

**Comment by Orijinn** [comment]
Hi @artf ,
could you please give us an example? The use case is to make all the text inputs to use RTL. How can one achieve this?
Tried to add a sector, nothing works. Direction is not among built-in props either.

thanks
