### ISSUE TITLE
[QUESTION] Onload event inside template

### ISSUE THREAD

**Issue by alfaalex81** [artf/grapesjs#1123]
Hi! I have a problem with some templates. This template has some scripts running after the page is loaded. When this templates is loaded by GrapeJs, the scripts do not starting because browser not detect the ending of load. 

It's possibile to load templete in a classic iframe (not injected)?

For example:
`<iframe src="http://myexamplepages.com" frameborder="0" style="overflow:hidden;height:100%;width:100%" height="100%" width="100%"></iframe>
`

It is possible to use this solution or you can suggest other one.

Thanks.

**Comment by artf** [comment]
Have you tried with this?
```js
const editor = grapesjs.init({
	...
	allowScripts: 1,
});
```

**Comment by alfaalex81** [comment]
Sure, other scripts with "allowScripts" parameter work fine, but scripts inside "on load event" don't.

I inject the code in this way:

`       var newComps = editor.DomComponents;
        $.get('http://myexamplepages.com', function (e) {
            newComps.setComponents(e);
        });
        window.editor.setComponents(newComps);
`

Thanks.

**Comment by artf** [comment]
@alfaalex81 can you provide a live demo of the issue?
