### ISSUE TITLE
Style is not copying after cloning the element

### ISSUE THREAD

**Issue by perfect-coders** [artf/grapesjs#1124]
Hi @artf.
At the first time before saving the template, When I make one element and clone it, the style is coming in the clonned element. That is running fine.
But when I save the template and render the template with this editor.setComponents(templateHTML);  
and then clone the elements, their styling does not applies to the clonned elements.

Thanks for help in advance

**Comment by artf** [comment]
Tested with the demo, everything works as expected. Without any kind of live demo demonstrating the opposite, IMHO, there is no reason to keep this issue open.
BTW, check [this](https://github.com/artf/grapesjs/wiki/Storage#store-and-load-templates) if you store and load templates back
