### ISSUE TITLE
[Question] How to Add Custom attribute in a Block through Block Manager?

### ISSUE THREAD

**Issue by fsaiyedOB** [artf/grapesjs#1126]
Hello,
I have a custom block in which there is custom attribute `@call-method="searchProduct"`. But when I directly use this in Grapes JS as `<datafieldsearch @call-method="searchProduct" label="Search"></datafieldsearch>` it throws an error saying `Uncaught DOMException: Failed to execute 'setAttribute' on 'Element': '@call-method' is not a valid attribute name.`

So how can I pass this custom attribute through `bm.add()`?

**Comment by d3vr** [comment]
You can't use `@` in an attribute's name, use something like `data-call-method` instead

**Comment by fsaiyedOB** [comment]
Thanks, actually I found alternative to `@` i.e. v-on for using `@` in VueJS
