### ISSUE TITLE
Command running multiple times

### ISSUE THREAD

**Issue by milapshah15** [artf/grapesjs#1127]
Hello Folks,

I need your help.I created a custom button on the commands Panel to publish the site created from Grapes.When i click on it, it executes the command 2 times and I am not sure why

Here is my code snippet.Any help would be really appreciated.

            //Get the default plugin set for all the blocks
            plugins: ['gjs-preset-webpage'],
            pluginsOpts: {
                'gjs-preset-webpage': { /* options */ }
            },

            //Commands
            commands: {
                defaults: [{
                    id: 'publishContent',
                    run: function (editor, senderBtn) {
                        publish(editor.getHtml(), editor.getCss());
                    },
                    stop: function (editor, senderBtn) {},
                }],
            },

        });

 //Manipulate existing panels
        var panelManager = editor.Panels;

        //get Panel Object
        var panelObj = panelManager.getPanel('options');

        //publish button to publish the website
        var publishButton = panelManager.addButton('options', {
            id: 'publish',
            className: 'fa fa-upload',
            command: 'publishContent',
            attributes: {
                title: 'Publish Site'
            },
            active: false,
        });`

Warm regards
Milap

**Comment by milapshah15** [comment]
@artf Can you please help on this.

**Comment by shareefhiasat** [comment]
@milapshah15  please check @artf response and my response here

https://github.com/artf/grapesjs/issues/625

**Comment by milapshah15** [comment]
@shareefhiasat if you see my code, I guess that issue is different than what I am facing.Moreover, I see that I face the issue when I load website-preset plugin

**Comment by artf** [comment]
@milapshah15 can't reproduce it, are you able to provide a simple live demo of the issue?

**Comment by milapshah15** [comment]
@artf I ended up blocking the executing by setting/resetting a flag.

Closing this issue.

Warm regards
Milap
