### ISSUE TITLE
Bug in dragging selected text

### ISSUE THREAD

**Issue by Abhisheknanda1344463** [artf/grapesjs#1128]
hi @artf as you can see my screenshot when you drag textblock than select text in that element and drag it to bottom of content than text get append to content without any tag and we are not able to edit that text.. can u please help me out.. @artf 
![screen shot 2018-05-24 at 2 40 14 pm](https://user-images.githubusercontent.com/20657737/40476292-4e202fee-5f61-11e8-8738-5ea5af3096f6.png)
![screen shot 2018-05-24 at 2 47 37 pm](https://user-images.githubusercontent.com/20657737/40476418-967568cc-5f61-11e8-9687-f17162fe984e.png)

**Comment by artf** [comment]
Don't drag the text from the component, create a new one

**Comment by Abhisheknanda1344463** [comment]
hi @artf Thanks for your reply.. i want to know if it is possible if i update style manager in mobile device then it'll not reflect in Desktop Mode...Please reply me asap  i need your help. Thanks @artf
