### ISSUE TITLE
I would like to ask how to solve the block component is not padding difficult to drag into the screen?

### ISSUE THREAD

**Issue by jay0319** [artf/grapesjs#113]
I think of a practice is to insert a block after each time will add a plus button to facilitate the addition of a section But this must be reset block manager to solve this problem.

Thank you @artf.

**Comment by artf** [comment]
Sorry @jay0319 but I don't get what is your issue. Can you elaborate the question?

**Comment by jay0319** [comment]
like this, this easy to drag to canvas because section have padding.

![1498104551469](https://user-images.githubusercontent.com/13900161/27417017-a581885e-5743-11e7-82ae-ebc9e88628f4.jpg)

But this not easy to drag to canvas, because between section have not padding.

![1498104825820](https://user-images.githubusercontent.com/13900161/27417090-459de9b8-5744-11e7-90e1-4b0e86d83072.jpg)

Sorry my english not very well, so I use img, hope you can understand my question thanks.

**Comment by artf** [comment]
Thanks @jay0319 now I got what do you mean and this is something I'm still working on.

At the moment you can tell a model what elements are acceptable and where they could be dragged, eg. example with a row/cell elements:
```html
<div class="row" data-gjs-droppable=".row-cell">
  <div class="row-cell" data-gjs-draggable=".row"></div>
  <div class="row-cell" data-gjs-draggable=".row"></div>
</div>
```

But this double opt-in process is only executed once the component is dropped, I think moving this process up in dragging event might solve some of the issues.

I'll add this to the [Roadmap](https://github.com/artf/grapesjs/issues/74)

**Comment by jay0319** [comment]
Oh @artf  i'm very happy you can understand my mean, and thanks you answer me the solution.

**Comment by jay0319** [comment]
Sorry @artf I want ask this function being built? Thank you.

**Comment by artf** [comment]
@jay0319 can you elaborate better what is doesn't work with the current model properties? What do you do and what do you expect to happen?

**Comment by jay0319** [comment]
@artf I used you support method to test drag to between two no padding component, I has upgrated new version but not working, I don't know why, thank you.

**Comment by artf** [comment]
I think you should wait for the improvement I've explained before because with `droppable`/`draggable` properties you can limit stuff but it's not gonna fix you problem with adjacent components. The orange outline just helps understand which is the parent but nothing more

**Comment by jay0319** [comment]
@artf Ok, I know thank you for your reply.

**Comment by artf** [comment]
Hi @jay0319 I implemented the behavior explained before. I'd suggest you trying the [demo](http://grapesjs.com/demo.html) with new column components (be sure to clean the cache/localStorage). You might notice how you aren't able to drag rows between cells and it should be easier drag rows around adjacent components.

**Comment by jay0319** [comment]
Thanks @artf I will try the new version, thank you very much.
