### ISSUE TITLE
[Question] How do I get <body> tag and its attributes

### ISSUE THREAD

**Issue by agungaja** [artf/grapesjs#1132]
I have set the background-color for `body`. But when it will be edit code or export data using command 
`editor.runCommand ('gjs-get-inlined-html');` there is no attribute for `body` that has been set. How do I solve for the body tag to retrieve when using that command? Or is there another way?

Image when set background-color for body: 
![image](https://user-images.githubusercontent.com/39617738/40535999-f7528692-6034-11e8-80c8-3ed02f5dada9.png)
Image when edit html (no attribute for body):
![image](https://user-images.githubusercontent.com/39617738/40536015-01e941e0-6035-11e8-84ae-60010a91a189.png)

Thanks.

**Comment by artf** [comment]
There is an option for it
```js
editor.init({
	...
	exportWrapper: true,
})
```

**Comment by agungaja** [comment]
Thanks @artf , it works :)
