### ISSUE TITLE
Add custom style in the style-sheet for a new class of existing block.

### ISSUE THREAD

**Issue by kuldeepcis** [artf/grapesjs#1134]
Hello @artf 

_("map") && i.add("map", {
                        label: n.labelMap,
                        category: n.category,
                        attributes: {
                            class: "fa fa-map-o"
                        },
                        content: {
                            type: "map",
                            classes:['map-width'],
                            // unstylable:['width'],
                            style: {
                                // height: "350px",
                                // width: "auto",
                            }
                        }
                    });

add a new class 'map-width' on map element, now I want to add new css for that class.
can you please guide me how to add custom style in the style-sheet for that class. so it'll display in the css section when click on export. and also reflect in pink with x sign like it's added externally.
please guide me 
Thanks in advance. :)

**Comment by artf** [comment]
You can add it in template or inside blocks. BTW check other issues before opening a new one, there are plenty of questions like this
