### ISSUE TITLE
Cant make Text Block not editable and style able at the same time !

### ISSUE THREAD

**Issue by shareefhiasat** [artf/grapesjs#1137]
**Demo / reproduce problem**
https://jsfiddle.net/shareefhiasat/u8Lodyh7/1/

**Question**
Not sure if its bug or i dont know how to get the desired behaviour

**Expected**
I need text element like, and be able to style it but **NOT** changing what content (text in it)

**Actual and What i have Tried**
I tried from wiki and docs some solutions like editable set to fales, but did not work
https://github.com/artf/grapesjs/blob/dev/src/dom_components/model/Component.js
it is becoming not editable and not clickable,dragale stylable all together , 

I need on not editable for content @artf can you tell me where and how from the demo above.

**Comment by shareefhiasat** [comment]
@julyanof @artf
Please help may be it too simple to figure out my self

**Comment by shareefhiasat** [comment]
please can you clarify me this question to close thanks @artf

**Comment by artf** [comment]
Hi @shareefhiasat I'm not sure if component's `content` property is exactly what you need here. 
The `content` is used for static text/HTML (indeed is used as editable part in RTE), in your case what is happaning is when the `<div>{BLOCK C}</div>...` is rendered that `<div>` (which is static, without model and therefore non selectable) "covers" your component and so you're unable to select it. 
So generally, you would use the `content` for something like this: `content: "Here <b>is</b> my static HTML, no div around"`, but I think in your case, as you also use another custom component inside it (`<component-b>`), probably you just need `components`
```js
bm.add('ev-name', {
          label: 'Block C',
          category: 'Basic',
          content: {
			// Force the div not to be editable with data-gjs-type="default"
			components: `<div data-gjs-type="default">{BLOCK C}</div>
<component-b></component-b>`
		  }
      });

// Or just
bm.add('ev-name', {
          label: 'Block C',
          category: 'Basic',
          content: `<div data-gjs-type="default">{BLOCK C}</div>
<component-b></component-b>`
      });
```

**Comment by shareefhiasat** [comment]
Hi @artf  million thanks for having time to reply , i know you have very tight schedule.

My requirment which is i have free marker replaced with my back end.

To summarize as mentioned in the screen shot below, i dont want user to change text in these
because it will through exception in my logs ( free marker exception )
[https://github.com/apache/freemarker](https://github.com/apache/freemarker)

![image](https://user-images.githubusercontent.com/1712274/40764444-c0c08422-64b1-11e8-8428-17f5e2ed6ebc.png)

Do you need more info, 
BTW

P.S i updated the fiddle and removed <component-b></component-b> because its typo and not relevant
from another fiddle.
[https://jsfiddle.net/shareefhiasat/u8Lodyh7/1/](https://jsfiddle.net/shareefhiasat/u8Lodyh7/1/)

**Comment by artf** [comment]
I didn't get what is wrong with the solution I proposed to you

**Comment by shareefhiasat** [comment]
@artf  yes its working my friend , thanks a million

here how it is now for future reference , fiddle you cant edit , but you can style

[https://jsfiddle.net/shareefhiasat/jdpkccz0/](https://jsfiddle.net/shareefhiasat/jdpkccz0/)

**Comment by shareefhiasat** [comment]
**UPDATE** for future reference , i updated jsfiddle with editable and none editable component example,
note that the appearance and behavior of hovering over elements dose not work with its not editable
