### ISSUE TITLE
[Question] Only showing "Block" element under Block Manager

### ISSUE THREAD

**Issue by dinhjeffrey** [artf/grapesjs#1138]
Not sure if it's suppose to be like this but I git cloned the repo and npm start. I can only see the "Block" element; cannot see Links, Videos, Sections, Text, Quotes, etc. elements. How do these other elements in the Block Manager?

**Comment by JulyanoF** [comment]
@dinhjeffrey you need to install this extension:
[https://github.com/artf/grapesjs-blocks-basic](Basic Blocks)
