### ISSUE TITLE
Is it possible to create SVG element?

### ISSUE THREAD

**Issue by ganjarsetia** [artf/grapesjs#114]
Hi,

I tried to create shape like triangle using SVG. I tried import the code, but its failed.

**Comment by artf** [comment]
what do you mean with failed? Do you get some kind of error?

**Comment by ganjarsetia** [comment]
@artf I import this code in demo page:
`
<svg height="210" width="500">
  <polygon points="200,10 250,190 160,210" style="fill:lime;stroke:purple;stroke-width:1" />
  Sorry, your browser does not support inline SVG.
</svg>
`
![image](https://user-images.githubusercontent.com/3258090/27389106-ab2c8a28-56c7-11e7-892c-59329cf5e969.png)

but it wont show. And there is no error.

My 2nd method is Add configuration block manager like "badge" demo. And the result is same.

**Comment by artf** [comment]
Ok, I confirm the issue, have to manage SVG differently (need an extra component). I'll try to bring this for the next release

**Comment by ganjarsetia** [comment]
@artf thank bro. Its cool. I'll donate for you :)
