### ISSUE TITLE
[BUG] IE11 Newsletter Demo not working

### ISSUE THREAD

**Issue by TclasenITVT** [artf/grapesjs#1140]
## General Information

I'm trying the the current demo on http://grapesjs.com/demo-newsletter-editor.html. The webpage demo works without a problem but the newsletter demo fails.
![image](https://user-images.githubusercontent.com/35216119/40603532-7caa65ac-625c-11e8-8c32-94a4db4cdb08.png)
I am using IE 11 on Windows 10. IE Version is 11.1088.15063.0, updateversion is 11.0.65 (KB4103768).

## What happens

![grapesjsie11](https://user-images.githubusercontent.com/35216119/40603398-0f32cbe0-625c-11e8-9b88-9c40d15b6edf.PNG)
As seen in the screenshot the whole page is just a blank screen with only the advertisment shown. 

## What is expected

I am expecting the newsletter demo to be displayed.

## Steps to Reproduce
1. Use this Link to [Open the newsletter demo in IE11](https://www.browserling.com/browse/win/7/ie/11/http%3A%2F%2Fgrapesjs.com%2Fdemo-newsletter-editor.html)
2. See blank page

**Comment by shareefhiasat** [comment]
@TclasenITVT  please edit steps to reproduce and add this link
[Test Browser online check IE 11 online grapesjs link](https://www.browserling.com/browse/win/7/ie/11/http%3A%2F%2Fgrapesjs.com%2Fdemo-newsletter-editor.html)

@artf its working on Edge IEs ( version 20 in my case )

Regards

**Comment by TclasenITVT** [comment]
@shareefhiasat  are you satisfied with the way I edited the steps to reproduce?

**Comment by shareefhiasat** [comment]
@TclasenITVT your issue is crystal clear and beautifully written.
Do you really need it for IE11 that badly , sorry am not familiar with code yet but hope some one will 
create this as improvment , but i dont think it blocker ? for you no ?

**Comment by artf** [comment]
Should work now

**Comment by shareefhiasat** [comment]
@artf yes it works now
https://www.browserling.com/browse/win/7/ie/11/http%3A%2F%2Fgrapesjs.com%2Fdemo-newsletter-editor.html

what did you do to fix this ? what was the issue i dont see commits, sorry am new to github collaboration if am missing something.

**Comment by artf** [comment]
Just a problem on the site https://github.com/artf/grapesjs/commit/911caf34f1804f7e21cd18ea90b231d229174350 :)

**Comment by TclasenITVT** [comment]
@artf  thank you a lot for fixing this 👍
