### ISSUE TITLE
how to update the model

### ISSUE THREAD

**Issue by ionic666** [artf/grapesjs#1142]
hi ,now I'm implementing to change my table.
i use this:this.selected.components('<table><tbody>'+tbodys+'</tbody></table>')
but there has one more table and after saving ,the redundant table has changed its site.
![qq20180529-152223](https://user-images.githubusercontent.com/36065691/40643908-1d320672-6354-11e8-8d58-06f081eb5aff.png)

![qq20180529-151857](https://user-images.githubusercontent.com/36065691/40643781-bc4fb1d8-6353-11e8-9a76-028201a3bfbc.png)

**Comment by artf** [comment]
Obviously, if you add rows on init every time, you will get them any time you refresh the page
