### ISSUE TITLE
How  to enable progamatic placeholder block insert

### ISSUE THREAD

**Issue by ssabrewolf** [artf/grapesjs#1143]
Hello grapesjs Team

I succesfully created a component with traits and a block to insert it, when i drag n drop the block there is a green line placeholder which works as guide helper for the user to insert components as seen here 
![landdrag](https://user-images.githubusercontent.com/4706041/40673651-f8e908e0-6337-11e8-84f1-9d5960a8ff47.jpg)
, this line helper only appears on block drag n drop operation, is it possible to trigger this line helper progamaticaly without a manual drag n drop operation, would want to render this line if a url param is present (e.g mysite.com/editor?wcomp=map is available )

Regards

**Comment by artf** [comment]
No, unfortunately, there is no way to trigger d&d in that way, something similar you can do with a selected component in canvas via `editor.runCommand('tlb-move')` but not with blocks
