### ISSUE TITLE
[Question]: Custom property to change multiple settings

### ISSUE THREAD

**Issue by fernandoagarcia** [artf/grapesjs#1144]
Is there a way to extend a current property or create a new one to change multiple properties? I have a component in which I would like to change font-size and padding-left, padding-right etc within one property setting using a radio. But I noticed there is only one value set per option. Is there a way to change multiple values at once?

**Comment by artf** [comment]
Hi Fernando, you can find more about the Style Manager API [here](https://github.com/artf/grapesjs/wiki/API-Style-Manager)

**Comment by fernandoagarcia** [comment]
@artf  My apologies. I meant to say that I would like to target width, padding-left, padding-right within one single property. Perhaps using a radio. I couldn't find an example of that in the docs. Was wondering if it was possible.

**Comment by artf** [comment]
Nope, style manager works per property. But you can create custom behaviors with [Traits](https://github.com/artf/grapesjs/wiki/Traits), in your case you can change the style
