### ISSUE TITLE
Adding traits to wrapper

### ISSUE THREAD

**Issue by sura2k** [artf/grapesjs#1146]
I found a way to add traits to wrapper via `init` function,
```
domComponents: {
	wrapper: {
            emovable: false,
	    copyable: false,
	    draggable: false,
            traits: [...]
        }
}
```

But I had to add other wrapper configs such as `emovable`, `copyable`, etc. Since `wrapper` is only a config element I hope this is the default behavior. However if there is a way to just add `traits[]` without other properties, how it could be done? 

Also I did following.
`DomComponents.getWrapper().get('traits').add({'name':'test', 'type': 'text', 'label':'Test'})`

When I click on wrapper element, I get following error message.
![image](https://user-images.githubusercontent.com/1226939/40719338-f870cd4a-6430-11e8-8a95-4b9aa07f893a.png)

Anyway I'm going to go with the config setting, the first one I described. If there is a better way of doing it, please give me some information.

Thanks.

**Comment by artf** [comment]
> But I had to add other wrapper configs such as emovable, copyable, etc. Since wrapper is only a config element I hope this is the default behavior. However if there is a way to just add traits[] without other properties, how it could be done?

If you do it via init config, this is the way and you have to specify all other properties if you need them.

>Also I did following.
DomComponents.getWrapper().get('traits').add({'name':'test', 'type': 'text', 'label':'Test'})
When I click on wrapper element, I get following error message.

Just tried the same code on the demo and it worked as expected (try to update to the latest version)

**Comment by sura2k** [comment]
I was using 0.14.5. It is working nicely with 0.14.15. Thanks for the tip and sorry to bother without testing it against latest version.

**Comment by betacar** [comment]
@sura2k How did you extract the trait values after they're set? /cc. @artf
