### ISSUE TITLE
[Question] Set selected by element or id (not model)

### ISSUE THREAD

**Issue by JulyanoF** [artf/grapesjs#1147]
Is it possible to set selected content in editor by passing an element or element id instead passing a model?

**Comment by artf** [comment]
```js
const selector = '#itvmm';
editor.select(editor.DomComponents.getWrapper().find(selector)[0]);
```

**Comment by khbhr** [comment]
Hello Artf, 
following the same subject, I am wondering if it is possible when clicking an element to select its parent?
exp: I have an element <a> <img> </a>. I want to have the <a> selected when the user clicks on the <img> knowing that the a has no id. 
Thanks in advance.
