### ISSUE TITLE
Listen to any change in the canvas

### ISSUE THREAD

**Issue by milapshah15** [artf/grapesjs#1152]
Hello Folks,

I have a requirement where I added a button which saves the configuration to the remote DB.Now I would like to listen to any change in the canvas to enable/disable the button.For example, If there is any change, enable the save button for user to save it.I have gone through available events but I found nothing which listen to any change (Style,Component add/remove).

Any help? @artf 

Warm regards
Milap

**Comment by IStirton10** [comment]
I'm not sure if there's one exclusive event that listens for any changes to the canvas. Perhaps you could have your method run on all of the canvas events instead?

https://github.com/artf/grapesjs/blob/dev/src/editor/index.js#L53
`* ## Canvas
 * * `canvas:dragenter` - When something is dragged inside the canvas, `DataTransfer` instance passed as an argument
 * * `canvas:dragover` - When something is dragging on canvas, `DataTransfer` instance passed as an argument
 * * `canvas:drop` - Something is dropped in canvas, `DataTransfer` instance and the dropped model are passed as arguments
 * * `canvas:dragend` - When a drag operation is ended, `DataTransfer` instance passed as an argument
 * * `canvas:dragdata` - On any dataTransfer parse, `DataTransfer` instance and the `result` are passed as arguments.`

**Comment by milapshah15** [comment]
@IStirton10 Let me try it out.I guess this should work.

Warm regards
Milap

**Comment by milapshah15** [comment]
@IStirton10 Its working.Thank you.

Is there a method which makes button disabled and not clickable.The Enable property is just about making it selected.Do we have anything to disable the button.

@artf Any thoughts?

Warm regards
Milap

**Comment by ionic666** [comment]
@milapshah15 hi ,bro.i am doing this.Have you implemented the disable button function

**Comment by artf** [comment]
> Its working.Thank you.

I'm closing this then

> Is there a method which makes button disabled and not clickable.The Enable property is just about making it selected.Do we have anything to disable the button.

```js
btnModel.set('disable', true);
```

**Comment by milapshah15** [comment]
@ionic666 No I did not find any method which can disable the button

Warm regards
Milap
