### ISSUE TITLE
Create minimalist Panel left sidebar

### ISSUE THREAD

**Issue by ssabrewolf** [artf/grapesjs#1153]
Hi grapesjs Team

Is it possible to create a quick access left panel sidebar with the most popular blocks(text,image,2column,etc), this way is always visible because selecting any component on canvas automatically hides the main right blocks panel, if so, how could the same drag n drop behaviour from original blocks could be replicated in this new custom left panel with buttons , e.g 
![panelmini](https://user-images.githubusercontent.com/4706041/40840656-4001cf46-656d-11e8-9bda-c6619fe7c009.png)

Regards

**Comment by artf** [comment]
Check this example https://codepen.io/artf/full/MQpZPj/

**Comment by ssabrewolf** [comment]
Hello  @artf  tx for the info, i checked the provided example but  hides all the other elements, i would like to keep complex advance elements while add an alternative quick access always visible panel with the most popular buttons, if a complex less often used element is required (e.g flexbox ) still can be selected on the 'right panel, is there any way to recreate some popuplar components in the left panel while keeping the other ones

Regards
