### ISSUE TITLE
[BUG] Droppable propagation

### ISSUE THREAD

**Issue by alfaalex81** [artf/grapesjs#1154]
I found a problem with droppable propagation. I do an example. I drop "3 columns" inside my template (yellow zone in jsfiddle), now, if i want add an image inside one of the columns, the green selector not appear. If I remove all data-gjs the system works correctly

https://jsfiddle.net/7tdkjj6a/

**Comment by artf** [comment]
This happens because in the inner box you propagate `droppable` and when you drop the table its `droppable` goes to columns
BTW use always the latest version
