### ISSUE TITLE
Plugin gjs-style-gradient not found

### ISSUE THREAD

**Issue by Deepak813** [artf/grapesjs#1156]
Hi @artf,

I am getting this issue in gradient plugin "Plugin gjs-style-gradient not found".Used below code to include in our file:

editor  = grapesjs.init({     
      plugins: [ 'gjs-style-gradient'], 
      pluginsOpts: {
                  'gjs-style-gradient': {
                      colorPicker: 'default',
                      grapickOpts: {
                          min: 1,
                          max: 99,
                      }
                    },

Also, i have reference this issue #1116 but not found any solution.
Please help us to resolve this issue.

**Comment by Deepak813** [comment]
Hi @ssabrewolf,

Thanks for the message.

I have used the same code but still get the same error "Plugin gjs-style-gradient not found" in Mozilla browser.See the code below:

editor.StyleManager.addProperty('Page Settings', {
    name: 'Gradient',
    property: 'background-image',
    type: 'gradient',
    defaults: '100'
});

editor.StyleManager.addProperty('Section Settings', {
    name: 'Gradient',
    property: 'background-image',
    type: 'gradient',
    defaults: '100'
});

Please provide the valuable solution.

**Comment by artf** [comment]
`but some time ...`?!? 
Please just check if the plugin is actually loaded, because it's just you
