### ISSUE TITLE
Return span randomly in custom component

### ISSUE THREAD

**Issue by krunal039** [artf/grapesjs#1157]
I have custom component and on trait change wanted to updated html but randomly it returned span/textnode in trait change function insted of html element. Below is html generated by component and on title change want to updated h4 element.

![capture](https://user-images.githubusercontent.com/11716808/40848263-9b5648b0-65b6-11e8-940d-dbe4ebec8fff.PNG)

```
updateTitle : function updateTitle() {
                    var title = this.get('title');
                    var linkModel = this.get("components").at(0);
                    if (linkModel) {
                        var titleContainer = linkModel.get("components").at(3);
                        if (titleContainer) {
                            var h4 = titleContainer.get("components").at(0);
                            if (h4) {
                                h4.set("content", title);
                            }
                        }
                        linkModel.attributes.attributes["aria-label"] = title;
                        linkModel.attributes.attributes["title"] = title;
                    }
                    this.set("data-title", title);
                    if (this.get('isCreatePage') && this.changed && this.changed.title) {
                        this.set('isPageCreated', false);
                        this.set('bespokePageUrl', '');
                        this.updateIsCreatePage();
                    }
                }
```

- linkModel.get("components").at(0) returns "div.programme-description" correctly
- linkModel.get("components").at(1) returns "span" not sure from where it is coming
- linkModel.get("components").at(2) returns "span" not sure from where it is coming
- linkModel.get("components").at(3) returns "img.programme-content-image" correctly
- linkModel.get("components").at(4) return "div.programme-play-button-hidden" correctly 
- linkModel.get("components").at(5) return "div.programme-title" correctly 

here not sure from where linkModel.get("components").at(1) & linkModel.get("components").at(2) "span" are returned and they are returned randomly so not sure what is happing and due to it h4 title is not updated as index of item changes.

**Comment by artf** [comment]
Well from what you've posted I can't tell what is happening but definitely, there is nothing generated randomly, just go deeper with the debug.
BTW you can solve this easier by using `find` method:
```js
var title = this.get('title');
...
var h4 = this.find('h4')[0]; // returns an array of models
h4 && h4.set("content", title);
...
```

**Comment by krunal039** [comment]
@artf  I tried to debug but no luck as it is happening on some pages and not on all pages. also 

`this.find` is undefined
![image](https://user-images.githubusercontent.com/11716808/41103010-0b5bbdf4-6a60-11e8-8982-bf9d8fc29533.png)

**Comment by artf** [comment]
Just update grapesjs

**Comment by krunal039** [comment]
@artf I did update grapesjs to  0.12.17 and under for trait changes it still says  this.find('a')[0] is not function.

**Comment by artf** [comment]
> I did update grapesjs to 0.12.17 

I mean the latest version...

**Comment by krunal039** [comment]
@art I updated it to 0.14.23 and it cannot find any element all are returned with empty array, not sure what am I doing wrong.

Component Code:
`function createPCBoxNewComp(comps, defaultModel, defaultView, defaultValue) {

        comps.addType('programmerContent', {
            // Define the Model
            model: defaultModel.extend({
                // Extend default properties
                defaults: Object.assign({}, defaultModel.prototype.defaults, {
                    droppable: false,
                    draggable: true,
                    type: 'programmerContent',
                    tagName: 'div',
                    void: 0,
                    isActive: true,
                    grayout: false,
                    isVideo: false,
                    isCreatePage: false,
                    src: 'https://team.global.hsbc/sites/LearningDevLib/hsbc_uni_images/placeholder-image/programme.png',
                    hoverText: 'Lorem Ipsum link',
                    title: 'Lorem Ipsum',
                    link: 'https://team.global.hsbc/sites/HSBCUni',
                    target: '_blank',
                    isPageCreated: false,
                    attributes: {
                        frameborder: 0,
                        'data-gjs-type': 'programmerContent'
                    },
                    traits: [{
                            type: 'checkbox',
                            label: 'Video',
                            name: 'isVideo',
                            changeProp: 1
                        },
                        {
                            type: 'checkbox',
                            label: 'Grayout(Link will not open)',
                            name: 'grayout',
                            changeProp: 1
                        }, {
                            type: 'text',
                            label: 'Hover Text',
                            name: 'hoverText',
                            placeholder: 'eg. Lorem Ipsum link',
                            changeProp: 1
                        }, {
                            type: 'text',
                            label: 'Title',
                            name: 'title',
                            placeholder: 'eg. Lorem Ipsum',
                            changeProp: 1
                        }, {
                            type: 'text',
                            label: 'Link to open',
                            name: 'link',
                            placeholder: 'eg. https://team.global.hsbc/sites/HSBCUni',
                            changeProp: 1
                        }, {
                            type: 'select',
                            label: 'Target',
                            name: 'target',
                            options: [{
                                value: '_parent',
                                name: 'This Window'
                            }, {
                                value: '_blank',
                                name: 'New Window'
                            }],
                            changeProp: 1
                        },
                        {
                            type: 'checkbox',
                            label: 'Create Page',
                            name: 'isCreatePage',
                            changeProp: 1
                        }
                    ]
                }),
                initialize: function initialize(o) {
                    defaultModel.prototype.initialize.apply(this, arguments);
                    this.listenTo(this, 'change:grayout', this.updateGrayout);
                    this.listenTo(this, 'change:isVideo', this.updateIsVideo);
                    this.listenTo(this, 'change:target', this.updateTarget);
                    this.listenTo(this, 'change:title', this.updateTitle);
                    this.listenTo(this, 'change:hoverText', this.updateHoverText);
                    this.listenTo(this, 'change:link', this.updateLink);
                    this.listenTo(this, 'dblclick active', this.openModal);
                    this.listenTo(this, 'change:src', this.updateSrc);
                    if (this.config.modal) this.modal = this.config.modal;
                    if (this.config.am) this.am = this.config.am;
                },
                updateGrayout: function updateGrayout() {
                    var grayout = this.get('grayout');
                    var image = this.find('img')[0];
                    var anchor = this.find('a')[0];
                    if (grayout) {
                        image && image.get('classes').add({
                            name: 'programme-content-image-grayout'
                        });
                        anchor && anchor.set("href", "#");
                    } else {
                        image && image.get('classes').remove({
                            name: 'programme-content-image-grayout'
                        });
                        anchor && anchor.set("href", this.get('link'));
                    }
                },
                updateIsVideo: function updateIsVideo() {
                    var isVideo = this.get('isVideo');
                    var playButton = this.find('div.programme-play-button')[0]
                    var link = this.get("components").at(0);
                    if (isVideo) {
                        playButton && playButton.get('classes').add({
                            name: 'programme-play-button-show'
                        });
                        playButton && playButton.get('classes').remove({
                            name: 'programme-play-button-hidden'
                        });
                    } else {
                        playButton && playButton.get('classes').add({
                            name: 'programme-play-button-hidden'
                        });
                        playButton && playButton.get('classes').remove({
                            name: 'programme-play-button-show'
                        });
                    }
                },

                updateTitle: function updateTitle() {debugger;
                    var title = this.get('title');
                    var h4Title = this.find('h4')[0];
                    h4Title && h4.set("content", title);
                },

                updateHoverText: function updateHoverText() {
                    var hoverText = this.get('hoverText');
                    var hoverTextDiv = this.find("div.programme-description-text");
                    hoverTextDiv && hoverTextDiv.set("content", hoverText);
                },
                updateLink: function updateLink() {
                    var link = this.get('grayout') ? "#" : this.get('link');
                    var anchor = this.find('a')[0];
                    anchor && anchor.set("href", link);
                },
                updateTarget: function updateTarget() {
                    var target = this.get('target');
                    var anchor = this.find('a')[0];
                    anchor && anchor.set("src", src);
                },
                updateSrc: function updateSrc() {
                    var src = this.get('src');
                    var anchor = this.find('a')[0];
                    anchor && anchor.set("target", target);
                }
            }, {
                isComponent: function isComponent(el) {
                    if (el.getAttribute && el.getAttribute('data-gjs-type') == 'programmerContent' ||
                        (el.className &&
                            el.className.indexOf('programmerContent') > 0)) {
                        return {
                            type: 'programmerContent'
                        };
                    }
                }
            }),


            // Define the View
            view: defaultView.extend({

                tagName: 'div',
                events: {
                    'dblclick': 'openModal',
                    'click': 'openSettings'
                },

                openSettings: function openSettings(e) {

                    this.el.click();

                    var openBlocksBtn = editor.Panels.getButton('views', 'open-blocks');
                    openBlocksBtn && openBlocksBtn.set('active', 0);

                    var openTMBtn = editor.Panels.getButton('views', 'open-tm');
                    openTMBtn && openTMBtn.set('active', 1);
                },
                initialize: function initialize(o) {
                    defaultView.prototype.initialize.apply(this, arguments);
                    this.classEmpty = this.ppfx + 'plh-pc-box';
                    if (this.config.modal) this.modal = this.config.modal;
                    if (this.config.am) this.am = this.config.am;
                },

                openModal: function openModal(e) {
                    var em = this.opts.config.em;
                    var editor = em ? em.get('Editor') : '';

                    if (editor) {
                        editor.runCommand('open-assets', {
                            target: this.model,
                            onSelect: function onSelect() {
                                editor.Modal.close();

                                editor.AssetManager.setTarget(null);
                            }
                        });
                    }
                    this.el.click();
                },
                disableClick: function disableClick() {
                    this.preventDefault();
                },
                render: function render() {
                    this.updateClasses();
                    this.updateAttributes();
                    var grayout = this.model.get("grayout");
                    var isVideo = this.model.get("isVideo");
                    var link = this.model.get("a_href");
                    var target = this.model.get("target");
                    var title = this.model.get("title");
                    var hoverText = this.model.get("hoverText");
                    var grayoutClass = grayout ? "-text-grayout" : "";
                    var grayoutImageClass = grayout ? " programme-content-image-grayout" : "";
                    var videoClass = isVideo ? "programme-play-button-show" :
                        "programme-play-button-hidden";
                    var src = this.model.get("src");

                    var template = '<a target=' + target +
                        ' onclick=\'event.preventDefault()\' href="' + link + '" aria-label="' +
                        title + '" text="' + title +
                        '"><div class="programme-description"><div class="programme-description-text"' +
                        grayoutClass + '>' + hoverText +
                        '</div></div> <img class="programme-content-image ' + grayoutImageClass +
                        '" src="' + src + '"><div class="' + videoClass + ' programme-play-button"' +
                        grayoutClass +
                        '> <i class="fa fa-play-circle" aria-hidden="true"></i></div><div class="programme-title"><h4>' +
                        title + '</h4></div> </a>';
                    this.el.className = "pcBox-new programme-item";
                    this.el.setAttribute("data-gjs-type", "pcBox-new");
                    this.el.innerHTML = template;
                    return this;
                }
            })
        });
    };`

 HTML on canvas: 
`<div data-gjs-type="programmerContent" frameborder="0" src="https://team.global.temp/sites/LearningDevLib/temp_uni_images/placeholder-image/programme.png" data-highlightable="1" id="iixq" class="programmerContent programme-item gjs-comp-selected"><a target="_blank" onclick="event.preventDefault()" href="undefined" aria-label="Lorem Ipsum" text="Lorem Ipsum"><div class="programme-description"><div class="programme-description-text">Lorem Ipsum link</div></div> <img class="programme-content-image " src="https://team.global.temp/sites/LearningDevLib/temp_uni_images/placeholder-image/programme.png"><div class="programme-play-button-hidden programme-play-button"> <i class="fa fa-play-circle" aria-hidden="true"></i></div><div class="programme-title"><h4>Lorem Ipsum</h4></div> </a></div>`

![1 1](https://user-images.githubusercontent.com/11716808/42750173-2dcb4e26-88de-11e8-8331-c9745711b739.png)
![2 1](https://user-images.githubusercontent.com/11716808/42750174-2e6731ec-88de-11e8-99dc-028feadb1aac.png)
