### ISSUE TITLE
[Question] Do I need to include dropzone css to show the dragging hover

### ISSUE THREAD

**Issue by besingasj** [artf/grapesjs#1161]
I have enable dropzone on assetManager and i think it works correctly. But I also notice that the hovering effect when the image is being dragNdrop is not working. I just see the text on the upper left corner. here is my initiation of the grapesjs.

```js
import grapesjs from 'grapesjs';
import 'grapesjs-blocks-basic';

let editor = grapesjs.init({
    container: '#gjs',
    height: '100%',
    plugins: ['gjs-blocks-basic'],
    pluginOptions: {
        'gjs-blocks-basic': {}
    },

    // storemanager
    storageManager: {
        type: 1,
        autoload: 'none'
    },

    // asset manager
    assetManager: {
        upload: 'http://localhost/upload.php',
        dropzone: 1,
        dropzoneContent: '<div class="dropzone-inner">Drop here your assets</div>'
    }
});
```

![dropzone bug](https://user-images.githubusercontent.com/25261663/40879896-59548eb6-66da-11e8-98de-ba3e89e87de1.png)

as you can see there is no hovering effect just like what is shown here. https://github.com/artf/grapesjs/wiki/Assets#setup-dropzone

**Comment by artf** [comment]
@besingasj the styling of the dropzone is up to you
