### ISSUE TITLE
[Question] How do I set <body> attributes

### ISSUE THREAD

**Issue by agungaja** [artf/grapesjs#1163]
Hi @artf, 

On the previous issue #1132 about export `<body my="attributes">` code, I think it's done using `exportWrapper: true`. But now experiencing constraints when it will import attributes from `<body>`, I try to set attributes does not work. I used ` importWrapper: true`. Any solutions? 

Please help and thank you :)

Figure 1: Import tag body with attributes, when I edit code, the attribute is missing
![image](https://user-images.githubusercontent.com/39617738/40899700-700c9f54-67f2-11e8-94ec-852116fe7de6.png)

**Comment by shareefhiasat** [comment]
Hi @agungaja  , can you please point the documentation of `exportWrapper: true,  ` for some reason i cant find it , i think it may solve me the problem but curious to read its wiki ! Thanks

**Comment by agungaja** [comment]
yes it is true, I also can not find it. I was only given info by @artf in issue #1132. Or maybe I have a less exploratory documentation 😄.

The point is, why when the content set uses 
`var initcontent = $('#import_html').val();`
`editor.setComponents(initcontent);`
the body attribute disappears

**Comment by artf** [comment]
@agungaja there is no `importWrapper` option and you can't import tag `<body>`. GrapesJS expect the user to pass the CONTENT... not the WRAPPER (which in most cases is body), the wrapper should be defined [by its configuration](https://github.com/artf/grapesjs/blob/dev/src/dom_components/config/config.js#L9-L24);
