### ISSUE TITLE
There will be extra div

### ISSUE THREAD

**Issue by ionic666** [artf/grapesjs#1166]
hi ,when i drag a div ,there will be a extra div around it.
![qq20180605-132832](https://user-images.githubusercontent.com/36065691/40956801-af942912-68c4-11e8-880d-d4248fd9d690.png)
![qq20180605-132816](https://user-images.githubusercontent.com/36065691/40956802-b066e032-68c4-11e8-89ea-2a7b13a02b5d.png)

**Comment by shareefhiasat** [comment]
@ionic666 good question , can you prepare js fiddle like this, [https://jsfiddle.net/ssabrewolf/7ur0cwq3/32/](https://jsfiddle.net/ssabrewolf/7ur0cwq3/32/) it will save us time to respond , thanks

**Comment by artf** [comment]
This is what you've asked to render... `components:` are children in your case, probably you just need this `content: '<div>123</div>'`

**Comment by ionic666** [comment]
@shareefhiasat sorry,I can't open the url you provided,Can you give me some screenshots or code.thanks

**Comment by shareefhiasat** [comment]
@ionic666 its just jsfiddle url it opens
[https://jsfiddle.net/ssabrewolf/7ur0cwq3/32/](https://jsfiddle.net/ssabrewolf/7ur0cwq3/32/)

1. You can open any issue with jsfiddle link prepared
2. fork it
3. And edit to match your code

The idea just try provide a demo so any one can trace/solve
