### ISSUE TITLE
[QUESTION] export options

### ISSUE THREAD

**Issue by maxencehenneron** [artf/grapesjs#1167]
Hi @artf,

Are there any other export options than HTML/CSS ? I'm thinking of a way to directly load the configuration from a remote server and render it on a web page on the fly.

Good job on grapejs! :)

**Comment by artf** [comment]
Thanks @maxencehenneron but I don't understand how this `I'm thinking of a way to directly load the configuration from a remote server and render it on a web page on the fly` (that you can alredy do it via the built-in remote storage) is related to `other export options than HTML/CSS`, what else do you need?
Btw maybe this can help: https://github.com/artf/grapesjs/wiki/Storage

**Comment by maxencehenneron** [comment]
Currently, grapeJS exports the template in HTML/CSS, I wanted to know if there was an easy way to create a front-end app that would load the configuration saved by GrapeJS via the remote storage and render it on a web page. The flow would be:

- Use GrapeJS to build the template, save it to the remote server via the remote storage in the wiki page you sent
- Have a webserver that would get the configuration from the remote endpoint and render all the components directly when someone loads a page.

I achieved the first part quite easily, but I'm still struggling about the second part, is it natively implemented?

**Comment by artf** [comment]
Yeah sure, I explain the exact thing here https://github.com/artf/grapesjs/wiki/Storage#store-and-load-templates
You can init the editor from HTML or directly (without parsing) via the JSON
```js
grapesjs.init({
  ...
  components: `<div>...</div><div>...</div>`,
});
// Or
const editor = grapesjs.init({
  ...
  components: [{...}, {...}],
});
// and now I can get its HTML
const html = editor.getHtml();
```
