### ISSUE TITLE
Why  transform : translate() is missing?

### ISSUE THREAD

**Issue by babak-karimi-asl** [artf/grapesjs#1168]
perfect . finally community is creating a perfect tool with 100% control over css and html.

but i'm wandered why  `transform:translate` is missing ?

![2018-06-05-233851_1366x768_scrot](https://user-images.githubusercontent.com/31150843/40997941-828730ca-691b-11e8-85dc-4d60b2e05103.png)

**Comment by artf** [comment]
It's missing just because this is how is defined [in the preset plugin](https://github.com/artf/grapesjs-preset-webpage/blob/master/src/styles/index.js) but you can actually override it with your configuration and add all the transform you need
