### ISSUE TITLE
Issue with Navbar Styling

### ISSUE THREAD

**Issue by milapshah15** [artf/grapesjs#1170]
Hello Everyone,

I am facing issue in Navbar where responsiveness is not working and styling is also conflicting with bootstrap.

@artf Can you please help on this?

Warm regards
Milap

**Comment by FrciSmrci** [comment]
Hey @milapshah15 ,

could you provide a little more information? Do you import bootstrap through the GrapesJS initialisation config under canvas styles property? Is the issue you are facing with responsiveness on bootstrap navbar or grapesjs?

Are your styles clashing with bootstraps when using basic blocks plugin? Here is an closed issue discussing the [solution](https://github.com/artf/grapesjs/issues/1109). Basically all you need to do is add an stylePrefix to the initialisation config . `grapesjs.init({ container: '#gjs', plugins: ['gjs-preset-webpage'], pluginsOpts: { 'gjs-preset-webpage': { **blocksBasicOpts**: { blocks: ['link-block', 'quote', 'image', 'video', 'text', 'column1', 'column2', 'column3'], **stylePrefix**: 'ch-' }}}});`

Have a great day.
