### ISSUE TITLE
how to change the content 

### ISSUE THREAD

**Issue by ionic666** [artf/grapesjs#1171]
hi ,Thank you for your advice on the previous question.but when i change the content ,there will be a extra table.can you tell me which method can just change the content?
![qq20180606-092912](https://user-images.githubusercontent.com/36065691/41010946-ef5fb9e6-696c-11e8-98e6-5b5beed936b1.png)
![qq20180606-092957](https://user-images.githubusercontent.com/36065691/41010950-f3ac39ac-696c-11e8-801f-8880efc00d9e.png)

**Comment by artf** [comment]
again @ionic666, `components` are children, so you're NOT replacing the component, you're just adding children. If you need for example to update attributes of the wrapper you do this `selected.setAttributes({ property: 'value' })`
