### ISSUE TITLE
How control settings like Google Maps

### ISSUE THREAD

**Issue by AlejandroBlackburn** [artf/grapesjs#1172]
I've been reading the GrapeJS API but couldn't find where I can manipulate a block's settings and pass those parameters as they are in the Google Maps block. Where can I find the information I need?

![image](https://user-images.githubusercontent.com/11187639/41020241-ae053650-6927-11e8-8681-f500277d05a0.png)

**Comment by artf** [comment]
This is how the map block is [inserted via basic blocks plugin](https://github.com/artf/grapesjs-blocks-basic/blob/master/src/blocks.js#L221-L229)
So you can override it in this way
```js
editor.BlockManager.add('map', {
    label: 'My Map',
    attributes: { class:'fa fa-map-o' },
    content: {
      type: 'map',
      style: { height: '350px' },
	  mapType: 'q', // q - Roadmap / w - Satellite
      address: 'Miami',
      zoom: 1, // max 20
    },
  });
```
