### ISSUE TITLE
How to change the content of a dragged component?

### ISSUE THREAD

**Issue by jerrytohvan** [artf/grapesjs#1174]
Hi everyone,
Im kinda stuck with creating a custom component. 

A custom block that im currently building supposed to show a modal with buttons pointing to a function which will then inserts a particular component based on selected button. The problem im having is that appending the div is not rendered and stored (component is gone when dragged). 

What are better ways to do it? Can a content of a dragged component be changed through a js function? 

Thank you

**Comment by artf** [comment]
Follow the issue template and post your code
