### ISSUE TITLE
How to modify the content of the added block

### ISSUE THREAD

**Issue by ionic666** [artf/grapesjs#1175]
sorry,I created a type for button and I don't know how to change the content of the button.thanks so much!!
![qq20180606-170858](https://user-images.githubusercontent.com/36065691/41028611-64bc6e52-69ac-11e8-8f09-9a43e3a2d011.png)

**Comment by FrciSmrci** [comment]
Hey @ionic666 ,

as it's stated in the [documentation](https://github.com/artf/grapesjs/wiki/Components) for the components. Turn off autorender when adding new types of component. 

You can change the content of an component extending the view of the defaultModel inside the render function. There are two possibilities: 
1. Change/set the model --> This will affect the final HTML code
2. Change/set the dom element --> This doesn't affect the final HTML code just the view.  

All of the above can be found in the grapesjs docs provided above.

Have a great day. :)
