### ISSUE TITLE
[QUESTION] Multiple identical classes usage

### ISSUE THREAD

**Issue by FrciSmrci** [artf/grapesjs#1177]
Hey @artf ,

I have a question around the Style Manager. Let's say we have multiple elements with row classes inside html, is there any possibility that on selection of a specific element the styles changed through the StyleManager are added on a programmatically created id/class instead of the existing class (in this scenario row)? 

I think that the current implementation may be a little confusing from the perspective that the user expects that his action will reflect on the specific element he chose to style not every other element with the same style. 

Thanks in advance 🙂

**Comment by artf** [comment]
> I think that the current implementation may be a little confusing from the perspective that the user expects that his action will reflect on the specific element he chose to style not every other element with the same style.

Yeah, I agree with you, the current implementation of classes is probably too much tech/dev oriented, what I have planned to do in the future is to create a similar approach [used in Sketch](https://www.sketchapp.com/docs/styling/shared-styles/) but unfortunately, don't have time to implement it.

BTW for now the only solution I can suggest is to make you selectors (classes) private, here is an example https://codepen.io/artf/pen/jaaKvq

**Comment by FrciSmrci** [comment]
@artf , works great. Thank you! :)
