### ISSUE TITLE
Override open assetsManager modal ?

### ISSUE THREAD

**Issue by FlashPapa** [artf/grapesjs#118]
Hi,
Is it possible to do override open assetsManager modal ? To open another modal or call another js function ?
Thanks

**Comment by artf** [comment]
Yeah, I think [grapesjs-plugin-filestack](https://github.com/artf/grapesjs-plugin-filestack) is a good example of how to extend the basic functionality, but, in the same way, you can "override" it (close the actual modal and call whatever you want)
