### ISSUE TITLE
[Question] React with GrapeJS

### ISSUE THREAD

**Issue by Silavin** [artf/grapesjs#1180]
Greetings, I did searches and could not particularly find a solution to my problem. Currently, I am trying to integrate my React App with GrapeJS. 
`import React, { Component } from 'react';
import './GrapesSrc/grapes.min.js';
import GrapesIndex from 'grapejs';

class GrapesEditor extends Component {
    constructor(props){
        super(props);
        
    }
    shouldComponentUpdate(){
        return false
    }

    componentDidMount(){
        
        const editor = grapesjs.init({
            container : '#gjs',
            components: '<div class="txt-red">Hello world!</div>',
            style: '.txt-red{color: red}',
        });
    }

  render() {

    return (
      <div id ='gjs'>    

      </div>
    );
  }
}

export default GrapesEditor;
`

I have tried using the CDN, including it into my index.html file but all of that still had the error of grapesjs being undefined.
I tried to import './GrapesSrc/grapes.min.js' directly. Creating a new folder with the codes in the CDN but it still did not work.

I am not sure if this is a valid question or not since there was one issue that seemed similar to this that was rejected.

**Comment by cjpollard** [comment]
If you're using webpack to build your React app, you can include it as a plugin.  It'll pull it from node_modules.
``plugins: [
        new webpack.ProvidePlugin({
            grapesjs: "grapesjs"
        })
    ],``
This worked for me.

**Comment by Silavin** [comment]
Alright. I've never done this before so here goes.

I'm really new to this so I don't really know what I'm doing so in case there is some kind of issue with my steps, I'll write it down.

1)npm run eject (since create-react-app does not allow me to directly change the the configurations)
2)added new webpack.ProvidePlugin({ grapesjs: "grapesjs" }) into files:
   webpack.config.dev and webpack.config.prod
under object:
    module.exports={module:{ plugins:[... ] }}

Unfortunately, 'grapesjs' is not defined  no-undef

**Comment by cjpollard** [comment]
"grapejs" is a different npm module to "grapesjs".  You should npm install grapesjs.  Step 3 shouldn't be necessary.

**Comment by Silavin** [comment]
Oh! I did not realise that there are two different npm packages. Yes. I've installed grapesjs now. 

However, I do not understand. why is it not necessary to import grapesjs from 'grapesjs'?

**Comment by cjpollard** [comment]
ProvidePlugin automatically loads grapesjs so it's available anywhere in the code, making importing it again redundant.

**Comment by Silavin** [comment]
Hmm... well, I removed step 3 but what appeared in its place is  
Line 10:  'grapesjs' is not defined  no-undef

Meanwhile, when I tried to import the file over, nothing is present

**Comment by sakshigarg9** [comment]
> If you're using webpack to build your React app, you can include it as a plugin. It'll pull it from node_modules.
> `plugins: [ new webpack.ProvidePlugin({ grapesjs: "grapesjs" }) ],`
> This worked for me.

Hi, I added this plugin under plugins:[..] in the webpack.config.js file and it still won't work

**Comment by artf** [comment]
@sakshigarg9 add `grapesjs` via npm, then in your code just use `import grapesjs from 'grapesjs'` It will work, without any need to update the webpack configuration
