### ISSUE TITLE
Working with big images

### ISSUE THREAD

**Issue by YairHadari** [artf/grapesjs#1181]
Hi,

My end user is trying to load a very big image.
When I"m working with local storage I"m reaching the local storage size limitation and when I"m working with remote I"m reaching the PHP post size limitation.
Is there any built in solution to reduce the size of the image or passing data with get when saving to remote?

Thanks in advance,
Yair

**Comment by artf** [comment]
For the local storage check this https://github.com/artf/grapesjs-indexeddb
For PHP, obviously, it's up to you
