### ISSUE TITLE
Is it possible to have only one button in the canvas

### ISSUE THREAD

**Issue by ionic666** [artf/grapesjs#1184]
hi,bro。I want to implement that there is only one button in the canvas.when i drag the second,it  will not be placed correctly or the button is disabled.
![qq20180608-143259](https://user-images.githubusercontent.com/36065691/41142638-df6c96ea-6b28-11e8-9ce7-ea3ef56808ff.png)

**Comment by artf** [comment]
You're just missing the check for the current dragged model
