### ISSUE TITLE
Create minimalist Panel left sidebar II

### ISSUE THREAD

**Issue by ssabrewolf** [artf/grapesjs#1188]
Hello grapesjs Team

Regarding the answer given on #1153  , im posting here cause im not sure if closed issues are still visible: 
 @artf tx for the info, i checked the provided example here   https://codepen.io/artf/full/MQpZPj/   but it hides all the other elements, i would like to keep complex advance elements while add an alternative quick access always visible panel with the most popular buttons, if a complex less often used component is required (e.g flexbox ) still can be selected on the 'right panel, is there any way to recreate some popular components in the left panel while keeping the other ones working as usual

Regards

**Comment by artf** [comment]
@ssabrewolf check better the JS code, I just rerender blocks with another collection, if you don't do it, you see them all

**Comment by ssabrewolf** [comment]
hello @artf  , thank you for the comment,  i see in the code  https://codepen.io/artf/full/MQpZPj/   the appendTo flag is used in order to render a filtered set of the components in the # blocks id, how could be rendered 2 differntent  component collections at the same time ,e.g we  .block1=>{ text,image  } and .block 2{ column2, column3, map  } so we have 2 blocks at the same time, using the current code it always reset the current collection, would like remove a few from main collection keep working and then render another collection in other block keeping both visible,    if there is only one BlockManager instance pointing to one single dom element
![singleblockpanel](https://user-images.githubusercontent.com/4706041/41413909-2f6a4c20-6faa-11e8-9285-cbb439580d53.png)

Regards
