### ISSUE TITLE
Autosave triggering when disabled

### ISSUE THREAD

**Issue by thecodefish** [artf/grapesjs#119]
I have configured the editor as follows (relevant bits only)

```
var editor = grapesjs.init({
...
storageManager: {
  autosave: false,
  stepsBeforeSave: 0,
  type: 'remote',
  urlStore: 'my/url',
  beforeSend: function() {
    console.log('before send');
  }
  ...
}
...
});
```

The only reason I specified 'remote' was just so that I could keep track of when/how it was saving (I'll be turning autosave on later).

The behaviour I'm seeing is that the editor attempts to autosave after every change (because stepsBeforeSave is 0) even though I have autosave disabled.

I'm not 100% sure but I wonder whether the bug lies in editor/model/Editor.js:

```
  componentsUpdated(model, val, opt) {
    var updatedCount = this.get('changesCount') + 1,
        avSt  = opt ? opt.avoidStore : 0;
    this.set('changesCount', updatedCount);
    var stm = this.get('StorageManager');
    if(stm.isAutosave() && updatedCount < stm.getStepsBeforeSave()){ //I think this is the problem
      return;
    }

    if(!avSt){
      this.store();
    }
  },
```
The way this reads, the code will still call this.store() if stm.isAutoSave() returns false. I think the line should actually be something like this:

`if (!stm.isAutosave() || updatedCount < stm.getStepsBeforeSave()) {`

If this is actually the problem, the same line of code exists in the rulesUpdated() function in the same file.

I intended to test this locally and do a pull request but I couldn't get the code building on my machine (I'll investigate that later and maybe raise another issue). So this is all a bit of speculation as to the source of the problem.

**Comment by artf** [comment]
thanks @thecodefish I think you're right and it should work correctly with your fix, editor/model/Editor.js is actually one of the files I have to hardly check and refactor. I'll fix it for the next release
