### ISSUE TITLE
[QUESTION] Not able to initialize colorpicker !

### ISSUE THREAD

**Issue by Siddharth-ss42279** [artf/grapesjs#1193]
Hi @artf ,
I made separate styles for mobile view . i want to initialize color-picker "onclick()". i want exactly same color-picker that you are using in grapesjs editor. how can i initialize same color-picker?? thanks in advance @artf  ??

**Comment by artf** [comment]
Internally, it's a modified version of https://github.com/bgrins/spectrum

**Comment by Siddharth-ss42279** [comment]
Thanks for the help ! @artf 
![screen shot 2018-06-14 at 11 33 52 am](https://user-images.githubusercontent.com/13647531/41394254-f91b7758-6fc6-11e8-870f-f9ebea3bbd23.png)

I want exactly same color-picker that you are using in your grapesjs-editor ? is there any way to get same color-picker ?????

i got this color picker from above solution , thanks in advance @artf 
![screen shot 2018-06-14 at 11 35 49 am](https://user-images.githubusercontent.com/13647531/41394377-5520f97e-6fc7-11e8-8e67-f9e8fefd0765.png)
