### ISSUE TITLE
[QUESTION]: load existing html web template into GrapesJS

### ISSUE THREAD

**Issue by MobileAppVault** [artf/grapesjs#1194]
Hi,

I want to load an existing HTML Template into grapesjs and edit the page.

Edit means:
- move sections
- add/remove edit buttons, images etc.

My template source will be https://html5up.net/ for example.

How I can achieve this? 
Do I need to split my template into components? 

Many thanks for any answer help or suggestions.

Marcus

**Comment by artf** [comment]
You can import it as it is but take care of this #1173

**Comment by MobileAppVault** [comment]
Could you please give me the link to the documentation how to import html into grapejs?
