### ISSUE TITLE
[Question] Load basic block component fromElement

### ISSUE THREAD

**Issue by kickbk** [artf/grapesjs#1195]
I probably missed it somewhere in the docs but could not find it.
I'd like to a "form" block inside a "column" block on page load fromElement and also when clearing the canvas using editor.setComponent().
With mjml I would do `editor.setComponents('<mjml><mj-body><mj-container>...` but what's the equivalent with the webpage preset?

**Comment by artf** [comment]
The recognition of the component depends on this https://github.com/artf/grapesjs/wiki/Components#component-recognition 
So the "form", for example, is [recognized just be the tagName](https://github.com/artf/grapesjs-plugin-forms/blob/master/src/components.js#L166-L169) so you don't need to do anything else, but the "column" [it's not a component, its just an HTML block](https://github.com/artf/grapesjs-blocks-basic/blob/master/src/blocks.js#L107-L120).

When you need, you can strictly declare the component type in this way
```html
<div data-gjs-type="text">
	<span>Don't parse the inner span, just treat it as a text component</span>
</div>
```
