### ISSUE TITLE
[Bug] AssetManager not automatically opening in v0.14.20

### ISSUE THREAD

**Issue by WkRPcoN** [artf/grapesjs#1196]
Hi,

I recently updated grapesjs from v0.14.17 to 0.14.20 and found the Asset Manager no longer automatically opens when dragging an image from the Blocks Basic plugin or when dragging an custom block to the canvas.
I have ensured that activeOnRender is set to 1 on a custom block, and it appears the Image block in the Blocks basic plugin has the activeOnRender set by default.

My custom block:
```
m.add('orderSnippet2', {
      label: 'Image',
      category: 'Custom',
      attributes: {
        class:'fa fa-youtube-play'
      },
      content: { type: 'image', activeOnRender: 1 },
    })
```

Also the demo site no longer appears to be automatically opening the asset manager when dragging an image on the canvas also.

**Comment by ivanezeigbo** [comment]
Hi @artf, also in previous versions, earlier than v0.14.17, I was able to trigger the opening of the asset manager by setting "activeOnRender:1" for videos and removing the original src, this allows me to automatically set the src attribute by choosing a video or adding a URL, but when this is done on this earlier versions, the asset manager does not automatically open for videos when you set activeOnRender to 1 in the basic-blocks plugin or the webpage-plugin. Please advise.
