### ISSUE TITLE
QUESTIONS : Find element in Model

### ISSUE THREAD

**Issue by krunal039** [artf/grapesjs#1198]
I have custom component and it render below html, I want to update value of h4 tilte and other element on trait changed, but not sure how can I find h4 and other element in model (NOT in view) and change value via trait change. I have used below approach but does not want to access model via index.
`updateTitle : function updateTitle() {
                    var title = this.get('title');
                    var linkModel = this.get("components").at(0);
                    if (linkModel) {
                        var titleContainer = linkModel.get("components").at(3);
                        if (titleContainer) {
                            var h4 = titleContainer.get("components").at(0);
                            if (h4) {
                                h4.set("content", title);
                            }
                        }
                        linkModel.attributes.attributes["aria-label"] = title;
                        linkModel.attributes.attributes["title"] = title;
                    }
                    this.set("data-title", title);
                    if (this.get('isCreatePage') && this.changed && this.changed.title) {
                        this.set('isPageCreated', false);
                        this.set('bespokePageUrl', '');
                        this.updateIsCreatePage();
                    }
                }`

![image](https://user-images.githubusercontent.com/11716808/41340023-4902ed16-6eee-11e8-9f70-7332ada6c7ff.png)

**Comment by artf** [comment]
https://github.com/artf/grapesjs/issues/1157#issuecomment-397104559
