### ISSUE TITLE
[Question] : Can we remove links?

### ISSUE THREAD

**Issue by algodata44** [artf/grapesjs#1199]
I tried to add a button to remove links but i couldn't find a way.
I can add them in a text with the RTE button and edit them by double-clicking,
(with the help of https://github.com/artf/grapesjs/issues/610).
but I would like to know if i can have a button that remove the link without removing the text inside.

**Comment by cjpollard** [comment]
If you use the [CKEditor plugin](https://github.com/artf/grapesjs-plugin-ckeditor), that button's there.

**Comment by artf** [comment]
@algodata44 for the built-in RTE you need to [implement a new action](https://github.com/artf/grapesjs/wiki/API-Rich-Text-Editor#add) for that
