### ISSUE TITLE
more features

### ISSUE THREAD

**Issue by chuqingsheng** [artf/grapesjs#120]
I love your project! and It is OPEN SOURCE. very nice.
In China, A prototype tool have more power features. [https://modao.cc/](https://modao.cc/) . I suggest you can review those features. Maybe helpful. 
![image](https://user-images.githubusercontent.com/29627257/27430934-0c5bfba2-577d-11e7-80f3-ed6ba47d31ad.png)

**Comment by artf** [comment]
Thanks for your suggestion @chuqingsheng it's definitely a good resource for inspiration but I'd like to specify that, even if `Absolute/Designer mode` is in the [Roadmap](https://github.com/artf/grapesjs/issues/74) the main GrapesJS goal is to create valid templates. 
Basically, ALL prototype tools are strictly relying on absolute positioning (which is more friendly for designers), this means you can't use them with dynamic content and are not mobile ready (generally those tools create a totally different template to handle mobile devices).

Just want to point this out that I'm not building another "Sketch App", the main purpose of GrapesJS is different even though we're all trying to make this process easiest for people.
