### ISSUE TITLE
Create copy of import and export button inside block manager in form of accordian 

### ISSUE THREAD

**Issue by ashuomble5** [artf/grapesjs#1201]

**Comment by ashuomble5** [comment]
I want to create blocks button for import and export inside the block manager as separate accordion like this one.
![2018-06-13-17-15-localhost](https://user-images.githubusercontent.com/26411777/41349478-91677114-6f2d-11e8-8778-e8c67cb7a27e.png)

in block manager there will be 2 accordions first will contain all the blocks, second will contain import and export button.
Also is there any possibility to add style manager inside the block management as third accordion.

**Comment by ashuomble5** [comment]
I want to create blocks button for import and export inside the block manager as separate accordion like this one.
![2018-06-13-17-15-localhost](https://user-images.githubusercontent.com/26411777/41349478-91677114-6f2d-11e8-8778-e8c67cb7a27e.png)

in block manager there will be 2 accordions first will contain all the blocks, second will contain import and export button.
Also is there any possibility to add style manager inside the block management as third accordion.

**Comment by artf** [comment]
You can create customized panels like this one https://codepen.io/artf/full/MQpZPj
but for the rest, it's up to you, so just move it as you wish
```js
editor.on('load', () => {
	// move stuff
})
```
