### ISSUE TITLE
FEATURE REQUEST: Export as single HTML5 document

### ISSUE THREAD

**Issue by btxtiger** [artf/grapesjs#1203]
It would be really nice to have an option to export as a single HTML5 document, including html/head/body, and embedded css between `<head><style>{{css}}</style></head>`

**Comment by artf** [comment]
Look how the original [ExportTemplate](https://github.com/artf/grapesjs/blob/dev/src/commands/view/ExportTemplate.js) is done, then [add your own export command](https://github.com/artf/grapesjs/wiki/API-Commands#add)
