### ISSUE TITLE
create block for charts

### ISSUE THREAD

**Issue by ionic666** [artf/grapesjs#1205]
hi,First of all, I wish you a happy life.i have created a block for charts like:
![qq20180614-133204](https://user-images.githubusercontent.com/36065691/41393293-a2afbab2-6fd7-11e8-9453-6aa89020e6c8.png)

I don't know how to get chart from my block.Global variables are not available.
And i also want to modify configuration items for charts
![6a5cc63b-d10f-49cf-883c-f7b79b56d8ae](https://user-images.githubusercontent.com/36065691/41393395-2c11dc18-6fd8-11e8-9bd8-ffff5f018d05.png)

**Comment by artf** [comment]
> I don't know how to get chart from my block. Global variables are not available.

I don't understand what do you want to do

> And i also want to modify configuration items for charts

You can use changeProp to get the property value of your components

```js
content: {
	type: 'mycharts',
	xaxis: 100,
	traits: [{
		label: 'xAxis',
		// Use changeProp and assign the same 
		// name of the property to get its value
		changeProp: 1,
		name: 'xaxis',
	}]
}
```
