### ISSUE TITLE
Create minimalist Panel left sidebar III

### ISSUE THREAD

**Issue by ssabrewolf** [artf/grapesjs#1208]
hello @artf , thanks to you for the comment on #1188, i see in the code https://codepen.io/artf/full/MQpZPj/  uses   the appendTo property to render a filtered collection  of component  in a div with id  # block1 ,
is posible to render 2 different collections, 1 in block1 and another in block2, since the BlockManager only points to one single dom element, i tried to use  editor.BlockManager.render twice, the second time after changin editor.BlockManager.getConfig().appendTo  property but no luck it keeps changing the orignal block collection in block1, i mean, is possible to have 2 different blocks at the same time in 2 different divs one block with popular components  and another with the remaining ones
Regards

**Comment by artf** [comment]
@ssabrewolf as you get it right, BlockManager points only to one single DOM element, so you can't create 2 different collections, but you can definitely move elements around with plain javascript. You should do it once the content is rendered
```js
editor.on('load', () => {
	// move stuff
})
```
