### ISSUE TITLE
urlLoad problem

### ISSUE THREAD

**Issue by adaman93** [artf/grapesjs#121]
I'm trying to use the "remote" storageManager and when I put in my URL in there I get

?keys%5B%5D=gjs-assets&keys%5B%5D=gjs-css&keys%5B%5D=gjs-html as URL parameters

I assume that its not returning the right saved css/html because it is defaulting to the "gls" abbreviation when it hits that url, how I read the right html/css when I open up an existing created html page

Thanks!

**Comment by artf** [comment]
try to remove the prefix in this way:
```js
var editor = grapesjs.init({
    container : '#gjs',
    ...
    storageManager: {
      type: 'remote',
      ....
      id: '', // <- default is 'gjs-'
    }
});
```

**Comment by adaman93** [comment]
I think I asked my question wrong

My question is how do I load the previous saved css/html when I open it up again?

and how do I replace "gjs-css" with my saved css/etc.?

**Comment by artf** [comment]
@adaman93 once you've setup the storage the editor tries to load it by itself, but you can do it manually if you want to:
```js
var editor = grapesjs.init({
    container : '#gjs',
    ...
    storageManager: {
      autoload: 0
    },
});

editor.load();
```
You need `storageManager.id` option just to prevent collisions, so if it's not your case just set it as an empty string, in this way the editor will always pass clean params like `html`, `style`, `components`, etc. and will expect the same on loading (so your endpoint have to return `html`, `style`, etc.)
