### ISSUE TITLE
Query for issue related to 873

### ISSUE THREAD

**Issue by kuldeepcis** [artf/grapesjs#1214]
[`Previous issue`](https://github.com/artf/grapesjs/issues/873)

Please confirm, above reported bug has been resolved. Or still having same issue. Please confirm .
Same issue with slider also.

Thanks in advance

**Comment by v8jupiter** [comment]
Please confirm, above reported bug has been resolved. - 100% resolved.

**Comment by kuldeepcis** [comment]
But still I'm facing same issue on latest version 14.20

**Comment by artf** [comment]
@kuldeepcis provide a live demo
