### ISSUE TITLE
Can't drag blocks

### ISSUE THREAD

**Issue by algodata44** [artf/grapesjs#1221]
Hello,
when I use grapesjs (with gjs-preset-webpage or gjs-preset-newsletter) I sometimes have a weird bug. I can't drag the blocks on the right, they don't move when i click on them.
Sometimes, even reload the page isn't sufficient.
We witnessed this bug with Mozilla and Safari but not with Google Chrome.
Did someone already have this bug?

**Comment by artf** [comment]
Hi @algodata44, do you use the latest version? Any error in console? Honestly, I don't face any issue with other browsers so can't actually help you here. You should at least provide a live demo with steps on how to reproduce the issue.
