### ISSUE TITLE
Specify the content and type for block

### ISSUE THREAD

**Issue by ionic666** [artf/grapesjs#1225]
when i just set the content like this:
![qq20180621-110517](https://user-images.githubusercontent.com/36065691/41695788-259d80ec-7543-11e8-93f9-778f14c2ec8c.png)Everything is all right.
But when I also specify the type,
![qq20180621-110508](https://user-images.githubusercontent.com/36065691/41695816-48f1500a-7543-11e8-9703-22f6cc9496cd.png)
there will be a extra label.can you help me?

**Comment by artf** [comment]
Add the type via attribute `data-gjs-type="input_box"`
