### ISSUE TITLE
Specifying tooltips

### ISSUE THREAD

**Issue by DavidSporer** [artf/grapesjs#1226]
Hi,

I've tried finding information about it in both the code as well as existing issues but either I looked for the wrong information or it's not there, yet.
I'd like to specify tooltips for e.g. the Style Manager - how can I do that?
I've noticed that in the newsletter presets there are less tooltips than in the website presets so I guess there must be a way to do it.
Could you please give me a hint?

Thanks,
David

**Comment by cjpollard** [comment]
If you search for tooltips in the [demo html](https://github.com/artf/grapesjs/blob/gh-pages/demo.html), the code's there.
