### ISSUE TITLE
Can't reset CSS code which has parent or child. 

### ISSUE THREAD

**Issue by ronaldaug** [artf/grapesjs#1228]
Tested on both **npm** and **cdn**
**GJS Version** - 0.14.20 (latest)
**OS** - Mac
**Browser** - Chrome

**Problem**
If CSS class name has a parent or child like `#parent .child{ color: red }`,  user can't reset the style to origin, it still remain inside CodeViewer. 

[Codepen Demo 1 - Adding CSS from block](https://codepen.io/ronaldaug/pen/Paadqd 
)
[Codepen Demo 2 - Adding CSS inside `#gjs <div>` ](https://codepen.io/ronaldaug/pen/yEExoe)

In demo1, Let's say user drag "Test Block" into the canvas and remove it. CSS style will still remains inside the CodeViewer. Even user clear the canvas, it will not be removed. 

I am not sure this is a bug or not. 
But in most case, we used to declare CSS selectors including parents not for ruining the other sections' styles.

**Comment by artf** [comment]
This is because you're just clearing components. You can use the built-in command `core:canvas-clear`

**Comment by ronaldaug** [comment]
@artf Thanks for your quick reply.

Sorry for my unclear question.

What I actually want to achieve is
- To remove the CSS codes that belong to a specific block.
For example, when I delete a block in the canvas, the CSS codes of that block will also be deleted.
I don't want to clear the entire canvas.

Probably, it will fire on destroy.
`editor.Commands.add ('tlb-delete', e => {`
   `// remove the CSS from this block`
`})`

In this case, I can remove the CSS code that has no parent by deleting the components but if the CSS codes have a parent or a child, it does not work.

[Codepen demo](https://codepen.io/ronaldaug/pen/Paadqd)
 
And here is a video I've tested.
[![Alt text for your video](https://pbs.twimg.com/media/DTIgRSrWsAUn0BW.jpg)](https://youtu.be/176jGzeRrXw)

Thanks in advance.

**Comment by artf** [comment]
> To remove the CSS codes that belong to a specific block.

Indeed that block of CSS doesn't belong to any component (I'm talking about how the editor works) so that declaration is always rendered. GrapesJS can associate only class-based selectors, eg.
```css
.class1 {...}
.class1.class2 {...}
.class1.class2, .class3 {...}
```
not even nested like `.class1 .class2`, in that case the rule is imported correctly but do not belong to any component
