### ISSUE TITLE
[Question]: Doctype in the canvas iframe

### ISSUE THREAD

**Issue by pintor-mato** [artf/grapesjs#1230]
Hey @artf, I noticed the canvas iframe doesn't appear to have any doctype set on it, which causes it to be in quirks mode. Is this intentional? I'd like to set it to <!DOCTYPE html>, but doing so causes some positioning issues that you can see in this [screenshot](https://i.imgur.com/Ga3mLKx.png) and [demo](https://jsfiddle.net/xu7fdxnj/1/).

Would you be open to a pull request that would allow the doctype to get set? I feel like exposing this in a config option (either a doctype string or perhaps a quirksMode boolean) would be the safest thing to do, but would like to get your thoughts before I continue exploring this.

**Comment by artf** [comment]
> which causes it to be in quirks mode
Which browser?

**Comment by tomichal** [comment]
@artf One issue I noticed with the lack of doctype is with HEX color definitions.
If a user defines a HEX color as, e.g.: "fff", rather than "#fff", this will work in the editor, but once the page is rendered inside a HTML with doctype specified, that "fff" color definition fails.

**Comment by artf** [comment]
@tomichal it's nothing to do with the doctype, `fff` it's just not an HEX, it works because of the color picker, nothing more.
BTW I think it's awful still talking about 'quirks mode' in 2018
