### ISSUE TITLE
How to change the margin from px to rem

### ISSUE THREAD

**Issue by Deepak813** [artf/grapesjs#1232]
Hi @artf,

Hope you are doing fine.

I have changed the margin settings from "px" to "rem" in one of the element using below code:

    {
    property : 'margin-top',
    name: 'Top Margin', 
    units : ['rem'], 
    type: 'integer', 
    }
but when i re-assign the same margin setting to element after save then its multiplies the margin with 16x px i.e means the "rem" is converted into "px" and element gets disapper.

Please let us know how we can change the "px" settings to "rem" settings in all the elements of the grapesJs.

Hope for the positive response.
Thanks Artf.

**Comment by artf** [comment]
Please @Deepak813... follow the template of the issue, provide a demo and steps to reproduce
