### ISSUE TITLE
Template Problems with GrapesJS

### ISSUE THREAD

**Issue by ivanezeigbo** [artf/grapesjs#1234]
1. Some templates just don't load well. Very simple templates do load properly, but there seems to be a problem with templates with more functions and css. For example, loading a template like [this](http://webbuild.jenezys.com/templates/free_templates/aerial/index.html) would generate some problems. First, the animation fade in of the letters would not occur. Once inside the #gjs div tags, the template gets stuck in the initial loading and does not completely load even with allowScripts. And it has only two css files linked and a simple js code. If the texts and icons happen to load by chance at some point, hovering over them makes them disappear again because there is a hover function attached to them. You may also check out [this other template](http://webbuild.jenezys.com/templates/free_templates/Kreo10/index.html), which is more complicated. The editor just gets stuck at the loader and would not be able to show the rest of the content. So it becomes impossible to edit such templates. 

2. Also, is it possible to have an "unlink" tooltip or something that allows us to unlink images that are linked? One cannot simply carry the image out of the link block like you can do with the editor's link block. So perhaps, this would allow one to delete the <a> tags surrounding the image given that the editor may not recognize this as a link block.

**Comment by ivanezeigbo** [comment]
@artf I don't understand. You tagged this as invalid.

**Comment by artf** [comment]
Follow the issue template please and always write ONE problem/question/bug per issue
