### ISSUE TITLE
Line-Height not working from typography section when we copied from MSWord

### ISSUE THREAD

**Issue by NorthstarTech** [artf/grapesjs#1235]
When we copy a text from word and then change the Line-height from Typography, it doesnot change it. How Can I change the Line-height of the text that is copied from word or pdf.

This issue also occurs in the demo. Please help me and provide me the solution asap.
Thanks
![2018-06-25_16-00-52](https://user-images.githubusercontent.com/33541046/41846723-1228194a-7891-11e8-9282-1c3ca099aaf5.png)

**Comment by artf** [comment]
You have to paste plain text instead of the formatted one copied from Word, use <kbd>Ctrl</kbd> + <kbd>⇧ (shift)</kbd> + <kbd>V</kbd>
