### ISSUE TITLE
Before you drag and drop the image,there was nothing in assetManager

### ISSUE THREAD

**Issue by ionic666** [artf/grapesjs#1237]
![qq20180626-104503](https://user-images.githubusercontent.com/36065691/41886286-4fb16508-792e-11e8-9703-d714cba49163.png)
and I don't know how to set the backgroundImage

**Comment by ronaldaug** [comment]
@ionic666 you can read Asset API documentation [here](https://github.com/artf/grapesjs/wiki/API-Asset-Manager
)
There is no image in your asset manager.  It seems you haven't added it yet.
You can add like this..
```
grapesjs.init({
....
.....
 assetManager: {
          assets: [
                  {
                  type: 'image',
                  src: 'http://via.placeholder.com/250x350/0174DF/ffffff/',
                  date: '2018-06-28',
                  height: 350,
                  width: 250
                    },
                  {
                  type: 'image',
                  src: 'http://via.placeholder.com/250x350/5FB404/ffffff/',
                  date: '2018-06-28',
                  height: 350,
                  width: 250
                    }
            ]
          }
....
....
})
```

**Comment by ionic666** [comment]
@ronaldaug 
![tim 20180628171659](https://user-images.githubusercontent.com/36065691/42025436-22b755b0-7af7-11e8-92e0-18d2a43fb659.png)
i have done it.but I mean that if i haven't drag the image component,I cannot set background images for other components

**Comment by ronaldaug** [comment]
Maybe, you didn't add the component **type** as **image**. Make sure you add it.
And you can just double click on the image to trigger the assets images box.

Could you share your codes via codepen or jsfiddle?

Do you mean [this official demo](https://grapesjs.com/demo.html) ?
I can see the images under **Flex is the new black** section do not work. It's because the images were added via CSS codes.

**Comment by ionic666** [comment]
i am sorry.i have the component for image.
when i use the component for image,there will be ok.
but i just want to change the background-image for div which id is wrapper before i open the assets.

**Comment by artf** [comment]
@ionic666 you can change the background-image from the style manager.
And again @ionic666 you **HAVE TO** follow the issue template otherwise you're making us waste our time to understand what you asking
