### ISSUE TITLE
#ISSUE: EDITOR IS NOT LOADING IN  SAFARI BROWSER

### ISSUE THREAD

**Issue by Abhisheknanda1344463** [artf/grapesjs#1238]
hi @artf  I am facing problem i use safari browser and grapesjs is not loading in safari browser and in console there is no errrors except 3 4 warnings thanks in advance

**Comment by ivanezeigbo** [comment]
@Abhisheknanda1344463 this [link](https://blog.webnersolutions.com/grapejs-not-working-in-safari-and-local-storage-problem) might help.

**Comment by Abhisheknanda1344463** [comment]
@ivanezeigbo Thanks for your's suggestion bro Problem is the version of safari i updated it to 11.1.1 and it works :)

**Comment by artf** [comment]
Next time @Abhisheknanda1344463 
* Follow the issue template
* Don't write in uppercase
* Close the issue if it's solved
