### ISSUE TITLE
How to make settings text multi-lingual

### ISSUE THREAD

**Issue by Deepak813** [artf/grapesjs#1239]
Hi @artf,

We have integrated the each element settings with their elements name using below code like HEADLINE SETTINGS, COLUMN SETTINGS and so on...

/* Headline Settings */
                              {
                                  name : 'Headline Settings',
                                  open: true,
                                  buildProps: ['background-color',  'color', 'text-align', 'font-family','font-weight', 'font-size', 'letter-spacing', 'line-height', 'width','margin-top', 'margin-left', 'padding-top', 'padding-left', 'padding-right', 'padding-bottom'],
                                  properties:[     
                                                {
                                                  name : 'Text Align',
                                                  property: 'text-align',
                                                  type: 'radio',
                                                  defaults: 'center',
                                                  list: [
                                                          { value : 'left',  name : 'Left',    className: 'fa fa-align-left'},
                                                          { value : 'center',  name : 'Center',  className: 'fa fa-align-center' },
                                                          { value : 'right',   name : 'Right',   className: 'fa fa-align-right'},
                                                          { value : 'justify', name : 'Justify',   className: 'fa fa-align-justify'}
                                                      ],
                                                },

So how we can make these name multi-lingual.I reference through all the discussions regarding the multi-lingual but found no results so can you please let us know how we can achieve this.

**Comment by artf** [comment]
You just have to set the already translated string
```js
name: i18n[locale]['headlineSettings'],
```
