### ISSUE TITLE
On the carousel of pictures and animation editor

### ISSUE THREAD

**Issue by dreamhuo** [artf/grapesjs#124]
Hello, dear master,
On the carousel of pictures and animation editor
What time can support

**Comment by dreamhuo** [comment]
https://daneden.github.io/animate.css/
I want to put the animate.css into the grapesjs editor, But I don't know how to do

**Comment by artf** [comment]
Unfortunately, have no plans for carousel or animation editor.
About the animate.css, something like this should work
```html
<div id="gjs">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css"/>
  <h1 class="animated bounce infinite">Example</h1>
  <style>.txt-red{color: red}</style>
</div>

<script type="text/javascript">
  var editor = grapesjs.init({
      container : '#gjs',
      fromElement: true,
  });
</script>
```

**Comment by dreamhuo** [comment]
thanks very much @artf
