### ISSUE TITLE
#UI - DISORTED IN TABLET MODE

### ISSUE THREAD

**Issue by Abhisheknanda1344463** [artf/grapesjs#1240]
hi @artf  UI is getting disorted in safari browser when we drag any element in desktop mode after that move to tablet mode than vertical lines are appears on the screen as you can see my screenshot attached Please let me know how to fix this Thanks in advance @artf 
![screen shot 2018-06-26 at 5 29 43 pm](https://user-images.githubusercontent.com/20657737/41910415-349f5e12-7967-11e8-8749-0dc5d1b507b9.png)

**Comment by ronaldaug** [comment]
@Abhisheknanda1344463 
Tested on Safari Version 11.1.1
Nothing happen here.

<img width="1154" alt="screen shot 2018-06-28 at 3 58 34 pm" src="https://user-images.githubusercontent.com/33022876/42025995-ffbb0eae-7aeb-11e8-8055-18026c65993e.png">

**Comment by Abhisheknanda1344463** [comment]
@ronaldaug 
please Change preview mode on after another in repeated times like mobile to Desktop, mobile to tab, Desktop to tab than it'll appears sometimes and Please let me know if you observe anything.Thanks in advance @ronaldaug

**Comment by ronaldaug** [comment]
No @Abhisheknanda1344463 ,
I add blocks and change the preview mode for many times.
And also I've even tried with safari sidebar as your first screenshot. 
No distorted lines are appeared.
 
Could you provide your OS version and Browser version? 
Probably, the error comes from your device or browser.

**Comment by Abhisheknanda1344463** [comment]
okie @ronaldaug  My OS version is OS X EI Capitan (10.11.6)
 and Safari browser version is 11.1.1
It's still showing.

**Comment by Abhisheknanda1344463** [comment]
@ronaldaug  Is Your's OS version is Same as Mine? Please let me know how can i fix this

**Comment by ronaldaug** [comment]
Yea, OS and browser version are exactly the same. 
I have no idea why it doesn't work at yours.

Currently, I can just proof you with a screen recording, check this out.
https://www.youtube.com/watch?v=UsZ6xl86gOU

Make sure you clear browser cache and uninstall some safari extensions.

**Comment by artf** [comment]
@Abhisheknanda1344463 it's definitely something wrong on your side with the browser rendering, seems like it doesn't update some pixels when the animation is performed. Try to restart your computer.
I'm using the same OS but with even older Safari and nothing strange happens
