### ISSUE TITLE
[FEATURE REQUEST]: JSON to HTML parsing

### ISSUE THREAD

**Issue by saravanan-palani** [artf/grapesjs#1242]
Is there any support for JSON to HTML rendering, so that we can get control over the content to be published in the newsletter or webpage. Rather than rendering direct HTML in the editor.

**Comment by Jogai** [comment]
You can put all your separate pieces of content in the blockmanager making it ready to be dragged in a template.

**Comment by artf** [comment]
Instead of
```js
blockManager.add('new block', {
  label: 'My label',
  content: '<section data-attr="some-value"><h1>Hello!<h1></section>',
})
```
You can do this
```js
blockManager.add('new block', {
  label: 'My label',
  content: {
	tagName: 'section',
	attributes: { 'data-attr': 'some-value' },
	components: [{
		tagName: 'h1',
		content: 'Hello!',
	}]
  },
})
```
