### ISSUE TITLE
Conflict on use of grapesjs social plugin

### ISSUE THREAD

**Issue by kuldeepcis** [artf/grapesjs#1244]
Hi @artf 

I'm using grapesjs with grapesjs social plugin, after using this plugin some conflicts generated in the system.
Social plugin option show with babbar and also change the design of tab.
![1530183577657-1686932218](https://user-images.githubusercontent.com/16045467/42030470-83baef72-7af0-11e8-8b61-31d871e00d62.jpg)

Please check code on fiddle;:
[Click here to check](https://jsfiddle.net/5neqrt0o/6)

**Comment by artf** [comment]
Wrong repository
