### ISSUE TITLE
[Question] How to preserve the Id attribute with toHTML

### ISSUE THREAD

**Issue by Jogai** [artf/grapesjs#1246]
The changelog states

> Added the possibility to output custom attributes in toHTML method

How do we use this feature? I cant find the corresponding issues, or any info on the options for the toHTML method in the wiki.

I used this function in 0.14.20 and earlier to post the html to the server and do some more processing on the html & css, but now the id's are not in the html anymore. I like to set it to preserve classes and id's.

**Comment by artf** [comment]
> but now the id's are not in the html anymore

Can you explain better your case because this new feature shouldn't change the previous behavior.

BTW to explain this new option let's take for example a component that on `component.toHTML()` returns this:
```html
<section id="some-id">
	<h1>Hello!</h1>
</section>
```
So now, for example, you can do this:
```js
component.toHTML({
	attributes(component, attr) {
		if (attr.id == 'some-id') {
			attr['some-attr'] = 'some-value';
		} else if (component.get('tagName') == 'h1') {
			attr.class = 'h1';
		}
		return attr;
	},
});
```
to return
```html
<section id="some-id" some-attr="some-value">
	<h1 class="h1">Hello!</h1>
</section>
```

**Comment by Jogai** [comment]
You're probably right. It's not this feature that's changed that behavior. 

My test case:

Template:

```
<head>
    <meta charset="utf-8">
	<style>div{margin:0 auto;}</style>
</head>
<div style="width:500px; border:2px solid black;">
	<div style="width:400px;height:400px; border:2px solid red;">
	</div>                     
	<div style="width:300px;height:300px; border:2px solid green;">
	</div>                    
	<div style="width:200px;height:200px; border:2px solid blue;">
	</div>
</div>
```

Version 0.14.21 html output (from grapesjs.com/demo.html):
```
<meta charset="utf-8"/>
<div class="c3945">
  <div>
  </div>
  <div>
  </div>
  <div>
  </div>
</div>
```
Version 0.14.21 html output
```
* {
  box-sizing: border-box;
}
body {
  margin: 0;
}
#iht0ek{
  width:400px;
  height:400px;
  border:2px solid red;
}
#i9ry44{
  width:300px;
  height:300px;
  border:2px solid green;
}
#igqj8h{
  width:200px;
  height:200px;
  border:2px solid blue;
}
div{
  margin-top:0px;
  margin-right:auto;
  margin-bottom:0px;
  margin-left:auto;
}
.c3945{
  width:500px;
  border:2px solid black;
}
```
The css have the proper id's, but the html doesn't have them.

In my local environment is still on 0.14.20 and the output is including the id's in both html & css:

HTML:
```
<meta charset="utf-8"/>
<div id="izai">
   <div id="iupd"></div>
   <div id="invg"></div>
   <div id="itzz"></div>
</div>
```

CSS
```
* {
     box-sizing: border-box;
}
 body {
    margin: 0;
}
#izai{
    width:500px;
    border:2px solid black;
}
#iupd{
    width:400px;
    height:400px;
    border:2px solid red;
}
#invg{
    width:300px;
    height:300px;
    border:2px solid green;
}
#itzz{
    width:200px;
    height:200px;
    border:2px solid blue;
}
div{
    margin-top:0px;
    margin-right:auto;
    margin-bottom:0px;
    margin-left:auto;
}
```

**Comment by artf** [comment]
Thanks @Jogai, you're actually right, there is bug (will be fixed for the next release), but I'd like to suggest to try this option which should also correct the current behaviour:
```js
grapesjs.init({
	...
	// Usually when you update the `style` of the component this changes the
  	// element's `style` attribute. Unfortunately, inline styling doesn't allow
  	// use of media queries (@media) or even pseudo selectors (eg. :hover).
  	// When `avoidInlineStyle` is true all styles are inserted inside the css rule
	avoidInlineStyle: true,
})
```
One day or another, probably, this will be `true` by default, as without it you can't style single component on different devices or in different states (eg. :hover)

**Comment by Jogai** [comment]
Thank you for looking into it. I'm looking forward to the update (as always, i'm very thankful for this project). 

Avoiding inline styles is not an option for us (yet). Our templates heavily use inline styles, and with the option set to true, those are completely ignored (I load my template from an element).

**Comment by artf** [comment]
> Our templates heavily use inline styles, and with the option set to true, those are completely ignored (I load my template from an element)

But wait, all the things just change internally, the import you do right now is always the same... can you provide a live example of your issue?

**Comment by Jogai** [comment]
0.14.23 fixes my original problem. Thanks!

If I set the following options:

            fromElement: 1,
            height: "1050px",
            container: '#gjs',
            forceClass: false,
            storageManager: { type: 'none' },
            plugins: p,
            avoidInlineStyle: true,

My template is imported without the inline styles. But thats not a problem for me if I leave avoidInlineStyle out.

**Comment by artf** [comment]
> My template is imported without the inline styles. But thats not a problem for me if I leave avoidInlineStyle out.

It works exactly the same... https://jsfiddle.net/szLp8h4n/245/ so check if it's something wrong on your side, because as I said one day or another that will be the default behaviour
