### ISSUE TITLE
Text disappear after creating a new type

### ISSUE THREAD

**Issue by algodata44** [artf/grapesjs#1247]
Hello!

I am creating a new block that will open a modal during the creation (drag and drop
https://github.com/artf/grapesjs/issues/174 really helped me and it works.

But it had a surprising side-effect: When I select and deselect a text component, the text disappear.
Here is the code, I think I changed the defaultType property unintentionally:

 ```
var defaultType = editor.DomComponents.getType('default');
		editor.DomComponents.addType('importType', {
		 		model: defaultType.model.extend({
		 				isComponent: function(el){
		 					if(el.tagName == 'IMPORTTYPE'){
		 						return {type: 'importType'};
		 					}
		 				},
		 		}),
		view: defaultType.view.extend({
		     init() {
		       this.listenTo(this.model, 'active', this.doStuff); // listen for active event
		     },
		     doStuff() {...}
		  }),
		});

```

**Comment by artf** [comment]
Wrong position for `isComponent`, it should be passed in the second argument object
```js
defaultType.model.extend({
	isComponent //<- wrong
}, {
	isComponent //<- correct
})
```
So it's like not declaring it, and as mentioned in [Components](https://github.com/artf/grapesjs/wiki/Components)

> As you're putting a new Component type on top of the stack, not declaring isComponent() might probably break stuff, especially if you extend the default one.

**Comment by algodata44** [comment]
It works perfectly, thank you!
