### ISSUE TITLE
[Question] Issue running on Cloud9

### ISSUE THREAD

**Issue by gregvissing** [artf/grapesjs#1249]
I'm trying to run this on Cloud9 but when I go to run it using the 'npm start' command it gives me the url of http://localhost:8080/ when I need it to follow the following format: https://app-name-username.c9users.io/. What do I need to update to achieve this?

**Comment by Owchzzz** [comment]
use process.env.HOST and process.env.PORT inside of the webpack dev server configurations

**Comment by artf** [comment]
And as the last command of `npm start` is webpack dev server you can pass them in this way
`npm start -- --host XXX --port 80`
