### ISSUE TITLE
Limit Grape Scope

### ISSUE THREAD

**Issue by chrisbarton126** [artf/grapesjs#125]
Firstly, GrapesJS looks absolutely fantastic and seems to be exactly what I am after! I do have a question as it is unclear through the documentation as to whether it is supported or not, but is it possible to limit the scope of the editor so that only certain elements are editable (i.e. div's with a certain class)? I work in a modular environment where there are modules which are not editable, however there are others that are editable; so allowing the user to edit content and add items only within certain areas would be a massive plus as it would allow a single editor to be present on the page. 

If this is not feasible, then I have managed to get an example working with multiple editors on the same page, however this means that the editor becomes rather condensed, this being the case are there any plans to offer alternative orientations for the toolbar?

**Comment by artf** [comment]
Hi @chrisbarton126 you can create components, directly in blocks, with model properties which can be used for limiting your scope (more info [here](https://github.com/artf/grapesjs/wiki/Blocks)), for instance, you can create something like this:
```js
blockManager.add('the-row-block', {
  label: 'Example block',
  content: `<div>
<div data-gjs-editable="false">Not editable</div>
<div data-gjs-draggable="false">Not draggable</div>
<div data-gjs-removable="false">Not removable</div>
</div>`,
});
```
Can you explain better which is your issue with the toolbar (maybe some screenshots)?

**Comment by chrisbarton126** [comment]
Hi @artf thanks for the quick response. My aim is to have a page with many elements on, but only for certain elements to be editable. So ultimately the editing would need to be disabled for the entire page, except for certain elements within. The editor would be instantiated using `fromElement: true` so that the editor picks up the entire page, but upon saving would need to be able to identify each editable element and post its data back to the server individually. Do you think this would be feasible with GrapesJS, or is the use-case perhaps a little too abstract from the original intentions of the project?

I have attempted to use the data attributes you provided, however this means the attributes would need to be specified on every element on the page, except for those that would need to be editable. I did try applying the attributes to the body of the page and then applying them again to the editable elements but with the property values inverted, however this did not work as expected. 

With regards my alternative which would be to have multiple editors on the page (one for each editable element), the screenshot below illustrates what happens when you instantiate the editor on a specific container which is not the full width of the page:

![image](https://user-images.githubusercontent.com/2964041/27624982-d91e2ea6-5bda-11e7-8229-51728e06319d.png)

**Comment by artf** [comment]
First of all, you can use model properties with the starting template, so something like this should work:
```html
<div id="gjs">
  <div class="txt-red" data-gjs-editable="false">Hello world!</div>
  <style>.txt-red{color: red}</style>
</div>

<script type="text/javascript">
  var editor = grapesjs.init({
      container : '#gjs',
      fromElement: true,
  });
</script>
```
Once the component is imported inside the editor the attribute is replaced with the model property, therefore you won't see it in the final HTML (eg. with `editor.getHtml()`) but inside the model (`editor. getComponents()`). You're also able to pass component models on store:
```js
var editor = grapesjs.init({
   ...
   storageManager: {
     ...
     storeComponents: true, 
   }
  });
```
About the layout issue you should be able to solve it with some custom CSS.

I didn't get exactly what you've tried to achieve, can you post some code snippet?

**Comment by mhsdts** [comment]
i have an existing theme i just want  to make user be able to style only header and footer of the theme and then store it in json object

**Comment by sathishstar** [comment]
@mhsdts 

Use 

`canvas: {}`
