### ISSUE TITLE
Countdown type "datetime-local" not working in Mozilla Browser

### ISSUE THREAD

**Issue by Deepak813** [artf/grapesjs#1250]
Hi @artf,

Hope you are doing fine.

Few days back i have asked question from you in reference #750 regarding how to set timezone in countdown element and you said we can use its different options so i have used "datetime-local" to show time but its not working in mozilla browser.please let us know how we can resolve this:

![countdown](https://user-images.githubusercontent.com/33951403/42122025-e14bcdaa-7c58-11e8-8c21-807846da626b.png)

Help Us to resolve this.
Thanks in Advance.

**Comment by artf** [comment]
1. The countdown is a plugin, so you should open all the relative issues here https://github.com/artf/grapesjs-component-countdown ... already told you [here](https://github.com/artf/grapesjs/issues/750#issuecomment-357432893)
2. Just create a [custom trait](https://github.com/artf/grapesjs/wiki/Traits) (eg. by using some date picker) and use it inside the plugin `dateInputType: 'your-date-picker'`
