### ISSUE TITLE
grapesjs IE 11 Not showing webpage

### ISSUE THREAD

**Issue by bhavinshiroya1994** [artf/grapesjs#1253]
Hello

i'm use grapesjs in creating webpage, works perfectly chrome browser but not showing grepesjs webpage on IE 11

please let me know how to solve this problem.

**Comment by brutalnoise** [comment]
Array.from is not supported in Internet Explorer. You can add the code, which is in the polyfill section of this page in yours.
[developer.mozilla.com](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/from)

**Comment by artf** [comment]
@bhavinshiroya1994 thanks for the report, this will be fixed for the next release
