### ISSUE TITLE
Style is not copying after cloning the element after Save

### ISSUE THREAD

**Issue by YashPrince** [artf/grapesjs#1258]
Hi @artf.
At the first time before saving the template, When I make one element and clone it, the style is coming in the clonned element. That is running fine.
But when I save the template using Ajax and Call the below code:-
   ```
 const LandingPage = {
        html: editor.getHtml(),
        css: editor.getCss(),
        components: null,
        style: null,
      };
        $.ajax({
            type: "POST",
            url: BASE_API_URLss+"/api/addTemplateBuilder",
            headers: {
                'Authorization' : "Bearer " + this.userJson.token
            },
            data: {
                content: LandingPage.html,
                css: LandingPage.css, 
             
            },
            beforeSend: function() 
            {
                $('.save_template_btn').addClass('loading');
            },
            success: function(response)
            {
                editor.setComponents(response.content);
                editor.setStyle(response.css);
         
            },
            error: function(jqXHR, textStatus, errorThrown) 
            { 
               
            }
        });


```
and then clone the elements, their styling does not applies to the cloned elements.
If I comment the editor.setComponents(response.content); and  editor.setStyle(response.css); in success
function then styling applies to the cloned elements but still does not style applies to the cloned elements after page refresh after save as  editor.setComponents(response.content); and  editor.setStyle(response.css); on page load and editor init .
![clonederror](https://user-images.githubusercontent.com/40828744/42276836-dcaa2b9a-7fb2-11e8-80e5-e96825d7dc25.png)

Thanks for help in advance

**Comment by artf** [comment]
Follow the issue template and provide a live demo
