### ISSUE TITLE
Toolbar and Actionbar Postion

### ISSUE THREAD

**Issue by YashPrince** [artf/grapesjs#1259]
Hi @artf.

How can I update position of Toolbar and Actionbar as it override the each other and toolbar also
hide the highlighter text like Menu Item. I just want to know is there any option for set top, right, left 
bottom postion for Toolbar and Actionbar.

![navigationissue](https://user-images.githubusercontent.com/40828744/42284314-ca05b2d6-7fc9-11e8-8aca-9b6dd9679e4d.png)

Thanks for help in advance

**Comment by artf** [comment]
Check this for the RTE toolbar https://github.com/artf/grapesjs/wiki/Replace-Rich-Text-Editor#toolbar-position
For the component toolbar there are no options for the positioning
