### ISSUE TITLE
Grapes.js instructions fail for users without eslint

### ISSUE THREAD

**Issue by kkinder** [artf/grapesjs#126]
Probably eslint should be included as a dev dependency.

**Comment by kkinder** [comment]
Also, since the project has no eslint configuration anyway, a user has to create one, which may or may not be compatible with the project's coding standards.

**Comment by artf** [comment]
thanks @kkinder didn't notice it. Anyway, I don't get if you suggest to include .eslintrc

**Comment by kkinder** [comment]
I would include .eslintrc, since if you choose some of the defaults (eg, Google), eslint comes up with all kinds of warnings.
