### ISSUE TITLE
How to upload image using jQuery within WordPress using assets manager.

### ISSUE THREAD

**Issue by JPPreusDev** [artf/grapesjs#1264]
This is the code that I have:

assetManager: {
    uploadFile: (e) => {
        jQuery.post(
            ajaxurl,
            {
                ......
            }
        );
    }
}

But when I drop the image inside of the drop area, it does not trigger the jQuery post function. can you please help guide me with what I am doing wrong?

**Comment by artf** [comment]
https://github.com/artf/grapesjs/wiki/Assets#uploading-assets
