### ISSUE TITLE
how to use php functions inside of editor iframe ???

### ISSUE THREAD

**Issue by roufriyas** [artf/grapesjs#1265]
Hi @artf,
currently i am working on php,wordpress and grapesjs.What I wanted here is..,
how can I add the php functions inside the iframe of the editor??? this is for getting the things same as that of wordpress used..! and is that possible, if i add something(wordpress styles) outside of the editor and that affects inside of the canvas??

**Comment by artf** [comment]
Hi @roufriyas you can use PHP to render templates dynamically but it doesn't make sense use PHP functions inside the iframe (probably only as a variable placeholder). I'd recommend asking such a question in some WP related forum
