### ISSUE TITLE
Could not load updates images in the assetmanager

### ISSUE THREAD

**Issue by kuldeepcis** [artf/grapesjs#1266]
We are saving the components to the MySQL database .So when we load the components we don't get updated value for example in asset manager the images present in it are 4 and we add one image and save it then whenever we edit the image we see only those 4 images even we have uploaded many images after that to asset manager this happens because we load components from the database.

**Comment by artf** [comment]
Assets have nothing to do with components, you have to store them too.
https://github.com/artf/grapesjs/wiki/Assets
