### ISSUE TITLE
Form component is not available?

### ISSUE THREAD

**Issue by ajstharsan-radus28** [artf/grapesjs#127]
I have cloned this repo (artf/grapesjs). When opening using /index.html of the editor I cannot see forms sections under the Blocks Menu which is anyway shown in demo. Is it something missing in my setup or the repo doesn't have it? Because I checked /src folder, but couldn't figure out a model for Form components.

**Comment by artf** [comment]
Form components come from the plugin https://github.com/artf/grapesjs-plugin-forms
