### ISSUE TITLE
Feature request: Asset manager more suitable for large amount of images

### ISSUE THREAD

**Issue by johnknoop** [artf/grapesjs#1273]
The asset manager window is kinda tiny. If you're selecting from thousands of product images, the user experience becomes quite limited. It would be great if you could increase the size of the window, and also support basic filtering of images using a textbox.

**Comment by artf** [comment]
For the size of the window, I think it's just a matter of adding some CSS. For the basic filtering, it's a bit different, you can do it by yourself actually (create the element, on change filter rendered assets and, for example, append the search element every time you call the asset manager) but we had thought about adding a more generic behavior on all collections #498
