### ISSUE TITLE
Remote storage option is not sending in $_POST the JSON structure

### ISSUE THREAD

**Issue by jvillena** [artf/grapesjs#1274]
Hi @artf! 
I'm working to adapt your content builder in our system using the latest release v.0.14.21. I have set up the following configuration of the StorageManager:
storageManager: {
        type: 'remote',
        stepsBeforeSave: 1,
        autoload: true,
        autosave: false,
        urlStore: '/save',
        urlLoad: '/load',
        contentTypeJson: true
    },

With contentTypeJson = true I can load the content correctly from load action. Also I created a new button to save the content manually using the call "editor.store()". The problem comes up now in the action save I never receive in $_POST the json structure with HTML, COMPONENTS, ASSETS, ... If I switch off the parameter contentTypeJson: false then I'm able to receive the json structure in $_POST but the data is not loading properly. So I don't now exactly if you can support me. I've just read all the issues closes and I don't find the correct solution.

Thanks in advance.

**Comment by artf** [comment]
We're using `fetch` under the hood so check this out https://stackoverflow.com/questions/36669911/post-not-retrieving-data-from-javascripts-fetch

**Comment by jvillena** [comment]
Thanks a lot! It works like a charm! Great Job. We are going to work in different new plugins so we will include them as open source as well. I'll keep you inform.
