### ISSUE TITLE
Set href for link block

### ISSUE THREAD

**Issue by AnkitKachhadiya** [artf/grapesjs#1277]
I want to set href for link block as there is empty href by default.

**Comment by AnkitKachhadiya** [comment]
I want to set href for link block as there is empty href by default.

**Comment by maryia-kabash** [comment]
@AnkitKachhadiya you can change it by goint to "Component settings" tab (gear icon). The same is for link block.

**Comment by artf** [comment]
@AnkitKachhadiya you can also update dynamically the default one
```js
editor.BlockManager.get('id-of-the-block').set({
	content: {
		type: 'link',
		content:'Text for the link',
		attributes: { href: '...' }
	}
})
```

**Comment by AnkitKachhadiya** [comment]
**Thank you for the help**

@maryia-kabash @artf  I have made  a custom block for my custom link see code:

> editor.BlockManager.add("unsubscribe-block", {
                                label: "Unsubscribe",
                                content: {
                                    type: "link",
                                    content: "unsubscribe_link",
                                    attributes: {href: "{unsubscribe_link}"}
                                },
                                attributes: {
                                    title: "Insert Unsubscribe block",
                                    class: "fa fa-ban"
                                }
                            });

Every thing works perfectly but the issue is whenever i remove href content using style manager it doesn't remove from my code editor (refer image). 
Do i need to add something or i am missing something
![2018-07-16-10-55-localhost 1](https://user-images.githubusercontent.com/28569675/42744512-c0e30af8-88ea-11e8-90dd-9d0dbbc59ccc.png)
