### ISSUE TITLE
What is the proper way to initialize the editor with an already existing HTML and CSS content?

### ISSUE THREAD

**Issue by tomichal** [artf/grapesjs#1281]
Hi @artf , it seems that in order to initialise an instance of the editor with an already existing CSS you can either give the editor "gjs_styles" or "gjs_css". Similarly for HTML it's either "gjs_components" or "gjs_html". What is the proper way?
So far the way I've been doing this is to have this code run just before running `grapesjs.init`:
```
let contentObject = fetchContentObjectFromTheServerViaAnAPICall()
localStorage.gjs_styles = contentObject.gjs_styles || ''
localStorage.gjs_css = contentObject.gjs_css || ''
localStorage.gjs_html = contentObject.gjs_html || ''
localStorage.gjs_components = contentObject.gjs_components || ''

// Now initialize the editor and it will pick up the HTML and CSS set above.
grapesjs.init({ 
...
})
```

Am I doing this right?

**Comment by artf** [comment]
> Am I doing this right?

Not really.

You have to [setup the remote storage](https://github.com/artf/grapesjs/wiki/Storage#setup-remote-storage)

**Comment by tomichal** [comment]
Thanks @artf !
