### ISSUE TITLE
[Bug]: avoidInlineStyle true breaks saving properties

### ISSUE THREAD

**Issue by SalesFeed** [artf/grapesjs#1282]
Case:
1. Set avoidInlineStyle to true
2. Drag an image to the canvas, set it's width to 100% via Layout > Width
3. Save the canvas
4. Reload the canvas

Expected:
Image to be 100% width

Actual result:
The image is back to it's original size

**Comment by artf** [comment]
Just tried this https://jsfiddle.net/szLp8h4n/235/ and works as expected (uses the default local storage)
Are you sure you're saving properly?
