### ISSUE TITLE
super confused - how to launch the GUI tool?

### ISSUE THREAD

**Issue by ORESoftware** [artf/grapesjs#1284]
Sorry I am very confused - I heard about this tool recently - it looks like it can be used as a GUI tool.

But in the downloads section of the readme it says:

`npm i grapejs`

etc.

those download techniques seem to be for installing a library, not for downloading/launching a GUI tool.
How do we download and install the GUI tool?

**Comment by artf** [comment]
[Download](https://github.com/artf/grapesjs#download) the library (eg. https://unpkg.com/grapesjs), include it inside your html page and launch it https://github.com/artf/grapesjs#usage

**Comment by ORESoftware** [comment]
If that's the case - why can't we just clone a Git repo and have everything set up for us?
Why do I have to create the HTML manually, to get started?

**Comment by artf** [comment]
Because GrapesJS is supposed to be a framework, not a ready to use application https://grapesjs.com/docs/#what-is-grapesjs
