### ISSUE TITLE
[Questions]: How suitable grapeJs for custom webPages for every user in an web app.

### ISSUE THREAD

**Issue by rdtomar** [artf/grapesjs#1285]
Thanks for such an awesome tool.
I am looking for a library which can support my user with custom personalised web pages under a single app. How suitable is grapeJS for such case where I need to store a lot of user template data?
Also in view of dataBases what should how and what I should be storing HTML/Json?
Thanks.

**Comment by artf** [comment]
I think GrapesJS fits perfectly your needs, just read about the [Storage](https://github.com/artf/grapesjs/wiki/Storage) to get an idea on how you would work
