### ISSUE TITLE
Cannot read property 'body' of null - Angular

### ISSUE THREAD

**Issue by panagulis72** [artf/grapesjs#1288]
Hi, 
I have a list of email template (page 'templates') and there is a button that open the edit (page 'templates/edit/:templateId'. All works fine, but when I go back into the templates' list I get this error in the console:

>  core.js:1624 ERROR TypeError: Cannot read property 'body' of null
>     at Object.getBody (grapes.min.js:11)
>     at Object.getWrapperEl (grapes.min.js:11)
>     at R.i.getCanvasWrapper (grapes.min.js:11)
>     at R.i.initialize (grapes.min.js:11)
>     at R.i.e.View (grapes.min.js:2)
>     at R.i [as constructor] (grapes.min.js:2)
>     at new R.i (grapes.min.js:2)
>     at Object.get (grapes.min.js:11)
>     at R.i.updateActive (grapes.min.js:11)
>     at y (grapes.min.js:2)

I tried also to implements OnDestroy into my edit component, but it doesn't effect:
`  ngOnDestroy() {
    this.grapejsComponent.destroy();
  }`

P.S. this.grapejsComponent is the following object:
`
  initGrape() {
    this.grapejsComponent = grapesjs.init({
        ..........
     })
    }`

**Comment by cmoutafidis** [comment]
I sometimes get the same error whenever I hit ctrl+c. Grapesjs is integrated with angularjs.

**Comment by artf** [comment]
@cmoutafidis would you able to provide a live demo, please?

**Comment by Camilo-Tavera** [comment]
me too, i sometimes get the same error with angular 6.

**Comment by mararn1618** [comment]
This is caused by Angular as an SPA triggering grapesjs.init(..) multiple times, see #914.

**Comment by artf** [comment]
@mararn1618 you might be right! When you create component wrappers in frameworks like Angular, React, Vue, etc remember always to use `editor.destroy()` in a `onDestroy`-like life-cycle hook
