### ISSUE TITLE
data-gjs-custom-name question

### ISSUE THREAD

**Issue by acamenhas** [artf/grapesjs#1289]
I've created a simple block content with a custom data-gjs-custom-name = "test".

When i save the page i cant see those attributes on the generated HTML.

Then, when i load that HTML, those custom components appears as BOX.

Is there any way to keep those attributes?

**Comment by artf** [comment]
No, those attributes are only used for the import. Please, learn how to store correctly your templates https://grapesjs.com/docs/modules/Storage.html#store-and-load-templates
