### ISSUE TITLE
[BUG]Set href for link block not editable once initialized

### ISSUE THREAD

**Issue by AnkitKachhadiya** [artf/grapesjs#1290]
#1277 is closed but issue still exist so i have to post as new issue

**Thank you for the help for earlier**

@maryia-kabash @artf  I have made  a custom block for my custom link see code:

> editor.BlockManager.add("unsubscribe-block", {
                                label: "Unsubscribe",
                                content: {
                                    type: "link",
                                    content: "unsubscribe_link",
                                    attributes: {href: "{unsubscribe_link}"}
                                },
                                attributes: {
                                    title: "Insert Unsubscribe block",
                                    class: "fa fa-ban"
                                }
                            });

Every thing works perfectly but the issue is whenever i remove href content using style manager it doesn't remove from my code editor. (refer image). 
**Check Fiddle** [FIDDLE](https://jsfiddle.net/Ankit_Kachhadiya/4Lzqvf0k/1/)
Do i need to add something or i am missing something
![2018-07-16-10-55-localhost 1](https://user-images.githubusercontent.com/28569675/42744512-c0e30af8-88ea-11e8-90dd-9d0dbbc59ccc.png)

**Comment by artf** [comment]
Seems like it doesn't update on the first reset but it actually reacts on changes, indeed you're able to clean it after the first change. I'll check it

**Comment by AnkitKachhadiya** [comment]
Thank you @artf for your atttention please let me know when its solved

**Comment by artf** [comment]
@AnkitKachhadiya the fix will be available in the next release
