### ISSUE TITLE
Submission of contact form

### ISSUE THREAD

**Issue by aj0022** [artf/grapesjs#1293]
Hi, 
artf

Thanks for your great work.
I would like to integrate this great editor with angular. I integrated this Angular 6 it working nicely. But i have one doubt is it possible to submit the contact form details with form group of angular and show error messages.

**Comment by artf** [comment]
If you need to use libraries inside your final templates you have to implement custom components with javascript https://grapesjs.com/docs/modules/Components-js.html#basic-scripts
