### ISSUE TITLE
How to add category for default block manager?

### ISSUE THREAD

**Issue by MooseFrankenstein** [artf/grapesjs#1294]
@artf  I want put all default blocks to category named "Basic". But I can't find any documents about it.

![image](https://user-images.githubusercontent.com/5143201/42876130-4e135512-8ab8-11e8-9d28-6c6c1867f490.png)

I use editor.BlockManager.getAll().reset(); removed all blocks then use plugin "grapesjs-blocks-basic" to create "Basic" but anything still removed.

Or I just add a category to "gjs-blocks-no-cat", but I can't find anyway. 

Thank you for help.

**Comment by AnkitKachhadiya** [comment]
Hey Refer this codepen it might help you [Codepen Demo](https://codepen.io/artf/pen/MQpZPj)

Please Try this code:

> const bm = editor.BlockManager;
editor.on('load', () => {
  editor.BlockManager.render([
    bm.get('column1').set('category', ''),
    bm.get('column2').set('category', ''),
    bm.get('column3').set('category', ''),
    bm.get('text').set('category', ''),
    bm.get('image').set('category', '')
  ])
});

put your category in `bm.get('column1').set('category', 'your own category')`

**Comment by MooseFrankenstein** [comment]
@AnkitKachhadiya Thanks for your help. bm.get(id).set('category', 'your own category'). It works for me. Thanks again. 👍
