### ISSUE TITLE
[Bug]: Unit select field missing on IE after click

### ISSUE THREAD

**Issue by lorrandavid** [artf/grapesjs#1295]
@artf I'm currently using GrapesJS latest version (but you can reproduce this bug using the demo). Basically all you have to do is select any element, go to a property that has a unit select field and select a value, it will turn blank until you select another value again. It just happens on IE.

EDIT: Changing unit works but the problem is I can't see the value on the select field, it stays blank until I select it again.

**Comment by artf** [comment]
Which IE?

**Comment by lorrandavid** [comment]
It seems like it happens on ie 10 and 11. I'm not exactly sure about the build version but I'll look into it when I get home and edit this.

**Comment by lorrandavid** [comment]
Any news on this matter @artf? I can try to help you if you need

**Comment by artf** [comment]
I'd really appreciate a help, it might be just a CSS "issue"

**Comment by xamdam777** [comment]
I have been checking it in IE11 but I do not see any CSS problem in the selectors.

Anyway, I found another problem when trying to open any of the groups from the style manager:

**this.getPropertiesEl().style.display="none",**
_Unable to get property 'style' of undefined or null reference_

I think supporting IE would be a bad idea.

Example: I have my own grapesjs code full of this: https://stackoverflow.com/questions/44437497/syntax-error-using-in-ie

I am sure that if I rewrite all that functions, new problems will appear.

**Comment by theanhmx** [comment]
@xamdam777 
my solution is to add a check before that line:
`if (this.getPropertiesEl() === null || this.getPropertiesEl() === undefined) {
return;
}`

**Comment by theanhmx** [comment]
@artf, I been trying to fix this issue also.
I figured that if I just add something to the select element around the units, the HTML got rerendered and the select working again. But that will erase all the event listener and it won't update the style.
could you give any advice on this?

**Comment by artf** [comment]
> I figured that if I just add something to the select element around the units

What do you mean? Adding what and how?

**Comment by theanhmx** [comment]
just use the inspector edit the select tag as html string, add any text or string to it. then it will work on IE. but when the select change its selected value, the style seem.to be not updated. i doubt that all th event listener got erased when we change html.like that.

**Comment by artf** [comment]
well, in that case, it's a normal behavior because it's like doing `el.innerHTML = "<select>..."` which creates new nodes... it also explains that IE fails for no real reason -.-

**Comment by theanhmx** [comment]
yah, but as @lorrant discribed "Basically all you have to do is select any element, go to a property that has a unit select field and select a value, it will turn blank until you select another value again. It just happens on IE.". you have any idea to workaround this issue? i dont know if it is possible or not but i was trying to copy all the event listener from the current select element to the new one after i had edited the html.

**Comment by makkaronis4e** [comment]
Hi! Just faced the same issue:
`this.getPropertiesEl().style.display="none"`
**Unable to get property 'style' of undefined or null reference**

Did anyone manage to fix it?
