### ISSUE TITLE
Custom Rich Text Editor is not working

### ISSUE THREAD

**Issue by jvillena** [artf/grapesjs#1296]
Hi @artf, I've just created a custom plugin of the RTE using different libraries like CKEditor 5, TinyMCE 4 or pell but all of them with the same result that the editor is losing the focus so the buttons are not applying to the text content.

![screen shot 2018-07-18 at 17 06 53](https://user-images.githubusercontent.com/1280854/42890567-70886f0c-8aad-11e8-9f55-8ce5aabb77b9.png)

 So on the image above if I press on Bold button then the effect is not applied to the content.

```
enable: function(el, rte){


            // If already exists just focus
            if (rte) {
                this.focus(el, rte); // implemented later
                return rte;
            }

            let rteToolbar = editor.RichTextEditor.getToolbarEl();
            [].forEach.call(rteToolbar.children, (child) => {
                child.style.display = 'none';
            });


            el.contentEditable = true;


            // Init Pell
            rte = window.pell.init({
                element: el,
                onChange: function (html) {
                    //console.log(html);
                }
            });

            el.focus();
            rte.focus();

            return rte;
        },

```

I think all my problem is on the enable function but I don't know why is happening this behaviour. Do you have any clue?

If I fix it then it will be really simple to include the 3 different plugins.

**Comment by artf** [comment]
To be honest, I'm not sure but maybe this happening because by clicking outside you're unfocusing from the input, indeed, you should probably append those buttons inside `rteToolbar` which has this listener `on(rteToolbar, 'mousedown', e => e.stopPropagation());` and so prevents from blur

**Comment by jmtt89** [comment]
How you solve this? i can't find a working example with Pell, CKEditor 5 or TinyMCE :/
