### ISSUE TITLE
how to add custom events

### ISSUE THREAD

**Issue by dreamhuo** [artf/grapesjs#130]
Hi, I want to drag blocks to the canvas, add custom events, How to make it work?

**Comment by dreamhuo** [comment]
`blockManager: {
blocks: [{
id: 'b1',
label: '1t',
category: 'Basic',
content: '

<style>'+ blkStyle +'.blk1{width: 100%;padding: 10px;min-height: 75px;}</style>',
attributes: {class:'d7js-fonts d7js-f-b1'},
Commands:{
DragStart: function(editor, sender){
alert('Hello world_DragStart!');
},
DragMove: function(editor, sender){
alert('Hello world_DragMove!');
},
DragEnd: function(editor, sender){
alert('Hello world_DragEnd!');
}
}
}]
}`

**Comment by dreamhuo** [comment]
blockManager: {
         blocks: [{
                  id: 'b1',
                  label: '1t',
                  category: 'Basic',
                  content: '<style>'+ blkStyle +'.blk1{width: 100%;padding: 10px;min-height: 75px;}</style>',
                  attributes: {class:'d7js-fonts d7js-f-b1'},
                  Commands:{
                           DragStart: function(editor, sender){
                                    alert('Hello world_DragStart!');
                           },
                           DragMove: function(editor, sender){
                                    alert('Hello world_DragMove!');
                           },
                           DragEnd: function(editor, sender){
                                    alert('Hello world_DragEnd!');
                           }
                  }
         }]
}

**Comment by artf** [comment]
Hi @dreamhuo currently is not possible to add custom events on blocks but you might make use of global listeners:
```js
editor.on('block:drag:start', function(e) {
   //
});
editor.on('block:drag:move', function(e) {
  //
});
editor.on('block:drag:stop', function(model) {
  //
});
```

**Comment by dreamhuo** [comment]
@artf Thank you very much.
