### ISSUE TITLE
Render blocks outside main editor not working

### ISSUE THREAD

**Issue by FrciSmrci** [artf/grapesjs#1300]
Hi @artf 

the render of blocks outside the main editor added in [v 0.14.5](https://github.com/artf/grapesjs/releases/tag/v0.14.5) isn't working with gjs-preset-webpage plugin, otherwise it works like a charm. Do you have any idea why this would be an issue? 

Thank you in advance!

**Comment by artf** [comment]
I think it's because the preset force the rendering inside its custom panels and, as the element of blocks is unique, is probably moved from the specified position.
I close this issue as it has nothing to do with the core but I'd be glad to accept a PR for preventing forced rendering
