### ISSUE TITLE
I need to add carousel block with flex slider

### ISSUE THREAD

**Issue by aj0022** [artf/grapesjs#1303]
Hi, 
artf

I would like to add some new block with custom slider when user dragged the slider into canvas need to show some popup with available options in flex slider and when user select that need to show the flex slider how can I achieve this. please help me, sir.

**Comment by artf** [comment]
You need to create a custom component
https://grapesjs.com/docs/modules/Components.html
https://grapesjs.com/docs/modules/Components-js.html
