### ISSUE TITLE
 "CanvasView.frame.el.contentDocument is null" in angular4

### ISSUE THREAD

**Issue by sanskipk** [artf/grapesjs#1304]
Hi I  integrated grapejs with angular4.I added custom button.After click on edit button  throwing error:-
**TypeError
​
columnNumber: 7
​
fileName: "http://localhost:4200/vendor.js"
​
lineNumber: 78800
​
message: "CanvasView.frame.el.contentDocument is null"**
ngOnInit() {
    console.log('oninit')

     this.editor  = grapesjs.init({
            allowScripts: 1,
            showOffsets: 1,
            autorender: 0,
            noticeOnUnload: 0,
            container  : '#gjs',
            height: '100%',
            fromElement: true,
            clearOnRender: 0,
            storageManager: {autoload: 0},

          });
  }

  // edit(){
  //   console.log('edit',this.editor)
  //   this.editor.runCommand('sw-visibility');
  //   this.nameModel='hello grapes edit !'
  //   this.editor.render();
  // }
  editBtn(){
    console.log('editBtn',this.editor)
    //this.editor.setComponents(this.editor.getHtml())
    this.editor.runCommand('sw-visibility');
    document.getElementById("preview").style.display = "block";
    document.getElementById("edit").style.display = "none";
  }
![image](https://user-images.githubusercontent.com/41565928/43061645-a446decc-8e73-11e8-9718-ab9c2ce5df47.png)

Thanks,
sandeep kumar.

**Comment by artf** [comment]
There is a very similar issue #1288 please discuss it here.
BTW I'd need a minimal live demo for such a case
