### ISSUE TITLE
About changing the configuration items on the chart

### ISSUE THREAD

**Issue by ionic666** [artf/grapesjs#1305]
Sorry, there's a problem that's been bothering me。
I created a component for chart.
I write configuration items in script
![aa](https://user-images.githubusercontent.com/36065691/43065140-793c5322-8e93-11e8-92d4-e279f4ec6a2d.png)

And I want the user to be able to modify the configuration items
![default](https://user-images.githubusercontent.com/36065691/43065214-b1ae31e4-8e93-11e8-8992-054d300f4842.png)
The problem is I can't get the chart

**Comment by artf** [comment]
You're completely misunderstanding the concept of JS in Components. Read the basics https://grapesjs.com/docs/modules/Components-js.html#basic-scripts and search in issues before posting a new one
