### ISSUE TITLE
[Question]: Initializing Canvas Scripts and Styles dynamically

### ISSUE THREAD

**Issue by inventorbit** [artf/grapesjs#1311]
Hello Grapejs team,

Thanks for this wonderful project saved my time and so far I had great experience with integration and your community support. 

I want to load Canvas Styles and Scripts after the page is loaded from DB (Rest API) 
canvas: {
            styles: ['https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css'],
            scripts: ['https://code.jquery.com/jquery-3.3.1.slim.min.js',
              'https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js',
              'https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js']
}

Is it possible to load this dynamically like

editor.Canvas or something. Please help me with this.

**Comment by artf** [comment]
Hi @inventorbit for such a case you should manipulate directly the canvas document
```js
const scriptEl = document.createElement('script');
scriptEl.src = '...';
editor.Canvas.getDocument().head.appendChild(scriptEl);
```
