### ISSUE TITLE
[Question] Set traits value from html on component load

### ISSUE THREAD

**Issue by krunal039** [artf/grapesjs#1313]
I have custom component and want to set trait default values from html. below is html rendered by component. traits I am trying to set for are  image url, anchor url and h4 content.

![image](https://user-images.githubusercontent.com/11716808/43134268-6b5ca10c-8f39-11e8-8d73-2453753794b4.png)

**Comment by artf** [comment]
By default, the initial value of the trait corresponds to component's attribute. In the case of `changeProp` use, you should pass the initial value via `data-gjs-*` attribute
