### ISSUE TITLE
Traits values are not saved if I'm not typing on them

### ISSUE THREAD

**Issue by jvillena** [artf/grapesjs#1314]
Hi @artf,
I'm struggling with an issue when I'm trying to insert values in the Traits parameters. If I insert a new value without typing on it then the value is gone after the component is deselected. If you check the video attached maybe it's clearer.

http://recordit.co/m9Jgp2XGXr

I need to know if there is a way to update the model with the new value inserted on traits parameters.

**Comment by mcsekar12** [comment]
You are changing the title attribute of the component. so the value will not be updated.
Can you post your trait creation code.

**Comment by mcsekar12** [comment]
@jvillena It is difficult to tell without seeing the code . Can you post the code where you are updating the input.

**Comment by jvillena** [comment]
@mcsekar12 There is not special code. I'm only injecting the value in the input with JQuery like:
$(element).val("test");

This action is typing "test" on the title input field but the traits model of the element is not triggering any event.

Do we have any way to update the component traits value by triggering an event?

**Comment by jvillena** [comment]
I saw that the traits input field when you type on it is updating the model attributes wit changeProp 1 and also in the changes attribute is including the new value. I would like to know how I can force to do it injecting value using jQuery or normal Javascript.

**Comment by jvillena** [comment]
Can someone support me, please? @artf

**Comment by xamdam777** [comment]
If you do not really type on them, the JS listener is not triggered, so they are not saved.
I tried everything some weeks ago, even trying to emulate human typing and press enter with code, but the traits were still not saved.
You would need to know that kind of event are traits listening (I still do not know it) and call it manually with your own code.

**Comment by artf** [comment]
@jvillena it's up to you triggering events... `$(element).val("test").trigger('change')`

**Comment by jvillena** [comment]
@artf I did it several times and I tested triggering different events but the result is the same it's not updating the model with the value changed. I don't know if you are catching the events on the traits and stop the propagation if not I would like to know how to update for instance the title of a components without typing on the input field element. I have to buttons that opens a popup where you can select a variable that it will be inserted on the title input field. But if after that I trigger the event change as you mention above and deselected the element if I click again on the element then the title is empty.

So I'd like to know how to update the traits input fields belongs to any component or plugin that it was by 3 parties.

**Comment by jvillena** [comment]
@artf  @xamdam777 I found a solution to update any traits input without typing on it. For instance in our project we have to buttons to add macro functions and also variables so I need to catch the value and inject on the trait parameter selected. To do that when the user click or select a component I need to inject some extra data parameter on the input field of each traits beforehand:

--------------------------------------------------
```
  editor.on('component:toggled', model => {
             addATButtons();
}

```

In my function called "addATButtons" I inject this extra parameters that I need them to later on update the traits values:
```

var addATButtons = function() {
        // To initialize at input variables in trait
        // First we need to look into trait panels to find input text field
        $('.gjs-trt-trait').each(function () {

            var label = $(this).find(".gjs-label");

            $(this).find("input[type=text]").each(function () {
                if (!$(this).hasClass("js-input-at")) {
                        if (label.attr("title").toLowerCase() != "id"){
                            $(this).addClass("js-input-at");
                            var random_value =  Math.floor((1 + Math.random()) * 0x10000).toString(16).substring(1);
                            $(this).attr("name", random_value);
                            $(this).attr("data-attributes", label.attr("title").toLowerCase());

                        }


                }
            });




        });

  
    };
```

Finally when I click on the "Accept" button of my modal dialog I need to update the traits value on the model of the component dynamically:
    ```
const component =  editorRTE.DomComponents.getWrapper().find('.gjs-comp-selected')[0];
                const updateTraits = model => {
                    if (model && model.get('traits')){
                        var attr_list = {};
                        model.get('traits').models.forEach(traits => {

                            var name_attr = '[data-attributes="' + traits.attributes.name + '"]';
                            attr_list[traits.attributes.name] = $(name_attr).val();
                            //console.log(traits.attributes);


                        });

                        if (!jQuery.isEmptyObject(attr_list)){
                            component.setAttributes(attr_list);
                        }


                    }

                };


                updateTraits(component);
```

The event "change" was not updating the model so I have to work around with this solution.

**Comment by jvillena** [comment]
@xamdam777 I'll take a look later. Now I'm struggling with creating a new Trait select re-implementing on my side the select trait because I need to inject new attributes on components dynamically.

I'll keep you inform.

**Comment by xamdam777** [comment]
@jvillena that sounds hard! good luck :)
Thanks

**Comment by artf** [comment]
jsfiddle.net/szLp8h4n/286

**Comment by xamdam777** [comment]
That fiddle will be very useful, thanks a lot @artf !

Do you think that we could use something like that to update style properties programmatically?

I would love to be able to update any value, like for example setting margin-top 10px to the selected component.
 
I can already do it, but the change will not appear on the style manager like your previous example, so it is not a solution.

Again thanks for your great work!

**Comment by jvillena** [comment]
Thanks @artf that solved my problem in a simple solution so then I don't run over all inputs to update only one.

Great jobs!

**Comment by artf** [comment]
@xamdam777 you can use `component.addStyle({ 'margin-top': '10px' })` (or `setStyle` for a compete replace of the style).

**Comment by xamdam777** [comment]
@artf thanks a lot for finding time to reply.

I have tried that before, but it did not work as expected.

Demo example:

**Comment by izaa** [comment]
@jvillena what is the variable editor are you using? "My variables" etc.  just curious :) Thanks
