### ISSUE TITLE
Get all the style value by ID

### ISSUE THREAD

**Issue by YashPrince** [artf/grapesjs#1315]
@artf   I want to get all the style associated with model selected by ID after save the template and reload and re init the editor.
But I can not get all the style value of the selected model.
![modelstyle](https://user-images.githubusercontent.com/40828744/43147579-fe468e28-8f80-11e8-96de-5bb9cb3e29c6.png)
But in css there are 2 css definition for that ID

![idselector](https://user-images.githubusercontent.com/40828744/43147607-162c4a78-8f81-11e8-9460-30781d55dd1e.png)

I want to know How can I get all the style value applied for a ID either it is 2 time or multiple time.
Please also tell me how to prevent css composer to add new style tag for same ID after page reload or editor re-init so that it will not create new style and it only update the previous style.

**Comment by xamdam777** [comment]
editor.getCss(); -> will give you all the CSS, is up to you to find what you need.

comp = editor.getSelected();	
const html = comp.toHTML(); -> selected comp html
const css = editor.CodeManager.getCode(comp, 'css', {cssc: editor.CssComposer}); -> selected comp CSS

**Comment by artf** [comment]
@YashPrince check the API https://grapesjs.com/docs/api/css_composer.html
