### ISSUE TITLE
Question: How to enable Event of mouse to increase value of input

### ISSUE THREAD

**Issue by Abhisheknanda1344463** [artf/grapesjs#1318]
hi @artf  I want  to know Is there any way to enable input mouse scroller in style manager as you can my screenshot. i want to initalize scroller to increase the values on click and drag .Thanks
![screen shot 2018-07-25 at 1 40 16 pm](https://user-images.githubusercontent.com/20657737/43188050-d7f476e6-9010-11e8-8e47-14c89fea6594.png)

**Comment by artf** [comment]
Like the one which already exists?
![scroll-input](https://user-images.githubusercontent.com/11614725/43229098-e14ae81c-9063-11e8-9571-d5c3327f1c58.gif)

**Comment by Abhisheknanda1344463** [comment]
Yes @artf i want to initialize same which is already exist.Thanks

**Comment by artf** [comment]
Ok... the feature is active by default on all number inputs
