### ISSUE TITLE
[LATEST] + GJS Plugin; Issues using the data-tab attribute

### ISSUE THREAD

**Issue by Moikapy** [artf/grapesjs#1320]
Hello had an issue using the data-tab attribute with my elements.

We were creating a tab that made use of the attribute allowing it to swap between the contents, and when rendered onto the page the data-tab attributes are changed from their original value to a 1. This change then returns an error saying that this isn't the correct selector.

Will post more information as it is found/requested.

**Comment by artf** [comment]
Hi @Moikapy, can you provide a minimal live demo of the issue, please?

**Comment by Moikapy** [comment]
Example Video:
https://youtu.be/0cD3fzWdnHk

Another thing I'm trying to figure out is how to keep GrapesJS from stripping the data-gjs-type attributes as well wen using the setComponent Function.

**Comment by artf** [comment]
You're using incorrectly the [template](https://github.com/artf/grapesjs-tabs/blob/master/src/index.js#L56). You should place attributes like `data-tab` and `data-tab-container` without assigning any value, those are used internally by JS to understand where pieces are placed
```js
<nav data-tab-container>
        <a href="#tab1" data-tab>Tab 1</a>
        <a href="#tab2" data-tab>Tab 2</a>
        <a href="#tab3" data-tab>Tab 3</a>
      </nav>
```
