### ISSUE TITLE
[Bug]: Image component is not deleted

### ISSUE THREAD

**Issue by maryia-kabash** [artf/grapesjs#1321]
The bug is reproducible on GrapesJs demo page.

Steps to reproduce:
1. Drag&Drop or select an Image component.
2. Click delete icon from the toolbar.
**Result**: nothing happens, as _ed.Canvas.hasFocus()_ (file commands/view/ComponentDelete.js) returns false.

3. Select any other component
4. Select image again and try to delete it.
**Result**: the image is deleted now.

**Comment by artf** [comment]
Thanks Maryia, it should be actually fixed with the latest version https://github.com/artf/grapesjs/releases/tag/v0.14.25 (same as #1298)
