### ISSUE TITLE
Disable editing in Preview Mode.

### ISSUE THREAD

**Issue by YashPrince** [artf/grapesjs#1322]
@artf How can we disable editing in the preview mode and re-enable it when preview mode off.
I want to remove editor and hide toolbar in the preview mode so that user can only view the changes 
and can not edit it also all the editable option should be come when user stop the preview mode.

**Comment by YashPrince** [comment]
@jvillena  I have used this code but it is not working.

editor.on('run:preview', () => {
    editor.stopCommand('sw-visibility'); 
});

editor.on('stop:preview', () => 
   `editor.runCommand('sw-visibility');`
});

**Comment by Mhatre1994** [comment]
Hi Artur ( @artf ),

I need to add save and publish button so is there any plugin available or do i need to hardcoded.
Can you please help me.

**Comment by artf** [comment]
```js
editor.on('run:preview', () => {
	// Execute a callback on all inner components starting from the root
	editor.DomComponents.getWrapper().onAll(comp => 
		comp.is('text') && comp.set({ editable: false })
	);
});
// Same for the `stop:preview` but set editable to true
```

**Comment by sakshigarg9** [comment]
> ```js
> editor.on('run:preview', () => {
> 	// Execute a callback on all inner components starting from the root
> 	editor.DomComponents.getWrapper().onAll(comp => 
> 		comp.is('text') && comp.set({ editable: false })
> 	);
> });
> // Same for the `stop:preview` but set editable to true
> ```

Using this, only the heading style (<h1>) properties become uneditable during preview mode. How can I make the other text described in <label> tag also become uneditable during preview mode?
