### ISSUE TITLE
Remove attributes from a component

### ISSUE THREAD

**Issue by jvillena** [artf/grapesjs#1324]
Hi @artf I don't know if it is possible to remove an attribute from a component. In our project I'm injecting a custom attribute from a custom trait that I created but there is an option to unselect this attribute so I would like to remove from the component.

I couldn't find the functionality on your code.

Thanks in advance

**Comment by artf** [comment]
```js
const attr = component.getAttributes();
delete attr.title;
component.setAttributes(attr);
```

**Comment by alemenciones** [comment]
@artf hi man!, can you say me some alternative to remove attributes?
