### ISSUE TITLE
How to disable drop for specific blocks/components

### ISSUE THREAD

**Issue by ploutos27** [artf/grapesjs#1325]
Hello, 

with the following code we are able to indicate if it's possible to drop other component(blocks) inside  that particular component...: 
```
/* Component */
    blockManager.add('component', {
        label: '<div class="gjs-block-label">COMPONENT</div>',
        attributes: { class: 'gjs-fonts gjs-f-b3' },
        content: {
            name: 'Component',
            classes: ['component'],
            type: 'component',
            droppable: false,
            components: `This is the component`
        }
    }); 
```
 We are looking to indicate if it's possible to drop other components **only** for specific blocks.  

For example: 

A. Container Block - > we want to drop only columns 
B. Column Block - >  we want to drop only columns and components 

We thought that we could do that by using an array of selectors which could be dropped inside (as documentation says) but unfortunately is not working: 

```
    /*Column*/
    blockManager.add('column', {
        label: '<div class="gjs-block-label">COLUMN</div>',
        attributes: { class: 'gjs-fonts gjs-f-b1' },
        content: {
            name: 'Column',
            classes: ['column'],
            type: 'column',
            droppable: ['column', 'component'],
            components: ``,
        }
    });
```

Any ideas?  Thank you!

**Comment by artf** [comment]
From the https://github.com/artf/grapesjs/releases/tag/v0.14.17 you get `data-gjs-type` on all rendered components, therefore you can do something like this:
`droppable: '[data-gjs-type="column"], [data-gjs-type="other"]',`

**Comment by ploutos27** [comment]
Thank you! :)
