### ISSUE TITLE
[QUESTIONS] Replacing selected text and getting html

### ISSUE THREAD

**Issue by ezequiel-thalamus** [artf/grapesjs#1327]
Hi! 
Im trying to replace selected text with a code (random code). It's works, i can see the code, but when i do editor.getHtml() not. If i deselect the component (selecting another one) the change takes effect.

```
var rte = editor.RichTextEditor;

rte.add('replace-text', {
    icon: '<b>${var}</b>',
    attributes: {title: 'Replace Text'},
    result: function(rte) {
        const codeToReplace = makeid(10);
        rte.exec('insertText', codeToReplace); // works
        
        //some magic(); 

        console.log(editor.getHtml());  //no showing the change.
    } 
});

```

Thanks!

**Comment by artf** [comment]
The content of the model is actually updated once you blur from the editable component, so when you call `getHtml` it's just not yet there
