### ISSUE TITLE
[Question/bug] Reordering components in the canvas

### ISSUE THREAD

**Issue by jorgecgll** [artf/grapesjs#1328]
I've noticed some inconsistencies when moving DOM components around in the canvas. Description in the gif below using the Webpage Demo:

![grapesjs_gif](https://user-images.githubusercontent.com/15037357/43487035-99d15e8a-94d2-11e8-979b-97440cc0a45a.gif)

In my case, I do see the DOM component "moves" being reflected when I output `editor.DomComponents.getComponents()`. They actually get reordered, but the Canvas does not reflect those moves sometimes.

**Comment by artf** [comment]
Never had time to debug it but I think it caused somehow by components with `float: right` style applied

**Comment by xamdam777** [comment]
Yes, it is related to the float right property. Actually, that is the real behavior of the float right property (the last element appears the first) so I do not see an easy solution.
