### ISSUE TITLE
Question: How to use same CSS for Multiple pages

### ISSUE THREAD

**Issue by inventorbit** [artf/grapesjs#1329]
Hello Grapejs Team,

We've been working on Multi-page Website Builder. 

For each project there will be multiple html pages  with single common "style.css" page. 

I am lazy loading each page with the following function - for handling multiple page loads

```
loadPage(pageId: string, cssPageId) {
    this.pageService.getEntity(pageId).subscribe(currentpage => {
      this.htmlPage = currentpage;
      this.editor.setComponents(currentpage.content);
    });
    this.pageService.getEntity(cssPageId).subscribe(stylepage => {
      this.cssPage = stylepage;
      this.editor.setStyle(stylepage.content);
    });
  }
```

The above page loads the page properly however, if page is empty or different from previous page  it removes certain CSS classes. It's not perfectly loading the entire css file.  

Am I missing something?  

How can I have a common CSS file? Whether there is any workaround. Please help me with this issue.

Thanks for your great work and support :)

**Comment by cjpollard** [comment]
This should work.
``var editor = grapesjs.init({
  keepUnusedStyles: true,
...
});``

**Comment by inventorbit** [comment]
@cjpollard  Thank you very much :) It's working. You saved my time...

**Comment by artf** [comment]
@inventorbit next time, if someone solves your issue, close it
