### ISSUE TITLE
How to support bootstrap

### ISSUE THREAD

**Issue by dreamhuo** [artf/grapesjs#133]
Hi,   I want to edit the bootstrap template with grapesjs, but it doesn't work.   How to do reference bootstrapJS in grapesjs?  And let both work.

**Comment by dreamhuo** [comment]
thanks

**Comment by artf** [comment]
You can place the bootstrap's `<link>` directly inside your template (same question #27).

**Comment by dreamhuo** [comment]
![qq 20170703101839](https://user-images.githubusercontent.com/4711168/27776084-2da31132-5fda-11e7-9bf3-5fd211f5b1b1.jpg)
![qq 20170703102100](https://user-images.githubusercontent.com/4711168/27776083-2d89369a-5fda-11e7-92e7-7964f2c4a239.jpg)

**Comment by dreamhuo** [comment]
Look at the pictures, for example：
Add
        
        <script src="dist/jquery-3.2.1.min.js"></script>
        
        <script src="demo/assets/js/bootstrap.min.js"></script>
In
      <div id="gjs"></div>

grapesjs  is not work.  It's normal to delete it.

**Comment by dreamhuo** [comment]
Look at the pictures, for example：
Add
<script src="dist/jquery-3.2.1.min.js"></script>
<script src="demo/assets/js/bootstrap.min.js"></script>
in grapesjs is not work. It's normal to delete it.

**Comment by dreamhuo** [comment]
Look at the pictures, for example：
Add
<script src="dist/jquery-3.2.1.min.js"></script>
<script src="demo/assets/js/bootstrap.min.js"></script>
in grapesjs is not work.
It's normal to delete it.

**Comment by dreamhuo** [comment]
Look at the pictures, for example：
Add
`<script src="dist/jquery-3.2.1.min.js"></script> <script src="demo/assets/js/bootstrap.min.js"></script>`
in grapesjs is not work.
It's normal to delete it.

**Comment by dreamhuo** [comment]
<div id="gjs">
      …
     <script src="dist/jquery-3.2.1.min.js"></script>
     <script src="demo/assets/js/bootstrap.min.js"></script>
</div>

**Comment by dreamhuo** [comment]
`<div id="gjs">
……<script src="dist/jquery-3.2.1.min.js"></script> <script src="demo/assets/js/bootstrap.min.js"></script></div>`

**Comment by artf** [comment]
@dreamhuo adding JS is slightly different from adding CSS (same as #51) and as in this case, it breaks stuff. I'd suggest you adding JS after the render 
```js
editor.addComponents(`
<script src="dist/jquery-3.2.1.min.js"></script>
<script src="demo/assets/js/bootstrap.min.js"></script>
`)
```
or even better try to load your template via config
```html
<div id="gjs"></div>

<script type="text/javascript">
  var editor = grapesjs.init({
      container : '#gjs',
      components: `
        <div>...</div>
        <script src="dist/jquery-3.2.1.min.js"></script>
        <script src="demo/assets/js/bootstrap.min.js"></script>
      `,
      style: '.txt-red{color: red}',
  });
</script>
```

**Comment by dreamhuo** [comment]
Master, on your way, I always make mistakes here:
Uncaught SyntaxError: Invalid or unexpected token

**Comment by dreamhuo** [comment]
![qq 20170704100139](https://user-images.githubusercontent.com/4711168/27812235-ef8ac3d8-609f-11e7-8b5f-12673eebc942.jpg)
![qq 20170704100156](https://user-images.githubusercontent.com/4711168/27812236-ef906f5e-609f-11e7-8e71-94e3f62e91ff.jpg)

**Comment by dreamhuo** [comment]
The same is true of the addComponents method.

**Comment by dreamhuo** [comment]
@artf 
Hi Master, I solved the mistake，splitting the script：

![qq 20170704101407](https://user-images.githubusercontent.com/4711168/27812654-eefadd74-60a2-11e7-9ca9-48bbff9ba89a.jpg)
But code is not neat, is there a better way?

**Comment by artf** [comment]
Seems like browser's parser issue, can't do a lot, you might try with '<\/script>' if you want

**Comment by dreamhuo** [comment]
Thank you very much for your patience.

**Comment by shimulch** [comment]
I have faced same issue. But escaping ```/``` character solved my problem. 
ex.
```js
editor.addComponents('<script src="../somejs.js"><\/script>')
```
