### ISSUE TITLE
Can i  create multiple pages?

### ISSUE THREAD

**Issue by ionic666** [artf/grapesjs#1331]
This framework is great。It helped me a lot。
Now I want to create a project through this framework implementation that includes multiple pages.
can you give me some adivce?

**Comment by inventorbit** [comment]
You can make use of the following reference 
[https://github.com/ronaldaug/gramateria/issues/2#issuecomment-402550395](url)

**Comment by ionic666** [comment]
@inventorbit It's a really great solution
