### ISSUE TITLE
[Feature Request]: Adding html flexibility 

### ISSUE THREAD

**Issue by orianne** [artf/grapesjs#1332]
Hi,

My team and I are new to grapesjs (have been going over the code during last couple of days), and I've gotten several requests from our designers. One of the requests has been giving me some trouble, and I'm wondering if my incapability to solve the issue is due to lack of understanding, or due to the code not  having this feature as of yet. 

The issue: The designers do not want to have 6 blocks representing h1-h6 but rather have one block titled "Header", or such, which can change by demand (much like certain "style"s and "trait"s can be changed). Is this possible using any of the current features or is there need to write a new one?

Thanks

**Comment by artf** [comment]
I think you're looking for https://github.com/olivmonnier/grapesjs-plugin-header Please, check its source, I think it might give more context on how to create your own components
