### ISSUE TITLE
Bug in WebPage Demo

### ISSUE THREAD

**Issue by kripper** [artf/grapesjs#1333]
To reproduce:

1) Open https://grapesjs.com/demo.html in incognito mode.

2) Import this code:

```
<style>* {
  box-sizing: border-box;
  }
  body {
    margin: 0;
  }
  *{
    box-sizing:border-box;
  }
  body{
    margin-top:0px;
    margin-right:0px;
    margin-bottom:0px;
    margin-left:0px;
  }
  h2{
    font-size:50px !important;
  }
  #bck-img7.wrapper-half-left::before{
    background-image:url("/dummy.png") !important;
  }
</style>
```

3) Clear Canvas

4) Press Import.

Result: The code is not cleared. There is thrash from the previous imported code.

Expected Result: Code should be clean.

**Comment by artf** [comment]
Only class-based selectors are tracked and therefore could be removed, others are left for the safety

**Comment by kripper** [comment]
What about id-based selectors? grapesJS is adding them all the time.
The problem can also be reproduced with just this code:

```
<style>* {
  #bck-img7.wrapper-half-left {
    background-image:url("/dummy.png") !important;
  }
</style>
```
