### ISSUE TITLE
How to import previous saved templates in new template.

### ISSUE THREAD

**Issue by YashPrince** [artf/grapesjs#1334]
@artf  I have saved some templates created by grapejs and want to use/import it in new template as a section / block. I do not want import as html and css, I want to import as Component and Style saved as JSON  format so that component like countdown and other do not change to div or box and also updated style include the current template style and previous template syle and same for the model also, Any help would be appreciated.

**Comment by nojacko** [comment]
Think you're missing the point of grapes. It let's you edit HTML. There's no underlying JSON format.

**Comment by YashPrince** [comment]
@nojacko I have a template which contain countdown, If I direct import as html then it changed to div so I want to import that as json and css so that component do not change to other type and also there style value preserve.

**Comment by YashPrince** [comment]
@xamdam777  When import countdomn saved in html format it changed it to box and countdown settings does not appear. When we use JSON then it's setting come when we reedit the template.

**Comment by xamdam777** [comment]
@YashPrince I think that is a small bug from the default countdown component. If you make your own custom component, that problem should not happen (it will still show settings when you load from HTML).

**Comment by artf** [comment]
@YashPrince you can use HTML string or Component objects
```js
editor.BlockManager.add('some-id', {
	label: '...',
	content: `<div title="text" data-gjs-draggable="false">
		<h1>Some <b>content</b><h1>
	</div>`,
});

// Same as ...
editor.BlockManager.add('some-id', {
	label: '...',
	content: {
		draggable: false,
		attributes: { title: 'text' },
		components: [
			{
				tagName: 'h1',
				components: 'Some <b>content</b>',
			}
		]	
	},
})
```
