### ISSUE TITLE
[Question] Image not rendering when upload the different image with the exact same name available in asset manager list

### ISSUE THREAD

**Issue by ajayya** [artf/grapesjs#1335]
Scenario:
I have image "image1.jpg" in asset manager list. Now I am renaming different image to "image1.jpg" and uploading to Asset Manager. Image is getting uploaded but not updating the existing image with new one. I tried by using asset manager's render() method after using the remove() method but no luck.

It looks like we have to clear cache somehow. Can someone help me on this?

Thanks in advance.

**Comment by artf** [comment]
Just remove the current from the list before uploading the one with the same name
