### ISSUE TITLE
The specified element mode is not supported on element: "a" and CKE config

### ISSUE THREAD

**Issue by kickbk** [artf/grapesjs#1338]
@artf there's an issue with CKE and grapes. Go to your Newsletter demo, double click the text on a button and check the inspector. We are getting _The specified element mode is not supported on element: "a"_ which is a CKE issue (as far as I know). Any ideas? Probably something to add to the CKE config. Just not sure what and how :)

**Comment by maryia-kabash** [comment]
Hi @kickbk,
You can try to add
`CKEDITOR.dtd.$editable.a = 1;`

**Comment by kickbk** [comment]
@maryia-kabash seems to work. Thanks!
