### ISSUE TITLE
how to load styles in editor ?

### ISSUE THREAD

**Issue by ryzraz** [artf/grapesjs#1339]
hi @artf ,
I am using grapesjs editor with wordpress. Is there any way to load the wordpress styles in that grapesjs editor ? because am loading  wocommerce products in the grapesjs editor and  not getting the styles of that wordpress used in the editor for the products. please suggest some way to do it ?

**Comment by Patrick-Spiegel** [comment]
grapesjs.init({
      container: '#gjs',
      plugins: [],
      canvas: {
        scripts: [
        ],
        styles: [
        'http://example.com/wp-content/style.css'
        ]
      }
    })

Is this what you were looking for?
