### ISSUE TITLE
Pressing backspace on text element goes to previous page

### ISSUE THREAD

**Issue by tribulant** [artf/grapesjs#134]
An event binding on this key will be great to prevent the back navigation.

**Comment by artf** [comment]
On which OS/browser? I can't able to reproduce it in chrome/firefox on Mac

**Comment by tribulant** [comment]
@artf 

Very sorry for the false report. Something went wrong on my computer with Parallels Toolbox and keyboard shortcuts it seems. So it is not GrapesJS, rather Parallels Toolbox hooking to keyboard shortcuts. Please mark as invalid.
