### ISSUE TITLE
how to add a new class to the editor's iframe body?

### ISSUE THREAD

**Issue by ryzraz** [artf/grapesjs#1342]
hi,
Is that possible to add a new css class to the body of editor's iframe ??

**Comment by ploutos27** [comment]
Hi @ryzraz  you can use setStyle as below

```
editor.setStyle(` 
   .your-selector {
       color: white;
       background: red;
   }
`);
```

**Comment by ryzraz** [comment]
hi @ploutos27,
its an existing class .. i wanted here to add that class to the body of iframe..!

**Comment by ploutos27** [comment]
@ryzraz  what do you mean an existing class ?
