### ISSUE TITLE
html2canvas give blank

### ISSUE THREAD

**Issue by alibouaziz** [artf/grapesjs#1345]
i want to export the disposition to an image, but give me blank image.
var div = document.querySelector('#wrapper');
                    html2canvas(div, {
                        onrendered: function (canvas) {
                            var screanshot = canvas.toDataURL("image/png");
                        }
                    });
thanks.

**Comment by artf** [comment]
@alibouaziz the `#wrapper` is inside the GrapesJS's iframe, so `querySelector` returns nothing.
You can access the content of the iframe via [Canvas](https://github.com/artf/grapesjs/blob/dev/src/canvas/index.js) module, so to get the body you would do `editor.Canvas.getBody()`
