### ISSUE TITLE
 Problem when building grapesjs

### ISSUE THREAD

**Issue by ionic666** [artf/grapesjs#1348]
hi,after npm build,
there has a problem
![2018-08-07_170038](https://user-images.githubusercontent.com/36065691/43765825-719201c2-9a63-11e8-85b0-14df9e4a88fc.png)

**Comment by umesh2k8** [comment]
npm install grapejs

**Comment by Patrick-Spiegel** [comment]
> npm install grapesjs

and did you import it in your Vue view? 

    import grapesjs from 'grapesjs'; 

Here is an example on how to use grapesjs in a SPA with Vue.

[![Edit Vue Template](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/401zl9xw07?module=%2Fsrc%2Fcomponents%2FHelloWorld.vue)

**Comment by ionic666** [comment]
@Patrick-Spiegel thanks,The example you provided is nice to me.
but there also has a problem about fonts
![2018-08-08_093830](https://user-images.githubusercontent.com/36065691/43811425-03e1ba96-9aef-11e8-94d9-eea55ee2ef78.png)
