### ISSUE TITLE
[BUG] render does not respond

### ISSUE THREAD

**Issue by shlomoko** [artf/grapesjs#1350]
When using the code:
```
pan = panelManager.getPanel('myNewPanel');
pan.buttons = [] 
editor.render()
```
I would expect the panel to appear without any buttons. It does not appear to do so...

[update] I switched to:
```
    pan = pnm.getPanel('myNewPanel');
      var i;
      for (i=0; i<pan.buttons.models.length; ++i) {
        pnm.removeButton('myNewPanel', pan.buttons.models[i].id)
      } 
```
Which when used on 3 buttons, deleted the first and the last, but not the second.

[update 2] I have finally added the next functions, as a temp workaround until bug is resolved..
```
  function sleep(ms) {
    return new Promise(resolve => setTimeout(resolve, ms));
  }

  async function removeBtn(buttonName) {
    await sleep(500);
    pnm.removeButton('myNewPanel', buttonName)
  } 
```

What I am trying to do is build a DOM parent tree of the selected component. So that every time I click on a component I have a bottom panel that has a list of buttons representing the parents of the component.

**Comment by artf** [comment]
`editor.Panels.getPanel('options').get('buttons').reset()`
