### ISSUE TITLE
Use  Ckeditor-5 with grapejs

### ISSUE THREAD

**Issue by YashPrince** [artf/grapesjs#1351]
How can I use [https://ckeditor.com/ckeditor-5/#inline](https://ckeditor.com/ckeditor-5/#inline)  in grapejs . I am using 'gjs-plugin-ckeditor' for ckeditor-4 but I want to move on ckeditor-5. I have checked and 'gjs-plugin-ckeditor' do not support 
ckeditor-5 so how can I use  ckeditor-5 with grapejs, any help would be appreciated.

**Comment by artf** [comment]
You should follow [this guide](https://grapesjs.com/docs/guides/Replace-Rich-Text-Editor.html)
