### ISSUE TITLE
Set JS

### ISSUE THREAD

**Issue by Big-Silver** [artf/grapesjs#1352]
I thrilled to GetHtml, GetCss are GetJs.
Is it possible SetHtml, SetCss and SetJs like above functions?

**Comment by artf** [comment]
You have these
https://grapesjs.com/docs/api/editor.html#setcomponents
https://grapesjs.com/docs/api/editor.html#setstyle

**Comment by Big-Silver** [comment]
Thanks @artf 
setcomponents and setstyle work well.
