### ISSUE TITLE
[Feature Request] Checkbox property type

### ISSUE THREAD

**Issue by emilsedgh** [artf/grapesjs#1353]
I'm interested in developing a "checkbox" (toggle) property type for the style manager.

Basically it'd be like the _radio_, except that it's singular and can be turned on off.

Use case is this:

I want to have a _Bold_ icon. If toggled on, it applies `font-weight: bold` otherwise applies `font-weight: normal`.

Just like the default rte. Except that I want it in the style manager.

Would you guys accept that in grapes? Should I call it `PropertyToggle` or `PropertyCheckbox`?

**Comment by xamdam777** [comment]
If I understood you ok, you are trying to create a new button like the others under "text-decoration" in https://grapesjs.com/demo.html

I do not have text decoration in my project, but I have text-align buttons that work the same. 
This should be the code that creates the text-align buttons in the style manager.

Notice that you may already have a font-weight property, so if you add it as a radio button, you will need to remove the default dropdown.


`    
                    properties: [{
                        property: "text-align",
                        list: [{
                            value: "left",
                            className: "fa fa-align-left"
                        }, {
                            value: "center",
                            className: "fa fa-align-center"
                        }, {
                            value: "right",
                            className: "fa fa-align-right"
                        }, {
                            value: "justify",
                            className: "fa fa-align-justify"
                        }]
                    }]
........
`    


`
                            case "text-align":
                                r.type = "radio";
........
`


`
                            case "text-align":
                                r.list = [{
                                    value: "left"
                                }, {
                                    value: "center"
                                }, {
                                    value: "right"
                                }, {
                                    value: "justify"
                                }];
                                break;
`

**Comment by emilsedgh** [comment]
Your example provides a _radio_ button of a few choices.

I want single toggle on/off buttons.

**Comment by xamdam777** [comment]
Oh, sorry, I just got right what you need now.
You could try a dirty jquery solution while waiting, using 2 radio buttons with the different on/off states and show/hide every button when you need it.

**Comment by emilsedgh** [comment]
Well all I'm saying is that if grapesjs will accept it into core, I will provide the patch that appropriately implements this property type for future use.

**Comment by xamdam777** [comment]
That would be great!

**Comment by artf** [comment]
Go ahead @emilsedgh 👍

**Comment by alikabeer32** [comment]
Is the checkbox usable yet? Please do tell me.. I need it

**Comment by artf** [comment]
@alikabeer32, unfortunately, it was never finished. FYI this is the PR started by Emil https://github.com/artf/grapesjs/pull/1371
