### ISSUE TITLE
Add "Insert" button to assets manager

### ISSUE THREAD

**Issue by kickbk** [artf/grapesjs#1356]
How would you go about adding a "Insert image" button to the assets manager modal? At the moment the "Add Image" may be confusing to some who would thing that button would actually insert the image onto the canvas and keep clicking it till their mouse would drop dead :)

**Comment by artf** [comment]
Are you just asking to rename the `Add image` with `Insert image`?

**Comment by artf** [comment]
ok, so the problem is it's not clear how to select and close the modal, right? In that case, probably, something like 'Select' button (at the bottom) might be a good solution

**Comment by kickbk** [comment]
indeed. Perhaps as an option to activate and change the title on the button so it doesn't disrupt anything.
