### ISSUE TITLE
npm run build issue

### ISSUE THREAD

**Issue by Chronis77** [artf/grapesjs#136]
Hi, 

I am really hoping someone can point me in the right direction. I need to make a couple of styling and functional changes to the core of grapesjs to cater for my requirements.. 

**Issue number 1:**
I am running "npm run build". It gets to the webpack command and then fails with a 
"ERROR in ./dist/grapes.min.js" from UglifyJS 
Unexpectedtoken: punc()..." 

Now i am assuming this has something to do this converting the code to ES5 for Uglify to compile. Any ideas what the issue could be. I haven't really altered the config file and i have installed babel babel-loader and the es2015 present, but it still seems to throw that error. 

**Issue number 2:**
If i comment out "webpack.optimize.UglifyJsPlugin" from the plugins it finishes running, however the code i am left with doesn't seem correct. It has multiple references to "__webpack_require__" and if i embed it on the web page i get that error that grapejs is not defined. 

My environment is: 
- Windows 10.
- Nodejs 6.9.1
- NPM 3.10.9

The help would be greatly appreciated.

**Comment by artf** [comment]
Sorry @Chronis77 but can't reproduce it.
First of all, did you run `npm i`? 
Are you able to start the project with `npm start`? 
Can you try to upgrade node to the latest version?

**Comment by fzs1994** [comment]
My Environment:
Node: 8.1.1
NPM: 5.0.3
`npm start` works fine

**Comment by Chronis77** [comment]
Thank you so much for the help. It was my node version!
