### ISSUE TITLE
[Question/bug] Need help saving data to Blackbaud database.

### ISSUE THREAD

**Issue by gregvissing** [artf/grapesjs#1360]
I'm trying to embed this into Blackbaud Internet Solutions using a [Custom Content Part](http://developer.blackbaud.com/bbis/guide/custom-content-parts/). Can someone help me figure out how to setup the storageManager so that I can Save and Load the data based on the ID? I'll be creating individual parts using this Custom Content Part so I'll need the ID, HTML, CSS, etc. stored separately from the other parts.  Here is the code that I have so far: https://github.com/gregvissing/grapejs-page-builder/blob/master/editor.html

**Comment by artf** [comment]
Hi Greg, for the grapesjs part I think that all you need is here https://grapesjs.com/docs/modules/Storage.html#setup-remote-storage I think that this approach, which allows you custom parameters and headers covers 99% of cases. So, for the rest you have to deal with the third-party integration and it has nothing to do with grapesjs itself
