### ISSUE TITLE
[Bug]: Error on multiple instances of grapesjs 

### ISSUE THREAD

**Issue by thangab** [artf/grapesjs#1364]
Hello,
I use Grapesjs in my reactJS application.
I have a react component which is an instance of Grapesjs. So I can add this component in my application as many times as I want.
Everytime I want to fire an event (delete a block) with my keyboard in the grapesjs Editor, it doesn't work.
This is the error throwing:
![grapesjs-error](https://user-images.githubusercontent.com/15085404/44101801-861e0d4a-9fe8-11e8-88f2-92ac2fcb60ba.png)
But if I click on the icon to delete the block, it works.

**Comment by artf** [comment]
Can you provide a reproducible live demo of your case, please?
