### ISSUE TITLE
[QUESTION] Vertical panel buttons

### ISSUE THREAD

**Issue by shlomoko** [artf/grapesjs#1365]
Hi,
I am trying to add vertical buttons in a panel. I have added a flexbox with a vertical direction, but since an additional div is added as an interim to the buttons, it does not affect them. Is there a way to solve this?

 I have added the following code that does not appear to work ():
      
```
#files-container {
  padding: 0;
  height: 100%;
  width: 70px;
  display: flex;
  flex-flow: column wrap;
}

<div id="files-container"></div>
panels: {
        defaults: [ {
          id: 'files-picker',
          el: '#files-container',
          buttons: [{
            id: 'layer-picker',
            label: '<img src="assets/layers.svg">' 
          },{
            id: 'file-picker',
            label: '<img src="assets/files.svg">' 
          }]
        }
]}
```

**Comment by artf** [comment]
@shlomoko sorry but I close this issue, has nothing to do with grapesjs itself, it's just about your UI layout setting
