### ISSUE TITLE
[BUG] Duplicating CSS

### ISSUE THREAD

**Issue by blairpanek** [artf/grapesjs#1366]
On newest version of Grapesjs. I can replicate bug on both. Linux Ubuntoo, Moxilla.
I expect that the css only shows up once, otherwise it'll be to much in the window for use when exporting it. Css gets duplicated. Duplication happens with @keyframes styles. So clear canvas drag tabs block onto canvas export import and css will duplicate.

In our version of grapes we also tried the protectedCss: '', didn't work either.

![duplicate](https://user-images.githubusercontent.com/32502045/44152359-f271b802-a06a-11e8-9f54-36a683dc2d36.png)

**Comment by artf** [comment]
@blairpanek I don't understand how to reproduce the issue, provide a live demo please
