### ISSUE TITLE
Need to change Grapes Js Dynamic ID selector.

### ISSUE THREAD

**Issue by rajatkumcom** [artf/grapesjs#1370]
Its not a issue,I need some help.

I have integrated Grapes Js with Drupal 8, for styling Drupal elements.
I don't want the id selector which you are generating dynamically, instead it select the id of the element if it has id or ask user to enter it.
Actually we don't have control on HTML elements. Only we can control css.
We have to edit HTML element from the server side in the PHP.

**Comment by rajatkumcom** [comment]
![grapes js selector](https://user-images.githubusercontent.com/16242362/44298378-a564b180-a2ff-11e8-8cce-3f297387d397.png)

**Comment by artf** [comment]
GrapesJS outputs style in CSS, it doesn't inline it, so in this case, it would require the user to indicate always the ID before applying the style, so it works like that by design
