### ISSUE TITLE
BUG - Backbone Deferred 

### ISSUE THREAD

**Issue by dsepulved** [artf/grapesjs#1373]
Hi, I am using backbone-deferred https://github.com/arhea/backbone-deferred, when starting GrapesJS this library is deleted, I have to restart the application to get it back, any way to solve it please?

**Comment by artf** [comment]
I don't know, try to load that library after GrapesJS or maybe check this http://backbonejs.org/#Utility-Backbone-noConflict it might be an issue as grapesjs, once compiled, contains its own version of Backbone
