### ISSUE TITLE
about the path of the styles

### ISSUE THREAD

**Issue by ionic666** [artf/grapesjs#1376]
hi,i want to know the path of the styles.
i want to use local css,and the local directory structure is as follows
![2018-08-23_111242](https://user-images.githubusercontent.com/36065691/44502731-79fa1200-a6c5-11e8-8849-ef50df4dbe5a.png).
I tried many times and it didn't work。

![2018-08-23_111422](https://user-images.githubusercontent.com/36065691/44502905-276d2580-a6c6-11e8-8eeb-14ec57d60385.png)
![2018-08-23_114057](https://user-images.githubusercontent.com/36065691/44503535-71a3d600-a6c9-11e8-8c77-d57396a293ab.png)

Can you tell me the correct way to write it

**Comment by artf** [comment]
I don't know exactly how the path is generated for you but you can easily inspect the grapesjs' `iframe` and check inside which path is used
