### ISSUE TITLE
Image upload doesn't work

### ISSUE THREAD

**Issue by imamovicm** [artf/grapesjs#138]
Everything works fine except image uploader, when I upload or drag image there is no preview and I can't use image at all.

**Comment by artf** [comment]
Are you talking about the demo or the last version itself?

**Comment by imamovicm** [comment]
@artf Last version, everything is on my localhost and when I want to upload some image from my local folder and want to use it - nothing happens.

**Comment by artf** [comment]
Did you set up the remote storage?
Check the console and let me know if you see any error

**Comment by imamovicm** [comment]
Remote storage?
When I drag or upload image there is no preview but it run upload file which I provided but when I tried to debug it shows me only empty array, so I can't write anything to db because its empty. 
Also shouldn't there will be preview for image no matter if its uploaded or not?

**Comment by artf** [comment]
The preview shows up only when the asset is already added to the Asset Manager.
Can I see your config pls?

**Comment by imamovicm** [comment]
`assetManager: {
        storageType      : '',
        upload: 'http://localhost/uploadImage.php',
        storeOnChange    : true,
        storeAfterUpload  : true,
        assets        : [
           { type: 'image', src : 'http://placehold.it/350x250/78c5d6/fff/image1.jpg', height:350, width:250},
           { type: 'image', src : 'http://placehold.it/350x250/459ba8/fff/image2.jpg', height:350, width:250},
           { type: 'image', src : 'http://placehold.it/350x250/79c267/fff/image3.jpg', height:350, width:250},
           { type: 'image', src : 'http://placehold.it/350x250/c5d647/fff/image4.jpg', height:350, width:250},
           { type: 'image', src : 'http://placehold.it/350x250/f28c33/fff/image5.jpg', height:350, width:250},
           { type: 'image', src : 'http://placehold.it/350x250/e868a2/fff/image6.jpg', height:350, width:250},
           { type: 'image', src : 'http://placehold.it/350x250/cc4360/fff/image7.jpg', height:350, width:250},
           { type: 'image', src : './img/work-desk.jpg', date: '2015-02-01',height:1080, width:1728},
           { type: 'image', src : './img/phone-app.png', date: '2015-02-01',height:650, width:320},
           { type: 'image', src : './img/bg-gr-v.png', date: '2015-02-01',height:1, width:1728},
         ]
      },`

**Comment by artf** [comment]
It's working from my side (the ajax call is correctly called). Are you able to see the ajax call in dev tools?

**Comment by imamovicm** [comment]
![screenshot from 2017-07-04 14 10 31](https://user-images.githubusercontent.com/17527987/27829595-9aab72f4-60c2-11e7-9ccc-a21e6f20d842.png)

**Comment by artf** [comment]
in php, uploaded files are in $_FILES

**Comment by imamovicm** [comment]
You're right, my mistake but my question wasn't about that. Even when I record image to DB how I can use it in realtime in my builder with preview?

**Comment by artf** [comment]
the ajax call expects, as a result, a JSON with assets inside `data` key:
```js
{
  data: [
    'https://image/path',
    {type: 'image', src: 'https://image/path', height:350, width:250},
    ..
  ]
}
```

**Comment by aliassad** [comment]
upload: 'http://localhost/uploadImage.php', 
what type of code is in this file ? @artf

**Comment by artf** [comment]
@aliassad it's just your server script which receives uploading files, stores them and outputs the result as a JSON

**Comment by ashishvarma04** [comment]
nice guide <a href="https://blog.webnersolutions.com/adding-image-upload-feature-in-grapesjs-editor#comment-14937" > webner solution </a> is best to guide me on grapesjs thanks it worked for me, for more learning for students you can also visit
<a href="www.saintlymonkey.com" > more details</a>
