### ISSUE TITLE
How can i make elements absolutely positioned on canvas by default when dropped.

### ISSUE THREAD

**Issue by bright-ic** [artf/grapesjs#1380]
Grapejs is what i have been looking for over a long time now. 
Though by default, all elements are relatively positioned when dropped on the canvas and i don't want that. I want the elements [blocks or components] to be absolutely positioned and can be dragged to any part of the canvas.

Your help would be saving me a great deal.
Thanks.

**Comment by artf** [comment]
Hi @bright-ic what you're asking is what we call the `Designer mode`, it's on our [Roadmap](https://github.com/artf/grapesjs/issues/74) but unfortunately not yet implemented :/
