### ISSUE TITLE
Custom Embed Video in Video Component

### ISSUE THREAD

**Issue by YashPrince** [artf/grapesjs#1381]
@artf I want to include a custom embed code in Video component so that user can add any iframe containing video. Any help would be appreciated.
eg:-
<iframe width="640" height="360" src="//player.vimeo.com/video/123456789?autoplay=0&title=0&byline=0&wmode=transparent" frameborder="0" allowfullscreen="" wmode="opaque"></iframe>

![customvideo](https://user-images.githubusercontent.com/40828744/44589767-06482a00-a7d7-11e8-8aaf-c737e3516c4b.png)

**Comment by artf** [comment]
Use https://github.com/artf/grapesjs-custom-code
