### ISSUE TITLE
can we change the icon of style manger?

### ISSUE THREAD

**Issue by Abhisheknanda1344463** [artf/grapesjs#1383]
hi @arthuralmeidap  i want to override font awesome icons of panel "views" say style manager i want to replace icon with my "svg" icon .Can you please help to sort-out the things

![screen shot 2018-08-27 at 11 01 59 am](https://user-images.githubusercontent.com/20657737/44644394-88139f80-a9f1-11e8-92da-c44cbcbf6930.png)

this is how i tried but it'll not reflect any changes. Thanks

**Comment by Abhisheknanda1344463** [comment]
???? @arthuralmeidap  i tried to do that many times but still failed.Can you please help me out?

**Comment by artf** [comment]
https://github.com/artf/grapesjs/issues/1379#issuecomment-417939769
