### ISSUE TITLE
newsletter preset button only view text

### ISSUE THREAD

**Issue by ahmadcore** [artf/grapesjs#1384]
hiii,
i use latest grapesjs with newsletter preset plugins, but when i drag & drop button control only view text

![screenshot from 2018-08-27 13-42-17](https://user-images.githubusercontent.com/28822541/44644711-3d008900-a9ff-11e8-8382-88953c1651a1.png)

this my code:
`<script type="text/javascript">
        var images = [];
        var editor = grapesjs.init({
            clearOnRender: true,
            storageManager: {
              id: 'gjs-nl-',
            },
            assetManager: {
                assets: images,
                upload: 0,
                uploadText: 'Not allowed',
            },
            fromElement: true,
            container : '#gjs',
           plugins: ['gjs-preset-newsletter'],
            pluginsOpts: {
                'gjs-preset-newsletter': {
                    modalTitleImport: 'Import template',
                    // ... other options
                }
            }
        });
    </script>`

**Comment by artf** [comment]
Styles of those blocks are defined [here](https://github.com/artf/grapesjs/blob/gh-pages/demo-newsletter-editor.html), you can copy them or define your own
