### ISSUE TITLE
Include all the google fonts?

### ISSUE THREAD

**Issue by YashPrince** [artf/grapesjs#1387]
@artf  I want to include all the google fonts in font family.

![fw](https://user-images.githubusercontent.com/40828744/44655069-7a6e1200-aa11-11e8-983d-d716ec7835a7.png)
How can we include/import all the font family, Any help would be appreciated.

**Comment by artf** [comment]
You can init the editor with custom style/scripts if you need 
```js
var editor = grapesjs.init({
        canvas: {
            styles: [
				'https://fonts.googleapis.com/css...',
				// ...
			],
            scripts: [
				'https://...some-script.js',
				// ...
			],
        },
    });
```
or you can add them dynamicly like this
```js
editor.Canvas.getDocument().head.appendChild(someEl);
```
