### ISSUE TITLE
Add Attribute to Child Elements in component 

### ISSUE THREAD

**Issue by mariselvanm** [artf/grapesjs#1389]
This is the component I try to add in Editor.

`
      
      <div class="page">

                <div class="col1"></div>

                <div class="col2"></div>

             </div> 
`

After adding those components I try to add some computed values to the elements like this,

`
                           
   element.on('component:add',function(ele){
        
          ele.addAttributes({

          'data-top' : topOffset,

          'data-left' : leftOffset,

        });

    editor.render();// For render Updated html
});`

But, this code only update the `.page` component only.

How Can I add those attr into `.col1,.col2` elements inside `.page` component ?

**Comment by artf** [comment]
Check here all the methods available for components: https://grapesjs.com/docs/api/component.html

Btw you would something like this
```js
element.on('component:add', component => {
	component.find('.col1, .col2').forEach(comp => {
		comp.addAttributes({ ... });
	});
	
	// YOU DON'T NEED TO RENDER
	// editor.render();
});
```
