### ISSUE TITLE
[BUG] Property slider view default unit

### ISSUE THREAD

**Issue by FrciSmrci** [artf/grapesjs#1391]
Hey @artf , thanks for the [enhancement](https://github.com/artf/grapesjs/issues/1346)! The implementation works as expected with some properties (font-size, border-radius, ...), but not with others (line-height, border-width, ...). I created a [example/demo](https://stackblitz.com/edit/angular-737uyd) where it's visible that the configuration is the same in both scenarios, however the unit doesn't apply in the case of previous mentioned properties.

Hope you can look into it.

Thank you.

**Comment by artf** [comment]
> I created a example/demo where it's visible that the configuration is the same in both scenarios

Actually, you didn't indicate the `defaults`, where in case of `line-height` takes `normal` by default and so resets its `unit` on initialization

**Comment by FrciSmrci** [comment]
@artf I think that this specific fix messed up the properties without units, like Opacity. The slider behaves weirdly in this case, even on the [demo](https://grapesjs.com/demo.html).
