### ISSUE TITLE
[Question] Add grapesjs color picker to a new trait type?

### ISSUE THREAD

**Issue by pnellesen** [artf/grapesjs#1393]
I'm building a a new trait type, and would like to be able to include the grapesjs color picker inside it - any suggestions on how to do that? Right now I'm including the standard HTML color input in my "inputEl" html  (along with a text field and radio button) but I would love to be able to use the one that comes with grapesJS instead, if that's possible.

Example of where I'd like to put the grapesjs picker. 

     inputEl =   `<div>SOME HTML HERE</div><div><span>Color: </span><span><input type="color" id="colorpicker" value=""></span></div><div>MORE HTML HERE</div>`

Thanks for any suggestions. Great tool, btw, thank you for creating it.

**Comment by artf** [comment]
Hi @pnellesen this is actually a really good question, definitely, we should allow doing so but unfortunately, right now it's not so straightforward. We should refactor few modules to make the UI more reusable.
BTW try to extend `editor.TraitManager.getType('color').prototype.getInputEl` inside `getInputEl` method and see if it might help you

**Comment by pnellesen** [comment]
@artf  - thanks for the response! Your suggestion worked pretty well (and it even works in Internet Explorer, which is better than my html5 color picker :p ). I have some tweaks to do to my styling and my input data, but otherwise it's good.

Thanks again!

**Comment by artf** [comment]
Great @pnellesen, I'm glad it worked out for you

**Comment by nojacko** [comment]
@pnellesen would you mind sharing the '... mode code ...' and '.. other code ...'? I'm trying to do something requiring the colour picker too but not having much luck.

**Comment by pnellesen** [comment]
@nojacko I've modified my code a little, here's basically what I'm doing:

 getInputEl: function() {
      if (!this.inputEl) {
        var input = document.createElement('div');
        input.innerHTML = this.inputHtml
        var inputEl = input;
        var pickerEl = inputEl.querySelector(".myolorPicker");
        pickerEl.id = "ppcp" + this.cid;
        if (!this.model.colorPickerEl) {// add the jQuery spectrum color picker to our trait editor
          this.model.colorPickerEl = editor.TraitManager.getType('color').prototype.getInputEl.apply(this, arguments);
        }
        pickerEl.appendChild(this.model.colorPickerEl)
        
        ... code to handle value changes and update other fields ...

      return this.inputEl;
}

Hope this helps. This is still a work in progress :)

**Comment by nojacko** [comment]
Thanks @pnellesen!
