### ISSUE TITLE
GrapesJS translate

### ISSUE THREAD

**Issue by huzineczerik** [artf/grapesjs#1398]
Hello @artf ,

Do I want to translate all functions into Hungarian, so that I can do it?

Please give me examples of how to modify these texts:

- ![kk5](https://user-images.githubusercontent.com/39269531/44957291-f6180500-aed0-11e8-93d1-6d0b798df97e.png)
- ![kk7](https://user-images.githubusercontent.com/39269531/44957302-18aa1e00-aed1-11e8-95ac-99282e981b8d.png)
- ![kk9](https://user-images.githubusercontent.com/39269531/44957315-5018ca80-aed1-11e8-865b-6f50a02282d0.png)
- ![kk10](https://user-images.githubusercontent.com/39269531/44957329-81919600-aed1-11e8-8800-4071a438fa3f.png)

I checked the issues #26 but I dont understand how to translate all texts.

Thank You,
Erik

**Comment by artf** [comment]
Hi @huzineczerik if you check the [Getting Started](https://grapesjs.com/docs/getting-started.html) guide you will see that all the texts are defined by the configuration object. If your goal is to extend an existing preset in that case you have to access each element of the module via its [API](https://grapesjs.com/docs/api).
Let's say for example you'd like to change the label of some block, you would do this:
```js
editor.BlockManager.get('ID-OF-THE-BLOCK').set({ label: 'Some label' })
```
the same for some style property
```js
editor.StyleManager.getProperty('Dimension', 'height').set({ name: 'Some name' })
```

**Comment by huzineczerik** [comment]
Thank You @artf ,

I tried but did not work
![kk](https://user-images.githubusercontent.com/39269531/44976989-198d8f00-af67-11e8-9ebf-91fb9cc83d6e.png)
What do I do wrong?

**Comment by huzineczerik** [comment]
![image](https://user-images.githubusercontent.com/39269531/44978027-ffa17b80-af69-11e8-8a99-43ba5f4d03b5.png)
so I tried

**Comment by artf** [comment]
Same as here https://github.com/artf/grapesjs/issues/1379#issuecomment-417939769
