### ISSUE TITLE
Change the trait view 

### ISSUE THREAD

**Issue by aj0022** [artf/grapesjs#1399]
Hi Artf,

Thanks for your great work i really wonder for your work. I have small doubt in trait management  i would like to open modal instead of gear icon in editor. When user select input it is hard to change the input names because of it is not getting halite user does not recognise that gear icon instead of gear icon i would like to show model when user select input. How to achieve this please help me.

**Comment by artf** [comment]
I think for your case you would need to extend the [input components](https://grapesjs.com/docs/modules/Components.html#update-component-type) and open the modal (eg. on double-click) where you can help the user setting its traits

**Comment by aj0022** [comment]
Thanks for your reply,

But I don't know how to do that could you please help artf.
