### ISSUE TITLE
"Test your Newsletter" seems to be broken

### ISSUE THREAD

**Issue by derblub** [artf/grapesjs#140]
I'm currently trying to implement a similar newsletter-testing feature as you have it on the newsletter demo.  

Unfortunately, that function on your demo seems to be broken currently:  
No matter what email I try, when I click "send", it's making two requests.   
First one returns `{errors: "Email not valid"}` and the second `{errors: ""}`. 
UI crashes/hangs after that.  

Also:  
I see that the form is being submitted to `http://grapes.16mb.com/s`. Can you please elaborate what's happening there? I've checked "PutsMail", but I couldn't find an API endpoint, so I'm curious how this testing-feature is implemented on that backend.  

Thanks in advance for help & info!

**edit:** Just realized, I should've posted to [artf/grapesjs-preset-newsletter](https://github.com/artf/grapesjs-preset-newsletter)? _..sorry!_

**Comment by artf** [comment]
Indeed PutsMail hasn't any public API so I just send raw backend requests from a `grapes.16mb.com` (PutsMail authorized me to do so). I have to check the backend script to see what is going on

**Comment by artf** [comment]
@derblub unfortunately, PutsMail added a reCaptcha on their form, therefore I'm unable to send other requests from the backend. Can't do much so I just removed it from the demo :/

**Comment by derblub** [comment]
I've ended up, using a payed Litmus account.
