### ISSUE TITLE
[BUG] double dash in texte

### ISSUE THREAD

**Issue by FlashPapa** [artf/grapesjs#1400]
With /*! grapesjs - 0.9.15 */
When we edit a text box and we put a double dash and we use the function 'mjml2htm' we have the following error : 
Error: [MJMLError] ParseError: Error while parsing the file grapesjs-mjml.min.js:2:30405
a
http://127.0.0.1/earcGrapesJs/app/bower_components/grapesjs-mjml/dist/grapesjs-mjml.min.js:2:30405
L
http://127.0.0.1/earcGrapesJs/app/bower_components/grapesjs-mjml/dist/grapesjs-mjml.min.js:8:9318
value
http://127.0.0.1/earcGrapesJs/app/bower_components/grapesjs-mjml/dist/grapesjs-mjml.min.js:2:27817
t
http://127.0.0.1/earcGrapesJs/app/bower_components/grapesjs-mjml/dist/grapesjs-mjml.min.js:2:27645
e.mjml2html
http://127.0.0.1/earcGrapesJs/app/bower_components/grapesjs-mjml/dist/grapesjs-mjml.min.js:2:20329
u
http://127.0.0.1/earcGrapesJs/app/bower_components/grapesjs-mjml/dist/grapesjs-mjml.min.js:108:13522
run
http://127.0.0.1/earcGrapesJs/app/bower_components/grapesjs-mjml/dist/grapesjs-mjml.min.js:108:13586

Regards

**Comment by artf** [comment]
@FlashPapa your grapesjs version is outdated and this is the core repository, which has nothing to do with mjml plugin

**Comment by jmchaves** [comment]
Double dash is still happening: 
![Screenshot from 2019-07-17 15-56-23](https://user-images.githubusercontent.com/2567814/61407334-7d812380-a8ab-11e9-9c5b-2248ed10c048.png)
