### ISSUE TITLE
how to build minified Css?

### ISSUE THREAD

**Issue by Abhisheknanda1344463** [artf/grapesjs#1403]
hi @artf  Can You please explain me how can i build css from style section. Everytime when i run "Npm run build".Code build  in min js only should i need to add file for css build???
Thanks.

**Comment by artf** [comment]
[`npm run build`](https://github.com/artf/grapesjs/blob/dev/package.json#L102) minifies also CSS via `"build-dev": "webpack --env=dev && npm run build:css",`

**Comment by Abhisheknanda1344463** [comment]
ok @artf thanks :)

**Comment by Abhisheknanda1344463** [comment]
@artf With command "Npm run build" my css doesn't get build.
i tried npm run build:css
it shows error various scripts are written in my package.json
My all css is in the Style folder.

**Comment by artf** [comment]
If you don't show the error how can I help you???

**Comment by Abhisheknanda1344463** [comment]
@artf i got the solution by adding  two scripts in package.json
```
"build:css": "node-sass src/style/YourFileName.scss dist/Filename.min.css
"start:": "WEBPACK_ENV=dev ./node_modules/.bin/webpack-dev-server --progress --colors & npm run build:css --w
```
but the problem is  that it will generated unminified css in the dist folder
how could i generate minified css in that file should i write another script ?

**Comment by Siddharth-ss42279** [comment]
@Abhisheknanda1344463 @artf  i also did same but i did not get minified css

**Comment by artf** [comment]
@Abhisheknanda1344463 @Siddharth-ss42279 guys... it's not difficult... look here https://github.com/artf/grapesjs/blob/dev/package.json#L105 
there is an option... `--output-style compressed` come on...
