### ISSUE TITLE
Why Text element converted into box ??

### ISSUE THREAD

**Issue by Siddharth-ss42279** [artf/grapesjs#1408]
Hi @artf ,

I am using grapesjs newsletter plugin with ckeditor plugin. I dragged TEXT element in canvas and did some editing with ckeditor. i have connected it to database. when ever i save content  in database after reloding the editor i set content value from database field and after that TEXT element get converted into BOX. 
 dont know why TEXT element is changing to BOX and also ckeditor in not loading in that BOX element ?? Please help me out in this. 
 
![screen shot 2018-09-06 at 6 47 41 pm](https://user-images.githubusercontent.com/13647531/45159639-f7b13800-b204-11e8-82b3-8231b43b0fb9.png)

**Comment by artf** [comment]
What do you store in your database? The HTML and CSS?

**Comment by Siddharth-ss42279** [comment]
Actually, i get in-lined html using command `editor.Commands.get('gjs-get-inline-html').run(editor)` and saving it to database and for rendering content i am using   `editor.setComponent(content_field)`  

problem is when i render content from database the TEXT element gets converted into BOX element
(only  when i edit some text in that text element using ckeditor) and in BOX element ckeditor in not loading.

Either one of the below can solve my problem :
1.  TEXT element should not get converted into BOX 
2.  or, BOX element should load ckeditor

**Comment by artf** [comment]
@Siddharth-ss42279 If you need to **EDIT** the template created from GrapesJS, you **SHOULD NOT USE ITS HTML**.... you should import its **JSON**... so you're doing it **WRONG**

It's like doing this 
```js
el.addEventListener('click', ...);
someOtheEl.innerHTML = el.innerHTML;
```
and then complaining why your `el` doesn't have click listener anymore... you're just ripping off all the information created by the editor.

Read here: https://grapesjs.com/docs/modules/Storage.html
