### ISSUE TITLE
Component Drag Event

### ISSUE THREAD

**Issue by YashPrince** [artf/grapesjs#1409]
I want to know how can I get that component  from which element is dragged and drop to the other component. I need to add a class if component become empty if element is dragged and droped to the 
outside element. I can get the component which dragged and in which it droped but not from where it dragged. Any Help would be appreciated. 

![dragevent](https://user-images.githubusercontent.com/40828744/45218205-64d7d280-b2c4-11e8-90f2-380b456221a5.png)

**Comment by artf** [comment]
In your case, I think it would be better listen to inner components changes (eg. what if I delete all children components?), but currently, there is no such an event, so I'll try to add it for the next release. It should be something like this
```js
editor.on('component:update:components', component => {
	if(!component.components().length) {
		component.addClass('component--is-empty')
	} else {
		component.removeClass('component--is-empty')	
	}
})
```

**Comment by sakshigarg9** [comment]
@YashPrince how did you get the id of the dragged component and where it was dropped
