### ISSUE TITLE
Adding images, only the first image displays, the others  show in the code but are not displayed.

### ISSUE THREAD

**Issue by altalker** [artf/grapesjs#141]
Adding images using get components,, only the first image displays, the others  show in the code but are not displayed. See example:
   var domc = editor.DomComponents;
   __var comps = domc.getComponents();
   imagecount = Math.floor((Math.random() * 10000) + 1);;
  comps.add("<img class=img" + imagecount.toString() + " src=" + response + "> </img>");
   comps.add("<style>.img" + imagecount.toString() + "{width:35%} </style>");

However, add components works fine:  var comp1 = domc.addComponent({
                                tagName: 'img',...

**Comment by artf** [comment]
This what `addComponent` does under the hood:
```js
addComponent(component) {
  return this.getComponents().add(component);
}
``` 
so I think you're doing something wrong from your side (maybe because in your example you add 1 image...)
