### ISSUE TITLE
[Bug]: Don't mess with onbeforeunload unless user wants to

### ISSUE THREAD

**Issue by dsgh** [artf/grapesjs#1416]
I have my own `window.onbeforeunload` handler, and I'm not passing in a `noticeOnUnload` config to grapesjs, so I wouldn't expect grapesjs to mess with it.

PR for this incoming.

**Comment by artf** [comment]
Thanks Duarte, fix applied and will be available in the next release

> I'm not passing in a noticeOnUnload config to grapesjs, so I wouldn't expect grapesjs to mess with it.

Just a note, `noticeOnUnload` is `true` by default 😬

**Comment by dsgh** [comment]
Oops, I meant I'm passing a `noticeOnUnload` as `false` 😁

Thanks!
