### ISSUE TITLE
Your webpage has a glitch

### ISSUE THREAD

**Issue by Cosmograph** [artf/grapesjs#1419]
The glitch is quite ironic. It's in "https://grapesjs.com/". It's in the section "Responsive design"; almost half of the image - is beyond my screen's border to the right. I tried on Pale-Moon and the newest FireFox. There isn't even a slider to see the whole image.

P.S. I hope this is the right place to post this; if no - tell me.

**Comment by nojacko** [comment]
I don't think that's a glitch. It's quite a common thing for that style of "text next to image" designs. On small screens you still get to see the editor with a mobile sized canvas and on big screens you get to see more. Importantly, nothing is lost for mobile users... responsive done right. 😉

**Comment by Cosmograph** [comment]
I'm not talking about the editor (in which also - part of the text is not visible); rather about your index page (see the link I posted).
P.S. - it's true also for some other wide images on that page.

**Comment by nojacko** [comment]
Yeah, index page looks fine to me. I'm not the creator or a member of the project... just a user.

**Comment by artf** [comment]
@Cosmograph welcome to the strange world of web design 😂
![schermata 2018-09-15 alle 14 52 12](https://user-images.githubusercontent.com/11614725/45586392-198e7700-b8f7-11e8-8da2-a8b1f0902d48.png)
![schermata 2018-09-15 alle 14 58 11](https://user-images.githubusercontent.com/11614725/45586460-062fdb80-b8f8-11e8-9eaa-7122b5eb7a9e.png)
![schermata 2018-09-15 alle 14 59 48](https://user-images.githubusercontent.com/11614725/45586465-0b8d2600-b8f8-11e8-94d5-bdd7c3c43987.png)

**Comment by Cosmograph** [comment]
@artf - more like - the strange world of humans.
