### ISSUE TITLE
Customizing Block(section block) While Dragging it

### ISSUE THREAD

**Issue by sureshDurai123** [artf/grapesjs#1420]
Hi I have seen that there was two separate blocks to add 'sections' and 'columns'.We have a flow like when we drag a section into canvas  need to show a popup on that we manually able select the section to be one column section/two column  section,how do we achieve this.

And also we have seen the method editor.on('component:selected'  which is triggered while dropping the block ,Is we need to use this to customize the section separation then how we do this.

Thanks in advance

**Comment by nojacko** [comment]
If your sections always require 1 or 2 columns, why not remove the section and column blocks, instead, add new blocks for "section with 1 column" and "section with 2 columns" and save the popup?

**Comment by sureshDurai123** [comment]
Yeah it is possible only .But we have the requirement that we need to show single section to customer  and based their pick in popup only we need to split it.

**Comment by nojacko** [comment]
Ok. In that case, it's the `canvas:drop` event. Hook into that, check it's a section and open your modal. I'm not sure on how you insert the columns but hope this helps.

```
    editor.on('canvas:drop', (dataTransfer, model) => {
        if (model.is('section')) { // <-- might not be called 'section' 
            // Open your modal and do your thing...
        }
    });
```

**Comment by sureshDurai123** [comment]
yes using this function i need to open the model ,but i don't know how  to add columns to this model.please give some suggestions.

**Comment by artf** [comment]
I would suggest creating a [new component](https://grapesjs.com/docs/modules/Components.html), add a new property (eg. `columns`), listen to `change:columns` and update them accordingly to the requested number (check methods available in the [Component](https://grapesjs.com/docs/api/component.html)).
For the modal opening I'd suggest another approach. The Block Manager can trigger `active` event on dropped blocks:
```js
blockManager.add('your-block', {
	  activate: true,
      label: 'Some Block',
      content: '<div>...</div>',
    });
```
Now you add `onActive` method in your Component's view
```js
view: ... {
	...
	onActive() {
		const { em, model } = this;
		const Modal = em.get('Modal');

		// Definitly you'd need some element which shows your UI 
		// for column selecting, it might be already in the document
		// or you can create it at runtime
		const yourPanelElement = '...';
		
		// Then you would attach an event (click/submit) on some element
		// which should update the model.
		// I use jquery-like API just to make more readible
		yourPanelElement.find('.some-button').on('click', () => {
			// Find the data you need
			const columns = ...;
			model.set({ columns });
			Modal.close();
		})	
		
		Modal.open({
			title: 'Select the number of columns',
			content: yourPanelElement,
		});
	}
},
```
In this way the logic for the Modal is insde the component itself and you can re-use it later (eg. by double-cliking on the component or selecting some command from the component's toolbar)
