### ISSUE TITLE
[Bug]: "disabled" instead of "active" class for Panel Button View

### ISSUE THREAD

**Issue by Valodya** [artf/grapesjs#1421]
Hello

I assume there is a bug with class when Panel Button is disabled

https://github.com/artf/grapesjs/blob/dev/src/panels/view/ButtonView.js#L22

**Comment by artf** [comment]
Yeap, the fix is ready for the next release. Thanks

**Comment by Valodya** [comment]
thanks @artf for the answer, 
do you have any estimate when it will be released?

**Comment by artf** [comment]
Probably during next week

**Comment by Valodya** [comment]
sounds great!
thanks you again =)

**Comment by AksharaKarikalan** [comment]
Hi artf!
 I need help in disabling panel button's active state and its color after button's pop up is functioned. Is their any way to do that?
Like for example: If i click view code button in panel - it should first enabled and open the pop-up, then after i clicking some operation like export to zip or close it should disable view code button's active state and its color. Thanks!
