### ISSUE TITLE
[BUG] Property without units slider

### ISSUE THREAD

**Issue by FrciSmrci** [artf/grapesjs#1422]
Hey @artf,

as already mentioned in this closed [ticket](https://github.com/artf/grapesjs/issues/1391) => I think that this specific [enhancement](https://github.com/artf/grapesjs/commit/d29274f0afd95bdb13f80b6598c7a16ed11b5e4e) broke the behaviour of properties without units, like Opacity. The slider behaves weirdly in this case, even on the [GrapesJS demo](https://grapesjs.com/demo.html).

Thank you in advance.

**Comment by artf** [comment]
You're right, I think I should use `parseFloat` here, will be fixed in the next release
