### ISSUE TITLE
Properties Validate of elements

### ISSUE THREAD

**Issue by YashPrince** [artf/grapesjs#1425]
@Arif How can we validate the properties for the grapejs element like background color
We have given an option for manual  background entry as well as color picker . If user 
did not add valid css then style break and preview page is not working properly.
Any help would be appreciated.

![error1](https://user-images.githubusercontent.com/40828744/45547093-32d2ed00-b83d-11e8-8516-7994ff9321ec.png)
![error2](https://user-images.githubusercontent.com/40828744/45547094-34041a00-b83d-11e8-8847-00abf5e563cc.png)
![error3](https://user-images.githubusercontent.com/40828744/45547097-36667400-b83d-11e8-825e-b4a85298f1e6.png)

**Comment by artf** [comment]
There is no built-in functionality for such a thing but keep in mind that once you render the style manager, all the elements, even when not visible, are still reachable via DOM, so you can add your validation logic post render
