### ISSUE TITLE
Make some element unediatble by default.

### ISSUE THREAD

**Issue by YashPrince** [artf/grapesjs#1426]
@artf how can we set some configuration so that while importing html in editor it will not consider some element as text component and it should consider as inside text of the parent. 
eg.`. <p> here is some example text.<span> Do not make it as text component </span> Example text 2 </p>`
I don't want to make span as text component as P is already editable. I can not set data-js-editable as false. because it need to 
update multiple places. So I want to know that there is any way where I can put that span like element 
will not convert to text component. 
Thank You!

**Comment by artf** [comment]
[Extend](https://grapesjs.com/docs/modules/Components.html#update-component-type) the `text` component type and implement your logic in `isComponent`. If the element meets your conditions (you would probably check for inner elements) just return the object in this way
```js
isComponent(el) {
	// ...
	if (isWhatYouNeed) {
		return {
			type: 'text',		
			content: el.innerHTML,
			components: [], 
			// By putting components you prevent the parser 
			// from going deeper traversing of your DOM elements
		}
	}
},
```
