### ISSUE TITLE
some paragraphs are not badgable and hoverable

### ISSUE THREAD

**Issue by chiqui3d** [artf/grapesjs#1427]
I'm testing the editor on a particular template with Boostrap 4 using flex, but I realized that some paragraphs do not show the badge correctly, I'm going to put here the demo [https://jsfiddle.net/kf5n9sdq/31/](https://jsfiddle.net/kf5n9sdq/31/), I've given myself that if I delete the main image if you can select, but I do not really understand what happens, because the image I need where it is, I have also tried modifying the styles and continues to do the same.

Ah, the paragraphs I'm referring to are all those after the featured image.

**Comment by juanj** [comment]
It looks like it have something to do with the scroll. If you scroll, the blue selection box shows where the paragraph was at the start. I don't think it have anything to do with the image. Even if you delete the image and scroll you get the same result.
