### ISSUE TITLE
Empty content when load from remote storage if components array is not empty

### ISSUE THREAD

**Issue by iainheng** [artf/grapesjs#1429]
I have problem loading stored remote content into the editor when the `JSON` contains non empty `gjs-components`

My JSON data looks like this which is very basic blockquote with a sentence of text
![image](https://user-images.githubusercontent.com/3263759/45588987-5b97d700-b950-11e8-9568-73fda5ca19cb.png)

Example response when calling my remote endpoint 
![image](https://user-images.githubusercontent.com/3263759/45589049-728af900-b951-11e8-9fc0-d8f1d55d1c31.png)

I am able to load the content if I set `gjs-components: ""` and it will load the `gjs-html` fine into the editor. 

And here is my current storage management configuration

![image](https://user-images.githubusercontent.com/3263759/45589054-99492f80-b951-11e8-997d-2822b0a45f95.png)

Trying to search for solution for few hours without any success. 😥

Any help will be very much appreciated.

**Comment by iainheng** [comment]
@artf Thanks for your help. 😊 It is a bug indeed. I store the `gjs-components` as a string and it is working now. 🎉

This is the same data store as string 
![image](https://user-images.githubusercontent.com/3263759/45592738-3a62d500-b9a8-11e8-9a53-5fbb912a9f68.png)

**Comment by artf** [comment]
Thanks @iainheng, for now, keep it like this until the next release (hope to push it the next week)
