### ISSUE TITLE
[Question] How to get value of "traits"?

### ISSUE THREAD

**Issue by fzs1994** [artf/grapesjs#143]
My code:

```
model: defaultModel.extend({
      init() {
        this.listenTo(this, 'change:url', this.doStuff);
      },

      doStuff() {
        console.log("change");
        console.log(this.model.value);
      },
```

Thanks!

**Comment by artf** [comment]
```js
doStuff() {
 this.get('traits').each(function(trait){
   console.log(trait.get('value'));
 });
},
```

**Comment by fzs1994** [comment]
Works like butter...!!!
Thanks!

**Comment by fzs1994** [comment]
How about getting particular named trait?:innocent:

**Comment by artf** [comment]
this should work:
```js
this.get('traits').where({name: '...'})[0].get('value')
```

**Comment by fzs1994** [comment]
`Uncaught TypeError: this.get is not a function`

**Comment by artf** [comment]
Check if the mode is actually returned `this.get('traits').where({name: '...'})[0]`, you might passed a wrong name

**Comment by fzs1994** [comment]
I checked all. Didn't worked. Same error. But I got it working for now by pushing values into array.
Thanks for the help.

**Comment by HarshOB** [comment]
How to get the value of a particular or single trait?

**Comment by artf** [comment]
@HarshOB just like above
```js
componentModel.get('traits').where({name: 'TRAIT-NAME'})[0].get('value')
```

**Comment by Geczy** [comment]
And if you don't have selected component context, here's how I get all values of a type:

```js
window.grapesjs.editors[0].getComponents().models.filter(_ => _.attributes.type === 'facebook-messenger').forEach(_ => {
    console.log(_.get('traits').where({
        name: 'campaign'
    })[0].get('value'))
})
```

**Comment by nethzor** [comment]
> And if you don't have selected component context, here's how I get all values of a type:
> 
> ```js
> window.grapesjs.editors[0]
>   .getComponents()
>   .models.filter(_ => _.attributes.type === 'facebook-messenger')
>   .forEach(_ => {
>     console.log(
>       _.get('traits')
>         .where({
>           name: 'campaign',
>         })[0]
>         .get('value')
>     )
>   })
> ```

One year later, I cannot seem to get this to work.

@artf, how do we get and set traits of a specific type?
