### ISSUE TITLE
Load HTML file from remote

### ISSUE THREAD

**Issue by mrajeshkrossark** [artf/grapesjs#1431]
I hosted my html content in cloud. Then trying to load the html content in the editor I found the error:  "**Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.**"

My code: const editor = () => grapesjs.init({
    container: '#editor-portal',
    canvas: {
        styles: ['https://codepen.io/mrajeshkrossark/pen/mGLyJX.css']
    },
    plugins: ['gjs-preset-webpage'],
    pluginsOpts: {
		"gjs-components":[]
	},
    storageManager: {
        type: 'remote',
        storeHtml: true,
        storeCss: true,
        urlStore: "http://www.lightblue.byethost4.com",
        urlLoad: "http://www.lightblue.byethost4.com",
        params: {},
    }
});

Note: I wrapped the grapesjs editor into react application.

**Comment by cjpollard** [comment]
You're pointing your storage manager to a website.  You need endpoints that can handle the requests. https://grapesjs.com/docs/modules/Storage.html#setup-remote-storage

**Comment by mrajeshkrossark** [comment]
> You're pointing your storage manager to a website. You need endpoints that can handle the requests. https://grapesjs.com/docs/modules/Storage.html#setup-remote-storage

Any example please..

**Comment by JulyanoF** [comment]
> > You're pointing your storage manager to a website. You need endpoints that can handle the requests. https://grapesjs.com/docs/modules/Storage.html#setup-remote-storage
> 
> I tried with below endpoints that also shows error
> storageManager: {
> type: 'remote',
> storeHtml: true,
> storeCss: true,
> contentTypeHTML: true,
> urlStore: "http://www.lightblue.byethost4.com/index.html",
> urlLoad: "http://www.lightblue.byethost4.com/index.html",
> params: {},
> }

I use a json content and it is working:
```
storageManager: {
        autosave: true,
        setStepsBeforeSave: 2,
        type: 'remote',
        urlStore: 'comunicados/store' + id,
        urlLoad: 'comunicados/load' + id,,
        contentTypeJson: true,
    },
```

**Comment by artf** [comment]
@mrajeshkrossark `contentTypeHTML`?!? I don't think guessing options will help you here. 

> I tried with below endpoints that also shows error
storageManager: {
type: 'remote',
storeHtml: true,
storeCss: true,
contentTypeHTML: true,
urlStore: "http://www.lightblue.byethost4.com/index.html",
urlLoad: "http://www.lightblue.byethost4.com/index.html",
params: {},
}

mmm nope, it doesn't work like this, those should be enpoints, usually a server-side script result, not simple HTML files.

**Comment by mrajeshkrossark** [comment]
I did with endpoint this time but no luck. 

**storageManager: {
type: 'remote',
autoLoad: 1,
urlLoad: "http://loyal-throne-215410.appspot.com/renderstaticwebsite",
params: {},
}**

**Comment by artf** [comment]
@mrajeshkrossark the problem is still your endpoint, it's an HTML document, you have to return an `application/json` like this:
```js
{
	"gjs-components": ...,
	"gjs-style": ...
}
```
Read this please: https://grapesjs.com/docs/modules/Storage.html#store-and-load-templates

**Comment by mrajeshkrossark** [comment]
> @mrajeshkrossark the problem is still your endpoint, it's an HTML document, you have to return an `application/json` like this:
> 
> ```js
> {
> 	"gjs-components": ...,
> 	"gjs-style": ...
> }
> ```
> 
> Read this please: https://grapesjs.com/docs/modules/Storage.html#store-and-load-templates

It's working @artf. Thanks for the reply and helped me to correct this issue.
