### ISSUE TITLE
Toolbar on hover

### ISSUE THREAD

**Issue by YashPrince** [artf/grapesjs#1433]
@artf how can we show toolbar on hover. Currently toolbar is open when we select any element but I want to show it on hover. Any help would be appreciated.
![toolbarpostion](https://user-images.githubusercontent.com/40828744/45635174-f19f3f00-bac1-11e8-95e5-c988d27f8531.png)

**Comment by artf** [comment]
The only way I can help you here is to tell you to check this command https://github.com/artf/grapesjs/blob/dev/src/commands/view/SelectComponent.js (id of the command: `select-comp`) which is responsible for showing the toolbar. So you can try to use [Commands API](https://grapesjs.com/docs/api/commands.html) to extend it

**Comment by sakshigarg9** [comment]
@YashPrince Hi, were you able to solve this? I need a similar implementation

**Comment by limbobark** [comment]
@sakshigarg9 ,
```js
editor.Commands.extend('select-comp', {
        onHovered(em, component) {
          const trg = component && component.getEl();
          if (trg) {
            const pos = this.getElementPos(trg);
            this.updateBadge(trg, pos);
            this.updateToolbar(component); // show toolbar
            this.updateHighlighter(trg, pos);
            this.showElementOffset(trg, pos);
          }
        },
      });
```

**Comment by ashercoren** [comment]
This doesn't seem to work anymore

**Comment by zauchad** [comment]
I just figured out solution with invoking select event on editor, it's doing slightly more than opening toolbar (additionally selects component), but for my case its perfect fit ;)

`
editor.Commands.extend('select-comp', {
        onHovered(em, component) {
            if (component && component.getEl()) {
                if (!editor.getSelected()) {
                    editor.select(component);
                } else if (editor.getSelected().getId() !== component.getId()) {
                    editor.select(component);
                }
            }
        },
    });
`

**Comment by surya492** [comment]
this.updateToolbar(component); // show toolbar -- it is not showing the toolbar.
            this.updateHighlighter(trg, pos); -- this is throwing the error in reactjs application.
Please let me know, is there anyone made changes for this?

**Comment by vladninja** [comment]
> I just figured out solution with invoking select event on editor, it's doing slightly more than opening toolbar (additionally selects component), but for my case its ok.
> 
> ```
> editor.Commands.extend('select-comp', {
>     onHovered(em, component) {
>         if (component && component.getEl()) {
>             if (!editor.getSelected()) {
>                 editor.select(component);
>             } else if (editor.getSelected().getId() !== component.getId()) {
>                 editor.select(component);
>             }
>         }
>     },
> });
> ```

Additionally, there is no block name visible on hover

**Comment by surya492** [comment]
@vladninja- Thank you for reply. but I'm looking for only onHover. in my case it is not acceptable to select event for hover event.
