### ISSUE TITLE
Toolbar Hide text element

### ISSUE THREAD

**Issue by YashPrince** [artf/grapesjs#1434]
@artf Please check you demo page text is hiding under the toolbar. how can we update the toolbar position?

![toolbarissue](https://user-images.githubusercontent.com/40828744/45635311-493daa80-bac2-11e8-9407-eb17dcb8205c.png)

**Comment by artf** [comment]
At the moment the position is [hard-coded](https://github.com/artf/grapesjs/blob/dev/src/commands/view/SelectComponent.js#L519) but we can extend it as [we do with the RTE toolbar via events](https://github.com/artf/grapesjs/blob/dev/src/rich_text_editor/index.js#L237-L239)

**Comment by artf** [comment]
Closed by https://github.com/artf/grapesjs/pull/1730
