### ISSUE TITLE
[BUG] - Checkbox Traits are not rendered correctly

### ISSUE THREAD

**Issue by benschiefer** [artf/grapesjs#1435]
Checkbox type traits are not getting shown as "checked" in the component settings.

To reproduce:
1. Import markup
```
<input type="checkbox" checked />
```
2. Select the input element in the canvas
3. Go to Component Settings
4. Notice that the Checked setting is not checked.

The same issue can be noticed for the "required" attribute.

Similarly, if you import
```
<input required />
```
or
```
<input required=""/>
```
or
```
<input required="required"/>
```

the component settings do not properly show that element as being Required.

Expectation: If the attribute is present, and its value is an empty string or a value that is an ASCII case-insensitive match for the attribute’s canonical name, with no leading or trailing white space, then the Checkbox in component settings should be CHECKED

**Comment by artf** [comment]
Should be fixed with the latest https://github.com/artf/grapesjs/releases/tag/v0.14.33 and https://github.com/artf/grapesjs-plugin-forms/releases/tag/v1.0.1 (changed the name of the plugin `gjs-plugin-forms` -> `grapesjs-plugin-forms`)
