### ISSUE TITLE
[Question] How to change a built-in trait?

### ISSUE THREAD

**Issue by rgcarrasqueira** [artf/grapesjs#144]
Hi Arthur!

I'm trying to translate some built-in traits, like that

![screen shot 2017-07-06 at 18 47 23](https://user-images.githubusercontent.com/97540/27934331-974bc996-627b-11e7-9411-9d2f2396d750.png)

This is a built-in trait inside grapesjs

I'm doing:
```
var editor = grapesjs.init({
(..)
traitManager:{

     labelContainer: 'Configurações de Componentes',
     traits: [{
            name: 'title',
            placeholder: 'Insira um texto aqui'
     }],
},
(...)
})
```

And no change effects on this.

Any clue, on how to deal with it?

P.s: this editor is awesome!

**Comment by artf** [comment]
thanks @rgcarrasqueira for pointing this out, those traits actually should not be there (I think I left them just for a demo purpose), the base component has to be as dry as possible. The correct behavior is to extend those components you want to be attached with custom traits. In this case you might want to extend the default one:
```js
var domc = editor.DomComponents;
var defaultType = domc.getType('default');
var defaultModel = defaultType.model;
var defaultView = defaultType.view;

    domc.addType('default', {
      model: defaultModel.extend({
        defaults: Object.assign({}, defaultModel.prototype.defaults, {
          traits: [{
            name: 'title',
            label: 'Título',
            placeholder: 'Insira um texto aqui'
          }]
        }),
      }),
    });
```
