### ISSUE TITLE
How to listen for changes to the selection box in Traits 

### ISSUE THREAD

**Issue by ionic666** [artf/grapesjs#1440]
![1](https://user-images.githubusercontent.com/36065691/45727423-4643d680-bbf6-11e8-9ab7-eb6954d0311f.png)
![2018-09-19_102259](https://user-images.githubusercontent.com/36065691/45727426-48a63080-bbf6-11e8-96f1-b9b448e9d4ac.png)
![3](https://user-images.githubusercontent.com/36065691/45727429-49d75d80-bbf6-11e8-8e71-c9406ebf0a71.png)
i just want to listen for changes to the selection box,but i can't enter the function updateType

**Comment by JulyanoF** [comment]
@ionic666 I guess you will need to create a custom trait:
[https://github.com/artf/grapesjs/wiki/Traits#define-new-trait-type](https://github.com/artf/grapesjs/wiki/Traits#define-new-trait-type)

**Comment by artf** [comment]
not having `changeProp: 1`, it will be a simple attribute, so you have listen to: `change:attributes:data-sensor`
