### ISSUE TITLE
How to generate uniminified file of js?

### ISSUE THREAD

**Issue by Abhisheknanda1344463** [artf/grapesjs#1444]
Hi @artf 
Can you please tell me.How to generate readable unminified javascript file like when i do `npm run build` i get only  minified file(grapesjs-preset-newsletter.min.js) in dist folder

I want to get unminified file in dist folder for newsletter plugin and in grapesjs "**grapes.js"** is present i want to generate same for newsletter plugin

**Comment by artf** [comment]
`npm run build-dev`
