### ISSUE TITLE
Child component not selectable when using custom view

### ISSUE THREAD

**Issue by prestonkscott** [artf/grapesjs#1448]
I'm trying to create a custom component that creates it's own view with nested HTML.  I do not want this HTML to be rendered as a component so I use (using jQuery)

    view: defaultType.view.extend({
      init: function () {
        $(this.el).html('<div class="container"></div>');
      },
      getChildrenSelector: function () {
        return '.container';
      },
    })

But, if I add child components, they are not selectable through the editor. They can only be selected through the Layer panel.  I've created a jsFiddle of the issue: https://jsfiddle.net/pscott/72xgqkdy/

I've found that if I remove the 'pointer-events' style from the parent, the child components become selectable BUT the parent can no longer be hovered and it's badge no longer displays.

    onRender: function () {
      $(this.el).find(this.getChildrenContainer()).css('pointer-events', '');
    }

What's the correct way to create a custom view for a component?  Should I be using `getChildrenContainer`?

**Comment by artf** [comment]
If you add elements via View you can't select them, only Models can be selectable
Read this page https://grapesjs.com/docs/modules/Components.html you also create new types without `isComponent`

**Comment by artf** [comment]
Ok, now I got it. The `getChildrenContainer` should work as you expect, I'll just try to remove those `pointer-events` stuff and make the `hover` work more like the `select`.
BTW you don't need jquery, grapesjs under the hood uses cash (which has jquery-like API) so you can do:
`this.$el.html('...');`
There is also a method to get the children container
`this.getChildrenContainer().style....`
