### ISSUE TITLE
[Question] List of events editor

### ISSUE THREAD

**Issue by bungambohlah** [artf/grapesjs#145]
Hi, can you give me reference or list of events in the editor?
There is no name of events in your wiki.
Thank you and sorry for my bad english or grammar.
Poke @artf

**Comment by derblub** [comment]
I'd like to add:  
Currently, I couldn't find an event to trigger the `store` method, when `autosave: false`.
Can you recommend a different way to trigger a storage-save, without having to manually read/pass data?

**Comment by artf** [comment]
@bungambohlah I have not yet defined a public list but you can keep track of them in the [Editor](https://github.com/artf/grapesjs/blob/dev/src/editor/index.js#L33)

@derblub you can use `editor.store()` method
