### ISSUE TITLE
[QUESTIONS] Devices panel appendTo

### ISSUE THREAD

**Issue by besingamkb** [artf/grapesjs#1450]
Hi Everyone.

I manage to redesign the grapesjs editor by using `appendTo` on the `styleManager`, `layerManager` and `blockManager` on its own division. I also use the `grapesjs-preset-newsletter`. But the device panel is still stick on the editor workspace. 
![screenshot_21](https://user-images.githubusercontent.com/6380139/45912408-41c82980-be53-11e8-9383-3e5dc99a9275.png)

Is it possible to append on its own division? and I also notice. Some buttons is not showing. 
![screenshot_22](https://user-images.githubusercontent.com/6380139/45912425-8eac0000-be53-11e8-9247-7b0a1159f887.png)

I guess those buttons  just not appended? im not sure. Can I also use `appendTo` option to append it to its own division? Please see my code below.

```js
var editor = grapesjs.init({
    container: '#gjs2',
    height: '500px',
    fromElement: true,
    storageManager: {type: 0},
    plugins: ['gjs-preset-newsletter'],
    layerManager: {
        appendTo: '#layers-container'
    },

    blockManager: {
        appendTo: '#blocks'
    },

    styleManager: {
        appendTo: '#style-manager-container'
    },


    selectorManager: {
        appendTo: '#selectors-container'
    },

    traitManager: {
        appendTo: '#traits-container'
    },

    panels: {
        defaults: [{
            id: 'layers',
            el: '#layers',
            resizable: {
                tc: 0,
                cr: 1,
                bc: 0,
                keyWidth: ''
            }
        },

            {
                id: 'styles',
                el: '#style-manager',
                resizable: {
                    tc: 0,
                    cr: 0,
                    cl: 1,
                    bc: 0,
                    keyWidth: ''
                }
            }]
    }
});
```
I base on the codepen example by the author.

Thank you guys. I hope someone can help me on this.

**Comment by artf** [comment]
Device buttons are inserted by `grapesjs-preset-newsletter`, you have to move them on `load` via JS
