### ISSUE TITLE
npm start not work at version 0.14.33

### ISSUE THREAD

**Issue by Gyanxie** [artf/grapesjs#1456]
### I downloaded source by zip,  and run 'npm i', but I can't run 'npm start'.  Here is how I fixed the problem.
- It works when I change package.json

before:
```
 "start": "npm run build:css -- -w & webpack-dev-server --open --progress --colors",
```
after:
```
"start": "npm run build:css -w & webpack-dev-server --open --progress --colors",
```

**Comment by artf** [comment]
Ok but `-- -w` is intended for the watch on CSS files, with your change, I think it will not work. (I guess you're using Windows)

Probably we should do something like this to make it run cross-platform:
```js
 "start": "npm run build:css:dev & webpack-dev-server --open --progress --colors",
 "build:css:dev": "node-sass src/styles/scss/main.scss dist/css/grapes.min.css --output-style compressed -w",
```
Please @Gyanxie try it and let me know if it works

**Comment by Gyanxie** [comment]
@artf 
I has run 'npm list', if it is necessary. 
[npmList.txt](https://github.com/artf/grapesjs/files/2421995/npmList.txt)

**Comment by artf** [comment]
> I have just try it with your change, but not works

What happens there? Nothing? It should work, try to understand why watch doesn't work with your node-sass (eg. maybe you just have to place `-w` before or using `--watch` instead)

**Comment by Gyanxie** [comment]
@artf 
I try all the command
```
"build:css:dev": "node-sass src/styles/scss/main.scss dist/css/grapes.min.css --output-style compressed -w"
```

```
"build:css:dev": "node-sass src/styles/scss/main.scss dist/css/grapes.min.css --output-style compressed -watch"
```

```
"build:css:dev": "node-sass  --watch src/styles/scss/main.scss dist/css/grapes.min.css --output-style compressed"
```

```
"build:css:dev": "node-sass  --w src/styles/scss/main.scss dist/css/grapes.min.css --output-style compressed"
```

- And when I change this file 'main.scss' , node-sass has compile with all of those command. the compile looks like
![image](https://user-images.githubusercontent.com/16382366/46117076-c17a3d80-c231-11e8-8b77-5cc1d314e3d1.png)

- I guess when 'node-sass' watches files, the command 'npm run build:css:dev' has not finshed. That  is why the 'cmd' command  '&' not works

**Comment by artf** [comment]
Ok, I forgot that `&` works differently in Windows. I'll add some lib to manage that in the next release
