### ISSUE TITLE
[Question]: Custom asset manager background-image in Style Manager

### ISSUE THREAD

**Issue by Stejsi** [artf/grapesjs#1457]
Hello,
i want to use custom Asset Manager
i am used this solution, 
`
var assettarget ='';

    editor.Commands.add('open-assets', {

        run(editor, sender, opts = {})  {

            const modal = editor.Modal;
            const styleManager = editor.styleManager;
            assettarget = opts.target;
            modal.setTitle('Add new image');
            var $test = $("<iframe style='width: 100%; height: calc(100vh - 60px);' src='http://192.168.0.227:45678/weby/fb/filemanager/dialog.php?editor=tinymce&type=1&lang=cs&popup=0&crossdomain=0&relative_url=0&akey=key&fldr=%2F&5ba947c59de97'>test</iframe>");
            $test.on("load", function () {
            
                var iframe = $(this).contents();
                iframe.find('.file').on("click",function(event){
                    var path = $(this).find("img").attr("data-src");
                    path = path.replace("../","./");
                    assettarget.set('src', path);

                });

            })
            
            modal.setContent($test);
            modal.open();
        }
    });

and it works, but now i **am not able to asset background-image in Style Manager**.
It use custom function spreadUrl(), but i dont know how to call it without modify Grapesjs core.
Thanks for help!

**Comment by artf** [comment]
@Stejsi inside `opts` you have `onSelect` callback which should update stuff in Style Manager. Unfortunately, it only accepts asset (object) as the argument (my bad, I'll make it also understand strings) so, for now you have to do this
```js
const fakeAsset = { get: () => path };
opts.onSelect(fakeAsset);
```
