### ISSUE TITLE
Embeded Jquery events in the grapesjs editor not working as expected.

### ISSUE THREAD

**Issue by mrajeshkrossark** [artf/grapesjs#1458]
@artf , I tried to embed my template into the grapesjs editor. The issue am getting is the editor not working as expected with that template.
Note: Am using react app for wrapping the grapesjs editor.

Initially the editor embeded my template and it is look like below image

![untitled](https://user-images.githubusercontent.com/22819712/46062687-2f6a2a80-c188-11e8-9de1-3714af7a08b0.png)

I used Parallax effects for my template. The issue is when I click first time on the navigation bar, it reacts differently and load one more editor iniside the existing editor. 

![untitled](https://user-images.githubusercontent.com/22819712/46062604-f762e780-c187-11e8-8fef-fa3ff2c4ce64.png)

The error is:
`Uncaught TypeError: Cannot read property '_cash1537883139698' of undefined -- grapesjs:6506`

the below javascript code using inside the editor:

```
<script type="text/javascript">	
		$(document).ready(function () {
			/*
			* Plugin intialization
			*/
			$('#pagepiling').pagepiling({
				menu: '#menu',
				anchors: ['VP', 'about', 'insurances-accepted', 'specialties', 'patient-reviews', 'contact'],
				sectionsColor: ['#fff', '#fff', '#fff', '#fff', '#fff', '#fff'],
				navigation: {
					'position': 'left',					
				},
				afterRender: function () {

					$('#pp-nav').addClass('custom');
				},
				afterLoad: function (anchorLink, index) {
					$("#title").text(anchorLink);
					if (index > 1) {
						$('#pp-nav').removeClass('custom');
					} else {
						$('#pp-nav').addClass('custom');
					}
				},
			});
			$('#toggle').click(function () {
			$(this).toggleClass('active');
			$('#overlay').toggleClass('open');
			});
		});

	</script>
```

**Comment by artf** [comment]
Please a create a live demo of the issue
