### ISSUE TITLE
Hide Trait Element

### ISSUE THREAD

**Issue by YashPrince** [artf/grapesjs#1460]
How can I hide a trait element while creating a trait for the component.

```
 traits: [ {
                            label: "XYZ",
                            name: "xyz",
                            defaults:0,
                            changeProp: 1,
                            type: 'text',
                            min:0
     }]
```

Is there any way like display:none or hidden:1. How can I show or hide any trait,  Any help would be appreciated.

**Comment by artf** [comment]
You can pass something like this `attributes: {style: 'display: none'}`
