### ISSUE TITLE
how to disable gjs-hoverable class from elements

### ISSUE THREAD

**Issue by Abhisheknanda1344463** [artf/grapesjs#1463]
hi @artf  
 i am using your boilerplate plugin and i want to disable hoverable property from all the elements as screenshot below yellow area appearing on hover
 i tried to do this 
` const updateAll = model => {
        model.set({hoverable:false});
        model.get('components').each(model => updateAll(model));
    }
    updateAll(editor.DomComponents.getWrapper());
`
It stops hoverable property  only for wrapper.
Can you tell me  how to stop  that property for all the elements  ?
Thanks
![screen shot 2018-09-27 at 11 35 31 am](https://user-images.githubusercontent.com/20657737/46126315-6274f280-c24a-11e8-91c8-a6c2ea07c5f5.png)

**Comment by artf** [comment]
@Abhisheknanda1344463 if you see "yellow area" probably because you're using `showOffsets: true` in your configurations (default is `false`)
