### ISSUE TITLE
Customizing  the Component Position

### ISSUE THREAD

**Issue by sureshDurai123** [artf/grapesjs#1464]
First of all thank you guys for this awesome library,

And I have one Clarification  that is how do i customize the drop position  example if i drag a text field into Canvas it will look like - (below reference image 1)

And want to Customize the position of that text  by simply Dragging it from left to right or right to left.In Reference image 2 you see the position of text is Right most this done by using column,Instead of using column how do i customize the text field Position(vertically or horizontally) Simply by Dragging it(moving across canvas).

Thanks in Advance.

![ss1](https://user-images.githubusercontent.com/35071500/46142259-0921b900-c274-11e8-9752-564aa8dcf922.png)

![ss2](https://user-images.githubusercontent.com/35071500/46142596-1d19ea80-c275-11e8-8809-f787194cc247.png)

**Comment by artf** [comment]
The "Designer mode" is not yet available but planned in the Roadmap (#74)
