### ISSUE TITLE
How to create the custom undo manager

### ISSUE THREAD

**Issue by Deepak813** [artf/grapesjs#1465]
Hi @artf,

How we can create the custom undo manager on button click.All the changes need to add in undo manager and then we can revert back to it.
As we have implemented certain changes in different element due to that certain css is not working.
Like when click on one button i have removed its class so when click on undo button that section class is not added/working.
Can you please help for the same.
Hope for positive response.
Thank you

**Comment by artf** [comment]
There are no built-in methods to add custom undo manager, but you can definitely improve the integration with the default one by opening some PR
