### ISSUE TITLE
[bug] modaltitle no effect

### ISSUE THREAD

**Issue by kornflex** [artf/grapesjs#1468]
Hello,

I can't translate asset manager title to french.
Example : 

 assetManager: {
			storageType: '',
			storeOnChange: true,
			storeAfterUpload: true,
			**modalTitle: 'Gestion des images',**
			uploadText: 'Glisser - déposer les images ici <br><br> <i>(2Mo max par image)</i>',
			addBtnText: 'Ajouter',
...
}

modalTitle is not changed, it's still "Select Image" but uploadText, addBtnText are OK.

Thank you

**Comment by artf** [comment]
I can't reproduce it, provide a live demo please
