### ISSUE TITLE
[Question] Blockmanager and Image

### ISSUE THREAD

**Issue by alfaalex81** [artf/grapesjs#1471]
Hi! I use this code to add a new block:

        blockManager.add("image", {
            label: 'Image',
            category: 'Basic',
            attributes: { class: "gjs-fonts gjs-f-image" },
            content: {
                style: { color: "black" },
                type: "image",
                activeOnRender: 1,
            },
        });

How can add a custom class to the img tag when i drop into canvas?

Thanks.

**Comment by arthuralmeidap** [comment]
@alfaalex81 
  For the `content` object, you can add a new index called `classes`. This index needs to be an array of classes, which will be applied to the new Image block;

Final code:

```
 blockManager.add("image", {
        label: 'Image',
        category: 'Basic',
        attributes: { class: "gjs-fonts gjs-f-image" },
        content: {
            style: { color: "black" },
            type: "image",
            classes: ['class1', 'class2']
            activeOnRender: 1,
        },
    });
```

**Comment by alfaalex81** [comment]
Awesome!

I have another question for the same argument. I need to create a custom block with an image inside, for example: 

	<div>
		<ul>
			<li>
				<div><a href="#link"><img src="" alt="Title Image" /></a></div>
				<a href="#link" >Title</a>
			</li>
		</ul>
	</div>

I add the code with block manager, but on drop into canvas not asset manager doesn't open. Otherwise if I use image type attribute, it ignore my html content, I save an example in js fiddle:

https://jsfiddle.net/fp78yon0/

**Comment by arthuralmeidap** [comment]
This is not the current grapesjs's behavior.  the AssetManager only opens if you dropping directly am img block.

You must have to select the img block within your custom block and execute a code like that:

```
editor.runCommand('open-assets', {
  target: editor.getSelected()
});
```

**Comment by artf** [comment]
> I add the code with block manager, but on drop into canvas asset manager doesn't open

The editor is not able to do that, your HTML code, for example, can contain 10 images, for which should I open the Asset Manager?!?

In your case you have two options:
1. Create a custom component with all the logic to put in activation (`view.onActive` method), so your block would be:
```js
blockManager.add("image", {
		// ...
		activate: 1,
        content: `<div data-gj-type="you-custom-component">...</div>`
    });
```
2. Detect the component via events
```js
blockManager.add("image", {
		// ...
        content: `<div data-custom-attr="1">...</div>`
});

editor.on('block:drag:stop', component => {
	if (component && component.getAttribute()['data-custom-attr']) {
		cons imgComponent = component.find('img')[0];
		imgComponent && imgComponent.trigger('active');
	}
});
```
