### ISSUE TITLE
[BUG] Canvas external CSS

### ISSUE THREAD

**Issue by detectedstealth** [artf/grapesjs#1473]
Comments in canvas/config.js state the external styles are added to the head of the iframe however the code in view/CanvasView.js actually appends the CSS to the body of the iframe.

```
if (externalStyles) {
     body.append(externalStyles);
}
```

Expect it to work how the external scripts do where they are appended to the head correctly.

**Comment by artf** [comment]
Should not cause any issue as being the first element inserted but for the sake of completeness we gonna move it inside the head element
