### ISSUE TITLE
[BUG]? Asset Manager remove button for assets

### ISSUE THREAD

**Issue by detectedstealth** [artf/grapesjs#1476]
Using the demo web preset template as a starting point, I noticed the remove asset button doesn't show up in the UI. Viewing source shows the button. It there some other setting that needs to be enabled for the remove button to be functioning? 

```
<div class="gjs-am-close" data-toggle="asset-remove"> ⨯ </div>
```

**Comment by artf** [comment]
Probably related to some style of the preset, please open the issue in the relative repository
