### ISSUE TITLE
[QUESTIONS] Make a component that can't be removed.

### ISSUE THREAD

**Issue by krisnaw** [artf/grapesjs#1483]
Hi there, 

Is it possible to make a component that can't be removed or without remove the trach icon when it clicked?

Thanks, looking forwards.

**Comment by Skovmissen** [comment]
I think what you want is _data-gjs-removable="false"_ add that as an attribute to your div like.
<div data-gjs-removable="false">Hello World!</div>

**Comment by krisnaw** [comment]
Hi, @Skovmissen Thanks for your responses. 

It's worked.
