### ISSUE TITLE
[Question]: Textblock subsequent rows do not give cursor/richtext editor when clicked, but are selected instead

### ISSUE THREAD

**Issue by mararn1618** [artf/grapesjs#1484]
I have noticed a strange behaviour in my adaptation of GrapesJS concerning the richtext editor and the gjs-blocks-basic plugin. Whenever I drop a textblock and start writing, I will end up with one component for the dropped block and several sub-components for each row (see  elements in screenshot with `data-gjs-type="text"`).

![image](https://user-images.githubusercontent.com/15421484/46597079-f5c9e580-cade-11e8-8565-24406491deb1.png)

This is okay so far. What is different and problematic is that ..
 - When clicking into the text, instead of starting the richtext editor and getting a cursor, the subcomponent is selected
 - In this case it is not possible to type
 - Every once in a while, after clicking several times, I will get a cursor in this position

I have not seen this behavior in any of the demos and could not figure out what I am doing wrong. Can anyone help me out?

 - Demo: https://www.secretbakery.io/grapesjs_text_subcomponent_selectable/issue.html

Thanks and Kind Regards

**Comment by mcsekar12** [comment]
[https://github.com/artf/grapesjs/issues/761](url)

**Comment by mararn1618** [comment]
Thanks, my issue seems to be a duplicate of https://github.com/artf/grapesjs/issues/761
I have tried GrapesJS 0.14.33, which should contain the fix for 761, but unfortunately it gives me a new exception within the richtext editor, which I did not have before.

```
index.js:141 Uncaught TypeError: Cannot read property 'body' of null
    at Object.getBody (index.js:141)
    at Object.getWrapperEl (index.js:149)
    at i.getCanvasWrapper (CommandAbstract.js:63)
    at initialize (CommandAbstract.js:26)
    at i.e.View (backbone.js:1224)
    at i [as constructor] (backbone.js:1884)
    at new i (backbone.js:1884)
    at Object.get (index.js:244)
    at Object.method (index.js:146)
    at keymaster.js:106
```

I will prepare another demo with GrapesJS 0.14.33 shortly.

**Comment by mararn1618** [comment]
I fail to recreate an isolated demo to reproduce the new exception, but I have found that the exception will also occur with GrapesJS 0.14.25, i.e. it was not introduced recently.

**Comment by mararn1618** [comment]
Exception seems to be a duplicate if #1288, as I am also using AngularJS.

**Comment by mararn1618** [comment]
I was finally able to reproduce this and find the cause for #1484 and #1288.

An Angular application, as an SPA, will have scenarios like this:
 - 1: user starts app
 - 2: user does some editing (grapesjs is initialized for the editor)
 - 3: user does sth else in the app
 - 4: user edits again (grapesjs is initialized for the editor)

This causes `grapesjs.init({..})` to be triggered again and again and creates the faulty richtext editor with the exception for me. I have verified this, by triggering `grapesjs.init()` twice, always ending up with exceptions as stated above when editing text.

I think Angular people would like to have a proper way to destroy the editor, as requested in
- #914
- #919
- #849
- #889

**Comment by mararn1618** [comment]
Hi @artf,

I have seen that you have introduced `editor.destroy()` with GrapesJS 0.14.33 in https://github.com/artf/grapesjs/commit/52f8bdf2e894de536d44c1699c1e18bbaf52488f . It seems that destroy is still not cleaning up everything, since it is possible to provoke various exceptions after destruction and reinitialization.

Demo incl Reproduction: https://jsfiddle.net/d9ohj0bk/

**Comment by artf** [comment]
Thanks @mararn1618 for all the details, would you mind to move your last post in a new dedicated issue as it's not related to the main topic of this one

**Comment by mararn1618** [comment]
You're right, let's close this and I'l open a new ticket.
