### ISSUE TITLE
How to prevent styling html components?

### ISSUE THREAD

**Issue by Skovmissen** [artf/grapesjs#1485]
Im trying to create some templates, which should not be editable and styleable. So that when i drag in my blocks then should stay as defined. Is there a way to disable the style manger for certain components?

i know about data-gjs-removable="false", data-gjs-editable="false"
But they do not do what im tryting to do.

Thanks.

**Comment by cjpollard** [comment]
Try `data-gjs-stylable="false"`.

**Comment by Skovmissen** [comment]
That doesn't seem to be an option.

**Comment by artf** [comment]
Yeah you should use `data-gjs-stylable="false"`
