### ISSUE TITLE
How to add/remove class undo manager

### ISSUE THREAD

**Issue by Deepak813** [artf/grapesjs#1486]
Hi @artf,

Can you please provide the way to add/remove class in undo manager.
Also,on live demo when we drag countdown and click on undo button then countdown element does not have any effect on it.

Thanks in advance

**Comment by takecore** [comment]
I have same problem. Anyone resolved?

**Comment by artf** [comment]
I'm closing this one in favor of the general improvement of UndoManager API https://github.com/artf/grapesjs/issues/3639
