### ISSUE TITLE
The copy function went wrong ？

### ISSUE THREAD

**Issue by lovesandy** [artf/grapesjs#149]
Hi, I have the latest version of Grapesjs: 0.8.8:

my code likes this:
`<h1>hello <small>only</small></h1>`
When i try clone the `small` element, the model of `small` element adds to parent's collection, but the canvas can't render the new `small` element.

I found this(`ComponentsView.js` line 75):
the return values of this code `p.children()` can't include textNode element.

Thanks !

**Comment by artf** [comment]
thanks @lovesandy, good catch

**Comment by arthuralmeidap** [comment]
@lovesandy @artf , is this still happening on the current version of grapesjs?

**Comment by artf** [comment]
I've not yet touched this, so I guess the bug is still there

**Comment by artf** [comment]
Should be fixed in the latest release https://github.com/artf/grapesjs/releases
