### ISSUE TITLE
How to send value from the layout section

### ISSUE THREAD

**Issue by kalislami** [artf/grapesjs#1490]
@artf 
I need your help to solve my issue with grapesjs

i have this code in the template:
![screenshot from 2018-10-09 19-18-53](https://user-images.githubusercontent.com/33272620/46669075-9233db00-cbf8-11e8-8e4c-56db821c28e9.png)

I want to pass that value in this way
![screenshot from 2018-10-09 19-19-49](https://user-images.githubusercontent.com/33272620/46669170-da52fd80-cbf8-11e8-8ed4-2beb69694278.png)

but when I edit that part into "Blogger Campaign",
it doesn't send the updated values, sent still "Campaign Title"

do you have a solution for this?

thanks before

**Comment by artf** [comment]
Use events
```js
editor.on('storage:start:store', data => {
	const compH1 = editor.DomComponents.getWrapper().find('#campaign_title')[0];
	data.title = compH1 && compH1.getEl().innerText;
})
```
