### ISSUE TITLE
[QUESTION] render() works on the first time but not on subsequent calls

### ISSUE THREAD

**Issue by dancodes** [artf/grapesjs#1493]
Hello,

I've created a custom component that shows images using `background-image` on a `<div>` instead of using an `<img>` element. It's mostly working, except that every time I change its `src` trait I must reload the editor to preview the rendered element. This is its view:

```js
view: originalMap.view.extend({
	initialize: function(o) {
		var model = this.model;
		
		// Extend the original initialize method
		originalMap.view.prototype.initialize.apply(this, arguments);
		
		this.listenTo(model, 'change:attributes:src', this.render);
	},

	render: function() {
		// Extend the original render method
		originalMap.view.prototype.render.apply(this, arguments);

		var src = "";

		this.model.get('traits').each(function(trait) {
			if (trait.get('name') == 'src') {
				src = trait.get('value');
			}
		});

		this.$el.css('background-image', 'url("' + src + '")');

		return this;
	},
})
```

On editor load, the component has its correct `background-image` value set. Upon changing its `src` trait (a text field), it loses that CSS property. What am I doing wrong?

**Comment by artf** [comment]
@dancodes can you provide a live demo of the issue, please?
