### ISSUE TITLE
[Question] Tailwind classes

### ISSUE THREAD

**Issue by DigicreateJens** [artf/grapesjs#1494]
I'm looking to use [Tailwind](https://tailwindcss.com/) with GrapesJS, but this framework uses _Utility-First CSS Classes_ to build quick layouts. The problem is that it also uses ['special' classes](https://tailwindcss.com/docs/state-variants/#app) to define style variants, eg: `hover:bg-blue` or `md:w-full` etc.

The problem is that the GrapesJS Selector `escape` function replaces the colons(:) with dashes(-), which in turn breaks my pages.

Can I change this for my own GrapesJS installation, or could this possibly be added to the _core_ or be made configurable? I'm sure that, with the popularity of Tailwind CSS rising, this could come in handy for others too.

Thanks in advance!

(This issue is pretty similar to #325)

**Comment by artf** [comment]
I'd appreciate a PR :)
