### ISSUE TITLE
issue in adding new row cell in grapejs not working

### ISSUE THREAD

**Issue by himanshubudhlakoti** [artf/grapesjs#1496]
i am using grapejs version 0.14.33 with angular 6
i want to add a section with 2 blocks on block manager as created  on grapejs demo.
and for that following code mentioned below but it is not working .
suggest me any code that can add a box with 2 section and sections are dragable.

```blockManager.add('the-row-block', {
  label: '2 Columns',
  content: '<div class="row" data-gjs-droppable=".row-cell" data-gjs-custom-name="Row">' +
      '<div class="row-cell" data-gjs-draggable=".row"></div>' +
      '<div class="row-cell" data-gjs-draggable=".row"></div>' +
    '</div>',
});
```

**Comment by nternouski** [comment]
@himanshubudhlakoti How you import grapesjs on angular 6, i cant imports plugin correctly

**Comment by nternouski** [comment]
@himanshubudhlakoti How you import grapesjs in Angular 6, i cant use plugins. Please help!
