### ISSUE TITLE
[Question] Is it possible to perform dom manipulation through the block's contents script?

### ISSUE THREAD

**Issue by taufeek6** [artf/grapesjs#1499]
Hey! First of all thank you so much to build such a great and versatile tool.
Is it possible that I can manipulate the dom elements of the block through block's content script?

Eg. 

```
 editor.BlockManager.add('open-question-2',  {
      id: 'open-question-2',
      label: `Open ended question 2`,

      category: 'Forms',
      attributes: {class:'fa fa-question-circle '},
      droppable: 'form',
      content:{
        content : `
          
        <div  data-id="question-container">
          <label>Question</label>
          <input type="textbox" class="form-control">
        </div>
        `,
        script : function(){
          $("div[data-id='question-container']").find("input").attr("value", "Enter you question here...")
        }

      }
    });
```

Basically I need a survey kinda block, where user can drop question block and then can enter the question string. 

Once again thank you so much.

**Comment by artf** [comment]
Sure, but be sure to understand correctly the context of `script` and how it works
https://grapesjs.com/docs/modules/Components-js.html#components-js
You can't use `$` if you didn't include it first

**Comment by taufeek6** [comment]
![gjs dom manipulation2](https://user-images.githubusercontent.com/19469610/46792130-3c7a4280-cd60-11e8-8571-34caf0428c97.PNG)

I've added the jquery,  in the above image I've added the **value** attribute to input tag as we can see that in the above image, but that **value** attribute is not there in the final HTML I'm getting from the editor.


```
editor.StorageManager.add('local', {
      // New logic for the local storage
      load() {
        // ...
      },
      store(data, clb, clbErr) {
        // ...
        console.log(data['gjs-html'])  //<<<< In this html I'm not getting the **value** tag that I've added thru jquery dom manipulation.

      },
    });
```

**Comment by artf** [comment]
@taufeek6 you've created a component **A** (`<input>`) with a script **B** (`.attr("value", "Enter you question here...")`) which should produce the **C** (`<input ... value="Enter you question here...">`). The editor exports **A** and **B** so if you put them together inside a blank page you will get the **C** 
So the **C** is the result for the end-user and not for the export step. Did you get now the point of using components with scripts?
