### ISSUE TITLE
[Bug] Creating multiple child element after editing using RTE

### ISSUE THREAD

**Issue by mudit-mittal** [artf/grapesjs#1502]
Hi All,

I am getting below issues which are related to RTE

1. RTE creating multiple child's as action performed on text block. Ex:- suppose we performed same action (Bold) three times in sequence on same text block then its creating three child's on the same element.
2. Font action in RTE is only supporting font size values between 1 to 7 so please provide the support for font size values between 1 to 100 in RTE.

![image](https://user-images.githubusercontent.com/44024159/46786571-e652d280-cd52-11e8-8e44-ec623f5391e2.png)

**NP:-** I am using latest version of library but issue is still here so kindly review.

Previous bug for reference https://github.com/artf/grapesjs/issues/1495#issue-368617259
Kindly revert on priority. Thanks in Advance !!!

**Comment by mudit-mittal** [comment]
Hi All,

Please find step for reproducing this scenario 

1) Initial state
![image](https://user-images.githubusercontent.com/44024159/46848964-71db6a80-ce0a-11e8-9c87-013099c64bf2.png)

2) Perform Bold Action then Italic Action then Underline Action
![image](https://user-images.githubusercontent.com/44024159/46848910-2759ee00-ce0a-11e8-94ff-03cb51fe8082.png)

3) Again click on Bold Action then Italic Action then Underline Action 
![image](https://user-images.githubusercontent.com/44024159/46848931-4bb5ca80-ce0a-11e8-8e69-7e8d8e2c2353.png)

Actual:- Getting three extra <span> element

**Comment by mudit-mittal** [comment]
Hi All,

rte.add('fontSize', {
     *   icon: `<select class="gjs-field">
     *         <option>1</option>
     *         <option>4</option>
     *         <option>7</option>
     *       </select>`,
     *     // Bind the 'result' on 'change' listener
     *   event: 'change',
     *   result: (rte, action) => rte.exec('fontSize', action.btn.firstChild.value),
     *   // Callback on any input change (mousedown, keydown, etc..)
     *   update: (rte, action) => {
     *     const value = rte.doc.queryCommandValue(action.name);
     *     if (value != 'false') { // value is a string
     *       action.btn.firstChild.value = value;
     *     }
     *    }
     *   })

this block of code is only supporting font size values between 1 to 7 although is should be generic and should be support all integer values

**Comment by artf** [comment]
This is just how [execCommand](https://developer.mozilla.org/it/docs/Web/API/Document/execCommand) works and the built-in RTE is based on it. If you need something more sophisticated you can try [grapesjs-plugin-ckeditor](https://github.com/artf/grapesjs-plugin-ckeditor) or implement any other 3rd-party editor by following this guide: https://grapesjs.com/docs/guides/Replace-Rich-Text-Editor.html
