### ISSUE TITLE
[Question] Dynamic height

### ISSUE THREAD

**Issue by dlorenzo** [artf/grapesjs#1504]
Hi:

Is it possible to have an instance of GrapesJS with dynamic height, as in, the editor adjusts to the content size. What I'm trying to do is to embed GrapesJS in a page with other elements (header, footer, etc.) and having only one scrollbar for the entire page. As you insert content in the editor, the page as a whole grows longer. Is this really possible?

Thanks in advance.

**Comment by artf** [comment]
Not by default, but you should be able to do so by relying on [Events](https://grapesjs.com/docs/api/editor.html#available-events)

**Comment by dlorenzo** [comment]
Got it working pretty nicely listening to the 'component:update' event, calculating iframe content height and applying it to the editor.

Thanks.
