### ISSUE TITLE
How to disable undo button

### ISSUE THREAD

**Issue by Deepak813** [artf/grapesjs#1509]
Hi @artf,

Hope you are doing well with grapesjs.

Can you please let us know how to disable the undo button when no data present in undo manager and vice-versa.I have check all new events but unable to find the undo active/disactive event.can you help us.

Thanks in advance

**Comment by artf** [comment]
On `undo`/`redo` events https://grapesjs.com/docs/api/editor.html#general
you can use Undo Manager APIs https://grapesjs.com/docs/api/undo_manager.html

**Comment by chrisrobbins** [comment]
@artf I am trying to conditionally render the undo/redo buttons based on there being anything to undo/redo. I am having trouble with the general event "Update". 

`
this.editor.on('update', () => {
      console.log('editor updating');
      const pnm = this.editor.Panels;
      const um = this.editor.UndoManager;
      const optsPanel = pnm.getPanel('options');
      console.log('UNDO MANAGER', um.hasUndo());
      if (um.hasUndo().length > 0) {
        optsPanel.get('buttons').add({
          id: 'undo',
          className: 'fa fa-undo',
          command: 'undo',
          attributes: { title: 'undo' },
        });
      }
      optsPanel.render();
    });
`

**Comment by artf** [comment]
> If the undo event needs to be triggered to present it's data, then how can we render or disable the undo/redo btns?

??? You can use the Undo Manager APIs wherever you want, I didn't say you can use it only after undo/redo events.

> The Update event never seems to be triggered

The `update` event was added in https://github.com/artf/grapesjs/releases/tag/v0.14.55
