### ISSUE TITLE
[Question] How to insert the editor inside a div with bootstrap class style

### ISSUE THREAD

**Issue by rgcarrasqueira** [artf/grapesjs#151]
Hi!

I'm trying to insert the editor into a div that receive a style class from bootstrap, something like that:

```
<div class="row">
      <div class="col-xs-3">Left Content</div>
      <div class="col-xs-9"><div id="gjs"></div></div>
</div>
```

And the editor is not rendered at the chosen location, any clue on how to deal with that?

Thanks

**Comment by artf** [comment]
just put a `<link>` tag of bootstrap inside your template, similar to #27
