### ISSUE TITLE
How to add video block on blockManager

### ISSUE THREAD

**Issue by himanshubudhlakoti** [artf/grapesjs#1514]
Hello All.
i want to add  a video block on blockmanager same as mentioned on below snapshot
![aaaa](https://user-images.githubusercontent.com/32187513/46931328-52417d80-d068-11e8-81d6-66a11e6ee59a.png)

i am using following code for adding video block on block manager
```  
editor = grapesjs.init({
      autorender: 0,
      container: '#gjs',
      components: '<div class="txt-red"></div>',
      style: '.txt-red{color: red}',

blockManager: {
        appendTo: '#gjs',
        blocks: [
          {
            id: 'Video',
            label: 'Video',
            attributes: { class:'fa fa-video'},
            content: `
            <video controls>
            <source src="https://www.w3schools.com/tags/movie.mp4" type="video/mp4">
            <source src="https://www.w3schools.com/tags/movie.mp4" type="video/ogg">
            Your video
          </video>`,
            category: 'Basic',
          },
    ]

})```
 but that code does not works
please let me know how can i add video block on block manager

**Comment by yomeshgupta** [comment]
@himanshubudhlakoti You can use https://github.com/artf/grapesjs-blocks-basic  as a plugin. It has pre built blocks. Documentation is pretty straight forward on this.

**Comment by himanshubudhlakoti** [comment]
thank you so much @yomeshgupta  for sharing this.
i have download code shared by you.
can you explain that how can i use that plugins with angular 6.
please let me know

**Comment by himanshubudhlakoti** [comment]
thnak you @yomeshgupta  it has done

**Comment by yomeshgupta** [comment]
@himanshubudhlakoti You are welcome! Close this issue if it is resolved.

**Comment by himanshubudhlakoti** [comment]
ok
