### ISSUE TITLE
How to add shape's block on blockmanager in grapesjs

### ISSUE THREAD

**Issue by himanshubudhlakoti** [artf/grapesjs#1517]
Hello All,
I am new in greapsjs.
i have a query **is it possible to add shapes( Rectangle , Triangle , Square) on blockmanager** as we  add sections.
i want to add shape's block on block manager and when i drop this shape on canvas then it should be appear there just like other blocks such as sections.
please let me know

**Comment by artf** [comment]
You can put inside blocks any HTML/SVG/CSS you want, how you achieve the result (Rectangle , Triangle , Square) it's up to you
