### ISSUE TITLE
[QUESTIONS]: Init components in grapesjs.init

### ISSUE THREAD

**Issue by Controlhaus** [artf/grapesjs#1519]
Is it possible to initialise the components at grapesjs.init.
We are not using StorageManager.load.
We already have the project data at init.

Using html works fine, but using components renders the components object as text in the editor.

`this.editor = grapesjs.init({
      components: projectData.components || projectData.html,
      style: projectData.styles || projectData.css,

      container: '#gjs',
      plugins: ['gjs-preset-webpage'],
      pluginsOpts: {
        'gjs-preset-webpage': {
        }
      },
      storageManager: {
        id: '',                   // Prefix identifier that will be used on parameters
        type: 'catchService',     // Type of the storage
        urlStore: `${this.backendConfig.url}api/content`,
        contentTypeJson: true,
        autosave: true,           // Store data automatically
        stepsBeforeSave: 1,       // If autosave enabled, indicates how many changes are necessary before store method is triggered
        storeComponents: true,  // Enable/Disable storing of components in JSON format
        storeStyles: true,      // Enable/Disable storing of rules in JSON format
        storeHtml: true,        // Enable/Disable storing of components as HTML string
        storeCss: true,
      },
    });
    this.setupStorage(this.project, this.contentService);
`

![screen shot 2018-10-16 at 08 58 22 2](https://user-images.githubusercontent.com/6704041/46998023-aceae000-d121-11e8-9f68-5b286bd91291.png)

**Comment by cjpollard** [comment]
You need to parse the string.
`JSON.parse(projectData.components)`

**Comment by Controlhaus** [comment]
Working now.
Thank you for the fast and accurate reply :-)
