### ISSUE TITLE
[QUESTIONS] S3 file upload example 

### ISSUE THREAD

**Issue by Controlhaus** [artf/grapesjs#1521]
Are any examples of using Aws S3 to store asset files available?

**Comment by Controlhaus** [comment]
To upload to S3 direct from the browser, a pre-signed URL needs to be obtained from the app's server first. The URL needs to contain the file's name.  

Is it possible to assign the asset manager's upload URL in the before upload event?  

This does not work:
`this.editor.on('asset:upload:start', () => {
  this.editor.assetManager['upload'] = preSignedUrl;
});`

**Comment by artf** [comment]
Check this PR https://github.com/artf/grapesjs/pull/1430
To update the config of the upload url:
`editor.AssetManager.getConfig().upload = 'asdasd'`
