### ISSUE TITLE
is there  any plugins for adding shapes(Line, Oval ,Rectangle) in grapesjs 

### ISSUE THREAD

**Issue by himanshubudhlakoti** [artf/grapesjs#1523]
Hello All,
please let me know 
**is there any plugins for adding shapes like Line, Rectangle oval at blockmanager**

**Comment by himanshubudhlakoti** [comment]
please let me know its urgent

**Comment by v8jupiter** [comment]
I have not seen such a plugin. But you can create you own, it not hard

**Comment by artf** [comment]
Duplicate of #1517
