### ISSUE TITLE
How to add countdown/navigation event in undo/redo

### ISSUE THREAD

**Issue by Deepak813** [artf/grapesjs#1527]
Hello @artf,

How can we add any changes/events in undo/redo Manager like when we drag element like navigation or countdown.
Hope for positive response
Thanks in advance

**Comment by artf** [comment]
Duplicate of #1512
@Deepak813 more issues you open, later you get the response... so please avoid generating useless noise

**Comment by Deepak813** [comment]
Hello @artf,

My bad.I forgot that i have already opened this issue.
I'll not repeat this thing.

Thankyou
