### ISSUE TITLE
[Question] How to combine grapesjs with polymer components?

### ISSUE THREAD

**Issue by bungambohlah** [artf/grapesjs#153]
I really like grapesjs, grapesjs's team and all the other person that working on it, this is really good and lightweight framework, but can grapesjs combine with polymer components? i want to improve UI to the material design, and i found the component that need some element to initialize it, like import the component called "webcomponents" with tag ```<link rel="import" href="bla/bla/bla.html"```.
I still try to combine it, but something problem that confuse me. In open layer manager menu, that show up link's tag on it, how to hide specific tag with specific attribute like this ```<link rel="import" href="bla/bla/bla.html"``` ?
![image](https://user-images.githubusercontent.com/19922064/28051092-1a405124-662c-11e7-9c62-ac1c66c43dfc.png)

And the second, i try to drag my custom blocks with polymer's component and it's not work, warning show up in the console.
![image](https://user-images.githubusercontent.com/19922064/28050991-6d3e0b1a-662b-11e7-8b62-00db257fc152.png)
Can you help me with this warning?
EDIT: this is for the canvas not the editor menu
Thank you and sorry for my bad english or grammar

**Comment by artf** [comment]
Never used polymer so can't help you, about the link tag you can create a new Component with `hiddenLayer: true` property, in this way it won't be visible in layers
