### ISSUE TITLE
Click events in undo/redo manager

### ISSUE THREAD

**Issue by Deepak813** [artf/grapesjs#1530]
Hi @artf,

I have a issue regarding undo manager and I have checked it's also on your demo page.
Problem is that undo manger also count the event when we click on outside the editor section
like on the layer button, style button, Block button or any other button which are on top.

So if we add a text and then click on layer button after that style button and after that on block button and then we drag a link then it consider as 5 events so if we have to revert back to the text then we need to click on 4-5 times. 
I also want to know is it a issue or you have added that events on the undo and redo manager.
I have created a video for this,please have a look.
https://www.useloom.com/share/c867df2124bb4fd89688e580840f4f32

Thanks in advance.

**Comment by artf** [comment]
Closing as fixed
