### ISSUE TITLE
[Question] Css class

### ISSUE THREAD

**Issue by alfaalex81** [artf/grapesjs#1531]
Hi! Probably this problem is already posted, but I can't understand where I'm wrong. I use this three parameters on init GrapesJs.

```
                protectedCss: '',
                avoidInlineStyle: true,
                forceClass: true,
```

I would like GrapeJs not to edit preexisting css, but only creates its own. Is it possible?

Thank you!

**Comment by alfaalex81** [comment]
For example i have this code on canvas

```
<div class="row">
    <div class="col-md-6" style="min-height: 50px"></div>
    <div class="col-md-6" style="min-height: 50px"></div>
</div>
```

GrapesJs add to CSS this class

```
.col-md-6 {
	min-height:  50px;
}
```

This rule modify all element with this class, this is a generic bootstrap class that we use in all site.

**Comment by artf** [comment]
@alfaalex81 I can't reproduce it, create a live demo please

**Comment by alfaalex81** [comment]
https://jsfiddle.net/ugc1otnk/

In the example when i change background color in the first column, GrapesJs set the css attribute to the external class "col-md-6", that is a bootstrap class name. I prefer Grapesjs set own class.

Moreover I think I've found a bug. Select the first column and deselect class "col-md-6" on the stylee manager panel, class name "example" appears but this class is associated in the second column. It is only a visual bug.

**Comment by artf** [comment]
For your first issue, just set `forceClass: false,`, about the bug please open another issue
