### ISSUE TITLE
How to ensure that the independent module is not dragged into other modules.

### ISSUE THREAD

**Issue by momu-smartcoach** [artf/grapesjs#1532]
sorry to ask again，I really want to know How to set up the independent module is not dragged into other modules ，just like Built-in Blocks in grapedrop.com。

Eagerly looking forward to the specific code module modification，thank you!

**Comment by momu-2016** [comment]
help~~~~

**Comment by artf** [comment]
At the bottom of this https://grapesjs.com/docs/modules/Blocks.html
you find an example of a Row block which does exactly what you need by using `droppable`/`draggable` properties of [Component](https://grapesjs.com/docs/api/component.html)
