### ISSUE TITLE
Update property Input value from model style.

### ISSUE THREAD

**Issue by YashPrince** [artf/grapesjs#1534]
@artf  I want to update height of the element and want to give a custom height using following code
      
```
var model = editor.getSelected();
var style=model.getStyle();
    style['height'] = '600px';
    model.setStyle(style);


```
![height](https://user-images.githubusercontent.com/40828744/47306097-1f3f5100-d649-11e8-859a-b8fa3be0c601.png)

It's working fine and it's update the selected model style but it does not update the property input value. How can we update the input  values also while updating the style.

Any help would be appreciated, thanks in advance.

**Comment by artf** [comment]
For now, use this `editor.trigger('component:toggled')` maybe one day I'll make it update automatically
