### ISSUE TITLE
[Bug]: After custom component is deleted the Trait's view does not clear out

### ISSUE THREAD

**Issue by christopherserrao05** [artf/grapesjs#1535]
Hi,

I'm using the grapesjs library version **0.14.33**.

I've created some custom components and I've noticed that on deleting the components the Traits panel does not clear out.
For instance when the canvas loads and no component is selected, the Traits panel does not display any traits. The traits are displayed only after a component is selected.
I would like the Traits panel to go back to the state where no component is selected as soon as a component is deleted.

**Browser Used for Testing :** Chrome v 69.0.3497.100

**Actual Behavior :** Once the component is deleted, the traits continue to be displayed for the deleted component.

**Expected Behavior :** Once the component is deleted, the traits controls should be hidden/removed from the traits panel, similar to the state the traits panel is when the application first loads and no component is selected.

**JS Fiddle link to reproduce the issue :** https://jsfiddle.net/g3zh12r7/1/

Thanks

**Comment by artf** [comment]
Ok thanks for the report. I'll fix that in the next release
