### ISSUE TITLE
Different content when exporting

### ISSUE THREAD

**Issue by Geelik** [artf/grapesjs#1538]
Hi,

I'm trying to use grapejs with dynamic contents. What i want to achieve is like wordpress, i want to have shortcodes / custom html tag  when i export html.

So here is an example of what i mean : 
```html
<!-- inside the editor -->
<div data-type="my-component">My component content here</div>
```

```html
<!-- this is what i want when i export-->
<my-component>My component content here</my-component>
```

So for that i use components, i have tried to do `this.model.set('tagName'', 'div')` inside the render method in my component view but it does an infinite loop cause modifying the model trigger the render method.

If you have any tips for me.

**Comment by artf** [comment]
@Geelik you can set the `tagName` in [Component](https://grapesjs.com/docs/api/component.html#component) definition
