### ISSUE TITLE
How and where  to define form's action in grapesjs

### ISSUE THREAD

**Issue by himanshubudhlakoti** [artf/grapesjs#1539]
Hello All,

how can i get data from forms in grapesjs.
i have droped a form on canvas as u can see that below
![4444444](https://user-images.githubusercontent.com/32187513/47430117-115b0e80-d7b6-11e8-806d-24b0628787fa.png).

so there is an action property as as  mentioned in above snapshot covered by red coloured rectangle.
i have put and action value. 
so where i can define this action in my code in which i can get that form's data .. i am sharing my code
```
editor = grapesjs.init({
      autorender: 1,
      container: '#gjs',
      components: '<div class="txt-red"></div>',
      style: '.txt-red{color: red}',
      plugins: ['grapesjs-blocks-basic','gjs-preset-webpage' ],
})```

**overall means when i will click on form's send button then where or in which function i will get that form's data or that function where should be defined** 
let me know please

**Comment by AshishTiwariMEAN** [comment]
Hello Team,

Need your suggestion about the same because of we need to use form builder in our application so we can easily customise our form also we need to get user input.

Waiting for your reply...

Thanks,

**Comment by artf** [comment]
If you want to define the action before dropping the form (eg. defined in the block) you just need to specify it as an attribute `<form action="your/end/point" method="POST">`
