### ISSUE TITLE
[Question] How to use submit button in TRAITS?

### ISSUE THREAD

**Issue by fzs1994** [artf/grapesjs#154]
![screenshot from 2017-07-11 13-07-28](https://user-images.githubusercontent.com/10684213/28056258-ea1e337c-6639-11e7-8ef6-45e4df528b94.png)
I want to perform action on click of this submit button. How can I do this?

```
traits: [
          // strings are automatically converted to text types
          {
            label: 'API URL',
            name: 'apiurl',
            options: [
              {value: 'text', name: 'Text'}
            ],
            changeProp: 1
          },
          {
            label: 'Items',
            name: 'items',
            type: 'number'
          },
          {
            label: 'Submit',
            name: 'callApi',
            type: 'submit'
          }
        ]
```
This is not working for me.
Thanks! :innocent:

**Comment by artf** [comment]
Create a [new Trait type](https://github.com/artf/grapesjs/wiki/Traits#define-new-trait-type)
