### ISSUE TITLE
[Question] Is it possible to add event for preview?

### ISSUE THREAD

**Issue by SeongwoonHong** [artf/grapesjs#1540]
I'd like to convert some texts when a user clicks the preview button.
for instance, ((name)) (in the editor) should be 'David' (in preview mode) which comes from the server as it is dynamic field.
So, would it be possible to call api when clicking preview and the preview result should wait till i get the data from the server

**Comment by artf** [comment]
You can use [command events](https://grapesjs.com/docs/api/editor.html#commands), eg:
```js
editor.on('run:preview', () => {
	// do stuff...
});
editor.on('stop:preview', () => {
	// undo stuff...
});
```
