### ISSUE TITLE
Remove Last changes From Undo Manager Stack

### ISSUE THREAD

**Issue by YashPrince** [artf/grapesjs#1541]
@artf  Hello Can we remove the last event (changes) from undomanger. I need remove last event (change) from undo manger stack. I can get undo manager stack but could not modify it. Is there any way to set pointer of stack one or two step back or remove the last events from the stacks. There is a way like um.stop() and um.start() but I can not use that as I have no Idea that from where that event are added in stack of UndoManager.

Any help would be Appreciated, thanks in advance!

**Comment by artf** [comment]
The only way to move the pointer is to use `undo`/`redo` methods, so if you need to remove **X** steps you have to execute `undo` **X** times
