### ISSUE TITLE
[Question] Enable Traist-checkbox by default

### ISSUE THREAD

**Issue by TommyLjung** [artf/grapesjs#1543]
Hi.

I am new to GrapesJs and really liking it so far.
But now I have a (probably beginner) question:

How can I make a trait-checkbox be selected by default?
I have tried with:
`traits: [
            {
              type: 'checkbox',
              label: 'Loop',
              name: 'model-loop-bool',
              changeProp: 1,
              selected: 'true',
            }],`

But "selected" or "checked" is not the right attribute to set, can someone please help me with this basic thing?

Thanks!

**Comment by artf** [comment]
If you use `changeProp` you get the value from the component value, eg:
```js
...
defaults: {
	...
	'model-loop-bool': true, // <- default value
	traits: [{ 
		type: 'checkbox', 
		label: 'Loop', 
		name: 'model-loop-bool', 
		changeProp: 1, 
	}]
}
```
without `changeProp`, it would be:
```js
defaults: {
	...
	attributes: {
		'model-loop-bool': true,
	},
	traits: [{ 
		type: 'checkbox',
		label: 'Loop', 
		name: 'model-loop-bool', 
	}]
}
```
