### ISSUE TITLE
[Question] How I Get ID From Block?

### ISSUE THREAD

**Issue by crashangelbr** [artf/grapesjs#1545]
Hi,  i have my block and I get print in Div id results from my javascript class component... How i get ID from my block ???

editor.BlockManager.add('test-block', {
		label: 'Test block',
		attributes: {class: 'fa fa-text'},
		content: {
			content:'<div id=""></div>',
			script: function () {
				console.log(document.getElementById("MyBlockDivIDHere"));
				uil.add('joystick', { target: document.getElementById("MyBlockDivIDHere"), pos:{left:'0', top:'0', bottom:'0' }, name:'JOY', w:100, multiplicator:1, precision:2, fontColor:'#D4B87B' });
			},
			style: {
				width: '100px',
				height: '100px',
				'background-color': 'red',
			}
		}
	});

**Comment by juanj** [comment]
You can use `this` inside the script to reference the block element. If you want the id you can use `this.id`.
Note that `document.getElementById(this.id) == this`
