### ISSUE TITLE
QUESTION: How insert box, section, footer, header...

### ISSUE THREAD

**Issue by jotakar** [artf/grapesjs#1548]
I'm trying to imagine how to insert a header or a section or a box... I see the blocks panel, and extra an every panel, but all I can insert are rows - columns, images, navs... but a section or a box .... how do it?
Please an answer :(
Thanks

**Comment by cjpollard** [comment]
You can easily create your own blocks. https://grapesjs.com/docs/modules/Blocks.html

**Comment by jotakar** [comment]
Thanks
Yes I know I can create blocks, but In the demo (https://grapesjs.com/demo.html) I see this elements but I can't see any special block for this kind of elements. This is the reason of my question, hoe this blocks have seen created if there is no block for them? 
Bye

**Comment by artf** [comment]
@jotakar it's just an import of a pre-made template https://github.com/artf/grapesjs/blob/gh-pages/demo.html#L147
