### ISSUE TITLE
Question: getAll and getAllVisible

### ISSUE THREAD

**Issue by jotakar** [artf/grapesjs#1549]
I read that getAll returns all assets collection and getAllVisible returns all assetes rendered in html (I understand:used in the template). But when I do execute editor.AssetManager.getAll().models and AssetManager.getAllVisible().models I get the same array: all assets in template used and not used.
Why?
Thanks

**Comment by artf** [comment]
It's not "the same array", you just get all the assets visible by default, so if do `editor.AssetManager.render(['img1.jpg', 'img2.jpg'])` you'll see the difference
