### ISSUE TITLE
Problem with my Cells when I load again the html and css.

### ISSUE THREAD

**Issue by Aitortilla22** [artf/grapesjs#1554]
When I retrieve my template from the database.
My Cells have become box and I can not modify their width as when they are cells.
Can I make my Cells remain cells without becoming something else by retrieving the template?
**Creating Template**
![aftersave](https://user-images.githubusercontent.com/44646666/47799997-b7b19180-dd2b-11e8-8d11-02f4f88e5289.png)
**Reloading Template**
![beforeload](https://user-images.githubusercontent.com/44646666/47800065-d748ba00-dd2b-11e8-8d5d-80ed4549492a.png)

**Comment by cjpollard** [comment]
Looks like you're storing/loading incorrectly.  Check here. https://grapesjs.com/docs/modules/Storage.html#store-and-load-templates

**Comment by Aitortilla22** [comment]
> Looks like you're storing/loading incorrectly. Check here. https://grapesjs.com/docs/modules/Storage.html#store-and-load-templates

Thank's @cjpollard I wasn't save the components only saved the html.
Know I save the components and when I recover the template it's perfect ^^
