### ISSUE TITLE
Code manager set code

### ISSUE THREAD

**Issue by froderf** [artf/grapesjs#1558]
Hi @artf. Is there something similar to this
`editor.CodeManager.setCode(component, 'css', {cssc: editor.CssComposer}`

to update the css rule of the selected block returned from 
`editor.CodeManager.getCode(component, 'css', {cssc: editor.CssComposer});`

For example:
This is the returned css rule collection from using  
`editor.CodeManager.getCode(component, 'css', {cssc: editor.CssComposer});`

Returned:
```
.c1234 {
  color: 'white';
}

.classx .c1234{
 background: black;
}
```

What I need is to save and update it to like
```
.c1234 {
   color: 'yellow';
}

.classx .c1234{
 background: #222222;
}
```

---------------------------------------

I tried the cc.setClassRule('c1234', { background: #222222 }); but this csscomposer function is limited for 1 class only I need a dynamic function that can update the content returned by 
` editor.CodeManager.getCode(component, 'css', {cssc: editor.CssComposer});`

Thank you !

**Comment by artf** [comment]
Hi @froderf, for now, the only way to get that rule is to use [`CssComposer.get`](https://grapesjs.com/docs/api/css_composer.html#get) method. In your case, `.classx .c1234` is stored inside `selectorsAdd` as not being a single level class selector (eg. `.class1.class2`)
```js
editor.CssComposer.get([], null, null, { selectorsAdd: '.classx .c1234' })
```
