### ISSUE TITLE
Apply changes in style mager to one class

### ISSUE THREAD

**Issue by froderf** [artf/grapesjs#1560]
Hi @artf, I noticed that when I used the style manager it applies the style to the whole class of the component selected

for example if i have a component that has class like this
`<div class="class1 class2 c1234"></div> `

the style manager applies the style to
```
.class1 .class2 .c1234{
   color: #222222;
}
```

is there a way to apply the style only in ".c1234" class?
something like this via style manager
```
.c1234{
 color: #222222;
}
```

**Comment by artf** [comment]
https://github.com/artf/grapesjs/issues/1558
