### ISSUE TITLE
Css shorthand

### ISSUE THREAD

**Issue by froderf** [artf/grapesjs#1561]
Hello @artf , is there a way to not convert a css added into shorthand? 
for example:
`border: 4px solid rgb(239, 13, 24);`

after visiting the code viewer, the above css is converted to the following
```
    border-top-color: rgb(239, 13, 24);
    border-right-color: rgb(239, 13, 24);
    border-bottom-color: rgb(239, 13, 24);
    border-left-color: rgb(239, 13, 24);
    border-top-style: solid;
    border-right-style: solid;
    border-bottom-style: solid;
    border-left-style: solid;
    border-top-width: 4px;
    border-right-width: 4px;
    border-bottom-width: 4px;
    border-left-width: 4px;
```

------------------------------------------------------------------------------------

how can I prevent this kind of conversion? What I want is to remain this style
`border: 4px solid rgb(239, 13, 24);`
to what is it.

**Comment by artf** [comment]
That happens due to the browser's CSS parser, which is used by default in GrapesJS. You can prevent that by using [grapesjs-parser-postcss](https://github.com/artf/grapesjs-parser-postcss)
