### ISSUE TITLE
[Bug] Trait - Change Video Provider issue

### ISSUE THREAD

**Issue by tranthanhhoa** [artf/grapesjs#1563]
**Version:** 
0.14.40

**Bug:**
When you change "Provider" field -> all settings gone.
It happens in Chrome, Safari and Firefox, last versions.

**How to reproduce it:**
1. Goto https://grapesjs.com/demo.html
2. Drag a video block in Basic category into canvas
3. Change "Provider" field

**Expect:**
![image](https://user-images.githubusercontent.com/6691878/48056879-49664680-e1e5-11e8-915c-ba9b1053e34b.png)

**Result:**

![image](https://user-images.githubusercontent.com/6691878/48056929-669b1500-e1e5-11e8-8885-a910799ad660.png)

**Comment by Chilli-B** [comment]
Hello, sorry but this has not been fixed on version 0.14.41. The bug still exists.

**Comment by artf** [comment]
@Chilli-B the latest release is https://github.com/artf/grapesjs/releases/tag/v0.14.40

**Comment by Chilli-B** [comment]
@artf really? The current /dist/grapes.min.js starts with
/*! grapesjs - 0.14.41 */ 
That's why I assumed the next release has already been published.

**Comment by artf** [comment]
@Chilli-B you're right but releases are on NPM, the `dev` branch can go further

**Comment by albertanthony** [comment]
Hello, when is it release to fix this problems?
