### ISSUE TITLE
Css/fonts/icons issues

### ISSUE THREAD

**Issue by MisterFK** [artf/grapesjs#1564]
Hi, i have an CSS issue with my project GrapesJS and i don't know why...
I try to do the tuto and i haven't icons. 
![bug_grapesjs](https://user-images.githubusercontent.com/44830209/48116478-b4645b80-e27f-11e8-8535-644e10d729ed.PNG)

Other issue, i can't split the window in 2 columns.
I work with the last css and js version.
Organisation : 
assets/js/grapes.js
assets/css/grapes.min.css
assets/fonts/FontAwesome.otf [...] main-fonts.woff

Code : 

> <link rel="stylesheet" href="assets/css/grapes.min.css">
> <script src="assets/js/grapes.js"></script>
> 
> 
> 
> <div id="gjs"></div>
> 
> <script>
>   var editor = grapesjs.init({
>       container : '#gjs',
>       components: '<div class="txt-red">Hello world!</div>',
>       style: '.txt-red{color: red}',
>   });
> </script>

Thanks !

**Comment by artf** [comment]
Somehow you're not able to load fonts, check in your dev-tools, probably you will see the error
