### ISSUE TITLE
Issue to create a "2 columns" block

### ISSUE THREAD

**Issue by MisterFK** [artf/grapesjs#1565]
Hi, Have a new problem, i'm following the tuto and i want to create the block "2 columns" (or more).
I try to use (and understand, that's why i don't want to use grapesjs-blocks-basic) this part of code : 

 ```
blockManager.add('the-row-block', {
   label: '2 Columns',
   content: '<div class="row" data-gjs-droppable=".row-cell" data-gjs-custom-name="Row">' +
       '<div class="row-cell" data-gjs-draggable=".row"></div>' +
       '<div class="row-cell" data-gjs-draggable=".row"></div>' +
     '</div>',
 })

```
But i don't know what i need to do in the class ".row" and ".row-cell" to make this example work...
I try some styles but nothing appears and it's impossible to drag something inside but the elements exist in the layers panels.
![bug_columns](https://user-images.githubusercontent.com/44830209/48183167-3ff4ef80-e347-11e8-8994-44233f3bf045.PNG)

Thanks for help!

**Comment by artf** [comment]
You should add the proper style to see something, try with something like this
```js
blockManager.add('the-row-block', {
  label: '2 Columns',
  content: `
	<div class="row" data-gjs-droppable=".row-cell" data-gjs-custom-name="Row">
		<div class="row-cell" data-gjs-draggable=".row"></div>
		<div class="row-cell" data-gjs-draggable=".row"></div>
	</div>
	<style>
		.row {
		  display: flex;
		  justify-content: flex-start;
		  align-items: stretch;
		  flex-wrap: nowrap;
		  padding: 10px;
		  min-height: 75px;
		}
		.row-cell {
		  flex-grow: 1;
		  flex-basis: 100%;
		  padding: 5px;
		}
	</style>
`,
})

```
