### ISSUE TITLE
Components & JS Question

### ISSUE THREAD

**Issue by wirelessed** [artf/grapesjs#1569]
Hi,

In your [Components & JS](https://grapesjs.com/docs/modules/Components-js.html#basic-scripts) documentation, it is mentioned that scripts can be added into the "block" section under a script attribute.

However, after some trial and error, whenever the page is saved and reloaded, the script seems to have disappeared.

When I tried to add the script into the "model" section instead, it seems like it becomes permanent. Why is this so?

**Comment by artf** [comment]
Probably you're not storing correctly https://grapesjs.com/docs/modules/Storage.html
BTW you can add a script inside blocks but I highly recommend creating a the component for that case
