### ISSUE TITLE
Text section drag & drop bug

### ISSUE THREAD

**Issue by niagi** [artf/grapesjs#157]
Not sure where to post this first, because I was only able to reproduce this while in the newsletter editor plugin..

I got this bug when I downloaded the latest dev version of the grapes js (0.9.1) when testing locally, but I found it now again on the demo page (for the newsletter).

Dragging a Text Section causes a bug
`Uncaught TypeError: n.set is not a function 
at n.endMove (grapes.min.js:formatted:21770)`

(utils/sorter.js, line 763)

**Comment by artf** [comment]
thanks @niagi I've already fixed this issue, should be available in the next release
