### ISSUE TITLE
Issue when adding video block manually

### ISSUE THREAD

**Issue by boris1989529** [artf/grapesjs#1572]
I added Video Block manually like this.
<pre>
blockManager.add('video', {
	label: 'Video',
	category: 'Media',
	attributes: {class: 'fa fa-youtube-play'},
	content: {
		type: 'video',
		classes: ['website-media', 'website-video'],
		//traits: ['data-panoramic'],
		resizable: 0,
		draggable: '.website-cell, .website-block, .video-container, .media-container',
		style: {
			width: '100%',
			height: 'auto'
		}
	},
});
</pre>

It seems this produce this element when I drop the video block to editor.
`<div class="website-media website-video" data-gjs-type="video" onmousedown="return false">`
`          <video src="" class="gjs-no-pointer" style="height: 100%; width: 100%;"></video>`
`</div>`
**But the height of video element is different every time when I add several video blocks,**

**Comment by artf** [comment]
The `style` you see on `<video>` is only applied in canvas, your styles are applied to the wrapper and you should see them correctly applied in the export code
