### ISSUE TITLE
Open modal after drop element

### ISSUE THREAD

**Issue by boris1989529** [artf/grapesjs#1573]
How to show custom modal dialog when drop element on editor?
like asset modal dialog appears when drop image block to the editor.

**Comment by mcsekar12** [comment]
Use Editor events 
[https://grapesjs.com/docs/api/editor.html#available-events](url)
`editor.on('component:add', (model, argument) => {
        //filter using component name       
        if (model.getName() === 'modelName') {
          //show modal
        }
        //filter using css Class
        if (model.getAttrToHTML().class === 'className') {
          //show model
        }
      });`

**Comment by boris1989529** [comment]
Thanks. I'm new to this platform.
How to create my own modal dialog that has checkbox or select options or etc ?

**Comment by mcsekar12** [comment]
Please check the docs 
[https://grapesjs.com/docs/api/modal_dialog.html#modal](https://grapesjs.com/docs/api/modal_dialog.html#modal) 

use Modal.setContent();

**Comment by umairabid** [comment]
Not sure of @mcsekar12 gave the right solution but did point me to a good one.

Browsing the source code I read that `onActive` will be called for component which will be dropped on editor, however it was not being triggered even with correct flag configured.

@mcsekar12 suggestion allowed me to trigger that event manually and it worked 

```
this._builder.on('component:add', (model, argument) => {
            model.trigger('active')
        })
```

**Comment by artf** [comment]
@umairabid use the `activate` option on your block (eg. https://grapesjs.com/docs/getting-started.html#add-blocks) and then create a component with `onActive` method (exactly like [Image component](https://github.com/artf/grapesjs/blob/dev/src/dom_components/view/ComponentImageView.js#L62))
