### ISSUE TITLE
Select element that has several blocks as one unit.

### ISSUE THREAD

**Issue by boris1989529** [artf/grapesjs#1576]
I've created new block (like form or dialog, etc) that has several blocks such as search box, button, text fields, ...
This element doesn't need to editable. I just want to select this whole block as one unit.
Thanks.

**Comment by artf** [comment]
You might want to use `propagate` to inject indicated properties from component to its children
```js
bm.add('your-block', {
      label: 'lol',
	  // ...
      content: `<div>
        <div data-gjs-selectable="false" data-gjs-hoverable="false" data-gjs-propagate='["selectable", "hoverable"]'>
          <div>Text 1</div>
          <div>Text 2</div>
          <div>Text 3</div>
        </div>
      </div>`,
    })
```

**Comment by boris1989529** [comment]
Thanks. That's just what I want to do.
