### ISSUE TITLE
Border Color Issue

### ISSUE THREAD

**Issue by YashPrince** [artf/grapesjs#1579]
@artf  There is bug in  the border color if you drag a button on the editor and paste color like rgb(255, 0, 0) in border color and select any other element in side the editor without changing any  property and reselet the button then border color become rgb(255, and if we changes in any property of border then css breaks. Please check and fix it. Please provide any quick fix if there is any. Thanks in advance.
![grapejs](https://user-images.githubusercontent.com/40828744/48477887-c23e5180-e828-11e8-9a94-cc786f1ff57c.png)
![grapeerror](https://user-images.githubusercontent.com/40828744/48477894-c66a6f00-e828-11e8-890a-0f91ba9175ae.png)

**Comment by loganvolkers** [comment]
I can reproduce this on the [demo website](https://grapesjs.com/demo.html)

Copy and pasting can trigger this error, but it looks like it has nothing to do with copy and paste and everything to do with whitespace.

Values that work:

- `rgb(255,0,0)`
- `rgb(255,0,0)     `

Values that don't work:

 - `rgb(255,0,0    )   ` transforms to `rgb(255,0,0`
 - `rgb(255,0,   0)     ` transforms to `rgb(255,0,`
 - `rgb(255,0    ,   0)     ` transforms to `rgb(255,0`
 - `rgb(255,    0    ,   0)     ` transforms to `rgb(255,`
 - `rgb(      255,0,0)` transforms to `rgb(`

As far as I can tell this affect the field for border-color, but not for background or font-color.

**Comment by artf** [comment]
> everything to do with whitespace

Correct, it's just a [poor parsing](https://github.com/artf/grapesjs/blob/dev/src/style_manager/view/PropertyCompositeView.js#L114) on composed types. 
We should split the value (eg. `1px solid rgba(255, 0, 0, 0)`) by spaces (or even better `propertyModel.get('separator')`, which exists already) but taking care of functions
