### ISSUE TITLE
Problem with background image and send form

### ISSUE THREAD

**Issue by martcot** [artf/grapesjs#158]
I got problem with background image on a cell and send form. Grapejs is wrapped in a <form> tag. When I click on a cell, click on style editor click on the + where you can choose background image and oooop it send the form. Any idea @artf ?

**Comment by artf** [comment]
I think '+' button triggers the send because there is no 'type="button"'
You can wait for the fix or put the editor off from the form  (add update some hidden input on editor change)

**Comment by martcot** [comment]
Thank you! I will check if I can put editor off from the form.
