### ISSUE TITLE
Hiding text editor

### ISSUE THREAD

**Issue by goremukin** [artf/grapesjs#1585]
Your method "hideToolbar " does not provide for a situation where the text editor is greater than 100px.
As a result, its piece is visible in some situations (for example, at the beginning of the customRte.enable method)

![image](https://user-images.githubusercontent.com/25577658/48562239-d6568180-e902-11e8-8c1c-65c30e377067.png)
![image](https://user-images.githubusercontent.com/25577658/48562280-ea01e800-e902-11e8-94ea-9d6d8409ea32.png)

**Comment by artf** [comment]
Can you provide a live example? I'd expect the toolbar to be hidden due to display `none`

**Comment by goremukin** [comment]
> Can you provide a live example? I'd expect the toolbar to be hidden due to display `none`

If you connect CKEDITOR according to this instruction:
https://grapesjs.com/docs/guides/Replace-Rich-Text-Editor.html#interface

And put breakpoint at the beginning of the **enable** method, you can see the same as in the screenshot

**Comment by goremukin** [comment]
Just need to take into account that I have a large size ckeditor (more than 100px)

**Comment by artf** [comment]
> Put a breakpoint at the beginning of the enable method and make a double click on the element, you can see the same thing as in the screenshot

Ok, but what is the point if at the end of the execution the element will be hidden?

**Comment by goremukin** [comment]
> > Put a breakpoint at the beginning of the enable method and make a double click on the element, you can see the same thing as in the screenshot
> 
> Ok, but what is the point if at the end of the execution the element will be hidden?

Yes, the toolbar will disappear later, but this flicker is noticeable 😥
The easiest and fastest fix is to change 100px to 1000px
The appearance of CKEDITOR immediately becomes much more enjoyable

**Comment by artf** [comment]
> but this flicker is noticeable

ah, this is the point then.

> The easiest and fastest fix is to change 100px to 1000px

I agree, would you like to create a PR? :)

**Comment by goremukin** [comment]
> I agree, would you like to create a PR? :)
With pleasure 😊
