### ISSUE TITLE
[Question] update Trait select option dynamically

### ISSUE THREAD

**Issue by boris1989529** [artf/grapesjs#1586]
I tried this to update trait selection.
var updateTrait = function(id, name) {

	var typeTrait = model.get('traits').where({name: 'type'})[0];
	var options = typeTrait.get('options');

	options.push({value: id, name: name});
	typeTrait.set('options', options);
};
But after click the element, it shows this error and the trait doesn't update.

![social attache local - edit templatereplacevalue1_en-us - google chrome 2018-11-16 02 39 55](https://user-images.githubusercontent.com/35139226/48586277-edb85d80-e948-11e8-863e-4eaaad7b5766.png)

**Comment by AkibDeraiya123** [comment]
Hey @boris1989529 
I am also stuck at this point to update the traits dynamically even in scenario i also need to push the option into the once of my trait.

Did you got any solution for this?
It would be your pleasure if you can share the solution for me if you found.
Thanks in advance.
