### ISSUE TITLE
Issue receiving loaded data from remote storage.

### ISSUE THREAD

**Issue by brandonburr86** [artf/grapesjs#159]
Hello,

I'm implementing remote storage for my editor and I'm running in to some JSON related problem. I'm thinking it's an error on my end, so let me know if I'm doing it wrong or if it's a bug in GJS.

Here is my code:

`
var editor = grapesjs.init({
        container : '#gjs',
		storageManager: {
		     type: 'remote',
		     urlLoad: "/admin/newbuilder/get_page/707/register/",
		     contentTypeJson: true,
		     params: {},
		   },
		allowScripts: 1,
		showOffsets: 1,
		autoload: 1,
		noticeOnUnload: 0
    });
`

This is the JSON response from that URL:

`
 {"gjs-html":"SOME HTML", "gjs-css":"SOME CSS"}
`

And when I dump the object that the remote storage module loads using this code:

`
	editor.on('storage:load', function(obj) {
	  console.log('Loaded ', obj);
	})
	editor.on('storage:store', function(obj) {
	 console.log('Stored ', obj);
	})
`

For some reason it's not correctly parsing the JSON object. I get this from the debugger: 

![screen shot 2017-07-12 at 12 06 57 pm](https://user-images.githubusercontent.com/29148060/28129879-a5e0b9f2-66fa-11e7-8384-253a3d45676c.png)

What am I doing wrong?

Thanks,

Brandon

**Comment by brandonburr86** [comment]
Actually, just resolved the issue. My PHP framework was kicking out a space in front of the JSON object. Notice obj[0]. I'm closing the issue and going to leave it for reference.

**Comment by brandonburr86** [comment]
I noticed my PHP framework was kicking a space out in front of the JSON object. Resolved that but it's still not working.

**Comment by brandonburr86** [comment]
Got it to kick back the correct JSON object after removing the space by using: `header('Content-Type: application/json');` in my PHP code.

Now it's returning the JSON object but still not rendering a page. It's blank.

**Comment by brandonburr86** [comment]
Got it resolved. Page is successfully loading from remote. The final issue was I called editor.render(); manually and that was causing it to break.

**Comment by xeux** [comment]
@brandonburr86 can you copy more of you code please? I'm having the same issue but still not working, I also noticed when content type is set to json, GrapesJS do not read it correctly, it have to be plain.

**Comment by souhirfeki** [comment]
Hello,
 I'm having the same issue but still not working, i receive the json string from my webapi (get method) i'm using .Net application.
Have you an example of using with .net application please,

Thanks,
Souhir
