### ISSUE TITLE
[Bug] Component attributes forced to lowercase on load when using fromElement

### ISSUE THREAD

**Issue by riteshdalal** [artf/grapesjs#1591]
When GrapesJs is initialized using "fromElement", the attributes in the HTML tags of the element are forced to lowercase. 

View live example (uses latest version):
https://codesandbox.io/s/zr139yj3m3

Look at the index.html file and the on-Tap property of the div. But upon initializing, if you view the code using the export command, you will see that the attribute has been changed to on-tap.

Expected behavior would be that the attribute name would remain unchanged.

**Comment by artf** [comment]
> Expected behavior would be that the attribute name would remain unchanged.

This is how HTML5 works

**Comment by riteshdalal** [comment]
Thanks @artf. If I create a trait with camelcase name then it seems to be working fine when value added through "Settings" but when element is initialized on canvas or block is dropped then the name is forced lowercase. 

I am trying to get Angular attributes added to the template - like *ngIf - can you please suggest a good way forward.

**Comment by artf** [comment]
Then you just shouldn't initialize the editor by HTML, but use Component objects, then check how to store correctly your template data https://grapesjs.com/docs/modules/Storage.html#store-and-load-templates
