### ISSUE TITLE
get uncompressed of grapesjs-preset-webpage.min

### ISSUE THREAD

**Issue by 4URGB** [artf/grapesjs#1596]
Hi,

to understand and learn how your preset is working, it will be much more easier if you can upload a uncompressed file of grapesjs-preset-webpage.min to the package - what do you mean? #

**Comment by 4URGB** [comment]
its no issue, but an answear will be nice...or not

**Comment by cjpollard** [comment]
All the code is here. https://github.com/artf/grapesjs-preset-webpage
