### ISSUE TITLE
Can we add resizable property in gjs-layer-manager frame?

### ISSUE THREAD

**Issue by Abhisheknanda1344463** [artf/grapesjs#1597]
hi @artf 
Is it possible to add resizable property on the frame of layer-manager as screen shot below 

![screen shot 2018-11-20 at 3 33 37 pm](https://user-images.githubusercontent.com/20657737/48766104-b267b700-ecd9-11e8-855e-81421822069f.png)

i want to add dynamic resizable property for this frame.
Thanks.

**Comment by artf** [comment]
You can create external resizable panels like in this example https://codepen.io/artf/full/MQpZPj/
or you can use any other kind of javascript library and make the panel resizable (once the editor is loaded)

**Comment by Abhisheknanda1344463** [comment]
@artf how can i achieve this for existing layer-manager in newsletter plugin.
Should i need to add same classes as above on editor load .

Please Let me know from where i can start.

Thanks
