### ISSUE TITLE
[Bug] Security Vulnerability Detected

### ISSUE THREAD

**Issue by kewilson** [artf/grapesjs#1598]
Hi, our SAST scanner detected the following, thought you might like to know. 

https://raw.githubusercontent.com/artf/grapesjs/dev/dist/grapes.js

Code (Line #29702): this.setElement(this._createElement(_.result(this, 'tagName')));

Client_DOM_Stored_XSS exists @ public/dist/grapes.js
Severity: High
CWE: 79
https://cwe.mitre.org/data/definitions/79.html

**Comment by artf** [comment]
Thanks for the report @kewilson but that line is totally legit for the editor. The library itself shouldn't be "able to hurt", most of the vulnerabilities might be added during the integration
