### ISSUE TITLE
ho to change style of added dom element

### ISSUE THREAD

**Issue by altalker** [artf/grapesjs#160]
I added text h2 title:
            var domc = editor.DomComponents;
                var comp1 = domc.addComponent({
                    tagName: 'h2',
                    type:'text',
                    removable: true, // Can't remove it
                    draggable: true, // Can't move it
                    copyable: true, // Disable copy/past
                    content: title, // Text inside component
                    style: { color: 'red' },
                    attributes: { title: 'title',id:'header' }
                });

I need to change the color after adding item. How do I change the color and background css?

**Comment by artf** [comment]
You can make use of some listener
```js
editor.on('component:add', function(model) {
 // ... put some check logic
 model.set('style', { color: 'blue' });
})
```

**Comment by altalker** [comment]
What I am struggling with is with changing values of DOM Components after reloading of the Canvas.
      var comps = editor.DomComponents;
        var hType = comps.getType('div');  ****I am trying to get the exact component by ID not by Type****
        var mmodel = hType.model;    **error- does not work**
        mmodel.set('style', { color: $("Color").val() });
