### ISSUE TITLE
[QUESTIONS] - Panel visibility

### ISSUE THREAD

**Issue by arthuralmeidap** [artf/grapesjs#1602]
Hey @artf ,

  How have you been?
  Quick question: a Panel has a property called `visible`. I'm trying to set it to false but nothing happens.
  I'm getting the panel after the  GrapesJS is rendered like `editor.Panels.getPanel('myId').set('visible', false)`;
  I was digging into the source code and I didn't find any use to the `visible` property for the Panel model. 
  Am I missing something?
  Thanks in advance

**Comment by arthuralmeidap** [comment]
Oh, I didn't say but I want to hide/show the panel according to some condition.

I know how  I could get the panel html element itself and change the `display` but I was wondering about the `visible` property

**Comment by artf** [comment]
> Toggle the style display property between none and block?

Yeah I think it's enough, but in case it's `true` just don't set any `display` (eg. if someone had customized the panel with `flex` that would break its layout)

**Comment by arthuralmeidap** [comment]
created MR https://github.com/artf/grapesjs/pull/1603
