### ISSUE TITLE
Issue with grapjs.init()

### ISSUE THREAD

**Issue by umairabid** [artf/grapesjs#1604]
Apparently options passed to `grapjs.init()` are not being deep cloned and same object is being mutated which was originally passed. This is creating a weird issue, I cannot do this

```
this._builder = grapesjs.init({
            container : '#gjs',
            plugins: ['gjs-preset-newsletter'],
            pluginsOpts: myOptions
});
```

Mutation can be seen by logging `myOptions` before `init` and the result is very weird, editor without any components 

<img width="1440" alt="screen shot 2018-11-26 at 10 15 55 am" src="https://user-images.githubusercontent.com/2821084/48994313-634fd500-f164-11e8-9ab4-2e31b86717a7.png">

I had to fix it using `cloneDeep` of lodash like

```
this._builder = grapesjs.init({
            container : '#gjs',
            plugins: ['gjs-preset-newsletter'],
            pluginsOpts: cloneDeep(myOptions)
});
```

My version is `"grapesjs": "^0.14.43",`

**Comment by artf** [comment]
The option object is passed to the plugin as it is and there is no reason to clone it
