### ISSUE TITLE
[Question] Customize CSS class name

### ISSUE THREAD

**Issue by narendravaghela** [artf/grapesjs#1608]
GrapesJs editor creates a unique class for element and adds CSS rules to it. For example,
```
.c1731 {
    color: #FA8072;
    border: 2px solid #FA8072;
}
```
Now, is there any way to customize this behaviour?
I want it to be `.parent-namespace .c1731` instead of just `.c1731`? 

```
.parent-namespace  .c1731 {
    color: #FA8072;
    border: 2px solid #FA8072;
}
```

Is there any solution to do so?

Thanks

**Comment by narendravaghela** [comment]
I found this related issue - https://github.com/artf/grapesjs/issues/391

**Comment by artf** [comment]
If you need to update CSS rules you should rely on [CSS Composer module](https://grapesjs.com/docs/api/css_composer.html)
