### ISSUE TITLE
[Bug]: adding css variables as style manager property

### ISSUE THREAD

**Issue by gcoda** [artf/grapesjs#1614]
trying to add css variable to style manager causing error:
`Uncaught TypeError: Cannot read property 'toUpperCase' of undefined` [fiddle](https://jsfiddle.net/GCoda/ke3p0mgj/)

```javascript
editor.StyleManager.addSector('test', {
  name: 'My Vars',
  open: true,
  properties: [{
    type: 'integer',
    property: '--my-var',
  }],
})
```

Am i doing something wrong?

Fixed by changing [utils/mixins.js#L76](https://github.com/artf/grapesjs/blob/62cad47e9c435b6e3bca5723a8b15b907bf4d207/src/utils/mixins.js#L76) to
```javascript
const camelCase = value => {
  const values = value.split('-').filter(v=>!!v);
```

**Comment by artf** [comment]
Hi @gcoda you should use `property` for the CSS property name (eg. `color`)

**Comment by gcoda** [comment]
Yes, it works with regular properties like `color`, is there another way to edit css custom properties on components?

**Comment by artf** [comment]
> is there another way to edit css custom properties on components?

Well, not currently, the style manager was made to edit style properties and not CSS custom one, but they have a lot in common

**Comment by gcoda** [comment]
> Well, not currently

i am storing `composite` type inside a variable and it is editable in style manager.
It works like a charm if check for `undefined` after `split('-')`, am i missing something?

**Comment by artf** [comment]
Probably it works for your case, from my general point of view this is probably not enough for a complete use of CSS custom properties. BTW, if you want to submit that as a PR I'll accept it
