### ISSUE TITLE
[Feature] support edit credentials request attribute on Remote Storage

### ISSUE THREAD

**Issue by jmtt89** [artf/grapesjs#1615]
The credentials options its forced to be 'include' on Remote Storage. 

https://github.com/artf/grapesjs/blob/master/src/storage_manager/model/RemoteStorage.js

```
    fetchOptions = {
      method: opts.method || 'post',
      credentials: 'include',
      headers
    };
````

**Comment by arthuralmeidap** [comment]
Created MR #1705
