### ISSUE TITLE
grapesjs editor.gethtml() not work in Edge Explorer

### ISSUE THREAD

**Issue by JordanTGVG** [artf/grapesjs#1616]
In my project i'm using this code to get the html from the grapesjs editor:

`var html = window.frames[0].editor.getHtml();`

my editor is in iframe and is displayed in another page, and it works good in chrome and mozzila but in edge i cannot get the html code because i can see this javascript error:

`Unable to get property 'getHtml' of undefined or null reference`

It seems like cannot find the editor with the previous code? why? is there any suggestions?

**Comment by artf** [comment]
This has nothing to do with GrapesJS itself, please investigate why in Edge you can find `window.frames[0].editor`
