### ISSUE TITLE
Child components are not tracked in models ??

### ISSUE THREAD

**Issue by ploutos27** [artf/grapesjs#1618]
Hi, I'm facing as strange issue and I need your help.  when I move components inside blocks, at the view model the changes successfully applied, but models it seems that grapsejs is not tracking (or I miss something), the parent components (or blocks your can check the image 1 [here](https://user-images.githubusercontent.com/12737690/49217101-61407d00-f3d5-11e8-8e12-c7dbd5e954e0.PNG))  are working fine but if I have inner components (or inner 'child blocks', as image 2 [here ](https://user-images.githubusercontent.com/12737690/49217104-643b6d80-f3d5-11e8-9f35-4526872ee429.PNG)here shows is not track the change) at position 0 it shows that the **footerpayment**  is there but in the view model the user swap the two components so **footercopyrights**   at position 0 and **footerpayment**  at position 1 

Thank you !  

![1stimage](https://user-images.githubusercontent.com/12737690/49217101-61407d00-f3d5-11e8-8e12-c7dbd5e954e0.PNG)

![2ndimage](https://user-images.githubusercontent.com/12737690/49217104-643b6d80-f3d5-11e8-9f35-4526872ee429.PNG)

**Comment by artf** [comment]
Please create a live demo with steps to reproduce the issue

**Comment by ploutos27** [comment]
> Please create a live demo with steps to reproduce the issue

Hi artf, thanks please give me 1-2 days to create a live demo! 

Thanks!

**Comment by ploutos27** [comment]
@artf here is the live demo: [here](https://codesandbox.io/s/zx7x8mqyl)

I have also create a live video to help you understand where am facing the issue.. 
video link [here](https://screencast-o-matic.com/watch/cFleXQrtg4) 

Let me know 
Thank you for your help!!!

**Comment by artf** [comment]
I've tried your demo but wasn't able to see the Overview panel content as in your video, so I've only played around with your blocks (Widgets and Blocks categories) and everything was as expected.
Before move
![schermata 2018-12-07 alle 12 36 28](https://user-images.githubusercontent.com/11614725/49645706-37aed380-fa1d-11e8-83a7-663fc3ce476b.png)
After move
![schermata 2018-12-07 alle 12 37 07](https://user-images.githubusercontent.com/11614725/49645719-41383b80-fa1d-11e8-836b-4c2bf649fa18.png)

**Comment by ploutos27** [comment]
@artf Hi & thanks you. I have disable the overview section complete. Follow this steps: open block - >  and find scroll down until you find 'desktopheader'  drag & drop it and it will load the block with the components..  like img 
![capture222](https://user-images.githubusercontent.com/12737690/49648011-fc1c0580-fa2c-11e8-98fd-b8fd65e3c5d7.PNG)
.

If you try to move something inside the 'desktopheader' for example changing position of the child components,  model is not affected...

**Comment by ploutos27** [comment]
@artf I Think I figure out what was the problem :o  I have use the content: to pass a custom component (for the title of each component ) with the actual component, and it seems like it mess up the whole situation on how grapse is read ..  If you check on ./api/get-widgets.js at line 59 I use the following:

```
content: {
 classes: ['block'],
 type: 'block',
 attributes: { ... },
   content: `<div class="title">${arrBlocks[i].value.code} </div>`,
   components: getInner(arrBlocks[i].value.blocks)
}
```

I remove the content: and I use before pseudo class and pass a custom data-attr for the title and it seems likes now it's working.. :) 

Let me know if my assumption is correct or I miss something again :) 

Thanks!

**Comment by artf** [comment]
Ah ok, I didn't notice that. The `content` inside Component definition is for static texts (like the one used inside Rich Text Editor), indeed for your case, use only `components`.
