### ISSUE TITLE
[Question] Custom Modal Classes

### ISSUE THREAD

**Issue by magnesiumdaily** [artf/grapesjs#1619]
Hi there,

Great app, much appreciated that you have put this out there for the community.

Just a quick question, I would like to modify the size and appearance of the different modals, ie. Export, Image upload etc.

But it seems there is no unique class/ID on any of the modals.

Is there an easy way to add a unique class based on the modal type?

I would like to add it specifically to the "gjs-mdl-dialog" element.

Thanks!

**Comment by artf** [comment]
You can do it by intercepting their commands
```js
const getDialog = () => document.querySelector('.gjs-mdl-dialog');
const assetsCls = 'gjs-mdl-dialog--assets';
editor.on('run:open-assets', () => getDialog().classList.add(assetsCls))
editor.on('stop:open-assets', () => getDialog().classList.remove(assetsCls))
```

**Comment by magnesiumdaily** [comment]
Great, thanks @artf.

I will give it a go.
