### ISSUE TITLE
Same Design for all blocks

### ISSUE THREAD

**Issue by froderf** [artf/grapesjs#1623]
Hi @artf , this is not actually a bug but I would like to ask

if there is something like global design for every blocks.

for example all images has same border and border radius

What I want to do is
1. Set global design that will apply on all blocks. e.g img, button, text, columns
2. Global Design that is editable and will apply on blocks realtime.

**Comment by ProfSaputo** [comment]
I think for the first Point you are searching for normal Components? [https://grapesjs.com/docs/modules/Components.html#how-components-work](url)

**Comment by froderf** [comment]
I did look at the link but it doesn't have what I'm looking for but I really appreaciate your help.

What I'm looking for is something like this:

1. I have a custom UI that generates this code below
```
img{
    border: 1px solid black;
    border-radius: 10px;
}
```

2. Now I need this generated code to be applied on all images on the canvas.

Thank you. :)

**Comment by artf** [comment]
@froderf it's up to you how to create/maintain a Design System, you can import your classes and them by changing them you will change the design on any component with that class
