### ISSUE TITLE
[Question]: $('.gjs-trt-traits') is null (trying to have 'Settings' sector under the style)

### ISSUE THREAD

**Issue by SeongwoonHong** [artf/grapesjs#1627]
Hi,
I'm using webpage preset and trying to have Settings sector under Style like the demo by doing this (exactly the same as demo.html) but the problem that i have is $('.gjs-trt-traits') this is null therefore, if I toggle 'Settings' under Styles, it is empty. Please let me know..Thank you!

    var traitsSector = $('<div class="gjs-sm-sector no-select">'+
    '<div class="gjs-sm-title"><span class="icon-settings fa fa-cog"></span> Settings</div>' +
    '<div class="gjs-sm-properties" style="display: none;"></div></div>');
    var traitsProps = traitsSector.find('.gjs-sm-properties');
    traitsProps.append($('.gjs-trt-traits'));
    $('.gjs-sm-sectors').before(traitsSector);
    traitsSector.find('.gjs-sm-title').on('click', function(){
      var traitStyle = traitsProps.get(0).style;
      var hidden = traitStyle.display == 'none';
      if (hidden) {
        traitStyle.display = 'block';
      } else {
        traitStyle.display = 'none';
      }

**Comment by artf** [comment]
Traits are not created by default if not requested, indeed I'm doing this in the demo https://github.com/artf/grapesjs/blob/gh-pages/demo.html#L1407-L1408
