### ISSUE TITLE
how to display Css in Code viewer in newsletter plugin?

### ISSUE THREAD

**Issue by rajeshmaropost** [artf/grapesjs#1631]
Hi @artf 
i want to display my css in replace of 
`  protectedCss: '* { box-sizing: border-box; } body {margin: 0;}',`
how can i achieve in newsletter plugin when i write css property it'll reflected in editor but not seen in code Viewer

**Comment by artf** [comment]
The export command in the newsletter plugin [doesn't take into account `protectedCss`](https://github.com/artf/grapesjs-preset-newsletter/blob/e0a91636973a5a1481e9d7929e57a8869b1db72e/src/openExportCommand.js#L45), you can submit a PR if you want
