### ISSUE TITLE
[Bug]: editor.runCommand('gjs-get-inlined-html') returns undefined (preset-webpage)

### ISSUE THREAD

**Issue by SeongwoonHong** [artf/grapesjs#1633]
Hi, Artur

I'm using grapesjs-preset-webpage v0.1.10, grapesjs v0.14.29

I'm trying to save templates with inline css rather than having classes. 
but editor.runCommand('gjs-get-inlined-html') returns undefined. I've read your comments regarding this on other issue tickets but you said it's for newsletter.

is it not available for preset webpage..? is there any way to save template with inline css instead of classes?

Thank you!

**Comment by SeongwoonHong** [comment]
P.S) Just tested on newsletter, it also returns undefined..

**Comment by artf** [comment]
1. You're not using the latest version
2. Webpage preset doesn't have `gjs-get-inlined-html` command, but you can copy it from the newsletter preset if you need it
3. It works here https://grapesjs.com/demo-newsletter-editor.html
