### ISSUE TITLE
Action on  built in checkbox traits

### ISSUE THREAD

**Issue by alialrabi** [artf/grapesjs#1634]
i want to add action to built in checkbox trait when i checked it 
![screenshot from 2018-12-06 13-39-10](https://user-images.githubusercontent.com/7685208/49582148-bb54bb80-f95c-11e8-9230-9af609ba9cd8.png)

**Comment by artf** [comment]
Read here first https://grapesjs.com/docs/modules/Traits.html#built-in-trait-types
