### ISSUE TITLE
Text component behaviour

### ISSUE THREAD

**Issue by frasza** [artf/grapesjs#1635]
We are having issues using Text component where its behaviour is different when using Enter for new paragraph or using double Enter where we would like to insert some space between.

If we use single Enter in Text component this is the result:
```
<div id="i2bhr5" style="padding: 10px;">Insert your text here
  <div>and here as well
  </div>
  <div>and here
  </div>
</div>
```
![image](https://user-images.githubusercontent.com/22049682/49583911-e38eeb00-f959-11e8-9ae9-51a5952052e2.png)

But if we use Text component with two Enters for one extra free line, this is the result:
```
<div id="i2bhr5" style="padding: 10px;">Insert your text here
  <div>
    <br>
    <div id="if94j1">and here as well
    </div>
    <div id="if94j1">
      <br>
    </div>
    <div id="is6bvk">and here
    </div>
  </div>
</div>
```
![image](https://user-images.githubusercontent.com/22049682/49583970-0c16e500-f95a-11e8-8d72-f1aa18593964.png)

What you see here is behaviour after I reload the template and when using more Enter for spacing, first line doesn't stay Text anymore but becomes Box and it becomes impossible to edit it. While editing it, it is fine, the problem is here at reloading/importing the template.

Any ideas?

**Comment by artf** [comment]
You're storing the template incorrectly https://grapesjs.com/docs/modules/Storage.html#setup-remote-storage
