### ISSUE TITLE
Unable to Insert Images into 1 Section Layout on Safari

### ISSUE THREAD

**Issue by prina92** [artf/grapesjs#1636]
Hello!

This is an issue that only happens on Safari. We detected it on our project and thought there was something wrong with our code but found later that this issue is reproducible on https://grapesjs.com/demo-newsletter-editor.html

Steps:
- On Safari go to https://grapesjs.com/demo-newsletter-editor.html and clear the canvas (clearing the canvas is not necessary but it helps with clarity on the issue)
- Drag and drop a 1 Section Layout
- Try to drag and drop an image inside the 1 Section

Notice that you won't be able to do so and the green line indicating where the image will be dropped skips the inside of the 1 Section block and lands above or below the section

Extra info that might be helpful:
- Drag and drop a 1/2 section and try to do the same.

Notice that the feature is working correctly for the rest of the sections as you will be able to add images within. The problem only occurs for 1 Section and only on Safari. Tested on other browsers and feature works as intended.

I'll attach a gif showing the issue for better clarity:
![grapes safari bug](https://user-images.githubusercontent.com/35826770/49593774-197ca100-f953-11e8-874f-28b5a3c4a152.gif)

We are willing to research and help with issue! ^^

Thanks!

**Comment by alimajed93** [comment]
Hello @prina92, @artf ,

I found a solution for this.
I will be creating a MR for the 'grapesjs-preset-newsletter' project that will fix this issue.
The problem mainly was in the HTML of the 1 section block.

Regards.

**Comment by artf** [comment]
Thanks @prina92 for the report and @alimajed93 for the coming PR.
I'm gonna close this issue as is not related to the core itself
