### ISSUE TITLE
[Question]: Would it be possible to have change settings under style manager in a way that it has href when a link is created?

### ISSUE THREAD

**Issue by SeongwoonHong** [artf/grapesjs#1639]
I'm using preset newsletter with built-in RTE (do not want to use ck editor like the demo)

In order to make any text to link, i need to click the link button in the RTE and lose the focus and re-click the text again in order to see Settings that has href in it.
Is there any way to do it in a way that the moment i click the link button in the RTE, i have settings that have href in it and opened it..

Thank you Artur :)

**Comment by artf** [comment]
@SeongwoonHong you can do whatever you want by adding your custom action to RTE
https://grapesjs.com/docs/api/rich_text_editor.html#add

**Comment by SeongwoonHong** [comment]
> @SeongwoonHong you can do whatever you want by adding your custom action to RTE
> https://grapesjs.com/docs/api/rich_text_editor.html#add

@artf  I can't figure it out.. could you give me a sample code if you don't mind...?
Can't figure out how to open settings that has href once a link component is created...
so what I'd like to do is the moment you click link button in RTE, i'd like to open 'Settings' and it should have href and title and stuff underneath...

Thank you.

**Comment by artf** [comment]
Settings/Traits are for components. When you select the text there are no component, just a text, so probably you have to create your own panel (or [Modal](https://grapesjs.com/docs/api/modal_dialog.html)) with all the fields

**Comment by SeongwoonHong** [comment]
@artf I'm so sorry for asking silly question but.. what do you mean by 'When you select the text there are no component, just a text'?
What i meant was when you click any text in side Text Block component..
