### ISSUE TITLE
ID attribute added automatically

### ISSUE THREAD

**Issue by brandonburr86** [artf/grapesjs#164]
Hello,

I've got some client code that for some reason is getting saved with duplicate ID's on a div. Here is the resulting code:

`<div id="c1198"  id="optin1-text">`

The original was `<div id="optin1-text">`.

How do I disable/fix that?

Brandon

**Comment by artf** [comment]
I guess I know where is the issue, will fix it for the next release

**Comment by brandonburr86** [comment]
Where is the issue? I'll create a temporary patch to fix it on my end before you put out the next release.
