### ISSUE TITLE
[QUESTIONS] Move panel to the left

### ISSUE THREAD

**Issue by afdallah** [artf/grapesjs#1645]
Hi grapesjs team,

I am trying to move BlockManager, StyleManager, TraitManager etc to the left.
I have tried to use `appendTo` but I don't know why the default panel still shows up.

![grapesjs](https://user-images.githubusercontent.com/11598084/49780892-13b40080-fd43-11e8-9f4a-6412db7725f4.png)

Is it to possible to move all things within the right sidebar to the left?.
Or append them to the new html element and remove the default one.

```html
<div class="row">
    <div class="column" style="flex-basis: 300px; background: #463a3c; color: #fff; text-align: center">
      Block Manager
      <div id="blocks" class="column"></div>

      Style Manager
      ...
    </div>

    <div class="column" style="flex-basis: calc(100% - 300px)">
      <div id="canvas" style="height:0px; overflow:hidden">
      </div>
    </div>
  </div>
```

```javascript
var editor = grapesjs.init({
  blockManager: {
        appendTo: '#blocks'
      },
      styleManager: {
        appendTo: '#style-manager-container'
      },
      selectorManager: {
        appendTo: '#selectors-container',
      },
      traitManager: {
        appendTo: '#traits-container',
      },
})
```

Sorry @artf if my question is too basic, but I have been digging to the docs and couldn't find any clue.

**Updated**
I found a way to remove the default panel by giving an empty array to the value of `defaults` property
```javascript
panels: {
  defaults: []
},
``` 
But it's just removing the panel, not the layout. It looks like this.
![empty panel](https://user-images.githubusercontent.com/11598084/49782631-950e9180-fd49-11e8-9466-7587b7599132.png)

I managed to remove the brown layout using CSS.
```css
.gjs-cv-canvas {
  /* remove the right gap */
  width: 100%;

  /* remove the top gap */
  height: 100%;
  top: 0
}
```

![screenshot at dec 11 13-38-44](https://user-images.githubusercontent.com/11598084/49782787-1e25c880-fd4a-11e8-84dd-c137c26c22aa.png)

I am still wondering whether I am doing it right or not. Please enlighten me

**Comment by artf** [comment]
Correct, as you see I'm doing the same here: https://grapesjs.com/docs/getting-started.html#start-from-the-canvas

**Comment by afdallah** [comment]
Thank you for confirming
