### ISSUE TITLE
[FEATURE REQUEST] Remove Font-Awesome from compiled css

### ISSUE THREAD

**Issue by gimzani** [artf/grapesjs#1648]
Hello - quick suggestion:

I'd suggest removing font-awesome from the minified css file.

The reason for this is that many developers are using node - and there is a conflict with loading the font files where it says "OTS parsing error: invalid version tag".  

If instead you declare that grapes requires a separate install of font-awesome you get several benefits:

* No conflicts using node
* The developer can decide which version of font-awesome they want to use.
* The developer can store the css wherever they like

Just a thought.

Cheers!

**Comment by artf** [comment]
Thanks for the request, Benjamin. Actually, we have already an open issue about this argument [here](https://github.com/artf/grapesjs/issues/644), so I close this one
