### ISSUE TITLE
0.14.43 update causes ckeditor focus to stop reacting in mjml

### ISSUE THREAD

**Issue by kickbk** [artf/grapesjs#1649]
@art, I realize you stopped supporting your MJML project, but if you don't mind, I noticed an issue that the latest update causes.

To reproduce:
1. Go to https://grapesjs.com/demo-mjml.html
2. Double click in the middle of a text element
3. The text area will highlight and possible one of the words will get selected.
4. click again anywhere in the middle of the text. For example, try selecting a word.

You will see that it is not possible anymore to select where in the text to position the blinking text cursor or select parts of the text.

This issue is not present in version 0.14.40 and below

**Comment by artf** [comment]
The same version of grapesjs with the same CKEditor plugin works fine [here](https://grapesjs.com/demo-newsletter-editor.html), so it seems not related to the latest version

**Comment by kickbk** [comment]
Let me demonstrate. I am going to double click a text field and then move around and try to click inside.

This is v0.14.40 - Works
![v0 14 40](https://user-images.githubusercontent.com/31323376/49907540-6d8ff580-fe2b-11e8-9998-a282a7126159.gif)

This is v0.14.43 - Has the issue.
![v0 14 43](https://user-images.githubusercontent.com/31323376/49907622-d0818c80-fe2b-11e8-927c-a317e871aba7.gif)


And same issue on https://grapesjs.com/demo-mjml.html. v0.14.43 - has the issue
![grapesjs-mjml](https://user-images.githubusercontent.com/31323376/49907605-b9db3580-fe2b-11e8-87e7-1cd01baf711c.gif)

**Comment by kickbk** [comment]
@artf I don't wanna be a pain, but would you please have a look at this issue? It's the same with v0.14.49 and you can see this bug on your demo page https://grapesjs.com/demo-mjml.html

**Comment by artf** [comment]
mjml demo is not my priority right now, but if you submit a PR I'd be glad to review it

**Comment by acamenhas** [comment]
Hi artf, i'm also interesed in this topic too.

Can we have access to the source code of:
https://grapesjs.com/demo-newsletter-editor.html

Thanks

**Comment by kickbk** [comment]
Resolved:
The issue happens with the functions `enableEditing` and `disableEditing` in the mjml components.
To fix, replace those functions with the [new ones](https://github.com/artf/grapesjs/blob/62cad47e9c435b6e3bca5723a8b15b907bf4d207/src/dom_components/view/ComponentTextView.js), however, I also update the `pointerEvents` to `none` on `disable` and `all` on `enable`.

```
// place inside gjs-mjml/components/Text.js

...

events: { // We need this to listen to the double click event
	dblclick: 'enableEditing',
},

enableEditing(e) {
	e && e.stopPropagation && e.stopPropagation();
	const rte = this.rte;

	if (this.rteEnabled || !this.model.get('editable')) {
		return;
	}

	if (rte) {
	try {
		this.activeRte = rte.enable(this, this.activeRte);
		} catch (err) {
			console.error(err);
		}
	}

	this.rteEnabled = 1;
	this.toggleEvents(1);

	this.getChildrenContainer().style.pointerEvents = 'all'; // << Enable editing of element
},

disableEditing() {
	const model = this.model;
	const editable = model.get('editable');
	const rte = this.rte;
	const contentOpt = { fromDisable: 1 };

	if (rte && editable) {
		try {
			rte.disable(this, this.activeRte);
		} catch (err) {
			console.error(err);
		}

		const content = this.getChildrenContainer().innerHTML;
		const comps = model.get('components');
		comps.length && comps.reset();
		model.set('content', '', contentOpt);

		// If there is a custom RTE the content is just baked staticly
		// inside 'content'
		if (rte.customRte) { // << This one we use since CKEditor is a custom rte
			// Avoid double content by removing its children components
			// and force to trigger change
			model.set('content', content, contentOpt);
		} else { // We don't use this
			const clean = model => {
				const selectable = !['text', 'default', ''].some(type =>
				model.is(type)
				);
				model.set({
				editable: selectable && model.get('editable'),
				highlightable: 0,
				removable: 0,
				draggable: 0,
				copyable: 0,
				selectable: selectable,
				hoverable: selectable,
				toolbar: ''
				});
				model.get('components').each(model => clean(model));
			};

			// Avoid re-render on reset with silent option
			model.trigger('change:content', model, '', contentOpt);
			comps.add(content);
			comps.each(model => clean(model));
			comps.trigger('resetNavigator');
		}
	}

	this.rteEnabled = 0;
	this.toggleEvents();

	this.getChildrenContainer().style.pointerEvents = 'none'; // << Disable editing of element
},
...
```
