### ISSUE TITLE
CKEDITOR is not defined

### ISSUE THREAD

**Issue by narraressan** [artf/grapesjs#165]
Hi!

I went to try the plugin for CKEDITOR and I am getting this error.

> Uncaught ReferenceError: CKEDITOR is not defined

`<div id="gjs"></div>`
`<script type="text/javascript">`
&nbsp;&nbsp;&nbsp;&nbsp;`var editor = grapesjs.init({`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`container : '#gjs',`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`plugins: ['gjs-plugin-ckeditor'],`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`pluginsOpts: {`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`"gjs-plugin-ckeditor": { `
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`options: { language: "en" } `
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`}`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`}`
&nbsp;&nbsp;&nbsp;&nbsp;`});`
`</script>`

- Am I missing something?

edit: Just read #140 and realized, I should've posted this at artf/grapesjs-plugin-ckeditor? .. my bad

**Comment by artf** [comment]
CKEditor is not included in the library

**Comment by prtjack** [comment]
hey! @artf ,
I am facing the same problem "Uncaught ReferenceError: CKEDITOR is not defined at grapesjs-plugin-ckeditor.min.js:2" . I wont get your answer in this  "CKEditor is not included in the library".
Sorry if i ask a silly one!

**Comment by artf** [comment]
@prtjack you just have to include CKEditor library inside your project

**Comment by shareefhiasat** [comment]
what a wonderfull work @artf is there a specific version ! or just try latest always , i can t find docs on this please advise thanks.

wish you best

**Comment by shareefhiasat** [comment]
**Thank its working now**

@prtjack  @artf  i got it , some text elements dose not open the dialog but if you added new one it works
exampls

This dose not work , on basic or standard, or even full
from
[https://ckeditor.com/ckeditor-4/download/#ckeditor4](url)
`<script src="//cdn.ckeditor.com/4.9.2/standard/ckeditor.js"></script>`

But this worked dont know why, but its not always working on all text elements, **especially** the one that are styled with old ( default toolbar like if you did bold in my case with old toolbar ) then added the ckeditor and tried double click nothing happens and says the following

```
Uncaught Error: [CKEDITOR.resourceManager.load] Resource name "sharedspace" was not found at "http://cdn.ckeditor.com/4.9.2/standard/plugins/sharedspace/plugin.js?t=I3I8".
    at CKEDITOR.resourceManager.<anonymous> (ckeditor.js:255)
    at e (ckeditor.js:250)
    at Array.z (ckeditor.js:250)
    at y (ckeditor.js:250)
    at HTMLScriptElement.A.CKEDITOR.env.ie.e.$.onerror (ckeditor.js:251)
```

**Comment by milapshah15** [comment]
@shareefhiasat were you able to fix this?I am getting the exact same issue

Warm regards
Milap

**Comment by shareefhiasat** [comment]
@milapshah15 

Am using newsletter-preset , here is my scripts

```
 <script src="//ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
 <script src="//feather.aviary.com/imaging/v3/editor.js"></script>

 <script src="//unpkg.com/grapesjs@0.10.7/dist/grapes.min.js"></script>
 <script src="https://cdn.jsdelivr.net/npm/grapesjs-plugin-export@0.1.5/dist/grapesjs-plugin-export.min.js"></script>
 <script src="https://cdnjs.cloudflare.com/ajax/libs/ckeditor/4.9.2/ckeditor.js"></script>
 <script src="https://cdn.jsdelivr.net/npm/grapesjs-plugin-ckeditor@0.0.9/dist/grapesjs-plugin-ckeditor.min.js"></script>
```

**The main notes to notice is** 

1. Only including the cdn version syntax from 

> //cdn.ckeditor.com/4.9.2/standard/ckeditor.js
Worked.

2. It is still not stable enought for all different operations for the ckeditor for example.
insert special character and insert table did not work with js exception.


**Finally**
About the js exception that appear for the old elements

> But this worked dont know why, but its not always working on all text elements, especially the one that are styled with old ( default toolbar like if you did bold in my case with old toolbar ) then added the ckeditor and tried double click nothing happens and says the following

```
Uncaught Error: [CKEDITOR.resourceManager.load] Resource name "sharedspace" was not found at "http://cdn.ckeditor.com/4.9.2/standard/plugins/sharedspace/plugin.js?t=I3I8".
    at CKEDITOR.resourceManager.<anonymous> (ckeditor.js:255)
    at e (ckeditor.js:250)
    at Array.z (ckeditor.js:250)
    at y (ckeditor.js:250)
    at HTMLScriptElement.A.CKEDITOR.env.ie.e.$.onerror (ckeditor.js:251)
```

I believe its not backward compatable templates , meaning either you save your template with ckeditor included as plugin and continue that way, or the default way.
otherwise you may have little in compatabilities with element or you shall delete it and re add it ( i mean like text for example readd and re edit it.

**Comment by milapshah15** [comment]
@shareefhiasat It is working if I use the exact same libraries as you have and the point you said as it is not backward compatible.

Thanks for your help.

Warm regards
Milap

**Comment by manabmrsoft** [comment]
@shareefhiasat Thank you very much
