### ISSUE TITLE
[Question] How to remove a link from text(remove a link)

### ISSUE THREAD

**Issue by SeongwoonHong** [artf/grapesjs#1650]
using built-in RTE and trying to add a rte custom button that when clicking, it removes current link.
Could you provide me with the code please?

something like this...
rte.add('custom-remove-all', {
      icon: 'remove',
      attributes: {title: 'Link', class: 'gjs-rte-action'},
      result: rte => rte.insertHTML(`${rte.selection()}`)
    });

**Comment by artf** [comment]
You can use `rte.exec('unlink')`
