### ISSUE TITLE
How create a new modal dialog like the icons one?

### ISSUE THREAD

**Issue by alu0100824810** [artf/grapesjs#1651]
Hi !
I would like create a new modal that contains templates for what users can use them later and add them to canvas/editor. I would like to do something similar to this. This is an example of https://grapedrop.com/

<img width="780" alt="captura de pantalla 2018-12-12 a las 9 09 10" src="https://user-images.githubusercontent.com/22544126/49859083-9a71e780-fdee-11e8-9c68-e9f14c0d6a11.png">

How do you do that?

**Comment by artf** [comment]
You can do it by creating new asset types https://grapesjs.com/docs/modules/Assets.html#customization
