### ISSUE TITLE
render method is repeated for a custom Component

### ISSUE THREAD

**Issue by ahmedeldeeb25** [artf/grapesjs#1657]
I have created a custom Component when I click on it to put it in the editor, the render method is repeated as long I still click on it, I want the render method to just work when i put the component in the editor

**Comment by artf** [comment]
Hi Ahmed, when you drag a component in the canvas a temporary one is created to check some functionality. If you need to skip something inside the render method you can check if it's temporary in this way
```js
render() {
	...
	if (!this.model.opt.temporary) {
		// do something...
	}
	...
}
```

**Comment by ahmedeldeeb25** [comment]
@artf thank you very much that's what i want
