### ISSUE TITLE
[Sugestion] Copy and Paste components

### ISSUE THREAD

**Issue by rgcarrasqueira** [artf/grapesjs#166]
Hi Art and Folks!

It would be nice that we can copy and paste elements from the canvas, not moving. Some persons have some difficulties to select and copy from the link above and could do this using the keyboard copy and paste functions.

This is a suggestion!

Thanks

**Comment by artf** [comment]
Actually I've already implemented copy/paste with Ctr+C/Ctr+V but there are few issues with keymaster library, seems like you can't bind keys to another window object (like the one I use for the canvas). Indeed if you select a component and click outside of the canvas, copy/paste is working

**Comment by artf** [comment]
released v0.10.2 which fixes issues with the keymaster
