### ISSUE TITLE
Content will automatically removed while edit in editor

### ISSUE THREAD

**Issue by AkibDeraiya123** [artf/grapesjs#1660]
Hello @artf 

I am facing an issue with grapes.js while editing any textual content.
I am using grapes.js Version 0.14.37 with angular 1.6.1.

While i am trying to edit some text in editor and then click at other space it will be hide/remove the content whatever i tried to edit.

Here is the screen cast video whatever i faced the issue.
https://drive.google.com/file/d/194P9L4kW1WLPTM12qS5LrtvaSg1Yk9qN/view

Please let me know if i am wrong at anywhere it's stop our future development.

**Comment by artf** [comment]
Before opening an issue be sure to have the latest version of grapesjs (0.14.37 doesn't even exist as a release...) in case the issue is still there, create a reproducible demo, thanks
