### ISSUE TITLE
How we can reinitialise editor

### ISSUE THREAD

**Issue by Deepak813** [artf/grapesjs#1662]
Hi @artf,
Hope you are doing good.

How we can reinitialise the editor with json data.
We want to reinitialise editor with some of the previous saved json data so that we can compare that.
Is there any option so that we can change the content of editor based on json data without reloading the page ? All the Undo, Redo and CSS composer and other setting should be reset after that so that it will not  affect the current  template or add in the current template after re initialisation.

I have an option
 editor.setComponents(data);
 editor.setStyle(data);

But I think it do not reset the css composer, undo redo and other changes which are done for the 
previous template.

Thanks in advance

**Comment by artf** [comment]
I think this should be enough
```js
editor.DomComponents.clear(); // Clear components
editor.CssComposer.clear();  // Clear styles
editor.UndoManager.clear(); // Clear undo history
editor.setComponents([{}, {}, ...]) // Add components
editor.setStyle([{}, {}, ...]) // Add rules
```
