### ISSUE TITLE
Newsletter preset doesn't support custom-code plugin..?

### ISSUE THREAD

**Issue by SeongwoonHong** [artf/grapesjs#1666]
Hi Artur, 

I'm wondering if newsletter preset supports custom-code plugin.
I've been using webpage preset before and custom-code plugin was working but since i moved to newsletter, custom-code plugin stopped working.. if it doesn't, how do i replicate the functionality..?
Could you provide me with piece of code example if you don't mind?

Thank you!.

**Comment by artf** [comment]
@SeongwoonHong this has nothing to do with the core of grapesjs, open this issue in the newsletter preset and provide a live example of your issue
