### ISSUE TITLE
Meteor App

### ISSUE THREAD

**Issue by emiledpretorius** [artf/grapesjs#167]
Firstly, well done on your web builder! Secondly, I'd like to know how one would go about including the builder in a Meteor app? Thanks in advance.

**Comment by artf** [comment]
I think exactly as you will do with any other js library

**Comment by kartboy16** [comment]
@emiledpretorius Were you able to import grapesjs?  I ran the imports but none of the icons are rendering.  

```
import grapesjs from "grapesjs";
import "grapesjs/dist/css/grapes.min.css";

componentDidMount() {
        let editor = grapesjs.init({
            container : '#gjs',
            components: '<div class="txt-red">Hello world!</div>',
            style: '.txt-red{color: red}',
        });
    }
```

<img width="787" alt="appsforadvisors" src="https://user-images.githubusercontent.com/4443907/28544181-43b9a4ec-7077-11e7-9dab-a44ad1e2686f.png">

**Comment by artf** [comment]
@kartboy16 I think you're importing, somewhere, jquery twice

**Comment by oransolutions** [comment]
You need the spectrum colorpicker ;)
