### ISSUE TITLE
[Question] Adding html once canvas is cleared.

### ISSUE THREAD

**Issue by SeongwoonHong** [artf/grapesjs#1671]
Hey Artur
I'd like to add some default html code when users click clear button.

for instance 1 section by default.

for clear command, i'm doing ```const comps = this.editor.DomComponents.clear();```
what should i do after this..?
Thank you

**Comment by artf** [comment]
`editor.setComponents(`<section>...</section>`)`
Use the [API Reference](https://grapesjs.com/docs/api/editor.html)
