### ISSUE TITLE
[Issue] Grapesjs not working when use with mobile devices(iphone,ipad)

### ISSUE THREAD

**Issue by sarindaSenevirathne** [artf/grapesjs#1673]
First, thank you for creating this awesome framework @artf. I integrated this framework with my project and i want it to be used through mobile devices. Basically i use this to create themes. When i use a iphone/ipad to access my website and use this, its not responding. I can edit text in buttons, placeholders of input tags through a desktop but cannot through a phone or a tablet. A help is very much appreciated. Thank you in advance.

**Comment by artf** [comment]
Hi @sarindaSenevirathne you have to use this plugin to make it work properly on mobile devices https://github.com/artf/grapesjs-touch

**Comment by sarindaSenevirathne** [comment]
Thank you @artf for your reply. I tried that but not working in our situation
![img_4267 1923](https://user-images.githubusercontent.com/32522173/50323823-91c19580-0501-11e9-8530-146ba9306563.jpg) . As shown in this figure we want the user to change an already uploaded image. But when i try from a mobile device the popup doesnt pop. Please can u point me in the right direction.
