### ISSUE TITLE
[Question] How to make 'Settings' has 'title', 'href' ,'title' manually?

### ISSUE THREAD

**Issue by SeongwoonHong** [artf/grapesjs#1675]
Hi Artur,

Usually, 'Settings' has 'Id' and 'Title'.
However, when you click any text that has become link, 'Settings' now has 'title', 'href' and 'title'.
How do i make this happen manually below...? (I'm trying to change 'Settings' the moment you click link in RTE)
 ```
editor.RichTextEditor.add('custom-link', {
          icon: '<img src="assets/images/link.png" />',
          attributes: {title: 'Link', class: 'gjs-rte-action'},
          result: rte => {
             // do something to make it happen..
            rte.insertHTML(`<a href="#">${rte.selection()}</a>`)
          }
        });
```
Thank you so much Artur

**Comment by artf** [comment]
https://grapesjs.com/docs/modules/Traits.html

**Comment by SeongwoonHong** [comment]
@artf 
Hi Artur, I've read it but what i'm trying to achieve is to open up settings that is already defined programatically.. I'm not trying to add or modify anything.. I'm not sure how the information in the link comes in play in this case.... please let me know
thank you so much

**Comment by SeongwoonHong** [comment]
@artf
I want that action happens when I click 'link' button in the built in RTE..
for webpage preset demo site, when you change text to link, you need to lose focus and re-click the text in order to see href under 'Settings'..

**Comment by artf** [comment]
You can open setting via a command `editor.runCommand('open-tm')` and to close it back `editor.stopCommand('open-tm')`

**Comment by artf** [comment]
Components inside the text component are refreshed/created only on blur, so the link component doesn't even exist when you add it... You have to add the href when you insert the HTML

**Comment by SeongwoonHong** [comment]
@artf  I really appreciate your replies..
but how do i prompt users to type href like trait manager..? except modal which I've looked into it but couldn't implement
i am so lost.. I just want to simplify the steps..
click link button and blur and re focus on the text is too much steps for users..i think..

**Comment by artf** [comment]
If you're not able to implement the link via custom modal I'd recommend then to use this plugin https://github.com/artf/grapesjs-plugin-ckeditor
