### ISSUE TITLE
How to render component in canvas using trait.  

### ISSUE THREAD

**Issue by alialrabi** [artf/grapesjs#1679]
Hi Artf ,Thanks for your great tool,I have created test case for my problem  
 https://js.do/code/271771
I have created custom tool sidebar and create trait to render component with checkbox updates.

-To reproduce 
1-drag sidebar component into canvas (it should print initial fname value in console)
2-open filter menu in classes style manager
3-check checkbox select fname
4-Then I want to render sidebar component in canvas with  fname  value
5-I would use this value as parameter to use in script after publish the page.

**Comment by artf** [comment]
In your doStuff method you're only getting the name of the trait, so nothing useful. I think if you change that checkbox trait in a simple input, you'll see the script changing correctly in the export code

**Comment by alialrabi** [comment]
Thanks for your replay, Could you please explain more what should 
i do?
