### ISSUE TITLE
Question: Edit parent & menu button styling

### ISSUE THREAD

**Issue by niagi** [artf/grapesjs#168]
So I have two questions.

1.
Is there anything built in the editor to apply edits to the parent element? For example aligning a button, I would like to add align to the button (custom menu I am building), to align the button directly instead of targeting the parent div and press align on it. Or do I need to do this manually? :)

2.
So (for the custom menu) I would like to format some buttons a bit. Instead of having a font awesome icon, I would like to apply some css and sizing to them. Any tips on this?

**Comment by artf** [comment]
1. Not built-in but you can achieve it with custom [Traits](https://github.com/artf/grapesjs/wiki/Traits)
2. You can style buttons as you like with CSS, if you want to get rid off font awesome you can use [Panel API](https://github.com/artf/grapesjs/wiki/API-Panels)
