### ISSUE TITLE
Missing Attributes

### ISSUE THREAD

**Issue by froderf** [artf/grapesjs#1680]
When I drag a block into the canvas, some attributes of that block is missing

```
blocks: [
                  {
                    label: 'Container',
                    content: '<div data-gjs-test="true" class="container"></div>',

                  },//end of container
]
```

from the above example the "data-gjs-test" was removed after dragging the block into the canvas.
I want it to remain .
Thank you

**Comment by artf** [comment]
Those attributes were made to be removed, if you need them, probably you're doing something wrong...
