### ISSUE TITLE
Remove cookies on GrapesJS?

### ISSUE THREAD

**Issue by CaloBM** [artf/grapesjs#1682]
Hello! I'm using the latest version of GrapesJS, however it is causing issues with my project, because GrapesJS is saving the edits as a cookie, so that if I come back, the design I had before is still there. The way my project works is that you have to select a template from a list, but it wont work because of the cookies. Is there any way to disable this on GrapesJS?

Many thanks, Calo.

**Comment by artf** [comment]
> because GrapesJS is saving the edits as a cookie

[localStorage](https://developer.mozilla.org/it/docs/Web/API/Window/localStorage), not cookies...

Read the documentation please https://grapesjs.com/docs/modules/Storage.html

**Comment by CaloBM** [comment]
Thank you!
