### ISSUE TITLE
Can i use react to develop components?

### ISSUE THREAD

**Issue by B-Esmaili** [artf/grapesjs#1684]
Hey guys.really impressed with the great job done.I have a question regarding component development. the question is can i use react to develop plugins?if yes is there any doc or guideline related?

**Comment by artf** [comment]
Hi @B-Esmaili GrapesJS is framework-agnostic so you just need to use its API to define new components. Here some doc where you can get started:
* [Create plugins](https://grapesjs.com/docs/modules/Plugins.html)
* [Create custom Components](https://grapesjs.com/docs/modules/Components.html)
