### ISSUE TITLE
How to send values to Editor from outside.

### ISSUE THREAD

**Issue by GabrielWillebaldTorch** [artf/grapesjs#1685]
hi there, 
few days ago I started to research about sending some values from an Angular modal (which is invoked at the front of the grapes editor) to the Editor itself, in this case I want to send some images from my custom Angular AssetManager, to the editor, in order to use those images for building the website. Is there any way to accomplish this? Some suggestions?

**Comment by artf** [comment]
You can manage GrapesJS assets via [Asset Manager](https://grapesjs.com/docs/modules/Assets.html) or if you want you can even replace the built-in one (find more about this here #491)
