### ISSUE TITLE
Broken Link in doc  https://grapesjs.com/docs/modules/Components-&-JS

### ISSUE THREAD

**Issue by ramachandranvenkat** [artf/grapesjs#1689]
https://grapesjs.com/docs/modules/Components-&-JS
page not found

**Comment by artf** [comment]
@ramachandranvenkat where did you get that link?
The correct one is https://grapesjs.com/docs/modules/Components-js.html

**Comment by adamlc** [comment]
The link is in the Components & JS section for the Component Manager - https://grapesjs.com/docs/modules/Components.html#components-js
