### ISSUE TITLE
Question : How to get the icon desktop and icon mobile 

### ISSUE THREAD

**Issue by blackbirdzzz** [artf/grapesjs#169]
Please how to change the device selection for "Desktop / mobile" to some icon my mjml version of grapejs i don't understand why i don't get the same version of with info buble hover.. effect css hover (orange) , i had to add my own css modified to get hover but i had do "npm install" , "npm start & npm run build"

**Comment by artf** [comment]
For the demo I've used this preset (just add it as another plugin)
https://github.com/artf/grapesjs/blob/gh-pages/js/grapesjs-preset-mjml.js
