### ISSUE TITLE
Flexbox icons missing in the distribution, but demonstrated in the grapesjs.com demo page.

### ISSUE THREAD

**Issue by charlietoleary** [artf/grapesjs#1690]
Hi,

It appears that the icons / images for the flexbox properties are missing (row, column, etc).

These icons are present on the [demo page of grapesJS](https://github.com/artf/grapesjs-blocks-flexbox): although it appears that these are hosted directly within the demo, rather than grapesJS itself.

This issue might have more of a home in the [grapesjs-blocks-flexbox repository](https://github.com/artf/grapesjs-blocks-flexbox), but as it is present in the main demo i thought it might be more relevant here.

Thanks,

**Comment by artf** [comment]
I've just made use of them for the demo page, you copy the code from here: https://github.com/artf/grapesjs/blob/gh-pages/demo.html
