### ISSUE TITLE
How to use variable/function outside of the script

### ISSUE THREAD

**Issue by AkibDeraiya123** [artf/grapesjs#1691]
Hello @artf ,
How can i access the variable as well functions which is outside of the script.

My code is like,
```
var temp = {};

function fnName() {
    // Here is some script execution and will do it on global variables
}

bm.add("image-cropper",
    {
        label: '<div class="gjs-block-label">Image Cropper</div>',
        tab: "2",
        content: {
            script: function () {
                // But here i am getting temp is undefinded.
                if (Object.keys(temp).length === 0) {
                    temp = {};
                }
                
                temp = {
                    a: "abcd",
                    b: "xyz"
                }
                // Here is the further code and using temp.
                // As well i also need to use `fnName()` function in some cases.
            },
            content: '<div><h1>Hello</h1><img id="staticId" onclick="jsFunc(staticId)" src="imagePath" /><div>'
        }
    }
)
```
I am using angular.js(Angular1). And the above code is for the controller file.
Can you please assist me how can i use this global variable as well function in my script?

**Comment by artf** [comment]
You can't, they're not in the same context, read carefully this page https://grapesjs.com/docs/modules/Components-js.html
You need to copy your global variables inside the `script` property or you can [inject them in the canvas as a dependecy](https://grapesjs.com/docs/modules/Components-js.html#dependencies)
