### ISSUE TITLE
Predefined non-changeable content blocks

### ISSUE THREAD

**Issue by Yamakasi** [artf/grapesjs#1692]
Is it possible to create predefined content blocks with data you put in from your backend and which the user cannot change and only place or move in it's "webpage" ?

I'm trying to find a way to have a user creating pages based on content that is made available by what I provide him and be able to use.

**Comment by arthuralmeidap** [comment]
Yes, it is.  

I can see, at least, one way to achieve this. You could create a new non-editable component and use it to create your own custom blocks.

PS: I don't remember if you can add non-editable blocks. If it's possible to do that, you don't need to create a new component. Just add non-editable custom blocks with your content

Here you can see how to create components: https://github.com/artf/grapesjs/wiki/Components

Here you can see how to add blocks: https://github.com/artf/grapesjs/wiki/Blocks

**Comment by artf** [comment]
@arthuralmeidap correct, @Yamakasi you can set `editable` as `false` on any text [Component](https://grapesjs.com/docs/api/component.html). BTW that wiki is outdated, you can find all the documentation here: 
* https://grapesjs.com/docs
* Component: https://grapesjs.com/docs/modules/Components.html
* Blocks: https://grapesjs.com/docs/modules/Blocks.html

**Comment by Yamakasi** [comment]
Hi Guys! Sorry for the late response! I can work with that, clearly, thanks! Have a good 2019!
