### ISSUE TITLE
CSS composer not working on two classes

### ISSUE THREAD

**Issue by froderf** [artf/grapesjs#1694]
```
//returnedCssObject is an object that contains css styles
cssComposer.setClassRule("class1 class2", returnedCssObject);
```

above code is not working
but the below is working

```
//returnedCssObject is an object that contains css styles
cssComposer.setClassRule("class1", returnedCssObject);
```

All i need is to apply the css rule in two class
.class1 .class2{
...
color: red;
...
}

**Comment by mailtopaul8** [comment]
I need to have a new CSS rule with the combination of both ID & class but currently there is no way to do that (tried using `setIdRule` by adding ` .class` after ID but didn't worked). Can you add a method like `setRule` which would simply accepts a whole selector with ID & class combination?

**Comment by artf** [comment]
@mailtopaul8 I'll try to bring it in the next release

**Comment by mailtopaul8** [comment]
Okay thank you very much :)
