### ISSUE TITLE
Adding new trait to Video component

### ISSUE THREAD

**Issue by ahmedeldeeb25** [artf/grapesjs#1695]
![screenshot from 2018-12-30 14-14-25](https://user-images.githubusercontent.com/14032350/50547162-49128680-0c3d-11e9-9b9e-b85351ed4d22.png)

 
I want to add a new trait for existing VIDEO '' component. I follow the docs and I didn't find what I want.

Now I got the new trait added to the VIDEO component, but the existing traits are gone, I need some help, Thank you so much

Here is what I've tried so far:
https://js.do/code/273166

**Comment by artf** [comment]
Extend the [`video` type](https://github.com/artf/grapesjs/blob/dev/src/dom_components/model/ComponentVideo.js) not the `default` one and be careful with your `isComponent` method, you're returning `return {type: 'input'};`

**Comment by ahmedeldeeb25** [comment]
@artf  I do the same thing as you mentioned with MAP and LINK components and it worked, but it didn't work with VIDEO component

**Comment by artf** [comment]
@ahmedeldeeb25 please refer to the source of the [video component](https://github.com/artf/grapesjs/blob/dev/src/dom_components/model/ComponentVideo.js). There, traits are created differently (look at the initialize method).

ps: work always with an update version of grapesjs, your is outdated

**Comment by kienduongbk** [comment]
@ahmedeldeeb25 
that is my solution.
https://js.do/code/274435
