### ISSUE TITLE
 Traits appear first time when draged custom component

### ISSUE THREAD

**Issue by muhamdgomaa28** [artf/grapesjs#1696]
Hi artf , i have created custom component and add traits for it , when dragging this component to editor and select it the setting  traits work correctly .
the proplem is when draged the same component behind the old component  to editor and select setting traits the default traits will appear ( id , title)  only , this is code that i implemented
for create component : 

        this.editor.BlockManager.add('customtext',{
            id: 'texttool',
            label: 'Text Tool',
            content:{
                components: [
                    {
                        tagName: 'texttool',
                        type:'texttool',
                        editable:true,
                        content:'// some html  '
    },
        ]
       },}

for adding traits for this comonent:

        this.domComps.addType('texttool', {
            model: dModel.extend({
            init(){
           this.listenTo(this, 'change:type', this.doStuff);
             },
            doStuff(){
               // do some tasks
               },
           defaults: Object.assign({}, dModel.prototype.defaults, {
                    traits: [
                        {
                            type: 'select',
                            label: 'data objects',
                            name: 'type',
                            options: this.contentobjectlist,
                            changeProp:1,
                        },
                    ],
                }),
            }, {
                isComponent: function(el) {
                    if(el.tagName == 'texttool'){
                        return {type: 'texttool'};
                    }
                },
            }),
           view: dView,
        });

**Comment by artf** [comment]
Please create a live demo of this issue

**Comment by ahmedeldeeb25** [comment]
Hi @artf I have the same issue as him exactly, when I drag the component for the first time traits are working fine, but when I'm in edit mode traits didn't work
this is an example for my code: https://js.do/code/274228
