### ISSUE TITLE
how to Set multiple options to data-gjs-droppable

### ISSUE THREAD

**Issue by momu-2016** [artf/grapesjs#1698]
as i know , ican set data-gjs-droppable=".row-cell" ,but how can i Set multiple options

**Comment by v8jupiter** [comment]
Hi. You can use a query string as with `draggable`.

**Comment by momu-2016** [comment]
> Hi. You can use a query string as with `draggable`.

thank you ，but I'm a novice. Can you give me an example?

**Comment by artf** [comment]
@momu-2016 `data-gjs-droppable=".class1, .class2, .class3"`
