### ISSUE TITLE
[BUG] Link elements are not copyable/deletable

### ISSUE THREAD

**Issue by narendravaghela** [artf/grapesjs#1699]
In the editor, if we have link element with some classes, the editor does not allow to copy/delete the element.

GrapesJS version: v0.14.50

#### Steps to reproduce:
1. Open https://grapesjs.com/demo.html
2. Import following simple link tag
```html
<a href="#" class="btn btn-lg d-block d-lg-inline-block">Get Started</a>
```
3. Select it and click on copy icon or delete icon from the toolbar

@artf Could you please suggest on this? We are running a live application and it's bit important to make links editable.

**Comment by artf** [comment]
For now, init the editor with this option:
```js
grapesjs.init({
	...
	canvas: {
		...
		notTextable: ['button', 'a', 'input[type=checkbox]', 'input[type=radio]'],
	}
})
```
in the next release I'll adjust the default value

**Comment by narendravaghela** [comment]
It is working now. Thank you @artf
