### ISSUE TITLE
How to render React components in grapesjs

### ISSUE THREAD

**Issue by tyua07** [artf/grapesjs#170]
I saw the grapesjs-mjml project, but did not solve my problem.

**Comment by artf** [comment]
Honestly, checking the grapesjs-mjml plugin is the best advice I can give you at the moment (especially [components](https://github.com/artf/grapesjs-mjml/blob/master/src/components.js)) as basically, it's the same concept. Technically, you have to create custom [Components](https://github.com/artf/grapesjs/wiki/Components) with a custom render logic.

**Comment by Chronis77** [comment]
Hi Art, would it be possible to get a bit of custom development done? I am not sure how to get hold of you, but would be happy to pay for a custom piece of work. Even if it's just a single element to give me insight.

**Comment by tyua07** [comment]
thank you @artf

**Comment by aditya-dikonia** [comment]
@tyua07 Can you please explain here how you grapesjs component with reactjs?

**Comment by beepsoft** [comment]
Hi,

I have a small example project solving this:

https://github.com/beepsoft/grapesjs-react-component-example

**Comment by alatella87** [comment]
Hi @beepsoft, thanks a bunch. I have forked your project and indeed the Timer (as a React) component renders inside GrapesJS canvas. Would you be able to list the steps needed to correctly implement a new React component in its simplest form? I understand you used a Timer component for its complexity as to capture most cases, would it be also possible to list the steps for a boilerplate?
