### ISSUE TITLE
Grapesjs-react

### ISSUE THREAD

**Issue by hemanthmc** [artf/grapesjs#1700]
**how to load an html file while starting the GrapesJs-react- editor**

I tried in this way but it is not working,

editor.StorageManager.add('local', {
      load() {
        'template.html'
      },
    });

**Comment by arthuralmeidap** [comment]
You could use the `editor.setComponents` to load the HTML. Here you can see an example: https://github.com/artf/grapesjs/wiki/API-Editor#setcomponents

You will need to get the content from the HTML file first.

**Comment by artf** [comment]
To be honest @hemanthmc , by lookings this:
```js
load() {
'template.html'
},
```
I'm not sure you even know what you're doing...

Start from the beginning:
https://grapesjs.com/docs/getting-started.html
