### ISSUE TITLE
Provide a way to filter toolbox items AKA(blocks).

### ISSUE THREAD

**Issue by B-Esmaili** [artf/grapesjs#1701]
with minimal set of blocks involved it doesn't make much sense to have a toolbox filter, but as the number of toolbox items grow it makes a lot of sense to have a filter on top of toolbox. other thing annoying  me is lack of auto-scroll when  dragging elements up or down on the canvas.i would appreciate any commitment addressing these issues.thanks for good job done between👍 .

**Comment by artf** [comment]
Hi @B-Esmaili for the filter you can create your UI (panel, input for the search, etc.) and use the block's API to filter them (example https://github.com/artf/grapesjs/issues/499#issuecomment-343482511)

> other thing annoying me is lack of auto-scroll when dragging elements up or down on the canvas

The auto-scroll should work instead (try to get closer to the canvas edge)
