### ISSUE TITLE
[QUESTION] Is it possible to affect child component's styling through parent component's style manager?

### ISSUE THREAD

**Issue by cmoutafidis** [artf/grapesjs#1709]
Hello there!

Awesome project and thanks for your contribution.
I would like to know if it is possible to change the styling of a child component through it's parent's style manager.

For example, I have a block of components. The parent component contains all the other components. By clicking the parent component and going to style manager, I want to be able to change the style of the child components, either by its style properties or custom traits.

Thanks in advance.

**Comment by artf** [comment]
It might be a bit tricky but yeah, you can do it.
For sure you have to create a custom [Component](https://grapesjs.com/docs/modules/Components.html) and inside its init method (model) you would place listeners to traits/styles. Then, inside the callback method, of the listener, you'd use [`find`](https://grapesjs.com/docs/api/component.html#find) method to detect child components
