### ISSUE TITLE
Trigger event on editor load

### ISSUE THREAD

**Issue by DaveOrDead** [artf/grapesjs#171]
It would be great if there was a way to trigger an event when the editor has loaded.  I tried 
```
var editor = grapesjs.init({
	container : '#gjs',
	on: {
		event: 'load',
		callback: myFunc
	}
});
```
but had no joy.  Am I missing something or is this feature not available?

Great project btw :)

**Comment by niagi** [comment]
editor.on('load',
            function() {
                alert("loaded"); // or call another funcion here
            });

**Comment by artf** [comment]
Correct, but you have to disable autorender first to make it work
```js
var editor = grapesjs.init({
 autorender: false,
 ...
});

editor.on('load', function(){ ... });
editor.render();
```

**Comment by DaveOrDead** [comment]
Cheers, thanks guys - I'd just figured out the autorender disabling this second :)

**Comment by niagi** [comment]
Oh yeah, didn't think of that one. Already had that set :)
