### ISSUE TITLE
Error in prompt position after moving canvas

### ISSUE THREAD

**Issue by fulus06** [artf/grapesjs#1711]
1、移动画布
2、点击layerManager（如果不点击layerManager 不会出错）
3、画布里的提示框位置出错

1、 moving canvas
2、 click layerManager （If you don't click layerManager, it won't go wrong.）
3、 The position of the tip box of the picture is wrong.
![grapesjs-issues](https://user-images.githubusercontent.com/12890684/50725484-1f73c680-1139-11e9-9fec-ebcc79afb559.gif)

**Comment by artf** [comment]
Thanks for the report @fulus06 can you provide a reproducible demo on https://jsfiddle.net/, please?

**Comment by fulus06** [comment]
@artf  https://jsfiddle.net/fulus06/kqsezd0c/5/

![grapesjs-issues](https://user-images.githubusercontent.com/12890684/50779258-d3608780-12da-11e9-8a46-b9664d18094c.gif)
