### ISSUE TITLE
Header and footer

### ISSUE THREAD

**Issue by froderf** [artf/grapesjs#1712]
I'm thinking about adding multiple page with header and footer

Currently I have an idea on how to implement the multiple page but I don't know how to implement header and footer.

With the current Api methods, seems there is no work around for this

please help to resolve this issue, since upon checking the issue there is no issue regarding this one yet

**Comment by froderf** [comment]
Header and footer should be same to all pages

**Comment by artf** [comment]
You have to use [Custom Components](https://grapesjs.com/docs/modules/Components.html)

example https://jsfiddle.net/5vcc3en6/
