### ISSUE TITLE
Hello, I am new to your project, but I love it. I have a small issue with image attributes.

### ISSUE THREAD

**Issue by JulioDavidMartinez** [artf/grapesjs#1715]
I added two new traits to the trait manager for images. Width and height.
I added it as a plugin following your example.
It totally works and lets me edit the image attributes for width and height.
The problem is that now the asset manager doesn't work any more. If I disable my changes then the asset manager works again. Is there any way that I can have both working?
My new traits and the asset manager for images?

Here is my code for adding the new traits.
To activate it I just call the function name as a plugin.
Did I do something wrong maybe? Please help!!!!

```js
function AddImageTraits(editor) {
	var domComps = editor.DomComponents;
	var dType = domComps.getType('default');
	var dModel = dType.model;
	var dView = dType.view;
	domComps.addType('image', {
		model: dModel.extend({
			defaults: Object.assign({}, dModel.prototype.defaults, {
				traits: [
					// strings are automatically converted to text types
					'name',
					'id',
					'alt',
					'width',
					'height'
				]
			}),
		}, {
			isComponent: function (el) {
				if (el.tagName == 'IMG') {
					return {
						type: 'image'
					};
				}
			},
		}),
		view: dView,
	});
```

**Comment by arthuralmeidap** [comment]
Try to override from the `image` type itself instead of `default` type
