### ISSUE TITLE
Block in Pannels?

### ISSUE THREAD

**Issue by chiqui3d** [artf/grapesjs#1716]
I'm looking for a way to add a group of blocks to a custom panel, I'm talking about blocks and not buttons because they need to be "Drag and Drop"?
What possibilities do I have?

**Comment by artf** [comment]
Hi @chiqui3d you can tell the editor when to append blocks at initialization:
```js
grapesjs.init({
	...
	blockManager: {
		appendTo: '#block-container',
	}
})
```
and then using the [`BlockManager.render`](https://grapesjs.com/docs/api/block_manager.html#render) method (check the example) to render filtered blocks

**Comment by artf** [comment]
yeah, correct, render method re-renders on the same container. I'll try to find a solution for the next release

**Comment by chiqui3d** [comment]
Hey @artf ,

works correctly, but only one problem, when I have two panels, one with external option, the category is added in the two panels. is there any possibility of fixing this?
 I have tried find the category by class in the generated html, but does not create any class i.e. category-basic to identify it through the container.

Currently the class that generates the block of categories is as follows:

`<div class="gjs-block-category gjs-open"></div>`

but it should be something like this, if the category where the block name is added like 'Basic';

`<div class="gjs-block-category category-basic gjs-open"></div>`

So through the panel container I can remove the category, although I think there has to be some better way to avoid duplication, but equally it will be a good idea to add the category name to the class.

Thank you for everything.

**Comment by artf** [comment]
You can pass `ignoreCategories` option to avoid rendering categories
