### ISSUE TITLE
Event while click on image from asset modal

### ISSUE THREAD

**Issue by AkibDeraiya123** [artf/grapesjs#1719]
Hello @artf ,
Hope you are doing well.

I am working on asset-manager. I have total 5 images as a default asset-manager image.

I want to do like,

1) When user click on any default image from template then i want to change this image's id **(Want to know about this how can i change)**
2) Then once asset manager pop-up opens and user can select any image and then that clicked image will be change with target image(This is working fine).
3) When this asset manager will close then also need to get event that notify like modal is closed and on which image tag i had clicked. **(Want to know about this event.)**

i had tried with this event for change id, but not worked
```
editor.on("run:open-assets", function () {
  // Here i can get the target
  editor.getSelected().set('id', 'custom-image')
})
```

**Comment by artf** [comment]
> i had tried with this event for change id, but not worked

You should use [`setId`](https://grapesjs.com/docs/api/component.html#setid) method

> When this asset manager will close then also need to get event that notify like modal is closed and on which image tag i had clicked. (Want to know about this event.)

You can make use of `stop:open-assets` event
