### ISSUE TITLE
How can I add a background image and a class to body inside the iframe

### ISSUE THREAD

**Issue by pournami17** [artf/grapesjs#172]

**Comment by artf** [comment]
Good question @pournami17, actually, at the moment, it's not so easy, you have to create a gap between inner sections to select it. I'm not exposing the wrapper/body inside layers and not even taking in consideration that the wrapper will be the `<body>`. Will work on this

**Comment by rgcarrasqueira** [comment]
I have cheated on this way:

```
var iframe = $('iframe.gjs-frame');

iframe.contents().find("head").append($('<link href="//netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css" rel="stylesheet">'));
            iframe.contents().find("head").append($('<link rel="stylesheet" href="{% static "mailerweb/css/emailtemplate_iframe.css" %}">'));
            $('#wrapper', iframe.contents()).css('padding-bottom','100px');
            
```

For me solved my problem.

**Comment by artf** [comment]
From the [v0.9.32](https://github.com/artf/grapesjs/releases/tag/v0.9.32) is now possible to select the body/wrapper from layers
