### ISSUE TITLE
[QUESTION] Resize image before adding it as base64

### ISSUE THREAD

**Issue by ThunderDev1** [artf/grapesjs#1721]
I'm currently adding images to the canvas as base64 (embedAsBase64: true).
I don't want to upload the image for the moment, to keep things simple. But, I want to be able to resize or crop the image before adding it through the asset manager as base64, to avoid oversized images added by the user.

Basically I would need an event before the image is added, so I can transform the image, but for now we only have access to asset:add event. Any ideas if this would be possible ?

Thanks

**Comment by artf** [comment]
Well, obviously you can't resize and crop without having all the image data at first. So, on `asset:add` event propose your "crop and resize" solution and then update the asset with the new data
