### ISSUE TITLE
Block customizing. 

### ISSUE THREAD

**Issue by Chronis77** [artf/grapesjs#173]
Hi, 

I was to create custom blocks and only make the outer dom highlightable/selectable. I tried it with the following code, but it didn't work, any insight would be appreciated. 

```
bm.add('mj-1-column', {
    label: '1 Column',
    content: `<mj-section>
        <mj-column data-gjs-highlightable="0"><mj-text data-gjs-highlightable="0">Content 1</mj-text></mj-column>
      </mj-section>`,
    attributes: {
      class: 'gjs-fonts gjs-f-b1',
      // Workaround
      'data-type': 'mj-section',
    },
  });
```

The other thing i would like to do is bind an action on clicking the outer dom. I would like the settings to be customized, and i would like to open an editor in the right panel for the text. 

Please could you point me in the right direction on how to do this!

**Comment by artf** [comment]
Hi @Chronis77 for such customization you have to use custom [Components](https://github.com/artf/grapesjs/wiki/Components) (eg. you bind events in the View of the component)

**Comment by Chronis77** [comment]
Hi Art, would it be possible to get you to do a bit of custom development for us. We would obviously pay...

Please let me know if there is a way to contact you outside of git. 

Thanks,
Spiro

**Comment by artf** [comment]
@Chronis77 artur.catch at hotmail.it
