### ISSUE TITLE
[QUESTION] What is the best way to manage dynamic components?

### ISSUE THREAD

**Issue by abozhinov** [artf/grapesjs#1731]
Hi,
can you please tell me what is the best way to manage dynamic templates.
I want to describe you what's my case.

1. Have e-commerce store and use GrapesJS.
2. We have PAGES and in this pages want to add product collections or collection with brands (logo). 
3. I want to create few components like product collection, brand collection, blog posts and ect.
4. I don't want user to write PHP code because can make REALLY big mess. I use SAMRTY as a template engine.

Let's check the following example:
1. Create a product collections - collection 1, collection 2 and collection 3.
2. Create new page and drag component "product collection".
3. In this component I choose from already added collections.
4. Between this components I add text, images, links ect.
5. Save the page and preview it. 
6. On the place of components "products collections" I want to see all the products that I add from the CMS.

Regards,
Alex

**Comment by artf** [comment]
You can make use of a custom component and variables to replace on server-side.
Take a look at the example I made for you:
https://jsfiddle.net/fcsa6z75/7/

**Comment by abozhinov** [comment]
Can you give me advice how to make mapping with dynamic data. Something like Webflow. They have product collection and you can edit template select TEXT component and choose this is ProductName.  Their editor looks like GrapesJS. My concerns are how to preview products in editor and how to store the template.
