### ISSUE TITLE
Vuejs components builder

### ISSUE THREAD

**Issue by bajki** [artf/grapesjs#1735]
Hi, it would be nice to have vue components builder like mjml..
This user started project:
https://github.com/Patrick-Spiegel/vue-grapesjs

But how create component like VBtn in this project, but to accept drop element..

So like VContainer and you can drop VBtn inside. 

Thanks,
Ivan

**Comment by artf** [comment]
This is very close to how I made the mjml editor, he created a custom component with its own renderer
https://github.com/Patrick-Spiegel/vue-grapesjs/blob/master/src/components/grapes-components/v-btn/index.js
Unfortunately, it's a not generic renderer but only for that VBtn component, which means you have to create the new file for each component.

**Comment by bajki** [comment]
But how push new component to rendered Vue..

This would be great stuff for vue if can be managed.
