### ISSUE TITLE
[Bug] Table cell(td, th) resize error

### ISSUE THREAD

**Issue by cnaa97** [artf/grapesjs#1738]
Hello. I'm working on Table feature with this awesome project grapesjs. 

## Problem

1. I added table component on canvas. 
2. In `ComponentTableBody.js`, change default rows and columns options.
2. In ComponentTableCell.js, add a `resizable` options on cell component.
4. then In order to make resizing cell feature, but It doesn't work. 

![2019-01-22 14-06-46 2019-01-22 14_09_43](https://user-images.githubusercontent.com/7259107/51516025-2c8ef600-1e59-11e9-911b-a6ed6d1e268b.gif)

## Description of problem

Then when I handle resizing cell, then It looks update css class, but didn't updated on view.
Because of the default css class of cell component has only one class named 'cell'. 

For the other hand, In order to change table column resize, colgroup and col is standard in HTML. 
and grapesjs looks to need a colgroup and col component.

## My suggestion

1. Add a indexed css class for each cell by default.
2. Add a new components, `colgroup` and `col` element.
3. In SelectComponent, add a conditional statements for resizing cell.

![2019-01-22 14-10-55 2019-01-22 14_12_44](https://user-images.githubusercontent.com/7259107/51516032-30bb1380-1e59-11e9-93d6-20968e345f4f.gif)

---

If you don't mind, I want to contribute with Pull Request.

**Comment by artf** [comment]
The real problem here is the class actually, so I'm ok with removing them from the core (they are actually useless here), but I'd avoid other table-related components.
