### ISSUE TITLE
How to load dynamic CSS style(Not Link) into the Canvas head

### ISSUE THREAD

**Issue by Soharab-Shaikh** [artf/grapesjs#1739]
Hi,
First of all thanks for your great Work !!!!!

I am trying to load a dynamic style into the canvas head. Is there any way to load dynamic object or string into the canvas head.

var **customeCss** = "h1 { color:#000000; font-family:Courier; font-style:italic;; }"
var editor = grapesjs.init({
............................................................
 canvas: {
            scripts: [ "https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"],
            styles: [**customeCss**]       **//Is there any way to do so.**
        }
............................................................
}); 
I need your help.
Thanks,

**Comment by artf** [comment]
Do this
```js
const head = editor.Canvas.getDocument().head;
head.insertAdjacentHTML('beforeend', `<style>YOUR CSS</style>`)
```
