### ISSUE TITLE
Execute command on drop

### ISSUE THREAD

**Issue by tribulant** [artf/grapesjs#174]
This is not an issue, I just need some help or information, please.

I created a custom block using `editor.BlockManager.add()`

How can I execute a command to run some Javascript to take user input in a prompt or something to modify the content of the model before it is inserted into the canvas after the drop?

I started with some code like this:

`editor.on('block:drag:stop', function(model) {});`

Or should I rather create a custom domcomponent somewhere?

Any help would be appreciated!

**Comment by artf** [comment]
Correct, you can use `editor.on('block:drag:stop', function(model) {});` or if you want something more component specific you can create a custom Component and make use of `activeOnRender` property
```js
editor.DomComponents.addType('custom-type', {
  model: {...},
  view: defaultView.extend({
     init() {
       this.listenTo(this.model, 'active', this.doStuff); // listen for active event
     },
     doStuff() {...}
  }),
});


blockManager.add('test-block', {
 label: 'Label',
 content: {
    type: 'custom-type',
    activeOnRender: 1, // <- this will trigger the active event
 },
});
```

**Comment by tribulant** [comment]
@artf 

Thank you so much, you rock!

**Comment by Brandonwaichunyu** [comment]
hi @artf 

is there a specific code to help change to Component Settings, im using blockManager as well just for the Video.

**Comment by Brandonwaichunyu** [comment]
@artf
