### ISSUE TITLE
[FEATURE REQUEST] Don't Strip off  html , head and body tags from imported html

### ISSUE THREAD

**Issue by sankaran85** [artf/grapesjs#1746]
Hi Team,

  We have noticed grapesjs has customised the actual template uploaded, by stripping off the html, head and body tags and adds new style tag in the content, Which we don't want to happen.

Is it possible for grapesjs editor to output html without altering the basic structure of the imported template. We looked for some options but couldn't find any.

Please help us in achieving this. Thanks

**Comment by artf** [comment]
Dupliate of #1745
