### ISSUE TITLE
How to prevent drag items inside the editor

### ISSUE THREAD

**Issue by AkibDeraiya123** [artf/grapesjs#1748]
Hello @artf 
You are doing great job with grapesjs and it's extremely helpful to make our functionality more user friendly.
Thanks for creating such a amazing open source lib.

I want to know that suppose i want to prevent drag of all html content like div, ul, li, etc then how can i?
I guess i just need to add some configuration when i initialise `grapesjs.init({ .... })`.

Actually i am providing default html content as a default template and on that default template/layout user can edit and launch his own website.
So, i have one page in my template and i want to prevent like user can't change layout but user can add new component.

I also tried with `nativeDnD` option but looks like not working for me.

Can you please help me for how can i fix this functionality?

**Comment by artf** [comment]
Start from reading this: https://grapesjs.com/docs/modules/Components.html
then check all the available properties on Components: https://grapesjs.com/docs/api/component.html

**Comment by AkibDeraiya123** [comment]
Hello @artf 
I have one div which class is like `testing` and i want to restrict the child items of this div with class `testing` then how can i do this?

Can anyone guys help me to figure it out?
Thanks in advance.
