### ISSUE TITLE
[Bug]: conditional comments getting removed on latest version

### ISSUE THREAD

**Issue by aaronseanph** [artf/grapesjs#1749]
@artf comment in #208 this is working in older versions but not in 0.14.50. Is there any work around available? I've tried adding it in plugins as per #1254  but no luck. Thanks!

**Comment by artf** [comment]
It works for me with the latest version https://jsfiddle.net/06L5ng19
Next time, create a reproducible demo before opening a BUG issue, thanks...

**Comment by aaronseanph** [comment]
Hi @artf , thanks for your time. The issue is happening when adding comments to blocks html. I've updated your code and added some test block with comments inside it: https://jsfiddle.net/orn4jqw7/1/

**Comment by artf** [comment]
I keep seeing it correctly...

**Comment by artf** [comment]
ok now I get it... you were talking about the comments in the canvas... Well, to be honest, I don't think you need to care about what you see in the canvas (the important part indeed is in `toHTML` of the comment component).In any case, you can always try to tweak the `view` to obtain what you need
