### ISSUE TITLE
[Question] Show drawing outlines only under actively editing blocks

### ISSUE THREAD

**Issue by stychos** [artf/grapesjs#1750]
Is it possible to show show drawing outlines only for the currently selected (with all children) and for the hovered elements? Thus all other page elements would be rendered as a final result.

**Comment by artf** [comment]
Each [component](https://grapesjs.com/docs/api/component.html) has the `highlightable` property, that you can disable on all types (by extending them) and change it on component select change (by listening to `component:selected` event)
