### ISSUE TITLE
Remote storagemanager not working

### ISSUE THREAD

**Issue by madcowtuning** [artf/grapesjs#1757]
Hello,

For 2 days I am fighting with the storageManager. I couldn't load template from remote file.  Finaly I discovered that it is working only when I load grapesjs from https://unpkg.com/grapesjs. If I triy to load grapesjs from any min.js or dev dist files remote template load is not working. It is also working with the grapes.min.js file from dev dist folder but only if I rename the file to grapes.js. If I try to load it as grapes.min.js it is not working.

**Comment by madcowtuning** [comment]
Now I notice that the store is not working when load is working. If I load grapes.js from dist folder store is working but the load is not working.

**Comment by madcowtuning** [comment]
Load is working when contentTypeJson: true. In some distributions it is true in some it is false.

**Comment by madcowtuning** [comment]
I am using dev package. Load is working when including grapes.js from dist forlder and change contentTypeJson to true but store is not working. When I include grapes.min.js from dist forlder (instead of grapes.js) then load is not working but store is working.

**Comment by madcowtuning** [comment]
When store is not working the problem is that fetch is sending empty "data".

**Comment by madcowtuning** [comment]
Solved! First problem was that I didn't cleared my browser cookies. The second was that I didn't put "/" after urlStore link.

**Comment by madcowtuning** [comment]
I figured out what is going on. If you set contentTypeJson "true" the load is working but the store is not because it is trying to send json data as POST data and it is not working. If you set contentTypeJson  "false" load is not working because it is in json format but then store is working.  I can't get out of this situation so I added a different function for storing data.

**Comment by artf** [comment]
> server didn't parse it

The server should take the POST content from the **body** of the HTTP request

**Comment by madcowtuning** [comment]
I fixed it by modifying this row:
var res = parsable ? JSON.parse(text) : text;

If I set contentTypeJson to false it couldn't load template because it is
JSON type but can store the data.
If I set contentTypeJson to true then it  reads the template but then send
POST data as json, php didn't parse it and I receive an empty POST.
So I set it to false and modified the upper row so It always parse the
template as JSON.

**Comment by artf** [comment]
> php didn't parse it and I receive an empty POST

Again @madcowtuning... the JSON is in the **body**

https://stackoverflow.com/questions/7047870/issue-reading-http-request-body-from-a-json-post-in-php

**Comment by madcowtuning** [comment]
I tried this. The php input file was empty.The explanation in your tutorial
was different.Anyway. I think it is better you to modify your script to
receive json data and send pure POST data as is described in the tutorial.
Nevertheless I love the script. You did a great job. Thank you.I was using
webflow before but it is too expensive.
