### ISSUE TITLE
Unable to load in CSS string with characters such as '#' with setStyle()

### ISSUE THREAD

**Issue by tjb295** [artf/grapesjs#1758]
## You're submitting a BUG
  1. Are you using the latest release (older versions are NOT supported)?
      1. If you're not sure, type `grapesjs.version` in console and press ENTER
  1. Are you facing the bug with your local copy of GrapesJS or with the current demo?

  1. If a local copy
      1. Indicate all informations about your OS, browser and GrapesJS version.
      Ubuntu 16.04 Firefox, Grapesjs V0.14.40
      1. Are you able to reproduce the bug from the demo?
Yes any time I call setStyle with a CSS string, it rejects any css containing # which is used to mark IDs
  1. What is the expected behavior?
I am using setStyle to load in an external CSS based on ongoing projects. When grapesjs sets css for attributes it creates a random id and after I export this Css and attempt to load it and set it again with a css string, it fails.

  1. What happens instead?
The function setStyles returns an error

**Comment by artf** [comment]
First of all, use the latest version and then, can you show an example and the error returned by setStyle?
