### ISSUE TITLE
[Question] Do any video tutorials exist for GrapesJS? 

### ISSUE THREAD

**Issue by ChaosWasTaken** [artf/grapesjs#176]
I'm fairly new to GrapesJS and was wondering if any video tutorials exist? The kind of stuff that shows how to make a website with it, tips on how to be faster, use certain features better, etc.

**Comment by artf** [comment]
I'd really like to make some but, at the moment, can't find time to do so

**Comment by landonwilkins** [comment]
- ya know, i knew nothing about grapesjs until this morning.
- someone commented on my gource viz*¹ of your codebase.
--- well, actually on my channel's discussion page*²... (lulz, why not on the actual video? amirite?)
- anyway, for such a popular project, seems like it'd be worthwhile to make a few videos ¯\_(ツ)_/¯
--- i scoured the web (and _may_ or may not have stalked you on the intertubes), found little.
--- i see "more tutorials coming soon" in one of your grapejs's tweets, but eh...
- but hey, i was just trying to help some beginner stranger, this isn't my problem so meh.
- cheers and best of luck in all your endeavors!
~~~
*¹: https://www.youtube.com/watch?v=hK5ZXjoNNQQ
*²: https://www.youtube.com/channel/UCIGrVrKtRyjrjEfPWBpJ12A/discussion?lc=UgzriQq6beBX1Z-YgVF4AaABAg (ictoTV's comment, at the bottom)
