### ISSUE TITLE
image not change while we fetch html using editor.getHtml()

### ISSUE THREAD

**Issue by AkibDeraiya123** [artf/grapesjs#1762]
Hello @artf 

I am using grapes.js for my website-builder tool into my website.
While i double click on any image the asset-manager will open and i can choose the image from asset-manager.

Now thing is that i putted the conditions like once user will choose any image from asset-manager i will replace that `img` tag with `div` tag and initialise one` image-editor (It's cropper.js) ` at there.

Now once i close the asset manager after selection of image the new path of image is set and also the new div will also set instead of img tag.

Once user will click on done button inside the editor(i mean image editor), then it will gives us the base-64 image i also replace the updated base-64 image into the UI but once i get the actual html content using `editor.getHtml()` i only get the updated path img tag instead of replaced div and base:64 image path.

Can i know how can i update the new image path (base-64) while i get html content using editor.getHtml()?

Here i attaching the screen-cast video for the same,
https://drive.google.com/file/d/1zeUcO8aVXDCeWCVakHpbycgHGtfnU4Qa/view

**Comment by artf** [comment]
You didn't show any code but I guess you've just edited DOM elements of the component when instead you should change its [Component](https://grapesjs.com/docs/api/component.html) model data (eg. `imgModel.set('src', 'base64....')`)

**Comment by AkibDeraiya123** [comment]
Hello @artf 
Thank you for your reply on my query.

I am attaching my code here, please let me know at where i am going wrong.
```
// This will execute once asset manager will be open
      editor.on("run:open-assets", function () {
        var dateNow = Date.now();
        editor.getSelected().setId(dateNow);

        // Store active asset manager image id and it's src
        localStorage.setItem('activeAssetManagerImageId', dateNow);
      })
```

So, basically above code will be run while user will double-click on particular image. In this function i am going to add one random generated  `id` attribute in selected image.

Now i also called the `stop:open-assets`,

```
editor.on("stop:open-assets", function () {
   // Here i am taking `src` from the `Dom` with `activeAssetManagerImageId` which is saved into `local-storage` and checking if both previous `src` and current `src` is not matched then i am going to initialize the cropper otherwise not. Now once user will be done with editing image i have one button and on button i called the one function. In this function right now i am changing the image `src` using jQuery which is working fine. But when i get `editor.getHtml()` It's not reflacted.
})
```

I have tried with like, This code is working fine while i am going to use `.set` function with `opts`. But here issue is that when i am adding this 3 lines then the assetManager is not going to open.

```
editor.Commands.add('open-assets', function(editor, sender, opts) {
        opts.target.set('src', 'https://images.pexels.com/photos/248797/pexels-photo-248797.jpeg');
      });
``` 

If there any editor.command method while user is choose the image and close the assetManager it will be run with three params like `editor, sender, opts`, so using this `opts` i can set the new image path which will be reflects into the UI as well as into model, so, when i will get the whole HTML then this src should be updated.?

or else how can i get this three params `editor, sender, opts` into the ```editor.on("stop:open-assets"``` function?

I did whatever, i tried to explained you here. If you still not get my point then let me know i will explain it again, but please give me some kinds of the example or something so i can get more idea about how can i achieve my goal with fantastic grapes.js lib as well people who have invented this.

Thanks in advance for your help.

**Comment by artf** [comment]
> In this function right now i am changing the image `src` using jQuery which is working fine. But when i get `editor.getHtml()` It's not reflacted.

... @AkibDeraiya123 this is exactlly what I told you in my previous comment... DON'T EDIT the DOM with JQuery... edit the model as I told you

**Comment by AkibDeraiya123** [comment]
@artf ,
I know you told me to solve using this solution `imgModel.set('src', 'base64....')`, but can you please let me know how can i get `imgModel` ?

Can i get this `imgModel` using id/class selector?

**Comment by artf** [comment]
You can get `imgModel` from the currently selected image component
```js
const imgModel = editor.getSelected();
```

> Can i get this `imgModel` using id/class selector?

Yes, if it's not selected you can find it by a selector 
```js
const imgModel = editor.getWrapper().find('img#eg-some-id')[0];
```

**Comment by AkibDeraiya123** [comment]
Hello @artf,
This is working fine. Thank you for your response.
But in my case it's slightly deffer, let me tell you in brief,
I have image tags in my default templates.
```
   // This will execute once asset manager will be open
      editor.on("run:open-assets", function () {
        var dateNow = 'img-'+Date.now();

        // Using below line i am changing the id of img tag on which user has clicked.
        editor.getSelected().setId(dateNow);

        // Store active asset manager image id and it's src
        localStorage.setItem('activeAssetManagerImageId', dateNow);
      })
```

Now once user will close the asset manager model, i am checking like if has select any image from asset manager or not.
If user has selected any image from the asset manager then i am initialize cropper.js with replace existing img tag and also add one function(`name is doneExternal`) into iframe window object.

When doneExternal will call, the edited image i am getting into base64, but when i am trying to set into the ui using `imgModel`, then it was't set. Actually when i am going to fetch imgModel it's getting an blank array `[]`.

```
 editor.on("stop:open-assets", function () {
    var mainDivId = Date.now();
    // fetch current active asset manager image
    var previousImageId = localStorage.getItem('activeAssetManagerImageId');
    var activatedImage = 'div-' + previousImageId;
    var previousSrc = localStorage.getItem('activeAssetManagerSrc');
    // Fetch iframe document. (Here we got the parent document not iframe's)
    var iframeDocument = document.getElementsByClassName('gjs-frame')['0'].contentDocument;
    // Fetch activated image's src to check we need to initialised cropper or not
    var updatedSrc = iframeDocument.getElementById(previousImageId).src;

    localStorage.setItem("activatedImageSrc", updatedSrc);

    // Check previous and updated image src are same or not. If not then we need to initialised cropper.
    if (updatedSrc !== previousSrc) {
        var mainDiv = "<div id='" + mainDivId + "'><img src ='" + updatedSrc + "' id ='" + previousImageId  + "' /><button onClick='doneExternal(previousImageId )'>Done</button></div>";
        iframeDocument.getElementById(previousImageId).replaceWith(mainDiv);
        
        // Cropper is initialising Here
        cropperInstance = new Cropper(activeCropperImageTag, {
            viewMode: 3,
            responsive: true,
            dragMode: 'move',
            autoCropArea: 1,
            restore: false,
            modal: false,
            guides: false,
            highlight: false,
            cropBoxMovable: false,
            cropBoxResizable: true,
            toggleDragModeOnDblclick: false,
            ready: function () {
                iframeWindow.doneButtonExternal = function (n) {
                    var base64Image = cropperInstance.getCroppedCanvas({
                        minWidth: 280,
                        fillColor: "#fff",
                        imageSmoothingEnabled: !1,
                        imageSmoothingQuality: "high"
                    }).toDataURL();
                    cropperInstance.destroy();
                    
                    // In below imgModel is getting undefined. Because imgModel is like blank array (Ex. [])
                    var imgModel = editor.getWrapper().find('img#'+previousImageId)[0];
                    imgModel.set('src', base64Image);
                }
            }
        })
    }
})

```

**Comment by artf** [comment]
```js
var mainDiv = "<div id='" + mainDivId + "'><img src ='" + updatedSrc + "' id ='" + previousImageId  + "' /><button onClick='doneExternal(previousImageId )'>Done</button></div>";
        iframeDocument.getElementById(previousImageId).replaceWith(mainDiv);
```
Again... you're editing the DOM and you're breaking the element with its model...
