### ISSUE TITLE
Add <Style> tag in block content objects (not a string)

### ISSUE THREAD

**Issue by poeeain** [artf/grapesjs#1763]
- Browser = Chrome
 - GrapesJS = Latest version ( 0.14.52 )

I am trying to create a block includes nesting content object with **script, style, type** properties. 
It works fine except adding **<style>** tag in the content. 

## Issue
If I create block content as a **String** like **option (A)** as below, CSS goes to CSS editor. 
But if I create block content as an object like **option (B)**, CSS remains in HTML editor.
( I am not sure this is a bug or not )

Here, What I want to achieve is 
 **_I want to create block like **option (B)**, but expect CSS to be in CSS editor._**

## **option (A)**
[codepen demo (A)](https://codepen.io/poepoe/pen/jdMKbj)
![a](https://user-images.githubusercontent.com/40139838/51924482-7a889880-241b-11e9-8535-49b5aee7cb67.jpg)

```
blocks: [
          {
                id: 'link',
                label: 'Link',
                category: 'Basic',
                attributes: {
                    class: 'fa fa-link'
                },
                content: `<a class="mylink-one" href="#">This is a link</a>
<a class="mylink-two" href="#">This is a link</a>
<style>.mylink-one{color:red;}.mylink-two{color:skyblue;}</style>`,     
            }
          ]
```

---- 

## **option (B)**
[codepen demo (B)](https://codepen.io/poepoe/pen/ERQjpK)
![b](https://user-images.githubusercontent.com/40139838/51924760-07335680-241c-11e9-8f75-7ca49906a8d0.jpg)
```
blocks: [
          {
                id: 'link',
                label: 'Link',
                category: 'Basic',
                attributes: {
                    class: 'fa fa-link'
                },
                content: {
                    script: function(){
                        console.log("I am dragged!")
                    },
                    type: 'link',
                    content: `<a class="mylink-one" href="#">This is a link</a>
<a class="mylink-two" href="#">This is a link</a>
<style>.mylink-one{color:skyblue};.mylink-two{color:teal}</style>`,
                }
            }
          ]
```

Why do I want this?
Because I have an inline CSS and custom javascript codes to append with the block (when user drag into the canvas).

----

_English is not my mother tongue; please excuse my bad explanation._

**Comment by artf** [comment]
```js
content: {
                    script: function(){
                        console.log("I am dragged!")
                    },
                    components: `...`, // use components instead of content
                }
```
BTW, I think, for your case, a custom component is more appropriate
