### ISSUE TITLE
How to use CKEditor/TinyMC editor instead of RichTextEditor inside GrapesJs 

### ISSUE THREAD

**Issue by hemanthmc** [artf/grapesjs#1764]
I need to add text styles and other text options so how to add CKEditor/TinyMC editor instead of RichTextEditor inside GrapesJs.

**Comment by ronaldaug** [comment]
You can check "Replace the built-in Rich Text Editor" in GrapesJS doc [here](https://grapesjs.com/docs/guides/Replace-Rich-Text-Editor.html#interface)
And there is a [GrapesJS CKEditor plugin](https://github.com/artf/grapesjs-plugin-ckeditor).

**Comment by hemanthmc** [comment]
> You can check "Replace the built-in Rich Text Editor" in GrapesJS doc [here](https://grapesjs.com/docs/guides/Replace-Rich-Text-Editor.html#interface)
> And there is a [GrapesJS CKEditor plugin](https://github.com/artf/grapesjs-plugin-ckeditor).

@ronaldaug CK Editors **Toolbar is not displaying** after adding grapesjs-plugin-ckeditor to my editor.
How to enable ToolBar options in it?

**Comment by ronaldaug** [comment]
I think you're missing something.
I made a [codepen demo](https://codepen.io/ronaldaug/pen/OdbxeY) here and it just works fine. 

You have to add CKEditor & [CKEditor Plugin](https://github.com/artf/grapesjs-plugin-ckeditor) scripts , and set the config options.

**Comment by hemanthmc** [comment]
Thank you so much for spending your time & answer. I had tried in the same way to integrate GrapesJs in react application. I am using npm packages 
**"ckeditor": "^4.11.2", "grapesjs-plugin-ckeditor": "0.0.9"** 

but i didn't able to get the CKEDITOR toolbar. i am getting the console error as shown in attached screenshot
![ckeditorerror](https://user-images.githubusercontent.com/12571680/52033119-d2bdb880-2549-11e9-934c-bb5c1407bd41.png)

**Comment by artf** [comment]
@hemanthmc check for errors in your code please, this has nothing to do with GrapesJS or CKEditor

**Comment by Amir2828** [comment]
> I think you're missing something.
> I made a [codepen demo here](https://codepen.io/ronaldaug/pen/OdbxeY) and it just works fine.
> 
> You have to add CKEditor & [CKEditor Plugin](https://github.com/artf/grapesjs-plugin-ckeditor) scripts , and set the config options.

Hey the CodePen link is not working, Can you please upload it again?
Im facing the same problem and it seems like you got the solution :)

**Comment by umerrinayat** [comment]
@ronaldaug codpen link is not working. Can you please share your code again. Thanks

**Comment by shubh9415** [comment]
> I think you're missing something.
> I made a [codepen demo here](https://codepen.io/ronaldaug/pen/OdbxeY) and it just works fine.
> 
> You have to add CKEditor & [CKEditor Plugin](https://github.com/artf/grapesjs-plugin-ckeditor) scripts , and set the config options.

@ronaldaug Can you please upload the codepen link again. I am struggling for hours to implement CKEDITOR but getting the error.

**Comment by matteocollina** [comment]
Here a codepen: https://codepen.io/artf/pen/wVdzYK
