### ISSUE TITLE
[Qusetion]: Production version number

### ISSUE THREAD

**Issue by master-procrastinator** [artf/grapesjs#1765]
Hi just a quick question
I've noticed that the **dev** branch is at version **0.14.52** but the **master** branch is still at **0.14.43** even though the documentation (https://grapesjs.com/docs/#why-grapesjs) states 0.14.52 as the latest and also the demo uses 0.14.52.
What I'd like to know is if 0.14.52 is production ready and has just not been moved over into the master branch yet or if the dev branch requires more work before being production ready?

Cheers

**Comment by artf** [comment]
> .. and has just not been moved over into the master branch yet

Yeah, in this case, 0.14.52 is the latest
