### ISSUE TITLE
Is There any way to integrate ImageEditor in GrapesJs

### ISSUE THREAD

**Issue by hemanthmc** [artf/grapesjs#1766]
After Dropping the image inside the editor is there any **plugin** for **GrapesJs** to **edit** that image like Cropping , adding text on it .....

**Comment by ronaldaug** [comment]
@hemanthmc, take a look the plugins list.
https://github.com/artf/grapesjs#plugins

**Comment by artf** [comment]
Unfortunately, Aviary is dismissed so [grapesjs-aviary](https://github.com/artf/grapesjs-aviary) doesn't work properly, but you can check [its code](https://github.com/artf/grapesjs-aviary/blob/master/src/index.js) to see how it was implemented
