### ISSUE TITLE
Error in integrating GrapesJs-plugin-ckeditor inside ReactJs

### ISSUE THREAD

**Issue by hemanthmc** [artf/grapesjs#1769]
I am integrating GrapesJs in react application. I am using npm packages
"ckeditor": "^4.11.2", "grapesjs-plugin-ckeditor": "0.0.9"

`import React from 'react';
import { connect } from "react-redux";
import GrapesJS from 'grapesjs';
import CKEDITOR from 'ckeditor';
import gjsCkEditor from 'grapesjs-plugin-ckeditor';

class gEditor extends React.Component {
  .
  .
  .
  var editor = GrapesJS.init({
                fromElement: true,
                autorender: false,
                container: `#${containerId}`,
                components: '<div className="txt-red">Hello world!</div>',
                assetManager: {},,
                plugins: ['grapesjs-plugin-ckeditor'],
                storageManager,
                blockManager
            });
}
`

but i didn't able to get the CKEDITOR toolbar. i am getting the console error as shown in attached screenshot
![ckeditorerror](https://user-images.githubusercontent.com/12571680/52046669-48874b80-256d-11e9-8426-044ff3093ff1.png)

Please help me to fix this error

**Comment by artf** [comment]
https://github.com/artf/grapesjs/issues/1764#issuecomment-460853741
