### ISSUE TITLE
[Bug] Components with custom tag are not rendered if specified in theme body

### ISSUE THREAD

**Issue by a-bashtannik** [artf/grapesjs#1770]
Hello
I created very simple skeleton of GrapesJS editor.
HTML template:
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Demo</title>
</head>
<body>
<div id="gjs">
    <test-tag></test-tag>
</div>
</body>
</html>
```
Javascript:
```javascript
import 'grapesjs/dist/css/grapes.min.css'
import grapesjs from 'grapesjs';

var editor = grapesjs.init({
    autorender: 0,
    container: '#gjs',
    fromElement: true,
    storageManager: {type: null},
});

// Get DomComponents module
var comps = editor.DomComponents;
var defaultType = comps.getType('default');

comps.addType('test-component-type', {
    model: {
        defaults: {}
    },
    view: {
        tagName: 'div',
        render: function () {
            defaultType.view.prototype.render.apply(this, arguments);
            var element = document.createElement("h1");
            element.innerText = "TEST-COMPONENT OK";
            this.el.appendChild(element);
            return this;
        }
    },

});

editor.render()

editor.BlockManager.add('test-block', {
    label: 'Test Block',
    content: {
        type: 'test-component-type'
    }
});
```
Result of loading: 
![image](https://user-images.githubusercontent.com/2712350/52058564-6609e480-2570-11e9-94f8-d7a4425837ad.png)
As you see, component is not rendered.
But if I drop blocks manually, everything is ok:
![image](https://user-images.githubusercontent.com/2712350/52058679-a10c1800-2570-11e9-9d46-dcee38db9e66.png)
If I change template and set `data-gjs-type` attribute to `<test-tag data-gjs-type="test-component-type"></test-tag>` value, everything works too. 
![image](https://user-images.githubusercontent.com/2712350/52058816-ecbec180-2570-11e9-98b5-dda664c24813.png)

I tried also construction with `isComponent` defined but with the same result. Custom tags, specified in templates are not rendered on page load. 

Looks like bug, or maybe I'm wrong somewhere and additional render calls required? 

Thanks.

**Comment by artf** [comment]
There are 2 issues:
* You forgot to specify `isComponent` (used in the parsing process)
```js
comps.addType('test-component-type', {
    isComponent: el => el.tagName === 'TEST-TAG',
    view: {
		// use onRender hook instead of render
        onRender() {
            const el = document.createElement("h1");
            el.innerText = 'TEST-COMPONENT OK';
            this.el.appendChild(el);
        }
    },
});
```
* Currently, new component types are not working for the initial template,
so the only way is to add them via plugins (I didn't find time to see why it's happening)

https://jsfiddle.net/m8hkuza3/
