### ISSUE TITLE
Traits type : button not working

### ISSUE THREAD

**Issue by Soharab-Shaikh** [artf/grapesjs#1771]
Hi, @artf 
When I try to use button type traits. It does not fire any function. Can you please help me with this.
Can you please share an example of new traits type creation like "Button", not the "Content" one.

`traits: [
	{
	type: 'button',
	label: 'Submit',
	name: 'blog_submit',
	changeProp: 1
	}
]
....													
init() 
{
	this.listenTo(this, 'change:blog_submit', this.changeFilter);
}
.....`

**For new traits type creation, I am trying**

 editor.TraitManager.addType('button', {
       events: {
            **'keyup' : 'onChange'**  **// what should we use in this part?**
        },
        getInputEl: function () {
            if (!this.inputEl) {
                var x = document.createElement("INPUT");
                x.setAttribute("type", "button");
              // x.setAttribute("onclick", "changeData()");
                this.inputEl = x;
            }
            return this.inputEl;
        }
      //changeData: function () {
       //alert("hi");
     // }
    });

**Comment by artf** [comment]
Hi @Soharab-Shaikh you have to pass the `command` option (will be executed on click):
```js
traits: [
	{
		...
		type: 'button',
		command: 'COMMAND-ID',
		// or like a function
		command: editor => {
			const selected = editor.getSelected();
			// do something...
		},
	}
]
```
