### ISSUE TITLE
Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by itsallrelative** [artf/grapesjs#1772]
Hello, 

I am spinning up a new instance of grapeJS, and immediately everything breaks and I get the following error:

Cannot read property 'indexOf' of undefined at grapes.js:6477

My code looks like the following:

```html
<link href="//unpkg.com/grapesjs/dist/css/grapes.min.css" />
    <script src="//unpkg.com/grapesjs"></script>

    <div id="gjs">
        <h1>Hello World Component!</h1>
    </div>
    <div id="blocks"></div>

    <script>
        $(document).ready(function () {
            grapesjs.init({
                // Indicate where to init the editor. You can also pass an HTMLElement
                container: '#gjs',
                // Get the content for the canvas directly from the element
                // As an alternative we could use: `components: '<h1>Hello World Component!</h1>'`,
                components: '<h1>Hello World component!</h1>'
            });
        });
    </script>
```

It looks like it is trying to return indexOf on self, but self isn't defined. Can you quickly help me resolve this?

`return self.indexOf(item) === index;`

**Comment by artf** [comment]
Try to disable (and then probably clean) the storage with passing `storageManager: {type: null}`

https://jsfiddle.net/h204La5o/
