### ISSUE TITLE
Feature Request: Drag and Drop Absolute Positioning

### ISSUE THREAD

**Issue by MACscr** [artf/grapesjs#1774]
Unless I am missing something, it appears that you cant drag and drop absolute positioned elements. In my opinion, if an element is set to absolute positioning, you should be able to drag and drop the the item to anywhere within its relatively positioned parent. We should not be required to manually input positions (top, left, bottom, right) and should be calculated when dragged and dropped. Im already doing something like this with a home brew editor, but looking into a more powerful option like yours that i can build off instead. Hopefully this feature isnt already available and I missed something.

**Comment by artf** [comment]
Not yet implemented, but it's in our Roadmap

**Comment by sccorby** [comment]
Bump. Definitely a high-priority feature for a WYSIWYG environment. 
Question for @artf : Would this be possible to implement with a custom menu/panel on our own?

**Comment by MACscr** [comment]
> Bump. Definitely a high-priority feature for a WYSIWYG environment.
> Question for @artf : Would this be possible to implement with a custom menu/panel on our own?

He already has it in the works: https://github.com/artf/grapesjs/issues/1936
