### ISSUE TITLE
[Question] Add read-only trait for all controls

### ISSUE THREAD

**Issue by shrnfnchr** [artf/grapesjs#1776]
We are using grapejs to create webpages.  We are doing some back end manipulation of the json to link each child of the html (usually a row) to a record in our database.  To that end, I've added a trait to every component called custom_pk.  Upon saving the grapejs, I loop through the first level of components and add a record.  Then I update the custom_pk with the primary key of the record in the database.    The json has the appropriate trait and the html shows the custom_pk that I need.  The last thing I'd like to do is to make the custom_pk trait read only while looking at the page through grapejs.  Since it's updated on save (and since any change to the PK will break our implementation), I'd like for the user to not be able to change it.  Here is my implementation: [https://jsfiddle.net/shrnfnchr/ju8n1xdg/30](https://jsfiddle.net/shrnfnchr/ju8n1xdg/30) In order to see the custom field, I drag and drop a column 1 block onto the canvas, click on the row and then look at settings.  I'm open to other ways to doing this.

**Comment by artf** [comment]
Create your own trait https://grapesjs.com/docs/modules/Traits.html
