### ISSUE TITLE
Traits type Checkbox not checked from the initialization of the Component type.

### ISSUE THREAD

**Issue by Soharab-Shaikh** [artf/grapesjs#1779]
Hi, Artur

When I try to **check traits (type: checkbox)** from the **init()** of the domCom Type the value set as true but not checked. 
**Code:**
```js
traits: [
{
    type: 'checkbox',
    label: 'Display Pagination',
    name: 'pagination',
    changeProp: 1
}
]
....
init()
{
	var pagination = this.get('traits').where({ name: 'pagination' })[0];
	**var paginationData = "true";    //(can came from DB)**
	pagination.set('value', paginationData == "true" ? true : false);
}
```

![image](https://user-images.githubusercontent.com/46919027/52396665-b0431680-2ad8-11e9-8fc8-51d400200205.png)

**_Thanks man for your great work_**

**Comment by artf** [comment]
The trait reads from the component, edit the component itself not the trait value.
`this.set('pagination',  paginationData == "true" ? true : false)`

**Comment by Soharab-Shaikh** [comment]
No, I just want to checked the trait not the componen y.
