### ISSUE TITLE
How to change extra dropdown for link change trait

### ISSUE THREAD

**Issue by AkibDeraiya123** [artf/grapesjs#1780]
Hello @artf ,
I want to give one more functionality to user like user can change any link with default links drop down.

![screenshot 5](https://user-images.githubusercontent.com/25474716/52442186-cfff2c80-2b22-11e9-8f2b-1e3249655125.png)

In above image i want to add one more dropdown for the default links.

If user will select the links from the drop-down then also need to change `href` of selected link and on other hand if user will type link into `href` input text-box(marked in above image) then also need to change the href of selected links.

How can i do this things can you please help me?

**Comment by artf** [comment]
Create a custom trait: https://grapesjs.com/docs/modules/Traits.html

**Comment by AkibDeraiya123** [comment]
Hello @artf 
If i only want to do in change trait for href(`<a `) tag then how can i change that?
I tried like,

```var domComps = editor.DomComponents;
    var dType = domComps.getType('default');
    var dModel = dType.model;
    var dView = dType.view;

    domComps.addType('a', {
      model: dModel.extend({
        defaults: Object.assign({}, dModel.prototype.defaults, {
          traits: [
            // strings are automatically converted to text types
            {
              type: 'select',
              label: 'Href',
              name: 'href',
              options: [
                {value: 'index.html', name: 'Home'},
                {value: 'index2.html', name: 'Home2'},
                {value: 'index3.html', name: 'Home3'},
                {value: 'index4.html', name: 'Home4'},
              ]
            }
          ],
        }),
      }, {
        isComponent: function(el) {
          if(el.tagName == 'a'){
            return {type: 'a'};
          }
        },
      }),

      view: dView,
    });```

But this is something like not works. Can you please help me at where i am doing wrong?

**Comment by AkibDeraiya123** [comment]
And one more question, how can i check the selected DOM element's type?
I guess it will use `isComponent` function. But i don't know how to use it and where?

**Comment by artf** [comment]
Extend the `link` component

https://jsfiddle.net/0y6fu9d1/

**Comment by AkibDeraiya123** [comment]
Hello @artf 
This is works fine in my system. Thanks for your support.
Now i want to add links into this traits while user add new page.
I am creating website builder using grapejs with default template choosing.

Let me explain you in brief.
Suppose user is creates one website with template-1. Then the `index.html` of template-1 will be shown into the grapesjs editor.

Now, i have one functionality like user can add new page into his/her template.
So, suppose user did creates one page with `test.html` and it's successfully created.
Now after successfully page creation i want to add this options into the traits without page refresh or something.

Is it possible?

**Comment by artf** [comment]
You have to update trait's options
```js
editor.getSelected().getTrait('href').set('options', [
	{ value: 'page1.html', name: 'Page 1' },
	...
])
```

**Comment by AkibDeraiya123** [comment]
Hello @artf 
I tried this your above solution. But it's not reflect into the `href` links drop-down.

I can show you the using screen-cast video. Can you check and let me know what still i missing to achieve my goal,

https://drive.google.com/file/d/1mLFLCVSvJx_up0ymu8zFwJJwpQDq3Dzg/view

**Comment by artf** [comment]
Does it work if, after adding the option, you add `editor.trigger('component:toggled');`?

**Comment by AkibDeraiya123** [comment]
@artf 
At where i need to put this line and test it?
`editor.trigger('component:toggled');`

**Comment by artf** [comment]
In your code, after updating trait options...

**Comment by AkibDeraiya123** [comment]
Yes @artf ,
It's working nice.
Thank you for response. 

But there is one issue is like when i click on template default links the traits are not going to show into sidebar, But when i drag some links near it's links and show the traits into settings table it shows the dropdown as well new dynamic options too.

I just update the grapes.js file version to 0.14.50.
Do you think is there any issue with myside code or new version for the links?

Here is my code,

```
editor = grapesjs.init({
 // Added configurations here
});

function loadHrefTrait() {
    var options = [
      {
        value: 'products.html',
        name: "Product"
      },
      {
        value: 'campaigns.html',
        name: "News"
      },
      {
        value: 'reviews.html',
        name: "Reviews"
      },
      {
        value: 'index.html',
        name: "Home"
      },
      {
        value: 'products.html?gender=men',
        name: "Mens Products"
      },
      {
        value: 'products.html?gender=ladies',
        name: "Ladies Products"
      },
      {
        value: 'products.html?gender=boy',
        name: "Boys Products"
      },
      {
        value: 'products.html?gender=girl',
        name: "Girls Products"
      },
      {
        value: '#',
        name: "No Links"
      }
    ];

    var dType = editor.DomComponents.getType('link');
    var dModel = dType.model;
    var dView = dType.view;

    editor.DomComponents.addType('link', {
        model: dModel.extend({
          defaults: Object.assign({}, dModel.prototype.defaults, {
            traits: [
              // strings are automatically converted to text types
              // title,
              {
                type: 'select',
                label: 'Target',
                name: 'target',
                options: [
                  { value: '', name: 'This window' },
                  { value: '_blank', name: 'New window' }
                ]
              },
              {
                type: 'select',
                label: 'Href',
                name: 'href',
                options: opts
              }
            ],
          }),
        }, {
          isComponent: function(el) {
            if(el.tagName == 'A' || el.tagName == 'LINK'){
              return {type: 'link'};
            }
          },
        }),
    
        view: dView,
      });
    })

loadHrefTrait();
editor.trigger();

// This function will call from ui dynamically and add new links into this above traits
function addDynamicOption(page) {
    editor.getSelected().getTrait('link').set('options', [
        { value: page +'.html', name: page }
    ]);
    editor.trigger('component:toggled');
}

```
