### ISSUE TITLE
add a font-size type prop

### ISSUE THREAD

**Issue by kickbk** [artf/grapesjs#1781]
I'm trying to create a font-size type of property that I would like to add to the dimensions sector.
Doing this:

```
styleManager.addProperty('Dimension',{
	name: 'Icon Size',
	property: 'icon-size',
	type: 'integer',
	units: ['px', 'em', 'rem', '%']
});
```

Getting the value and all, but it's just showing an input box. Not one with the select option between the units. What am I doing wrong?

**Comment by artf** [comment]
Seems to work on my side: https://jsfiddle.net/ewyb2zcu/
