### ISSUE TITLE
How to deploy to heroku 

### ISSUE THREAD

**Issue by justinechacko** [artf/grapesjs#1783]
Hi,  
I am trying to deploy grapesjs to heroku. I successfully deployed it. But I can't find the app in home page. It says application error. Do I need to set url in the project?

**Comment by artf** [comment]
The index.html is there for the dev environment... so create your app first, then deploy wherever you want

**Comment by justinechacko** [comment]
Does this app require a database?

**Comment by artf** [comment]
no, it's up to you decide how to store your data, more info here: https://grapesjs.com/docs/modules/Storage.html
