### ISSUE TITLE
Remove Default components with canvas elements

### ISSUE THREAD

**Issue by metamohitsharma** [artf/grapesjs#1784]
How to remove default components that comes with canvas elements i.e., Copy, move and delete
![screenshot from 2019-02-11 15-35-49](https://user-images.githubusercontent.com/41181457/52556524-d2a79d80-2e12-11e9-8c7b-d6449f4cf7d3.png)

**Comment by artf** [comment]
??? There are no default components if you don't load them (eg. from LocalStorage)
