### ISSUE TITLE
[Question] Change HTML of Panel buttons from span to button

### ISSUE THREAD

**Issue by ateebahmed** [artf/grapesjs#1787]
I have created some Panels and would like to change the element of panel buttons from `span` to `button` as its more appropriate and looks better with CSS, how would I configure it?

**Comment by artf** [comment]
Right now it's not possible, but I'll add this possibility in the next release, so it'll be something like this:
```js
editor.Panels.addButton('PANEL-ID', {
	id: 'test',
	tagName: 'button',
	className: 'someClass',
	command: editor => alert('Test'),
})
```

**Comment by ateebahmed** [comment]
That'd be great!
