### ISSUE TITLE
[Question] How to append a plus icon in the column and element section?

### ISSUE THREAD

**Issue by sunhillbd** [artf/grapesjs#1789]
Hi @artf .
First of all, great work.
I have been trying to use grapesjs for a month now. So, I stumbled upon a situation where I need to let the user show the block sidebar when they click on a + icon. This would have given the users a bit more simplicity. Any guideline on how I can achieve this? See the attachment pls. thanks
![plus-grapesjs](https://user-images.githubusercontent.com/8676756/52689074-2802bc80-2f83-11e9-9471-5374bc88e277.png)

**Comment by artf** [comment]
Hi @sunhillbd I think this is a perfect case when you should use the `view` in components. The "plus button" is part of the component but only inside the canvas/editor and it shouldn't be exported in the final code
https://jsfiddle.net/xcv07abt/
