### ISSUE TITLE
[Bug]: Duplicate CKEditor Toolbar 

### ISSUE THREAD

**Issue by tranthanhhoa** [artf/grapesjs#1793]
hi @artf ,
Grapejs version: 0.14.52

**Steps reproduce:**
1. Access the link: https://grapedrop.com
2. Login and go to template site.
3. Edit one template.
4. Drag and drop text component first.
5. Continues to drag and drop the 2 columns component under the text component.
6. Click and hold the mouse to move text component to inside the 2 columns.
7. Double click on the text and observe the tool bar.

**Expected:**
- It should only one tool bar.

**Actual:**
- Tools bar are displayed.
![image](https://user-images.githubusercontent.com/6691878/52771356-51494880-3068-11e9-8c3e-c64febb9eaaf.png)

**Comment by artf** [comment]
Seems like it happens with the upgrade of CKEditor (4.6.2 -> 4.9.2), BTW @tranthanhhoa I kindly ask you to move this issue to the appropriate repository as it's not related to the core one
