### ISSUE TITLE
LeadPages - Thrive - Looking to integrate into Mautic a real designer of landing pages and email templates

### ISSUE THREAD

**Issue by kuggaa** [artf/grapesjs#1799]
1. Looking through docs - api to integrate into Mautic as a plugin to create forms and email templates.
Any advice in tasking this?  Anyone interested in a couple day project?  Have bounty

**Comment by arthuralmeidap** [comment]
@kuggaa , I'm interested. How could I reach you out?

**Comment by artf** [comment]
You can keep discussing all the details here but I close the issue as it's kinda off-topic
