### ISSUE TITLE
Asset Manager store function

### ISSUE THREAD

**Issue by fgiannar** [artf/grapesjs#18]
When using remote storage for asset handling, I believe there is a bug in the _store_ function inside the _AssetsView.js_ file.

Replacing:
`this.storagePrv.store(this.storeName, JSON.stringify(this.collection.toJSON()) );`

With:
```
var a = [];
a[this.storeName] = JSON.stringify(this.collection.toJSON());
this.storagePrv && this.storagePrv.store(a)
```

seems to fix it, but have only tested with remote storage.

**Comment by artf** [comment]
Hi @fgiannar , at first, you should update your grapesjs because from the 0.3.10 I've refactored a lot of stuff and moved store/load methods on the top level of each module.
Then let me know if you still have problems.
Thanks
