### ISSUE TITLE
Unable to get ::after of class of selected

### ISSUE THREAD

**Issue by froderf** [artf/grapesjs#1802]
```
.sample-class{
     color: red;
}

.sample-class::after{
   content:'';
   color: black;
}
```

I can't get the css rule of a class with '::after'

`cssComposer.getClassRule("sample-class", {state: 'after'})`

is there a way to get 
```
content:'';
color: black;
```

since the only state I know were 'hover', and 'active'

Thank you !

**Comment by artf** [comment]
You should use `{state: ':after'}`, anyway I'd recommend to start using the new [`getRule`](https://grapesjs.com/docs/api/css_composer.html#getrule) as it would be even faster `cssComposer.getRule('.sample-class::after')`
