### ISSUE TITLE
[Feature request] Fixed size canvas

### ISSUE THREAD

**Issue by ageir** [artf/grapesjs#1803]
We're using GrapesJS at work for building a kiosk-system into our CMS.
Currently using the webpage template.
We are displaying the content on displays/tvs which has a fixed resolution, for example 1920x1080 laying down, or 1080x1920 standing on the side And I've tried to find a way to limit the resolution in the canvas with no luck.
We'd like to limit the size of the canvas to the resolution in both x and y to the resolution (and rotation) on the display we're editing for, so that you can see the actual content that will be displayed on the tv. This will (sometimes) add scrolling in the canvas in the webpage template ofcourse, but I don't see that as a problem as its more important to know that the design you're working on will look the same on the tv.

Any ideas on how to solve this?

I'm not familiar with the code yet so I have no idea how to best solve this. Any help appreciated.

**Comment by artf** [comment]
Have you tried the [Device Manager API](https://grapesjs.com/docs/api/device_manager.html)

> This will (sometimes) add scrolling in the canvas in the webpage template ofcourse, but I don't see that as a problem as its more important to know that the design you're working on will look the same on the tv.

Probably from the next release it will expose an API for zooming (from the Canvas module)

**Comment by ageir** [comment]
Yeah I did, works great if you are editing on a screen that is larger than the intended content. But if your for example editing for a 4k screen on a full HD screen its a bit problematic. Zooming seems great! Would be great if you can zoom at a pixel level as well as percent.

But it doesn't support max height, which makes it impossible to know where it will cut the content vertically. Would be great to have that option. Any idea how to solve this? Is there an easy fix? or is it a big change? The best would be to limit vertical height so you can't add new content below it. Or next best would be to have a divider/line/indicator so you can see where it will cut off for a set height.

**Comment by artf** [comment]
> Yeah I did, works great if you are editing on a screen that is larger than the intended content. But if your for example editing for a 4k screen on a full HD screen its a bit problematic. Zooming seems great! Would be great if you can zoom at a pixel level as well as percent.

The zoom will be a value from 0 to 100

> The Device Manager API doesn't support max height, which makes it impossible to know where it will cut the content vertically. This is pretty important for editing fixed height displays. Would be great to have that option. Any idea how to solve this? Is there an easy fix? or is it a big change? The best would be to limit vertical height so you can't add new content below it. Or next best would be to have a divider/line/indicator so you can see where it will cut off for a set height.

Well, you can pass the `height` to the device, it's not clear to me what exactly MAX height would do here. If you exceed the limit, eg. by adding a component to the wrapper or changing the height style of a section, you will obviously see the canvas with the scrollbar

**Comment by ageir** [comment]
How do you pass the height? It's not mentioned in the manual: https://grapesjs.com/docs/api/device_manager.html#add

Max height in my idea, would limit the height, so that you can't add new components below that height.

**Comment by artf** [comment]
@ageir look at the example...


> Max height in my idea, would limit the height, so that you can't add new components when the height of the contents in the canvas reaches the limit..

No, this is not something I'd like to have in the core, would be too much expensive as a check on any update

**Comment by ageir** [comment]
> @ageir look at the example...
> 
> > Max height in my idea, would limit the height, so that you can't add new components when the height of the contents in the canvas reaches the limit..
> 
> No, this is not something I'd like to have in the core, would be too much expensive as a check on any update

@artf 
Yeah, probably. But some kind of horizontal indicator where it cuts off would be great.

**Comment by artf** [comment]
> Yeah, probably. But some kind of horizontal indicator where it cuts off would be great.

Why horizontal indicator? I think the fixed frame of the canvas is already an indicator?!?

**Comment by jokin** [comment]
it works a bit different as it works with fixed size canvas instead of scrollable ones, but the slides.com editor does it quite nicely. It has a fixed size div which scales to fit on the viewport. 

![image](https://user-images.githubusercontent.com/58509/58133379-fc4b3e80-7c23-11e9-8d96-a583692d4076.png)
