### ISSUE TITLE
Define new Image component

### ISSUE THREAD

**Issue by sakshigarg9** [artf/grapesjs#1805]
I'm new to GrapesJs and am unable to figure out how to create an image component. For example, I have an img tag and have defined the src , what is the code to make it an image component, one that induces an asset manager on double click, is resizable and movable.

**Comment by artf** [comment]
Read about [Components](https://grapesjs.com/docs/modules/Components.html), check the API of each [Component](https://grapesjs.com/docs/api/component.html), check the source of the [ImageComponent's view](https://github.com/artf/grapesjs/blob/dev/src/dom_components/view/ComponentImageView.js)
