### ISSUE TITLE
GrapeJs framework breaks on adding external stylesheet

### ISSUE THREAD

**Issue by sakshigarg9** [artf/grapesjs#1807]
When i add my external stylesheet using

```
const editor = grapesjs.init({

	canvas: {
		styles: [
		'style.css',
		]
	}
});
```
the grapesjs framework no more works. How can I have the style sheet as well as the grapesjs framework.
Is this happening because some styles may not be compatible with GrapesJs?

**Comment by artf** [comment]
Well it's not that hard to break stuff with CSS, so yes, a bad written CSS (eg. using global selectors `*` or via tags like `div, span { ... }`) definitely can break the editor
