### ISSUE TITLE
Customize image resizing

### ISSUE THREAD

**Issue by sakshigarg9** [artf/grapesjs#1809]
If i want to limit resizing an image to only specific dimensions, how can i do that?
Also is it possible to enable resizing only from the bottom right corner and disable from the other corners and points?

**Comment by artf** [comment]
You can use [this options](https://github.com/artf/grapesjs/blob/e79ffd96979e2e435462ffc76139f5b5906eae5d/src/utils/Resizer.js#L4-L69) for the `resizable` property of components

**Comment by sakshigarg9** [comment]
How can I update these properties if I'm using the grapesjs-preset-webpage?

**Comment by artf** [comment]
> How can I update these properties if I'm using the grapesjs-preset-webpage?

You can always update a component type (but do it as a plugin)
```js
editor.DomComponents.addType('image', {
	model: {
		defaults: {
			resizable: {
				  tl: 0, // Top left
                  tc: 0, // Top center
                  tr: 0, // Top right
                  cl: 0, // Center left
                  bl: 0, // Bottom left
			}
		}
	}
})
```

**Comment by sakshigarg9** [comment]
'image' refers to image type components or is it the classname?

**Comment by sakshigarg9** [comment]
@artf how can make this setting apply only to a particular img class and not all img tags?
