### ISSUE TITLE
i cant upload images from my pc only from online resources please help

### ISSUE THREAD

**Issue by mhsdts** [artf/grapesjs#181]
i need to upload images from pc but i cant find a way to apply it

**Comment by fzs1994** [comment]
My solution, in your `grapesjs.init` method, init your images:
```
var your_image = '/path/to/your/image.png';
editor = grapesjs.init({
...,
assetManager: {
      assets: your_image
}
...
```
Else,
You need to post images to your API.

**Comment by mhsdts** [comment]
thak you, now i created an api to store the image , 
now how can i use the images , the exact way

**Comment by fzs1994** [comment]
https://github.com/artf/grapesjs/wiki/API-Asset-Manager
https://github.com/artf/grapesjs/wiki/API-Asset-Manager#add
Check this out.

**Comment by rafal-olszewski** [comment]
This doesn't show how to show images in the "uplodaer" after the image has been uploaded. Also, function `load()` of AssetManager, does not always load the images in the modal.

**Comment by artf** [comment]
Once the image(s) is uploaded the ajax request expects a JSON response with `data` key containing an array of images to add inside the asset manager. This might help #138
