### ISSUE TITLE
changesCount change on clicking any element in editor

### ISSUE THREAD

**Issue by metamohitsharma** [artf/grapesjs#1811]
Hello,
I have used changesCount to resizeEditor if any change occurs to the canvas.
But when I select any element in canvas like, clicking any div in canvas increases changesCount so the editor resizes it.
So, I want to disable changesCount on selecting any element, it should only increase its count when some change is done in canvas.
If you have another approach that I can use please share it.

**Comment by artf** [comment]
No, you can't disable it
