### ISSUE TITLE
[Bug]: 404 when trying to add background image (reproducible in demo)

### ISSUE THREAD

**Issue by ryancwalsh** [artf/grapesjs#1812]
1. Visit https://grapesjs.com/demo.html in Chrome Incognito
1. Click the "Header" element
1. Click Decorations > Background
1. Delete Layer 2
1. Click Layer 1
1. Click "x" to delete the purple background image
1. Notice "GET https://grapesjs.com/none 404" error in the console
1. Click "Images"
1. Try to add any other new image, and nothing works

**Comment by artf** [comment]
> 9. Try to add any other new image, and nothing works

I can't reproduce this one

**Comment by ryancwalsh** [comment]
I'm still experiencing the same bug in Win 10 Chrome Incognito, and I also tried Firefox (Private Window) and experienced the same bug except without the 404 in the console (step 7).

**Comment by NicoEngler** [comment]
I can confirm step 7 tested in Chrome 72.0.3626.119 both normal & incognito mode

**Comment by artf** [comment]
@NicoEngler are you able to reproduce also the 9th?

**Comment by NicoEngler** [comment]
@artf I can't, adding images works (both normal & incognito mode).

**Comment by ryancwalsh** [comment]
Update: I just tried again on Win 10 Chrome Incognito Version 72.0.3626.121 (Official Build) (64-bit) using my original steps above.

This time, the console error says `Failed to load resource: the server responded with a status of 404 () none:1`.

_But_, in Step 9, I can successfully add an image.

I don't know if something changed with grapesjs or with Chrome, but this seems to work for me now.

**Comment by ryancwalsh** [comment]
And it works in Firefox (Private Window) now too.

**Comment by Bhavana20** [comment]
Hi @artf,

I'm also facing the same issue in the demo and also with my application. When I follow the below steps, there are error messages as in the attached screenshots. 

1. Select a component.
2. Select decorations from the style manager.
3. Click on the plus sign (+) next to **Background**. There is an error in the console.

This is internally crashing my application.

Error in the GrapesJs Demo:
![image](https://user-images.githubusercontent.com/10365593/59582737-d4ea7300-90f6-11e9-9b38-ee77b81914a9.png)

Error in my application:
![image](https://user-images.githubusercontent.com/10365593/59582772-edf32400-90f6-11e9-9047-6f900aef5400.png)

**Comment by verdverm** [comment]
https://github.com/artf/grapesjs/search?q=placehold&unscoped_q=placehold

The `placehold.it` does not seem to be part of the internet anymore
