### ISSUE TITLE
[Question]: How to fire event which triggers component:selected with my component

### ISSUE THREAD

**Issue by ateebahmed** [artf/grapesjs#1814]
I want to select my component whenever it is dragged from blocks to canvas and rendered, I have tried with registering events on `component:add`, `component:mount` and calling `editor.select(component)`, passing the component I get from callback, but it is not properly initialize or has properties missing, like its type is not what I expect for my component to be and its custom trait is not initialized when called through this way, but if I select the same component by clicking, the component I get in `component:selected` is what I expect and its trait is also rendered correctly.

What am I doing wrong?

**Comment by artf** [comment]
https://github.com/artf/grapesjs/issues/1813#issuecomment-466408328
