### ISSUE TITLE
[Bug]: component:mount is fired multiple times

### ISSUE THREAD

**Issue by ateebahmed** [artf/grapesjs#1815]
I had been using editor events and I noticed that `component:mount` event fires multiple times when a component is dragged from blocks to canvas, you can confirm it in your JSFiddle Starter.

```javascript
editor.on('component:mount', component => console.log('mounted', component))
```

**Comment by artf** [comment]
@ateebahmed please don't open issues like this. **Follow the template**

**Comment by ateebahmed** [comment]
okay will reopen it
