### ISSUE TITLE
[Question]: Block content attributes (ngModel in my case) forced to lowercase

### ISSUE THREAD

**Issue by sushiljic** [artf/grapesjs#1819]
I am trying to use angular directive.
On any of the block content,
for example 
`  bm.add('radio-block',{
    label:'Basic Form Element',
    category: c.category,
    content: '<input type="text" name="username" id="username"  ngModel> '
  })
`
on export ngModel will be ngmodel
So what will be possible solution so that it display ngModel on export Code
I have also look for the [issue#1591](https://github.com/artf/grapesjs/issues/1591) 
But Could not find solution.

**Comment by artf** [comment]
ngModel is converted in ngmodel by the browser (HTML5 doesn't accept uppercase for attributes)
You can skip the parser by passing a component object
```js
bm.add('radio-block', { 
	label:'Basic Form Element', 
	content: {
		tagName: 'input',
		attributes: { type: 'text', ngModel: true }
	}
})
```
