### ISSUE TITLE
How to post the web

### ISSUE THREAD

**Issue by clarisavalen** [artf/grapesjs#182]
If you store it in local storage, would you able to post the web? And how you do that?

**Comment by bassouma21001** [comment]
I make it ;
i get html  and Css from string val then i use javascript to build new page html  like this 
(var htmlx = editor.getHtml; 
var cssx = editor.getCss;)
than 
concat = ("<html>+"<style>"+cssx+"</style>"+htmlx+"</html>")

**Comment by mhsdts** [comment]
lets say i created a template and stored it in local storage how can i preview only the created template without showing the grapejs editor lets say in another html page i want to see the only final template css and html

**Comment by artf** [comment]
@mhsdts store your templates remotely and fetch them from another page, otherwise, you can get HTML and CSS from the local storage and send them via ajax to your server but it doesn't make too much sense, just use the remote storage
