### ISSUE TITLE
[QUESTIONS]  How to apply the style changes to the ID instead of the class?

### ISSUE THREAD

**Issue by abozhinov** [artf/grapesjs#1821]
Hi, 
I have two elements with the same classes. I want to apply style changes with style manager to one of these two elements. I add ID but the style applies to the class not to the ID.

What can I do?

**Comment by arthuralmeidap** [comment]
At the Style Manager painel, you have a way to select/unselect to which css selectors (classes or id) 
you want to apply the styling. 

Click on a block and open the Style Manager panel. You will see all selectors applied to that block.

**Comment by abozhinov** [comment]
Thanks ... The UI is not user-friendly.

**Comment by artf** [comment]
@abozhinov 
> Thanks ... The UI is not user-friendly.

Suggestions are not prohibited...

**Comment by abozhinov** [comment]
@artf 
I think the problem is in the ICON. I edit the sources code and replace it with SVG also rewrite the style.
Do I have an option to replace the TEMPLATE for each section without editing the source code?
<img width="1132" alt="screenshot 2019-02-22 at 18 18 06" src="https://user-images.githubusercontent.com/1404839/53255476-5ba1bd00-36ce-11e9-8974-5e51abc03575.png">

The framework is great I really love it :)

**Comment by artf** [comment]
No, unfortunately, editing templates of the UI it's not yet possible but we hope to achieve it one day
