### ISSUE TITLE
[QUESTIONS] How to set different styles on one element for each device. (responsive)

### ISSUE THREAD

**Issue by abozhinov** [artf/grapesjs#1823]
@arthuralmeidap can you tell guide me how to set style different style for each device. 
I use the mobile-first strategy.

For example to set a different background on mobile and desktop devices.

mediaCondition: 'min-width',

var deviceManagerConfig = {
			devices: [
				{
					name: 'Desktop',
					width: '',
					widthMedia:'768px'
				},
				{
					name: 'Tablet',
					width: '768px',
					widthMedia:'320px'
				},
				{
					name: 'Mobile',
					width: '320px',
					widthMedia:'0px'
				}
			]
		};

**Comment by umerrinayat** [comment]
@abozhinov I'm facing the same issue. If you solved the issue? Can you share it here. Thanks

**Comment by theSC0RP** [comment]
@abozhinov @umerrinayat I am facing the same issue. If you have solved it, can you please share it here?

**Comment by abozhinov** [comment]
No I didn’t. Still search for solution.

**Comment by theSC0RP** [comment]
Alright. Thank you.

**Comment by padcom** [comment]
It's May 2023 - @abozhinov Did you find a solution for that?
