### ISSUE TITLE
[Question] How to add link to an image?

### ISSUE THREAD

**Issue by SeongwoonHong** [artf/grapesjs#1826]
Hi Artur,

![capture](https://user-images.githubusercontent.com/19713918/53278675-a4f70a00-36d8-11e9-8ae2-4fd22dcbf2a0.JPG)
How to add a link to this image?
If i need to create a custom component, please give me some example code Artur..

Thank you so much

**Comment by Shah-ali** [comment]
Drag a link block, Then drag an image block inside the link block.

**Comment by luvcharan** [comment]
Hi,  
Add link (href) to image in grapesjs .

First we add image in grapesjs and then add link to that image, its shows " Link " text next to that image, but i was unable to add link to that image. here i am adding screenshot below, can you please help me out 

![Screenshot from 2019-10-29 14-06-22](https://user-images.githubusercontent.com/17022456/67750508-5662f200-fa55-11e9-8dd4-80878ab7c96d.png)

**Comment by luvcharan** [comment]
Hi,  
Add link (href) to image in grapesjs .

First we add image in grapesjs and then add link to that image, its shows " Link " text next to that image, but i was unable to add link to that image. here i am adding screenshot below, can you please help me out


![screenshot_grapesjs_from_2019-10-29_14-06-22](https://user-images.githubusercontent.com/17022456/67751622-75628380-fa57-11e9-9341-447a2480412f.png)

**Comment by luvcharan** [comment]
Hi,  
Add link (href) to image in grapesjs .

First we add image in grapesjs and then add link to that image, its shows " Link " text next to that image, but i was unable to add link to that image. here i am adding screenshot below, can you please help me out

![grapesjsLinkIssue](https://user-images.githubusercontent.com/17022456/67752261-b313dc00-fa58-11e9-8643-f86a8b9bfe7d.png)

**Comment by artf** [comment]
@luvcharan you have to use "Link Block", not "Link"
