### ISSUE TITLE
[QUESTION] How to add a button in the section (block) on hover?

### ISSUE THREAD

**Issue by sanjib00** [artf/grapesjs#1827]
Hello @artf,
You are doing great work.
I tried to add a button in the section (block) on mouseover. Can you please help me to add or show "Add Column" button on hover?
I was following the issue #1789 

![hover_btn](https://user-images.githubusercontent.com/8086390/53349309-091f0580-3947-11e9-8629-21a1a67d5164.png)

**Comment by artf** [comment]
@sanjib00 I think this demo https://jsfiddle.net/xcv07abt/ is enough to understand what to do next
