### ISSUE TITLE
[Question] Add an additional text box for image upload modal?

### ISSUE THREAD

**Issue by SeongwoonHong** [artf/grapesjs#1828]
Hi Artur,
I'm wondering if that's possible to add some input boxes for image upload modal?
![capture](https://user-images.githubusercontent.com/19713918/53359191-35636380-3900-11e9-84b2-2c2242b6cb3b.JPG)
I'd like to add some boxes in the red area in the screenshot above.
Those boxes is intended for adding href for the image

**Comment by artf** [comment]
You can intercept the asset open command and then manipulate the DOM for your needs
```js
editor.on('run:open-assets', () => {
	const el = editor.Modal.getContent().querySelector('.gjs-am-assets-cont');
	...
})
```
