### ISSUE TITLE
[Bug]: StyleManager properties without "property" defined cause an error on component selection

### ISSUE THREAD

**Issue by skateborden** [artf/grapesjs#1830]
When using a StyleManager property where "property" is not defined, and defaults to '', I'm seeing an error on component selection: "TypeError: values[0] is undefined" at PropertyView.js targetUpdated -> getComputedValue-> camelCase.  I'm seeing this in my local project with v0.14.52.

jsfiddle: https://jsfiddle.net/okc9abez/7/

In my case this is a sub-property of a stack, where it wouldn't make sense for a property to be defined.

**Comment by artf** [comment]
> In my case this is a sub-property of a stack, where it wouldn't make sense for a property to be defined.

Yeah, it makes sense, but unfortunately, the `property` is kind of mandatory for the Style Manager, probably for now I'll just check the model on init and update `property` in case is empty (eg. by taking the `name` or `id`)
