### ISSUE TITLE
[Question] How to run command for a block component?

### ISSUE THREAD

**Issue by SeongwoonHong** [artf/grapesjs#1831]
```
editor.BlockManager.add('test', {
      label: 'test',
      category: 'Basic',
      command: () => {
        editor.runCommand('open-assets')
       }
    });
```
I'd like to do something like this.
so once a user drops the test component into the canvas, I'd like to open up asset manager modal where you can upload an image by running 'open-assets' command.

Thank you very much Artur

**Comment by NicoEngler** [comment]
To achieve this, you can listen to the drag event of the editor:

```
editor.on('block:drag:stop', component => {
    // identify your component and do something cool :)
});
```

**Comment by SeongwoonHong** [comment]
@NicoEngler Thank you for reply!
although, I'm wondering how to indentify my component.
I want to target link block component. so I did like this
```
editor.on('block:drag:stop', component => {
      if (component.is('link-block')) {
         console.log('here')
      }
    });
```
but didn't work..

**Comment by NicoEngler** [comment]
I´m afraid I can't assist further without playing around with the code myself. Though I can help debugging if you shoot up an example on codepen or similar.

**Comment by artf** [comment]
```js
editor.on('block:drag:stop', target => {
      if (target && target.getName() === 'Link') {
        editor.runCommand('open-assets', {
			target, // Not sure if the 'Link' is the correct target as it doesn't have `src`
			onSelect: () => editor.Modal.close(),
        });
      }
    });
```
