### ISSUE TITLE
Div not resizing automatically on resizing image when using flex

### ISSUE THREAD

**Issue by sakshigarg9** [artf/grapesjs#1832]
This is my code wherein I want the logo-image to be resizable. Also, I want a div element at the other extreme end so that the user may drag and drop the logo into that container. To have that arrangement, I'm using flex display with justify-content as space-between. But with flex the background doesn't resize automatically. If I remove the flex styling, then it works alright, but my div then is not visible inline in the extreme right corner, the way I want it to.

```
<div class="padding-left-small blue-background">
            <div class="@Html.RtlClassName() container">
              <div class="padding-bottom-small padding-top-small" style="display: flex; justify-content: space-between" >
                <a class="logo-image" style="">
                  <img data-gjs-type="image" data-gjs-draggable="div[class~='padding-bottom-small']" src="logo.png"></img>
                </a>
                <div style=" width: 61px; height: 61px;"></div>
              </div>
            </div>
          </div>
```

**Comment by NicoEngler** [comment]
This is most likely not a problem with grapejs but rather css. Could you set a up a demo?
