### ISSUE TITLE
Custom Resizer

### ISSUE THREAD

**Issue by sakshigarg9** [artf/grapesjs#1833]
I'm using the grapesjs-preset-webpage, how do i set the intial state of the properties under Resizer?

**Comment by NicoEngler** [comment]
I'd like to help but could not get my head around the problem. Could you be more precise on what you are trying to accomplish?

**Comment by sakshigarg9** [comment]
I wish to limit resizing an image upto a specific dimension and I also want to have a specified minimum dimension. Besides that, I want to enable only br (bottom-right) point in the image for resizing.

**Comment by artf** [comment]
https://github.com/artf/grapesjs/issues/1809#issuecomment-469027859
@sakshigarg9 avoid opening duplicates of your own issues, please...
