### ISSUE TITLE
[BUG]: background image for wrapper doesn't work if custom styling properties are selected

### ISSUE THREAD

**Issue by diktar** [artf/grapesjs#1834]
When editor is initialized with custom styling props defined for wrapper, background image is not set to wrapper. It is set correctly if editor is initialized with default configuration for wrapper.

Steps to reproduce:
1. open https://jsfiddle.net/gu289h0q/
2. select root element in editor
3. in Style Manager open 'Decorations' sector and try adding a background image

**Comment by artf** [comment]
@diktar you have to pass all the background properties to styleable
```js
'background',
      'background-color',
      'background-image',
      'background-repeat',
      'background-attachment',
      'background-position',
      'background-size'
```
probably it's not the cleanest way to customize stuff but for now I wouldn't spend time on this
