### ISSUE TITLE
How to open up 'Settings' all the time?

### ISSUE THREAD

**Issue by SeongwoonHong** [artf/grapesjs#1835]
![capture](https://user-images.githubusercontent.com/19713918/53430157-fd215b00-39bb-11e9-8a8d-9d875585df43.JPG)

I'd like make 'Settings' opened at all times by default without having users to open up manually.
How'd you do that?

Thank you..

**Comment by NicoEngler** [comment]
You can pass in the property **open** to your sector definiton.

```
sectors: [{
            name: 'Typografie',
            open: true,
            ...
}]
```

**Comment by SeongwoonHong** [comment]
@NicoEngler Hi, Thank you but
I'm not talking about sector (dimension, typografie etc). I'm talking about 'Settings'..

**Comment by NicoEngler** [comment]
From my understanding, this has been answered here: https://github.com/artf/grapesjs/issues/1675#issuecomment-449413972

**Comment by artf** [comment]
@SeongwoonHong That settings panel it's a custom element
https://github.com/artf/grapesjs/blob/6cb1199048a753a77466efd4ae8ff3752d413623/demo.html#L1409-L1430
I just append traits there, but the toggle (open/close) is actually a custom thing
