### ISSUE TITLE
How to add !important in all the generated apis

### ISSUE THREAD

**Issue by AkibDeraiya123** [artf/grapesjs#1836]
Hello @artf,

While i am going to edit some html from editor with the help of css then i need to add `!important` into all the css which is changed.

Let me give you an example,
This is previous css

```
.banner-title {
    background-color: #e6d8d8;
    border: 3px #acbe5a #b83dd3;
    color: #f80000;
}
```

Now i am going to change this font's color with `#000`.
then only this changed css need to be append with `!important`, So, new css will be get while i am going to fetch using `editor.getCss()` will be like,

```
.banner-title {
    background-color: #e6d8d8;
    border: 3px #acbe5a #b83dd3;
    color: #f000 !important;
}
```

Can i achieve this goal?

**Comment by NicoEngler** [comment]
I don't think you need to add **!important** because your element with the class **.banner-title** gets a unique class added holding the property that has changed.

So if you change the color, a new class is added with **color: #your-color** and thus the color defined in **.banner-title** is overwritten.

**Comment by AkibDeraiya123** [comment]
@NicoEngler ,
Thank you for your valuable response.
But thing is that i am loading one default template page with default css.
In this css we have css like
```
.banner-title {
    background-color: #e6d8d8;
    border: 3px #acbe5a #b83dd3;
    color: #f80000 !important;
}
```

Now when i am changing the color to `#000` using editor then the new css will be created like,
```
.banner-title {
    color: #000;
}
```

But thing is that default css have already `!important` so it will take the default template's css not the new one.

So, that's why i'm adding `!important` to new generated css by editor.

Let me know if you didn't got my point i can understand with more description.

**Comment by NicoEngler** [comment]
I think I get your point. The easiest option would be to remove the **!important** from the template. Either manually or as a preprocessing step before you add it to the editor.

**Comment by AkibDeraiya123** [comment]
Hey @NicoEngler ,
Thanks for your response.
But things is that i have also another properties like border, width, height, background-color etc.
If i will remove it from the default CSS then it will be affect on my layout and that i don't want.
Actually my CSS file is around 7000 lines. It will be more take time to fix it after removing `!important`.
So, i want to achieve this goal using grapes.js if possible.

I am sure i will get some positive response from @artf and help me to out of this deep.

**Comment by NicoEngler** [comment]
I may have found a solution for your problem. Please check https://github.com/artf/grapesjs/issues/1041#issuecomment-382545102

**Comment by AkibDeraiya123** [comment]
@NicoEngler 
Thank you for your response.
It's works for me.
You saved my lots of time.
Thank you 👍

**Comment by artf** [comment]
Thanks @NicoEngler for the help 👏
