### ISSUE TITLE
How to change the label of traits?

### ISSUE THREAD

**Issue by SeongwoonHong** [artf/grapesjs#1837]
I'd like change the labels of triats which are going to be french.

![capture](https://user-images.githubusercontent.com/19713918/53445691-1ee00980-39df-11e9-9047-7f9a8f8865de.JPG)

Could you give a piece of example code?
Thank you Artur

**Comment by NicoEngler** [comment]
You just need to define the label! :)

```
          traits: [{
            type: 'text',
            label: 'Title',
            name: 'title',
            placeholder: 'Lorem ipsum',
            changeProp: 1
          }]
```

**Comment by SeongwoonHong** [comment]
@NicoEngler Hi Thank you for reply!
but I'm trying to modify existing built in traits. i'm not trying to create custom traits..

**Comment by NicoEngler** [comment]
From what I have observed, you cannot define a label for the built in traits. Also the name (with uppercase(0)) is used if a label is undefined. That's why I guess your best bet is to define your traits along with proper label. Or better, write a PR for this. 👍 

I may be wrong on this, maybe Artur can eloborate further.

**Comment by artf** [comment]
Just extend the component (do it via plugins)
```js
editor.DomComponents.addType('link', {
	model: {
		defaults: {
			traits: [
                { type: 'text', label: 'My title', name: 'title' },
				{ type: 'text', label: 'My href', name: 'href' },
				{ 
					type: 'select', 
					label: 'My href', 
					name: 'href', 
					options: [
						{ value: '', name: 'This' }, 
						{ value: '_blank', name: 'New' }  
					] 
				},
			]
		}
	}
})
```

**Comment by SeongwoonHong** [comment]
> Just extend the component (do it via plugins)
> 
> ```js
> editor.DomComponents.addType('link', {
> 	model: {
> 		defaults: {
> 			traits: [
>                 { type: 'text', label: 'My title', name: 'title' },
> 				{ type: 'text', label: 'My href', name: 'href' },
> 				{ 
> 					type: 'select', 
> 					label: 'My href', 
> 					name: 'href', 
> 					options: [
> 						{ value: '', name: 'This' }, 
> 						{ value: '_blank', name: 'New' }  
> 					] 
> 				},
> 			]
> 		}
> 	}
> })
> ```

@artf , I tried above exactly but it does not work.. i also tried below but same.. does not work. any ideas?
```
const defaultType = editor.DomComponents.getType('default');
const defaultModel = defaultType.model;
editor.DomComponents.addType('link', {
      model: defaultModel.extend({
        defaults: Object.assign({}, defaultModel.prototype.defaults, {
          traits: [
            {
              type: 'text',
              label: 'My title',
              name: 'title'
            },
            {
              type: 'text',
              label: 'My href',
              name: 'href'
            },
            {
              type: 'select',
              label: 'My select',
              name: 'href',
              options: [
                {
                  value: '',
                  name: 'This'
                },
                {
                  value: '_blank',
                  name: 'New'
                }
              ]
            }
          ]
        })
      })
    });
```
