### ISSUE TITLE
Remove upload image option and disable (x) icon for default images

### ISSUE THREAD

**Issue by sakshigarg9** [artf/grapesjs#1844]
I want to remove the "Drop files here or click to upload" section and also disable the (x) cross icon next tothe default images, not allowing the user to delete default images.

@artf where do i change the css? I'm using the grapesjs-preset-webpage

_Originally posted by @sakshigarg9 in https://github.com/artf/grapesjs/issues/578#issuecomment-467823560_

**Comment by NicoEngler** [comment]
One easy way to achieve this would be adding some CSS rules:

`.gjs-am-file-uploader { display: none; }`
`.gjs-am-assets-cont { width: 100%; }`

And so on ... :)

**Comment by sakshigarg9** [comment]
Thanks worked! But I'm unable to remove the (x) icon next to the default images despite using 
`.gjs-am-close{ display: none; }`

**Comment by NicoEngler** [comment]
Great, just use that css rule to hide it.. :)

**Comment by sakshigarg9** [comment]
It won't work...

**Comment by NicoEngler** [comment]
I don't have a plain vanilla demo running. If you set one up, I can look into it.

**Comment by NicoEngler** [comment]
I had a chance to look a bit closer. Use this:

`.gjs-am-asset:hover .gjs-am-close {
    display: none;
}`

**Comment by sakshigarg9** [comment]
Worked like a charm!
