### ISSUE TITLE
Deleting a form input

### ISSUE THREAD

**Issue by kickbk** [artf/grapesjs#1845]
I think there are some bugs with the form inputs

It is not possible to delete a form input.
When you turn off "Show borders", you can then select the input and delete, but trying that again right after, again doesn't let you delete. It also makes the inputs un-selectable.
See below:

![grapesnodeleteforminput](https://user-images.githubusercontent.com/31323376/53656871-719d0980-3c09-11e9-8563-cd5415ecdc25.gif)

**Comment by artf** [comment]
Thanks for the report @kickbk this is already fixed by https://github.com/artf/grapesjs/pull/1800 and will be available in the next release
