### ISSUE TITLE
[Question] After page reload plus ("+") button not showing.

### ISSUE THREAD

**Issue by sanjib00** [artf/grapesjs#1848]
Hi @artf ,
When I drag the section block, a plus button is displaying. After save and reloading the page, "+" button not showing. I need to show the button after page reload also. Please suggest me, how can I solve this problem? 
Please check the [jsfiddle](https://jsfiddle.net/sanjib00/o3tvskyn/14/), similar scenario created.
![reload_issue](https://user-images.githubusercontent.com/8086390/53692556-59212080-3dbc-11e9-91f2-82610c788b3c.png)

**Comment by noogen** [comment]
@sanjib00 when you render fromElement, it's a content, not component.  e.g. "<section>" html would not automatically get recognize as component because you don't have any code to recognize it as so.

**Comment by artf** [comment]
@sanjib00 probably you're loading incorrectly your template data https://grapesjs.com/docs/modules/Storage.html#store-and-load-templates
