### ISSUE TITLE
[QUESTION] How to show blocks under different tabs

### ISSUE THREAD

**Issue by sunhillbd** [artf/grapesjs#1850]
Hello @artf ,
Hope you are doing fine. I was trying to show all the blocks under different tabs. For example: displaying sections, columns under Basic tab and other items under another tab named Elements. I have gone through the issue: https://github.com/artf/grapesjs/issues/499 but didn't find any final solution or didn't find any tab related stuff in the API. Any suggestion how can I achieve this? thanks

**Comment by artf** [comment]
Hi @sunhillbd I don't know exactly what is not clear in that issue but I think all you have to know is [here](https://github.com/artf/grapesjs/issues/499#issuecomment-343482511). With the [`BlockManager.render`](https://grapesjs.com/docs/api/block_manager.html#render) method you can control block listing, which logic/UI you'll use (select input, tabs, search, etc.) it's up to you
