### ISSUE TITLE
doesn't working with react js 

### ISSUE THREAD

**Issue by ramusesan** [artf/grapesjs#1852]
if any changes happened state/reducer then grapes js component doesn't re-rendering any help please

**Comment by arthuralmeidap** [comment]
Yeah, GrapesJS doesn't work like that. 

In this case you will need to get the reference and use the API provided by GrapesJS to handle the changes.

Take a look here: https://reactjs.org/docs/refs-and-the-dom.html

**Comment by ramusesan** [comment]
yup, it works... great when using ref to DOM and also handles the changes using grapes js' APIs
thank you @arthuralmeidap
