### ISSUE TITLE
Drag&Drop position

### ISSUE THREAD

**Issue by MisterFK** [artf/grapesjs#1853]
Hi,

I try to have the mouse position when i drag&drop a block. Is it possible to have the X position and Y position with this event or another ?
`editor.on('block:drag:stop', model => [...]);`

Thanks

**Comment by NicoEngler** [comment]
Hi, one attempt to solve this could be:

1. Find the iframe of the canvas
2. Find the mouse position inside the iframe

To do so, you could combine functions shared on StackOverflow.

The **first step** could be tackled with the function found right here:
https://stackoverflow.com/a/1452885/8658366

The **second step** could be tackled with the function found right here:
https://stackoverflow.com/a/7790764/8658366

I have combined those and set up a demo for you right here: https://jsfiddle.net/6f3rw4um/ Check the output of the console. 

Good luck

**Comment by MisterFK** [comment]
Thanks artf,

I already try to catch the onmouseup or onmousemove events on the iframe (and it's work) but when i drag&drop a block the event don't trigger (maybe because the mouse is on the block image)...
There is no event grapesjs to have the drop position (absolute position) ?

Thanks again !

**Comment by NicoEngler** [comment]
Well, first off I am not artf :) Second, set up a demo we can work on to solve your issue.

**Comment by artf** [comment]
@MisterFK https://grapesjs.com/docs/api/editor.html#available-events you can use `block:drag` where the mouse event is passed as a second argument

**Comment by MisterFK** [comment]
Hi,
I don't understand how can i put mouse event into the `block:drag` event... The first argument is the "Datatransfert" and the second is the "model".... Can you show me an example plz?

**Comment by artf** [comment]
> I don't understand how can i put mouse event into the block:drag event... The first argument is the "Datatransfert" and the second is the "model"

No @MisterFK... read carefully...
> block:drag - Dragging block, the block's model and the drag event are passed as arguments

The event is passed as a second argument
