### ISSUE TITLE
Asset manager empty on second open

### ISSUE THREAD

**Issue by NicoEngler** [artf/grapesjs#1854]
Hi, I am trying to build a plugin which sets up the asset manager as a SVG repository. If the user selects a SVG, the asset manager opens. Next, the user can replace the current SVG with the one selected. Most of the code I am using is found on: https://grapesjs.com/docs/modules/Assets.html#customization

**Demo:** https://jsfiddle.net/9vgf573s/12/

**Problem:**
1. Click the SVG, (asset manager opens)
2. Close the asset manager
3. Click the SVG again -> **asset manager is empty**

What am I doing wrong?

PS: Replacing does not seem to work either but I have not really looked into it because the current problem makes it annoying to debug.

Cheers

**Comment by noogen** [comment]
Line 28, you're filtering it twice since you're already doing it on line 23?  am.render(am.getAll().filter(assets));

Works when I'm doing it like so: am.render(assets);

**Comment by NicoEngler** [comment]
Awesome, thanks for the catch! @noogen
