### ISSUE TITLE
[Questions] getHtml grapesjs web builder

### ISSUE THREAD

**Issue by fmr411** [artf/grapesjs#1856]
I have a problem in getHtml. I add an icon in the button, in the web the icon is visible, and when in the inspect element there is an icon object, but when in getHtml it uses the editor.getHtml() function, the icon disappears.
Object icon
![6a9nc](https://user-images.githubusercontent.com/15244481/53781371-323d2880-3f3b-11e9-82a4-0f89ebffa162.png)

result `editor.getHtml()` :
![duzid](https://user-images.githubusercontent.com/15244481/53781398-4c770680-3f3b-11e9-88fb-1be3961807f3.png)

**Comment by artf** [comment]
`getHtml` is based on the component model data, you probably just changing its view data (eg. `this.$el.append('<i class="fa ...')`). Read carefully this part https://grapesjs.com/docs/modules/Components.html
