### ISSUE TITLE
Change an element type in editor

### ISSUE THREAD

**Issue by MisterFK** [artf/grapesjs#1859]
Hi,

In my javascript i already create 2 components (type "A" and type "B) with their own traits.
I create a context menu on both elements to switch (in the editor) the selected element from type "A" to type "B" and change the traits in consequence.

I didn't found the way to change the type of an element already insert in the editor.
Do you have a function or a solution plz?

Thanks artf !

**Comment by arthuralmeidap** [comment]
Take a look here: https://grapesjs.com/docs/modules/Traits.html#add-traits-to-components

It shows how to add/remove custom traits for existing types. It may help you

**Comment by MisterFK** [comment]
Thanks, but i don't want to change the type but i want to change the type of only one selected element...
If i change the traits of component, all the others elements with this type will be changed and it's not the purpose.

**Comment by artf** [comment]
> I didn't found the way to change the type of an element already insert in the editor.

The solution will be the same in case you would like to change a `<div>` with an `<img>`... so you remove it and replace it with another component at the same index
