### ISSUE TITLE
Custom block containing image. Why it is not recognized as an 'image' type?

### ISSUE THREAD

**Issue by NETCreator-US** [artf/grapesjs#186]
I am creating a new block containing an image:

```
    bm.add("thumbnail", {
        label: 'Custom Image',
        category: 'Media',
        content: `<img data-gjs-custom-name="Image" class="rounded" src="test.png">`
    });

```
Why it is not recognized as an `image` (type) as to be able to resize it and change the source using assets manager? How to solve this problem?

Thank you!

**Comment by artf** [comment]
I used your snippet directly in the demo and the image component was recognized as expected. Are you sure you're not overwriting `thumbnail` block somewhere else?

**Comment by NETCreator-US** [comment]
Thank you, @artf, for your answer! I am overriding the `image` component. I haven't redefined `is_component`, because I need the default `is_component`, and I thought if I don't override it, it will use the default. I just rewrite `is_component`, and seems to work.
