### ISSUE TITLE
Asset manager for buttons and text

### ISSUE THREAD

**Issue by sakshigarg9** [artf/grapesjs#1861]
Just like an image has an asset manager that can provide predefined alternatives for the image component, is it possible to implement a similar thing for buttons and text. Like providing alternative icons for the button component or alternative predefined text for the text component. For eg, in place of the "Show" button I wish to provide an alternative of choosing the eye icon (fa fa-eye) to the user. 
![show-button](https://user-images.githubusercontent.com/31568599/53858279-91fd0780-3fff-11e9-8387-ba3c2422906a.png) 
or for some text, i want to have some predefined text options avaiable for the user to choose from.

**Comment by artf** [comment]
@sakshigarg9 with custom [Components](https://grapesjs.com/docs/modules/Components.html) you can do whatever you want. Probably just take a look at how the image component is made (its [model](https://github.com/artf/grapesjs/blob/dev/src/dom_components/model/ComponentImage.js) and [view](https://github.com/artf/grapesjs/blob/dev/src/dom_components/view/ComponentImageView.js))
