### ISSUE TITLE
Reflect deleted components in block manager

### ISSUE THREAD

**Issue by sakshigarg9** [artf/grapesjs#1862]
How can I create dynamic components in block manager such that when a delete action is performed on a component it triggers the component to be placed in the block manager?

**Comment by arthuralmeidap** [comment]
Well, component and blocks are different concepts.  

If you are saying about blocks you can use the `.trigger('remove')` on the block that will remove it from the BlockManager

**Comment by artf** [comment]
@sakshigarg9 
1. Read the documentation https://grapesjs.com/docs
2. Try to understand what you're reading
3. Try to solve your issues by yourself
4. If you're not able to do it, then you can open an issue, by following its template, and **SHOW US** what you have tried to do

**Comment by sakshigarg9** [comment]
@artf thanks for all your patience, I'll do the same now onwards
