### ISSUE TITLE
[Bug]: Grapes change page position

### ISSUE THREAD

**Issue by Gianglo** [artf/grapesjs#1865]
Hello, 
I found the following problem using grapes inside an html page:
when you click on some elements of the editor, such as the arrow to move an element in the label manager, all the page shift up.

 The problem is also found in your JSFiddle Starter template https://jsfiddle.net/szLp8h4n.

![bug_grapes](https://user-images.githubusercontent.com/25904038/53885056-20cc4d00-401d-11e9-98fc-035e4c7032a5.gif)

**Comment by artf** [comment]
Ok, we use the [scrollIntoView](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView) API to center elements in the canvas (when you select the component in Layers) and layers (on component select in canvas) but seems like this bubbles up to the main window. By looking at https://stackoverflow.com/a/52835382 this configuration seems to fix the issue
```js
const editor = grapesjs.init({
	// ...
  	layerManager: {
  		scrollCanvas: { behavior: 'smooth', block: 'nearest' },
    	scrollLayers: { behavior: 'auto', block: 'nearest'},
  	},
});
```
I'll update the default values in the next release
