### ISSUE TITLE
[QUESTION] how to add extra field in input traits 

### ISSUE THREAD

**Issue by Ramkumar-Murugesan** [artf/grapesjs#1869]
Hi, 
I want to add the new field in default input traits. 
for example:- 
 i need to add {label: binding, name:binding} in already exist input traits

![image](https://user-images.githubusercontent.com/33427536/53938957-cba14180-40d7-11e9-9342-1fab368f9c44.png)

in the above image. i need to add the new field in between of name and placeholder.

can anyone please help me

Thanks in Advance

**Comment by arthuralmeidap** [comment]
In the docs, there is exactly an explanation about what you are looking for. 

Take a look here: https://grapesjs.com/docs/modules/Traits.html#add-traits-to-components

**Comment by Ramkumar-Murugesan** [comment]
I did this by using 

 this.editor.DomComponents.getType('input').model
            .prototype.defaults.traits.push({
                type: 'text',
                label: binding,
                name:binding

            });
and its working fine
