### ISSUE TITLE
[QUESTIONS] set data-gjs-type in tag i (Why iscomponent not working)

### ISSUE THREAD

**Issue by fmr411** [artf/grapesjs#1870]
when i add block(tag i), data-gjs type is "I" (there is no problem from the trait that I made)
![screenshot_5](https://user-images.githubusercontent.com/15244481/54005438-05338480-418c-11e9-89a6-639fcdcce03d.png)
i'm have trait
![screenshot_7](https://user-images.githubusercontent.com/15244481/54005451-0f558300-418c-11e9-9d69-508a4f5f859d.png)
but if save and reload, data-gjs type to be "default" (trait doesn't work)
![screenshot_6](https://user-images.githubusercontent.com/15244481/54005462-1a101800-418c-11e9-8f2d-7c679943b0da.png)
Thank's

**Comment by artf** [comment]
You store/load incorrectly, read here please https://grapesjs.com/docs/modules/Storage.html#store-and-load-templates
