### ISSUE TITLE
Grid Component Resize  Its cells width not works

### ISSUE THREAD

**Issue by alialrabi** [artf/grapesjs#1873]
Hi artf,
 i have a question when  i implement  grid component having row and  three cells  , i want to make these  cells resiazable on width and height , So i make an event when component selected set it resizable =true , 
when resize cells height it works  , but the cells width not affect yet when resize it , how i can make cells resizable.
this is my code :

     blockmanager.add('my-grid', {
    label: 'Grid',
    category: 'Basic',
    content: '<div title= "grid" class="row" style="height:50px; border-width:0px"><div class="cell"></div><div class="cell"></div><div class="cell"></div></div>',
    attributes: {class:'gjs-fonts gjs-f-b3 gjs-block gjs-one-bg gjs-four-color-h'},
    style:{
        'width': '33vw',
    }  });

and the event is  : 

      editor.on('component:selected', function (args) {
        args.attributes.resizable = true;

    });

**Comment by artf** [comment]
This is because the grid uses flex so you should use `flex-basis` for the width. In that case `resizable` should be an object like this `{ keyWidth: 'flex-basis' }`
