### ISSUE TITLE
[QUESTION] export to pdf

### ISSUE THREAD

**Issue by VardanNersesyan** [artf/grapesjs#1876]
Hi all, 
1) Can I use this framework for generate pdf file after editing html page? And how can I do it?
2) Can I make ready templates and provide it for editing by user via framework? And how can I do it?

Tnx.

**Comment by artf** [comment]
> Can I use this framework for generate pdf file after editing html page? And how can I do it?

There is no built-in command to generate PDF for you but you can get the HTML code of the template and generate the PDF from it

> Can I make ready templates and provide it for editing by user via framework? And how can I do it?

Sure, I recommend to start reading from the [Getting started](https://grapesjs.com/docs/getting-started.html) and then checking [Storage Manager](https://grapesjs.com/docs/modules/Storage.html)
