### ISSUE TITLE
[FEATURE REQUEST] Custom styles that add/remove custom classes?

### ISSUE THREAD

**Issue by jwilson-lyonscg** [artf/grapesjs#1877]
Currently, all the style manager values that you change for an element simply update a <style> tag inline in the HTML. Is it possible to change this behavior so that changing the CSS values adds or removes custom classes to the element?

A good reason for this is Bootstrap 4. 99% of Bootstrap customization involves simply adding classes to the element to alter various things like margins, padding, display values, etc.

Is it possible to do this? If not is this a valid feature request?

**Comment by artf** [comment]
It's already possible with Classes section (you can remove/toggle/update them)
![Schermata 2019-03-21 alle 13 33 00](https://user-images.githubusercontent.com/11614725/54752332-0037f180-4bde-11e9-9abb-451369e3c5f8.png)

**Comment by jwilson-lyonscg** [comment]
Have you considered that the potential target audience for such a tool (think eCommerce merchandisers) has no idea what "classes" are in HTML and would be able to greatly benefit from having simple dropdown menus to choose from predefined settings?

**Comment by artf** [comment]
> Have you considered that the potential target audience for such a tool (think eCommerce merchandisers) has no idea what "classes" are in HTML and would be able to greatly benefit from having simple dropdown menus to choose from predefined settings?

Yeah sure, indeed I've planned to make this part less "class-oriented" but for any solution I'll take it will be always too much opinionated, so I think it'd be better creating your own solution by looking at the [Selectors API](https://grapesjs.com/docs/api/selector_manager.html) and make a UI (select, tags, etc.) which fits better your needs
