### ISSUE TITLE
[Question] Traits manager - image type field.

### ISSUE THREAD

**Issue by lyczos** [artf/grapesjs#1879]
Hello,
I want to add a new field in traits manager (components settings). This field should select an image from the assets manager and retrieve back URL link to the image)after selecting an image from assets).
I just want to ask is there any smilar built-in solution in current GrapesJS version?

**Comment by artf** [comment]
> I just want to ask is there any smilar built-in solution in current GrapesJS version?

Unfortunately no, maybe one day we'll create a common module for UI elements but currently, there is no one, so you have to create a new custom trait.
