### ISSUE TITLE
Positioning Rich Text Editor where rte.selection() is located

### ISSUE THREAD

**Issue by mjshalash** [artf/grapesjs#1884]
I would like to be able to position the Rich Text Editor toolbar right above the text a user highlights inside of a div/textarea/etc.  The reason for this is when the text sections are too large and the top nor the bottom of the component is visible then it would be convenient for the user to just see the toolbar appear wherever they select text.  

Is this possible or am I understanding the RTE incorrectly?

Thank you in advance for your help!

**Comment by artf** [comment]
It's a bit out of the scope for the RTE and, personally, I don't plan to invest time on this
