### ISSUE TITLE
How to append a child component at required position/index

### ISSUE THREAD

**Issue by Nagavijay-kolla** [artf/grapesjs#1889]
For example, 
I have a parent component and this parent component has 4 child components. Here with trait functionality, I want to move the 3rd child component to 1st position likewise.

I am able to move a component from any position to last by removing it from the existing position using **component.remove()** and adding it to parent using **component.append(ref of removecomponent)** . So it is moving to last.

Now I want to move a child component from one place to another place on trait value change

Can you give me any idea?

Thanks in Advance.

**Comment by artf** [comment]
Use `at`, as an index, in options, eg. `component.append(comp, { at: 0 })` will place the `comp` as a first element
