### ISSUE TITLE
[Question] Flexbox column is not working correctly.

### ISSUE THREAD

**Issue by sanjib00** [artf/grapesjs#1892]
Hi @artf ,

We are using flexbox block. The problem is, when we are trying to resize the middle column it affects all other columns, like automatically reducing the width of left column. It should affect the right column only. 

To create this scenario please add three columns and try to resize the middle one (https://codepen.io/sanjib00/pen/wOpVNv).  

Can you give some hints how can we solve this problem?

[](url)
![Flexbox_issue](https://user-images.githubusercontent.com/8086390/54337389-f734a680-4658-11e9-9041-28a2393ba853.png)

**Comment by artf** [comment]
This is how the flexbox is supposed to work when you resize a middle column. What you're trying to achieve is a bit different and would require another kind of implementation, so I'd suggest to create your grid components
