### ISSUE TITLE
[Question] view vs code

### ISSUE THREAD

**Issue by sandromattei** [artf/grapesjs#1897]
Hello...and sorry for my english!
First of all, congratulations for this fantastic framework.
I'm trying to use GrapeJS to create my own wordpress editor and I have a doubt.
If in my code I use a wordpress "shortcode", how can I preview this shortcode in grapeJS but leaving the html code unchanged?
thanks a lot

**Comment by artf** [comment]
I don't know what kind of API WordPress allows you to use for shortcodes but if it's possible I'd render them and put inside the editor as blocks

**Comment by sandromattei** [comment]
sorry, maybe I explained myself wrongly. I would like to insert a shortcode in the code (eg [my shortcode param1 = value1 param2 = value2 /] and render an html output instead [eg <div class = "param1" id = "param2"> <dev>]

**Comment by artf** [comment]
Well if you need to do that on runtime you should create a custom component which on render makes an async call to Wordpress to ask to render that shortcode (again, I know nothing about WP API so I'm not sure if it's possible)
