### ISSUE TITLE
some bug in grapedrop

### ISSUE THREAD

**Issue by foolsopts** [artf/grapesjs#1898]
Step to produce
1. drag image-block to canvas and select background.
2. drag icon to canvas.
3. click on image-block and go to background style tab click on background and click image button.
4. when modal shown click on any image (not double click) then close modal.
5. Now look at the icon in canvas you cannot change it to another icon.
6. double click on image-block again and change to another image.
7. and now icon back to work again.

**Comment by artf** [comment]
You're right, weird issue, I'll check it later.
I'm gonna close it as is part of the Grapedrop product and not the grapesjs core, btw thanks for the report
