### ISSUE TITLE
React with GrapeJS- without plugin

### ISSUE THREAD

**Issue by prgmono2018** [artf/grapesjs#1899]
Hi,
How can I use grapesjs with react?
I don't want to use the  plugin- I have made some changes and I want to use the editor with react and other pages.
how can I do it? 

Thanks you vaety much!

**Comment by simplecommerce** [comment]
Not sure what you mean by without plugin.

But if you are talking about just the GrapesJS instance, you just need to initialize it in `componentDidMount`.

So for example:

In your render
```
render() {
  return <div id="gjs"></div>
}
```

In componentDidMount
```
const editor = grapesjs.init({
  // Indicate where to init the editor. You can also pass an HTMLElement
  container: '#gjs',
});
```

Something like that, normally it should work.

**Comment by artf** [comment]
Nothing to add beyond what already said by @simplecommerce
