### ISSUE TITLE
State drop down menu text

### ISSUE THREAD

**Issue by 2braincells2go** [artf/grapesjs#19]
I have spent little time trying to solve the issue without luck, so not much help:)

The issue is text within the state drop down menu is invisible.  Have tracked it to following CSS:

```
.wte-clm-tags .wte-clm-field select, .wte-clm-tags .wte-sm-field select, .wte-sm-sector .wte-clm-field select, .wte-sm-sector .wte-sm-field select {
    background: 0 0;
    border: none;
    color: transparent;
    width: 100%;
    padding: 2px 10px 2px 0;
    text-shadow: 0 0 0 rgba(255,255,255,.7);
    position: relative;
    z-index: 1;
    -webkit-appearance: none;
    -moz-appearance: none;
    appearance: none;
}
```
![image](https://cloud.githubusercontent.com/assets/2567500/18029246/76108772-6c58-11e6-8c57-807260374c03.png)

Seems the "color:transparent" is causing issue but changing to <#color> did not solve. Wish I could be more help...

Using Chrome latest if that helps.

Woody

**Comment by artf** [comment]
Hi Woody,
that trick with transparent color was there to solve annoying outline in Firefox but seems like it's causing problems on Windows (on Mac in Chrome it's ok).
I'll let you know you when I done with it

**Comment by 2braincells2go** [comment]
Don't you just love all the browser quirks:)

No big issue, just thought you may like to know about.

Thanks much!

**Comment by artf** [comment]
`Don't you just love all the browser quirks:)`
Sure, the world would be too much boring without :)

Anyway, hope to solved your issue with this 05aee801a26387ff514eded93633cbfa535e9d7c
Try the demo and let me know, unfortunately can't test it on my own

**Comment by 2braincells2go** [comment]
Tried on Chrome and Edge, no change, still invisible until hoovered.

Sorry...

**Comment by 2braincells2go** [comment]
I forgot to add:

When disabling the color in chrome dev console the word "state" turns black and then the other items in drop down are visible (black):

.gjs-clm-tags .gjs-clm-field select, .gjs-clm-tags .gjs-sm-field select, .gjs-sm-sector .gjs-clm-field select, .gjs-sm-sector .gjs-sm-field select {
    background: 0 0;
    border: none;
    /* color: rgba(255,255,255,.7); */ <= disabled
    width: 100%;
    padding: 2px 10px 2px 2px;
    position: relative;
    z-index: 1;
    -webkit-appearance: none;
    -moz-appearance: none;
    appearance: none;
}

**Comment by artf** [comment]
Ok, thanks Woody.
Seems like <option> tags inherits the `color` but not the `background`...

Does `background` value is actually `0 0`?? 
If so, seems not to be correct, try to change it and see if it fixes.

Otherwise, try to add this rule:
```css
#gjs-clm-states > option {
  background-color: #444;
}
```
And let me know 
Thanks

**Comment by 2braincells2go** [comment]
Hey Art!

Going to be a few days before back and can actually try changes on my setup but using your demo thsis is what I see (notice the changes I made in dev console).

HOW IT APPEARS WITH NO MODS:
![image](https://cloud.githubusercontent.com/assets/2567500/18136103/cc05e51e-6f69-11e6-9287-76580bab899c.png)

HOW IT APPEARS BY REMOVING BACKGROUND 0 0:
![image](https://cloud.githubusercontent.com/assets/2567500/18136154/ef991dfc-6f69-11e6-984e-896db1832877.png)

HOW IT APPEARS BY ADDING BG COLOR #444:
![image](https://cloud.githubusercontent.com/assets/2567500/18136193/0fc2a490-6f6a-11e6-86f2-ec5aea44b5c6.png)

Hope this helps:)

**Comment by artf** [comment]
Thanks Woody, very exhaustive elucidation.
I'll ping you back as soon as possible, lately I have less time to work on it

**Comment by 2braincells2go** [comment]
Don't worry about it Art. No biggie for me, just alert you to issue:)

**Comment by artf** [comment]
Demo updated, let me know Woody :)

**Comment by WebCrew** [comment]
It seems, that Woody has no time to answer so I will do it. I tested Your demo and nothing has changed. I use latest Chrome Browser and the drop down menu still looks like:

![76108772-6c58-11e6-8c57-807260374c03](https://cloud.githubusercontent.com/assets/12986067/19021180/3f5181ac-88bc-11e6-93be-ff51d6f583f4.png)

**Comment by artf** [comment]
thanks @WebCrew I forced `<option>` bg color now, does it change?

**Comment by WebCrew** [comment]
@artf You did it :+1: it is working now and all the dropdown entries are visible.

**Comment by 2braincells2go** [comment]
@WebCrew Sometimes bad things happen to good people. Have been out of touch due to death of a parent. This was the last thing on mind.

@artf Just tried the demo and seems like you have solved the issue. The text in drop is visible. Thank you!

**Comment by WebCrew** [comment]
@2braincells2go I`m sorry for You.

**Comment by artf** [comment]
My deepest condolences @2braincells2go 
I had bad period too, but not so bad.

**Comment by 2braincells2go** [comment]
Thank you @artf and @WebCrew 

Appreciate the words.
