### ISSUE TITLE
Creating custom block with custom style. The style does not appear in Style Manager

### ISSUE THREAD

**Issue by NETCreator-US** [artf/grapesjs#190]
If I am trying to create a custom block, with a custom style, as below, the style does not appear in Style Manager (padding-top shows 0), and if I try to edit it, using keyboard (to set it to zero) it does not make any changes. I can only make it zero, by setting another integer value, and then back to 0.

```
    bm.add("thumbnail", {
        label: 'Example',
        category: 'Media',
        content: `<div style="padding-top: 10px;">TEST</div>`
    });

```

How can I solve this problem? Thanks!

**Comment by artf** [comment]
Sorry @NETCreator-US but as #186 I can't reproduce your issue, do you use the last version?

**Comment by NETCreator-US** [comment]
Thank you, @artf for your message! I have updated GrapesJS from 0.9.7 to the latest version, and it is working now.
