### ISSUE TITLE
[QUESTIONS] Set border weight at hover

### ISSUE THREAD

**Issue by fmr411** [artf/grapesjs#1901]
Is it possible to change the weight of border when hover, I have searched for the ".gjs-hovered" class in the css file but did not find it, I have also tried using setStyle "editor.setStyle('.gjs-hovered{outline:"4px solid #3b97e3 !important;"}');" but still nothing has changed, Thank's
![Screenshot_8](https://user-images.githubusercontent.com/15244481/54507006-d11d4800-4971-11e9-9da0-a97a086eadb6.png)

**Comment by artf** [comment]
You don't need to use `editor.setStyle` if you need to customize the UI of the editor, just include this CSS after the GrapesJS one
```css
.gjs-cv-canvas .gjs-highlighter {
    outline-width: 3px;
}
```

**Comment by fmr411** [comment]
Thank you @artf, it worked, but if I want to change the border when drag and drop, which class should I change, I have tried changing class `.gjs-comp-selected-parent` but didn't work
![ss baru 1](https://user-images.githubusercontent.com/15244481/54894234-3631ea00-4eec-11e9-99e2-a26bb836bcb2.png)
`style`
![ss baru 2](https://user-images.githubusercontent.com/15244481/54894261-56fa3f80-4eec-11e9-8949-66d91fb3769d.png)
