### ISSUE TITLE
[QUESTIONS] Disable/change build-in components behavior

### ISSUE THREAD

**Issue by JoeriAben** [artf/grapesjs#1902]
Hey, 

Trying to get GrapesJs work for a project I'm currently working on. But is there a way to disable the built-in components that convert `div` & `span` into editable components (or change the isComponent so I can add a class/data flag). Because I don't want all div's & span's editable only the ones I say need to be editable with a data-gjs flag.

Hopefully, someone can point me in the right direction.

Kind regards,

Joeri

**Comment by simplecommerce** [comment]
@JoeriAben did you try this? https://grapesjs.com/docs/modules/Components.html#improvement-over-addtype

**Comment by artf** [comment]
Create a custom `text-editable` component by extending the `text` one. Then extend the `text` component by setting `editable` to `false`.
Now in your template use `data-gjs-type="text-editable"`
