### ISSUE TITLE
[QUESTION]: Drag and drop external html to editor ?

### ISSUE THREAD

**Issue by u-ashikov** [artf/grapesjs#1907]
I have created a component which is **heading** and a block element for it. I have set the draggable property to be **section** html element. If I try to drag and drop external heading html element to the editor, it is dropped, but if I try to drag and drop the **heading** block element (which I have defined in the editor), it is not allowed to drop if it is outside the **section**. Should it work this way, or it is a **bug** ?

**Comment by artf** [comment]
>  I have set the draggable property to be section html element.

>  it is not allowed to drop if it is outside the section. Should it work this way, or it is a bug ?

Well, if you set `draggable: 'section'` it means you can drag that heading component only inside sections... so it works as expected...
