### ISSUE TITLE
[Bug] Change default font size unit to EM instead of REM.

### ISSUE THREAD

**Issue by lyczos** [artf/grapesjs#1914]
Now in GrapesJS editor, we have some of font sizes in `REM`. I think they should be in `EM` unit because if we want to embed editor in the existing page there may be some issues with proper font size - in case when the parent font size is set to other then default size (ex. `:root { font-size: 10px }`). 
https://i.imgur.com/Vzoa5y9.png

**Comment by artf** [comment]
Yeah, I think you're right, would you like to create a PR?

**Comment by lyczos** [comment]
Yep, sure, I will do it later :)
