### ISSUE TITLE
[QUESTION] How to change the dragging nature?

### ISSUE THREAD

**Issue by sunhillbd** [artf/grapesjs#1916]
Hi,
We have been working with GrapesJs for sometime. I know you have already been asked about the designer mode (Free drag) and you said it was on the roadmap. What I want to ask is, do you have any rough guideline on how we can achieve the free drag? Should we go for integrating any 3rd party library or plugin?
thank you.

**Comment by artf** [comment]
Take a look here please https://github.com/artf/grapesjs/issues/1890 for now I can't add more about this topic
