### ISSUE TITLE
[QUESTIONS] Icons on Block Manager

### ISSUE THREAD

**Issue by trafalmejo** [artf/grapesjs#1917]
Hi,
I want to change the icon of a Block in the Block Manager: I know it is part of the attributes in the manner:
    attributes: { class:'gjs-fonts gjs-f-b1' }
and the class defines the icon to be used. Where is the list of icons?
I didn't find it in the documentation: [Block Manager](https://grapesjs.com/docs/modules/Blocks.html).

Thanks!

**Comment by artf** [comment]
There is no list of icons, we used fontawesome and some custom one but we're planning to remove them from the core
