### ISSUE TITLE
How can we load the edits in another html page without rendering the editor itself

### ISSUE THREAD

**Issue by mhsdts** [artf/grapesjs#192]
I want to load the edits made in the editor in a separate html after I stored them remotely,
Can you can walk me through this? or point me to documentation on how can I achieve this?

Thank you.

**Comment by artf** [comment]
[Here](https://github.com/artf/grapesjs/wiki#storeload-data) you can find more about storage options. Basically, all you need is the HTML and CSS stored remotely by the editor and then you can wrap and render those contents in another page.
