### ISSUE TITLE
Image/Video resizing - Not working from all the sides

### ISSUE THREAD

**Issue by Nagavijay-kolla** [artf/grapesjs#1921]
Hi @artf ,

I am trying to resize the image/Video, When I drag in/out from the right side it is working fine but when I drag it using left side buttons it is resizing from the right side. What I suppose to say is the video/ image is sticking to the left side and it is not shrinking from the left side.

I have used the option **component.set("resizable", true);**  it is not working as expected. Please give me some ideas on this.

Thank in advance.

**Comment by artf** [comment]
This is how the default static positioning works in HTML...
