### ISSUE TITLE
[Question] Create dropdown menu inside options panel

### ISSUE THREAD

**Issue by Aleksandrov91** [artf/grapesjs#1924]
I'm trying to create **dropdown** menu (like the device selection menu) inside options panel. In the documentation is described how can create panels and buttons only.  How to do that?

![dropdown-menu](https://user-images.githubusercontent.com/21690902/55012454-1f74bb80-4ff0-11e9-9639-64a110fb6dd1.JPG)

**Comment by artf** [comment]
It was created by its own [view](https://github.com/artf/grapesjs/blob/dev/src/device_manager/view/DevicesView.js) so nothing special, there is no API to create select inputs, do them as you wish with your framework of choice then on change just bind your actions

**Comment by Soharab-Shaikh** [comment]
@artf  Could you please help me to add select input(dropdown) inside  the device panel?

**Comment by alimurad52** [comment]
@artf can you provide an example of this?

**Comment by artf** [comment]
As already mentioned, there is no API for creating inputs, so create your input/select, move it in any panel you need and then bind something to do on `change`

I'm talking about pure JS, GrapesJS has nothing to do here...
