### ISSUE TITLE
[QUESTIONS] Edit Placeholder on keyup in Trait

### ISSUE THREAD

**Issue by fmr411** [artf/grapesjs#1926]
How so that `Placeholders` can change when typing a word in the trait `directly`, current placeholders can change only when mouseover

I have a `trait` like this, is there anything that isn't right? Thank you  :
![Screenshot_12](https://user-images.githubusercontent.com/15244481/55048108-9efa9d00-5079-11e9-8a49-2be5d1e21c4c.png)

**Comment by artf** [comment]
I think you might need to create a new [trait type](https://grapesjs.com/docs/modules/Traits.html) for a custom behavior
