### ISSUE TITLE
[QUESTIONS] Sender.set('active') error Maximum call stack size exceeded

### ISSUE THREAD

**Issue by edward1893** [artf/grapesjs#1927]
I have a button with the `show-left` command, I want to make when the button is clicked a second time (or more) remains `active`, but when running `Sender.set ('active')` in the` stop` function, there is a loop on `stop` so that an error appears `Maximum call stack size exceeded` 

`First click`
![Screenshot_10](https://user-images.githubusercontent.com/48974803/55055621-22c28280-5096-11e9-83a5-82a43bde9e82.png)
`Second click`
![Screenshot_11](https://user-images.githubusercontent.com/48974803/55055655-3c63ca00-5096-11e9-8361-71ab6a659690.png)

`My Commands`
![Screenshot_13](https://user-images.githubusercontent.com/48974803/55055670-4685c880-5096-11e9-8883-c42fe0aab642.png)

**Comment by artf** [comment]
Create a reproducible demo, please

**Comment by edward1893** [comment]
I have 3 buttons, I want when the button is clicked for the second time (or more), the button remains active, for example, when first clicking on the layer, the layer button becomes active, if clicked again the layer button will remain active
`my button`
![Screenshot_1](https://user-images.githubusercontent.com/48974803/55300066-09d41b80-5460-11e9-99de-33efe170e7bf.png)
`at the moment my button when active and then clicked will change deactive`
![hover2](https://user-images.githubusercontent.com/48974803/55300081-1b1d2800-5460-11e9-8727-e5931039a3ec.gif)

**Comment by artf** [comment]
use `togglable: false` instead of `togglable: true`
