### ISSUE TITLE
[QUESTIONS] Change the Onclick event to Hover when select objects

### ISSUE THREAD

**Issue by Ericson1991** [artf/grapesjs#1928]
Can I change the `onclick` event to `hover` when select objects and display a toolbar?

![hover](https://user-images.githubusercontent.com/48981140/55063030-bd788c80-50a9-11e9-8041-5ed0fca2a19b.gif)

**Comment by artf** [comment]
You might need to extend the [SelectComponent](https://github.com/artf/grapesjs/blob/dev/src/commands/view/SelectComponent.js) command (take a look at toggleSelectComponent method)

**Comment by afdallah** [comment]
@artf Is there any example on how to extend the SelectComponent?

**Comment by artf** [comment]
mmm not really, I hope to publish soon a general doc about Commands.
BTW it's just about getting the command (https://grapesjs.com/docs/api/commands.html#get) and overwriting its method
```js
const myCommand = commands.get('select-comp');
myCommand.someMethod = function() {
	// ...
};
```

**Comment by afdallah** [comment]
I see, thanks for your answer. 👍
