### ISSUE TITLE
Loads asset manager, but assets not working

### ISSUE THREAD

**Issue by sakshigarg9** [artf/grapesjs#1929]
I'm using the pencil icon to trigger the asset manager. The triggering works fine but when I click on any of the images, no change is reflected in my image component. It shows me the existing photo even if I select a different image.

```
 domc.addType("image", {
    model: {
      initToolbar() {
        typeImage.prototype.initToolbar.apply(this, arguments);
        const tb = this.get("toolbar");
        const tbExists = tb.some(item => item.command === "open-assets");

        if (!tbExists) {
          tb.unshift({
            command: "open-assets",
            label: toolbarIcon
          });
          this.set("toolbar", tb);
        }
      },
      }
    }
  });
```

**Comment by prashant2018** [comment]
Click on the image you want to be replaced, in developer console write the following code snippet:
```
editor.runCommand('open-assets', {
    target: editor.getSelected()
});
```
You will see the selected image gets changed. The key here is **target: editor.getSelected()** , the selected image is treated as the target for the new image to take it's place. You need to trigger the about code when the pencil icon is clicked.

**Comment by artf** [comment]
```js
tb.unshift({
	command: editor => editor.runCommand('open-assets', {
    	target: editor.getSelected(),
	}),
    label: toolbarIcon
});
```
