### ISSUE TITLE
[QUESTIONS] change 2 attributes with 1 trait

### ISSUE THREAD

**Issue by rikoyudiansyah1** [artf/grapesjs#1930]
I have an input trait, I want to change the 2 attributes (name and type) on the selected input element, on canvas is appropriate, but in the final html(editor.getHtml()) it doesn't work, I've read `https://grapesjs.com/docs/modules/Components.html#define-new-component` but I didn't find a solution, Thank's 
![Screenshot_2](https://user-images.githubusercontent.com/48851039/55144166-c8e3ba80-5172-11e9-9872-e4381ed505c2.png)

**Comment by artf** [comment]
You should change the model and not the view element `this.model.setAttributes({ 'data-attr': 'value' })`
