### ISSUE TITLE
Render without iframe

### ISSUE THREAD

**Issue by Fi1osof** [artf/grapesjs#1933]
## You're submitting a FEATURE REQUEST

Good day!

Can you create CANVAS view with render without iframe? For render editor directly into some HTML-node.

**Comment by artf** [comment]
> Can you create CANVAS view with render without iframe?

No, iframes allow us to keep CSS isolated and trigger media queries, there is no reason for us to find a way to not using them

> For render editor directly into some HTML-node.

Just render the editor result

**Comment by Lakshit-Singhal** [comment]
> It's a pity. I partially redid it without a frame, but did not fully achieve the result. In the case of a frame, the rendering of the react components breaks down. I had to write my own component. But now with component rendering everything is OK. https://youtu.be/N3AVCJllXgc

@Fi1osof 
Could you please give some example on how we can render react components inside the editor. And also if we can have a them as a block and drag and drop them to the editor.

**Comment by Fi1osof** [comment]
@Lakshit-Singhal, you may use [official react example](https://reactjs.org/docs/integrating-with-other-libraries.html#embedding-react-in-a-backbone-view).
But if you render more that one component in different backbones view, you have not one react root node. This causes a lot of problems.

**Comment by Lakshit-Singhal** [comment]
> @Lakshit-Singhal, you may use [official react example](https://reactjs.org/docs/integrating-with-other-libraries.html#embedding-react-in-a-backbone-view).
> But if you render more that one component in different backbones view, you have not one react root node. This causes a lot of problems.

@Fi1osof, Thanks, I really appreciate your quick response.
So is there an alternative approach if we want to render multiple react components within the editor ?

**Comment by Fi1osof** [comment]
@Lakshit-Singhal 

> So is there an alternative approach if we want to render multiple react components within the editor ?
I dont know. I abandoned this idea and wrote my own editor.
