### ISSUE TITLE
Adding multiple plugins together 

### ISSUE THREAD

**Issue by Amir2828** [artf/grapesjs#1935]
Hello all,

I have encountered a problem when trying to add 2 plugins together for example:
grapesjs-preset-webpage and grapesjs-plugin-ckeditor.
I downloaded both via npm, imported them and added to the plugin field at grapesjs.init.

this.editor = grapesjs.init({
 plugins: [ckEditorPlugin,grapesjsPreset], ... })

For some reason ckeditor is not recognized and there is no sign for him.
Any ideas will be appreciated.

**Comment by artf** [comment]
add CKEditor library...
