### ISSUE TITLE
Customising close preview button and adjusting views container width

### ISSUE THREAD

**Issue by Josephaberry54** [artf/grapesjs#1937]
Is there a way to use a custom button for the close preview button? I can style it using css but wondered if there was something more direct in the api

Also I cant find a way to set the width of the views container when using an asset manager. Cant be dragged wider by user and cant find anything in the api to do with styling

Thanks

**Comment by artf** [comment]
You can update or completely replace the preview [command](https://grapesjs.com/docs/api/commands.html)
