### ISSUE TITLE
[QUESTION] what would be the best way to store the template dynamically

### ISSUE THREAD

**Issue by CharlesBilbo** [artf/grapesjs#1938]
I'm looking to store data dynamically though a id that is called in, at the moment I'm loading in templates dynamically but cant seem to figure out a way to store them. 
below is a rough idea but something along those lines , any help is appreciated. 
````
 storageManager: {
        type: 'remote',
       if(id){
        urlStore: 'save + id',
     }
       urlStore: 'save',
        success: true/false,
        params: { },   // For custom values on requests
        headers: {},
    },
````

**Comment by artf** [comment]
`editor.StorageManager.getConfig().urlStore = 'save/' + id;`
