### ISSUE TITLE
Table and Div with Grapesjs

### ISSUE THREAD

**Issue by minuwan** [artf/grapesjs#1939]
I need to place a "Div with some texts"  inside a table's "tbody". I managed to trag and drop it. But when I saved it and load it again the div goes back to before the table tag. I belive this is happens in the blocks/compents coded to not allow any other elemenet to go inside. Is there any way to overcome this ?

PS: I'm using that Div to generate a loop in the final generated html code.

```
// Before saved
<table>
    <thead>
        <tr>
            <th>Column 1</th>
            <th>Column 2</th>
        </tr>
    </thead>
    <tbody>
        <div>loop_start</div> <-------- THESE (Orignal position)
        <tr>
            <td>Column 1</td>
            <td>Column 2</td>
        </tr>
        <div>loop_end</div> <-------- THESE (Orignal position)
    </tbody>
</table>
```

```
// After saved
<div>loop_start</div> <-------- MOVED TO HERE
<div>loop_end</div>   <-------- MOVED TO HERE
<table>
    <thead>
        <tr>
            <th>Column 1</th>
            <th>Column 2</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>Column 1</td>
            <td>Column 2</td>
        </tr>
    </tbody>
</table>
```

**Comment by artf** [comment]
> I need to place a "Div with some texts" inside a table's "tbody".

You can't because it's against HTML5. Inside `tbody` you can only place `tr`
