### ISSUE TITLE
[QUESTION] Add custom font

### ISSUE THREAD

**Issue by ankitjainOfficial** [artf/grapesjs#1940]
Hello,

I went through, the following GitHub issues: #857 #1622 #1215 

Almost all of the issues, though a little different, provide a way to add font family to the list.

Most common way to tackle, as far as I've understood:

```
let styleManager = this.editor.StyleManager;
let typographySector = styleManager.getSector('Typography');
let fontProperty = styleManager.getProperty('Typography', 'font-family');

... Add fonts then
```

```
const styleManager = editor.StyleManager;
const fontProperty = styleManager.getProperty('Typography', 'font-family');

... Add fonts then
```

For both of this, I'm getting the `typographySector` and `fontProperty` as undefined. I don't know, if I'm doing something incorrect or, if I'm incorrectly implementing them.

Here's my snippet, of what I'm trying.

```
editor.on('load', () => {
      const styleManager = editor.StyleManager;
      const fontProperty = styleManager.getProperty('Typography', 'font-family');
      const typographySector = styleManager.getSector('Typography');
      console.log({fontProperty, typographySector}); // both are returned undefined
})
```

Thanks for putting your time on this.

**Comment by artf** [comment]
Try using this `editor.StyleManager.getProperty('typography', 'font-family')`

**Comment by ankitjainOfficial** [comment]
@artf Thanks for the tip, but this also doesnt seem to work.

```
editor.on('load', (loadedEditor) => {
      // const styleManager = editor.StyleManager;
      // let typographySector = styleManager.getSector('Typography');
      const fontProperty = editor.StyleManager.getProperty('Typography', 'font-family');
      console.log({ fontProperty });
      const loadedFontProperty = loadedEditor.StyleManager.getProperty('Typography', 'font-family');
      console.log({ loadedEditor, loadedFontProperty });
```


`fontProperty` and `loadedFontProperty` are still null.

**Comment by workadev** [comment]
Hi @ankitjainOfficial, I'm new to this so can you please help me how to add some Google fonts in detail? Thanks in advance.
