### ISSUE TITLE
Document lack

### ISSUE THREAD

**Issue by starcraft0429** [artf/grapesjs#1943]
Thank for this awesome module.
But Document of this module is very lack.

In one word, This doc is only for who knows grapes.js instance already.

Pls write PRO document.

**Comment by artf** [comment]
The documentation is always in developing, but please be more specific on what/where you see a lack... eg. [Getting started](https://grapesjs.com/docs/getting-started.html) should introduce you to many aspects of the editor

**Comment by starcraft0429** [comment]
I already passed Getting Started Document.
But in order to go deep development, guide doesn't give enough info. e.g API document too.

**Comment by artf** [comment]
> But in order to go deep development, guide doesn't give enough info. e.g API document too.

Can you be more specific? 
What would you like to see in the documentation? 
What are the questions arose after reading the Getting Started?!

**Comment by starcraft0429** [comment]
for example https://grapesjs.com/docs/api/style_manager.html#addtype
I wanna add new property of style.
but I have no idea with this doc.
There is no info about Model and View.
What is it
