### ISSUE TITLE
Adding a toolbar button in custom place

### ISSUE THREAD

**Issue by mailtopaul8** [artf/grapesjs#1945]
Hi,

I added a new tool  for adding new sections in the toolbar but I need to place that alone at the bottom of the section (as per attached screenshot). Can you please let us know how to achieve this?

Thanks.
![new_section](https://user-images.githubusercontent.com/46489615/55621819-2a7fd680-57bc-11e9-88b3-5284bdbc5c52.png)

**Comment by artf** [comment]
Please, avoid duplicate content https://github.com/artf/grapesjs/issues/791#issuecomment-481660537
