### ISSUE TITLE
Hi, I am trying to deploy grapesjs to heroku. I successfully deployed it. But I can't find the app in home page. It says application error.

### ISSUE THREAD

**Issue by rajesh1285** [artf/grapesjs#1946]
Hi,
I am trying to deploy grapesjs to heroku. I successfully deployed it. But I can't find the app in home page. It says application error.

**Comment by rajesh1285** [comment]
Hi,
I am trying to deploy grapesjs to heroku. I successfully deployed it. But I can't find the app in home page. It says application error.
what config is required for index.html ?

thanks

**Comment by artf** [comment]
GrapesJS is not an application, is a framework, so you have to build your index.html https://grapesjs.com/docs/
