### ISSUE TITLE
How do I reference external CSS in blockManager instead of adding each and every style in body of index.html?

### ISSUE THREAD

**Issue by cpcashion** [artf/grapesjs#195]
@artf 

Let's say I'm adding a new custom block called 'big-hero', and I want the custom HTML that I'm adding to that new block to reference an entire stylesheet instead of having to add each individual style in the `<body>`. How does one accomplish that? Where does one add an external stylesheet?

![image](https://user-images.githubusercontent.com/5933214/28637571-df9b7ab8-71f6-11e7-993a-efb34381d5a7.png)

**Comment by artf** [comment]
For block specific styles I'd recommend just using `style` tag
```js
content: `
<section class="big-hero">...</section>
<style>
  .big-hero{...} ....
</style>
`,
```
If you want to preload external stylesheet inside the canvas
```js
var editor = grapesjs.init({
  ...
  canvas: {
    styles: [
      'https://...',
      ...
    ]
  }
});
```

**Comment by charlieshum1** [comment]
> For block specific styles I'd recommend just using `style` tag
> 
> ```js
> content: `
> <section class="big-hero">...</section>
> <style>
>   .big-hero{...} ....
> </style>
> `,
> ```
> 
> If you want to preload external stylesheet inside the canvas
> 
> ```js
> var editor = grapesjs.init({
>   ...
>   canvas: {
>     styles: [
>       'https://...',
>       ...
>     ]
>   }
> });
> ```

Hi @artf 

When using <style> tag to define styles inside the 'content', after the block is dropped on the canvas, the css rules of the block overrides those of the elements that already in the canvas with the same selector. 
For example, if the block has the following rules
`.class1{
     color: #fff;
}`
After the block is added, the other elements not inside the block that also has the 'class1' will also have the color changed to white

Even after I removed the newly added block, the new styles still exists 



Any quick way to limit the scope of the block CSS to that particular block only? 
Or I need to update every selectors to prevent this happening?
