### ISSUE TITLE
Is there a way to convert gjs-components to gjs-html?

### ISSUE THREAD

**Issue by momu-2016** [artf/grapesjs#1950]
In my opinion, this is two different ways of storing the same data,Now I have a need to convert gjs-components to gjs-html，Is there such a method?

Looking forward to your reply, I wish the project better and better!

**Comment by artf** [comment]
> Is there such a method?

Not really, but actually it would be the same as initializing the editor with components (gjs-components) and then getting the code via `editor.getHtml()` (gjs-html)
