### ISSUE TITLE
[QUESTIONS] change or add event on add component from block

### ISSUE THREAD

**Issue by fmr411** [artf/grapesjs#1951]
is it possible ?, change the drag and drop event to on click when adding a new component, I want to add components by clicking the block then it will be added directly to the selected component, Thank's
![baru](https://user-images.githubusercontent.com/15244481/55772491-9f9e2500-5ab6-11e9-925e-4341bcf355e7.gif)

**Comment by artf** [comment]
Not really, but I was already thinking about this possibility, so probably I'll add it in the next release. 
I'd ask what would you expect in case of your gif? On click, the block should be added inside the cell?

**Comment by fmr411** [comment]
Yes, I want when I click, the block is added to the cell, but can I know where the function handles the event to add the block?

**Comment by artf** [comment]
https://github.com/artf/grapesjs/blob/dev/src/block_manager/view/BlockView.js#L7-L8

**Comment by fmr411** [comment]
Thank you @artf , I have succeeded in adding the onclick event, but I have another problem when dragging and dropping blocks into the canvas

can I find out where the function is, when a new component is added (when the drop block), on my canvas, there is content img, I want to delete it when adding a new component.

![neww](https://user-images.githubusercontent.com/15244481/56336451-a4578d00-61ca-11e9-8d10-1231c5c215fa.gif)
