### ISSUE TITLE
[QUESTIONS] render without iframe or get global styles and scritps

### ISSUE THREAD

**Issue by krubenrc** [artf/grapesjs#1953]
Hello, I am trying to integrate grapesjs in prestashop, but due to the iframe, I do not get the global css or js.

I tried to enter the css and js manually, but the prestashop js gives errors when I add it.

Is there a way to not use the iframe?
Or that has global access to styles and js?

a greeting.

**Comment by artf** [comment]
```js
var editor = grapesjs.init({
  ...
  canvas: {
    styles: ['...style1.css'],
	scripts: ['...script1.js'],
  },
});
```

**Comment by krubenrc** [comment]
Already tried with it, and dont work. Js from prestashop not work inside the iframe, and because that i need render out of iframe.

**Comment by artf** [comment]
> Js from prestashop not work inside the iframe, and because that i need render out of iframe.

Open the console and check for errors, probably you're passing a wrong path or you need other js from prestashop
