### ISSUE TITLE
[QUESTIONS] Creating image map on canvas

### ISSUE THREAD

**Issue by sdrebel** [artf/grapesjs#1954]
Hi,
Is there anyway to create image map like functionality on canvas. User should be able to select particular area for linking.  Example the way it's done in this below link.
https://www.jqueryscript.net/demo/Easy-Imagemap-Generator-With-jQuery-hotArea-js/

I have tried creating link like below but this doesn't give flexibility to move around all the places. 
 
var bm = editor.BlockManager;
  bm.add('link-block3', {
        category: 'Basic',
        label: 'Link Block3',
        attributes: { class: 'fa fa-link' },
        content: {
            type: 'link',
           droppable: true,
            draggable: true,
            resizable: true,
            attributes: { class: 'fa fa-link' },
            style: {
                display: 'inline-block',
                padding: '5px',
                'min-height': '50px',
                'min-width': '50px'
            }
        },
    });

canvas:dragover will trigger only when blocks are dragged inside the canvas. Is there any solutions or events which I can trigger to select the canvas?

**Comment by artf** [comment]
With a [custom component](https://grapesjs.com/docs/modules/Components.html) you should be able to create whatever you want
