### ISSUE TITLE
Resizing images with non corner points resizes both width and height.

### ISSUE THREAD

**Issue by EJM5** [artf/grapesjs#1955]
This bug can be reproduced in either GrapesJS demos.

**Bug:**
After dragging and dropping an image, using one of the resize points that are not on the corners (height or width resize points), both height and width will be resized.

**Expected behaviour:**
The non corner points should only resize the height or the width of the image, depending on which point is being used.

**Additional note:**
If you use one of the corner points at least once, the other non-corner points will have the correct resize behaviour, resizing only width or height depending on which point you are using.

**Steps for reproduction:**
1- Drag and drop an image.
2- Use one of the resize points that is not one of the corner points.
_Optional:_
3- Use one of the corner points at least once.
4- Reuse one of the resize points that are not on the corner, and you will find it having the expected behaviour.

**Comment by artf** [comment]
This is not a bug, this is just the autoscaling handled by the browser, if you don't like it you can think about extending the image component to store size information on load
