### ISSUE TITLE
[Question] Edit innerHTML in a custom button

### ISSUE THREAD

**Issue by trafalmejo** [artf/grapesjs#1959]
Hi All,

I am trying to change the text in a button component, but I am not able to edit it. I added this type:
```
comps.addType('button', {
  // Define the Model
  model: defaultModel.extend({
    // Extend default properties
    defaults: Object.assign({}, defaultModel.prototype.defaults, {
    	style: {
    		width: '130px',
    		height: '50px',
    	},
      // Can't drop other elements inside it
      droppable: false,
      resizable: true,
      editable: true,
      }),
  },
```
I included the editable: true parameter but is not working
And add the button to the Component Manager
```
 editor.BlockManager.add('button', {
 	label: 'Button',
 	attributes: { class:'gjs-fonts gjs-f-b1'},
 	category: 'Basic',
 	content: '<button type="button">Click Me!</button>'
 })
```

Is there any way to workaround this?
Thanks!

**Comment by simplecommerce** [comment]
@trafalmejo Try looking at the way they implement the link component, I think it might help you, not 100% sure though.

**Comment by artf** [comment]
You should extend the `text` component
