### ISSUE TITLE
How to modify the src and minify to a .min.js

### ISSUE THREAD

**Issue by blackbirdzzz** [artf/grapesjs#196]
Hi i'm actually modifing everything in my .min.js but every variable is renamed and i want to know a technique to modify everything and get a clear code, i'm new in js if you can tell me a tutorial to get everything with npm with no problem, cause i got some error using npm

**Comment by rgcarrasqueira** [comment]
My advice to you is install it as a NodeJS project and build the min.js from there. It is more safe and more productive.

**Comment by artf** [comment]
As @rgcarrasqueira suggested just install and build it via nodejs
Here is the Development steps from the README

Clone the repository and install all the necessary dependencies
```sh
$ git clone https://github.com/artf/grapesjs.git
$ cd grapesjs
$ npm i
```

Start the dev server (visit the printed url, eg. http://localhost:8080). When you update files, inside the `src/` folder, the server will automatically reload the page

```sh
$ npm start
```

When you're ready, build the source, you'll find the output minified file(s) in the `dist/` folder

```sh
$ npm run build
```
