### ISSUE TITLE
[QUESTION] Dynamic class generation with a template

### ISSUE THREAD

**Issue by davydav** [artf/grapesjs#1960]
Hi there ! 

I am wondering if there is a way to force the dynamic class generation (of the form `cXXXXX` which happens when I drag'n'drop a component) at template import ? 
The problem is, when I use a template, the generated components in the editor don't have that dynamic class, which I need to be able to generate media queries while editing in the phone/tablet modes.
For reference, here is the template I am importing : 
https://gist.github.com/davydav/2413f5fdaa154a80dfa49a633bd247bb

Thanks a lot for your awesome work ! 

![Screenshot 2019-04-10 at 16 08 33](https://user-images.githubusercontent.com/272360/55885905-0dc41400-5bab-11e9-9adf-4e952715aaf4.png)

**Comment by artf** [comment]
Hi Davy, if you need a class you can set it already in your template, if you need a dynamic one, probably you would make use of [events](https://grapesjs.com/docs/api/editor.html#available-events) like `component:add` or `block:drag:stop`

**Comment by davydav** [comment]
Thank you for your answer ! Is there anyway to access your method of class generation, or could you point me to where it is in your code ? I've been trying to find it but no luck !
Thanks again

**Comment by artf** [comment]
https://github.com/artf/grapesjs/blob/5fe64423b2a4c94f5b3cd9b7b8e1d887a8896ab0/src/dom_components/model/Components.js#L70-L87

As you see it's called on add, so you can actually disable it (`forceClass` option) and implement your own logic
