### ISSUE TITLE
Some user return

### ISSUE THREAD

**Issue by micker** [artf/grapesjs#1961]
Hello i try to use grapesjs like an enduser to builde a page some returns : 
- how to select row to change width when we use column blocks ? its realy difficult to use ....
- i create a box + text it realy strange impossible to change height of box it always 75px ... realy strange
- how to create a 4 columns elements ?
thanks for your freat component its realy impressive

**Comment by artf** [comment]
> how to select row to change width when we use column blocks ? its realy difficult to use ....

You can change the row width in Style Manager (Dimension sector)

> i create a box + text it realy strange impossible to change height of box it always 75px ... realy strange

Check always the value in the Style Manager

> how to create a 4 columns elements ?

just clone the selected column

**Comment by micker** [comment]
ok thanks i will try !
