### ISSUE TITLE
Custom content type

### ISSUE THREAD

**Issue by vinayakprabhu** [artf/grapesjs#1965]
@artf  Instead of using plugins js files, can we create our own content using html as I have done below. Is it a correct way to do it? 
```js      blockManager:
 {
        appendTo: '#blocks',
        blocks: [
          {
            id: 'text',
            label: 'List',
            attributes: {class: 'fa fa-list-alt'},
            content: '<div data-gjs-type="text" data-highlightable="1"><ul><li>List 1</li><li>List 2</li><li>List 3</li></ul></div>',
            activate: true,
            category: 'Standard UI Elements'
          },
```

Sorry for the formatting unable to format..
Thanks in advance.

**Comment by artf** [comment]
> Is it a correct way to do it?

yes...

**Comment by vinayak99999** [comment]
Thank you for your reply @artf . I just have one more query I want to have an vertical carousel. So from the above code snippet where do I add say Jquery or script for delay or scroll effect

**Comment by artf** [comment]
Create a new [component type](https://grapesjs.com/docs/modules/Components.html) and follow this guide: https://grapesjs.com/docs/modules/Components-js.html
