### ISSUE TITLE
[QUESTION] Loop over all components

### ISSUE THREAD

**Issue by trafalmejo** [artf/grapesjs#1966]
Hi all,

I want to create a socket for every button that I add to the canvas. This is working just fine. However, when I reload (using storage), I have to look for my components of type "Button" and reopen the sockets. Is it a way to loop over the components?

Best,

**Comment by artf** [comment]
Hi @trafalmejo in case you need to iterate component's first level children you can do this:
```js
yourComponent.components().forEach(component => {
 if (component.is('COMPONENT-ID')) {
  // do something
 }
})
```
If you need to lookup ALL inner children, use `onAll`
```js
yourComponent.onAll(component => {
 if (component.is('COMPONENT-ID')) {
  // do something
 }
})
```
Once the component is rendered you can also make use of `find` method and pass any query selector string
```js
yourComponent.find(`[data-gjs-type=COMPONENT-ID]`).forEach(component => {
 // do something
})
```

**Comment by trafalmejo** [comment]
Perfect! Highly appreciated.
