### ISSUE TITLE
Get information on action that was undone

### ISSUE THREAD

**Issue by sakshigarg9** [artf/grapesjs#1968]
Is it possible to extract information on what was undone.
I tried 

```
const um=editor.UndoManager;
um.getStack();

```
but I'm unable to fetch information on exactly what was undone, the value of `after `property under `model.attributes` is null. I wish to extract the id of the element that action was performed on and what update in style/removal/property/edit was made.

**Comment by artf** [comment]
Check `model.attributes.type` to understand the action executed, probably the `after` is null because the action was `remove`
