### ISSUE TITLE
Rename attributes (Editor)

### ISSUE THREAD

**Issue by minuwan** [artf/grapesjs#1969]
Is there any way to rename "data-gjs-" attributes to "data-myOwnProjectName-"? 

For example:

- "data-gjs-type" => "data-myOwnProjectName-type"
- "data-gjs-droppable" => "data-myOwnProjectName-droppable"
etc...

**Comment by artf** [comment]
No, currently it's hardcoded https://github.com/artf/grapesjs/blob/5fe64423b2a4c94f5b3cd9b7b8e1d887a8896ab0/src/parser/model/ParserHtml.js#L4
