### ISSUE TITLE
Background opacity slider

### ISSUE THREAD

**Issue by acamenhas** [artf/grapesjs#1972]
Hi all,

A quick question: i'm using the 1.8.3 grapes version.

It's easy to implement the background opacity slider?

Thanks!

**Comment by artf** [comment]
> i'm using the 1.8.3 grapes version

??? https://github.com/artf/grapesjs/releases/tag/v0.14.57 is currently the latest

> It's easy to implement the background opacity slider?

You can set the alpha on the background color, there is no kind of `background only opacity` in HTML/CSS
