### ISSUE TITLE
[QA]: Can you drag elements to specified subcontainers of custom components

### ISSUE THREAD

**Issue by xuxiaozhou** [artf/grapesjs#1973]
> Thank you for the great open source project.

- I'm working on a web drag-and-drop site project
- **I have a requirement to drag the react component into the specified location sub-container of another component**.
- A component may have several sub-containers in different locations
- Previous I use  https://github.com/SortableJS/Sortable
- My boss must use your open source project to implement custom drag-and-drop stations

**Comment by xuxiaozhou** [comment]
> Part of the reason I feel I'm going to be fired is because of this open source project. The task is to transform this project into a plug-in that supports various JS frameworks, such as react, vue, angular and other syntax implementations, and can nest multiple plug-ins.

**Comment by artf** [comment]
About integrating react components start by reading this #170 You have to create your own render logic
