### ISSUE TITLE
[QUESTION] gjs-component is not updated with my traits values

### ISSUE THREAD

**Issue by Ramkumar-Murugesan** [artf/grapesjs#1977]
Hi, have I modified my HTML using the toHTML function in traits. An HTML element is updated but the gjs-component is not updated still it shows the old code.

my traits are

```
 toHTML: function () {
          const html = this.view.el.innerHTML;
          const name = this.get('traits').where({ name: 'name' })[0].get('value');
          const value = this.get('traits').where({ name: 'value' })[0].get('value');
          let renderHtml = `<input type="radio" `;
          if (name) {
            renderHtml += ` name="${name}" `;
          }
          if (value) {
            renderHtml += ` value="${value}" `;
          }
          renderHtml += `class="radio"/>`;
          return renderHtml;
        }
```
but its shows older code like type="radio" is not stored in gjs-component after i loaded my saved screens

before saving the screen

![image](https://user-images.githubusercontent.com/33427536/56748889-457fae00-679e-11e9-995a-8f70ec2f303b.png)

after saved and load into grapesjs using 

editor.setComponents(JSON.parse(existScreenDetail[0]['gjs-components']));

but its 

![image](https://user-images.githubusercontent.com/33427536/56748999-7f50b480-679e-11e9-8a57-1ad59c313d51.png)

can any please help me.

**Comment by artf** [comment]
I barely understand you here... please provide a reproducible demo
