### ISSUE TITLE
[Bug]: Styles allways applied to classes

### ISSUE THREAD

**Issue by 3dmedium** [artf/grapesjs#1978]
Hello,

I have a Problem with styling individual Items.

The following html Code:
```html
<div class="ddm-flex-cols">
      <div class="ddm-flex-cols-element">
          This is some Text
        </div>
      <div id="icbp" class="ddm-flex-cols-element">
        Text
      </div>
    </div>
    
<style>


.ddm-flex-cols {
    display: flex;
    flex-direction: row;
    margin: -16px;
    padding: 16px 0px;
    flex-wrap: wrap;
}


.ddm-flex-cols-element {
    flex-grow: 2;
    margin: 16px;
    flex-shrink: 0;
    flex-basis: 0;
}

#icbp {
	max-width:300px;
}
</style>
```

Loads fine. But when I Click the Component with "#icbp" then the class .ddm-flex-cols-element will get the style max-width.
Setting this.el.style while rendering the Object is also Integrated to the CSS (Id only) the Docs tell changes to this.el will not being saved to Components.

Reproduction with DEMO is not possible for me because its only happening with some loaded canvas styles. I'm using version 0.14.57
My Config for reproduction:
```typescript
let options = {
    container: '#gjs-content-editor',
    protectedCss: '',
    style: '',
    canvas: { styles: ['/some/file.css'] },
  };
```

**Comment by artf** [comment]
Can you please try to add this to your options `avoidInlineStyle: true` and let me know

**Comment by 3dmedium** [comment]
Hi @artf ,
Yes I tried this, still no luck.
I had the time to minimize this issue to a codesandbox:

[https://codesandbox.io/embed/jnplq7op55](https://codesandbox.io/embed/jnplq7op55)

Position of the protectedCss Content can be varied put it to style or in a file and load it by cvanvas.style the behavior keeps the same.

The Issue is gone by deactivationg selectors before adding components:
```javascript
editor.on('selector:add', selector => selector.set({ 
	active: false, // disable the selector
	// or
	private: true, // hide the selector
}));
```
from #1979 (both versions work)
for me this is a solutuion but I think in some cases it might not.

Best regards

**Comment by artf** [comment]
Ok, the problem happens here: https://github.com/artf/grapesjs/blob/dev/src/style_manager/index.js#L284-L285

if there is no CSS rule with the selector found on the component (in our case `ddm-flex-cols-element`) the rule is created and all its styles are moved to the rule. I think I made it for the optimization reason but now not quite sure if it's a right approach...
