### ISSUE TITLE
[FEATURE REQUESTS]: StyleManager Option for Editing single Elements allways

### ISSUE THREAD

**Issue by 3dmedium** [artf/grapesjs#1979]
I'm using this great Library for Editing only Parts of Pages.
I mainly design Compontens ready to use on the Page and when using the style Manager it allways should only take effect to only the selected Elements, not its classes.

So at the Moment I allways have to deselect calsses and edit. 
Is it possible to add an Option so Style Manager will allways use the ID for generating CSS?

**Comment by artf** [comment]
You can make use of `selector:add` event
```js
editor.on('selector:add', selector => selector.set({ 
	active: false, // disable the selector
	// or
	private: true, // hide the selector
}));
```

**Comment by 3dmedium** [comment]
Thanks for the Solution.
This is rather easy.
