### ISSUE TITLE
[Sugestion] Drag and drop images outside browser directly to GrapesJs

### ISSUE THREAD

**Issue by rgcarrasqueira** [artf/grapesjs#198]
A good feature that could be awesome is the ability to drag images outside browser, as desktop for example and drop it inside the canvas area and automatically fire the upload backend (if it is active) and place it on design canvas. It will be awesome!

CKEditor has this feature, and I think it could be great to have it portable to grapesjs also!

**Comment by artf** [comment]
👍  Like it, added to the Roadmap, thanks

**Comment by rgcarrasqueira** [comment]
Art, it is not working well :-(

![kapture 2017-08-10 at 16 53 10](https://user-images.githubusercontent.com/97540/29189558-5bbf53e2-7ded-11e7-88cf-3a2c85e0d772.gif)

**Comment by artf** [comment]
I don't get if it's uploading the image or not

**Comment by rgcarrasqueira** [comment]
Art,

It is uploading, but not placing the image inside the editor.



Rogério Carrasqueira




2017-08-10 17:12 GMT-03:00 Artur Arseniev <notifications@github.com>:

**Comment by artf** [comment]
Actually, I've not implemented what you're asking. At the moment I just upload images dragged inside the editor and show them by opening the asset manager (more options here https://github.com/artf/grapesjs/blob/dev/src/asset_manager/config/config.js). I'll check if it's possible what you're asking.
ps. what do you expect if you drag multiple images?

**Comment by rgcarrasqueira** [comment]
Hey Art!

I think that the correct dynamic is select a component and drag images to
there. If the user drop more than one image, the asset window can open and
select just one or place all images and the user can adjust using the
current flow. But I think that it is important to drag and place the images
at canvas. It will be very appreciated.

Thanks!



Rogério Carrasqueira




2017-08-11 8:53 GMT-03:00 Artur Arseniev <notifications@github.com>:
