### ISSUE TITLE
[BUG]: RTE Editor not scrolling

### ISSUE THREAD

**Issue by 3dmedium** [artf/grapesjs#1980]
The Toolbar of the RTE Editor is not visible vor Text field higher than the Browserwindow. While scrolling to the middle the RTE Toolbar is not visible.
![grapes](https://user-images.githubusercontent.com/18495706/56764192-74991e00-67a4-11e9-98f5-1d11b405dc9f.gif)

The Toolbar is on top or on the bottom.
It should be sticking somewhere it keeps visible. Perhaps it is better to stick it to the top / top frame border.

This is also the case for the CKE Plugin.

**Comment by artf** [comment]
Yeah, we should replicate the behavior of the component toolbar
