### ISSUE TITLE
[QUESTION] Modals open once

### ISSUE THREAD

**Issue by trafalmejo** [artf/grapesjs#1981]
Hi all,

I am using the plugins 'gjs-preset-webpage', and 'grapesjs-custom-code'. I have noticed that the import modal and the custom-code modal are opening just once. I have tried last versions for Mozilla and Chrome but this is not solving the issue. Once they open and close once, I am not able to open them again. I am not getting any console error either.

**Comment by artf** [comment]
Thanks for the report, this is actually due to the breaking change in https://github.com/artf/grapesjs/releases/tag/v0.14.55 I didn't manage well the state of those commands, I'll try to release soon the patch for both

**Comment by artf** [comment]
Fixed released
https://github.com/artf/grapesjs-preset-webpage/releases/tag/v0.1.11
https://github.com/artf/grapesjs-custom-code/releases/tag/v0.1.2
