### ISSUE TITLE
[QUESTIONS] addcomponent after the selected component

### ISSUE THREAD

**Issue by fmr411** [artf/grapesjs#1982]
how do I make it possible to add new components after the component I selected, at this time I use `editor.DomComponents.addComponent (block);` , but new components are added at the end, not after the selected component, Thank you

**Comment by fmr411** [comment]
clear, I use index
![Screenshot_1](https://user-images.githubusercontent.com/15244481/56844718-2b99b480-68df-11e9-93fc-87bb1abf558b.png)

**Comment by artf** [comment]
You can also use this to get the index of the component `index = editor.getSelected().index()`
