### ISSUE TITLE
Support extending grapesjs

### ISSUE THREAD

**Issue by rodenp** [artf/grapesjs#1983]
Hi Arthur,
I am not on twitter and am wondering what the best way is of contacting you to discuss a piece of work i have.

Since you know grapesjs so well, I was wondering whether you would be interested in helping me develop something for grapesjs and what the costs would be.

My idea would not only help me, but would also make grapesjs much more appealing to others too.

Regards
Peter

**Comment by artf** [comment]
You can try to post your job offer here https://discordapp.com/channels/365099684114464769/404263782559514624
