### ISSUE TITLE
Getting issue while click on edit option of image

### ISSUE THREAD

**Issue by AkibDeraiya123** [artf/grapesjs#1984]
Hey @artf ,
I see version release 0.14.57. In this version, you support to the image editor using this lib `grapesjs-tui-image-editor.min.js?0.1.2`.

Previously, I used cropper.js for image editing. But it was not properly working fine. I see demo for image editing using `grapesjs-tui-image-editor.min.js?0.1.2` it's working very very fine.

I implemented it, but when I clicked on any default images, I am getting this kind of issue,

![error-in-edit-default-image](https://user-images.githubusercontent.com/25474716/56813825-72de6180-685b-11e9-8d0e-c9d90c31431a.png)

It'll not work in local? Do I need to use this functionality with any domain?

**Comment by artf** [comment]
Please check the README file https://github.com/artf/grapesjs-tui-image-editor
I mention this issue in the `icons` option and the example shows you exactly what to do
