### ISSUE TITLE
[BUG] Autosave with remote storage doesn't send network requests

### ISSUE THREAD

**Issue by DylanSp** [artf/grapesjs#1985]
OS: Windows 10
Browser: Chrome 73
GrapesJS version: `0.14.57`

I have remote storage configured using this call to `grapesjs.init()`:

```
const editor = grapesjs.init({
        container: editorRef.current,

        storageManager: {
            autosave: true,
            type: "remote",
            urlStore: "/store",
            urlLoad: "/load"
        }
    });
```

While I see the request to `/load` fire in the Network tab of Chrome's dev tools, I don't see any requests to `/store`, no matter how many changes I make in the editor. Is there a configuration option I'm missing, or something simple like that? I'm using Grapes inside React, using create-react-app; could that cause an issue?

I can replicate this [on CodeSandbox](https://codesandbox.io/s/j4xkz244zv?fontsize=14).

**Comment by DylanSp** [comment]
I should also note that manually saving with `editor.store()` *does* send a request that I can see in the Network tab.

**Comment by artf** [comment]
Thanks for the report @DylanSp actually there is an issue with the listener. If the first `load` call fails (and I guess your `/load` endpoint is fake just like mine) it never starts tracking the editor changes so autosave doesn't work. It will be fixed in the next release

**Comment by DylanSp** [comment]
Updating to the next release fixed this, I now see requests to to the `/store` endpoint. Thanks for the prompt fix!
