### ISSUE TITLE
[QUESTIONS] Create toolbar in bottom

### ISSUE THREAD

**Issue by fmr411** [artf/grapesjs#1987]
can I make a new toolbar that is located at the bottom (as shown by the cursor) when selected component? Thank's
![Screenshot_2](https://user-images.githubusercontent.com/15244481/56845881-eb8ffd00-68f1-11e9-9529-488dbd5d4174.png)

**Comment by afdallah** [comment]
If you make that cell as a custom component, you can manipulate its `View`
```javascript
const comps = editor.DomComponents
  comps.addType('cell', {
    isComponent(el) {...},
    model: {},
    view: {
      events: {
        'click #extra-toolbar': 'doSomething'
      },
      onRender() {
        const el = this.$el

        el.append(`<button id="extra-toolbar">Extra button</button>`)
      },
      doSomething() {
        alert('toolbar clicked')
      }
    }
  })
```

PS: this new syntax required version 0.14.50+

**Comment by fmr411** [comment]
not only in the cell, but for all components

**Comment by afdallah** [comment]
Of course, you can apply the same technique to any component.

**Comment by artf** [comment]
As suggested by @afdallah you have to extend the component type and do in the onRender of the View.
