### ISSUE TITLE
bug on resize image

### ISSUE THREAD

**Issue by MisterFK** [artf/grapesjs#1988]
Hi !
I have some issues when i want resize an image.
When i put an image and when i click one resizer handler, the image don't keep his height but expand it to 100% of parent container...
I didn't found an option into the "resizable" option to disable that :
`editor.DomComponents.addType('image', {
    model: {
        defaults: {
            resizable: {
                step: 0.05,
                minDim:1,
                maxDim:100,
                unitHeight: '%',
                unitWidth: '%',
                currentUnit:0,
            }
        }
    }
});`

For context, the image has a absolute position.
Thanks for help !

**Comment by afdallah** [comment]
It would be easier for everybody here to help you if you can provide a live demo. 
I experienced the same issue, but in my case, it was because I set the image height to auto.

Here is the example of my old issue: 

![Image of demo](https://media.giphy.com/media/XzdC7pfQ9LTQPTxCT4/giphy.gif)

**Comment by MisterFK** [comment]
Thanks but it's not the same issue. I take a video to show the problem : 
![image](https://user-images.githubusercontent.com/44830209/56891696-5fffa300-6a8e-11e9-86a8-caabf3a712af.png)

**Comment by artf** [comment]
Thanks for the report @MisterFK can you provide a live demo of the issue, please?
