### ISSUE TITLE
How can I change default selected tab?

### ISSUE THREAD

**Issue by Pisikoll** [artf/grapesjs#199]
Hello

By default style manager is selected, but I would like to open Blocks tab by default # #

**Comment by Pisikoll** [comment]
Got it! Sorry

**Comment by cpcashion** [comment]
@Pisikoll how did you solve this? Looking to do the same thing...

**Comment by artf** [comment]
@cpcashion check the code from the demo preset https://github.com/artf/grapesjs/blob/gh-pages/js/grapesjs-preset-webpage.js#L284-L288
