### ISSUE TITLE
[QUESTIONS] need to call method before remove the html component

### ISSUE THREAD

**Issue by Ramkumar-Murugesan** [artf/grapesjs#1990]
Hi, I need to call the method before remove the HTML component. how can I do that
![image](https://user-images.githubusercontent.com/33427536/56888970-ef0eba00-6a92-11e9-85a4-04d6cf616e26.png)

calling method like 
editor.on('block:drag:stop', function (model) {})

**Comment by artf** [comment]
```js
editor.on('run:core:component-delete:before', () => {
	alert('Before delete')
})
```
