### ISSUE TITLE
[QUESTIONS] is any way to store the html id with its component when i click save button

### ISSUE THREAD

**Issue by Ramkumar-Murugesan** [artf/grapesjs#1993]
Hi. I know the grapesjs will generate the unique id for each HTML. when I store that HTML and CSS. the HTML id is not stored in my database. so when i reloaded my saved data into grapesjs it shows new unique id for each HTML element.

before saving the HTML. we have id="i63ss1" as u can see in the below image

![image](https://user-images.githubusercontent.com/33427536/57007721-75004180-6c08-11e9-8df6-4a3f8756224e.png)

but after I saved and loaded into grapesjs it shows id="i3ibuf" in the below image

![image](https://user-images.githubusercontent.com/33427536/57007765-babd0a00-6c08-11e9-896b-879c4574b845.png)

I want to load the same HTML id. is there any way to store the HTML id along with its HTML element 

Thanks in Advance

**Comment by artf** [comment]
You shouldn't load the HTML/CSS but the JSON data
Read this please https://grapesjs.com/docs/modules/Storage.html

**Comment by maryia-kabash** [comment]
@artf JSON doesn't have ids as well. Is there any way to force saving ids?

**Comment by artf** [comment]
@maryia-kabash IDs are created when required (added component-related style, has scripts, etc.)
