### ISSUE TITLE
[question] Is it possible to add StyleManager property for only class name

### ISSUE THREAD

**Issue by starcraft0429** [artf/grapesjs#1994]
Thank for this awesome library.

I am gonna to add style controller to sector.
This style will be for only one class name and won't set target.
For example ".xxx-wrapper div.active button:before"
(xxx will be identifier of component so that inside buttons will be controlled by this sector)
I tried to find in document but I can't find.
pls help.
Thanks in advance.

**Comment by artf** [comment]
No style manager can only change style properties (CSS) for any other thing you have to use [Traits](https://grapesjs.com/docs/modules/Traits.html)

**Comment by starcraft0429** [comment]
Thank you artf.
so we can't use nested css selector (".xxx-wrapper div.active button:before") in cssCompose?

**Comment by artf** [comment]
You can create any CSS Rule by using [setRule](https://grapesjs.com/docs/api/css_composer.html#setrule) method but only class-based are visible in Style Manager
