### ISSUE TITLE
Mobile first: Media query ordering issue

### ISSUE THREAD

**Issue by prosenjit-manna** [artf/grapesjs#1996]
1. Are you using the latest release (older versions are NOT supported)?
    - 0.14.61
  1. Are you facing the bug with your local copy of GrapesJS or with the current demo?
    - I am facing the issue with both local and 'https://unpkg.com/grapesjs' 
  1. The issue is mobile first media query ordering issue.
With the current version media query ordering status is 
```
@media (min-width: 1367px)
@media (min-width: 1024px)
@media (min-width: 320px)
```

  1. What is the expected behavior?
```
@media (min-width: 320px)
@media (min-width: 1024px)
@media (min-width: 1367px)

```

I tried to fix the sorting in the correct order. 

```
sortMediaObject: function sortMediaObject() {
 ...
   if (a.key.includes('min-width') && b.key.includes('min-width')) {
       return  _this4.getQueryLength(a.key) - _this4.getQueryLength(b.key);
     } else {
      return  _this4.getQueryLength(b.key) - _this4.getQueryLength(a.key);
     }
...
}

Is it a good solution? If so, please include this.

**Comment by prosenjit-manna** [comment]
See the changes here https://github.com/itobuztech/grapesjs/commit/3aa3b2dc7611d23e51eac524404df5b1a5814c74

**Comment by artf** [comment]
Seems legit. I'll add it in the next release
