### ISSUE TITLE
evaluate/help/reuse this nice library

### ISSUE THREAD

**Issue by pierreozoux** [artf/grapesjs#20]
We need to let user be able to create nice website/pages, without technical knowledge. A lot of project are reinventing the wheel, and I really think we should mutualize effort around a nice library and reuse that library. 

I will ping other projects to see what they think about collaborating here.

We already know Silex is in, let 's see for others, I'll complete the following list.
- [x] [Silex](https://editor.silex.me/)
- [ ] [Mautic](https://www.youtube.com/watch?v=hEPguULxy6g)
- [ ] [Odoo](https://www.odoo.com/page/website-builder)
- [ ] [elementor](https://elementor.com/) for WordPress [response](https://github.com/pojome/elementor/issues/509)
- [ ] [Tailor](http://gettailor.com//) for WordPress

**Comment by artf** [comment]
Hi @pierreozoux thank you, I really appreciate your initiative.
I've already seen some of those amazing projects and they're pretty much further than me.
Anyway, another big goal for me is to show how to integrate GrapesJS with some other software so if anybody here is adventurous enough to play with an alpha-stage, undocumented project I'm here to help :)

**Comment by iCoachLive** [comment]
artf looks very clean and promising.

**Comment by tuongpgjz** [comment]
Hi pierreozoux,

I think you can add other one is [KingComposer](https://kingcomposer.com) page builder into your list

They just release new version 2.5.

**Comment by pierreozoux** [comment]
@tuongpgjz nice try :) But there are not open source, so... they do their life :) would be nice if they use this also, but I don't know where to ping them... Would you like to try?

**Comment by tuongpgjz** [comment]
Oh, it is open source for backend. You can try from https://wordpress.org/plugins/kingcomposer/

**Comment by pierreozoux** [comment]
Ah ok :) It is not open-source then, I call it fauxpen-source (faux means fake in french). Or maybe I missed it? Where is the code? What is the license?

**Comment by iCoachLive** [comment]
Check on Gimp. Says it IS open source. GL.

**Comment by joshmarom** [comment]
https://github.com/pojome/elementor/issues/509

**Comment by artf** [comment]
thanks for the reply @joshmarom

**Comment by andrew-worsfold** [comment]
Really impressive project and something I intend to delve into for an upcoming project!  Please see my comments re: Tailor [here](https://github.com/andrew-worsfold/tailor/issues/32).

**Comment by artf** [comment]
Thank you @andrew-worsfold hope to see you here in the future. Anyway, I'm surprised that didn't hear about Tailor, truly simple and well done.

**Comment by etewiah** [comment]
grapejs is truly awesome.  I will try to integrate it in my website builder for real estate over the coming weeks: 

[https://github.com/etewiah/property_web_builder/issues/7](https://github.com/etewiah/property_web_builder/issues/7)

**Comment by artf** [comment]
Thanks for the interest @etewiah excited to see your results :)

**Comment by pavan168** [comment]
Hello @artf, this is a lovely tool. I have been looking for something like this for ages. We have a SaaS product where we give websites for customers. However, we need to incorporate a website builder. Do you think we can use your library? How are the licensing done?

**Comment by artf** [comment]
Of course you can @pavan168 The library is under BSD 3-clause license

**Comment by pavan168** [comment]
Can we integrate this to our product and sell with the package as well? There wont be any licensing issues right?

**Comment by artf** [comment]
sure @pavan168 no problem, there is no other licenses for the commercial use. Anyway, would be cool to see your final work :)

**Comment by pavan168** [comment]
Sure. would love to speak more on this line. Would you be able to pass me your email address?

**Comment by subek** [comment]
Is there anything for the editing tools for the image ?? I couldn't find any.

**Comment by artf** [comment]
@subek not at the moment, it's possible to add one via plugins but at the moment I have no time to make one.

**Comment by subek** [comment]
@artf : Ok Thank You !

**Comment by LukeTowers** [comment]
@artf What would you say in regards to how extendable this library is? 
Say if I wanted to replace / modify certain components (for example the RTE and Asset Manager) dynamically via a plugin or other means; how difficult would that be to accomplish? What about custom styling / "themes" for the GrapeJS editor as a whole? 

And one final question, does GrapeJS support editing previously saved HTML (even if it's just editing previously saved HTML that has been created by GrapeJS)? If not, what are the major hurdles in adding such support?

This project looks quite interesting and it looks like you've put a lot of work into it! Great job so far!

**Comment by artf** [comment]
Thanks @LukeTowers I'd say that the goal point is to make GrapesJS as much extendable/modular as possible.

You can already find examples on how to replace/modify built-in features:
 [plugin-ckeditor](https://github.com/artf/grapesjs-plugin-ckeditor) - Replace the default RTE with CKEditor - [How-to guide](https://github.com/artf/grapesjs/wiki/Replace-Rich-Text-Editor)
[plugin-filestack](https://github.com/artf/grapesjs-plugin-filestack) - Enable Filestack uploader inside the Asset Manager

You can import previously saved HTML as well. In GrapesJS, you store templates as HTML (this is actually what the final user will see, so clean HTML without additional info) and, of course, reimport them later, in addition, there is also a JSON structure which stores additional informations (eg. edited name inside Layers panel)

**Comment by remcovo** [comment]
At this moment I am playing with Grapejs, it looks really amazing!
Is there also an example available how to add/control repeating elements? 

For example I want to add tabs or image slider. f.e.  <li><a href="#">image.jpg </a></li>

 It would be handy if you can upload in de component panel the image slides and set the links. Or edit/ remove an li element

**Comment by artf** [comment]
thanks @remcovo 
It's definitely possible, but not yet available

**Comment by megarg** [comment]
I am trying and evaluating grapesjs. It looks amazing though one question: is it possible to render a component which is created by another JS library (such as a rendering a form created by a "forms creation library" such as formio)?

**Comment by artf** [comment]
@megarg not sure exactly about what is the output of "another JS library" but you can import any HTML element, then you can create custom components to give them specific/customized behaviors
