### ISSUE TITLE
Drag & Drop Image uploader Not Working

### ISSUE THREAD

**Issue by aliassad** [artf/grapesjs#200]
Can't able to upload a new image from my computer.

Errors in console:

POST http://localhost/assets/upload 
send @ jquery.min.js:4
ajax @ jquery.min.js:4
uploadFile @ grapes.min.js:2
dispatch @ jquery.min.js:3
q.handle @ jquery.min.js:3
(index):1 XMLHttpRequest cannot load http://localhost/assets/upload. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access. The response had HTTP status code 404.

**Comment by uniacid** [comment]
You have to build the API/web endpoint for the assets/upload function itself as there is no pre-existing function to actually handle the upload itself if you're using the default uploader provided.

**Comment by aliassad** [comment]
can you create a demo i have unable to handle this, after upload how the image will shown in that image component ?

**Comment by artf** [comment]
@aliassad you have to indicate your image storage endpoint, check this #138
