### ISSUE TITLE
[Question] How to select a specific element nested inside a template

### ISSUE THREAD

**Issue by Jogai** [artf/grapesjs#2003]
My test case: https://codepen.io/jogai/pen/QRjKyN?editors=1111

I want to select the middle column so I thought I can use selectorManager.get() but its not selecting what I'm expecting.

I supply the class name (because id doesn't work anyway) and the element with that class name has 4 images. but if I look in the collection I cant see the child elements.

Do I use it wrong? Should I initialize the selectorManager with other options?

**Comment by artf** [comment]
[SelectorManager](https://grapesjs.com/docs/api/selector_manager.html) is meant for managing Selector entities (eg adding, updating and removing classes) not for selecting components. In your case, you should do this:

```js
editor.on('load', () => {
	editor.select(editor.getWrapper().find('.finder')[0])
});
```

**Comment by Jogai** [comment]
Thanks for clearing up my misunderstanding!
