### ISSUE TITLE
Invalid class names allowed

### ISSUE THREAD

**Issue by benvmatheson** [artf/grapesjs#2005]
When adding a class name, the editor allows you to create class names that are invalid in CSS, but valid in HTML (e.g. `123`). As adding class names with this tool is primarily meant for styling, it may make sense to add a warning when the class name is invalid for CSS.

**Comment by artf** [comment]
You can add this kind of warning (and even apply your logic to fix the invalid name) by yourself by using `selector:add` event
```js
editor.on('selector:add', selector => {
		const name = selector.get('name');

      	if (nameNotValid(name)) {
			alert('Class changed');
			selector.set({ name: `fixed-${name}` });
      	}
    });
```

**Comment by benvmatheson** [comment]
That's perfect. Thank you!
