### ISSUE TITLE
[Question]The canvas turns dark and unmodifiable on adding a large piece of custom html.

### ISSUE THREAD

**Issue by amoslover** [artf/grapesjs#2008]
I used to add custom html with `editor.addComponent()`.
It works well at most of the time, but when I try to insert a large piece of HTML which may contain a bunch of children elements the canvas turns black and cannot be modified. I can only reload the whole editor to make it works again.

**Comment by artf** [comment]
> the canvas turns black

weird thing. 
Are you able to create a reproducible demo? Upload here the template if you need
