### ISSUE TITLE
'Select' trait no updated in edit mode

### ISSUE THREAD

**Issue by ahmedeldeeb25** [artf/grapesjs#2009]
Hi there,
There is a problem with me, I don't know if it from my code or from grapejs itself,

For LINK tool, it takes its links from my DB that contains for ex: link1,link2, then I put LINK tool in my page and save it in BD.
I added link3 to DB then when I go to edit my previous created Page that contains LINK tool, I found just link1,link2 but If I choose new LINK the 3 links are loaded.

What's the problem now ?!

**Comment by artf** [comment]
I think you're in the same case of #2007

**Comment by ahmedeldeeb25** [comment]
![Screenshot from 2019-05-12 13-06-21](https://user-images.githubusercontent.com/14032350/57581380-f3859a80-74b6-11e9-9f17-fa8491707908.png)


![2](https://user-images.githubusercontent.com/14032350/57581381-faaca880-74b6-11e9-9cff-f98d34f6cab9.png)

I did the same but it removed my custom trait 'Page' in edit mode like in these 2 pics
