### ISSUE TITLE
Question regarding traits

### ISSUE THREAD

**Issue by flipmokid** [artf/grapesjs#201]
Hi,

I'm playing around with grapesjs at the moment. I want to create a trait such as:
```javascript
var stateTraits = [
  { type: 'select',
    label: 'Session',
    name: 'session',
    options: [{ value: '', name: '-' },
              { value: 'session-y', name: 'yes' },
              { value: 'session-n', name: 'no' }],
    changeProp: 1
  },
  { type: 'select',
    label: 'Optin',
    name: 'optin',
    options: [{ value: '', name: '-' },
              { value: 'optin-y', name: 'yes' },
              { value: 'optin-n', name: 'no' },
	      { value: 'optin-x', name: 'ineligible' }],
    changeProp: 1
  }
];
```
and I want to apply this to every existing component. When someone changes the value I would like to take some action, such as setting a CSS class. I'm having difficulty working out how to do something such as change the class when the user sets the traits value as I can't seem to access the model. I'm currently doing:

```javascript
function addTraits(componentManager, component) {
  var arr = component.model.prototype.defaults.traits.slice(0);
  stateTraits.forEach(function(x) { arr.push(x); });
  componentManager.addType(component.id, {
     model: component.model.extend({
      init() {
	this.listenTo(this, 'change:session', function() {
	  console.log(this);
	  // can I do something here to set the class?
	});
      },
      defaults: Object.assign({}, component.model.prototype.defaults, {
        traits:  arr
      })
    }, { isComponent: component.model.isComponent }),
    view: component.view
  });
}

grapesjs.plugins.add('test-plugin', function(editor, options) {
  var partial = function(component) {
    return addTraits(editor.DomComponents, component);
  };
  editor.DomComponents.componentTypes.forEach(partial);
});
```

I suspect the way to do things like this is to re-write the toHTML function for each component but I'm hoping there is another way as I would like to avoid re-writing the toHTML function for every existing component.

Finally, what would I have to do to make sure that my trait values in the model is correct when importing html?

Thanks!

**Comment by artf** [comment]
You can add a class to the model in this way:
```js
model.get('classes').add({name: 'class-name'});
```

About the value, by default, [Traits](https://github.com/artf/grapesjs/wiki/Traits) relies on attributes of the model, so, for example, adding a trait named `data-test` you will be able to assign the value by importing this `<div data-test="value"></div>`. When you use `changeProp`, the trait relies on the model property, so you have to use this format for importing model properties from the HTML `<div data-gjs-data-test="value"></div>`
