### ISSUE TITLE
[BUG] Droppable query selector [data-gjs-type="my-component-type"] no longer working

### ISSUE THREAD

**Issue by simplecommerce** [artf/grapesjs#2010]
Hi, since the latest version, I noticed that when I use the droppable query selector using `[data-gjs-type="my-component-type"]` no longer seems to work.

I have added two codesandbox demos to show you the issue.
I am not able to figure out what changed.

Hope it helps, thanks!

## You're submitting a BUG
  1. Are you using the latest release (older versions are NOT supported)?
     Yes
  2. Are you facing the bug with your local copy of GrapesJS or with the current demo?
     Latest version available 0.14.61.
  3. What is the expected behavior?
     Components defined by type in droppable selector, would detect and allow only specified types to be dropped.
  4. What happens instead?
     Component is no longer recognized and can't be dropped into said component.
  5. If you're able to reproduce the bug indicate all the necessary steps
    1. Create two components and blocks.
       * One component has the droppable attribute selector, e.g.: `droppable: ['[data-gjs-type="test-drop"]']` and the other would be the component we want to drag and drop inside the first one.
  6. Attach screenshots (using KAP/LICEcap), screencasts or live demo
    1. [Version that works with the previous release - 0.14.57](https://codesandbox.io/s/zz2nz90r7x)
    2. [Version that doesn't work with the latest release - 0.14.61](https://codesandbox.io/s/zxrr42mn9l)

  **To test the issue, just drag and drop the `TEST` block in the canvas, 
and then try to drag and drop the `TEST DROP` block onto the `TEST` component.**

**Comment by artf** [comment]
Ok seems like the regression was introduced by this change: https://github.com/artf/grapesjs/commit/702ba828b13bae4b64bfd7bc79f23d8909d757f4#diff-6aa74cf54855daa6ca63a5d1e8b77c44R358

I'll fix it in the next release
