### ISSUE TITLE
[question] how to add script for all widgets(like protectedCss)

### ISSUE THREAD

**Issue by starcraft0429** [artf/grapesjs#2012]
I want to add some functions for all components accessible.
when initialize editor, there is a option like protectedCss. 
Isn't there a way javascript like above?

**Comment by artf** [comment]
You can initialize custom js in the canvas in this way:
```js
const editor = grapesjs.init({
  ...
  canvas: {
    scripts: ['https://.../script.js']
  }
});

```

**Comment by starcraft0429** [comment]
Thank you.
Btw what I want to need is inline javascirpt.
not external link...
regards.

**Comment by artf** [comment]
In that case, I suggest you access the document of the iframe and to add the inline script (to get the document use `editor.Canvas.getDocument()`)
