### ISSUE TITLE
[Question] Is it possible to extract the updated properties in events 

### ISSUE THREAD

**Issue by Patrick-Spiegel** [artf/grapesjs#2015]
Hello,

I am wondering if it is possible to react on property updates. 

I have tried to use the built-in events, but its not clear to me how I am supposed to extract the required information from the model. 
For example when I handle the event ```component:styleUpdate:font-family``` then I get a model with alot of information, but not exactly which font-family is the new one. 

It would be awesome, if it was possible to have the updated html node and the updated css properties for further processing.

**Comment by artf** [comment]
You can do it in this way:
```js
editor.on('component:styleUpdate:font-family', component => {
      console.log('updated component', component, 'font-family new value', component.getStyle()['font-family']);
    });
```

**Comment by Patrick-Spiegel** [comment]
Thanks for your answer. That would mean that I had to write for every single an event handler. Isn't there a more generic way to solve this issue?

**Comment by artf** [comment]
> That would mean that I had to write for every single an event handler.

Every single what? property? In that case you can try this:
```js
editor.on('component:styleUpdate', (component, prop) => {
	console.log('updated component', component, 'property:', prop, 'value:', component.getStyle()[prop]);
});
```

**Comment by Patrick-Spiegel** [comment]
Hey, 

thanks for the answer, I think I can work with that.
