### ISSUE TITLE
[QUESTION] How to remove unnecessary component?

### ISSUE THREAD

**Issue by yrbn** [artf/grapesjs#2016]
@artf I use CKEditor and it's link plugin can't work with 'Link' blocks. How can I prevent creating 'Link' component when grapesjs newsletter is rendering? Or prevent link wrapping on chosen class.
When adding a link:
![OnPaste 20190514-165727](https://user-images.githubusercontent.com/17144018/57703873-8a925400-7669-11e9-8084-f6b11b650201.png)

After importing the code of template shown above:
![OnPaste 20190514-165801](https://user-images.githubusercontent.com/17144018/57703912-a3026e80-7669-11e9-96b9-faacfc543890.png)

**Comment by artf** [comment]
If you want to disable the component from the parser you can do this:
```js
editor.DomComponents.addType('link', {
	isComponent: () => false,
})
```

**Comment by yrbn** [comment]
no, If I do in such way the link becomes a text. I want grape js not to wrap it with any block

**Comment by artf** [comment]
> I want grape js not to wrap it with any block

Which block are you talking about?

**Comment by yrbn** [comment]
> > I want grape js not to wrap it with any block
> 
> Which block are you talking about?

Link block, the screenshots are above. I create a link via CKEditor(First picture) and it is not wrapped by the Link block. But if I paste this code to a new template, the link is getting wrapped by the Link block(Second picture). I want grapejs not to create Link block(or any other) around the <a> tag. Like it is on the first picture

**Comment by artf** [comment]
> But if I paste this code to a new template

If you copy and import the FINAL CODE of the editor, you can't expect it to work properly. The final HTML doesn't have the information about when the TEXT component  starts/ends. So you have to [store them properly](https://grapesjs.com/docs/modules/Storage.html) if you need to edit them later
