### ISSUE TITLE
RSS Feed

### ISSUE THREAD

**Issue by shaunc869** [artf/grapesjs#2022]
Hi!

I have a question, I searched but couldn't find an answer, is there a component that pulls in an RSS feed and formats it on the page. MailChimp and Campaign Monitor do this, here is an example feed: http://www.homecaredaily.com/feed/ I realize some of this is done server side, but just looking to see if anyone has tackled this before or some guidance on this feature. Thanks!

**Comment by artf** [comment]
Hi Shaun, I think it should not be that complex to implement if you read how [Components](https://grapesjs.com/docs/modules/Components.html) and [Traits](https://grapesjs.com/docs/modules/Traits.html) work.
It should be something like this (take it as a pseudo-code):
```js
editor.DomComponents.addType('rss-feed', {
	model: {
		defaults: {
			total: 10, // eg. how many feeds to render
			feed: 'https://.../feed1', // default feeds to render
			traits: [
				{
					type: 'select',
					name: 'feed',
					changeProp: 1,
					options: [ 'https://.../feed1', 'https://.../feed2' ],
				}, {
					type: 'number',
					name: 'total',
					changeProp: 1,
				}
			]
		},
		init() {
			this.listenTo(this, 'change:feed change:total', this.refreshContent);
			this.refreshContent();
		},
		async refreshContent() {
			const { feed, total } = this.attributes;
			let parser = new RSSParser(); // eg. using https://www.npmjs.com/package/rss-parser
			const feeds = await parser.parseURL(feed);
			const result = feeds.items.slice(0, total).map(item => `<div>
				<h1>${item.title}</h1>
				<p>${item.text}</p>
			<div>`);
			this.components(result.join(''));
		}
	}
});
```
then add a block to let users drag it in the canvas

**Comment by shaunc869** [comment]
This is amazing, thank you so much!

**Comment by Idaryss** [comment]
Hello I tried to create this component using mjml but I ma getting 
![Capture d’écran 2024-09-17 à 10 49 31](https://github.com/user-attachments/assets/e8303602-c599-4f2b-97ff-062f3c97e175)


This is my block 


  addBlock('rss-feed', {
    label: getI18nLabel('rss'),
    media: ``,
    content: `<mj-section>
        <mj-column>
          <mj-text>RSS Feed Title</mj-text>
          <mj-text>RSS Feed Description</mj-text>
        </mj-column>
      </mj-section>`,
    category: categorySimple
  });


and the rss.ts is looking approximatively as showing above
