### ISSUE TITLE
TUI Editor

### ISSUE THREAD

**Issue by Amir2828** [artf/grapesjs#2023]
Hello all,

Im having a problem with the TUI editor plugin, 
If I try to edit a newly updated image that has been through the asset manager, Everything works fine.
But if I try to edit an already existing image in an exisiting page the TUI dosent recognize the image and open the editor with no image on display.
Any solution? should I try some how to make every double click on an image to go through the assets manager first?

**Comment by artf** [comment]
1. Wrong repository
2. Create at least a demo of the issue
