### ISSUE TITLE
[Question]Is it possible to customize a block which load data from database

### ISSUE THREAD

**Issue by Femonzor** [artf/grapesjs#2030]
For example, I want to create a complex custom navbar block. It has several first level navigations, and each of one also has several second level navigations. The data of navbar is loaded from database. And when I drag it to the canvas, I can modify properties in trait to change the data navbar loaded. Also, when I export template, I want the code is just html, not js contains ajax request, something like server side rendering.

Is it possible?

**Comment by artf** [comment]
Sure, but in that case, I'd suggest you create a [custom component](https://grapesjs.com/docs/modules/Components.html).

Here an example/pseudo-code of triggering an async function for changing the component content
```js
editor.DomComponents.addType('my-custom-component', {
	model: {
		defaults: {
			endpoint: 'http://A', // some prop for the trait
			traits: [
				{
					type: 'select',
					name: 'endpoint',
					changeProp: 1,
					options: [ 'http://A', 'http://B' ],
				}
			]
		},
		init() {
			this.listenTo(this, 'change:endpoint', this.refreshContent);
			this.refreshContent();
		},
		async refreshContent() {
			const { endpoint } = this.attributes;
			const response = await fetch(endpoint);
			...
			let result = '';
			// ... Build the HTML result from the async response
			...			
			this.components(result);
		}
	}
});
```
