### ISSUE TITLE
[QUESTIONS] How to change the style of the outline of selected components 

### ISSUE THREAD

**Issue by charlieshum1** [artf/grapesjs#2033]
Hi @artf 

I can change the style of outline of a hovered component with 
`.gjs-cv-canvas .gjs-highlighter {
......
}`

How can I change the outline style of a selected component?
I cannot apply the style using '.gjs-comp-selected'

Also, how can I change the style of the component type/name label of hovered/selected components?

Thanks!

**Comment by artf** [comment]
Only selected component style is inside the canvas, so you have to use `canvasCss` option https://github.com/artf/grapesjs/blob/8915ae417bed25a4834b34d8f0ecc08f0e03fd64/src/editor/config/config.js#L74-L78

for the rest, you can use simple CSS as always
