### ISSUE TITLE
[QUESTIONS] Toolbar error position when adding elements

### ISSUE THREAD

**Issue by fmr411** [artf/grapesjs#2037]
I made canvas in modal, but there were a few bugs, when I added a new component, the position of the toolbar went down, the top canvas value that was initially 0 changed (console.log (r.canvasTop) in grapesjs.min.js), but when I resized the browser, everything was normal again (the bug only happens every time the page loads), how can I fix it, Thank you very much.
![gif](https://user-images.githubusercontent.com/15244481/58365566-7e6f8780-7ef0-11e9-820b-9df72a293a9f.gif)

when dropping the component, the position of the component (indicated by the green line) is not appropriate.
![error drag](https://user-images.githubusercontent.com/15244481/58397557-bc4ce700-807b-11e9-942f-3c42cab02eef.gif)

**Comment by artf** [comment]
If you encounter an error, open the issue as a bug, please. So follow the template for the bug.
