### ISSUE TITLE
Buttons flashing with question mark and non responsive.

### ISSUE THREAD

**Issue by Apetrou** [artf/grapesjs#2038]
Hi,

I'm having issues using this library, firstly some buttons are missing their icons and are flashing when clicking on them they are not responsive. E.g.: 
![Screenshot 2019-05-25 at 12 53 28](https://user-images.githubusercontent.com/17902157/58368978-5c740600-7eec-11e9-858e-485b50727c7c.png)

Aswell when I select certain elements on the page some white blobs appear. E.g:

![Screenshot 2019-05-25 at 12 55 08](https://user-images.githubusercontent.com/17902157/58369017-aeb52700-7eec-11e9-8811-a529c06c2d38.png)

For reference i am using the preset newsletter plugin however I have tried without and I still face the same issue. 

Any help would be appreciated. Thanks, Alkis.

**Comment by artf** [comment]
@Apetrou I think you're missing some files (those white blobs seems to be huge toolbar icons, so the font-size seems to be changed). 
Try to start from the file used for the demo https://github.com/artf/grapesjs/blob/gh-pages/demo-newsletter-editor.html

**Comment by umer936** [comment]
I also have this problem. 

I am trying to include it in a CakePHP application. If I run my same gjs includes and scripts on a simple HTML file from my desktop, it works as expected - meaning it is not a missing include. However, including that gjs setup in the application I need it to causes it to look identical to the image above.

**Comment by umer936** [comment]
Okay. After lots of trial and error, the issue is that I am already including font-awesome in my header.

**Comment by umer936** [comment]
The issue is with Font Awesome 5 when grapesjs wants Font Awesome 4
Fixed by changing the FA 5 include to: 

`    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/v4-shims.min.css" integrity="sha512-iaLhEHW3p+ZNgkDKBi4zEfH+aWAMGJ7I7njqD3jKnbN0ux4Gkumu2vjuI71YUov20OIPl3R32v8HO+V+6OgbvQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
`
