### ISSUE TITLE
[QUESTIONS] How can I update the styles of a class?

### ISSUE THREAD

**Issue by goprime10** [artf/grapesjs#2039]
Hi, so I have this button, whose style changes when hovered, a new class is added:
`<button class="btn btn_hovered">Button 1</button>`

` <button class="btn">Button 2</button>`

Is there a way I can change the styles of a particular class? If I wanted to add a custom color to the "btn_hovered" class?  Any help appreciated, thanks.

**Comment by artf** [comment]
To get the rule with that class use [`CssComposer.getRule`](https://grapesjs.com/docs/api/css_composer.html#getrule) and once you have the rule update it style
```js
const rule = editor.CssComposer.getRule('.btn_hovered');
rule && rule.addStyle({ color: 'red' });
```

**Comment by goprime10** [comment]
@artf Hi, I am trying to access with that statement, but I get null as a response, what could be the issue?

**Comment by artf** [comment]
Well, the rule should be there at first. If you're using `canvas.styles` option in your init method those are not appended inside CssComposer, so you have to add it first.
