### ISSUE TITLE
GrapeJS plugin developer wanted

### ISSUE THREAD

**Issue by dizzydes** [artf/grapesjs#2040]
Looking to develop a plugin and would like to hire an experienced GrapeJS plugin developer on a contract basis for this work.

Please respond or dm or email (below) if you’re interested and we can chat.
desmondconlon @ gmail

**Comment by artf** [comment]
@dizzydes try also to post your offer in the dedicated channel in the [discord chat](https://discord.gg/QAbgGXq)

**Comment by dizzydes** [comment]
Will do Artur thanks.

Thanks,
Des

**Comment by GoodPHP** [comment]
https://github.com/GoodPHP/GrapesJS-devfuture
