### ISSUE TITLE
[Question/Feature Request] Licence info is missing?

### ISSUE THREAD

**Issue by EthanM11122** [artf/grapesjs#2041]
Hi,

While reading the [licencing requirements](https://github.com/artf/grapesjs/blob/dev/LICENSE) for this project and also grapesjs-preset-newsletter project the licence states that the disclaimer must be referenced/included in the output source/binary files.
To meet this need should the [source js](https://github.com/artf/grapesjs/blob/dev/src/index.js) not include a reference similar to [this](https://github.com/twbs/bootstrap/blob/111024695a70e1133256b6aeaac41fae98c8150e/js/index.esm.js#L3) example, or have I misinterpreted the licencing requirement?

**Comment by artf** [comment]
> While reading the licencing requirements  for this project and also grapesjs-preset-newsletter project the licence states that the disclaimer must be referenced/included in the output source/binary files.

I think that sentence might be a subject to different interpretations, in that case, redistributions of code/repository should contain the LICENCE file
