### ISSUE TITLE
Npm start to develop on local server didn't work

### ISSUE THREAD

**Issue by eduardonunesp** [artf/grapesjs#2044]
Did the procedure to start the local server using `dev` branch as described on README, it worked on the console, but fails on chrome and the grapesjs don't load due to the following error

![image](https://user-images.githubusercontent.com/582516/58523839-48eec680-819c-11e9-8c3f-4fbbd7d0a012.png)

**Comment by artf** [comment]
Weird, never seen that before. It might be some dev dependency change in some minor release. Try to reinstall node_modules with exact dependency versions

**Comment by verdverm** [comment]
I'm having issues following the dev setup:

```
Uncaught TypeError: Cannot read property 'key' of undefined
    at eval (keymaster.js?c3d1:274)
    at eval (keymaster.js?c3d1:296)
    at Object../node_modules/keymaster/keymaster.js (grapes.min.js:335)
    at __webpack_require__ (grapes.min.js:30)
    at Object.eval (index.js?e835:38)
    at eval (index.js:236)
    at Object../src/keymaps/index.js (grapes.min.js:2204)
    at __webpack_require__ (grapes.min.js:30)
    at eval (Editor.js?c6c5:11)
    at Object../src/editor/model/Editor.js (grapes.min.js:2168)
```

Maybe a bundler issue?

**Comment by artf** [comment]
Ok, seems like there is definitely something wrong somewhere in dependencies (on my local machine it works but I didn't trigger the install for a long time)

Unfortunately, this week (maybe also the next one) I'm busy and don't think I'll have any time to investigate on this, so I'd really appreciate a help 😬

Probably we should also try to update dependencies like webpack and babel (still using the old version). Last time I've tried I had some issues, didn't have that much time, so I gave up :/

**Comment by verdverm** [comment]
so I removed the `package-lock.json` file and tried both npm and yarn, both to no avail, still getting the same error.

```
babel-core@^6.0.0, babel-core@^6.26.0, babel-core@^6.26.3:
  version "6.26.3"

webpack@^4.26.1, webpack@^4.8.1:
  version "4.34.0"
```

Any insights or pointers?

**Comment by verdverm** [comment]
I can get it working in dev mode!

package.json:115
```
    "start:js": "webpack-dev-server --open --progress --colors --env=dev",
```

add `--env-dev` to the end

**Comment by verdverm** [comment]
@artf I see you made a commit on June 13 for building dist, however I am still seeing errors on dev@HEAD

Do you have any updates at this point?

**Comment by artf** [comment]
I made a quick check and the reason seems to be the latest Backbone@1.4.0 I don't have time to investigate so I'll just freeze the currently used version
