### ISSUE TITLE
[QUESTIONS] How to disable Scripts inside the editor?

### ISSUE THREAD

**Issue by sdrebel** [artf/grapesjs#2046]
Hi @artf ,
I need to disable all the scripts (component scripts and other scripts) inside the editor, and scripts should run  only when we click on 'preview button'. 
Is there any method for it?

**Comment by artf** [comment]
No, at the moment, there is no kind of public API to do that

**Comment by sdrebel** [comment]
Hi @artf ,

Thank you for the reply. Right now i'm removing all the scripts and running only in preview mode.

**Comment by mariasmol** [comment]
Hi @sdrebel   would love if you can share your solution.
Also,after allowing scripts in the editor i copied this example  to import
![image](https://user-images.githubusercontent.com/54943482/64351748-8b2d6c80-d003-11e9-9b15-4a64e9feb180.png)
pressed the import and saw the hello world.
**however** when using the preview mode i don't see the alert .
Do i need to configure something to execute scripts in preview mode?
Also my next step is that i would like the editor not to execute the JS , hoe did you handle it? by adding  CDATA?
thanks for the help!
