### ISSUE TITLE
Where is the Box component used in the demos?

### ISSUE THREAD

**Issue by kwayebopp** [artf/grapesjs#2048]
Hi! First, I'd like to say thanks to @artf for building such a slick library. I just started using it in my project and it was super easy to get set up. 

I'm building a React app using `grapesjs` with the [ `grapesjs-preset-webpage`](https://github.com/artf/grapesjs-preset-webpage) plugin. I've been trying mimic building a webpage like the one in the [demo](https://grapesjs.com/demo.html), and I noticed that there are a lot of `Box` components being used. Naturally, I expected to find `Box` under the Blocks menu, but I couldn't locate it. To my surprise, there wasn't a `Box`  in the demo menu either! So where is the `Box` element coming from and how can I add it to my Blocks menu?

Thanks in advance for the assistance!

**Comment by artf** [comment]
Thanks @kwayebopp BTW the `Box` label is used for the default component, nothing special (at the moment of writing `Box` was more pleasant than `Div`)
