### ISSUE TITLE
[Question]: Can the editor be instructed to ignore a class?

### ISSUE THREAD

**Issue by benvmatheson** [artf/grapesjs#2049]
Once the editor creates HTML/CSS we hand it off to another piece of code. That piece of code relies on classes using a predetermined class name to perform actions on the HTML. (switching out placeholders for actual data etc.) If this class is added to an element, once that element is clicked, it attempts to add styles to this class. Is it possible to tell the editor to ignore a class?

**Comment by artf** [comment]
What do you mean "to ignore"? To ignore where? Being available in the style manager or something else?

**Comment by benvmatheson** [comment]
Sorry, I was unclear there. When clicking an element/block and proceeding to styling the element, the class is chosen by default. Could this class be deselected by default and hidden from the `Classes` field?

![image](https://user-images.githubusercontent.com/9043745/58724427-cc293b80-8399-11e9-86de-8714a9d6a2cb.png)

**Comment by artf** [comment]
You could place a listener on a new selector

```js
editor.on('selector:add', selector => {
		const name = selector.get('name');

      	if (someConditionForSelectors(name)) {
			selector.set({
				// Can't be seen by the style manager, therefore even by the user
				private: true,
			})
      	}
});
```

**Comment by benvmatheson** [comment]
@artf This is perfect. Thank you!

**Comment by benvmatheson** [comment]
@artf If I export components/style then reimport, this doesn't appear to be persisted. Should that be saved, or do I need to add a listener to set them to private when loaded as well?

**Comment by artf** [comment]
well if the condition is the same there is no need to save it

**Comment by benvmatheson** [comment]
My issue is that when I drag an item onto the canvas, it is set to private. But when I export, private is set to false. So when I open the same file, the classes now show again for all of these items. It's not a big issue for me, as I've just set a second listener to set them all to false when loaded. Just let me know if you think I should open a bug for this issue.

**Comment by artf** [comment]
> as I've just set a second listener to set them all to false when loaded

The listener should always be there
