### ISSUE TITLE
[QUESTION] Can I give default styling to an html tag like <p>?

### ISSUE THREAD

**Issue by alikabeer32** [artf/grapesjs#2051]
I want that p tag should **always** have 0 margin. How do I do that? The reason is that ckeditor is wrapping the text around a p tag and p tag has a margin that's making it all ugly.

**Comment by artf** [comment]
You can pass all the style you want to your initial template
```js
const editor = grapesjs.init({
      container : '#gjs',
      components: '<div class="txt-red">Hello world!</div><p>Text</p>',
      style: '.txt-red{color: red} p {margin: 0}',
  });
```

**Comment by alikabeer32** [comment]
Exactly what I needed, Thanks!!
