### ISSUE TITLE
[QUESTION]: Custom Asset Manager Layout

### ISSUE THREAD

**Issue by Bhavana20** [artf/grapesjs#2056]
Hi,

We are trying to modify the Asset manager layout, to match our requirement below.

Requirement:
- User double clicks on the image or adds a new image or any other option that opens the Asset manager, there should be a popup with the options: (Point1.png)
1. Select from existing list from the server. (Point1AB.png)
2. Select from existing list from Veeva Vault. (Point1AB.png)
3. Upload new image (Point1C.png)

- If user clicks on **Select from existing list**, Asset manager will open with only the list of images, and a back button to go the first point. User will not upload new image in this case.

- If user clicks on **Upload new image**, Asset manager will open with the upload option (Existing Asset manager). This will enable user to upload new images.

We are currently trying to create a new plugin using the [boilerplate](https://github.com/artf/grapesjs-plugin-boilerplate) available. 

Could you please suggest a better way to achieve this change in the Asset Manager layout, as we see there is no option to add new layout or modify the existing layout using the methods available in Asset Manager.

Please find attached the screenshots of the layout we are trying to achieve for reference.

Thanks in advance.

**Point1.png**
![Point1](https://user-images.githubusercontent.com/10365593/58718279-d32c6a00-83ea-11e9-9778-034b688f216d.png)
**Point1AB.png**
![Point1AB](https://user-images.githubusercontent.com/10365593/58718277-d32c6a00-83ea-11e9-9624-d7686b99f687.png)
**Point1C.png**
![Point1C](https://user-images.githubusercontent.com/10365593/58718276-d293d380-83ea-11e9-81e6-8fdef3ebf994.png)

**Comment by artf** [comment]
For such custom behaviour, I'd suggest [replacing the built-in Asset Manager](https://github.com/artf/grapesjs/issues/491#issuecomment-342813486) panel with your own
