### ISSUE TITLE
Custom block does not appear selected

### ISSUE THREAD

**Issue by adamwpe** [artf/grapesjs#2059]
It appears when adding a custom block to the block manager, if you past it a content object, when selected, it does not appear selected (With the blue box around the component):

![image](https://user-images.githubusercontent.com/49768920/58748534-344b5080-8472-11e9-9083-ac9bf580c31e.png)

An example of my code is here:
Example: https://jsfiddle.net/v5k4jqfg/1/

Is there any way to show the selected blue box?

**Comment by verdverm** [comment]
I bet it's some configuration value, though I'm new to grapes and don't know the answer yet... :[

**Comment by artf** [comment]
Remove the custom tag `tagName: 'does_not_appear_selected'`
