### ISSUE TITLE
AssetManager Upload

### ISSUE THREAD

**Issue by rubendsc** [artf/grapesjs#206]
Hello, 

I have a problem with the "AssetManager", I can not upload images to insert in the html,  i am using:

`       assetManager: {
           storageType: '',
           storeOnChange: true,
           storeAfterUpload: true,
           assets: images,
           upload: 'https://www.dropbox.com/home/folder1',  // or "http://localhost:55328/img"
           uploadText: 'Drop files here or click to upload',
       },`

But when I select the image I get the following error:

_SEC7120: Origin http://localhost:55328 not found in Access-Control-Allow-Origin header.
HTTP405: BAD METHOD - The HTTP verb used is not supported.
(XHR)POST - https://www.dropbox.com/home/folder1_

This is when I use this section

![image](https://user-images.githubusercontent.com/30706327/28946954-f8c82f72-7872-11e7-97e2-bd95991e0b2c.png)

Thanks.

**Comment by aliassad** [comment]
Actually your GrapeJS code is Running on Localhost:8080 u need to set cors header settings

**Comment by artf** [comment]
as already mentioned by @aliassad it's related to CORS settings, if you're uploading stuff directly from the browser to some other domain, the end point script should accept your requests via CORS.
