### ISSUE TITLE
Custom defined css classes do not work if I use editor.setStyle(css_text);

### ISSUE THREAD

**Issue by alikabeer32** [artf/grapesjs#2060]
I need to set styles using the data I receive from the database asynchronously. But then the css I composed manually gets removed. 
```js
const cssComposer = editor.CssComposer;
var sm = editor.SelectorManager;
var sel1 = sm.add('simple-div');
var rule = cssComposer.add([sel1]);
// Update the style
rule.set('style', {
  width: '100%',
  height:'auto',
  padding:'15px',
  float: 'left',
});
```
the above class .simple-div doesn't exist If I use setStyle()

**Comment by artf** [comment]
Use the [setRule](https://grapesjs.com/docs/api/css_composer.html#setrule) API
