### ISSUE TITLE
[QUESTION] How to place a component at the end of the canvas.

### ISSUE THREAD

**Issue by froderf** [artf/grapesjs#2061]
How can I put my footer at the end of the canvas?

I want the editor to not allow placing a block/widget below the footer.

example
```

<!-- only allow dragging/placing of widgets here -->

FOOTER
<!-- Should not have blocks/widgets below this -->

```

**Comment by artf** [comment]
You can use something like this
```js
const footer = '<div style="padding: 100px">My footer</div>';
editor.getWrapper().getEl().insertAdjacentHTML('afterEnd', footer);
```

**Comment by froderf** [comment]
@artf Do we have something like removeAdjacentHTML()
`editor.getWrapper().getEl().removeAdjacentHTML('afterEnd', footer);`

because when we used 
```
const footer = '<div style="padding: 100px">My footer</div>';
editor.getWrapper().getEl().insertAdjacentHTML('afterEnd', footer);
```
it keeps duplicating every after you reload the window.

--------------

I'm looking for a way to solve this but no luck :(
Seems like a bug?

**Comment by artf** [comment]
> Do we have something like removeAdjacentHTML()

getEl() gives you the HTMLElement instance so insertAdjacentHTML is from DOM API, not GrapesJS

> it keeps duplicating every after you reload the window.

... can you create a reproducible demo?
