### ISSUE TITLE
[Question] Can I disable media queries?

### ISSUE THREAD

**Issue by benvmatheson** [artf/grapesjs#2063]
Is it possible to disable media queries?

E.g. turn this:
`@media (max-width: 331px){
  .image-block{
    position:absolute;
    top:0;
  }
  .c976{
    width:331px;
    height:526px;
    position:absolute;
  }
}`

Into this:
`.image-block{
  position:absolute;
  top:0;
}
.c976{
  width:331px;
  height:526px;
  position:absolute;
}`

**Comment by benvmatheson** [comment]
I could remove these programmatically, but is it possible to tell grapes not to add media queries to CSS?

**Comment by artf** [comment]
Yes, you can use this option:
https://github.com/artf/grapesjs/blob/60c1755c57da02b57988fbe0e1a0321a5395728c/src/editor/config/config.js#L90-L93

**Comment by benvmatheson** [comment]
We're needing to allow selecting device sizes while editing, but need to remove media queries. As this is a bit of an edge case, I'm assuming I should expect media queries to always be applied if in device preview mode?

**Comment by artf** [comment]
> We're needing to allow selecting device sizes while editing

Indeed, you can

**Comment by benvmatheson** [comment]
Looks like that solves my issue. Thank you!
