### ISSUE TITLE
Issue Starting and building GrapesJS

### ISSUE THREAD

**Issue by Moikapy** [artf/grapesjs#2064]
I Clone, Downloaded/Unzipped, & checked out into an upstream I have in my fork to preview the changes and for some reason, they are failing 456 of the tests when I try to build and I get this error in the console.

![grapes error](https://user-images.githubusercontent.com/18318332/58892495-5506e680-86bc-11e9-9f82-784422821553.JPG)

**Comment by verdverm** [comment]
I can verify the same tests results as well, I came across a TODO somewhere about making all these pass.

**Comment by artf** [comment]
@Moikapy ok thanks, seems like the same issue of #2044 
I close this, let's keep talking there
