### ISSUE TITLE
[QUESTION] Page Limit 

### ISSUE THREAD

**Issue by tsuwunrut-carecloud** [artf/grapesjs#2066]
I'm currently using GrapesJS as a Letter/Form Composer, and it's been working wonderfully so far. However I'm just finishing up the last few requirements

- I'm scaling the canvas to the size of an A4 piece of paper so that when it prints, everything is consistent with the form they've built. However, I'm unsure whether or not there's a way of limiting my user from creating new lines once they've reached the "end" of the page. I have a height on both my editor, and my canvas. Yet this still does not prevent the user from hitting "enter" repeatedly to make the paper grow. 

- ^ If there is no way to limit a user from expanding the document, would it be possible replicate a behavior similar to a word document, meaning instead of expanding the document past its set height, the editor would create a new "page" or "paper"

**Comment by bloigge** [comment]
@tsuwunrut-carecloud - did you find a solution for your problem? I am facing something similar.

**Comment by bbart001** [comment]
I recently began a project with the exact same requirements as both of you. If anyone has any solutions, it would be fantastic to hear them.

**Comment by sagarneo11** [comment]
@tsuwunrut-carecloud, Can you please let us know if you find solution on above mentioned function?, would love to have same function in my app it would be really helpful if you could suggest.

**Comment by bharatnadkarni** [comment]
@tsuwunrut-carecloud @bloigge @sagarneo11 did any of you find a solution to this?

**Comment by ahmafi** [comment]
@artf Any comments on this?

**Comment by tomasz-zwak** [comment]
facing similar challenge now, has anyone solve this?
