### ISSUE TITLE
GrapesJs gradient plugin not working anymore

### ISSUE THREAD

**Issue by ssabrewolf** [artf/grapesjs#2068]
Hello GrapesJs team

After updating the grapesjs version form 14.0.59 i noticed the gradient plugin stopped to work,
i also checked the gradient demo page and i noticed the same behavior here
https://codepen.io/artf/pen/bYwdQG

Thanks in advance

**Comment by ssabrewolf** [comment]
hi @artf  i noticed you added the help wanted tag, i could try but could you give some tips or hypothesis about what could be the reason to not start from zero  wondering in the dark, of course im  asking because you seem to be the author of the gradient plugin, if not , please ignore this message

**Comment by artf** [comment]
@ssabrewolf yeah I'm the author of the gradient plugin but to be honest I've no idea what is happened, definitely a regression after some update in the Style Manager module. What I can say, is working fine with the v0.14.50 https://codepen.io/anon/pen/KjVBzd

**Comment by alikabeer32** [comment]
It's absurd but I find that if you type 'decoration' instead of Decoration, the plugin works! In the demo and in my code as well.

**Comment by artf** [comment]
Shame 😂 I totally forgot about the sector id change.
I should definitely print a warning if the property is not found.
Demo updated https://codepen.io/artf/pen/bYwdQG
Thanks @alikabeer32 ❤️
