### ISSUE TITLE
[BUG] `allowScripts: true` still deletes <script> tags

### ISSUE THREAD

**Issue by Sparragus** [artf/grapesjs#2069]
Hi all. Thanks for creating and maintaining this amazing project. 🙏 

## Bug Description

I have a block that inserts a script as specified here: https://grapesjs.com/docs/modules/Components-js.html#basic-scripts

When I drag the block to the canvas, the component will indeed have the script attached to itself. However, when I reload the page, the script is no longer there.

I've seen multiple issues where this is discussed, and they all seem to be resolve by adding

```js
const editor = grapesjs.init({
	...
	allowScripts: 1,
});
```

Examples:
https://github.com/artf/grapesjs/issues/1123
https://github.com/artf/grapesjs/issues/837
https://github.com/artf/grapesjs/issues/721

However, `allowScripts: 1` doesn't seem to be working for me.

## Expected

I expect the <script> to still be there because `allowScript: 1`.

## Reproducible Case
Here's a CodeSandbox where the bug can be reproduced: https://codesandbox.io/s/compassionate-gagarin-dclo5

Steps to reproduce:
1. Drag a "Button" block to the canvas.
2. Click the button. It displays an alert.
2. You can see the code for the script if you open the modal where the code is shown.
3. Reload the page.
4. Click the button again, no alert is shown.
5. Go see the code, and the <script> will no longer be there.

Here's a short video of me reproducing these steps: https://www.youtube.com/watch?v=g4fes1nU5h0

I hope this is enough information. If more is needed, I'll be happy to provide it.

Thank you. Cheers!

**Comment by ramakrishnachowdary** [comment]
Can you please provide the solution for this issue.

**Comment by artf** [comment]
Thanks for the report @Sparragus 
The problem here is when you use a function for the `script` inside Blocks. When the editor tries to store the JSON the structure is serialized but the function is not serializable so for that component an empty `script` string is stored.

I know that is what we indicate in the documentation but we used blocks only to show quick examples, actually, you should always create a custom component for the one with a script.

```js
editor.DomComponents.addType('custom-button', {
	model: {
		defaults: {
			tagName: "button",
		    type: "foo-button",
		    name: "Button",
		    content: "Button",
		    script: function() {
		      this.addEventListener("click", () => {
		        alert("Meow");
		      });
		    }
		}
	}
})
editor.BlockManager.add("button", {
  label: "Button",
  content: { type: 'custom-button' }
});
```

**Comment by Sparragus** [comment]
@artf Thank you for the clarification. Cheers.

**Comment by RJCAM** [comment]
Hello guys, sorry to bother but I just want to be sure if this method (creating a custom component) really works on you, because I tried your code and still not works when I reload the page, and I see in the console log "**Component type 'foo-button' not found**":
![image](https://user-images.githubusercontent.com/49693237/64342131-03c70580-cfd1-11e9-9d9f-0db36500a27c.png)
**BTW**: I needed to change -> **editor.BlockManager.add("button"** to -> **("button-block"** otherwise the button doesn't show as a new block, don't know why works on you but not on me.

**Comment by CKitisak** [comment]
Hi @artf ,
Thank you for your great works!

I would like to know if there any ways to make the script automatically fire after reload (in case of editing later) ?

any help would be appreciated. thank you.

my index.html file:
```<script src="node_modules/grapesjs/dist/grapes.min.js"></script>
  <script src="custom-components.js"></script>
  <script>
    var editor = grapesjs.init({
      container: '#gjs',
      allowScripts: 1,
      jsInHtml: false,
      plugins: ['custom-components'],
      canvas: {
        scripts: [
          'https://unpkg.com/ag-grid-community/dist/ag-grid-community.min.noStyle.js'
        ],
        styles: [
          'https://unpkg.com/ag-grid-community/dist/styles/ag-grid.css',
          'https://unpkg.com/ag-grid-community/dist/styles/ag-theme-balham.css'
        ]
      },
    });
  </script>
```


my custom-components.js file:
```
(function () {
  grapesjs.plugins.add('custom-components', (editor, options) => {
    editor.DomComponents.addType('my-table', {
      model: {
        defaults: {
          name: 'My Table',
          tagName: 'div',
          components: [
            {
              tagName: 'div',
              classes: ['ag-theme-balham'],
              script: function () {
                const elm = this
                const columnDefs = [...]
                const rowData = [...]
                new agGrid.Grid(elm, { columnDefs: columnDefs, rowData: rowData })
              }
            }
          ]
        }
      }
    })

    editor.BlockManager.add('my-table', {
      label: 'My Table',
      content: { type: 'my-table' }
    });
  })
}());
```

**Comment by artf** [comment]
@CKitisak 
Here 
```js
script: function () {
	const elm = this
	const columnDefs = [...]
	const rowData = [...]
	new agGrid.Grid(elm, { columnDefs: columnDefs, rowData: rowData })
}
```
you should add the code which checks if the library exists (what you're doing now is mixing 2 completely different contexts, explained better here #2181). In that case it will be actually loaded only if the user dropped in the page the `custom-components`.
But create its OWN component for the one containing the `script` property or you will face issues later.
