### ISSUE TITLE
[QUESTIONS] Stop the style manager from replacing AUTO with the pixel units

### ISSUE THREAD

**Issue by adamwpe** [artf/grapesjs#2070]
Not too sure how to explain it, but it appears that the style manager replaces 'AUTO' with the actual units. But if the user changes a value, e.g. margin-top. It saves the units, not the 'AUTO' value within the other fields that were not amended. Meaning the behavior of the div is unexpectedly different. e.g. no longer centered when the canvas is resized.

Example:

Before amending top-margin (centered on a small screen):
![image](https://user-images.githubusercontent.com/49768920/59130742-30369b80-8968-11e9-925e-fe9c8a0ceb98.png)

Before amending top-margin (centered on a largescreen):
![image](https://user-images.githubusercontent.com/49768920/59130762-3dec2100-8968-11e9-9ab4-9abdee91f43d.png)

Amending only the top-margin field:
![image](https://user-images.githubusercontent.com/49768920/59130379-2f513a00-8967-11e9-9035-ca9348064a4d.png)

Resize the canvas (ideally, the right and left margin should still be set to AUTO:
![image](https://user-images.githubusercontent.com/49768920/59130795-56f4d200-8968-11e9-8344-89f6f1423d10.png)

Is the expected behavior and is there anything I can do to prevent it?

**Comment by adamwpe** [comment]
One of my settings was incorrect during testing.

**Comment by danielwirz** [comment]
Hi @adamwpe 

I have the exact same issue. 
What setting did you change to solve this?

Thanks & best regards

**Comment by AnnaSu** [comment]
@adamwpe

I have the same issue. How did you solve it?
