### ISSUE TITLE
[QUESTIONS] show rte editor

### ISSUE THREAD

**Issue by fmr411** [artf/grapesjs#2072]
I want to ask, why when I want to display the rte editor with "editor.getSelected (). view.enableEditing ()" but there is an error "editor.getSelected (...). view.enable Edit is not a function", Thanks

**Comment by artf** [comment]
Actually, `enableEditing` method was removed and replaced with `onActive`, but to avoid any future change I'd recommend using this `editor.getSelected().trigger('active')`
