### ISSUE TITLE
[QUESTIONS] Trouble using urlLoad

### ISSUE THREAD

**Issue by AlejandroSuarezA** [artf/grapesjs#2073]
I've got an issue calling to my endpoint to load a template, it's doing a pre flight OPTIONS request but I cant find how to continue after the OK response

    componentDidMount() {
        this.editor = GrapesJS.init({
            container: '#grapeEditor',
            plugins: [gjsPresetNewsletter],

            storageManager: {
                id: 'gjs-',
                type: 'remote',
                urlLoad: 'http://localhost:9999/templateEndpoint',
                urlStore: 'http://localhost:9999/templateEndpoint',
                contentTypeJson: true
            }
        });
    }

    componentDidUpdate() {
        this.editor.load(e => console.log(e))
    }

This is my express server

    app.all('*', function (req, res, next) {

        res.header('Access-Control-Allow-Origin', '*');
        res.header('Access-Control-Allow-Methods', 'GET,PUT,POST,DELETE');
        res.header('Access-Control-Allow-Headers', 'Content-Type, Authorization');

        if (req.method == 'OPTIONS' || req.path.indexOf('favicon.ico') >= 0) {
            console.log('options method... lets pass...');
            res.sendStatus(200);
        }
        else {
            next();
        }

    });

![image](https://user-images.githubusercontent.com/22684283/59199300-ecc17480-8b95-11e9-80c6-4071032685f8.png)

**Comment by verdverm** [comment]
Is there more to you server? Does next() actually reach a handler?

**Comment by artf** [comment]
Try to check errors in console, probably you miss something in your CORS configuration. Try to start only with `res.header('Access-Control-Allow-Origin', '*');`
BTW I close this as it's not related to grapesjs itself
