### ISSUE TITLE
Can not use space while editing drop down menu in block manager

### ISSUE THREAD

**Issue by VM8198** [artf/grapesjs#2074]
hello @artf 
I have applied a drop down menu in block manager the code is given below

```js
bm.add("dropdown-menu-in-navbar",
        {
          label: '<div class="gjs-block-label">Dropdown Menu</div>',
          tab: "1",
          category: "Others",
          removable: true,
          draggable: true,
          droppable: true,
          highlightable: true,
          copyable: true,
          editable: true,
          allowSpacing: true,
          type: "default",
          attributes: {
            class: 'fa fa-ellipsis-h',
            title: 'Insert Dynamic Menu of Navigation'  
          },
          content: '<div data-gjs-type="default" class="dropdown"> <span class="dropdown-text">Dropdown </span> <div data-gjs-type="default" data-gjs-editable="true" class="dropdown-menu"> <a href="index.html"> Dropdowm 1 </a> </div> </div>'
        }
      );
```

It works fine but whenever I try to change the dropdown lists it doesn't applies space.
It takes all letters but space is ignored by the editor 
please help

**Comment by verdverm** [comment]
Try looking at the DOM to see what your drop-down item in the canvas to see what html elements are created. Does that output look like the html you expect?

**Comment by VM8198** [comment]
@verdverm yes in DOM the output looks exactly same as I needed

**Comment by artf** [comment]
Not able to reproduce with you code, create a reproducible demo please.
BTW properties like removable, draggable, droppable are part of the component definition not blocks...

**Comment by VM8198** [comment]
hello @artf 
I am imolementing grapesjs in my website as a website builder with which the user can create websites as their need. So, I have given a block for drop-down menu so that user can easily create drop-down menu and it is working fine too.
But when I am trying to change the menu content after dropping the block it is not getting the space.
If i change the menu name with space it is not considering the space anymore
The link of video is attached here...https://drive.google.com/file/d/1bgb6QibnPPU6qGbLDudOD9xeMGtmvsnG/view

**Comment by artf** [comment]
Hi @VM8198 one more time, create a reproducible demo, otherwise I'm not able to help you...
