### ISSUE TITLE
[bug] style manager slider min value bug

### ISSUE THREAD

**Issue by starcraft0429** [artf/grapesjs#2075]
when I set slider to 0 (min value) the slider return -1 value and this style property is ingored completely since it is not valid css. for example ```border-width: -1px !important```

I found the code why this happens only min value.
in the [ style manager slider view code ](https://github.com/artf/grapesjs/blob/dev/src/style_manager/view/PropertySliderView.js#L37)

when slider value not min value, this works well. but if value is set to minimum(for example 0), second model.set didn't work and it break the real value.

Isn't possible set value standard without -1 and +1?

for short fix, how can I extend this function?

**Comment by storyofyours** [comment]
@artf Be our hero ;)

**Comment by artf** [comment]
Guys, it's really important to follow the ISSUE template, I don't even know which version do you use? Can you create a reproducible demo because I don't understand how to reproduce it

**Comment by arthuralmeidap** [comment]
@santiph could you provide us a code example? I have tried to simulate it but without success.
