### ISSUE TITLE
Blocks with HTML Conditionals

### ISSUE THREAD

**Issue by DevonHansen** [artf/grapesjs#208]
Is there anyway to include HTML conditionals when exporting? I have them in my blocks but when use `editor.getHtml();` they are not included in the output (assuming because you are ignoring comments?).

Was looking at using DomComponents but this wont work since it expected both start and end tags to be the same. In case of conditionals it would look like:

``

**Comment by artf** [comment]
If not yet done check the [Components](https://github.com/artf/grapesjs/wiki/Components) wiki and add a new custom Component in this way:
```js
    var textnodeType = domc.getType('textnode');

    domc.addType('comment', {
      model: textnodeType.model.extend({
        toHTML() {
          return `<!--${this.get('content')}-->`;
        },
      },{
        isComponent(el) {
          if (el.nodeType == 8) {
            return {
              tagName: 'NULL', // just need this to avoid some parser rule
              type: 'comment',
              content: el.textContent
            }
          }
        },
      }),
      view: textnodeType.view,
    });
```

**Comment by alperenuzun** [comment]
Hi Artur,

First of all, thank you for sharing such a great project :)
I want to tell you a problem about this issue that I have experienced.

I was using grapesjs - v0.5.41 before using grapesjs - v0.10.7 and i wanted to add category structure for blocks in grapesjs newsletter plugin. And then, i realize that grapesjs - v0.10.7 already contained what i want. So, category structure is working very well but, above code doesn't work with grapesjs - v0.10.7 and doesn't include conditional comments. However, it worked with v0.5.41.

What is the reason for this? Thank you for your answers.
