### ISSUE TITLE
[Question]Is it possible to update existing pages when components are modified?

### ISSUE THREAD

**Issue by Femonzor** [artf/grapesjs#2082]
For example, a custom component is used by some existing published pages. When the component is modified, maybe the style is adjusted, or the content property of it is completely changed, I want to notice those pages to update, and when I preview those pages, they should be rendered with the latest component.

Is it possible?

**Comment by artf** [comment]
If the property you've changed was stored, obviously when you load the component back its properties are going on top of the component definition. So, the only solution would be to avoid storing those properties
