### ISSUE TITLE
[QUESTION] model.get('toolbar') always return null

### ISSUE THREAD

**Issue by afdallah** [artf/grapesjs#2083]
Hi @artf 
I am trying to add a custom toolbar to my custom component without changing the default toolbar. So I expect it to be like [movable, copyable, removable, **newToolbar**]. I use this #266 as a reference.

```javascript
model: {
  // ...
  initToolbar () {
    const tb = this.get('toolbar')

    console.log(tb) // Return null
    tb.unshift({
      attributes: { class: 'fa fa-plane' },
      command: 'some-command'
    })

    this.set('toolbar', tb)
  },
  // ...
}
```

But strangely `this.get('toolbar')` always return null.
Is this something normal? 

I got this instead
![toolbar image](https://i.imgur.com/TsPhISr.png)

**Comment by artf** [comment]
Yes, if you override the original `initToolbar` method the `toolbar` property is never created, so you have to call the parent one first. Try with this component creation helper
```js
extendFn: ['initToolbar'], // array of model functions to extend
model: {
  // ...
  initToolbar () {
```

**Comment by afdallah** [comment]
Actually, I have tried that before but still not work.

Here is the [Demo](https://jsfiddle.net/afdallah/5t63s8g0/11/)

I also try a different method but it's kind of dirty. [code](http://prntscr.com/o9yw6c)
It would be cool if I just extend it like the way it should be.

**Comment by artf** [comment]
The `extendFn` was added from https://github.com/artf/grapesjs/releases/tag/v0.14.61 in the demo you're using the 0.14.57

**Comment by afdallah** [comment]
I am so sorry, it's my mistake.  Thanks for your guidance
