### ISSUE TITLE
[QUESTION] Is it possible to save templates by name, then provide user list of templates like files?

### ISSUE THREAD

**Issue by gobanana66** [artf/grapesjs#2084]
I've got firestore storage set up for remote storage, and currently it correctly saves and loads from storage. However, I'd like the user to be able to name the template and have it save with that name. Then provide the user with a list of saved templates that they can load up as they choose. Is this possible to do?

**Comment by artf** [comment]
It's not something built-in in the editor but for sure you can implement it by yourself
