### ISSUE TITLE
[QUESTION] how a modal/floating window comes on top of existing page on hover event

### ISSUE THREAD

**Issue by megarg** [artf/grapesjs#2085]
My Goal is to be able to create a page like (just an example). Want to create using editor and not code
https://www.progressive.com/
I am not able to create the header row with grapesjs because of I cannot define how a modal/floating window comes on top of existing page on hover event 

regards
-Ashish

**Comment by artf** [comment]
Start by reading how to implement [custom components](https://grapesjs.com/docs/modules/Components.html)
