### ISSUE TITLE
[Question] Defining CSS in style manager

### ISSUE THREAD

**Issue by megarg** [artf/grapesjs#2086]
Can we define CSS in editor style manager. Primarily:
- What is "state" and "class" in editor style manager
- If I define a custom class to a element. How to define CSS for that class. What is I want to assign the same class to another element so there should be a mechanism to define CSS at class level and not at element level (one class can be assigned to multiple elements)

regards
-Ashish

**Comment by artf** [comment]
It works already like this, if you select a component with a class you will edit the CSS style assigned to that class and you can add it to other components to see the same style
