### ISSUE TITLE
General Questions should be asked else where

### ISSUE THREAD

**Issue by verdverm** [artf/grapesjs#2087]
@artf I'm wondering if you would be interested in creating an alternative forum for question usage. Most of the issues seem to be question that would be better answered in a chat or forum, or by reading the docs...

My issue is that it pollutes the issues section of the repository, when most are support or new user questions.

What do you think?

**Comment by artf** [comment]
Thanks for the suggestion @verdverm IDK to be honest, we have already the [Discord Chat](https://discordapp.com/invite/QAbgGXq) but it's more community driven and I'm not so active there. IMHO I prefer using only one channel for the communication of questions/issues about the framework and Github is a good fit for me
