### ISSUE TITLE
[QUESTIONS] Can I build quiz and polling questions in grapeJS

### ISSUE THREAD

**Issue by revathitarento** [artf/grapesjs#2088]
I really like the features of grapeJS, it would be very helpful to know if I will be able to extend it with creating questions and answers, polling, Multiple choice questions and answers, Please guide me how to start with. It would be a great help

**Comment by verdverm** [comment]
So one significant factor is the requirement for third party scripts, is this the case in your situation?

**Comment by afdallah** [comment]
I suggest you start with this [https://github.com/artf/grapesjs-preset-webpage](https://github.com/artf/grapesjs-preset-webpage). And start building components from there
