### ISSUE TITLE
How to reload block content based on trait value change

### ISSUE THREAD

**Issue by abhilashks1985** [artf/grapesjs#2089]
I have added new block with some trait value and i want to pass that trait value with ajax call. 
Also should be able to reload block when trait value changes. Is that possible? I am pasting my block code.

editor.BlockManager.add('loginBlock', {
        label: 'Login Block',

        attributes: {
            class:'fa fa-sign-in',
            title: 'My title',
            my_field: 'My title'
        },

        content: {
            traits: [{
                type: 'text',
                label: 'Test',
                name: 'model-prop-name',
                changeProp: 1
            }],
            myModelPropName: 'login',
            script: "" +
            "myVar3 = this;" +
            "var xhttp = new XMLHttpRequest();" +
            "xhttp.onreadystatechange = function() {" +
            "if (this.readyState == 4 && this.status == 200) {" +
            "myVar3.innerHTML = this.responseText;" +
            "}" +
            "};" +
            "xhttp.open('GET', '/?index=apiv2', true);" +
            "xhttp.send();"
        }
    });

**Comment by artf** [comment]
The `script` content part has NOTHING to do with the editor components... read carefully [Components & JS](https://grapesjs.com/docs/modules/Components-js.html)

**Comment by igorMarynich** [comment]
try use components methods, for example: editor.getSelected().components(`your content`)
