### ISSUE TITLE
How to add more options to codemirror running inside grapesjs

### ISSUE THREAD

**Issue by rgcarrasqueira** [artf/grapesjs#209]
Hi Art!

I'm doing great progress with Grapesjs. I've found a way to edit the code inside a modal window and it reflects immediately on canvas. But I'm facing some problems in how setup the codemirror to work with Grapes.

For example, i'm trying to add the plugin that allows search and replace inside the code, I'm just calling the JS and nothing is happening.

If I add a setting like that:

```
odeViewer = editor.CodeManager.getViewer('CodeMirror').clone();
    
    
    codeViewer.set({
        codeName: 'htmlmixed',
        readOnly: 0,
        theme: 'hopscotch',
        autoBeautify: true,
        autoCloseTags: true,
        autoCloseBrackets: true,
        //lineWrapping: true,
        styleActiveLine: true,
        smartIndent: true
       # Where I'm trying to add:
        indentWithTabs: true,
    });
    
    codeViewer.init(document.getElementById('code'));
    viewer = codeViewer.editor;
```

The editor stops to work. Any clue about this?

Thanks

**Comment by adamdyson** [comment]
@rgcarrasqueira Could this simply be because the object data being set is malformed?

```
odeViewer = editor.CodeManager.getViewer('CodeMirror').clone();
    
    
    codeViewer.set({
        codeName: 'htmlmixed',
        readOnly: 0,
        theme: 'hopscotch',
        autoBeautify: true,
        autoCloseTags: true,
        autoCloseBrackets: true,
        //lineWrapping: true,
        styleActiveLine: true,
        smartIndent: true // Missing comma
       # Where I'm trying to add:
        indentWithTabs: true, // Remove trailing comma just to be safe
    });
    
    codeViewer.init(document.getElementById('code'));
    viewer = codeViewer.editor;
```

**Comment by artf** [comment]
@rgcarrasqueira unfortunately, the code viewer part is not so well designed and should be definitely refactored, at the moment few options available are just [hard-coded](https://github.com/artf/grapesjs/blob/dev/src/code_manager/model/CodeMirrorEditor.js) and it's not possible to add other options

**Comment by vtista** [comment]
so there is nothing we can do about this code editor? @artf

**Comment by artf** [comment]
not yet
