### ISSUE TITLE
Create Traits for navbar plugin 

### ISSUE THREAD

**Issue by alialrabi** [artf/grapesjs#2093]
Hi Artf,
i have two question:
1- i want to  adding  traits to Navbar component  instead of default one and didnt know its type 
2-  i want to add fixed property to navbar ( position: fixed) in traits ( select dropdown )  , so  i can select it or not to add it to navbar in editor, how can i implement it?

**Comment by artf** [comment]
Please read how to extend [Components](https://grapesjs.com/docs/modules/Components.html)

**Comment by alialrabi** [comment]
i know that we can add traits by know the type of components to extend , but i dont how to extend navbar component , can u show me how to extend this component please ?

**Comment by alialrabi** [comment]
@artf

**Comment by artf** [comment]
> i know that we can add traits by know the type of components to extend, but i dont how to extend navbar component

Exactly as it is explained in the documentation...
```js
editor.DomComponents.addType('the-type-to-extend', {
  model: {
    defualts: {
		traits: [
			// place here your new traits...
		]
	}
  }
});
```

**Comment by alialrabi** [comment]
@artf thank u for explanation but i install gjs-navbar  and its type is null value so i cant extend  , can i add type for it to extend   to identify(''the-type-to-extend'')  ?

**Comment by artf** [comment]
Read the [summary](https://github.com/artf/grapesjs-navbar#summary) from the plugin, there is only ONE custom component: `burger-menu` so this is why the type is null, it's just a base component
