### ISSUE TITLE
[QUESTIONS] add sector in first index

### ISSUE THREAD

**Issue by fmr411** [artf/grapesjs#2094]
I want to add a sector, but in the top position (above the general), thank you

![sector atas](https://user-images.githubusercontent.com/15244481/59987212-197c8e00-9664-11e9-8356-107ba3573bbe.gif)

**Comment by artf** [comment]
Currently, it's not possible doing it via API (only via initial config), but I'll add an option in the next release, so you'd do:
```js
editor.StyleManager.addSector('Test', {
	name: 'New sector',
	...
}, { at: 0 })
```

**Comment by fmr411** [comment]
Thank you, now I delete and re-create the sector in the order
