### ISSUE TITLE
Is there any possibility to add the title attribute into the iframe tag of video ?

### ISSUE THREAD

**Issue by Andiswamy** [artf/grapesjs#2095]
@artf  Can you help me?
     When i click a video and go to settings , where i can select the youtube and i found that when i view the code , there is no title attribute present in the iframe tag. Is there any possibility to add the title attribbute into the iframe tag of video ?
`<iframe id="iyat" src="https://www.youtube.com/embed/au2pDQ_tgD8?&loop=1&playlist=au2pDQ_tgD8" width="300" height="150" data-mce-fragment="1"><source src="" style="box-sizing: border-box;" />Your browser does not support the video tag.</iframe>`

**Comment by artf** [comment]
You can [extend the component](https://grapesjs.com/docs/modules/Components.html) and add your title trait
