### ISSUE TITLE
Class not exported for body

### ISSUE THREAD

**Issue by benvmatheson** [artf/grapesjs#2096]
1. Go to https://grapesjs.com/demo.html
2. Clear canvas
3. Click on body, add class, apply background color
4. Background color now appears
5. Click `Export` -> Export to Zip
6. Open the Zip file and look at the `index.html` file. While the class was created in style.css, the class name was never applied to `<body></body>` in the html.

**Comment by florinr1** [comment]
I'm experiencing the same problem. 
The wrapper class attribute is set but the editor.getHtml() returns "<body></body>".
I'm initalizing GrapesJS using:
 {
      fromElement: true,
      autorender: 0,
      // Size of the editor
      height: '100%',
      width: '100%',
      showOffsetsSelected: true,
      log: true,
      allowScripts: 1,
      mediaCondition: 'min-width',
      exportWrapper: 1,
      wrapperIsBody: 1,
      clearStyles: 0,

      domComponents: { storeWrapper: 1 }
}
