### ISSUE TITLE
[Bug] IE11, Entering long text doesn't wrap automatically like in chrome / firfox

### ISSUE THREAD

**Issue by Jyamurugan** [artf/grapesjs#2098]
Entering long text doesn't wrap automatically  like in chrome / firefox
![ie11_grapesjs](https://user-images.githubusercontent.com/14156356/60097729-9cd7d580-9771-11e9-909a-73fc7c5adb2e.JPG)

**Comment by afdallah** [comment]
Simple CSS might do the trick. [stackoverflow](https://stackoverflow.com/questions/35111090/text-in-a-flex-container-doesnt-wrap-in-ie11)
