### ISSUE TITLE
When moving the Canvas Div to a bottom of a html page the drag icon location does not correspond to the canvas position. 

### ISSUE THREAD

**Issue by altalker** [artf/grapesjs#210]
When moving the Canvas Div to a bottom of a html page the drag icon location does not correspond to the canvas position.  (it displays off the canvas on the top of the page)
<body>
....other html elements...
....
......
......
    <div id="gjs" style="height:660px; overflow:hidden;">
   
    </div>

**Comment by artf** [comment]
I think I don't get exactly what do you mean, can you provide some example?

**Comment by altalker** [comment]
![image](https://user-images.githubusercontent.com/29933877/29083066-5410c144-7c1c-11e7-8a87-296b0ee3f9e2.png)
After moving the canvas location to the bottom of the screen, the Drag icon will be placed above the canvas and will not correspond to cursor position.

**Comment by artf** [comment]
Canvas location? your canvas seems to be in the correct position, maybe you mean moving the entire editor down?!? Anyway, try to trigger this after you moved it down `editor.trigger('change:canvasOffset')`

**Comment by altalker** [comment]
Yes, moving the div section containing the editor down causes this issue. 
 editor.trigger('change:canvasOffset') does not correct this issue.

**Comment by artf** [comment]
Try to change the Device select and see if it corrects the position

**Comment by altalker** [comment]
It seems that the scroll position of the document makes the difference. If the document main page scroll bar is on top position the drag icon will be placed correctly. However, when scrolled down then the drag icon is off its drag position.

**Comment by artf** [comment]
ok, but did you try to update the device select?

**Comment by altalker** [comment]
I tried and device select did not make a difference. Only the outer scroll bar position alters the drag icon location

**Comment by artf** [comment]
Ok I need to see your code because I can't reproduce it

**Comment by rgcarrasqueira** [comment]
@altalker I've suggest to place a screencast here showing what is happening. There is a program called Kap that helps a lot on trying to explain the problems.

**Comment by artf** [comment]
any update @altalker?

**Comment by altalker** [comment]
I was on vacation. I tried device select. If the div <div id="gjs"> is on top the cursor will show the correct position. However if scrolled down and the div is below other content the cursor if off.
![image](https://user-images.githubusercontent.com/29933877/29477461-60c930de-841d-11e7-965b-03f1b8ab7a13.png)

![image](https://user-images.githubusercontent.com/29933877/29477473-688ad5de-841d-11e7-9719-eb33adb91e58.png)

**Comment by artf** [comment]
seems like an old issue for me... @altalker  Are you sure you're using the last version?

**Comment by artf** [comment]
ping @altalker

**Comment by altalker** [comment]
Latest version.  I also removed some code blocks that were not compatible with IE 11 and caused errors

**Comment by artf** [comment]
post your code @altalker because if I can't reproduce it I can't help you
