### ISSUE TITLE
[QUESTIONS]  change the class style (like color: white to color: red) 

### ISSUE THREAD

**Issue by fmr411** [artf/grapesjs#2100]
is it possible to change the class style (like color: white to color: red) in the trait, I create a new type, I want to change the style in onChange event. I have tried using setcustomparsercss but it doesn't work, Thanks 
![Screenshot_8](https://user-images.githubusercontent.com/15244481/60148286-abb69a80-97fa-11e9-9d22-7ad939a2d30c.png)

**Comment by artf** [comment]
I think you're looking for this: https://grapesjs.com/docs/api/css_composer.html#setrule
eg. `editor.CssComposer.setRule('.my-class', { color: 'red' });`
