### ISSUE TITLE
[QUESTION] Custom Component dragging issue

### ISSUE THREAD

**Issue by imanubhardwaj** [artf/grapesjs#2103]
This is how I've created a custom component:

```
comps.addType('custom-video', {
  extend: 'image',
  isComponent: function (el) {
    if (el.getAttribute && el.getAttribute('element-type') === 'custom-video') {
      return {type: 'custom-video'};
    }
  },
  model: {
    defaults: {
      'video-preview-type': 'gif',
      traits: [{
        type: 'select',
        label: 'Type',
        name: 'video-preview-type',
        options: [{value: 'gif', name: 'GIF'},
          {value: 'image', name: 'Image'}],
        changeProp: 1
      }],
      selectable: true
    },
    init: function () {
      this.listenTo(this, 'change:video-preview-type', this.updateSrc);
    },
    updateSrc: function (component, value) {
      const attributes = component.attributes.attributes;
      let src;
      if (value === 'gif') {
        src = attributes['gif'];
      } else if (value === 'image') {
        src = attributes['image'];
      }
      component.view.$el.find('img').attr('src', src);
      this.set('src', src);
    }
  },
  view: {
    events: {
      dblclick: function () {
        postDoubleClickEvent(EditorEvents.VIDEO_DOUBLE_CLICK);
      }
    }
  }
});
```

This is my custom block:

```
blockManager.add('Video', {
  label: 'Video',
  content: '<a style="display: inline-block"><img element-type="vaetas-video" style="width: 400px; object-fit: cover" src="https://argoswimvideo.com/wp-content/uploads/2017/11/video-placeholder-1280x720-40.jpg"></a>',
  attributes: {
    class: 'gjs-block fa fa-film',
    title: 'Insert Video'
  }
});
```

The thing is that I have wrapped the image tag inside <a> tag when it is rendered to canvas. When I click on the element and try to drag it, only <img> tag gets dragged and <a> remains on it's original place. 

[Live demo](https://screencast-o-matic.com/watch/cq1t22TRoF)

**Comment by artf** [comment]
Well, I see 2 different solutions for this case:
1. Easy and fast, make the `custom-video` component not draggable, so you have to drag the parent to move it. The tiny downside is more from UX side, you force users to select the parent.
2. More solid solution. Make the `<a>` element a custom component itself, something like `custom-video-wrapper` which should contain by default the `custom-video` component
```js
comps.addType('custom-video-wrapper', {
  model: {
    defaults: {
	   tagName: 'a',
	   components: { // here you define default components
		type: 'custom-video',
		selectable: false,
		hoverable: false,
	   },
       ...
	   traits: ... 
// Probably you'll need the same traits/properties 
// but on their changes you'll propagate them to the 
// children 'custom-video' component
```

**Comment by imanubhardwaj** [comment]
Thanks @artf but a new problem is arising now, when I drag the **custom-video-wrapper** component across the canvas, **custom-video** isn't dragged with it, only the <a> tag is dragged. 

[Live Demo](https://screencast-o-matic.com/watch/cqifXnO1w6)

**Comment by artf** [comment]
No wait, you dragged the component but the old one is still there?!? 
Are you able to create a reproducible demo or at least a demo with only your implementation of `custom-video-wrapper`?

**Comment by imanubhardwaj** [comment]
@artf Steps to replicate the issue:

Drag a video component and a button component try dragging the video component around the button by clicking on the video component.

Codepen => https://codepen.io/mnbhardwaj888/pen/rEEMGE

Video => https://screencast-o-matic.com/watch/cqiolwOYKh

**Comment by artf** [comment]
Ah wait you can't drag components like this, at least, now even with the current version and you're using an old one (I added this functionality but it'll be ready only in the next release). 

So, the drag effect you have now is an issue from the extended `image` component, where it activates the Native Drag&Drop and it's acting like an ADD operation, this is why is not moving. 

For now, you have to update your events likes:
```js
events: {
      dblclick: function () {
       console.log('double click video');
      },
	  dragstart: 'noDrag', // prevent drag on images
    },
```
probably I'll move this event outside of `events` to make it more hidden.

Wait for the next release to have the ability to move components by drag

**Comment by imanubhardwaj** [comment]
@artf I'm still not able to get it right, I have vaetas-video (non editable component) inside custom-video-wrapper component and when I double click on custom-video-wrapper it sets a random src on vaetas-video but when I try to double click on the custom-video-wrapper again, it isn't interactive anymore. Debugger shows current selected element is still custom-video-wrapper but it doesn't react to double click on it.

Codepen => https://codepen.io/mnbhardwaj888/pen/rEEMGE?editors=1010

Video => https://drive.google.com/file/d/1DDGoAVqm9iAyEpAOjeqrs0nS2kRKhNnL/view?usp=sharing

**Comment by artf** [comment]
With this
```js
view: {
    dragstart: 'noDrag'
  }
```
you're still letting the view capturing your click events, so fix it:
```js
view: {
    events: {
      dragstart: 'noDrag'
    }
  }
```
