### ISSUE TITLE
[BUG] Incorrect border radius controls

### ISSUE THREAD

**Issue by wldyslw** [artf/grapesjs#2105]
Changing `border-bottom-left-radius` prop changes bottom right radius, and vise versa.
Reproducing: 
1. Go to https://jsfiddle.net/szLp8h4n
2. Add, for instance, any image
3. Try to change `border-bottom-left-radius` prop in Decorations section

Playing around config didn't help much, the best one fixes naming problem but reorder controls themselves. So, the config like:
```
{
    property: 'border-radius',
    type: 'composite',
    properties: [
        {
            name: 'Border Top Left Radius',
            property: 'border-top-left-radius',
            type: 'integer',
            defaults: '0px',
            min: 0,
            units: ['px', '%'],
        },
        {
            name: 'Border Top Right Radius',
            property: 'border-top-right-radius',
            type: 'integer',
            defaults: '0px',
            min: 0,
            units: ['px', '%'],
        },
        {
            name: 'Border Bottom Left Radius',
            property: 'border-bottom-right-radius',
            type: 'integer',
            defaults: '0px',
            min: 0,
            units: ['px', '%'],
        },
        {
            name: 'Border Bottom Right Radius',
            property: 'border-bottom-left-radius',
            type: 'integer',
            defaults: '0px',
            min: 0,
            units: ['px', '%'],
        },
    ],
},
```
...results in:
![image](https://user-images.githubusercontent.com/13451336/60348936-36e58b00-99c9-11e9-88f8-cd761d8316e4.png)
(notice bottom radius controls reorder)

**Comment by artf** [comment]
Correct, the current default order is wrong but as the `composite` type **follows the CSS order of the `border-radius` property** the result will be exactly like the one achieved by you. In case you need to change the ordering of composite properties I'd suggest adding this CSS style
```css
.gjs-sm-property__border-bottom-right-radius {
    order: 1;
}
```
