### ISSUE TITLE
Traits not appear in edit mode when i update grapes version

### ISSUE THREAD

**Issue by alialrabi** [artf/grapesjs#2106]
Hi artf, 
i make traits for specific component ,when i saved  this component as a json and load again in editor the traits were load correctly and there is no proplem , when i update version of grapesjs traits appear only in first time , when load component again default trait was exist , how can i load traits again , and appear it in edit mode ?

**Comment by artf** [comment]
@alialrabi How do you define traits? Inside blocks or custom components?

**Comment by alialrabi** [comment]
@artf  i have created traits like this 
        domComps.addType('courseTool', {
            model: dModel.extend(
                {
                    init() {
                        this.listenTo(this, 'change:type', this.doStuff);
                    },
                    doStuff() {                     
                        });
                    },
                    defaults: Object.assign({}, dModel.prototype.defaults, {
                        traits: [
                            {
                                name: 'button',
                                label: 'Add',
                                type: 'buttonModal',
                                changeProp: 1

                            },
                            {
                                type: 'select',
                                label: 'Page',
                                name: 'type',
                                options: this.pagesList,
                                changeProp: 1,
                            },
                            {
                                type: 'input',
                                label: 'Link',
                                name: 'type',
                                changeProp: 1,
                            },
                            {
                                placeholder: 'Type your text here',
                                type: 'select',
                                label: 'Target',
                                name: 'Target',
                                options: [{ value: '', name: 'This window' }, { value: '_blank', name: 'New window' }],
                                changeProp: 1,
                            },
                        ],
                    }),
                },

                {
                    isComponent: function (el) {
                        if (el.tagName == 'div') {
                            return { type: 'asset' };
                        }
                    },
                },
            ),

            view: dView,
        });

**Comment by artf** [comment]
@alialrabi you're defining your component with a name `assetType` but then in isComponent the type is `asset`

**Comment by alialrabi** [comment]
@artf  this is not the proplem when i update it still same proplem , are this way that i made  is correct and it save traits in database? u say before that i will delete traits when saving components. if traits didnt save with components how to load it in editor with custom components in edit mode ?
