### ISSUE TITLE
[BUG] Tailwind flex classes are not working

### ISSUE THREAD

**Issue by inventorbit** [artf/grapesjs#2109]
Thanks for providing the amazing framework and making it opensource.  I'm looking to use Tailwind with GrapesJS, unfortunately grapesjs replaces "/" with "-" in the selector. Is it possible to override this?

When I try to drag and drop responsive columns in canvas

```
<!-- Two columns -->
<div class="flex mb-4">
  <div class="w-1/2 bg-gray-400 h-12"></div>
  <div class="w-1/2 bg-gray-500 h-12"></div>
</div>
```

It replaces them to:

```
<div class="flex mb-4">
  <div class="w-1-2 bg-gray-400 h-12">Drop Your Content
  </div>
  <div class="w-1-2 bg-gray-500 h-12">Drop Your Content
  </div>
</div>
```

How can I fix this issue? Please help me.

**Comment by artf** [comment]
#1703 waiting for a help 😬

**Comment by gavinhewitt** [comment]
> Thanks for providing the amazing framework and making it opensource. I'm looking to use Tailwind with GrapesJS, unfortunately grapesjs replaces "/" with "-" in the selector. Is it possible to override this?
> 
> When I try to drag and drop responsive columns in canvas
> 
> ```
> 
> <div class="flex mb-4">
>   <div class="w-1/2 bg-gray-400 h-12"></div>
>   <div class="w-1/2 bg-gray-500 h-12"></div>
> </div>
> ```
> 
> It replaces them to:
> 
> ```
> <div class="flex mb-4">
>   <div class="w-1-2 bg-gray-400 h-12">Drop Your Content
>   </div>
>   <div class="w-1-2 bg-gray-500 h-12">Drop Your Content
>   </div>
> </div>
> ```
> 
> How can I fix this issue? Please help me.

What's your progress on making grapes work with Tailwind @inventorbit? Would love to see!

**Comment by chrisreedio** [comment]
> What's your progress on making grapes work with Tailwind @inventorbit? Would love to see!

@artf , I'm also curious if there is any progress on this or an available work around? 

Thanks for your time developing grapes!

**Comment by artf** [comment]
You can already define your escape strategy for selectors
https://github.com/artf/grapesjs/blob/6296bf8c970f700aa69e44728b7db80833452f69/src/selector_manager/config/config.js#L15-L17
