### ISSUE TITLE
Issue on getting html and css while editing

### ISSUE THREAD

**Issue by logeshkrishna0** [artf/grapesjs#2111]
Hi, Hope you all have a good day. I'm looking on edit html function. In that, I changed the view of edit window like export modal. (ie, Separate window for Html and CSS). I can edit the content. I need to get the content (html & CSS) which is in modal window while I click the save button. Now I used ```$editor.view.el.outerText```. It gives the content for minimum amount of CSS. If I edit the large block, the outerText couldn't return the full CSS. Any other way to get modal html & CSS while saving? 

![edit](https://user-images.githubusercontent.com/52228872/60480649-ef504f00-9ca7-11e9-9e85-1e1fa8c1ffb7.png)

**Comment by artf** [comment]
I think you're looking for [`getHtml`](https://grapesjs.com/docs/api/editor.html#gethtml) and [`getCss`](https://grapesjs.com/docs/api/editor.html#getcss)
