### ISSUE TITLE
Disable event.preventDefeault() for anchor onClick event

### ISSUE THREAD

**Issue by metamohitsharma** [artf/grapesjs#2114]
I want to open a modal on clicking to anchor in the provided html in grapesjs Editor.
I have bind onClick event on anchor but on clicking to that anchor takes to prevDef method of grapesjs which triggers 'event.preventDefault()'.
So is there a way to disable it or a way to open a modal on clicking to that modal?

**Comment by metamohitsharma** [comment]
I want to open a modal on clicking to anchor in the provided html in grapesjs Editor.
I have bind onClick event on anchor but on clicking to that anchor takes to prevDef method of grapesjs which triggers event.preventDefault().
So is there a way to disable it or a way to open a modal on clicking to that modal?

**Comment by artf** [comment]
Can you show use a live demo of your example?

> I want to open a modal

The modal from the template or the one from GrapesJS?
