### ISSUE TITLE
[Question] Attributes not loading on editor

### ISSUE THREAD

**Issue by sdrebel** [artf/grapesjs#2117]
Hi @artf ,

I have created some custom components with traits. I save the file and reload not able to see the attributes in the editor and in preview mode. However those attributes can be seen in the code manager. 
Is there anyway to make show it? If i give any event based on the attributes events are not getting triggered in preview mode. 

Component in the editor
![attributes1](https://user-images.githubusercontent.com/19382262/60640782-6de2f300-9e46-11e9-8100-b396c0b075fa.jpg)

Component in the code manager
![attributes2](https://user-images.githubusercontent.com/19382262/60640781-6de2f300-9e46-11e9-8304-554f7f8c2952.jpg)

**Comment by artf** [comment]
Please read carefully this part https://grapesjs.com/docs/modules/Storage.html
if it's still not working, open a bug issue and create a reproducible demo
