### ISSUE TITLE
Multiple select option 

### ISSUE THREAD

**Issue by tuanleincepit** [artf/grapesjs#2119]

**Comment by tuanleincepit** [comment]
![Screen Shot 2019-07-05 at 3 39 35 PM](https://user-images.githubusercontent.com/46736391/60709650-29854f00-9f3b-11e9-8301-275fe9f6bdde.png)
Hi,
please help me add multiple select in categories. Thanks!

**Comment by adamwpe** [comment]
What's the problem you are having? Are you not able to populate the options?

Create an example of your problem using this link and I'll see if I can help:
https://jsfiddle.net/szLp8h4n

**Comment by tuanleincepit** [comment]
I have corrected this problem.
Thanks @adamwpe
