### ISSUE TITLE
CSS properties of body (#wrapper) not editable after editor.setComponents(html);

### ISSUE THREAD

**Issue by alikabeer32** [artf/grapesjs#2120]
When I save my page in a database refresh, the html and css are set like so
`
          $.ajax({
            url: "../feeder.php",
            type: 'POST',
            processData: false,
            contentType: false,
            data: fd,
          success: function(result){
            var response = JSON.parse(result);
            html = response.html;
            css = response.css;
            //editor.CssComposer.getAll().reset();
            editor.setComponents(html);
            editor.addComponents('<style>'+css+'</style>');
          }});`

But I cannot seem to be able to change the background image. It kind of gets stuck and the whole page then gets ruined. What am I missing? I can set a new image as background but background-color doesn't work.

**Comment by artf** [comment]
@alikabeer32 follow the BUG template please, without a demo it's hard to understand the issue
