### ISSUE TITLE
[QUESTIONS] get html component video

### ISSUE THREAD

**Issue by edward1893** [artf/grapesjs#2124]
- Why on the editor canvas, the video component has a div in parent tag (video), whereas when I get html(editor.getHtml()), the div doesn't exist
![Screenshot_2](https://user-images.githubusercontent.com/48974803/60871456-fd304200-a25c-11e9-858c-cb159f08bd39.png)

- is it possible if I want to add 1 div as a parent again? (for stye css)
```
<div>
	<div data-gjs-type="video" >
		<video ></video>
	</div>
</div>
```

**Comment by artf** [comment]
> Why on the editor canvas, the video component has a div in parent tag (video), whereas when I get html(editor.getHtml()), the div doesn't exist

To make a component behave in a specific manner its view (what you see in canvas) can be **completely different** from its model (what you see when you export the code) so it's totally ok

> is it possible if I want to add 1 div as a parent again? (for stye css)

As explained above, you can update the `video` view and use/add whatever you want
