### ISSUE TITLE
GrapesJS Editor functionalities not working Properly IE browser.

### ISSUE THREAD

**Issue by ghost** [artf/grapesjs#2126]
## WARNING
1) **Maximize** and **Minimize** button not working properly in IE Browser.
2) Not able to add **bold**, **italic**, **underlined**, **strike** and **link** to the text.
3) If adding freemarker string like **<#if test> ${test} </#if>** getting **=""** and **style="box-sizing: border-box;** appended. we can see here: **  <#if test="" style="box-sizing: border-box;">${test} 
                                    </#if>**

**Comment by artf** [comment]
Which IE?

**Comment by arju1503** [comment]
> Which IE?

IE 11.
