### ISSUE TITLE
[QUESTIONS] How to add device manager mobile landscape?

### ISSUE THREAD

**Issue by tuanleincepit** [artf/grapesjs#2128]
Hi,
Please help me add device manager mobile landscape with structure example: 
@media only screen 
  and (min-device-width: 375px) 
  and (max-device-width: 667px) 
  and (-webkit-min-device-pixel-ratio: 2)
  and (orientation: landscape) { 

}
Currently, i have device manager with structure:
@media (max-width: 480px) {

} 

Thanks

**Comment by artf** [comment]
Check the [DeviceManager API](https://grapesjs.com/docs/api/device_manager.html)
For now, it's only possible to use a single condition (configurable via `mainConfigObject.mediaCondition` option, `max-width` is the default)

**Comment by Ensaphelon** [comment]
@artf Is there any reason why grapesjs still does not support this feature? It seems that it could be resolved just by removing `mediaCondition` option from the `EditorConfig` at all, and allowing to pass any media query for each device in the `widthMedia` field
