### ISSUE TITLE
this is js file can be removed? http://feather.aviary.com/imaging/v3/editor.js

### ISSUE THREAD

**Issue by antcto** [artf/grapesjs#2133]
http://feather.aviary.com/imaging/v3/editor.js net::ERR_NAME_NOT_RESOLVED

after npm start and then got this error:

http://feather.aviary.com/imaging/v3/editor.js net::ERR_NAME_NOT_RESOLVED

i can open this file. can i remove it from project?

**Comment by artf** [comment]
yes
