### ISSUE TITLE
[QUESTIONS] How can I group some options when use the trait "select"

### ISSUE THREAD

**Issue by doanhcn2** [artf/grapesjs#2135]
I want to group options into groups like the optgroup tag in HTML. 
![Screenshot from 2019-07-12 14-21-50](https://user-images.githubusercontent.com/32545547/61110299-2cd78800-a4b1-11e9-99e4-b7c8b211e6ec.png)

I need some help?
Thanks!

**Comment by artf** [comment]
Create a [custom trait](https://grapesjs.com/docs/modules/Traits.html)
