### ISSUE TITLE
Is it possible to move components within a Block?

### ISSUE THREAD

**Issue by bidishad** [artf/grapesjs#2139]
Do grapeJS provide support moving component within a block.If yes, please redirect to some material? Moreover I want to restrict the component from moving outside the block? Is it possible to do so?
I see GrapeJS do provide drag and drop feature. Can you point me where I can start that too?

**Comment by artf** [comment]
Start by checking all the properties available on [Component](https://grapesjs.com/docs/api/component.html#properties) instance, especially (for your case) `draggable` and `droppable`
