### ISSUE TITLE
GrapesJS does not work in IE11

### ISSUE THREAD

**Issue by altalker** [artf/grapesjs#214]
GrapesJS does not work in IE11 as many of the JS function are not supported (e.g. remove().. , "`", blob.map..

**Comment by artf** [comment]
Can you show me exactly what kind of errors do you have?

**Comment by altalker** [comment]
1. ![image](https://user-images.githubusercontent.com/29933877/29083361-5b1c84f4-7c1d-11e7-82d6-a653d2a8fc1e.png)
  content: `<di

2. 
![image](https://user-images.githubusercontent.com/29933877/29083505-d47a6dac-7c1d-11e7-8c83-84eaec9ed0fa.png)
3. 
![image](https://user-images.githubusercontent.com/29933877/29083531-e8fb12fe-7c1d-11e7-937f-24fdbcfbb599.png)

**Comment by altalker** [comment]
This is when I use IE 11 when items are dragged into the Canvas or using filestack.  MS Edge it is ok. (JavaScript ECMA compatibility differences)

**Comment by artf** [comment]
thanks @altalker unfortunately, I'm not able to check those issues right now but hope to do so soon

**Comment by nicksav** [comment]
Actually have dnd broken on Edge as well.
Just doesn't work

**Comment by artf** [comment]
hey @nicksav can you post please your errors

**Comment by umangpasricha** [comment]
I am facing the same problem when using GrapesJs on IE11. Even [http://grapesjs.com/demo.html](URL) is not working fine. I am getting these errors:

![image](https://user-images.githubusercontent.com/25193657/30860372-88441472-a2e4-11e7-9b79-1f0d4cec2355.png)
when I drag the components/blocks to the canvas(even before I drop them).

**Comment by artf** [comment]
I think it's clear that we have to add some polyfill for those methods, but at the moment, it's just not my priority (can't even test them properly), so... PRs are welcome

**Comment by arthuralmeidap** [comment]
@altalker wich Windows version are you using?

**Comment by umangpasricha** [comment]
I added polyfill for these methods and now it is working fine on IE too. 
Here is the code I added for 'assign' method in the .js file I am using:

**if (typeof Object.assign != 'function') {
		  Object.defineProperty(Object, "assign", {
		    value: function assign(target, varArgs) { 
		      'use strict';
		      if (target == null) { 
		        throw new TypeError('Cannot convert undefined or null to object');
		      }
		      var to = Object(target);
		      for (var index = 1; index < arguments.length; index++) {
		        var nextSource = arguments[index];
		        if (nextSource != null) { 
		          for (var nextKey in nextSource) {
		            if (Object.prototype.hasOwnProperty.call(nextSource, nextKey)) {
		              to[nextKey] = nextSource[nextKey];
		            }
		          }
		        }
		      }
		      return to;
		    },
		    writable: true,
		    configurable: true
		 });
	}**

and here is the code I added before the use of 'matches' function in grapes.min.js:

 **if (!object.matches)
         object.matches = object.msMatchesSelector || object.webkitMatchesSelector;**

As IE does not support these methods so before using matches function in grapes.min.js, we are going to check if any object.matches method exists. If not then define object.matches with object.msMatchesSelector(this is supported by IE instead of matches).

**Comment by ateshuseyin** [comment]
@artf I can change babel presets with env preset. It should  work with appropriate configuration. Or web can add babel-polyfill to this configuration

**Comment by artf** [comment]
Can anybody try the latest version (the demo is updated too) and report if you get errors in console?

**Comment by vishal5033** [comment]
@artf Can you please help me out. It is not working for me also.
@umangpasricha if you have working copy of js which works in IE11 can you please send me?

**Comment by umangpasricha** [comment]
Yes, GrapesJS editor is working fine on Firefox, Chrome. IE11 and safari at my end. The changes I made in my code are:
In index file, I added the following code:

**if (typeof Object.assign != 'function') {
		  Object.defineProperty(Object, "assign", {
		    value: function assign(target, varArgs) { 
		      'use strict';
		      if (target == null) { 
		        throw new TypeError('Cannot convert undefined or null to object');
		      }
		      var to = Object(target);
		      for (var index = 1; index < arguments.length; index++) {
		        var nextSource = arguments[index];
		        if (nextSource != null) { 
		          for (var nextKey in nextSource) {
		            if (Object.prototype.hasOwnProperty.call(nextSource, nextKey)) {
		              to[nextKey] = nextSource[nextKey];
		            }
		          }
		        }
		      }
		      return to;
		    },
		    writable: true,
		    configurable: true
		 });
	}**

Then I made some changes in the grapes.min.js file. Here I am attaching this file as .txt:
[grapesminjs.txt](https://github.com/artf/grapesjs/files/1449849/grapesminjs.txt)

**Comment by artf** [comment]
@vishal5033 do you see any error in console?
@umangpasricha what about the current demo (v0.12.25) in IE11? Can you tell me if you see any error

**Comment by umangpasricha** [comment]
@artf Yes I am getting the same error:

> Object doesn't support property or method 'assign'

To resolve this I added the same code(mentioned above) in index.php file at my end.

**Comment by artf** [comment]
@ateshuseyin seems like [babel-preset-env](https://github.com/babel/babel/tree/master/experimental/babel-preset-env) doesn't work as expected 🤔  or I'm missing something?

**Comment by ateshuseyin** [comment]
@artf I'm busy next 2 days but I will be look at as soon as possible

**Comment by NorthstarTech** [comment]
I m getting this error when I am running grapesjs with MJML in IE11
SCRIPT5007: Unable to get property 'plugins' of undefined or null reference
File: grapesjs-mjml.min.js, Line: 61790, Column: 1
I made the changes given by umangpasricha mentioned above. but still not working.
Please help me out to resolve this issue asap.
Thanks.

**Comment by vishal5033** [comment]
Hi @ateshuseyin 
it is still giving error in IE11 as invalid character.

![image](https://user-images.githubusercontent.com/194415/32832354-2a1ef1b4-ca21-11e7-8a7e-cfeda5974449.png)

**Comment by ateshuseyin** [comment]
@vishal5033 It is only about demo page. I fixed and deployed. Could you try again please?

**Comment by vishal5033** [comment]
@ateshuseyin Sorry but now same old error "Object doesn't support property or method 'assign' ".

**Comment by ateshuseyin** [comment]
This is the last update I hope. I added babel-plugin-transform-object-assign into babel config and transform all Object.assign usages. 

Could you tray again? If won't I will find a windows machine

**Comment by vishal5033** [comment]
No problem. I will check. But again new error now. "Argument not optional"

**Comment by ateshuseyin** [comment]
ok. I will find a windows machine then fix this. It is too hard to fix with remote help. 
@vishal5033 Thank for your help.

**Comment by vishal5033** [comment]
@ateshuseyin No problem. Welcome.

**Comment by tomichal** [comment]
Hey all, I guess this is already known, but the editor on the demo site, at http://grapesjs.com/demo.html,  does not get initialized at all in MS Edge and IE 11.

**Comment by artf** [comment]
Thanks for the help @ateshuseyin, by the way, I was trying to use the library with `babel-polyfill` but unfortunately, keep getting this error in console `only one instance of babel-polyfill is allowed`. Obviously, the `babel-polyfill` is included once but seems like it conflicts with some other library and I believe this will happen with someone other, so I have to remove it from the next release

**Comment by tomichal** [comment]
Hey @artf is there a timeline for when MS Edge / IE 11 would be supported or nothing planned yet?

**Comment by artf** [comment]
@tomichal apologize but nothing planned

**Comment by tomichal** [comment]
No worries @artf 
I'm trying to go through the Edge / IE errors and fix them in my project. 
So far made a fix for an "... Argument not optional..." error. 
This seems to make MS Edge happy enough for the editor to run without any more errors (not sure about IE 11 yet).
In case it would help others here is the code I added to my project (it needs to be added such that the browser gets it after the grapesjs JS code:
    
    // 'detectIE()' sourced from https://codepen.io/gapcode/pen/vEJNZN
    if (detectIE()) {
        var originalCreateHTMLDocument = DOMImplementation.prototype.createHTMLDocument
        DOMImplementation.prototype.createHTMLDocument = function (title) {
          if (!title) title = ''
          return originalCreateHTMLDocument.apply(document.implementation, [title]);
        }
    }

**Comment by sura2k** [comment]
@tomichal Thanks, that worked. In IE 11 I had to replace `dragHelper.remove()` with with `dragHelper.parentNode.removeChild(dragHelper)`.

**Comment by NorthstarTech** [comment]
Where should I place this detectIE() code? Can you please let me know the file name or correct position, so I can run this on IE explorer and MSEdge too. Thanks.

**Comment by tomichal** [comment]
@NorthstarTech there are a few ways to do that. You could for example place it inside a <script> tags at the end of your HTML page code, right before the closing </body> tag.

**Comment by NorthstarTech** [comment]
@tomichal I added in the script tag, The page is loading now, Thanks. but as I am using mjml with grapesjs, the following error is coming now. Help needed to fix this issue. Thanks.

![grapesjs-mjmlerror](https://user-images.githubusercontent.com/33541046/33596659-39db759e-d9be-11e7-8632-20fcf27f7a20.png)

**Comment by tomichal** [comment]
@NorthstarTech Are you hitting this errors in MS Edge and IE11 or only IE11?
From what I experienced, after adding that code snippet (`if (detectIE()) ...`) MS Edge worked fine and I didn't spend that much time debugging/fixing cases for IE11. I would like to make the editor work in IE11, but am currently working on other project.

**Comment by NorthstarTech** [comment]
I am experiencing the same error for both. I have used the fixes suggested in this thread. @artf Is there any additional work to be done in the grapejs-mjml.min,js?

**Comment by sura2k** [comment]
@NorthstarTech I didn't check the above suggested fix with mjml, but without mjml it works. Tested on IE 11 and Edge 15.

**Comment by artf** [comment]
Sorry guys but still not able to work on this, any PR is welcome.
I'd create a new `polyfill.js` file here [/src/utils](https://github.com/artf/grapesjs/tree/dev/src/utils) and import it in [/src/grapesjs/index.js](https://github.com/artf/grapesjs/blob/dev/src/grapesjs/index.js)

**Comment by vishal5033** [comment]
Hello All,
After some modifications, I am able to work grapesJS in IE11 also. I will post it here.

Thanks,

**Comment by NorthstarTech** [comment]
any update on IE11 issue with grapesmjml? GrapesJS is not working in IE11 and Edge with MJML. Can anyone help to fix this issue?
Thanks.

**Comment by NorthstarTech** [comment]
@artf , I updated the grapesJS updated version of  0.12.55. I am getting these errors now.

![grapesjs-mjmlerror](https://user-images.githubusercontent.com/33541046/34204104-51c71360-e59f-11e7-8a3c-a9748956b46f.png)
![ie11mjmlissue](https://user-images.githubusercontent.com/33541046/34204097-4baa72ba-e59f-11e7-8eb7-ada00999cbf9.png)

**Comment by NorthstarTech** [comment]
Is IE11 and Edge Issue also fixed with MJML??

**Comment by artf** [comment]
@NorthstarTech it might be an issue with MJML itself

**Comment by NorthstarTech** [comment]
@artf is there any plan to fix this issue with mjml? Any timeline when this issue will be fix?
