### ISSUE TITLE
how to import the external  css styles，eg. boostrap.css

### ISSUE THREAD

**Issue by Sara1991908** [artf/grapesjs#2141]
hi, thanks for your great project. I have a problem confused recently. I want to import some react components to my projects,I changed this Jsx to html through renderToStaticMarkup method,and get the result ` <button type="button" class="ant-btn ant-btn-primary"><span>test</span></button> `and I also import  this class by` import 'antd/dist/antd.css', `but it didn't seem to work, so I'd like to ask you about this question, how to import the external  css styles.

**Comment by artf** [comment]
```js
```
