### ISSUE TITLE
[QUESTION] IE11 (Unable to get property 'style' of undefined)

### ISSUE THREAD

**Issue by makkaronis4e** [artf/grapesjs#2148]
Hi! Just faced the same issue: https://github.com/artf/grapesjs/issues/1295#issuecomment-410046832
While click on one of this buttons
![image](https://user-images.githubusercontent.com/33792090/61413961-741ca900-a8f5-11e9-92b5-41328b9c5ddc.png)

`this.getPropertiesEl().style.display="none"`
**Unable to get property 'style' of undefined or null reference**

Did anyone manage to fix it?

**Comment by zgeist** [comment]
I have same issue

How can I fix it?

**Comment by senchden** [comment]
I can confirm that in web page demo v0.15.8 it is not possible to set a style to an element. IE11 print out this to the console when trying to set a style via the Style Manager:
```
SCRIPT5007: Unable to get property 'style' of undefined or null reference
grapes.min.js (3,172032)
```

**Comment by Alkotronikk** [comment]
For me the issue was with [ParentNode.children](https://developer.mozilla.org/en-US/docs/Web/API/ParentNode/children) which muuri uses and I had no polyfill. Other than that, try checking the children of your items, and your manipulation with those (in case you're using ajax etc.).
