### ISSUE TITLE
[QUESTIONS] Create checkbox(input) in define new trait

### ISSUE THREAD

**Issue by fmr411** [artf/grapesjs#2149]
How to make a checkbox input type in define new trait (https://grapesjs.com/docs/modules/Traits.html#define-new-trait-type), I have made it, and the checkbox does not appear, if I compare with Built-in trait types(checkbox) there are tags i, Thank's
![Screenshot_4](https://user-images.githubusercontent.com/15244481/61429979-8842c380-a952-11e9-95e1-b3aacfb93ce4.png)
`create elemen in define new type`
![Screenshot_5](https://user-images.githubusercontent.com/15244481/61430003-a5779200-a952-11e9-9696-058dfe4cd6df.png)

**Comment by artf** [comment]
First of all, you have to provide a demo for such a case, and why the default checkbox trait type is not working for you?
