### ISSUE TITLE
Integrate FullPage.js with grapesjs

### ISSUE THREAD

**Issue by vish4395** [artf/grapesjs#2150]
Hello @artf ,
I want to add Fullpage.js with GrapesJS.
So please help what should I do?
I trying by it loading as simple HTML content and add fulpage.js in canvas scripts. but I can't do it.

**Comment by artf** [comment]
Start by reading the documentation:
https://grapesjs.com/docs/modules/Components.html
https://grapesjs.com/docs/modules/Components-js.html

If you're not yet able to do it after docs, open an issue by showing the code which is not working
