### ISSUE TITLE
[QUESTION]  How to distinguish between a successful or invalid store?

### ISSUE THREAD

**Issue by csb346** [artf/grapesjs#2152]
Hi! I'm integrating GrapesJS ina laravel app and so far so good.

After configuring remote load and storage, I'm trying to show a notification after any store (auto or manual). 

Following the API documentation I got that easily:
`editor.on('storage:end:store', () => {
   showNotification()
});`

This works fine. Then I tried to show a different notification in case of a remote error like this:
`editor.on('storage:error:store', () => {
   showErrorNotification()
});`

It's working, but in case of an error it shows both the notifications. I think there is no **storage:success:store** event. Is there any way to achive this with the available events?

Thanks and keep on the excelent work!

**Comment by artf** [comment]
@csb346 yes, you're right, there is no `storage:success:store`, the event `storage:end:store` is correctly called even in case of errors, but being the last called you can make use of a flag variable
```js
let error;
editor.on('storage:error:store', () => {
	showErrorNotification();
	error = 1;
});
editor.on('storage:end:store', () => {
	!error && showNotification();
	error = 0;
});
```
