### ISSUE TITLE
Possible to have multiples BlockManagers on one Editor ?

### ISSUE THREAD

**Issue by Thebleach0** [artf/grapesjs#2155]
Hello,

thanks for the hardwork, grapesjs is very good :)

Just wondering, is it possible to add multiple blockmanagers on one editor ?
The code hereunder won't work for me :
`
grapesjs.init({
blockManager: [
		{
			appendTo: '#album_editor_panel_left',
			blocks: [ ... ]
		}, {
			appendTo: '#album_editor_panel_right',
			blocks: [ ... ]
		}
		],
...
`
Thank you very much for your help.

**Comment by artf** [comment]
Yes, use the [blockManager.render()](https://grapesjs.com/docs/api/block_manager.html#render) method with `external` set to `true`
