### ISSUE TITLE
[QUESTION] Show Component settings

### ISSUE THREAD

**Issue by miky9585** [artf/grapesjs#2162]
There is a way to show "Component settings tab" on component click?
I'm trying 

editor.on('component:update', function(propertyName)...

but I cannot find a way to show the second tab ("Component Settings")

**Comment by miky9585** [comment]
I've solved in this way. But I'ld have a more grapesjs friendly solution

	
	editor.on('component:update', function(propertyName){ 
		if(typeof propertyName.changed.status != 'undefined' && propertyName.changed.status == "selected"){
			$('[data-original-title="Settings"]').trigger('click')
		}
			 
	} )

**Comment by selcukcura** [comment]
Here's a cleaner approach:

```
editor.on('component:selected', (some, argument) => {
    editor.Panels.getButton('views', 'open-tm').set('active', true);
});
```

**Comment by miky9585** [comment]
Thank's @selcukcura
