### ISSUE TITLE
[QUESTION] How to overwrite classes manager?

### ISSUE THREAD

**Issue by CimattiConsulting** [artf/grapesjs#2164]
Hi @artf ,
Is there a way to modify the attribute where the classes are placed? (default: `class`)
is there also a way to change the position and tag of the styles? (default: `<style>`)

**Comment by artf** [comment]
> Is there a way to modify the attribute where the classes are placed? (default: class)

Not really, the only thing you can do now is to extend methods from base components.
This is where is assigned in the model (used in the final HTML code)
https://github.com/artf/grapesjs/blob/02ceecc87dc2116435cab1c65014fab7d6a05293/src/dom_components/model/Component.js#L422

and here for the View (when is rendered in canvas)
https://github.com/artf/grapesjs/blob/02ceecc87dc2116435cab1c65014fab7d6a05293/src/dom_components/view/ComponentView.js#L219

is there also a way to change the position and tag of the styles?
Nope, styles are handled (imported inside CssComposer) and removed internally by the editor
