### ISSUE TITLE
[QUESTION] How to extend style manger Sector's property

### ISSUE THREAD

**Issue by sdrebel** [artf/grapesjs#2165]
Hi @artf ,

We have created a custom asset manager which is working perfectly for image component. However we are not able to call custom asset manager for background image. 

Tried to access using this methods
          var stm = editor.StyleManager;
var fileType = stm.getType('file');
stm.addType('file',{
 model: fileType.model,
view: fileType.view.extend({
        events: {
     ......
   }
})
})

Is there any other method which we can use editor.StyleManager.getSector() and override the function?

Thank you,

**Comment by artf** [comment]
Hi @sdrebel can you show us your implementation of custom asset manager? If you have followed [this](https://github.com/artf/grapesjs/issues/491#issuecomment-342813486) you should see it also in the Style manager
