### ISSUE TITLE
[QUESTION][REQUEST] How to remove a block?

### ISSUE THREAD

**Issue by froderf** [artf/grapesjs#2166]
`editor.DomComponents.getWrapper().getEl().insertAdjacentHTML('beforeBegin', letBlock)`

letBlock letblock is a variable that contains HTML.

Question:
1. How to remove this adjacent HTML?
2. is there a function like "insertAdjacentCSS()"?

**Comment by Zachary1748** [comment]
You touched on a few questions here, but to get to your first in your headline; reference the [BlockManager api docs here](https://grapesjs.com/docs/api/block_manager.html#remove)

e.g. ```BlockManager.remove('custom-block-id')```

**Comment by artf** [comment]
You're mixing too much stuff in one question and without any context

**Comment by froderf** [comment]
@artf I just wanted to remove the new block that I added via 
`editor.DomComponents.getWrapper().getEl().insertAdjacentHTML();`

**Comment by artf** [comment]
Blocks are those: https://grapesjs.com/docs/modules/Blocks.html

`editor.DomComponents.getWrapper().getEl().insertAdjacentHTML();` you're not removing "blocks", you're dealing with native DOM elements there.
Probably you need to remove a [Component](https://grapesjs.com/docs/modules/Components.html), in that case use [`component.remove()`](https://grapesjs.com/docs/api/component.html#remove)
