### ISSUE TITLE
Custom html DOM changes does reflected when saving changes to database

### ISSUE THREAD

**Issue by jadejahardipsinh** [artf/grapesjs#2168]
I created new toolbar option called text-align using following code 

```js
const rteStudio = studio.RichTextEditor;
rteStudio.add('text-align', {
	icon: "<select id=\"textAlignSelector\" class=\"gjs-field lm select\">" +
	"<option value=''>Select alignment</option>" +
	 "<option value=\"left\">Left</option> " +
	 "<option value=\"center\">Center</option> " +
	 "<option value=\"right\">Right</option> " +
	"</select>",
	attributes: { title: 'Text Align'},
	event: 'change',
	result: (rteStudio, action) => {
		var val = action.btn.firstChild.value;
		var fontTag = "";
		if(action.btn.className && (action.btn.className.indexOf("gjs-rte-active") < 0)) {
			action.btn.className += " ".concat("gjs-rte-active");
		}
		var el = rteStudio.getCurrentEl();
		if (el && val != "" ) {
			debugger;
			if(el.tagName == "SPAN") {
				el = el.parentNode;
			}
			el.style.textAlign = val;
			rteStudio.syncActions();
		}
		//rteStudio.insertHTML(fontTag)
	}
});
```

In order to make above code work, I added following function into `grapes.js` file :

```js
{
	key: "getCurrentEl",
	value: function getCurrentEl(value) {
		var lastNode;
		var doc = this.doc;
		var sel = doc.getSelection();

		if (sel && sel.rangeCount) {
			var node = doc.createElement('div');
			var range = sel.getRangeAt(0);
			return range.commonAncestorContainer.parentNode;
		}
		else {
			return null;
		}
	}
}
```

Due to above code, my changes working in the editor in UI refer:
![text-align-feature-demo](https://user-images.githubusercontent.com/53306499/61884473-e86cd300-af19-11e9-9da1-7274dfd26e98.png)

I am getting html of editor using following code :

```js
studio.runCommand('gjs-get-inlined-html')
```

Now, the issue is, in the HTML got using above command, I don't see my formatting changes done using above code. 

Please help me to fix this issue. Due to this, I can't save changes done using _text-align_ feature into database

**Comment by artf** [comment]
Be sure to use the latest version and try to call `sync:content` on selected component before calling the desired command, eg.
```js
editor.getSelected().trigger('sync:content');
editor.runCommand('gjs-get-inlined-html')
```

**Comment by jadejahardipsinh** [comment]
@artf, Thanks for the answer. I tried with that but unfortunately not working. I am getting that using following code:

```js
studioCommand.add('com-save', {
				run: function(studio, sender) {
					studio.getSelected().trigger("sync:content")
					var studioContent = studio.runCommand('gjs-get-inlined-html');
                                    // Saving studioContent in the database using ajax call
```

I already did this but nothing happens. Please correct me if something wrong. 

Again, highly appreciate your help on this.

**Comment by artf** [comment]
@jadejahardipsinh grapesjs version?

**Comment by jadejahardipsinh** [comment]
I am using version: 0.14.65

**Comment by jadejahardipsinh** [comment]
I tried with integrating my customizations on [grapes.js](https://github.com/artf/grapesjs/commit/08720f2177c5b5aec4c46bf3c40f82b8aaa6c525#diff-98f3150a17acca5fa8f39d763af5e5fd)

**Comment by artf** [comment]
No... I'm asking which version of grapesjs do you use...

**Comment by jadejahardipsinh** [comment]
@artf I am using v0.15.3

**Comment by artf** [comment]
Provide a reproducible demo, please

**Comment by jadejahardipsinh** [comment]
Please refer attached js file which I used and contains all the changes that I made
[grapes.js](https://github.com/artf/grapesjs/files/3545389/grapes.js.txt)

**Comment by artf** [comment]
No @jadejahardipsinh it doesn't work like this, create a LIVE demo ONLINE with the original library, not a one edited by you (eg. use this as a starting point https://jsfiddle.net/szLp8h4n)
For now, I can't see any issue with the current version and I close this ticket. When I'll be able to see the problem on a demo I'll reopen it
