### ISSUE TITLE
[QUESTION]Block Placeholder

### ISSUE THREAD

**Issue by froderf** [artf/grapesjs#2169]
I just noticed, it is hard to drag blocks/component from toolbox if the placeholder (a line with yellow green color e.g see it in demo online) is just a lign.

Is it possible to make the "yellow green line/placeholder" to become a box  and while we are dragging the blocks, this placeholder should take up some space like a new element is there.

-----------------------

For example
Default: https://imgur.com/Ym69GDt

Is it possible to make it a block tahas has some height and all other elements below it will move down to make some space on it?
Like this
https://imgur.com/WbLbyZw

**Comment by artf** [comment]
You can change the aspect of the line with your custom CSS but you can't move other components around it, the DOM of the placeholder is like a layer on top of the canvas and not between them

**Comment by FawadOmerEsk** [comment]
Can you explain this a little bit as to how can we update the custom CSS?
