### ISSUE TITLE
Style Manager does not pick up css element classes

### ISSUE THREAD

**Issue by Akashb3** [artf/grapesjs#217]
Hi guys,

I am having an issue with the style manager not being able to pick up css classes that have an element tag infront of the css class name.

For example I have the following css class:
```
div.Frame {
               border: #d6d8dd 2px solid;
               border-radius: 4px 4px;
               position: absolute;
            }
```

Now the style manager will refuse to edit this class and if i take out the element 'div' and have the class name .Frame it works with no issues.

How can i get this to work with the element infront of the class name?

**Comment by artf** [comment]
Sorry but you can't do it if you want the class to be selectable by the Style Manager, but you can use this trick to keep some not class based selectors inside the rule:
```html
<div class="Frame"></div>
<style>
.Frame,
div.Frame {
               border: #d6d8dd 2px solid;
               border-radius: 4px 4px;
               position: absolute;
            }
</style>
```
