### ISSUE TITLE
[QUESTION] Custom component - how to set editable to true

### ISSUE THREAD

**Issue by inaLar** [artf/grapesjs#2170]
Hi, I've created a custom component type, but I am having some trouble making it editable.
The component is a "span" with component type "tag". it will contain only text, but I want it to extend the default, not the text component. Any idea how can I make it editable, even if it is not "text".

```js
comps.addType('tag', {
        
        model: { 
            defaults:  {
                type: 'tag',
                tagName: 'span',
                editable: true,
                droppable: false,
                attributes: {
                  'data-gjs-type': 'tag',
                },
                textable: 1,
                traits: [{
                    type: 'select',
                    label: 'Tag',
                    name: 'selected-tag',
                    options: tagTypes,
                }], 
            },

            isComponent: function(el) {
              let result;
              if (el.tagName == 'SPAN' && el.getAttribute("data-gjs-type") === "tag") {
                result = {
                  type: 'tag',
                };
              }
              return result;
            }
        }, ... 
```

**Comment by Zachary1748** [comment]
What would be your intention and goal of making it editable if you don't intend to extend the text component type? The text component type extends the default type and adds editing capabilities such as the rich text editor. Are you looking at implementing your own RTE? [RichTextEditor Docs](https://grapesjs.com/docs/api/rich_text_editor.html#richtexteditor). Otherwise look at the source of the text component type and see what parts you don't want and reimplement it those parts that you do want in your own component.

**Comment by inaLar** [comment]
I'd prefer not to use RTE, as I do not need any of its functionality. I only want to be able to edit the content and save it ( by edit I mean - click into the span change the text and save it again).
Also the new type will have specific traits and will be added to the canvas after a choice.

If I wanted to a component of type text, I wouldn't ask the question :)

Thank you for the advise to look more closely into the text component - I will.

**Comment by Zachary1748** [comment]
@inaLar Then something you could do is get the built-in RTE and remove all of it's actions. [Reference here](https://grapesjs.com/docs/api/rich_text_editor.html#remove).

**Comment by artf** [comment]
I think you're looking for something like this

```js
editor.DomComponents.addType('tag', {
	model: {
		defaults: {
                tagName: 'span',
                editable: true,
                droppable: false,
				// ... all your other stuff
		}
	},
	view: {
		events: {
			dblclick: 'onActive',
			focusout: 'onDisable',
		},
		onActive() {
			this.el.contentEditable = true;
		},
		onDisable() {
			const { el, model } = this;
			el.contentEditable = false;
			model.set('content', el.innerHTML)
		},
	}
});
```

ps: there is no need to check/handle for `data-gjs-type`, the editor does it already for you. If you don't import HTML and need to recognize your `tag` custom component you can skip `isComponent`

**Comment by inaLar** [comment]
Thank you! I have done something similar, but yours is not so complicated. I've had other events attached to onActive, so I couldn't use it. Now I detached them and I will do as you suggest.
About the `data-gjs-type` - I need it because the content I am creating is stored and when reloaded the components have to be recognized in order for their settings/traits to be loaded and especially this custom type component I've added. There is also a possibility to change the content via traits, which complicates things a bit too :)
P.S.: @artf You have done a great work by far!

**Comment by Jimil-8000** [comment]
> Thank you! I have done something similar, but yours is not so complicated. I've had other events attached to onActive, so I couldn't use it. Now I detached them and I will do as you suggest. About the `data-gjs-type` - I need it because the content I am creating is stored and when reloaded the components have to be recognized in order for their settings/traits to be loaded and especially this custom type component I've added. There is also a possibility to change the content via traits, which complicates things a bit too :) P.S.: @artf You have done a great work by far!

I am also trying  to do similar work like want to bind the traits value to be displayed on the component and whatever we write on component should also update the triat value as well. It's kind of two way binding, where at the same time i am also saving the content from the `data-gjs-type`. Can you suggest me how can i implement such functionality ?
