### ISSUE TITLE
QUESTION: is there a way to do trait based placeholders

### ISSUE THREAD

**Issue by danrcoull** [artf/grapesjs#2172]
Hi Not sure if this is the correct place to ask.

trying to load the content of  a textarea into this framework. 

But allot of the links have placeholders within the default html such a <a href="{{placeholder for default url }}" is there a way to render this link within the canvas but leave the original html unmodified?

**Comment by Zachary1748** [comment]
Your question isn't completely clear are what you're trying to achieve, but take a look at [creating components](https://grapesjs.com/docs/modules/Components.html#define-new-component).

**Comment by danrcoull** [comment]
Sorry Let me explain

take a cms widget such as {{widget name="test" type="\Php\Class"}} 

Concenpt is to drag a block which opens a widget select model  to choose a widget set the options and hit add that generates such as above. This needs to the ajaxly render to canvas, but leave the html with the above widget. 

Ive done something similar for asset management, and got normal placeholders working but the variables in that widget may have different values

**Comment by pouyamiralayi** [comment]
hi! for the select model you may use editor.Modal and as it's content, inject your desired login for choosing and configuring your widgets. then you can inject the result widget using yourComponent.components(yourWidget) to fill the content of block with your widget.
for the ajax rendering part, you can define some logic in the view property of your component definition as well.

**Comment by artf** [comment]
@danrcoull as already suggested by others, basically you have to create a custom component with a custom **View** logic (indeed you use it when you have to change something inside the canvas for the user and not the final code) to render something different for those placeholders
