### ISSUE TITLE
[Feature Request]: Canvas Touch Support iOS

### ISSUE THREAD

**Issue by yanosuke** [artf/grapesjs#2175]
My customers also require the ability to use the GrapesJS platform on their mobiles, therefore I am currently using the GrapesJS-Touch plugin. The issue, however, is not with the plugin, but rather about a missing method within the GrapesJS code. The issue and solution are provided by Mikereem at the following link: [https://github.com/artf/grapesjs-touch/issues/1]

To recap the link: on iOS devices clicking on the canvas does nothing at all. Adding "methods[method](body, 'touchend', this.onClick);" to the toggleSelectComponent function fixes the problem. The method is exactly the same as the normal onClick method with the addition of "e.preventDefault();" right after "e.stopPropagation();"

I have just added the suggested solution and everything works perfectly on iOS using the latest dev version (0.14.66). Could this solution be added as a permanent implementation within GrapesJS so that we don't need to manually edit the codes after every release? Thank you in advance.

**Comment by artf** [comment]
I'd be happy to merge a PR

**Comment by saltyfoam** [comment]
We're making use of GrapesJS and would love to have greater support on mobile so I hope this goes through!
