### ISSUE TITLE
How to create a block with HTML and CSS and javascript content.

### ISSUE THREAD

**Issue by alikabeer32** [artf/grapesjs#2177]
Can somebody please show me a code example of how to create a block with javascript and css styles.
```js

    editor.BlockManager.add('a_block', {
      label: 'Sample Block',
      content: 
          `<style>
              .sampleclass{
                padding:10px 15px;
              }
              .sampleclass2{
                opacity:0;
                visibility:hidden;
              }
              .sampleclass:hover > .sampleclass2{
                visibility:visible;
                opacity:1;
              }

              @media (max-width: 768px){
                .sampleclass{
                  width:100%;
                }
              }
          </style>
          <div class="samplecalss">Text<div class="sampleclass2"><div><a>A Link</a></div></div>
              <script>
                 console.log('hello world');
              </script>
          `,
      attributes: {
        title: 'A block'
      },    
  });
```

The  main problem is that the js code is added right after the html rather than at the end of the file

**Comment by pouyamiralayi** [comment]
Hello there! what you are looking for is [here](https://grapesjs.com/docs/modules/Components-js.html)
`
    grapesjs.plugins.add('textplugin', editor => {
 editor.DomComponents.addType('custom-type',{
            model:{
                defaults:{
                    script: function () {
                        console.log('hello world');
                    }
                },
                isComponent(){
                    return true
                }
            },
        })
editor.BlockManager.add('a_block', {
            label: 'Sample Block',
            content:

                `<style>
              .sampleclass{
                text-align: center;
                /*padding:10px 15px;*/
              }
              .sampleclass2{
                opacity:0;
                visibility:hidden;
              }
              .sampleclass:hover > .sampleclass2{
                visibility:visible;
                opacity:1;
              }

              @media (max-width: 768px){
                .sampleclass{
                  width:100%;
                }
              }
          </style>
          <div data-gjs-type="custom-type" class="sampleclass">Text<div class="sampleclass2"><div><a>A Link</a></div></div></div>

            `,
            attributes: {
                title: 'A block'
            },
        });
    })
`
Notice I am using these stuff inside a plugin, because for custom component types you must use plugins for the moment.
cheers.

**Comment by alikabeer32** [comment]
Thank you.

**Comment by alikabeer32** [comment]
Thank you.

**Comment by pouyamiralayi** [comment]
Hello there! what you are looking for is [here](https://grapesjs.com/docs/modules/Components-js.html)
`
editor.DomComponents.addType('custom-type',{
            model:{
                defaults:{
                    script: function () {
                        console.log('hello world');
                    }
                },
                isComponent(){
                    return true
                }
            },
        })
`
you must **define the custom type** before your **block definition**.
then in your block content modify this line to inject your type:
`
          <div data-gjs-type="custom-type" class="sampleclass">Text<div class="sampleclass2"><div><a>A Link</a></div></div></div>
`
**Notice** that for using custom types, they must be defined in a plugin for the moment. more info [here](https://grapesjs.com/docs/modules/Plugins.html)
cheers.

**Comment by lugies** [comment]
@pouyamiralayi thank you for your help
