### ISSUE TITLE
[QUESTION] Can i add my own attribute inside the BlockManager.add ?

### ISSUE THREAD

**Issue by sherngar** [artf/grapesjs#2183]
editor.BlockManager.add('testBlock' + i, {
	    label: 'Box' + i,
	    attributes: { MyAttribute: 'hi'},
	    content: html
	  })

Can i do something like that ? or i need to use standard html attributes?

I tried, but didn't work

Thank you.

**Comment by artf** [comment]
It works as expected https://jsfiddle.net/90y7wuo8/ 
Next time create a reproducible demo
