### ISSUE TITLE
SVG icons instead of PNG

### ISSUE THREAD

**Issue by vegadesign** [artf/grapesjs#2185]
Hello.

There are some PNG icons in the application:

- flex-just-start.png
- flex-al-end.png
- flex-just-sp-bet.png
- flex-dir-col.png
- flex-just-sp-ar.png
- flex-al-start.png
- flex-dir-row.png
- flex-just-end.png
- flex-just-sp-cent.png
- flex-dir-col-rev.png
- flex-al-str.png
- flex-al-center.png
- flex-dir-row-rev.png

I've created the same but in SVG format. Please see [attached folder](https://drive.google.com/open?id=189-erUech7_3HPCQKL18pu9j7R6u4OoO) with files and also the Sketchapp format as the source. 

Would be great to replace.

**Comment by artf** [comment]
Wow, thank you very much @vegadesign really appreciated. We actually use those only for the demo ([gh-pages](https://github.com/artf/grapesjs/tree/gh-pages) branch), here:
https://github.com/artf/grapesjs/blob/be39c6baf55f4e644b6bc8bbdd71ead71723dd6b/demo.html#L53-L91
I'll try to replace them as soon as I can, but if you're even able to create a PR by yourself it would be really appreciated
