### ISSUE TITLE
How to change the title for Image component on Hover?

### ISSUE THREAD

**Issue by Chaitwo** [artf/grapesjs#2187]
Hello @artf ,

How can I change the title for my image component when I hover on it?

LIke the highlighted text on this image:

![image](https://user-images.githubusercontent.com/44081652/62636455-35f43180-b957-11e9-8270-edcd12fca966.png)

Thanks!

**Comment by Zachary1748** [comment]
Set the **'custom-name'** attribute on the component.

**Comment by artf** [comment]
`custom-name` is deprecated, use `name` instead

**Comment by Chaitwo** [comment]
Thanks a ton @Zachary1748 and @artf for the help, it worked like a charm.

I've updated the getName function and changed the name attribute for images.

` name = name == 'image' ? 'image (Double Click to upload Images)' : name;`
