### ISSUE TITLE
[Question] Define components in template

### ISSUE THREAD

**Issue by Jogai** [artf/grapesjs#2195]
### Questions
- How can I make a part of my template a component ?
- How can I set draggableComponents on such a component?
- If so, then can I stop setting selectable: false, highlightable: false, hoverable: false on the child nodes inside said component?
- Is it possible to supply a different external link to the component? 

### More explanation and a code part
I have a question because I think grapesjs is smarter than I use it currently. We have an asp.net app where its integrated, and we initialize it from an element. That element is the combination of our html template and data which give our users every day a prefilled newsletter with new content. They can drag articles around and then send it.

Our template has stuff like this (code in there is razor/cshtml stuff):

```
	<tr data-gjs-draggable="#main" data-gjs-copyable="false">
		<td data-gjs-selectable="false" data-gjs-highlightable="false" data-gjs-hoverable="false">
			<a data-gjs-selectable="false" data-gjs-highlightable="false" data-gjs-hoverable="false" href="https://www.@(Model.Site.Address)/subscribe/" target="_blank">
				<img data-gjs-selectable="false" data-gjs-highlightable="false" data-gjs-hoverable="false" style="margin-bottom: 5px;" alt="" src="https://cdn.@(Model.Site.Address)/Subscribe.jpg" border="0" width="468" />
			</a>
		</td>
	</tr>
```

To me it looks if this should be a component with the new draggableComponents option enabled. (see question 1-3)

This piece has an external link that will end up in the output. It would help our users if there could be another link that is not send out, but just for internal use (link to the editor in our cms). Maybe only available in the layer manager.

**Comment by pouyamiralayi** [comment]
https://grapesjs.com/docs/modules/Blocks.html#custom-render

**Comment by pouyamiralayi** [comment]
please refer to this for defining your custom component type: [define_new_component](https://grapesjs.com/docs/modules/Components.html#define-new-component)

then refer to this for adding your custom type as a block: [block](https://grapesjs.com/docs/modules/Blocks.html)

for your case it is something like this:
`
 editor.DomComponents.addType('custom-type',{
            model:{
                defaults:{
                    tagName: 'tr',
                    // highlightable: false,
                    // hoverable: false,
                    // selectable: false,
                    // draggable: '.some-class[title=Hello]', //can be boolean
                    components: {
                        tagName: 'td',
                        // highlightable: false,
                        // hoverable: false,
                        // selectable: false,
                        // draggable: '.some-class[title=Hello]',
                        components: {
                            tagName: 'a',
                            // highlightable: false,
                            // hoverable: false,
                            // selectable: false,
                            // draggable: '.some-class[title=Hello]',
                            // components: {
                                    tagName: 'img',
                            //     // highlightable: false,
                            //     // hoverable: false,
                            //     // selectable: false,
                            //     // draggable: '.some-class[title=Hello]',
                            // }
                        }
                    }
                },
                isComponent() {
                    return true
                }
            }
        })
        editor.BlockManager.add('b_block', {
            label:'Template',
            attributes: {
                title: 'Template Block'
            },
            content: {
                type:'custom-type'
            }
        })
`
you can customize this by uncommenting the properties like draggable, selectable...
cheers.

**Comment by Jogai** [comment]
Thanks for the answer and the links. They are really helpful. 
For this question however I was looking for a way to do this within a template. Currently we dont use the blockmanager, our users only drag stuff around. They never add anything.

**Comment by pouyamiralayi** [comment]
if you mean, you want to initialize the editor with some components already placed into the canvas, you need this:
`
editor initialization...
//define custom component as before
//instead of proceeding with block definition, use this snippet below:
editor.setComponents(`
          	<tr data-gjs-type="custom-type">
                <td >
                    <a>
                        <img  style="margin-bottom: 5px;" alt="" src="https://cdn.@(Model.Site.Address)/Subscribe.jpg" border="0" width="468" />
                    </a>
                </td>
            </tr>
            `,)
`
cheers.

**Comment by Jogai** [comment]
That would mean a fundamental change in how we load stuff, but maybe for the better. Thanks.

**Comment by pouyamiralayi** [comment]
how you load the required stuff? the common procedure is to inject the requirements into the canvas using canvas.scripts and canvas.styles in this way they are available on the canvas for further usage.
for third party components like vue or react you have the local script available for each component where you instantiate and mount  the component using vue instance or react.renderDOM.
cheers.

**Comment by Jogai** [comment]
We use the method where we load the template as html and instantiate grapesjs from that element. 
If I understand correctly I can just supply a bunch of elements which are the same custom type and then I only have to define that type once?

**Comment by pouyamiralayi** [comment]
yes exactly. just remember defining your custom type inside a plugin. for the moment grapes has some issue on storing custom components defined outside plugins.
cheers.

**Comment by artf** [comment]
> for the moment grapes has some issue on storing custom components defined outside plugins.

Actually, are stored correctly, it's just about loading components which are no recognized because the custom type doesn't exist yet, so this is the reason of putting the code in the plugin (plugin are loaded before fetching components). We're updating the Component documentation and this thing will be the first recommendation (and the only available) for defining custom types

BTW @Jogai the approach described by @pouyamiralayi is correct. Instead of writing
```html
<tr data-gjs-draggable="#main" data-gjs-copyable="false">
```
You can just define a custom component type (or extend the built-in [`row`](https://github.com/artf/grapesjs/blob/dev/src/dom_components/model/ComponentTableRow.js) one)
```js
 editor.DomComponents.addType('my-row',{
			extend: 'row',
            model:{
                defaults:{
					draggable: '#main',
					copyable: 'false',
				}
// ...
```
And use it where you need it

```html
<tr data-gjs-type="my-row">
```
The properties will be taken from the defined component type.
In this way, you're more Component-oriented and it's easier to reuse them around your templates
