### ISSUE TITLE
Instanciation problem: grapesjs.init is not a function

### ISSUE THREAD

**Issue by francoisandre** [artf/grapesjs#22]
Dear Sir,

I really apologize for my stupid question  

- I've basically installed grapesjs via Bower:
`bower install grapesjs`

- Then I've tried to setup my page following your instructions :

````
<html>
<head>
<title>Test GrapeJS</title>

<script src="http://code.jquery.com/jquery-2.2.0.min.js"></script>
<link rel="stylesheet" href="./bower_components/grapesjs/dist/css/grapes.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css">
<script src="./bower_components/grapesjs/dist/grapes.min.js"></script>
</head>
<body>

<div id="gjs"></div>

<script type="text/javascript">

  var editor = grapesjs.init({
      container : '#gjs',
      components: '<div class="txt-red">Hello world!</div>',
      style: '.txt-red{color: red}',
  });

</script>

</body>
</html>
````

But, when I try the page, I've got a **grapesjs.init is not a function** error in the console and nothing more happens.

Is it that the instanciation of the editor has changed in the latest versions or have I stupidely missed something important ?

Your work seems really great.

Sincerly

François

**Comment by francoisandre** [comment]
Dear Sir,

I clone the repo instead of using bower and everithing seems to be ok now.

I apalogize for having opened this issue.

Sincerly

François

**Comment by artf** [comment]
thanks @francoisandre anyway it's my fault with bower, I'm not updating the master branch which is trying to download :)

**Comment by magixsource** [comment]
@artf update the master please,i use bower and this exception still.

**Comment by artf** [comment]
@magixsource done :)

**Comment by sebastianha** [comment]
The problem still exists, just tried the same with the same problem
