### ISSUE TITLE
Customize your GrapesJS

### ISSUE THREAD

**Issue by GoodPHP** [artf/grapesjs#2200]
Hi there,

I will offer your my service of customizing your grapesJS editor to any result.

I have experience about 3 years with GrapesJS and 9 years in Web developing.

Example of my work:
https://monosnap.com/file/MnXzYlIK5UVe3oVr8dqveDzZG7PVU8

Video:
https://monosnap.com/file/Lw0E8VmGdsyWUGe8jsRII6i66P1urm

Email: support@devfuture.pro
Skype: maxim2356

Best regards :)

**Comment by Chaitwo** [comment]
Hey, @GoodPHP I need help with a challenge I've been facing

I want to hide images with src empty on preview mode and show them on editor mode i.e stop: preview.

I've tried this but it doesn't seem to work for some reason

editor.on('run:preview', () => {
    $('.img[src=""]').hide();
});

Thanks,
Chaitu

**Comment by smik3** [comment]
Hi @GoodPHP 
Do you create your own plugins? I'm working on creating my own for custom blocks but I'm not in a node environment so having to go from the minified example files... heavy going!
Do you have any tips? :)

**Comment by pouyamiralayi** [comment]
@smik3  you do not need node environment for defining plugins. 
` grapesjs.plugins.add('your-plugin', editor => { your stuff }`
this will define the behavior and you have the editor instance available to you as argument.
then initialize your editor as before and specify the plugin.
cheers.

**Comment by smik3** [comment]
Oh I know that! What I was referring to is that if you try and use the index/block/component files from dist (ie unminified and easier to work from) they don't work outside of a node/webpack environment.

**Comment by inaLar** [comment]
@smik3 , I have tried this, but is not a good practice, as this wont let you update GrapesJS easy in future. You better separate the custom code in a js functions and whichever of them you need to use as a plugin, you can load. Or use node only for compilation of your plugin and put the plugin-name.min.js in production.

`var editor = grapesjs.init({
...
plugins: [yourCustomFunction], 
...
})
`

**Comment by artf** [comment]
@GoodPHP thanks for the lettings us know. 

Be sure to post also on our discord chat (jobs channel) https://discordapp.com/channels/365099684114464769/404263782559514624
Generally, when someone asks me for a job on GrapesJS I redirect them there
