### ISSUE TITLE
Remove an Image when on preview and show on editor 

### ISSUE THREAD

**Issue by Chaitwo** [artf/grapesjs#2202]
Hey, @artf I need help with a challenge I've been facing

I want to hide images with src empty for particular class images in preview mode and show them on editor mode.

I've tried this but it doesn't seem to work for some reason

```
editor.on('run:preview', () => {
    $('.img[src=""]').hide();
});

editor.on('stop:preview', () => {
    $('.img[src=""]').show();
});
```

Thanks,
Chaitu

**Comment by pouyamiralayi** [comment]
is your selector right? grapes will set `background-image:url()` instead of src.

**Comment by inaLar** [comment]
Same question about the selector. Is it working?
You can try: $('.img-class').attr('src', '');

**Comment by artf** [comment]
You can't just do `$('.img[src=""]')` GrapesJS components are not in the same context, are placed inside an iframe so you have to use the `document` from that iframe, eg.
```js
editor.Canvas.getDocument().querySelectorAll('.img[src=""]')
```
