### ISSUE TITLE
[Enhancement] Possible configuration bloat

### ISSUE THREAD

**Issue by benvmatheson** [artf/grapesjs#2203]
We had an issue with Grapes metadata (Components, Style, etc.) growing to the point it was causing issues on our end. After inspecting we noticed that the HTML/CSS grapes was outputting was less than 5k, but the Components/Style objects were storing at ~190k.

After looking into the components, I noticed most of the data is keys with empty/default values ("", [], 0, etc.). Would it be worth leaving these values out to save space, and changing the logic within grapes to assume undefined attributes represent empty/default values?

**Comment by devgru** [comment]
Consider using `avoidDefaults` flag, it reduces config footprint by removing these default values:
https://github.com/artf/grapesjs/blob/c1fb490a73adefb0fa073f37bef4e6178d9321a8/src/editor/config/config.js#L131

**Comment by artf** [comment]
> Consider using avoidDefaults flag, it reduces config footprint by removing these default values

Correct
