### ISSUE TITLE
[Feature] custom processor callback for components generated from Vue

### ISSUE THREAD

**Issue by pouyamiralayi** [artf/grapesjs#2204]
Hello there! i recently ran into this new awesome feature introduced [here](https://github.com/artf/grapesjs/blob/c1fb490a73adefb0fa073f37bef4e6178d9321a8/src/dom_components/config/config.js#L40-L58)
here you can have some processing done on the react generated element which is awesome.
for the moment i am working on some third party components that use vue as their compiler.
the current approach i am dealing with is as below that is working fine:
```js
script: function () {
                        const appl = new Vue({
                            el: '#ccid',
                            data: {
                                message: 'button'
                            },
                            template: '<q-btn>{{message}}</q-btn>'
                        }).$mount()
                        $(this).append(appl.$el);
                    }
```

it will result something like this:
![qbtn](https://user-images.githubusercontent.com/53266765/63349094-f292bd80-c36f-11e9-927e-300c4d3e75bd.png)

now the problem is this:

![qbtn](https://user-images.githubusercontent.com/53266765/63349266-48676580-c370-11e9-94cb-d510315ea075.png)

when you resize, it will resize the wrapper element, not the vue rendered one. if there was a way to process this iniside the component (like the way this new feature is doing it), it would be recognized by the editor and would be part of the model. is there any workaround for this?

thanks in advance.

**Comment by artf** [comment]
mmm probably I didn't describe it correctly, especially with this:
```js
// By default, GrapesJS supports already React Element
```
I need to correct it with 
```js
// By default, GrapesJS supports already elements generated from React JSX preset
```

So the point of this feature is simply to understand objects generated from JSX and transform them into GrapesJS component definition objects and NOT for understanding React/Vue components itself

In your example, you successfully load a Vue component but you can't edit it as it's not part of the editor, it's more like a static content for the editor. You might probably need some custom CSS to make those buttons expand to the wrapper.
