### ISSUE TITLE
[QUESTION] Text component converted to Box after saving

### ISSUE THREAD

**Issue by inaLar** [artf/grapesjs#2205]
I have a custom component when dropped inside a Text component (I am using a custom text component that extends the original text component) after saving and reloading the HTML/CSS I am experiencing the same problem - the text component converts to a Box. I use a custom attribute, but no matter the attribute the type of the component converts from Text to Default.
P.S.: The custom component becomes editable on double click.

Before saving:

`<div data-gjs-type="text" data-highlightable="1" data-text-extended="Text">Insert <span data-gjs-type="custom-type" contenteditable="false" data-gjs-textable="true" >Custom comp test</span>your text here</div>`

On loading already saved content:

`<div data-gjs-type="default" data-highlightable="1" data-text-extended="Text">Insert <span data-gjs-type="custom-type" contenteditable="false" data-gjs-textable="true" >Custom comp test</span>your text here</div>`

Related issues: https://github.com/artf/grapesjs/issues/761

**Comment by pouyamiralayi** [comment]
do you define your custom type inside a plugin?

**Comment by inaLar** [comment]
@pouyamiralayi , yes I am defining the custom type in a function/plugin. Could this be a problem?

**Comment by pouyamiralayi** [comment]
no! not defining it in plugin has some storage issue. see if [this](https://github.com/artf/grapesjs/issues/2179#issuecomment-517666958) can help you fixating the wrapper for every usage.
cheers.

**Comment by inaLar** [comment]
I have managed to get to the point that this works by editing the isComponent, but now when I load the stored data again, if there are children inside this custom text component they remain selected(highlited). Do you know an easy way to affect components children class="" on render?

`isComponent: function (el) {
            if (el.tagName === 'DIV'  && el.getAttribute('data-text-extended') === 'Text') {
                return { type: 'text', name: 'Text', content: el.innerHTML, components: [] }
            }
          },`

Where innerHTML could be:
`Insert your <span data-gjs-type="custom-tag" data-highlightable="1" class="gjs-comp-selected">Some text</span>text here`

**Comment by pouyamiralayi** [comment]
hi! notice that using isComponent, you only have access to the element dom and not the model itself.
but when you use the solution i mentioned in above comment, you have access to the model as the parameter(argument named 'element' in that code) and then you can iterate through element.components() array and change their attributes.
cheers.

**Comment by pouyamiralayi** [comment]
because of the loading stage nature of your situation, just consider using this listener instead of:
`
editor.on('block:drag:stop')
`
use this:
`
editor.on('component:mount', function(el){
     if(el.attributes.tagName === 'tagName'){
        el.components().forEach(comp => {// your modifications on the children components})
        //or
       el.components('<tag></tag>') // resetting the internal children
    }
})
`

**Comment by inaLar** [comment]
Hi! This is very useful information - about accessing the model this way instead the DOM.
I will explore it. I still don't understand why the gjs-comp-selected class is stored in the innerHTML precisely when I drop the custom component inside a text component. Maybe this is just uncovered behavior.

Also I am exploring the option to remove the class attribute (gjs-comp-selected) from the custom component inside its model, onRender(). But still determining the parent from child model is a new territory for me :)

**Comment by pouyamiralayi** [comment]
> Also I am exploring the option to remove the class attribute (gjs-comp-selected) from the custom component inside its model, onRender(). But still determining the parent from child model is a new territory for me :)

well as suggested at above comments, you have access to the component, so now you can iterate through its children as said before. on the iteration detect the proper child. for your case, first determining the parent:


```
editor.on('component:mount' , function (el) {
        if(el.attributes.tagName === 'div' && el.attributes['text-extended'] === 'Text'){
           // here el is our parent div with data-text-extended='Text'
               el.components().forEach(comp => {
                    if(comp.attributes.tagName === 'span'){
                           //here comp is our specific child span with that unwanted class
                           const classes = comp.get('classes')
                           classes.forEach(cls => {
                               if (cls.id === 'gjs-com-selected'){
                                   classes.remove(cls)
                               }
                           })
                    }
               }
})
```
cheers.

**Comment by inaLar** [comment]
@pouyamiralayi, yes, I have done exactly the same and it is working, but also I've managed to iterate via tagName in the isComponent of an extended text component and this also works in my case.
I will close the question now.

Thank you very much for all the inside! 

Cheers
