### ISSUE TITLE
Style value to "undefined !important"

### ISSUE THREAD

**Issue by WebEtSolutions** [artf/grapesjs#2206]
Hi !

Little problem when I type a style property with important. When I clear the value of the field (like color type for exemple) value is set to "undefined !important".

For fix this, on Property.getFullValue, you must check the value before add " !important" :

if (value !== undefined && this.get('important')) 
{
        value = `${value} !important`;
}

Bye !

**Comment by artf** [comment]
Thanks @WebEtSolutions it'll be fixed in the next release
