### ISSUE TITLE
Button active state

### ISSUE THREAD

**Issue by zgeist** [artf/grapesjs#2208]
Have problem with button active state

![0f3a046be015a260dfcdd6069a8a378e](https://user-images.githubusercontent.com/6919961/63423129-4eaf1d80-c414-11e9-9f8c-efc9e7a42a55.gif)

If button already active, when click active state have unset

Probably wrong logic here https://github.com/artf/grapesjs/blob/dev/src/panels/view/ButtonView.js#L142

How can I extend `toogleActive` method?

**Comment by artf** [comment]
I think the issue is just with the webpage preset (didn't have time to update) but is the same property described in getting started: https://grapesjs.com/docs/getting-started.html#style-manager
You have to add the button with `togglable: false` property

**Comment by kerryj89** [comment]
I'm having this same issue and the link @artf mentioned while it starts with active state it stops working when you click on another device.
