### ISSUE TITLE
blockManager.remove not working

### ISSUE THREAD

**Issue by aryeharmon** [artf/grapesjs#221]
when i use blockManager.remove i get an output with the insatnce of the block. if i call it again i will get undefined, however the block does not get removed from the list.

that being said, when i use blockManager.add it a new block gets added to the list with no problem.

**Comment by artf** [comment]
Seems like just the view is not updating, will fix it for the next release

**Comment by aryeharmon** [comment]
i fixed this issue, 
Question regarding pull requests, should i run npm run build before pushing?

**Comment by artf** [comment]
👍 
> should i run npm run build before pushing?

I'll do it before pushing the release so don't worry
