### ISSUE TITLE
Editing text in Safari doesn't work

### ISSUE THREAD

**Issue by redgenie** [artf/grapesjs#2210]
When you open the [demo page](https://grapesjs.com/demo.html) in Safari, you cannot edit the text.

**Comment by artf** [comment]
mmm seems like the `draggable` (introduced in https://github.com/artf/grapesjs/releases/tag/v0.15.3 with the `draggableComponents` option) and `contendeditable` are not working great together in Safari

For now, I can only suggest disabling `draggableComponents`, btw thanks for the report

**Comment by StudPro** [comment]
Hi,
the same problem with Firefox and Edge last version.
Thank's

**Comment by artf** [comment]
@jesusdp 
```js
grapesjs.init({
	// ...
	domComponents: { draggableComponents: false },
})
```

**Comment by stpp2** [comment]
@artf - a little random to revive this old thread, but this still seems to be an issue with Safari - any chance `draggableComponents` can be set to `true` and still work on Safari?

It's been 5 years since this issue so hopefully the browser has evolved enough to get a better solution.
