### ISSUE TITLE
[QUESTIONS] How to set style for pseudo elements (:after and :before)

### ISSUE THREAD

**Issue by abozhinov** [artf/grapesjs#2211]
Hi, 
I add STATE in style manager :before and :after but all the styles are applied to the component.

**Comment by artf** [comment]
Do you mean during the editing? Do you see it good if you deselect the component?

**Comment by abozhinov** [comment]
Yes during the editing. My idea was to implement the pseudo elements. When you select component to select state like hover, but to be :after or :before.
The problem is that I need to set content: '' in the css rule and all the styles are applied on the main element.

**Comment by artf** [comment]
Ok but is it correct once you deselect the component?

**Comment by abozhinov** [comment]
When deselect the component all the styles disappear.

**Comment by artf** [comment]
@abozhinov weird, can you create a live demo please?

**Comment by abozhinov** [comment]
Check here https://codepen.io/abozhinov/pen/YzKrzQr 
Just add two states. When select element and choose :before all the styles applied to selected component. When deselect it the styles disappear.

**Comment by artf** [comment]
Ok actually pseudo-elements ::after/::before don't exist without a proper `content` value, this is why you can't see them after the deselect, but at first, I have to find a way to avoid the helper class (`.hc-state`) for pseudo-selectors like this

**Comment by chaegumi** [comment]
```javascript
css.setRule(`#${id} .jeawin-icon-list-item:not(:last-child):after`, {
                        content: '""',
                        height: '100%',
                        'border-color': '#009499'
                    });
```
