### ISSUE TITLE
Extending default image component, resizable properties ignored

### ISSUE THREAD

**Issue by angelocala94** [artf/grapesjs#2212]
I'm trying to extend the default image component.

```
export default function(editor) {
    editor.DomComponents.addType("image", {
        model: {
            defaults: {
                resizable: {
                    autoHeight: true,
                    keepAutoHeight: true,
                    tc: false,
                    bc: false,
                    cl: false,
                    cr: false
                },
                traits: [
                    {
                        type: "checkbox",
                        label: "Test",
                        name: "test",
                        changeProp: 1
                    },
                    "alt"
                ]
            }
        }
    });
}
```

I can see my "Test" trait, so I assume that the component is correctly overridden, but the `resizable`properties are completely ignored.

Could anyone help me to figure out why?

**Comment by angelocala94** [comment]
```
init: function() {
    this.set("resizable", {
        ratioDefault: 1,
        autoHeight: true,
        keepAutoHeight: true,
        tc: false,
        bc: false,
        cl: false,
        cr: false
    });
}
```

I'm able to set `resizable` property manually inside the component init function, but this is not the best way to do that.

**Comment by angelocala94** [comment]
Since the `resizable` property is part of the component model, the existing components (previously saved on DB) in the canvas have the old `resizable` settings.

This will replace your `resizable` configuration with the default one to all `image` components.

``` 
init: function() {
    this.set(
        "resizable",
        editor.DomComponents.getType("image").model.prototype
                        .defaults.resizable
    );
}
```

**Comment by artf** [comment]
Try to use `config.avoidDefaults` option as `true`
Probably I'll set it to `true` by default in the next release
