### ISSUE TITLE
[Question] CSS property always added to the end of sector

### ISSUE THREAD

**Issue by benvmatheson** [artf/grapesjs#2213]
I wanted to add `min-height` and `max-width` to the default properties. Is it possible to add these next to `max-height` instead of at the end of the sector? Or will I need to just manually define the entire sector in order to manage property order?

Also, I was just curious why these weren't included in the defaults?

Thanks for making such a rad project!

**Comment by artf** [comment]
> Is it possible to add these next to max-height instead of at the end of the sector? Or will I need to just manually define the entire sector in order to manage property order?

Unfortunately, currently, you have to define the entire sector. I'll add `at` option (same as in [`addSector`](https://grapesjs.com/docs/api/style_manager.html#addsector)) in the next release

> Also, I was just curious why these weren't included in the defaults?

IDK to be honest, probably those I have defined were already enough

> Thanks for making such a rad project!

Thanks to you for using it 😁
