### ISSUE TITLE
[BUG] SVG Element is not a real SVGElement 

### ISSUE THREAD

**Issue by Firefox2005** [artf/grapesjs#2214]
**Behavior**
I use an external Javascript code that replaces some SVG elements dynamically based on their attributes. The Javascript code first checks for the type of the element to validate, that it is an SVGElement like this:

`document.querySelector('#someId') instanceof SVGElement`

The code returns True in Firefox but False in Safari and Chrome although I can verify in the Chrome Properties tab, that it is indeed of type SVGElement.

**How I create the SVG Element**
I tried different things but ended up using a Plugin.

**_component.js_**
```javascript
domc.addType('myType', { 
    isComponent: function(el) {
      if(el.tagName == 'svg' && el.classList && el.classList.contains('someClass'))
        return {type: 'myType'};
    },
    extend: 'svg',
    model: {
      defaults: {
        type: 'svg',
        tagName: 'svg',
        name: 'SomeName',
        traits: [...],
        attributes: {
          class:'someClass',
          ...
        },
        script: function () {
          console.log(document.querySelector('.someClass'));
          console.log(document.querySelector('.someClass') instanceof SVGElement)
          ...
        },
      }
    }
});
```
**_blocks.js_**
```javascript
bm.add('myBlock', {
    label: 'someLabel',
    category: 'someCategory',
    name: 'blockName',
    content: '<svg class="someClass"\
                ...\
              </svg>'
});
```

**Additional Information**
According to this: [https://stackoverflow.com/questions/24174975/document-createelementsvg-instanceof-svgelement-is-false](url) SVG elements are special, but from what I can see in src/dom_components/view/ComponentSvgView.js I assume, that they are created correctly.

Of course there is nothing wrong with the generated HTML-Code when using it, as browsers will then use the correct SVG - it is just not showing up when editing in GrapesJS.

**Comment by artf** [comment]
> The code returns True in Firefox but False in Safari and Chrome although I can verify in the Chrome Properties tab, that it is indeed of type SVGElement.

Weird, seems like a Chromium issue...
