### ISSUE TITLE
[BUG] Resizing canvas on Safari

### ISSUE THREAD

**Issue by alimajed93** [artf/grapesjs#2215]
Hello,

I am having the following problem when switching between Desktop view, tablet view and mobile view in GrapesJs:
When the template contains an image, strips with the same "pattern" of the image appear when switching to a smaller view as shown below:
![Screen Shot 2019-08-23 at 5 19 17 PM](https://user-images.githubusercontent.com/28840780/63599505-6a5c2480-c5ca-11e9-81bb-021a248ec02e.png)
![Screen Shot 2019-08-23 at 5 19 08 PM](https://user-images.githubusercontent.com/28840780/63599508-6defab80-c5ca-11e9-99ed-7cb6dd7bb459.png)
Those lines will disappear when I inspect element, trying to get more info about them and what are they actually.

Can anyone please help in this? Has anyone faced this before?

Thanks and regards.

**Comment by artf** [comment]
Seems the same issue of https://github.com/artf/grapesjs/issues/1240
