### ISSUE TITLE
Could anyone give me a proper guideline for making cell components in blockmanager which add others components inside them (Like coumn1, column3/7 and vise versa)

### ISSUE THREAD

**Issue by nikhilmate** [artf/grapesjs#2221]
## WARNING
READ and FOLLOW next 5 steps, then REMOVE them before posting the issue

1. Follow CONTRIBUTING Guidelines https://github.com/artf/grapesjs/blob/master/CONTRIBUTING.md
2. Use the GitHub Issues EXCLUSIVELY for BUGS, FEATURE REQUESTS or QUESTIONS. Prefix the title of the issue with its context, eg. `[Bug]: ....`
3. Do a quick SEARCH first, to see if someone else didn't open the same issue
4. DON'T ASK to create examples/code for you, read DOCS and APIs first, then you can post what you have tried (we'd like to see your code) and what you're unable to achieve
5. All relative statements/questions have to be filled/answered, otherwise, the issue might be CLOSED

## You're submitting a BUG
  1. Are you using the latest release (older versions are NOT supported)?
      1. If you're not sure, type `grapesjs.version` in console and press ENTER
  1. Are you facing the bug with your local copy of GrapesJS or with the current demo?
  1. If a local copy
      1. Indicate all informations about your OS, browser and GrapesJS version.
      1. Are you able to reproduce the bug from the demo?
  1. What is the expected behavior?
  1. What happens instead?
  1. If you're able to reproduce the bug indicate all the necessary steps
  1. Attach screenshots (using KAP/LICEcap), screencasts or live demo
     1. JSFiddle Starter template https://jsfiddle.net/szLp8h4n
     1. CodeSandbox Starter template https://codesandbox.io/s/1r0w2pk1vl

## You're submitting a FEATURE REQUEST
  1. Be sure to work on the latest version, as the feature might be already there
  1. Keep in mind that the feature should be considered valid to use for everyone, not only for your case

**Comment by artf** [comment]
https://grapesjs.com/docs/modules/Blocks.html

**Comment by smik3** [comment]
I am also getting really confused about this. For example, how do you decide where to put the html markup, in the block content property or in the component view property?

**Comment by artf** [comment]
> For example, how do you decide where to put the html markup, in the block content property or in the component view property?

It depends, but I highly suggest to adopt more a component-oriented approach, so blocks could only be a mix of already defined components.

```js
Blocks.add('...', {
	...
	content: {
		type: 'component-type-1',
		components: [
			{ type: 'component-type-2' },
			{ type: 'component-type-2', someProp: '...' },
		]
	}
})
```

**Comment by smik3** [comment]
Yeah, after 3-4 re-writes I've managed to get to the approach there, haha. Would it be possible for that snippet to be added to the docs? It's taken a few days of searching through issues to see that it is even possible to pass an array of components to the content property
