### ISSUE TITLE
[Question] Should default text-align property have icons?

### ISSUE THREAD

**Issue by benvmatheson** [artf/grapesjs#2223]
If styleManager is left out of the configuration, the default includes `text-align` with icons showing the choices.
![image](https://user-images.githubusercontent.com/9043745/63802171-3a18cc80-c8cf-11e9-9f08-88c4b4c87307.png)

If I include a styleManager configuration and add `text-align`, it uses words instead.
![image](https://user-images.githubusercontent.com/9043745/63802288-85cb7600-c8cf-11e9-94e5-debff3ad4919.png)

Should this be the case since it's a "built in" property, or do I still need to manually add the icons?

**Comment by ramusesan** [comment]
hi @benvmatheson all you have to do is
include fontawesome in your project and  add the class Names

i.e 
```
{
                                property: 'text-align',
                                defaults: 'left',
                                list: [
                                    { value: 'left', name: 'Left', className: 'fa fa-align-left' },
                                    { value: 'center', name: 'Center', className: 'fa fa-align-center' },
                                    { value: 'right', name: 'Right', className: 'fa fa-align-right' },
                                    { value: 'justify', name: 'Justify', className: 'fa fa-align-justify' }
                                ],
                            },
```

**Comment by artf** [comment]
@benvmatheson I preferred not to bind the font-awesome dependency (that I still hope to remove soon) to the property factory
