### ISSUE TITLE
[QUESTION] Updating a component type trait definition after init

### ISSUE THREAD

**Issue by tliscomb** [artf/grapesjs#2226]
I have created a custom component & block which is used to display/embed uploaded files. 

I have defined traits for this component see below. When a new file is uploaded I need to update the options of the selected-src trait so that the user can use the select in the settings panel to select the file to be displayed. 

```
                        traits: ['title', 'id',
                            {
                                type: 'select',
                                label: 'file',
                                name: 'selected-src',
                                options: files
                            },
                            {
                                type: 'text',
                                label: 'Override',
                                name: 'override-src',
                                placeholder: 'path to file'
                            }
                        ],
```

Any help would be greatly appreciated.

**Comment by pouyamiralayi** [comment]
Hello! you must attach a listener for the file property, so whenever it changes to a new value(file),
your listener will append it to the end of the options:
```
            model: {
                defaults: {
                    ['selected-src']: '',
                    tagName: 'div',
                    resizable: true,
                    content: '<b>UPLOAD</b>',
                    traits: [
                        {
                            id: 'selected-src',
                            type: 'select',
                            label: 'file',
                            name: 'selected-src',
                            options: files,
                            changeProp: 1,
                        },
                    ]
                }
            },
            view: {
                init() {
                    this.listenTo(this.model, 'change:selected-src', this.doStuff)
                },
                doStuff() {
                    const trait = this.model.getTrait('selected-src')
                    const traitOptions = [{name: 'new file', value: 'new file url'}]
                    trait.set('options', [...trait.get('options'), ...traitOptions])
                },
            }
```
**NOTICE** here i am listening to the changes on the selected-src itself, for your case you must listen to your file related property.
**NOTICE** i see that for your selected-src trait definition, you have not specified chageProp. if it is intentional then you are dealing with an attribute of the component and listener attachment would be like this:
``
init() {
         this.listenTo(this.model, 'change:attributes:selected-src', this.doStuff)}
``
cheers.

**Comment by artf** [comment]
Yeah the key part proposed by @pouyamiralayi is here
```js
const trait = this.model.getTrait('selected-src')
const traitOptions = [{name: 'new file', value: 'new file url'}]
trait.set('options', [...trait.get('options'), ...traitOptions])
```
This is how you update traits at run-time (more about this [here](https://grapesjs.com/docs/modules/Traits.html#updating-traits-at-run-time))
