### ISSUE TITLE
Target collection not found

### ISSUE THREAD

**Issue by kickbk** [artf/grapesjs#2228]
@artf, could we please get the `Invalid target position: Target collection not found, Target is not droppable, accepts [undefined], Component not draggable, acceptable by [undefined]` to return values instead of `[undefined]`in the next release?
I realize it's just a warning and not a top priority, but would be nice to have it return real values.

**Comment by artf** [comment]
Unfortunately, the Sorter instance (the one which creates that warning) is the one we have to refactor (the code is old and has other bugs), it's already in my todo list, so I hope to update it soon. For now, I can only check for undefined and print empty string, but is pointless

**Comment by navewi** [comment]
Hello anything new on this? I have the same warning now and i can't drop the image block. 
`Invalid target position: Target collection not found, Target is not droppable, accepts [undefined], Component not draggable, acceptable by [undefined]` This has worked before and i can't find a mistake in my code.

**Comment by artf** [comment]
@navewi, unfortunately, didn't have time to work on this :/

**Comment by navewi** [comment]
@artf No Problem, the warning is gone for now, i think i got a mistake in my code.
