### ISSUE TITLE
[QUESTIONS] ignore select component in undo and redo

### ISSUE THREAD

**Issue by fmr411** [artf/grapesjs#2229]
can I ignore the select component in the undo or redo process?

**Comment by artf** [comment]
Nope, right now is quite hard to avoid

**Comment by Franci5co5aoco** [comment]
> can I ignore the select component in the undo or redo process?

Hi @artf any update on this?
Thanks!

**Comment by artf** [comment]
https://github.com/artf/grapesjs/discussions/4226
