### ISSUE TITLE
[Suggestion] Insert a image inside link

### ISSUE THREAD

**Issue by rgcarrasqueira** [artf/grapesjs#223]
Hi Art!

A feature that is really needed is about insert a link into a image or have a link can place a image inside a link. Today it cannot possible to do that using drag and drop feature. We have to edit the html code e insert it by hands.

Thanks.

**Comment by aryeharmon** [comment]
@rgcarrasqueira create an "a" tag component then put the image in there.

**Comment by rgcarrasqueira** [comment]
I've already tried to do that, see what is happening

![screen shot 2017-08-09 at 11 16 35](https://user-images.githubusercontent.com/97540/29126308-60cc8b42-7cf4-11e7-8184-b8038c49709b.png)

**Comment by aryeharmon** [comment]
@artf i am working on a component builder, where one can save and build custom components. saving them externally or locally. is that something your interested in adding to the project once completed? 
For example someone wanting to add an 'a' tag component will be able to do so from the UI.

**Comment by rgcarrasqueira** [comment]
It will be great!

**Comment by rgcarrasqueira** [comment]
See my screencast
![kapture 2017-08-09 at 11 40 01](https://user-images.githubusercontent.com/97540/29127468-8ab9a978-7cf7-11e7-8ec9-1dedbfe4e6c5.gif)

**Comment by aryeharmon** [comment]
@rgcarrasqueira add screenshot of layer manager link section

**Comment by rgcarrasqueira** [comment]
Ok, it follows

![kapture 2017-08-09 at 13 20 04](https://user-images.githubusercontent.com/97540/29132115-83ea9e8c-7d05-11e7-94f7-e1df53421cde.gif)

But I must confess we have to improve better this, because the user experience is not going well. I have some uses with not high acknowledge like us and are having some problems to deal with this use case.

**Comment by aryeharmon** [comment]
It seems to me we should set a minimum hight for links. To make sure you can drop into it.

**Comment by aryeharmon** [comment]
5px should do it

**Comment by rgcarrasqueira** [comment]
Ok, how to set it? I think it not intuitive for final user

**Comment by aryeharmon** [comment]
Edit the component code. Add style property min-height: 5px

**Comment by rgcarrasqueira** [comment]
I think that is a problem, because this is inside the grapejs-preset-newsletter plugin, I have to change it and ask for a pull request. Have you got my point that means that it is not intuitive?

**Comment by aryeharmon** [comment]
So fork, and use your fork. Yes I agree with you. I am in the middle of
making a builder for the component's so we will be able to edit them

**Comment by rgcarrasqueira** [comment]
I would like to help you, how to join with you in this journey?

**Comment by aryeharmon** [comment]
i created a small little dirty prototype today, i will commit tomorrow to my fork and we can implement it properly.

**Comment by artf** [comment]
@aryeharmon would be awesome to see your work as a plugin :)
@rgcarrasqueira #88 the Link Block was made for this purpose

**Comment by rgcarrasqueira** [comment]
Art, sorry I did not understand why you closed this ticket. I think that this matter still remains.

**Comment by artf** [comment]
Sorry @rgcarrasqueira but I think the #88 explains pretty much well the same situation. You can't attach links on the Image Component but there is 'Link Block'. 
Without the link block, you should probably create a new component type, best as a plugin
