### ISSUE TITLE
[QUESTIONS] Can i load data from variables

### ISSUE THREAD

**Issue by fmr411** [artf/grapesjs#2230]
Can i load data from variables, not from the server, like
`var datajson = editor.store();`
`editor.load(datajson);`
I've learned (https://grapesjs.com/docs/modules/Storage.html#storage-api), but still did not understand examples if they included the new logic to load the data, Thank You

**Comment by artf** [comment]
You can use [`editor.setComponents`](https://grapesjs.com/docs/api/editor.html#setcomponents) and [`editor.setStyle`](https://grapesjs.com/docs/api/editor.html#setstyle)
