### ISSUE TITLE
css issue in getCss

### ISSUE THREAD

**Issue by ramusesan** [artf/grapesjs#2231]
FYI: am using 0.15.3
i have loaded a html component into editor and saved for multiple times i noticed that how many times we load /edit and save the same html component  that many times the css are appending even with same id, class etc
![bug1](https://user-images.githubusercontent.com/15937743/63932342-a2ed7980-ca74-11e9-8547-38e0104d1d71.png)
![bug2](https://user-images.githubusercontent.com/15937743/63932343-a2ed7980-ca74-11e9-8f9a-a63bbb24ee6f.png)

**Comment by makkaronis4e** [comment]
I bet you’ve changed this parameters:
![B45B0E93-DCAE-4389-A413-D844C0E004ED](https://user-images.githubusercontent.com/33792090/63982773-87ae5880-cacc-11e9-843a-b5adc8122370.jpeg)

You save wrapper all the time

**Comment by ramusesan** [comment]
i didn't changed any parameter even i dunno where these properties are exist , can you tell me where i can see this properties and change the value of it

**Comment by ramusesan** [comment]
am not only getting body style am also getting all the style duplicating i.e what are the components i have moved / drag and dropped for multiple times saved and reloaded that times am getting duplicating styles

**Comment by makkaronis4e** [comment]
mb this will help you #609

**Comment by ramusesan** [comment]
@makkaronis4e  still facing same issue 

`#elem_stu_photo{transform: translateX(635px) translateY(70px);}#elem_stu_photo{transform:translateX(237px) translateY(8px);}.c5689{background-color:!important;}.c5975{background-color:!important;color:!important;}.c6218{color:#FF0000 !important;}.c6278{background-color:#005a70 !important;color:#fff !important;}`

**Comment by artf** [comment]
@ramusesan if you don't create a reproducible live demo of the issue I can't afford to invest my time on debugging this. IMHO it might also be an issue due to your custom storing logic... 
If you have an issue you should follow the [BUG] issue template

**Comment by vinceumo** [comment]
I have the same issue, I create a small codesandbox https://codesandbox.io/s/snowy-wave-85dxo?file=/index.js

Steps to follow,

- Look at the default export
- Click on the flask icon, edit some properties
- Look at the export, you should have `*` and `body` duplicated

Adding `protectedCss: ''` fix the issue for me
