### ISSUE TITLE
editing of text separately

### ISSUE THREAD

**Issue by ovesyan19** [artf/grapesjs#2233]
Hi! Thanks for the great library!
I am using webpage plugin and what I am interested in is editing text. I know that this functionality is already in there and we can edit text by double clicking on it, but how can I do it separately? like having an additional dropdown on the right pane where "General", "Typography" etc. live to make changes there in some textarea

**Comment by artf** [comment]
You can add a custom [Trait](https://grapesjs.com/docs/modules/Traits.html) which updates the component content (`component.components('<span>New content...</span>')`) on input change
