### ISSUE TITLE
I/O operations with PHP/MySQL - I'm stuck

### ISSUE THREAD

**Issue by arievanden** [artf/grapesjs#2234]
Hello and thank you for GrapesJS. It's awesome. I do have a question that I haven't been able to find an answer to. I'm using PHP/Yii and MySQL db.

Your example for external storage config:

> storageManager: {
    type: 'remote',
    urlStore: 'http://endpoint/store-template/some-id-123',
    urlLoad: 'http://endpoint/load-template/some-id-123',    
  }

> {
  // `gjs-` is the id prefix
  'gjs-components': [{ tagName: 'div', ... }, {...}, ...],
  'gjs-style': [{...}, {...}, ...],
}

My problem is that I'm trying to get the HTML to JSON conversion formatted properly before saving to the db record so we can pull it up again from urlLoad. I can't find ANY clear examples of how to do this from PHP. I could try using the Firestore plugin and save myself the trouble, but I thought I'd ask if there were any clear examples of how to do I/O operations with PHP/MySQL.

Maybe using HTML-5 html2json (http://masterminds.github.io/html5-php/) would help? Or does GrapesJS automatically do the HTML to JSON/DOM conversion on the fly? It's not clear to me from the docs.

**Comment by smik3** [comment]
Is there any reason why you can't use PHP to save it directly as a JSON file rather than on the database?

**Comment by arievanden** [comment]
I probably could, but we need to saved to DB. I'm OK, a developer figured it out for me, but it would be great to have some more detailed code examples for use with php/mySQL. Your docs are great, but this would be a nice addition to your docs section.

**Comment by artf** [comment]
> My problem is that I'm trying to get the HTML to JSON conversion formatted properly

GrapesJS, by default, generates 4 types of data: HTML, CSS, Components (JSON from HTML), Styles (JSON from CSS)
So you shouldn't do any kind of conversion... it's explained here https://grapesjs.com/docs/modules/Storage.html#store-and-load-templates
