### ISSUE TITLE
Styles are overriding when new styles are added for different device

### ISSUE THREAD

**Issue by damey2011** [artf/grapesjs#2235]
Great project.. I'm trying to integrate this and I have this issue. 
Assuming I have a style for Desktop already and I add a new style for mobile for example, instead of creating a media query for mobile, it overwrites it without creating any media query.
Any help ?

**Comment by artf** [comment]
Please @damey2011 follow the [BUG] template when you open an issue like this, with the current information it's impossible to us give you any valid help
