### ISSUE TITLE
[QUESTION] General editor updates using editor.on('update') event

### ISSUE THREAD

**Issue by gabd1411** [artf/grapesjs#2237]
Hi! Is there a way to get general, last editor updates using editor.on('update') event?
Something like this:
editor.on('update', e => {
  // get the event
 // get the specific, recent updates (HTML and CSS) 
})

**Comment by gabd1411** [comment]
I've found another available event, editor.on('change'), but it seems difficult to read the HTML and CSS updates from that event

**Comment by olgertpysqyli** [comment]
Hello.
You can declare variables for html, css and js and their value is going to get updated every time when editor change event is triggered.

`change() {
      this.html = editor.getHtml();
      this.css = editor.getCss();
      this.js = editor.getJs();
}`

`editor.on('change', this.change);`
