### ISSUE TITLE
[QUESTION] Is this the expected behaviour of the RichTextEditor?

### ISSUE THREAD

**Issue by adriangroch** [artf/grapesjs#2241]
When the `rte` section of the editor config is defined, I'm assuming that the defined default actions should reflect the `actions` array:
```
const editor = grapesjs.init({
  // ...
  rte: {
    actions: ['bold']
  }
});
```
Meaning that this should _should_ only render the `bold` action

Instead all default actions are instantiated: `'bold', 'italic', 'underline', 'strikethrough', 'link'`
See: https://codesandbox.io/s/pedantic-sky-qs5qj

Additionally, I've cloned the branch locally, and have replaced the `actions` array in `src/rich_text_editor/config/config.js`:
```
export default {
  stylePrefix: 'rte-',

  // If true, moves the toolbar below the element when the top canvas
  // edge is reached
  adjustToolbar: 1,

  // Default RTE actions
  // actions: ['bold', 'italic', 'underline', 'strikethrough', 'link']
  actions: []
};

```
And the same behavior is present.

Is this the expected default behavior, or am I missing something?

**Comment by artf** [comment]
mmm wrong key in docs... it should be
```js
const editor = grapesjs.init({
  // ...
  richTextEditor: {
    actions: ['bold']
  }
});
```
thanks for the report
