### ISSUE TITLE
how do I change "- State -" and "Selected"

### ISSUE THREAD

**Issue by parmando** [artf/grapesjs#2242]
Hello, how do I change "- State -" and "Selected" I need to translate this ...
Thank you
![select](https://user-images.githubusercontent.com/2301752/64298595-85c11b00-cf4c-11e9-8d9a-ca94fb4f1b5d.jpg)

**Comment by artf** [comment]
Comes from [selector manager configuration](https://github.com/artf/grapesjs/blob/dev/src/selector_manager/config/config.js)
```js
grapesjs.init({
	//...
	selectorManager: {
		statesLabel: '- State -',
		selectedLabel: 'Selected',
	}
})
```

**Comment by parmando** [comment]
Thank you! Where can I find a full map "map" for me to translate?

**Comment by artf** [comment]
Sorry there is no full map at the moment, any module has its own options for strings
