### ISSUE TITLE
[FEATURE REQUEST] - place cursor in position when clicking inside text node

### ISSUE THREAD

**Issue by arievanden** [artf/grapesjs#2244]
When you click on a text node, the cursor is at the beginning of the block. Clicking again doesn't move the cursor into position when you want to insert more text, so you must use the arrow key to move the cursor into position. Not a big deal, but it would be great if when you click on a text node to edit that it would place the cursor in the position of the mouse, at least on the 2nd click. This is standard behavior in most editors and would be a nice change if possible. Thanks!

Client: Win7/FF

**Comment by artf** [comment]
Indeed, this is how it should work...
It's due to this bug #2210
Already fixed and ready for the next release (hope to publish it this week)
