### ISSUE TITLE
[QUESTIONS] how do I change the "Layer" in text shadow?

### ISSUE THREAD

**Issue by parmando** [artf/grapesjs#2246]
Hello, how do I change the "Layer" in text shadow. I need to translate this ...
Thank you
![layer](https://user-images.githubusercontent.com/2301752/64391270-84602300-d01e-11e9-922f-2a7dc0a2ff00.JPG)

**Comment by TheDiamondKing** [comment]
I do not think you can do that... but you can change the html of the page when the style is added or updated using jquery or javascript. Like `replace(/Layer/g, 'Other')` in editor update.

**Comment by parmando** [comment]
This is interesting ... but I can't implement it in practice.

**Comment by parmando** [comment]
> Eu não acho que você pode fazer isso ... mas você pode alterar o html da página quando o estilo é adicionado ou atualizado usando jquery ou javascript. Como `replace(/Layer/g, 'Other')`na atualização do editor.

How can I do this?
It would be like this?
editor= editor.replace(/Layer/g, "Other");

**Comment by artf** [comment]
I'll add a new option in the next release for this label, so you'll be able to update it in this way:
```js
grapesjs.init({
	// ...
	styleManager: {
		textLayer: 'MyLayer',
	}
})
```

**Comment by parmando** [comment]
Thank you! We really need a translation module ... it's very hard to work like that.
