### ISSUE TITLE
Global Settings

### ISSUE THREAD

**Issue by benoj** [artf/grapesjs#225]
Hi,

Are there any examples of global pages settingd – e.g. setting page title or setting Google Analytics Account etc..?

Thanks,

Ben

**Comment by artf** [comment]
See grapesjs as a template builder, not just as a page, so changing the title is out of the scope. What you can actually do, for instance, is printing/storing something before/after the final HTML (as I do in [grapesjs-plugin-export](https://github.com/artf/grapesjs-plugin-export/blob/master/src/main.js#L13-L14)). 
GA actually could be a [custom component](https://github.com/artf/grapesjs/wiki/Components)
