### ISSUE TITLE
adding Traits properties in canvas body[QUESTION]

### ISSUE THREAD

**Issue by Ramkumar-Murugesan** [artf/grapesjs#2251]
Hi,
I know that we add the traits options or properties for any component blocks. but I don't know how to add the traits for canvas body. can anyone please help me.

![image](https://user-images.githubusercontent.com/33427536/64472883-b4c0d200-d182-11e9-89d1-858fe6df5ff3.png)

In the above image. under the settings options. I need to add one input and radio button.

**Comment by artf** [comment]
You can add them at run time https://grapesjs.com/docs/modules/Traits.html#updating-traits-at-run-time

```js
editor.getWrapper().set('traits', [
	{ name: 'title', label: 'Title' },
])
```
