### ISSUE TITLE
Preview mode does not run the scripts

### ISSUE THREAD

**Issue by mariasmol** [artf/grapesjs#2252]
Hi all,
I am checking Grapesjs for our product
After allowing scripts in the editor and ,writing this simple example
![image](https://user-images.githubusercontent.com/54943482/64485465-f9537880-d229-11e9-86d3-108e2df14ad1.png)
i pressed the import and indeed saw the hello world which is great.
however when using the preview mode i don't see the alert ( or anything else i tried instead of the alert)  .
how can i make it work?
Do i need to configure something to execute scripts in preview mode?
thanks for the help!

**Comment by artf** [comment]
Scripts are working, the problem is that your script was already executed inside the editor and the preview mode doesn't re-render the content...
For any custom behavior, I would suggest creating your own preview command
