### ISSUE TITLE
[HELP] Unable to replace style for elements with id

### ISSUE THREAD

**Issue by makkaronis4e** [artf/grapesjs#2255]
Hi, 
i think that in API docs we need some clarification regarding **avoidInlineStyle: true**, that its still not default option, i've spent hours on investigating this style/id issue :)

**Comment by makkaronis4e** [comment]
I've created some small example here: https://codepen.io/makkaronis4e/pen/PoYQvYx?editors=1111

Steps to reproduce:
1. Element container has id="container" and some background image (which editor cant parse to styles manager (assets is empty));
2. Replace background image for container and press "CHECK CSS" button on the top, it will print ountput of editor.getCss() to console. In this output youll see something like:
![image](https://user-images.githubusercontent.com/33792090/64544835-5fc2be80-d330-11e9-9e8a-e09002f86362.png)

**Comment by artf** [comment]
yeah, you're right, I'll make it true, by default, in the next release and soon I'll probably remove it. 
IMHO it doesn't make sense to support the old inline-style method
