### ISSUE TITLE
 wrapper.set({ draggable: false }); not working in 0.15.5

### ISSUE THREAD

**Issue by ramusesan** [artf/grapesjs#2256]
am trying to prevent the user to drag/drop the component   on editor by setting **draggable: false**  
i.e wrapper.set({ draggable: false }); 

but this is  not responding now, actually it was working old version 0.14.62

**Comment by artf** [comment]
@ramusesan 
1. wrapper is not draggable by default (I'm able to update it anyway)
2. if you're talking about the update on other components, I can run `editor.getSelected().set({ draggable: false })` without any issue, the component becomes immediately not draggable

please provide a live demo example in case it's not true on your side
