### ISSUE TITLE
[HELP] Responsiveness gone

### ISSUE THREAD

**Issue by eltoredo** [artf/grapesjs#2257]
Hello,

I started a web page with GrapesJS from scratch. I was wondering why my forms and stuff aren't responsive like GrapesJS' demo.

I can show code if necessary but I don't think it will be necessary. Do I miss a plugin or something that makes the page responsive? Do I have to start a project based on the current demo code?

Thanks for your help,
Tanguy.

**Comment by artf** [comment]
Well, it all depends how you implemented your forms. If you don't include the CSS for the responsiveness you can build it in the editor (by changing the device and then its style)

**Comment by eltoredo** [comment]
I changed the CSS directly in the editor, what do you mean by 'indlucing' it then?
Oh, if I changed the style in the desktop mode, I have to do it for the two other devices as well? I thought that if I changed the style with percentages only, it would fit all the devices.

**Comment by artf** [comment]
> Oh, if I changed the style in the desktop mode, I have to do it for the two other devices as well? I thought that if I changed the style with percentages only, it would fit all the devices.

Make a live demo of your example because it's not clear what is wrong

**Comment by eltoredo** [comment]
What is wrong is that all the elements crush themselves into each other.

This is a screen in the mobile mode: https://imgur.com/a/CsTqwua
While it's perfectly fine in the Dekstop Mode, in  which I created all of the elements.

Thanks for your answers!

**Comment by theSC0RP** [comment]
@eltoredo If you have found the solution, can you please share it here? Thanks.

**Comment by eltoredo** [comment]
@theSC0RP I didn't, I just gave up on this, it was way too complicated for nothing haha

**Comment by theSC0RP** [comment]
@eltoredo Ohh okay 😅
