### ISSUE TITLE
Multiple Trait Manager Tabs

### ISSUE THREAD

**Issue by angelocala94** [artf/grapesjs#2258]
I know that I can use `appendTo`property to append the Trait Manager into a custom element.

```
traitManager: {
    appendTo: '.traits-container',
},
```

But there is a way to create more tabs and divide traits into these tabs by a category attribute?

**Comment by artf** [comment]
No, there is no available API to do so, someone tried already to implement categories in traits but being poorly implemented https://github.com/artf/grapesjs/pull/1790 I couldn't accept
For now, the only solution would be to play directly with the DOM (eg. hide/move some traits by changing the category tab/select)
