### ISSUE TITLE
[Bug] Deleted Element Styles Are Still Saved

### ISSUE THREAD

**Issue by wire-rabbit** [artf/grapesjs#2259]
Expected Behavior:
After deleting an element from the canvas that has received custom styles using the style manager, the deleted element's styles should no longer be saved in the `styles` JSON.

Actual Behavior:
The `styles` JSON retains entries for deleted elements on save.

Steps to Reproduce:
1. Fiddle based on the starter template that logs the `styles` JSON to the console on save is available at: https://jsfiddle.net/g48sLxrt/
2. Modify the default text block, changing its color to red using the style manager. The following appears in the console:
```json
[{"selectors":[{"name":"c620","label":"c620","type":1,"active":true,"private":false,"protected":false}],"style":{"padding":"25px","color":"red"}}]
```
3. Delete the existing, styled text block and add a new one. This output appears in the console:
```json
[{"selectors":[{"name":"c620","label":"c620","type":1,"active":true,"private":false,"protected":false}],"style":{"padding":"25px","color":"red"}},{"selectors":[{"name":"c1044","label":"c1044","type":1,"active":true,"private":false,"protected":false}],"style":{"padding":"10px"}}]
```
The deleted element's styles are still present.

Environment:
- Using version 0.15.5 of GrapesJS
- Tested on: Chrome 76.0.3809.132 and Firefox 69 on Ubuntu 18.04.3

**Comment by artf** [comment]
Try to use the `clearStyles` option
```js
const editor = grapesjs.init({
	// ...
	clearStyles: 1,
});
```

**Comment by wire-rabbit** [comment]
That resolves the issue. Thank you!
