### ISSUE TITLE
Drag and drop of selected text displays null

### ISSUE THREAD

**Issue by olgertpysqyli** [artf/grapesjs#2260]
Hello,
I have a problem with GrapesJS editor because when some text is selected in a component and when you drop it outside component it shows null or sometimes it shows the selected text and you cannot select or edit it.

Could you please help me how to fix this problem so when I select some text the whole text component to be dragged and not just the selected text.

I just checked the demo website and there it's ok.

Here I'm providing a video example of the issue.

![buggrapes](https://user-images.githubusercontent.com/17994334/64559657-1cc01580-d347-11e9-86e6-dcc71055a11b.gif)

**Comment by artf** [comment]
The issue seems to come from the CKEditor and we discussed it here #1797 so I close this one, reply there in case
