### ISSUE TITLE
[Question]: Is it possible to get CSS excluding protected CSS?

### ISSUE THREAD

**Issue by benvmatheson** [artf/grapesjs#2263]
I'm attempting to build this:
https://github.com/artf/grapesjs/issues/324

I've noticed that each time the CSS is saved, the protected CSS is prepended. This results in duplicate CSS rules:
`* {
  box-sizing: border-box;
}
body {
  margin: 0;
}
*{
  box-sizing:border-box;
}
body{
  margin-top:0px;
  margin-right:0px;
  margin-bottom:0px;
  margin-left:0px;
}`

Is it possible to fetch CSS excluding protected CSS, or will I just need to remove that manually?

**Comment by artf** [comment]
Use this option `editor.getCss({ avoidProtected: true })`
