### ISSUE TITLE
[QUESTION] Are there any component libraries?

### ISSUE THREAD

**Issue by Sparke2** [artf/grapesjs#2267]
# The question

I like grapesjs and I think that it is the best GUI builder solution but I can't find any built-in component libraries.

I know there are [official extensions](https://github.com/artf/grapesjs#extensions) but there are few elements.

Are there any additional plugins/ libraries/ templates? May be developed by some 3d party devs.

I'm looking for

- [ ] progress bar

- [ ] pagination

- [ ] dropdown menus

- [ ] burger menus

- [ ] modals

- [ ] cards element

For example [LayoutIt](http://bit.ly/2NXrDdN) supports a wide variety of elements and I wanted to use the same elements in GrapesJS without a requirement to rewrite them all by hands.

**Comment by artf** [comment]
Try this one: https://github.com/kaoz70/grapesjs-blocks-bootstrap4
