### ISSUE TITLE
[BUG] `textable` component disappears with custom RTE

### ISSUE THREAD

**Issue by adriangroch** [artf/grapesjs#2272]
1. Are you using the latest release (older versions are NOT supported)?
Yes

  1. Are you facing the bug with your local copy of GrapesJS or with the current demo?
Current demo & local, also using the [CKEditor plugin](https://github.com/artf/grapesjs-plugin-ckeditor)

  1. What is the expected behavior?
When a `textable` component, e.g. [#481 Merge field](https://github.com/artf/grapesjs/issues/481#issuecomment-481460506) is dragged into a text area (i.e. paragraph, heading), it renders accordingly (as it would without the custom RTE)

  1. What happens instead?
The component disappears

  1. If you're able to reproduce the bug indicate all the necessary steps
- Add the `grapesjs-ckeditor-plugin`
- Add a `textable` component to the canvas
- Drag into an area that the RTE has usage in

Attach screenshots (using KAP/LICEcap), screencasts or live demo
Here is the working component with the default RTE showing the functionality of the `textable` component:
![Alt](https://media.giphy.com/media/Wmihwaa3RcCjBq7ilF/giphy.gif)

Now here it is (disappearing) with the `grapesjs-ckeditor-plugin`:
![Alt](https://media.giphy.com/media/Ph72Z8OEGylCeEh9oh/giphy.gif)

Working JS-Fiddle with `grapesjs-plugin-ckeditor` and the `component` from [#481](https://github.com/artf/grapesjs/issues/481#issuecomment-481460506) :
https://jsfiddle.net/2egpdhtb/7/

**Comment by artf** [comment]
Hi @adriangroch thanks for the report but unfortunately it's not a bug, it's just not possible, currently, having components (`textable` in this case) inside a custom RTE. Each RTE has its own implementation and we can't ensure correct usage of external elements (in this case out components) inside them
