### ISSUE TITLE
[BUG] Default styling not being applied when default panels are instantiated

### ISSUE THREAD

**Issue by adriangroch** [artf/grapesjs#2275]
It seems that when the default `panels` is altered in the config, the basic styles are stripped from the panels. For example the font and scrollbars.

  1. Are you using the latest release (older versions are NOT supported)?
Yes

  1. Are you facing the bug with your local copy of GrapesJS or with the current demo?
Both

  1. What is the expected behavior?
When a `default` panel is added, that overflow scrolling and stylings consistent with the rest of the editor

  1. What happens instead?
Stylings are not applied to the panel

Live example: https://jsfiddle.net/bhujavo5/

It's weird because the default styling is applied to the canvas, but is rejected from the rest of the editor. Am I incorrectly initializing the editor?

**Comment by artf** [comment]
Sorry @adriangroch but I don't really understand what do you expect. I see the panel and its styles correctly applied. 
Are you talking about the scroll **outside** the editor?? That has nothing to do with the editor and its styles...

**Comment by adriangroch** [comment]
@artf, when you have enough components on the canvas and then select the layer manager, the styles are not applied as they are in the default example - the font is different and the scrollbar has changed. It's all still within the editor
![](https://i.imgur.com/GrS1b5k.png)

**Comment by artf** [comment]
That scrollbar is not from the editor but from the `body` and about the font, being a custom UI (when you use `appendTo`) the font is taken from the parent
