### ISSUE TITLE
[BUG] `change:style` listener is not triggered

### ISSUE THREAD

**Issue by iamriel** [artf/grapesjs#2276]
1. Are you using the latest release (older versions are NOT supported)?
      version 0.15.8
  1. What is the expected behavior?
       `change:style` listener should be triggered when changing/updating style
  1. What happens instead?
       nothing happens
  1. If you're able to reproduce the bug indicate all the necessary steps
      1. Drag the text block to the canvas
      1. Try changing the text's style and attributes
  1. Demo
     https://codepen.io/iamriel/pen/aboROrz

I have also tried `change:attributes:style` and even specific style like `change:style:padding-top` but still nothing happens.  I am not sure if I just missed something.  Thanks!

**Comment by iamriel** [comment]
Nevermind, I just disabled `avoidInlineStyle: 0` :)

**Comment by VanShane** [comment]
Hi, is there any way to listen to component style updates (in model or view) without using `avoidInlineStyle: 0`.
