### ISSUE TITLE
Unable to make work GrapesJS inside a bootstrap modal dialog

### ISSUE THREAD

**Issue by davellanedam** [artf/grapesjs#228]
Is there any reason why I can´t make GrapesJS work inside a bootstrap modal dialog? I try it on a single HTML file and works great, but then I put it inside a bootstrap modal dialog (in the modal-body) and drag and drop any element doesn't seem to work. Please help! Million thanks.

**Comment by artf** [comment]
@davellanedam are you able to post some code? I'd like to see how you append the editor inside the modal

**Comment by davellanedam** [comment]
I´m really sorry, I was testing this in Firefox, and we were discussing a bug on Firefox, That´s the problem, It works perfect inside a modal dialog on other browsers
