### ISSUE TITLE
[Question] How to show the traits manager button/panel

### ISSUE THREAD

**Issue by Davidvlv** [artf/grapesjs#2280]
Hi, I must be missing something basic, but how do I add the traits manager panel without adding a plugin?
The newsletter plugin has it added by default:
![image](https://user-images.githubusercontent.com/24515980/65213830-08b8a880-daeb-11e9-81c9-b73b5f440960.png)
But the editor with no plugins added does not have it:
![image](https://user-images.githubusercontent.com/24515980/65213881-356cc000-daeb-11e9-913b-93877fd23c6e.png)

**Comment by pouyamiralayi** [comment]
Hi there! i am not ever of your current page DOM structure. but i always do the customization this way:
```
<div id="style-manager">
           <div id="selectors-container"></div>
           <div id="traits-container"></div>
           <div id="style-manager-container"></div>
</div>
```
then in your editor instantiation config:
```
traitManager: {
     appendTo: '#traits-container',
},
```
same scenario goes for others like: style manager, layer manager...
cheers.
