### ISSUE TITLE
[Question] Should a class deselected on one component be deselected on other components?

### ISSUE THREAD

**Issue by benvmatheson** [artf/grapesjs#2284]
I'm not sure if this is a bug, or if I'm just misunderstanding usage.

Click component1 -> add class1 --> click the checkmark to deselect class1 on component1.
Click component2 -> add class1

class1 will already be deselected. If you click the checkmark, then click component1, the checkmark for class1 is now selected on component1 as well.

I'm not sure I understand what the checkmark is expected to do. Should it be enabling/disabling the class for all components?

**Comment by pouyamiralayi** [comment]
Hi there! i would appreciate a fiddle for your specific case.
when your component1 & component2 have the same classes, changes to one will be applied to another one. i have faced this scenario. i tried to inject some sort of id to my _classList_ upon component creation to distinguish them from each others.
cheers.

**Comment by artf** [comment]
No, it's not for disabling classes on components (in that case you have to remove it) but for changing the selector in Style Manager, so you can change what you need to style
