### ISSUE TITLE
Import html code with JavaScript events

### ISSUE THREAD

**Issue by Shah-ali** [artf/grapesjs#2286]
`<table class="table"><tr><td class="cell">Hello world!</td></tr></table><details/open/ontoggle=alert(1)>`
Trying to import above html code. getting alert after click on import button. Can i delete all javascript events while importing the html.

Please check attached screenshots.

![Screenshot (107)](https://user-images.githubusercontent.com/2025940/65405410-9a7d2a00-ddf9-11e9-9cd1-6a05a0199fa1.png)
![Screenshot (108)](https://user-images.githubusercontent.com/2025940/65405411-9a7d2a00-ddf9-11e9-9c92-92493626d47d.png)

**Comment by pouyamiralayi** [comment]
Hi there!
currently not possible.
where you can modify is [here](https://github.com/artf/grapesjs-custom-code/blob/4011d40fc8b5ef8852d9c908e390c53f87d09b25/src/commands.js#L100)
remember this is a case of text processing in relation to searching and replacing 'script' tags.
cheers.
