### ISSUE TITLE
[QUESTION] Why stylable and unstylable props not working?

### ISSUE THREAD

**Issue by ColdTuna** [artf/grapesjs#2288]
First of all, excellent project! I love it! Very complete all-around. I've been reading and re-reading the doc and it is a steep learning curve.

Anyway, I would like to serve a template to the user with restrictions in styling. I have been trying to use stylable and unstylable props like this:

`<h1 data-gjs-unstylable={["float"]}>Title</h1>`

But yet the float style shows in the style manager. Why?

Is there any other way to customize the style manager based on the component? For example, if `#site-logo` is selected, the style manager shows the asset uploader and a text field (fallback).

**Comment by pouyamiralayi** [comment]
Hi there! for your first problem: i think this property must be specified on your component type definition.
for your case it would be something like this:
```
 editor.DomComponents.addType('my-h1',{
            isComponent:(el) => {
              if(el.tagName === 'H1'){
                  return true
              }
            },
            model:{
                defaults:{
                    tagName:'h1',
                    unstylable:['float'],
                }
            }
        })
```
for your second problem, see if [this ](https://github.com/artf/grapesjs/issues/2287#issuecomment-534564632)can help you out.
cheers.

**Comment by ColdTuna** [comment]
I see! Thanks man! I will give it a go. :)

**Comment by artf** [comment]
@ColdTuna 
You wrote the attribute incorrectly, it should be
`<h1 data-gjs-unstylable="[\"float\"]">Title</h1>`
