### ISSUE TITLE
Groups in Asset Manager

### ISSUE THREAD

**Issue by danaketh** [artf/grapesjs#229]
Is there a way to organize assets in Asset Manager into groups (directories, categories or whatever you wish to call it) to make it easier to go through the files? And if not, would it be possible to implement that?

We're having hundreds of images and it's hard to navigate through them in a single long list.

**Comment by artf** [comment]
At the moment there are no groups in the Asset Manager, maybe in the future, I'll think to implement something more functional. In your case, what do you think about adding, for instance, a select which on change resets the collection by a selected value?

**Comment by danaketh** [comment]
I've sketched two possible ways of doing it: http://imgur.com/a/H6wMl (can't upload files to GitHub for some reason).

Implementation could be kept simple. Each asset would have a `group` property, which can be either `string` or `array` and carries the IDs of the groups it belongs to. Picking a group from combo box would then filter out everything that doesn't belong in selected group.

Implementing it as a file browser would be a bit trickier and since the modal itself is quite small, I'd probably stick with the combo box. It's simple and it does the job done.

Question is if the upload should respect the selected group and along the file also send a group ID.

**Comment by artf** [comment]
@danaketh thanks Dan, the combobox concept is exactly what I thought.
About the upload I think it's exactly as you described, the uploader might send also the group ID

**Comment by artf** [comment]
New [Assets](https://github.com/artf/grapesjs/wiki/Assets) wiki explains how to achieve it :)
