### ISSUE TITLE
[FeatureRequest] New trait type: component relationship

### ISSUE THREAD

**Issue by JCKodel** [artf/grapesjs#2290]
I have a custom component that will render the results of a remote query inside a component, so, I added a text trait on my block manager so the user can select the query selector for the destination component.

It would be nice if there were a trait called "componentRelationship" that renders a target button. When we drag'n'drop that target button over a component inside canvas, the trait value is populated with the component query selector.

**Comment by pouyamiralayi** [comment]
hi there! 

> trait value is populated with the component query selector.

do you mean binding the result of an api call to a property and show them inside our trait?

**Comment by artf** [comment]
Thanks @JCKodel for the suggestion, I like it but I also think it might a bit overwhelmed for being placed in the core library. Probable in this case it would be best to [define a custom Trait](https://grapesjs.com/docs/modules/Traits.html#define-new-trait-type)
