### ISSUE TITLE
Move components with same class?

### ISSUE THREAD

**Issue by rushmabaj33** [artf/grapesjs#2299]
Hello!

Is there any way to change position of all components with the same class? 

For example, I have two divs with class name 'title' and 'location'. And there are several other components with the same class names:
![snapshot](https://user-images.githubusercontent.com/11989846/65830472-1a027180-e2b0-11e9-8d7d-da7d498f60db.png)

When I drag the component with class name 'title' and drop it below 'location', all the other components should be updated likewise. How can I do so?

**Comment by artf** [comment]
No, classes are made for sharing styles and not the structure
