### ISSUE TITLE
Bug in adding a new css rule with selectors

### ISSUE THREAD

**Issue by fgiannar** [artf/grapesjs#23]
In css_composer/main.js line 173 (add):

`rule.get('selectors').add(selectors);`

returns selectors with empty ids..

instead

`
selectors.each(function(selector){
   rule.get('selectors').add(selector);
});
`

seems to work.

**Comment by artf** [comment]
Hi @fgiannar 
sorry but I can't reproduce the bug
Anyway, the return of `rule.get('selectors').add(selectors)` should be the "same" `selectors` array

```js
var sm = editor.SelectorManager;
var sel1 = sm.add('myClass1');
var sel2 = sm.add('myClass2');
var selectors = [sel1, sel2]; 

var cssComposer = editor.CssComposer;
var rule = cssComposer.add(selectors, 'hover');
//...
// And inside the add()... when you are at 173 line:
var addedSelectors = rule.get('selectors').add(selectors); 
/*
'addedSelectors' and 'selectors' are 2 different arrays but contain
the same instances of sel1 and sel2
*/
```

**Comment by fgiannar** [comment]
No I'm afraid not. This occurred from a custom script of mine, where I had:
`cssComposer.add(target.get('selectors'), '', '480px');`  where target is an instance of a CssRule with maxWidth not set.

If I replaced the line 173, as explained in my first comment above, the selector models had ids else they had the `name` attribute set but empty id which lead me to think it's a general bug.

Probably my bad, I am closing it since it's not reproducible on your end.
Thanks a lot for your prompt response.

**Comment by artf** [comment]
Hi @fgiannar I think I get it, `target.get('selectors')` returns a [Backbone Collection](http://backbonejs.org/#Collection) but [cssComposer.add](https://github.com/artf/grapesjs/wiki/API-Css-Composer#add) accepts Array as the first argument, so you should fix with this:
`cssComposer.add(target.get('selectors').models, '', '480px');`

**Comment by fgiannar** [comment]
Just an update, in case anyone else faces the same issue:
The mistake was passing the selectors collection instead of array of models, so replacing:
`cssComposer.add(target.get('selectors'), '', '480px');`
with
`cssComposer.add(target.get('selectors').models, '', '480px');`
fixed the issue.

Again thanks for your time.
