### ISSUE TITLE
default component settings not updated in html if not changed.

### ISSUE THREAD

**Issue by aryeharmon** [artf/grapesjs#230]

**Comment by artf** [comment]
thanks @aryeharmon can you provide an example of your issue?

**Comment by aryeharmon** [comment]
If for example i have a component with traits:
```
[
{
        name: 'ng-repeat',
        value: 'e in data track by $index',
        default: 'e in data track by $index',
      }
]
```
if i add a block with that component, when i add it to the page. the html element will not have my default settings. only if i change the value in the settings will the element update

**Comment by artf** [comment]
thanks @aryeharmon got it and confirmed

**Comment by aryeharmon** [comment]
I tried changing the the value on drop, however this only worked when the component was selected. 
Can you give me some hint about where and when i should implement this?

**Comment by artf** [comment]
@aryeharmon you might want this
```js
editor.on('block:drag:stop', function(model){
 //...
});
```

**Comment by aryeharmon** [comment]
@artf it seems like the html only gets updated on a component that is selected by the builder. how would i would automatically select a component that is dropped?

**Comment by artf** [comment]
thanks @aryeharmon just realized I haven't provided an easy API method to select a component, will add it in the next release
