### ISSUE TITLE
Updating toHTML of a new custom component

### ISSUE THREAD

**Issue by megarg** [artf/grapesjs#2303]
I would like to change how the toHTML output. I would like to modify the existing html output.

I tried the "toHTML" property of component
- it allows to return a new html element
- but it does not allow to get existing html and then update it and return it

I tried calling toHTML inside toHTML to get access to original component html but as expected it went in an infinite loop.

Is there a way to get access to existing toHTML so that I can modify it and then return as new "toHTML:. Editor or export will use the new output.

**Comment by pouyamiralayi** [comment]
Hi! did you try using ``component.view.el`` inside your ``toHTML``? it will give you access to the current DOM.
cheers!

**Comment by megarg** [comment]
I tried this but this does not solve my problem. i have scripts as part of model which are not getting added in `this.view.el`. Is there a way to get original html from inside toHTML so that I can update it a bit and then return.

**Comment by megarg** [comment]
Basically, I am trying to add a global variable above (basically ass a global variable as first line of script)
`var items = document.querySelectorAll('#ijck');`

I have a unique use case which requires me to update how Grapesjs is adding scripts to final HTML code. I was thinking if I can get access to html output, I can modify it and return it.

**Comment by pouyamiralayi** [comment]
> Is there a way to get original html from inside toHTML

what i proposed has been tested and is working:
```
el.toHTML = function(){
   console.log(el.view.el)
}
```
this will log the original HTML in the console as you desired.

>  I am trying to add a global variable above

i am not aware of your current architecture, but [grape-expose](https://github.com/alvimm/grapesjs-expose) might be helpful for you.

if you want any further help for your specific case, i would appreciate a fiddle.
cheers!

**Comment by megarg** [comment]
i solved this by doing below
`
toHTML: function () {
        let el = `<script>  console.log("add script here") </script>`;
        el = defaultType.model.prototype.toHTML.apply(this) + el;
        return el;
      },
`

**Comment by scottccoates** [comment]
To get `defaultType` run this: `var defaultType = editor.DomComponents.getType('default');`

And this works too:

```javascript
var prototype = Object.getPrototypeOf(this);
var el = prototype.__proto__.toHTML.call(this);
return el;
```
