### ISSUE TITLE
How get the components inside canvas? I want to get the same you can see in https://grapesjs.com/demo.html inside the localStorage in the item gjs-components

### ISSUE THREAD

**Issue by alu0100824810** [artf/grapesjs#2304]

**Comment by pouyamiralayi** [comment]
[check this](https://grapesjs.com/docs/api/editor.html#getcomponents)

**Comment by alu0100824810** [comment]
Yes, but getComponents does not return you the same as in the demo. The function getComponents return as shown in the following picture:

<img width="500" alt="Captura de pantalla 2019-10-02 a las 19 47 22" src="https://user-images.githubusercontent.com/22544126/66072876-d75dc500-e54d-11e9-9256-2e03ecc98772.png">

And I only want as shown in the demo:
<img width="500" alt="Captura de pantalla 2019-10-02 a las 19 55 17" src="https://user-images.githubusercontent.com/22544126/66073251-a6ca5b00-e54e-11e9-839f-13290cdf3689.png">

**Comment by pouyamiralayi** [comment]
> And I only want as shown in the demo:

using the `editor.getComponents` you have access to an array of components, after that you can simply do the following based on your use case:
```
const comps = editor.getComponents()
        comps.forEach(comp => {
            console.log(comp.attributes.type)
            console.log(comp.attributes.tagName)
            console.log(comp.attributes.classes)
            console.log(comp.attributes.components)
            console.log(comp.attributes.content)
        })
```
please do not be _misdirected by the log output of the provided pictures_. notice that grapesjs is leveraging from **backbone js** and that is the _reason for the odd output you are seeing_.
cheers!

**Comment by artf** [comment]
@alu0100824810 use this `JSON.stringify(editor.getComponents())`
