### ISSUE TITLE
Wrap and UnWrap function is not working in Grapesjs selected element

### ISSUE THREAD

**Issue by rajasubburaj** [artf/grapesjs#2305]
if(data.component.get('tagName') === 'img') { 

							const selectedComponent = editor.getSelected();
							const href = this.getHref();
							const childHtml =`<a href="${href}"></a>`
							$(`img#${selectedComponent.ccid}`).wrap(childHtml);

							data.component.view.render();

							editor.Modal.close();
						}

**Comment by pouyamiralayi** [comment]
[autoWrap](https://github.com/artf/grapesjs/issues/2179)
