### ISSUE TITLE
How to remove "Custom code" and "Tooltip" block?

### ISSUE THREAD

**Issue by dukie66** [artf/grapesjs#2306]
I using grapejs demo websites script so that I can learn and build. 
is there any way I can remove all blocks and add my own blocks.

**Comment by pouyamiralayi** [comment]
Hi there! for **removing blocks**:
```
editor.BlockManager.getAll().forEach(b => {
    editor.BlockManager.remove(b.cid) })
```
for adding your own blocks see [this](https://grapesjs.com/docs/modules/Blocks.html#custom-render).
cheers!
