### ISSUE TITLE
API call in GRAPES JS

### ISSUE THREAD

**Issue by Amitkumar85533** [artf/grapesjs#2307]
Hi Everyone,

I created a calendar plugin using @fullcalendar in GrapesJS
Now I want to call a GraphQL API to fetch the events in the calendar. 
How to perform this in GrapesJS?

Thanks in Advance !!!!!

**Comment by pouyamiralayi** [comment]
> How to perform this in GrapesJS?

you can make your api calls inside [script](https://grapesjs.com/docs/modules/Components-js.html#components-js).

what ever _js library_ you are using for making the calls it would be okay.
cheers!
