### ISSUE TITLE
[QUESTION]-Is there a way to add alphabetical ordered list

### ISSUE THREAD

**Issue by shubh9415** [artf/grapesjs#2309]
Hey, @artf thanks for creating this awesome library. its really helpful.
I am using it in angular and I have used order list with numbers but it would be really helpful if there is a way to add an alphabetical ordered list or in roman numbers
I was trying this 
```
this._editor.RichTextEditor.add('orderedList',
          {
            icon: 'a',
            attributes: { title: 'Ordered List',type:'a' },
            result: rte => rte.exec('insertOrderedList'),

          });
```
but didn't work. please help

**Comment by artf** [comment]
Hi @shubh9415 the default RTE relies on [`execCommand API`](https://developer.mozilla.org/it/docs/Web/API/Document/execCommand) so the only available options are `insertOrderedList` and `insertUnorderedList`.
