### ISSUE TITLE
[QUESTION] How can I specify position for dragging elements ?

### ISSUE THREAD

**Issue by CookiePHP** [artf/grapesjs#2310]
Hi iam doing a project with this library and i want to specify position for dragging components in it
for example i have a div with id="drag-here" i want all components to be dragged in this div only

i hope you can understand me , thank you all

**Comment by pouyamiralayi** [comment]
> i have a div with id="drag-here" i want all components to be dragged in this div only

if by this you mean you want all components to be draggable only in your target component, you can use ``droppable`` [property](https://grapesjs.com/docs/api/component.html#properties).
by specifying droppable on your components like this:
```
droppable: 'target, target *'
```
cheers!

**Comment by CookiePHP** [comment]
> by specifying draggable on your components like this:

thank you for fast replay , but i don't have components iam using blocks

**Comment by pouyamiralayi** [comment]
> i don't have components iam using blocks

according to this: 

> i have a div with id="drag-here"

i assume your block is something like this:
```
content: '<div id="drag-here"></div>'
```
the approach for your container block would be:
```
editor.BlockManager.add('drag-here',{
    lablel:'Drag Here',
    content:'<div id="drag-here" data-gjs-droppable="true" style="width:100px;height:100px; background:red;"></div>'
})
```
and for target blocks:
```
editor.BlockManager.add('drop',{
    lablel:'Drop',
    content:'<div data-gjs-draggable="div#drag-here" style="width:50px;height:50px; background:blue;"></div>'
})
```
cheers!
