### ISSUE TITLE
[QUESTION] Set href for link component

### ISSUE THREAD

**Issue by gabrielbitencourt** [artf/grapesjs#2311]
Hello guys.

I'm trying to modify the native link component, so far I have a modal that opens on the dblclick event and the user may choose between some pre defined links. The problem is, when I have the chosen link I'm not able to set it to the component.

It works fine when I type the link in the Trait Manager.

Here's the code I tried:

		domc.addType('link', {
			view: {
				events: {
					dblclick: 'linkModalPicker',
				},
				async linkModalPicker(ev: MouseEvent) {
					ev.preventDefault();
					const ref = modal.open(LinkModalComponent, {
						width: '70%',
						height: '70%'
					});

					const link = await ref.afterClosed().pipe(first()).toPromise();
					if (link) {
						this.model.set('href', link.url);
					}
				}
			}
		});

I did something similar, but for the images component, and it worked with this code:

		domc.addType('image', {
			view: {
				events: {
					dblclick: 'imagesModalPicker',
				},
				async imagesModalPicker(ev: MouseEvent) {
					ev.preventDefault();
					const ref = modal.open(ImagesModalComponent, {
						width: '70%',
						height: '70%'
					});

					const img: Item = await ref.afterClosed().pipe(first()).toPromise();
					if (img) {
						this.model.set('src', img.url);
					}
				}
			},
		});

But for some reason it's not setting the href in the anchor tag.

Thanks!

**Comment by artf** [comment]
@gabrielbitencourt Link Component doesn't have an href property, so add it directly to attributes
```js
if (link) {
	this.model.addAttributes({ href: link.url });
}
```

**Comment by gabrielbitencourt** [comment]
thank you for the response @artf 

I tried that but it didn't work either, I could see (in the trait manager) that the href had been set using `model.addAttributes({ href: link.url })` but it did not persist when I deselected and selected the component again, neither in the resulting `editor.getHtml()` the anchor tag had href empty.

I think this could be related to some bugs I've read here like #1290

Thanks

**Comment by artf** [comment]
> but it did not persist when I deselected and selected the component again

maybe because you're still reading from `this.model.get('href')`... 
btw can't help you more than this without a reproducible demo

**Comment by gabrielbitencourt** [comment]
Actually I wasn't reading it, I just expected that the href would be set in the final result of the editor, which wasn't the case. But I found a workaround using the rich text editor, replacing the native link button with a custom implementation, setting the href directly in the html.

Thank you for the help!

**Comment by artf** [comment]
Ok... but keep in mind that, if after doing this `model.addAttributes({ href: link.url })` you don't see any change in HTML code (eg. `editor.getHtml()`) it means you're doing something "wrong"

**Comment by simpy-surbhi** [comment]
I want to add list of address
