### ISSUE TITLE
[QUESTION] - More control over panel buttons, dynamic panel buttons

### ISSUE THREAD

**Issue by DamodarSojka** [artf/grapesjs#2312]
Hi,

I am trying to implement several more dynamic buttons for the panel, for example a save button that depending on some flag will show an animated loading spinner, save icon or "Saved" text. In order to achieve that I need to be able to dynamically set the content, potentially size and also use not only icons but also text.

I am wondering if there is a better way than either removing the button and adding it back (I guess the order of the buttons would change and I would actually need to be adding and removing a whole set of them to keep the ordering same) or using DOM manipulation to change it's content.

Thank you in advance

**Comment by artf** [comment]
Well you can change the attribute and the content in this way
```js
const prevBtn = editor.Panels.getButton('options', 'preview');
prevBtn.set({ 
	attributes: {title: 'New title'}, 
	label: 'New content' 
})
```
for anything else more specific you can go with direct DOM manipulation

**Comment by DamodarSojka** [comment]
Thank you for a very quick response, didn't know about the label property as it doesn't seem to be mentioned in the docs.
