### ISSUE TITLE
[BUG] grapesjs does not handle correctly outlook specific HTML

### ISSUE THREAD

**Issue by alimajedcme** [artf/grapesjs#2314]
Hello all,

I have a template that includes outlook specific HTML as shown below:
`<!--[if (gte mso 9)|(IE)]><table width="100%" border="0" cellpadding="0" cellspacing="0"><![endif]-->`

When I import this HTML, and try to add a block above or below this specific location in the DOM, the green line showing where the component will be dropped in the canvas won't be displayed correctly, and will become much smaller than expected, as show below
<img width="1232" alt="Screen Shot 2019-10-07 at 6 48 18 PM" src="https://user-images.githubusercontent.com/51313079/66327476-9130a900-e933-11e9-901e-eec3ddebef46.png">

Any idea why this is happening? I think it is because the comment tagname does not have a width but is there any workaround for this?

Thank you all.

**Comment by artf** [comment]
Probably you would need to create a [custom component](https://grapesjs.com/docs/modules/Components.html) to handle such a case
