### ISSUE TITLE
Customizing the assets-manager view

### ISSUE THREAD

**Issue by kickbk** [artf/grapesjs#2316]
I would like to create a custom assets-manager modal to open in bootstrap modal. I'd like to keep the original assets manager functionality (like drop image zone, input to fetch image from remove, and I'd like to use datatable for the images/assets). In addition, I would like to integrate with Pixabay API so images can be easily entered into the editor. This can be in a separate tab. See mockup.
Would you please offer some general guideline on how I can create a bootstrap modal in my view and load the assets manager inside it? 
![mockupgrapes2](https://user-images.githubusercontent.com/31323376/66350823-1d7da480-e911-11e9-80e8-179a0f7335cc.jpg)

**Comment by khoa-justuno** [comment]
You can do this with a custom modal by overwriting the default image asset manager.

`editor.Commands.add("open-assets", {
        run(editor, sender, opts) {
          const assettarget = opts.target;
          // code to open your own modal goes here.
        }
      });
`

When you want to set an image use this.
`
const assettarget = opts.target;
assetTarget.set("src", image.url);
`

**Comment by artf** [comment]
I'd suggest the same solution proposed by @khoa-justuno 
If you need a new modal it will be easier to create the Asset Manager UI from scratch, reusing the DOM elements created by GrapesJS, in this case, would be just a pain to maintain

**Comment by luishdez** [comment]
Hi @artf I'm posting this here because I'm not pretty sure that this is a bug. 

I'm trying to implement my custom Asset Manager, everything ok so fat. But when I drop directly the src it's not replace or at least it doesn't take effect. But it works it then I click en the same img in the canvas. In that case works every time.

There is something that changes after dropping the block image.

This works 

```js
  run(editor, sender, opts) => {
    setTimeout(() => {
      opts.target.set('src', 'https://via.placeholder.com/150');
    },  1);
  }
```
But this doesn't work.
```js
  run(editor, sender, opts) => {
    setTimeout(() => {
      opts.target.set('src', 'https://via.placeholder.com/150');
    }, 4000);
}
```

**Comment by PriyankaPrabhu** [comment]
@kickbk 
did you achieve the custom asset manager ? If yes please share the code

**Comment by arjavsethi** [comment]
@throne1986    did you manage to create a custom asset manager?

**Comment by Hunganh3012** [comment]
Hi @khoa-justuno . a Khoa có thể hổ trợ e được không ạ E đang có custom phần select-images. để nhận hình ảnh. nhwung trong code-viewer thì nó không hiện url của ảnh, còn ở trên devtool thì có ạ
link https://github.com/GrapesJS/grapesjs/discussions/5011

Em cảm ơn a Khoa ạ

**Comment by Hunganh3012** [comment]
@khoa-justuno  . Anh Khoa ơi a giúp e vấn đề này với #5055 . Em cảm ơn ạ
