### ISSUE TITLE
Image is not centering at canvas

### ISSUE THREAD

**Issue by rgcarrasqueira** [artf/grapesjs#232]
Hi Art!

Another issue that I've got about canvas. At this times, I'm attaching a screencast where I've got an image from AssetManager and place it into a table that has 100% width with left and right margin set to 0px. 

I've tried to apply margin auto to image on trying to place it at the center, but did not has any effect on the image. Tried also to apply a center text button, but nothing happen. After all I've opened the import code and I've placed a

```
<div style="text-align:center"><img src="blabla"></div>
```

And the image was set correctly at the canvas. I think that set the margin or click at aligment could help to place the image at the middle as I wanted.

![kapture 2017-08-15 at 17 36 32](https://user-images.githubusercontent.com/97540/29335484-34c6b3aa-81e1-11e7-8e6d-f96aaecf7d42.gif)

I believe that has an another alternative like adding an internal table with column, but unfortunately I have some dummy users that cannot deal on trying to add a table and after that insert image. For them is more simple to add image and center image, just clicking in a button.

Thanks for your help.

**Comment by artf** [comment]
Hi @rgcarrasqueira, first of all, the `<img>` is an inline element, so if you want to center it with `margin: 0 auto` trick you have to apply first something like this `display: block`. 
Anyway you've already posted the solution:
```html
<div style="text-align:center"><img src="blabla"></div>
```
just apply `text-align:center` to the parent

**Comment by anand-gopinath** [comment]
@artf - Can we do the same functionality as a **custom style** property which has 

> left, right and center

 options and once the user clicks on the corresponding alignment, the **custom style** property will apply 

> "text-align:center"

 to its parent. Is this possible?
