### ISSUE TITLE
[HELP] Missing fonts after compile with Webpack

### ISSUE THREAD

**Issue by eduardonunesp** [artf/grapesjs#2320]
The project is using webpack to compile the project in order to distribute as bundle, it's a kind of plugin using GrapesJS as editor, everything works fine except the fonts loaded by GrapesJS are missing, when running with `webpack-dev-server` everything looks fine, but when building with webpack and try to run on a simple server (different folder using dist files) it looks like:

![image](https://user-images.githubusercontent.com/582516/66448498-185f4900-ea28-11e9-81a1-8ad11be0596e.png)

And now with `webpack-dev-server` on project directory

![image](https://user-images.githubusercontent.com/582516/66448795-23ff3f80-ea29-11e9-961d-76105af84000.png)

```js
const webpack = require('webpack')
const HtmlWebpackPlugin = require('html-webpack-plugin')

const environment = process.env.NODE_ENV || 'development'

module.exports = {
  entry: ['regenerator-runtime/runtime', './src/index'],
  devtool: 'source-map',
  output: {
    path: __dirname + '/dist',
    filename: 'plugin-editor.js',
    library: ['PluginEditor'],
    libraryTarget: 'umd'
  },
  devServer: {
    historyApiFallback: true
  },
  module: {
    rules: [
      {
        test: /\.js$/,
        exclude: /node_modules/,
        loader: 'babel-loader'
      },
      {
        test: /\.scss$/,
        use: [
          'style-loader', // creates style nodes from JS strings
          'css-loader', // translates CSS into CommonJS
          'sass-loader' // compiles Sass to CSS, using Node Sass by default
        ]
      },
      {
        test: /\.css$/,
        use: ['style-loader', 'css-loader']
      },
      {
        test: /\.(png|jpe?g|gif|svg|eot|ttf|woff|woff2)$/,
        loader: 'url-loader',
        options: {
          limit: 10000
        }
      }
    ]
  },
  plugins: [
    new webpack.DefinePlugin({
      'process.env.NODE_ENV': JSON.stringify(environment)
    }),
    new HtmlWebpackPlugin({
      filename: 'index.html',
      template: 'index.html'
    })
  ]
}
```

Also worth to mention that I have copied the `src/styles` folder from the project `GrapesJS` with the intuit of better customize colors and details. And all fonts generated on `/dist` folder are loaded on `index.html` when loaded on another folder. The project is loaded on another folder using command `python -m SimpleHTTPServer 3000`

**Comment by pouyamiralayi** [comment]
did you try using ``file-loader `` instead of ``url-loader`` for ``ttf`` or other font types?

**Comment by eduardonunesp** [comment]
Same `file-loader` or `url-loader` the issue only happens when building the bundle for distribution and run on `nxing` for example. The issue seems to be related with `font-awesome` because those items are from there.

**Comment by eduardonunesp** [comment]
Everywhere on my project where use `font-awesome` is broken, not sure what is happening right now, unfortunately, I don't have much time to dig deeper on these issues

**Comment by pouyamiralayi** [comment]
using [outputPath](https://webpack.js.org/loaders/file-loader/#outputpath) option, you specify the output folder where webpack will emit files. and based on you saying:

> running with webpack-dev-server everything looks 
 project is loaded on another folder

it seems to be an output path problem.
sorry if this was not helpful.

**Comment by eduardonunesp** [comment]
Great, thanks @pouyamiralayi I'll double check the outputPath this night

**Comment by artf** [comment]
Definitely an issue with the output path. 
I close this as it's not an issue with the core itself

**Comment by eduardonunesp** [comment]
Hey guys thanks for the support, just to report the final status of the issue, it's solved, and wasn't the `outputPath`, but the `utf-8` tag on my `index.html` file, ok maybe because of the mix of Windows + WSL + Chrome? not sure.


```html
 <html lang="en">
   <head>
       <meta charset="utf-8"/>                                                                                                                                                                                  
       <title>My Editor</title>
   </head>
   <style type="css">
```

**Comment by artf** [comment]
Good to know, thanks @eduardonunesp
