### ISSUE TITLE
Drag and drop re-ordering of components?

### ISSUE THREAD

**Issue by glassdimly** [artf/grapesjs#2321]
I've got a several `bolt-interactive-step`s within `bolt-interactive-pathway` and I wish to order them, but grapesJS dragger only allows me to drop it inside `bolt-interactive-pathway` to be appended to the end: no ordering.

![ezgif-4-a2ad6c15e82c](https://user-images.githubusercontent.com/1361104/66575077-f0acd580-eb3a-11e9-9bfa-e54bf13dee20.gif)

This is compounded by the fact that this actually works about 10% of the time.

**Comment by artf** [comment]
Is it only within Layers or also on canvas? Can you create a reproducible demo, please?
