### ISSUE TITLE
What is protectedCss option ? How to use it?

### ISSUE THREAD

**Issue by dukie66** [artf/grapesjs#2322]
I want to give some default style for some elements. Is there any option for doing that?

**Comment by jcarizza** [comment]
Hello @dukie66 one way to add default styles is adding a stylesheet in the initilalization of GrapeJS. This will load inside the canvas the stylesheet

```

    const editor = grapesjs.init({
        container : '#gjs',
        canvas: {
            styles: [
                "http://path.to/style.css
            ]
        }
    }
```

**Comment by dukie66** [comment]
@jcarizza Thanks for commenting. If you see when you export canvas there are always some default styles for "body" and "*". Like that, I want to give my all "img" element width of 100%. Putting an external css file in the canvas option is not working for me. Maybe I'm doing something wrong.
`canvas:{
    styles:[
      './css/canvas.css'
    ]    
  },`

**Comment by jcarizza** [comment]
Its neccessary to write the full URL to load the CSS stylesheet.
```
canvas:{ styles:[ http://yourdomaon.com/css/canvas.css' ] },
```
or 
```
canvas:{ styles:[ 'http://localhost:8000/css/canvas.css' ] },
```

Here is an example using protectedCss.

https://codepen.io/jcarizza/pen/rNNeQvG
