### ISSUE TITLE
Not able to select / resize the tr (row) wise of table

### ISSUE THREAD

**Issue by ramusesan** [artf/grapesjs#2324]
am trying to select row **(tr)** wise ans resize but i couldn't  
am able to select **td** wise only

live demo is here 
**https://drive.google.com/file/d/1zzsGrWkrDAPozDncaHTwwGggeE2ZzJYP/view**

**Comment by artf** [comment]
Visually the cell is on top of the row so you can't select it, you have to use the parent selection button (arrow up icon on the toolbar) to select the row.
