### ISSUE TITLE
sector not found

### ISSUE THREAD

**Issue by Uysim** [artf/grapesjs#2326]
I try to add properties
```jsx
  styleManager.addProperty('decorations',{
    name: 'Border Top width',
    property: 'border-top-width',
    type: 'integer'
  })
```
I got warning `'decorations' sector not found`
I try to debug with `editor.getSector('decorations')` and I got undefined 
When I console `editor.getSector('decorations')` it has the decorations sector there.

**Comment by artf** [comment]
Probably you're placing your code before the `decorations` sector is loaded. Check the order of your plugins
