### ISSUE TITLE
CSS rules overwritten by cssComposer.setRule(...)

### ISSUE THREAD

**Issue by ColdTuna** [artf/grapesjs#2331]
My site has a custom sidebar to set site-wide colors, font-families, font-sizes and so on. When I change one style (i.e. text color), I lose any other styles that were previously set by my custom sidebar (i.e, font-family, font-size).

To change these styles I am doing:

     cssComposer.setRule("p", { "font-family": value });
     cssComposer.setRule("h1", { "font-size": value });
     cssComposer.setRule("a", { "color": value });

Is this the correct way going about changing site-wide styles? Why is it getting overwritten?

**Comment by artf** [comment]
> When I change one style (i.e. text color), I lose any other styles that were previously set by my custom sidebar (i.e, font-family, font-size).

It's not clear to me what do you change and where the style is overwritten... maybe you can provide a live demo of your case?!

Doing this `cssComposer.setRule("p", { "font-family": value })` is correct but it doesn't change the way CSS work, if you have another rule with a strongest selector, that will gonna win
