### ISSUE TITLE
[BUG] Can not edit label in Firefox browser

### ISSUE THREAD

**Issue by kondziu95** [artf/grapesjs#2332]
Hi,

I can not edit label in Firefox browser (v. 69.0.3).
The issue occurs when I double click the component to edit it. RTE shows toolbar but changing text or attributes is unable. The web console does not show any errors.
When the text is selected and I am trying to for example bold the text then in web console there is an error:

```
NS_ERROR_FAILURE: 4 grapes.min.js:12
    value https://grapesjs.com/js/grapes.min.js?v0.15.8:12
    result https://grapesjs.com/js/grapes.min.js?v0.15.8:12
    <anonimowa> https://grapesjs.com/js/grapes.min.js?v0.15.8:12
```

After triple click text can be edited but only whole text. Can not select only part of the text or move cursor left or right to change only part of the text.

**Double click issue**
Steps to reproduce (actual behavior):
1. Put label block to the canvas,
2. Double click the label to edit it,
3. Cannot edit text or text attributes (bold, etc.)

Expected behavior:
1. Put label block to the canvas,
2. Double click the label to edit it,
3. Can edit text and text attributes (bold, etc.)

![issue - dbl](https://user-images.githubusercontent.com/25708371/66899871-f94e5180-effb-11e9-92aa-8fc1d3bdb73a.gif)

**Triple click issue**
Steps to reproduce (actual behavior):
1. Put label block to the canvas,
2. Triple click the label to edit it,
3. Can edit text but can not edit text attributes (bold, etc.) and move cursor left or right using arrows keys

Expected behavior:
1. Put label block to the canvas,
2. Triple click the label to edit it,
3. Can edit text, text attributes (bold, etc.) and move cursor left or right using arrows keys

![issue - triple](https://user-images.githubusercontent.com/25708371/66899890-00755f80-effc-11e9-9d31-2c6bb2c994c7.gif)

**Comment by artf** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=853519

Probably the easiest solution would be to force the View to use `span` tag instead of `label`

**Comment by schmelik** [comment]
This was an interesting `fix` but it comes with issues...

spans != labels

when applying padding to the labels such as bootstrap labels the padding will not be applied to a span
not unless `display: inline-block;` is also applied to the span
