### ISSUE TITLE
[BUG / QUESTION] Deleting default styles does not work

### ISSUE THREAD

**Issue by navewi** [artf/grapesjs#2337]
Hello, 
i'm trying to delete some of the default styles of the blocks. I wrote everything I changed in a plugin.

I used this function to update for example the Text Components style-defaults:
`editor.DomComponents.addType(.....)`
seen here: https://grapesjs.com/docs/modules/Components.html#update-component-type

Am I getting this wrong? 

Also I can't figure out where the style defaults are written, when I change the style-defaults in Text.js for testing, nothing changes in the editor. 

Oh and i'm using the mjml-plugin, maybe this issue is wrong here sorry.

Edit: Okay i figured out "style" works but not "style-default":
![image](https://user-images.githubusercontent.com/38751963/66996966-e7d77900-f0d1-11e9-9a92-4f475817298f.png)

Is this a bug?

**Comment by pouyamiralayi** [comment]
Hi there! have you tried using [setStyle](https://github.com/artf/grapesjs/blob/7d1dff957d62bbbaefd75b042e4092ae6f28e3d1/src/dom_components/model/Component.js#L403) ?
cheers.

**Comment by artf** [comment]
I'd expect something like this to work (update `style-default`)

```js
editor.DomComponents.addType('mj-text', {
	model: {
		defaults: {
			'style-default': {
				// your new styles...
			}
		}
	}
})
```

Be sure to load your plugin after the mjml one

**Comment by navewi** [comment]
Hello @artf, thanks for your reply. this is the exact same code, that i tried out. This one works if I use "style" instead of "style-default".

**Comment by artf** [comment]
`style` "works" because [`mj-text`](https://github.com/artf/grapesjs-mjml/blob/master/src/components/Text.js) doesn't have any `style` property, as I said before you're probably facing an order issue (you're component is placed before the plugin is loaded). Can we see your full code?

**Comment by navewi** [comment]
I am loading my plugin after all other plugins:
![image](https://user-images.githubusercontent.com/38751963/67841198-d0e44e00-faf7-11e9-9172-ddf7feea3585.png)

And this is how i change the style, default style does not work on any component, not only mj-text.
![image](https://user-images.githubusercontent.com/38751963/67841251-efe2e000-faf7-11e9-846d-d7f15e6edaa1.png)

Do you need any other code?
