### ISSUE TITLE
[Feature request] Localisable component text based on page language

### ISSUE THREAD

**Issue by senchden** [artf/grapesjs#2342]
It would be great to create pages that would share the component layout, but allow to edit text for each component based on language value set externally (one page per language). Not sharing layout per language is not optimal since if a user edits not only the component text, but also the page layout, all pages in other languages must be edited to use the new layout, which is not easily maintainable. Personally, I envision this as component inner text not being propagated to HTML inner text on export, but rather as pairs of component id (or text key) and text values.

**Comment by artf** [comment]
I18n module is already in the roadmap

**Comment by senchden** [comment]
Does this module have any tentative date of implementation?

**Comment by varadero** [comment]
Looking at the branch named `i18n` and i18n module code here: `https://github.com/artf/grapesjs/tree/i18n/src/i18n` it looks like this module is not for localizing page content that the users are creating but just the GapesJS interface itself, is that right @artf ? We also would like to have module that will enable the users to provide different texts of the pages they create for different languages. If the i18n module on the roadmap is not about supporting different page languages, do you have an idea how can we implement it in a "GrapesJS" way ?

**Comment by artf** [comment]
@varadero 
> it looks like this module is not for localizing page content that the users are creating but just the GapesJS interface itself, is that right

correct

> We also would like to have module that will enable the users to provide different texts of the pages they create for different languages

Well, the content has nothing to do with the core library, this is something you have to implement by yourself
