### ISSUE TITLE
Add html5 video

### ISSUE THREAD

**Issue by jeff-panart** [artf/grapesjs#2343]
Hi,

How should one add a html5 video to grapesjs?

I uploaded both a webm and mp4 file, added a video component on my grapesjs page and under Settings I chose HTML5 Source. Then I added the complete path to the video file.
Only thing I get back is a black element, without any video. For test purposes I change the complete path to just /video/file.mp4 en .../file.webm, but no luck so far.

If I change to a youtube video, all seems to work fine.

Console doesn't give any errors back either, so I'm in a bit of a tiffy...

Any tips would be appreciated.

**Comment by artf** [comment]
Those video files should be served from the server (local or remote one), the browser shouldn't be able to read your local files for security reason
