### ISSUE TITLE
When a component  is clicked is there a hook to know when the traits have rendered.

### ISSUE THREAD

**Issue by CoCreator-Frank** [artf/grapesjs#2346]
Hey Grapes Community, 
When a component  is clicked from within canvas is there a hook or event to know when the traits have rendered in view container for the selected component?

**Comment by pouyamiralayi** [comment]
Hi there! 

> When a component is clicked

``component:selected`` is the event you are looking for. more on this [here](https://grapesjs.com/docs/api/editor.html#components)

> to know when the traits have rendered in view container

based on the nature of the the suggested event, you will receive the model of the selected component as an argument, this way you can check for the availability of any trait on the model:
```
ditor.on('component:selected',(model => {
    console.log(model.get('traits'))
})
)
```

**Comment by CoCreator-Frank** [comment]
Perfect, Thank you!
