### ISSUE TITLE
Remove badge for all the components

### ISSUE THREAD

**Issue by suchiitsme** [artf/grapesjs#2347]
I have to remove badgable to all the components. I have added this on editor.init
domComponents: {
			wrapper: {
			  badgable: false
			},
		  },
Still not working. Please help

**Comment by suchiitsme** [comment]
OK. I have fixed this

**Comment by niveth09** [comment]
Hi @suchiitsme, I am facing the same issue. Can you tell me how did you fix that?

**Comment by elquchiri** [comment]
@niveth09, the simple way is to hide the css class => https://github.com/GrapesJS/grapesjs/issues/2441#issuecomment-562992791
