### ISSUE TITLE
[Question] How can I export including code inside <script></script?>

### ISSUE THREAD

**Issue by HarryChristianR** [artf/grapesjs#2349]
Hi, the <a href="https://github.com/artf/grapesjs-code-editor/">code editor plugin</a> only limits me to preview the HTML & CSS and if I try to add <script></script> .. it's gone?

**Comment by giorgiosjames** [comment]
Do you have allowScripts enabled for your editor?
`const editor = grapesjs.init({
	...
	allowScripts: 1,
});`
