### ISSUE TITLE
Insert block in canvas/domComponents.

### ISSUE THREAD

**Issue by ErnestsMillers** [artf/grapesjs#235]
I am working with grapesjs-mjml and I have created a CKEditor plugin. The following event happens on CKEditor dialog OK button press.
#### All I need to do is take a predefined block and then use domComponents to add it inside wrapper in the editor. Could you help with this? I couldn't find a way in docs or I am just doing something wrong.

It shows up and sort of works if I restart the page. 
But on event I get this: Uncaught TypeError: e.join is not a function, and it gets placed inside 'Box' element, that can be seen in Layer Manager. 
It also breaks MJML parsing into HTML, the element just doesn't show up in output. And on View Code press I get Line 1 (div) — Element div doesn't exist or is not registered.

This is what I have now:
```
var blockManager    = editor.BlockManager;
var domComponents   = editor.DomComponents;
var wrapperChildren = domComponents.getComponents();

var mjText = blockManager.get('mj-text');

var comp1 = wrapperChildren.add(mjText.attributes);
```
Thank you in advance! :)

**Comment by artf** [comment]
You're adding attributes instead of the content
```js
// From
var comp1 = wrapperChildren.add(mjText.attributes);
// To
var comp1 = wrapperChildren.add(mjText.content);
```

**Comment by ErnestsMillers** [comment]
Thank you a lot, @artf. The fix for me was actually 
``var comp1 = wrapperChildren.add(mjText.attributes.content);``
