### ISSUE TITLE
Autocomplete / suggestions for attributes

### ISSUE THREAD

**Issue by bitfactory-angelo-vancleef** [artf/grapesjs#2352]
Hi, cannot find anything on the internet, but I was wondering if it would be possible to have autocomplete in the menu when changing attributes? e.g. a field to edit a block's content, when typing it will give auto suggestions... 

Is this even possible and if so, how can this be done?

**Comment by pouyamiralayi** [comment]
Hi! you can make your own [custom trait](https://grapesjs.com/docs/modules/Traits.html#define-new-trait-type) and for that trait you can use something like [Selectize.js](https://selectize.github.io/selectize.js/) or other libraries alike that suit your needs.
cheers!
