### ISSUE TITLE
Text: New div is created every time I hit enter instead of creating a </br>

### ISSUE THREAD

**Issue by logeshkrishna0** [artf/grapesjs#2353]
## WARNING
READ and FOLLOW next 5 steps, then REMOVE them before posting the issue

1. Follow CONTRIBUTING Guidelines https://github.com/artf/grapesjs/blob/master/CONTRIBUTING.md
2. Use the GitHub Issues EXCLUSIVELY for BUGS, FEATURE REQUESTS or QUESTIONS. Prefix the title of the issue with its context, eg. `[Bug]: ....`
3. Do a quick SEARCH first, to see if someone else didn't open the same issue
4. DON'T ASK to create examples/code for you, read DOCS and APIs first, then you can post what you have tried (we'd like to see your code) and what you're unable to achieve
5. All relative statements/questions have to be filled/answered, otherwise, the issue might be CLOSED

## You're submitting a BUG
  1. Are you using the latest release (older versions are NOT supported)?
      1. If you're not sure, type `grapesjs.version` in console and press ENTER
  1. Are you facing the bug with your local copy of GrapesJS or with the current demo?
  1. If a local copy
      1. Indicate all informations about your OS, browser and GrapesJS version.
      1. Are you able to reproduce the bug from the demo?
  1. What is the expected behavior?
  1. What happens instead?
  1. If you're able to reproduce the bug indicate all the necessary steps
  1. Attach screenshots (using KAP/LICEcap), screencasts or live demo
     1. JSFiddle Starter template https://jsfiddle.net/szLp8h4n
     1. CodeSandbox Starter template https://codesandbox.io/s/1r0w2pk1vl

## You're submitting a FEATURE REQUEST
  1. Be sure to work on the latest version, as the feature might be already there
  1. Keep in mind that the feature should be considered valid to use for everyone, not only for your case

**Comment by logeshkrishna0** [comment]
Is there a reason why when inserting text a new div is created for every break instead of a standard

![31329777-adf6ee50-aca9-11e7-9a4d-7cd06b367135](https://user-images.githubusercontent.com/52228872/67483098-aa9b5a00-f682-11e9-9037-335443e71ca0.png)

> <div class="c4840">Insert your text here. I hit enter
  <div data-highlightable="1">a new div is created
  </div>
  <div data-highlightable="1">I hit enter again
  </div>
</div>

> 
Is it possible to disable this behavior and make a
instead.

I know this works if I hit the shift + enter but I would like for it to be the default option.

**Comment by pouyamiralayi** [comment]
are you on the latest version? i can not see this behavior on the official demo.

**Comment by logeshkrishna0** [comment]
@pouyamiralayi, Are you saying that you wont form the new div when eneter is clicked, but when you try to save it, it would consider that space or next line as new div

**Comment by logeshkrishna0** [comment]
@pouyamiralayi It also happen in the new version have check using the inspect element it add a div each time when click enter in text block

**Comment by pouyamiralayi** [comment]
Hi! i assume that you are not using the text type, just try this one:
```
editor.BlockManager.add('text-block', {
            label: 'Text Block',
            content: '<text>Hi@</text>'
        })
```
cheers!

**Comment by artf** [comment]
> Is there a reason why when inserting text a new div is created for every break instead of a standard

It's a WebKit's behavior

A possible solution: https://github.com/artf/grapesjs/issues/761#issuecomment-484234039
