### ISSUE TITLE
No possibility to use native styles for scrollbar

### ISSUE THREAD

**Issue by kiril-malyhin** [artf/grapesjs#2354]
Hello everyone!

I was fighting for few hours, so maybe someone can help me.
I want to use native styles for scrollbars in editor. But as soon as those styles are set from grapesjs.min.css I have no chance to reset them to browser default.
Do you have any ideas, how I can achieve my goals?

Thanks in advance!

**Comment by artf** [comment]
Unfortunately from what I know, scrollbars are quite particular (are not even part of the DOM) and once a custom style is detected you can't force the redraw to the original. The only solution would be right now to build your own custom grapesjs.css file
