### ISSUE TITLE
[req] Rulers support in designer mode?

### ISSUE THREAD

**Issue by ned-kelly** [artf/grapesjs#2355]
I know there's an older thread with Rulers support as a suggested roadmap item (but it's been closed) - Just wondering if there's any chance of seeing this in GJS in the future? - Would be an awesome addition - I'm currently in the process of writing crop/bleed marks plugins also for responsive print design (aka one design can be exported with various different dimensions for various types of print media).

**Comment by artf** [comment]
> Just wondering if there's any chance of seeing this in GJS in the future?

Sure we might see it one day but for now, it's not my priority so if someone else would like to start this as a PR it would be great

**Comment by ronaldohoch** [comment]
Hello, may it help: 
https://github.com/Ju99ernaut/grapesjs-rulers

**Comment by artf** [comment]
Thanks @ronaldohoch, I'll close this in favor of the plugin
