### ISSUE TITLE
Add link on image in grapsjs editor

### ISSUE THREAD

**Issue by luvcharan** [artf/grapesjs#2356]
Hi,  
Add link (href) to image in grapesjs .

First we add image in grapesjs and then add link to that image, its shows " Link " text next to that image, but i was unable to add link to that image. here i am adding screenshot below, can you please help me out , how to add link in image

![grapesjsLinkIssue](https://user-images.githubusercontent.com/17022456/67752850-c07d9600-fa59-11e9-9515-503f62645809.png)

**Comment by pouyamiralayi** [comment]
Hi @luvcharan you must use ``Link Block`` not ``Link``.
1) first add the link block.
2) then drop your image inside link block.
3) specify href for link block.
cheers!

**Comment by luvcharan** [comment]
Hi @pouyamiralayi
1. I have used the same, first i added link block
2. Then i added image in  that link block
3. Now how can we add URL in that link ( thats the issue )

please assist me in this issue, thanks

**Comment by ck1ldn** [comment]
Hi Do the links not work in a demo, unpublished template.
I've been trying this and it's not working, it works in webflow
![image](https://user-images.githubusercontent.com/13010623/126843974-9c022944-06d3-42b6-ba9a-4ce01f41109a.png)

**Comment by ajayguptacrm** [comment]
editor.on('component:selected', () => {
        if (selectedComponent.attributes.type === 'image') {
            const ImageLinkCommand = {
                icon: 'fa fa-link font-14',
                title: 'Link',
                commandName: 'image-link',
            };
            const DefaultToolbar = selectedComponent.get('toolbar');
            const CommandExists = DefaultToolbar.some(
                (item) => item.command === ImageLinkCommand.commandName,
            );
            if (!CommandExists) {
                DefaultToolbar.push({
                    attributes: {
                        class: ImageLinkCommand.icon,
                        title: ImageLinkCommand.title,
                    },
                    command: ImageLinkCommand.commandName,
                });
                selectedComponent.set('toolbar', DefaultToolbar);

                editor.Commands.add('image-link', {
                    run(editor, sender) {
                        var url = window.prompt('Enter the URL to link to:');
                        if (url) {
                            const SelectedStyles = selectedComponent.getStyle();

                            const newElement = `<a href=${url}>
                                ${selectedComponent.view.el.outerHTML}
                            </a>`;
                            selectedComponent.replaceWith(newElement);
                            
                            var event = new Event('change');
                            selectedComponent.setStyle(SelectedStyles);
                            selectedComponent.view.el.dispatchEvent(event);

                            editor.trigger('change:canvas');
                        }
                    },
                });
            }
        }
    });
    
    This is better approach to handle link image, instead of going ahead with dropping two components for Image link.
