### ISSUE TITLE
[QUESTIONS] How to set callbacks when asset click

### ISSUE THREAD

**Issue by Uysim** [artf/grapesjs#2358]
I can see that image has been set only with a single click on image asset. I want to close the modal even on when click. I try to set a callback on asset click
```javascript
  editor.AssetManager.onClick((model)=>{
    console.log('model');
  })
```
But when I click on asset. The console never trigger.

**Comment by pouyamiralayi** [comment]
Hi there! your answer is [here](https://github.com/artf/grapesjs/issues/763#issuecomment-357958101)
> I want to close the modal even on when click.
```
editor.on('run:open-assets', () => editor.Modal.close())
```

>  try to set a callback on asset click
```
editor.on('run:open-assets', () => console.log('callback!'))
```
cheers!

**Comment by Uysim** [comment]
@pouyamiralayi  This is not correct. My question is about the callback when user click on image on assets manager. 

Your answer mean to close the modal immediately after it is opened

**Comment by pouyamiralayi** [comment]
@Uysim sorry my bad i misunderstood your question.

**Comment by pouyamiralayi** [comment]
@Uysim to my knowledge there is no api for this. the hackish workaround for this might be something like this:
```
editor.on("run:open-assets", function () {
  const assets = document.querySelector('.gjs-am-assets')
  assets.addEventListener('click', () => console.log('callback'))
})
```
cheers!

**Comment by artf** [comment]
@Uysim you can extend the image type
https://grapesjs.com/docs/modules/Assets.html#extend-asset-types

Here is the original [view of the image type](https://github.com/artf/grapesjs/blob/dev/src/asset_manager/view/AssetImageView.js)
