### ISSUE TITLE
Absolute mode, component's style missing when dragged into canvas

### ISSUE THREAD

**Issue by sheldonwr** [artf/grapesjs#2359]
Hi guys, I'm working with grapesjs which version is '0.15.8', and in 'absolute' mode when I drag a block into canvas, I find the styles of component are missing.

Define component as following:

```javascript
domc.addType(lineChartRef, {
    model: defaultModel.extend({
      defaults: {
        ...defaultModel.prototype.defaults,
        name: lineChartRef,
        resizable: true,
        dmode: 'absolute',
        childrenSelectable: false,
        highlightable: false,
        droppable: false,
        style: { "width": "700px", "height": "500px" },
        traits: [...],
        ...
        script() {
          ...
        }
     }
  })
})
```
[And I found the code in Droppable here: /utils/Droppable.js@L78](https://github.com/artf/grapesjs/blob/master/src/utils/Droppable.js#L78)

```javascript
const { left, top, position } = target.getStyle();
comp.setStyle({ left, top, position });
```

the component's styles are replaced.
Should 'addStyle' be used here instead of 'setStyle'?

**Comment by pouyamiralayi** [comment]
Hi @sheldonwr this bug you are referring to is not reproducible in my side, here i tried your type definition on the demo and it is working, please check the below code and see what is missing in your side:
```
domc.addType('lineChartRef', {
    model: {
      defaults: {
      tagName:'p',
        content:'some random text',
        resizable: true,
        dmode: 'absolute',
        childrenSelectable: false,
        highlightable: false,
        droppable: false,
        style: { "background":'red',"width": "700px", "height": "500px" },
        script() {
        }
     }
  }
})
```
```
bm.add("testLine",{
label:'lineChartRef',
  content:{
  type:'lineChartRef'
  }
})
```
the issue i observed with this component was that when i move it around, the component stops rendering children and freeze with no respond to any interaction. this might be a bug by specifying component level drag mode instead of global. @artf
cheers!

**Comment by artf** [comment]
Ok, actually a weird thing happens when a component has `script` property defined...
Thanks for the report guys, I'll check this out. Can you confirm that without `script` it behaves correctly?

**Comment by pouyamiralayi** [comment]
@artf yes! this is not happening if i remove ``script``. the behavior is fine.

**Comment by sdrebel** [comment]
In my custom component script is not there but still I have the issue.
