### ISSUE TITLE
Images don't display over email

### ISSUE THREAD

**Issue by timkelly0810** [artf/grapesjs#2361]
My team and I used grapesjs to create email templates and are storing them in an AWS S3 bucket. We have successfully sent an email through our web application, however, images fail to display. After clicking "view original", I can see that the image src displays properly, but the actual image doesn't display. We believe it may have something to do with the base64 encoding. Is there any reason why images within a template wouldn't display when sending to a popular email service such as Gmail?

**Comment by artf** [comment]
From what you said it might be also because you simply didn't enable to view images in that email... 
Anyway, this has nothing to do with GrapesJS itself so there is no reason to keep this issue open.

**Comment by timkelly0810** [comment]
Does grapesjs encode images within templates to base64? If so, is there a way to NOT do this or to decode before sending to S3?

**Comment by artf** [comment]
https://github.com/artf/grapesjs/blob/dev/src/asset_manager/config/config.js#L77

**Comment by devtechk** [comment]
Hello there, ther's a way to convert images src="" that are already present in the template when loading the first (placeholder) template? 
I'm not talking about import images from the asset, but handle img src's tag decoding in base64 in the dom (canvas).
Thank you
