### ISSUE TITLE
[Question] How to add toolbar functionality to the layers panel. 

### ISSUE THREAD

**Issue by marlitob** [artf/grapesjs#2364]
I am trying to add the toolbar to the layers panel and I am not sure how to go about this. 

Is there any way to accomplish this? 

toolbar 
![toolbaricons](https://user-images.githubusercontent.com/31751146/67986516-724acd00-fbe8-11e9-8967-21d301b1fb42.png)

Where I would like to place them:

![layersPannelGrapesJS](https://user-images.githubusercontent.com/31751146/67986313-f0f33a80-fbe7-11e9-9c89-1484f4b7c300.png)

Thank you for your response guys!

**Comment by pouyamiralayi** [comment]
Hi there! what do you mean by toolbar? is [this ](https://github.com/artf/grapesjs-navbar)what you are looking for?
cheers!

**Comment by memariolife** [comment]
@pouyamiralayi  This is what i mean 
![updatedTBimg](https://user-images.githubusercontent.com/31751146/68037607-5b0ded00-fc85-11e9-917c-d873a915c005.jpeg)

**Comment by MatthewMariner** [comment]
@artf Is there a way to do this? I was looking at the LayerManager and didn't see any copy/delete methods in the layer manager

**Comment by artf** [comment]
At the moment, there is no easy way to change/customize navigator items content. 

What we could add next is a new callback option in [configs](https://github.com/artf/grapesjs/blob/dev/src/navigator/config/config.js) that would be executed inside [ItemView template](https://github.com/artf/grapesjs/blob/7a23e20fe5138c37088ef05382f7c759cb6fa951/src/navigator/view/ItemView.js#L22) and would allow any HTML content (similar to [custom render](https://grapesjs.com/docs/modules/Blocks.html#custom-render) in Blocks)

I don't have any priority on this so PRs are welcome

**Comment by hashimkhatri** [comment]
Hello guy I have customized the plugin and add delete feature in layer list,

add css:
.gjs-layer-vis{
    height: auto !important;
    width: auto !important;
    left: 25px;
    top: 0;
    padding: 10px 0px 10px 0px;
    position: absolute;
    cursor: pointer;
    z-index: 1;
}
.gjs-layer-delete{
    height: auto !important;
    width: auto !important;
    left: 10px;
    top: 0;
    padding: 10px 0px 10px 0px;
    position: absolute;
    cursor: pointer;
    z-index: 1;
}

//GrapesJS Initialization:

var editor = grapesjs.init({ 
layerManager: {
        appendTo: '#sitelayercomponent',
        **deleteable:1,** //add this line in your layer manager config.
    }
})


//Package Customization
**Line (12596):**
events: {
                'mousedown [data-toggle-move]': 'startSort',
                'touchstart [data-toggle-move]': 'startSort',
                'click [data-toggle-visible]': 'toggleVisibility',
                **'click [data-toggle-delete]': 'toggleDelete',** //Add this line
                'click [data-toggle-open]': 'toggleOpening',
                'click [data-toggle-select]': 'handleSelect',
                'mouseover [data-toggle-select]': 'handleHover',
                'mouseout [data-toggle-select]': 'handleHoverOut',
                'dblclick [data-name]': 'handleEdit',
                'keydown [data-name]': 'handleEditKey',
                'focusout [data-name]': 'handleEditEnd'
            } 

**Line (12616):** 
**replace return with**

return "\n      ".concat(odl ? "<i class=\""+e+"layer-delete fa fa-trash\"  data-toggle-delete></i>": '').concat("\n      ").concat(o ? "<i class=\"".concat(e, "layer-vis fa fa-eye ").concat(this.isVisible() ? '' : 'fa-eye-slash', "\" data-toggle-visible></i>") : '', "\n ").concat("<div class=\"",c, "\">\n        <div class=\"").concat(l, "\" style=\"padding-left: ").concat(f, "\" data-toggle-select>\n          <div class=\"").concat(e, "layer-title-inn\">\n            <i class=\"").concat(u, "\" data-toggle-open></i>\n            ").concat(g ? "<span class=\"".concat(v, "__icon\">").concat(g, "</span>") : '', "\n            <span class=\"").concat(d, "\" data-name>").concat(p, "</span>\n          </div>\n        </div>\n      </div>\n      <div class=\"").concat(this.clsCount, "\" data-count>").concat(a || '', "</div>\n      <div class=\"").concat(this.clsMove, "\" data-toggle-move>\n        <i class=\"fa fa-arrows\"></i>\n      </div>\n      <div class=\"").concat(this.clsChildren, "\"></div>")


**Line (12640):**            
 **Add this function**            
toggleDelete: function (t) {
                t && t.stopPropagation();
                var e = this.model,
                    n = this.em,
                    r = '__prev-display',
                    i = e.get(r),
                    o = e.getStyle(),
                    a = o.display;
                if (confirm("Are you sure you want to delete this component.")) {
                    e.remove() && n.trigger('component:toggled')
                } else {
                    n.trigger('component:toggled')
                }
            }
            
          
            **If you confuse due to my English please check attachment (I am attaching the grapes.js file: change file extention)**

[grapes.min.txt](https://github.com/artf/grapesjs/files/6277307/grapes.min.txt)

**Comment by artf** [comment]
Actually, it should be possible now to use the [`layerManager.onRender`](https://github.com/artf/grapesjs/blob/a2450ff4585a06f5ace0242c6ea56fe6d56ba81c/src/navigator/config/config.js#L50-L61) callback option
