### ISSUE TITLE
Unable load predefined template.

### ISSUE THREAD

**Issue by dukie66** [artf/grapesjs#2365]
I want to show a predefined template when users open grapesJs something like this: [Storage manager](https://grapesjs.com/docs/modules/Storage.html#store-and-load-templates).
![image](https://user-images.githubusercontent.com/52957816/68020631-11dd8d80-fcc5-11e9-9bc6-f4bd3484ab42.png)
**HTML:**
		`<div id="gjs" style="height:0px; overflow:hidden"></div>
		<script src="app.js"></script>`

**javascript in app.js:**
```js
// Set up GrapesJS editor with the Newsletter plugin
const LandingPage = {
	html: '<div> style="background-color="red"; height="100px"; width="100px"</div>',
	css: null,
	components: null,
	style: null,
};
components: LandingPage.components || LandingPage.html,
	style: LandingPage.style || LandingPage.css,
	clearOnRender: true,
	storageManager: {
		id: 'gjs-',
		type: 'local',
		autoload: true,
		autosave: true,
		storeComponents: true,
		storeStyles: true,
		stepsBeforeSave: 1,
		// contentTypeJson: true,
	},
```
**Result**: Blank editor
![image](https://user-images.githubusercontent.com/52957816/68021027-4d2c8c00-fcc6-11e9-8e50-16cf83f9cd70.png)

**Comment by pouyamiralayi** [comment]
[template](https://github.com/artf/grapesjs/issues/2195#issuecomment-522504337)

**Comment by artf** [comment]
@dukie66 `<div> style="background-color="red"; height="100px"; width="100px"</div>` this is not how you supposed to write HTML
