### ISSUE TITLE
Jquery Conflict Issue

### ISSUE THREAD

**Issue by bungambohlah** [artf/grapesjs#237]
Hello again @artf, long time no see you hehehe, i have a problem with your GrapesJS.
The problem is when i try to init grapesJS with jquery included for sure, then in my canvas have a jquery's script too but different version, then i try to run it's error, can't drop anything component into the canvas and show error like this :
![image](https://user-images.githubusercontent.com/19922064/29453573-477e23e8-8434-11e7-85c2-1a066270a0a3.png)

Then i remove jquery scripts inside the canvas, it's works.
Well, my question is, can i duplicate or overriding jquery inside or outside the canvas? it's make more compatibility with any component.

EDIT: Jquery Same version still error

Thank u and sorry for my bad english

**Comment by artf** [comment]
Hi @bungambohlah can you show me how you inject the script inside the canvas. Maybe this might help you https://github.com/artf/grapesjs/wiki/Components-&-JS#template-related

**Comment by bungambohlah** [comment]
Thank u for ur reply, i can show my code

First in the container with id "gjs" and grab the content directly from the element :

**Comment by artf** [comment]
@bungambohlah you're loading an entire HTML document inside another, don't do it, it's wrong just by definition. Basically, this is what happening before the browser fixes it by itself
```html
...
</head>
  <body>
    <div id="gjs" style="height:0px; overflow:hidden">
       <html> <!-- not good -->
          <head>
          ...
             <!-- With this new jquery you're overriding the one already in and therefore breaks it -->
             <script type="text/javascript" src="//code.jquery.com/jquery-3.2.1.min.js"></script>
          ...
    </div>
    ...
```
> can i initialize jQuery for the content directly from the element

Sure, this is what you see here
https://github.com/artf/grapesjs/wiki/Components-&-JS#component-related

**Comment by bungambohlah** [comment]
Thank u as ur help @artf ,

> you're loading an entire HTML document inside another, don't do it, it's wrong just by definition. Basically, this is what happening before the browser fixes it by itself

Yes sure, i want to load dynamically html that changed or saved by user and could be edit again, it's done with load/save storage method but i want to get the file from my web designer intact and when the client made the first change will be sure load html entirely, and the second change and so on will use load/save storage method, am i right? or you have another suggestion?

i have a suggestion with this,
it's works when i try execute this script in my ```someinternalhtmlforload.html``` file that from my web designer :

```html
...
<script>
    if(typeof jQuery == 'undefined')
    {
      console.log('inserting jquery...');
      var script = document.createElement('script');
      script.type = "text/javascript";
      script.src = "https://code.jquery.com/jquery-3.2.1.min.js";
      document.getElementsByTagName('head')[0].appendChild(script);
    }
</script>
...
```
it's make more compatibility and not overriding with anyone component, i can give that script to my web designer :+1: 

Thank u and sorry for my bad english

**Comment by artf** [comment]
Nice workaround, about how to store templates properly I think I'll make a quick guide later

**Comment by KMantas** [comment]
Hi

I have little bit different issue, but it is similar so posting here.

I'm using jQuery in component and I've tried both recommend options for loading custom script. Through canvas for all components:
```
    canvas: {
        scripts: ['jquery.min.js']
    }
```
and also inside component: 

```
var jquery = document.createElement('script');

jquery.src = "jquery.min.js";
jquery.onload = function() {
  var script = document.createElement('script');
  script.onload = initMySLider;
  script.src = "jquery.cycle2.min.js";
  document.body.appendChild(script);
};
document.body.appendChild(jquery);
```

initially bothways it works fine - I use jQuery cycle plugin and it works. But I'm trying to access that plugin when model change event is fired:

```
init() {
  this.listenTo(this, 'change:count', this.updateSlideCount);
},
updateSlideCount() {
  $(this.view.el).cycle('reinit');
},
```

this doesnt work, because here $ refers to jQuery loaded by GrapesJS and cycle plugin is not there.
any ideas how to fix this? 


thanks

**Comment by ateshuseyin** [comment]
Canvas works inside of a iframe. So, you can use document.querySelector('iframe').contentWindow.$; I think it should works

**Comment by KMantas** [comment]
it worked! thanks
