### ISSUE TITLE
Using existing jsx template with grapesjs and also convert the grapesjs UI generated template to react jsx template

### ISSUE THREAD

**Issue by arunkumar413** [artf/grapesjs#2370]
Hi Team,

I just started playing with grapesjs and I'd like to use the exising/currently working react template/component in grapesjs UI editor. And also convert the template created in grapesjs to the react/jsx template/component format. Could you please let me know if this is possible with grapesjs and guide me to use/configure grapesjs to achieve my requirement. 

Thanks,
Arun

**Comment by pouyamiralayi** [comment]
Hi there! you can use ``editor.addComponents(<div>Hello JSX</div>)`` to add components.
for framework specific JSX, you can use [processor callbacks](https://github.com/artf/grapesjs/blob/c1fb490a73adefb0fa073f37bef4e6178d9321a8/src/dom_components/config/config.js#L40-L58) as well.
cheers!

**Comment by artf** [comment]
@arunkumar413 we're not yet at the point of working directly with React components but something is moving #1970
