### ISSUE TITLE
wrong position for datapicker and element controls

### ISSUE THREAD

**Issue by picozzo92** [artf/grapesjs#2373]
[Bug]: Hello, I integrated grapes js into an asp.net core / angular project I have two problems:
1. Randomly after adding blocks the toolbar and the highlighter are displayed in wrong positions.
![screen_position](https://user-images.githubusercontent.com/7261023/68115728-623d3100-fef9-11e9-8b8a-ebd2d2ad0377.png)

2. When I click on the datapicker it is displayed in a wrong position outside my window.
![screen_position_cp](https://user-images.githubusercontent.com/7261023/68115743-6c5f2f80-fef9-11e9-9d58-16bdc8c5c6c3.png)

**Comment by artf** [comment]
@picozzo92 Are you able to create a minimal reproducible demo of this issue?
I'm working on a [big canvas refactoring](https://github.com/artf/grapesjs/tree/multi-frame) that will probably fix all related issues, having a reproducible demo will help to understand that

**Comment by SaleDrache** [comment]
I had same issue for colorpicker positioning and concluded that it's position is given related to screen / html tag (position: absolute , left: x px) , but if any parent element containing gjs-editor has position: relative , it will affect modal's position (if for example you have a sidebar on a page like I had).

Hope that this helps and can give some hints.

**Comment by artf** [comment]
To the color position issue refer to this one https://github.com/artf/grapesjs/issues/1533#issuecomment-432146597
