### ISSUE TITLE
using material UI with grapesjs

### ISSUE THREAD

**Issue by arunkumar413** [artf/grapesjs#2376]
Hi Team,

I'm trying to use the material UI components in with  the grapes but the material UI components aren't rendering as expected (https://codesandbox.io/s/grapesjsapp-umxf5). I have used this template (https://github.com/prashant2018/GrapesJs-React) to test the material UI.

Also could you please clarify on the use case of this tool. Is this tool intended for building components using the regular HTML tags as opposed to using any framework like react? Or does this complement the react, angular, vue etc? 

On a side note, a chat channel to discuss beginner and small implementation issues would be of great help.

Thanks,
Arun

**Comment by pouyamiralayi** [comment]
@arunkumar413 for material use case please refer to [gramateria](https://github.com/ronaldaug/gramateria)

> please clarify on the use case of this tool

grapesjs is a template builder that currently supports web. also it provides api's that can easily be integrated with any type of cms.

>  Is this tool intended for building components using the regular HTML tags as opposed to using any framework like react? Or does this complement the react, angular, vue etc?

the frameworks you mentioned have different use cases compared to grapesjs. to my knowledge reactivity or web hooks does not have any relationship with grapesjs but sure thing is that you can use grapesjs to build web pages composed of these frameworks components or integrate their components libraries into the ecosystem as well. no need to mention grapesjs allows you to build upon your custom defined components which has built in supports for react .
cheers!

**Comment by artf** [comment]
> Also could you please clarify on the use case of this tool. Is this tool intended for building components using the regular HTML tags as opposed to using any framework like react? Or does this complement the react, angular, vue etc?

https://github.com/artf/grapesjs/issues/2370#issuecomment-550515205

**Comment by Rishabh-prescience** [comment]
I was able to integrate Material UI with GrapesJS, but I am stuck at Integration of ApexCharts. Can anyone look into it?
['CodeSandBox'](https://codesandbox.io/s/grapesjs-emilsedgh-example-forked-xiq9r?file=/src/index.js). Thanks

**Comment by Saif-Hossain-Mredul** [comment]
@Rishabh-prescience  can you please share the repo of material UI integration? or give an idea about it? I am stuck here
