### ISSUE TITLE
[QUESTION] Support multiple languages for the page content

### ISSUE THREAD

**Issue by varadero** [artf/grapesjs#2380]
What we need is to create a page once but translate the text content in multiple languages. Imagine a very simple sample of a single text block saying "Hello" - we don't want to force the users to create another page with that same text block saying the same in different language. Imagine the page must be translated in 10 languages and the page has 20 text blocks - it would be too hard to do and maintain clones of the page containing the same components with just different texts (adding new text field would require adding it in every clone, which is something that nobody will do). Is there any way to do this with current GrapesJS like a drop-down which switches between different "sets" of text content so the user can choose a language and then go and change the text content for that language of whatever components he wants ?

I was thinking of storing the "data" object on StoreManager's "store" function on language change, but this will not work well if the user switches the language and adds new component - then the current language object and all other language objects will become different (other language objects not having the new component added for the current language).

**Comment by pouyamiralayi** [comment]
@varadero i18n module is on the [roadmap](https://github.com/artf/grapesjs/issues/74#issue-222570799)
cheers!

**Comment by varadero** [comment]
@pouyamiralayi But isn't that i18n mentioned there just a module that will allow you to translate GrapesJS itself, not the content that the user created ?

**Comment by pouyamiralayi** [comment]
@varadero please refer to [this](https://github.com/artf/grapesjs/issues/2342)

**Comment by varadero** [comment]
Closing s duplicate of https://github.com/artf/grapesjs/issues/2342
