### ISSUE TITLE
[QUESTION] Is it possible to add info modal on the editor

### ISSUE THREAD

**Issue by ColinTenaguillo** [artf/grapesjs#2381]
Hi,

I would like to add on the grapejs editor a clickable questionmark we can click so we could give information on what does this specific spec to the user.

![image](https://user-images.githubusercontent.com/36203690/68286437-65fbbf80-0081-11ea-9e47-ba366c822984.png)

It would open a modal with all the information that we could give when we add the property to a sector. Like you do in the webpage demo.

![image](https://user-images.githubusercontent.com/36203690/68287251-b9bad880-0082-11ea-94e9-429c2477e1cc.png)

**Comment by artf** [comment]
Currently, there is no documentation about extending/updating style manager properties (I've just realized few plugins like [grapesjs-style-filter](https://github.com/artf/grapesjs-style-filter) and [grapesjs-style-gradient](https://github.com/artf/grapesjs-style-gradient) but is not enough) and in all honesty, what I've done so far (as public API) it's not that solid, I don't like it. I'd like to reach the same result of [customizing traits](https://grapesjs.com/docs/modules/Traits.html#define-new-trait-type) but we have to wait before reaching this change...

**Comment by ColinTenaguillo** [comment]
Here what i made today with a bit of modifications : 

![image](https://user-images.githubusercontent.com/36203690/68382538-2ce04f80-0154-11ea-8ad9-c6ef9b77a444.png)

**Comment by artf** [comment]
Great, if you want to share your current solution with others it for sure will be appreciated :)

**Comment by ColinTenaguillo** [comment]
Hey, how can i publish my branch with my modification for a pull request ?

**Comment by artf** [comment]
> Hey, how can i publish my branch with my modification for a pull request ?

https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork

About the changes, as you were able to edit `templateLabel` in that case I'd just add the info icon and on click would use Modal API (so without rendering `templateModal` in all properties)

**Comment by sagar7993** [comment]
If possible could you provide a working snippet for this please, i am unable to figure this out.
