### ISSUE TITLE
Custom component not pulling through style on first add.

### ISSUE THREAD

**Issue by smik3** [artf/grapesjs#2383]
Fiddle replicating the issue: https://jsfiddle.net/gd8mo3e4/1/

I have a custom component for creating a gallery of pdf documents. There's a custom asset manager that opens when the block is dropped into the editor, to allow you to choose the pdf which then changes the thumbnail.

The issue that i'm having is that on a fresh page reload, the first time you drop in a new pdf block, it isn't importing the styles from the model. If you delete it and add in a new block, it does.

You can see this by creating columns, and dropping a pdf block into it.

**Comment by pouyamiralayi** [comment]
Hi @smik3 what do you mean by unloaded styles? i can not see that from the provided fiddle. it was working fine.

**Comment by smik3** [comment]
The thumbnail/image which it puts into the editor should be scaling to fit the container. I'm seeing it at original size on first-load, all subsequent block adds correctly fit whichever column they are dropped into. If you look at the export code, you can also see that the first time you drop a block in, it does not update the css. On subsequent blocks it's added

**Comment by smik3** [comment]
A couple of screenshots demonstrating the behaviour I'm seeing...

<img width="1021" alt="Screen Shot 2019-11-06 at 11 32 16" src="https://user-images.githubusercontent.com/19346508/68294968-394ba600-0089-11ea-941a-e441d3469c6f.png">

<img width="1003" alt="Screen Shot 2019-11-06 at 11 32 33" src="https://user-images.githubusercontent.com/19346508/68294986-3fda1d80-0089-11ea-8be3-323152923b73.png">

**Comment by pouyamiralayi** [comment]
i guess this is related to [this one](https://github.com/artf/grapesjs/issues/738) and probably [this one](https://github.com/artf/grapesjs/issues/2337) @artf

**Comment by artf** [comment]
Changing `modelThumbElement.setAttributes({"data-gallery":fileName});` to use `addAttributes` seems to fix it, but I'm not sure what is really happening (I'd expect the "wrong" behavior all the time, not only the first time)

**Comment by smik3** [comment]
Hmm, yes I can confirm that fixes the issue - I'm guessing the setAttributes function is somehow (but not consistently?) resetting the styles as well, since there are no styles included in the object?

**Comment by artf** [comment]
> I'm guessing the setAttributes function is somehow (but not consistently?) resetting the styles as well

Yes exactly, this is why I'd expect it to reset attributes every time

**Comment by bgrand-ch** [comment]
@artf 2 years is a very long time, closed all 2 years and more?

**Comment by artf** [comment]
Yeah for now we can close it as inactive, thanks
