### ISSUE TITLE
Finer drag and drop resizing and repositioning control

### ISSUE THREAD

**Issue by rodenp** [artf/grapesjs#2384]
I would like to be able to add extra functionality to the drag and drop of components, so as to allow for easy resizing and repositioning without having to manually go through the panels on the right side of the screen.

Can you please provide some guidance on where in the code base to focus on?
Has anyone else done anything similar who would like to share their experience and knowledge?

Thanks

**Comment by pouyamiralayi** [comment]
> allow for easy resizing

you can add ``resizable: true`` to your [component type definition](https://grapesjs.com/docs/api/component.html#properties)

> functionality to the drag and drop of components

you can apply this on either the editor or an specific component:
```
editor = grapesjs.init({
      dragMode:'absolute',
})
// or for a specific component:
component.setDragMode('absolute')
```
cheers!

**Comment by rodenp** [comment]
thanks @pouyamiralayi for your guidance.
Will this also work for things like columns?

**Comment by pouyamiralayi** [comment]
@rodenp yes! every component type can benefit from this.
