### ISSUE TITLE
[Question] - How to import styles from <link> to be rendered when dragging block to canvas

### ISSUE THREAD

**Issue by fasaas** [artf/grapesjs#2388]
My situation:  
I'm slowly importing some of my custom made UI components in `ReactJS` to `GrapesJS`.  
Now, I am able to render the component properly by integrating it with Backbone.  
But my question is, can I use `<link` tags to download my own custom styles, so that I can see them properly within the canvas?  

I have tried doing so, but to no success. I wouldn't want to manually download every CSS of my UI Library, but if I render any component, I would like that the component styling matches the `<link` imported styles.

**Comment by pouyamiralayi** [comment]
Hi @fasaas you can inject your global styles this way:
```
const editor = grapesjs.init({
    canvas:{
        styles: [ 'https://...1.css', 'https://...2.css' ]
    }
})
```
the same goes for your custom scripts. more on this [here](https://github.com/artf/grapesjs/blob/master/src/canvas/config/config.js)
cheers!

**Comment by artf** [comment]
Just init the editor with your `<link>` inside the template, it will be loaded in the canvas and you will be able to see it in your export code

**Comment by devtechk** [comment]
Hi @artf I'm looking to import inside canvas a style like code below. The problem is that I'm using Angular, and I'd like to import the scss of the component instead. How can i do?
Thank you
```
canvas: {
    styles: ['https://...'] 
}
```

**Comment by senthil177cse** [comment]
@devtechk did you found solution for this issue in angular?
