### ISSUE TITLE
[QUESTIONS]urlLoad, keeping telling me 400 bad request

### ISSUE THREAD

**Issue by bjccdsrlcr** [artf/grapesjs#2391]
When I trying to use urlLoad, why keeping telling me 400 bad request. please help
![image](https://user-images.githubusercontent.com/30322340/68465815-233b1280-024e-11ea-91ae-e8ab91018bcd.png)

**Comment by bjccdsrlcr** [comment]
it seems that front using content-type with json. but didnt pass any value. and my backend frame required value when the content-type is json. where can i pass any param?

**Comment by bjccdsrlcr** [comment]
![image](https://user-images.githubusercontent.com/30322340/68470625-65b51d00-0257-11ea-9f16-b3714ab60fb9.png)
I change the source code "get" to "post", works.

**Comment by bjccdsrlcr** [comment]
![image](https://user-images.githubusercontent.com/30322340/68471452-330c2400-0259-11ea-819f-8736e49014b1.png)
a new question is that remote data is not rendered

**Comment by pouyamiralayi** [comment]
@bjccdsrlcr consider that you are overriding the load logic, are you calling the passed callback with correct data?

**Comment by bjccdsrlcr** [comment]
@pouyamiralayi  solved it. maybe my backend framework add the extra key (jsonrpc, id) cause it. 
so I change the source code to get the actual gjs-assets, gjs-components, gjs-css, gjs-html, gjs-styles value. then it works
![image](https://user-images.githubusercontent.com/30322340/68521305-b457cb00-02da-11ea-99b0-965d6acab709.png)
