### ISSUE TITLE
[Bug] - Unable to nest <div id="gjs"> into any other tag

### ISSUE THREAD

**Issue by fasaas** [artf/grapesjs#2392]
It seems that the `index.html` structure needs to be the following:  
```html
<body>
      <div id="gjs" style="height:0px; overflow:hidden"></div>
<script ... >
```
I am not able to nest this `div` within another `div` like so:
```html
<body>
    <div class="site-content">
        <main class="site-main">
            <div id="gjs" style="height:0px; overflow:hidden"></div>
        </main>
    </div>
</body>
```

Since my custom styles require the presence of the first `div` and the `main`, and I've tried updating the `container` property for the `grapesjs.init` to no success, I'm asking if this is possible

**Comment by fasaas** [comment]
If this is not possible, is there a way to explicitly indicate that when I add a new Block into the BlockManager, the container should be a specific container that I can have previously define in `index.html` ?  
E.g.  
```javascript
  blockManager.add('whatever', {
    label: 'Content Label name',
    content: { type: 'my component type name' },
    category: 'category name',
    component: '.site-main`
  });

```

**Comment by pouyamiralayi** [comment]
@fasaas i am not sure that your approach at above code is the right way to define blocks!
for your problem with nesting divs, i think there is some problem with your styles, because there is no limitation on the way you put your div with ``gjs`` as it's id. it could be any where.
please provide a fiddle if you can.
cheers!

**Comment by fasaas** [comment]
What I have done is to just clone this repo, and nest the `<div id="gjs" style="height:0px; overflow:hidden;">` within another `<div>`, so it would be like 
```
<div>
    <div id="gjs" style="height:0px; overflow:hidden;">
    </div>
</div>
```

When I run `npm start`, I am getting a blank page

**Comment by pouyamiralayi** [comment]
@fasaas did you specify this in your html?
```
<style>
        body,
        html {
            height: 100%;
            margin: 0;
        }
    </style>
```
