### ISSUE TITLE
Remove Font-Awesome 4.7 dependency

### ISSUE THREAD

**Issue by chiqui3d** [artf/grapesjs#2394]
Hello,

I found that the editor depends on the Font-Awesome 4.7 library, so much is the categories, in the panels, layer manager (fa fa-eye, fa-caret-down), Why hasn't this been included with the grapes font?

I got to modify the panels icons, but not the categories, I mean fa-caret-down and fa-caret-right, now when I include a template that includes Font-Awesome 5, it breaks everything.
Do you know any way to change these icons?

**Comment by pouyamiralayi** [comment]
hi @chiqui3d getting rid of Font Awesome is currently on the [road map](https://github.com/artf/grapesjs/issues/74).

if you want to update to Font-Awesome 5.0, there is a closed [PR ](https://github.com/artf/grapesjs/pull/2240)that can help you.

cheers!

**Comment by chiqui3d** [comment]
Thanks, but the best thing is that the default icons are own Grapesjs(with IcoMoon) and then the user is the one who chooses which fonts to use for his project, but of course not to depend on whether it is version 4 or 5.

**Comment by pouyamiralayi** [comment]
yes @chiqui3d and it is going to be like this. check this [PR](https://github.com/artf/grapesjs/pull/1932)
cheers!

**Comment by artf** [comment]
Hey @chiqui3d I was waiting the PR from you https://github.com/artf/grapesjs/issues/644#issuecomment-421553006 😝
BTW I'd close this issue and move the discussion to the old one #644
I'd like also to propose a quick solution
