### ISSUE TITLE
[Question] Dumb question: what's the simplest way to build a simple website with this?

### ISSUE THREAD

**Issue by JpTiger** [artf/grapesjs#2395]
This is a really dumb question, but I'm not finding the answer anywhere obvious: I'm a beginner with a free JS codecademy course under my belt and a lot of time spent making/maintaining sites on WordPress. I want to make a new website or three using open-source tools that'll be more user-friendly for myself and end users and leave behind some of the unnecessary complexity and security holes that [my webhost is always complaining about with WP](https://www.helionet.org/index/topic/33983-what-was-the-anonymousfox-hack/).

So I started looking for open-source page builders. GrapesJS' interface looks fantastic, but I'm having a hard time finding the rest of the tools I'd need to build an actual site - I'm guessing the an actual CMS it's meant to be embedded inside. Are there any open source CMS' that use grapesJS that I could install on my server and set something up with? Thank you!

**Comment by pouyamiralayi** [comment]
@JpTiger there are tools out there based on grapesjs that can help you design your page very quickly: [gramateria](https://github.com/ronaldaug/gramateria) and 
the rest can be achieved using popular open source and easy to use cms's like [pagekit](https://github.com/pagekit/pagekit) and [directus](https://directus.io/). i personally prefer [strapi](https://strapi.io/); these all come with user friendly interfaces and you barely touch the code during the process.
cheers!

**Comment by artf** [comment]
I know [OctoberCMS](https://octobercms.com/) has this [plugin](https://octobercms.com/plugin/pkurg-pagebuilder) and I've seen others but can't recall their names 😓
