### ISSUE TITLE
Can't select the model using editor.select()

### ISSUE THREAD

**Issue by naveen-15697** [artf/grapesjs#2396]
I am trying to select the first component in the editor by using editor.select(editor.DomComponents.getComponents().models[0]). It is not working.

**Comment by pouyamiralayi** [comment]
> select the first component in the editor
```
editor.select(editor.getComponents().models[0])
```
cheers!

**Comment by naveen-15697** [comment]
> > select the first component in the editor
> 
> ```
> editor.select(editor.getComponents().models[0])
> ```
> 
> cheers!

@pouyamiralayi , I tried this too. But it is not working.

**Comment by naveen-15697** [comment]
@artf , @pouyamiralayi :I need this condition inside the 'canvas:drop' event
editor.on('canvas:drop', ()=>{ 
...
... // My code to select the first component is here //...
...
})

**Comment by pouyamiralayi** [comment]
@naveen-15697 you can achieve this with:
```
editor.on('block:drag:stop', (m) => {
    if(m){
       editor.select(editor.getComponents().models[0])
    }
})
```
cheers!

**Comment by naveen-15697** [comment]
@pouyamiralayi Thanks! It's working now.

@artf , But, Why it is not working in 'canvas:drop' event?

**Comment by artf** [comment]
I think the selection is cleared somewhere after `canvas:drop`, I'll try to check it later

**Comment by RutujaBadbe** [comment]
i want to append dropped block at specific index. for example I want to append it at top of everything else. currently, I am doing this. but it is not working. Can anybody help? I am new to this.

editor.on('canvas:drop',(DataTransfer, model)=> {
   if (model.is('header')) {
      var index = 0;
      editor.getComponents().add(model, {at: index});
        }    
})
