### ISSUE TITLE
Styles not recognized in the Style Manager

### ISSUE THREAD

**Issue by chiqui3d** [artf/grapesjs#2397]
Hello,
I am testing why some styles are not recognized in the Style Manager, but I don't find it, I have tried to use `avoidInlineStyle: true`, but the same, it are not recognized.
Here is the example:
https://jsfiddle.net/charles_es/x6yr7z91/28/

**Comment by chiqui3d** [comment]
Okay I just realized, having a class element the inline styles are no longer recognized, why?

**Comment by pouyamiralayi** [comment]
@chiqui3d  ``avoidInlineStyle`` is true by default in the latest [release](https://github.com/artf/grapesjs/releases/tag/v0.15.8).

**Comment by chiqui3d** [comment]
Thank you, I also realized that if the element has a class and an id, then the ID styles are not recognized in the style manager either.

**Comment by pouyamiralayi** [comment]
yes @chiqui3d i guess that is also because of the ``avoidInlineStyle`` being ``true``.

**Comment by chiqui3d** [comment]
Even if I set it to false, it still happens.
https://jsfiddle.net/charles_es/x6yr7z91/33/

**Comment by pouyamiralayi** [comment]
@chiqui3d yes this is because of the shared selectors.

**Comment by chiqui3d** [comment]
Do you know how to solve it?

**Comment by pouyamiralayi** [comment]
@chiqui3d this [thread](https://github.com/artf/grapesjs/issues/404#issuecomment-345253384) might be helpful.
cheers!

**Comment by artf** [comment]
@chiqui3d the behavior of why it's happening is explained here #863
