### ISSUE TITLE
SVG Component Not Draggable

### ISSUE THREAD

**Issue by imranali2045** [artf/grapesjs#2399]
Hi,
I am using grapesjs in angular 7.What I want to achieve when ever canvas drop method called I add svg component in canvas.I have add svg component on canvas drop method.But its not draggable. I attach my code and video for better understand.Thanks @artf if you help me.   
 
<code>const domComponents = this._editor.DomComponents;</code>
        <code>const wrapperChildren = domComponents.getComponents();</code>
         <code>comp = wrapperChildren.add({</code>
          <code> tagName: 'svg',</code>
           <code>type: 'svg',</code>
           <code>attributes: { viewBox: '0 0 100 100', xmlns: 'http://www.w3.org/2000/svg' },</code>
           <code>stylable: true,</code>
           <code>resizable: true,</code>
           <code>removable: true, </code>// Can't remove it
           <code>draggable: true, </code>// Can't move it
           <code>copyable: true, </code>// Disable copy/past
           <code>content: `
          <circle cx="50" cy="50" r="40" stroke="black" stroke-width="3" fill="red" />`, </code>
<code> });</code>

![HD2-GoogleChrome2019-11-1215-08](https://user-images.githubusercontent.com/52451938/68665848-a1582b80-0564-11ea-88a7-ffb9160c0db6.gif)

**Comment by imranali2045** [comment]
@artf please see that It is very important for me to solve this problem.thanks

**Comment by artf** [comment]
Unfortunately, HTML5 drag and drop API doesn’t work on SVG elements, so if you need to support it you have to wrap your SVG components (eg. in a `div` element)

**Comment by imranali2045** [comment]
@artf ok thanks

**Comment by pardeepenverx** [comment]
Tried wrapping into another components HTML Div but still not working for me, any other workaround?

**Comment by pardeepjainsolulab** [comment]
Tried wrapping into another components HTML Div but still not working for me, any other workaround?
