### ISSUE TITLE
Can't put Form element to page

### ISSUE THREAD

**Issue by phil1995** [artf/grapesjs#240]
If I try to put something from the Form block onto the webpage (demo) it grabs and I can move it around but it doesn't release it. And console says TypeError: 'warn' called on an object that does not implement interface Console. Using Firefox 48.0.2 on Mac OS.

**Comment by artf** [comment]
Hi @phil1995 if you're talking about elements like `input`, `textarea`, `select`, etc. you have to drop them inside a `Form` component. This is how are implemented in [grapesjs-plugin-forms](https://github.com/artf/grapesjs-plugin-forms), but you can extend them and change this behaviour if it's what you want. 
For the `warn` issue try to update your Firefox
