### ISSUE TITLE
How to check a component or element is present in canvas or not

### ISSUE THREAD

**Issue by Indhumathi2016** [artf/grapesjs#2401]
I have been trying to enable a checkbox in trait on load, when a element is present in canvas but unfortunately i don't know how to check the element is present or not, i'm trying the following code in onRender() method

const canvasElement = editor.DomComponents.getWrapper();
  let isGdprEnabled = false;
  if (canvasElement.getEl().getElementById('gist-gdpr')) {
    isGdprEnabled = true;
  }

when i tried the above code, i got error "getElementById is not a function" if i used getElementsByClassName it return the HtmlCollection but when i trying to get the length of HtmlCollection it returns 0, but actually there is one element inside the HtmlCollection.
Is there any other way to do it ?, pls help me in this.

Thanks

**Comment by pouyamiralayi** [comment]
Hi @Indhumathi2016  you can use [find method](https://grapesjs.com/docs/api/component.html#find).

```
const wrapper = editor.getWrapper()
const el = wrapper.find('#gist-gdpr')[0]
```
cheers!

**Comment by Indhumathi2016** [comment]
@pouyamiralayi 
It's working fine when i do like this

editor.on('load', () => {
const wrapper = editor.getWrapper()
const el = wrapper.find('#gist-gdpr')[0]
});

Thanks
