### ISSUE TITLE
Question: how to observe children changes in component

### ISSUE THREAD

**Issue by scottccoates** [artf/grapesjs#2404]
Is there an easy way to subscribe/listen to changes in the components/children of my custom component type? Perhaps an event I can subscribe to? Something like `change:content`?

I want to add traits to children of my `container` component. If the children leave the container, the traits should disappear.

I can think of 1 workaround. Something like:
```javascript
// in the view
this.el.bind("DOMSubtreeModified",function(){
  alert('changed');
});
```

**Comment by pouyamiralayi** [comment]
> Is there an easy way to subscribe/listen to changes in the components/children of my custom component type?

@scottccoates you can subscribe this way:
```
init(){ // inside your model
    this.listenTo(this.components().at(0),'change:prop-name', handler)
}
```
cheers!

**Comment by scottccoates** [comment]
@pouyamiralayi thanks. I need to watch for children leaving/entering my component. I'm not sure what you supplied will help or am I missing something?

**Comment by pouyamiralayi** [comment]
@scottccoates this might help:
```
 editor.on('component:add', model => console.log(model.parent().get('custom-name')))
 editor.on('component:remove', model => console.log(model.parent().get('custom-name')))
```
cheers!

**Comment by DevLinh** [comment]
> 

thank you
you help me !

**Comment by divya-pidugu-1007933** [comment]
how to handle events of child elements in custom component, like  if  table is my custom components i want to do something on mousehover of table column head
