### ISSUE TITLE
[QUESTIONS] ckeditor is not initialized when replace trait text

### ISSUE THREAD

**Issue by fmr411** [artf/grapesjs#2405]
why when i change the ckeditor trait text it is not initialized
my trait
<pre>
domComps.addType('text',{
		model: dModel.extend({
		  defaults: Object.assign({}, dModel.prototype.defaults, {
			traits: [
			 {label:"Font Size", type:"text_fontsize"} 
			  ],
		  }),
		},
		{
		  isComponent: function(el) {
			 if (el.getAttribute && "text" == el.getAttribute("data-gjs-type")) return {type: "text"}
		  },
		}),
		view: dView,
	});
</pre>

there is no ckeditor class in the component
![Screenshot_3](https://user-images.githubusercontent.com/15244481/68734062-7bd22d00-060b-11ea-962d-86366acad007.png)

**Comment by artf** [comment]
As you're still using the old API definition (which is quite an error-prone) I recommend reading first the documentation about [Component](https://grapesjs.com/docs/modules/Components.html) then probably you'll find the issue

**Comment by fmr411** [comment]
or is there another way to add trait (for text) so that ckeditor can work

**Comment by artf** [comment]
In the documentation you can see how to extend other components
