### ISSUE TITLE
Include href property for a widget

### ISSUE THREAD

**Issue by promodnl** [artf/grapesjs#2406]
Hello,
##Can anyone help me with the href property for any widget??

- I want to have the href property for a widget. So how can i add it.

**Comment by pouyamiralayi** [comment]
Hi @promodnl  you must define a [trait](https://grapesjs.com/docs/modules/Traits.html#add-traits-to-components) for your component.

**Comment by promodnl** [comment]
Hi @pouyamiralayi thank you for your response......
