### ISSUE TITLE
Event listener for undo?

### ISSUE THREAD

**Issue by kickbk** [artf/grapesjs#2408]
I am listening for a component delete and move with `removed()` and `sorter:drag:end`.
One last way (I hope) that I see the component move is by undo-ing a move. I need to listen to that event. Is there an event listener for undo?

**Comment by pouyamiralayi** [comment]
@kickbk to my knowledge there is no such event, but i guess you can catch it by listening to ``component:add`` event.
cheers!

**Comment by artf** [comment]
We actually support [`undo`/`redo` events](https://grapesjs.com/docs/api/editor.html#available-events)

**Comment by kickbk** [comment]
@artf I tried to use the undo event, but it doesn't contain what component was last changed in position. What I mean is that if I recently moved component from point A to B, I want to track the event of that component moving back from point B to A when undoing.
How do I do that?

**Comment by artf** [comment]
`update` is just a generic event.

> What I mean is that if I recently moved component from point A to B, I want to track the event of that component moving back from point B to A when undoing.
How do I do that?

When you're using the Sorter (not in absolute mode) you can use `sorter:drag:start`, `sorter:drag`, `sorter:drag:end` but those are not part of public API so I can't promise they will work consistently

**Comment by kickbk** [comment]
If I move a component and then `undo` which makes the component move back, the` sorter:drag event` is not triggered.
Obviously, something changes, so there must be a way to detect the change in position of a component when undoing. That is all I am asking. Or in pseudo code:

```
editor.on('some:position:change:event:when:undoing', (targetCollection) => {
	console.log("moved >>", targetCollection)
});
```

**Comment by artf** [comment]
I think, currently, the only possible way to track those changes is by using `component:update:components` event which will pass the added/removed component
