### ISSUE TITLE
Table widget with a popUp message to accept the rows and columns.....

### ISSUE THREAD

**Issue by promodnl** [artf/grapesjs#2409]
Hi...

- Can anyone please help me with the table widget.
- How can I have a popUp on the drag and drop of the widget.....which will accept the no. of rows and columns.
- Then get that no of rows and columns for that table in the editor.

It would be a great help.
Thanks in advance!!!

**Comment by artf** [comment]
Try to read the [Getting Started guide](https://grapesjs.com/docs/getting-started.html), it more or less recaps your request. The only thing that is up to you is what to show in the Modal (eg. inputs UI)
