### ISSUE TITLE
[bug]: grapesjs-preset-webpage form css is not working in chrome

### ISSUE THREAD

**Issue by Ramkumar-Murugesan** [artf/grapesjs#2412]
I installed the grapesjs-preset-webpage using its npm. when I drag and drop the form its CSS is not working.

![Selection_022](https://user-images.githubusercontent.com/33427536/68861883-6c89d700-0712-11ea-9f02-9603935b5fb1.png)

In the above screenshot. the css is not working exactly that what we have in grapesjs webpage.

my grapesjs code

```
editor = grapesjs.init({
      container: '#gjs',
      plugins: ['gjs-preset-webpage'],
      pluginsOpts: {
        'gjs-preset-webpage': {
          // options
        }
      },
      components: '<div class="txt-red">Hello world!</div>',
      style: '.txt-red{color: red}',
      styleManager: {
        clearProperties: 1
      }
    });
```

**Comment by artf** [comment]
CSS is not included in this case, if you want you can copy the one you see in the demo [here](https://github.com/artf/grapesjs/blob/0276220d5863aaac3f723238a70939980cf206ca/demo.html#L750)
