### ISSUE TITLE
Your document like shit just override it!

### ISSUE THREAD

**Issue by thieuanh1995hn** [artf/grapesjs#2414]
https://grapesjs.com/docs/getting-started.html#style-manager

- Hard to look.
- Hard to copy paste.
- Quite hard to get it

**Comment by artf** [comment]
The help is welcome 👍

**Comment by thieuanh1995hn** [comment]
Find a newbie to read all your document and ask him .
It's very suck. May be you can not reach it just because you created it .

**Comment by artf** [comment]
Indeed I'm asking for help
