### ISSUE TITLE
Editor is not defined: When I import grapejsjs in react

### ISSUE THREAD

**Issue by sdrebel** [artf/grapesjs#2415]
Hi @artf ,

I'm importing grapesjs in React and getting the error editor not defined when we add dragMode in the configuration. 
I'm not getting this issue when I downloaded the package from dev version.

Version is 0.15.8

If  set using window.editor it works, but is there any alternative way or fix?

**Comment by pouyamiralayi** [comment]
Hi @sdrebel this [project](https://github.com/beepsoft/grapesjs-react-component-example) is a good reference on how to use grapesjs inside react.
cheers!

**Comment by artf** [comment]
> I'm not getting this issue when I downloaded the package from dev version.

The issue with the not defined editor [is fixed](https://github.com/artf/grapesjs/pull/2371) in dev and will be released in the next version

> If set using window.editor it works, but is there any alternative way or fix?

No, for now, the only solution is to have editor globally available
