### ISSUE TITLE
Is there an api or function to insert a value in a data-attribute in the canvas?

### ISSUE THREAD

**Issue by CoCreator-Frank** [artf/grapesjs#2418]
Hey Grapes Community!
I created a custom trait select  field that fetches options from our db for <a> components... when <a>(link) is clicked in canvas, component settings displays and our select field is rendered... 

I am looking for a solution to pass the selected value from our custom select field to the canvas.
And to get value in canvas to insert in custom select field when component is clicked in canvas. 

Thanks in advance

**Comment by artf** [comment]
Hi @CoCreator-Frank I think the [Trait](https://grapesjs.com/docs/modules/Traits.html) docs page has already the answer to your questions (especially when we explain how to [define a custom one](https://grapesjs.com/docs/modules/Traits.html#define-new-trait-type)). 
[Here](https://grapesjs.com/docs/modules/Traits.html#integrate-external-ui-components), for example, when you change the slider the value is passed to the component via `onEvent` and on `onUpdate` it takes the value from the component and passes it back to the slider
