### ISSUE TITLE
Center Components

### ISSUE THREAD

**Issue by ruiJorge** [artf/grapesjs#242]
Hello guys, i'm trying to create a behaviour for the components, to center or leave them where i prefere, by dragging to the desire position.
Any idea how can i do it?

Imagine this ideia .... i create a button and i want to position it where ever i want, inside, for example, a section .... i want to drag and drop it on the position i want.

I'm stuck with it .....

Thanks.

**Comment by artf** [comment]
Hi @ruiJorge what you're asking is probably a `Designer mode` (eg. like the Wix builder), it's already on the [Roadmap](https://github.com/artf/grapesjs/issues/74) but still in development
