### ISSUE TITLE
[BUG] Number Trait Type Adds Attributes to Element

### ISSUE THREAD

**Issue by brentonkelly1982** [artf/grapesjs#2421]
Working Example: https://codepen.io/brenton-kelly/pen/wvvOgLN

On the latest versions:
https://unpkg.com/grapesjs
https://unpkg.com/grapesjs/dist/css/grapes.min.css

I created a grid component where the user will set the number of columns and the gutter via trait manager. When I use the "number" type for the traits, my "updateModel" method is never fired from my listener and instead, the traits are added to the csGrid element in the canvas DOM as attributes. When I change the trait type to "text", only my method is called as expected.

**Comment by artf** [comment]
You forgot `changeProp: 1` in your traits

**Comment by brentonkelly1982** [comment]
Thank you!
