### ISSUE TITLE
[Questions]custom traits is not saving in Remote storage manager 

### ISSUE THREAD

**Issue by Ramkumar-Murugesan** [artf/grapesjs#2425]
I added more traits from the default input traits. but that traits are not saving in the grapesjs JSON metadata. 

  ```
 storageManager: {
                type: 'remote',
                autosave: false,
                autoload: false,
                stepsBeforeSave: 1,
                contentTypeJson: true,
                urlStore: ''http://localhost:8009/template/save"
            }
```

the above is my storage configuration in grapesjs init function.

![image](https://user-images.githubusercontent.com/33427536/69521323-b2e9fc00-0f84-11ea-99dd-25489b7ee25b.png)

the above image shows that I have custom traits called entity and its field after I saved and come back that those traits are not shown even though the name values also not showing in the traits name input box as shown in below images:

![image](https://user-images.githubusercontent.com/33427536/69521445-fe9ca580-0f84-11ea-9439-a22c9ae04516.png)

**Comment by artf** [comment]
> I added more traits from the default input traits. but that traits are not saving in the grapesjs JSON metadata

Traits shouldn't be stored, are not extensions of your Components but just a way to update your Components' props/attributes. The problem probably because you're not following the [first rule](https://grapesjs.com/docs/modules/Components.html#define-custom-component-type)
