### ISSUE TITLE
[FEATURE REQUEST] Add toolbar redraw functionality

### ISSUE THREAD

**Issue by senchden** [artf/grapesjs#2427]
If a selected model toolbar is being changed dynamically (adding a button, removing a button, etc.), the change is not being reflected visually unless the whole component is being redrawn. I think it would be nice to have a capability to see the change in toolbar property being rendered visually (automatic or manual).

**Comment by artf** [comment]
Closing this as the update of the toolbar is already in place
```js
const selected = editor.getSelected();
selected.set('toolbar', selected.get('toolbar').splice(1))
```
