### ISSUE TITLE
not abled to when cmd + z pressed & can we disable cmd + z completely from editor?

### ISSUE THREAD

**Issue by Indhumathi2016** [artf/grapesjs#2430]
Hi,

I can't able to track cmd + z pressed in anywhere since i want to perform some actions when undoing changes, i have acheived that with undo manager when i click on undo button but i can't do with cmd + z, is there any way to do this?

Or i just want to restrict the ctrl + z option since have undo button in editor itself, is that possible?

Thanks

**Comment by artf** [comment]
You can track [`undo/redo`](https://grapesjs.com/docs/api/editor.html#general) events and managing shortcuts (eg. in your case, removing default one) with [Keymaps API](https://grapesjs.com/docs/api/keymaps.html)
