### ISSUE TITLE
Social Blocks

### ISSUE THREAD

**Issue by adityaMurarka** [artf/grapesjs#2431]
Hi guys,
I am trying to include social elements blocks in my project. I am already using gjs-preset-webpage plugin for basic blocks. I want to give the user the option of providing the social blocks as used in gjs-mjml. Is there any way to import the plugin from mjml preset or any other way to provide multichoice social elements.
Attaching the screenshot for the demo of mjml preset of the plugin.

![Screenshot from 2019-11-27 17-19-02](https://user-images.githubusercontent.com/50452256/69721386-c048e700-113a-11ea-8ec1-53331e18c503.png)

Thanks in advance.

**Comment by artf** [comment]
No, you can't mix those components... Just [read the documentation](https://grapesjs.com/docs/modules/Components.html) and create a new one
