### ISSUE TITLE
Styles by ID in components 

### ISSUE THREAD

**Issue by edwinjoel1984** [artf/grapesjs#2435]
How do I make the styles of the components I take them by id and not by class

**Comment by artf** [comment]
You can toggle classes, this will change the style selector
![Schermata 2019-11-30 alle 00 12 32](https://user-images.githubusercontent.com/11614725/69892469-00a89080-1306-11ea-811b-f7282d8900c3.png)

**Comment by edwinjoel1984** [comment]
The main problem that i have is I'm trying to do a resize in a component that I made, but if I have Two Components equals, when I do the resize one of them the other do the same resize. So, I think that I would need manage the style of them by id and not by class.

This is my code: 
`const buttonComponent = {
    name: "button-bk",
    data: {
      id: "button",
      label: `Button`,
      category: "Basic Components",
      draggable: true,
      content: `<button class="btn-builder" data-gjs-draggable=".cell" data-gjs-resizable='{"tl":0,"tc":0,"tr":0,"cl":0,"cr":1,"bl":0,"br":0,"minDim":1,"bc":0,"currentUnit":1,"step":0.2}' data-gjs-name="Button">Send</button>`,
    },
  };
editor.BlockManager.add('button', buttonComponent);
`
View Example https://cl.ly/c4bfaf626adc
