### ISSUE TITLE
[QUESTION] Add more video provider

### ISSUE THREAD

**Issue by umerrinayat** [artf/grapesjs#2437]
Thank you @artf I'm using grapesjs in my project and it really help us out to do amazing stuff. I'll share it with you once the whole project completed (quite big project).

[Question]
Is it possible to add more video providers in grapesjs? Currently I'm able to use these 

`
 { value: 'so', name: 'HTML5 Source' },
          { value: yt, name: 'Youtube' },
          { value: ytnc, name: 'Youtube (no cookie)' },
          { value: vi, name: 'Vimeo' }
`

I want to add few more like twitch and google drive public video links. I don't want to update **"ComponentVideo.js"** file. 
Any help will be appreciated. Thanks you

**Comment by artf** [comment]
Hi @umerrinayat you just need to [extend the video component](https://grapesjs.com/docs/modules/Components.html#extend-component-type)

**Comment by Mirna-Nasrallah** [comment]
I kinda have the same question now, did you figure out the right way to add a provider?
