### ISSUE TITLE
How to install everything like the demo with all the plugins? [Not issue]

### ISSUE THREAD

**Issue by herboratory** [artf/grapesjs#2439]
Hello, everyone!

I know my question is highly possibly stupid to most of experts here. I am new to making website and I am building a web app on my own with Django and by accident I found that I can use GrapesJS to deal with the frontend. I don't really need fancy thing but just need to get something like the demo with all the plugin functions so that I can work on the frontend. 

I have been working on, struggling and confusing with the document since I have no idea where to put those codes (it should be looked like the demo after finishing, I suppose?) and put the plugins in there. Would anyone give me some directions or tell me what to do?

Many thanks!

**Comment by pouyamiralayi** [comment]
> get something like the demo

if you want the exact thing as demo, the source is [here](https://github.com/artf/grapesjs/blob/53cfe888a0ee5d49c43cd4e3fa5daf0b55f8277c/demo.html)

>  put the plugins in there

please see this [thread](https://github.com/artf/grapesjs/issues/2382)
cheers!
