### ISSUE TITLE
custom competent <template> missing inner html when creating a block with it

### ISSUE THREAD

**Issue by aryeharmon** [artf/grapesjs#244]
i have a custom component "template" that when i create a block out of it, example:

`<div><template><div>SOME TEXT</div></template></div>`

when i drag it to the page i will only get:

`<div><template></template></div>`

This only happens with a with this specific component.

**Comment by artf** [comment]
Hi @aryeharmon `<template>` is a particular HTML5 tag which behaves in a different way https://developer.mozilla.org/en-US/docs/Web/HTML/Element/template

**Comment by aryeharmon** [comment]
@artf i am trying to create an AMP builder, and need to use that component. how do i do so?

**Comment by artf** [comment]
Maybe something like this
```js
domc.addType('template', {
      model: defaultModel.extend({}, {
        isComponent: function(el) {
          if (el.tagName == 'TEMPLATE') {
            // as template.children will return an empty array the traverser
            // will skip all nodes, therefore attach them as a string (they 
            // will be processed later)
            return {type: 'template', components: el.innerHTML}
          }
        }
      }),
      view: defaultView.extend({
        // '<template>' can't be shown so in canvas use another tag
        tagName: 'div'
      }),
    });
```

**Comment by aryeharmon** [comment]
@artf does not work.

**Comment by aryeharmon** [comment]
@artf Works like a charm

**Comment by aryeharmon** [comment]
@artf works like a charm thanks

**Comment by aryeharmon** [comment]
@artf this fix no longer works with latest version
