### ISSUE TITLE
Resize by class :(

### ISSUE THREAD

**Issue by edwinjoel1984** [artf/grapesjs#2440]
The main problem that i have is I'm trying to do a resize in a component that I made, but if I have Two Components equals, when I do the resize one of them the other do the same resize. So, I think that I would need manage the style of them by id and not by class.

This is my code: 
`const buttonComponent = {
    name: "button-bk",
    data: {
      id: "button",
      label: `Button`,
      category: "Basic Components",
      draggable: true,
      content: `<button class="btn-builder" data-gjs-draggable=".cell" data-gjs-resizable='{"tl":0,"tc":0,"tr":0,"cl":0,"cr":1,"bl":0,"br":0,"minDim":1,"bc":0,"currentUnit":1,"step":0.2}' data-gjs-name="Button">Send</button>`,
    },
  };
editor.BlockManager.add('button', buttonComponent);
`
View Example https://cl.ly/c4bfaf626adc

_Originally posted by @edwinjoel1984 in https://github.com/artf/grapesjs/issues/2435#issuecomment-560447001_

**Comment by edwinjoel1984** [comment]
@artf this is the problem

**Comment by ramusesan** [comment]
even i am facing the same issue its probably issue with precedence, assume incase i have id and class for same element i.e **<table id="myId" class="myClass"> ..... </table>** and trying to resize a table then styles are applying on .myClass not #myId

why precedence is more for class than id 

how to fix 

live demo here :
https://stackblitz.com/edit/react-mcv9vz

**Comment by pouyamiralayi** [comment]
@ramusesan  @edwinjoel1984 your issues is because of the shared selectors. similar issue [here](https://github.com/artf/grapesjs/issues/2368).
for the solution i suggest this [thread](https://github.com/artf/grapesjs/issues/404).
cheers!

**Comment by ramusesan** [comment]
@pouyamiralayi  what you mean of the **shared selectors**,  if am using same class on both elements then we can say as that **class** is shared .  
but here i am using id also right along with class name 
i.e 
`<table id="myId" class="myClass"> ..... </table>`
ID should take more precedence than class 
but here class taking more precedence than id

**Comment by artf** [comment]
@ramusesan @edwinjoel1984 Already [replied here](https://github.com/artf/grapesjs/issues/2435#issuecomment-559893061) what to do, you just have to tell the editor to style only the component and not the class...
