### ISSUE TITLE
[QUESTION] How to completely disable badges on hover?

### ISSUE THREAD

**Issue by BobMerks** [artf/grapesjs#2441]
Hello,

I've been looking to completely disable the badges that appear on hover, but I can only seem to disable it fro the wrapper with the following code:
`
 domComponents: {
        wrapper: {badgable: false}
    },
`

Is there a similar way to completely disable them?

Thanks in advance!

**Comment by artf** [comment]
Probably in your case the easiest solution would be to hide it via CSS
```css
.gjs-badge {
    display: none !important;
}
```

**Comment by fredrickreuben** [comment]
You can use canvas: {
                    customSpots: { hover: true },
                },
