### ISSUE TITLE
Set charset of canvas or grapesjs to UTF-8

### ISSUE THREAD

**Issue by MariusDK** [artf/grapesjs#2444]
Hey @artf ,

How to get UTF-8 encoding from canvas in angular 8.
I need this because i encode btoa from frontend and send to server. Server use base64 to decode with UTF-8 and special characters like spanish are not recognized by server.

Please help me.

**Comment by artf** [comment]
Hi @MariusDK the iframe in the canvas doesn't use any particular charset so it should depend on the parent page or at least, due to HTML5, be in UTF-8
FYI, if you need to get the iframe element (for any kind of manipulation) you can do this `editor.Canvas.getFrameEl()`
