### ISSUE TITLE
Style Same Class Components

### ISSUE THREAD

**Issue by bungambohlah** [artf/grapesjs#245]
Hello @artf i don't know its bug or not, but can i style just one selected component and the others component with same class will not be affected as well ?
I currently use grapesjs and combine it with materializecss framework as a design, and of course some components like button in the materializecss framework need class ```btn``` and ```waves-effect``` as button effect. This picture will explain everything

This is with the red block show components with the same class, and style for alignment is none
![image](https://user-images.githubusercontent.com/19922064/29654777-ca759508-88d8-11e7-9353-375f12c6d61e.png)

When i try to change aligntment to right, the other components with same class will be affected
![image](https://user-images.githubusercontent.com/19922064/29654931-6d714194-88d9-11e7-95d8-fbea8ef164bd.png)

Can you help me with this issue?
Sorry for my bad english, and thank you very much for your help

**Comment by artf** [comment]
@bungambohlah you can add a new class on the element (eg. `btn-right`) or just turn off all classes by clicking on their checkboxes, this will affect the style manager selection
