### ISSUE TITLE
[Question] Browsers support

### ISSUE THREAD

**Issue by hudy1** [artf/grapesjs#2450]
Hi,

Which browsers are supported by GrapesJS? I couldn't find information about it on website / docs. I need to know it before adding GrapesJS to company project which supports i.a. IE 11 and Safari.

Thanks :)

**Comment by artf** [comment]
You can see it here https://github.com/artf/grapesjs/blob/041904f1f3364b05b5908f0da2a0e2460a292aa4/package.json#L69-L73
