### ISSUE TITLE
Understanding of how style manager implements and handle CSS

### ISSUE THREAD

**Issue by adityaMurarka** [artf/grapesjs#2451]
### Issue 1
I made a page using grapesJS and then I exported the page and then imported it back. On importing whatever styles I had applied I am not able to see the styles in the style manager.

### Issue 2
Due to issue 1 on applying new styles since I do not see what earlier styles I applied, in some cases, I can see them in the view but on deploying the page I am not seeing the changes done.
(p.s. I think probably it's due to CSS conflicts. 2 or more classes are being applied and both of them are trying to change the same attribute, thus choosing one).
So on what basis is class is being chosen and is there any way to resolve it.

### Issue 3
So by default grapes supports 3 views. Desktop, tablet, and mobile. So on changing views I believe I can different CSS for all different views. So I tried implementing some CSS on different views. In some cases, the changes could be seen as expected on changing views, but in some cases, it is changing the complete CSS irrespective of the view. 
So is there any logic to it? On what things different stylings can be applied and can be maintained differently for other views and what are attributes can be changed like this?

Any help or clarity will be appreciated.

Thank You in advance.

**Comment by artf** [comment]
> Issue 1 & Issue 2

Please provide the exact steps on how you export and import the template

> Issue 3

Sorry but "in some cases" doesn't help here. You have to explain exactly what you're doing and what you expect

**Comment by adityaMurarka** [comment]
>  Issue 1 & Issue 2
>Please provide the exact steps on how you export and import the template

By using the default option provided in grapesJS to export the HTML and CSS and importing using the import button on the grapesJS toolbar.

> Issue 3
> Sorry but "in some cases" doesn't help here. You have to explain exactly what you're doing and what you expect

Is there any documentation about how to apply different CSS for the different views. Does it works completely like how media query works?
