### ISSUE TITLE
[Bug] Text disappears after component is deselected after two moves with selected text

### ISSUE THREAD

**Issue by senchden** [artf/grapesjs#2452]
Steps to reproduce:
1. Select all text in a component
2. Move the component
3. Select all text again
4. Move the component again
5. Deselect the component

Expected result:
Text remains

Actual result:
Text disappears

Reproducible in a web page demo, version 0.15.9.

See attached screencast:
![gjs-text-drag-disappear](https://user-images.githubusercontent.com/31250983/70540827-37807100-1b66-11ea-90cb-6a0dd195b512.gif)

**Comment by artf** [comment]
Good catch, thanks
