### ISSUE TITLE
Not able to use colors(TextColor,BGColor) and styles(Font,FontSize) in toolbar

### ISSUE THREAD

**Issue by adityaMurarka** [artf/grapesjs#2453]
Hi artf,

I am adding colors and styles section in toolbar. I am able to see other sections but not colors and styles in the editor.

"gjs-plugin-ckeditor": { position: "center", options: { toolbar: [ { name: 'styles', items: ['Font', 'FontSize'] }, { name: 'basicstyles', items: ['Bold', 'Italic', 'Strike', '-', 'RemoveFormat'] }, { name: 'links', items: ['Link', 'Unlink'] }, { name: 'colors', items: ['TextColor', 'BGColor'] } ] } },

Am I doing anything wrong in the above code. Can you help me out with this? @artf 

Thanks in advance.

**Comment by artf** [comment]
This is not related to the GrapesJS core library and probably not even the plugin. Check the CKEditor documentation please (you might missing some plugin)
