### ISSUE TITLE
grapesjs-preset-newsletter returns undefined

### ISSUE THREAD

**Issue by chezhiane** [artf/grapesjs#2457]
I am using the bellow versions.

 "grapesjs": "^0.14.62",
    "grapesjs-preset-newsletter": "^0.2.20",

Believe these are the latest versions available in npm . I am getting the undefined error.
See in your earlier posts that the version was incorrect, but mine i believe is current.

**Comment by pouyamiralayi** [comment]
@chezhiane you are not using latest version. link to latest version:
[Download](https://grapesjs.com/docs/#download)
