### ISSUE TITLE
FEATURE REQUEST - Add Color Variables and typography styleing

### ISSUE THREAD

**Issue by aryeharmon** [artf/grapesjs#246]
lets say i want to style a h2 tag not the class, all h2 tags. not possible to do so now.
also would be awesome to have color variables https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_variables

**Comment by artf** [comment]
Thanks for your requests @aryeharmon I already thought about tags selection in style manager but decided to avoid it as class-based only selection is much easier to understand for non-dev people. About CSS variables, are good for developers but in this kind of application I think it'll just make stuff more complex, I'd prefer instead something like theme changer which simply switches color values inside CSS rules (maybe as a plugin).
