### ISSUE TITLE
Convert & to &amp; < to $lt; and save html data 

### ISSUE THREAD

**Issue by suchiitsme** [artf/grapesjs#2460]
Im using editor and generating a html string and saving it to a file. But before saving I have to encode all the &, <, > characters.

Please Help

**Comment by pouyamiralayi** [comment]
@suchiitsme 
```
 editor.on('storage:start:store', o => {
        o.html = o.html.replace(/&/gi,'&amp')
        o.html = o.html.replace(/</gi,'&lt')
        o.html = o.html.replace(/>/gi,'&gt')
  })
```
cheers!

**Comment by artf** [comment]
In the next release, we'll escape HTML characters https://github.com/artf/grapesjs/pull/2446
