### ISSUE TITLE
How to apply style or trait to parent or child element of selected component

### ISSUE THREAD

**Issue by obrazkow** [artf/grapesjs#2461]
For example i have component image that wrapped in div.
I want to style image with multiple properties(horizontal position, border-radius, etc)
When update horizontal position, need to update current element - div
When update border-radius, need to update child element - img.
Also i have such problem with Trait, i cannot update src for img.
I added listener at Trait and on change i apply value on img, then div and img had src together, but it's bad solution.
`
export default (editor) => {
    editor.TraitManager.addType('image', {
        onEvent({ elInput, component, event }) {
            component.view.el.querySelector('img').src = elInput.value
        },
    });
}
`
 Can you advice me solution ?

**Comment by pouyamiralayi** [comment]
@obrazkow
You can access the parent like this: `component.parent();`
and for the children: `const collection = component.components();`

> Also i have such problem with Trait, i cannot update src for img.

```
 editor.DomComponents.addType('image', {
            model: {
                defaults: {
                    traits: ['src']
                }
            }
        })
```
cheers!

**Comment by obrazkow** [comment]
@pouyamiralayi 
that's exactly what I did, but with such solution selected component have attribute or style that need only for child component.

**Comment by obrazkow** [comment]
@pouyamiralayi 
yesterday i rewrite src trait 
`export default (editor) => {
    editor.TraitManager.addType('text', {
        onEvent({ elInput, component, event }) {
            component.attributes.components.at(0).set({'src': elInput.value})
        },
    });
}`
and this works fine, but i don't like this solution, because i cannot set attribute directly to img element and attributes duplicate in div and img elements

**Comment by obrazkow** [comment]
I overrided target element in trait in init method and this works fine. src sets only in img tag, but what do with style don't know yet

```
export default (editor) => {
    editor.TraitManager.addType('image', {
        createInput({ trait }) {
            const el = document.createElement('input');
            el.type = 'text';
            el.value = trait.target.get(trait.attributes.name) || '';

            return el;
        },

        init() {
            this.target = this.target.attributes.components.at(0);
            this.model.target = this.model.target.attributes.components.at(0);
        },

    });
}
```

**Comment by pouyamiralayi** [comment]
@obrazkow 
```

        /*Custom Trait*/
        editor.DomComponents.addType('custom-type', {
            model:{
                init(){
                    this.on('change:src', this.handleSrc)
                },
                handleSrc(){
                    this.components().at(0).addAttributes({src:this.get('src')})
                },
                defaults:{
                    tagName:'div',
                    src:'',
                    traits:[{
                        name:'src',
                        changeProp:true
                    }],
                    components:{
                        type:'image'
                    }
                }
            }
        })
```
cheers!

**Comment by obrazkow** [comment]
@pouyamiralayi 
With your solution trait don't know src value and input will be empty.
What do you think about my solution with override target in init method? 
```
export default (editor) => {
    editor.TraitManager.addType('image', {
        createInput({ trait }) {
            const el = document.createElement('input');
            el.type = 'text';
            el.value = trait.target.get(trait.attributes.name) || '';

            return el;
        },

        init() {
            this.target = this.target.attributes.components.at(0);
            this.model.target = this.model.target.attributes.components.at(0);
        },

    });
}
```

In this solution i see issue only with responsibility. Trait know too much about DomComponent structure

**Comment by pouyamiralayi** [comment]
> With your solution trait don't know src value and input will be empty at init editor phase.

i do not understant what you are talking about!

> What do you think about my solution with override target in init method

you are treating a very simple use case with an advanced solution, and i do not personally recommend defining custom trait for a case like this.
cheers!

**Comment by obrazkow** [comment]
If someone faced with such problem, i found solution. Maybe it's not best solution, but another i didn't find

I override base types in StyleManager
```
export default (editor, fromType, newType) => {

    const sm = editor.StyleManager;
    const type = sm.getType(fromType);

    const view = type.view;

    sm.addType(newType, {
        model: type.model,
        view: view.extend({
            init() {
                const customComponent = this.model.get('customComponent');
                if (typeof customComponent === 'function') {
                    this.currentSelectedTarget = customComponent(this.em.getSelected())
                }

                if (view.prototype.init) {
                    view.prototype.init.apply(this, arguments);
                }
            },

            onRender() {
                if (view.prototype.onRender) {
                    view.prototype.onRender.apply(this, arguments);
                }

                this.model.set('value', this.getTargetValue());
            },

            getTargetValue() {
                if (this.currentSelectedTarget) {
                    const value = this.currentSelectedTarget.getStyle()[this.model.get('property')];
                    
                    return fromType === 'integer' ? parseInt(value) : value;
                }

                return view.prototype.getTargetValue.apply(this, arguments);
            },

            getTarget() {
                if (this.currentSelectedTarget) {
                    return this.currentSelectedTarget;
                }

                return view.prototype.getTarget.apply(this, arguments);
            }
        })
    });
}
```
```
import customValue from "path/to/customValue";

export const RADIO_CUSTOM_VALUE_TYPE = 'radioCustomValue';
export const INTEGER_CUSTOM_VALUE_TYPE = 'integerCustomValue';

export default editor => {

    customValue(editor, 'radio', RADIO_CUSTOM_VALUE_TYPE);
    customValue(editor, 'integer', INTEGER_CUSTOM_VALUE_TYPE);

}
```

On each block i have specific sectors(my requirements), 
On component:selected event i add sector to StyleManager

For example, image shape structure.

in Property i added customComponent function, that gets selected component and must return component
```
import {RADIO_CUSTOM_VALUE_TYPE} from "path/to/const";

export default (styleManager, customComponent = void 0) => {
    return {
        addSector: () => {
            styleManager
                .addSector('image-shape',{
                    name: 'Style',
                    open: true,
                    properties: [
                        {
                            name: 'Shape',
                            property: 'border-radius',
                            type: RADIO_CUSTOM_VALUE_TYPE,
                            customComponent,
                            list: [
                                {
                                    value: '0%',
                                    name: '0%'
                                },
                                {
                                    value: '5%',
                                    name: '5%',
                                },
                                {
                                    value: '50%',
                                    name: '50%'
                                }
                            ]
                        }
                    ]
                })
                .off('change:open')
        },
        removeSector: () => {
            styleManager.removeSector('image-shape');
        }
    }
}
```

```
shapeSector = shape(styleManager, component => component.find('img')[0]),
editor.on('component:selected', (component) => {
        if (component.is('image-wrapper')) {
            shapeSector.addSector();
        }
    });

 editor.on('component:deselected', (component) => {
        if (component.is('image-wrapper')) {
            shapeSector.removeSector();
        }
    })
```

I will be glad if this helps someone

**Comment by artf** [comment]
IMHO @obrazkow your approach is way harder to maintain and to think about. I'd stay with @pouyamiralayi [solution](https://github.com/artf/grapesjs/issues/2461#issuecomment-568178570), bouncing properties/styles between components is quite unusual so I'd keep this responsibility only to your root component. 

> With your solution trait don't know src value and input will be empty at init editor phase.

I got what you mean, indeed, in your `init` method you have to take those values from your child and update the prop (`src`) of your root component.
For styling, always in the `init`, I'd try to use listeners (eg. when the border of the root changes, update with those styles the child component)
