### ISSUE TITLE
Not able to implement it with iframe. "CONTAINER" in frame and "BLOCK" outside the frame

### ISSUE THREAD

**Issue by Atmiya735** [artf/grapesjs#2463]
Hello Team,
I m new to grapejs and little bit fresher in JS.

What i have to achieve
=> I have to make display the container in iframe which i m loading for the preview 
=> Blocks section should be out of the ioframe in main page from where i will drag and drop the block within iframe.

Which issue i m facing 
=> if i add the init container in iframe and try to add block section in main page using block manager it is doing. But when i try to drop the block in that container of iframe it is not working.
The same thing will work if i put the block within the iframe itself.

Hope my explanation is better enough to understand the issue.
Please help me out in this.

Thanks in advance.

**Comment by pouyamiralayi** [comment]
@Atmiya735 take a look at this [fiddle](https://codepen.io/artf/full/MQpZPj) which is using custom layout for blocks section.
cheers!

**Comment by Atmiya735** [comment]
Thanks for help, but i want to implement container section in iframe and blocks section  outside of the iframe, and still want to achieve the feature of drag and drop in it. 
Please help me out in this

**Comment by pouyamiralayi** [comment]
@Atmiya735 unfortunately i am not aware of a way to do this.

**Comment by Atmiya735** [comment]
@pouyamiralayi i have checked and they have used both container andblocks in same page there is no use of iframe there. 
https://codepen.io/artf/pen/MQpZPj Once change the view and check the html content, you will get an idea. 
And yes this same thing is achieved in the demo which is given by grapejs. [https://grapesjs.com/demo.html](url).

**Comment by pouyamiralayi** [comment]
@Atmiya735  i understand what you are saying, the thing is that grapesjs canvas is inside an iframe itself, so i do not think that would be even possible.

**Comment by Atmiya735** [comment]
Anyone having any solution for this or have faced this such kind of issue, thenplease help me out.

**Comment by Atmiya735** [comment]
@artf  Will you please help me out in this. I have to add the grapesjs container within my iframe where i m loading the page and i use to make drag and drop there from out of main frame.

Thanks.

**Comment by artf** [comment]
No, I don't think, putting another iframe between blocks and the canvas makes even sense, try to rethink what you're doing.
And please, next time, avoid spamming your posts on other issues...
