### ISSUE TITLE
Problem replacing component in absolute dragMode

### ISSUE THREAD

**Issue by alemenciones** [artf/grapesjs#2464]
I have a problem to replace a componente in the same position (top/left), the new component is always added in the positions top: 0px / left: 0px;

I'm triyng something like this:

```js
const selectedComponent = editor.getSelected();
const coll = selectedComponent.collection;
const at = coll.indexOf(selectedComponent);

var styles = selectedComponent.getStyle() || {};   

coll.remove(selectedComponent);

let newComponent = coll.add(component, {
   fromAddNewComponent: true,
   at: at,
});

newComponent .setStyle(styles);
```

But setStyle() is not working this time...

**Comment by artf** [comment]
The code, more or less, seems ok, be sure to check `styles` contains the position properties (and the component has also the absolute position). If it's not working yet try to create a reproducible demo, please
