### ISSUE TITLE
[BUG] Adding buttons to RTE toolbar in React App causes buttons to be duplicated.

### ISSUE THREAD

**Issue by simplecommerce** [artf/grapesjs#2469]
1. Are you using the latest release (older versions are NOT supported)? 
    * YES, 0.15.9
2. Are you facing the bug with your local copy of GrapesJS or with the current demo?
    * Local copy
      * Are you able to reproduce the bug from the demo?
        * No, not React app.
3. What is the expected behavior?
    * Toolbar buttons should only be added once on load of editor.
4. What happens instead?
    * When navigating away and coming back to the editor, the toolbar buttons are duplicated, as many times as navigation is done.
5. If you're able to reproduce the bug indicate all the necessary steps
Attach screenshots (using KAP/LICEcap), screencasts or live demo
   * https://codesandbox.io/s/react-router-basic-49ki1?fontsize=14&hidenavigation=1&theme=dark
     * Click on the Dashboard link.
     * Double-click on the text to edit, look at the toolbar.
     * Click on another link, except Dashboard, at the top and click back on Dashboard.
     * Double-click to edit the text again.
     * Do it as many times as needed.

Result should be:

Initial look:

![image](https://user-images.githubusercontent.com/31987945/71416835-4e2bcb00-2630-11ea-8c6e-3d6e4af54024.png)

After navigation:

![image](https://user-images.githubusercontent.com/31987945/71416849-5b48ba00-2630-11ea-9ae2-0a1279360d80.png)

**Comment by simplecommerce** [comment]
For now, I have to do `rte.remove` before my `rte.add` so it doesn't duplicate.

**Comment by artf** [comment]
Ok, seems like we don't clear the RTE instance in the `destroy` method... I'll fix it for the next release
