### ISSUE TITLE
How to add multiple page 

### ISSUE THREAD

**Issue by nguyenhiep2906** [artf/grapesjs#247]
Hi all
I want to create multiple page in Grapesjs but i'm not found any solution.Can you help me ?

**Comment by artf** [comment]
Hi @nguyenhiep2906 grapesjs has no concept of pages, but definitely could be added via plugin. Will add this to the Roadmap

**Comment by nguyenhiep2906** [comment]
Hi @artf 
Thank you for your comment,I'll try to create plugin.

**Comment by artf** [comment]
thanks @nguyenhiep2906 it'd be awesome

**Comment by uripre** [comment]
+1 👍

**Comment by tataclassedge** [comment]
hi
any updates on this please

**Comment by rishavs** [comment]
a simple client side router will be amazing!
