### ISSUE TITLE
Mobile device view is not working well.

### ISSUE THREAD

**Issue by Excellent-Developer** [artf/grapesjs#2470]
![image](https://user-images.githubusercontent.com/54437031/71449450-c35de400-2787-11ea-8e59-9fc04b61f836.png)
This is for Desktop
![image](https://user-images.githubusercontent.com/54437031/71449454-e25c7600-2787-11ea-86ab-9ca4e9be376d.png)
This is for Mobile
Please teach me how to solve it.

**Comment by devmohitagarwal** [comment]
@Excellent-Developer what exactly is the problem in the UI? 

If you're suggesting that the button for the device selection don't have the resolutions you need,then you can change that from the config file inside editor forlder.

If you're suggesting that the UI inside the canvas is not auto-aligned according to the smaller device. that is the intended behavior.
The Flow goes like this.
1.You make a page according to the desktop view.
2.you choose the mobile/tablet view you are suppose to again choose the CSS properties appropriate for the mobile/table (it adds media queries for the same.)
