### ISSUE TITLE
DragData extend for other components like div etc

### ISSUE THREAD

**Issue by imranali2045** [artf/grapesjs#2472]
Hi @artf 
How to implement dragData event for custom components(external).I called dragData method on div drag but dataTransfer and content has no information of current drag component.Please help me its urgent thanks.
` this._editor.on('canvas:dragdata', (dataTransfer, content) => {
       console.log('dataTransfer', dataTransfer);
       console.log('content', content);
    });`

**Comment by artf** [comment]
`canvas:dragdata` is meant to be used to enrich the Native D&D support. If for example, you drag into the canvas a video from your desktop and want the editor to understand it correctly, you would do something like this
```js
editor.on('canvas:dragdata', (dataTransfer, result) => {
	if (/* dataTransfer contains a video file */) {
		result.content = { type: 'video', src: '...' }
	}
});
```

**Comment by manuel-84** [comment]
have you managed to do this?
i have problems with dropped text with mjml plugin enabled, it should create a mj-text element, instead it's creating a div
