### ISSUE TITLE
Broken Import when trying to use GEditor

### ISSUE THREAD

**Issue by bumpradar** [artf/grapesjs#2477]
×
Unhandled Rejection (Error): Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

`import React from 'react';
import { GEditor } from 'grapesjs-react'

export default () => {

    return (
        <GEditor />
        
    );
} `

**Comment by pouyamiralayi** [comment]
@bumpradar this issue must be posted here: [grapesjs-react](https://github.com/thanhtunguet/grapesjs-react)
cheers!

**Comment by Ace0611** [comment]
Hi, I am getting this error while trying to import GEditor from grapesjs-react (import GEditor from 'grapesjs-react';):
Error: 'grapesjs-react' does not contain a default export (imported as 'GEditor').

Has anyone resolved this issue?
