### ISSUE TITLE
Error when trying to move cell from row

### ISSUE THREAD

**Issue by obrazkow** [artf/grapesjs#2478]
If try move cell from table on body then appears error

![image](https://user-images.githubusercontent.com/56313520/71551300-c1488f00-29ec-11ea-8638-7c68e16875ee.png)

Also error appears on grapesjs demo https://grapesjs.com/demo-newsletter-editor.html

**Comment by obrazkow** [comment]
Problem in Sorter. 
function dimsFromTarget return empty array, when target element not in draggable list
see 
https://github.com/artf/grapesjs/blob/dev/src/utils/Sorter.js#L644(not found target)
https://github.com/artf/grapesjs/blob/dev/src/utils/Sorter.js#L648(return empty array)

And after this function call getTargetModel with target undefined and appears error
see https://github.com/artf/grapesjs/blob/dev/src/utils/Sorter.js#L449

Maybe need add check on exists target? Can you fix this error or i need to do pull request?

**Comment by artf** [comment]
Can you tell me exactly how to reproduce the error because I don't see any error by dragging off the cell

**Comment by obrazkow** [comment]
First error.
1. Select cell wrapper(see on screenshot) and try drag it
2. In console will appear errors
![image](https://user-images.githubusercontent.com/56313520/71686681-89eb3100-2da4-11ea-9ac2-b5602cb5fe56.png)

For more details i attach link on two video files. When i tried to reproduce, i found another bug. Try select first component for example text and move it and after select cell and try drag it. You'll see that line of destination will be in wrong position

https://dropmefiles.com/wJvVt

**Comment by artf** [comment]
> Maybe need add check on exists target? Can you fix this error or i need to do pull request?

Yeah, it actually doesn't even make sense to continue onMove without the target, I'll take care of it, thanks for the insight

**Comment by obrazkow** [comment]
But is not fixed.
Repeat steps and you will get error Uncaught TypeError: Cannot read property 'indexEl' of undefined.
It can reproduce in your demo
