### ISSUE TITLE
[Suggestion]: Use a shim function for components that use script function (not string)

### ISSUE THREAD

**Issue by ackvf** [artf/grapesjs#2480]
The current approach that converts a component's script to text before placing it in the document is rather limiting. Wouldn't it be possible to use an approach like this, so that the scope is retained?

Put the function in window and use a shim function in the component instead.

_original code:_
```js
var myVar = 'John';

editor.BlockManager.add('test-block', {
...
  script: function () {
    alert('Hi ' + myVar);
    console.log('the element', this);
  },
...
});
```
_follows my suggestion:_

_function (as a function not string) detected, let's use a shim:_

```
globalThis['test-block'] = identifierOfTheTestBlockComponent.script
```

```html
<div id="c764"></div>
<script>
  var items = document.querySelectorAll('#c764');
  for (var i = 0, len = items.length; i < len; i++) {
    (window['test-block'].bind(items[i]))();
  }
</script>
```

originally mentioned in a PR here https://github.com/artf/grapesjs/pull/2479#issuecomment-569628660

**Comment by artf** [comment]
> Wouldn't it be possible to use an approach like this, so that the scope is retained?

No, because you're trying to mix the scope of the editor environment with the one which will be deployed to the final user (which has nothing to do with the editor, he is only able to see the final HTML/CSS/JS).

Try to check out this issue: https://github.com/artf/grapesjs/issues/2181
