### ISSUE TITLE
How do I change the name of the default component?

### ISSUE THREAD

**Issue by andrewryan1906** [artf/grapesjs#2482]
I noticed everywhere in the canvas "Box" is the term for the default container. I'd like to change that

I found the customLabel strategy function on the canvas; that works, but as soon as I implement it, I lose the default behavior for labelling everywhere else in the template designer. Don't want that. 

Really, what I just want to do is change the name of the "default" container so that the badge appears as "Responsive Container."

What's the best way to do that?

Andrew

**Comment by artf** [comment]
You can do it by updating the [i18n](https://grapesjs.com/docs/modules/I18n.html) string
```js
grapesjs.init({
	...,
	i18n: {
		messages: {
          en: {
            domComponents: {
              names: {
                '': 'Responsive Container', // default has an empty key
              }
            }
          }
        }
	}
})
```

**Comment by andrewryan1906** [comment]
Outstanding! Thanks.

**Comment by andrewryan1906** [comment]
Hey... this works, but nulls out all of the other names. How do I override just that name?

**Comment by artf** [comment]
Sorry, to update messages you have to add them via API
```js
editor.I18n.addMessages({
	en: {...}
});
```
