### ISSUE TITLE
Default model names not persisting to local storage

### ISSUE THREAD

**Issue by andrewryan1906** [artf/grapesjs#2483]
When I create a new Dom Component, I give it a name in the "defaults" section, like:

domComponents.addType(''ugly-type-name', {
 model: {
        defaults: {
          tagName: 'component',
          name: 'Foo Bar',   <-----
   
          attributes: {

            'component-id': component.id
          },

          traits: [{}

          ]
        }
      },
```

When the component is dragged on to the canvas, the Foo Bar string shows up as a badge like it should, and the text appears in the Layers panel and everything is good. But when the canvas is persisted to storage, and I refresh the page, the badge now shows the ugly-type-name, and it appears in the layers as well.

What am I doing wrong?

**Comment by pouyamiralayi** [comment]
@andrewryan1906  please define your component type inside a plugin.
cheers!

**Comment by andrewryan1906** [comment]
That works, thanks!
