### ISSUE TITLE
[BUG] Updating a trait resets the component styles

### ISSUE THREAD

**Issue by msantore** [artf/grapesjs#2487]
I'm having an issue with Traits, wondering if this may be a bug.  When I update the fontColor or fontSize trait, the other traits reset. 

**Video:**
https://www.loom.com/share/6a40830699ad4c4590363f2641a07eac

**Code:** https://github.com/msantore/vue-builder/blob/master/src/plugins/materials/components/index.js#L362

GrapesJS Version: 0.15.9

**Comment by pouyamiralayi** [comment]
@msantore i tried to update the fontSize and i got this error:
```
Uncaught TypeError: this.props is not a function
```
in your ``src/plugins/materials/components/index.js`` you are using ``updateFontSize`` like this:
```
let value = this.props().fontSize
```
which should be changed to this:
```
let value = this.get('fontSize')
```
cheers!

**Comment by pouyamiralayi** [comment]
@msantore you are using ``setStyle`` which will override the previous styles. use it like below:
```
link[0].setStyle({ ...link.getStyle(), color: `${value}` });
```
cheers!

**Comment by msantore** [comment]
That fixed it, thanks!

**Comment by artf** [comment]
You can also use `addStyle({ color: `${value}` })` which does the same thing
