### ISSUE TITLE
Form is send when import code

### ISSUE THREAD

**Issue by martcot** [artf/grapesjs#249]
When I use the import code button, the form around grapejs is send. Any idea?

**Comment by artf** [comment]
I used an import only inside demos so I guess you're using some of those presets, in that case just add `type="button"` to the button

**Comment by martcot** [comment]
ok thanks I will do this!

**Comment by martcot** [comment]
ok thanks I'll do this.



<https://mailtrack.io/> Sent with Mailtrack
<https://mailtrack.io/install?source=signature&lang=en&referral=mcote@d-modules.com&idSignature=22>

*---*

*Martin Côté, Directeur technologique*
D-Modules.com <http://www.d-modules.com>
Bureau: (418) 613-0825
*Skype: martyman01*



*Agence d'inbound marketing*


2017-08-25 15:13 GMT-04:00 Artur Arseniev <notifications@github.com>:
