### ISSUE TITLE
How to restict the adding of css property for the gjs-hovered class when the styles are addded

### ISSUE THREAD

**Issue by logeshkrishna0** [artf/grapesjs#2492]

**Comment by logeshkrishna0** [comment]
Hey, i am using the latest version of grapejs, i am trying add a new list component and it works as excepted but i face a issue while adding the style to the list.
The issue i am facing is when i select the li tag, add the style from the style component such as changing the font color, it apply to the "gjs-hovered" class.
I tried this in both local(OS:Ubuntu,BROWSER:Chrome,Firefox,GRAPESSJS:0.14.49)and demo instance it reflect the same.

Expected Behaviour:
The style of the li tag should be added to the class of li tag when the option from style manager is selected.
Outcome:
The style applies to other default grapejs classes such as gjs-hovered or gjs-comp-selected
![Screenshot from 2020-01-03 15-00-41](https://user-images.githubusercontent.com/52228872/71801868-30278700-3082-11ea-9ba9-57a98536acb5.png)
![Screenshot from 2020-01-03 15-00-55](https://user-images.githubusercontent.com/52228872/71801875-33bb0e00-3082-11ea-9c6c-847369ca3bcd.png)
The above image shows the code of the grapesjs

**Comment by logeshkrishna0** [comment]
@artf could you please help me out with this

**Comment by logeshkrishna0** [comment]
@here someone could help me out with this

**Comment by thomas1204** [comment]
I'm also facing the same issue.

**Comment by artf** [comment]
0.14.49 is not the latest version... update it first, if the issue still persists create a live reproducible demo please
