### ISSUE TITLE
Convert rgb/rgba color value to hex code

### ISSUE THREAD

**Issue by prabha-912** [artf/grapesjs#2496]
Hi Folks, 

**Steps I followed:** 
1. Drag the text block. 
2. set the font color. (its in rgb/rgba format)

**What I Expected:** 
Style needs to be updated as like hexa code. (like, #f0f0f0)

I tried to get the particular color update using, ` editor.on('component:styleUpdate:color', function (model) {` . But I could not get the solution. Guide me how to achieve the expected solution. 

Thanks in advance, 
Prabha.

**Comment by pouyamiralayi** [comment]
@prabha-912 
```
    editor.on('component:styleUpdate:color', function (model) {
            console.log(model.getStyle()['color'])
     })
```
cheers!

**Comment by prabha-912** [comment]
It returns undefined for me @pouyamiralayi

**Comment by pouyamiralayi** [comment]
@prabha-912 i tested this on the [demo](https://grapesjs.com/demo) it was fine.

**Comment by artf** [comment]
As the StyleManager can target Components and CssRules you have to find out first what was selected
```js
editor.on('component:styleUpdate:color', component => {
	const sm = editor.StyleManager;
    const model = sm.getModelToStyle(component);
	// the model can be a Component or CssRule
    console.log(model.getStyle()['color'])
})
```
