### ISSUE TITLE
[Bug] Error when trying to move cell from row. 

### ISSUE THREAD

**Issue by obrazkow** [artf/grapesjs#2498]
Bug [#2478](https://github.com/artf/grapesjs/issues/2478) after release still exists.

Repeat steps and you will get error Uncaught TypeError: Cannot read property 'indexEl' of undefined.
It can be to reproduce in your demo

**Comment by artf** [comment]
Ok seems like we have also to fix the `endMove` function

**Comment by artf** [comment]
Nope 🤦‍♂️
Will be fixed in the next release.
thanks @bgrand-ch
