### ISSUE TITLE
Prevent Table cell from automatically resizing on dropping a Text component inside

### ISSUE THREAD

**Issue by AbdiasM** [artf/grapesjs#2499]
I have a Table with say 1 row and 3 cells. When I drag and drop a Text component inside one of the cells, that cell enlarges and occupies the entire width of the table. How can I prevent that from happening and make the Text component take the width of the cell. 
![TableCellResize](https://user-images.githubusercontent.com/18558443/72007538-e607f680-3277-11ea-8963-1cdc409dc365.gif)

**Comment by artf** [comment]
This is how the `<table>` works, you should specify a fixed width to your cells to avoid it
