### ISSUE TITLE
events are not firing in translate DragMode

### ISSUE THREAD

**Issue by ramusesan** [artf/grapesjs#2500]
am using  npm : "grapesjs": "^0.15.10", and dragMode: translate 

added events 

```
editor.on('block:drag', () => {
  console.log('Triggered')
})
```

but this is working only default drag mode, not in translate drag mode.
how get I fix this

**Comment by artf** [comment]
I see it working here https://jsfiddle.net/2gezckxL/

**Comment by ramusesan** [comment]
@artf  no it does'nt working see the Demo below

![image](https://user-images.githubusercontent.com/15937743/72234651-06c3a980-35f4-11ea-80b6-7f156422cf25.png)

**Comment by artf** [comment]
You're dragging a component there, not a block.

**Comment by ramusesan** [comment]
@artf  okay cool  my question is wrong, sorry for that. actually i want listen the Component drag:start and drag-end  .  how can i achieve this one if use :
`editor.on('component:drag', () => {
  console.log('Triggered')
})`  does'nt working

**Comment by artf** [comment]
Actually, we've never provided a listener for a component during the drag, but I can think about adding it in the next release (eg. `component:drag:start`, `component:drag`, `component:drag:end`)

**Comment by ramusesan** [comment]
okay thanks for reply @artf
