### ISSUE TITLE
[Bug] Video traits do not propagate to attributes when parsing video

### ISSUE THREAD

**Issue by senchden** [artf/grapesjs#2501]
Expected behaviour:
After checking certain HTML5 video attributes, they persist across reloads and checkboxes reflect current state.

Actual behaviour:
After reloading a video for which attributes have already been set, the checkboxes display default value set.

Steps to reproduce:
1. Select HTML5 video provider.
2. Select video path and all checkboxes
3. Reload the page
4. Select the video again and observe that checkboxes have been reset to default state (loop and autoplay unchecked and controls checked).

Reproducible in web page demo v0.15.10

See attached screencast:
![video-traits-not-parsing](https://user-images.githubusercontent.com/31250983/72164176-80c21b80-33c5-11ea-88e4-c5981f1c84c6.gif)

**Comment by artf** [comment]
Found the issue, it will be fixed in the next release
