### ISSUE TITLE
Setting the initial color of the color picker

### ISSUE THREAD

**Issue by electrotype** [artf/grapesjs#2502]
I'm trying to set an inital color different than _black_ for the color picker:

```
grapesjs.init({
    // ...
    colorPicker: { 
        color: '#3777B4',
        showAlpha: false,
        showPalette: false,
        preferredFormat: "hex",
        appendTo: 'parent', 
        offset: { 
            top: 26, 
            left: -190 
        }
    }
));
```
This doesn't work, even if [color](https://bgrins.github.io/spectrum/#options-color) is a valid option.

Is there a way to set this initial color? 

I'm open to solutions even if they don't use the config directly but involve some hacky code.

**Comment by artf** [comment]
It doesn't make sense setting a default value on it, the color picker takes the color from the selected target (probably you want to change the color on the component level)

**Comment by electrotype** [comment]
Well, black doesn't make sense either. I would prefere the selected color on the picker to be something else by default, when the component doesn't have any color.

**Comment by artf** [comment]
Try to see if changing the `defaults` color of the property from the Style Manager works for you. You can do it from [initialization](https://grapesjs.com/docs/getting-started.html#style-manager) or via [API](https://grapesjs.com/docs/api/style_manager.html#getproperty)

**Comment by electrotype** [comment]
I'll try that. Thanks for the help!
