### ISSUE TITLE
Making the actions toolbar and rte toolbars follow the text zone on "enters"

### ISSUE THREAD

**Issue by electrotype** [artf/grapesjs#2503]
I don't know if this is an issue on my side (some custom modifications) or if this is an known issue with GrapesJs: in a text zone, when I type "enter" characters, the _actions_ and _rte_ toolbars don't follow the bottom of the zone. I have to type some other characters for the toolbars to reposition themselves correctly:

![issue2](https://user-images.githubusercontent.com/1643012/72210661-c39af680-348c-11ea-8c31-97a8fac3a5c4.gif)

Is there something I can do to improve this?

**Comment by artf** [comment]
Works as expected on my side... version of GrapesJS? Browser?

**Comment by electrotype** [comment]
GrapesJs 0.15.9. Tested on the latest versions of Firefox and Chrome. But I tweaked a lot of things/css... I probably broke something! Thanks for that validation it does work for you.
