### ISSUE TITLE
Move the layer manager to the left side

### ISSUE THREAD

**Issue by vfxdude** [artf/grapesjs#2505]
The layer manager is currently hidden away in a tab, but it should in my opinion be visible all the time. Webflow also had it hidden away in a tab, but moved it to the left side. https://webflow.com/feature/new-navigator-location

**Comment by pouyamiralayi** [comment]
@vfxdude please check out this [fiddle](https://codepen.io/artf/full/MQpZPj) for custom UI.
cheers!

**Comment by vfxdude** [comment]
@pouyamiralayi thanks. 

I was fiddling with a similar idea myself. https://codepen.io/neocoder/pen/bGNMyQK (using the Webpage Preset plugin ).

It would be better and easier if there was an option for this in the Webpage Preset plugin though.

**Comment by artf** [comment]
> It would be better and easier if there was an option for this in the Webpage Preset plugin though.

Currently, I can't dedicate time to presets, but PRs are always welcome

**Comment by vfxdude** [comment]
The layers manager is in a tab in the core, this has nothing to do with the preset plugins (I just thought it had since I'm new to GrapesJs). A better layout system i what I'm asking for, like changing the positions of the panels and also making them resizable.
