### ISSUE TITLE
Default font size units and values

### ISSUE THREAD

**Issue by darrenbreeze** [artf/grapesjs#2507]
Hi

I am using grapesjs in a project that uses proportional scaling everywhere. based on your advice, I can now default the font size selectors to 'em' and make 'em' the only option. 

editor.on('load', function () {
        const styleManager = editor.StyleManager;
        //force font-size to EM
        const fontSize = styleManager.getProperty('typography', 'font-size');
        fontSize.set('units', ["em"]);
        fontSize.set('unit', "em");
        fontSize.set('step', 0.1);
        fontSize.set('min', 0.1);
        fontSize.set('max', 10);
.
.
.
}

everything is fine but when I set the units to EM, the value of the selector is staying as the default in piixels (in this case 9.7) so the selector shows 9.7em whilst the gadgets are appearing in the editor with the font sizes I define as part of creating my gadgets.

Is there a way to sync these up so that the font-size shows the correct value?

I have tried 

fontSize.set('value', 1);

but this is overridden.

thanks

Darren B.

**Comment by artf** [comment]
Can you create a reproducible demo?
