### ISSUE TITLE
[Bug] Draggable property added in the final HTML text components

### ISSUE THREAD

**Issue by alexiswbr** [artf/grapesjs#2508]
This bug is also on the online demo : https://grapesjs.com/demo.html

1. Add a Text Block to the page, start typing and hiting enter to make several break lines.
2. Unselect the block.
3. Double click on the block to start editing again.

Now if you click on the "view code" button, you will see that the HTML nodes inside the Text Block have some `draggable="true` attributes.
This always occure at step three. The first time you edit the text and add break lines, everything is fine, as long as you do not want to edit the block again later.

The problem is, in the final HTML displayed on a website, these attributes are still there. You can not select anything because the navigator interpreting the draggable attributes.
And yes I am saving in database both of the `html` and `components` separately

It seems like a bug to me, or I misunderstood something else

![draggable-html-bug-1](https://user-images.githubusercontent.com/15452514/72326985-831bc280-36b0-11ea-8bbe-4cea0b751d9b.png)
![draggable-html-bug-2](https://user-images.githubusercontent.com/15452514/72326991-84e58600-36b0-11ea-8609-08a04aa2e44e.png)

**Comment by pouyamiralayi** [comment]
@alexiswbr using the below snippet, the ``div``'s will become ``br``'s as the expected behaviour:
```
var iframeBody = editor.Canvas.getBody();
	$(iframeBody).on("keydown", "[contenteditable]", e => {
		// trap the return key being pressed
		if (e.keyCode === 13) {
				e.preventDefault();
				// insert 2 br tags (if only one br tag is inserted the cursor won't go to the next line)
				e.target.ownerDocument.execCommand("insertHTML", false, "<br><br>");
				// prevent the default behaviour of return key pressed
				return false;
		}
	});
```

**Comment by obrazkow** [comment]
I use such way to prevent transformation to component and keep original html.
Just override component that you need, for example `text` or create new.

Maybe it's not good solution, but it works :)

```
export default (editor, type) => {
    const comps = editor.DomComponents;

    const typeToExtend = comps.getType(type);
    const modelToExtend = typeToExtend.model;

    comps.addType(type, {
        model: modelToExtend.extend({
            init() {
                if (modelToExtend.prototype.init) {
                    modelToExtend.prototype.init.apply(this, arguments);
                }

                const models = this.components().models;
                if (models.length) {
                    const elem = models.reduce((content, component) => {
                        content.append(component.get('rawContent') || component.get('content'));
                        return content;
                    }, document.createElement('div'));

                    for (let i = models.length; i !== 0; i--) {
                        models[i - 1].remove();
                    }

                    this.set({content: elem.innerHTML});
                }
            }
        }, {
            isComponent(el) {
                if (el && el.parentElement && el.parentElement.dataset && el.parentElement.dataset.gjsType === type) {
                    return {
                        type: type,
                        content: el,
                        rawContent: el,
                        tagName: 'raw_html'
                    };
                }

                return false;
            }
        }),

        view: typeToExtend.view
    });
}
```

**Comment by alexiswbr** [comment]
Well these are some quick fix but there is another bug maybe linked to this one. 
The more you click on the text component, the more the ids are duplicated and you end up with some HTML nodes having this kind of id : `ilin-2-2-2-2-2-2-2-2-2-2-2-2`.

**Comment by artf** [comment]
Ok I'll try to check this out

**Comment by riteshagarwalsw** [comment]
@artf The same issue exists in the  latest online demo : [https://grapesjs.com/demo.html]
Please help me find a solution to the problem. Although it's marked fixed, but maybe because of some other code it's happening again.
