### ISSUE TITLE
Undo does not work when code is loaded from container 

### ISSUE THREAD

**Issue by martcot** [artf/grapesjs#251]
Undo button does not work very well when HTML code is loaded from container. Is there any standards for HTML in grapejs? better to use bootstrap templates?

**Comment by artf** [comment]
There is already an issue about the undo #64 but exactly what do you mean `does not work very well`? Can you provide any use case? 
Grapesjs doesn't imply any standard, it's all about users of your application domain, you can set it just as a bootstrap template builder if you want

**Comment by artf** [comment]
For all updates about undo issues check #64
