### ISSUE TITLE
How to open a sector when selecting a element?

### ISSUE THREAD

**Issue by ikenderham** [artf/grapesjs#2511]
Hello everybody

How do i open a selector like general as i select the element. 

I am new to javascript, but i tried something out like this.
```js
editor.on('component:selected', function(component) {
  if(component.attributes.tagName == 'div') {
    const styleManager = editor.StyleManager;
    styleManager.getSector('General',{
 
      open: true,
   
    });
  }
});
```
what iam doing wrong?

Thx for help

**Comment by simplecommerce** [comment]
I think you can see a working example here in the source code.

https://github.com/artf/grapesjs-preset-webpage/blob/6306f45d9de77b5b60f72679717e10e6081e81be/src/panels/index.js

At the bottom.

**Comment by ikenderham** [comment]
Can you show me a example, if i click on a DIV then i need general to be opened, or when i click on a h1, then i need to open the "typography"?

Thanks alot im new to this.

**Comment by ikenderham** [comment]
> 
> 
> I think you can see a working example here in the source code.
> 
> https://github.com/artf/grapesjs-preset-webpage/blob/6306f45d9de77b5b60f72679717e10e6081e81be/src/panels/index.js
> 
> At the bottom.

Can you show me a example, if i click on a DIV then i need general to be opened, or when i click on a h1, then i need to open the "typography"?

Thanks alot im new to this.

**Comment by artf** [comment]
@ikenderham you were almost there
```js
editor.StyleManager.getSector('general').set({ open: true })
```

**Comment by ikenderham** [comment]
Thx you so much, nice work artf! 

Last question. If i need it to open settings, what should i do?

Hope you can help, tried to find the answer, but not finding it

**Comment by artf** [comment]
The default UI make use of buttons from [`Panels API`](https://grapesjs.com/docs/api/panels.html) so, you can simulate their activation in this way:
```js
editor.Panels.getButton('views', 'open-tm').set({ active: true })
```
