### ISSUE TITLE
[Question] GrapesJS in a VueJS app

### ISSUE THREAD

**Issue by eyesurewould** [artf/grapesjs#2512]
I'm building a VueJS app and would like to use GrapesJS inside the app (and I'm NOT trying to use VueJS *inside* GrapesJS). 

I've searched and read through existing Issues but so far I have not seen any examples of how to use GrapesJS in a VueJS app (unless I'm misunderstanding the examples).

Thanks for any suggestions!

**Comment by pouyamiralayi** [comment]
Hi @eyesurewould check this one: [2465](https://github.com/artf/grapesjs/issues/2465#issuecomment-568466490)
cheers!

**Comment by eyesurewould** [comment]
@pouyamiralayi Thanks!
