### ISSUE TITLE
[Question]: How to change device from dropdown to icon

### ISSUE THREAD

**Issue by petervandeput** [artf/grapesjs#2514]
I'm trying to replace the dropdown with icon for the devices following the example in the newsletter template yet it doesn't work.

```
//custom commands
    // Turn off default devices select and create new one
    let pnm = editor.Panels;
    editor.getConfig().showDevices = false;
    let devicePanel = pnm.addPanel({
        id: 'devices-c'
    });
    let deviceBtns = devicePanel.get('buttons');
    devicePanel.get('buttons').add([{
        id: 'deviceDesktop',
        command: 'set-device-desktop',
        className: 'fa fa-desktop',
        attributes: {title: 'Desktop'},
        active: 1,
    }, {
        id: 'deviceTablet',
        command: 'set-device-tablet',
        className: 'fa fa-tablet',
        attributes: {title:'Tablet'},
    }, {
        id: 'deviceMobile',
        command: 'set-device-mobile',
        className: 'fa fa-mobile',
        attributes: {title: 'Mobile'},
    }])
```

**Comment by artf** [comment]
You should also create those commands
https://github.com/artf/grapesjs-preset-newsletter/blob/04f1eb21c1ae45f8d2b2912323e79354d8e72f18/src/commands.js#L30-L44

**Comment by umerrinayat** [comment]
@petervandeput 
After grapesjs init. 
`// Add device icons on panels bar 
		editor.getConfig().showDevices = 0;
		editor.Panels.addPanel({ id: "devices-c" }).get("buttons").add([
		{ id: "set-device-desktop", command: function(e) { return e.setDevice("Desktop") }, className: "fa fa-desktop", active: 1},
		{ id: "set-device-tablet", command: function(e) { return e.setDevice("Tablet") }, className: "fa fa-tablet" },
		{ id: "set-device-mobile", command: function(e) { return e.setDevice("Mobile portrait") }, className: "fa fa-mobile" },
		]);

		// Panel should re render again otherwise 
		// New button will not be shown on device panel
		editor.Panels.render();`

**Comment by juice77** [comment]
When you call editor.Panels.render() the Style Manager doesn't work anymore, I think this is a bug.

**Comment by Phil-B** [comment]
The above examples didn't work for me in version 0.17.28 (I presume the API has changed). This worked:

```
    editor.getConfig().showDevices = 0;

    editor.Panels.addPanel({
        id: 'devices-c', buttons: [
            { id: "set-device-desktop", command: function (e) { return e.setDevice("Desktop") }, className: "fa fa-desktop", active: 1 },
            { id: "set-device-tablet", command: function (e) { return e.setDevice("Tablet") }, className: "fa fa-tablet" },
            { id: "set-device-mobile", command: function (e) { return e.setDevice("Mobile portrait") }, className: "fa fa-mobile" }
        ]
    });
```

**Comment by a-szczepan** [comment]
I use version 0.19.5 and I had to rerender the whole editor (not only Panels) after adding the button. 
`editor.Panels.addButton('options', {
    id: 'sample-btn'
}); editor.render();
`
