### ISSUE TITLE
Asset manager alert 

### ISSUE THREAD

**Issue by pradeeshattlee** [artf/grapesjs#2516]
Hi, thanks for the wonderful editor,
I Tried to integrate the editor and everything is Fine.
When the user selects an image from the asset manager there is no action if an alert is shown that image has been replaced or image selected successfully how can an alert be achieved is there any options for That.
Couldn't find a way to add an alert please let me know if there is a way to achieve this

**Comment by pouyamiralayi** [comment]
Hi @pradeeshattlee place the below code inside a [plugin](https://grapesjs.com/docs/modules/Plugins.html):
```
 /*Asset Manager*/
        const am = editor.AssetManager;
        am.addType('image', {
            view: {
                onDblClick(){
                    alert('Selected Successfully!');
                    this.em.get('Modal').close();
                },
            }
        })
```
for more on extending asset manager, check out this [link](https://grapesjs.com/docs/modules/Assets.html#extend-asset-types)
cheers!

**Comment by pradeeshattlee** [comment]
hi @pouyamiralayi @artf 
I tried the code it's working perfectly.
but this Generates alert on double click 
but the image gets replaced on a single click
I tried the bellow code the alert is shown on a single click but the image doesn't get replaced 

Is there a way to change the image and get an alert on a single click or to only change the image on double click.

        const am = editor.AssetManager;
        am.addType('image', {
            view: {
                onclick(){
                    alert('Selected Successfully!');
                    this.em.get('Modal').close();
                },
            }
        })

**Comment by artf** [comment]
> I tried the bellow code the alert is shown on a single click but the image doesn't get replaced

This happens because you overwrite the original method, to extend correctly you should do this:
```js
const am = editor.AssetManager;
const tImageView = am.getType('image').view;

am.addType('image', {
        view: {
            onClick(){
				tImageView.prototype.onClick.apply(this);
                alert('Selected Successfully!');
                this.em.get('Modal').close();
            },
        }
})
```

**Comment by pradeeshattlee** [comment]
Thanks @artf this works like a charm.
