### ISSUE TITLE
Screen flickers on mouse hover on container

### ISSUE THREAD

**Issue by denish-kanabar** [artf/grapesjs#2517]
Tried multiple plugin i.e. webpage, newsletter and basic block but all three cases it starts flickering as soon as I take move over container (div: gjs). Due to this, its not allowing to format text bold, italic, underline and all. Attached is code sample without npms
[studio-fabric-grapesjs-app.zip](https://github.com/artf/grapesjs/files/4089577/studio-fabric-grapesjs-app.zip)

**Comment by artf** [comment]
If you think there is a problem with GrapesJS please open an issue correctly (follow the BUG template): specify the version, browser, live demo, and all the details necessary to give your issue a context (`it starts flickering` means nothing)
