### ISSUE TITLE
Improved form Select component

### ISSUE THREAD

**Issue by kickbk** [artf/grapesjs#2520]
@artf, could you please provide some pointers as to how I go about improving the form select component in grapesjs-plugin-forms so it looks someting like this:

![select](https://user-images.githubusercontent.com/31323376/72849891-b0daab80-3c5c-11ea-8e2a-23f8939174f1.png)

The idea is to provide a sleeker way to add select options and remove them like one would add dropshadow layers.

**Comment by artf** [comment]
You should create a new [Custom Trait](https://grapesjs.com/docs/modules/Traits.html#define-new-trait-type)
