### ISSUE TITLE
Warning on setting up wrapper's height to 100%

### ISSUE THREAD

**Issue by jcamejo** [artf/grapesjs#2522]
Hi @artf I hope everything's going well.

This is more like a reminder or a warning message for an issue I've just had that it took me some time to figure out. 

if the wrapper's height  (modified by the selector #wrapper by default) is set to `height: 100%;` instead of `min-height: 100%`, the editor's tool container will take a non desirable behavior.

![demo](https://user-images.githubusercontent.com/1976679/72892947-1770cf80-3d18-11ea-8695-3a371cf57767.gif)

This happens because the scroll event will not be triggered by the window object but rather the wrapper element, this causes the `onFrameScroll` not to be fired in the CanvasView.

The OnFrameScroll is assigned in the renderBody function.
```
...
      body.append('<style>' + frameCss + '</style>');
      body.append(wrap.render()).append(cssc.render());
      body.append(this.getJsContainer());
      em.trigger('loaded');
      **this.frame.el.contentWindow.onscroll = this.onFrameScroll;**
      this.frame.updateOffset();
...
```

Should this warning be written somewhere in the code? Maybe in the editor configuration file where the baseCSS is set, along with the comments you have there. 

What do you think?

Thanks!

**Comment by artf** [comment]
Hi Juan, thank you for all the details, I'm going to merge soon a big canvas refactoring and will see if we can fix it (eg. attaching scroll callback to the wrapper)

**Comment by jcamejo** [comment]
Glad to hear it, i hope the refactoring helps to fix the issue.

**Comment by artf** [comment]
Thanks for the reminder @bgrand-ch I actually forgot about this issue 😬
Will be fixed in the next release.
