### ISSUE TITLE
Custom storage : autoload not triggered

### ISSUE THREAD

**Issue by treztreiz** [artf/grapesjs#2526]
### version : grapes.min.js 0.15.10

Hi,
I'm using a custom storage to load & store json data from/to a textarea.
Using a custom storage seems to not support the autoload option. Instead, I have to manually trigger editor.load(), but it seems to update the editor so it messes with the noticeOnUnload option (which get triggered before any changes made by the user).

Here is the storageManager configuration : 
### storageManager
```
const editor = grapesjs.init({
...
storageManager: {
    type: 'customStorage',
    autosave: false,
    autoload: true
},
...
});
```

Here is the the custom storage :
### custom storage 
```
editor.StorageManager.add('customStorage', {
        load: function(keys, clb, clbErr) {

            var res = {}, data = storageEl.text(); // get textarea json content

           // custom logic
            if( "" !== data ) {
                try {

                    data = JSON.parse(data);
                    for (var i = 0; i < keys.length; i++) {
                        var v = data[keys[i]];
                        if(v) res[keys[i]] = v;
                    }

                } catch(e) { clbErr( "Error while parsing JSON : " + e.message ); }
            }

            clb( res );

        },
        store(data, clb) {
            var dataString = JSON.stringify( data );
            storageEl.text( dataString ); // updating textarea json content
            clb();
        }
    });
```

Is there any way to autoload a custom storage ?
Thank you !

**Comment by treztreiz** [comment]
The autoload option actually works while adding the custom storage as a plugin.
### custom storage plugin :
```
grapesjs.plugins.add('customStorage', editor => {
    ... 
    sm.add('customStorage', { 
        // custom storage logic
    });
    ...
});
```
### Editor :
```
const editor = grapesjs.init({
    ...
    plugins: ['customStorage'],
    storageManager: {
        type: 'customStorage',
        autoload: true
    },
    ...
});
```

**Comment by collindutter** [comment]
@treztreiz did you ever figure out how to do it without registering it as a plugin? I'm also running into this issue.

**Comment by treztreiz** [comment]
@collindutter It seems that you must make a plugin. I suppose that the autoload option is used while grapes is instantiated, and unfortunately the function editor.StorageManager.add actually needs that instance...
This does not happen with plugins as they are injected in the configuration before the instantiation :)
