### ISSUE TITLE
Layers moving events?

### ISSUE THREAD

**Issue by mtasic-realware** [artf/grapesjs#2528]
Are there available events that's fired when layers are moving ?
![image](https://user-images.githubusercontent.com/55843134/73080303-e7672f00-3ec5-11ea-95ce-c30dada68271.png)
 I've tried with sorter (sorter:drag:start) , block:drag:start ... Nothing happens 
Founded somewhere that there is event **startSort** but i can't set up it properly. I'm using grapesjs on angularjs , adding events like 

grapesEditor.on('sorter:drag:start', function (drag, drop) {

**Comment by artf** [comment]
https://github.com/artf/grapesjs/issues/2500#issuecomment-576463783
