### ISSUE TITLE
[Bug] Can't select/remove/edit gjs-row component if gjs-cell removed first. 

### ISSUE THREAD

**Issue by VelMrnk** [artf/grapesjs#2529]
Can't choose/select/remove gjs-row after removing gjs-cell separately. Row that is left without cell exists on wrapper but can't be highlighted and selected.

Example:

<img src="https://raw.githubusercontent.com/VelMrnk/Images/master/ezgif.com-video-to-gif-3.gif"></img>

**Comment by artf** [comment]
Hi @VelMrnk this is not a bug, as the row is empty and doesn't have its own height, you can't see it (indeed is still selectable from Layers). If you want to change this behavior it's enough to update the component CSS (eg. using the `min-height` or `:empty` pseudo-class)

**Comment by VelMrnk** [comment]
> Hi @VelMrnk this is not a bug, as the row is empty and doesn't have its own height, you can't see it (indeed is still selectable from Layers). If you want to change this behavior it's enough to update the component CSS (eg. using the `min-height` or `:empty` pseudo-class)

Hi. Thanks for response. You are correct, this is css problem, because height doesn't exists. But also, adding of min-height doesn't help for firefox browser. And this is happens because of `display:table` rule. 

So I added css code: 

`.gjs-row:empty  { 
    min-height:60px;
    display: block
;}`

And now it works as it must. Thanks.
