### ISSUE TITLE
add component but dont selected 

### ISSUE THREAD

**Issue by aminio101** [artf/grapesjs#253]
Hi
i added some component but when add in iframe i click on it isn't select must be select it from layer manager

my component like this : 
`{
                    id: 'AnalogClock',
                    label: 'AnalogClock',
                    category: 'free',
                    attributes: {
                        class: 'fa fa-clock-o'
                    },
                    content: '<embed src="AnalogClock.swf" class="cell" style="width: 100%;height: 100%;position: absolute;" data-gjs-badgable="true" data-gjs-custom-name="Clock"  data-gjs-stylable="true">'
                }`

how can fixed and why dont selected from iframe??!!

Please Help Me
TankS.....

**Comment by artf** [comment]
Because when you click inside that embed box you're interacting with .swf object and it doesn't propagate click events, so you have to ignore it somehow. I suggest to wrap it and turn off its pointer events
```js
content: '<div>< embed ... style="pointer-events: none" ></div>'
```
