### ISSUE TITLE
how to drag parent component from selectable child

### ISSUE THREAD

**Issue by alemenciones** [artf/grapesjs#2530]
i have a component type "table" and i find move this table draging her inner components (selectables/stylables) (th, td, ...) this is posible? thanks a lots

**Comment by pouyamiralayi** [comment]
@alemenciones Select parent using the arrow icon:

![arrow](https://user-images.githubusercontent.com/53266765/73119530-72a0fd00-3f78-11ea-82cf-9c6d4677e69c.png)

then drag parent like below:

![plus](https://user-images.githubusercontent.com/53266765/73119566-12f72180-3f79-11ea-89a5-640586db8dc7.png)


Cheers!

**Comment by alemenciones** [comment]
thanks man, but, i was looking for something like this (just for absolute mode)

`editor.on("run:tlb-move:before", (targetCollection) => {

       // Obtengo referencias al componente seleccionado
        var target = targetCollection.target;
        var el = target.view.el;

        //Verifico si tengo un componente padre que me interese
        var component = !!el.closest("table") ? "table" : !!el.closest("form") ? !!el.closest("form").attributes["data-ic-profiling-form"] ? "profiling-form" : "form" :  null;

        //Si tengo padre y el hijo no es arrastrable
        if (component && !target.get("draggable")) {

            //functión para recorrer los componentes padres
            var findParentContainerComponent = parent => {

                //Si estoy parado en el padre actualizo el drag-target
                if (parent.get("type") === component) {

                    //Actualizo el target y detengo el bucle
                    targetCollection.target = parent;
                    return ;
                }

                //Busco al padre del elemento actual
                findParentContainerComponent(parent.parent());
            };

            //Busco y selecciono el componente padre que me interesa
            findParentContainerComponent(target);

        }
    });`
