### ISSUE TITLE
Replacing Font Awesome Icons

### ISSUE THREAD

**Issue by darkcavalry** [artf/grapesjs#2531]
Hello,

I'm using Font Awesome 5 in my project, I was checked grapejs' previously asked questions Font Awesome is removed I guess. 

So, I'm replaced some icons with panel/block options to font awesome 5 but I cant find some icon parameters in editor. When I click on element, drag and remove icons doesnt appears, how can I find that element selectors? Also Style manager show extra large plus icon over panel how can I remove it?

![grapes](https://user-images.githubusercontent.com/5808540/73094469-b270d180-3ef1-11ea-8b8f-08e90ec94da1.jpg)

When I change my Font Awesome build to 4, everthings works fine (except style manager large icon) but my other site styles doesnt work, thats why I asked again that question, sorry about that.

Regards.

**Comment by pouyamiralayi** [comment]
Hi @darkcavalry have you seen this [PR](https://github.com/artf/grapesjs/pull/2240)?
Cheers!

**Comment by artf** [comment]
For changing toolbar icons I'd recommend checking the following issue #1632 

> Also Style manager show extra large plus icon over panel how can I remove it?

Will be fixed in the next release, for now, use this [temporary fix](https://github.com/artf/grapesjs/issues/2490#issuecomment-573441236)
