### ISSUE TITLE
Open blocks UI Components are not visible in Downloaded (localhost) grapejs repository

### ISSUE THREAD

**Issue by nawaz123** [artf/grapesjs#2533]
"Open blocks" UI Components on right top are not visible in Downloaded (localhost) grapejs repository as shown in screenshot. 
![grapejs-localhost](https://user-images.githubusercontent.com/2770455/73122102-b90b5180-3fa2-11ea-8c05-75754091d563.PNG)
while  UI Components on right top are visible on online demo page (https://grapesjs.com/demo.html) 
![demo-page-grapejs](https://user-images.githubusercontent.com/2770455/73122119-efe16780-3fa2-11ea-9ea4-c45c15417cc0.PNG)

**Comment by nawaz123** [comment]
"Open blocks" UI Components on right top are not visible in Downloaded (localhost) grapejs repository as shown in screenshot. 
![grapejs-localhost](https://user-images.githubusercontent.com/2770455/73122102-b90b5180-3fa2-11ea-8c05-75754091d563.PNG)
while  UI Components on right top are visible on online demo page (https://grapesjs.com/demo.html) 
![demo-page-grapejs](https://user-images.githubusercontent.com/2770455/73122119-efe16780-3fa2-11ea-9ea4-c45c15417cc0.PNG)

**Comment by nawaz123** [comment]
kindly guide me to resolve this issue?

**Comment by pouyamiralayi** [comment]
@nawaz123 you can have them by using the [grapesjs webpage preset](https://github.com/artf/grapesjs-preset-webpage)
Cheers!

**Comment by nawaz123** [comment]
@pouyamiralayi thanks, this is exactly what i wanted.
