### ISSUE TITLE
[Question] Swap out Image src

### ISSUE THREAD

**Issue by awaredigital** [artf/grapesjs#2534]
Hi,

I've been doing so much reading on GrapesJs to find out how to build a component and assign it to a block. But after some time, I've figured using components isn't the right way to go.

I'm looking to swap out the image src and set a data-src to the image, however, I only want to do this on the save.

I have a storage manager setup, which passes data simply using the data['html'] into a text area.

```
editor.StorageManager.add('simple-storage', {
store(data, clb, clbErr) {
const html = data['gjs-html'];
}
});
```

Is there any route that Grapes can do this?

Thanks

**Comment by pouyamiralayi** [comment]
@awaredigital you can perform operations like text replacement for your specific case before the grapesjs[ try to store the components & html](https://grapesjs.com/docs/api/editor.html#storages).
``editor.on('storage:start:store', objToStore => {} )``
Cheers!
