### ISSUE TITLE
file://unpkg.com/grapesjs net::ERR_FILE_NOT_FOUND

### ISSUE THREAD

**Issue by eyeamkd** [artf/grapesjs#2535]
I was following the getting started guide, encountered this error. 
CDN link works but unpkg link gives me this error. 

![grapeBug](https://user-images.githubusercontent.com/31094327/73159762-4c609600-410d-11ea-877a-05b35710eaa6.png)

**Comment by pouyamiralayi** [comment]
@eyeamkd the links provided at [getting_started_guide](https://grapesjs.com/docs/getting-started.html#import-the-library) are working fine!
Cheers!

**Comment by eyeamkd** [comment]
Great! @pouyamiralayi , can i know the reason behind the error that i'm facing?

**Comment by pouyamiralayi** [comment]
@eyeamkd 

make sure it is like this:

``https://unpkg.com/grapesjs/dist/css/grapes.min.css`` for css

and

``https://unpkg.com/grapesjs`` for js

also you can benefit from [grapesjs cli](https://github.com/artf/grapesjs-cli) which will do the setup and dependency configurations for you under the hood.

Cheers!

**Comment by eyeamkd** [comment]
okay!! Thank you @pouyamiralayi
