### ISSUE TITLE
[Question] How to make a block that could drop inline with a text block ?

### ISSUE THREAD

**Issue by eyeamkd** [artf/grapesjs#2537]
I need to create an element, that probably is of span type, but the user need to drop it inline with a text. How can i achieve this functionality? To elaborate further, this block of mine, should have the property that could enable it to be inserted anywhere inside already defined text blocks

**Comment by pouyamiralayi** [comment]
Hi @eyeamkd you need to set ``textable`` property of your custom component type to ``true``.
here is more [info](https://github.com/artf/grapesjs/issues/481#issuecomment-481460506) 

custom component [docs](https://grapesjs.com/docs/modules/Components.html#define-custom-component-type)

Cheers!

**Comment by eyeamkd** [comment]
Thanks!!
