### ISSUE TITLE
[Bug] Adding background makes an extraneous request

### ISSUE THREAD

**Issue by senchden** [artf/grapesjs#2538]
Steps to reproduce:
1. Select any element.
2. Try to add a background via Style Manager using 'Decorations' -> 'Background'.
3. Click a plus sign.

Expected behaviour:
No extraneous requests are made.

Actual behaviour:
An extraneous GET request is made to `../none` (i.e. to `https://grapesjs.com/none` if on `https://grapesjs.com/demo.html`)

Caused by `getPosition()` function in `CanvasView.js` file.

Reproducible on version 0.15.10 on web page demo.

**Comment by artf** [comment]
Should be fixed in the next release
