### ISSUE TITLE
[Question] Getting started

### ISSUE THREAD

**Issue by SNaushadS** [artf/grapesjs#2540]
I am a designer, i want to try around GrapeJS.

My understanding is that i can use GrapeJS locally similar to that of WordPress.

I am familiar with Commandline and followed the Docs to install npm followed by installing grape js.. and i dont know what else to do so that i can try it.

WOuld be helpful if there is some followup text added for non-programmers.

Thanks.

**Comment by pouyamiralayi** [comment]
@SNaushadS grapesjs is a **template builder** so it can be integrated into wordpress or any other cms out there. See this [one](https://octobercms.com/plugin/pkurg-pagebuilder) as an example of integration for **octobor cms**

See the [getting_started](https://grapesjs.com/docs/getting-started.html) guide to become familiar with the basics.

Cheers!

**Comment by SNaushadS** [comment]
@pouyamiralayi thanks for the reply. to clarify further, grapejs is not something which can be used like [pinegrow ](https://pinegrow.com/).

**Comment by artf** [comment]
@SNaushadS GrapesJS might be a good base for building something like that

**Comment by michaelVictoriaDev** [comment]
@pouyamiralayi  can you go me through or is there any docs how to integrate to specific like october cms ?
