### ISSUE TITLE
How to remove the right side bar?

### ISSUE THREAD

**Issue by Elvincth** [artf/grapesjs#2543]
<img width="1033" alt="Annotation 2020-02-02 032330" src="https://user-images.githubusercontent.com/6602723/73597835-77af0f00-456b-11ea-9286-2c8b012bf9da.png">
 panels: { defaults: [] },
and I add my own panel using  pn.getPanels().reset([...

Thx in advance.

**Comment by Elvincth** [comment]
`.gjs-cv-canvas {
  width: 100%;
  height: 100%;
}`

**Comment by atikhashmee** [comment]
were you able to solve this problem? I don't know for some reason mine is not hiding. Please do let me know what solution did you apply

**Comment by lukajose** [comment]
Overwriting the initial css, all css variables are declared in grapesjs. 
Simply add to your css:
`:root {
     --gjs-left-width: 0%;
}`
