### ISSUE TITLE
Get CSS of selected component ?

### ISSUE THREAD

**Issue by gentritabazi01** [artf/grapesjs#2544]
Hello how can i get css of selected component  ?

**Comment by longdoan7421** [comment]
You could listen the event `component:selected`, then you will get the component's DOM element.  After that, you could simply use javascript to get style of that component. About getting style by javascript, you can check this link [How to get CSS values in JavaScript](https://zellwk.com/blog/css-values-in-js/)

Here is an example: 
```
editor.on('component:selected', (component) => {
  const domElement = component.getEl();
  const style = window.getComputedStyle(domElement)
})
```

**Comment by artf** [comment]
You can also get the currently selected component by doing `editor.getSelected()`

**Comment by alemenciones** [comment]
How to get/setStyle() of hover state from a component? this is posible?

**Comment by sohaib389** [comment]
@alemenciones 
`hoverColor = (event) => {
        let myColorHover = event.target.value;
        const selectedComp = editor.getSelected();
        const selectorComp = '#' + selectedComp['ccid'];
        const css = editor.Css;
        const rule = css.setRule(selectorComp + ':hover', {color: myColorHover});
    }`
I think this will help you!

**Comment by Jaminur-Rashid** [comment]
@artf Is there a way to reset the style of a selected element and its nested elements to their previous state with a single click? This would be similar to an 'undo' function, but specifically for resetting styles.
**Example Scenario:**

- A user selects a component (e.g., a div with nested elements) and makes several style changes (e.g., color, font-size, margin, etc.).

-  After some time, the user decides to revert all the style changes made to this component and its nested elements to their original styles.

- The user clicks a 'Reset Styles' button which should restore the original styles for the selected component and all its nested elements, without undoing other changes.

**Comment by padcom** [comment]
Here's a bit of code that takes the DOM `el` of type `HTMLElement` and returns a string that has all the styles assigned to this particular element:

```typescript
function getHtmlWithInlinedStyles(el: HTMLElement, editor: Editor) {
  const temp = document.createElement('div')
  temp.innerHTML = el.outerHTML

  function computeStyleFromCssRule(rule: CssRule) {
    return Object.entries(rule.attributes.style || {})
      .reduce((acc, [name, value]) => [...acc, `${name}: ${value};`], [] as string[])
      .join(' ')
  }

  // eslint-disable-next-line complexity
  function processNodes(root: Element) {
    if (root instanceof HTMLElement && root.id) {
      const rule = editor.Css.getIdRule(root.id)
      if (rule) root.setAttribute('style', computeStyleFromCssRule(rule))
    }

    let node = root.firstElementChild
    while (node) {
      processNodes(node)
      node = node.nextElementSibling
    }
  }

  processNodes(temp)

  return temp.innerHTML
}
```

And a bit of explanation of what's happening here:
- first we give the function the `HTMLElement` we want to convert to `style`-inlined HTML and an `Editor` instance
- then we create a temporary `div` so we can parse the element's `outerHTML` into a DOM structure
- after that we iterate over each element of the temporary DOM tree and if the current element has an `id` and if there is a CSS rule in the project that matches this element then we convert the rule into the CSS style string and set the `style` attribute to that value
- finally we return the `innerHTML` of the temporary `div` which contains everything, including the inlined styles.
