### ISSUE TITLE
Error while resizing with golden layout: Cannot read property 'appendChild' of null

### ISSUE THREAD

**Issue by Elvincth** [artf/grapesjs#2545]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/6602723/73630535-57797000-4691-11ea-8fd5-183503760d1f.gif)

`index.js:129 Uncaught TypeError: Cannot read property 'appendChild' of null
    at Object.postRender (index.js:129)
    at index.js:757
    at Array.forEach (<anonymous>)
    at r.<anonymous> (index.js:756)
    at m (backbone.js:368)
    at v (backbone.js:356)
    at h (backbone.js:155)
    at r.c.trigger (backbone.js:346)
    at renderBody (CanvasView.js:263)
    at I (underscore.js:762)`

**Comment by artf** [comment]
@Elvincth, as you have the error stack, click on the error to see exactly where it happens

**Comment by Elvincth** [comment]
> @Elvincth, as you have the error stack, click on the error to see exactly where it happens

`
    /**
     * Initialize module. Automatically called with a new instance of the editor
     * @param {Object} config Configurations
     * @return {this}
     * @private
     */
    init(conf = {}) {
      c = {
        ...defaults,
        ...conf
      };
      const em = c.em;
      const ppfx = c.pStylePrefix;
      this.em = em;

      if (ppfx) {
        c.stylePrefix = ppfx + c.stylePrefix;
      }

      this.selectorTags = new ClassTagsView({
        collection: new Selectors([], { em, config: c }),
        config: c
      });

      // Global selectors container
      selectors = new Selectors(c.selectors);
      selectors.on('add', model => em.trigger('selector:add', model));
      selectors.on('remove', model => em.trigger('selector:remove', model));
      selectors.on('change', model =>
        em.trigger(
          'selector:update',
          model,
          model.previousAttributes(),
          model.changedAttributes()
        )
      );
      em.on('change:state', (m, value) => em.trigger('selector:state', value));

      return this;
    },

    postRender() {
      const elTo = this.getConfig().appendTo;

      if (elTo) {
        const el = isElement(elTo) ? elTo : document.querySelector(elTo);
        el.appendChild(this.render([])); //this line error
      }
    },

    select(value, opts = {}) {
      const targets = Array.isArray(value) ? value : [value];
      const toSelect = this.em.get('StyleManager').setTarget(targets, opts);
      const res = toSelect
        .filter(i => i)
        .map(sel =>
          isComponent(sel)
            ? sel
            : isRule(sel) && !sel.get('selectorsAdd')
            ? sel
            : sel.getSelectorsString()
        );
      this.selectorTags.componentChanged({ targets: res });
      return this;
    },`


![image](https://user-images.githubusercontent.com/6602723/73726047-a2ff4d00-4769-11ea-887c-9e3d2d71ed51.png)

**Comment by artf** [comment]
Ok, seems like you're using this option
```js
selectorManager: {
	...
	appendTo: '#some-selector',
}
```
and for some reason it re-renders the container and tries to query for it again. 
Do you trigger the rerender manually? 
In any case, I think this might solve the issue if the DOM (of `#some-selector`) is not altered
```js
selectorManager: {
	...
	appendTo: document.querySelector('#some-selector'),
}
```

**Comment by Elvincth** [comment]
@artf 
Yes , it did fixed the error problem! 
But after resizing / moving the canvas it lose control, and no error shown.
P.S. Is there anyway that I can use appendTo after grapesjs.init? Seems we can only use appendTo in config.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/6602723/73812785-009ea280-4819-11ea-881b-dff5ae1376c2.gif)

`grapesjs.init({
  container: document.querySelector('#gjs'),
  fromElement: true,
  allowScripts: true,
  avoidInlineStyle: true,
  height: '100%',
  width: 'auto',
  storageManager: false,
  layerManager: {
    appendTo: document.querySelector('#layers-container')//appened to jspanel(popup window)
  },
  selectorManager: {
    appendTo: document.querySelector('#selectors-container'), //appened to jspanel(popup window)
  },
  traitManager: {
    appendTo: document.querySelector('#traits-container'), //appened to jspanel(popup window)
  },
  styleManager: {
    appendTo: document.querySelector('#style-manager-container'), //appened to jspanel(popup window)
  },
   panels: { defaults: [] },
});`

**Comment by artf** [comment]
After init/render you can use the simple `querySelector` and move the DOM wherever you need, but again, I hope you don't re-render stuff manually

**Comment by Elvincth** [comment]
@artf Thanks a lot for your help!

**Comment by Elvincth** [comment]
> After init/render you can use the simple `querySelector` and move the DOM wherever you need, but again, I hope you don't re-render stuff manually

Seems when I move the panel, the editor re-render or load itself again.
Any method that can I prevent it re rendeing?
