### ISSUE TITLE
Unable to drag cell inside row

### ISSUE THREAD

**Issue by AbdiasM** [artf/grapesjs#2546]
@artf Could you please take a look at this.

On deleting a cell and trying to add a new cell from the blocks manager, it gives the following error: 
"Invalid target position: Target collection not found, Target is not droppable, accepts [undefined], Component not draggable, acceptable by [undefined]". 

These are my cell and row components:

    comps.addType("cell", {
        isComponent: el => el.tagName == "TD",
        model: cellType.model.extend({
            defaults: {
                ...cellType.model.prototype.defaults,
                name: 'mycell',
                draggable: ['tr'],
                droppable: true,
                resizable: true,
                removable: true,
                select: true,
        })
    });

    comps.addType("row", {
        isComponent: el => el.tagName == "TR",
        model: rowType.model.extend({
            defaults: {
                ...rowType.model.prototype.defaults,
                name: 'myrow',
                draggable: ['tbody'],
                droppable : ['td'],
                resizable: true,
                select: true,
                highlightable: true              
            },
        })
    });

The cell gets added if I drag it over another cell. How can I add the cell if I drag it over the empty space in row element.

Please see attached gif.
![DragCell](https://user-images.githubusercontent.com/18558443/73633315-64439700-4684-11ea-89d5-59c9f732c2c4.gif)

**Comment by artf** [comment]
Please, create a reproducible demo of your issue
