### ISSUE TITLE
Unable to drag an element if style has bottom or right values

### ISSUE THREAD

**Issue by sdrebel** [artf/grapesjs#2547]
Hi @artf ,

If any component CSS has bottom or right values , not able to drag them. Values are generating as NaN. Attached the screenshot for your reference. 

![image](https://user-images.githubusercontent.com/19382262/73723718-bb626e00-474f-11ea-8953-11156f96c926.png)

**Comment by artf** [comment]
Can you create a reproducible demo?

**Comment by sdrebel** [comment]
> Can you create a reproducible demo?

Hi @artf 

Demo link is here https://jsfiddle.net/fn43hpj1/2/

You can check the 'Popup' component.  Since in Draggable mode style gets overridden, I'm getting the style and update onRender method.

**Comment by artf** [comment]
> Since in Draggable mode style gets overridden, I'm getting the style and update onRender method.

Yeah, that will be fixed in the next release, I'll check later with your example

**Comment by bgrand-ch** [comment]
@artf closed?
