### ISSUE TITLE
[Bug] Unable to scroll all canvas with zoom enabled

### ISSUE THREAD

**Issue by christiancannata** [artf/grapesjs#2548]
When zoom is enabled is not possible to scroll over all canvas and move components.

I think that is transform: scale(1.5) translate(0px); property on canvas the origin of the problem.

If I enable an overflow: scroll property outside the canvas, I can move only for a partial canvas, but not on all canvas size.

<img width="892" alt="Schermata 2020-02-04 alle 14 57 14" src="https://user-images.githubusercontent.com/4604959/73724866-e0121200-475e-11ea-875d-eb9cbd88fbc7.png">

<img width="892" alt="Schermata 2020-02-04 alle 14 57 14" src="https://user-images.githubusercontent.com/4604959/73724911-f324e200-475e-11ea-9757-85d921ef1808.png">

**Comment by artf** [comment]
Hi @christiancannata when you enable the zoom you should be able to pan the canvas  by pressing SPACE and left mouse click

**Comment by mmotov** [comment]
Hi @artf! That was really helpful, but how I set canvas's original position when I zoomed back to normal state?
