### ISSUE TITLE
[QUESTION] Update component view on property change

### ISSUE THREAD

**Issue by rjrodriguezalvarez97** [artf/grapesjs#2549]
Hi everyone,
I'm trying to create a component that will update it's view based on a property value
```javascript
editor.DomComponents.addType("price-value-type", {
            isComponent: el => {
              if (el.tagName == "div" && el.hasAttribute("price-value")) {
                return { type: "price-value-type" };
              }
            },
            model: {
              defaults: Object.assign({}, defaultProperties, {
                defaultPrice: 0,
                name: "Price",
                classes: ["price"],
                components: model => {
                  return `${model.get("defaultPrice")}`}
              })
            },
            extendView: 'default',
            extendFnView: ['render'],
            view: {
              init() {
                console.log(this.render);
                this.listenTo(this.model, 'change:defaultPrice', this.render);
              },
              // render() {
              //   this.el.innerHTML = this.model.get("defaultPrice");
              // }
            }
          });

```
My approach is bassed on #1227 and on [the docs](https://grapesjs.com/docs/modules/Components.html#update-component-type) In my use case I don't need the trait, I can just update the property programmatically. But this won't work and will not display any component on the canvas even though they are on the layer manager as we can see [here](https://prnt.sc/qx9j12)(they show properly with the render function commented) maybe i'm missing something?

**Comment by artf** [comment]
Did you try something like this?
```js
view: {
	init() {
		this.listenTo(this.model, 'change:defaultPrice', this.render);
	},
	onRender() {
		this.el.innerHTML = this.model.get("defaultPrice");
	}
}
```

**Comment by rjrodriguezalvarez97** [comment]
If I recall properly that did work(updated the view) when I tried it, but it didn’t change the Html generated when exported

**Comment by artf** [comment]
to update the HTML you have to change `toHTML` in the model
```js
model: {
	...
	toHTML() {
		const tagName = this.get('tagName');
		const price = this.get('defaultPrice');
		return `<${tagName}>${price}</{tagName}>`;
	}
}
```

**Comment by rjrodriguezalvarez97** [comment]
I’ll give it a try the day after tomorrow. Thanks for your quick replies!

**Comment by kishan-ranawat** [comment]
> to update the HTML you have to change `toHTML` in the model
> 
> ```js
> model: {
> 	...
> 	toHTML() {
> 		const tagName = this.get('tagName');
> 		const price = this.get('defaultPrice');
> 		return `<${tagName}>${price}</{tagName}>`;
> 	}
> }
> ```

Thank you very much @artf. I was struggling with it. Couldn't understand what is wrong and then came to this comment. You saved my day!!!
