### ISSUE TITLE
How to add headings (h1, h2, etc.) ?

### ISSUE THREAD

**Issue by marc-fun** [artf/grapesjs#255]
If I add a text block, I cannot tell if it's a paragraph or a heading (h1, h2, etc.)

**Comment by artf** [comment]
You might want to check out how to create custom [Blocks](https://github.com/artf/grapesjs/wiki/Blocks)

**Comment by marc-fun** [comment]
Great, it works now I've managed to install it on my server !
Really a great job you've done with this app, thanks a lot !
