### ISSUE TITLE
DragMode 'absolute' not able to drag and drop other components

### ISSUE THREAD

**Issue by sdrebel** [artf/grapesjs#2553]
Hi @artf,
In absolute dragmode, not able to drag and drop other components inside the selected component.

This issue is not for custom component, tried with basic column component. 

Let me know if any work around is there

Demo is here
https://jsfiddle.net/fn43hpj1/2/

Thank You.

**Comment by artf** [comment]
At the moment the absolute dragmode doesn't work in that way, all the dropped blocks go directly in the root
