### ISSUE TITLE
[QUESTION] Create dynamic table with dynamic data from server

### ISSUE THREAD

**Issue by irfanhaider5** [artf/grapesjs#2554]
Hi ,
I want to make dynamic component using table with dynamic data.And want to render generated html in react component.Will you please help me out how can I do that I didn’t find any thing that help me out.I m stuck.

**Comment by artf** [comment]
You need to create a custom component and you could load the dynamic data in `onRender` callback function

**Comment by irfanhaider5** [comment]
> You need to create a custom component and you could load the dynamic data in `onRender` callback function

i asking after saving html and css from grapesjs in our database.how to load dynamic data while rendering stored html css on any other page like i m using react how can i load dynamic data from db and view in html css i have create from grapesjs. thanks in advance
