### ISSUE TITLE
[QUESTION] Update min max values of vue-slider 

### ISSUE THREAD

**Issue by marlitob** [artf/grapesjs#2555]
Hello, 

Ive added vue-slider to my project and I am trying to set the min and max range on the sliders to go -100 to 100. However when I set them I get:

[Vue warn]: Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders. Instead, use a data or computed property based on the prop's value. Prop being mutated: "min"

I understand this is because I am setting the values on the parent level but I am having trouble setting them directly on my traits. 

Would you be able to give me some insight on how to set these using grapes? Thank you!

please see fiddle 

https://jsfiddle.net/uwrn3okf/

**Comment by artf** [comment]
Dude, this is Vue related question...

btw, you just need to pass them in vue function render
```js
h(VueSlider, {
	props: {
		min: -100,
		max: 100,
		contained: true,
    }
})
```
