### ISSUE TITLE
[Question] Limit UndoManager to X amount of steps

### ISSUE THREAD

**Issue by MatthewMariner** [artf/grapesjs#2556]
**Use Case:**
Hey guys, I looked through the UndoManager API/Searched for issues - but I am unable to figure out how to limit the UndoManager. If I create a robust website and spend 30 minutes making it, it looks like I can ctrl + z all the way back to start. I'm thinking this could possibly slow down the Editor since it saves all these steps in the Undo Manager.

**TLDR**
So, does anyone know how to limit the UndoManager to only save X amount of steps?

**Comment by artf** [comment]
```js
editor.UndoManager.getInstance().set('maximumStackLength', 100);
```

**Comment by MatthewMariner** [comment]
Thank you @artf
