### ISSUE TITLE
[QUESTIONS] Resize text size when resize component area with mouse

### ISSUE THREAD

**Issue by christiancannata** [artf/grapesjs#2557]
Is it possibile resize the text inside a text component when I risezie the component area with the mouse with ratio sizes?

<img width="517" alt="Schermata 2020-02-08 alle 16 19 01" src="https://user-images.githubusercontent.com/4604959/74081888-bfafc380-4a8e-11ea-989f-ff9b80c04446.png">

**Comment by artf** [comment]
You should create a custom component which updates the component font-size on container resize ([detect element resize](https://stackoverflow.com/questions/6492683/how-to-detect-divs-dimension-changed))
