### ISSUE TITLE
style update to gjs classes

### ISSUE THREAD

**Issue by prabha-912** [artf/grapesjs#2558]
Hey team,

Greetings!

I come up here for clarification and next level upgrade. I'm facing the following issue. 
I just update the font color or background color, the property updated to either gjs-comp-selected or gjs-hover class. So this results, while I select a new component, the style updated to the selected one or hovered one. 

Kindly give me a guidance. 

Note: I'm using the old version of the grapesjs. I could update to latest one. It works in other property update. This issue raised only with LIST style update. 

![Screenshot from 2020-02-10 15-13-58](https://user-images.githubusercontent.com/45986663/74138641-ffee7d80-4c17-11ea-9cf1-153e2a308b03.png)

**Comment by artf** [comment]
At first, update to the latest version, then open a correct issue by explaining **step by step** how to reproduce it
