### ISSUE TITLE
[Bug] bug in toggle className status

### ISSUE THREAD

**Issue by majidh1** [artf/grapesjs#2559]
If try change checkbox from className in styleManager then appears error
**error message:** Cannot read property 'parentNode' of null
<img src="https://imgur.com/download/W78R17J">

**Comment by adriangroch** [comment]
@artf any suggestions on where I should start looking?

**Comment by artf** [comment]
Thanks @adriangroch 
This is from the [selector view](https://github.com/artf/grapesjs/blob/dev/src/selector_manager/view/ClassTagView.js), [event](https://github.com/artf/grapesjs/blob/73e383777c2379b9a8b5dfe83cc0943b1eae3fda/src/selector_manager/view/ClassTagView.js#L21) binded to this [function](https://github.com/artf/grapesjs/blob/73e383777c2379b9a8b5dfe83cc0943b1eae3fda/src/selector_manager/view/ClassTagView.js#L89)
