### ISSUE TITLE
How can I make a slider with Slick?

### ISSUE THREAD

**Issue by tranbaduyuy** [artf/grapesjs#256]
I try to make a slider with the Slick library but I did find the way I can do it.

Anyone have the example or document for this point?

Please help.

Thanks.

**Comment by artf** [comment]
Sure @tranbaduyuy check out [Components](https://github.com/artf/grapesjs/wiki/Components) and [Components-&-JS](https://github.com/artf/grapesjs/wiki/Components-&-JS) to get more about how to create a custom component like a slider

**Comment by tranbaduyuy** [comment]
Hi @artf, 
I tried with this but I can't found solution about this.
This is very simple just add block with 4 item and then using jquery to init slider :(

Could You give me more detail of this point.

Thanks You!

**Comment by artf** [comment]
Should be something like this
```js
var comps = editor.DomComponents;
...
comps.addType('slider', {
  model: defaultModel.extend({
    defaults: ... {
      ...
      script: function () {
         // here you put your init slider function
      }
    }
  }, {
    isComponent:...
  }),
 view: ...
});
```
