### ISSUE TITLE
[Editor] gjs-css-rules invalid sort

### ISSUE THREAD

**Issue by WebEtSolutions** [artf/grapesjs#2562]
Hi,

On the latest version 0.15.10, we have a problem with the css generator.
Devices is configured like this :
```javascript
mediaCondition: 'max-width',
deviceManager: {
	devices: [
		{
			name: 'small',
			width: '40em',
		},
		{
			name: 'medium',
			width: '64em',
		},
		{
			name: 'large',
		}
	]
},
```

When I add a rule like background-color, on the real css I have
```html
<style>
@media (max-width: 40em)
.id-usr-ix0a {
    background-color: #ff0000;
}

@media (max-width: 64em)
.id-usr-ix0a {
    background-color: #828282;
}

.id-usr-ix0a {
    background-color: #000000;
}
</style>
```

This order is perfect. But on the javascript style (for editor) I have

```html
<div id="gjs-css-rules"></div>
<div id="gjs-css-rules-40"></div>
<div id="gjs-css-rules-64"></div>
```
So my CSS result on editor is 
```html
<style>
@media (max-width: 64em)
.id-usr-ix0a {
    background-color: #828282;
}

@media (max-width: 40em)
.id-usr-ix0a {
    background-color: #ff0000;
}

.id-usr-ix0a {
    background-color: #000000;
}
</style>
```
And the style under 40em is the 64em ....

Have you an idea of the correction ?

Thanks a lot !

Flo.

**Comment by WebEtSolutions** [comment]
Sorry, it's another script

Bye

**Comment by WebEtSolutions** [comment]
Re sorry !

So when attribute mediaCondition is on min-width on the editor configuration, we need to sort gjs-css-rules on the render for get the good order on the editor 

CssRulesView.js -> after line 126 -> prs.sort() if it's mobile first

Thanks
Bye
Flo.

**Comment by artf** [comment]
You can use the [`priority`](https://github.com/artf/grapesjs/blob/73e383777c2379b9a8b5dfe83cc0943b1eae3fda/src/device_manager/model/Device.js#L20) property in your devices definition
