### ISSUE TITLE
[Question]After adding the forms plugin in grapesjs we are able to see bootstrap class properties in the stylemanager panel

### ISSUE THREAD

**Issue by KishanRavindran** [artf/grapesjs#2563]
In our project, we are using the grapesjs. In that, we have used the grapesjs Form. When we drag and drop the form to the grapesjs canvas. We see in the style manager the class properties of bootstrap. But we have added our own CSS in the grapesjs canvas object on initialization in code. 

As we have added our own styles should we not see those style class reflected for the forms rather than the bootstrap class.

If we remove those bootstrap class and put our custom CSS class it is working and changes are seen in the canvas for the forms.

Please let us know if this is the default behavior of the forms plugin.

**Comment by artf** [comment]
You can extend the form component and add your classes
