### ISSUE TITLE
Style changes affecting classes

### ISSUE THREAD

**Issue by jdillon001** [artf/grapesjs#2564]
When changing some of the styles on an element (with class .col), it changes the class .col which of course affects everything on the page. 

I've tried:         

**avoidInlineStyle:0,**

but its not working

**Comment by jdillon001** [comment]
Figured it out really needs to be clearer that clicking on tag does nothing, you have to click on the tick.

**Comment by artf** [comment]
You can use the component-first styling https://github.com/artf/grapesjs/pull/2474
