### ISSUE TITLE
[QUESTION] Color picker default colors

### ISSUE THREAD

**Issue by jdillon001** [artf/grapesjs#2566]
Is there a way to set a number of default colours to appear at the top of the color picker? 

![Screenshot 2020-02-13 at 00 49 55](https://user-images.githubusercontent.com/19665911/74391043-eb1e0f80-4dfa-11ea-8208-305dc8d5bbba.png)

**Comment by artf** [comment]
```js
grapesjs.init({
	...
	colorPicker: {
		palette: [
			['#000000','#ff0000','#ff8000','#ffff00','#008000','#0000ff','#4b0082']
      	],
	}
})
```

**Comment by jdillon001** [comment]
Thank you!
This may sound stupid, but is this documented somewhere, as I didnt find it in the official docs

**Comment by artf** [comment]
No, unfortunately not yet, the idea was to make the color picker replaceable, so I've planned to document it once the new API was ready

**Comment by Kamran544** [comment]
@artf default selected palette color is black with a tick sign as shown in the picture above. can we change this to another color?
