### ISSUE TITLE
[BUGS] Can't change background-color a component on FireFox

### ISSUE THREAD

**Issue by tranthanhhoa** [artf/grapesjs#2567]
**Version:**
0.15.10

**Bug:**
Can't change the background color of a component on FireFox (v73.0)

**How to reproduce it:**

Goto https://grapesjs.com/demo.html on Firefox
Select a component then open Decorations group and change Background Color 

**Result:**
https://prnt.sc/r1oxhg
The selected component doesn't apply new background color

**Expect:**

The selected component should change to new background color

**Comment by artf** [comment]
Increase the alpha channel
