### ISSUE TITLE
[QUESTION] 3rd party RTE integration

### ISSUE THREAD

**Issue by h3llomoto** [artf/grapesjs#2570]
Hi there!
Great work at grapesjs!

Is there any list of external RTE's to integrate in grapesjs?
I've spent a few days trying to integrate any, but still no results.
If anyone already has a solution for integration other RTE's, please share them.

**Comment by pouyamiralayi** [comment]
[#1697 comment](https://github.com/artf/grapesjs/issues/1697#issuecomment-451742181)

**Comment by h3llomoto** [comment]
@pouyamiralayi thank you. 
but earlier I checked tinyMCE thread and it seems that TMCE still doesn't work properly.
and I've seen ckeditor. I'm looking for anything small and simply as quill, pell and so one.

**Comment by pouyamiralayi** [comment]
@h3llomoto ``ckeditor`` is small and simple! what do you suggest in place of that?

**Comment by h3llomoto** [comment]
hmm, this is what i get after installing ckeditor4 and grapesjs-plugin-ckeditor
![Снимок экрана от 2020-02-17 15-27-34](https://user-images.githubusercontent.com/58657254/74653934-46088b80-519a-11ea-9822-dde6bf0375c7.png)

and you can't say "ckeditor is small and simple' after I mentioned pell. it is really small and simple.

**Comment by pouyamiralayi** [comment]
@h3llomoto sorry my bad! for the error unless you are serving css from a local server (webpack or ...)
you must reference it through the online link.
Cheers!

**Comment by h3llomoto** [comment]
Even when I solved all console errors, CKEDITOR is a GPL licensed software. 
Pell, Squire, Quill are MIT/BSD licensed which is necessary for commercial projects.

So, the question is open: **is there anyone has a ready solution with a 3rd party custom RTE?**

**Comment by artf** [comment]
> So, the question is open: is there anyone has a ready solution with a 3rd party custom RTE?

At the moment, we only have the plugin for CKEditor as it is able to work with a nested iframe. If you want to try to create a new plugin with some other library please refer to [this guide](https://grapesjs.com/docs/guides/Replace-Rich-Text-Editor.html)
