### ISSUE TITLE
[QUESTION] Can we start from a default template rather than blank canvas?

### ISSUE THREAD

**Issue by ahmeds63** [artf/grapesjs#2572]
Hi,

Thank you for this great library! Very handy to use. I have implemented this on a project as per the clients' requirement. But they are wondering if they can start building from a default template like the one you have here in demo: https://grapesjs.com/demo.html is there a plugin for this or some boolean option that we can add to editor object? Or do I need to create components for this (which is hectic job plus I am short on time)

Can we start from a default template rather than blank canvas?

Any help would be appreciated, thanks!

**Comment by pouyamiralayi** [comment]
[# 2195 comment](https://github.com/artf/grapesjs/issues/2195#issuecomment-522504337)

**Comment by ahmeds63** [comment]
thanks that helped!
