### ISSUE TITLE
[QUESTION] How do I block the insertion of a block inside another block?

### ISSUE THREAD

**Issue by dskarasev** [artf/grapesjs#2577]
Please tell me how do I prevent inserting a block inside another block? 
I use the editor to create the internal structure of an article for a WEB site. Grapejs building blocks are not used. All custom blocks are added via the configuration editor.BlockManager.add
I will be grateful if you can tell me how to do that.
Thanks!

**Comment by pouyamiralayi** [comment]
@dskarasev you can define [custom component type](https://grapesjs.com/docs/modules/Components.html#define-custom-component-type) and control the dragging using draggable property:
```
model: {
    // Default properties
    defaults: {
      tagName: 'input',
      draggable: 'form, form *', // Can be dropped only inside `form` elements
      droppable: false, // Can't drop other elements inside
    }
  }
```
Cheers!
