### ISSUE TITLE
[Bug]: How to use components

### ISSUE THREAD

**Issue by Jogai** [artf/grapesjs#2581]
Using GrapesJS 0.15.10 I cant get the components to work the way I intent. Its probable me, so if its a question, feel free to adjust the title of the issue. (its a follow up of https://github.com/artf/grapesjs/issues/2195) 

I've made a pen (hope thats ok, didnt see the fiddle templates) for my example: https://codepen.io/jogai/pen/yLNJgLZ?editors=1011

I see the same behavior in chrome & firefox.

Expected to have a row with text that is not selectable/draggable/highlightable but instead the row has text that is draggable into the other component.

Expected attributes of the component:

    data-gjs-selectable="false" data-gjs-highlightable="false" data-gjs-hoverable="false"

But instead the attributes are:

    data-gjs-type="cell" draggable="true" data-highlightable="1"

data-gjs-type is fine, the others have a wrong value, hoverable is missing entirely, one is missing data-gjs completely, and one is missing the -gjs- part.

**Comment by pouyamiralayi** [comment]
Hi @Jogai you must also specify the ``data-gjs-draggable`` on the ``<td>``:
```
            <table width="770" cellpadding="0" cellspacing="0" style="background-color:#CAD;">
                <tr style="display:block;padding:15px;">
                    <td data-gjs-draggable="false" data-gjs-selectable="false" data-gjs-highlightable="false">
                        Component text 1
                    </td>
                </tr>
                <tr style="display:block;padding:15px;">
                    <td data-gjs-draggable="false" data-gjs-selectable="false" data-gjs-highlightable="false">
                        Component text 2
                    </td>
                </tr>
            </table>
```
Cheers!

**Comment by Jogai** [comment]
Thanks. At least thats an improvement, but still the other properties are not taken into account, and if you try tro drag it (since the drag arrows still show up) it throws an error and then the whole editor is in a broken state.

**Comment by Jogai** [comment]
Updated the example. Its sort of a followup on https://github.com/artf/grapesjs/issues/2195

My assumption is wrong that draggable needs data-gjs- prefix, because the html part without using component doesnt have that either. Still the child td is not seen as part of the component.

**Comment by artf** [comment]
> data-gjs-type is fine, the others have a wrong value, hoverable is missing entirely, one is missing data-gjs completely, and one is missing the -gjs- part.

Forget what is happening in the editor code, the view could be TOTALLY different from the code, you SHOULD NOT consider it

By looking at your demo EVERYTHING works as expected by your definition, so I don't see any bug, maybe take a better look at the [component properties](https://grapesjs.com/docs/api/component.html) because seems like you're missing something...

**Comment by Jogai** [comment]
Ok, I'll disregard the dom properties. But my original question still stands:

> Expected to have a row with text that is not selectable/draggable/highlightable but instead the row has text that is draggable into the other component.

It seems that the td is not recognised. Yes its probably me, but I looked at the docs and I cant see what I'm doing wrong.

**Comment by artf** [comment]
> It seems that the td is not recognised. Yes its probably me, but I looked at the docs and I cant see what I'm doing wrong.

You've defined the TD in this way `<td data-gjs-selectable="false" data-gjs-highlightable="false" data-gjs-hoverable="false" data-gjs-draggable="false">` indeed the editor ignores the TD and selects the TR which has only `data-gjs-draggable="#main" data-gjs-copyable="false"`, so I don't see the isssue...
