### ISSUE TITLE
create a new button in the panel manger

### ISSUE THREAD

**Issue by ayana30** [artf/grapesjs#2582]
I want to add a new button after the settings icon.
![Screenshot from 2020-02-18 17-14-16](https://user-images.githubusercontent.com/54315979/74733431-58ee8f00-5272-11ea-8818-0bab23016209.png)

and I used the following code to create the button.but its not working

` var panelManager = editor.Panels;
    var newButton = panelManager.addButton("myNewPanel", {
      id: "myNewButton",
      attributes: { title: "Edit Menu",
       class: "fa fa-sort-desc" },
      active: true
    });`

**Comment by pouyamiralayi** [comment]
[#2350 comment](https://github.com/artf/grapesjs/issues/2350#issuecomment-587744144)
