### ISSUE TITLE
Breakpoints don't match media query in canvas

### ISSUE THREAD

**Issue by MariusDK** [artf/grapesjs#2583]
Hey @artf 

I have multiple breakpoints 
![image](https://user-images.githubusercontent.com/26068332/74736935-7fa1cb00-525c-11ea-9d33-e30b6bc44ae5.png)

The problem is that when i am a resolution (set using the icons) like 411 (mobile) not always the canvas show the style of the elements in that resolution. Canvas use the media query of the tablet and not the resolution that is set from the device manager for mobile.

Ex: I am on 411 resolution but the priority is the tablet breakpoint that canvas display the page.

![image](https://user-images.githubusercontent.com/26068332/74737465-9694ed00-525d-11ea-9104-bb600cc27425.png)

A solution is set forceClass = true?

**Comment by MariusDK** [comment]
@artf please help

**Comment by artf** [comment]
Hi @MariusDK I'm not really sure if I got your problem, can you create a little online demo to show better the issue?
Maybe you're talking about the difference between the canvas size and the actual media query in CSS? In that case, you can change them:
```js
// 900px is the size of the canvas, by default it will 
// be used also for the CSS media query
editor.DeviceManager.add('tablet2', '900px', {
 // You can use widthMedia option to change the media query in CSS
 widthMedia: '850px',
});
```
