### ISSUE TITLE
Set a button from Component settings  active on click

### ISSUE THREAD

**Issue by MariusDK** [artf/grapesjs#2584]
So i made a custom countdown with a button 
![image](https://user-images.githubusercontent.com/26068332/74738370-6f3f1f80-525f-11ea-963e-c6ddfa46dfb3.png)
The button set the countdown but i want to make the button active like other elements on click.

my code:

![image](https://user-images.githubusercontent.com/26068332/74738575-e379c300-525f-11ea-9d64-339a0481acc2.png)

**Comment by MariusDK** [comment]
@artf please help

**Comment by artf** [comment]
Unfortunately, the default button type is made to execute only one command, so if you have to do something fancy I'd suggest you to create your own trait https://grapesjs.com/docs/modules/Traits.html#define-new-trait-type
