### ISSUE TITLE
Countdown warning

### ISSUE THREAD

**Issue by MariusDK** [artf/grapesjs#2585]
![image](https://user-images.githubusercontent.com/26068332/74738689-250a6e00-5260-11ea-88d9-fea8cd2baa77.png)

I have a countdown on my custom trait with the type datetime-local. When i click the element this issue appears. 

My code:

![image](https://user-images.githubusercontent.com/26068332/74738845-6b5fcd00-5260-11ea-8e0d-7991189b1b23.png)

This happens also for your countdown: https://jsfiddle.net/apaoa5o2/14/

**Comment by artf** [comment]
The same as https://github.com/artf/grapesjs/issues/2615
