### ISSUE TITLE
[Suggestion] Grids and Scales for the editor

### ISSUE THREAD

**Issue by sdrebel** [artf/grapesjs#2590]
Hi @artf,

Working with Grapesjs has been great so far. It's easy to use once we understand it.  

I just have one suggestion, is it possible to include grids and  scale options in the editor?

**Comment by artf** [comment]
What do you mean by grids and scale?

**Comment by sdrebel** [comment]
Hi @artf,
Attached the image. Something like this

![image](https://user-images.githubusercontent.com/19382262/75219367-94351480-57c2-11ea-8708-fab4f0747a9f.png)

**Comment by artf** [comment]
No, this is not available and not even planned, but if someone wants to try to integrate it (even via a plugin) please let me know
