### ISSUE TITLE
Modal width

### ISSUE THREAD

**Issue by kaoz70** [artf/grapesjs#2592]
Hello, is there a way to set a modal's width, its currently set to 850px by CSS, but I would like to create a dialog with a small amount of text and its too big for this:

![image](https://user-images.githubusercontent.com/79406/74995098-d9052800-541d-11ea-9563-0ec3c8a3dc24.png)

But it would be great to get this:

![image](https://user-images.githubusercontent.com/79406/74995129-f33f0600-541d-11ea-936d-15570597a6f6.png)

Without overriding the CSS, because I would still like to use large modals.

I checked the source code and the docs, it seems the only properties you can set are title and content.

**Comment by artf** [comment]
> I checked the source code and the docs, it seems the only properties you can set are title and content.

Correct, probably it would be great to let it pass custom attributes... a PR would be welcome

**Comment by kaoz70** [comment]
OK, what I'm thinking is to create a function to be able to set the width like: setWidth('400px'), and also a method to set custom attributes: setAttributes({'data-custom-attribute': 123}).

I think 2 functions are needed because the width is controlled by CSS, and so is the modal's design, so just letting the user set the width is good enough in this case. The attribute function would be for any other case that's needed

 What do you think?

**Comment by artf** [comment]
Good idea, but to be honest, for now, I'd simply add a new `attributes` option to the [open](https://github.com/artf/grapesjs/blob/ff504880d634fa1f834286aa6d9180b94f553e75/src/modal_dialog/index.js#L92) function and apply them to the main container by taking care of keeping the [original class](https://github.com/artf/grapesjs/blob/ff504880d634fa1f834286aa6d9180b94f553e75/src/modal_dialog/view/ModalView.js#L130). 
So, in your case, you'd add a new class on open and the additional CSS to make that modal larger

**Comment by sunnykgupta** [comment]
I can help with this, @artf, let me know if it is okay to contribute.

**Comment by artf** [comment]
@sunnykgupta sure if @kaoz70 is not already on it, it would be great

**Comment by kaoz70** [comment]
Hello, sorry I'm piled with work now, if @sunnykgupta can give this a shot it would be great.

**Comment by marcepoblet** [comment]
> Correct, probably it would be great to let it pass custom attributes... a PR would be welcome

Hi,

This change was introduced in grapesjs?

we have some property to change the size of the modal?

**Comment by artf** [comment]
I'll add the `attributes` option to the `open()` method in the next release

**Comment by marcepoblet** [comment]
> I'll add the `attributes` option to the `open()` method in the next release

Perfect thanks

**Comment by ronaldaug** [comment]
For those who don't know how to use modal `attributes`. 
You can add option `opts.attributes` to modal's **open method** as below.
```javascript
const modal = editor.Modal;
const opts = {
    attributes: { class:'my-custom-class' }
}
modal.open(opt);
```
Because I didn't find how to use it in [the documentation here](https://grapesjs.com/docs/api/modal_dialog.html#modal).
