### ISSUE TITLE
flex-direction: column causes extreme slowdown in Chrome and Safari

### ISSUE THREAD

**Issue by Davidvlv** [artf/grapesjs#2593]
Hello,
We are having a major issue - our layouts use copious amounts of `display: flex; flex-direction: column;`, and this is causing extreme amounts of lag in Chrome and Safari browsers (not Firefox).

If the `flex-direction` style is set to `row`, there is no slowdown at all.

Sample: https://jsfiddle.net/gkeft254/
click on an inner element, duplicate and drag it around.

Video: 
[grapesjs slowdown.zip](https://github.com/artf/grapesjs/files/4234338/grapesjs.slowdown.zip)

**Comment by artf** [comment]
Yeah, it's definitely slower, not sure what is really happening but at the first guess, it might be this function which checks if the component is a block (eg. div) or an inline element (eg. span)
https://github.com/artf/grapesjs/blob/1214bbd957e88df78cd99491e53ab243010cd1ed/src/utils/Sorter.js#L549
Any help is welcome

**Comment by artf** [comment]
Not able to reproduce anymore
