### ISSUE TITLE
Asset Manager: add extra button field

### ISSUE THREAD

**Issue by eduardo-loyica** [artf/grapesjs#2594]
Is it possible to add an extra button to call any other action inside the default asset manager?

Something like this:
<img width="895" alt="Screen Shot 2020-02-21 at 16 45 45" src="https://user-images.githubusercontent.com/26910184/75078089-48385600-54ca-11ea-9ad0-6279e7a8b20e.png">

**Comment by pouyamiralayi** [comment]
#2316
