### ISSUE TITLE
Video component error

### ISSUE THREAD

**Issue by olgertpysqyli** [artf/grapesjs#2598]
I have a problem with video component.

I select provider and add the source of the video and then save the html, but when i load the html again to the editor video component source gets replaced with 
< svg xmlns="http://www.w3.org/2000/svg" width="100" viewBox="0 0 24 24" style="fill: rgba(0,0,0,0.15); transform: scale(0.75)"><path d="M8.5 13.5l2.5 3 3.5-4.5 4.5 6H5m16 1V5a2 2 0 0 0-2-2H5c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h14c1.1 0 2-.9 2-2z"></path></ svg>.

Is there any possibility to fix this issue I'm saving html from editor.getHtml() and giving it again with editor.setComponents();

![Screenshot from 2020-02-24 18-59-04](https://user-images.githubusercontent.com/17994334/75178423-5c818a80-5738-11ea-89fa-9097b796fe8e.png)

**Comment by artf** [comment]
Hi @olgertpysqyli you should follow this and rely on JSON data for editing https://grapesjs.com/docs/modules/Storage.html#store-and-load-templates
