### ISSUE TITLE
HELP - Wanted

### ISSUE THREAD

**Issue by ko06** [artf/grapesjs#2599]
## HELP 

Can we show the delete icon, duplicate icons once hover the element instead of clicking?

![Screenshot 2020-02-25 at 7 00 12 PM](https://user-images.githubusercontent.com/24521034/75251694-265c0d80-5801-11ea-9706-6b8a33f6bf38.png)
![Screenshot 2020-02-25 at 7 00 32 PM](https://user-images.githubusercontent.com/24521034/75251692-265c0d80-5801-11ea-94df-6182dda76bff.png)
![Screenshot 2020-02-25 at 7 00 32 PM](https://user-images.githubusercontent.com/24521034/75251701-28be6780-5801-11ea-8c91-bc24faa398b6.png)

**Comment by pouyamiralayi** [comment]
@ko06 [#1433 comment](https://github.com/artf/grapesjs/issues/1433#issuecomment-529290842)

**Comment by ko06** [comment]
=
