### ISSUE TITLE
GrapeJS for existing CMS

### ISSUE THREAD

**Issue by orionseye** [artf/grapesjs#2600]
I am experimenting for a while with GrapeJS and already incorporated to our existing (custom) CMS, replacing tinyMCE.
Since the two approaches are different, i would like to ask for your assistance how to handle the page saving after finishing editing the content.
Right now, the approach is to extract contents of a standard defined area 
<div class='editableHtmlArea' id='EDITABLE_CONTENT'>
<?php /*** EDITABLE_CONTENT ***/ ?>

..then post data in between and place it back (saving) to same file

What is your experience / approach, recommendation?
Meanwhile, i tried 'editor.destroy()' before saving the data, but could not make it work .. so far :)

**Comment by pouyamiralayi** [comment]
@orionseye 

> ..then post data in between and place it back (saving) to same file

if you are going for a custom approach, i suggest you see [setup remote storage](https://grapesjs.com/docs/modules/Storage.html#setup-remote-storage) otherwise i do not understand what you mean by place it back!
and in case you mean the resulted html, you can always receive that by calling ``editor.getHtml()`` and ``editor.getCss()``; no need to say you can do this regularly upon each save leveraging [storage end](https://grapesjs.com/docs/modules/Storage.html#events) callback.
Cheers!

**Comment by orionseye** [comment]
@pouyamiralayi 
Thank you for tip, i am considering to switch to remote storage, but for time being, the CMS was build to store (edited) content into flat file, the file someone currently edits.
Each page has its own index.php, so GrapeJS is active once the 'edit' button is clicked.
In that case, and after edit, the editor has to be destroyed, to save the template edits only.
That's what i meant.

**Comment by orionseye** [comment]
editor.destroy() is not an option, since all the the html block declared with .init ..is gone as well.
I need  a generic solution, to attach editor and then detach from the edited dom.
Can GrapeJS do this? Could'n find solution in the documentation

**Comment by pouyamiralayi** [comment]
@orionseye 

> editor.destroy() is not an option, since all the the html block declared with .init ..is gone as well.

you can call ``editor.getHtml`` and ``editor.getCss`` before destroying.
Cheers!

**Comment by orionseye** [comment]
That is beau.ti.ful !
3 lines and it works like a rocket.. get.Html even takes care to output valid html5
Sorry Pouya that i didn't think about that myself.
Thanks so much
