### ISSUE TITLE
[QUESTION/BUG?] Dragging second block don't haveCSS 

### ISSUE THREAD

**Issue by cristianumali22** [artf/grapesjs#2601]
Hi! I've manage to create different blocks with their own HTML and CSS using BlockManager. But once I drag the same block, the CSS is not working. I've already debug it. And I found that its renaming the my blocks' id. Example. I have a table with an id of `custom-table`. And when I drag the same table, the id becomes `custom-table-2`. But the css with a selector of `#custom-table` does not change. So it will not get the style. How to fix this issue. Thank you

**Comment by rjrodriguezalvarez97** [comment]
Try styling with classes as selector rather than ids

**Comment by artf** [comment]
You can't have multiple elements with the same ID (against also [HTML5 specs](https://www.w3.org/TR/2011/WD-html5-20110525/elements.html#the-id-attribute)) so the editor tries to fix that, so yeah, you have to use classes
