### ISSUE TITLE
[BUG] Storage Manager type:remote breaks containment

### ISSUE THREAD

**Issue by CharlesBilbo** [artf/grapesjs#2603]
It seems that whenever the parameter type: 'remote' is added to the storageManager it causes the container to break thus putting elements in visual editor that should not be selectable such as the iframe ( https://imgur.com/a/dytYIV7 ).

`      var editor  = grapesjs.init({
        allowScripts: 1,
        avoidInlineStyle: 0,
        container: '#gjs',
        fromElement: 1,
        forceClass: true,
        forceID: true,
        height: '100%',
        showOffsets: 1,
        assetManager: {
          embedAsBase64: 1,
          assets: images
        },
        storageManager: {
          type: 'remote',
          urlStore: '/admin/pages',
          autosave:0,
          headers: {
            "X-CSRF-TOKEN": $('meta[name="csrf-token"]').attr('content'),
          },
          contentTypeJson: true,
        },`

**Comment by artf** [comment]
@CharlesBilbo if this is a BUG, you have to open the issue correctly by following the template and provide a reproducible demo. From what I see now it might be something wrong on your side, you have the `gjs-*` class applied on the body?! Definitely something odd to see
