### ISSUE TITLE
Style gets lost on deselecting a component when using rte.exec method

### ISSUE THREAD

**Issue by AbdiasM** [artf/grapesjs#2610]
Hi @artf,

When setting the backcolor/forecolor (or any other formatting like fontsize, etc) using the RichTextEditor toolbar, the formatting gets lost on deselecting > selecting and deselecting the component again. Please see the demo on code pen - https://codepen.io/AbdiasM/pen/LYVydpr
Moreover, the RTE toolbar doesn't show again on entering edit mode.

Steps to reproduce:
1. Drop a text block
2. Double click the text block and select some text (eg. here)
3. Click on the last icon in the RTE Toolbar and set the backcolor
Observe: Backcolor is applied
4. Click outside the text block
5. Double click text block again to enter edit mode
6. Click outside text block again
Observe: Backcolor is lost
7. Double click inside text block again
Observe: RTE toolbar doesn't show

Could you please take a look into this. This is kind of crucial.

**Comment by AbdiasM** [comment]
Anyone?

**Comment by AbdiasM** [comment]
Solved this by setting 

    avoidInlineStyle: 0,
    forceClass :0,

in editor's config

**Comment by artf** [comment]
Thanks for the report @AbdiasM we're already aware of the issue, it should be fixed once #1470 will be solved (so you can subscribe to the issue there)
