### ISSUE TITLE
[HELP] Dragging external content to Canvas

### ISSUE THREAD

**Issue by orionseye** [artf/grapesjs#2611]
I am trying to add d&d functionality from a modal which lists a bunch of html files (html snippets)  .. into the editor canvas.
Each of them enclose the content with a `<section>`

I tried to use 'canvas:dragdata' to allow dropping into canvas
```
editor.on('canvas:dragdata', (dataTransfer, result) => {
          if(el.tagName == 'SECTION' && el.classList.contains('section')){
		result.content = { type: 'text/html'}
          }
		
});
```
As i understood, this is to extend the file types can be dropped, GrapesJS supports text + image, so above approach should work? 

Meanwhile, and after playing around with
`editor.DomComponents.addType`
i am changing the scope of my issue ..see comment below

**Comment by orionseye** [comment]
And of course, since type 'text/html' is not found, i have (obviously) to add it

```
editor.DomComponents.addType('text/html', {
  isComponent: el => el.tagName === 'SECTION',

  model: {
    defaults: {
      tagName: 'SECTION',
      draggable: '*',
      droppable: false, 
      attributes: {
        type: 'text/html'
      }
    }
  }
});
```
So far so good, the element is not dragged into the canvas as:
`<section data-gjs-type="text/html" draggable="true" data-highlightable="1" type="text/html" id="i51i"></section>`

But the content in-between is missing

**Comment by artf** [comment]
Here you can find how to do that
https://github.com/artf/grapesjs/issues/2595

**Comment by orionseye** [comment]
I am sorry to re-open this issue, as i can not follow the idea behind the solution provided here:
https://github.com/artf/grapesjs/issues/2595

Whatever is dragged from outside the editor, is pure text. And even if you drag any of the basic blocks inside the canvas, you get something like:
`{"type":"text","content":"Insert your text here","style":{"padding":"10px"},"activeOnRender":1}`

So, what's finally the correct approach to drag any html snippets outside from the editor by
a) keeping the app's blocks intact
b) retain the html of the snippets as dragged into canvas?

For example, i made a `<seection>` snippet which just won't keep the original html once dragged into the canvas
https://jsfiddle.net/pivi/f7jyqt6d/34/
