### ISSUE TITLE
GrapesJs Asset Manager Not working with iPad & Touch enabled devices

### ISSUE THREAD

**Issue by pradeeshattlee** [artf/grapesjs#2612]
Hey @artf 
I have a question around Asset Manager. When uploading an image via computer or URL You can create image blocks with the command from the left panel and edit them with double click everything Seems to work perfectly. But when I try the same in an iPad or a Touch-enabled device it doesn't work I used this Plugin so the other features are working.

URL - https://github.com/artf/grapesjs-touch

The asset manager doesn't pop up on the iPad - chrome, firefox, and safari. 

And the editor canvas scroll doesn't work on the iPhone - chrome, firefox, and safari. 

What am I missing?

Thanks in advance.

**Comment by bgrand-ch** [comment]
Hello,

For future questions or technical issues, which aren't bugs, GitHub's [Discussions](https://github.com/artf/grapesjs/discussions) tab is the place to be.

Don't forget to close this issue if it is resolved or write a new detailed message in [Discussions](https://github.com/artf/grapesjs/discussions) -> [Q&A](https://github.com/artf/grapesjs/discussions/categories/q-a) category (and close this issue).

Thank you for your understanding.
