### ISSUE TITLE
Dragging blocks into another block

### ISSUE THREAD

**Issue by Rasazna** [artf/grapesjs#2613]
## WARNING
READ and FOLLOW next 5 steps, then REMOVE them before posting the issue

1. Follow CONTRIBUTING Guidelines https://github.com/artf/grapesjs/blob/master/CONTRIBUTING.md
2. Use the GitHub Issues EXCLUSIVELY for BUGS, FEATURE REQUESTS or QUESTIONS. Prefix the title of the issue with its context, eg. `[Bug]: ....`
3. Do a quick SEARCH first, to see if someone else didn't open the same issue
4. DON'T ASK to create examples/code for you, read DOCS and APIs first, then you can post what you have tried (we'd like to see your code) and what you're unable to achieve
5. All relative statements/questions have to be filled/answered, otherwise, the issue might be CLOSED

## You're submitting a BUG
  1. Are you using the latest release (older versions are NOT supported)?
      1. If you're not sure, type `grapesjs.version` in console and press ENTER
  1. Are you facing the bug with your local copy of GrapesJS or with the current demo?
  1. If a local copy
      1. Indicate all informations about your OS, browser and GrapesJS version.
      1. Are you able to reproduce the bug from the demo?
  1. What is the expected behavior?
  1. What happens instead?
  1. If you're able to reproduce the bug indicate all the necessary steps
  1. Attach screenshots (using KAP/LICEcap), screencasts or live demo
     1. JSFiddle Starter template https://jsfiddle.net/szLp8h4n
     1. CodeSandbox Starter template https://codesandbox.io/s/1r0w2pk1vl

## You're submitting a FEATURE REQUEST
  1. Be sure to work on the latest version, as the feature might be already there
  1. Keep in mind that the feature should be considered valid to use for everyone, not only for your case

**Comment by Rasazna** [comment]
I am using gridly and high charts as two different blocks. I  will drag the gridly block first and drag the the chart into the gridly block. How can this be done. I am only able to place the chart around the gridly block. But I want it inside the gridly block. Each gridly block has an div element where i want to add the chart inside the div element.

**Comment by artf** [comment]
Please read the documentation first, seems like you have no idea how [Components](https://grapesjs.com/docs/modules/Components.html) work...

**Comment by Rasazna** [comment]
can you just help me how to do it . I still could not figure it out. A sample code would be really helpful.
