### ISSUE TITLE
[Bug]: 'range' trait type not found

### ISSUE THREAD

**Issue by vinu-noldor** [artf/grapesjs#2615]
Hi @artf ,

Thank you for creating this amazing repo! I came across a bug that is present in the website demo (https://grapesjs.com/demo.html) and in my local version. When I add a map block and I click on it to change trait values, I get an error like this in the console:
![image](https://user-images.githubusercontent.com/61001081/75694037-91e62500-5cb0-11ea-90fd-7d6606b6e30a.png)
I looked through the main grapesjs repo and couldn't find this type defined. Please can you investigate this.

**Comment by artf** [comment]
Seems like a false positive, I've put the warning to help in debugging but forgot that not found types will fallback to simple inputs with `<input type="TRAIT-TYPE"...`. I'll try to fix it for the next release

**Comment by vinu-noldor** [comment]
Thanks @artf
