### ISSUE TITLE
Enable Drag Mode to inner of a  single component instead of editor

### ISSUE THREAD

**Issue by rufusnguyen** [artf/grapesjs#2617]
Hi @artf ,
I set dragMode of my Grapesjs builder to "absolute" and then build a section component to ensure that all other components must be placed in section component. 
![image](https://user-images.githubusercontent.com/6136341/75757994-f4e5c380-5d65-11ea-9c3e-59db73b88472.png)
However, section component should be ignore of being "absolute", it should be static. I had tried: 

- Remove dragMode: absolute for builder
- Add dmode: 'absolute' to section component
But no luck. Could you please advise?

**Comment by artf** [comment]
Well if you declare dragMode in the init config, that will be the default for ALL the components, then, if you want, you can change the dragMode per component https://github.com/artf/grapesjs/issues/1936#issuecomment-521269499
