### ISSUE TITLE
[QUESTIONS]: How to close tabs at start.

### ISSUE THREAD

**Issue by verloka** [artf/grapesjs#2618]
Hi.
How to automatically close tabs with blocks? I mean that the tabs should be closed when the editor starts.

![Untitled](https://user-images.githubusercontent.com/5623092/75777633-f6f85400-5d5e-11ea-94f7-260556441eac.png)

**Comment by artf** [comment]
https://github.com/artf/grapesjs/issues/318#issuecomment-330210088
