### ISSUE TITLE
[Bug]: Default image placeholder's src attribute generated / exported as <svg> element

### ISSUE THREAD

**Issue by mcottret** [artf/grapesjs#2619]
Hi, and thanks for the great library !

We might have found the following bug when playing around with it:

When adding a new default "Image Block" without further configuration (leaving the default image placeholder), the exported / generated HTML code embeds the default `svg` element as the image's `src` attribute value (cf attached screenshots).

![Screenshot 2020-03-03 at 4 31 40 PM](https://user-images.githubusercontent.com/9916749/75793303-7857e280-5d6f-11ea-9fa3-340cfb3a6be1.png)
![Screenshot 2020-03-03 at 4 31 06 PM](https://user-images.githubusercontent.com/9916749/75793310-78f07900-5d6f-11ea-86f4-95afc496edb7.png)

After digging a bit into the code, it appears that the `grapesjs/src/dom_components/model/ComponentImage.js`'s `getAttrToHTML` function should call `this.getSrcResult` (not sure whether or not to use the `fallback` option) rather than `this.get('src')` to retrieve the base64 encoded image `src` attribute (cf https://github.com/artf/grapesjs/blob/dev/src/dom_components/model/ComponentImage.js#L78) .

Note: this would not satisfy a case where the `embedAsBase64` option would be set to `false`, maybe in this case a public image placeholder URL could be used (TBD) ?

I'd be happy to open a PR to fix it, let me know :)

**Comment by artf** [comment]
Thanks for the report Mathieu

> grapesjs/src/dom_components/model/ComponentImage.js's getAttrToHTML function should call this.getSrcResult (not sure whether or not to use the fallback option) rather than this.get('src') to retrieve the base64 encoded image src attribute

Correct, ignore the fallback option, it's used in the canvas only when the image is failed to load.

> Note: this would not satisfy a case where the embedAsBase64 option would be set to false, maybe in this case a public image placeholder URL could be used (TBD) ?

`embedAsBase64` option is for the file upload, this has nothing to do with this issue

So... go ahead for the PR! 👍

**Comment by mcottret** [comment]
Thanks ! #2620 opened.
