### ISSUE TITLE
[Question] Publish the edited canvas with injected scripts

### ISSUE THREAD

**Issue by bungambohlah** [artf/grapesjs#262]
Hi @artf this is very nice web builder framework and can integrate with anyone

I wanna to ask, how to publish the edited canvas or get fully html canvas code with injected scripts from :

```javascript
var editor  = grapesjs.init({
...
  canvas: {
    scripts: [
      "https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"
    ]
   },
...
```

Thank you and sorry for my bad english

**Comment by artf** [comment]
Hi @bungambohlah I'm glad you like it and don't worry about your english, it's always good :)
Anyway, when you inject stuff via canvas config (JS or CSS) it means that you have to add them **manually** later in your final page.

eg. `editor.js`
```js
var editor  = grapesjs.init({
...
  canvas: {
    scripts: ['...script1.js', '...script2.js']
    styles: ['...style1.css', '...style2.css'],
   },
...
```
eg. `final-page.html`
```html
<script src="...script1.js"></script>
<script src="...script2.js"></script>
<link rel="stylesheet" href="...style1.css">
<link rel="stylesheet" href="...style2.css">

{{ HTML FROM GRAPESJS }}
```
