### ISSUE TITLE
[Bug] editor.Panels.addPanel duplicate buttons 

### ISSUE THREAD

**Issue by YUzhva** [artf/grapesjs#2621]
While creating a custom plugin, in case, when `editor.Panels.addPanel` is using inside plugin function - buttons are duplicated.

Example:
https://jsfiddle.net/kncdah8b/

Buttons are not duplicated:
- when using single `Panels.addButton` API while loop buttons separately
- when adding panel after editor `const editor = grapesjs.init({})` has been created

Currently, I'm using the next trick to avoid the duplications:
```javascript
function gjsPlugin(editor) {
  editor.on('load', () => {
    editor.Panels.addPanel({
      id: 'custom-panel',
      el: '.custom-panel',
      buttons: [
        {
          id: 'PANEL_ACTION.EXPT',
          className: 'fa fa-code',
          command: 'export-template',
          attributes: { title: 'View code' }
        }
      ]
    });
  });
}
```

**Comment by YUzhva** [comment]
Closing the issue, as I found the other solution:

```javascript
const panelCusom = editor.Panels.addPanel({
    id: 'panel__custom',
    el: '.panel__custom'
  });

const panelCusomButtons = panelCusom.get('buttons');
panelCusomButtons.add(topBarButtonsCenter);
```

But the issue with `editor.Panels.addPanel({ buttons: [] });` still exist (=

**Comment by artf** [comment]
Thanks @YUzhva for the report and the solution. I'll try to check this out

**Comment by ColdTuna** [comment]
Same here, I tested the panels example (Getting started) in the docs too and keep getting duplicate buttons. @yuzhva solution works, thanks :)

**Comment by FaisalShaikhHA** [comment]
Hi, @artf  facing the same issue and @yuzhva solution not working for me as well.
I am adding panels from (Getting started) docs but with different names.
![Screenshot on 2022-11-19 at 12_44_11](https://user-images.githubusercontent.com/102785785/202841276-cb82cad6-8516-4a64-8450-7dda2e0bef35.png)

**Comment by Adarshsingh2k** [comment]
did any one find any resolution for this ug in react
