### ISSUE TITLE
[Bug]: Asset manager addType function not working after reload page

### ISSUE THREAD

**Issue by light-effect** [artf/grapesjs#2622]
`am.addType('svg-icon', {
  view: {
    // `getPreview()` and `getInfo()` are just few helpers, you can
    // override the entire template with `template()`
    // Check the base `template()` here:
    // https://github.com/artf/grapesjs/blob/dev/src/asset_manager/view/AssetView.js
    getPreview() {
      return `<div style="text-align: center">${this.model.get('svgContent')}</div>`;
    },
    getInfo() {
      // You can use model's properties if you passed them:
      // am.add({
      //  type: 'svg-icon',
      //  svgContent: '<svg ...',
      //  name: 'Some name'
      //  })
      //  ... then
      //  this.model.get('name');
      return '<div>SVG description</div>';
    },
  },
  isType(value) {...}
})`

getPreview and getInfo functions do not apply if assets load from local storage.

**Comment by artf** [comment]
Follow the issue template if you're submitting a bug, you have to create, at least, a reproducible demo
