### ISSUE TITLE
[BUG] Generated styles do not escape colons in classnames

### ISSUE THREAD

**Issue by kierenayima** [artf/grapesjs#2624]
Currently using GrapeJS for a project that I am working on locally and integrated it with some tailwind UI components.

It mostly works great, but I have noticed that making changes on some elements does not work (for example, changing text color or formatting). 

Looking at it further I can see that this is because the generated styles do not escape colons from the classes grapesJs uses to make the CSS selector. 

For example, this is a selector grapeJs outputs: 
```
.text-3xl.leading-9.font-extrabold.text-gray-900.sm:text-4xl.sm:leading-10.lg:text-5xl.lg:leading-none{
  color:#3866c2;
}
```

The selector should actually be something like this:
```
.text-3xl.leading-9.font-extrabold.text-gray-900.sm\:text-4xl.sm\:leading-10.lg\:text-5xl.lg\:leading-none{
  color:#3866c2;
}
```

**Comment by artf** [comment]
Thanks for the report @kierenayima 
Selectors will be escaped in the CSS in the next release
