### ISSUE TITLE
[QUESTION] Move component up or down through panel button

### ISSUE THREAD

**Issue by ikenderham** [artf/grapesjs#2626]
Hello i thinking of making a function that move component up or down in  the canvas, when a button beeing pushed. Is it possible, and can anyone show me how to do it? Maybe this future is allways there?

**Comment by artf** [comment]
You can do something like this to move components
```js
const moveUp = component => {
	const comp = component || editor.getSelected();
	const parent = comp.parent();
	const index = comp.index();

	if (index > 0) {
		comp.remove();
		parent.append(comp, { at: index - 1 });
	}
}

const moveDown = component => {
	const comp = component || editor.getSelected();
	const parent = comp.parent();
	const index = comp.index();

	if (index < parent.components().length - 1) {
		comp.remove();
		parent.append(comp, { at: index + 1 });
	}
}
```

**Comment by ikenderham** [comment]
Hello 

Thanks for the answer.. But how do I add the button to component toolbar? I tried the examples on issues/266 but its not working here. Can i overrule the toolbar in another file, so i dont need to change the core files?

**Comment by ikenderham** [comment]
I found out how to do that. the code you provided me is not working for me.

I tried to add it in a command, but its not moving the component up or down. 

Here is a example: If i have a row with content inside, then i need to move the container up over another container.  hope you understand me 

`        commands: {
    defaults: [
      {
        // id and run are mandatory in this case
        id: 'my-command',
        run() {
          const moveUp = component => {
          const comp = component || editor.getSelected();
          const parent = comp.parent();
          const index = comp.index();

          if (index > 0) {
            comp.remove();
            parent.append(comp, { at: index - 1 });
          }
        }
        },
      }, {
        id: '...',
        // ...
      }
    ],
  },


editor.DomComponents.addType('link', {
    isComponent: el => el.tagName == 'A',
    model: {
      defaults: {
        toolbar: [{
        attributes: {class: 'fa fa-link'},
        command: 'my-command',
      },{
        attributes: {class: 'fa fa-clone'},
        command: 'tlb-clone',
      }

`

**Comment by artf** [comment]
> I tried to add it in a command, but its not moving the component up or down.

This is because you have have to use JS properly
```js
run() {
	const moveUp = component => {...
```
it'll never work if you create the function `moveUp` and then you don't call it...

**Comment by ikenderham** [comment]
I do have run() inside the code? :-)

    defaults: [
      {
        // id and run are mandatory in this case
        id: 'my-command',
        run() {
          console.log('Køre kommandoen');

const moveUp = component => {
  const comp = component || editor.getSelected();
  const parent = comp.parent();
  const index = comp.index();

  if (index > 0) {
    comp.remove();
    parent.append(comp, { at: index - 1 });
  }
}
        },
      }, {
        id: '...',
        // ...
      }
    ]

how should you understand your answer?

**Comment by ikenderham** [comment]
If i just put a alert('test'); inside instead of, i got a alert when i push the button.

**Comment by ikenderham** [comment]
Ahhh it just worked now. BUt what do run do?

**Comment by ikenderham** [comment]
Right now i have this command on a specifc component -> link. How can i put this button on all components?  :-) Thx for helping me

**Comment by ikenderham** [comment]
It seems to be working.

Last question, hope you can answer me here i tried everything now

How can i use these buttons on components that have a specific class?

I tried to `editor.DomComponents.addType('testmodul', {
   

 

    isComponent: el => el.className == 'row segment',
    model: {
      defaults: {
          toolbar: [{
        attributes: {class: 'fa fa-arrow-up'},
        command: 'moveUp-command',
      },
      {
        attributes: {class: 'fa fa-arrow-down'},
        command: 'moveDown-command',
      },{
        attributes: {class: 'fa fa-clone'},
        command: 'tlb-clone',
      },{
        attributes: {class: 'fa fa-trash'},
        command: 'tlb-delete',
      }],
      },
    },
});`

But here i can only select these class, if there are another class it wouldnt work. I tried el.hasClass, but its not working.

Thx for help

**Comment by artf** [comment]
you can create different components with other toolbars, you can change it by class
