### ISSUE TITLE
New Customized Editor by DevFuture.pro

### ISSUE THREAD

**Issue by GoodPHP** [artf/grapesjs#2627]
Hi There,

We want promote our new design for GrapesJS. 

Our work: https://github.com/GoodPHP/GrapesJS-devfuture

You can write to us any questions: support@devfuture.pro

Write your opinion below. Do you like?

**Comment by pouyamiralayi** [comment]
@GoodPHP great work! do you have plans on integrating grapesjs with a cms?

**Comment by GoodPHP** [comment]
> @GoodPHP great work! do you have plans on integrating grapesjs with a cms?

yeh, I did it some time. I have integrated grapesjs with Laravel, Codeigniter, Wordpress, Custom PHP, etc.

**Comment by pouyamiralayi** [comment]
@GoodPHP awesome! have you implemented dynamic data layer using the CMS?

**Comment by pouyamiralayi** [comment]
like below:
<img width="349" alt="Desktop 2017-03-14 at 6 06 23 PM" src="https://user-images.githubusercontent.com/53266765/76199255-c7d15f00-6204-11ea-8c9b-52a4ea1f2dc1.png">
<img width="351" alt="Desktop 2017-03-14 at 5 10 46 PM" src="https://user-images.githubusercontent.com/53266765/76199261-cb64e600-6204-11ea-83da-fb2a9c228602.png">

**Comment by GoodPHP** [comment]
> have you implemented dynamic data layer using the CMS?

I implemented page builder websites like:

https://wix.com/ 
https://www.websitebuilder.com/ 
https://www.squarespace.com/ 

Where users can buy domain, connect exist domain, create website, publish this website, etc

I have a lot of groundwork for GrapesJS.

**Comment by artf** [comment]
Great work @GoodPHP it would be also super cool to see some live demo :)

**Comment by GoodPHP** [comment]
Ok
