### ISSUE TITLE
Button to switch designer mode

### ISSUE THREAD

**Issue by micker** [artf/grapesjs#2630]
hello
its possible to add a button to switch of designer mode ? absolute / translate ?
regards

**Comment by pouyamiralayi** [comment]
@micker  you need a [command](https://grapesjs.com/docs/modules/Commands.html#basic-configuration) for that which executes: ``editor.setDragMode('absolute')``. for panels & buttons you can refer to [getting started](https://grapesjs.com/docs/getting-started.html#panels-buttons) guide.
Cheers!

**Comment by micker** [comment]
hi thanks
did you think it possible to mix twice mode for more ? are its too early ?

**Comment by pouyamiralayi** [comment]
@micker  yes! you can do it per component: [#1936 comment](https://github.com/artf/grapesjs/issues/1936#issuecomment-521269499)
Cheers!

**Comment by micker** [comment]
i see the demo of bubble .. its realy cool can you explain more how to acheive same things ?

**Comment by pouyamiralayi** [comment]
@micker can you explain what specific feature you are interested in bubble that you want to achieve in grapesjs?

**Comment by micker** [comment]
i didn't understand how tomix absolute and standar mode to use like this :
- 1 create a column (rezizable and absolute)
- 1 create a block text and mode inside column (block will be absolute inside the column)
result column can be "movable" with text block inside
thanks for your prompt support

**Comment by pouyamiralayi** [comment]
@micker 

> create a column (rezizable and absolute)

i don't think if it is possible to have both modes at the same time for a particular component.

you can change the mode constantly by checking the component type at ``component:selected`` [event](https://grapesjs.com/docs/api/editor.html#components) to see if it is a text block and check the [parent](https://grapesjs.com/docs/api/component.html#parent), so in case the parent is the desired column, change it's mode to absolute!
Cheers!

**Comment by micker** [comment]
ok maybe a switcher mode can be in basic panel ?

**Comment by artf** [comment]
@micker GrapesJS becomes more API oriented and less UI dependent, so you should create buttons/panels/switches on your own. 
Maybe in the future I'll add the UI module in the core (to help building the UI using GrapesJS elements) but it's just an idea, still far from being achieved

**Comment by micker** [comment]
cool thanks !
you explain : data-gjs-resizable
that exist with dragmode ?
