### ISSUE TITLE
textNoElement not working

### ISSUE THREAD

**Issue by HansSchouten** [artf/grapesjs#2631]
I am trying to update the textNoElement of the Style and TraitManager, but it does not seem to be working.

```
let editor = grapesjs.init({
  container: '#gjs',
  traitManager: {
    textNoElement: 'Hello Trait Manager'
  },
  styleManager: {
    textNoElement: 'Hello Style Manager',
  }
});
```
See the result here:
https://jsfiddle.net/zrobkL80/5/

Also the default StyleManager sectors disappear, any suggestion on what I am doing wrong?
I am using the the latest GrapesJS version (0.15.10).

**Comment by artf** [comment]
Those options were removed, you have to use the [i18n module](https://grapesjs.com/docs/modules/I18n.html)

**Comment by HansSchouten** [comment]
Ok thanks, I will look into it.
