### ISSUE TITLE
Rezize block with drag and drop

### ISSUE THREAD

**Issue by micker** [artf/grapesjs#2632]
Hello i trying the absolute mode ! its realy good but to be complet with this designer mode did you plan to add rezize module via drag and drop ?
regards

**Comment by pouyamiralayi** [comment]
@micker you must specify ``resizable:true`` on your [component type definition](https://grapesjs.com/docs/modules/Components.html#component-definition).
Cheers!

**Comment by micker** [comment]
ok i will check it thanks
did you have a demo ?

**Comment by pouyamiralayi** [comment]
@micker 
```
 editor.DomComponents.addType('image', {
            model: {
                defaults: {
                    resizable:true,
                    traits: ['src']
                }
            }
        })
```
Cheers!

**Comment by micker** [comment]
ok cool thanks !

**Comment by micker** [comment]
i try this
`			editor.BlockManager.add(\'fcfield\', {
				label: \'Flexicontent Field\',
				category: \'Data\',
				content: \'<div style="display: inline-block">{flexi_field:FIELDNAME  item:{{fc-item-id}}  method:display}</div>\',
				select: true,
				activate: true,
				rezizable:true,
				attributes: { class:\'fc-iblock fa fa-database\' },
			});`
but i didn't find how to rezize ...

**Comment by pouyamiralayi** [comment]
@micker if you want to go with blocks, you have to do it like this:
```
editor.BlockManager.add('test', {
    label: 'test',
    content: '<div data-gjs-resizable="true">content</div>',
})
Cheers!
```

**Comment by micker** [comment]
very cool works thanks
