### ISSUE TITLE
[HELP] Adding new category for later use (without blocks yet)

### ISSUE THREAD

**Issue by orionseye** [artf/grapesjs#2638]
How do i define a new category, to use for later blocks i create ..without yet assigning a block to it.. and keep it closed by default?

I mean this one can be used to for a block added, but what if i have multiple blocks to add to same category again and again? Is there a way to have the category id, label, open state defined elswhere, instead repeating the process?
```
editor.BlockManager.add('block-id', {
    ...
    label: 'Label content',
    category: {
        id: 'some-cat', 
        label: 'Some cat', 
        open: true
    }
})
```

To collapse the default ones i used
`editor.BlockManager.getCategories().each(ctg => ctg.set('open', false))`

**Comment by orionseye** [comment]
Ok, seems that when i don't use `canvas:dragdata` and set to drag outerHtml, the whole approach works. `.setData('text', `${target.outerHTML}`);`
Is this correct?

**Comment by artf** [comment]
Once the category is created you can use its ID in this way `category: 'some-cat'
