### ISSUE TITLE
Code editor Support

### ISSUE THREAD

**Issue by vFire** [artf/grapesjs#2641]
I am wondering is it possible to have a code editor in GrapesJs, if will be much better for frontend developer.
And if it support sysn scroll will be better, e.g. when you right click the element, the code will auto scroll and hightlight the code block related to the element.

**Comment by vFire** [comment]
And an option we can disable the style manager, since in the real world end user if not a technical guy , he will not understand css style and the style is too complicated, and for the frontend developer, without a code editor, it is too hard to work, if you want a real and good designed responsive page, these inline style will cause a lot of problems.

**Comment by vFire** [comment]
Further more, I just want to set some rule in particular level of tag it will be selectable and visually editable, but beyond the rule the visual won't change it, alternately we can just select it in the code editor and directly edit by row code. E.g. only the root .page under body can be drag to sort and droppable.

**Comment by artf** [comment]
This might be a good candidate for a plugin https://grapesjs.com/docs/modules/Plugins.html
