### ISSUE TITLE
[QUESTION] Body sectors

### ISSUE THREAD

**Issue by verloka** [artf/grapesjs#2646]
How to add the Dimension sector for the body?

![Untitled](https://user-images.githubusercontent.com/5623092/76606236-94e7dd80-651a-11ea-9cf0-80e229ae526f.png)

**Comment by pouyamiralayi** [comment]
@verloka here is the [example](https://github.com/artf/grapesjs/blob/53cfe888a0ee5d49c43cd4e3fa5daf0b55f8277c/demo.html#L1034)
Cheers!

**Comment by verloka** [comment]
> @verloka here is the [example](https://github.com/artf/grapesjs/blob/53cfe888a0ee5d49c43cd4e3fa5daf0b55f8277c/demo.html#L1034)
> Cheers!

This is a plugin configuration that I do not use, any other suggestions?

**Comment by pouyamiralayi** [comment]
@verloka  here is how to add sectors inside[ grapesjs init config](https://grapesjs.com/docs/getting-started.html#style-manager):
```
styleManager: {
    sectors: [{
        name: 'Dimension',
        open: false,
       //,,,
```
use the code i posted for you as the complete example.
Cheers!

**Comment by verloka** [comment]
> @verloka here is how to add sectors inside[ grapesjs init config](https://grapesjs.com/docs/getting-started.html#style-manager):
> 
> ```
> styleManager: {
>     sectors: [{
>         name: 'Dimension',
>         open: false,
>        //,,,
> ```
> 
> use the code i posted for you as the complete example.
> Cheers!

Do you know a way to add only the Dimension sector without overriding all other sectors?
I need to add the Dimension sector for Body element (wrapper) only and without affecting other sectors.

**Comment by pouyamiralayi** [comment]
@verloka please refer to the [addSecotor api](https://grapesjs.com/docs/api/style_manager.html#addsector)
Cheers!

**Comment by verloka** [comment]
> @verloka please refer to the [addSector api](https://grapesjs.com/docs/api/style_manager.html#addsector).
> Cheers!

What i do wrong?
https://codepen.io/verloka/pen/KKpoopv

**Comment by mcottret** [comment]
Hi @verloka & @pouyamiralayi,

The sectors list seems to be common to all applications components.

However, components hold a list of attributes that can be edited through the style manager panel when they are selected, which is used to filter the application sectors.

From the [Component API Reference](https://grapesjs.com/docs/api/component.html#component), you can use the `stylable`, & `unstylable` properties to include and / or exclude editable attributes.

By default, the "Body" element (referred to as "Wrapper"), seems to hold the following `stylable` property: `["background", "background-color", "background-image", "background-repeat", "background-attachment", "background-position", "background-size"]`, which is why even with default sectors, it only shows the "Decorations" one on the style manager.

You'd need to edit its `stylable` property in order to add the "Dimension" related ones, which could be achieved like so:

`editor.getWrapper().set('stylable', editor.getWrapper().get('stylable').concat(['width', 'height', 'max-width', 'min-height', 'margin', 'padding']));`

**Comment by verloka** [comment]
> Hi @verloka & @pouyamiralayi,
> 
> The sectors list seems to be common to all applications components.
> 
> However, components hold a list of attributes that can be edited through the style manager panel when they are selected, which is used to filter the application sectors.
> 
> From the [Component API Reference](https://grapesjs.com/docs/api/component.html#component), you can use the `stylable`, & `unstylable` properties to include and / or exclude editable attributes.
> 
> By default, the "Body" element (referred to as "Wrapper"), seems to hold the following `stylable` property: `["background", "background-color", "background-image", "background-repeat", "background-attachment", "background-position", "background-size"]`, which is why even with default sectors, it only shows the "Decorations" one on the style manager.
> 
> You'd need to edit its `stylable` property in order to add the "Dimension" related ones, which could be achieved like so:
> 
> `editor.getWrapper().set('stylable', editor.getWrapper().get('stylable').concat(['width', 'height', 'max-width', 'min-height', 'margin', 'padding']));`

Ok, this is better BUT
https://codepen.io/verloka/pen/BaNrrzL
look at margins for the Body and other element in the Dimensions sector
![Безымянный](https://user-images.githubusercontent.com/5623092/76645283-5aedfa00-6561-11ea-9237-295e211d4f55.png)

**Comment by pouyamiralayi** [comment]
@mcottret  you are totally correct, i was ignoring the face that @verloka wants the sectors for a specific component!

**Comment by pouyamiralayi** [comment]
@verloka based on @mcottret answer, you can bring back the whole styling options like this:
```
editor.on('load', function () {
            editor.getWrapper().set('stylable',true)
            //...
```
Cheers!

**Comment by verloka** [comment]
> @verloka based on @mcottret answer, you can bring back the whole styling options like this:
> 
> ```
> editor.on('load', function () {
>             editor.getWrapper().set('stylable',true)
>             //...
> ```
> 
> Cheers!

yay, it works, cheers.

**Comment by mcottret** [comment]
> > Hi @verloka & @pouyamiralayi,
> > The sectors list seems to be common to all applications components.
> > However, components hold a list of attributes that can be edited through the style manager panel when they are selected, which is used to filter the application sectors.
> > From the [Component API Reference](https://grapesjs.com/docs/api/component.html#component), you can use the `stylable`, & `unstylable` properties to include and / or exclude editable attributes.
> > By default, the "Body" element (referred to as "Wrapper"), seems to hold the following `stylable` property: `["background", "background-color", "background-image", "background-repeat", "background-attachment", "background-position", "background-size"]`, which is why even with default sectors, it only shows the "Decorations" one on the style manager.
> > You'd need to edit its `stylable` property in order to add the "Dimension" related ones, which could be achieved like so:
> > `editor.getWrapper().set('stylable', editor.getWrapper().get('stylable').concat(['width', 'height', 'max-width', 'min-height', 'margin', 'padding']));`
> 
> Ok, this is better BUT
> https://codepen.io/verloka/pen/BaNrrzL
> look at margins for the Body and other element in the Dimensions sector
> ![Безымянный](https://user-images.githubusercontent.com/5623092/76645283-5aedfa00-6561-11ea-9237-295e211d4f55.png)

My answer was indeed incomplete, sorry. Just adding `margin` or `padding` to the `stylable` array only adds the corresponding label & form group, you still have to specify which properties to add inside it (eg `margin-top`, `margin-right` etc ...). This can be useful in case you don't want the whole styling options like mentioned previously.

I also updated my answer with a working snippet, thank you :)

**Comment by artf** [comment]
@pouyamiralayi @mcottret thanks for the support guys, really appreciated ❤️❤️❤️
