### ISSUE TITLE
[QUESTION] Background image via inline style not accessible?

### ISSUE THREAD

**Issue by orionseye** [artf/grapesjs#2651]
This is very simple, but i can not access the background image set via CSS, within my custom block 'content'.
How do i change the background image here?
(even editor.getCss 'sees' the style)
https://codepen.io/dimimet/pen/NWqYmbB

Cheers!

**Comment by orionseye** [comment]
Strange .. i have explicitly to use specific class to access the background (in my case it's class .bg) 
#desc-text-6 .bg will not work.
I saw a configuration for that from Artur .. but don't remember where

**Comment by orionseye** [comment]
Never mind.. reading half of the issues here, i saw that there is a little 'checkbox' next to the selected classes, which let me toggle the class view on/off.
That way, i can add unique class now and assigned my bg-image to that ..then clicking on the lil checkbox, it will allow me to 'access' the background image layer.

I must admit, that this is hard stuff...especially to teach people how todo that.
Anyway, problem solved, but my recommendation would be, that this needs a fix.

**Comment by artf** [comment]
> Now, since .bg is a global style declaration, i need to make use of #desc-text-6 .bg

No, actually there are absolutely no good reasons to use a selector like this `#desc-text-6 .bg`, just create a single class for your element and point your CSS to it, no more checkbox to toggle...
