### ISSUE TITLE
How to get the changed property from StyleManager

### ISSUE THREAD

**Issue by AbdiasM** [artf/grapesjs#2654]
Hi,

Is there a way to find out which property was changed in the StyleManager? For eg. If I select a Text component and change its background-color property from the StyleManager, is there any event where I can get the property that was changed. 
I've tried the 'component:styleUpdate' event, but it passes the component's model as argument, not the property.

Any help is appreciated.

**Comment by pouyamiralayi** [comment]
Hi @AbdiasM based on [component:styleUpdate](https://grapesjs.com/docs/api/editor.html#available-events) or [component:styleUpdate:{propertyName}](https://grapesjs.com/docs/api/editor.html#available-events) you can get the property like below:
```
editor.on('component:styleUpdate:background-image', component => {
    const sm = editor.StyleManager
    const model = sm.getModelToStyle(component)
    // the model can be a Component or CssRule
    const bg = model.getStyle()['background-image']
```

**Comment by AbdiasM** [comment]
Thanks for your answer @pouyamiralayi but this way I'll have to add a hook for each property. I need a way to get which property was changed and its previous and changed values.

**Comment by pouyamiralayi** [comment]
@AbdiasM i think this is kinda backbone related stuff and to my knowledge currently not possible. This is how it should be:
```
editor.on('component:styleUpdate', component => {
        console.log(Object.keys(component.changedAttributes()))
})
```
Cheers!

**Comment by artf** [comment]
Actually, you get the changed property as a second argument of the callback
```js
editor.on('component:styleUpdate', (component, propChanged) => {
	...
})
```
