### ISSUE TITLE
[BUG] Wrong position of toolbar when duplicate children component

### ISSUE THREAD

**Issue by abozhinov** [artf/grapesjs#2656]
Hi, 
you can check this example: https://codepen.io/abozhinov/pen/XWbqjEJ

Steps to reproduce the problem:
1. If components existing delete them all.
2. Drag a new carousel block. 
3. Select the first children's container.
4. Click on the DUPLICATE icon to create a new component.
5. After that try to select the newest component and then select the first component again. 
6. The position of the toolbar is wrong because the browser can't get the width and height of the element.

[Error] TypeError: null is not an object (evaluating 'this.canvas.getHighlighter(t).style')
	showHighlighter (grapes.min.js:2:263826)
	updateToolsLocal (grapes.min.js:2:266937)
	(anonymous function) (grapes.min.js:2:260549)
	forEach
	onHovered (grapes.min.js:2:260438)
	m (grapes.min.js:2:22592)
	v (grapes.min.js:2:22263)
	h (grapes.min.js:2:20216)
	(anonymous function) (grapes.min.js:2:22156)
	set (grapes.min.js:2:24026)
	setHovered (grapes.min.js:11:128341)
	handleHover (grapes.min.js:2:351496)
	I (grapes.min.js:2:9008)
	(anonymous function) (grapes.min.js:2:9208)
	(anonymous function) (grapes.min.js:2:2321)
	t (grapes.min.js:2:80874)

When I trigger getView().reset() the new elements in the DOM don't exist and their width and height are 0. I want to reset the view and then to trigger JS which will build the carousel.

**Comment by abozhinov** [comment]
The same result you can get when trigger render instead of reset.

**Comment by abozhinov** [comment]
@artf if you try on the demo is the same. Just drag the carousel and click on the slide.
<img width="1440" alt="Screenshot 2020-03-16 at 14 58 23" src="https://user-images.githubusercontent.com/1404839/76760669-b8b75780-6796-11ea-8e24-8946e27949f9.png">

**Comment by abozhinov** [comment]
this.PageBuilder.Commands.extend('select-comp', {
            onHovered(em, component) {
                let result = {};

                if (component) {
                    component.views.forEach(view => {
                        const el = view.el;
                        const pos = this.getElementPos(el);

                        result = { el, pos, component, view };

                        this.updateToolsLocal(result);

                        if (el.ownerDocument === this.currentDoc) {
                            this.elHovered = result;
                        }
                    });
                }
            },
            hideHighlighter(view) {
                const el = this.canvas.getHighlighter(view);
                if (el) {
                    el.style.opacity = 0;
                }
            },
            showHighlighter(view) {
                const el = this.canvas.getHighlighter(view);
                if (el) {
                    el.style.opacity = '';
                }
            },
            getElementPos(el) {
                let data = this.canvas.getCanvasView().getElementPos(el);

                if (data.width === 0) {
                    const element = this.editor.Canvas.getDocument().getElementById(el.id);
                    if (element) {
                        data = element.getBoundingClientRect();
                    }
                }

                return data;
            },
        });

**Comment by artf** [comment]
Thanks for the report @abozhinov I've seen this error somewhere in my logger but was never able to reproduce it. 
First of all, I can't see any issue (or console logs) from your demo link (by following your steps) but I actually see the wrong toolbar position of the slider in the official demo, but still, no errors in the console.
Are you able to create another demo without using custom components (less nested components possible).

Obviously doing the check in the `showHighlighter` function skips the error but there is a hard assumption that `this.canvas.getHighlighter(view)` always exists, so I'd like to understand better the real problem

**Comment by abozhinov** [comment]
@artf the error happens when I reset the view. I want to reset the view when add children component. 

`updated(property) {
                if (property === 'components') {
                    this.getView().reset();
                }
            },`

**Comment by abozhinov** [comment]
When I duplicate children component I receive this error:
DevTools failed to parse SourceMap: webpack:///node_modules/tooltip.js/dist/esm/tooltip.js.map
DevTools failed to parse SourceMap: webpack:///node_modules/popper.js/dist/esm/popper.js.map
Language.js:126 GET https://cdn.mydreamshop.io/assets/docker/language-cms-1584641945.json 403
Language @ Language.js:126
eval @ Language.js:211
./assets/utils/Language.js @ app-cms.js:2469
__webpack_require__ @ runtime.js:790
fn @ runtime.js:151
eval @ Cms.js:15
./assets/Cms.js @ cms.js:11
__webpack_require__ @ runtime.js:790
checkDeferredModules @ runtime.js:46
webpackJsonpCallback @ runtime.js:33
(anonymous) @ vendors-app-cms.js:1
page:1 A cookie associated with a cross-site resource at http://www.facebook.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
page:1 A cookie associated with a cross-site resource at http://google.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
favicon.ico:1 GET https://docker.mydreamshop.io/favicon.ico 404
DevTools failed to parse SourceMap: webpack:///node_modules/grapesjs/dist/grapes.min.js.map
DevTools failed to parse SourceMap: webpack:///node_modules/grapesjs-touch/dist/grapesjs-touch.min.js.map
DevTools failed to parse SourceMap: webpack:///node_modules/grapesjs-parser-postcss/dist/grapesjs-parser-postcss.min.js.map
DevTools failed to parse SourceMap: webpack:///node_modules/tooltip.js/dist/esm/tooltip.js.map
DevTools failed to parse SourceMap: webpack:///node_modules/popper.js/dist/esm/popper.js.map
DevTools failed to parse SourceMap: webpack:///node_modules/tooltip.js/dist/esm/tooltip.js.map
DevTools failed to parse SourceMap: webpack:///node_modules/popper.js/dist/esm/popper.js.map
Language.js:126 GET https://cdn.mydreamshop.io/assets/docker/language-app-1584719361.json 403
Language @ Language.js:126
eval @ Language.js:211
./assets/utils/Language.js @ app-cms.js:2469
__webpack_require__ @ runtime.js:790
fn @ runtime.js:151
eval @ App.js:33
./assets/App.js @ app.js:11
__webpack_require__ @ runtime.js:790
checkDeferredModules @ runtime.js:46
webpackJsonpCallback @ runtime.js:33
(anonymous) @ vendors-app-cms.js:1
Language.js:126 GET https://cdn.mydreamshop.io/assets/docker/language-app-1584719361.json 403
Language @ Language.js:126
eval @ Language.js:211
./assets/utils/Language.js @ app-cms.js:2469
__webpack_require__ @ runtime.js:790
fn @ runtime.js:151
eval @ App.js:33
./assets/App.js @ app.js:11
__webpack_require__ @ runtime.js:790
checkDeferredModules @ runtime.js:46
webpackJsonpCallback @ runtime.js:33
(anonymous) @ vendors-app-cms.js:1
grapes.min.js:2 Uncaught TypeError: this[0].getAttribute is not a function
    at y.w.attr (grapes.min.js:2)
    at K (grapes.min.js:2)
    at y.w.data (grapes.min.js:2)
    at r.onHover (grapes.min.js:2)
    at I (grapes.min.js:2)
    at HTMLBodyElement.eval (grapes.min.js:2)
    at HTMLBodyElement.eval (grapes.min.js:2)
w.attr @ grapes.min.js:2
K @ grapes.min.js:2
w.data @ grapes.min.js:2
onHover @ grapes.min.js:2
I @ grapes.min.js:2
eval @ grapes.min.js:2
eval @ grapes.min.js:2
index.js:1356 open
index.js:1356 open
index.js:1356 traits
index.js:1356 traits
index.js:1356 traits
index.js:1356 traits
index.js:1356 traits
index.js:1356 open
index.js:1356 open
index.js:1356 components
index.js:1356 open
index.js:1356 open
index.js:1356 open
grapes.min.js:2 Uncaught TypeError: Cannot read property 'style' of null
    at r.showHighlighter (grapes.min.js:2)
    at r.updateToolsLocal (grapes.min.js:2)
    at eval (grapes.min.js:2)
    at Array.forEach (<anonymous>)
    at r.onHovered (grapes.min.js:2)
    at m (grapes.min.js:2)
    at v (grapes.min.js:2)
    at h (grapes.min.js:2)
    at r.c.trigger (grapes.min.js:2)
    at r.set (grapes.min.js:2)
showHighlighter @ grapes.min.js:2
updateToolsLocal @ grapes.min.js:2
eval @ grapes.min.js:2
onHovered @ grapes.min.js:2
m @ grapes.min.js:2
v @ grapes.min.js:2
h @ grapes.min.js:2
c.trigger @ grapes.min.js:2
set @ grapes.min.js:2
setHovered @ grapes.min.js:11
onHover @ grapes.min.js:2
I @ grapes.min.js:2
eval @ grapes.min.js:2
eval @ grapes.min.js:2
grapes.min.js:2 Uncaught TypeError: Cannot read property 'style' of null
    at r.hideHighlighter (grapes.min.js:2)
    at r.updateToolsLocal (grapes.min.js:2)
    at r.eval (grapes.min.js:2)
    at o (grapes.min.js:2)
    at eval (grapes.min.js:2)
hideHighlighter @ grapes.min.js:2
updateToolsLocal @ grapes.min.js:2
eval @ grapes.min.js:2
o @ grapes.min.js:2
eval @ grapes.min.js:2
setTimeout (async)
eval @ grapes.min.js:2
eval @ grapes.min.js:2
eval @ grapes.min.js:2
eval @ grapes.min.js:2
m @ grapes.min.js:2
v @ grapes.min.js:2
h @ grapes.min.js:2
c.trigger @ grapes.min.js:2
eval @ grapes.min.js:11
selectAdd @ grapes.min.js:11
eval @ grapes.min.js:11
m @ grapes.min.js:2
v @ grapes.min.js:2
h @ grapes.min.js:2
c.trigger @ grapes.min.js:2
_onModelEvent @ grapes.min.js:2
m @ grapes.min.js:2
v @ grapes.min.js:2
h @ grapes.min.js:2
c.trigger @ grapes.min.js:2
set @ grapes.min.js:2
add @ grapes.min.js:2
push @ grapes.min.js:2
eval @ grapes.min.js:11
addSelected @ grapes.min.js:11
eval @ grapes.min.js:11
setSelected @ grapes.min.js:11
select @ grapes.min.js:11
select @ grapes.min.js:2
onClick @ grapes.min.js:2
I @ grapes.min.js:2
eval @ grapes.min.js:2
eval @ grapes.min.js:2
Show 8 more frames
grapes.min.js:2 Uncaught TypeError: Cannot read property 'style' of null
    at r.showHighlighter (grapes.min.js:2)
    at r.updateToolsLocal (grapes.min.js:2)
    at eval (grapes.min.js:2)
    at Array.forEach (<anonymous>)
    at r.onHovered (grapes.min.js:2)
    at m (grapes.min.js:2)
    at v (grapes.min.js:2)
    at h (grapes.min.js:2)
    at r.c.trigger (grapes.min.js:2)
    at r.set (grapes.min.js:2)
showHighlighter @ grapes.min.js:2
updateToolsLocal @ grapes.min.js:2
eval @ grapes.min.js:2
onHovered @ grapes.min.js:2
m @ grapes.min.js:2
v @ grapes.min.js:2
h @ grapes.min.js:2
c.trigger @ grapes.min.js:2
set @ grapes.min.js:2
setHovered @ grapes.min.js:11
onHover @ grapes.min.js:2
I @ grapes.min.js:2
eval @ grapes.min.js:2
eval @ grapes.min.js:2
grapes.min.js:2 Uncaught TypeError: Cannot read property 'style' of null
    at r.showHighlighter (grapes.min.js:2)
    at r.updateToolsLocal (grapes.min.js:2)
    at eval (grapes.min.js:2)
    at Array.forEach (<anonymous>)
    at r.onHovered (grapes.min.js:2)
    at m (grapes.min.js:2)
    at v (grapes.min.js:2)
    at h (grapes.min.js:2)
    at r.c.trigger (grapes.min.js:2)
    at r.set (grapes.min.js:2)
showHighlighter @ grapes.min.js:2
updateToolsLocal @ grapes.min.js:2
eval @ grapes.min.js:2
onHovered @ grapes.min.js:2
m @ grapes.min.js:2
v @ grapes.min.js:2
h @ grapes.min.js:2
c.trigger @ grapes.min.js:2
set @ grapes.min.js:2
setHovered @ grapes.min.js:11
onHover @ grapes.min.js:2
I @ grapes.min.js:2
eval @ grapes.min.js:2
eval @ grapes.min.js:2
grapes.min.js:2 Uncaught TypeError: Cannot read property 'style' of null
    at r.showHighlighter (grapes.min.js:2)
    at r.updateToolsLocal (grapes.min.js:2)
    at eval (grapes.min.js:2)
    at Array.forEach (<anonymous>)
    at r.onHovered (grapes.min.js:2)
    at m (grapes.min.js:2)
    at v (grapes.min.js:2)
    at h (grapes.min.js:2)
    at r.c.trigger (grapes.min.js:2)
    at r.set (grapes.min.js:2)
showHighlighter @ grapes.min.js:2
updateToolsLocal @ grapes.min.js:2
eval @ grapes.min.js:2
onHovered @ grapes.min.js:2
m @ grapes.min.js:2
v @ grapes.min.js:2
h @ grapes.min.js:2
c.trigger @ grapes.min.js:2
set @ grapes.min.js:2
setHovered @ grapes.min.js:11
onHover @ grapes.min.js:2
I @ grapes.min.js:2
eval @ grapes.min.js:2
eval @ grapes.min.js:2
grapes.min.js:2 Uncaught TypeError: Cannot read property 'style' of null
    at r.showHighlighter (grapes.min.js:2)
    at r.updateToolsLocal (grapes.min.js:2)
    at eval (grapes.min.js:2)
    at Array.forEach (<anonymous>)
    at r.onHovered (grapes.min.js:2)
    at m (grapes.min.js:2)
    at v (grapes.min.js:2)
    at h (grapes.min.js:2)
    at r.c.trigger (grapes.min.js:2)
    at r.set (grapes.min.js:2)
showHighlighter @ grapes.min.js:2
updateToolsLocal @ grapes.min.js:2
eval @ grapes.min.js:2
onHovered @ grapes.min.js:2
m @ grapes.min.js:2
v @ grapes.min.js:2
h @ grapes.min.js:2
c.trigger @ grapes.min.js:2
set @ grapes.min.js:2
setHovered @ grapes.min.js:11
onHover @ grapes.min.js:2
I @ grapes.min.js:2
eval @ grapes.min.js:2
eval @ grapes.min.js:2

**Comment by abozhinov** [comment]
@artf I don't why there are no errors in codepen. Second paramter in console log is NULL.
<img width="789" alt="Screenshot 2020-03-21 at 21 29 57" src="https://user-images.githubusercontent.com/1404839/77235064-6f627000-6bbb-11ea-8736-04e37a36c824.png">

**Comment by artf** [comment]
I think we would need more help to understand better what is really happening and in this period I'm quite busy with other non-GrapesJS-related stuff 😞

**Comment by artf** [comment]
Probably I've found the issue, seems to be a bug with components containing scripts. Should be fixed in the next release

**Comment by abozhinov** [comment]
When overwrite this the methods everything works perfectly.
The problem was that "el" doesn't exist in the DOM. 

`this.PageBuilder.Commands.extend('select-comp', {
            onHovered(em, component) {
                let result = {};

                if (component) {
                    const { view } = component;
                    const { el } = view;
                    const pos = this.getElementPos(el);

                    result = { el, pos, component, view };

                    if (pos.width > 0) {
                        this.updateToolsLocal(result);

                        if (el.ownerDocument === this.currentDoc) {
                            this.elHovered = result;
                        }
                    }
                }
            },
            onSelect() {
                const { em } = this;
                const component = em.getSelected();

                if (component) {
                    const { view } = component;
                    const { el } = view;

                    if (el) {
                        const pos = this.getElementPos(el);
                        const result = { el, pos, component, view };

                        if (pos.width > 0) {
                            this.elSelected = result;
                            this.updateToolsGlobal();
                            // This will hide some elements from the select component
                            this.updateToolsLocal(result);
                        }
                    }
                } else {
                    this.toggleToolsEl();
                    this.lastSelected = 0;
                }
            }
        });`

**Comment by artf** [comment]
Should be fixed https://github.com/artf/grapesjs/releases/tag/v0.16.12

**Comment by abozhinov** [comment]
I have the same error when select.

<img width="794" alt="Screenshot 2020-04-23 at 10 06 14" src="https://user-images.githubusercontent.com/1404839/80069604-4cc0cf80-854a-11ea-87ec-4db151548f66.png">

**Comment by artf** [comment]
I can't reproduce the toolbar issue anymore in the official demo. Without a reproducible demo, I can't do much
