### ISSUE TITLE
ERROR TypeError: r is not a function

### ISSUE THREAD

**Issue by vectaankit** [artf/grapesjs#2658]
Grapesjs working absolutely fine at my local end as well as at yarn build --aot, but once we done with yarn build --prod, once we opening editor showing me 
```
ERROR TypeError: r is not a function
Array.forEach (<anonymous>)
    at Object.init

```
can please help me to resolve this issue?

**Comment by artf** [comment]
Sorry but that chunk of error, pasted like this (without the stack, file reference, etc.), tells absolutely nothing, it might also be an error in your source
