### ISSUE TITLE
[QUESTION] Millimeter support for margin and padding properties

### ISSUE THREAD

**Issue by verloka** [artf/grapesjs#2659]
How to use millimeters for margin or padding property?

![Annotation 2020-03-16 143552](https://user-images.githubusercontent.com/5623092/76759080-a982da80-6793-11ea-9e85-8aacd508083d.jpg)

**Comment by artf** [comment]
You can use the Style Manager API with [`getProperty`](https://grapesjs.com/docs/api/style_manager.html#getproperty) and update the units (example https://github.com/artf/grapesjs/issues/2509#issuecomment-575552807)
