### ISSUE TITLE
[BUG] toggleStateCls returns js error

### ISSUE THREAD

**Issue by h3llomoto** [artf/grapesjs#2661]
Hi there, guys.
I found a bug at the LayerManager:
I've got an html comment as a layer in the LM.
I click the comment.
I get an error at the console:
```
Uncaught TypeError: Cannot read property 'remove' of undefined
```
And the code this error relates to is:
src/style_manager/view/SectorsView.js:47
```
  toggleStateCls(targets = [], enable) {
    targets.forEach(trg => {
      const el = trg.getEl();
      el && el.classList[enable ? 'add' : 'remove'](helperCls);
    });
  },
```
So, html comments cant have classList property and this is the bug.

**Comment by artf** [comment]
Can you create a live demo, please? By default definition, you shouldn't be able to see Comment component in Layers
