### ISSUE TITLE
[BUG] WASD keypress returns an errror at Canvas

### ISSUE THREAD

**Issue by h3llomoto** [artf/grapesjs#2663]
Hi there,
I get an error on a keypress at canvas without RTE enabled.

Uncaught TypeError: Cannot read property 'hasFocus' of null
node_modules/grapesjs/src/canvas/index.js:544
```
hasFocus() {
  return this.getDocument().hasFocus();
},
```

**Comment by artf** [comment]
What do you mean by `without RTE enabled`? I'm not able to reproduce it. Create a live demo with all the necessary steps, please
