### ISSUE TITLE
[Help]Keyboard on mobile device will not display on text edit? Anyone else?

### ISSUE THREAD

**Issue by darylamonica** [artf/grapesjs#2665]
Is anyone else having this problem? Or resolved it? Editing on a tablet seems reasonable. While using a mobile device I cannot get the keyboard to display when trying to edit a text field. Even using the grapes touch plugin does not help. There is an example here:

[http://jsfiddle.net/v9kecdpz/](http://jsfiddle.net/v9kecdpz/)

**Comment by darylamonica** [comment]
Is there something else I can do to get a response? I included a demo jsfiddle. Many answered questions don't have an example. So, what am I doing wrong?

**Comment by artf** [comment]
Give more information about the device (OS, browser, etc.)

**Comment by darylamonica** [comment]
I've tried to edit text unsuccessfully at (http://jsfiddle.net/v9kecdpz/) on the following devices.
iPad (10.2 inch) 13.3.1
iPhoneX iOs 13.3.1
Using either Safari or Chrome mobile browsers do not work.
Works fine on desktop browsers.

**Comment by abozhinov** [comment]
Can't edit the text because dbclick is not supported on touch devices. I try to create double tap event  but cannot position the cursor.

events: {
                dblclick: 'onActive',
                input: 'onInput',
                touchend: (e) => {
                    if ((e.timeStamp - e.target.lastTouchEndEventTimeStamp) < 400) {
                        const event = new MouseEvent('dblclick');
                        e.target.dispatchEvent(event);
                    }

                    e.target.lastTouchEndEventTimeStamp = e.timeStamp;
                },
            },

**Comment by AFIFIHishame-Z** [comment]
`<h1>asdasdasd</h1>`
