### ISSUE TITLE
link element not append in head element in ediot.canvas  #firefox #grapesjs

### ISSUE THREAD

**Issue by sampathrajs** [artf/grapesjs#2667]
am trying to add google fonts in web-builder to change the font style for that to import am adding cdn in editor the code works in chrome and safari but firefox not working 

createLinkElement(fontFamily) {
        let link = document.createElement("LINK");
        link.setAttribute("rel", "stylesheet");
        link.setAttribute("href", `https://fonts.googleapis.com/css?family=${fontFamily}`);
        return link;
    }

editor.Canvas.getDocument().head.append(this.createLinkElement(fontFamily));

element also not appending

**Comment by artf** [comment]
I've made the issue template for a reason

**Comment by sampathrajs** [comment]
> I've made the issue template for a reason

i want to add custom fonts in web builder could you please help me out

**Comment by RutujaBadbe** [comment]
Hi! might be very late to comment but have you tried this? -
const link1 = document.createElement('link');
link1.rel = 'stylesheet';
link1.href = '/page-builder-assets/css/style.css';
canvas.getDocument().head.appendChild(link1);

it worked for me
