### ISSUE TITLE
Changing color of a text part

### ISSUE THREAD

**Issue by 4URGB** [artf/grapesjs#2676]
Hi, if i select only a part of a text to change the color it dosnt work. It change only the color for the complete text.

For example. If i want to change in "this is my text", only "my text", i select it, change the color, but the new color will go to the complete text.

May it is a smal thing, but its really useful at daily work :-)

**Comment by qtarant** [comment]
Hi,
I made this task integrating CKEditor, so you can change font, font style, size or color.. The best is that you can select any part of the text an customize only that specific part.

**Comment by artf** [comment]
To do what you ask, you should [add a new action](https://grapesjs.com/docs/api/rich_text_editor.html#add) to the built-in RTE and wrap the selected text in a wrapper (eg. a `<span>` element) and once it's wrapped you should be able to add the style you need
Using a custom RTE (like the CKEditor) takes the content outside of the GrapesJS context so all the possible styles should be managed by the third-library itself
