### ISSUE TITLE
[QUESTION] How to delete a list with devices

### ISSUE THREAD

**Issue by verloka** [artf/grapesjs#2677]
How to delete a list with devices?

![Аннотация 2020-03-23 170147](https://user-images.githubusercontent.com/5623092/77330422-03e9e100-6d28-11ea-9f29-c4507cc405ae.png)

**Comment by teawithfruit** [comment]
You have to set a custom device manager configuration in your init block.
https://grapesjs.com/docs/api/device_manager.html

With this snippet you can clear the list.
```js
const editor = grapesjs.init({
  deviceManager: []
})
```

**Comment by verloka** [comment]
> You have to set a custom device manager configuration in your init block.
> https://grapesjs.com/docs/api/device_manager.html
> 
> With this snippet you can clear the list.
> 
> ```js
> const editor = grapesjs.init({
>   deviceManager: []
> })
> ```

I do not need to clear the list. I need to hide the list.

**Comment by teawithfruit** [comment]
```js
editor.on('load', () => {
  editor.Panels.removePanel('devices-c')
})
```
Next time you can try to use the search function... ;)
#875

**Comment by verloka** [comment]
> ```js
> editor.on('load', () => {
>   editor.Panels.removePanel('devices-c')
> })
> ```
> 
> Next time you can try to use the search function... ;)
> #875

thx
