### ISSUE TITLE
[Question:]  adding classname for custom DomComponent

### ISSUE THREAD

**Issue by LOMFM** [artf/grapesjs#2679]
[Question:]  
Hi, I have used this builder plugin in angular 7. This is very well structured and extendable.  
  
But I have some issue in define custom components this plugin.  
**The Question is How to add Classes to custom DomComponent.**  
  
I have created new video wrapper dom component.
This contains iframe inside of them. 
I want following result of this domComponent.
<div class="cus-gjs-video"><iframe class="cus-video-content" src=""></iframe></div>

The domComponent code is following.
model: {
          defaults: {
            type: 'cus-video',
            tagName: 'div',
            editable: 1,
            droppable: 0,
            resizable: 0,
            video: 'http://localhost:3000/embed/video/5e2a05c94d04d37842cc8ff9',
            src: `http://localhost:3000/embed/video/5e2a05c94d04d37842cc8ff9`,
            fallback: `Error Video`,
            autoplay: false,
            controls: true,
            mute: false,
            loop: false,
            playMethod: 'inline', // inline | popup
            classes: ['gjs-crm-video-wrapper']
          }

With this, i can get only following result.
<div><iframe class="cus-video-content" src=""></iframe></div>

I want class name of wrapper div of iframe. 
Is there some solution for this?
I appreciate your help. Thanks.

**Comment by artf** [comment]
Can you create live demo with the complete code of your custom component, please?
