### ISSUE TITLE
Selected block is not editable 

### ISSUE THREAD

**Issue by darves** [artf/grapesjs#268]
Great work mate! I realy like it!

This morning I was playing around and found this issue:

Steps to reproduce

- Select text block
- Change margin-top (for example), press the up arrow N times
- Click on the undo N + 1 times
=> Block is still selected (on UI), but changes not applied

![image](https://user-images.githubusercontent.com/3004389/29958605-cfbb22e6-8ef3-11e7-8e97-49ceb780aa8e.png)

**Comment by artf** [comment]
Hi @darves I'm actually trying to reproduce it (using the current demo) but unable, maybe I got it wrong
![error](https://user-images.githubusercontent.com/11614725/30038872-c8cdb0b0-91c9-11e7-8778-5e097552533b.gif)

**Comment by darves** [comment]
Hello @artf,
try to remove everything from LocalStorage before.
here is the video, sry for low-quality 
https://drive.google.com/file/d/0B5kfETdbwBM1dXlnMDVieGFIZjg/view

**Comment by artf** [comment]
Seems like I haven't the right permission to see the video.
Anyway, just tried with no storage active and it the same from my side. Are you working with the current demo? Did you also face the issue with the webpage one?

**Comment by darves** [comment]
Sry for late answer mate,
I give you permission for the video. I hope you are able to reproduce it

**Comment by artf** [comment]
yeah Darko, thanks to the screencast I got it and was able to reproduce, but only within the newsletter preset which is bit strange... will ping you back when it's fixed

**Comment by darves** [comment]
Yes, I know is strange.... I was able to reproduce it only on newsletter preset :)

Tnx Artur
