### ISSUE TITLE
Style cleaned on loading

### ISSUE THREAD

**Issue by picozzo92** [artf/grapesjs#2680]
Hi, 

when I load the html with the inline style previously saved by the editor the style is removed. How can I solve my problem?

**Comment by pouyamiralayi** [comment]
@picozzo92 i believe from [v15.08](https://github.com/artf/grapesjs/releases/tag/v0.15.8) inline styles are not supported anymore.
Cheers!

**Comment by picozzo92** [comment]
thank you

**Comment by artf** [comment]
`config.avoidInlineStyle` is `true` by default, there are some rare cases where it might be useful to disable (eg. disabled in the mjml plugin to make it work properly) but for the common web pages we encourage to keep it as it is
