### ISSUE TITLE
Text element change tag after save

### ISSUE THREAD

**Issue by picozzo92** [artf/grapesjs#2682]
Hi, 

the block of text changes tags when reloading html after saving.

in detail as soon as you insert the text block the ckeditor is initialized on the div, when entering edit the ckeditor is initialized on the p tag.

This is the text block on load
`<div data-gjs-type="default" draggable="true" data-highlightable="1" id="iysen" class=""><p data-gjs-type="text" draggable="true" data-highlightable="1" id="i5utb" class="gjs-selected">Inserisci il tuo testo</p></div>`

This is the text block before saving
`<div data-gjs-type="text" draggable="true" data-highlightable="1" id="inuej" contenteditable="false" class="cke_editable cke_editable_inline cke_contents_ltr cke_show_borders" spellcheck="false"><p>Inserisci il tuo testo</p></div>`

**Comment by artf** [comment]
With the usage of a custom RTE like CKEditor we leave all the responsibility to the third-party handle the content, so if there is something you'd like to change you have to check their documentation
