### ISSUE TITLE
[?] What Are The Programming Languages/Frameworks/Libraries/Plugins?

### ISSUE THREAD

**Issue by peterlinus** [artf/grapesjs#2688]
I am very interested in this project but need some guidance please.
Is there any documentation on what are the programming languages, frameworks, libraries, plugins etc used in this project?
Any documentation explaining what each folder contains?
Any guidance on how to get started to further develop this project would be greatly appreciated. 
What must I learn in order to continue coding this project?
Thanks.

**Comment by GoodPHP** [comment]
Hello, for add changes to editor need know Javascript or looking for someone who know.

Docs: https://grapesjs.com/docs/

Such a description as you want, will not be. The documentation describes the main methods.
