### ISSUE TITLE
Custom component with non-customizable content

### ISSUE THREAD

**Issue by theanhmx** [artf/grapesjs#269]
hi
Thank for the framework, 
i trying to create a component which user can drag and drop, change style
but will NOT able to change the content (used {{ and }} for data binding)

i have created a new type with custom dblclick event.
`let comps = editor.DomComponents;
    let originalText = comps.getType('text');
    const defaultModel = originalText.model;
    const defaultView = originalText.view;

    comps.addType('unchangeable', {
      model: defaultModel.extend(
        {
          defaults: Object.assign(
            {},
            defaultModel.prototype.defaults,
            {
              removable: true,
              draggable: true,
              droppable: true,
              badgable: true,
              stylable: true,
              highlightable: true,
              copyable: true,
              resizable: true,
              editable: true
            }
          )
        },
        {
          isComponent: function(el) {}
        }
      ),
      view: defaultView.extend({
        // Bind events
        events: {
          dblclick: function(){
            alert('Hi!');
          }
        }
      })
    });`

then add the block like this:
`
bm.add('title', {
          label: c.labelTitle,
          category: 'Mapped by default',
          attributes: {class:'gjs-fonts gjs-f-text', disabled: true},
          content: {
            type: 'unchangeable',
            content: '<h1 class="alert__title">{{title}}</h1>'
          }
        });
`
the problem is only dblclick works
i though about put the default click event there, but dont know how to get it.

**Comment by darves** [comment]
Hello @theanhmx ,
That is because backbone extends does not "merge " events obj. You can try something like this:
`
defaultView.extend({
    initialize: function () {
        var defaultClickEventHandler = this.events['click'] || function () {};

        defaultView.prototype.initialize.apply(this, arguments);

        this.events['click'] = function () {
            defaultClickEventHandler.apply(this, arguments);
            // do you'r stuff here
        }
    }
})
`

**Comment by theanhmx** [comment]
thank you @darves,
i'm able to separate the events now.
