### ISSUE TITLE
[BUG] Rich Text Editor's position is not updated on enter/return

### ISSUE THREAD

**Issue by mazuschlag** [artf/grapesjs#2693]
Once again thanks for all the hard work on the project!

This is reproducible on the current release 0.16.3 - you can check it out in the newsletter demo: https://grapesjs.com/demo-newsletter-editor.html

Normally the RTE appears above the element so this is not an issue. However, when a RTE-enabled element is placed close to the top of the editor, there is no room for the RTE above the element, so it is placed below. When pressing "enter" or "carriage return", the RTE stays in place, blocking much of the element that is now below it.

To reproduce:
1. Open GrapesJS
2. Place a text field at the top of the editor
3. Type some text and press enter.

When the user removes a row in the text element via backspace, the RTE's position is updated correctly and moves to the new edge of the element. But for enter, it does not move at all.

**Comment by artf** [comment]
Canvas tools should be updated on `input` event of the text component, in the current version there is an issue even with the built-in RTE but it will be fixed in the next release. 
Somehow, this issue doesn't affect the CKEditor plugin but, from what I've seen, the "enter" never triggered the `input` event so I think there should be attached some other event to the CKEditor instance. I'd be glad to receive a PR on the plugin

**Comment by mazuschlag** [comment]
@artf Thanks for the response but I'm a little confused. This is happening with the CKEditor plugin - are you saying the fix will be separate from the fix to the built in CKEditor? I wouldn't mind fixing it but do you have some pointers on where to start?

**Comment by artf** [comment]
> are you saying the fix will be separate from the fix to the built in CKEditor?

correct

> I wouldn't mind fixing it but do you have some pointers on where to start?

You can trigger [this event](https://github.com/artf/grapesjs-plugin-ckeditor/blob/7c227de0b187da8cb7b1e22b3da34837659977d1/src/index.js#L79) once you've found how to catch on "enter" event

**Comment by khurram900** [comment]
@mazuschlag if you are using ckeditor you can try this patch. 

`CKEDITOR.on('instanceReady', function (e) {
            that.editor.RichTextEditor.updatePosition();
        });`
