### ISSUE TITLE
[QUESTION] How to use replace fontawesome url ?

### ISSUE THREAD

**Issue by adeguntoro** [artf/grapesjs#2698]
I'm new with Grapejs. Firts time i use, it look awesome. So, how can i replace cdn fontawesome with css/js file from my own computer without need to use internet ?
I live in country where internet is a big problem for me to use something. Sorry for my english.

**Comment by noogen** [comment]
@adeguntoro Take a look at this: https://github.com/artf/grapesjs/blob/8b315e4ba053043889456fcc4048c4f504257551/src/editor/config/config.js#L152

Pass in your config with `cssIcons` property of '/localpath/css/font-awesome.min.css` to override?
