### ISSUE TITLE
can not use external link library  

### ISSUE THREAD

**Issue by piyalmaduranga** [artf/grapesjs#27]
i try to add bootstrap library  is not working for me , that show grapesjs error like this

![screenshot from 2017-01-09 17 00 42](https://cloud.githubusercontent.com/assets/12907174/21765173/34ffd536-d68d-11e6-8afa-9cd31ec77f78.png)

**Comment by artf** [comment]
Hi @piyalmaduranga,
I think I don't get what you're trying to achieve. Do you want to import bootstrap inside the GrapesJS's canvas? If so, you should be able to do it with the simple `<link>` tag inside your template (tried now and it's worked for me)

**Comment by piyalmaduranga** [comment]
Hi @artf  
i try to add template with bootstrap library to grapesjs , like this but , that not having bootstrap css 
![screenshot from 2017-01-10 08 56 08](https://cloud.githubusercontent.com/assets/12907174/21792847/aab36132-d712-11e6-82b6-9dde3145d9df.png)

**Comment by piyalmaduranga** [comment]
HI @artf 
thank you so much , now working for me
