### ISSUE TITLE
Are you able to define srcSet or picture via asset manager

### ISSUE THREAD

**Issue by lewishealey** [artf/grapesjs#2702]
When replacing an image via the asset manager, I have a requirement where I need to input multiple sizes of images for responsive optimisation. Any guidance on defining srcSet attributes or picture?

**Comment by abozhinov** [comment]
Hi, 
overwrite IMAGE component. Add listen on SRC and when changed it generate srcset attribute. 
Before that when you upload image should generate 1x and 2x version.

**Comment by pouyamiralayi** [comment]
@lewishealey you have also the option to change the assets manager behavior; checkout [#2516 comment](https://github.com/artf/grapesjs/issues/2516#issuecomment-576398168)
Cheers!
