### ISSUE TITLE
Compoentn getScript

### ISSUE THREAD

**Issue by sdrebel** [artf/grapesjs#2704]
Hi @artf ,

The way we get component.getStyle() do we have any method to get scripts or events attached to the component?

**Comment by pouyamiralayi** [comment]
Hi @sdrebel you can [retrieve any model property](https://backbonejs.org/#Model-get) by calling ``get`` function:
```
component.get('script')
```
Cheers!

**Comment by sdrebel** [comment]
@pouyamiralayi  will this give if scripts are in jquery? I tried this it returned null.

**Comment by pouyamiralayi** [comment]
@sdrebel if you have specified any script, it should return a string containing the script code.
Cheers!

**Comment by sdrebel** [comment]
@pouyamiralayi Thank You. 
If I have added along with component those scripts only I  can get right. 
Ex below code.

       dc.addType(CompName, {
        model: defaultModel.extend({
            defaults: {
                ...defaultModel.prototype.defaults,
                name: 'Test',
                draggable: true,
                droppable: true,
                resizable: true,
                script() {
                    var el = this;
                    console.log(el)
                },
        }})...
component.get('script') -- is fetching only above script
I have a code editor , where user can write own script using Js or Jquery.  Trying to get that script.

**Comment by artf** [comment]
> I have a code editor , where user can write own script using Js or Jquery. Trying to get that script.

This is has nothing to do with components and those scripts are totally unrelated
