### ISSUE TITLE
[Question] Adding image sizes to image

### ISSUE THREAD

**Issue by awaredigital** [artf/grapesjs#2705]
When I add an image attribute to the page I noticed that inside of the **component** the image has attributes to it.

When I call my images into the asset manager I do it like the following:

```
    type: 'image',
    src: 'http://placehold.it/350x250/459ba8/fff/image2.jpg',
    height: 350,
    width: 250
```

However, the height and width aren't available when the image gets added to the canvas. I've tried to get the sizes by doing:

`component.views[0].el.height`

and adding it to the object, but every time I try I get **0** because the image isn't available in the DOM yet, so it doesn't know what size it is. 

Is there a way to pass these heights and widths to the image, I need this for some lazy load functions I'm doing.  I'm currently doing this on an **update**

```
editor.on('component:update', component => {
    const item = component.attributes.attributes;
			
    // item['width'] = component.view.el.width;
    // item['height'] = component.view.el.height;

    console.log(editor.AssetManager.getAll());
    console.log('Comp:', component.views[0].el.height);
    //console.log(image.naturalWidth);
			
});
```
Should i be adding to the attributes earlier than this? 

Thanks.

**Comment by pouyamiralayi** [comment]
Hi @awaredigital checkout [#2696 comment](https://github.com/artf/grapesjs/issues/2696#issuecomment-610823851) which is updating the styles whenever the ``src`` changes.
Cheers!

**Comment by awaredigital** [comment]
Hi @pouyamiralayi, thanks for the answer but that isn't what I'm looking to do. I'm looking to add height and width to the image element itself. So for example at the moment, the image goes in like this:

`<img src="http://placehold.it/350x250/459ba8/fff/image2.jpg" id="123" />`

What I want to do is insert the image with the according height and width.

`<img src="http://placehold.it/350x250/459ba8/fff/image2.jpg" id="123"  height="350" width="250" />`

However, I can't see how to do this.

**Comment by pouyamiralayi** [comment]
@awaredigital 

>  I want to do is insert the image with the according height and width

you can do it like below:
```
domc.addType('image_basic', {
        extend:'image',
        model: {
            defaults: {
                attributes: {
                    width: '200px',
                    height: '200px',
                }
            }
        }
    })
```

>  I need this for some lazy load functions

go like below:
```
 editor.on('component:update', component => {
        const computed = getComputedStyle(component.view.el)
        console.log(computed.width)
        //....
```
Cheers!

**Comment by awaredigital** [comment]
Thank you for that, it makes sense. But, I can't see how to get the attributes of the image from the asset manager. When I try to access it, it's always data from the "image"

**Comment by artf** [comment]
@awaredigital probably the best solution would be to follow the suggestion to listen up to `src` changes, then find the right asset and update attributes accordingly
```js
model: {
	init() {
		this.on('change:src', this.onSrcUpdate);
	},
	onSrcUpdate() {
		const src = this.get('src');
		const assets = editor.AssetManager.getAll();
		const asset = assets.filter(asset => asset.get('src') == src)[0];
		if (asset) {
			const width = asset.get('width');
			width && this.addAttributes({ width });
			// ...
		}
	}
}
```

**Comment by Mustufask** [comment]
hi @artf , in my case when i upload the image in modal then the image converts to base64, but i need the actual url and store it in my api and then get my updated url in response so how can i doit?
