### ISSUE TITLE
[QUESTION] Is GrapesJS a browser or desktop editor?

### ISSUE THREAD

**Issue by Gamesnic** [artf/grapesjs#2708]
[QUESTION]

Hello there,
I have a question regarding to the installation of GrapesJS.
I'm hosting a vServer with full root control, but it doesn't have a graphics output / Teamviewer didn't work since I tried. 

**Is GrapesJS a browser based editor/sandbox or is it run on the desktop of the machine?**
This means, can you edit your website with GrapesJS in a browser, connected to let's say the IP of the server, or do you edit on the desktop of the server?
Any replys would help, thank you.

Best Regards, stay safe.

**Comment by jorisros** [comment]
Browser. As you can see here https://grapesjs.com/demo.html

It is a front-end library which can be implemented inside a CMS.

**Comment by Gamesnic** [comment]
Thank you. I'll look into it.
