### ISSUE TITLE
[Bug] Not able to use CSS variables

### ISSUE THREAD

**Issue by fzs1994** [artf/grapesjs#271]
Hey @artf again! Hope you are doing fine. As you know, I've been working on GrapesJS from last two months, it was a very satisfying response from you about every issue. Really appreciated! Thanks! 

So I want to use CSS variables for customizing some component, but what I'm facing the problem is, the variables defined in `:root{}` in CSS, their values becomes undefined. I don't know what exactly is happening. I tried a lot from my side but failed. 

![image](https://user-images.githubusercontent.com/10684213/29964671-72d2aad8-8f28-11e7-88d9-3f4694e75438.png)

Hope this gets solved sooner.
Thanks!

**Comment by artf** [comment]
@fzs1994 will fix it for the next release

**Comment by fzs1994** [comment]
Thanks, just saw now that this is fixed! Thanks!
