### ISSUE TITLE
[QUESTION] Unsplash images in asset manager modal

### ISSUE THREAD

**Issue by kuhelbeher** [artf/grapesjs#2710]
Hello, I want to add a support for unsplash API when user opens AsssetManager modal with search input (similar to Grapedrop)
![image](https://user-images.githubusercontent.com/37115006/79126984-a6d2cf80-7da9-11ea-9ebb-0c1ec515f075.png)
Is there an easy way to do it?

**Comment by pouyamiralayi** [comment]
@kuhelbeher you can use the ``assets`` option, more on this [here](https://grapesjs.com/docs/modules/Assets.html#configuration)
Cheers!

**Comment by obiweb** [comment]
Can somebody explain step by step how to integrate Unsplash API inside GrapesJS? I„m not quiet a programmer but still understand.
Thank you!

**Comment by jmlcs** [comment]
> Hello, I want to add a support for unsplash API when user opens AsssetManager modal with search input (similar to Grapedrop) ![image](https://user-images.githubusercontent.com/37115006/79126984-a6d2cf80-7da9-11ea-9ebb-0c1ec515f075.png) Is there an easy way to do it?

Did you make it?
could you share?

@artf
