### ISSUE TITLE
Disable focus of panel view container on selected element in editor

### ISSUE THREAD

**Issue by mydeenferozkhans** [artf/grapesjs#2711]
Hi
i am using grapejs for our project and my editor design is below.
My question is how to stop autofocus panel  views container.
it only show when i click the panel buttons.
It always open when we drop a element to canvas or click a element in canvas.
![image](https://user-images.githubusercontent.com/63667587/79258131-52624980-7ea8-11ea-96cc-326f461994ed.png)

**Comment by Ju99ernaut** [comment]
When you select a component in the canvas
```js
editor.on('component:selected', () => {
  //unfocus panel
});
```
When you start dragging a block onto the canvas
```js
editor.on('block:drag:start', () => {
  //unfocus panel
});
```
