### ISSUE TITLE
issue in adding custom font in grapejs

### ISSUE THREAD

**Issue by Sameedkhan25** [artf/grapesjs#2716]
@artf 
i have followed the method below and successfully added the font in list but not all of the fonts are showing correct behavior, I want to add Avenir font in the system , When i added them it is not changing the font to Avenir but giving it some default value

editor.on('load', function () {
    styleManager = editor.StyleManager;
    fontProperty = styleManager.getProperty('Typography', 'font-family');
    var list = [];
    fontProperty.set('list', list);
    list = [
        fontProperty.addOption({value: "'Oswald', sans-serif", name: 'Oswald'}),
        fontProperty.addOption({value: "Helvetica Neue,Helvetica,Arial,sans-serif", name: 'Helvetica'}),
        fontProperty.addOption({value: "sans-serif", name: 'sans-serif'}),
        fontProperty.addOption({value: "Times New Roman", name: 'Times New Roman'}),
        fontProperty.addOption({value: "Arial Black", name: 'Arial Black'}),
 fontProperty.addOption({value: "'Avenir Book', Avenir", name: 'Avenir Book'}),
          fontProperty.addOption({value: "'Avenir Medium', Avenir", name: 'Avenir Medium'}),
          fontProperty.addOption({value: "'Avenir Roman', Avenir", name: 'Avenir Roman'}),
          fontProperty.addOption({value: "'Montserrat', sans-serif", name: 'Montserrat'}),
          fontProperty.addOption({value: "'Oswald', sans-serif", name: 'Oswald'}),
          fontProperty.addOption({value: "'Shadows Into Light', cursive", name: 'Shadows Into Light'}),
          fontProperty.addOption({value: "'Pacifico', cursive", name: 'Pacifico'}),
        fontProperty.addOption({value: "Tahoma", name: 'Tahoma'}),
        fontProperty.addOption({value: "Verdana, Geneva, sans-serif", name: 'Verdana'}),
        fontProperty.addOption({value: "Courier New Courier, monospace", name: 'Courier New Courier'}),
        fontProperty.addOption({value: "'Lato', sans-serif", name: 'Lato'}),
        fontProperty.addOption({value: "'Open Sans', sans-serif", name: 'Open Sans'}),
        fontProperty.addOption({value: "'Montserrat', sans-serif", name: 'Montserrat'}),
    ];
    fontProperty.set('list', list);
    styleManager.render();
});

```

_Originally posted by @hgphpdev in https://github.com/artf/grapesjs/issues/857#issuecomment-443104577_

**Comment by artf** [comment]
Just do this
```js
const prop = editor.StyleManager.getProperty('typography', 'font-family');
prop.set('options', [
    {value: "'Oswald', sans-serif", name: 'Oswald'},
	...
]);
```
and you should never doing this `styleManager.render()`

**Comment by Sameedkhan25** [comment]
> Just do this
> 
> ```js
> const prop = editor.StyleManager.getProperty('typography', 'font-family');
> prop.set('options', [
>     {value: "'Oswald', sans-serif", name: 'Oswald'},
> 	...
> ]);
> ```
> 
> and you should never doing this `styleManager.render()`

@artf thanku so much for this

i have replaced my code with this 

i have successfully listed the fonts in the editor as show in the screenshot,
but i want to add external CSS file to add local font in the editor.
currently i m using the following method attached in screenshot.

is it the right method to import external css that i want to preload in the editor??

![grapejs3](https://user-images.githubusercontent.com/22944289/79864994-d7db8180-83f3-11ea-98f3-f582fe1dc49e.PNG)
![grapejs2](https://user-images.githubusercontent.com/22944289/79864996-d90cae80-83f3-11ea-98e9-b0d6cb978fc3.PNG)
![grapejs1](https://user-images.githubusercontent.com/22944289/79864998-d9a54500-83f3-11ea-9c6a-30cf877d7cf5.PNG)

**Comment by artf** [comment]
> is it the right method to import external css that i want to preload in the editor??

Yeah, you're doing it right, you should see it. Check your font is loading correctly (wrong path, browser compatibility with .otf, etc.)

**Comment by Sameedkhan25** [comment]
Thank u so much for this but still my fonts are not loading correctly ,

i have checked the paths and otf compatibility its working fine with simple html 

but my font is not loading in the canvas -> styles 

I am able to load fonts through CDN link but local files are not loading...
can you please recheck and guide me about it 

you help would be highly appreciated 

i just want to add the Avenir font in the editor

p.s i am using Newsletter preset

**Comment by artf** [comment]
> I am able to load fonts through CDN link but local files are not loading...

Well, this explains a lot... your local path to the font is not working, check it in the devtool, I can't help you more here

**Comment by navdeep1897** [comment]
@artf 
const prop = editor.StyleManager.getProperty('typography', 'font-family');
prop.set('options', [
    {value: "'Oswald', sans-serif", name: 'Oswald'},
	...
]);

Prop is undefined when I used in next js project. Any another way to add open-sans font family in next js?
