### ISSUE TITLE
[BUG] - Trigger "change:script" 

### ISSUE THREAD

**Issue by tranthanhhoa** [artf/grapesjs#2717]
**Version:**
0.16.40

**Bug:**
Error: Cannot read property 'style' of null
https://prnt.sc/s0bqer

**How to reproduce it:**

Goto https://grapedrop.com
Drag a Typed component and observe into canvas

Expect:
- No error

**Comment by artf** [comment]
Related to https://github.com/artf/grapesjs/issues/2656#issuecomment-610333308. Should be fixed in the next release
