### ISSUE TITLE
[QUESTION] How can I mark a class name as protected or private in a component.

### ISSUE THREAD

**Issue by ajumell** [artf/grapesjs#2719]
Hi team,

First let me thank you all for creating this wonderful library.  You guys are awesome.

I want to disable editing a specific class name in a component. like row and col. How can i do it.
I saw private and protected option in selector_manager code. But I am not sure how to implement it. Can you guys please help me on this.

**Comment by pouyamiralayi** [comment]
Hi @ajumell checkout [#1979 comment](https://github.com/artf/grapesjs/issues/1979#issuecomment-488133174)
Cheers!

**Comment by ajumell** [comment]
> Hi @ajumell checkout [#1979 comment](https://github.com/artf/grapesjs/issues/1979#issuecomment-488133174)
> Cheers!

Thanks for the response. 

I have a doubt, this is generalised right, Do we have an option per component.

**Comment by artf** [comment]
@ajumell you can check the name of your selector before making it private
```js
editor.on('selector:add', slc => 
	slc.get('name') === 'my-private-cls' && slc.set({ private: true })
);
```
