### ISSUE TITLE
[RePost] - Content html and update it by ajax

### ISSUE THREAD

**Issue by blackbirdzzz** [artf/grapesjs#272]
Hi you answer last time to my issues i wanted to change some content in html by some var 

When i'm using this my console.log(finalHtml) 
display the good change, but i don't see anything on my browser i don't know if my ajax request in jquery is good see the code bellow thanks again for your answer

` cmd.add('wikiopen', {
      run: function (editor, sender) {
 var finalHtml = editor.getHtml();
 finalHtml = finalHtml.replace("test", "caca");
 console.log(finalHtml);
 $.ajax({
  type: "POST",
  url: window.location.href,
  data: {html: finalHtml}
 })
`

**Comment by artf** [comment]
I don't think I understand properly what you say... but maybe this is what you're looking for:
```js
var finalHtml = editor.getHtml(); 
finalHtml = finalHtml.replace("test", "caca"); 
editor.setComponents(finalHtml)
```
