### ISSUE TITLE
[QUESTIONS] pages in one canvas

### ISSUE THREAD

**Issue by jozue06** [artf/grapesjs#2724]
Hello, not sure exactly where this should go, but here goes.

I'm creating a builder for making long menus for restaurants that will be printed.

My question is, does anyone have any in the wild examples of making a page-size bounding box for each page of a "menu"? 

lets say i have 150 types of beer. i'd like to make each page hold a certain amount of content, then jump to a next page, and have that visible in the canvas, basically taking the newsletter demo, and instead of infinite scroll, making a section inside the canvas <body> have multiple "page" sections of a certain size.

If aren't any examples or ideas, where would be a good place to start other than the top level grapejs docs?

Thanks all!

**Comment by Ju99ernaut** [comment]
You can make use of css properties [break-before](https://developer.mozilla.org/en-US/docs/Web/CSS/break-before) or [break-after](https://developer.mozilla.org/en-US/docs/Web/CSS/break-after). You can maybe create a page break block that you add manually after every page, check out [grapesjs-plugin-page-break](https://github.com/levonet/grapesjs-plugin-page-break), or you can break before or after a certain element.
>Always page break before `<h1>` element, [reference](https://www.w3schools.com/cssref/pr_break-before.asp)
```css
@media print{
   h1 {break-before: always;}
}
``` 
>Always page break after `<footer>` element, [reference](https://www.w3schools.com/cssref/pr_break-after.asp)
```css
@media print{
   footer {break-after: always}
}
```
