### ISSUE TITLE
editor.getCss() issue with PHP when using Cookie to pass Css styles

### ISSUE THREAD

**Issue by Chewhern** [artf/grapesjs#2725]
My company would like me to develop an automated no import(Not downloading zip and upload zip) template builder that can be used on Email marketing system. 

![Error](https://user-images.githubusercontent.com/7954644/79830298-b371ac00-83d7-11ea-8edf-fb9ebe4b3c3c.png)

However whenever I tried to export the CSS to a server file through writing and creating the file without downloading it. The CSS just contains the one that I highlighted. All the unhighlighted CSS does not include in the file. Any idea on how to solve this?

Here's my coding
![Error2](https://user-images.githubusercontent.com/7954644/79831064-495a0680-83d9-11ea-80c5-e176f993dd67.png)

**Comment by adamwpe** [comment]
Hi Chewhern,

Cookies can't hold a lot of information - something like 4k - so it will not be large enough to store CSS or HTML. You really need to use the Storage Manager.

 https://grapesjs.com/docs/modules/Storage.html

Thanks,
Adam

**Comment by Chewhern** [comment]
since you are here, I did like to know on the behavior of the storage manager, if I create a script to store those 2 data in server, can i do so without saving it directly to database? Cuz i have seen some of the people here save it directly to database.

**Comment by adamwpe** [comment]
The StorageManager is only a mechanism to get the data to your endpoint in a nice format. I would see no reason why you then can't save it into a file if you wish. Just get the $_POST data, and then do file_put_contents.

Thanks
Adam

**Comment by adamwpe** [comment]
Something like this if you don't want to use a StorageManager - assuming you have an endpoint.

```
 
        $.ajax({
            type: "POST",
            url: "/save_template",
            data: {
              html:  editor.getHtml(),    
              css:  editor.getCss()
            },
            success(response) {
                
                alert(':)');

            },
            error() {
                
                alert(':(');
                
            }
        });
```

**Comment by Chewhern** [comment]
I actually do use $_POST data on the CSS and it worked, but I can't do so with the HTML, not sure the reason behind it, but I use JS cookie to pass the HTML data to PHP. I will do so with ur ajax script or with grapesjs remotestorage if i still have the time to do so, otherwise i will notify my company and the person who takeover my task

**Comment by Chewhern** [comment]
alright thank you for your response, it indeed help me a lot, I will open up an issue again if it's required. Thanks
