### ISSUE TITLE
[BUG] Custom Component Class is not being rendered unless trait changes

### ISSUE THREAD

**Issue by adamwpe** [artf/grapesjs#2727]
I think this is a bug,

Basically, I have a custom component that has an attribute of a class ('gjs-button'), but that class only appears to get rendered/applied when a trait is changed.

1. Drag and drop the component: 
![Capture1](https://user-images.githubusercontent.com/49768920/79913334-54358b00-841b-11ea-834a-248cda3db5ff.PNG)

2. Amend the component Trait.
![Capture3](https://user-images.githubusercontent.com/49768920/79913331-539cf480-841b-11ea-8e4f-745a4803b378.PNG)

3. The component is rendered again, but now you can see the class 'gjs-button' has been applied.
![Capture4](https://user-images.githubusercontent.com/49768920/79913330-53045e00-841b-11ea-8dd0-36f9b4eda248.PNG)

I've created an example: https://jsfiddle.net/tb2gyas8/3/

Is that a bug? Or is there something wrong messing up the component?

Thanks
Adam

**Comment by adamwpe** [comment]
Appears a similar thing happens on save and reload. With this custom component, you are allowed to amend the size, but when you save and reload, the renderer doesn't draw it to the correct size, even though it has saved the correct width:

Before Save:
![Capturea](https://user-images.githubusercontent.com/49768920/80026932-d638b900-84da-11ea-9d0d-422a7c94d032.PNG)

On Reload (It has the correct with):
![Captureb](https://user-images.githubusercontent.com/49768920/80026935-d769e600-84da-11ea-8ccb-38b9bb6fe827.PNG)]

If I then change the trait, it will then default back to its original settings (AKA losing the width).

**Comment by pouyamiralayi** [comment]
Hi @adamwpe please use ``classes`` attribute instead of ``attributes``:
```
//...
resizable: true,
editable: true,
hoverable: true,   
classes:['btn','gjs-button'],
//...
```
Cheers!

**Comment by adamwpe** [comment]
Oh Thanks, @pouyamiralayi,

Seen someone used attributes and assume that was the correct method - worked like a charm!
