### ISSUE TITLE
[QUESTION] How can I set the background image of a component programtically.

### ISSUE THREAD

**Issue by ajumell** [artf/grapesjs#2728]
Hello,

I want to create an option to change background of a component by double clicking it. I could open the modal when double clicking it. But how can I se the background-image property using it. I checked the codebase couldn't find a clue. Have any one done something similar. Please provide some suggestions or leads.

**Comment by artf** [comment]
@ajumell when, for example, you select the background to apply you can change the component background in this way 
```js
component.addStyle({ 'background-image': `url('${url}')` })
```
