### ISSUE TITLE
[Question] Updating to latest verion

### ISSUE THREAD

**Issue by DaithiLynch** [artf/grapesjs#2729]
I updated to the latest version 0.16.3 from the downloaded newsletter 0.10.7 , the test-form for sending a test mail does not work in the newer version, actually it seemed to have stopped working after verion 0.10.8 , , the form itself seems to be appended to the end of the screen when opened

**Comment by artf** [comment]
Yeah that thing was dropped years ago (the service on which it was relying disabled the possibility to use it in that way)

**Comment by DaithiLynch** [comment]
Hi Arthur,

Thanks for reply,
It is not the sending that is the problem, I have that covered, it is the showing of the actual modal that is the issue, the send button is missing along with the subject , no matter what I tried to do, it will not show, it will in 0.10.7 but not any newer versions

**Comment by artf** [comment]
don't try to reuse that modal, just create your own...
