### ISSUE TITLE
Webpack fails, Missing dependency jQuery

### ISSUE THREAD

**Issue by SimplyCorey** [artf/grapesjs#273]
Webpack fails to compile due to jQuery not be installed, even when it is.  This is due to it looking for jQuery and not jquery (3.x)

This can be fixed here: https://github.com/artf/grapesjs/blob/master/webpack.config.js#L30

Once I changed this line, it compiled correctly.

`jQuery` is deprecated and `jquery` should be used.

![image](https://user-images.githubusercontent.com/624784/29983954-2854d5d2-8f26-11e7-8406-33ec5ac77298.png)

**Comment by ahmeddabak** [comment]
```npm install jquery```

and then in your main.js

```js window.$ = window.jQuery = require('jquery');```

![capture](https://user-images.githubusercontent.com/11370582/30016773-be730e94-9156-11e7-953f-458c371c6bb5.PNG)

**Comment by artf** [comment]
strangely on my side, everything works fine even when apparently shouldn't 
```js
externals: {jquery: 'dasjkdhas'}, // jquery "correctly" unbundled
//...
externals: {stuff: 'dasjkdhas'}, // no errors, but at least jquery is bundled
```
I think this should work fine for everyone
````js
externals: ['jquery'],
```
will update on the next release

**Comment by SimplyCorey** [comment]
@ahmeddabak Doesn't work for me unfortunately.  The externals need's to be updated for webpack to compile this down for me, or it errors out before it even gets to my main.js

@artf Thanks.

**Comment by artf** [comment]
Have to rectify, with `externals: ['jquery'],` once it's bundled, it doesn't work as expected and [spectrum](https://github.com/bgrins/spectrum) throws errors about missing jQuery (?!? wtf). What I've discovered is that the bundled file was loading as an `amd` module instead as a root and as jquery might be loaded differently  ($, jQuery, require('jquery')...)  so causes a mess with some dependency.
Seems like the correct way is:
```js
externals: {
    jquery: {
      commonjs: 'jquery',
      amd: 'jquery',
      root: 'jQuery'
    }
  },
```
will try also to update the webpack
