### ISSUE TITLE
[QUESTION] Keep Hover state when amending the child

### ISSUE THREAD

**Issue by adamwpe** [artf/grapesjs#2738]
I'm trying to edit a dropdown list option, and it's quite difficult to style it because you cannot move your mouse to the Style Manager since the hover will disappear. So is there a way to keep the hover state active when amending a child? 

I know you can style using the Layer Manager - but that's not as user friendly, just wondering if anyone has discovered a nice work around this issue.

Made a super simple demo of the problem.
https://jsfiddle.net/3g8yd9tL/

**Comment by Ju99ernaut** [comment]
Had tried this, but realized you can only edit the styles for the hover state.

```html
<div id="gjs">
  <div style="padding: 25px">Hello World!!!</div>
  <style>
     :root{
        --display: none;
     }

     .dropbtn {
        background-color: #4CAF50;
        color: white;
        padding: 16px;
        font-size: 16px;
        border: none;
    }

    .dropdown {
       position: relative;
       display: inline-block;
    }

    .dropdown-content {
      display: block;
      position: absolute;
      background-color: #d42020;
      min-width: 160px;
      box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
       z-index: 1;
    }

    .dropdown-content a {
      color: black;
      padding: 12px 16px;
      text-decoration: none;
      display: var(--display);
    }

    .dropdown-content a:hover {
       background-color: #ddd;
       --display: block;
    }

    .dropdown:hover {--display: block;}
  </style>
</div>
```

```js
const editor = grapesjs.init({
  container: '#gjs',
  fromElement: 1,
  height: '100%',
  storageManager: { type: 0 },
  plugins: ['gjs-blocks-basic']
});

editor.BlockManager.add("dropdown-menu-in-navbar",
  {
     label: 'Dropdown Menu',
     tab: "1",
     category: "Others",
     type: "default",
     attributes: {
       class: 'fa fa-ellipsis-h',
       title: 'Insert Dynamic Menu of Navigation'
     },
    content: `
     <div class="dropdown">
       <button class="dropbtn">Dropdown</button>
       <div class="dropdown-content">
         <a class="dropdown-content-a" href="#">Link 1</a>
         <a class="dropdown-content-a" href="#">Link 2</a>
         <a class="dropdown-content-a" href="#">Link 3</a>
       </div>
     </div>`
});
```
![fiddle](https://user-images.githubusercontent.com/48953676/80318771-b5d76a00-880c-11ea-84dc-6a563ac2200d.PNG)

**Comment by Ju99ernaut** [comment]
You can also just select the `div.dropdown-content` and set its display to block in the `Style Manager` then set it back to none when you finish editing.

**Comment by adamwpe** [comment]
Hi Ju99ernaut -

That does work, actually - but I wonder if it's possible to bind a 'component:selected' event, which will change the display type of the child component, and then when unselected, it will revert the display type?

**Comment by adamwpe** [comment]
I had a play with some custom select events and I don't think it will very manageable. Because if you then select a list item, it still needs 'dropdown-content' to display to block, and then unselecting will become a pain. Don't know if there is a better solution?

```

        editor.on('component:selected',  model => {

            model.get('components').each(child => {

                child.setStyle({
                    display: 'block'
                });

            });
            
        });
```

**Comment by artf** [comment]
For such a case you'd need to create a custom component and add a trait (eg. a button type) which toggles the visibility (eg. by adding a class or attribute in the View of the component). You'll need also to extend the CSS which makes items appear on hover
```scss
// Pseudo code example

// From
.dropdown:hover .items {
	// show items
}

// To
.dropdown:hover .items,
.dropdown.show-items .items {
	// show items
}
```

**Comment by adamwpe** [comment]
@artf Thank you! 

I made an example of a working Drop Down List for anyone who comes across this.

https://jsfiddle.net/f74zqpgx/

Adam

**Comment by karol93** [comment]
> @artf Thank you!
> 
> I made an example of a working Drop Down List for anyone who comes across this.
> 
> https://jsfiddle.net/f74zqpgx/
> 
> Adam

your solution is very helpful, thank you very much for it but I have one question. do you know why I can not add whitespace in the dropdown?
