### ISSUE TITLE
if there is an uncompressed version for study. Thank you for opening source

### ISSUE THREAD

**Issue by momu-smartcoach** [artf/grapesjs#274]
Nice to meet you. I'm a beginner. I'm interested in your project, but I see JS is a compressed version. I don't know if there is an uncompressed version for study. Thank you for opening source

**Comment by ahmeddabak** [comment]
you can check the source code here on github

[https://github.com/artf/grapesjs/tree/dev/src](url)

**Comment by momu-smartcoach** [comment]
Thanks for the answer，but i may need the https://github.com/artf/grapesjs/tree/dev/dist  grapes.min.js,but it's a compressed version

**Comment by ahmeddabak** [comment]
Here you go, but i do not think it will help you as Grapejs is written as js modules that need to be bundled together with Webpack and the result file is not as clear as the source modules.

[grapes.zip](https://github.com/artf/grapesjs/files/1275134/grapes.zip)

**Comment by momu-smartcoach** [comment]
Thank you for your generosity!!!

**Comment by artf** [comment]
as @ahmeddabak already said https://github.com/artf/grapesjs/tree/dev/src is where all the source in (https://github.com/artf/grapesjs/blob/dev/src/grapesjs/index.js is the starting point)
