### ISSUE TITLE
[QUESTION] How to prevent unique ids generation?

### ISSUE THREAD

**Issue by nikita-balakirev** [artf/grapesjs#2742]
Hi! Thanks for your work @artf.
This is a simplified code of how I use grapesjs, I want to save the styles and then want to apply them again. The problem is that ids already changed in DOM after first call of `container.components()` so styles will not be applied.
How to prevent this behavior? What should I clear/reset?

```
wrapper = [...]
style = [...]
components = [{mainBody: [...]}]

this.editor.setComponents(
  Array.isArray(wrapper) ? this.pruneWrapper(wrapper) : wrapper,
);
const grapesWrapper = this.editor.getWrapper();

const [container] = grapesWrapper.find(
  '[data-main-container]',
);

if (container) {
  container.components(components.mainBody);
}
if (style) {
  this.editor.setStyle(style);
  const grapesJsWrapper = this.editor.getWrapper();
  grapesJsWrapper.rerender();

}
```

**Comment by nikita-balakirev** [comment]
I fixed it now using `editor.DomComponents.componentsById = {};`
but I think it can lead to collisions between blocks at some point
what do you think?

**Comment by pouyamiralayi** [comment]
Hi @nikita-balakirev see if [#2706 comment](https://github.com/artf/grapesjs/issues/2706#issuecomment-610902152) can help you.
Cheers!

**Comment by artf** [comment]
Sorry @nikita-balakirev can't help you here without a complete reproducible example. 
When you export components as JSON all IDs are preserved and reused if load correctly, so for sure you're doing something wrong with storing/loading data.
Obviously you shouldn't prevent unique ids generation (or doing what you did) as it'll break a lot of stuff

**Comment by ahmedmeskine** [comment]
Hello i was using grapejs with vuejs and had the same problom.
I was saving components and style as json objects
- let components =this.editor.getComponents().toJSON();
then load them with setComponenets 
-    this.editor.setComponents(JSON.parse(components));
my editor would take very long to load then as soon as i try to edit an image or anything it freezes.
when i checked to html and css i found that the editor would changed the id from #id95 to #id95-2-2-2-2 everywhere

my solution was to load the componenets and style in the init function when creating the editor like this 

 this.editor = grapesjs.init({
            container: '#editor',
   
            plugins: plugins,

            showOffsets: 1,
            noticeOnUnload: 1,
          
            components: JSON.parse(components),
            style: JSON.parse(style),
            storageManager: { autoload: 0, autosave: 0, },


        });
