### ISSUE TITLE
Mouse hovering overlaping on text toolbar ckeditor/richtext editor

### ISSUE THREAD

**Issue by NorthstarTech** [artf/grapesjs#2746]
When ckeditor/richtext toolbar is open. Mouse hovering on elements, Border line overlapping the toolbar. borders overlaping.

**Comment by adamwpe** [comment]
Can you provide an example? Ideally using https://jsfiddle.net/szLp8h4n

**Comment by bgrand-ch** [comment]
Hello,

For future questions or technical issues, which aren't bugs, GitHub's [Discussions](https://github.com/artf/grapesjs/discussions) tab is the place to be.

Don't forget to close this issue if it is resolved or write a new detailed message in [Discussions](https://github.com/artf/grapesjs/discussions) -> [Q&A](https://github.com/artf/grapesjs/discussions/categories/q-a) category (and close this issue).

Thank you for your understanding.

**Comment by sanjaysamcom** [comment]
How to resolve one section to another section drag-drop overlapping issue?
