### ISSUE TITLE
[FEATURE REQUEST][BUG] Slider doesn't work with a non-integer step value

### ISSUE THREAD

**Issue by sjul66** [artf/grapesjs#2748]
Default StyleManager property "slider" doesn't work with a non-integer step value.
GrapesJS version: 0.16.1

In many cases, it’s convenient to use a slider with a non-integer step value:
![GrapesJS](https://user-images.githubusercontent.com/34565082/80721884-6f815400-8b07-11ea-893f-041551c1a4e5.gif)

seems that Grapesjs supports only integer and rounds non-integer values.

**Steps to reproduce:**
Add a property with type 'slider'
```
var property = styleManager.addProperty('mySector',{
   name: 'Opacity',
   type: 'slider',
   property: 'opacity',
   defaults: 1,
   step: 0.1,
   max: 1,
   min: 0,
   }, { at: 0 });
```

**Comment by adamwpe** [comment]
HI @sjul66 

This is my one and it does work fine:

```


        editor.StyleManager.addSector('Extras',{
            name: 'Extras',
            open: false,
            properties: [{
                property: 'opacity',
                type: 'slider',
                defaults: 1,
                step: 0.01,
                max: 1,
                min: 0
            }]
        }, { at: 9 });

```

Looks like your properties entry is different from mine.

Thanks
Adam

**Comment by adamwpe** [comment]
Oddly enough - this works for me (I know I'm creating the sector at the same time):

```
        editor.StyleManager.addSector('General',{
            name: 'Extras',
            open: false,
            properties: [{
                property: 'opacity',
                type: 'slider',
                defaults: 1,
                step: 0.01,
                max: 1,
                min: 0
            }]
        }, { at: 9 });
```

Can you make a demo?

**Comment by sjul66** [comment]
Yes of course. 
I've created a sample with your snippet, but seems that it doesn't want to work with me.

https://codepen.io/sjul66/pen/VwvMwNY

Thanks!

**Comment by sjul66** [comment]
Hi Adam,

So many thanks for your reply!
Sorry for bothering you, you know I was sure that rounding in
the downArrowClick/upArrowClick methods was the reason.

Best regard,
Julia

**Comment by adamwpe** [comment]
Ah, you mean the arrows - sorry, thought you meant in general that the slider doesn't work.

![image](https://user-images.githubusercontent.com/49768920/80743652-35b74a00-8b15-11ea-9a13-a1545f4e86b2.png)

Never noticed that - always use the slider order the mouse dragging over the arrows.

I'll have a look at the view - not too sure where to start haha.
