### ISSUE TITLE
Shared styles between pages

### ISSUE THREAD

**Issue by makkaronis4e** [artf/grapesjs#2750]
Hi,

i want to have multiple pages whith shared styles. But when i'm switching between pages, it replaces not only components but also css rules and stores css rules separately.
Are there any way to have shared styles?

UPD: Managed to implement in different way/ Closed

**Comment by etamity** [comment]
@makkaronis4e 
chould you share how did you implemented? Thank you.

**Comment by zee-algo** [comment]
@makkaronis4e 
Can you please your implementation?

**Comment by gxanshu** [comment]
can you please share implementation
