### ISSUE TITLE
Exact size in media query

### ISSUE THREAD

**Issue by motazad** [artf/grapesjs#2752]
I want the changes made to the page to be displayed only when the size is selected.  
[Image](http://uupload.ir/files/gez8_captured.gif)

**Comment by motazad** [comment]
@artf In fact I want min-width and max-width for devices selected

**Comment by artf** [comment]
You can add your own [devices](https://grapesjs.com/docs/api/device_manager.html)

**Comment by motazad** [comment]
> You can add your own [devices](https://grapesjs.com/docs/api/device_manager.html)

But it only works with the max-width

**Comment by MohammadGh2179** [comment]
I have the same problem 
please help me
Thanks

**Comment by artf** [comment]
The only other option is to change the [mediaCondition](https://github.com/artf/grapesjs/blob/fbfa812eaaeeb467337107896ee6decfbfbc028e/src/editor/config/config.js#L96), you can't have both now. 
If you have a better way to handle devices PRs are welcome

**Comment by motazad** [comment]
I used a trick and it was solved.

`    deviceManager.add('Extra Small', '576px', {
      widthMedia: '576px'
    });
    deviceManager.add('Small', '767px', {
      widthMedia: '767px) and (min-width:577px'
    });
    deviceManager.add('Medium', '991px', {
      widthMedia: '991px) and (min-width:768px'
    });
    deviceManager.add('Large', '1199px', {
      widthMedia: '1199px) and (min-width:992px'
    });
    deviceManager.add('Extra Large');`

**Comment by teknosains** [comment]
> deviceManager

You're the man @motazad ..i;ve been suffering this issue so long. Didnt realize that it was just a string


```javascript
 grapesjs.init({
     mediaCondition: screen === 'mobile' ? 'min-width' : 'max-width',
     deviceManager: {
        devices: [
            {
              id: 'desktop',
              name: 'Desktop',
              width: '720px',
              widthMedia: '3840px) and (min-width:720px', // trick it to make it right
              priority: 1,
            },
            {
              id: 'tablet',
              name: 'Tablet',
              width: '550px',
              widthMedia: '680px) and (min-width:550px',
              priority: 3,
            },
            {
              id: 'mobilePortrait',
              name: 'Mobile portrait',
              width: screen === 'mobile' ? '320px' : '380px',
              widthMedia: screen === 'mobile' ? '320px) and (min-width:320px' : '480px) and (min-width:380px',
              priority: 2,
            },
        ],
    },
});
```

will produce

```css
@media (max-width: 3840px) and (min-width:720px) {

}
...
```
