### ISSUE TITLE
[QUESTION] Change 2 properties values in Style manager

### ISSUE THREAD

**Issue by Lerdouille** [artf/grapesjs#2755]
Hi,

i woud like to add a switcher in the style manager to update multiple properties in one click.
For example, a switcher with some font awesome icons to align the DOM with the properties margin-left and margin-right.
If i click on the "Align left" button, i would like to update both property "margin-left" and "margin-right"

Is it possible ?

Best regards

**Comment by artf** [comment]
At the moment it's not that easy (we don't have documentation for custom styles) so, for now, I'd recommend using [Traits](https://grapesjs.com/docs/modules/Traits.html)
