### ISSUE TITLE
[HELP] Hide style manager if no component selected

### ISSUE THREAD

**Issue by makkaronis4e** [artf/grapesjs#2757]
Hi, i want to reproduce default gjs behavior, when style-manager is hidden if no component selected.
like this:
![image](https://user-images.githubusercontent.com/33792090/81327850-9b22b200-90a4-11ea-884d-234ecae1ed7b.png)

But it seems like this doesnt work by default, if markup is custom, like in artf example here:
https://codepen.io/artf/pen/MQpZPj

**Comment by artf** [comment]
Yeah, that logic is handled in this [command](https://github.com/artf/grapesjs/blob/fbfa812eaaeeb467337107896ee6decfbfbc028e/src/commands/view/OpenStyleManager.js#L46) which is not included with a custom UI, so you have to add it on your own
