### ISSUE TITLE
Change edito language

### ISSUE THREAD

**Issue by grodriguez88** [artf/grapesjs#2759]
Hi

I'm trying to change the editor language, I've added this lines in grapesjs.init:

```
i18n: {
                locale: 'it', // default locale
                localeFallback: 'it', // default fallback
                messages: { it },
            }
```

But this not works for me.

Thanks in advance

**Comment by ZaheerNiazi007** [comment]
@grodriguez88  please update your grapes js version
    
    i18n: {
      locale: "en",
      detectLocale: false,
      messagesAdd: {
        en: en,
      },
    },
    and use this 
    mine is working perfectly
