### ISSUE TITLE
Fonts, CSS3 keyframes

### ISSUE THREAD

**Issue by janisppc** [artf/grapesjs#276]
Hi! 

I am working on a project where GrapesJS is used for Bootstrap template editing. Almost everything is so far so good except I have some trouble with custom font integration and some CSS3 features. 

1. What is the correct way of including new fonts in the template? How to alter inbuilt ones? 

I have tried to include @font-face in the inline CSS of the template or in an external file passed with the script but the Editor is just ignoring it. 
My problem is because of missing Font-Awesome fonts the editor does not show icons for a templates that are using them. 

2. I also noticed GrapesJS is crashing if CSS3 keyframes are included in the inline css of the template.

**Comment by artf** [comment]
At the moment I just don't support them, for now, you can load them staticly inside the editor
```js
grapesjs.init({
    canvas: {
            styles: ['https://...style.css'],
    }
})
```
