### ISSUE TITLE
Resolved - "Â" characters in HTML (character encoding issue)

### ISSUE THREAD

**Issue by supershwa** [artf/grapesjs#2761]
Regarding the (closed) thread here:  https://github.com/artf/grapesjs/issues/1693

I had the same problem with "Â" characters replacing tabs, and creating havoc each time I saved the content.

I realized that the server I had it on was on an outdated version of PHP (version 5-ish).  I promptly upgraded PHP to the latest (7.something) which solved the problem.  My guess is that it had something to do with character encoding in older versions of PHP.

Just thought I'd drop this here for future reference.

**Comment by artf** [comment]
Great, thanks @supershwa for the reference
