### ISSUE TITLE
[QUESTION] How to listen to trait value change directly from block add

### ISSUE THREAD

**Issue by lofcz** [artf/grapesjs#2762]
I'm passing following JSON to `editor.BlockManager.add()` function to define my block, load it's content from the server and populate select-type trait named `defaultCategory` in the same manner.  
Everything works nice. Now I need to listen to `onchange` event of that select and execute some JS there. 
I've consulted https://grapesjs.com/docs/modules/Traits.html#add-traits-to-components but can't fugure out how to do this. 

Would you mind to quickly show how would I execute `alert('test')` when value of my trait is changed (by user selecting one of the options)? Thanks in advance.

```js
{
    label: '<img src="/Uploads/Lanbuilder/articlesRow.png" class="lanbuilderIcon" width="50" height="50"/><div>My block</div>',
    category: c.category,
    attributes: {
      class:'gjs-fonts gjs-f-b4',
      defaultCategory: ''
    },
    content: {
        content: 'AJAX loading content of this block...',
        script: function() {
          moduleCommonFunctions.loadContentToDiv(this.id, '/topic/getTopicRow');
        },
        traits: [
          {
            type: 'select',
            name: 'defaultCategory',
            label: 'Default category',
            options: JSON.parse(categoriesJson)
          }
       ]
    }
  });
```

![image](https://user-images.githubusercontent.com/10260230/81474361-33d04380-9205-11ea-8bee-f4628bfe1750.png)

For the button there is an option we can assign our JS, it would be really usefull to have such event for all built in trait types.

![image](https://user-images.githubusercontent.com/10260230/81474860-6fb8d800-9208-11ea-9d0a-ef0a2a775953.png)

**Comment by adamwpe** [comment]
Have you tried listento?

Something like this:

```
   editor.DomComponents.addType('something', {
            model: {
                init() {

                    this.listenTo(this, 'change:attributes', this.myFunction);

                },
              //// normal setup
                myFunction() {
                    this.view.render();
                }
           }
        });
```

Otherwise, create a fiddle with it:

https://jsfiddle.net/szLp8h4n

Thanks,
Adam

**Comment by Aiyush-G** [comment]
Did you solve this issue? If so, how?

**Comment by SwapnilSoni1999** [comment]
guide please

**Comment by Vampire-V** [comment]
@lofcz How do you fix this problem?
