### ISSUE TITLE
[Bug]  backspace key trigger navigating back

### ISSUE THREAD

**Issue by svalenciano81** [artf/grapesjs#2765]
Hi,

in grapesjs  in Firefox  75.0  when  "backspace key"  (event.which === 8) is pressed the navigator is going back and grapesjs is lost.

To reproduce it:
Open Firefox browser
Open URL: https://grapesjs.com/
Click on: "Newsletter Demo" buttom
Delete a element from editor usign "backspace key"          (NOT using supr key)

The behavior is:  the navagator is going back and the editor is lost.

I am trying this but it doesn't work:

      **$document.on('keydown', function(e){
          if(e.which === 8){ // you can add others here inside brackets.
            e.preventDefault();
            e.stopPropagation();
          }
      });**

i can do something over/inside editor instance  to disable "firefox behavior" and prevent go back in history in browser?

thanks.

**Comment by tiptronic85** [comment]
Yes this is very annoying

**Comment by Lloyd66** [comment]
Hi,
Encountering the same issue : with Firefox on Mac, when you click on a block without having the focus, if you press backward key it goes back.

This does not happen on Chrome on Mac, neither with Firefox or Chrome on Ubuntu.

Thanks

**Comment by artf** [comment]
Should be fixed in the next release

**Comment by juice77** [comment]
Hello, I have noticed that after this commit on components of type text the backspace and delete keys doesn't work anymore. The only way to delete a string is to select it and press backspace.

**Comment by artf** [comment]
@juice77 the issue was fixed in the latest release https://github.com/artf/grapesjs/compare/v0.16.17...v0.16.18
