### ISSUE TITLE
[BUG] set background-color to table/table-cell  in Firefox not working

### ISSUE THREAD

**Issue by svalenciano81** [artf/grapesjs#2766]
Hi

**Where can I reproduce it?**  
In demo url: https://grapesjs.com/demo-newsletter-editor.html

**Browser info:**
Firefox 75.0

**How can I reproduce it?**
Select a table or table-cell and  try change background-color with picker selector.  The result no change the color :(

**Comment by svalenciano81** [comment]
Increase the alpha channel   solve the problem   :-)

**Comment by svalenciano81** [comment]
but,   why  alpha channel is "0" by default in Firefox  and is "100" in chrome?

**Comment by artf** [comment]
I close this in favor of #3260
