### ISSUE TITLE
how to integrate grapesjs in loopback application

### ISSUE THREAD

**Issue by HPsisodia** [artf/grapesjs#2767]
I am working on a loopback application and wanted to integrate grapesjs, so that the client can make his own web template which will be later used by the server to send some information overlayed on the template. However, i am not able to integrate grapesjs and run it alongside when the main application when server starts. I am new to this so don't know much about this, i will really appreciate any help

**Comment by cartifon** [comment]
GrapesJS is a Client side JavaScript library, I don't think you can add that to a back-end NodeJS application.... But I may be wrong... What do you think @artf ?

**Comment by artf** [comment]
@HPsisodia on the client you render the editor using the grapesjs, with loopback you just provide API (https://grapesjs.com/docs/modules/Storage.html#setup-the-server). If you don't know how to set up the server with loopback, unfortunately, this is not the right place to ask
