### ISSUE TITLE
[QUESTION] Can I add listener when user drag element on the canvas?

### ISSUE THREAD

**Issue by kuhelbeher** [artf/grapesjs#2768]
Hello, GrapesJS has bunch of events which could be listened with editor.on. One of them is `canvas:drop`. But it triggers only when I drop element which hasn't been on canvas yet. But I want to listen when user drops some component which already existed on canvas. Can I achiive this?

**Comment by cartifon** [comment]
Hi @kuhelbeher, in the version 16.2 they added that option, you can take a look here: 
https://github.com/artf/grapesjs/releases/tag/v0.16.2
