### ISSUE TITLE
[QUESTION] - Event Handler from KeyMap should trigger the core events?

### ISSUE THREAD

**Issue by cartifon** [artf/grapesjs#2769]
Hey @artf, question, should the core commands be triggered when the keyMap is activated?

The situation:

I added this listeners: 

```
 
function addCommands() {
  console.log(editor.Commands.getAll());
  editor.on('run:core:component-delete:before', function (options) {
    console.log('run:core:component-delete:before: ', options);
  });
  editor.on('run:core:component-delete', function (options) {
    console.log('run:core:component-delete: ', options);
  });
  editor.on('core:component-delete', function (options)  {
    console.log('core:component-delete: ', options);
  });
  const keyMaps = editor.Keymaps;
  console.log('keyMaps: ', keyMaps.getAll());
}
```

When I delete a component using the delete icon it calls my listener, but when I press the `delete` key, it does not trigger the listener... Am I doing anything wrong here? 

You can check it here:
https://www.w3schools.com/code/tryit.asp?filename=GEQBCR5CLYQF

**Comment by artf** [comment]
Yeah, you're right, the command handler is executed directly here https://github.com/artf/grapesjs/blob/fbfa812eaaeeb467337107896ee6decfbfbc028e/src/keymaps/index.js#L154
it should pass through `Commands.run(id, opts)` https://github.com/artf/grapesjs/blob/fbfa812eaaeeb467337107896ee6decfbfbc028e/src/commands/index.js#L310
Would you like to create a PR? :)
