### ISSUE TITLE
[QUESTION] Set selected element

### ISSUE THREAD

**Issue by tiptronic85** [artf/grapesjs#2770]
Hello,
is there a way to select an element after added to the body?
When i add a link, i want to open the Component Settings immediately.

How can i do it ?

Thank you in advance

**Comment by Mohsen-Khakbiz** [comment]
I think this should work
```
editor.on('component:mount', function(model) {
	editor.select(model);
	const openBl = editor.Panels.getButton('views', 'open-tm');
	openBl && openBl.set('active', 1)
});
```

**Comment by tiptronic85** [comment]
It works, thank you a lot.
I add the code only for links and button and it is perfect.

`if model.is('link')`
