### ISSUE TITLE
[Question]: loading scripts/css to the canvas depending on traits

### ISSUE THREAD

**Issue by Mohsen-Khakbiz** [artf/grapesjs#2772]
hey there. first of all thanks for this sweet lovely tool.

what I need is to load js or css files to the canvas depending on traits.
let's say I have a button with an option for making it triggering a lightbox.
![1](https://user-images.githubusercontent.com/1507948/81849162-64004500-956b-11ea-9927-867bff19dfbc.jpg)

now what I need is to only load the lightbox plugin's files only when this checkbox is checked.
I couldn't manage doing this from Component's "script" property. in a clean way at least
![2@2x](https://user-images.githubusercontent.com/1507948/81849776-454e7e00-956c-11ea-8ea4-b1fdc234a1cd.jpg)

this one may work btw. but I just prefer to have something like a global list of scripts or styles, and at the end put them in my html
something like canvas: { scripts: [] } but I want to be able to dynamically add to this list

**Comment by artf** [comment]
When you use `canvas: { scripts: [], styles: [] }` it appends only those files to the canvas of the editor, so you won't see them in your final code (`editor.getHtml()`).
There is no kind of global list but you still can tell the component to avoid including your script

```js
const myScript = function() {
	const el = this;
	// ...
}

editor.Components.addType('...', {
	model: {
		init() {
			this.on('change:my-trait-prop', this.onTraitPropChange);
			this.onTraitPropChange(); // do the check on init
		},

		onTraitPropChange() {
			const prop = this.get('my-trait-prop');
			
			prop ? this.set({ script: myScript }) : this.set({ script: '' });
		}
	}
})
```
