### ISSUE TITLE
[BUG] (type: video) html5 always src of previous provider

### ISSUE THREAD

**Issue by Light0815** [artf/grapesjs#2773]
Minor bug:
When switching video type component to html5 provider it always takes the src of the previous provider. Instead I would expect it to be cleared. This also has another side effect since it seems (without checking code) that you set the provider depending of the src. This is especially annoying when you save a page and reload it to the editor. 
It also does not trigger an editor.on('update'). When switching from the wrong provider to the html5 provider since nothing changes in the canvas.

**Comment by artf** [comment]
It should be fixed in the next release, thanks for the report
