### ISSUE TITLE
mediaCondition: "min-width" breakpoints not applying the correct style in canvas

### ISSUE THREAD

**Issue by vinceumo** [artf/grapesjs#2774]
Hi, 

I'm having some issue with mobile first approach. The canvas render the wrong style when setting different styles at multiple breakpoints. But the code generated is good, this issue only happen in the canvas.

https://codesandbox.io/s/xenodochial-shockley-s02lp?file=/index.js:496-524

```js
const breakpoints = [
  { name: "xs", width: "320px" },
  { name: "xsLg", width: "400px" },
  { name: "sm", width: "630px" },
  { name: "md", width: "740px" },
  { name: "lg", width: "1024px" },
  { name: "xl", width: "1280px" },
  { name: "xxl", width: "1800px" }
];

const editor = grapesjs.init({
  container: "#gjs",
  fromElement: 1,
  storageManager: { type: 0 },
  mediaCondition: "min-width",
  deviceManager: { devices: breakpoints },
  plugins: ["gjs-blocks-basic"]
});

```

![Screenshot 2020-05-14 at 12 49 03](https://user-images.githubusercontent.com/21067002/81931499-24c10b00-95e2-11ea-9220-f650e4175fb2.png)

 1. Are you using the latest release (older versions are NOT supported)?
     **Yes using 0.16.12**
  1. Are you facing the bug with your local copy of GrapesJS or with the current demo?
      **With my local copy**
  1. If a local copy
      1. Indicate all informations about your OS, browser and GrapesJS version.  
           **MacOs, tried on firefox and Chrome and same issue**
  1. What is the expected behavior?
     **Still should change according to the breakpoint in the canvas when using mediaCondition: "min-width"**
  1. What happens instead?
    **Style in canvas only apply the change from the 1st breakpoint. but the code in the export view is right. The issue is only in how the canvas render.**
  1. If you're able to reproduce the bug indicate all the necessary steps
     - **Follow this codesandbox https://codesandbox.io/s/xenodochial-shockley-s02lp?file=/index.js:496-524**
     -  **Change the device to xs**
     -  **Select the copy box and change the color of this one**
     -  **Change the device to md**
     -  **Select the copy box and change the color of this one to a new color, the color is still the old one from xs**
     -  **Desktop first works fine**

Thanks a lot for your help

**Comment by artf** [comment]
We should apply the same logic from https://github.com/artf/grapesjs/blob/201e1f9a61783080f7be885e9e0be9a40ecc16cc/src/code_manager/model/CssGenerator.js#L151-L162
here
https://github.com/artf/grapesjs/blob/201e1f9a61783080f7be885e9e0be9a40ecc16cc/src/css_composer/view/CssRulesView.js#L122-L129
