### ISSUE TITLE
[QUESTION] Is it possible to use grapejs for printable documents?

### ISSUE THREAD

**Issue by math-artist** [artf/grapesjs#2776]
Hello, I have a requirement to create a drag and drop template editor for a desktop application, to generate beautiful reports, and found almost nothing to do that easily. Then I found grapejs, and I am considering using the Qt WebEngine and have grapejs embedded in my application.

I may have a web-based version of my application in 1-2 years, so that could be a better long-term solution.

But I will also need to properly print the documents with headers and footers, and manage height and width more like a "paper" document editor.

Is my idea a bad idea? Is there a better framework for what I am trying to do? I searched and found nothing without having to build everything from scratch.

**Comment by Ju99ernaut** [comment]
I think `grapesjs` would be perfect for your use case. Here #2724 it's probably being used in the same context.

**Comment by math-artist** [comment]
Ok, that seems right the right solution to manage a long list or table.

Is there a way to lock the height of the web page and see the layout limit while editing? My plan is to create 3 or 4 pages with the same footer and insert variable tags in the layout to fill those pages dynamically.

**Comment by Ju99ernaut** [comment]
For pages that's a matter of creating a page [block](https://grapesjs.com/docs/modules/Blocks.html#custom-render) with height defined. As for variable tags, those can be included in the block as well.

**Comment by artf** [comment]
@math-artist check the [DeviceManager API](https://grapesjs.com/docs/api/device_manager.html) where you can use a custom height for the canvas preview
