### ISSUE TITLE
[Question] How to change attributes for defined model's?

### ISSUE THREAD

**Issue by bungambohlah** [artf/grapesjs#278]
Hi @artf see you again :smiley: 
I have a question, first i was define a new component for example is collapsible
```javascript
...
          var domComps = editor.DomComponents;
          var dType = domComps.getType('default');
          var textType = domComps.getType('text');
          var dModel = dType.model;
          var textModel = textType.model;
          var textView = textType.view;
          var dView = dType.view;

          domComps.addType('collapsible', {
              model: dModel.extend({
                defaults: Object.assign({}, dModel.prototype.defaults, {
                  droppable: false,
                  ...
                  script: function() {
                    $(document).ready(function(){
                      $('.collapsible').collapsible();
                    });
                  }
                }),
              }, {
                isComponent: function(el) {
                  if(el.getAttribute && el.getAttribute('data-gjs-type') == 'collapsible') {
                    return {
                      type: 'collapsible'
                    };
                  }
                },
              }),

              view: dView.extend({
                init() {
                  const view = this;
                  const comps = this.model.get('components');
                }
              }),
          });
...
```
and then in blockmanager
```javascript
...
          var blockManager = editor.BlockManager;
           ...
          // Collapsible Materialize
          blockManager.add('collapsible-materialize', {
            label: 'List of Menu',
            attributes: {
              class: 'fa fa-ellipsis-h',
              title: 'Insert List of Menu'
            },
            category: 'Section',
            content: `<ul class="collapsible" data-gjs-type="collapsible" data-collapsible="accordion">
              <li>
                <div class="collapsible-header"><i class="material-icons">filter_drama</i>First</div>
                <div class="collapsible-body"><span>Lorem ipsum dolor sit amet.</span></div>
              </li>
              <li>
                <div class="collapsible-header"><i class="material-icons">place</i>Second</div>
                <div class="collapsible-body"><span>Lorem ipsum dolor sit amet.</span></div>
              </li>
              <li>
                <div class="collapsible-header"><i class="material-icons">whatshot</i>Third</div>
                <div class="collapsible-body"><span>Lorem ipsum dolor sit amet.</span></div>
              </li>
              <li>
                <div class="collapsible-header"><i class="material-icons">whatshot</i>Third</div>
                <div class="collapsible-body"><span>Lorem ipsum dolor sit amet.</span></div>
              </li>
            </ul>`,
          });
...
```

then how to make droppable for all component inner or outer is false and copyable only for ul and li tag?
Thank you very much :+1:

**Comment by ahmeddabak** [comment]
i hope this helps you

https://github.com/artf/grapesjs/issues/263#issuecomment-325980387

**Comment by bungambohlah** [comment]
@ahmeddabak i was try and confuse about the logic :face_with_head_bandage: 
please, can you explain that? and give me some example :smile: 
thank you for your help :+1:  :clinking_glasses:

**Comment by artf** [comment]
What does confuse you @bungambohlah ?
You can add `data-gjs-{property name}` on any HTML element you want and therefore limit where stuff could be dropped

**Comment by bungambohlah** [comment]
@artf And can i use other option like boolean true/false for example ```data-gjs-{property boolean}```

**Comment by artf** [comment]
Sorry @bungambohlah but I don't think I get where is your problem, do you have an issue with selecting the `ul` or copying it?
> Or any other option like boolean true/false for example data-gjs-{property boolean} ?

yeah, you can use boolean types, eg. `<div data-gjs-droppable="false">`

**Comment by bungambohlah** [comment]
Sorry @artf for very late reply, i have a issue with selecting the ul, no want to select the li tag, and i want to copy element per section with the ul tag selected, but when i select the element, li selected, can i disable li tag for being selected?

Thank you very much @artf  have a nice day

**Comment by artf** [comment]
Hey @bungambohlah in the latest versions there is a new toolbar button which allows you to select easily parents
![schermata 2017-10-11 alle 14 47 50](https://user-images.githubusercontent.com/11614725/31441392-5beffaca-ae93-11e7-91b8-8c0b42157710.png)

**Comment by Sibbir7350** [comment]
Hello @artf ,
I have also similar kind of issue.

Case: I open Block Manager. Then when i click on any component I open the Layer manager.
But the issue is when I open the layer manager first time it not showing the selected element.. it showing from body.. to get the selected element i need to scroll the layer manager..

But when the layer manager already open the on click it showing the selected elements..

Please refer my two screen shot.. you will get some idea.. Please help me.

![1](https://user-images.githubusercontent.com/42797395/49273135-09b81500-f49a-11e8-858d-b494fb7efed7.png)
![2](https://user-images.githubusercontent.com/42797395/49273140-0e7cc900-f49a-11e8-9dae-be01277d7c98.png)
