### ISSUE TITLE
Unable to Press Space Within Button Componet

### ISSUE THREAD

**Issue by adamwpe** [artf/grapesjs#2781]
Hi Guys,

I have a button component, it lets me edit the text, but doesn't let me type a space ' '. Though you can copy and paste one in.

I have an example here: 
https://jsfiddle.net/qz2cumo6/2/ 

Any idea why that would be?

Thanks,

**Comment by Mohsen-Khakbiz** [comment]
try adding components like this
```javascript
components: [
	{
		tagName: 'button',
		classes: ['gjs-button'],
		components: [
			{
				selectable: true,
				editable: true,
				tagName: 'span',
				type: 'text',
				content: 'edit me'
			}
		]
	}
],
```

**Comment by adamwpe** [comment]
That's a nice simple solution - worked a treat.
