### ISSUE TITLE
Are media queries broke?

### ISSUE THREAD

**Issue by joshbedo** [artf/grapesjs#2784]
I'm just trying the demo on my phone
https://grapesjs.com/demo.html

render of HTML/CSS
https://us-central1-connectionhelper-6e7ed.cloudfunctions.net/app/api/pages

and noticed that it still looks like the desktop version. When i'm in the editor and look at the mobile version it looks a bit different. Kind of confused why the editor mobile preview looks different than the actual render.

Doesn't seem like any media queries are being applied.

**Comment by montali** [comment]
I second this!

**Comment by vinceumo** [comment]
Same issue on **0.16.12**, When importing CSS with media query most css in the media query get removed, but not all?? I tried with the postcss parser as well and same issue.

**Comment by artf** [comment]
@joshbedo I can't help if you don't indicate what you've changed on the template, I don't see issues on my side (real phone and simulated in chrome)

@vinceumo same like above, I need more info (template, code, etc.) and preferably in another issue

**Comment by vinceumo** [comment]
Hi @artf I did open an issue regarding mine with a codesandbox https://github.com/artf/grapesjs/issues/2774
Thanks a lot
