### ISSUE TITLE
Using Grapes in own Webpack configuration

### ISSUE THREAD

**Issue by A----** [artf/grapesjs#279]
I have my own app that uses Webpack to package my vendors (and more).
Now I can't manage to bundle GrapesJs into it because of the `src` path resolution here:
https://github.com/artf/grapesjs/blob/dev/webpack.config.js#L41

Is there a way to do that without:
- using Grapes as an external;
- add something along the `nodes_modules/grapesjs/src` line in my `resolve` property?

**Comment by A----** [comment]
Duh!

`import * as grapesjs from 'grapesjs/dist/grapes.min.js'`

Not perfect but that should work.

**Comment by artf** [comment]
ok but, isn't the same as `import grapesjs from 'grapesjs'`?

**Comment by A----** [comment]
Nope:

```javascript
import grapesjs from 'grapesjs';
[…]
console.log(grapesjs); // undefined
```

With my webpack configuration at least.

**Comment by A----** [comment]
A drawback of using the webpacked/`dist` version is that it requires `jQuery` (not `jquery`), meaning duplicate jQuery bundling, with the `Spectrum missing` error.

I had to add capped alias to my webpack conf.

```javascript
return {
        […]
        resolve: {
            alias: {
                jQuery: "jquery/dist/jquery"
            },
        […]
};
```

Or at least, I think that's what's going on. No webpack expert here.

**Comment by A----** [comment]
@artf I did change requires to internal modules by relative paths, see if it can help.
It doesn't things change much in my case. I do not use the same transcripter. Mine keeps lambdas in exports, and it seems you can use a lambda for a constructor.

```javascript
var test = function (test) { return { "toto": "tata" }; };
new test(); //{toto: "tata"}

var toast = (test) => { return { "toto": "tata" }; };
new toast() // Uncaught TypeError: toast is not a constructor at <anonymous>:1:1
```

 I can PR it, if you want me to.

**Comment by artf** [comment]
try to check this one #273 :)

**Comment by A----** [comment]
Looks like it works!

**Comment by A----** [comment]
If you ever need those relative paths: https://github.com/A----/grapesjs/tree/relative-path-requires
