### ISSUE TITLE
[BUG] Devices not working  in Version 0.16.12

### ISSUE THREAD

**Issue by motazad** [artf/grapesjs#2790]
@artf When I click on the devices(tablet, mobile), the size of the canvas is not updated
But it Worked in Version 0.15.x and lower.

**Comment by cdespinosaagmx** [comment]
I have the same issue

**Comment by alitorki2651** [comment]
I have the same issue @artf

**Comment by motazad** [comment]
@artf 

> @artf When I click on the devices(tablet, mobile), the size of the canvas is not updated
> But it Worked in Version 0.15.x and lower.

@artf I installed it from NPM
But the editor.setDevice("Tablet") doesn't work

**Comment by artf** [comment]
ok, can someone create a reproducible demo, please? Seems to work correctly on my local copy and on the official demo

**Comment by kuhelbeher** [comment]
I had the same issue after grapejs update. In my case it turned out that I was using old version of css file: 
`https://unpkg.com/grapesjs@0.14.62/dist/css/grapes.min.css`

I updated it to use version as grapesjs and it solved my problem.
Try it out, maybe you have the same problem.
