### ISSUE TITLE
Video component error on provider update

### ISSUE THREAD

**Issue by josfh2005** [artf/grapesjs#2792]
Hi, when provider change I get the "this.model is undefined" error in updateProvider function.

This screenshot is form https://grapesjs.com/demo.html, just add the video component and change the provider.

![Screen Shot 2020-05-20 at 12 59 21](https://user-images.githubusercontent.com/938654/82474911-bd033800-9a99-11ea-9da9-433960085207.png)

**Comment by artf** [comment]
relates to this https://github.com/artf/grapesjs/issues/2773
