### ISSUE TITLE
Assset Image onclick customization

### ISSUE THREAD

**Issue by AndiswamyDev** [artf/grapesjs#2794]
## Can I customize the asset image click event, so that I can stop auto updating image source on a single click. Is there any way to say the target.set() to the default source of an image component?

    Iam customizing asset image onclicking property. What's happening by default grapesJS is onclicking  the image from an asset, the source url will be auto updating to the selected image component from the editor.
What am looking for is, Iam gonna click the asset image and it willl preventing grapesjs property. I am trying thi sby achieving via JQuery.
   I refered our Docs and API docs, couldn't get things related to asset image click and updating source in it.

Need your help ASAP guys.
@artf

**Comment by artf** [comment]
Refer to this part https://grapesjs.com/docs/modules/Assets.html#extend-asset-types
