### ISSUE TITLE
CSS get removed when project init

### ISSUE THREAD

**Issue by vinceumo** [artf/grapesjs#2796]
Hi,

I'm trying to import utility classes into grapes js. My issue is that grapes remove them if they are not use by an element in the canvas. I'm building a custom panel to link to my CSS variables (CSS custom properties) to manage this classes in grapes. 

How can I import my CSS and keep all the classes? 

I have created a small demo of my issue https://codesandbox.io/s/musing-moore-1tswh?file=/index.js

Go in index.html and you will see all the CSS. When clicking on **view code**, you will see most of the CSS have been removed.

Thanks a lot

**Comment by Ju99ernaut** [comment]
`grapesJS` does not deal with `css` directly it first parses it into a `CSSOM` and uses that in the editor so a class will not show up in the code preview unless there is a component in the editor canvas using it. Your classes will be imported dynamically as they are used in the editor canvas.

**Comment by vinceumo** [comment]
Thanks @Ju99ernaut, do you know if there is anyway to add some css and make it available in the canvas and as well have it in the export?

**Comment by Ju99ernaut** [comment]
You could load the stylesheet externally during init and remove it from the index.html altogether
```js
canvas:{
   styles: [
      'path/to/stylesheet'
   ]
}
```
You can also check the [SelectorManager](https://grapesjs.com/docs/api/selector_manager.html) and [CssComposer](https://grapesjs.com/docs/api/css_composer.html#csscomposer) api reference

**Comment by artf** [comment]
> How can I import my CSS and keep all the classes?
`config.clearStyles` is for removing CSS rules completely from the collection, if you do `editor.Css.getAll()` you'll see are still there. The export doesn't print the rules if there is no match with components and, at the moment, we don't plan an option to avoid that

The solution proposed by @Ju99ernaut is the best one to deal with external styles, but that path is not included in the export code so it's up to you to include it in you final product (eg. the page which renders the designed content)
