### ISSUE TITLE
Parent reference in block:drag

### ISSUE THREAD

**Issue by niklasdahlback** [artf/grapesjs#2798]
I wonder if it is possible to get the parent and/or index during block:drag event for the resulting component, similar to the parent attribute in the component:drag event? It seems like the event argument passed does not contain any reference to parent. 
The reason I am asking is that I am working on a solution to preview the presumed drop result of a dragged block, using a box rather than the green line indicating the drop position.

**Comment by artf** [comment]
`block:drag` can't contain the reference to the component as it's not yet created before being dropped
