### ISSUE TITLE
[Questions] Ordering of selector with id and class selectors, space after id-selector

### ISSUE THREAD

**Issue by dintifla** [artf/grapesjs#2799]
I am currently working on a web application for which we integrate this project as GUI editor to customize the environments.

Our GUI components are loaded and parsed from the database. We can identify e.g. a button, data grid, etc. by an ID (e.g. `_17190fbd-13d6-430f-bb32-1a09d2151a77`). These components are then built from several nested HTML elements by a framework, which adds classes for styling.

My goal is now to access these inner elements from GrapesJS with something like `#ancestor-id .framework-class1.framework-class2` (e.g. `#_17190fbd-13d6-430f-bb32-1a09d2151a77 .my-text-label`)

I add the id-selectors to each nested element after the canvas is loaded:

`allComponents.forEach((component: any) => {`
`        const ancestorId = this.getAncestorId(component);`
`        const idSelector = selectorManager.add('#${ ancestorId }');`
`        const selectors = component.getSelectors();`
`        selectors.add(idSelector);`
`    });`

My problem is now that the class selectors are listed before my Ancestor-id selector.
This results in a full selector like `.my-text-label#_17190fbd-13d6-430f-bb32-1a09d2151a77 ` instead of  `#_17190fbd-13d6-430f-bb32-1a09d2151a77 .my-text-label` with the space between the id and classes.

Does anyone have an idea where or how I could change this behavior?

Thank you very much for your support.

**Comment by dintifla** [comment]
a short update:

I managed to get the the selectors in the right order when using `selectors.unshift(idSelector)` instead of `selectors.add(idSelector)` in above sample.

Now i still have the issue with the missing space between the id- and the class-selectors.

Until now I could not find a way to get into `Selectors.getFullString(..)` to change the behavior

**Comment by artf** [comment]
Hi @dintifla SelectorManager is not meant to work like that (you can only have a mix of classes `.class1.class2` but not with IDs), but honestly I don't understand what is your goal of using the SelectorManager at all. 
If you need to query a component the editor you can just do this `anyParentComponent.find('#my-id .my-class')[0]`

**Comment by dintifla** [comment]
Hi @artf Thanks for your reply. In the end it is not just about querying a component, but generate the CSS for it. I don't need the HTML since my application is designed in a rich client application, stored in an abstract representation into the database and then parsed into a DOM. As a result, I can't use the IDs generated by GrapesJS, since I have no chance to store back HTML (or any other representation of the DOM).

In the end, i expect all my rules to look like this: `#top-level-component-id .my-class { ...}`

maybe as a simple example, the generated HTML of a button:

```html
<div id="_4b9c8f66-85d3-4488-8e23-5932bc3e8420"
    class="dx-button dx-button-normal dx-widget dx-button-has-text dx-button-mode-contained" role="button"
    aria-label="x" tabindex="0">
    <div class="dx-button-content"><span class="dx-button-text">Close</span></div>
</div>
```
to change the label of that specific button my CSS would look like this:
`#_4b9c8f66-85d3-4488-8e23-5932bc3e8420 .dx-button-text {...}`

**Comment by artf** [comment]
> As a result, I can't use the IDs generated by GrapesJS, since I have no chance to store back HTML (or any other representation of the DOM).

Sorry Flavio, but I really don't understand what is your issue... Why can't you use IDs generated by GrapesJS? And why you need this format `#_4b9c8f66-85d3-4488-8e23-5932bc3e8420 .dx-button-text`? 
If you use `config.selectorManager.componentFirst` option, on update in Style Manager the editor will apply styles on the single component https://github.com/artf/grapesjs/pull/2474

You said that you don't need the HTML/CSS, so I guess you're storing JSON template, in that case there should be no issue in loading back all the styles.

IDK maybe I'm missing something. If you're able to create tiny demo of your case it might help a lot

**Comment by dintifla** [comment]
Hi Artur,
Our web application is a database application with forms, buttons, etc. These forms are designed (in another application) comparable to a diagram designer (e.g. draw.io). This means the web application is not responsible for the structure of the forms. It is parsed into a DOM from a propriety format stored in the database, not from the HTML of GrapesJS. We use for most things devExtreme to build the HTML components from our representation. This library also adds kind of default styling.
We use GrapesJS only to add additional CSS in order to let our customers adjust the style to their needs.
The ID generated by GrapesJS is useless for us, because we can't store it and when the form is parsed next time, we don't have the id anymore. Therefore we would like to with our id of the main components, which has this strange format.

In below image you see, such a sample form. You can see, that I e.g. adjusted color and font of the title.
They propriety format just says like "I have two tables with this data, these buttons, etc." Our application then build the form from this information.

![image](https://user-images.githubusercontent.com/45663292/85234339-fae2db80-b40c-11ea-8e41-0b3d6c1ef3b6.png)

As a workaround I recursively added a class with this id as value to each child-element so that I can identify the elements. But I would really prefer to access the child-elements with `ancestor-id .class` as described above.

Hope this clarifies things a bit:) I expect we intend to use GrapesJS in a quite different way than others..

**Comment by artf** [comment]
> Hope this clarifies things a bit:) I expect we intend to use GrapesJS in a quite different way than others..

Yeah, more or less, but probably a tiny demo which shows what you store and how you process the result would be more helpful to understand better your case. 
Unfortunately, being such a particular case I don't think I'm able to provide more support, but try to look if [`setRule`](https://grapesjs.com/docs/api/css_composer.html#setrule) from CssComposer might be helpful in your case.

**Comment by chaegumi** [comment]
hi @artf ,css.remove cssRule,sometimes success sometimes do not work well

https://codesandbox.io/embed/great-matan-s83hmj?fontsize=14&hidenavigation=1&theme=dark

![image](https://user-images.githubusercontent.com/9654650/216911193-e5be5caf-3442-4cee-a799-fe93843e1460.png)
sometimes can not remove
