### ISSUE TITLE
Image removal from AssetManager fired twice

### ISSUE THREAD

**Issue by g41n** [artf/grapesjs#280]
I assign a listener on AssetManager removal in this way
```javascript
var assets = editor.AssetManager.getAll() // <- Backbone collection
assets.on('remove', function(asset) {
  console.log(asset.get('src'));
})
```
as suggested in #86 

It worked like a charm for me with 0.9.8 version.
Now I've upgraded to 0.9.32 and results in firing the function twice...
That's a problem for me: the second time my app raise an error because the image was deleted the first time.

Any hint about that?

Thanks in advance for the support.

**Comment by artf** [comment]
Hi @g41n honestly, I've done some refactoring work on Assets so some bug might appear, but testing your snippet in the [demo](http://grapesjs.com/demo.html) (`editor` var is exposed to window globally so you can play with APIs) I can't reproduce it.
By the way, in the last release, I've introduced new "official" events for Assets

 * `asset:add` - New asset added
 * `asset:remove` - Asset removed
 * `asset:upload:start` - Before the upload is started
 * `asset:upload:end` - After the upload is ended
 * `asset:upload:error` - On any error in upload, passes the error as an argument
 * `asset:upload:response` - On upload response, passes the result as an argument

Let me know

**Comment by g41n** [comment]
Hi,
I've tried to implement it in this manner
```javascript
this.templateEditor = grapesjs.init({
    container : '#HtmlTemplateEditorGjs:not(.gjs-editor-cont)',
    storageManager: {
        type: 'none'
    },
    plugins: ['gjs-preset-newsletter'],
    assetManager: {
        upload: '/asset'
    }
});

this.templateEditor.on('asset:remove', (asset) => {
    var filename = asset.get('src').split('/').reverse()[0];
    this.http.DELETE(`/assets/${filename}`, (response) => {
        console.log('asset remove', response);
    });
});
```
but seems that the second time I open the AssetManager the upload is not fired anymore...

Any hint on how to initialize and reuse it in a complex application?


Thanks for the support.

**Comment by artf** [comment]
>  Every time I run that code I have a new item in grapesjs.editors array and that seems not so good to me.

Why do you care about `grapesjs.editors`? It just contains the initialized editor, nothing more.

Your configuration seems good, so can you explain more about the issue with the uploader, because I'm not able to reproduce it. The ajax is not firing?!? you're not able to select files?!?

**Comment by g41n** [comment]
With version 0.12.8 my [previous implementation](https://github.com/artf/grapesjs/issues/280#issuecomment-328545451) seems working.
Thanks for the support :D
