### ISSUE TITLE
[Bug] when removing a tooltip its css is not removed

### ISSUE THREAD

**Issue by meyerco** [artf/grapesjs#2800]
## Description
- The bug is reproduced on the current demo 

## Expected behavior 
- When a tooltip is removed its css is removed 

## What happens instead ? 
- When a tooltip is removed its css is not removed 

## Steps to reproduce on the demo 
- Clear the canvas 
- Drag a tooltip 
- Remove the tooltip
- Click on Import button on top toolbar , the tooltip css is not removed .

![image](https://user-images.githubusercontent.com/65889198/82789579-32448380-9e73-11ea-8269-20a4c0a54788.png)

## The conclusions of my research
Trying to understand this bug i notified that the **style-signature** feature is not working properly .

My supposition is that the bug occurs inside the [**run**](https://github.com/artf/grapesjs/blob/dev/src/commands/view/ComponentStyleClear.js#L11) method of the command **core:component-style-clear** .

On [Components model](https://github.com/artf/grapesjs/blob/dev/src/dom_components/model/Components.js#L47) the  **core:component-style-clear** command run before the component is removed .
So when the **core:component-style-clear** command check if an element of a specific type exists yet on the canvas the response is true . Then [this condition](https://github.com/artf/grapesjs/blob/dev/src/commands/view/ComponentStyleClear.js#L11) is false and the css is not removed .

**Comment by artf** [comment]
Yeah, I think you're right, probably replacing 
```js
// relies on the view
const len = dc.getWrapper().find(`[data-gjs-type="${type}"]`).length;
``` 
with 
```js
// relies on the model
const len = dc.getWrapper().findType('tooltip').length;
``` 
might fix the issue, would you like to check and create a PR? :)

**Comment by meyerco** [comment]
Maybe this code to keep the code generic :
```js
// relies on the model
const len = dc.getWrapper().findType(type).length;
```

**Comment by artf** [comment]
@meyerco 😅 yeah sure, sorry it was a copy-paste from my try
