### ISSUE TITLE
[QUESTION] "Changes you made may not be saved." alert popup is displayed

### ISSUE THREAD

**Issue by EgorPashko** [artf/grapesjs#2805]
Hey guys

I have some problem related to alert which displayed when I tried log out of page.
Actually I do not know bug is it or something else. 
I have read documentation, but did not get answer yet. If you help me I will gratefully to you.

Alert message is "Changes you made may not be saved."

**Comment by Ju99ernaut** [comment]
It's probably because you have no `storage` set up

**Comment by Ju99ernaut** [comment]
I guess the alert still shows up even if you have storage set up. Add this to your initialization:
```js
var editor = grapesjs.init({
   //...
   // Show an alert before unload the page with unsaved changes
   noticeOnUnload: 0,
   //...
})
```
By default it's set to true

**Comment by pjdevries** [comment]
I thought about `storage` as well and was about to set up a dummy storage, hoping it would circumvent the problem. The `noticeOnUnload: 0` works like a charm though, so no need for that.

Thank you very much.
