### ISSUE TITLE
[Question] Modal destroy contents on close

### ISSUE THREAD

**Issue by antman3351** [artf/grapesjs#2809]
Hello, 

I'm using the modal with some commands. I've noticed when calling `modal.setContent( ... )` what ever was in the modal before is moved to a hidden div with class `gjs-mdl-collector` .

Is there a way to destroy the content on close? Or should I just remove the content `.innerHTML('')` before closing?

Thanks,
Antonio

**Comment by artf** [comment]
If you don't need those references you can clean them manually
