### ISSUE TITLE
[QUESTION]: Possible to make it for non-devs?

### ISSUE THREAD

**Issue by BerkeAras** [artf/grapesjs#2810]
Hello!

Is it possible to make a version for non-developers or people who don't know css basics. I am programming a CMS and most users don't know what position: absolute is, they just want to drag and drop element to a place, where they want.

**Comment by Ju99ernaut** [comment]
`grapesjs` already supports moving components freely, check issue #1936

**Comment by BerkeAras** [comment]
Thanks 👍
