### ISSUE TITLE
[BUG]: Failed to execute 'appendChild' on 'Node'

### ISSUE THREAD

**Issue by BerkeAras** [artf/grapesjs#2811]
Hello. I am getting this error in the console:
Uncaught TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.

What could this be?

**Comment by RJCAM** [comment]
You need to be more specific in what your trying to do and how are you getting this error.

**Comment by BerkeAras** [comment]
I don't do anything. If I just place GrapesJS on my page, this happens.

**Comment by RJCAM** [comment]
You mean when you just initialize GrapesJS? If so, here is the basic code to work, you can compare this with yours and see what you have different.

```
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>GrapesJS</title>
    <link href="https://unpkg.com/grapesjs/dist/css/grapes.min.css" rel="stylesheet">
    <script src="https://unpkg.com/grapesjs"></script>
    <style>
        body,
        html {
            height: 100%;
            margin: 0;
        }
    </style>
</head>

<body>

    <div id="gjs" style="height:0px; overflow:hidden"></div>

    <script type="text/javascript">
        var editor = grapesjs.init({
            height: '100%',
            noticeOnUnload: 0,
            storageManager: {
                autoload: 0
            },
            container: '#gjs',
            fromElement: true,
            plugins: [],
            pluginsOpts: {}
        });
    </script>
</body>

</html>
```

**Comment by BerkeAras** [comment]
There is nearly no difference, but I still get the error

**Comment by artf** [comment]
@BerkeAras follow the issue template please, it's impossible for us to understand your issue with that kind of information.
We need to see the code, the version you're using, the stack of the error, etc.

**Comment by BerkeAras** [comment]
@artf I'm sorry, for my issue. The bug is fixed. The problem was because I tried to remove the settings pane, but there was a typography mistake.
