### ISSUE TITLE
[BUG]: Cannot place button

### ISSUE THREAD

**Issue by BerkeAras** [artf/grapesjs#2812]
Hello. In the latest version it is not possible to drag and drop a button. It gives this error:
``Invalid target position: Target collection not found, Target is not droppable, accepts [undefined], Component not draggable, acceptable by [undefined]``

**Comment by RJCAM** [comment]
@BerkeAras the default button inside the Form category **is only droppable inside a form block** (the first block inside Form category). All those blocks are allowed to be dropped inside a form only. If you want a button to be dropped inside any other component you can create a custom one.
You can see how to do it here: [https://grapesjs.com/docs/api/block_manager.html#add](url)

**Comment by BerkeAras** [comment]
Thank you!
