### ISSUE TITLE
Blocks attributes

### ISSUE THREAD

**Issue by KaytotheH** [artf/grapesjs#2813]
``
const blocktext = blockManager.get('text').set({
                label: 'Modified text',
                attributes: {
                }
            })
``
I want to add an attribute to the original text block, I want the attribute to give the user the option of giving the component, time to appear and disappear at another time.
My question is, what are the attributes that I can make use of? and does it work if I refer in the attribute to a javascript that allows him to do this function?

**Comment by artf** [comment]
You can do this `editor.Blocks.get('text').set({ attributes: { class: 'my-custom-class' } })`
