### ISSUE TITLE
I want to just preview the page that is build/make by grapseJS 

### ISSUE THREAD

**Issue by rathodrupesha** [artf/grapesjs#2817]
Hello Sir,

We have used grapesJS for page builder. We have created a page by grapesJS & store on a remote server. Now we want to just show/preview that page in our angular.
Kindly give us solution for How to display Readonly grapes js preview in Angular 8?

**Comment by artf** [comment]
Just render the HTML/CSS you store on your remote server

**Comment by wojiaoxiaomayun** [comment]
hi，I want to dynamically display projectData in the preview interface, just for previewing, without any other functions, including right-clicking and dragging, etc. It's not required, nor is it HTML/CSS
