### ISSUE TITLE
[Question] I am updating trait using addTrait function? It updates and adds the trait in trait manager but unable to reflect it in html section of codeManager?

### ISSUE THREAD

**Issue by akashdesale98** [artf/grapesjs#2819]
I have written the following code - 

const component = editor.getSelected();
 component.addTrait({
        name: 'traitName',
        type: 'text', label: 'traitLabel', value: 'traitValue'
      });
      const traits = component.get('traits');
      traits.forEach(trait => console.log(trait.props()))

**Comment by artf** [comment]
Traits change the component (and its final HTML) when you use them. By simply updating traits collection in the component doesn't make any change to it on the HTML side
