### ISSUE TITLE
Dynamically attach CDN(external resources) to canvas head #grapesjs #attach #cdn #external #resources

### ISSUE THREAD

**Issue by Rubark** [artf/grapesjs#2820]
Dear artf 

I'm trying to add feature to my application, for end user. It's a tool for - Dynamically adding CSS and JS CDN-s. Like in jsFiddle or Codepen, when we add external resources(css/js) CDN-s. That means, that after adding a link for js, or css, it will appear in Canvas iFrames head. Unfortunately I couldn't find any way to do that.
1. I can't use 
                canvas: {
                    scripts: ['......'],
                },
because the end user will be able to add CDN in process of making his tamplate
2. I can't append to canvas head, because it's simply won't save it. 

So, what to do? Any solutions? Any packages? 

@artf

**Comment by artf** [comment]
You if need to save dynamic css/js inside the template you have to append them to the body (eg. `editor.addComponents('<script src="...">..')`) if you need them outside the template (which manages ONLY the body), like in the <head>, you can append even manually to the canvas but it's up to you storing/loading them to the user
