### ISSUE TITLE
Custom Select list to text component?

### ISSUE THREAD

**Issue by tonypartridge** [artf/grapesjs#2826]
Hey Guys.

I've seen this before but now I cannot find it for the life of me. Basically on the text component we have the top bar:
https://gyazo.com/754513edcebbb0566f18e384d3eba453

How can we insert a select list here for example:

Name
Email
Phone

which inserts: {{NAME}} {{EMAIL}} {{PHONE}}

It's a short code selector basically?

**Comment by RJCAM** [comment]
Hi @tonypartridge here is an example code to achieve that
```
// An example with fontSize
rte.add('fontSize', {
  icon: `<select class="gjs-field">
        <option>1</option>
        <option>4</option>
        <option>7</option>
      </select>`,
    // Bind the 'result' on 'change' listener
  event: 'change',
  result: (rte, action) => rte.exec('fontSize', action.btn.firstChild.value),
  // Callback on any input change (mousedown, keydown, etc..)
  update: (rte, action) => {
    const value = rte.doc.queryCommandValue(action.name);
    if (value != 'false') { // value is a string
      action.btn.firstChild.value = value;
    }
   }
  })
```

You can see in the documentation for more details:
[https://grapesjs.com/docs/api/rich_text_editor.html#add](url)

**Comment by artf** [comment]
@tonypartridge probably you're referring to this https://github.com/artf/grapesjs/issues/481#issuecomment-342282125
