### ISSUE TITLE
"Checked" trait does not get updated

### ISSUE THREAD

**Issue by gpmonch** [artf/grapesjs#2829]
When updating a component of type checkbox which has the "checked" trait via html import, it does not update the trait input, i.e: in the grapes.js demo, import html option, add a checked="checked" attribute to the "Male" checkbox in the demo form, the result is that the checkbox on the form is checked, but it's "checked" trait is not.

**Comment by artf** [comment]
Thanks @gpmonch for the report but it's just an issue with the webpage preset which uses an old version of forms plugin.
Here you can see a working example https://jsfiddle.net/bp5e9zkc/

**Comment by gpmonch** [comment]
Thanks for the quick reply!
