### ISSUE TITLE
Using Google Chart as Block with Component

### ISSUE THREAD

**Issue by suchithmahadi** [artf/grapesjs#283]
Artur Arseniev
Need help in creating a custom block for Google Chart. Need your help to solve.

**Comment by artf** [comment]
ok... read this [Components-&-JS](https://github.com/artf/grapesjs/wiki/Components-&-JS) and then let me know what is not working

**Comment by suchithmahadi** [comment]
Thanks Artur Arseniev
Going through  Components-&-JS will update you once i finish the Google Chart Block.
Appreciate your patience to listen for me.

**Comment by suchithmahadi** [comment]
@artf I have integrated google charts but unable to use configuration options (https://developers.google.com/chart/interactive/docs/gallery/gauge) as Traits here. Please help.

**Comment by suchithmahadi** [comment]
@artf Please help me out.

**Comment by artf** [comment]
@suchithmahadi take this as example for binding Traits with js variables/configs
https://github.com/artf/grapesjs-component-countdown/blob/master/src/components.js

**Comment by ionic666** [comment]
@suchithmahadi ,hi ,have you achieved this yet？I'm looking forward to your advice about using configuration options
