### ISSUE TITLE
[QUESTIONS]: Creating Responsive Websites

### ISSUE THREAD

**Issue by BerkeAras** [artf/grapesjs#2830]
Hello,

is it possible to create responsive websites? For example: A text should be smaller on mobile devices and bigger on desktop. How can I do that?

**Comment by artf** [comment]
Yes, you have to change the device

![Schermata 2020-06-17 alle 01 42 22](https://user-images.githubusercontent.com/11614725/84838850-cf8e7400-b03b-11ea-8549-a661bd13257b.png)

**Comment by BerkeAras** [comment]
But it does not make the website responsive. I mean, isn't it possible to just make text 15px for example on mobile and 20px on desktop?

**Comment by artf** [comment]
When you edit in a different view those changes are saved only for that current device

**Comment by BerkeAras** [comment]
Thanks!
