### ISSUE TITLE
Replace/Override template for CategoryView?

### ISSUE THREAD

**Issue by mbaird4** [artf/grapesjs#2832]
Hi,

Wondering if it's at all possible to use custom HTML to replace the CategoryView's template when adding a new block?

I've tried a couple things, but just based on the source code, I'm not seeing a way.

```
editor.BlockManager.add(name, {
            category: {
                view: {
                    template: '<div><h1>Layout</h1></div>',
                    render() {
                        this.$el.html(this.template);
                        return this;
                    }
                }
            },
            ...
        });
```

**Comment by artf** [comment]
No, unfortunately, it's not possible but you can always create your own blocks container and using HTML5 D&D to drop stuff

Here you can find an example https://github.com/artf/grapesjs/issues/2595#issuecomment-593699277
