### ISSUE TITLE
[Questions]: How to add a toolbar to a component?

### ISSUE THREAD

**Issue by jpdigital** [artf/grapesjs#2833]
Hello,

I would like to extend the table component with a toolbar for adding and removing columns and rows. As far as I understood the documentation and the code the function `onActive` should be triggered when a component is selected. Or did I misunderstood this function? Because when I try to extend the view of the `table` component like this 

```
editor.DomComponents.addType("table", {
    view: {
         onActive() {
           ...
        },
        onDisable() {
             ...
        }
    }
}
```

the functions are no executed.

Best, Jens

**Comment by artf** [comment]
Check here https://github.com/artf/grapesjs/issues/266
