### ISSUE TITLE
[BUG] Grapesjs doesn't initialize styles for wrapper

### ISSUE THREAD

**Issue by kuhelbeher** [artf/grapesjs#2834]
Hello, I've met a bug where grapesjs doesn't initialize styles for wrapper. Steps to reproduce:
1. Go to https://grapesjs.com/demo.html 
2. Select wrapper and set background. It will add "body" rule to styles and it will be displayed in style settings
3. Refresh the page - "body" rule still present (you can check it in "View Code" modal) but it didn't applied to the wrapper
![simplescreenrecorder-2020-06-16_15 23 25](https://user-images.githubusercontent.com/37115006/84775520-00dd5480-afe8-11ea-97ad-9a7613608ba1.gif)

Also it is causes in my project similar problem to this - https://github.com/artf/grapesjs/issues/2231

**Comment by michaelhofer** [comment]
@kuhelbeher Did you ever manage to find a solution for this issue? I am currently facing the same problem.

**Comment by jlpatrick** [comment]
We have run into the same issue on our project.
I believe this is the same issue but another variation:

1. Go to https://grapesjs.com/demo.html
2. Select Body/wrapper and set a class name - the class will be added to the wrapper div
3. Refresh the page - a new wrapper div with a different id is now in place and the class setting is gone

**Comment by michaelhofer** [comment]
@jlpatrick That looks indeed similar to the issue I was facing. I have found a hacky workaround in the meantime, but I wonder if there is a better way to do that.

There are options to define whether the wrapper should be stored or not, as well as on option for protected classes. However, none of the settings mentioned around here did help in my project, I always ended up having a multiple `body` rules in the generated CSS.

At the moment, I initialize the editor as follows:

```
// 1. Set CSS Style
editor.setStyle(myCSS);

// 2. Set the wrapper style if it has been saved before
var wrapper = editor.DomComponents.getWrapper();    
var style = editor.CssComposer.getRule("body");      
if (style !== null)
{
    wrapper.set('style', style.config.style);
}

// 3. Remove the existing body rule
const regex = /body{(.*?)}/mgs;
css = editor.getCss().replace(regex, '');
editor.setStyle(css);
editor.refresh();
``` 

As you can see, it's quite hacky, but I haven't found a better solution so far.

**Comment by jlpatrick** [comment]
@michaelhofer Thanks for the tip. I have managed to put a workaround into our code as well for now.

**Comment by michaelhofer** [comment]
Does anybody else still have this issue? I have updated to the latest version in the meantime, but this broke the workaround I mentioned above.

How can we load the `body` call from the CSS and apply this style to the wrapper?

**Comment by michaelhofer** [comment]
I still have the same issue. I had a workaround for a while, but unfortunately it does not work reliably...

**Comment by artf** [comment]
This one is planned to be fixed with this PR https://github.com/artf/grapesjs/pull/4223

**Comment by bryanjamesmiller** [comment]
This seems to fix the issue:
`const wrapper = editor.getWrapper();
 wrapper.set('attributes', { id: 'grapes-iframe-body' });`
 
 Any reason not to do this @artf ?

**Comment by artf** [comment]
With the actual Storage Manager refactor release (https://github.com/artf/grapesjs/releases/tag/v0.19.4) this seems to be fixed (at least the demo works properly now), so this can be closed.

**Comment by Jowcey** [comment]
Hey, this issue is still persisting.
The Classes and CSS added to the body layer (wrapper) get wiped every time it's restarted.
It seems to be that the ID get's randomised and that's why the CSS breaks, but unsure why the class gets cleared.

**Comment by JoanCodinachUoc** [comment]
Any update? I have the same problem
