### ISSUE TITLE
Style sections are duplicated

### ISSUE THREAD

**Issue by levansuper** [artf/grapesjs#2838]
Hello Guys 

I'm using:
    "grapesjs": "0.16.12",
    "grapesjs-preset-webpage": "0.1.11",

and in the css edit area i get this strange behavior:
<img width="1527" alt="Screen Shot 2020-06-19 at 00 39 13" src="https://user-images.githubusercontent.com/223112/85069933-01cbdd00-b1c6-11ea-909b-7b77a048eefe.png">
a lot of the sections are duplicated!

this is the  repository with my code:
https://github.com/levansuper/grapes

**Comment by artf** [comment]
Hi Levan, please try to follow the template from the preset page https://github.com/artf/grapesjs/blob/gh-pages/demo.html

**Comment by levansuper** [comment]
@artf in my case the problem was that i was loading the module using node not directly in html. In the end I found and answer:
```
            plugins: [gjsPresetWebpage],
            pluginsOpts: {
                [gjsPresetWebpage]: {
                    customStyleManager: [{
                        name: 'General2',
                        open: false,
                        buildProps: ['float', 'display', 'position', 'top', 'right', 'left', 'bottom']
                    }]
                }
            },
```

**Comment by etamity** [comment]
> @artf in my case the problem was that i was loading the module using node not directly in html. In the end I found and answer:
> 
> ```
> import gjsPresetWebpage from "grapesjs-preset-webpage";
> bla, bla, bla...
> GrapesJS.init({
> ...
> plugins: [gjsPresetWebpage],
> pluginsOpts: {
>     [gjsPresetWebpage]: {
>         customStyleManager: [{
>             name: 'General2',
>             open: false,
>             buildProps: ['float', 'display', 'position', 'top', 'right', 'left', 'bottom']
>         }]
>     }
> })
> ```

I found out if you pass `styleManager: { clearProperties: 1 }` to GrapesJS also will resovle the problem
