### ISSUE TITLE
How to get HTML & CSS style tag?

### ISSUE THREAD

**Issue by pirmax** [artf/grapesjs#284]
How to get HTML & CSS style tag as:

`<div style="font-weight: bold;">text</div>`

Instead of HTML on one side, and CSS on the other...

**Comment by artf** [comment]
Hi @pirmax by default GrapesJS do not inline styles but you might want to check how I made it in the newsletter preset
https://github.com/artf/grapesjs-preset-newsletter/blob/master/src/openExportCommand.js
