### ISSUE TITLE
[Bug]: Cannot use 'delete key' on keyboard when editing text.

### ISSUE THREAD

**Issue by BerkeAras** [artf/grapesjs#2841]
Hello. I have a problem, that I can edit text, but I cant use the delete key on keyboard.

Here is my code:
[https://pastebin.berkearas.de/?e1c4c8db9a70894f#DCUHVHZzyhFTnAk2RoJ9faQxQPvAqWMoiBqXHMEzRH5G](https://pastebin.berkearas.de/?e1c4c8db9a70894f#DCUHVHZzyhFTnAk2RoJ9faQxQPvAqWMoiBqXHMEzRH5G)

**Comment by aakos** [comment]
I have the same problem.
Version: 0.15.8

Tracked it down to keymaster blocking. Running this would let edited text backspace delete:
`editor.Keymaps.keymaster.unbind('backspace'));`

**Comment by BerkeAras** [comment]
@aakos Thank you. ``editor.Keymaps.keymaster.unbind('backspace');editor.Keymaps.keymaster.unbind('delete');`` works.
But there should be a fix for that problem.

**Comment by artf** [comment]
Thanks for the report, I'll push a new release with the fix
