### ISSUE TITLE
[Bug]: Text shadow disappears on doubleclick

### ISSUE THREAD

**Issue by BerkeAras** [artf/grapesjs#2842]
Hello. I have a problem, that the text shadow on text element disappears when I doubleclick the element. What should I do?

Here is my code:
https://pastebin.berkearas.de/?e1c4c8db9a70894f#DCUHVHZzyhFTnAk2RoJ9faQxQPvAqWMoiBqXHMEzRH5G

**Comment by BerkeAras** [comment]
Edit: The Text Shadow does not disappear. The shadow color is set to the shadow blur, and shadow blur gets 0.

**Comment by BerkeAras** [comment]
![image](https://user-images.githubusercontent.com/36629890/85132497-3331c080-b239-11ea-97f4-c56a748ae3c1.png)

**Comment by artf** [comment]
I can't reproduce it on the main [demo](https://grapesjs.com/demo.html) so I'd need also a live demo of your case

**Comment by BerkeAras** [comment]
Can just upload video and code: [https://pastebin.berkearas.de/?e1c4c8db9a70894f#DCUHVHZzyhFTnAk2RoJ9faQxQPvAqWMoiBqXHMEzRH5G](https://pastebin.berkearas.de/?e1c4c8db9a70894f#DCUHVHZzyhFTnAk2RoJ9faQxQPvAqWMoiBqXHMEzRH5G)

Video: [https://youtu.be/_aeHzmoQo5U](https://youtu.be/_aeHzmoQo5U)

**Comment by artf** [comment]
sorry, I can't help without a reproducible demo (in your code, you don't even use the StorageManager so it's not complete)...
