### ISSUE TITLE
[BUG] Can't remove style property on selected device

### ISSUE THREAD

**Issue by abozhinov** [artf/grapesjs#2843]
Hi,
have a problem with removing style property on selected device (clearProperties: true).
You can reproduce the problem on https://grapesjs.com/demo.html.

Steps:
1. Clean everything.
2. Drag custom code.
3. Add this sample code.
```html
<div id="test">
  Test content
</div>
<style>
  #test {
  	color: red;
  }
  @media (max-width: 767px) {
    #test {
    	color: green;
    }
  }
  @media (max-width: 991px) {
    #test {
    	color: green;
    }
  }
</style>
```
4. Switch devices to tablet or mobile and select the component.
5. In the Typography style you can see that the COLOR property is YELLOW and there is NO clean icon.

I have X icon only on desktop device but on mobile or tablet is just yellow label.

**Comment by abozhinov** [comment]
@artf  do you have idea how can i fix it?

**Comment by artf** [comment]
To make the StyleManager read the proper style rule your media query should reflect the same width of the selected Device. Did you try it?

**Comment by abozhinov** [comment]
Yes I do it.
deviceManager: {
        devices: [
        {
            name: 'Desktop',
            width: '',
            priority: 3
        }, {
            name: 'Tablet',
            width: '768px',
            widthMedia: '991px',
            priority: 2
        }, {
            name: 'Mobile',
            width: '360px',
            height: '640px',
            widthMedia: '767px',
            priority: 1
        }]
    },
