### ISSUE TITLE
[BUG] If we give "<input data-gjs-type="myInput" type="text" required/>" this html string to setComponents, it sets it like "<input data-gjs-type="myInput" type="text" required=""/>" in code manager 

### ISSUE THREAD

**Issue by akashdesale98** [artf/grapesjs#2844]
editor.setComponents("html stiring"), method which takes html string as an input and sets that code in the html section in the Code Manager

if we pass ,<input data-gjs-type="myInput" type="text" **required**/>" to editor.setComponents,

then its output will be "<input data-gjs-type="myInput" type="text" **required=""**/>

If you see setComponents is adding extra strings to required tag , it happens with every single attribute like autofocus, disabled and all othe single boolean tags?

is there any way to avoid this?

**Comment by artf** [comment]
For now, you can avoid it only by adding the Component Definition in this way
```js
editor.addComponents({ 
    tagName: 'input',
    attributes: { type: 'text', required: true }
})
```
but I'll update the HTML parser in the next release to handle this properly
