### ISSUE TITLE
[Feature]: Drag-and-Drop Images

### ISSUE THREAD

**Issue by BerkeAras** [artf/grapesjs#2845]
Hello,

what about a drag-and-drop for images into image-elements? Like this:

![](https://docs.adobe.com/content/dam/help/experience-manager-65.de-DE/help/release-notes/assets/connected-assets-drag-and-drop-only.gif)

**Comment by micker** [comment]
interesting !

**Comment by artf** [comment]
I think you can accomplish that by extending the default image component. As the user is already able to drop images in the canvas by using the HTML5 D&D I would skip such a feature from the core component.

**Comment by revdfdev** [comment]
Is there any example to extend an image component
