### ISSUE TITLE
[BUG] Using image url for background-image is not working properly

### ISSUE THREAD

**Issue by meyerco** [artf/grapesjs#2849]
## Description
- On our project for images assets we use url instead of base64 code .

## Expected behavior 
- When setting a background-image to a control , it has to update the css of this control .
- The css have to be reflected on the canvas and the style panel .

## What happens instead ? 
- If the image have spaces or parentheses on its name , when setting it as background-image it is not reflected anywhere , not on the canvas and not on the style-panel .

## The conclusions of my research
Trying to understand this bug i notified that if the image have spaces or parentheses on its name , it breaks background-image value . 

For example if the image is named "my image.jpg":
The css will break on the space as bellow :
```css
background-image : url(http://localhost:3000/images/my image.jpg)
```

I think that the solution is simply to add quotes around url or base64 code , it will not break the current functionality  ,

**Comment by artf** [comment]
Thanks for the report, I'd appreciate a PR for this issue

**Comment by meyerco** [comment]
Can you direct me to a file , where **background-image** is set ?

**Comment by artf** [comment]
https://github.com/artf/grapesjs/blob/dev/src/style_manager/view/PropertyFileView.js

**Comment by meyerco** [comment]
Hi @artf ,
#2975 Here is a PR to fix the issue .
Please update me if its good enough .

Thanks
