### ISSUE TITLE
[QUESTION]: Can't enable 2 panel buttons at the same time

### ISSUE THREAD

**Issue by RJCAM** [artf/grapesjs#2852]
Hi, I'm trying to enable more than one custom panel button at the same time. I think when I create some custom panel button (using code below) they will have the same behavior as normal html radio inputs, meaning that you can only select one and not more then that. See the example below when I try to enable both buttons but one disables the other:
![panel-button](https://user-images.githubusercontent.com/49693237/85432504-33e49280-b56a-11ea-9ce1-c88d94cd2259.gif)
I want to enable both buttons at the same time, is there any property that I can add to do so?
Here is how I create the panel buttons.

```
cmdm.add('example_cmd1', {
    run: function(editor) {
        alert("Button 1 enabled");
    },
    stop: function(editor) {
        alert("Button 1 disabled");
    },
});

pnm.addButton('options', [{
    id: 'button1',
    className: 'fa fa-edit',
    command: 'example_cmd1',
    attributes: {
        // ...'
    }
}]);

cmdm.add('example_cmd2', {
    run: function(editor) {
        alert("Button 2 enabled");
    },
    stop: function(editor) {
        alert("Button 2 disabled");
    },
});

pnm.addButton('options', [{
    id: 'button2',
    className: 'fa fa-edit',
    command: 'example_cmd2',
    attributes: {
        // ...'
    }
}]);
```

**Comment by Ju99ernaut** [comment]
You have to add a different `context` for each button
```js
editor.Panels.addButton('options', [{
    //...
    context: 'some string',
    // ...
}]);
```

**Comment by RJCAM** [comment]
Thank you @Ju99ernaut , that's exactly what I needed.
