### ISSUE TITLE
[QUESTION] - add multiples CSS attributes with one button on StyleManager sidebar 

### ISSUE THREAD

**Issue by cartifon** [artf/grapesjs#2854]
Hey man, once again, great work on the GrapesJS, you are getting tons of things done, it is incredible!

So, my question is, how can I add multiples CSS properties with just one button on the StyleManager? 

What I want to add is a `display: flex; justify-content: center`, the way we have right now that I found on the documentation is to add just one property with one value, or you can stack the values for a complex property like border, shadow and so on... 

Am I missing anything on how to add that? 

Thanks in advance.

**Comment by Ju99ernaut** [comment]
At the moment I don't think you can do that with the `StyleManager` it may be easier to use [traits](https://grapesjs.com/docs/modules/Traits.html#add-traits-to-components)

**Comment by artf** [comment]
Yeah, unfortunately, @Ju99ernaut is right! 
Probably soon I'll start working on the StyleManager API which would allow a similar level of customization we have in Traits
