### ISSUE TITLE
reload prev data for custome react component plugin after reload page

### ISSUE THREAD

**Issue by i3laddin** [artf/grapesjs#2855]
Hello @artf 
i am working with that awesome tool for long time 
i integrate it with react , and create a react plugin component for it , and create custom trait to get data from api and render it throw the plugin , i setup a local storage and also make a button to save all data in the local storage and db
but i have a little problem , that when i reload page , all data for the custom component gone , and load the default setup , despite of all the others plugin keep it's own data when reload page , sorry if i didn't follow template for the issue , this is my first time to post my question on git , so if i made a mistake , just tell me and i will solve it 
thanks
 @artf

**Comment by artf** [comment]
For sure you didn't configure correctly the Storage Manager
Please read carefully this guide https://grapesjs.com/docs/modules/Storage.html

**Comment by i3laddin** [comment]
thanks @artf  for answer , i know how much time is important to you , but sorry for that , i configure it correctly , also i am get 200 for post request , also i get all of html and components and css for load request , but i have a little problem for prev traits for component , and render prev data 
![image](https://user-images.githubusercontent.com/62021418/85908456-6fef5000-b815-11ea-89a3-6b62b24621e3.png)
![image](https://user-images.githubusercontent.com/62021418/85908493-88f80100-b815-11ea-86c1-97aec11b7990.png)
![image](https://user-images.githubusercontent.com/62021418/85908558-d6746e00-b815-11ea-8bde-9193ae12f2b1.png)

and my porblem is i can't save that traits and get the same data from storage after reload editor 
and this screen to show that data and traits below 

![image](https://user-images.githubusercontent.com/62021418/85908615-091e6680-b816-11ea-8a52-278808f8f40b.png)

so when i reload editor it will like this 

![image](https://user-images.githubusercontent.com/62021418/85908644-2c491600-b816-11ea-8a0f-86fdc2087ed4.png)

it's render the default data for component when first initial , not the final data which i stored in db even html data in canvas or the traits and options for component 

i am sorry to bother you @artf  , and wish you can help !

**Comment by artf** [comment]
How did you define that custom component?
