### ISSUE TITLE
[HELP] "showComputed: false" strange behavior

### ISSUE THREAD

**Issue by makkaronis4e** [artf/grapesjs#2857]
Hi, i want to use showComputed: false, to prevent from counting right/left/top/bottom for position absolute.
But when i'm initializing grapesjs with this parameter, style manager doesnt show css-prop values for tablet/mobile screen size:

![image](https://user-images.githubusercontent.com/33792090/85742612-0e8f8a00-b70c-11ea-9910-6cc14020da53.png)

you can check it here https://codepen.io/makkaronis4e/pen/PoZjaXJ

**Comment by artf** [comment]
Steps to reproduce, please?

**Comment by makkaronis4e** [comment]
1. Drop some element on canvas
2. Add some styles (for example background color)
3. Switch to tablet/mobile view
4. check style prop value in style manager

**Comment by artf** [comment]
Ah ok, now I get it. Unfortunately, to show a style of a different view is part of the `showComputed` feature, so disabling it is what you get.
