### ISSUE TITLE
[QUESTION] After installing grapesjs-style-bg plugin, how do I add it to StyleManager?

### ISSUE THREAD

**Issue by ColdTuna** [artf/grapesjs#2858]
Newbie question here, I added the plugin `grapesjs-style-bg` to the stack, now how to I show it in my StyleManager?

I reset all the sectors from the StyleManager on initialization, and then I add them one by one using `styleManager.addSector("id", {...})`.

**Comment by pooriamo** [comment]
You can cheat from here: https://github.com/artf/grapesjs/blob/gh-pages/demo.html#L1127

You must add `background-bg` to the `buildProps` array and then config it in properties, the `type` must be `bg`:
```
[
    ...
    {
        name: 'Decorations',
        open: false,
        buildProps: ['opacity', 'border-radius', 'border', 'box-shadow', 'background-bg'],
        properties: [
            ...
            {
                id: 'background-bg',
                property: 'background',
                type: 'bg',
            }
        ]
        ...
    }
]
```

**Comment by ColdTuna** [comment]
@pooriamo, thanks man! Life saver! It works great! :)))

Thanks for the cheatssheet too, lots of goodies in there!
