### ISSUE TITLE
[HELP] Get css of selected component and its children

### ISSUE THREAD

**Issue by makkaronis4e** [artf/grapesjs#2861]
Hi,

i'm trying to implement possibility to save elements as custom blocks. 
How can i get css of component and its children? I can recursively get styles from each nested component, but maybe there is a way, how it can be done easier?

**Comment by Ju99ernaut** [comment]
```js
const component = editor.getSelected();
let componentCss = editor.CodeManager.getCode(component,  'css', {
   cssc: editor.CssComposer
});
```

**Comment by makkaronis4e** [comment]
@Ju99ernaut thanks!
