### ISSUE TITLE
[Bug]: Programmatic retrieval of layers' visibility always returns `true`

### ISSUE THREAD

**Issue by mcottret** [artf/grapesjs#2863]
Hello again :)

Our team might have found a bug while using the Layer Manager API: every call to `component.viewLayer.isVisible()` seems to always return `true`, regardless of their actual state.

Steps to reproduce:

- Open the [demo](https://grapesjs.com/demo.html)
- Switch to the layers panel
- Click on the eye icon to hide the "Body" layer
- Open the console
- Executing `editor.getWrapper().viewLayer.isVisible()` returns `1` instead of `false`

Looking at [the code](https://github.com/artf/grapesjs/blob/dev/src/navigator/view/ItemView.js#L303), I believe `this.model.getStyle()` should be used instead of `this.model.get('style')` (which always returns `{}`) to retrieve the current `display` value.

As always, I'd be happy to open a PR to fix it !

Cheers :)

**Comment by artf** [comment]
Yeah, you're totally right, the PR is welcome :)

**Comment by mcottret** [comment]
Great ! #2879 opened.
