### ISSUE TITLE
[QUESTION] enable 'view components' button on panel by default

### ISSUE THREAD

**Issue by Enmaboya** [artf/grapesjs#2865]
this button is currently off by default.
so you have to turn it on every time, which is not obvious to everyone.

how do you make it active right away?
![image](https://user-images.githubusercontent.com/32259003/86211877-1924a600-bb88-11ea-809d-1cb3bcc56275.png)

**Comment by mcottret** [comment]
Hi @Enmaboya !

You can retrieve the button using the [Panels API](https://grapesjs.com/docs/api/panels.html#getbutton) to make it active after initializing the editor, eg: 

`editor.Panels.getButton('options', 'sw-visibility').set('active', true);`

Note that the `getButton` parameters may vary depending on your panels & buttons configurations.

**Comment by Enmaboya** [comment]
@mcottret thank you so much!
