### ISSUE TITLE
[QUESTION] How to remove empty space at end of the page for free dragging?

### ISSUE THREAD

**Issue by sanjib00** [artf/grapesjs#2866]
Hello @artf ,

For free dragging, we are using `dragMode: 'translate'`. 
When we're moving all components from bottom to top position, it remains some blank space at end of the page and browser shows scroll, although we don't have any content at end of the page. See screenshot -

For better understanding, you can watch the video too. [Video URL](https://drive.google.com/file/d/1fA56z3CdbqQ1skGxBZIKqtf35kQAYfsp/view)

![grapesjs_empty_space](https://user-images.githubusercontent.com/8086390/86243227-cf5bb000-bbc7-11ea-8294-32f5ea903866.png)

Thanks.

**Comment by artf** [comment]
This is how `translate` mode works, the `absolute` mode doesn't leave any empty space
