### ISSUE TITLE
[Question] not escape html characters in textNodes?

### ISSUE THREAD

**Issue by Lostpixelr** [artf/grapesjs#2867]
Hi,

We are using some Twig template features in our grapesjs implementation. 
like: {% if variable == "value" %}<b>text</b>{% endif %} 

But due to the toHtml() function in src/dom_components/model/ComponentTextNode.js this gets converted into 
{% if variable == &quote;value&quote; %}<b>text</b>{% endif %}

Is there an easy way to not replace these values in a textNode  or replace the function with our own toHtml function ? 

Btw it used to be:  (which would've been awesome for us) 
toHTML() {
      return this.get('content');
}

**Comment by artf** [comment]
Yeah sure, you can extend the `textnode` component and use your toHTML function
