### ISSUE TITLE
[BUG] Image doesn't resize toolbar and selection frame on update

### ISSUE THREAD

**Issue by acxvgalanov** [artf/grapesjs#2871]
GrapesJs version: 0.16.18;

Steps to reproduce:

1. Add Image block, set any image;
2. Select the added block;
3. Double click and change image to any other image with a different size and/or ratio.

Expected result:
The image is updated, the toolbar position and selection frame are updated.

Actual result:
The image is updated, the toolbar position and selection frame stay the same.

[Video](https://monosnap.com/file/1aAcGfuTqJq9hEahwph7ELCx4sj7YN)

**Comment by artf** [comment]
Thanks for the report, it will be fixed in the next release
