### ISSUE TITLE
[BUG] Toolbar overflows the canvas

### ISSUE THREAD

**Issue by acxvgalanov** [artf/grapesjs#2874]
**Actual behavior:**
If the toolbar is placed on the element that is positioned near the bottom border, it may overflow the canvas and be partly hidden.

It can be reproduced with the default toolbar: [screenshot](https://monosnap.com/file/6mqG4QSX2WBBXnDkoZDuvsArBANyHP), but it's especially noticeable when the toolbar is customized and tall enough so some elements are inaccessible.

**Expected behavior:**
The toolbar is moved higher being "attached" to the canvas bottom border.

**Comment by artf** [comment]
Let me know if you're still working on the PR
