### ISSUE TITLE
[Bug] Resizing frame may be positioned around invalid element

### ISSUE THREAD

**Issue by fedulovivan** [artf/grapesjs#2876]
`Steps` to reproduce:

- open newsletter demo at https://grapesjs.com/demo-newsletter-editor.html
- clean canvas
- place "1/3 section"
- place "Image" in the middle column
- try to resize image - works correctly
- move selection to images's parent with click on upper arrow - 
![image](https://user-images.githubusercontent.com/752105/86509201-d6b0d280-bdee-11ea-942b-ff7d9f2f1003.png)
- resizing frame was moved to table cell which is incorrect. actioning with it impacts the image - works wrongly
- moving selection to parent makes frame to appear for table. actioning with it still impacts the image - works wrongly

See demo:
https://github.com/fedulovivan/misc/blob/master/Jul-04-2020%2011-49-35.gif

**Comment by artf** [comment]
Nice, it will be fixed in the next release
