### ISSUE TITLE
[Bug] Obsolete tag used on RTE

### ISSUE THREAD

**Issue by robsonsobral** [artf/grapesjs#2877]
Hi!

The [**strikethrough** command](https://github.com/artf/grapesjs/blob/master/src/rich_text_editor/model/RichTextEditor.js#L41) on RTE uses the [obsolete tag `<strike>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/strike):

> This feature is obsolete. Although it may still work in some browsers, its use is discouraged since it could be removed at any time. Try to avoid using it.

For no longer relevant or no longer accurate text, the [recommended tag is `<s>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/s).

> This element is deprecated in HTML 4 and XHTML 1, and obsoleted in HTML5. If semantically appropriate, i.e., if it represents deleted content, use `<del>` instead. In all other cases use `<s>`.

Thank you for your attention.

**Comment by artf** [comment]
Would you like to create a PR? :)

**Comment by robsonsobral** [comment]
Not at all! I'll send one later today!
