### ISSUE TITLE
FEAT: Extend 'undo' event

### ISSUE THREAD

**Issue by acxvgalanov** [artf/grapesjs#2888]
Hi, is there a way to find out the exact changes that happened to the document on the 'undo' (redo) event?
```
editor.on('undo redo', (...params) => {
// params is empty
});
```
It'd be a useful feature to know which elements have been affected (moved, changed, etc) by undo/redo.

**Comment by artf** [comment]
You can use the UndoManager API like `getStack` to check last changes
