### ISSUE TITLE
In panel create drop down of block as categorywise

### ISSUE THREAD

**Issue by rathodrupesha** [artf/grapesjs#2889]
Hello sir,

I want to create a dropdown button in the panel. Dropdown show category  & on category select one other drop down its showing for different block.

panel btn
  |_cat A
  |_Cat B 
         |-block A (that can draggable & on drag in layout area its showing HTML code or output)

How it's possible? could you pls provide code or details for how to do above things

Thanks
Rupesh

**Comment by artf** [comment]
https://grapesjs.com/docs/api/block_manager.html
