### ISSUE TITLE
Template font not loading

### ISSUE THREAD

**Issue by flavius75** [artf/grapesjs#289]
Hi,

I'm working on a project with GrapesJS and I want to set the font-family from 'Arial' to 'Raleway'.
 This font is correctly loaded in the style tag in header but it dosn't show in the preview.

Am I supposed to add it elsewhere (like  ../dist/fonts) ?
So I want to know what is the correct way of including new fonts supports in GrapesJS?

Thank you in advance.

**Comment by artf** [comment]
The canvas/preview is located in its own iframe so it doesn't see any of your document styles/scripts. You can inject your styles via `canvas` option and load them later in your final page/template (check also #262 to get more about it)
```js
const editor = grapesjs.init({
     ...
     canvas: {
            styles: ['https://...style', 'https://...font'],
          },
})
```
or you can just put the `<link>` tag inside your template and it will be loaded
```html
<div id="gjs">
    <link ...>      
    <div>Content</div>
</div>

<script>
const editor = grapesjs.init({
     container : '#gjs',
     fromElement: true,
})
</script>
```

**Comment by bungambohlah** [comment]
Hi all..

> or you can just put the <link> tag inside your template and it will be loaded

i dont recommend this, when empty the canvas, ```html <link> ``` tag will be removed
