### ISSUE TITLE
[Question] Upgraded 0.15.3 => 0.16.18, saved JSON is not storing some properties

### ISSUE THREAD

**Issue by Davidvlv** [artf/grapesjs#2891]
Hi, we upgraded from 0.15.3 to 0.16.18 and now the saved JSON coming out of grapesjs doesn't include some things that we were using before, namely styles and tagName.

Before Upgrade (0.15.3):
![image](https://user-images.githubusercontent.com/24515980/87260409-19f8f880-c4f5-11ea-8625-2147d0b72cb2.png)

After Upgrade (0.16.18):
![image](https://user-images.githubusercontent.com/24515980/87260384-f635b280-c4f4-11ea-9271-1e1192c71ee0.png)

As we don't use the HTML, only the JSON, we need those properties to be in the schema.

Is there some config we could turn on to save more info in the JSON schema? Or else how can we solve this?

Thanks

**Comment by longdoan7421** [comment]
Yes, there is. When init grapesjs, you could set the config [`avoidDefaults`](https://github.com/artf/grapesjs/blob/012d2d692b13e3510b2e322fc5290d93018b4046/src/editor/config/config.js#L132) to `false`.
