### ISSUE TITLE
BUG: CanvasView.clearOff not called when parent element is scrolled

### ISSUE THREAD

**Issue by metatick** [artf/grapesjs#2892]
v0.16.18 (also tested v0.16.22)

**Are you able to reproduce the bug from the demo?**

[X] Yes
[ ] No

**What is the expected behavior?**
grapesjs should behave correctly inside a scrolling element

*Describe the bug **detailed***
When grapesjs run within a scrolling parent element (except for window), the canvas does not clear it's offset cache when the parent element is scrolled.
This causes the highlighting boxes and other canvas effects to be displayed incorrectly.

**What is the current behavior?**
Anything written to the canvas is misaligned when a parent element is scrolled. This can be 'fixed' by calling CanvasView.clearOff().

**Are you able to attach screenshots, screencasts or a live demo?**

[X] Yes (attach)
[ ] No

https://codesandbox.io/s/pensive-golick-gjsmi

Steps to reproduce:
1. Hover over the canvas
2. Scroll down/right
3. Hover over the canvas again

**Comment by artf** [comment]
Thanks for the report @metatick are you able to confirm if it's the same issue as #2722?
In that case, this should be closed (but might worth reporting the same codesandbox).
