### ISSUE TITLE
How to replace RTE with TinyMCE

### ISSUE THREAD

**Issue by krishnaeverestengineering** [artf/grapesjs#2895]

**Comment by fedulovivan** [comment]
https://grapesjs.com/docs/guides/Replace-Rich-Text-Editor.html

**Comment by krishnaeverestengineering** [comment]
> https://grapesjs.com/docs/guides/Replace-Rich-Text-Editor.html

It's not working with Tiny. I tried some solutions but some of the tiny tools like formatting isn't working, instead it is creating new P elelements

**Comment by artf** [comment]
If anybody wants to help with the TinyMCE integration can post here: https://github.com/artf/grapesjs/issues/1697
