### ISSUE TITLE
[Question] help contributing to the mjml repository

### ISSUE THREAD

**Issue by DRoet** [artf/grapesjs#2897]
Hi @artf 

I'm sure you are very busy these days, but I have been trying to reach out about helping move the  `grapesjs-mjml` project forward.
I know this is not the right repository to ask but I have higher hopes of reaching you here.

I have several PRs open, see https://github.com/artf/grapesjs-mjml/pulls and I've contributed in the past.

I would like to become a contributor to the project so I can triage/close issues and release new versions if this is possible.

Thank you for you time, keep up the great work

**Comment by artf** [comment]
Yeah sure man, unfortunately, I can't focus on that plugin right now so your help is really appreciated

**Comment by DRoet** [comment]
No problem, I appreciate all the effort you put in so far, thanks for the invite

**Comment by artf** [comment]
DM me on twitter if you need my direct contact

**Comment by DRoet** [comment]
Unfortunately I don't have twitter, I created a release but I think I'm missing rights to the NPM repo so I can't publish it
