### ISSUE TITLE
Reload after importing newsletter template removes inline css styles.

### ISSUE THREAD

**Issue by bariscimen** [artf/grapesjs#29]
Hi!,

I really appreciate you for this great project! :)

My problem is that on newsletter editor, when I import a newsletter template, all inline styles are removed after reloading the page.

**Comment by artf** [comment]
Hi @bariscimen thanks for the report, but I can't replicate the issue, can you post your template here? Or at least, a part of it?

**Comment by artf** [comment]
@bariscimen Did you solve the problem?

**Comment by Alcuin-van-Zijl** [comment]
Hi,

This is quite easy to reproduce. Try loading this html:

<div id="c818" style="box-sizing: border-box; padding: 10px;"><span style="box-sizing: border-box; font-size: 28px;">Insert your text here</span></div>

The result should be text with font-size 18. This element is removed though.

Best regards,

**Comment by artf** [comment]
@Alcuin-van-Zijl tried in the demo but it works as expected

**Comment by Alcuin-van-Zijl** [comment]
Hi, 
Thanks for your reply and the great work you do here.
I came to the conclusion later that this was an issue that played in an older version.

Please ignore my post. I should have removed it.

Best regards!
