### ISSUE TITLE
Can we use GrapesJS as Content Editor (WYSIWYG) also? 

### ISSUE THREAD

**Issue by krishnaeverestengineering** [artf/grapesjs#2900]
We have a requirement of both writing articles, landing pages and writing articles more like landing page as well. So we thought GrapesJS would best suit for us but we want to know that, Is this framework would good for Content Editing as well like TinyMCE / CKEditor experience? 

Because CKEditor / TinyMCE is text area based content for specially for blog / article writings whereas GrapesJS is for Canvas based mostly to design the pages. So how good it is use as a WYSIWYG editor?

**Comment by artf** [comment]
Using GrapesJS only as a WYSIWYG editor probably is an overhead as it would require more time on configuration, but for sure it's possible as internally there is already an RTE module (the default one is probably too much simple but you can use the CKEditor plugin)
