### ISSUE TITLE
FEAT: reset current frame view

### ISSUE THREAD

**Issue by nlnbich** [artf/grapesjs#2902]
**Version: 0.16.12**

**Are you able to reproduce the bug from the demo?**

[ ] Yes
[x ] No

**What is the expected behavior?**
Reset window content of current frame view

*Describe the bug **detailed***
I want to implement a component to help user do certain action by attaching event to widow (ex: *scroll* or *resize* event) or add some data to window (ex: window.pageConfig = "abc")

This component is used in different pages. But each time user switches between pages, more and more handlers get attached or component use old data from the previous page. 
I try to use [clear-canvas] command but it only clear dom-elements and css-rules.
I try to add a new frame view to replace the current frame view, but I know sure how to do that correctly.

Could you please help to give some advice ?
Thanks

**Comment by artf** [comment]
You can get the canvas inner window in this way `editor.Canvas.getWindow()`
