### ISSUE TITLE
FEAT: Please Provide a Sample Image Uploader for PHP

### ISSUE THREAD

**Issue by moemos** [artf/grapesjs#2903]
Hello, great editor!

It would be very handy if there was a sample PHP upload script to get images uploaded to a PHP webserver.
It could be a simple one with the correct configuration explained in the documentation. For beginners it is quite hard to figure out how to enable image uploading and what kind of Server/API is needed.

Thanks!

**Is there an alternative at the latest version?**

[ ] Yes (descripe the alternative)
[x] No

**Is this related to an issue?**

[ ] Yes (Give a link to the issue)
[x] No

**Comment by artf** [comment]
Sorry but this is totally off-topic

**Comment by moemos** [comment]
Sorry :(
