### ISSUE TITLE
BUG: dragging components in preview mode enables editor mode

### ISSUE THREAD

**Issue by RJCAM** [artf/grapesjs#2904]
We can reproduce the bug from the [demo](https://grapesjs.com/demo.html)

**Current Behavior:**
![chrome-capture](https://user-images.githubusercontent.com/49693237/87928689-5b952080-ca6c-11ea-89e1-8437f82a0908.gif)

**Expected Behavior:**
We should not be able to drag/move components when in preview mode.

**Comment by artf** [comment]
Will be fixed in the next release. For now, you can patch it on your own, in this way:
```js
const preventDrag = (opts) => opts.abort = 1;
editor.on('run:core:preview', () => {
	editor.on('run:tlb-move:before', preventDrag);
});
editor.on('stop:core:preview', () => {
	editor.off('run:tlb-move:before', preventDrag);
});
```
