### ISSUE TITLE
BUG: editor.refresh() not working in custom setup

### ISSUE THREAD

**Issue by neon12345** [artf/grapesjs#2906]
I have a problem with a custom setup where the canvas iframe is moved around with js. The "editor.refresh()" call does not fix the positioning of the tools after the move. 

I think the problem is due to the offset cache not cleared on refresh.

If I call this before refresh, the tools are positioned as expected:

                    editor.trigger('test:canvasOffset');
                    editor.trigger('frame:updated');

Version: 0.16.18

**Comment by artf** [comment]
@nedim1511 can you please provide a reproducible demo, please?

**Comment by neon12345** [comment]
https://jsfiddle.net/3gqh6p5a/

Click select the "Hello World" and drag the vertical splitter to the left to resize the split window. The "editor.refresh()" called on dragEnd should align the tools but it does not seem to work.

**Comment by artf** [comment]
On my local copy, your example works correctly so probably in the next release it will be fixed

**Comment by artf** [comment]
New release published, try to check if it fixes your issue
