### ISSUE TITLE
FEAT: Combine getDirtyCount with undo/redo

### ISSUE THREAD

**Issue by neon12345** [artf/grapesjs#2908]
Currently the changesCount is only increased regardless of undo and redo. I wonder if there is an application where the actual value is used or if this is just a boolean indicator for changes.

If it is just used as boolean, it would be possible to instead add a flag to the undo state and mark the saved position. This way it is possible to signal changes only when the undo stack does not point to the saved position on undo and redo.

Something like this seems to work:

        var um = editor.UndoManager;
        var changepoint = null;
        var hasChange = false;

        function findChange() {
            var s = um.getStack();
            var idx = s.pointer;
            var old = hasChange;
            
            if(idx != -1) {
                hasChange = changepoint !== s.models[idx];
            } else {
                hasChange = changepoint !== null;
            }
            
            if(old != hasChange) {
                console.log('changed', hasChange);
            }
        } 
        
        function saveChange() {
            var s = um.getStack();
            var idx = s.pointer;

            if(idx != -1) {
                changepoint = s.models[idx];
            } else {
                changepoint = null;
            }
        }

        editor.on('undo', findChange);
        editor.on('redo', findChange);
        editor.on('load', function() {
            var i = um.getInstance();
            var add = i.constructor.prototype._addToStack;
            i.constructor.prototype._addToStack = function() {
                var ret = add.apply(this, arguments);
                findChange();
                return ret;
            }
        });

**Comment by mcottret** [comment]
Hi @neon12345 !

As far as I know, the `changesCount` is also used in conjunction with `stepsBeforeSave` to trigger storing when `autosave` is enabled. 

(cf: 
    - https://grapesjs.com/docs/modules/Storage.html#store-and-load-templates
    - https://github.com/artf/grapesjs/blob/dev/src/editor/model/Editor.js#L170
)

**Comment by neon12345** [comment]
Ok. But that means undo and redo will trigger autosave, which is not optimal.

**Comment by artf** [comment]
getDirtyCount returns the number of changes, so it's not used as a boolean.
If you have a better solution to handle undo/redo changes the PR is welcome
