### ISSUE TITLE
FEAT: Support for search and commands in the editor for custom components

### ISSUE THREAD

**Issue by tvvignesh** [artf/grapesjs#2909]
Hi. First of all, awesome work with grapesjs. Had a feature request which may greatly improve usability for users.

While grapesjs does allow to categorize components like these:

![Screenshot from 2020-07-21 13-55-26](https://user-images.githubusercontent.com/1165845/88031174-db4ce900-cb59-11ea-98ad-4fd3c95b40ee.png)

It will be great if there is support for searching components to import and import them (a normal filter from the sidebar would also do). This way, even if there are hundreds of blocks, i can search for what I need and import them rather than going through the layers individually and picking them.

Also, if you have use editors like `notion.so` they support adding their components like these via commands `/` as and when you type in the editor. This can also be added to grapesjs and users can keep editing their page and use the commands to add components they want to the page in the place where the cursor is.

![Screenshot from 2020-07-21 13-57-32](https://user-images.githubusercontent.com/1165845/88031501-50202300-cb5a-11ea-8fea-35e1b043de2b.png)

Infact, you can combine search with this like this (for instance if you want a todo list, you type todo)

![Screenshot from 2020-07-21 13-59-14](https://user-images.githubusercontent.com/1165845/88031606-6fb74b80-cb5a-11ea-98f2-c7848cae7148.png)

Hope this makes sense. Thanks again.

CC: @artf

**Comment by artf** [comment]
Hi @tvvignesh for sure it makes sense but as you know UIs related stuff are highly arguable so it requires a lot of code to make it as much customizable as possible.
So far, I've stopped adding UI stuff in the core and started making it more API-oriented, indeed you should be able to implement it by using [Blocks API](https://grapesjs.com/docs/api/block_manager.html) which is the same thing we've done in Grapedrop
![blocks-search](https://user-images.githubusercontent.com/11614725/89180930-03ddd580-d593-11ea-8d47-1aa8625c70ea.png)

**Comment by tvvignesh** [comment]
@artf Thanks for your inputs on this. Will try implementing using Blocks API. 

Just one question though. Since I would like to add blocks in the location where the cursor is by searching for the block as in the screenshot, may I know the recommended way that you would do that using the Blocks API?

Would you get the JS Cursor position X,Y coords then add it or is there a way to find out the container in which the cursor is present? If you could provide some inputs on how you would get the position on where to add the block, I will try implementing it myself and see if that works. Thanks.
