### ISSUE TITLE
BUG: Infinite Recursion by dragging and dropping an component into itself on firefox

### ISSUE THREAD

**Issue by FlowingCloudRTL** [artf/grapesjs#2911]
**Version: 0.16.18**

**Are you able to reproduce the bug from the demo?**

[X ] Yes
[ ] No

**What is the expected behavior?**
You should not be able to drag a component into itself

*Describe the bug **detailed***
On firefox, you can drag a component into itself by directly clicking on the element and then drag it within itself.
This gets rid of the element and creates infinite recursion. 

**Are you able to attach screenshots, screencasts or a live demo?**

[X
![2020-07-22 00-53-18](https://user-images.githubusercontent.com/49292515/88136398-26491980-cbb7-11ea-89b4-896c25cd7e41.gif)
 ] Yes (attach)
[ ] No

**Comment by artf** [comment]
Thanks for the report @FlowingCloudRTL. The issue will be fixed in the next release
