### ISSUE TITLE
biorender

### ISSUE THREAD

**Issue by perfectwebtech** [artf/grapesjs#2912]
hello

is it similar  i can build  https://biorender.com/

like online design builder ? 

i can use this grapes or any other suggestion for me ?  i wam tto build biorender same thing plz help me or suggestion me

**Comment by Ju99ernaut** [comment]
I wouldn't recommend it, `grapesjs` is mainly a website builder framework...you need something like an svg editor in my opinion.

**Comment by artf** [comment]
You can actually make use of absolute mode in GrapesJS but there is still a lot of work to do make it work good like in your example, and, as already suggested, the editor is mainly focused on web projects.

**Comment by perfectwebtech** [comment]
oh ok great thanks a lot really

**Comment by perfectwebtech** [comment]
any other js framework also reminder might be some tools usefull from others too ? paperjs ? like this ? also good ? 

http://paperjs.org/examples/
