### ISSUE TITLE
BUG: src is stored twice with image

### ISSUE THREAD

**Issue by neon12345** [artf/grapesjs#2913]
The output of "JSON.stringify(editor.getComponents())" shows that the src of an image is stored twice.

                 {
                    "type": "image",
                    "void": true,
                    "status": "selected",
                    "content": "",
                    "attributes": {
                      "id": "iy3c7",
                      "src": "data:image/png;base64,..."                    <--- 1.
                    },
                    "src": "data:image/png;base64,...",                     <--- 2.
                    "activeOnRender": 0,
                    "open": false
                  }

Version is v0.16.18 - validated with the demo.

**Comment by longdoan7421** [comment]
Hi @artf, 

I just took a quick look through `ComponentImage`. I think it is possible to drop the `src` property in image model and replace the code which use `src` in `ComponentImage` and `ComponentImageView` with the `attribute.src`. 

But I am not sure that do you use the `src` property in any where else? What do you think about that?

**Comment by artf** [comment]
@longdoan7421 I think we can delete it in `toJSON` method when the `src` is equal to `attribute.src` and ensure is loaded back correctly on load
