### ISSUE TITLE
FEAT: Adding custom styles to element using ID.

### ISSUE THREAD

**Issue by BerkeAras** [artf/grapesjs#2914]
**What are you trying to add to GrapesJS?**
Adding custom styles (like background) to element using ID.

**Is there an alternative at the latest version?**

[ ] Yes (descripe the alternative)
[X] No

**Is this related to an issue?**

[ ] Yes (Give a link to the issue)
[X] No

**Comment by mcottret** [comment]
Hi @BerkeAras !

Apparently it is undocumented but `editor.Components.allById()` might be what you're looking for, eg:

```typescript
editor.Components.allById()['your-id'].set('style', {'background-color': 'red'});
```

Hope this will help, cheers :) !

**Comment by artf** [comment]
The proper way would be this:
```js
const compById = editor.getWrapper().find('#i9x9h')[0];
compById && compById.addStyle({ 'background-color': '...' });
```
