### ISSUE TITLE
Usage with react-pdf

### ISSUE THREAD

**Issue by maxaggedon** [artf/grapesjs#2915]
React-pdf is cited [in the docs](https://grapesjs.com/docs/) but I don't see any other mention of it anywhere...

Does someone know if a working project was ever made using grapesjs as a pdf template builder ?

Any info about how to integrate both would highly appreciated =)

**Comment by artf** [comment]
You can create custom components and reflect the behavior of React-PDF components (similar to what we've done with MJML) so it's about understanding how custom components work.
