### ISSUE TITLE
BUG: textnode is not removed from canvas

### ISSUE THREAD

**Issue by neon12345** [artf/grapesjs#2918]
Text imported directly to the wrapper is not removed from the canvas with the component. 

To verify one can import simple texts multiple times to the demo and watch how they combine instead of replacing the previous one.

Adding this seems to help:

        editor.DomComponents.addType('textnode', {
            model: {
                removed() {
                    var el = this.getEl();
                    el.parentNode.removeChild(el);
                }
            }
        });

Tested with the demo v0.16.18.

**Comment by artf** [comment]
I don't follow your example, can you illustrate exact steps to reproduce, please?

**Comment by neon12345** [comment]
Go to the newsletter demo at https://grapesjs.com/demo-newsletter-editor.html and use the "Import template" function with simple text like "hello" but no html (or combine it with html and text on the root level). Repeat this and the text on the root level will not be removed but add up on each import.

**Comment by artf** [comment]
Thanks @neon12345, I was able to find the issue and it should be fixed in the next release
