### ISSUE TITLE
BUG: Custom Blocks are wrapped into a div

### ISSUE THREAD

**Issue by BerkeAras** [artf/grapesjs#2919]
**Version:**
0.16.18

**Are you able to reproduce the bug from the demo?**

[X] Yes: [https://codesandbox.io/s/empty-night-8q733?file=/index.js](https://codesandbox.io/s/empty-night-8q733?file=/index.js)
[ ] No

**What is the expected behavior?**
The Element "Link Button" should not be in a div. There should not be a div, just a 'a' tag

**What is the current behavior?**

Custom blocks are wrapped into a div.

**Are you able to attach screenshots, screencasts or a live demo?**

[X] Yes [https://codesandbox.io/s/empty-night-8q733?file=/index.js](https://codesandbox.io/s/empty-night-8q733?file=/index.js)
[ ] No

**Comment by mcottret** [comment]
Hi @BerkeAras !

As shown on the [Getting started page](https://grapesjs.com/docs/getting-started.html#define-components), you can specify a `tagName` property when defining custom blocks & components to override the default `div` tag.

Cheers !

**Comment by artf** [comment]
You're passing a description for a component and then adding inner `content` (`<a>` tag) to that component
