### ISSUE TITLE
Links disable editing text

### ISSUE THREAD

**Issue by BiserStoilov** [artf/grapesjs#292]
Hi, 

When add link to word in text:

```
<div>Insert your text 
     <a class="link" data-highlightable="1">here</a>
</div>
```

and save to db and reload, text is not editable.

Structure in layer manager before save:
>Body
>>Row
>>>Cell
>>>>Text
>>>>>Link

Structure in layer manager after save and reload:
>Body
>>Box
>>>Box
>>>>Box
>>>>>Link

What's the problem?
Thanks in advance!

**Comment by BiserStoilov** [comment]
Please, import this code

```
<div class="c3520">Insert 
  <a class="link" data-highlightable="1">your</a> text here
</div>
```

in your demo
http://grapesjs.com/demo.html
to see this bug.

**Comment by ArtDesignCreativeStudio** [comment]
Find in grapes.js this code

```
t.exports = {
     textTags: ["br", "b", "i", "u"]
}
```

and replace with this:

```
t.exports = {
     textTags: ["br", "b", "i", "u", "a"]
}
```

**Comment by BiserStoilov** [comment]
Works perfect, thanks!
