### ISSUE TITLE
Question: Replace Rich Text Editor with summernote does not seem to work 

### ISSUE THREAD

**Issue by wfcheng** [artf/grapesjs#2920]
I am trying to replace the default RTE in grapesjs with [summernote](https://summernote.org/).  I got some help from the author of summernote and got this [codepen](https://jsfiddle.net/easylogic/hxre19cL/43/) to work somewhat, but the summernote author concluded that:

`But grapejs p element is a content in iframe.  In other words, there is a structure where a p tag exists in an iframe and ui must exist outside. Summernote is a structure that hides the element and puts the tag of summernote. It seems difficult to use because the rest of the resources of summernote are not loaded in the iframe.`

I prefer summernote over TinyMCE or CKEditor since it is "MIT license". Has anyone tried to replace RTE with summernote with success?  Any suggestions?

**Comment by wfcheng** [comment]
Made some more changes and now the summernote toolbar appears correctly but only bullet formatting works.  The new codepen is [here](https://jsfiddle.net/easylogic/hxre19cL/70/).  @artf Any pointers would be greatly appreciated.

**Comment by timramseyjr** [comment]
@wfcheng Did you ever get anywhere with this? The codepen includes the canvas script/styles which adds the resources inside the iframe, so I was a little confused what summernote author was referring to.

**Comment by wisecheng38** [comment]
@timramseyjr I ended up just adding more buttons to the RTE toolbar to allow applying font styles and color on selected text, even though the grapesjs documentation recommends to use the style manager.  I found that it is more user friendly to have them on the toolbar.

**Comment by wfcheng** [comment]
Close issue as I am using a workaround.
