### ISSUE TITLE
[QUESTION]: Get all css without specific component and it's children

### ISSUE THREAD

**Issue by RJCAM** [artf/grapesjs#2922]
Hi, so, in this issue #2861 we can **get all the css of a selected element and it's children** with:
```
const component = editor.getSelected();
let componentCss = editor.CodeManager.getCode(component,  'css', {
   cssc: editor.CssComposer
});
```

But if I want to get all the css but **without** specific component and it's children or exactly the inverse of the above
Is there a way to do this?

**Comment by mcottret** [comment]
Hi @RJCAM !

I don't think there's a built-in way to achieve this, but building on top of the answer you linked, you can retrieve all the components except the selected one & its children, then concatenate all their CSS' like the following (assuming `window.editor` for the example, may need to be adapted):

```typescript
function getAllExceptSelectedComponentsCss(includeWrapper) {
    const selectedComponent = editor.getSelected();
    const allExceptSelectedComponents = includeWrapper ?
            allExceptSelectedComponentsReducer([], editor.getWrapper()) :
            editor.getComponents().reduce(allExceptSelectedComponentsReducer, []);

    function allExceptSelectedComponentsReducer(allExceptSelectedComponents, component) {
      if (component !== selectedComponent) {
        allExceptSelectedComponents.push(component);

        const childrenComponents = component.components();

        if (childrenComponents.length) {
          allExceptSelectedComponents = childrenComponents.reduce(allExceptSelectedComponentsReducer, allExceptSelectedComponents);
        }
      }

      return allExceptSelectedComponents;
    }

    return allExceptSelectedComponents.reduce((allExceptSelectedComponentsCss, component) => allExceptSelectedComponentsCss + editor.CodeManager.getCode(component,  'css', {
      cssc: editor.CssComposer
    }), '');
  }
```

Cheers !

**Comment by RJCAM** [comment]
Hi @mcottret, thanks for your response
I think your right, I'm going to edit your code to make it work as I expect
I really appreciate your help, thank you!

**Comment by mcottret** [comment]
@RJCAM I'm sorry I just noticed that my previous answer wasn't working because retrieving the CSS of a component with children also includes the children's CSS (it hence produced duplicated styles, as well as including the selected component's style if it was nested). I edited it to fix that.

**Comment by RJCAM** [comment]
@mcottret that's awesome 🤩, actually, i've noticed that, the styles were duplicated as you said. I did a tiny function to remove the duplicated styles, hahahah (it works)
But if you were able to resolve that issue editing the code is really better. Thanks again, and sorry for any constraints ✌😁
