### ISSUE TITLE
[QUESTION] Component HTML being changed

### ISSUE THREAD

**Issue by tomazkramberger** [artf/grapesjs#2924]
I am using GrapesJs to define Freemarker FTL templates. I am seeking an issue when my custom component HTML has been changed after inserted into canvas or imported through Import template component using newsletter plugin.

So my original HTML content looks like:

```
<table>
    [#list items as item]
        <tr>
            <td>
                <div class="m-stack m-stack--ver m-stack--general">
                    Some content ${item.id}
                </div>
            </td>
        </tr>
    [/#list]
</table>
```

into

```
[#list items as item][/#list]
<table>
    <tr>
        <td>
            <div class="m-stack m-stack--ver m-stack--general">
                Some content ${item.id}
            </div>
        </td>
    </tr>
</table>
```

which corrupts my template.

Is there a way to bypass HTML formatting or whatever is going behind to cause this?

**Comment by ShenolHusein** [comment]
@tomazkramberger did you find a solution to this problem?

**Comment by tomazkramberger** [comment]
> @tomazkramberger did you find a solution to this problem?

@ShenolHusein Yes, i did. Here is the link to solution https://stackoverflow.com/questions/63475404/html-editor-removes-freemarker-tags-inside-table-tag
