### ISSUE TITLE
[Question] How to realize click hyperlink jump？

### ISSUE THREAD

**Issue by Zero-Zheng** [artf/grapesjs#2926]
hi @artf 

I want to implement dynamic link jump in grapes JS, but I can't find an effective method.

Can you help me?

![image](https://user-images.githubusercontent.com/18066536/88675948-146af780-d11e-11ea-83c3-05687b3dfef6.png)

**Comment by artf** [comment]
If for "hyperlink jump" you mean the anchor link, in that case, you have to append `#ID_ELEMENT` to the link, where ID_ELEMENT is the id of the element you want to point
