### ISSUE TITLE
Enable the default RTE with a command

### ISSUE THREAD

**Issue by phil1995** [artf/grapesjs#293]
Hello artf,

is it possible to trigger the default RTE with a command?
I've found that it should be enableEditing() but it won't work.
In my case I have selected a editable Component and it shows a Edit Item in the component-toolbar. 
But I can't figure out how to trigger it the same way like a doubleclick in this component would do it.

**Comment by artf** [comment]
`enableEditing` is attached to to the view and you can get its instance from the model, so select the component and run this in console `editor.getSelected().view.enableEditing()`

**Comment by phil1995** [comment]
Ok thanks for the fast answer!
I've tried it but nothing happen when I call it. Not even an error occurs.
in my `var editor  = grapesjs.init({..}`
I have the following command:
`commands: {
      defaults: [{
        id: 'tlb-edit',
          run:  function(editor){
          editor.getSelected().view.enableEditing();
        },
    }]
    },`
Sorry for the weird formatting but otherwise Github display it not longer as code.

**Comment by artf** [comment]
> I've tried it but nothing happens when I call it. Not even an error occurs.

weird... I just tried it in the demo and it works, are you sure you have selected an editable component?
![text-edit](https://user-images.githubusercontent.com/11614725/30296455-8468950e-9744-11e7-9474-309277be49ff.gif)

GitHub tip: https://guides.github.com/features/mastering-markdown/ use triple backquote (and name of the language for colors) if you want a formatted code

**Comment by phil1995** [comment]
Okay I have found the error for me. 
I initialized the editor inside the document.ready function and with this I got an reference error (but only on console and not with the button).
But my problem is now when I call it with the button like in my snippet above, still nothing happens only when I use the code via console.

**Comment by artf** [comment]
which button? how do you call the command `tlb-edit`?

**Comment by phil1995** [comment]
I added a new button to the component toolbar in the Component.js with:
```
if(model.get('editable')) {
        tb.push({
          attributes: {class: 'fa fa-pencil'},
          command: 'tlb-edit',
        });
      }
```

**Comment by artf** [comment]
Try to add some debug inside the command (eg. `debugger;/console.log`) and call it via the editor to see if it's actually there
```js
editor.runCommand('tlb-edit');
```

ps: is there a reason of why you're editing the source file?

**Comment by phil1995** [comment]
The command is working because when I placed an alert inside it for example:
```
commands: {
      defaults: [{
        id: 'tlb-edit',

        run:  function(editor){
          editor.getSelected().view.enableEditing();
          alert("Hello world!");
        },
    }]
    },
```
On click it shows the alert "Hello world!" correctly.
I edit the source file because I want to delete later the things which I don't need to get a lot smaller code.

**Comment by artf** [comment]
maybe there is some event overlapping between the click and focus, try to call it in this way
```js
...
setTimeout(() => editor.getSelected().view.enableEditing(), 0)
```

**Comment by phil1995** [comment]
Perfect now it's working.
Thank you so much for your help! :+1:

**Comment by edwardjiawei** [comment]
How does make it work on http://grapesjs.com/demo.html


`
  editor.Commands.add('tlb-edit', {
    run:  function(editor, sender){
      alert('Hello world!');
    },
    stop:  function(editor, sender){
    },
  });

    editor.RichTextEditor.add('tlb', {
    command: function(){editor.getSelected().view.enableEditing();
          alert("Hello world!");},
    class: 'fa fa-link',
    title: 'test',
  });  
`

**Comment by sakshigarg9** [comment]
> `enableEditing` is attached to to the view and you can get its instance from the model, so select the component and run this in console `editor.getSelected().view.enableEditing()`

How do i get the instance of view from the model? I'm trying to get a similar implementation as in question
