### ISSUE TITLE
FEAT: Documentation update for block manager 

### ISSUE THREAD

**Issue by PrabuPro** [artf/grapesjs#2931]
Hi,

First I need to thank you for creating this amazing editor. 

I want to contribute for the documentation of the block manager part. When I'm digging through the documentation I found out the block manager remove example is missing from the documentation.  
I have updated the documentation and create a pull request.

**Comment by GoodPHP** [comment]
Hi,

If you didn't find answer here, you can contact with Devfuture Team: https://devfuture.pro/contact/

We specialise on GrapesJS.
