### ISSUE TITLE
BUG: "display" property of Style Manager doesn't sync with Layer Manager

### ISSUE THREAD

**Issue by tranthanhhoa** [artf/grapesjs#2938]
**Version:** v0.16.18

How to reproduce:
- Select a component
- Choose Layer tab
- Hide component
- Back to Style tab
- Check "display" property
![Alt Text](https://s7.gifyu.com/images/display-error.gif)

Expected:
- "display" should be "none"

Actually:
- "display" is still "block"

**Comment by Ju99ernaut** [comment]
The `StyleManager` doesn't seem to update when styles are changed from somewhere else...the `display` property does get updated once you deselect and select the component again. Probably the `StyleManager` needs to updated to listen for changes to `display` property from the `LayerManager`.

**Comment by artf** [comment]
Will be fixed in the next release. Thanks
