### ISSUE TITLE
QUESTION: Why does the editor itself not using `gjs-html``for canvas representation?

### ISSUE THREAD

**Issue by nhh** [artf/grapesjs#2941]
Hey,

we are currently using grapejs to create liquid templates (shopify syntax). The way its currently implemented will leave the template, for example ``{{ name }}`, unrendered within the editor.

This is due to the fact, that even if the `gjs-html` gets interpolated by the server after a store/load cycle, the editor still uses not-interpolated `gjs-components` to represent the editors content.

Why does the editor not use the rendered html to display? As i understand the component structure is only used internally for component assignment.

Is there a way to work around this behavior? (I dont really want to run my interpolation on the components json)

**Comment by artf** [comment]
Well, if you load back the HTML you'll lose all the component information (kind of explained [here](https://grapesjs.com/docs/modules/Storage.html#store-and-load-templates)).
As an analogy, try to think about Photoshop files and JPG as an output. If you load back the JPG you won't see the layers used in your Photoshop project.

It's up to you find the way to make the interpolation work with your components (eg. making an async call to some endpoint and update the content of the component)
