### ISSUE TITLE
Question:How to add multiple levels to "category" so that blocks can be displayed in the preview floating window?

### ISSUE THREAD

**Issue by mofengwyh** [artf/grapesjs#2942]
Hi!
I want to achieve such a feature: when the mouse moves over a block, the floating window displays its next level blocks. As shown below:
![效果](https://user-images.githubusercontent.com/67369201/89601205-8f5aad80-d896-11ea-865e-a99b5961ed72.jpg)
I made a floating window div, but I don’t know how to display the blocks in the floating window. I read about [`BlockManager.render()`](https://grapesjs.com/docs/api/block_manager.html#render) in the documentation, but it can only control where the blocks are displayed, I don't think it is an appropriate way. I would like to ask if there are other solutions?
Hope someone can answer this question, thank you very much!

**Comment by artf** [comment]
By using the BlockManager API you have to build your own UI for such a case
