### ISSUE TITLE
BUG: this.get('content') returns empty string when trying to add custom component type

### ISSUE THREAD

**Issue by Joshmamroud** [artf/grapesjs#2943]
**Version:**
0.16.18

**Are you able to reproduce the bug from the demo?**

[>>> Demo <<<](https://jsfiddle.net/b4ox0nLp/16/)

[ X ] Yes
[    ] No

**What is the expected behavior?**
Expecting this.get('content') in the context of the model while creating a new component type (extending the default component type) should return the children as HTML.

*Describe the bug **detailed***
Not sure if it's a but or I'm doing something wrong however in all of the examples I've come across in other issues it seems like `this.get('content')` should return it's children's HTML but instead it returns an empty string.

**What is the current behavior?**
It only returns the text content in the component if there is any but if there are children components it will not return them.

**Are you able to attach screenshots, screencasts or a live demo?**

![demo](https://user-images.githubusercontent.com/5224187/89663818-2a0db900-d8a4-11ea-84eb-61282ece0136.gif)

[ X ] Yes (attach)
[    ] No

**Comment by Joshmamroud** [comment]
@artf does this look like a bug or am I doing something wrong?

**Comment by DmitryTar1** [comment]
> @artf does this look like a bug or am I doing something wrong?

May be try model.components() insead of content

**Comment by Joshmamroud** [comment]
That does return the components however as an object. I'm looking for the HTML. Any thoughts?

**Comment by DmitryTar1** [comment]
May be el.innerHTML

> That does return the components however as an object. I'm looking for the HTML. Any thoughts?

**Comment by Joshmamroud** [comment]
> May be el.innerHTML or var el = prototype.__proto__.toHTML.call(this);
> 
> > That does return the components however as an object. I'm looking for the HTML. Any thoughts?
> 
> 

OK I'll give those a try and report back. Thanks!

**Comment by artf** [comment]
No, `content` property is only used in components like Text/Textnode.
Replace your `this.get('content')` with `this.components().map(comp => comp.toHTML())`

**Comment by Joshmamroud** [comment]
Thank you!
