### ISSUE TITLE
[Question]: Modify block category and label image

### ISSUE THREAD

**Issue by jayeshmotwani** [artf/grapesjs#2945]
Hii, I wanted to change the category of the bootstrap4. I wanted to rename the typography to Text and Change the icon for the blocks.
![Edit type and Change Icon](https://user-images.githubusercontent.com/27188013/89708578-09be2700-d996-11ea-8dcf-d9840a21a105.png)

Could you please help me understand how can I achieve this?

**Comment by Joshmamroud** [comment]
@jayeshmotwani check out the documentation [here](https://grapesjs.com/docs/api/block_manager.html#examples)
