### ISSUE TITLE
Edit panels styles (rookie question)

### ISSUE THREAD

**Issue by sircoko** [artf/grapesjs#2950]
Hi all, I would like to get some guidance about the code I should add/edit in order to change the way panels look. 
In general, I will need to change all the UI styles, but I want to start with blocks, layers, and style managers. 

I want to be able to change the layout, colors, etc in order to make it fit my brand image. 

I tried to read in the issues questions and either the docs. But I feel quite lost withing the names.  
Could anyone help me with this journey?

Thanks in advance

**Comment by Joshmamroud** [comment]
@sircoko Can you provide some code examples of what you have and explain in more detail what you're confused about?

**Comment by sircoko** [comment]
> @sircoko Can you provide some code examples of what you have and explain in more detail what you're confused about?

Well, not code but I can explain my needs quite better with an image...
In a few words, I want to go from here: https://imgur.com/a/3UseHB6

to something like this:  https://imgur.com/Z2B4DR4

**Comment by Joshmamroud** [comment]
> > @sircoko Can you provide some code examples of what you have and explain in more detail what you're confused about?
> 
> Well, not code but I can explain my needs quite better with an image...
> In a few words, I want to go from here: https://imgur.com/a/3UseHB6
> 
> to something like this: https://imgur.com/Z2B4DR4
> 
> As you see, the elements on the panel are placed in a different layout, with different styles, etc.. That's what I need to change

@sircoko To style it this way I believe you'll need to override the default gjs style with your own css.  See [theming guide](https://grapesjs.com/docs/getting-started.html#theming) to help get you started.

For the title I believe you'll need to add a new trait type to make it a textarea. See the [guide in the docs](https://grapesjs.com/docs/modules/Traits.html#define-new-trait-type). 

As far as the order of the traits & styles you can just set up a custom layout as shown in the [getting started guide](https://grapesjs.com/docs/getting-started.html#traits).

Hope this helps!
