### ISSUE TITLE
typography sector not found

### ISSUE THREAD

**Issue by tasham16** [artf/grapesjs#2951]
When using trying to add a font to the style manager, I use the following code:

`const prop = editor.StyleManager.getProperty('typography', 'font-family');
prop.set('options', [
    {value: "'Oswald', sans-serif", name: 'Oswald'},
	...
]);`

However, when I use this inside a plugin (in the index.js) I am creating, I call it with editor.on('load',....) I keep getting 'typography' sector not found. However if I call it outside of the plugin (in the index.html) in the same way, where I am initializing the editor with all the configs, it works. So I was wondering, can we not add new fronts in a plugin so that they are automatically packaged with that plugin? and if not, why? If it is possible, please let me know how I can achieve this.

P.S. Thank you so much for all the time/work you've put in to building this project!

**Comment by tasham16** [comment]
Thank you so much! I will try that out!

**Comment by artf** [comment]
The right way is to wait for the load of the editor
```js
editor.on('load' => {
  const prop = editor.StyleManager...
})
```
