### ISSUE TITLE
BUG: Error when navigating out from Grapes with something selected.

### ISSUE THREAD

**Issue by cartifon** [artf/grapesjs#2953]
Hey @artf,

Steps:
Open Canvas with GrapesJS, select any of the components, then click on `Go to Random`, I get an error that says "Cannot read property 'models' of undefined". 

This only happens if I call the `editor.destroy()` before navigating to a different page. But if I remove the destroy, it works fine... 
Demo: https://stackblitz.com/edit/grapesjs-models

Should I really call the `destroy()`? Will I have any issue on opening GrapesJS multiples times if I don't destroy it?

**Comment by artf** [comment]
Thanks @cartifon should be fixed in the next release

**Comment by Nelida27** [comment]
Hello, 
I have the same problem now that I moved to latest version.
Should I call editor.destroy()?
