### ISSUE TITLE
Add event and getJs for a component

### ISSUE THREAD

**Issue by dat15021999** [artf/grapesjs#2956]
Hi artf,
I'm newbie with this Grapesjs.
How to add event for a component and get the corresponding javascript or jquery ?
Thank all

**Comment by RJCAM** [comment]
Hi @dat15021999 
GrapesJS doesn't have support for javascript code, only html and css.
Although, you can retrieve all js code by running `editor.getJs()` function.

**Comment by Ju99ernaut** [comment]
You can use something like:
```js
const target = editor.getSelected();
const code = target.get('script') || '';
// some logic to view and edit code
targer.set('script', code);
```

To add an event for example you set code to:
```js
const el = this;
el.addEventListener('event', eventHandler);
function eventHandler(e) {
  // handle event
};
```

You can check out [grapesjs-script-editor](https://github.com/Ju99ernaut/grapesjs-script-editor) and [grapesjs-blockly](https://github.com/Ju99ernaut/grapesjs-blockly) plugins.
