### ISSUE TITLE
FEAT: Extending Settings

### ISSUE THREAD

**Issue by papyr** [artf/grapesjs#2959]
Hello, this is really a very very nice tool

Can you share some insights, in the settings, and I can help with adding more so it can be rolled into the Wiki for others.

1. How to how to extend `settings `to allow user to select/switch/change the Graph type, for e.g. `Bar graph`
2. Allow user to _pick a data source for a table_, from a predefined list in a drop down, after dragging onto page.
3. Allow user to checkbox, auto generate ID's, for. e.g. I want to prepend `BudgetPage2-`_AutoIncrementedNumbers_ for the` div ID`

![image](https://user-images.githubusercontent.com/12733414/90340424-165e0300-dfc6-11ea-9387-9562d5b172ab.png)

**Comment by artf** [comment]
You have to extend the `toolbar` property https://grapesjs.com/docs/api/component.html#properties
