### ISSUE TITLE
BUG: The UI for Margin and Padding properties inside the sector

### ISSUE THREAD

**Issue by jayeshmotwani** [artf/grapesjs#2960]
Hello,

I am creating a sector for just margin and padding with the code below:

```
{
	name: 'Layout Settings',
	open: false,
	buildProps: ['margin', 'padding'],
	properties: [
		{
			property: 'margin',
			properties: [
				{name: 'Top', property: 'margin-top'},
				{name: 'Bottom', property: 'margin-bottom'},
				{name: 'Left', property: 'margin-left'},
				{name: 'Right', property: 'margin-right'}
			],
		},
		{
			property: 'padding',
			properties: [
				{name: 'Top', property: 'padding-top'},
				{name: 'Bottom', property: 'padding-bottom'},
				{name: 'Left', property: 'padding-left'},
				{name: 'Right', property: 'padding-right'}
			],
		}
	]
}
```

And the sector is created with Margin Properties as shown in below screenshot:

![Grapes js margin placement](https://user-images.githubusercontent.com/27188013/90367227-2f2ded80-e086-11ea-94dd-4e312728e731.PNG)

As you could see, the properties are placed in the same row. I want them to be displayed as 2 properties only in a row. Please refer the below screenshot for more information:

![Grapes js width and height placement](https://user-images.githubusercontent.com/27188013/90367374-69978a80-e086-11ea-8df0-8f2600674bce.PNG)

Thanks for your help.

**Comment by RJCAM** [comment]
Hi @jayeshmotwani, wich version are you using?
I've just copy/paste your code and it seems working as you expect like in your second image, not the first.
I've also did it in the demo, works fine, the properties are organized with 2 prop in the same row. See below:
![image](https://user-images.githubusercontent.com/49693237/90389536-e3bd1480-e070-11ea-82b8-7b7b46952a04.png)

**Comment by jayeshmotwani** [comment]
Hello @RJCAM,

Thanks for your reply.
I am using version 0.16.18

**Comment by jayeshmotwani** [comment]
Ahhh! I just realized! It is because I increased the size of the panel!
