### ISSUE TITLE
BUG: 

### ISSUE THREAD

**Issue by SintoDema** [artf/grapesjs#2962]
Hi @artf,

**Version:**
grapesjs - 0.16.18
ckeditor - standard - 4.14.1

**Are you able to reproduce the bug from the demo?**
Yes

**What is the expected behavior?**
While applying the inline formatting options from inline CKeditor options, it should reflect in the selected text.

*Describe the bug **detailed***
I have integrated the CKeditor in the grapesJS editor for inline editing purposes. Currently, when I select text to format it, the inline CKeditor options are displaying along with another few options in a black toolbar. I'm confused about that. And the main issue is that even I use any of the inline formatting options, the formatting is not reflecting in the selected text. Can't do anything from the CKeditor inline option like text formatting, list, image uploads, link, etc..

**What is the current behavior?**
The main issue is that even I use any of the inline options, the formatting is not reflecting in the selected text. Can't do anything from the CKeditor inline option like text formatting, list, image uploads, link, etc..

**Plugins used**
grapesjs-lory-slider, grapesjs-tabs, grapesjs-custom-code, grapesjs-touch, grapesjs-parser-postcss, grapesjs-tooltip, grapesjs-tui-image-editor, grapesjs-typed, grapesjs-style-bg, gjs-preset-webpage, grapesjs-plugin-forms, gjs-component-countdown, gjs-plugin-ckeditor.

**Are you able to attach screenshots, screencasts or a live demo?**
Yes, here is a [demo link](https://jsfiddle.net/Sinto990/nog0b3u6/) and screenshot [from demo](https://drive.google.com/file/d/1b1w5SQvlFpcDwuxHzFIZe7gPPvN9ZZxH/view?usp=sharing), another from [my work](https://drive.google.com/file/d/1BL6-DW4HTZ0ZoITmnz19uyJt3Labx1l5/view?usp=sharing)

**Comment by mcottret** [comment]
Hi @SintoDema !

The [GrapesJS CKEditor plugin](https://github.com/artf/grapesjs-plugin-ckeditor) already registers CKEditor as a custom RTE, so calling `editor.setCustomRte` is actually setting it up **twice**, which I believe causes those problems.

Remove the `editor.setCustomRte` block & it should work as expected. If you want to provide CKEditor options, this should be done at the `pluginOpts` level as shown [here](https://github.com/artf/grapesjs-plugin-ckeditor#readme).

Cheers !

**Comment by SintoDema** [comment]
Hi @mcottret,

I have already tried that earlier & as your suggestion again I have removed that section from my application. Now, there is no formatting options tab. I do not have given any restrictions(```pluginsOpts```) in CKEditor option, just loaded the CDN files & its plugin name in GrapesJS plugin in section. Also, after removing ```editor.setCustomRte``` block, I'm getting another error as:

```
ckeditor.js:270 Uncaught Error: [CKEDITOR.resourceManager.load] Resource name "sharedspace" was not found at "https://cdn.ckeditor.com/4.14.1/standard/plugins/sharedspace/plugin.js?t=K5H9".
    at CKEDITOR.resourceManager.<anonymous> (ckeditor.js:270)
    at e (ckeditor.js:265)
    at Array.x (ckeditor.js:265)
    at w (ckeditor.js:265)
    at HTMLScriptElement.CKEDITOR.env.ie.e.$.onerror (ckeditor.js:266)
```

**Are you able to reproduce the bug from the demo(after removing ```editor.setCustomRte``` block, you can try that)?**
Yes

Here is a [screenshot from the demo](https://drive.google.com/file/d/1kh354lpWV-w6Ir82NWKNDIWHRFQv8G8Z/view?usp=sharing)

**Comment by mcottret** [comment]
@SintoDema,

I believe the [GrapesJS CKEditor plugin](https://github.com/artf/grapesjs-plugin-ckeditor) is dependent on the [Standard-All CKEditor version](https://cdn.ckeditor.com/4.14.1/standard-all/ckeditor.js), but your JSFiddle includes the [Standard CKEditor version](https://cdn.ckeditor.com/4.14.1/standard/ckeditor.js), which explains the missing plugin error. Including https://cdn.ckeditor.com/4.14.1/standard-all/ckeditor.js instead of https://cdn.ckeditor.com/4.14.1/standard/ckeditor.js should fix this.

Regarding formatting options, I suggest you to read the [CKEditor `toolbar` configuration documentation](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-toolbar). But see the following if you'd like an example `pluginOpts` configuration:

```json
{
   "pluginsOpts": {
      "grapesjs-plugin-ckeditor": {
         "options": {
            "language": "en-gb",
            "extraPlugins": "sourcedialog,justify,showblocks,colorbutton",
            "removeButtons": "",
            "format_tags": "p;h1;h2;h3;h4;h5;h6;pre",
            "toolbar": [
               [
                  "Format",
                  "-",
                  "Bold",
                  "Italic",
                  "Strike",
                  "Underline",
                  "Subscript",
                  "Superscript",
                  "RemoveFormat",
                  "-",
                  "NumberedList",
                  "BulletedList",
                  "-",
                  "Outdent",
                  "Indent",
                  "-",
                  "JustifyLeft",
                  "JustifyCenter",
                  "JustifyRight",
                  "JustifyBlock",
                  "-",
                  "Link",
                  "Unlink",
                  "Anchor",
                  "TextColor",
                  "BGColor",
                  "-",
                  "ShowBlocks",
                  "-",
                  "Image",
                  "Table",
                  "-",
                  "Sourcedialog"
               ]
            ]
         }
      }
   }
}
```

**Comment by SintoDema** [comment]
Hi @mcottret,

That was a very helpful reply. It fixed the whole issues related to the inline formatting.

Thank you.
