### ISSUE TITLE
Traits are not created by default if not requested, indeed I'm doing this in the demo https://github.com/artf/grapesjs/blob/gh-pages/demo.html#L1407-L1408

### ISSUE THREAD

**Issue by Nikesh-hub** [artf/grapesjs#2964]
Traits are not created by default if not requested, indeed I'm doing this in the demo https://github.com/artf/grapesjs/blob/gh-pages/demo.html#L1407-L1408

_Originally posted by @artf in https://github.com/artf/grapesjs/issues/1627#issuecomment-445216188_

Hello artf 
can you please give here proper example how we can request for Traits

**Comment by Ju99ernaut** [comment]
```js
const openTmBtn =  editor.Panels.getButton('views', 'open-tm');
openTmBtn && openTmBtn.set('active', 1);
```
