### ISSUE TITLE
FEAT: Plugin Names

### ISSUE THREAD

**Issue by gunslingor** [artf/grapesjs#2965]
Request that I be allowed to refer to plugins by two conventions: "grapesjs-lory-slider" and "grapesjsLorySlider".

I'm using a Kotlin JS DSL and it can't handle the dashes; also typically dashes are reserved for css class names and should be minimized in JS... though I suspect there is a class by that name, it should probably be decoupled from the JS object names to avoid confusion and _help_ prevent unknown issues.

**Comment by gunslingor** [comment]
I did find a solution this["grapesjs-lory-slider"], still recommended addition.

**Comment by artf** [comment]
Honestly, I don't see any advantage in having 2 conventions. The name with dashes is generated by Webpack UMD bundler (eg. using grapesjs-cli) which is taken from the package.json `name`.
If we'll get more requests from the community and a proposed solution, I might reopen it.
