### ISSUE TITLE
Adding columns does not work on very simple example

### ISSUE THREAD

**Issue by SchneiderSIT** [artf/grapesjs#297]
I am evaluating GrapesJS, which seems to really great.
I installed the core library and added blocks-basic. 

Now I am using the following code snippet and try things out:

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="dist/css/grapes.min.css">
</head>
<body>
<div id="gjs"></div>
</body>
<script src="http://code.jquery.com/jquery-2.2.0.min.js"></script>
<script src="dist/grapes.min.js"></script>
<script src="node_modules/grapesjs-blocks-basic/dist/grapesjs-blocks-basic.min.js"></script>
<script type="text/javascript">
  var editor = grapesjs.init({
      fromElement: 1,
      container : '#gjs',
      // components: '',
      style: '.txt-red{color: red}',
      plugins: ['gjs-blocks-basic']
  });
</script>
</html>
```

Everything works fine so far, but I cannot add one of the column blocks. Nothing happens and there is no error or anything to see on the browser's console.

Update: Using current version of Chrome on the Mac. 

Am I doing sth. wrong or is it a bug?

**Comment by artf** [comment]
Which version of grapesjs do you use? It's happening only with column blocks? Are you able to see the green dragging helper?
Not sure, but try also with another version of jquery (eg. https://code.jquery.com/jquery-3.2.1.min.js)

**Comment by SchneiderSIT** [comment]
I installed GrapesJS yesterday over npm. So it is 0.10.4 and 0.1.1 for blocks basic. And yes, the green line appears. I can see a console log, when I drop a block where it is not droppable. But when it should work, nothing happens. I will try out another jQuery version. Just copy + pasted the version I am using from your examples. Thank you!

**Comment by artf** [comment]
I was thinking if it might be an issue with styles, can you check in Layers (or even via inspector) if components are actually added to the structure. What about other blocks?

**Comment by SchneiderSIT** [comment]
I just uploaded my trial code to http://brokenlande.de/grapesjs/ - and now it works. No changes at all. I swear. Must be something on my local development server (using ubuntu vm with PHP7). 

To answer your question: I can see changes on the DOM in the inspector when dropping on my local development env. So yes, I am thinking of (local) stylesheet problems as well.

Sorry for that issue. Can be closed as invalid. But thanks for your attention!

**Comment by VM8198** [comment]
@SchneiderSIT  I am facing same problem...
can you suggest anything ?
