### ISSUE TITLE
BUG: Minor issue in webpage demo Tooltip

### ISSUE THREAD

**Issue by gunslingor** [artf/grapesjs#2971]
webpage demo

Summary: ` el.setAttribute('title', '');` fails for view panel buttons only (not options panel buttons).

Symptom: You can see the mouse over on the view buttons, they all start with "Open yada yada", the word open should be removed per the array (e.g. ['open-sm', 'Style Manager']).

Cause: Suspect something isn't happening in the right order, probably due to the presets again.

would be nice if orderings were inherently taken care of with a preset =).

**Comment by artf** [comment]
Can elaborate better on how to reproduce the issue, please?

**Comment by gunslingor** [comment]
- Go here: https://grapesjs.com/demo.html
- Hover over any view icons, notice the tooltip starts with Open
- If you look a the javascript, in the same area you set the other tooltips your changing these as well to show the name without the word "Open"; I tried to change them to random things but it never took. Not sure if its a preset issue.

Maybe not a big deal since I hope to start making my own plugins soon. I'm just diving deep into grapejs so figured you might wanna know.

**Comment by artf** [comment]
Those tooltips are made for the demo purpose, this has nothing to do with the core library... 
Anyway, the value shown is taken from `data-tooltip` and not `title`.
