### ISSUE TITLE
make not removable elements inside a block

### ISSUE THREAD

**Issue by trony2020** [artf/grapesjs#2973]
Hello,
Given:

 editor.BlockManager.add('test-component', {
			      id: 'MappaPiuDescrizione',
				  label: 'Mappa + Descrizione',
				  content: `<div data-blockname='mappaDescrizione1'>
					  			  <br/>
							          <div data-blockname='mappaDescrizione2' style='margin:2px;border: 1px solid red'>
								  			<div><h3>Test Moto</h3></div>
										    <div data-gjs-type="map" style='height:200px;width:400px'></div> 
										    <div>Test Zaltbommel<br>
											     Schimminck 4<br>
											     5322 Daltbommel <br>
											     Netherlands
											</div>
								      </div>	
							      <br/>
						  </div>`,
 });

I want to make `<div><h3>Test Moto</h3></div>` not droppable, how it's done? With a class ? Like 
 `<div class='notDropppable'><h3>Test Moto</h3></div>` ?

thanks,
Walter

**Comment by RJCAM** [comment]
Hi @trony2020 
Not really a class, but you can do it adding some attributes indeed, like [here](https://grapesjs.com/docs/api/components.html#addcomponent) in the documentation, when you add a new component to the DOM, it adds the property as an attribute of the added element.
```
// Example of a new component with some extra property
var comp1 = domComponents.addComponent({
  tagName: 'div',
  removable: false, // Can't remove it
  draggable: false, // Can't move it
  copyable: false, // Disable copy/past
  droppable: false, // Can't add elements inside
  content: 'Content text', // Text inside component
  style: { color: 'red'},
  attributes: { title: 'here' }
});
```
So you can do something like this:
`<div data-gjs-dropppable='false'><h3>Test Moto</h3></div>`
Now you wont be able to add inside this div

**Comment by trony2020** [comment]
I've tried with


editor.BlockManager.add('Title-component', {
					      id: 'TitleEB',
						  label: 'TitleEB',
						  content: `"<div data-blockname='TitleForm' style='width:600px' data-gjs-removable='false'>" + data + "</div>"`							  		 
						});	

where data is: 

`<div id="headerText" class="info " data-ebplatform-template-elementId="boxHeader" data-ebplatform-template-role="borderedBox">
		<h3><span data-eventname="true" data-gjs-removable="false">ititiit</span></h3>
		<h4 data-gjs-removable="false" aa="test">
			<span class="eventDate long"><span class="date"><span>Monday, August 31, 2020</span></span> <span class="time"><span>from 11:00 AM to 3:45 PM</span></span></span>
		</h4>
	</div>	
`

but after rendereing data-gjs-removable="false" disappeared, why? 

![image](https://user-images.githubusercontent.com/57098736/91301525-5cc11800-e7a5-11ea-94da-b122099677c8.png)

thanks!

**Comment by RJCAM** [comment]
> but after rendereing data-gjs-removable="false" disappeared, why?

Sorry, I've never searched why hahah, but is working right? It doesn't need to be displayed like `droppable` property
You can see when you select the element that the trash icon is no longer visible 
![image](https://user-images.githubusercontent.com/49693237/91310344-e74f4a80-e798-11ea-9ac7-a60f48642c5b.png)
This behavior will be the same in some other properties :grin:

**Comment by trony2020** [comment]
Yes working.

Another question:
      if I delete all chars in a box then the box disappear, is there a way to not delete the box and keep a min-width?

thanks!

**Comment by trony2020** [comment]
How to tell elements inside h4 are data-gjs-editable="false" also?

<h4 data-gjs-removable="false" data-fieldname="dateEventoString" data-gjs-editable="false">
    ...
</h4>

thanks, Walter

**Comment by trony2020** [comment]
Why a single text 

"Monday, August 31, 2020 from 11:00 AM to 4:45 PM Tuesday, September 1, 2020 from 10:30 AM to 11:15 AM"

is splitted in many <span>s creating a lot of edit boxes? How to avoid that?
 
![image](https://user-images.githubusercontent.com/57098736/91325075-0fec3a00-e7c3-11ea-9b4d-8f9ea91d812e.png)

**Comment by RJCAM** [comment]
So, I'm not sure if this are the best answers but they work for me.

> How to tell elements inside h4 are data-gjs-editable="false" also?

With this attribute: contentEditable="false"

> if I delete all chars in a box then the box disappear, is there a way to not delete the box and keep a min-width?

I'm doing this but the box still remains when removed all chars, try some attributes when creating it like contentEditable

> Why a single text...

I'm not able to reproduce this behavior, the text is added as a unique string, perhaps can be the way your declaring it

**Comment by artf** [comment]
`data-gjs-*` are attributes related to GrapesJS components, so once created, there is no point to keep them on the element

**Comment by trony2020** [comment]
> `data-gjs-*` are attributes related to GrapesJS components, so once created, there is no point to keep them on the element

I'm passing data-gjs-* directly in content:"...." in editor.BlockManager.add many times because we need to exclude some elements to modification and some others not, so it's useful to return them in the getHml(), or there is another way to do that in the passed "content:...html..."?

Also will be useful to us: exclude all editing in children elements but enable it in some children elements: 

<div data-gjs-editable=false >

    <div>...</div> 
... <div data-gjs-editable=true >
    </div>

</div>

Is there a way to do this?

thanks,
Walter

**Comment by artf** [comment]
> I'm passing data-gjs-* directly in content:"...." in editor.BlockManager.add many times because we need to exclude some elements to modification and some others not, so it's useful to return them in the getHml(), or there is another way to do that in the passed "content:...html..."?

If you're reusing the same HTML after the edit, you're doing it wrong, you should always rely on the JSON structure.

> Also will be useful to us: exclude all editing in children elements but enable it in some children elements:

Try to check if [`propagate` property](https://grapesjs.com/docs/api/component.html#properties) might be useful in your case, otherwise use `data-gjs-editable` only on not editable elements

**Comment by trony2020** [comment]
> If you're reusing the same HTML after the edit, you're doing it wrong, you should always rely on the JSON structure.

How to use it properly, link with example?

**Comment by trony2020** [comment]
> Try to check if [`propagate` property](https://grapesjs.com/docs/api/component.html#properties) might be useful in your case, otherwise use `data-gjs-editable` only on not editable elements

Hi, doing:

$.get( "/iscrizionePrivacy.plp?a=VGsflaU2d7D0sUcDhl7lCkkX8tE1UW9kBzLcqcUAR_8-yKo74nLUmyXKrfIUst_kUirvlSC_A5sqeHrBsznmUg&locale=it_IT&fromBE=true", function( data ) {					  
					    editor.BlockManager.add('Privacy-component', {
					      id: 'PrivacyEB',
						  label: 'PrivacyEB',
						  editable: false,
						  propagate: ['editable', 'removable', 'draggable'],
						 ` content: "<div data-blockname='PrivacyForm' class='eb-block' style='width:600px'>" + data + "</div>"` });	
	   $("#success5").html("Load plp Privacy was performed.");
  });

Doesn't works. all elements inside are editable, we have complex boxes with a lot of html, we need to propagate "not editable" (or removable,...) and then specity editable in a few children that are eligible to be edited.

thanks.

**Comment by artf** [comment]
You should use it on the Component properties, not the Block one
