### ISSUE TITLE
GrapesJS deletes html attributes 

### ISSUE THREAD

**Issue by trony2020** [artf/grapesjs#2981]
Hello I start from:

`<table style="width:100%;height:100%" border="1" data-template="true">`
    ...  
 `<h4 data-fieldname="dateEventoString" data-gjs-editable="false" data-gjs-removable="false" >`
         .... 
   `</h4>`
...
`</table>`
 

but when i do editor.getHtml() the returned html is missing some original attributes !
Here the returned html:
  
`<table border="1" data-template="true" id="i8wv">`
    ...
                  `<h4 data-fieldname="dateEventoString">`
                    ... 
                  `</h4>`
             ...
`</table>`

I need that GrapesJS leave attributes unchanged, is that possible?

thanks, 
Walter

**Comment by artf** [comment]
https://github.com/artf/grapesjs/issues/2973#issuecomment-682264998
