### ISSUE TITLE
BUG: Executing editor.load(x) on x = editor.store() results in error.

### ISSUE THREAD

**Issue by mitcht** [artf/grapesjs#2982]
**Version:**
0.16.18

**Are you able to reproduce the bug from the demo?**
[X ] Yes
[ ] No

**What is the expected behavior?**
I would expect that assets, components, css, html, and styles would be repopulated.

*Describe the bug **detailed***
I am working on an existing system that has a database schema preventing me from using the StorageManager built into grapesjs.  I am attempting to store the current state of the GrapesJS editor into a javascript variable, and then reload it - using editor.store() and editor.load() respectively.  According to the documentation, these features are listed as part of the editor, not the storage manager (https://grapesjs.com/docs/api/editor.html#store) and would be expected to compliment each other.

**What is the current behavior?**
var x = editor.store();
editor.load(x);

This results in an error.  I would expect to just reload the current data.

**Are you able to attach screenshots, screencasts or a live demo?**

[X ] Yes (attach)
[ ] No

![image](https://user-images.githubusercontent.com/750330/91580354-f4944280-e91a-11ea-869c-dba8a24312f1.png)

**Comment by mitcht** [comment]
Yes, I see that `.load` takes a callback function.  I'll admit, I'm probably doing this wrong.  I only started using grapesJS a few days ago.

**Comment by mitcht** [comment]
I'm investigating https://grapesjs.com/docs/modules/Storage.html#storage-api but I still would like to just be able to 'set and forget' :)

**Comment by artf** [comment]
There is an example which illustrates exactly what you're looking for https://grapesjs.com/docs/modules/Storage.html#define-new-storage
