### ISSUE TITLE
BUG: Addframe method not working with the component props

### ISSUE THREAD

**Issue by FlowingCloudRTL** [artf/grapesjs#2986]
**Version:**
"0.16.18"

**Are you able to reproduce the bug from the demo?**

[ X] Yes
[ ] No

Steps to reproduce the bug in web builder demo:
Open the demo and the console, enter 
`editor.Canvas.addFrame({
name: 'Mobile home page',
x: 100, // Position in canvas
y: 100,
width: 500, // Frame dimensions
height: 600,
// device: 'DEVICE-ID',
components: [
'<h1 class="testh">Title frame</h1>',
'<p class="testp">Paragraph frame</p>',
],
styles: `
.testh { color: red; }
.testp { color: blue; }
`,
});`

Expected Result:
An iframe is created with the appropriate components

Bug: 
![image](https://user-images.githubusercontent.com/49292515/91671007-daac5880-eaf0-11ea-8683-34667261804c.png)

It seems that the issue is just the component part, if you take it out the iframe will be created just fine. However I currently am not sure how to create components in the generated iframe in other ways.

**Comment by artf** [comment]
Thanks @FlowingCloudRTL for the report but the multi-frame feature is still far from being complete so I'm not surprised about the issues. If anyone is interested in bringing this feature further, please let me know
