### ISSUE TITLE
How to append button in custom div

### ISSUE THREAD

**Issue by Abhisheknanda1344463** [artf/grapesjs#2989]
Hi @artf Is there any way to append all the defaults buttons of grapesjs in custom div like the same way we are append the style manager.
here 
[https://codepen.io/artf/pen/MQpZPj](url)
Thanks

**Comment by artf** [comment]
As you can see from the example, you can specify the Panel target via `el: '#'` option, which then should be able to contain your buttons

**Comment by Abhisheknanda1344463** [comment]
Hi @artf  Could you please confirm this-way `    panels: {
      id: 'options',
      el: '.panel__basic-actions'}`
I tried this is not working 
or do i need to create new button again for my new panel?
