### ISSUE TITLE
Autosave on keyup

### ISSUE THREAD

**Issue by vmourya** [artf/grapesjs#299]
Hi,

Currently Autosave is working on element focus Out, i want it to autosave on keyup as well.

TIA.

**Comment by artf** [comment]
At the moment it's not possible if not extending the built-in [TextComponent](https://github.com/artf/grapesjs/blob/dev/src/dom_components/view/ComponentTextView.js) with your [custom one](https://github.com/artf/grapesjs/wiki/Components)
