### ISSUE TITLE
Editor.getSelected() giving me undefined.

### ISSUE THREAD

**Issue by Abhisheknanda1344463** [artf/grapesjs#2991]
Hi @artf  I want to append dynamic pages to the specific link trait.
Here is what i am using.
`const component = editor.getSelected();
component.getTrait('link').set('options', [
  { value: 'opt1', name: 'New option 1'},
  { value: 'opt2', name: 'New option 2'},
]);
`
This is giving  component is undefined in the console because by default not any element is selected 
Could you please guide me on this . I want to append that pages in list of link trait whenever i click on the link

**Comment by Ju99ernaut** [comment]
You can add that to each component type using:
```js
const components = editor.Components.getTypes();
components.forEach(component => {
    //manipulate traits here...
});
```

**Comment by Abhisheknanda1344463** [comment]
@Ju99ernaut  I want to update trait for link only
I made my custom component in the plugin that plugin i m using  in the My other application.
So I want to update the trait of type("href") which is select list
I tried to update list but on edit mode it'll not reflected on the editor.
Then I've used this which is mentioned in docs 
`const component = editor.getSelected(); component.getTrait('link').set('options', [ { value: 'opt1', name: 'New option 1'}, { value: 'opt2', name: 'New option 2'}, ]);`
It gives me undefined.

Could you please help me out.
Thanks

**Comment by Ju99ernaut** [comment]
Oh, try running your logic when a component is selected only

```js
editor.on('component:selected', component => {
   // run your logic here...
});
```

**Comment by Abhisheknanda1344463** [comment]
Thanks @Ju99ernaut  It Works like a charm.
Here What I did 
`    editor.on('component:selected', component => {
    	component.getTrait('href').set('options', data.list);
    });`
But one problem is that whenever I click on other component from canvas it give me error in the console
Uncaught TypeError: component.getTrait(...) is undefined

Because getTrait is only work for linkComponent.So,How could i achieve this for link only.
Could you please guide me here.
Thanks

**Comment by Ju99ernaut** [comment]
You can check if `component.getTrait('href')` gets anything first:

```js
editor.on('component:selected', component => {
   component.getTrait('href') && component.getTrait('href').set('options', data.list);
});
```

**Comment by Abhisheknanda1344463** [comment]
Hi @Ju99ernaut  I need your help.
I want to make my custom block of light box.
Could you please help me out

**Comment by Ju99ernaut** [comment]
How can I help?

**Comment by Abhisheknanda1344463** [comment]
Hi @Ju99ernaut  Can we talk on skype or other platform.
So that i can explain you the things?
