### ISSUE TITLE
QUESTION: Float Left/right removes the component from the container

### ISSUE THREAD

**Issue by jayeshmotwani** [artf/grapesjs#2995]
I have observed that whenever I align a component left or right (float left or float right), that component comes out of the parent container, however If I make it to 'None' it comes back inside the container in it's last position. I found this on live demo too.

Refer the attached screenshots
![Grapes JS Before alignment](https://user-images.githubusercontent.com/27188013/92104326-c7560180-edfe-11ea-96b5-20c8f0928a37.png)

![Grapes JS After alignment](https://user-images.githubusercontent.com/27188013/92104317-c3c27a80-edfe-11ea-9150-e3ec3b21af32.png)

Could you please let me know why it happens like this?

Thanks for your help.

**Comment by Ju99ernaut** [comment]
The float property collapses the parent div. You can use [this](https://css-tricks.com/all-about-floats/) for reference.

**Comment by artf** [comment]
Yeah, unfortunately, that is how weird the float works, so if you're creating a builder for non-tech people avoid that property 😬
