### ISSUE TITLE
Cannot read property 'mediaText' of undefined

### ISSUE THREAD

**Issue by tverney** [artf/grapesjs#300]
Hi everyone,

I`m trying to use grapejs in an angular project that have an web builder inside. We are loading templates from html + css, but, when loading in grapejs, it`s having this problem: "Cannot read property 'mediaText' of undefined". It`s something related to CSS, but I don`t know how to solve it.
 
Any idea?

**Comment by artf** [comment]
Probably due to `@keyframes` (or some other CSS instance with `node.cssRules` property), if it is the case, please close this issue and subscribe here #276

**Comment by tverney** [comment]
@artf We will check it out and if its, close the issue. Thanks!

**Comment by artf** [comment]
any update Thiago?

**Comment by tverney** [comment]
@artf Thanks for reply. I found an workaround loading the css from an external stylesheet, like uploading in cloudfront. That solved the issue.

**Comment by Owchzzz** [comment]
any update on this? Im having the same problem as well. and moving to an external stylesheet just isnt going to be possible

**Comment by tverney** [comment]
@Owchzzz I made a workaround in the project by adding the extra CSS by an CDN in head. But the problem still, for me, it`s not related with @keyframes.

**Comment by ivanezeigbo** [comment]
@tverney please share code on how you made the addition with CDN. Would it work for a user trying to import their code by pasting it? I am trying to get a workaround with the @keyframes problem given that there are some bugs with the recent releases (hopefully to be corrected in the next release) that makes me it easier for me to stick with older versions for now. The keyframes issue is just the holdback.
