### ISSUE TITLE
How to remove a style rule of CssCompoer?

### ISSUE THREAD

**Issue by alemenciones** [artf/grapesjs#3000]
Hi man, im trying to remove a style-rule, some antithesis of CssComposer.setRule(".selector") ?

Thanks you very much!

**Comment by longdoan7421** [comment]
Unfortunately, GrapesJS does not have any built-in function like `CssComposer.removeRule`. 

However, you could do that with a workaround like this:
* Get all rules by using `CssComposer.getAll()`, it will return you a Backbone Collection of all rules.
* I assume that you have the rule model which should be removed, you can use method `remove` of Backbone Collection to remove it.

```javascript
const ruleModel = /* the model of rule which you want to remove */;
const allRules = editor.CssComposer.getAll();
allRules.remove(ruleModel);
```

* If you don't already have rule model, you first need to get the model of selector. Then, you could use method `filter` of Backbone Collection to find the rules. Finally, `remove` it `.

```javascript
function removeRule(willBeRemoveSelector) {
  const willBeRemoveSelectorModel = editor.SelectorManager.get(willBeRemoveSelector);
  const allRules = editor.CssComposer.getAll();
  const willBeRemoveRules = allRules.filter(rule =>
    return rule.get('selectors').has(willBeRemoveSelectorModel)
  });
  allRules.remove(willBeRemoveRules);
}

removeRule('.some-class')
```

**Comment by artf** [comment]
@longdoan7421 is correct but in the second solution I'd use [`CssComposer.getRule`](https://grapesjs.com/docs/api/css_composer.html#getrule) directly
```js
  const willBeRemoveRules = editor.CssComposer.getRule(willBeRemoveSelector);
```
