### ISSUE TITLE
BUG: CSS Properties are not correctly loaded if style manager panel is not active at initialization

### ISSUE THREAD

**Issue by jcamejo** [artf/grapesjs#3002]
Hi @artf!

Let me describe the issue

**Version:**

16.22

**What is the expected behavior?**
The css property  values and visibility settings should take the correct configuration
*Describe the bug **detailed***
If the style manager is not  active on editor load, when you click on an element and open the style properties, they are not updated.

**Steps to reproduce**

1 - Make the style manager panel view not active by default
2 - Make any css property in a component unstylable,  In this example, the text component css 'display' property is unstylable
3 - When you click and open the styles view of the component, the display property is present
<img width="1305" alt="image" src="https://user-images.githubusercontent.com/1976679/92250339-a4ddea00-eecb-11ea-8178-a7980db90642.png">
4 - Click on any other component and go back to the style settings of the text, the display will not be visible.
<img width="727" alt="image" src="https://user-images.githubusercontent.com/1976679/92250476-d060d480-eecb-11ea-8fd2-47b425361c61.png">

This is related to the propertyView method **targetUpdated** not being fired the first time the style manager loads if its panel is not active  at the initialization process, I've tried to find a fix for this but i need some guidance here.

This not only affects the visibility but also the values are not correctly displayed.

Let me know what you think,

Thanks!

**Comment by artf** [comment]
I guess we have to call [`checkVisibility `](https://github.com/artf/grapesjs/blob/43dc05ffecabdb69f880f163f35b033222a7482a/src/style_manager/view/PropertyView.js#L266) also in render (probably before onRender call)

**Comment by artf** [comment]
I'm closing this one as I'd expect this to be fixed from v0.18.*
