### ISSUE TITLE
QUESTION : custom style properties to change class

### ISSUE THREAD

**Issue by Bakino** [artf/grapesjs#3004]
Hi, 

Thanks for this good editor.

In my project, I want to adjust classes of components using the style manager. For example, I am using bootstrap and I want the user to be able to apply classes such as bg-danger, bg-primary from a drop box instead of input the class name manually.

I am aware that I can do it using trait (and it works well) but it is more consistent that styling control goes in the style manager part (and also it is too much option to put in the traits part)

I saw that it is possible to add custom type in the style manager but it always to update a single CSS property. Is it possible to use this custom types to update class attribute of the component ?

**Comment by artf** [comment]
There is an option which allows you to indicate which target to select (classes or component-specific style)
https://github.com/artf/grapesjs/pull/2474 (in your case `componentFirst` should be disabled)
Unfortunately, the selector manager's UI itself it's not easily customizable but I think you should be able to create one from scratch by relying on [events and API](https://grapesjs.com/docs/api/editor.html)

**Comment by Bakino** [comment]
thanks for your answer :)
