### ISSUE TITLE
BUG: I am not able to drag and drop a component outside form getting a warning.

### ISSUE THREAD

**Issue by KishanRavindran** [artf/grapesjs#3007]
## WARNING
**Version:**
0.16.22

**Are you able to reproduce the bug from the demo?**

[1 ] Yes
[ ] No

Not able to drag and drop the input or textbox or select from the forms block

Whenever I drag and drop an input component I am getting the below

![image](https://user-images.githubusercontent.com/22557988/92380658-3301dc80-f127-11ea-98b8-925c7d16b2e4.png)

When I try to drag and drop an input or any component except a form the drag and drop is not working I checked the same in the grapesjs demo link and I am able to relicate it. Can someone guide me on this.

https://grapesjs.com/demo.html

**Are you able to attach screenshots, screencasts or a live demo?**
![image](https://user-images.githubusercontent.com/22557988/92380938-9429b000-f127-11ea-8790-99c778dd7a59.png)

[1 ] Yes (attach)
[ ] No

**Comment by RJCAM** [comment]
Hi @KishanRavindran that's not a bug, it's the default behavior of the editor.
Check this issues #2812 and #2180 to see more info.
