### ISSUE TITLE
Center a Div and resizable borders

### ISSUE THREAD

**Issue by trony2020** [artf/grapesjs#3008]
1) How to center a div inside a div in the Layer Manager?
What button i must use?

2) How to make appear the resizable borders for a block?

thanks!

**Comment by artf** [comment]
> How to center a div inside a div in the Layer Manager?

What do you mean?? which div?

> How to make appear the resizable borders for a block?

A block or a component?

**Comment by trony2020** [comment]
Hi,

>What do you mean?? which div?

Inside a Block we have many div nested or not, selecting one div and press some button to center it in the father div

>A block or a component?

Block

**Comment by artf** [comment]
Please, read the documentation first https://grapesjs.com/docs
Avoid mixing terminologies like blocks/layers because from my point of view what I'm reading doesn't make any sense

**Comment by trony2020** [comment]
1) The documentation is missing examples, where are examples?
2) And then why you closed the issue? I've not received real help.

Thanks.
