### ISSUE TITLE
Asset Manager Configuration Is not Working

### ISSUE THREAD

**Issue by vijayshukla30** [artf/grapesjs#3010]
Hi,
I tried all possible ways to change asset manager configuration, but it is not working as expected.
Even I create a sample plugin but it does not seem to work.
Basically I want to upload the file on my server, I gave the URL but it not sending any request on the server.

I then override **uploadFile**, it works to send data on the server and receive a response in the same format which was is documentation but from there I have to use **editor.AssetManager** but the editor is null until we create it's instance. 

https://github.com/artf/grapesjs/issues/216#issuecomment-321051380
https://github.com/artf/grapesjs/issues/1581
<img width="1210" alt="Screenshot 2020-09-08 at 9 25 18 AM" src="https://user-images.githubusercontent.com/11537372/92431974-75262f00-f1b6-11ea-84b4-ba465818e3a6.png">

**Comment by artf** [comment]
You have to use the [I18n module](https://grapesjs.com/docs/modules/I18n.html) to update [those labels](https://github.com/artf/grapesjs/blob/43dc05ffecabdb69f880f163f35b033222a7482a/src/i18n/locale/en.js#L4-L9)

**Comment by vijayshukla30** [comment]
@artf This is not only about label.
I gave my API URL in upload but not able to receive any call on the API, neither didn't see any in the network.

**Comment by vijayshukla30** [comment]
I tried to disable upload but not working.
<img width="1384" alt="Screenshot 2020-09-15 at 12 48 57 PM" src="https://user-images.githubusercontent.com/11537372/93178562-0a469c00-f752-11ea-89ce-ed1b2a9ac33c.png">

**Comment by christosapos** [comment]
New assetManager configuration  does not work when we want to edit addButton label.
