### ISSUE TITLE
Customize result from image drag'n'drop desktop

### ISSUE THREAD

**Issue by jcze91** [artf/grapesjs#3011]
Hello,

I'm using GrapesJs with the MJML plugin and when I drag'n'drop an image from my desktop, the dropped result on the wrapper is an "image" component.
But in my case I would like that the dropped result is directly a "mj-image" component.

I saw the result from the drag data transfer is computed in this method  from the Droppable utils class : https://github.com/artf/grapesjs/blob/ea2f7954937c2306b284e09cf08c6e7bffb9309c/src/utils/Droppable.js#L151

Is there a way to extend this method via a new plugin ?

Thanks

**Comment by artf** [comment]
Check this one https://github.com/artf/grapesjs/issues/2472#issuecomment-570228050
