### ISSUE TITLE
BUG: HTML exported from the demo not responsive to screen size

### ISSUE THREAD

**Issue by chongma** [artf/grapesjs#3015]
**Version:**
0.16.22

**Are you able to reproduce the bug from the demo?**
[*] Yes
[ ] No

**What is the expected behavior?**
the exported html should be responsive

*Describe the bug **detailed***
1. click </> view code at the top of the demo, and then click the "Export to ZIP"
2. unzip the file and click index.html
3. resize the window using the chrome developer tools (e.g. iPhone 6/7/8).  refresh the window

**What is the current behavior?**
html should be resized responsively to fit screen size but it seems not to be.  it seems too small for smaller screen size
also images are not exported

**Are you able to attach screenshots, screencasts or a live demo?**

[*] Yes (attach)
[ ] No

![Screenshot from 2020-09-10 20-36-49](https://user-images.githubusercontent.com/6253322/92782782-8aad7b80-f3a5-11ea-86a2-60086f974ba4.png)

**Comment by artf** [comment]
Well for sure the export plugin could be configured better but for sure it's not the core issue and not even the real purpose of the demo

**Comment by chongma** [comment]
This is my first time using grapes.  If the template resizes well in the grapes editor but I can't export the html then how to use the template?
