### ISSUE TITLE
FEAT: secondary block manager

### ISSUE THREAD

**Issue by adamtang79** [artf/grapesjs#3016]
Currently there is only 1 block manager.

I wish to move the blocks to the left of canvas.

Where I can drag and drop the block from the left and see the style on the right.

I will be able to add more new kind of manager either left or right.

Are they any example to do this?

**Comment by adamtang79** [comment]
is this the correct way?

https://codepen.io/artf/pen/MQpZPj

**Comment by artf** [comment]
> is this the correct way?

Correct
