### ISSUE TITLE
FEAT: Extending or Override Library

### ISSUE THREAD

**Issue by adamtang79** [artf/grapesjs#3017]
Said I want to override BlockManager inside my plugin project. Currently I have to fork the grapesjs, create branch and modify BlockManager codes. Some changes are not related to grapesjs, so I have to build my branch and refer it from my plugin.

It possible for me to override BlockManager inside my plugin project eg. src/block_manager so that when my other project html refer to my plugin .min.js it is using my plugin's block_manager instead of grapesjs'?

**Comment by artf** [comment]
What exactly you'd like to override?

**Comment by artf** [comment]
yeah, I got it.....
Let's try again, what EXACTLY you'd like to override?

**Comment by adamtang79** [comment]
Good morning from here. Thanks for your replies and wonderful project. There are some classes we wish to override such as changing variable value, adding function or changing function behavior. I'm currently using fork and branch to do it. Is it possible to override at plug in level?

**Comment by artf** [comment]
For sure not a priority but I might evaluate a PR

**Comment by adamtang79** [comment]
Means not possible in plug in level?
