### ISSUE TITLE
[QUESTION] - Bind inner text/html (like div, p, h1)  to Trait

### ISSUE THREAD

**Issue by sircoko** [artf/grapesjs#3019]
Hi!
I've created a custom trait, and I want to be allowed to change the content of the tags (in this case it's a H1 tag) based on the trait values..

It would be awesome if it can be bi-directional;  changes in the traits panel will update the canvas  and also changes in the canvas would update the input in the panel.

I've tried a lot of approaches with no success at all. 

Do you have any clue?

**Comment by artf** [comment]
> changes in the canvas

What kind of changes? How would you like to change the tag in the canvas?

**Comment by sircoko** [comment]
No, i want to change the content.

for example

`<p> $CHANGE_THIS </p>

**Comment by artf** [comment]
`onUpdate` function in the custom trait definition allows you to update the input as you wish (in the example you see how the component parameter is passed and used to update the trait value)

**Comment by sircoko** [comment]
Ok, but this `onUpdate` updates the info on the canvas? or just into the trait manager?

**Comment by artf** [comment]
You use `onUpdate` to change the trait input and `onEvent` to change components in the canvas

**Comment by sircoko** [comment]
Hi again and sorry for commenting over an over about the same topic. 

I tried the onEvent and it works perfect! but it only change the HTML CODE... but it is not re-rendering the component in the canvas.   I mean, when I see the  html in the code viewer, it's ok, but in the canvas there is no change at all

**Comment by artf** [comment]
How do you update the component?
