### ISSUE TITLE
Localization without using "import"

### ISSUE THREAD

**Issue by trony2020** [artf/grapesjs#3022]
Hi,
to do localization is there a way to do it without using "import" ie with <script src="myFolder/grapesjs/locale/it.js"></script>?

From the docs:

import grapesjs from 'grapesjs';
import it from 'grapesjs/locale/it';
import tr from 'grapesjs/locale/tr';
const editor = grapesjs.init({
  ...
  i18n: {
    // locale: 'en', // default locale
    // detectLocale: true, // by default, the editor will detect the language
    // localeFallback: 'en', // default fallback
    messages: { it, tr },
  }
});

**Comment by artf** [comment]
Current locale files are optimized only for importing them via `import` but you always build them on your own

**Comment by Ahriman** [comment]
Same problem here, how we can set the locale in JavaScript vanilla?
