### ISSUE TITLE
BUG: Double Ckeditor 

### ISSUE THREAD

**Issue by pucksart** [artf/grapesjs#3026]
**Version:**
0.16.22

**Are you able to reproduce the bug from the demo?**
Yes

**What is the current behavior?**

Try to select a text or drag its block, now double click on it. You will see 2 Ckeditors
<img width="739" alt="Schermata 2020-09-16 alle 10 47 14" src="https://user-images.githubusercontent.com/4941395/93315251-1b9faf00-f80b-11ea-81fb-58782aa68295.png">

**Are you able to attach screenshots, screencasts or a live demo?**

 Yes, image taken from https://grapesjs.com/demo-newsletter-editor.html
<img width="739" alt="Schermata 2020-09-16 alle 10 47 14" src="https://user-images.githubusercontent.com/4941395/93315290-28bc9e00-f80b-11ea-8147-c7235401fc7c.png">

**Comment by GoodPHP** [comment]
Hi,

If you didn't find answer here, you can contact with Devfuture Team: https://devfuture.pro/contact/

We specialise on GrapesJS.
