### ISSUE TITLE
BUG: Image asset manager, on remove no ability to re-upload the same image that was removed

### ISSUE THREAD

**Issue by gpmonch** [artf/grapesjs#3027]
**Are you able to reproduce the bug from the demo?**
No, in the image asset manager in the demo there is no option to remove images.

**What is the expected behavior?**
When removing an image, if a user decides to re-upload it, before closing the asset manager dialog he should be able to.

*Describe the bug **detailed***
Once a user uploads an image in the asset manager then selects an image, then removes the image he uploaded from the assets manager dialog, he cannot upload it, no error is thrown, it simply does not upload.

**What is the current behavior?**

**Comment by artf** [comment]
Hi @gpmonch, I'm not able to reproduce it, after deleting the asset I'm able to reupload it again. Are you able to provide a live example?

**Comment by gpmonch** [comment]
Dear Artur,
Thank you so much for your reply, I'm sorry for only responding now,
I've made a screen recording using webex of reproducing the bug in my local
environment,
Please let me know if this helps clear the issue, any help would be highly
appreciated,
Kind regards
Guy

**Comment by artf** [comment]
Hi @gpmonch if I can't reproduce it I'm not able to fix it, so I'd need a reproducible demo

**Comment by gpmonch** [comment]
Hi Artur,
I can send you a video capture of me reproducing the bug in our environment,
or we can schedule an online meeting and I'll show you the issue.
Let me know if either option works for you.
Please notice that the bug reproduces only when following these steps:
1. click the upload area which opens files explorer.
2. double click the photo you want to upload.
3. delete that photo, clicking the X.
4. click the upload area again, and when file explorer open try to select
the same image to upload it.
Kind wishes,
Guy

**Comment by artf** [comment]
> 1. click the upload area which opens files explorer.
> 2. double click the photo you want to upload.
> 3. delete that photo, clicking the X.
> 4. click the upload area again, and when file explorer open try to select
the same image to upload it.

This is exactly what I'm doing and I'm not able to reproduce it. Ensure, at least, to have the latest version, please.

As I'm not able to reproduce it and you're not able to create a live demo, this issue has no reason to be open

**Comment by gpmonch** [comment]
I understand, I will investigate the issue further in our environment,
Thank you very much for your assistance

**Comment by archerbj** [comment]
@gpmonch  hi, I am trying to find a way to delete uploaded assets in assets manager. Since you mentioned clicking x to delete the photo, would you please tell me how to manage that? 

I am not seeing any x in the assets manager except for the close icon for the modal.
