### ISSUE TITLE
While Dragging component to top, removed event is not triggered for another component

### ISSUE THREAD

**Issue by krishnaeverestengineering** [artf/grapesjs#3033]
<img width="949" alt="Screenshot 2020-09-20 at 10 12 52 AM" src="https://user-images.githubusercontent.com/55732888/93694492-ee644100-fb29-11ea-8854-be8d6c7198e3.png">

I moved selected component to top (see in image). So removed/onrender callback triggered for the moved component. But callback is not triggered for below component which is at index 1. Is that a bug or expected behaviour? if it is expected, how can we call removed or something to know its changed its position?

**Comment by artf** [comment]
This is correct behavior, the event is triggered only on updated/moved component otherwise all children would emit events (which is definitely not what we want). You can also try to see if setting the listener on the parent might help you in your case
