### ISSUE TITLE
FEAT: Responsive columns for email clients 

### ISSUE THREAD

**Issue by AlinaKontarero** [artf/grapesjs#3036]
**What are you trying to add to GrapesJS?**
GrapesJS blocks responsiveness for email clients. 

*Describe your feature request **detailed***
The GrapesJS blocks like columns are responsive on app or demo. Hovewer, the email template created with GrapesJS blocks is not responsive to the email client (like gmail app or outlook app). 

**Is there an alternative at the latest version?**

[ ] Yes (descripe the alternative)
[x] No

**Is this related to an issue?**

[ ] Yes (Give a link to the issue)
[x] No

**Comment by artf** [comment]
Hi Alina, this feature is kind of unrelated to the core implementation. You can create your custom components/blocks for email templates and wrap them in a plugin
