### ISSUE TITLE
FEAT: Mouse over text on Style Manger items

### ISSUE THREAD

**Issue by ksn-systems** [artf/grapesjs#3040]
**What are you trying to add to GrapesJS?**

Hi. Not sure if this is already baked in but:

Is it possible to change the mouse over text on a custom trait in the Style manager

![image](https://user-images.githubusercontent.com/60980627/93938576-93c32300-fd7d-11ea-9981-265cd61d1734.png)

I would like to use the mouseover text to give more information about the option the user is changing.

I have looked through the docs but can't see a way forward.

thanks

**Comment by artf** [comment]
Hi @ksn-systems, you can customize the whole label section https://grapesjs.com/docs/modules/Traits.html#define-new-trait-type

**Comment by ksn-systems** [comment]
Thank you
