### ISSUE TITLE
Question: How to render the website in frontend after designing it in the editor? 

### ISSUE THREAD

**Issue by WilburJZHAO** [artf/grapesjs#3041]
Hi all, 

I am wondering how to render the website with our own components designed by the editor into frontend?
I cannot find any info about it in the documentation.

I have tried several ways:

- directly load the html and css get from editor (It is not working as it does not contain any components info)

- use Canvas.getBody.innerHTML (It is working for some simple component, not working on some complex one, eg video component)

So, can anyone suggest me on how to correctly render the website into frontend (I am using Vue)? 

Thank you so much!

**Comment by artf** [comment]
I'd suggest reading this part https://grapesjs.com/docs/modules/Storage.html#store-and-load-templates
