### ISSUE TITLE
FEAT: Accurate Documentation on uploadFile

### ISSUE THREAD

**Issue by patoperpetua** [artf/grapesjs#3042]
## WARNING
READ and FOLLOW next 3 steps, then REMOVE them before posting the issue

1. Follow CONTRIBUTING Guidelines https://github.com/artf/grapesjs/blob/master/CONTRIBUTING.md
2. Do a quick SEARCH first, to see if someone else didn't open the same issue
3. All relative statements/questions have to be filled/answered, otherwise, the issue might be CLOSED
4. JSFiddle Starter template https://jsfiddle.net/szLp8h4n
5. CodeSandbox Starter template https://codesandbox.io/s/1r0w2pk1vl

**What are you trying to add to GrapesJS?**
Add more documentation to uploadFile and also create a function to upload files by providing a URL.

*Describe your feature request **detailed***
So, basically I want to add more documentation to the first parameter of uploadFIle function and to add another function to save files just by providing the URL. I've already done this, you can see at the bottom of this issue.

**Is there an alternative at the latest version?**

[ ] Yes (describe the alternative)
[X] No

**Is this related to an issue?**

[ ] Yes (Give a link to the issue)
[X] No

---

In File [FileUploader.js](https://github.com/artf/grapesjs/blob/dev/src/asset_manager/view/FileUploader.js)
```javascript
...
/**
     * Upload files
     * @param  {Object}  e Event OR an array of file objects.
     * @return {Promise}
     * @private
     * */
    uploadFile(e, clb) {
        const files = Array.isArray(e)? e : e.dataTransfer ? e.dataTransfer.files : e.target.files;
   ...
/**
     *
     * @param url
     * * @param name
     */
    async uploadFileURL(url, name){
      const response = await fetch(url);
      // here image is url/location of image
      const blob = await response.blob();
      const file = new File([blob], name, {type: blob.type});
      this.uploadFile([file]);
    }
```

If you want I can create a pull request with it.

**Comment by artf** [comment]
There is already an option for upload URL https://github.com/artf/grapesjs/blob/8822aa6c6e8ced09ad50f2c8392f1754d3a6ec8b/src/asset_manager/config/config.js#L18-L21
