### ISSUE TITLE
BUG: Unable to remove Strike via selection toolbar

### ISSUE THREAD

**Issue by BCleverly** [artf/grapesjs#3047]
Current version: 0.16.22

**Are you able to reproduce the bug from the demo?**

[x] Yes
[ ] No

**What is the expected behavior?**
Be able to apply and remove the Strike-through styling via the mini toolbar on a selection and remove it via the same process

**What is the current behavior?**
You're able top apply the styling via the mini toolbar, but you're not able to remove it once it's applied.

If you do all of this via the Style manager it works as intended as this applies it via CSS instead of wrapping it in a HTML element.

**Comment by Ju99ernaut** [comment]
This is as a result of this change #2886, as a temporary fix you can use:
```js
const rte = editor.RichTextEditor;
rte.add('clearFormatting', {
    icon: icons.clear || '<i class="fa fa-eraser"></i>',
    attributes: {
      title: 'Clear Formatting'
    },
    result: rte => rte.exec('removeFormat')
  });
```
This adds a button that removes all formatting tags.

**Comment by BCleverly** [comment]
Thanks @Ju99ernaut - appreciate the help :)

**Comment by artf** [comment]
Will be fixed in the next release
