### ISSUE TITLE
[BUG]: TypeError: Cannot read property 'get' of undefined

### ISSUE THREAD

**Issue by ealipio** [artf/grapesjs#3048]
### Version:
0.16.22

### Are you able to reproduce the bug from the demo?

[x] Yes
[ ] No

### What is the expected behavior?
no errors in the console.

### Describe the bug detailed

```
TypeError: Cannot read property 'get' of undefined
  at apply (./node_modules/grapesjs/dist/grapes.min.js:11:64180)
  at HTMLDocument.r (./node_modules/@sentry/browser/esm/helpers.js:71:23)
```

File involved is:
https://github.com/artf/grapesjs/blob/6296bf8c970f700aa69e44728b7db80833452f69/src/dom_components/view/ComponentTextView.js#L61

```
  const { model, rte, activeRte, em } = this;
    const editable = model.get('editable'); // if model is undefined we have the bug

```

**Comment by artf** [comment]
Weird (the view component can't exist without the model), are you able to provide exact steps to reproduce the issue?
