### ISSUE TITLE
Map Not Loaded full-width

### ISSUE THREAD

**Issue by Abhisheknanda1344463** [artf/grapesjs#3050]
Hi @artf ,

When i drop a "Map" on the canvas and hit the preview in new tab which is my custom preview. In that new tab of preview "Map" will not loaded with full width.
Could you please help me on that.

**Comment by MartinPutz** [comment]
@Abhisheknanda1344463 
I checked on the demo editor and it seems to work fine. 
Could you create a jsfiddle with your problem?

**Comment by artf** [comment]
I guess it might be something wrong with your preview, provide a live example at least, for now, I'll close the issue
