### ISSUE TITLE
BUG: build tests are failing

### ISSUE THREAD

**Issue by ashercoren** [artf/grapesjs#3051]
**Version:**
dev branch (pre-release)

**What is the expected behavior?**
When running `npm test` or `npm run build`, the tests should complete successfully.

**What is the current behavior?**
I tried to build a production version of the repo, but `npm test` fails on multiple errors.
I traced back the commits and the commit the broke the tests is [this commit](https://github.com/artf/grapesjs/commit/68403f86077bff635c6749635a776429077715ad)

**Comment by artf** [comment]
Thanks @ashercoren I've seen it and fixed it locally but not yet updated the remote branch as I've noticed there is another issue to fix on Travis. I'll update it soon btw
