### ISSUE TITLE
FEAT: option for responsive design

### ISSUE THREAD

**Issue by micker** [artf/grapesjs#3056]
hello i am not sure its not already implement but i didn't find where
=> with grap we can change display for check responsive option but we can't change option for specific device ?
like change size of block on smartphone
exemple
![image](https://user-images.githubusercontent.com/2539440/94736976-5eb26400-036d-11eb-9900-a7f083e6020b.png)
what do you think about this ?

**Comment by MartinPutz** [comment]
@micker 
If I'm understanding you correctly, then this is already implemented, when you change the styles of a component on a given device, a media query will be used.

You can see that on the demo page: https://grapesjs.com/demo.html

You can change the device to mobile, change the width of something and go back to desktop. The change is only applied for the mobile device. You can click on the view code icon at the top, scroll down to the bottom and you will see the media queries.

**Comment by micker** [comment]
Ah cool

**Comment by theSC0RP** [comment]
@MartinPutz I have implemented the responsive feature as shown in the getting started guide but when I click on the mobile icon, the layout is only squished. (The two-column layout does not change to two-row. Only the width is reduced) Can you pls help me if you have worked on the responsive design?

**Comment by RakulAgn** [comment]
This Option is Not available in Grapesjs MJML right ?
