### ISSUE TITLE
How to convert the output of getComponents to html and getStyle to css strings ?

### ISSUE THREAD

**Issue by muzammilkghrix** [artf/grapesjs#3057]

**Comment by MartinPutz** [comment]
@muzammilkghrix 
There are built-in commands to get the HTML and CSS from the editor:
https://grapesjs.com/docs/api/editor.html#gethtml

```js
let html = editor.getHtml();
let css = editor.getCss();
```


Or if you really want to convert 'getComponents' then:

```js
let html = '';
editor.getComponents().forEach((m) => {
    html += m.toHTML();
});
```

**Comment by muzammilkghrix** [comment]
Thank you. The second part is what I was looking for.
