### ISSUE TITLE
How to modify existing block properties in style manager

### ISSUE THREAD

**Issue by dharmatv** [artf/grapesjs#3058]
**Version:**
0.15.9

How to modify/remove few CSS properties for existing blocks like(text, image) in style manager

I have checked the following link also
https://github.com/artf/grapesjs/issues/1428

Could u please provide a solution

**Comment by dharmatv** [comment]
I tried with the above solution(#1428) but didn't get output, please check the following code and view screenshots, so, please help on this
https://snipboard.io/Om0BXG.jpg
https://snipboard.io/tcJVY0.jpg

**Comment by artf** [comment]
Please explain better what are you trying to achieve
