### ISSUE TITLE
Header goes on a textbox

### ISSUE THREAD

**Issue by lebonsavane** [artf/grapesjs#3059]
Hello, so first thanks to have create GrapesJs this very usefull. I have an issue i add an header on my page and that's the code i add for the header: 
`<header style="padding: 100px 0px;position: absolute;top:0; width:100%"></header>`
The problem is : When i add first a text area or an other element and then i add the header both superimposed : 
![Screenshot_1](https://user-images.githubusercontent.com/39559339/94820866-36744500-0401-11eb-8c5f-830e73a48d4f.png)

So can you answer with the property i have to manage. I want when i insert the header, the other elements go under.  @artf

**Comment by artf** [comment]
Are you able to provide a live example?

**Comment by lebonsavane** [comment]
How can i contact you ?

**Comment by artf** [comment]
@lebonsavane just provide an example on JSFiddle or similar
