### ISSUE TITLE
Asset manager - After click on image how to hide modal

### ISSUE THREAD

**Issue by dharmatv** [artf/grapesjs#3062]
**Version:**
0.15.9

**What is the expected behavior?**
After clicking on the uploaded image in the asset manager, that modal should be closed

*Describe the bug **detailed***
After clicking on the uploaded image in the asset manager, that modal shouldn't be close

Could u please provide a solution on how to hide the modal after clicking on the image or after dropping the image

**Comment by artf** [comment]
You can read here about how to extend assets https://grapesjs.com/docs/modules/Assets.html
