### ISSUE TITLE
BUG: gjs-hovered is not being removed when cursor leaves the layers

### ISSUE THREAD

**Issue by Davidvlv** [artf/grapesjs#3065]
**Version:**
0.16.22

**Are you able to reproduce the bug from the demo?**

[x] Yes
[ ] No

**What is the expected behavior?**

1. Hover over body in the layers - body element has the class gjs-hovered and has a blue outline
2. Move mouse up and out of the layers

body element should remove gjs-hovered and no longer have a blue outline

**What is the current behavior?**

Body element keeps the gjs-hovered class and remains hovered

**Are you able to attach screenshots, screencasts or a live demo?**

[x] Yes (attach)
[grapesjs hover doesn't go away.zip](https://github.com/artf/grapesjs/files/5338784/grapesjs.hover.doesn.t.go.away.zip)

**Comment by fq-selbach** [comment]
I discovered another issue with `gjs-hovered`. Sometimes the blue outline will move during scrolling.
Check out this JsFiddle: https://jsfiddle.net/vb7r1zns/

It seems to happen only when the HTML code starts with another full width/height DIV:
```
<div id="gjs">
<div style="width: 100%; height: 100%;">
...
```

**Comment by artf** [comment]
Thanks @Davidvlv for the report. The fix will be available in the next release.

@fq-selbach your issue is a bit different, that happens with scrollable inner elements.

**Comment by fq-selbach** [comment]
Since you closed this I've created a new issue for the related problem: https://github.com/artf/grapesjs/issues/3152
