### ISSUE TITLE
FEAT: remove 'display: block' inline style from Style Manager sectors and properties

### ISSUE THREAD

**Issue by maryia-kabash** [artf/grapesjs#3067]
**What are you trying to add to GrapesJS?**
Improve visibility for Style Manager sectors and properties. 

*Describe your feature request **detailed***
Currently if a sector or property is visible, inline style "display: block;" is added, which limits styling opportunities (e.g. it's now impossible to add 'display: flex' to property wrappers).

**Is there an alternative at the latest version?**
Do not add "display: block;" for visible elements, just remove 'display: none' as it was done in previous versions of GrapesJS

**Comment by artf** [comment]
The fix will be ready in the next release, thanks

**Comment by maryia-kabash** [comment]
Thanks! Do you have any estimates on the release date?

**Comment by artf** [comment]
Probably, the end of this week
