### ISSUE TITLE
BUG: Style gone on link or nested text elements after exiting edit

### ISSUE THREAD

**Issue by orosl** [artf/grapesjs#3069]
Hello,

I am editing legacy HTML with version 0.16.3 + newsleter-plugin. The style is stored inline (since the tool is used for authoring emails) and I use the feature  `componentFirst: true `. 

I am facing a problem when trying to edit **Component Text** that has other text elements inside. 

```
<div  style="font-size: 20px;" class="my-class" > 
            A text component  
           <span style="font-size: 35px;">---and a text inside---</span>
</div>
```

Once I **edit** the text from the parent div, the styling of the nested element disappears at **blur**. The inline style is stored on the id and the **id of the subnode is completely removed**.  
How can I stop this from happening?

 The behavior is presented in this JSFiddle: https://jsfiddle.net/jsh8yv4p/

I have read about including the text inside the parent div in a span or another text element, but since the HTML that is loaded in the editor is legacy I do not want to alter its structure in this manner.

Is there any way I can edit text(that might have subnodes) and not alter the subnodes?

Thank you in advance,
Lavinia

**Comment by artf** [comment]
Hi @orosl, thanks for the report. I was able to find and fix the bug so, it'll be available in the next release.

**Comment by orosl** [comment]
Hi @artf, thank you very much for your prompt response and release. I upgraded with the latest version **0.16.27**. However I still encounter the problem, but with a slightly different behavior.

I am not sure if I should open a new issue since it is partially solved but nonetheless, I will explain the behavior here. 

Given a similar configuration as above and presented in this demo: https://jsfiddle.net/x5srzpvk/5

If I change the styling of the link(or any other such element) in the nested span element, after an edit, the styling is lost since the id is altered (styling is kept on the id).

So,  id: **jp365 transforms into jp365-2** and continues to be added **-2-2** after **each edit**.
I encountered this behavior in multiple similar situations.  Also, the HTML gets difficult to read after many edits, as the ids increase in size. 

Is there any way I can stop the process of altering ids of subnodes if text is edited?

Thank you and much appreciation,
Lavinia

**Comment by artf** [comment]
Thanks @orosl actually the fix was working with inner components but not with nested ones. I'll fix it in the next release

**Comment by orosl** [comment]
Thank you @artf! So glad! I am not sure what will be your approach for the fix. It will be really helpful if the ids of subelements would not be altered on text edit (it gets unmanageable if it keeps adding -2 or -x after every edit).

Many thanks for everything!

**Comment by artf** [comment]
@orosl indeed ids won't be altered :)

**Comment by omergr8** [comment]
It's still not fixed. Every time I edit text, my p tag id get vanished.
