### ISSUE TITLE
Multiple CSS generated and new function

### ISSUE THREAD

**Issue by blackbirdzzz** [artf/grapesjs#307]
Hi , i wanted to know how to correct the CSS generated by grapesjs cause when i drop my code some useless css are generated like those background-.. = initial for every side : See the picture bellow, i want to know how to get a clear code.
![capture d ecran 2017-09-14 a 10 46 52](https://user-images.githubusercontent.com/30260928/30420849-3216f5ae-993b-11e7-9e5f-f71d9fa095b7.png)
Second question : 
How to create a new function that open a modal like when you double click to a picture that open the asset manager picture, i want to create something like this but for button open a modal and write the link that i want and modify the link of the button and also i can re open the modal of this button and get the link actually available on the button. i think i need to create a domcomponents but i just need to know how to create a gesture about double clicking on the button will open a modal. Thanks again :).

Another question : when i import my code my code don't get any indentation if i want to rework the code i need to go on internet and use an html formatter , did you know if there is , an javascript script to format code ? Thanks

**Comment by blackbirdzzz** [comment]
I wanted also to know on the side of my domcomponent that open a modal on dropping the elements i want to delete the content, if the person leave the modal can i control an elements that being dropped that a few second before ? this is the code : https://codeshare.io/29pbvg

**Comment by artf** [comment]
1. Can't do much with the CSS, this is what is generated from the browser, I've already added to Roadmap the integration with some custom CSS parser.
2. Check here to see how to create a command which opens a Modal https://github.com/artf/grapesjs/blob/dev/src/commands/view/OpenAssets.js
3. https://github.com/prettier/prettier
