### ISSUE TITLE
BUG / Feature? Applying background color to body component isn't part of the exported HTML.

### ISSUE THREAD

**Issue by mhowey** [artf/grapesjs#3070]
Hi Art, thanks for creating such a fantastic project!

I'm not sure if this would be considered a bug or feature request...but I'm having issues deciding how to hande the **background color on the body** while using the **newsletter plugin** with GrapesJS.

Steps to Reproduce:

1. Select the body (root element) in the canvas.
2. In the style palette under "decorations" >> "Background" -- select a color to fill the body with
3. Click export HTML, only the children elements are provided, so when the output HTML is used, it has no wrapper to apply the background color with.

If there is a way to handle this correctly that I'm missing, I'm not sure. I am considering manually wrapping the HTML in a table or div that applies the color or something like that??

Thanks in Advance for any and all assistance.

![image](https://user-images.githubusercontent.com/148117/95581050-51007c80-0a06-11eb-8084-75ddddba7301.png)

**Comment by JoshLucio** [comment]
@mhowey I have seen this also, but I always assumed that the body is just the placeholder canvas for the content. Changes to the body do not export since the content placed in the body is the only thing being exported. In my application use, the body color change is used just to visualize what the content will look like when I place it on my site if the site has a background color.

**Comment by artf** [comment]
You can use this option 
```js
grapesjs.init({
 exportWrapper: true,
})
```

**Comment by mhowey** [comment]
Perfect Thanks so much!

**Comment by mhowey** [comment]
@artf -- when I use the newsletter's 
```javascript
editor.runCommand('gjs-get-inlined-html');
```
It only returns the innerHTML and not the. body element that I see when I look at the code in the export modal.

How do I retrieve the entire content body + all components programmatically?

Thanks again in adavance!
