### ISSUE TITLE
BUG: 

### ISSUE THREAD

**Issue by marcepoblet** [artf/grapesjs#3072]
is there any way to set the size of the "blocks"? because in IE11 the size of the blocks look different.

IE11: 
![blocks-ie11](https://user-images.githubusercontent.com/64096863/95980864-28a4c380-0df4-11eb-843e-61492690b7b9.png)

Firefox/EDGE/Chrome:
![blocks](https://user-images.githubusercontent.com/64096863/95980899-39553980-0df4-11eb-945c-6ecfb02715c2.png)

**Comment by artf** [comment]
CSS
