### ISSUE TITLE
BUG: Unhandled Rejection (TypeError): i.classList is undefined

### ISSUE THREAD

**Issue by ColdTuna** [artf/grapesjs#3075]
Hi. I updated GrapesJS to its current version 0.16.22 and I get an error on the callback function:

    editor.on("component:add", (model) => {
        editor.select(model);
    });

The error stack:

    Unhandled Rejection (TypeError): i.classList is undefined

    Stack:
    ./node_modules/grapesjs/dist/grapes.min.js/</</w.toggleClass/</<
    node_modules/grapesjs/dist/grapes.min.js:2
    S
    node_modules/grapesjs/dist/grapes.min.js:2
    ./node_modules/grapesjs/dist/grapes.min.js/</</w.toggleClass/<
    node_modules/grapesjs/dist/grapes.min.js:2
    ./node_modules/grapesjs/dist/grapes.min.js/</</w.each/<
    node_modules/grapesjs/dist/grapes.min.js:2
    S
    node_modules/grapesjs/dist/grapes.min.js:2
    ./node_modules/grapesjs/dist/grapes.min.js/</</w.each
    node_modules/grapesjs/dist/grapes.min.js:2
    ./node_modules/grapesjs/dist/grapes.min.js/</</w.toggleClass
    node_modules/grapesjs/dist/grapes.min.js:2
    ./node_modules/grapesjs/dist/grapes.min.js/</</w.removeClass
    node_modules/grapesjs/dist/grapes.min.js:2
    updateStatus
    node_modules/grapesjs/dist/grapes.min.js:2
    m
    node_modules/grapesjs/dist/grapes.min.js:2
    v
    node_modules/grapesjs/dist/grapes.min.js:2
    d
    node_modules/grapesjs/dist/grapes.min.js:2
    ./node_modules/grapesjs/dist/grapes.min.js/</</</o</a.Backbone</c.trigger
    node_modules/grapesjs/dist/grapes.min.js:2
    set
    node_modules/grapesjs/dist/grapes.min.js:2
    selectAdd
    node_modules/grapesjs/dist/grapes.min.js:11
    init/<
    node_modules/grapesjs/dist/grapes.min.js:11
    m
    node_modules/grapesjs/dist/grapes.min.js:2
    v
    node_modules/grapesjs/dist/grapes.min.js:2
    d
    node_modules/grapesjs/dist/grapes.min.js:2
    ./node_modules/grapesjs/dist/grapes.min.js/</</</o</a.Backbone</c.trigger
    node_modules/grapesjs/dist/grapes.min.js:2
    _onModelEvent
    node_modules/grapesjs/dist/grapes.min.js:2
    m
    node_modules/grapesjs/dist/grapes.min.js:2
    v
    node_modules/grapesjs/dist/grapes.min.js:2
    d
    node_modules/grapesjs/dist/grapes.min.js:2
    ./node_modules/grapesjs/dist/grapes.min.js/</</</o</a.Backbone</c.trigger
    node_modules/grapesjs/dist/grapes.min.js:2
    set
    node_modules/grapesjs/dist/grapes.min.js:2
    add
    node_modules/grapesjs/dist/grapes.min.js:2
    push
    node_modules/grapesjs/dist/grapes.min.js:2
    addSelected/<
    node_modules/grapesjs/dist/grapes.min.js:11
    addSelected
    node_modules/grapesjs/dist/grapes.min.js:11
    setSelected/<
    node_modules/grapesjs/dist/grapes.min.js:11
    setSelected
    node_modules/grapesjs/dist/grapes.min.js:11
    select
    node_modules/grapesjs/dist/grapes.min.js:11

**Comment by ColdTuna** [comment]
Never mind, problem solved by:

    editor.on("load", () => {
        editor.on("component:add", (model) => {
            editor.select(model);
        });
    });

**Comment by ColdTuna** [comment]
Ok, never mind the previous never mind. It worked a few times now I'm getting the same error. Sorry about that.

**Comment by artf** [comment]
Can you provide a demo, please?

**Comment by ColdTuna** [comment]
Let me double check my code before, maybe I did something silly. I think all I did was update the library, I haven't changed anything in the editor, however, I make mistakes all the time... so... I'll get back to you. Thanks Artf!

**Comment by ColdTuna** [comment]
What seems to be causing the my problem is the StorageManager on the load() function. When I load the template from a React component directly into the canvas, things work fine. When I load the template from the database as object { html, styles, components, assets...} using the StorageManager load() > clb(data), it crashes right after loading the template page.

Maybe something structurally changed on how StorageManager loads data? I suspect this because when I create a new page from a React component, save it as an object into the database and reload it, it works. Which means, new template pages are ok, my old template pages aren't. 

Anyway, I rolled it back to my previous version (0.16.18) and things are working normally. At the moment I can't create a demo editor with all the features mine has, it'd be a project of its own. I'll do some more investigating later.

**Comment by artf** [comment]
Thanks @ColdTuna let me know about the demo, please, as I'm not able to reproduce by following you logic
