### ISSUE TITLE
QUESTION: Set component's empty state

### ISSUE THREAD

**Issue by Joshmamroud** [artf/grapesjs#3076]
Hi @artf ,

How would you recommend giving a component an empty state? 

Say, for instance, I have a layout component (ie. a column) which should contain child elements (ie. text component or image). When that layout component is empty I'd like to display some help text inside such as "Add an element here" and when it has children it shouldn't be displayed. 

Of course, this should only exist in the view and not render in the output HTML.

**Here is an example of what I am looking to create:**
![image](https://user-images.githubusercontent.com/5224187/96303828-129c2c00-0fc9-11eb-9654-f8965f1402ef.png)

If there is another issue that explains how to do this then I apologize, I searched and wasn't able to find anything on it.

Thank you in advance!
Josh

**Comment by ColdTuna** [comment]
Hi Josh, I like your idea.

No expert here, but here are couple thoughts:

Basically I would add some kind of flag to the component itself.

idea 1) If the component is some kind of container (i.e. div), add a `<p class="empty-message">Drag an element here</p>` to it, then when a new component is added, you could use the editor event `component:add`and check for any siblings with the `empty-message` class and remove it.

idea 2) Add a `empty-message` class to the component itself, then use CSS :before/:after to add content to it. Then remove the componentś parent empty-message class using JS, similarly to idea 1.

Hope it helps.

**Comment by Joshmamroud** [comment]
Hi @ColdTuna ,

Those solutions seem like they could definitely work. I didn't think of approaching it from that angle but I think I'll take a crack at it and see if it does the trick.

I was hoping for something that could be implemented on the component type definition level but hey let's give it a shot!

Thanks,
Josh

**Comment by ColdTuna** [comment]
Hello,

At the component level you might be able to do it too. Perhaps you could explore the [component model/view](https://grapesjs.com/docs/modules/Components.html#define-custom-component-type), set event listeners and go from there. I didn't think about it this way before, but yeah, that's a possibility I think.

**Comment by MartinPutz** [comment]
@Joshmamroud There might be an easier way, since GrapesJS lets you entirely customize the rendered HTML regardless of the view HTML.
Related to https://github.com/artf/grapesjs/issues/252#issuecomment-325018814

**Comment by Joshmamroud** [comment]
@MartinPutz I believe the issue here is that the component is only updated on the initial render. If for instance, we had a column with child components and the user were to remove the child components I don't believe the component would update to display the placeholder.

I could be wrong but I believe a component's view render method only fires when the template is initialized or when a new component is added.

Thank you for linking that issue though. I think it's heading in the right direction.

**Comment by artf** [comment]
I've done something similar in this way using only CSS
```js
const doc = editor.Canvas.getDocument();

...addType('cc', {
 model: {...},
 view: {
  init() {
   ...
   const stl = doc.querySelector('style#cc-id');

   if (!stl) {
    doc.body.insertAdjacentHTML('beforeend', `
     <style id="cc-id">
      .cc-class:empty:after {
         content: "Empty block";
         text-align: center;
         display: block;
       }
      </style>
     `);
    } 
  }
 }
})
```

**Comment by Joshmamroud** [comment]
@artf You are THE MAN! I didn't even know the `:empty` selector existed. So simple, so awesome! Mind blown. Thank you!
