### ISSUE TITLE
BUG: on style manager panel , height/width properties did not reflect the right values 

### ISSUE THREAD

**Issue by meyerco** [artf/grapesjs#3077]
## Description

- The bug is reproduced on the current demo

## What happens ?

- On Style Manager Panel height/width property input did not reflect the right values .

## Steps to reproduce on the demo

- Open the import popup and paste this and click import
```html
<label>Test</label>
<style>
label {
	height:50px;
	width:50px;
}
</style>
```
- Select the label
- On Style Manager panel , under dimension sector , check the height/width property .

The values are not correct , **auto** instead of **50px** . 
However the css is applied correctly .

**Comment by artf** [comment]
Unfortunately, calculated height and width (like in this case, because are attached to the tag and not to a single class/id) can't be displayed properly so are excluded intentionally
