### ISSUE TITLE
Issue when adding/viewing custom class inside the panel control 

### ISSUE THREAD

**Issue by gstucki** [artf/grapesjs#3079]
Hi,

I try to add custom class using the button on the panel control but it is not working. Check the quick video to see what I'm talking about : https://www.loom.com/share/c50fdc3741094c0f9fea65b05eb78d3a

Thx.

**Comment by artf** [comment]
Sorry, but for such a case I can't do much without a reproducible demo, the official demo with the latest version works fine, so I guess it might be something wrong only on your side.
