### ISSUE TITLE
BUG: How to view style manager properties after drag and drop 

### ISSUE THREAD

**Issue by dharmatv** [artf/grapesjs#3088]
**Version:**
0.15.9

**Are you able to reproduce the bug from the demo?**
Yes

**What is the expected behavior?**
(In newsletter plugin)Click on the component in the builder part which need to show style manager properties related to that component

**What is the current behavior?**
Didn't show style manager properties after clicking on the component(In newsletter plugin)
(https://drive.google.com/file/d/1du5A0j-8D37109UqUaJv3NAW-jyl9pAy/view)

**Are you able to attach screenshots, screencasts, or a live demo?**

Yes (https://drive.google.com/file/d/1YNNEYdttOlvkQhyVPjD7XDGx4lwKc_eV/view)

Could u please help me, anyone, with this

**Comment by artf** [comment]
It's not a core feature, it was implemented in the website preset in this way
https://github.com/artf/grapesjs-preset-webpage/blob/3e5a9e12998c9a32b6f1199953084163678e6c17/src/panels/index.js#L108-L118
