### ISSUE TITLE
Issue with responsive design.

### ISSUE THREAD

**Issue by theSC0RP** [artf/grapesjs#3089]
When I switch to the mobile view, the elements on the screen are just squeezed. (I am using the [grapesjs-blocks-basic](https://github.com/artf/grapesjs-blocks-basic) plugin) 
In the screenshots below, a have a column with 2 cells. I expect it to be converted to rows in the mobile view <br/>
![Screenshot (179)](https://user-images.githubusercontent.com/30771519/96841881-f76a6a00-1469-11eb-9bfe-56cf76a7eb05.png) <hr/>
![Screenshot (178)](https://user-images.githubusercontent.com/30771519/96841931-06511c80-146a-11eb-8b03-7cdee2846453.png) <br>
The code for the deviceManager is: 
```
deviceManager: {
      devices: [{
          name: 'Desktop',
          width: '', // default size
        }, {
          name: 'Mobile',
          width: '400px', // this value will be used on canvas width
          widthMedia: '480px', // this value will be used in CSS @media
      }]
},
```

**Comment by Ju99ernaut** [comment]
Try using [flexGrid](https://github.com/artf/grapesjs/issues/3085#issuecomment-715230559)

**Comment by theSC0RP** [comment]
@Ju99ernaut Thank you so much. Using flexGrid solves the issue.
