### ISSUE TITLE
[QUESTION] How to use grapesjs with static HTML

### ISSUE THREAD

**Issue by NeekoGta** [artf/grapesjs#3091]
Sorry in advance for my English.

I'm developing a CMS using Laravel and Vue.js.

I want to use grapesjs for editing page content but with static HTML elements (like navbar, footer ...).
Here is a simple image of what I would like to have.

![grapesjs-question](https://user-images.githubusercontent.com/70320232/97079273-d3866000-15f2-11eb-84e3-3248f065394e.jpg)

I went through the documentation to try to find answers and did several tests without actually achieving this.

Thank you !

**Comment by artf** [comment]
> did several tests without actually achieving this

What did you try? Please, show the code.

**Comment by NeekoGta** [comment]
I found a solution by combining `fromElement: true` and this : https://github.com/artf/grapesjs/issues/336#issuecomment-332205060
But I have to use `type: 'local'` and can't use `urlStore` and `urlLoad` anymore.
I have to implement myself the save / load.

**Comment by akkivaghasiya5** [comment]
@NeekoGta did you get solution? I'm also facing the same issue.
BDW, it's as great effort to build such a tool/library like GrapesJS.

**Comment by NeekoGta** [comment]
@akkivaghasiya5 2 years ago yes 😆
But trying again today, it doesn't seem to work.

`fromElement` seems deprecated now.

@artf It's possible to you to provide example how we can achieve this?

Thanks!

**Comment by artf** [comment]
There are different ways to achieve the same desired result, so I'd recommend checking these examples:

Identify the editable component and ignore everything else
https://jsfiddle.net/artur_arseniev/aku70f5w/

Identify placeholder components and ignore them
https://jsfiddle.net/artur_arseniev/w6mvq4bx/
