### ISSUE TITLE
BUG: Missing Hover style on the duplicated component

### ISSUE THREAD

**Issue by tranthanhhoa** [artf/grapesjs#3093]
**Version:** 
- 0.16.27

**Summary:**
- Missing hover style on the duplicated component

**Steps to reproduce:**
- Try to change something on Hover state
- Duplicate the changed component

**Expected:**
- The duplicated component has hover style

**Actual:**
- The duplicate component hasn't hover style

**Comment by artf** [comment]
Good catch, thanks @tranthanhhoa I'll try to fix it in the next release
