### ISSUE TITLE
Components & Js - Load Template Re-Post

### ISSUE THREAD

**Issue by BanksyDog** [artf/grapesjs#3099]
I have the same issue reported in [Components & Js - Load Template #1906 ](https://github.com/artf/grapesjs/issues/1906#issuecomment-477773294)

Components with JS work fine when dropped, and on first export. However, if the page is refreshed, js is not loaded which causes issues.

The JS is also excluded from any exports after a refresh.

Thanks for the help.

**Comment by GoodPHP** [comment]
Hi,

If you didn't find answer here, you can contact with Devfuture Team: https://devfuture.pro/contact/

We specialise on GrapesJS.

**Comment by artf** [comment]
Ensure to have the `script` on a defined Component and not Block, then you have to store and load the JSON structure, not HTML/CSS
