### ISSUE TITLE
[Question] Is it possibile to select multiple elements?

### ISSUE THREAD

**Issue by pfurini** [artf/grapesjs#310]
Hi, I've come across this wonderful project, looking for an editor to embed in a future product, but I noticed that I cannot select multiple blocks in a page (tried with several key combinations, both in the editor and in the layer manager pane)..

Is it supported or planned? With the added ability to make bulk changes to the selected elements, this could be a killer feature..
As a side question, do you maintain an updated list of complex/requested features you'd like to add, but for which you'd need financial support?

Thx, P.

**Comment by artf** [comment]
Hi Paolo, unfortunately, multiple selections are not supported and not even planned, but I agree that it could be a really good feature. Honestly, I've already thought about this but was a little bit concerned about few points: 
* Being a class-based editor, how styles, applied via style manager, have to be applied (each component could have multiple classes)
* Assuming I'd also like to select multiple components with `shift` key (like generally happens), how does this should work if those components are in two different parents

**Comment by pfurini** [comment]
Hi, couple of considerations to start:

- at first multiple selection with shift key, both in the panel and in the
editor, could be supported only for moving the selection under another
parent. If elements are under different parents, they will be moved under
the new destination, valid or not (I don't know if the editor does check
semantic validity of the HTML)
- next feature: the ability to edit common style properties (pure
intersection of supported properties), even if some of them does not make
sense (for example editing the top property of all the elements at once is
an bit useless if stacked with absolute positioning)
- next next feature: treat selection groups specially, and give smart
editing experience (for example if selecting a group of absolute positioned
elements within same parent, let the user move the entire group by finding
top or left element and adjust the properties accordingly)

This is only an example, and the third point needs a lot more of
investigation, but the first two are achievable in decent amount of time
IMHO..
What do you think ?

PS: if the editor could support web components, the properties panel should
be customized to support custom (non style) properties, and multiple
selection should work with that properties too

Il giorno 16 settembre 2017 @ 12:34:17, Artur Arseniev (
notifications@github.com) ha scritto:

**Comment by artf** [comment]
Thanks Paolo for your considerations, really appreciate. About the styling, I'd rather consider the intersection of classes instead of properties (as the editor is class-based), so you can style only components which have at least one class in common, does it make sense?

Can you tell me more about how do you see the integration with web components?

**Comment by artf** [comment]
The first version of multiple selection is available from https://github.com/artf/grapesjs/releases/tag/v0.14.20
