### ISSUE TITLE
BUG: Getting Started Docs example is static

### ISSUE THREAD

**Issue by palerdot** [artf/grapesjs#3101]
https://grapesjs.com/docs/getting-started.html - Getting started guide examples are static. All we can see is 'Hello World Component!' when different blocks, panels are added after each step.

**What is the current behavior?**
Getting started page examples are static after each step in the guide.

**What is the expected behavior?**
It should be interactive, or atleast should be a screenshot of how it would look after following the necessary steps in the `Getting Started` section.

**Comment by theSC0RP** [comment]
@palerdot The examples aren't static in my browser. Here's a screenshot: <br/>
![Capture](https://user-images.githubusercontent.com/30771519/97701463-79463d00-1ad3-11eb-8c5f-65057184585e.JPG)
 <br/>
As you can see in the image, there is a panel at the bottom which contains various blocks. I am able to drag and drop them on the canvas. Here's another screenshot showing the result after adding each block  <br/>
![Capture2](https://user-images.githubusercontent.com/30771519/97701768-f5d91b80-1ad3-11eb-8c8c-401cb6374683.JPG)

**Comment by palerdot** [comment]
It is working fine now. For some reason, when I raised the issue it was completely static. Will close the issue as this is not relevant right now.
