### ISSUE TITLE
How to add/apply event listener (change) to wrapper component

### ISSUE THREAD

**Issue by integerManual** [artf/grapesjs#3102]
Hy @artf how can i add event listener to `wrapper` component trait ?, based on issue #1146 i only know how to add trait, but not binding an event

**Comment by GoodPHP** [comment]
Hi,

If you didn't find answer here, you can contact with Devfuture Team: https://devfuture.pro/contact/

We specialise on GrapesJS.

**Comment by artf** [comment]
@integerManual the purpose of the trait is to change some component attribute/property, so you have to add listeners on components and not traits.
