### ISSUE TITLE
platforma wireframes support?

### ISSUE THREAD

**Issue by awais786327** [artf/grapesjs#3103]
Hi @artf, how can i add [platforma](https://platforma.ws/) collection of components and UI elements in this grapesJS any idea?

**Comment by integerManual** [comment]
hy @awais786327 you can try read docs on how to add blocks and components, when init grapesjs dont forget include css/javascript from platforma to the canvas
```javascript
const editor = grapesjs.init({
        canvas:{
          styles: ["https://platforma.com/path/to/bootstrap.css"],
          scripts:[
              "https://platforma.com/path/to/bootstrap.bundle.js"
          ]
        },
      });
```
