### ISSUE TITLE
Creation of a type

### ISSUE THREAD

**Issue by lebonsavane** [artf/grapesjs#3107]
I need to create a type of component like "link" but when i deploy it with npm start nothing happened and my component which is defined as a fusion type is not recognized. In the compilator they said "Component type not found. Can someone help me ? 
@artf

**Comment by artf** [comment]
Please read here how to create custom [Components](https://grapesjs.com/docs/modules/Components.html) and how to properly use them in your [plugins](https://grapesjs.com/docs/modules/Plugins.html)
