### ISSUE TITLE
Move Layer up & down with arrows

### ISSUE THREAD

**Issue by vijaycreatise** [artf/grapesjs#3108]
Can we move layers up and down with arrows or with buttons? This will be helpful in mobile to move the layers.

**Comment by artf** [comment]
In the core, there is no such functionality but for sure you can add your buttons and use the [API](https://grapesjs.com/docs/api) to move components up and down

**Comment by vijaycreatise** [comment]
@artf thanks for the reply and grapesjs is awesome, great work.
I went through the API but not able to find out which one to use. Can you please help me out which api should I use?
