### ISSUE TITLE
BUG: CKEditor is collapsing

### ISSUE THREAD

**Issue by kuhelbeher** [artf/grapesjs#3109]
Hi, I have an issue with CKEditor. When the block is too narrow when I edit it CKEditor is collapsing:

![image](https://user-images.githubusercontent.com/37115006/97874734-1dbdbe80-1d22-11eb-8159-4d190a1c782f.png)

Is there a way to prevent this behavior? I noticed that in Grapedrop CKEditor has normal view even though the element is narrow.

![image](https://user-images.githubusercontent.com/37115006/97875169-ad636d00-1d22-11eb-93bf-142b83f208d7.png)

I'd be appreciated for any help.

**Comment by artf** [comment]
Hi @kuhelbeher I've defined a min-width for the RTE container via CSS :)
