### ISSUE TITLE
BUG: component droped position is wrong when I changed canvas size under Absolute/Designer mode

### ISSUE THREAD

**Issue by xinyufyj** [artf/grapesjs#3115]
## WARNING
I changed the canvas size and I drop a compent from blocks panel. The result is compent postion is wrong. By the way, the editor is under  'Absolute/Designer' mode.

I read the source code of the drop part. I found the compent drag start position is not based on 'editor.Canvas.getFrameEl()'. So, is this right?

**Comment by artf** [comment]
Can you provide a live demo of the issue?

**Comment by xinyufyj** [comment]
@artf OK, I provide some screenshot for explaining.Sorry for my bad English.
![image](https://user-images.githubusercontent.com/7018771/98490960-40922a80-226e-11eb-9c45-998a1fa10916.png)
![image](https://user-images.githubusercontent.com/7018771/98490964-4556de80-226e-11eb-9793-7e2819f878a4.png)
![image](https://user-images.githubusercontent.com/7018771/98490967-47b93880-226e-11eb-920b-32072ca18e19.png)
![image](https://user-images.githubusercontent.com/7018771/98490972-4a1b9280-226e-11eb-93bc-34bc820fea16.png)

**Comment by artf** [comment]
I close this issue as I'm planning to solve all ones related to absolute positioning here: https://github.com/artf/grapesjs/issues/3770
