### ISSUE TITLE
How to remove a category if no component in it

### ISSUE THREAD

**Issue by zhiyuanzhang-unai** [artf/grapesjs#3117]
I build the custom components at runtime based on a dropdown. When user changes the selection of that dropdown, related custom block will be added and non-related block will be removed.
all custom blocks are group by different category name.

if all blocks are removed from that category, it will show on the screen. 

Is there any way to remove a category? Or somehow make it auto-removed if no blocks within?

**Comment by artf** [comment]
Try to re-[render](https://grapesjs.com/docs/api/block_manager.html#render) the block manager with a new collection of blocks
