### ISSUE TITLE
[QUESTION] How to create custom block made of grapesjs components? 

### ISSUE THREAD

**Issue by makkaronis4e** [artf/grapesjs#3119]
Hi, i want to have custom blocks made of grapesjs components.

I found solution how to add components: https://github.com/artf/grapesjs/issues/1334#issuecomment-411519845
but i'm struggling with adding CSS (eaiher as string or as object).

**Comment by artf** [comment]
You should be able to do something like this:
```js
...
components: [
  { tagName: 'h1', components: 'Some <b>content</b>', },
  '<style>....</style>'
]
```

**Comment by makkaronis4e** [comment]
@artf thanks it works, but i found bug there.

When you drop this block on canvas it works ok, but if you delete this element from canvas or clear whole canvas, then drop this block on canvas 2nd time, it will lose css. 2nd time, 3rd time.. doesnt matter, If you removed element from canvas once, it will lose style for next drops.

**Comment by artf** [comment]
@makkaronis4e for such a case, I'd ask you a reproducible demo, please
