### ISSUE TITLE
Issue with View code button

### ISSUE THREAD

**Issue by awais786327** [artf/grapesjs#3120]
I want both devices and menu buttons on the same panel but the issue is with **View code** button

If i remove `panel.render()` **Devices button** get disappear

If i do not remove `panel.render()` **View Code** doesn't work

what am I doing wrong?

![image](https://user-images.githubusercontent.com/12613564/98472369-6be82b80-2214-11eb-9933-ead334d82654.png)

**Comment by artf** [comment]
Check the [Panel API](https://grapesjs.com/docs/api/panels.html#panels), you're using them totally wrong...
