### ISSUE TITLE
FEAT/ISSUE: CSS standards

### ISSUE THREAD

**Issue by sadtaco** [artf/grapesjs#3121]
I'm going to say this is both a feature request as I get into some parts of it, but also a bit of an issue.

I would say it looks bad to have a project newer than 2015 that's using px for nearly everything.
People are using screensizes that are only 768 pixels on the narrowest plane, whether mobile or desktop, to 2160p and beyond.  "px" measurements are bad for this.
A tool like this is made for non-technical people who aren't going to understand that something looking fine in px measurements on their screen will not look right on all screens.
The most similar thing to GrapeJS is carrd.co right? There they actually just use arbitrary "size" measurements that they translate internally so the end user can't do dumb things.

**My suggestion:**
Remove px in controls interface, and CSS for the styling of GrapeJS itself. Replace with vmax, rem and/or % where appropriate as the new defaults.

Yes there are drop downs for % and/or em and rem generally, but px is usually the default when it really shouldn't even be an option except for possibly being a configuration option that's disabled by default.

**I'd also label this as a bug:**
Default CSS for the editor panels is using z-index. This is something I also don't expect of something modern, as stacking order is a cleaner and more issue and edge-case free way of ordering what's on top. I found this out as I was working on custom controls and I'm having to overwrite CSS that shouldn't even exist.
The editor seems to display fine if you remove all the z-index css and place 
`<div class="gjs-pn-panel gjs-pn-views gjs-one-bg gjs-two-color">` as the bottom most element of those siblings

**Comment by anatoli-dp** [comment]
or a better suggestion for the controls interface could be to have a way to set what unity you want as the default that way those who need px wont have to rely on adding the unit themselves.
