### ISSUE TITLE
BUG: Missing media style on the duplicated component

### ISSUE THREAD

**Issue by tranthanhhoa** [artf/grapesjs#3122]
**Version:**
0.16.27

**Summary:**
Missing media style on the duplicated component

**Steps to reproduce:**
Try to change something on Tablet or Mobile
Duplicate the changed component

**Expected:**
The duplicated component has media style

**Actual:**
The duplicate component hasn't media style

**Comment by artf** [comment]
Thanks @tranthanhhoa I've actually fixed it already on your other [issue](https://github.com/artf/grapesjs/issues/3122), that one was related to the state of rules but I've noticed the same with media, so both are ready for the next release  :)
