### ISSUE TITLE
FEAT: component:clicked / dbclicked event

### ISSUE THREAD

**Issue by archerbj** [artf/grapesjs#3124]
Hi, i am trying to use video component to upload in the assets manager. And I realize I can leverage editor event `component:selected` to do so. 

it works but not perfect. I prefer to use double click to trigger assets manager to open.
If we can have an event like `component:clicked/dbclicked`, it would be better

**Comment by artf** [comment]
You can extend the Video component and in its view add the same event like the one in the [Image](https://github.com/artf/grapesjs/blob/175151b69a041c5bcb3cd4b93bee4df8b2063103/src/dom_components/view/ComponentImageView.js#L8)

**Comment by addlistener** [comment]
@archerbj have you made it work? I tried and it seems ComponentView is only type exported? 

```
Attempted import error: 'ComponentView' is not exported from 'grapesjs' (imported as 'ComponentView').
```
