### ISSUE TITLE
Video throwing error

### ISSUE THREAD

**Issue by awais786327** [artf/grapesjs#3126]
on click to upload button side preview works fine but when clicking on that video preview it throws error and rest of all images stop working, I need to show video in canvas body like images are shown

![gif](https://user-images.githubusercontent.com/12613564/98598005-a24ca600-22fb-11eb-867e-95dc66a6f5a5.gif)

this is what I am doing

![image](https://user-images.githubusercontent.com/12613564/98591110-96f47d00-22f1-11eb-9520-8c201f0b27d8.png)

![image](https://user-images.githubusercontent.com/12613564/98594388-67943f00-22f6-11eb-9ac4-2a62e88ba220.png)

Here you see [live](https://grapes.netlify.app/)

**Comment by awais786327** [comment]
@artf what is happening wrong in it can you see it please?

**Comment by awais786327** [comment]
@artf can you tell me please how can I upload and preview video files rather then images?

**Comment by ZeroCoolHacker** [comment]
@awais786327 I am also struggling with uploading different assets. Maybe this can help.
https://grapesjs.com/docs/modules/Assets.html#uploading-assets

**Comment by ZeroCoolHacker** [comment]
@awais786327 I have looked at the site and it looks like that you need to add `autoplay="true"` in your video tag to make it play

**Comment by awais786327** [comment]
@ZeroCoolHacker my point to say is the video needs to be shown in canvas /editor body (at backside) not in asset manager modal window
