### ISSUE TITLE
Error: Requires Babel "^7.0.0-0", but was loaded with "6.26.3"

### ISSUE THREAD

**Issue by lebonsavane** [artf/grapesjs#3129]
I tried to install new version but in my package.json nothing moves. It's on a plugin called "blocks avancées" of grapesJs but i have this issue on every folder when i try to run the code
"
ERROR in ../src/dom_components/view/ComponentFusionView.js
Module build failed: Error: Requires Babel "^7.0.0-0", but was loaded with "6.26.3". If you are sure you have a compatible version of @babel/core, it is likely that something in your build process is loading the wrong version

"

**Comment by artf** [comment]
ComponentFusionView? That is for sure not from the main grapesjs core, we don't have that component... Probably you're using some kind of modified version, so that might be the reason behind that error
