### ISSUE TITLE
[Question] Standard approach in slight restructuring the HTML toolbar & badge

### ISSUE THREAD

**Issue by jenter** [artf/grapesjs#3130]
**Version:**

`0.15.10`

This question is intended to validate if there is a proper way to extend the current https://github.com/artf/grapesjs/blob/master/src/canvas/view/CanvasView.js with a custom plugin. We were specifically reviewing the `render()` method within this file, to slightly alter the HTML to combine the toolbar and badge for this intended UI design: 
![image](https://user-images.githubusercontent.com/1368216/98736636-12e2d980-2373-11eb-8871-7ac45dcdae3e.png)

In the past, I have successfully extended commands with `editor.Commands.extend('select-comp', {` but wanted to get feedback if a similar approach could be taken with view files -and- if you see any red flags with this altered UI.

thanks in advance for any feedback or insight

**Comment by artf** [comment]
Hi @jenter, good question. Unfortunately, I've never focused that much on the possibility of canvas extension or its UI elements, so for sure there is no right way to do that. 
If anyone is willing to propose solutions I'll be glad to evaluate them.

**Comment by jenter** [comment]
@artf I will review some proposals / thoughts and add it to this thread.

**Comment by artf** [comment]
Great, thanks Jason
