### ISSUE TITLE
BUG: Paste as plain text into Text component adds <font /> wrapper to pasted text

### ISSUE THREAD

**Issue by Joshmamroud** [artf/grapesjs#3131]
**Version:** 0.16.27

**Are you able to reproduce the bug from the demo?**

[] Yes
[X] No

**What is the expected behavior?**
Paste as plain text (text node) without Grapes JS wrapping pasted text in <font /> element.

**What is the current behavior?**
When I paste text as plain text into an **empty** Text element, the editor wraps it in a <font /> element.

**Before text is pasted**
![Screenshot_1](https://user-images.githubusercontent.com/5224187/98757808-4d606c80-239b-11eb-8194-3b854dd8ac97.png)

**After text is pasted (as plain text)**
![Screenshot_2](https://user-images.githubusercontent.com/5224187/98757820-52252080-239b-11eb-942b-ff9ce91baa84.png)

The contents on my clipboard are plain text then I paste as plain text and it still gets wrapped in a <font /> element. This does not happen when there's already content in the Text component.

The text  "I'm a Text Element. Double-click me and start typing." is not actually in the Text component but added using an :empty css rule.

Does anyone know why this is happening and how I can fix it?

Thank you,
Josh

**Comment by Joshmamroud** [comment]
@artf do you know if this is this happening in the component or the RTE or somewhere else? Could you please point me in the right direction? Any help on this would be greatly appreciated. Thanks!

**Comment by artf** [comment]
I can't reproduce it, but I see you're using a custom `dm-text` component, so that might be a reason?!

**Comment by Joshmamroud** [comment]
@artf I don't believe so. Here is the configuration of the dm-text component type
``` javascript
{
  extend: 'text',
  model: {
    defaults: {
      name: 'Text',
      traits: [],
      editable: true,
      droppable: false,
      textable: true,
      style: {
        padding: '10px',
        width: '100%',
        height: 'auto',
      },
      stylable: [
        'background-color',
        'page-break-inside',

        'color',
        'text-align',
        'font-size',
        'font-family',
        'font-weight',
        'line-height',

        'border-width',
        'border-color',
        'border-style',

        'padding',
        'padding-top',
        'padding-right',
        'padding-bottom',
        'padding-left',

        'border-top-left-radius',
        'border-top-right-radius',
        'border-bottom-right-radius',
        'border-bottom-left-radius',
      ],
    },
  },
};
`
Do you see anything here that might be causing it?

**Comment by artf** [comment]
mmm can you try to remove the style from the definition? I think some kind of style triggers chrome to add that element... indeed I've also found [this](https://stackoverflow.com/questions/16262812/delete-content-of-contenteditable-div-add-strange-font-element)

**Comment by maxtsh** [comment]
Hello.
I've got the same issue here though I'm not using any custom dm-text component and its just main text from newsteller plugin. 
Whenever I copy some text from somewhere in browser and paste it in the text node, it behaves like above making nested <font /> and <span /> tags causing style manager not to work on them because it targets parent div elm which can't affect children.

any help is appreciated.

@artf
