### ISSUE TITLE
BUG: Canvas scroll to top of the page when I try to drag an element from the last sections

### ISSUE THREAD

**Issue by josfh2005** [artf/grapesjs#3134]
**Version:**
0.16.27

**Are you able to reproduce the bug from the demo?**

[ X] Yes
[ ] No

**What is the expected behavior?**
When a try to drag a component the canvas should not scroll to the top of the page.

*Describe the bug **detailed***
Whenever I try to drag a component that is in the last sections of the page, the canvas scroll to the top. Sometime this just happens the first time but other time always, maybe has to do with the component type.

**Comment by artf** [comment]
Hi José, are you able to provide a screencast of your issue? I've tried to drag the last section of the template but seems all good to me

**Comment by josfh2005** [comment]
Hi @artf ,

You can check it out here https://recordit.co/vn1ZVN6J1N, is no a section it happens with any element but only the first tiem I try to drag something.

**Comment by artf** [comment]
Ah ok, only the first time, I've got it now on my side too 👍
