### ISSUE TITLE
[Help Wanted] How to easily override existing component ?

### ISSUE THREAD

**Issue by archerbj** [artf/grapesjs#3135]
For example, I want to add a double click event handler on the default video component to open the assets manager.

```
let v = editor. DomComponents.getType('video')
let view = v.view()
```
My basic idea was to get the view definition of the video component and add `events` + handler.
At last, set it back to the video component.

Unfortunately, this idea failed in the first step. `v.View()` gives me an error 

```
TypeError: this._ensureElement is not a function
    at Object.e.View (grapes.min.js?e1c1:2)
    at Object.r (grapes.min.js?e1c1:2)
    at Object.r (grapes.min.js?e1c1:2)
    at Object.r (grapes.min.js?e1c1:2)
    at VueComponent.configVideo (HelloWorld.vue?18db:218)
    at VueComponent.mounted (HelloWorld.vue?18db:88)
    at invokeWithErrorHandling (vue.esm.js:formatted:1729)
    at callHook (vue.esm.js:formatted:3882)
    at Object.insert (vue.esm.js:formatted:2877)
    at invokeInsertHook (vue.esm.js:formatted:5887)
```

I am new to this project and barely know about Backbone.js.
Would you please offer me some suggestions?

**Comment by Joshmamroud** [comment]
@archerbj here's a demo of what you're looking for: https://codesandbox.io/s/sharp-easley-3hrdn?file=/index.js
You want to create a new `Component Type` that extends the `video` type then add the `dblclick` event handler to the view. Once you've got that, then you create a block that uses your new component type. 

Here is some documentation on [how to extend component types ](https://grapesjs.com/docs/modules/Components.html#define-custom-component-type) and here's the guide on [creating a custom block](https://grapesjs.com/docs/modules/Blocks.html#custom-render)

Hope this helps.

Josh

**Comment by archerbj** [comment]
> @archerbj here's a demo of what you're looking for: https://codesandbox.io/s/sharp-easley-3hrdn?file=/index.js
> 
> You want to attach the functionality to the `component type` itself rather than trying to find all instances of that component and add it on some change. So to do that, create a new `Component Type` that extends the `video` type then add the `dblclick` event handler to the view. Once you've got that, then you create a block that uses your new component type.
> 
> Here is some documentation on [how to extend component types ](https://grapesjs.com/docs/modules/Components.html#define-custom-component-type) and here's the guide on [creating a custom block](https://grapesjs.com/docs/modules/Blocks.html#custom-render)
> 
> Hope this helps.
> 
> Josh

Thanks a lot! I missed that part in the docs. I'll try to figure it out

**Comment by abulka** [comment]
@Joshmamroud Thanks for that running example. Yours is the only example I can find of using the `extend` feature mentioned in the documentation. 

Your example is very simple and zen - however it merely shows adding a `dblclick` handler to the video component and does not show adding additional component attributes or properties and traits. Any chance you could explain that or provide an example, as I am struggling to comprehend how to use `extend` - as I've mentioned in #3060.

**Comment by Joshmamroud** [comment]
> @Joshmamroud Thanks for that running example. Yours is the only example I can find of using the `extend` feature mentioned in the documentation.
> 
> Your example is very simple and zen - however it merely shows adding a `dblclick` handler to the video component and does not show adding additional component attributes or properties and traits. Any chance you could explain that or provide an example, as I am struggling to comprehend how to use `extend` - as I've mentioned in #3060.

@abulka Sure. Could you provide some detail about your use case, what your desired functionality is, and even a sample of your implementation? Then I'll do my best to help fill in the gaps.

**Comment by abulka** [comment]
Thanks @Joshmamroud - I'd like to add an additional attribute `info1` to a text or input (or any default) component, without losing their existing default `id` and `title` attributes.

Then I want to also add a property (not an attribute) `info2` to that component.

Then I want to expose both `info1` and `info2` as traits, together with the existing default `id` and `title` traits.

**Comment by Joshmamroud** [comment]
@abulka I believe this should do the trick: [Example](https://codesandbox.io/s/silly-frog-jtqw9?fontsize=14&hidenavigation=1&theme=dark)

I couldn't find a better way to preserve the original traits other than spreading them from the default Dom Component Type. 

As far as your new traits, `info1` is straightforward as it will use the default functionality and be interpreted as an attribute. For  `info2`, all you need to do is set the `changeProp` property to true when declaring the new trait as explained [here](https://grapesjs.com/docs/modules/Traits.html#add-traits-to-components).

I hope this makes sense and helps. Let me know if you have any questions.

**Comment by abulka** [comment]
Thanks @Joshmamroud - that's a great example. The use of `...defaultModel.prototype.defaults.traits` is not mentioned in the documentation on extending components, which led me to think - what does the `extend: text` field actually do? Leaving it out in your example makes no difference and your example still works without it! 

Investigating further, I tried to extend the link component, and would expect the usual 'link' traits of `title, href, target` plus our extra `info1, info2` traits.
```javascript
// Lets try to extend a link component with those extra traits
domComps.addType("custom-link", {
    extend: "link",
    isComponent: el => el.tagName == 'A',
    model: {
        defaults: {
            info2: "default value for info 2",
            traits: [
                // ...defaultModel.prototype.defaults.traits,
                ...domComps.getType('link').model.prototype.defaults.traits,
                {
                    label: "Info 1",
                    type: "text",
                    name: "info1"
                },
                {
                    label: "Info 2",
                    type: "text",
                    name: "info2",
                    changeProp: true
                }
            ],
            attributes: { info1: "default value" }
        },
        init() {
            this.on("change:info2", this.handlePropChange);
        },
        handlePropChange(e, changedValue) {
            console.log("Current value of info2 ", changedValue);
        }
    }
});

editor.BlockManager.add("custom-link-block", {
    label: "custom-link",
    attributes: { class: "fa fa-rocket" },
    content: {
        type: "custom-link",
        content: 'hyper please click here',
    }
});
```
which works OK. Here the meaning of `extend: "link"` became clear to me. If you don't extend from `link`, when you export html you get the erroneous
```html
<div info1="default value" href="here" id="iu79j">hyper please click here</div>
```
instead of
```html
<a info1="default value" href="here" id="i1bwp">hyper please click here</a>
```

## Musings on .model.prototype.defaults.traits

As I really like having the `id` trait in my components, and because it is missing from the `link` component, I tried inheriting traits from both `default` and `link`
```javascript
traits: [
  ...domComps.getType('default').model.prototype.defaults.traits,
  ...domComps.getType('link').model.prototype.defaults.traits,
    {
        label: "Info 1",
        type: "text",
        name: "info1"
    },
    {
        label: "Info 2",
        type: "text",
        name: "info2",
        changeProp: true
    }
],
```
which unfortunately resulted in two `title` traits (one from default and one from link).  Not good, but promising. So I investigated the data type of `.traits` and was surprised to discover it was merely an array of strings, so tried just
```javascript
traits: [
  ...["id"],  // <-- does this work? yes!
  ...domComps.getType('link').model.prototype.defaults.traits,
    {
        label: "Info 1",
        type: "text",
        name: "info1"
    },
    {
        label: "Info 2",
        type: "text",
        name: "info2",
        changeProp: true
    }
],
```
which worked and I got the full range of `id, title, href, target, info1, info2`.  

Encouraged by this, I pushed my luck and tried replacing all references to the `model.prototype.defaults.traits` expression like this:
```javascript
traits: [
    ...["id", "title", "href", "target"],  // <--
    {
        label: "Info 1",
        type: "text",
        name: "info1"
    },
    {
        label: "Info 2",
        type: "text",
        name: "info2",
        changeProp: true
    }
],

```
which also worked - I got the full range of `id, title, href, target, info1, info2`. Everything in the traits UI seemed to work correctly and the exported html was correct.

**Comment by Joshmamroud** [comment]
@abulka Thanks for the update and explanation. I didn't know that you could simply add `"id"` to the list of traits without it breaking the default behavior. Hopefully, I won't forget it the next time I need it lol.

Glad it all worked out for you!

**Comment by abulka** [comment]
For those that are interested, here are more musings and explorations on what`extend` is really good for. Ideally perhaps @artf or one of the other core Grapesjs developers could clear this up?

The following custom link component has been created **without** the use of `extend` and seems to show that specifying _either_
- `extend: "link"` or
- `model.defaults.tagname: 'a'`
is enough to define a custom link component properly. You seemingly don't need to use `extend`.

Also, amazingly, all link component traits like target etc. are available even if you don't specify extend: "link" (even the 'target' dropdown trait UI appears OK).

```javascript
function customLinkPlugin(editor) {

    editor.DomComponents.addType("customLink", {
        // extend: "link", // alone fixes the canvas <a> rendering and correct export of <a> - but can use tagName instead
        model: {
            defaults: {
                tagName: 'a', // alone fixes the canvas <a> rendering and correct export of <a>
                traits: [
                    "id",
                    "title",
                    "href", 
                    "target",  // drop down UI link traits available even without use of 'extend' !!
                    "data-info1"  // custom attribute
                ],
            },
        },
    });
}

const editor = grapesjs.init({
    container: '#gjs',
    fromElement: 1,
    height: '100%',
    storageManager: { type: 0 },
    plugins: ['customLinkPlugin']
});


// create initial component
editor.addComponents(
    {
        type: 'customLink',
        classes: ['cls'],
        content: 'my custom hyperlink',
        attributes: { href: "somewhere", 'data-info1': "whatever" }
    },
);

// auto select our demo component
editor.on('load', () => {
    editor.select(editor.getWrapper().find('[data-gjs-type="customLink"]')[0])
});

// make settings panel the default
editor.Panels.getButton('views', 'open-tm').set('active', true)
```

See fiddle https://jsfiddle.net/tcab/pb8dz94L/

So respectfully, what is `extend` really good for, when you can e.g. define a custom `link` component without using it?

**Comment by artf** [comment]
Well, the `extend` takes all the properties and methods from the extended component. Indeed, your `customLink` is a simple component with the `<a>` tag and a bunch of text traits (strings fallback to simple text traits) to edit its attributes, but, for example, you can't edit its text in the canvas by double-clicking the link, that is because this functionality is generally included in the `text` component (`link` extends `text`).

ps. `target` transformation is due to an old [thing](https://github.com/artf/grapesjs/blob/dev/src/trait_manager/model/TraitFactory.js)

**Comment by addlistener** [comment]
@Joshmamroud have you found a way to make all <video /> elements by default custom-video? 

In my case I take external html input and cannot control the component type.
