### ISSUE TITLE
BUG: When I select an particular element I'm not getting its styles. This issue happens only with some elements.

### ISSUE THREAD

**Issue by Asha1597** [artf/grapesjs#3137]
## Not getting styles of the selected element

Here is my code, 
        const model =  editor.StyleManager.getModelToStyle(component);
        let styleObject = model.getStyle();
        console.log("styles", styleObject)

**Version:**

0.14.49

**Are you able to reproduce the bug from the demo?**

[X] Yes
[ ] No

**What is the expected behavior?**

When an element is selected I should get the styles of the selected element. 

**What is the current behavior?**

When an element is selected  I'm not getting any styles only empty object.

**Are you able to attach screenshots, screencasts or a live demo?**

[X] Yes (attach)
[ ] No

Here's the screenshot of actual and expected result, 
## Actual
![Screenshot from 2020-11-12 16-54-12](https://user-images.githubusercontent.com/74352383/98934282-d72d4880-2507-11eb-96fa-4f48c2d0e0b6.png)

## Expected
![Screenshot from 2020-11-12 16-54-41](https://user-images.githubusercontent.com/74352383/98934286-d85e7580-2507-11eb-9244-54ada73a1628.png)

**Comment by artf** [comment]
First of all, you need to upgrade your grapesjs version (you're using a 2 years old one), then you have to provide a live demo of the issue.
