### ISSUE TITLE
FEAT: Disable <table> being auto amended during save

### ISSUE THREAD

**Issue by adamwpe** [artf/grapesjs#3139]
I'm getting an issue, when saving a custom HTML component (just a table), grapes JS will modify it.

before save
![image](https://user-images.githubusercontent.com/49768920/99049128-62512180-258e-11eb-9213-10bc30c037b0.png)

after save.
![image](https://user-images.githubusercontent.com/49768920/99049054-464d8000-258e-11eb-9545-726b0348fa4c.png)

So I want to be able to insert a table like because I would like to intergate it with twig (a templating language) :

```
<table>
{% for item in items %}
   <tr>
   {{ item.name }}
   </tr>
{% endfor %}
</table>
```

I believe it is linked to #606, but I can't see if that helps this problem I'm having.

It's also linked to #1939 

Is there a possibility of disabling this feature?

**Ideally, have a way to have a html component that the content cannot be modified in any way by grapesjs.**

Thanks,
Adam

**Comment by adamwpe** [comment]
Ah, If I use this https://github.com/artf/grapesjs-custom-code, it works :)

**Comment by artf** [comment]
You can't insert invalid HTML. If you need to handle stuff like that, you have to create a [custom component](https://grapesjs.com/docs/modules/Components.html) which then will output the custom code.
