### ISSUE TITLE
[Question] Disable editing elements by default

### ISSUE THREAD

**Issue by telliott22** [artf/grapesjs#314]
Hi,

Is it possible to disable editing on all elements by default, then opt in elements that I do want to be editable?

Thanks,
T

**Comment by artf** [comment]
What do you mean with `editing`? Editing text or like moving around/removing a component?

**Comment by telliott22** [comment]
Both. I only want certain elements within a component to have editable text, and only the outer most element of each component to be draggable/droppable/removable. I know I could disable these things on each element individually using data tags, but since the components will have quite a few elements, I thought the best way to achieve this would be disable everything by default, and use data tags to enable the things that I want editable on each element.

**Comment by artf** [comment]
You might want to update your component types (Components#update-component-type)[https://github.com/artf/grapesjs/wiki/Components#update-component-type], specifically, updating the `default` one you will cover most of them
