### ISSUE TITLE
Interactive component in canvas

### ISSUE THREAD

**Issue by ZeroCoolHacker** [artf/grapesjs#3140]
I am building a quiz builder plugin using grapesjs. I was wondering if we can add a component which is interactive and adds new components when clicked.
For example
![image](https://user-images.githubusercontent.com/18724529/99068996-56d21a80-25cf-11eb-8aa7-29ca26ac4e6c.png)
Something like this. When dropped, there are no inputs but when clicked add new field, the input appears.

Is it possible? how?

**Comment by artf** [comment]
You have to [extend the View](https://grapesjs.com/docs/modules/Components.html#view) of your custom component
