### ISSUE TITLE
Loading dynamic content

### ISSUE THREAD

**Issue by webdevhayes** [artf/grapesjs#3141]
I really apologise if this has been covered previously. I have searched the issues and also read the documentation quite extensively and maybe I am not just understanding it correctly. 

I understand you can do run a script in the page builder to load the content however that content/html will be saved once I click save? which means on my front end would load out of date content/html?

Would you be able to point me in the direction to understand this more and have the content always dynamically loaded through an ajax call? I am using laravel and I have the save functionality all working just fine. 

Again apologies if this has been covered already.

**Comment by artf** [comment]
I think you have to read [this guide](https://grapesjs.com/docs/modules/Storage.html)

**Comment by anuragk15** [comment]
Did you find the solution?
I have a similar issue. For example, when I write blog and store them in my database. Now whenever someone visits my landing page(made with Grapesjs) I want them to see my latest blog there. Also, if some end-user comes to site, I will just have to send the Grapejs html and css right? no components?
