### ISSUE TITLE
AssetManager rendering issue

### ISSUE THREAD

**Issue by awais786327** [artf/grapesjs#3142]
@artf this is the same [issue #2760](https://github.com/artf/grapesjs/issues/2760) that has already been addressed before, is this wrong or am i doing? i expected assets not to be shown but they are all visible

![image](https://user-images.githubusercontent.com/12613564/99156432-99d0e280-26e2-11eb-8289-d76d66af2ad1.png)

this is my code and I am using version of `"grapesjs": "^0.16.27",`

![image](https://user-images.githubusercontent.com/12613564/99156485-04821e00-26e3-11eb-8463-ca22280f5990.png)

**Comment by artf** [comment]
@awais786327 provide a live demo of the issue, please
