### ISSUE TITLE
[Question] Swap default factories 

### ISSUE THREAD

**Issue by antman3351** [artf/grapesjs#3144]
Hello, I'm using GrapesJs to template HTML for printing so I need the measurements in mm. 
Is there a way to swap the default factory in the StyleManager? maybe pass it in the options?

Thanks,
Antonio

**Comment by artf** [comment]
No, you can't, you just need to configure your properties in the StyleManager configuration (example configuration can be found [here](https://grapesjs.com/docs/getting-started.html#style-manager))
