### ISSUE TITLE
FEAT: how to edit a button if the button has an action (opening a modal window)?

### ISSUE THREAD

**Issue by sashapawlow726** [artf/grapesjs#3145]
I have a html template. the html template has a button. when you click on the button, an event occurs (opening a modal window). Is it possible to visually change the appearance of a button without firing an event? With allowScript: 0, I can edit the appearance of the button, but in this case, the event does not fire (opening a modal window). In case of allowScript: 1, an event is triggered (opening a modal window), but there is no way to edit the appearance of the button. There were ideas to switch between allowScript 0 and allowScript 1, but allowScript removes all js from the page.

**Comment by artf** [comment]
You have to create a [custom component](https://grapesjs.com/docs/modules/Components.html) for that button if it requires custom logic/behavior from what the original HTML does
