### ISSUE TITLE
There are so many clicks required to enable RTE can i edit text with just single click

### ISSUE THREAD

**Issue by fahadali1** [artf/grapesjs#3146]
There are so many clicks required to enable RTE can i edit text with just single click 
i tried by adding attribute contenteditable but storage manager not recognize text changes that way plz hlep

**Comment by artf** [comment]
You can extend the Text Component View and trigger onActive with a click instead of dblclick
https://github.com/artf/grapesjs/blob/d3256e621bb43a537213ffcd86b10dc0bd070c0b/src/dom_components/view/ComponentTextView.js#L7-L10

**Comment by fahad157** [comment]
@artf  I tried by changing it to click but it not working for me please help
![image](https://user-images.githubusercontent.com/80100955/111276504-35ef0400-8659-11eb-8507-968d8b71eaf1.png)

**Comment by vidhii16** [comment]
@artf I've followed the steps closely, but I'm still encountering the same issue. If you could offer any additional guidance or help, it would be greatly appreciated.

**Comment by antoineando-zenchef** [comment]
@vidhii16 @fahad157 
I was able to get it to work using this code:

<img width="758" alt="image" src="https://github.com/user-attachments/assets/2f9418e8-66f4-43ef-a5ac-428ede52e8a9" />
