### ISSUE TITLE
BUG: Background layers empty in reload editor

### ISSUE THREAD

**Issue by MarksEliel** [artf/grapesjs#3149]
Version: Last

In the demo the bug does not appear, I believe that for using localstorage for storage.

Grapesjs works normally, with background, but when I insert the background layers, except, everything is displayed correctly.

The problem is that when I reload the editor, it does not show the layers that were created, but everything is displayed normally, the problem is that it is not possible to edit again, because the layers do not appear.

See the video for more details.

https://youtu.be/F_YRlJpONSM

**Comment by artf** [comment]
> In the demo the bug does not appear, I believe that for using localstorage for storage.

No, using local storage or remote one has no difference as the JSON structure to use is the same. 
Indeed, I guess you're loading back the HTML instead of the JSON (as explained here https://grapesjs.com/docs/modules/Storage.html#store-and-load-templates)
