### ISSUE TITLE
FEAT: Is there a way or tutorial how we can integrate in october cms ?

### ISSUE THREAD

**Issue by michaelVictoriaDev** [artf/grapesjs#3150]
## WARNING
READ and FOLLOW next 3 steps, then REMOVE them before posting the issue

1. Follow CONTRIBUTING Guidelines https://github.com/artf/grapesjs/blob/master/CONTRIBUTING.md
2. Do a quick SEARCH first, to see if someone else didn't open the same issue
3. All relative statements/questions have to be filled/answered, otherwise, the issue might be CLOSED
4. JSFiddle Starter template https://jsfiddle.net/szLp8h4n
5. CodeSandbox Starter template https://codesandbox.io/s/1r0w2pk1vl

*Describe your feature request **detailed***
Tutorial or documentation how to integrate in cms

**Comment by artf** [comment]
There is already a plugin for October CMS https://octobercms.com/plugin/pkurg-pagebuilder
