### ISSUE TITLE
QUESTION: Position of selector manager.

### ISSUE THREAD

**Issue by theSC0RP** [artf/grapesjs#3151]
Hi, @artf. I was going through the getting started guide and the selector manager is placed below the style manager.
![Screenshot from 2020-11-23 13-40-46](https://user-images.githubusercontent.com/30771519/99940268-d0b59100-2d91-11eb-8ce9-f4027fed58ea.png)

How do I position the selector manager above the styles manager?

**Comment by artf** [comment]
As you can see from the example
```js
selectorManager: {
    appendTo: '.styles-container'
  },
 styleManager: {
    appendTo: '.styles-container',
```
Both of them append the element inside the same container. You can simply create different containers
```html
<div class="styles-container">
  <div class="styles-container-t"></div>
  <div class="styles-container-b"></div>
</div>
```
```js
selectorManager: {
    appendTo: '.styles-container-t'
  },
 styleManager: {
    appendTo: '.styles-container-b',
```
