### ISSUE TITLE
BUG: the blue outline (gjs-hovered) is not following its parent during scrolling

### ISSUE THREAD

**Issue by fq-selbach** [artf/grapesjs#3152]
**Version: 16.27**

**Are you able to reproduce the bug from the demo?**

[x ] Yes
[ ] No

**Describe the bug:**

I discovered an issue with `gjs-hovered`, the class that handles the mouse-hover outline for elements. Sometimes the blue outline will move relative to its parent during scrolling .
Check out this JsFiddle (and scroll with mouse-wheel): https://jsfiddle.net/vb7r1zns/

It seems to happen only when the HTML code starts with another full width/height DIV:
```
<div id="gjs">
<div style="width: 100%; height: 100%;">
...
```

**What is the expected behavior?**

The blue outline should always be exactly matching its parent element, no matter if there is an overflow or scrolling.

**Are you able to attach screenshots, screencasts or a live demo?**

[x ] Yes (attach)
[ ] No

https://jsfiddle.net/vb7r1zns/

**Comment by lofcz** [comment]
Would be nice to have this fixed, not the end of the world, but mildly annoying.

**Comment by matteocollina** [comment]
any news?

**Comment by artf** [comment]
I'm closing this one as it was actually already fixed, indeed the old demo is working now properly.
You might still face the issue if your editor is placed in a scrollable container, in that case, use this option please: 
https://github.com/artf/grapesjs/blob/dc45604962e4e6a4a075f19d5de67090bac15fa5/src/editor/config/config.js#L157-L163
