### ISSUE TITLE
FEAT: adding Dynamic Data Blocks

### ISSUE THREAD

**Issue by excitedbox** [artf/grapesjs#3153]
I am considering doing this one myself and as this has been requested so often I wanted to ask if this is already being worked on and if not maybe people would like to give some input.

The way I picture it working is kind of like a form with a container block where you define the data source, method (post/get) for getting the key and if it is a one time data item or a looped item like a list or a set of cards. Then you would insert a dynamic template block with placeholders for your data items which define the columns. For a list that would mean a table row and for a set of cards it would be a card block with the content replaced by the column ids.

This could also be used to set the default value for forms, process form responses into a DB, and open up a host of other content possibilities.

My questions are 
- Should I use a template engine to make it easier on myself but that would require an extra dependency.
- Is it possible to make a sub canvas for creating the template while pulling components from the main sidebar?
- Should I separate the db script instead of using the storage manager since the output site might not use the same server
- Which DB technology is preferred? Mysql is easiest for me but json or csv might be better for mostly static sites. For users of a website builder managing a mysql db might be difficult.

**Comment by artf** [comment]
This kind of things could be done via plugins but I can't reply to your questions, are totally off-topic and it's up to your knowledge find the right answer (maybe try to ask on StackOverflow)
