### ISSUE TITLE
Hide elements when i click eye icon in Open Layer Manager

### ISSUE THREAD

**Issue by phamhongphuc1999** [artf/grapesjs#3154]
I want to see the code handle event hide or delete elements. Where can i find it?
<img width="958" alt="Capture" src="https://user-images.githubusercontent.com/56115755/99949266-509d2480-2dad-11eb-8203-51432975b4d3.PNG">

Thanks so much!

**Comment by artf** [comment]
Here https://github.com/artf/grapesjs/blob/d802eba08559a3e1c7830e937a78b0b2a417f2e4/src/navigator/view/ItemView.js#L12-L22
