### ISSUE TITLE
BUG: 

### ISSUE THREAD

**Issue by pranay2210** [artf/grapesjs#3157]
I want to apply script to rte element which is select html element, on selecting the value for from one select field the dynamic values should get appended to other select field but the script is not working in rte 
![Screenshot 2020-11-25 at 1 30 28 PM](https://user-images.githubusercontent.com/37976696/100198880-77309c00-2f22-11eb-93ad-83ba83da06ba.png)

```
 rte.add('custom-parentkey', {
                icon: htmlForParent,
                  // Bind the 'result' on 'change' listener
                event: 'change',
                result: (rte, action) => {
  // Here I want to get the field value and get the result dynamically and append it to other select field but the script 
is not working
 alert(JSON.stringfy(rte))
//rte.insertHTML("<first>HELLLLLOOOO</first>")
                },
                update: (rte, action) => { action.btn.firstChild.value = "";}
              })
```
             rte.add('custom-childkey', {
                icon: htmlForChild,
                  // Bind the 'result' on 'change' listener
                event: 'change',
                result: (rte, action) => {},
                // Reset the select on change
                update: (rte, action) => { }
              })

I even tried initialising {allowScript:1} in the editor.init() still didn't work

**Comment by artf** [comment]
Maybe because it's `stringify` and not `stringfy`...
