### ISSUE TITLE
[Question] Is there any way to get the parser errors other than from console log

### ISSUE THREAD

**Issue by sathyanarayananaCES** [artf/grapesjs#3159]
I am using the latest GrapesJS (v0.16.27). As per the fix for the issue, (#2029) the exception has been caught and logged into the console.

Is there any way where we can get to know about the errors other than from console log?

Something similar to **asset:upload:error**, if we have **parse:error**, it would be helpful to handle the errors in a custom way. If we already have a way to handle this, please let me know.

**Comment by artf** [comment]
Usually, the error doesn't come from the parser but from the creation of the DOM (eg. the editor creates the element by using `setAttribute`). You can catch the editor's errors by listening to the log event
```js
editor.on('log:error', (err) => console.log('error from the editor', err))
```
Here, for example, you can put your logic (eg. by reading the error) and show the appropriate response
