### ISSUE TITLE
[Question] Add toggle-move label in custom setting panel in Vue

### ISSUE THREAD

**Issue by congweibai** [artf/grapesjs#3160]
Version: ^0.16.18

This question is intended to extract layer moving function to custom one.

I only want to given components could be seen in this components, and children components could be reorder in the panel.

Assume these components are in same level. My code will be like this: 

![Reorder](https://user-images.githubusercontent.com/53634020/100399696-a91d3c00-30a3-11eb-8c48-107480ec4746.png)

I have seen reorder can be happened in Layers. Is anywhere I can get this functions? 

Thanks in advance for any feedback or insight

**Comment by artf** [comment]
No, in this case, you have to handle the sorting on your side
