### ISSUE TITLE
BUG: Editor Undo is removing collection and unable to replace the component

### ISSUE THREAD

**Issue by ssmanoj-grapes** [artf/grapesjs#3161]
The collection of the selected component before Undo
![element-collection-before-u](https://user-images.githubusercontent.com/75111879/100419275-467b6e80-30aa-11eb-8df4-10e210d41689.png)

The collection of the selected component after Undo
![element-collection-after-un](https://user-images.githubusercontent.com/75111879/100419319-55622100-30aa-11eb-8272-baebedf9313e.png)

Code to replace the component with new component
![code](https://user-images.githubusercontent.com/75111879/100419345-6317a680-30aa-11eb-9861-d26d01772e99.png)

**Uncaught TypeError: n.getEl is not a function and Uncaught TypeError: t.getSelectors is not function** are the errors reported on save. I’m unable to replace the selected component with new component.

**Comment by artf** [comment]
Sorry, but without a reproducible demo, this issue doesn't make sense to me

**Comment by ssmanoj-grapes** [comment]
Hi artf,

Please find the demo video of the issue [grapejs-issue.zip](https://github.com/artf/grapesjs/files/5630421/grapejs-issue.zip).

**Comment by artf** [comment]
Ok, as you're not able to create a reproducible demo, I have to close this...
