### ISSUE TITLE
Button switcher to editor.allowsCripts

### ISSUE THREAD

**Issue by sashapawlow726** [artf/grapesjs#3162]
Hello, @artf ! :) Maybe you can help with grapesjs. I have buttons which has own scripts(e.g. opening modal window by click). And if I set property allowScripts: 0 - I can to edit these buttons, but if editor.allowScripts == 1, buttons execute logic(e.g. opening modal window) and I can't to edit buttons in that case. I found a great solution - it's switch property allowScripts = 0 : 1, but changes are only applied after page reload. How can I switch scripts? p.s execute command editor.refresh() after change a value allowScripts does not bring results

![Screenshot_24](https://user-images.githubusercontent.com/56075186/100451821-17282a00-30c9-11eb-82b1-7f96e17e1be8.png)

**Comment by artf** [comment]
I'd recommend creating a custom component for those buttons to handle the logic with scripts

**Comment by sashapawlow726** [comment]
@artf  thank you very much! :+1:
