### ISSUE TITLE
FEAT: Shape Divider for GrapesJS

### ISSUE THREAD

**Issue by MarksEliel** [artf/grapesjs#3163]
Is there grapedrop shape divider plugin for grapesjs?

Is there a website that sells plugins for grapesjs?

**Comment by artf** [comment]
Nope.
Anyway, you just need to create a trait (as a prop) and update the component contents (eg. with the SVG of a shape divider) on its change

**Comment by MarksEliel** [comment]
Is there an example model? I can't understand the documentation.

**Comment by Abhisheknanda1344463** [comment]
Hi, @MarksEliel  Did you manage to get it?

**Comment by Abhisheknanda1344463** [comment]
@MarksEliel  I've created an plugin for shape-divider
https://www.npmjs.com/package/grapesjs-shape-divider
FYI @artf

**Comment by MarksEliel** [comment]
> Hi, @MarksEliel Did you manage to get it?

Wow, I received a notification from github this morning, when I saw it was your link, thank you very much, it was amazing! congratulations!

Do you want to develop other plugins?

**Comment by Abhisheknanda1344463** [comment]
Yes @MarksEliel  For sure
Let me know which plugin you want to develop.

**Comment by MarksEliel** [comment]
> Yes @MarksEliel For sure
> Let me know which plugin you want to develop.

I have several ideas, one of which would be a plugin for fontawesome and even other icon libs

**Comment by Abhisheknanda1344463** [comment]
@MarksEliel  okay that's great can we communication on skype or some other plarform?

**Comment by MarksEliel** [comment]
Telegram? https://t.me/MarksEliel

**Comment by Abhisheknanda1344463** [comment]
https://www.npmjs.com/package/grapesjs-shape-divider

FYI @artf

**Comment by micker** [comment]
@Abhisheknanda1344463 the project is dead ? it doesn't works anymore ...

**Comment by Abhisheknanda1344463** [comment]
@micker  Earlier, I've made the repo private by mistake that's why it was not working.
It's working fine now.
