### ISSUE TITLE
FEAT: `grapesjs-plugin-ckeditor` version

### ISSUE THREAD

**Issue by mcottret** [artf/grapesjs#3164]
Hi @artf !

A while ago you've merged the following PRs:

- https://github.com/artf/grapesjs-plugin-ckeditor/pull/39
- https://github.com/artf/grapesjs/pull/2977

Related to [this issue](https://github.com/artf/grapesjs/issues/2916).

Would it be possible to version `grapesjs-plugin-ckeditor`, so that the fix could be included ?

Thanks in advance !

**Is there an alternative at the latest version?**

[ ] Yes
[ x ] No

**Is this related to an issue?**

https://github.com/artf/grapesjs/issues/2916

**Comment by artf** [comment]
Done! 
Sorry, totally forgot about it 😬
