### ISSUE TITLE
BUG: Problem with copy and paste a node 

### ISSUE THREAD

**Issue by nanaya1** [artf/grapesjs#3166]
**Version:*0.16.27*

**Are you able to reproduce the bug from the demo?**

[ * ] Yes
[ ] No

**What is the expected behavior?**
   In the right panel and canvas, the pasted node should be after the copied node.

**What is the current behavior?**
  I copy a node. In the views-container(right panel), the pasted node is after the copied node. But in the canvas,  the pasted node is before the copied node. As shown below:
![image](https://user-images.githubusercontent.com/22161888/100718588-7c945780-33f6-11eb-9f8d-ef17fc192031.png)

*Describe the bug **detailed***
This bug occurs when there are spaces or carriage returns between html tags.
Because in the ‘grapesjs/src/dom_components/view/ComponentsView.js’，**addToCollection** Method uses js **childNodes** to get the child nodes. 
![image](https://user-images.githubusercontent.com/22161888/100721779-bf582e80-33fa-11eb-838d-b2b5dc1d1f5e.png)

In the Chrome browser, in addition to the complete label as a node, the content between the ending character ">" of one label and the starting character "<" of the next label (except comments, including any text, Spaces, carriage returns, tabs) are also considered a node.

**Are you able to attach screenshots, screencasts or a live demo?**
[ bug.mov.zip](https://github.com/artf/grapesjs/files/5621482/bug.mov.zip)

Can sombody help with this?
Thank you very much!

**Comment by artf** [comment]
I've tried locally but the node is placed correctly. Are you able to create a live demo, please?

**Comment by nanaya1** [comment]
Sorry, I did not elaborate on the scenario where this error occurred.
The components that come with grapesjs do not produce this error, because they don‘t have spaces，carriage returns or tabs.
I found this problem while customizing components.
I have customized a lot of my own components, and some of them will have this situation.
An example of the initialization of the custom component node that found this problem is as follows.
```
viewTemplate() {
    return '
      <form data-gjs-type="form-panel" class="form-panel">
      </form>
    '
  },
...
 onViewInit() {
    const comps = this.model.get('components');
    if (!comps.length) {
      comps.reset();
      comps.add('
        <div class="form-panel-group" data-gjs-type="form-panel-group"><label class="label">多/单选：</label><div data-gjs-type="select-comp" class="select-comp"></div></div>
        <div class="form-panel-group" data-gjs-type="form-panel-group"><label class="label">多选选择：</label><div data-gjs-type="mdc-checkbox-group" class="mdc-checkbox-group"></div></div>
       </div>
      ')
    }
    ...
  }
```
If you want to reproduce this problem in the grapesjs default component, you can enter a space between nodes through the “Editor as HTML” of the f12 Elements . as follows.
![live_demo](https://user-images.githubusercontent.com/22161888/100816087-561afe80-3480-11eb-9b23-67644d855824.gif)

**Comment by nanaya1** [comment]
@artf I accidentally closed the issue.

**Comment by artf** [comment]
If you edit the HTML in devtools you're breaking the state between the DOM and the editor, so what is happening is normal...
