### ISSUE TITLE
FEAT: Download / Export images - Love to use in classroom project

### ISSUE THREAD

**Issue by oleteacher** [artf/grapesjs#3168]
**What are you trying to add to GrapesJS?**

Ability to export images / images folder in zip download

*Describe your feature request **detailed***

GrapeJS would be an excellent tool in which grade school children use to create their own about me page.

Not sure how difficult it would be to add ability to include image folder in zip download. See see css is exported. but not the img folder.

Looked at the grapesjs-plugin-export / index.js and see where it adds css, but I am not strong enough in JS to add image export.

Thank you in advance for your time!

**Comment by artf** [comment]
Hi @oleteacher doing something like that, is not entirely possible due to security restrictions in browsers (eg. when the image is downloaded from another domain). You would need a server process that generates images for you.

**Comment by oleteacher** [comment]
Yes, we have a local server for the classroom. We just do not have our own IT support to help with things like this, very small school

Sorry to have bothered you.
