### ISSUE TITLE
How to remove the eye-slash button in preview mode?

### ISSUE THREAD

**Issue by niveth09** [artf/grapesjs#3173]
Hi @artf ! I have created a web builder using GrapesJS.  I want to remove the eye-slash button in preview mode and replace it with the back button. How to do it? Kindly please help me.

**Comment by artf** [comment]
I'd suggest [extending](https://grapesjs.com/docs/modules/Commands.html#extending) the original [Preview](https://github.com/artf/grapesjs/blob/dev/src/commands/view/Preview.js) command

**Comment by niveth09** [comment]
> I'd suggest [extending](https://grapesjs.com/docs/modules/Commands.html#extending) the original [Preview](https://github.com/artf/grapesjs/blob/dev/src/commands/view/Preview.js) command

Thank you for reply @artf  .  Is there any documentation or sample code about extending an existing command?

**Comment by robsonsobral** [comment]
> 
> 
> > I'd suggest [extending](https://grapesjs.com/docs/modules/Commands.html#extending) the original [Preview](https://github.com/artf/grapesjs/blob/dev/src/commands/view/Preview.js) command
> 
> Thank you for reply @artf . Is there any documentation or sample code about extending an existing command?

https://grapesjs.com/docs/modules/Commands.html#extending

**Comment by niveth09** [comment]
> > > I'd suggest [extending](https://grapesjs.com/docs/modules/Commands.html#extending) the original [Preview](https://github.com/artf/grapesjs/blob/dev/src/commands/view/Preview.js) command
> > 
> > 
> > Thank you for reply @artf . Is there any documentation or sample code about extending an existing command?
> 
> https://grapesjs.com/docs/modules/Commands.html#extending

Still, I don't get how to remove the icon. Can you show me a sample code? Thanks in advance.

**Comment by collindutter** [comment]
@niveth09 here is the code for extending the preview command without the eye button:

```
    const cmdVis = 'sw-visibility';
    commands.extend('preview', {
        run(editor, sender): void {
            this.sender = sender;
            this.selected = [...editor.getSelectedAll()];
            editor.select();

            if (!this.shouldRunSwVisibility) {
                this.shouldRunSwVisibility = editor.Commands.isActive(cmdVis);
            }

            this.shouldRunSwVisibility && editor.stopCommand(cmdVis);
            editor.getModel().stopDefault();

            const panels = this.getPanels(editor);
            const canvas = editor.Canvas.getElement();

            panels.forEach((panel) => panel.set('visible', false));

            const canvasS = canvas.style;
            canvasS.width = '100%';
            canvasS.height = '100%';
            canvasS.top = '0';
            canvasS.left = '0';
            canvasS.padding = '0';
            canvasS.margin = '0';
            editor.refresh();
            this.tglEffects(1);
        },
    });

```

**Comment by kerryj89** [comment]
I am trying to extend the `preview` command, what am I doing wrong?  I expected the following code below to run the normal preview command along with console output, but only console output runs.  How can I preserve the original preview statements?

```
editor.Commands.extend('preview', {
    run() {
        console.log("foo");
    }
});
```

The below works for me until someone can enlighten where my thought process went wrong.

```
editor.Commands.add('preview-ext', {
    run(e) {
        e.runCommand('preview');
        console.log("foo");
    }
});
```
