### ISSUE TITLE
BUG: Selection & active RTE not cleared when component is removed programatically

### ISSUE THREAD

**Issue by mcottret** [artf/grapesjs#3175]
**Version:** 0.16.30

**Are you able to reproduce the bug from the demo?**

[x] Yes
[ ] No

**Steps to reproduce:**

- Select a text component in the demo's canvas
- The selection box & RTE appear
- Open the console
- Execute `editor.setComponents('');`
- The component is removed, but the selection box & RTE are still present (see attached screenshot)

**What is the expected behavior?**

When programatically removing a selected component with an active RTE, the selection & active RTE should be cleared.

**What is the current behavior?**

Component selection & RTE stay active on top of an unexisting component. Component selection disappears when clicked, but the RTE does not & causes an error.

**Proposed solution:**

- Execute the [`ComponentTextView`'s `onDisable` handler](https://github.com/artf/grapesjs/blob/dev/src/dom_components/view/ComponentTextView.js#L57) when it's removed
- Add a generic remove handler for components, removing them from selection if appropriate

As always, I'd be happy to take care of the PR if this looks good to you !

**Are you able to attach screenshots, screencasts or a live demo?**

[x] Yes (attach)
[ ] No

<img width="1043" alt="Screenshot 2020-12-09 at 11 08 41 AM" src="https://user-images.githubusercontent.com/9916749/101615984-17042480-3a0f-11eb-9d17-465dfa9b72ba.png">

**Comment by artf** [comment]
Thanks @mcottret for the report. I've handled this on my side, so it should be fixed in the next release, but as always, thanks for your willingness to help :)
