### ISSUE TITLE
QUESTION/FEATURE REQUEST: Changing Selected Component Tooltip

### ISSUE THREAD

**Issue by anatoli-dp** [artf/grapesjs#3177]
Is there a way through the api to change the selected component tooltip or is that something that can only be done by editing the source? If so with the api please exlain as I am not bright enough to be able to effectively change the source and every time i try to make other changes I end up with errors when using the modified framework. If not please add this as a feature as This would be extremely useful for certain custom componenets.

**Comment by artf** [comment]
Hi, when you define a new component, you can customize its toolbar
```js
...
model: {
  defaults: {
    ...
    toolbar: [
      { attributes: { class: 'fa fa-arrow-up' }, command: () => alert('Hi') },
      ...
    ],
  }
}
```
You can also update the toolbar at runtime in this way:
```js
someComponent.get('toolbar').push({
 attributes: { class: 'fa fa-arrow-up' },
 command: () => alert('Hi')
});
```
but won't be stored (eg. on a refresh of the page), so I always suggest to think more in a component-oriented way.

**Comment by anatoli-dp** [comment]
Thanks, that is a big help to some of the things i want to add for my own
use.
