### ISSUE TITLE
AssetManager seems to load assets from cache and doesnt update (Question)

### ISSUE THREAD

**Issue by TheEightArms** [artf/grapesjs#3179]
Hi,
i've been trying to integrate Grapes for last few weeks into my VueJs project, but i got a question for the AssetManagement.

```
assetManager: {
    assets: ['http://localhost:3001/upload/hg_1920_1080.jpg'],
}
```

thats my simple assetManager configuration, for some reason it loads another Image i uploaded two weeks ago and doesnt update, no matter what i try. 
If i use assetManager.add('URL'), it says getAllVisible is one more, but it doesnt show anything. If i do assetManager.render() after adding, the html Element i  get in return, just shows me the old image from before. 
Any suggestions ? 

Thank You 

Daniel

**Comment by TheEightArms** [comment]
I found out, its loading its assets from the saved code and from the database, is there a possibility to tell the StoreManager not to load assets ? 

Thx

**Comment by gixid192** [comment]
@TheEightArms You can set storeManager to false in [init function](https://grapesjs.com/docs/getting-started.html#start-from-the-canvas)

**Comment by artf** [comment]
You can also avoid returning assets from your endpoint (where you load components and styles)
