### ISSUE TITLE
Is there a way to load blocks closed by default?

### ISSUE THREAD

**Issue by daniel-farina** [artf/grapesjs#318]
Hi guys, 

Excited to play and explore this code. Is there a way to load blocks collapsed? 

I noticed the style manager has properties for open = false, but I don't see it for blocks. 

I was able to make them all collapsed by default by changing this code

src/block_manager/view/CategoryView.js

```
  updateVisibility() {
    if(this.model.get('open'))
      this.**close**(); //used to be open by default
    else
      this.**open**();
  },
```

Thanks!

**Comment by daniel-farina** [comment]
It turns out there is a default value you can change in the model. 

src/block_manager/model/Category.js
```
var Backbone = require('backbone');

module.exports = Backbone.Model.extend({

  defaults: {
    id: '',
    label: '',
    **open: false,**
    attributes: {},
  },

});
```

but I'm not able to set it when I'm loading a new block. Still looking will  update soon.

**Comment by artf** [comment]
Hi Dan, when you add a block you can indicate the category and its state if you want
```js
editor.BlockManager.add('block-id', {
    label: 'Lable content',
    category: {
        id: 'some-cat', 
        label: 'Some cat', 
        open: true
    }
})
```

If you want to close all block categories opened by default just add this
```js
editor.BlockManager.getCategories().each(ctg => ctg.set('open', false))
```

**Comment by daniel-farina** [comment]
Thanks Artur!
Can;t wait to contribute once I get familiar with the code.
Dan

**Comment by rafael-chile** [comment]
Hi Artur! Is there a way to leave one category always open (state open)? So user can't collapse it.
