### ISSUE TITLE
[Question] Click issue on integrating grapesjs-style-bg plugin to the web builder

### ISSUE THREAD

**Issue by sathyanarayananaCES** [artf/grapesjs#3184]
I am using GrapesJS version (0.16.27) and have integrated **grapesjs-style-bg** plugin to the editor. The functionality works perfectly fine. But on clicking the tabs on the background property, click issue arises. Immediately it toggles the tab. 

Especially it occurs when we select Gradient option, I have integrated the plugin as mentioned in this [issue ](https://github.com/artf/grapesjs/issues/2858). I am not sure whether am I missing something here. It works perfectly fine in the GrapesJS demo.

On analysis it seems like the click event is getting fired multiple times, is there any hook where we can listen to the click icon of the tabs in the style-bg plugin or please let me know the approach to solve this issue in a better way

Please refer to the attached video to get  more clarity on the issue
[video.zip](https://github.com/artf/grapesjs/files/5678985/video.zip)

**Comment by artf** [comment]
Thanks for the video of the issue, but it doesn't help in any way to solve it. If you're not able to create a reproducible demo, I can't help.

**Comment by sathyanarayananaCES** [comment]
Thank you @artf  for taking a look at the video, will try to create a reproducible demo and attach it here.
