### ISSUE TITLE
BUG: Resize with percentage

### ISSUE THREAD

**Issue by kuhelbeher** [artf/grapesjs#3186]
Hello, there is a bug with resizing elements when their sizes are set with percentage:
![simplescreenrecorder-2020-12-11_15 46 17](https://user-images.githubusercontent.com/37115006/101912204-195eae00-3bca-11eb-9c8b-c202b61b9d1e.gif)

You can check this issue [here](https://codesandbox.io/s/grapes-resize-2ycel?file=/src/index.js)

**Comment by artf** [comment]
Not a bug, I've just never handled properly resizing with the percentage 🙃
A PR would be welcome
