### ISSUE TITLE
BUG:   changesCount is incremented, without changes applied

### ISSUE THREAD

**Issue by marcepoblet** [artf/grapesjs#3189]
[double-click.pptx](https://github.com/artf/grapesjs/files/5705054/double-click.pptx)

Is it possible that the "changesCount" parameter is not incremented when you only double click on a component?

The parameter "changesCount" is incremented when you double click and no changes are made.

I have attached a video in the pptx file, showing this behavior.

This is reproducible in any browser.

**Comment by artf** [comment]
Should be fixed in the next release
