### ISSUE TITLE
Event on selected Element

### ISSUE THREAD

**Issue by vmourya** [artf/grapesjs#319]
How can i fire an event on selected element when user edit the content.

**Comment by artf** [comment]
you can listen to changes with this (not only on selected elements)
```js
editor.on('component:update:content', model => {
  console.log('New content', model.get('content'));
  // do your stuff...
})
```

**Comment by telliott22** [comment]
Which event is fired when the element is selected? Not necessarily when the user edits content.

**Comment by daniel-farina** [comment]
That would be: **change:selectedComponent**

I did a search for: em.on( on the source code to see the different options available. 

```
 editor.on('change:selectedComponent', model => {
              console.log('New content selected', model.get('content'));
              // do your stuff...
          });
```

**Comment by telliott22** [comment]
Thanks!

**Comment by vmourya** [comment]
Thanks everyone for replying but my requirement was bit different .

I am using remote server for saving page content.

Default AutoSave events are:

    editor.on('storage:store', function(e) {
      // console.log('STORE ', e);
    })

OR

editor.on('component:update:content', model => {
  console.log('New content', model.get('content'));
  // do your stuff...
})

OR 

    editor.on('change:selectedComponent', model => {
      console.log('New content', model.get('content'));
      // do your stuff...
    })

But these all run when user select component, Drag/Drop component. 

Problem with these methods is  just that if user made changes (e.g changed text content) and refresh page without selecting other component then all text changes he recently made will lost.

For above case, solution i found is:
1. Bind keyup event on iframe inner containers, 
2. In keyup event callback, define interval that checks iframe content in every given duration.
3 If content is changed that it send data on remote server to save.


@artf : Let me know if there is a better way to achieve this.

Thanks

**Comment by artf** [comment]
I don't trigger any event on keyup so, at the moment, binding on iframe is the only way to do.
About refreshing the page, maybe you want to define your custom `onbeforeunload` function?!?
```js
window.onbeforeunload = e => {
     const comp = editor.getSelected();
     comp.view.disableEditing && comp.view.disableEditing()
     editor.store();
     return 1;
};
```

**Comment by vmourya** [comment]
Yes this could be a good solution for above case, but there are many other cases as page reload/crash or user can close browser tab direct instead refreshing.

So here is code snipper i used:

Created a command:

            id: 'commandName',
            run: function(){
              var keyUpStart = false;
              var iframe = document.getElementsByTagName('iframe')[0];
              var iframe = iframe[0];
              var innerDoc = iframe.contentDocument || iframe.contentWindow.document;
              divs = innerDoc.querySelectorAll("div");
              for(var i=0; i< divs.length; i++){
                var div = divs[i];
                div.addEventListener("keyup",function(e){
                  if(!keyUpStart){
                    console.log( "Start interval");
                    startInterval();
                    keyUpStart= true;
                  }
                });
                div.addEventListener("blur",function(e){
                  console.log("Stop interval");
                  stopInterval();
                  keyUpStart= false;
                });
              }
            }


And then here is rest code i added:


// SCRIPT START TO AUTO SAVE WHILE EDITING 
    editor.runCommand('commandName'); 
    var autoSaveIntervar;
    var updateTimigs = 3; // seconds as Numeric
    function startInterval(){
      autoSaveIntervar= setInterval(savePageContent, updateTimigs * 1000)
    }
    function stopInterval(){
      clearInterval(autoSaveIntervar);
    }

    var savePageContent = function(){
      var iframe = document.getElementsByTagName('iframe')[0];
      var innerDoc = iframe.contentDocument || iframe.contentWindow.document;
      var frameBody = innerDoc.querySelector('body');
      var style  = frameBody.querySelector('style');
      var htmlContent = frameBody.querySelector("#wrapper");
      data = {'gjs-html': htmlContent.innerHTML, 'gjs-css': style.innerText}
      $.ajax({
         url: "your remote url",
         type: "POST",
         contentType: "text/html",
         data: data,
         success: function(res){
           console.log(res);
         },
         error: function(res){
           console.log(res);
         }
      });
    }
    // SCRIPT END TO AUTO SAVE WHILE EDITING

@artf: Is it good to go with this code?

Thanks
Vijay M

**Comment by artf** [comment]
no @vmourya it's not good at all, try to add a new component and your code will not work.
`keyup` it's a bubbling event you don't have to add it on ALL elements and if you use GrapesJS API it's even much easier
```js
var timer;
...
run: function(editor) {
    editor.Canvas.getBody().addEventListener('keyup', e => {
        timer && clearTimeout(timer);
        timer = setTimeout(() => {
             const comp = editor.getSelected();

             // Store the current state of the focused text element
             if (comp.get('type') == 'text') {
               comp.set('content', comp.view.el.innerHTML);
             }

             // If you've configured the remote storage you can just call
             editor.store();
        }, 1000);
    });
     ...
}
```

**Comment by sakshigarg9** [comment]
> you can listen to changes with this (not only on selected elements)
> 
> ```js
> editor.on('component:update:content', model => {
>   console.log('New content', model.get('content'));
>   // do your stuff...
> })
> ```

model.get('content') does not seem to give me the updated text?

**Comment by ColdTuna** [comment]
For those landing here and looking for an updated solution:

    editor.on("component:selected", model => {
        alert("hi buddy");
        console.log("New content selected", model.get("content"));
        // do your stuff...
    });

:)
