### ISSUE TITLE
BUG: src automatically added to video tag

### ISSUE THREAD

**Issue by mshafiq235** [artf/grapesjs#3190]
Hi @artf,

Thanks for building and maintaining this wonderful package.

**Issue**
I am using **Nicepages** to build template and upload it to my webapp. I have integrated with Grapesjs, which allows admins to edit the templates easily. The issue that I am facing is Nicepages adds video tag as follows

```
<video>
    <source src="PATH_TO_VIDEO" type="mime/type"/>
</video>
```

When this template is opened in the Grapesjs, grapesjs adds source to the parent `video` tag like this

```
<video src="SOME_SVG_CODE" >
    <source src="PATH_TO_VIDEO" type="mime/type"/>
</video>
```

If you can help me to resolve this issue, that would be great. I am happy to fix it in GrapesJS and make a pull request

**Comment by artf** [comment]
The default video component in GrapesJS is handled differently (without source). In your case, I'd suggest extending the default one and add the support for sources.
