### ISSUE TITLE
How to make components not editable in preview mode?

### ISSUE THREAD

**Issue by niveth09** [artf/grapesjs#3192]
I am trying to make components not editable in the preview mode. The following code isn't working. Please help me to fix it.

editor;
ngOnInit(){
this.editor = this.initializeEditor();
this.editor.on('load', () => this.editor.runCommand('preview'));
this.editor.on('run:preview', () => {
      this.editor.Panels.getPanels().reset([
      //some code
])
this.whenRunPreview(this.editor,'text');
this.whenRunPreview(this.editor,'image'); 
.....
} 

whenRunPreview(editor, compType) {
    editor.on('run:preview', () => {
      editor.DomComponents.getWrapper().onAll(
        (comp) => comp.is(compType) && comp.set({ editable: false })
      );
    });

**Comment by artf** [comment]
Fix your method in this way ()
```js
whenRunPreview(ed, type) {
  ed.getWrapper().findType(type).forEach(cmp => cmp.set({ editable: false }))
}
```
