### ISSUE TITLE
QUESTION: How do I repurpose the Spectrum Color Picker?

### ISSUE THREAD

**Issue by stljeff1** [artf/grapesjs#3194]
I would like to repurpose the color picker used in GrapesJS.

I have to use a color picker for some project level settings. These settings are accessible from the GrapesJS editor. I would like to leverage the existing color picker that is used for traits like font colors, etc.  I've seen [this post](https://github.com/artf/grapesjs/issues/1393) about extending a trait to get the color picker. Unfortunately, I don't think I can do that in my case. As far as I know, Traits are part of components; I am not dealing with components, I'm dealing with project-level settings that are outside the general scope of GrapesJS.

I just need to pass my input tag to spectrum, and be able to add onChange event handling. I can see the Spectrum plugin inside the grapesjs.js compiled bundle, I just don't understand if/how I can leverage it. I would like to avoid including jquery/Spectrum manually just for this feature, and it would be great if I could use Spectrum for the sake of consistent UI.

Thanks for your attention

**Comment by artf** [comment]
Currently, the only way is to use this, not public, API.
```js
editor.getModel().initBaseColorPicker(DomElement, { /* spectrum options */ });
```
I've started working on a new UI module, to handle similar situations (ability to add/replace GrapesJS UI elements) but unfortunately, I have no idea when it'll be released, as it's more in an experimental stage.

**Comment by himedlooff** [comment]
is there a way to keep the color picker but configure the spectrum options? for example if i wanted to force hex colors i could pass `{ preferredFormat: "hex" }`?
