### ISSUE TITLE
BUG: 

### ISSUE THREAD

**Issue by craighaworth** [artf/grapesjs#3197]
**Version:**
"0.16.30

**Are you able to reproduce the bug from the demo?**

[ x] Yes (the news letter demo)

**What is the expected behavior?**
Image resize handles should resize image without throwing an exception.

*Describe the bug **detailed***
Clicking on any of the image resize handles throws an Uncaught TypeError.

PropertyView.js:504 Uncaught TypeError: Cannot read property 'get' of undefined
    at r.isTargetStylable (PropertyView.js:504)
    at r.checkVisibility (PropertyView.js:326)
    at r.targetUpdated (PropertyView.js:269)
    at Et (index.js:759)
    at r.<anonymous> (index.js:772)
    at r.<anonymous> (index.js:113)
    at m (backbone.js:371)
    at v (backbone.js:356)
    at d (backbone.js:151)
    at r.c.trigger (backbone.js:346)

Error occurs in:
  /**
   * Check if target is stylable with this property
   * The target could be the Component as the CSS Rule
   * @return {Boolean}
   */
  isTargetStylable: function isTargetStylable(target) {
    var trg = target || this.getFirstTarget(); // *** Target returned is undefined
    var model = this.model;
    var id = model.get('id');
    var property = model.get('property');
    var toRequire = model.get('toRequire');
    var unstylable = trg.get('unstylable'); // *** error thrown on unchecked variable
    var stylableReq = trg.get('stylable-require');
    var requires = model.get('requires');
    var requiresParent = model.get('requiresParent');
    var sectors = this.sector ? this.sector.collection : null;
    var selected = this.em ? this.em.getSelected() : null;
    var stylable = trg.get('stylable'); // Stylable could also be an array indicating with which property
    // the target could be styled

...

**Comment by artf** [comment]
Thanks for the report, it'll be fixed in the next release.
