### ISSUE TITLE
BUG: block render function not trigger 

### ISSUE THREAD

**Issue by awais786327** [artf/grapesjs#3199]
@artf - In the documentation, it says that If we need to customize the aspect of each block preview we can pass a render callback function in the block. 

But here is the actual thing Basically, I wrapped this render callback in a function named *func()* and calling it on some ajax request

If I call this on page load it works but if I try to call this *func()* function after page load on some click event/handler or API response this *render* callback inside that function doesn't trigger

![image](https://user-images.githubusercontent.com/12613564/102699399-34828b00-4266-11eb-93eb-ce102028baf0.png)

**Comment by artf** [comment]
The block manager doesn't see the change if you do this `block.attributes.render = ...`. 
You have to update the property explicitly in this way:
```js
block.set({
 render: () => {
  return `<div>NEW HTML</div>`
 }
})
```
**And be careful**, the render function SHOULD return the HTML string or the DOM node, NOT a Promise. If you need to do something async, at first resolve it, THEN update the render with the returned content.
