### ISSUE TITLE
Problem occurs from upload image from Assests Manger in grapejs

### ISSUE THREAD

**Issue by piyalmaduranga** [artf/grapesjs#32]
I have problem with image uploading section in assets manager.I have go though your override method of `uploadFile` in `fileUploader.js`. I uploaded selected image in our server. I applied that image uploaded api endpoint in config file.Image is uploaded is fine..but I want to get that image data into frontend.
 I want to know about what is the response type of image uploading api. because we want response in our side. Is it image data, or image url? Can you help me on this situation.following is code section.that is ajax call how uploading image api in your code.

```
			$.ajax({
				url			: this.config.upload,
				type		: 'POST',
				data		: formData,
				beforeSend	: this.config.beforeSend,
				complete	: this.config.onComplete,
				xhrFields	: {
					onprogress: function (e) {
						if (e.lengthComputable) {
							/*var result = e.loaded / e.total * 100 + '%';*/
						}
					},
					onload: function (e) {
					    //progress.value = 100;
					}
				},
				cache: false, contentType: false, processData: false
			}).done(function(data){
                                // what is type of this data.data object.
				target.add(data.data);
			}).always(function(){
				//turnOff loading
			});
```

**Comment by artf** [comment]
@piyalmaduranga  Indeed is not yet documented, sorry about that.
Anyway, the target (a Backbone Collection) could accept an object or an array of objects like this:
```js
target.add([
  {
    src: 'http://img.jpg',
    height: 300,
    width: 200,
  },{
    src: 'http://img2.jpg',
  },
  ...
])
```

**Comment by piyalmaduranga** [comment]
Thanks artf..It works fine..

**Comment by devhameed** [comment]
can you send me complete grapesjs.min.js file and php files please?
