### ISSUE TITLE
Adding component to canvas and making them active.  Refresh canvas elements? 

### ISSUE THREAD

**Issue by daniel-farina** [artf/grapesjs#320]
Hi Guys. 

I have a question about adding a block to canvas using another UI. I'm currently adding some blocks  from a different modal dialog this way:

When the block is clicked from my modal it executes this: 

```
 $(".addSection").click(function () {
              //ID of Block we are about to insert to Canvas. (Its a block that already exist)
              var id = $(this).attr('data-section-id');
              // Get the Block using the id.
              var block = blockManager.get(id);

              //Add component to wrapper
              editor.addComponents({
                  type: 'text',
                  content: block.attributes.content,
              });
          });
```

and it works!! I cans see my new content inside canvas. 

**The problem** is that  the elements inside of them are not selectable, or editable.  

However, if I click on any block from the sidebar, not even dragging it then  my new component that was added to canvas becomes  selectable and active right away. 

Is there a way to make new components that are added to canvas from external functions active/sent to the models? 

I tried every single function and it doesn't work.

Thanks a bunch in advance!  I'm getting familiar with the code. 

I really like what I see. Great job!!

**Comment by artf** [comment]
Hi Dan, this is happening because `content` should only contain stuff you'd like to edit via the text editor (like a raw text), if you want actually to add other components you can use `components` key
```js
editor.addComponents({
    type: 'text',
    components: block.attributes.content,
});
```

**Comment by daniel-farina** [comment]
Hi Artur, 

ah, I completely missed that but now it makes sense. Great job! The best editor (most promising) by far available in the open source community. 

Dan

**Comment by artf** [comment]
Thanks Dan, really appreciate your kind words :)
