### ISSUE TITLE
Custom block category question 

### ISSUE THREAD

**Issue by MariusDK** [artf/grapesjs#3203]
Hi,
I want add attributes to the category of blocks but the don’t apply.

**Comment by MariusDK** [comment]
@artf any advice on this?

**Comment by artf** [comment]
Please, elaborate better on what you're trying to achieve.

**Comment by MariusDK** [comment]
I want to add an html attribute on the category of blocks like **Basic Category** .
something like this 
![image](https://user-images.githubusercontent.com/26068332/103411637-aa95c480-4b79-11eb-8433-335622478e51.png)

**Comment by MariusDK** [comment]
`attribute="eq"`

**Comment by artf** [comment]
Ok and what did you try?

**Comment by MariusDK** [comment]
I was trying to modify when a new category is created and added with the block. Adding an attributes with this value but it dosen't apply so i view in category model that the only attributes that category are adding is title and count (or order). So i want to find another way on doing that

**Comment by artf** [comment]
Can you please paste the code?

**Comment by xQwexx** [comment]
I also had the same question I found with `attributes: { attribute: 'eq' },`. You can add more attributes for the end html.
