### ISSUE TITLE
Form is not submitting

### ISSUE THREAD

**Issue by shkhalid** [artf/grapesjs#3207]
I am trying to create as custom block. But the form is not submitting when i use `components` inside content. 

```
const blockManager = editor.BlockManager;

  blockManager.add("pre-made-element--registration", {
    label: "Registration Form",
    category: "Pre-Made Elements",
    attributes: { class: "fa fa-user-plus" },
    content: {
      script: function () {
        const $ = window.$;
        const form = $(this).find("form");

        form.submit((event) => {
          const formData = form.serializeArray();
          console.log(data);
        });
      },
      components: "HERE IS THE FORM COMPONENT",
    },
  });
};
```

I am able to get all the form data when i use `content` instead of component.  But then it's not allowing me drag new inputs to form.

```
const blockManager = editor.BlockManager;

  blockManager.add("pre-made-element--registration", {
    label: "Registration Form",
    category: "Pre-Made Elements",
    attributes: { class: "fa fa-user-plus" },
    content: {
      script: function () {
        const $ = window.$;
        const form = $(this).find("form");

        form.submit((event) => {
          const formData = form.serializeArray();
          console.log(data);
        });
      },
      content: "HERE IS THE FORM COMPONENT",
    },
  });
};
```

**Comment by gixid192** [comment]
The important part - the html is missing.
If you can, you should share the code in codesandbox or similar online editors.

**Comment by artf** [comment]
Yeah, we need the complete code to understand the issue.

Anyway, if you're using `script` please define a Custom Component instead of placing it directly in the Block, or you'll face issues on storing. I know that this is how is illustrated in the documentation but the usage of blocks was there only as an example (I hope to update it for the next release)

**Comment by Ayamahmoud359** [comment]
I faced this problem also the form doesnot submit
