### ISSUE TITLE
BUG: When in preview mode, the toolbar is only being hidden but still clickable

### ISSUE THREAD

**Issue by TouficNouwayhedd** [artf/grapesjs#3209]
**Version:**
0.16.22

**Are you able to reproduce the bug from the demo?**

Yes

**What is the expected behavior?**

When the use presses the preview button, the icon toolbar must no be clickable.

*Describe the bug **detailed***

When the user presses preview (even in the demo website), if you hover over the selected component before pressing preview, you can notice that you can click the toolbar again.
To fix this currently in my project, I had to hide the toolbar div ("gjs-toolbar") when the preview is run and show it again when the preview is exited.

**What is the current behavior?**

In preview mode, hover over the selected component, there are still clickable elements.

**Are you able to attach screenshots, screencasts or a live demo?**

Yes. Please check this attached mp4 
https://user-images.githubusercontent.com/66264061/103091217-26cd5c80-45fc-11eb-9b17-7e915396fb56.mp4
If this link doesn't work, check this one
https://vimeo.com/494426495

**Comment by artf** [comment]
Fix ready for the next release
