### ISSUE TITLE
How to use SVG 

### ISSUE THREAD

**Issue by suchithmahadi** [artf/grapesjs#321]
I want to use a SVG component in a block how to use the SVG, If i create a Block using Component&JS, by default div tag comes. Need help.

**Comment by artf** [comment]
You should be able to put them directly within a Block
```js
editor.BlockManager.add('svg-block', {
    label:'SVG BLOCK', 
    content:`<svg ...>...</svg>`
})
```

**Comment by suchithmahadi** [comment]
Thanks for the Help, One quick question, Can we use javascript within the content of SVG block explained above , i wanted to try using Components&JS with SVG. Appreciate your work.

**Comment by artf** [comment]
Yeah, you should be able to do so by using a new Component Type or even directly within a block as explained in Components&JS
