### ISSUE TITLE
how to move components 

### ISSUE THREAD

**Issue by alemenciones** [artf/grapesjs#3211]
Hello dear:

I want move a component to first/end in the wrapper programmatically, i think something like editor.getWrapper().add(editor.selectedComponent(), {at: 0});, but this's adding a new clone from selectedComponent, 

maybe with  trigger "sorter:drag:end" at position??

can you help me?

sorry for my poor english :')

**Comment by artf** [comment]
Probably it makes sense to add a new `component.move(desComponent, opts)` method to cover such a case, but for now you can achieve it in this way:
```js
const selected = editor.getSelected();
selected.remove({ temporary: true }); // temporary option will avoid removing component related styles
editor.getWrapper().append(selected, { at: 0 });
```
