### ISSUE TITLE
QUESTION: How to save the dynamically added traits

### ISSUE THREAD

**Issue by theSC0RP** [artf/grapesjs#3213]
Hi, @artf, I have a custom component that has a button trait. When the button is pressed, I am adding a custom trait dynamically using `comp.addTrait()`. 
When I load the saved template, I want the container to show the dynamically added traits too. (I am loading the template using components but the dynamically added traits are not being shown). What might I be doing wrong?

**Comment by theSC0RP** [comment]
I made it work by having a count attribute on the component and then adding the trait count times in the init of the container.

**Comment by artf** [comment]
> I made it work by having a count attribute on the component and then adding the trait count times in the init of the container.

This is the correct way. 

Traits are intentionally skipped from the JSON, otherwise, you'd put on hold your component definition in the storage (eg. the day you'll upgrade the component with new traits, your users will still see the old ones)

**Comment by gandhar-workik** [comment]
@artf, thanks for the reply. It made stuff more clear.

**Comment by theSC0RP** [comment]
@artf, thanks for replying. That was a really valuable piece of information.
