### ISSUE TITLE
Ckeditor Enable for header type

### ISSUE THREAD

**Issue by Abhisheknanda1344463** [artf/grapesjs#3214]
Hi @artf
I've added the CKEditor in the grapesjs  and it's working fine but the problem is on the header-block CKEditor is not showing up
I've tried to add the format tags 
```
 format_tags: 'p;h1;h2;h3;h4;h5;h6;pre;address;header;div',
  ```
  but it didn't work.
Could you please help me
Thanks

**Comment by artf** [comment]
Please confirm/ensure it's related to GrapesJS and not CKEditor as it might be an expected behavior (might be also against HTML5 specs as I don't see a reason to have a content editable header...)

**Comment by Abhisheknanda1344463** [comment]
@artf  
What should be the type of header Block in that case?
If we allow the user to modify the text of the header block from Ckeditor.

If we change the type text to header it won't allow me to edit the element on that canvas
Could you please suggest some way for this?
In the same way, it's working in the grape drop in that type is showing the header but we can still edit the text of the heading.

Thanks
