### ISSUE TITLE
BUG: changesCount is not incremented, when changes are applied in any Text component

### ISSUE THREAD

**Issue by marcepoblet** [artf/grapesjs#3224]
https://user-images.githubusercontent.com/64096863/104047608-af352b00-51c0-11eb-8261-1d7ae9277d25.mp4

The parameter "changesCount" is not  incremented when you double click in any text component and  write or changes are made inside of any text component.

For button/images components, the parameter "changesCount" is incremented and is working ok.

I have attached a video, showing this behavior. 
I have been able to reproduce this error in versions 0.16.27, 0.16.30 and 0.16.34. In older versions, this issue does not happen

**Comment by artf** [comment]
Thanks @marcepoblet the fix is ready for the next release

**Comment by marcepoblet** [comment]
> Thanks @marcepoblet the fix is ready for the next release

Thanks! @artf ,   do you have some estimation for the release date?
