### ISSUE TITLE
FEAT: how to make 4 properties in one row，like padding，margin

### ISSUE THREAD

**Issue by chenjingling90** [artf/grapesjs#3226]
How could I control the properties to be show in one row or two, like the demos?
![image](https://user-images.githubusercontent.com/46340968/104158854-2ff66000-5429-11eb-8d8d-dc40ff2e3e38.png)
![image](https://user-images.githubusercontent.com/46340968/104158859-3389e700-5429-11eb-9825-570f8df6b064.png)
When I download the project grapesjs-preset-newsletter to local,  also shows padding and margin in two rows which is puzzling.
In fact，I would like to put them flexible with customized rows and columns. Or at least， 4 properties can be controled in one row.

**Comment by artf** [comment]
Just use the CSS
