### ISSUE TITLE
BUG: Modal won't open after closing it dynamically 

### ISSUE THREAD

**Issue by alivex** [artf/grapesjs#3230]
Hello;

Thank you guys for the great tool, I just love the documentation, the easy to use/understand.
I think I ran into an issue with the modal not opening again after closing it dynamically the first time.
example:

```

editor.on('modal:open', () => this.openModalHandler(editor));

openModalHandler(editor){
        const model = editor.getSelected();
        const modal = editor.Modal;
        const {type} = model.attributes;

        modal.close();

        switch (type) {
        case 'image':
        case 'section':
            return this.addBackgroundImage(type);
        }
    }
    
```

**Comment by artf** [comment]
I can't reproduce it on the official demo, eg.
```js
editor.on('modal:open', () => {
 console.log('Modal opened');
 setTimeout(() => {
  console.log('Close modal');
  editor.Modal.close()
 }, 2000)
});
```
But just checking your code I'd say it doesn't open because you're closing it immediately after (just after the open is triggered), am I missing something?!
