### ISSUE TITLE
BUG:  how to change gjs-ckeditor-format component

### ISSUE THREAD

**Issue by vatte21** [artf/grapesjs#3231]
hi guys,
we all know that gjs-ckeditor-plugin working with [data-gjs-type]="text" components.
I wanna know , could we change this option?
I want to make my own custom component with for example [data-gjs-type]="anyDiv" and have the same functionality like in
[data-gjs-type]="text". maybe someone knows how to change that?
maybe i can change that in ckeditor config? when we initialize ckeditor for example:
options: {
!!!!!for example:
format: 'text' , want to add ('anyDiv'),
language: 'en',
startupFocus: true,
extraAllowedContent: '();{}', // Allows any class and any inline style
allowedContent: true, // Disable auto-formatting, class removing, etc.
enterMode: ckeditor.ENTER_BR,
uiColor: '#0000001a', // Inline editor color
extraPlugins: 'justify,colorbutton,panelbutton,font,sourcedialog,showblocks',
height: 5,
toolbar:[
[ "Format", 'Font', 'FontSize',"-", "Bold", "Italic", "Strike", "Underline", "Subscript", "Superscript", "RemoveFormat", "-", "-", "JustifyLeft", "JustifyCenter", "JustifyRight", "JustifyBlock", "-", "TextColor", "BGColor", "-", "-", "-"]
]
},
position: 'left',

**Comment by Abhisheknanda1344463** [comment]
@vatte21 
You've to extend the text type in your component  like this way
```js
editor.Components.addType('anyDiv', {
  model: {
      defaults: {
       type: 'text',
       traits:[
          ...editor.Components.getType(type.id).model.prototype.defaults.traits,
          ...[]
        ]
      },
      reRender() {
         this.view.render();
      },
  },
  extend: 'text',
  isComponent: function (el) {
    if (el.tagName === 'anyDiv')
        return {type: 'anyDiv'};
  }
});
```

**Comment by vatte21** [comment]
@Abhisheknanda1344463  Thank you! Ill try

**Comment by abulka** [comment]
@Abhisheknanda1344463 your code fragment gives me an error `Uncaught ReferenceError: type is not defined` on the line
```
...editor.Components.getType(type.id).model.prototype.defaults.traits,
```
where is `type` defined?

**Comment by abhi-161994** [comment]
@abulka  I've just written an example 
you should've written like this
```js
domComponents.getType('default').model.prototype.defaults.traits,
```
