### ISSUE TITLE
DRAG AND DROP COMPONENTS: 

### ISSUE THREAD

**Issue by matiasmasciotta** [artf/grapesjs#3232]
Hi, I have the following issue:
I need an event type editor.on ("sorter: drag: end") which is thrown in all these cases:
(detect what element and where I'm dropping it)
1- let it hear when you drag and drop an element from the blockManager and drop it on the canvas.
2- let it hear when you drag an already componentized element from the canvas to another area of ​​the canvas.
3- that I hear when I move an element in the layerManager.

With the sorter I was able to solve case 2, 1 did not come out because the element is not yet componentized, so when trying to add attributes to it, before being componentized it is added to the html canvas as a standard element and ignores the attributes that I added manually.

can you help me with this?
thanks

**Comment by bgrand-ch** [comment]
Hello,

For future questions or technical issues, which aren't bugs, GitHub's [Discussions](https://github.com/artf/grapesjs/discussions) tab is the place to be.

Don't forget to close this issue if it is resolved or write a new detailed message in [Discussions](https://github.com/artf/grapesjs/discussions) -> [Q&A](https://github.com/artf/grapesjs/discussions/categories/q-a) category (and close this issue).

Thank you for your understanding.
