### ISSUE TITLE
Add Trait For wrapper

### ISSUE THREAD

**Issue by Abhisheknanda1344463** [artf/grapesjs#3237]
Hi @artf  
I've added trait for wrapper this way.
How can I perform the init function for the same
Here is the code
```js
  editor.getWrapper().set('traits',
    [
      {
        changeProp: 1,
        name: 'abc',
        label: 'abc',
        type: 'checkbox',
        changeProp: 1
      },
    ],
  )
```
@artf  Could you please help me? 
Thanks.

**Comment by Abhisheknanda1344463** [comment]
@ryandeba  Any suggestion?

**Comment by Abhisheknanda1344463** [comment]
@artf  Could you please help me here?

**Comment by artf** [comment]
You can use this option from components on init https://github.com/artf/grapesjs/blob/69e5ab2c1176e6fdeac1b058398cca55efe92df3/src/dom_components/config/config.js#L9

PS: **stop annoying other people with your issues, please or I have to block you from this repo**

**Comment by Abhisheknanda1344463** [comment]
Sorry @artf  I'll keep this in mind.
Thanks

**Comment by Abhisheknanda1344463** [comment]
@artf 
i've manage to add trait for wrapper how could i peform init function for trait
Not getting the exact way
```js
var editor = grapesjs.init({
    domComponents: {
      wrapper: {
        removable: false,
        copyable: false,
        draggable: false,
        components: [],
        traits: [
          {
            name: 'abc',
            type: 'checkbox',
            label: 'abc',
            changeProp: 1,
          },
        ],
        init(){
          this.on('change:abc', this.abc);
        },
        updateScroll(){
          alert("jo");
        },
        stylable: [
          'background',
          'background-color',
          'background-image',
          'background-repeat',
          'background-attachment',
          'background-position',
          'background-size'
        ],
      },
    }
 });
```

**Comment by artf** [comment]
`domComponents.wrapper` is only for props... You can always extend the `wrapper` component
