### ISSUE TITLE
[Question]: How to load external javascript,i tried all methods,Useless

### ISSUE THREAD

**Issue by sizhousama** [artf/grapesjs#3238]
I write html strings as blocks, and need to introduce a lot of external scripts and styles, but I tried all the methods, when I drag the block to the canvas, the script does not take effect, but styles can be loaded,I hope to get help。
1.
Load by appendchild
![image](https://user-images.githubusercontent.com/40018231/104894741-fbc0f900-596c-11eb-9d92-2d5c1e59f4d3.png)

2.
init load by canvas:{scripts:[...]}
![image](https://user-images.githubusercontent.com/40018231/104894830-14c9aa00-596d-11eb-909f-e6bcf2aa6cef.png)

who can help me?

**Comment by sizhousama** [comment]
The console shows loaded
![image](https://user-images.githubusercontent.com/40018231/104895114-62dead80-596d-11eb-9f6e-0b73d17b3f02.png)

**Comment by harsh201** [comment]
@sizhousama I am loading scripts/stylesheets via canvas while initializing grapesjs editor and it works for me.
``` js
 canvas: {
          scripts: ['https://unpkg.com/abc.js'],
          styles: ['https://unpkg.com/abc/dist/css/abc.min.css'],
        },
```
More details can be found [here](https://grapesjs.com/docs/modules/Components-js.html#dependencies).
Hope it helps!
