### ISSUE TITLE
BUG: UndoManager: combination between undo and redo is not working properly, lost some styles

### ISSUE THREAD

**Issue by marcepoblet** [artf/grapesjs#3240]
https://user-images.githubusercontent.com/64096863/104953457-35adf180-59a5-11eb-85bd-2f84ffa24d83.mp4

The styles of the text and button blocks are lost after deleting them from the template, and undo the changes and redo them several times.

The issue is that the styles applied from the blocks, are lost after apply the undo and redo functionality. I attach a video to show this issue.

**Comment by artf** [comment]
It should be fixed in the latest release, please follow the issue template properly and ensure to use the latest version before submitting a bug
