### ISSUE TITLE
Is it possible to use existing trait types in new custom traits? (e.g the colorpicker)

### ISSUE THREAD

**Issue by DodoTrip** [artf/grapesjs#3246]
I would like to create a new custom trait to use, that has the input of the color picker and a checkbox so that the end result is either the predefined color coming from the checked checkbox or if unchecked choosing from the picker. This is too specific for my case so my question is if i can use pre-existing trait types when creating a new one in general. I am coming straight from the documentation , i may have missed something but there was no mention of it so i got curious, thanks in advance!.

**Comment by artf** [comment]
Not at the moment, I'm working on a new UI module that will allow the reuse and override of internal UI elements.
