### ISSUE TITLE
Question : Traits

### ISSUE THREAD

**Issue by fmay** [artf/grapesjs#3247]
Hi @artf - what you've built is magnificent. It's been a gentle struggle as I'm far from being a JS wizard. However, I've got just about everything fully configured - except for this!

I want to set traits that display when an image is selected (alt, src, id). I am sure it can be done once at initialisation, but I'm buggered if I can figure out how do do it. I've read everything I can find in the issues and am still stuck.

The only way I got it to work is as follows ...

```
  // Set the traits for <img>
  editor.on('component:selected', function(a) {
    const component = editor.getSelected()
    if( component.attributes.tagName === 'img' ) {
      if( !component.getTrait('alt')) component.addTrait( { name: 'alt' } )
      if( !component.getTrait('src')) component.addTrait( { name: 'src' } )
      if( !component.getTrait('id')) component.addTrait( { name: 'id' } )
    }
  })
```

Also - the out-of-the-box "Alt" comes first and I'd really like it to be after ```src```. I can't figure out how to get rid of it as ```removeTrait()``` doesn't seem to work.

While my solution works, I'd love to know how it **should** be done.

Many thanks!

**Comment by artf** [comment]
Hi Freddy, you can simply extend the image component in this case
```js
editor.Components.addType('image', {
  model: {
   defaults: {
     traits: [{name: 'alt'}, {name: 'src'}, {name: 'id'}]
   }
  }
});
```
