### ISSUE TITLE
QUESTION regarding JSON stored by the StorageManager

### ISSUE THREAD

**Issue by theSC0RP** [artf/grapesjs#3249]
Hey, @artf. I want to access the json that is generated when a template is stored without actually storing the template. The json object can be accessed using the events but I don't want to call `editor.store()` and then use the events.
Is there a way I can do get the json object (a function call on editor or some property)?
Or is there a way to stop `editor.store()` method so I can get the json being stored and abort the call?

**Comment by Joshmamroud** [comment]
@theSC0RP Is this what you're looking for [getComponents](https://grapesjs.com/docs/api/editor.html#getcomponents) ?

**Comment by artf** [comment]
@theSC0RP it's not clear if you want the storage functionality or not, but what proposed Josh is correct or you can always add your storage (and do nothing inside if need to...) https://grapesjs.com/docs/modules/Storage.html#define-new-storage

**Comment by theSC0RP** [comment]
> you can always add your storage (and do nothing inside if need to...) https://grapesjs.com/docs/modules/Storage.html#define-new-storage
Thanks @artf. This is what I ended up doing. With `editor.getComponents()`, you get a  cyclic structure structure right (model -> view -> model -> ...) and that isn't stored by the storageManager and it can't be used to load the template.
