### ISSUE TITLE
BUG: How does the property color changes to blue when value changed?

### ISSUE THREAD

**Issue by luziye9** [artf/grapesjs#3253]
Hi, 

We are encountering an issue - color of property name such as "Width" is blue when dragging a new component to canvas, but we don't modify its value.
![image](https://user-images.githubusercontent.com/64573639/106257856-13935980-6258-11eb-92fb-6ad0e17da323.png)

Grapesjs is powerful, and very helpful to us. However, we are new to grapesjs, and have spent much time on this issue with no progress. 

Would you please tell us the machanism, or which file the related code locates? 

It will be much appreciated if you can get back to me by end of this week.

Thanks a lot in advance :)

Regards,
Jaron

**Comment by artf** [comment]
Hi @luziye9 for sure you're using a block/component with a custom `style` property on it...
Anyway, if you're opening a BUG issue, you have to follow the template (grapesjs version, reproducible demo, etc.). So, for now, I'm closing this as an invalid issue.
