### ISSUE TITLE
How to hide ".gjs-traits-label" in traitManager?

### ISSUE THREAD

**Issue by alemenciones** [artf/grapesjs#3254]
maybe can you help me... i want remove the label ".gjs-traits-label" when traitManager's opened.

![image](https://user-images.githubusercontent.com/2309686/106330419-f499c500-6261-11eb-9aa5-27eaae11619b.png)
![image](https://user-images.githubusercontent.com/2309686/106330330-c6b48080-6261-11eb-9513-1371cb59e840.png)

i tried something like this:

```
    message[editor.I18n.getLocale()] = {
        traitManager: {
            label: "", // OR NULL
        }
    };

    editor.I18n.addMessages(message);
```

**Comment by artf** [comment]
```css
.gjs-traits-label { display: none }
```
