### ISSUE TITLE
[QUESTION]: Parse styles to a Css string

### ISSUE THREAD

**Issue by lacieri** [artf/grapesjs#3262]
Hi @artf ! 
```javascript
  "editor": {
    "css": "* { box-sizing: border-box; } #wrapper{font-family:Helvetica,Arial Black, sans-serif;color:#9500b3;}",
    "html": "<div id=\"iecr\">Insert your text here</div>",
    "assets": "[]",
    "styles": "[{\"selectors\":[\"#wrapper\"],\"style\":{\"font-family\":\"Helvetica,Arial Black, sans-serif\",\"color\":\"#9500b3\"}},]",
    "components": "[]"
  }
}
```
Is there any way to parse the styles into a CSS string?
This would be helpful in a scenario where you have multiple GrapesJs instances stored and you want to update the CSS on all of them. You can manipulate the styles because that is an array and it's reliable. Currently, on the CSS I am using regex to locate and update. Would prefer to parse the `editor.styles` and override the `editor.css`.

**Comment by artf** [comment]
Well, you should be able to take the CSS from any GrapesJS instance with `editorInstance.getCss()`. Which basically generates the CSS from the `styles` JSON
