### ISSUE TITLE
Remote storage issues 

### ISSUE THREAD

**Issue by san-123** [artf/grapesjs#3263]
Hi,

     grapeJs initiated,   I normally load function call and append content to gjs div,

$.ajax({
type: "GET",
            url: ''
 
            processData: false,
            contentType: 'application/json; charset=utf-8',
            DataType: "Json",
 $.each(data, function (key, data) {
 $('#gjs').append(html);
}
});
My issues, After save content, reload same function call not working.   How to call save/ load function simply?

Please guide me

**Comment by artf** [comment]
https://grapesjs.com/docs/modules/Storage.html
