### ISSUE TITLE
[Question] How to know from which block is the selected component generated ?

### ISSUE THREAD

**Issue by amliu** [artf/grapesjs#3266]
Wondering how to do a reverse lookup, from component back to block.

I use Block Manager add() to add a block like below after initialization.
```
editor.BlockManager.add(
  'my-module-id', 
  {
    label: ...
    content: editor.getSelected().toHTML(),
   category: ...
  }
}
```

How do I if the selected component is generated by this custom block ?

**Comment by artf** [comment]
You should think more about components than blocks, indeed the right Block should look more like that.
```js
editor.BlockManager.add('block-id',  {
    label: ...
    content: { type: 'component-id' },
})
```

But in case you need it, you can always attach custom properties to your content block (which then will be appended to the component)

```js
editor.BlockManager.add('block-id',  {
    label: ...
    content: { type: 'component-id', fromBlock: 'block-id'  },
})
```
Once that block is dropped you will always be able to get that property `component.get('fromBlock')`
