### ISSUE TITLE
BUG: Cannot set 0px box shadow blur

### ISSUE THREAD

**Issue by tudor-ooo** [artf/grapesjs#3267]
For some reason, the editor does not allow to set the blur to 0px.
0 always magically turns into 5px.

<img width="243" alt="Screenshot 2021-02-11 at 17 14 05" src="https://user-images.githubusercontent.com/668451/107664461-ba321e00-6c8c-11eb-91ce-4e8a87a2e33c.png">

**Are you able to reproduce the bug from the demo?**
Yes

You can find this bug here:
https://grapesjs.com/demo.html

**Comment by artf** [comment]
Thanks, I guess there is some falsy check with the `0` which leads to the default 5px value.

**Comment by akankshach29** [comment]
Would like to help fix this bug. Will raise a PR.

**Comment by artf** [comment]
This one should already be fixed
