### ISSUE TITLE
QUESTION: How to add javascript in the html without sanitization?

### ISSUE THREAD

**Issue by theSC0RP** [artf/grapesjs#3268]
Hey @artf, I am taking javascript input from the user. I need to add this javascript inside the template HTML but it gets sanitized. 
Is there a way that I can turn off the sanitization? (I don't have an issue with the problems you mentioned in #3245 ) or can you add a property in the editor like `allowSanitization: false`
If not, then how can I add the javascript to the canvas?

**Comment by theSC0RP** [comment]
I tried adding the script to the iframe in which the canvas renders by adding a `<script>` tag at the end of the body of the iframe. This works to some extent. The problem here is that when I need to update the js inside the script I will need to refresh the iframe (to remove any event listeners if present) and doing so gives me the following error: 
![Screenshot from 2021-02-18 10-54-24](https://user-images.githubusercontent.com/30771519/108309560-beec5a00-71d7-11eb-9bfe-e7a48c5e6f7a.png)

**Comment by artf** [comment]
Can you provide a reproducible demo of your issue, please?

**Comment by theSC0RP** [comment]
Thanks for the reply @artf. 
I was doing a mistake while updating the iframe so now my problem is solved! 
Just another question, is there any built-in method to refresh the iframe?

**Comment by LeonardoAraujoLisboa** [comment]
> Obrigado pela resposta@artf. Eu estava cometendo um erro ao atualizar o iframe, então agora meu problema está resolvido! Apenas outra pergunta, existe algum método interno para atualizar o iframe?

Hello, @theSC0RP. How did you add the script, could you show it? Thanks
