### ISSUE TITLE
Translating html string

### ISSUE THREAD

**Issue by acondura** [artf/grapesjs#3269]
Great library! It meets all the requirements but one: website text translation.
I've searched high and low through the issue queue and docs and for some reason I can't find anything about this subject. My clients do not care that the grapesjs editor is in English. What they want is the ability to easily translate their text in the actual website in any language they want. 

If the home page header says "Welcome to my website", they would want a simple option of hovering that text, click a dropdown, then click Translate and maybe a popup would display to translate that line in French for example or any other language they desire to use for the website. Then, of course, there would be the need for a language dropdown selector for visitors to use.

Is there something like this? If not, what would be the rough structure for such a plugin to make this work?

**Comment by artf** [comment]
This is something you would need to create on your own. Maybe a custom text component, which gives the possibility to change the content with the selected language.

**Comment by jordandevogelaere** [comment]
@acondura do you have a solution for this? I have the same requirement for my client. 
Thanks

**Comment by gxanshu** [comment]
i have the same requirement too. and yes only way we can achive this is by creating our own component
