### ISSUE TITLE
Drag element anywhere

### ISSUE THREAD

**Issue by vmourya** [artf/grapesjs#327]
Is there a method so that i can drop element anywhere in canvas.

Currently it is sorting element,but i want to drop text element on image element.

Thanks

**Comment by artf** [comment]
What you're asking will be achievable with `Designer mode` and it's already on [Roadmap](https://github.com/artf/grapesjs/issues/74)

**Comment by Sibbir7350** [comment]
Hello @artf 
Any update on drop event?

**Comment by artf** [comment]
@Sibbir7350 nope

**Comment by sunhillbd** [comment]
Is there any way to free move components within their own column? @artf

**Comment by vinayak99999** [comment]
> 
> 
> Is there a method so that i can drop element anywhere in canvas.
> 
> Currently it is sorting element,but i want to drop text element on image element.
> 
> Thanks
Is the issue solved????

**Comment by artf** [comment]
@vinayak99999 check out this issue #1936
