### ISSUE TITLE
QUESTION: How to export JS code from angular components?

### ISSUE THREAD

**Issue by haizenbergD** [artf/grapesjs#3270]
Hey, I am using grapesjs in my Angular app
I have a custom angular component (which is basically custom HTML created with angular) and I am trying to export content using `grapesjs-plugin-export`

Issue I am facing is that after export there is no JS code (which is initially inside angular component) that can do with html what ever I need.

I wonder if you can help me with this.

<img width="1025" alt="Screen Shot 2021-02-15 at 11 41 37 AM" src="https://user-images.githubusercontent.com/51407611/107929782-cf57c700-6f82-11eb-8c8f-049e32639b2f.png">

**Comment by artf** [comment]
You can more about components with js here: https://grapesjs.com/docs/modules/Components-js.html#basic-scripts
