### ISSUE TITLE
BUG: id are added to <img/> on double click on it

### ISSUE THREAD

**Issue by ThomasPof** [artf/grapesjs#3272]
**Version:**

0.16.37

**Are you able to reproduce the bug from the demo?**

[X] Yes
[ ] No

**What is the expected behavior?**

It's about the GrapesJS-mjml plugin : this syntax doesn't accept id's on elements. But AssetsManager add ids to image elements. I would like to not add id attributes to <img> tags

**Steps to reproduce**

- clone and run the project
- add an image on the index.html file
- open the code viewer : no id
- double click on the image
- close the asset manager
- open the code viewer : an id has been added to the tag

You can find the GrapesJS-mjml issue here : https://github.com/artf/grapesjs-mjml/issues/179

**Comment by ThomasPof** [comment]
The id seems to be added way before opening the asset manager :
- clone and run the project
- add an image on the index.html file
- inspect this image element : there is the id on the dom element

**Comment by ThomasPof** [comment]
Found a clue in `/Users/thomaspopoff/Sites/grapesjs/src/code_manager/model/HtmlGenerator.js` line 10, the `opts.cleanId` is always undefined. I don't know how to set it to true to remove auto-generated ids

**Comment by ThomasPof** [comment]
Ok sorry for all my self-dialog : there is an option `opts.cleanId` inside `getHtml()` function you can configure to remove auto-generated ids...

**Comment by artf** [comment]
Well, that option was actually released today https://github.com/artf/grapesjs/releases/tag/v0.16.41 😅
