### ISSUE TITLE
REQUEST : Need a new release to have cleanId function

### ISSUE THREAD

**Issue by ThomasPof** [artf/grapesjs#3273]
[The grapesjs-mjml extension](https://github.com/artf/grapesjs-mjml) needs a newer version of grapes.js

[This commit](https://github.com/artf/grapesjs/commit/442cdf97b772f54029737f2450acb30e87074654) is cleaning ids and grapesjs-mjml need it in order to produce valid MJML code.

Can you provide a new release ? (the master version is 0.16.37 and the release is still 0.16.34)

Thanks a lot ! :-)

**Comment by artf** [comment]
Done https://github.com/artf/grapesjs/releases/tag/v0.16.41
