### ISSUE TITLE
Block.js `initialize` function is not doing anything

### ISSUE THREAD

**Issue by mig8447** [artf/grapesjs#3274]
https://github.com/artf/grapesjs/blob/3199d76ba5677229e90f13ef48fb91e9bfe1e90d/src/block_manager/model/Block.js#L23

As far as I can see, the code in the initialize function tried to set the category as a new Category object but it currently doesn't do anything. And since the category part is taken care by the BlocksView at:

https://github.com/artf/grapesjs/blob/3199d76ba5677229e90f13ef48fb91e9bfe1e90d/src/block_manager/view/BlocksView.js#L129

The initialize function is not needed in `Block.js` anymore

**Comment by artf** [comment]
yeap, seems like an old thing, thanks
