### ISSUE TITLE
Limit the number of times of block to be dropped

### ISSUE THREAD

**Issue by confettidc** [artf/grapesjs#3275]
Hi,

Is it possible to limit the number of times of block to be dropped? e.g. the form block and be dropped once only.

Thanks.

**Comment by theSC0RP** [comment]
Hi @confettidc, you can try doing something like, have a counter variable and update it once a block of a type is added and remove the newly added block if the counter condition is satisfied.
```
editor.on('block:drag:stop', (comp, addedBlock) => {
  // if the counter condition is satisfied then remove the component `comp`
  // else check the type of 'addedBlock' If it matches with the one you want to limit  and update the counter 
})
```

Do check the [API Reference](https://grapesjs.com/docs/api/).
