### ISSUE TITLE
BUG: CleanId function not working with MJML code

### ISSUE THREAD

**Issue by ThomasPof** [artf/grapesjs#3276]
This issue is about MJML code but I think this is more about grapesjs than grapesjs-mjml

There is a function that remove unnecessary IDs in `src/code_manager/model/HtmlGenerator.js`. This function is working well on HTML tags, but not on MJML tags.

What I found is 

```
      htmlOpts.attributes = (mod, attrs) => {
        const { id } = attrs;
        console.log(attrs) // this log will return all dom elements in HTML, not in MJML
        if ( id && id[0] === 'i' && !mod.get('script') && idRules.indexOf(id) < 0 ) {
          delete attrs.id;
        }
        return attrs;
      };
```

**Comment by artf** [comment]
https://github.com/artf/grapesjs/releases/tag/v0.16.41
