### ISSUE TITLE
BUG: Default PDF size: US letter How to set A4?

### ISSUE THREAD

**Issue by FrancoFasano** [artf/grapesjs#3277]
## WARNING
READ and FOLLOW next 3 steps, then REMOVE them before posting the issue

4. JSFiddle Starter template https://jsfiddle.net/szLp8h4n
5. CodeSandbox Starter template https://codesandbox.io/s/1r0w2pk1vl

**Version:*0.16.3*

*You can get the version by typing `grapesjs.version` into the console*

**Are you able to reproduce the bug from the demo?**

[ X ] Yes
[ ] No

**What is the expected behavior?**
A setting or a doc to help developpeur to define PDF size

*Describe the bug **detailed***
This isn't really a bug but a setting issue.
I can't change the PDF size to A4, no parameter or configuration found in code to allow A4 fromat

**What is the current behavior?**
I use grapesjs to build template in invoiceninja 4.5.21. By default the PDF size is US letter.

*Descripe the bug **detailed***

**Are you able to attach screenshots, screencasts or a live demo?**

[ X ] Yes (attach)
![image](https://user-images.githubusercontent.com/32268027/108403464-064a0900-721f-11eb-895b-9f791df25809.png)

**Comment by artf** [comment]
Hi Franco, you can define the frame size by changing [devices](https://grapesjs.com/docs/api/device_manager.html)
