### ISSUE TITLE
[Bounty] Remove jQuery dependencies

### ISSUE THREAD

**Issue by Geczy** [artf/grapesjs#328]
Use native javascript, no jQuery libraries

[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=49598156)](https://www.bountysource.com/issues/49598156-bounty-remove-jquery-dependencies?utm_source=49598156&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by Geczy** [comment]
@artf any word? 🥇

**Comment by artf** [comment]
Unfortunately, it's taking more than I expected, especially with regressions and some issue with spectrum (which is a JQuery plugin), by the way, it's almost done just need to refactor few other modules and then I'll release the rc, here is the branch
https://github.com/artf/grapesjs/tree/no-jquery

**Comment by arthuralmeidap** [comment]
@artf how can I help you to achieve that? I cloned the repo and ran the tests against the no-jquery branch and some were skipped but the rest of them were fine

**Comment by artf** [comment]
thanks @arthuralmeidap I'd really appreciate any feedback when I'll publish a new release

**Comment by artf** [comment]
Hi guys, I've just published the first RC (`npm install grapesjs@v0.11.3-rc`) which you can try online here http://grapesjs.com/demo-no-jq.html

Few notes about this update:
You don't need jQuery anymore but you can still use some of its API, which is possible thanks to the integration of https://github.com/kenwheeler/cash (`An absurdly small jQuery alternative for modern browsers` - 3.71 kb). With this approach, I break less stuff and still leave the possibility to manage the DOM easily (`view.$el.find(...)`)

Any feedback is highly welcomed thk

**Comment by artf** [comment]
Hi @Geczy if the demo seems ok for you I'll release it officially the next week

**Comment by arthuralmeidap** [comment]
@artf , the next release will come with all bug fixes?

**Comment by Geczy** [comment]
Gave it a test and it seems to be working in our environment! Great job

**Comment by artf** [comment]
@arthuralmeidap everything done until the latest release will be merged to this branch (plan to do it today 😬)

**Comment by arthuralmeidap** [comment]
@artf , thanks! Let me know if I can help you in anything!

**Comment by artf** [comment]
Ok it's out https://github.com/artf/grapesjs/releases/tag/v0.12.5 🎉
All demos are updated too

**Comment by Geczy** [comment]
@artf grapesjs still bundling jquery https://github.com/artf/grapesjs/blob/dev/package.json#L20

**Comment by artf** [comment]
oops! forgot to remove it, will update soon

**Comment by artf** [comment]
@Geczy npm updated

**Comment by bayareawebpro** [comment]
@artf Just wanted to say amazing job on this.   Excellent Work!

**Comment by artf** [comment]
thanks Dan

**Comment by musen** [comment]
@artf Amazing work!
