### ISSUE TITLE
BUG: BlocksView rendering is being called twice

### ISSUE THREAD

**Issue by mig8447** [artf/grapesjs#3283]
https://github.com/artf/grapesjs/blob/b199083f6a6128ecff41d20865493294f71fe0a1/src/block_manager/view/BlocksView.js#L186

The Block Manager is looking for a `rendered` property in the model to tell if the view did render already or not but this method doesn't set said property and therefore this function is called twice, once by the `reset`event and once ny the Block Manager. A line containing:

```js
this.rendered = true;
```

Should be added for this to stop happening

**Comment by artf** [comment]
Yeah, makes sense, thanks

**Comment by mig8447** [comment]
@RutujaBadbe This is the exact change you need:
https://github.com/artf/grapesjs/commit/640661b0a44e5e2857b615559c1db27da3e17a6c
