### ISSUE TITLE
QUESTION: Wrapper styling

### ISSUE THREAD

**Issue by RaresVlaiduc** [artf/grapesjs#3287]
First of all, congrats @artf for this amazing project 💯 

I am currently working on a project and I wanted to ask if I can edit the wrapper (body) like I edit other components inside it.
For example I would like to edit the padding of the wrapper as I do with the background-color. 

![grapesjs-question](https://user-images.githubusercontent.com/73160095/108832886-c72c0700-75d4-11eb-8d74-daa48d8a0440.png)

I've had a look over the configs but couldn't find anything helpful.

Thank you!

LE: I have found a way. I am overwritting the stylable array from getWrapper() but I'm not 100% sure this is the correct way. Can you confirm this?

**Comment by artf** [comment]
> LE: I have found a way. I am overwritting the stylable array from getWrapper() but I'm not 100% sure this is the correct way. Can you confirm this?

Yeah sure it's ok, but if you need, you can change the wrapper properties on init via `mainConfig.domComponents.wrapper` option
https://github.com/artf/grapesjs/blob/18b2f95b7f844578dc2b28d786b126013d155d9e/src/dom_components/config/config.js#L9

**Comment by kuhelbeher** [comment]
> you can change the wrapper properties on init via `mainConfig.domComponents.wrapper` option
> https://github.com/artf/grapesjs/blob/18b2f95b7f844578dc2b28d786b126013d155d9e/src/dom_components/config/config.js#L9

Hello, I've noticed that this options is for old version of grapesjs, but in new version wrapper property is removed from domComponents config. Is there a way to set some wrapper properties on initialization in new version?

**Comment by artf** [comment]
Yes @kuhelbeher, now the wrapper is created post plugins, so you can entirely extend it as any other component

**Comment by masonmonu** [comment]
@artf Could you please provide an example of adding traits in the wrapper?
