### ISSUE TITLE
BUG: Edit a clone without affect the cloned components

### ISSUE THREAD

**Issue by ilsantuzzo** [artf/grapesjs#3288]
I realized that the cloned and all the clone components have mirror editing. Is there a way to avoid it?
![GJS](https://user-images.githubusercontent.com/5839445/108843429-f6457700-75da-11eb-91d7-0e097519ef54.gif)

**Comment by artf** [comment]
I should be able to release the fix today 😬 https://github.com/artf/grapesjs/issues/3291
