### ISSUE TITLE
BUG (v0.16.41): the duplicate icon from the icon toolbar is modifying the original element too

### ISSUE THREAD

**Issue by marcepoblet** [artf/grapesjs#3291]
**Version:**
v0.16.41

**Are you able to reproduce the bug from the demo?**

[ ] Yes

**What is the expected behavior?**
The elements duplicated not should be impact the changes in the original element.

*Describe the bug **detailed***
steps: 
- select an element (text, image, etc)
- click on the duplicate icon from the toolbar
- modify the new element duplicated
- the original element is modified too

https://user-images.githubusercontent.com/64096863/109187944-27f04680-7771-11eb-8ba4-1181ed56b08f.mp4

**What is the current behavior?**
when some elements are duplicated, and the element duplicated is modified, the original element is modified too.

**Are you able to attach screenshots, screencasts or a live demo?**

[ ] Yes (attached a video)

**Comment by AadilMehrajBhat** [comment]
Regression issue since ` "grapesjs": "0.16.34"`

**Comment by ebereonyechere** [comment]
@artf any fix or walk around for this? Also experiencing this.

**Comment by mmotov** [comment]
Also wondering how to solve this. That's really annoying

**Comment by artf** [comment]
Thanks for the report guys, I'm aware of the bug and it's already fixed in dev. I've just totally forgot to release it 😬 I'll try to release it today

**Comment by artf** [comment]
Should be fixed here https://github.com/artf/grapesjs/releases/tag/v0.16.44

**Comment by devtechk** [comment]
@artf Thanks a lot! you saved me a lot of work *_*  I was trying to debug this issue all this entire afternoon... then for casuality I've realized, checking npm that the 0.16.44 version was out...

You saved man. Thank a lot! Donation, you deserve it all!
