### ISSUE TITLE
BUG (v0.16.41): Button component with draggable property is not working properly

### ISSUE THREAD

**Issue by marcepoblet** [artf/grapesjs#3295]
**Version:**
v0.16.41

**Are you able to reproduce the bug from the demo?**

[ ] Yes
[ ] No

**What is the expected behavior?**
When we have a button with the property data-gjs-draggable in false, this button not should be dragged in the canvas.

*Describe the bug **detailed***
Steps
- Set a button component  with draggable property in false
- Drag the button inside other components
- the button is dragged

**What is the current behavior?**
Steps
- Set a button component  with draggable property in false
- Drag the button inside other components
- the button not should be dragged

**Are you able to attach screenshots, screencasts or a live demo?**

[ ] Yes (attached a video )

https://user-images.githubusercontent.com/64096863/109490335-da245880-7a66-11eb-8143-8ead257c9ba8.mp4

**Comment by artf** [comment]
I guess you're doing something wrong, how do you create those components and their properties?? You shouldn't even see those attributes in the editor.

**Comment by marcepoblet** [comment]
@artf  In our codes we have not changed anything. The only difference is that we update the GrapesJs version.
Before I had version v0.16.18 and it worked correctly, but now we update GrapesJs to v0.16.41 and it doesn't work for buttons.

**Comment by marcepoblet** [comment]
we set the properties with this:

    editor.getSelected().attributes.attributes["data-gjs-editable"] = 'false'
    editor.getSelected().attributes.attributes["data-gjs-copyable"] = 'false'
    editor.getSelected().attributes.attributes["data-gjs-droppable"] = 'false'
    editor.getSelected().attributes.attributes["data-gjs-draggable"] = 'false'
    editor.getSelected().attributes.attributes["data-gjs-resizable"] = 'false'
    editor.getSelected().attributes.attributes["data-gjs-stylable"] = 'false'


this way was working perfectly for v0.16.18

**Comment by artf** [comment]
I have no idea what was happening in v0.16.18 but this is completely wrong!
You have to update the model of the component, not its DOM in the view
```js
editor.getSelected().set({
 editable: false,
 draggable: false,
 ....
})
```
