### ISSUE TITLE
[QUESTION]: Multiple pages plugin

### ISSUE THREAD

**Issue by RaresVlaiduc** [artf/grapesjs#3296]
Hello there!

I've seen some discussions about some sort of multiple pages plugin in here.
Is this still a thing? Is there something done regarding this or should I start my own plugin?

Thanks!

**Comment by Ju99ernaut** [comment]
I've made a simple one for indexedDB but it can also be adapted for other storage types https://github.com/Ju99ernaut/grapesjs-indexeddb-ui however I plan on deprecating it in favour of a new plugin that has other storage types built in, also with an improved UI/UX. I plan on releasing it once the `PageManager` api mentioned in issue  #3206 by artf is out, and there might also be another plugin in the works as mentioned in the same issue.

**Comment by artf** [comment]
Yeah, it's still quite in progress (I have no ETA, unfortunately) but for sure the PageManager will be in the core.
