### ISSUE TITLE
want to get edit content when that page close or refresh tab event 

### ISSUE THREAD

**Issue by piyalmaduranga** [artf/grapesjs#33]
problem is when close the grapesjs editor without save it lose the edit content using grepesjs, how can we get the edit content until close it ?
when close tab below event fire , how to get that event?

![screenshot from 2017-01-23 14 55 18](https://cloud.githubusercontent.com/assets/12907174/22198319/0d2e3e86-e17c-11e6-9ab5-d0ff285b53ec.png)

**Comment by artf** [comment]
Hi @piyalmaduranga 
you can override this event easily in this way:

```js
var editor = grapesjs.init({...});
...
window.onbeforeunload = function(e) {
  console.log('Do something');
  //...
  editor.store();
  //...
  return 1; // Return something if you want the alert message
};
```

**Comment by piyalmaduranga** [comment]
Thanks lot
