### ISSUE TITLE
Category order not displaying properly

### ISSUE THREAD

**Issue by RutujaBadbe** [artf/grapesjs#3303]
Hi! 
I want to display the categories in block manager in certain sequence. I looked into docs and previous issues and found about order attribute. So, I tried setting order attribute. but it is not yet displaying in that order even though order attribute is getting set. Am I missing something? or doing something wrong? 

what I am doing is: 
```
var categories = editor.BlockManager.getCategories();
categories.map(category => {
    //console.log(category.id);
    switch (category.id) {
        case 'Header':
            category.order=1;
            break;
        case 'Carousel Banner':
            category.order=2;
            break;
        case 'Sections':
            category.order=3;
            break;
        case 'Category':
            category.order=4;
            break;
        case 'News Letter':
            category.order=5;
            break;
        case 'Footer':
            category.order=6;
            break;
        default:
            break;
    }
});
```
so, expected result is to see categories in sequence- Header, Carousel Banner, Section, Category, News Letter , Footer 

but what I am still getting is this- 
![Capture](https://user-images.githubusercontent.com/53044783/109652612-0387d600-7b86-11eb-88ca-38a9ed0c219a.PNG)

**Comment by Ju99ernaut** [comment]
I think the order in which blocks are added is what determines category order.

**Comment by RutujaBadbe** [comment]
@Ju99ernaut hi! Thanks for the reply. yes. At the end I did that. but what if I want to do it dynamically? if there are many blocks, isn't it hard to maintain the order?

**Comment by Ju99ernaut** [comment]
I guess you can make this a feature request, I'm not sure if something like this exists yet in grapesjs. Though the order of the blocks might be easier to manage if you split each category's blocks into different files then load those files in order.
