### ISSUE TITLE
How I can  customize the UI of Grapesjs? 

### ISSUE THREAD

**Issue by SyedHashimShah** [artf/grapesjs#3304]
I want to customize the ui of Grapesjs but the js and css files are minified.Please tell me how can I do this? I just want to keep some specific blocks like images,text etc in my interface.

**Comment by echobinod** [comment]
Sass is used to generate the minified css files. You can change the style variables from here: **src/styles/scss/**

**Comment by artf** [comment]
@SyedHashimShah https://grapesjs.com/docs/getting-started.html
