### ISSUE TITLE
BUG: (v0.16.41) Button not set as active on click

### ISSUE THREAD

**Issue by RaresVlaiduc** [artf/grapesjs#3305]
**Version: v0.16.41**

**Are you able to reproduce the bug from the demo?**

[ ] Yes
[x] No

**What is the expected behavior?**

When I click on a button, the gjs-pn-active class should be added.

*Describe the bug **detailed***

I have 3 buttons for 3 different devices (desktop, tablet and mobile).
I have them on a top panel and when I click on them the canvas changes the size but the clicked button is not set as active.

**Are you able to attach screenshots, screencasts or a live demo?**

[x ] Yes (attach)
[ ] No

![image](https://user-images.githubusercontent.com/73160095/109790439-164bea80-7c1a-11eb-9aeb-98954166afa2.png)
![image](https://user-images.githubusercontent.com/73160095/109790726-6034d080-7c1a-11eb-9422-09d90836d61c.png)

**Comment by Ju99ernaut** [comment]
Grapesjs requires your commands to have the `run` and `stop` functions,  so maybe that might be the issue:

```js
const cm = editor.Commands;

// grapesjs unable to toggle panel buttons on this command format 
cm.add('desktop', e => e.setDevice('Desktop'))

// grapesjs able to toggle panel buttons because of run and stop
cm.add('desktop', { 
   run(e) {
      e.setDevice('Desktop')
   }, 
   stop() {} 
});
```

**Comment by kerryj89** [comment]
@Ju99ernaut

Thank you for that.  Active state is now working for me when creating `devices-c` panel through `grapesjs.init()`.

```
const editor = grapesjs.init({
    panels: {
        defaults  : [{
            id:       'devices-c', // Responsive view controls
            appendTo: '.gjs-toolbar-responsive-views',
            buttons: [
                { id: "set-device-desktop", command: { run(e) { e.setDevice('Desktop') }, stop() {}}, className: "fa fa-desktop", active: 1},
                { id: "set-device-tablet", command: { run(e) { e.setDevice('Tablet') }, stop() {}}, className: "fa fa-tablet" },
                { id: "set-device-mobile", command: { run(e) { e.setDevice('Mobile portrait') }, stop() {}}, className: "fa fa-mobile" }
            ]
        }]
    }
});
```
