### ISSUE TITLE
FEAT: Provide a not minified version

### ISSUE THREAD

**Issue by neon12345** [artf/grapesjs#3307]
Is there a single file version of grapesjs that is not minified?

It would be nice to have one for bug fixing and quick testing of new features/improvements.

**Comment by Ju99ernaut** [comment]
That's already available, just reference `grapesjs.js` instead of `grapesjs.min.js`

**Comment by mig8447** [comment]
Also the minified file contains the sourcemap which you can use for debugging in the browser development tools

**Comment by neon12345** [comment]
Thanks, I want to do some quick changes and validate them without a dev environment. 

What reference does work without min?

**Comment by Ju99ernaut** [comment]
Looks like grapesjs doesn't ship an unminified version anymore so you might have to rely on the source map, otherwise there's no option but to setup a dev environment.

**Comment by artf** [comment]
Yeah, I've removed it as with the sourcemap there is no need to have the unminified version. About "quick changes", I guess you can simply rely on Chrome Local Overrides which should allow you to edit the file in memory (based on the sourcemap).

**Comment by neon12345** [comment]
It is disappointing that this is just closed. Sure I could change my workflow but why not make it as comfortable as possible for people to contribute?

**Comment by stljeff1** [comment]
Would somebody kindly explain how to use the sourcemap? I am having a very difficult time upgrading to the latest grapes version, and need any debugging help I can get.

I am importing grapesjs into my Angular/Typescript app. I don't understand how I make use of the sourcemap if I am not including the minified file itself.

**Comment by addlistener** [comment]
The point being, using the code below
```
        <GjsEditor
          className="gjs-custom-editor"
          grapesjs="https://unpkg.com/grapesjs"
          grapesjsCss="https://unpkg.com/grapesjs/dist/css/grapes.min.css"
```
I'm not sure about the classname printed in the console
<img width="359" alt="image" src="https://github.com/GrapesJS/grapesjs/assets/4531670/4da3c2cd-2f8e-4188-a4e8-5df8246a25e0">
