### ISSUE TITLE
Demo page and download is not the same? Thank you

### ISSUE THREAD

**Issue by 851091009** [artf/grapesjs#331]

**Comment by artf** [comment]
Can you elaborate better your statement, please

**Comment by 851091009** [comment]
Thanks for your reply！
The demo page is different from the local page
demo:
http://grapesjs.com/demo.html
local：https://github.com/851091009/grapesjs/blob/dev/localhost.png
How can it be the same as the demo page?

**Comment by vignesh1203** [comment]
I can’t able to see import option and export to zip button in the downloaded version. 
But its available in demo version

**Comment by artf** [comment]
The demo just uses a website preset
https://github.com/artf/grapesjs/blob/gh-pages/js/grapesjs-preset-webpage.js
