### ISSUE TITLE
BUG: Tablet and mobile view not resizing

### ISSUE THREAD

**Issue by Andrew-Chen-Wang** [artf/grapesjs#3310]
**Version:** The one in the demo

**Are you able to reproduce the bug from the demo?**

[X] Yes
[ ] No

**What is the expected behavior?**

Mobile and tablet view should resize the canvas when window resizes.

*Describe the bug **detailed***

The desktop view properly resizes the canvas when resizing the window

**What is the current behavior?**

The canvas does not resize when window resizes below certain width for mobile and tablet view. The panel then covers up the canvas. This does not happen on desktop view, only when you view on mobile and desktop view.

*Describe the bug **detailed***

The desktop view properly resizes the canvas when resizing the window. But only the desktop view. The mobile (including portrait and landscape) and tablet views do not resize

**Comment by Ju99ernaut** [comment]
The `mobile` and `tablet` devices are pixel pased, so they just resize the canvas to a certain number of pixels regardless of window size. I believe `desktop` just sets canvas to 100%.

**Comment by artf** [comment]
As mentioned by @Ju99ernaut this is how devices work. 
Honestly, I don't even see the reason behind such a case, why the user should resize the window?  You might also start to see/update styles not related to the proper device and that would be definitely confusing.
