### ISSUE TITLE
FEAT: Make side panel's width to 20%

### ISSUE THREAD

**Issue by Andrew-Chen-Wang** [artf/grapesjs#3312]
**What are you trying to add to GrapesJS?**

The side panel looks scrunched. Unless you've got a big desktop, I'd rather not have images from the blocks panel go off to the side. Additionally, the icons at the top e.g. "getting a new block" icon is just obscured unless you've got a decently large screen.

*Describe your feature request **detailed***

Changing the width of the side panel from 15% to 20%, specifically the class: `gjs-pn-views-container`

**Is there an alternative at the latest version?**

[ ] Yes (descripe the alternative)
[X] No

**Is this related to an issue?**

[ ] Yes (Give a link to the issue)
[X] No

**Comment by Ju99ernaut** [comment]
The idea is to maximize the area covered by the canvas, but you can easily change panel sizes with custom css.

**Comment by Andrew-Chen-Wang** [comment]
For sure, I just don't think the demo should look all scrunched up like that :P I suppose it's personal opinion then.
