### ISSUE TITLE
There are lots of click required to make text editable, can we make text field editable on a single Click.

### ISSUE THREAD

**Issue by fahad157** [artf/grapesjs#3313]
## WARNING
READ and FOLLOW next 3 steps, then REMOVE them before posting the issue

1. Follow CONTRIBUTING Guidelines https://github.com/artf/grapesjs/blob/master/CONTRIBUTING.md
2. Do a quick SEARCH first, to see if someone else didn't open the same issue
3. All relative statements/questions have to be filled/answered, otherwise, the issue might be CLOSED
4. JSFiddle Starter template https://jsfiddle.net/szLp8h4n
5. CodeSandbox Starter template https://codesandbox.io/s/1r0w2pk1vl

**What are you trying to add to GrapesJS?**

*Describe your feature request **detailed***

**Is there an alternative at the latest version?**

[ ] Yes (descripe the alternative)
[ ] No

**Is this related to an issue?**

[ ] Yes (Give a link to the issue)
[ ] No

**Comment by Andrew-Chen-Wang** [comment]
Single click can get annoying when dragging around blocks. If you've already selected a block, you still need to do a double click. If you didn't select a block, then you can just double click the block to edit the text. I think that's pretty standard already.

**Comment by fahad157** [comment]
Yes that's right but in my scenario i want edit on just single click, if it is possible then plz guide.

**Comment by mihir-khandekar** [comment]
@fahad157 were you able to fix this?
