### ISSUE TITLE
mm or cm Units are converted to px

### ISSUE THREAD

**Issue by devtechk** [artf/grapesjs#3315]
I realized that mm or cm units are converted to px. How can i solve this problem? 
Thank you
![image](https://user-images.githubusercontent.com/22073497/110118707-0ddee580-7dbb-11eb-8749-69e918b9ce91.png)

**Comment by Andrew-Chen-Wang** [comment]
I think that's just what the browser engine does in general. I'm no expert, but I think that output is just the final info interpreted by the engine.

**Comment by Ju99ernaut** [comment]
As stated above it's what the browser engine does, usually this is the fix, but I've never used it with units that aren't built in: 
```js
window.editor = grapesjs.init({
   // ...
   styleManager: {
      // ...
      avoidComputed: ['width', 'height', 'padding', 'margin'],
      // ...
   }
   // ...
});
```

**Comment by devtechk** [comment]
Thank you, I'll try this way. I'll update this post. I hope it'll work

**Comment by devtechk** [comment]
Sorry, but it's not working...

**Comment by Ju99ernaut** [comment]
Did you add mm, cm etc, as units to the style manager inputs, these are not built in
