### ISSUE TITLE
FEAT: Add support for promises to custom RTE API

### ISSUE THREAD

**Issue by martijnc** [artf/grapesjs#3317]
**What are you trying to add to GrapesJS?**
Support for richtext editors with promise based APIs.

*Describe your feature request **detailed***
CKEditor5's `Editor.create` and `Editor.destroy` methods return a `Promise` that resolves when the editor has been fully created or destroyed. This causes an issue when destroying the editor (when you finish editing a component) because GrapesJS syncs the changes to the model before the `Editor.destroy` promise has resolved which causes CKEditor HTML to be written to the model.

As a workaround you can sync the content again after the promise has resolved but it would be cleaner if the API supported promises.

We could add this in a backward compatible way be checking if the return values of the RTE's `enable` and `disable` methods are thennable and, if so, wait for the promise to resolve before continuing.

Is this something GrapesJS would consider supporting?

**Is there an alternative at the latest version?**
No

**Is this related to an issue?**
https://github.com/artf/grapesjs/issues/1516
https://github.com/artf/grapesjs/issues/1236

**Comment by artf** [comment]
This should be already possible.
