### ISSUE TITLE
BUG: layers text does not center after creating a new line

### ISSUE THREAD

**Issue by anatoli-dp** [artf/grapesjs#3319]
**Version:**
current?

*You can get the version by typing `grapesjs.version` into the console*

**Are you able to reproduce the bug from the demo?**
[ ] Yes
[ x] No // to be fair never tried in the demo

**What is the expected behavior?**
when editing the layers text and adding a new line then backspacing i would expect the edited text to be recentered

*Describe the bug **detailed***
the text does not recenter but is raised (please see attatched image)

**What is the current behavior?**
text is raised above the center after pressing enter to start a new line and then backspacing out of the line. however completely clearing all text and the retyping does recenter the text.

**Are you able to attach screenshots, screencasts or a live demo?**
[ x] Yes (attach)
[ ] No
![Screenshot (32)](https://user-images.githubusercontent.com/75029364/110149310-8174f880-7da3-11eb-83bd-23dd037a0084.png)cce9b8ed74f8.png)

also attatched is a second image of something which i dont know how to fix. but the toolbar stays in position when resizing the canvas container (not the one grapesjs provides but my own i use for positioning). how can i prevent this from happening? This also happens with the tooltip that says the name of the object when hovering and the outline when hovering. it does not reset

![Screenshot (33)](https://user-images.githubusercontent.com/75029364/110149667-efb9bb00-7da3-11eb-8390-cce9b8ed74f8.png)

**Comment by anatoli-dp** [comment]
im sorry but the picture order is switched. the bottom image  should be on top and vice versa.

**Comment by artf** [comment]
Ok, I'll push a fix for the editing of layers name, probably it doesn't make sense having new lines enabled there (I'll make stop the editing on Enter/Esc).
For the second issue, If you're using something yours to resize the canvas, probably you should call `editor.refresh()` to adjust the toolbar

**Comment by anatoli-dp** [comment]
yeah I didn't realize editor.refresh() was a thing until after. otherwise thanks. awesome project
