### ISSUE TITLE
GrapesJS & NetlifyCMS

### ISSUE THREAD

**Issue by kosirm** [artf/grapesjs#332]
Hi, I've been testing NetlifyCMS lately and I really like it, it has git workfow under the hood, it is under active development and has a great community around it. By default it is using superfast Hugo [site generator](https://www.staticgen.com/), but it is generator-agnostic, so it can be used also with other site generators. I would like to use grapesjs as frontend editor (netlifycms has markdown editor). As far as I can see there is no real chance to do this, as NetlifyCMS has quite small possibilities for [customization](https://www.netlifycms.org/docs/#customization). I would like to know if someone here maybe tried to do this before or has idea how to use GrapesJS & NetlifyCMS together. Any hint much appreciated. Sorry for using Issues as help system, please activate gitter :)

**Comment by kosirm** [comment]
I think I'll give up on that...

**Comment by artf** [comment]
Unfortunately, can't help you here (never used NetlifyCMS), if it's as you said I think there is no other way if not to ask a direct integration by NetlifyCMS team
