### ISSUE TITLE
QUESTION: increase the padding of layer item

### ISSUE THREAD

**Issue by RaresVlaiduc** [artf/grapesjs#3323]
Hi!

I am trying to increase the value of the padding-left in the layer manager.
I've found the file where this is happening but honestly I have no idea how I could modify that.

I could do a small trick to achieve this but I am curios if I can do this by a config or something.

![image](https://user-images.githubusercontent.com/73160095/110297054-b8dde200-7ffb-11eb-8fc5-4b2aba9d1f7b.png)
![image](https://user-images.githubusercontent.com/73160095/110298403-3ce49980-7ffd-11eb-8449-5b9ad9c866a5.png)

**Comment by artf** [comment]
No @RaresVlaiduc as you can see by yourself it's not configurable at the moment, but I'd be happy to accept a PR for such a case (eg. a new function option [here](https://github.com/artf/grapesjs/blob/dev/src/navigator/config/config.js) which takes the level as the argument and returns the number for the padding)
