### ISSUE TITLE
How can I update the nodeValue (text value) of components by inputs forms

### ISSUE THREAD

**Issue by D-Rosa99** [artf/grapesjs#3328]
Hello. 

Grapesjs is a great tool. Thanks for it.

I want to update the text value of a component by inputs, how can I do that??
if a user filled the input box with something like: **TEA SITE**, the title should change to it

![image](https://user-images.githubusercontent.com/43874147/110532756-9d560280-80f3-11eb-8d27-639a006b3e79.png)

**Comment by millord** [comment]
I'm also want something similar with my grapes app, but using react to update a text component via a control input.

**Comment by artf** [comment]
Just find the component and update it as you wish
```js
const typedByUser = 'type something...',
const cmp = editor.getWrapper().find('.any-query-selector')[0];
cmp && cmp.components(typedByUser);
```

**Comment by D-Rosa99** [comment]
it works, thanks
