### ISSUE TITLE
Expand Documentation

### ISSUE THREAD

**Issue by cmcintosh** [artf/grapesjs#333]
It would be good to add a couple of pages in regards to what the accepted Block attributes and other parameters that can be used as a part of the documentation.

Additionally, documentation regarding the proper method of including external styles/js libraries would be good as its own wiki page as I have seen multiple questions around this

**Comment by artf** [comment]
Can you tell me exactly which are your questions about `external styles/js libraries` I've added something here [Components-&-JS](https://github.com/artf/grapesjs/wiki/Components-&-JS) but maybe to too much in details

**Comment by cmcintosh** [comment]
I was thinking more like what unity does for their classes, https://docs.unity3d.com/410/Documentation/ScriptReference/GameObject.html .

**Comment by artf** [comment]
Ah ok got it, would be great to use some tool which does this work automatically (eg. [documentationjs](https://github.com/documentationjs)) and then wrap it in something like [docsify](https://github.com/QingWei-Li/docsify)

**Comment by cmcintosh** [comment]
Im not familiar with the tools but can look into it.  Seeing as this is something im building a Drupal 8 module around it would be beneficial for everyone to have strong docs.

**Comment by artf** [comment]
I close this as https://grapesjs.com/docs/ is actually online
