### ISSUE TITLE
npm start not working

### ISSUE THREAD

**Issue by xinnai** [artf/grapesjs#3333]
Hi, I want to develop the source code but I cannot get started. I got errors when start the project. Can anybody help me? Thank you very much!!!
![Snip20210311_1](https://user-images.githubusercontent.com/23135336/110728865-b1ffdb00-8258-11eb-8cc4-e4c57892a893.png)

**Comment by Andrew-Chen-Wang** [comment]
For source code development, check out: https://github.com/artf/grapesjs#development

**Comment by xinnai** [comment]
@Andrew-Chen-Wang Yeah, I did that, but always get this error, what can I do?

**Comment by Andrew-Chen-Wang** [comment]
@xinnai I'm unable to reproduce that error. Maybe try deleting that entire directory and restart the clone. Then run those exact commands again. Finally, if that doesn't work, do you mind providing the debug log from `.npm/_logs/blah` where blah is that error log from the provided error message. That'd be helpful!

**Comment by xinnai** [comment]
@Andrew-Chen-Wang Thank you very much for your help, here is the log file
[2021-03-14T07_03_24_710Z-debug.log](https://github.com/artf/grapesjs/files/6138148/2021-03-14T07_03_24_710Z-debug.log)

**Comment by Andrew-Chen-Wang** [comment]
Hey @xinnai have you resolved it yet? I'm not sure what's going on... my only recommendation is to fork it and try again using your fork.

**Comment by xinnai** [comment]
@Andrew-Chen-Wang I think that must be something with my develop environment so I use another computer to install and move it to my computer , still don't know why but now it works fine. Hope no errors happen again, and thank you so much!!!
