### ISSUE TITLE
Creating trait with Style Manager property UI

### ISSUE THREAD

**Issue by zachsnoek** [artf/grapesjs#3335]
I have a component using the `background-url` Style Manager property:

```
editor.DomComponents.addType('mj-hero', {
    model: {
	defaults: {
            // ...
	    stylable: ['background-url'],
	},
    },
});
```

I would like to reuse this UI that is shown in the Style Manager for a background URL trait that shows up under "Settings":

![Screen Shot 2021-03-11 at 12 28 27 PM](https://user-images.githubusercontent.com/26049962/110852079-be8b3000-8266-11eb-9e59-2802744c9e4a.png)

Is it possible to make a Style Manager property behave like a trait and show up in the "Settings" section, or would I have to create a new trait with this UI?

Thanks.

**Comment by artf** [comment]
Unfortunately, it's not yet possible, but there is a plan to add soon a new UI module that should allow the reuse of UI elements

**Comment by zachsnoek** [comment]
:+1: Thank you!
