### ISSUE TITLE
gjs-cv-tools in a wrong position when I put grapesjs in a splitpanes

### ISSUE THREAD

**Issue by xinnai** [artf/grapesjs#3340]
Hi, Thank you for your work. I get a problem. I want to make a codepen-like view and want to make the grapesjs view to be dragable up and down. But when I drag it the tools go to the wrong position and also the hover highlight elements's position is wrong.I tried splitjs and other split open source code and always got this problem.  Cound you help me please? Thank you so much!!!

https://user-images.githubusercontent.com/23135336/111138227-a5fa7d00-85ba-11eb-9393-0f3307322a56.mp4

**Comment by Ju99ernaut** [comment]
You can try running `editor.refresh()`

**Comment by xinnai** [comment]
@Ju99ernaut Thank you very much, you save my day!
