### ISSUE TITLE
Question:  Social Media Group - Facebook

### ISSUE THREAD

**Issue by HeyWrecker** [artf/grapesjs#3341]
Hello,

Is the Facebook social media component intended to be used to provide a Facebook link to a business or organizations Facebook page or is it exclusively designed to share something specific to your timeline? It appears to be the latter, even though that seems counter-intuitive to me since many emails simply provide links to the social media accounts in the headers and footers. I'd just like some confirmation on how it is intended to work and if there are any workarounds or plans to change this behavior if it is indeed functioning as designed.

Best,
Rick

**Comment by HeyWrecker** [comment]
As a follow-up, I have confirmed that the Instagram social component does link to the IG profile page. Whereas the Facebook option does not.

**Comment by artf** [comment]
Hi Rick, I think you're on the wrong repo 😅 
This one is intended only for core related issues

**Comment by HeyWrecker** [comment]
Hi Art,

Which repo should I ask this on? Are Social Media Components in GrapesJS on a different repo?

**Comment by artf** [comment]
I guess you're looking for this https://github.com/artf/grapesjs-mjml

**Comment by HeyWrecker** [comment]
Ah, my mistake, then, thank you!
