### ISSUE TITLE
FEAT: I am trying to get js using getJs() method but i am getting null value. How I can get js?

### ISSUE THREAD

**Issue by NagarRahul** [artf/grapesjs#3344]
![image](https://user-images.githubusercontent.com/42827466/111476570-4b952400-8754-11eb-8d3c-1b8b9d29156c.png)

**Comment by NagarRahul** [comment]
@artf

**Comment by artf** [comment]
That method takes the JS used in your components. So, if you don't have components with JS it'll be empty
