### ISSUE TITLE
Related Links ?

### ISSUE THREAD

**Issue by FlashPapa** [artf/grapesjs#335]
On the [newletters demo](http://grapesjs.com/demo-newsletter-editor.html), the linking of text does not work with the ckeditor plugin, the code is not updated. We are forced to click again on the text box to force the update of the source.
There is the same problem with grapesjs-mjml

It is damage, that makes this beautiful program is unusable with basic things!

**Comment by artf** [comment]
Does this solve the issue?
```js
document.querySelector('.cke_dialog').addEventListener('mousedown', function(e){ 
    e.stopPropagation();
})
```

**Comment by FlashPapa** [comment]
Actually it works, I have extended the problem on the modal backdrop and it is ok!
Like this : 
```        
CKEDITOR.on('dialogDefinition', function(e) {
            $timeout(function() {
                document.querySelector('.cke_dialog_background_cover').addEventListener('mousedown', function(e) {
                    e.stopPropagation();
                });
                document.querySelector('.cke_dialog').addEventListener('mousedown', function(e) {
                    e.stopPropagation();
                });
            }, 300);
        });
```

Regards,
