### ISSUE TITLE
Uncaught TypeError: can't access property "el", n is undefined

### ISSUE THREAD

**Issue by devtechk** [artf/grapesjs#3350]
Hello, I'm using grapesjs 0.16.44 and only in firefox I'm faceing this issue.
Using grapesjs block basic preset.
Anyone can help me?

Thank you a lot!

![image](https://user-images.githubusercontent.com/22073497/111650465-9b7ff380-8805-11eb-87a6-7b653997367d.png)

![image](https://user-images.githubusercontent.com/22073497/111650496-a5a1f200-8805-11eb-91e9-1f16c3dc7f0b.png)

**Comment by devtechk** [comment]
Problem "solved" removing :
```
const panelManager = editor.Panels;
**panelManager.getButton('views', 'open-blocks').set('active', true);**

```
looking for a better solution to make active the block panel af first

**Comment by artf** [comment]
try to place your code inside
```js
editor.on('load', () => {
 // ...
})
```
