### ISSUE TITLE
BUG: Default Content is getting Inserted while using setComponents if Tag Body is empty

### ISSUE THREAD

**Issue by harsh201** [artf/grapesjs#3352]
**Version:** Latest

*You can get the version by typing `grapesjs.version` into the console*

**Are you able to reproduce the bug from the demo?**

 - [X] Yes
 - [ ] No

**What is the expected behavior?**
Component with empty body should not be populated with default content. 

**What is the current behavior?**
When we create an empty node and pass it on to GrapesJS as input using setComponents(), the component extending TextNode adds default content if tag body is empty.

*Describe the bug **detailed***
When we create an empty node and pass it on to GrapesJS as input using setComponents(), the component extending TextNode adds default content if tag body is empty. We have use cases where some tags might be empty. Is there a way we can handle where we can disable it inserting it via setComponents?

Demo:
https://jsfiddle.net/senbyh2g/1/

**Comment by harsh201** [comment]
@artf Any help here?

**Comment by artf** [comment]
You have defined the default `content` in the component definition, so, an empty one will use that as default. 
Just move that `content` from component definition to the `paragraph` block.

**Comment by harsh201** [comment]
Thanks @artf! Completely forgot about adding at block level.
