### ISSUE TITLE
BUG: The colorpicker scroll off the input box

### ISSUE THREAD

**Issue by jcsofts** [artf/grapesjs#3353]
thanks for your work, this is a good project, this may be is not a bug
I trying to make the colorpicker in style manager scroll with the input box. 
for example:
 the (color,background) input box
1. open the colorpicker
2. scroll the style manager
the input box moved, but the colorpicker stay at the old position

I try this on the grapesjs demo site

<img width="506" alt="WeChat944c23a71851577e18470c0dec31441e" src="https://user-images.githubusercontent.com/33087222/111763958-a73ee900-88dd-11eb-9751-b6012039d577.png">
<img width="510" alt="WeChat96482d571136e2371f981b54f8774b31" src="https://user-images.githubusercontent.com/33087222/111763973-ae65f700-88dd-11eb-991c-5c4abb53dc38.png">

how to make the colorpicker scroll with the inputbox?

**Comment by artf** [comment]
The color picker is placed absolutely. Unless you'll find a way to update it on the scroll of the style manager, I don't see alternatives.
