### ISSUE TITLE
FEAT: Add a title attribute to the Layers panel elements

### ISSUE THREAD

**Issue by Franci5co5aoco** [artf/grapesjs#3355]
Hi @artf ,

When I have several elements nested in the Layers panel then some elements names are truncated because the Layer panel's width is not big enough, I know that custom resizable panel can be a solution but adding a title attribute would be enough for the majority of the use cases.

![Screenshot 2021-03-22 at 14 50 53](https://user-images.githubusercontent.com/23215166/112005599-338e1d80-8b23-11eb-9596-8e436734d383.png)

A tooltip (title) would be helpful to the user.

**grapesjs/src/navigator/view/ItemView.js**
May be adding a title attribute to the follow line can do the job?
https://github.com/artf/grapesjs/blob/7a23e20fe5138c37088ef05382f7c759cb6fa951/src/navigator/view/ItemView.js#L47  
  
Example:
```javascript
<div class="${pfx}layer-title-inn" title="${name}">
```

Let me know what do you think,

Thanks!

**Comment by artf** [comment]
Yeah, why not... would you like to create a PR? :)

**Comment by Franci5co5aoco** [comment]
@artf of course, thanks!
I'm going to create the PR...
