### ISSUE TITLE
FEAT: Unminified version in the latest release

### ISSUE THREAD

**Issue by mitcht** [artf/grapesjs#3356]
**What are you trying to add to GrapesJS?**
Un-minified versions for each release

*Describe your feature request **detailed***
I am working with some more complex methods utilizing the Component Manager.  The last release that had an un-minified 'debug' version was 0.15.xx.  Can you please release the unminified as well as the minified versions, so stepping into the code is possible?

_This request comes from me trying to explain to a coworker how the addComponent feature worked and I could not explain it fully, so I tried to step into the code only to find that no unminified version existed_

**Is there an alternative at the latest version?**

 - [ ] Yes (describe the alternative)
 - [X] No - I would want to use the latest version, not an older version for this feature

**Is this related to an issue?**

 - [ ] Yes (Give a link to the issue)
 - [X] No

**Comment by artf** [comment]
Hi @mitcht the current bundle includes the minified file but also its source map, so you can easily view the original code from dev tools (more about it [here](https://developers.google.com/web/tools/chrome-devtools/javascript/source-maps)), therefore there is no reason to include also the unminified version if you need to debug the code.
And what about your case, I think showing directly the source code (on Github) is way more informative.
