### ISSUE TITLE
[Question] How to disable editing on fetched content

### ISSUE THREAD

**Issue by DwolinH** [artf/grapesjs#336]
Hi, 
i want to integrate your project into an existing webpage as a kind of CMS-editor. It is necessary for the editor to wrap the whole body of the page, but i want only parts of the fetched content to be editable. The website header, sidebar and footer should be unchangeable.

Is there an option to differentiate between the editors container and the editable elements?

example markup:

```
<body>
   <header>...</header>
   <div id="content-wrapper">
      <div id="content" class="editable">...</div>
      <aside id="sidebar">...</div>
   </div>
   <footer>...</footer>
</body>
```

**Comment by artf** [comment]
All components are editable by default, you can change their properties with `data-gjs-*` attributes
```html
<header data-gjs-editable="false" data-gjs-removable="false" ...>...</header>
```
To get more about components check [here](https://github.com/artf/grapesjs/wiki/Components)

**Comment by DwolinH** [comment]
That is not really feasible to rewrite thousands of files/ HTML-tags.

Maybe it is better to set components attributes to false after editor.init() and find a way to enable it on specific areas.

**Comment by artf** [comment]
Probably the easiest way is to update all components
```js
const updateComp = (component) => {
    if (/* is not editable */) {
        component.set({
            removable: false,
                ...
            })
    }
    component.get('components').each(c => updateComp(c))
}
editor.domComponents.getComponents().each(c => updateComp(c))
```
