### ISSUE TITLE
BUG: Set content function empties the component content

### ISSUE THREAD

**Issue by nairdapuiu** [artf/grapesjs#3363]
I am trying to use the set function to change the content of a component, but actually the result is an empty component with nothing inside.

This is an example with the code summarized 

```
editor.on('component:selected', () => {
    const selectedComponent = editor.getSelected()
    selectedComponent.set('content', "foo")
  });
```

**Version used: 0.16.44**

**What is the expected behavior?**

The code executed should result in a component with text "foo" inside.

**What is the current behavior?**
The executed code empties the component content.

In version 0.16.34 everything works as expected.

Is there an workaround for this issue or should i stick with 0.16.34 verison ?

**Comment by artf** [comment]
you shouldn't use the `content` property, use `selectedComponent.components(str)`
