### ISSUE TITLE
FEAT: @How to fix container size when we are drag element inside the container,Container will be expended according to the child dragged element. How we can auto size child element according to the parent container. Container should not be expend according to the child element. It's should be show scroll. 

### ISSUE THREAD

**Issue by NagarRahul** [artf/grapesjs#3364]
## WARNING
READ and FOLLOW next 3 steps, then REMOVE them before posting the issue

1. Follow CONTRIBUTING Guidelines https://github.com/artf/grapesjs/blob/master/CONTRIBUTING.md
2. Do a quick SEARCH first, to see if someone else didn't open the same issue
3. All relative statements/questions have to be filled/answered, otherwise, the issue might be CLOSED
4. JSFiddle Starter template https://jsfiddle.net/szLp8h4n
5. CodeSandbox Starter template https://codesandbox.io/s/1r0w2pk1vl

**What are you trying to add to GrapesJS?**

*Describe your feature request **detailed***

**Is there an alternative at the latest version?**

 - [ ] Yes (describe the alternative)
 - [ ] No

**Is this related to an issue?**

 - [ ] Yes (Give a link to the issue)
 - [ ] No

**Comment by NagarRahul** [comment]
@artf 
![image](https://user-images.githubusercontent.com/42827466/112465042-40607a80-8d8a-11eb-828c-a0e88ca7e113.png)
when I drag button it is expend. I want to fix it. It's should not expend when drag new button. It will shoe scroll after overflow.

**Comment by artf** [comment]
it just depends on the styling of the component (eg. using display inline-block for that button might fix the that)
