### ISSUE TITLE
QUESTION: contenteditable attribute on Layer's name span

### ISSUE THREAD

**Issue by Franci5co5aoco** [artf/grapesjs#3365]
Hi @artf 

I would like to know why layer's name span has a `contenteditable` attribute.

There is no mechanism implemented on grapesJs to really change the layer name after refreshing the page if I'm not wrong.
It can be a little bit confusing to the user.

```html
<div class="gjs-layer-title-inn">
  <i class="gjs-layer-caret fa fa-chevron-right" data-toggle-open=""></i>
  <span class="gjs-layer-name gjs-no-app gjs-layer-name--no-edit" data-name="" contenteditable="true">Image</span>
</div>
```

Thanks.

**Comment by artf** [comment]
If you double click on the layer name you can actually change its name :)

**Comment by Franci5co5aoco** [comment]
@artf , sorry I think I was misunderstood. 
I meant you can change the name but when you refresh the page the changes are not been saved... and I think that there isn't a mechanism implemented to achieve it.
I would like the people using the editor can change the layer name and save it.

Here a little video showing the case using the official GrapesJs demo:
*I changed the`Header` layer's name to`Test` when refreshing the page `Header` stills the name of the layer. Is it the expected behaviour?*

Thanks a lot for your time.

https://user-images.githubusercontent.com/23215166/113898126-dacdae80-97cb-11eb-9224-1d57d2d53195.mov

**Comment by artf** [comment]
No, the mechanism to store/load custom layer names is there, the only issue is that the change is not triggering the store... indeed, if you try to move some component right after the change, you will see them after page refresh.
Anyway, this should be fixed with the upcoming page manager module.
