### ISSUE TITLE
Extending preview command

### ISSUE THREAD

**Issue by kerryj89** [artf/grapesjs#3366]
I am trying to extend the `preview` command.  I expected the code below to run the normal preview command along with console output, but only console statement runs.  How can I preserve the original preview code?

```
editor.Commands.extend('preview', {
    run() {
        console.log("foo");
    }
});
```

The below works for me until someone can enlighten where my thought process went wrong.

```
editor.Commands.add('preview-ext', {
    run(e) {
        e.runCommand('preview');
        console.log("foo");
    }
});
```

**Comment by artf** [comment]
If you specify a new `run()` function the command will run only the new one, otherwise, it wouldn't be possible to fully change a command (here more about [extending commands](https://grapesjs.com/docs/modules/Commands.html#extending))

**Comment by ronaldohoch** [comment]
Hello Artf, oddly enough, i need the same thing he does.

So, the best way to do is doing the same way he does? Running the original preview command inside the extended preview?

**Comment by ronaldohoch** [comment]
Well...

Other thing i'm doing is extending the preview by running the command on event.:

```js
  editor.on("run:preview",()=>{console.log("run-preview")});
  editor.on("stop:preview",()=>{console.log("stop-preview")});
  ```
