### ISSUE TITLE
Modal template

### ISSUE THREAD

**Issue by kerryj89** [artf/grapesjs#3367]
Is there a way for me to modify the template from a compiled state?

https://github.com/artf/grapesjs/blob/d3256e621bb43a537213ffcd86b10dc0bd070c0b/src/modal_dialog/view/ModalView.js#L1-L16

If not, what would be the cleanest way to insert title and content into a modal skeleton from our CMS for a tighter look and feel?  I realize by doing that it would lose grapesjs modal open close events.

**Comment by Ju99ernaut** [comment]
Here's a list of plugins that use the built in modals, hopefully they're helpful:
https://github.com/artf/grapesjs-tui-image-editor
https://github.com/artf/grapesjs-custom-code
https://github.com/Ju99ernaut/grapesjs-template-manager
https://github.com/Ju99ernaut/grapesjs-script-editor
https://github.com/Ju99ernaut/grapesjs-blockly

**Comment by kerryj89** [comment]
Thanks, but I was looking for a way to inject the content into my own modal.  A lot of plugins have a modal template variable to do this.

**Comment by artf** [comment]
Now it's possible to replace the modal https://grapesjs.com/docs/modules/Modal.html#custom-modal
