### ISSUE TITLE
FEAT: is it possible add a relative offset for the colorpicker

### ISSUE THREAD

**Issue by jcsofts** [artf/grapesjs#3369]
![image](https://user-images.githubusercontent.com/33087222/112741199-0a074300-8fb6-11eb-83e9-aa665b9291d3.png)
for example:
I add a left bar and top bar outside the editor. I know the colorpicker's position is relative the body, so is it possible add a relateoffset to the config. so I can add a -40 to mek the colorpicker to right position?

**Comment by artf** [comment]
You should be able to define color picker options in this way
```js
grapesjs.init({
   colorPicker: {
      ...
    }
});
```
here you can check all the [available options](https://github.com/artf/grapesjs/blob/86ce053309235c2a0a8bed9d9ded4326e82310df/src/utils/ColorPicker.js#L11)

**Comment by skru** [comment]
Is it possible to access the colorPicker after .init()?
