### ISSUE TITLE
IE 11 issue

### ISSUE THREAD

**Issue by vmourya** [artf/grapesjs#337]
Can not drop components on canvas in IE 11 but working fine in Firefox, Chrome.
While clicking on blocks to drag getting error in console: **Object doesn't support property or method 'matches'**
Also checked on http://grapesjs.com/demo.html getting same error.

TIA

**Comment by artf** [comment]
Duplicate of #214

**Comment by ruelcena** [comment]
Hey Guys, 
I don't this is fix but it works fine, here is what I do. Please have a look all matches error and replace this
`this.matches` that's it.
