### ISSUE TITLE
Question: Predefined background colors when selecting a element with a certain class or div. 

### ISSUE THREAD

**Issue by ikenderham** [artf/grapesjs#3373]
**I have a question i hope sombody can help with.**

I want to make a trait where i can chose predefined colors, when selecting a div with a certain div. Can anyone help me, how to achive that in a simple way?

**Comment by artf** [comment]
Well, you can use a simple select trait type with the list of colors and update its style once is changed.
Here you can find all the examples necessary for your case: https://grapesjs.com/docs/modules/Traits.html
