### ISSUE TITLE
images and videos are not focused

### ISSUE THREAD

**Issue by FacuCarbon** [artf/grapesjs#3374]
Hello, I have a problem which is that when adding a video or an image to the canvas, it is not centered, but to the left. With the help of the panel I set the alignment but it does not center it either.

![image](https://user-images.githubusercontent.com/67525225/113194408-7f357b00-9237-11eb-973b-fa7305418354.png)

**Comment by Ju99ernaut** [comment]
Try placing it inside a container, you can probably centre it using something like flexbox.
