### ISSUE TITLE
Cannot add spaces to extended button component based on text component.

### ISSUE THREAD

**Issue by christosapos** [artf/grapesjs#3375]
Hello guys,

First of all i would like to express my gratitudes for this amazing tool. I have extended button component based on text component so as to can edit the content of button manually without using traits.
The code for the extended button component is this:

var comps = editor.DomComponents;
var defaultType4 = comps.getType('text');  
    
editor.DomComponents.addType('button', {
  
 model:{
      defaults: {
          tagName: 'button',
          classes: ['.pointer'], //Add click pointer on hover,
      },
 },
 
  extend: 'text',
  isComponent: function (el) {
      if (el.tagName === 'BUTTON')
          return {type: 'button'};
  },
  view: defaultType4.view.extend({

    events: {
      dblclick: 'onActive',
      input: 'onInput',
      dragstart: 'handleDragStart',
      click: function() {
         /*Click function */
      }
    },
  })  

})

At this point i am capable of edit content of button components manually. Now the problem that i am dealing with is that i can not add space characters inside content of buttons.Can anyone help me ?

**Comment by artf** [comment]
Seems like space triggers the `click` event in Chrome. The solution seems to be to add the preventDefault on `keypress` https://stackoverflow.com/questions/22104860/chrome-firing-onclick-when-space-typed-in-contenteditable-button

ps. avoid extending the view in that way. By default, when you use `extend` of some type, it's also extending its view (if you need to extend the view of another component you can use ` extendView: 'another-component-type',`)
