### ISSUE TITLE
Changing upload URL for AssetManager programmatically

### ISSUE THREAD

**Issue by rcloss** [artf/grapesjs#3376]
I've got an situation where depending on how the Asset Manager is opened I want to pass a slightly different upload URL.

In the asset:upload:start event I have it looking to see which upload URL it should use, and if I have to change it I'm doing the 

amConfig = editorAssetManager.getConfig()
amConfig.upload = 'NEW URL'

but it's not using the new URL for the upload it sticks with the one defined on init. Is there way to update the config once grapesjs has been loaded? I don't see a set or a setConfig anywhere

**Comment by Ju99ernaut** [comment]
The value in config is only used during init so changing it does nothing, maybe changing these might help:
```js
editor.Assets.FileUploader().config.upload = 'NEW_URL';
editor.Assets.AssetsView().config.upload = 'NEW_URL'
```

**Comment by rcloss** [comment]
Thanks, just tried both of those, but no luck, at least in the asset:upload:start event

**Comment by artf** [comment]
The `asset:upload:start` is triggered right after taking the url from config, so you have to find a way to update it before that event

**Comment by SzaboGabesz** [comment]
editor.AssetManager.config.upload = 'NEW_URL' will do it
