### ISSUE TITLE
BUG: StyleManager options repeating 2 times

### ISSUE THREAD

**Issue by assadnazar** [artf/grapesjs#3377]
**Version: 0.16.45**
If i add grapejs-preset-js, then stylemanager repeats each option 2 times.

Here is the jsfiddle link where you can check the same behaviour.
[https://jsfiddle.net/assadnazar/2asojqrc/1/](https://jsfiddle.net/assadnazar/2asojqrc/1/)

Maybe it's not merging the options

**Comment by assadnazar** [comment]
bump!

**Comment by Ju99ernaut** [comment]
Use:
```js
window.editor = grapesjs.init({
   // ...
   styleManager: {
      clearProperties: 1
   },
   // ...
});
```
