### ISSUE TITLE
FEAT: Tailwind CSS

### ISSUE THREAD

**Issue by virgiltu** [artf/grapesjs#3379]
I think the one thing that would make this builder amazing is adding tailwind css classes. Especially now with the new tailwind css on demand generator.

**Comment by Ju99ernaut** [comment]
I'm not sure if this is something that can be added to the core library, but definitely a plugin for that would be awesome.

**Comment by artf** [comment]
Yeah, I agree with Brendon, this is definitely something that could be added as a plugin for sure
