### ISSUE TITLE
BUG: Default properties not selected in styleManager

### ISSUE THREAD

**Issue by alemenciones** [artf/grapesjs#3380]
Hello dear, can you know why default properties is not selected in style manager ??

What event can I trigger to update this ??

![image](https://user-images.githubusercontent.com/2309686/113360884-0ca0ca00-9321-11eb-9542-c38bc6c85a92.png)

**Comment by artf** [comment]
Try to check your configuration for the `styleManager` https://github.com/artf/grapesjs/blob/dev/src/style_manager/config/config.js (highlightChanged should be `true`)
