### ISSUE TITLE
BUG: Not able to add more than 2 projects under free version

### ISSUE THREAD

**Issue by Squirrel1489** [artf/grapesjs#3382]
![Screenshot (11)](https://user-images.githubusercontent.com/57554308/113369015-1a505280-9315-11eb-8d48-c9b8bdef335e.png)
## WARNING
READ and FOLLOW next 3 steps, then REMOVE them before posting the issue

1. Follow CONTRIBUTING Guidelines https://github.com/artf/grapesjs/blob/master/CONTRIBUTING.md
2. Do a quick SEARCH first, to see if someone else didn't open the same issue
3. All relative statements/questions have to be filled/answered, otherwise, the issue might be CLOSED
4. JSFiddle Starter template https://jsfiddle.net/szLp8h4n
5. CodeSandbox Starter template https://codesandbox.io/s/1r0w2pk1vl
![Screenshot (11)](https://user-images.githubusercontent.com/57554308/113412676-c160d880-936d-11eb-8983-84c433e67106.png)

**Version:**

*You can get the version by typing `grapesjs.version` into the console*

**Are you able to reproduce the bug from the demo?**

 - [x] Yes
 - [ ] No

**What is the expected behavior?**

*Describe the bug **detailed***

**What is the current behavior?**

*Describe the bug **detailed***

**Are you able to attach screenshots, screencasts or a live demo?**

 - [x] Yes (attach)
 - [ ] No

**Comment by Ju99ernaut** [comment]
`grapesjs` and `grapedrop` are separate projects, you should try raising your issue here  https://spectrum.chat/grapedrop
