### ISSUE TITLE
FEAT: Load through URL

### ISSUE THREAD

**Issue by assadnazar** [artf/grapesjs#3387]
Can we add an option to load through URL?

e.g.

we pass a URL to the init and there it initializes the page with editor?

**Comment by Ju99ernaut** [comment]
Pretty hard to come up with a universal solution due to CORS restrictions.

**Comment by artf** [comment]
> Pretty hard to come up with a universal solution due to CORS restrictions.

Correct, if your intention is to load HTML of some external site, you should have a server to fetch the content.

**Comment by assadnazar** [comment]
@Ju99ernaut, @artf I want to load same domains' pages to edit html for.

**Comment by artf** [comment]
ok @assadnazar but when you're requesting a feature for the core library you should also think about how the thing will be perceived by other users, not only in your particular case.
