### ISSUE TITLE
Save the template into Database

### ISSUE THREAD

**Issue by mekamleshk** [artf/grapesjs#339]
Hi artf,

thanks for creating such a wonderful framework, I am using it for newsletter.
I just had a question on how can I store the template into my database and retrieve it for different types of newsletter I create.

**Comment by cmcintosh** [comment]
Take a look at https://github.com/artf/grapesjs/wiki/API-Storage-Manager

**Comment by mekamleshk** [comment]
Thank you @cmcintosh

**Comment by artf** [comment]
For an example on how to configure the Remote Storage, check here #122 Hope to post soon some wiki about it

**Comment by mekamleshk** [comment]
I am not able to find in which function or object is the data of html, css and js of the template been stored,  In case I want to send that data via ajax post what needs to be done please provide some inputs
@cmcintosh

**Comment by cmcintosh** [comment]
you can use editor.getHtml() or editor.getCss() respectively to get that part.  What i am doing is storing the json returned when it sends to post to my endpoint, then just returning when the editor calls my load endpoint.

**Comment by mekamleshk** [comment]
This is my code :
`var editor = grapesjs.init({
      container : '#gjs',
      storageManager:{
          autoload: 0,
           type: 'remote',
           urlStore: 'http://cimailer.dev/lets_dragdrop',
           urlLoad: 'http://cimailer.dev/lets_dragdrop',
        },
      plugins: ['gjs-preset-newsletter'],
      pluginsOpts: {
        'gjs-preset-newsletter': {
          modalTitleImport: 'Import template',
        }
      }
     
  });

       var pnm = editor.Panels;
       pnm.addButton('options', [{ 
        id: 'save-database',
        className: 'fa fa-floppy-o',
        command: 'save-database',
        attributes: {
          title: 'Save to database'
        } } ])

       var cmdm = editor.Commands;
       cmdm.add('save-database', 
        {
          run: function (em, sender) 
          { 
            sender.set('active', true);
            var InnerHtml = this.frameEl.contentDocument.activeElement.innerHTML;
            $.post("http://cimailer.dev/lets_dragdrop", {html: InnerHtml},
            function (result)
            {  

            }); 
          }, 
        });`

Little Confused with [https://github.com/artf/grapesjs/issues/122](url)

**Comment by artf** [comment]
@mekamleshk your code should work, where is the problem?

**Comment by mekamleshk** [comment]
Not receiving data in POST @artf

**Comment by artf** [comment]
> Not receiving data in POST

Well, might be just a problem with your server script, so it's not helping. Check what it's sending in devtools

**Comment by mekamleshk** [comment]
Hi @artf 

It was just the double quotes, now I can get the data in post

` var editor = grapesjs.init
       ({
          height: '100%',
          fromElement: 1,
          clearOnRender: true,
          container : '#gjs',
          plugins: ['gjs-preset-newsletter'],
          storageManager: {
          autosave: false,
          setStepsBeforeSave: 1,
          type: 'remote',
          urlStore: 'http://cimailer.dev/lets_dragdrop',
          urlLoad: 'http://cimailer.dev/lets_dragdrop',
          contentTypeJson: true,
          },
      });

      editor.Panels.addButton
      ('options',
        [{
          id: 'save-db',
          className: 'fa fa-floppy-o',
          command: 'save-db',
          attributes: {title: 'Save DB'}
        }]
      );

    // Add the command
    editor.Commands.add
    ('save-db',
    {
        run: function(editor, sender)
        {
          sender && sender.set('active', 0); // turn off the button
          editor.store();

          var htmldata = editor.getHtml();
          var cssdata = editor.getCss();
          console.log(htmldata);
          console.log(cssdata);
          $.post("http://cimailer.dev/lets_dragdrop",
          {
            "html": htmldata,
            "css": cssdata
          });          
        }
    });`


I have a question on store Manager it doesn't seem to work:

` storageManager: {
          autosave: false,
          setStepsBeforeSave: 1,
          type: 'remote',
          urlStore: 'http://cimailer.dev/lets_dragdrop',
          urlLoad: 'http://cimailer.dev/lets_dragdrop',
          contentTypeJson: true,
          },`

**Comment by artf** [comment]
@mekamleshk please use ``` for posting formatted code, anyway I don't understand where is your problem...

**Comment by mekamleshk** [comment]
@artf If you see at the bottom of the code I am using ajax post, I don't want to use it.
I have a question why are the load and store urls in the storageManager not being used :

`storageManager: { 
autosave: false,
type: 'remote', 
urlStore: 'http://cimailer.dev/lets_dragdrop',
 urlLoad: 'http://cimailer.dev/lets_dragdrop', 
contentTypeJson: true,
 },`

**Comment by artf** [comment]
Are you able to see the ajax call in inspector? 
Have you tried to add storage listeners?
```js
editor.on('storage:load', function(e) {
      console.log('Loaded ', e);
})
editor.on('storage:store', function(e) {
      console.log('Stored ', e);
})
```

**Comment by pheeque** [comment]
Hi @mekamleshk ,

I find myself in a situation similar to yours. My urlStore endpoint gets called. The urlLoad endpoint is also called but nothing further happens and the 'storage:load' event listener is ignored . It perhaps failed somewhere parsing the urlLoad input.

Could you be so kind as to show me a sample of what your server outputs at the urlLoad endpoint? I return what I get from the urlStore but that appears to be wrong?? From what I can tell, adding the event listeners solved your problem?

Thank you.

**Comment by shareefhiasat** [comment]
@kamleshkatpara i dont understand on your last post you said it worked , i noticed you removed the post part.
while at first post or second you say is storeurl or loadurl is even used !.

what happend since you discarded your post part, dose the store automatically send the html and css objects/jsons, because in my case it **dose** not send it

@artf  can you comment please thanks , docs dose not clearly say what it will send to store/load url as parameter

**Comment by artf** [comment]
@shareefhiasat read this https://github.com/artf/grapesjs/wiki/Storage

**Comment by abdodeve** [comment]
>Thank you my problem was i missed this -----> before retrieving html editor.store();

**Comment by ratermegh** [comment]
I have written the same code as @kamleshkatpara written.. but It is not working. The template what I created, it is not saving at given localhost folder.

var editor = grapesjs.init({
        height: '100%',
       
        container : '#gjs',
        fromElement: true,
        storageManager: {
              autosave: false,
              setStepsBeforeSave: 1,
              type: 'remote',
              urlStore: 'localhost://C:/wamp/www/templates',
              urlLoad: 'localhost://C:/wamp/www/templates',
              contentTypeJson: true,
              },
        plugins: ['gjs-preset-newsletter'],
});

var pnm = editor.Panels;
var cmdm = editor.Commands;

//Add Save button
		pnm.addButton('options',
        [{
          id: 'save-db',
          className: 'fa fa-floppy-o',
          command: 'save-db',
          attributes: {title: 'Save DB'}
        }]
      );
	cmdm.add('save-db',
        {
            run: function(editor, sender)
            {
              sender && sender.set('active'); // turn off the button
              editor.store();
              
                editor.on('storage:load', function(e) {
                    console.log('Loaded ', e);
              });

              editor.on('storage:store', function(e) {
                    console.log('Stored ', e);
              });         
            }
        });

Please let me know, What I did wrong? Why the template is not saved?
