### ISSUE TITLE
UndoManager add

### ISSUE THREAD

**Issue by ExReminiscence** [artf/grapesjs#3394]
how to add undo/redo event to UndoManager from custom rich text editor ckeditor?

**Comment by Ju99ernaut** [comment]
`UndoManger` usually tracks changes to component models, so if you can record the changes from the rte in the component in some way it could work. I'm not completely sure how this would work so I can't give a more in depth description. Anyway ckeditor does come with it's own undomanager so alternatively you could use that, you'd probably just need to include the undo/redo buttons in your config

**Comment by artf** [comment]
Yeah, as already mentioned by @Ju99ernaut all major RTE editors implement their own undo manager. Indeed, when the RTE is enabled (built-in or a custom one) all shortcuts are disabled, in order not to mess with text editing (when you edit text and press CTRL+Z you expect to undo the edited text).
