### ISSUE TITLE
mod is not defined

### ISSUE THREAD

**Issue by 3ch3r46** [artf/grapesjs#34]
I found error the mod method is not defined on line:2 grapes.min.js.
Below the error message:
`Uncaught ReferenceError: mod is not defined`
what the solution to fix that error?

**Comment by artf** [comment]
Hi @3ch3r46 
can you post here you html file? 
From the error seems like you're trying to load it via node :/ bit strange

**Comment by 3ch3r46** [comment]
My html code look like your index.html
but, js file is rendered using node.

**Comment by artf** [comment]
ah ok, not sure about this technique, but anyway could you replace `mod()` with `b()` inside the grapes.min.js and let me know if it solves the problem. Thanks

**Comment by artf** [comment]
@3ch3r46 solved?

**Comment by 3ch3r46** [comment]
Yes, that is solved. thanks.
