### ISSUE TITLE
css variables undefined value bug

### ISSUE THREAD

**Issue by aryeharmon** [artf/grapesjs#340]
I am trying to extend the editor to support css vars
i added:
```
:root {
  --main-bg-color: brown;
}
```

to the page and i get in the browser:
```
:root {
  --main-bg-color: undefined;
}
```

can you explain how the editor parses the css into the canvas? maybe i am missing something

**Comment by artf** [comment]
This was already fixed (#271). Are sure you using the latest version?

**Comment by artf** [comment]
@aryeharmon ping

**Comment by aryeharmon** [comment]
@artf yes in the latest update it works. thanks
