### ISSUE TITLE
Ckeditor5 + GrapesJS now is possible!

### ISSUE THREAD

**Issue by GoodPHP** [artf/grapesjs#3400]
We are [DevFuture](https://devfuture.pro/grapesjs-development/), we developed plugin for integrate GrapesJS + ckeditor5.

Video example:
https://www.youtube.com/watch?v=xn4gSMIrx-A

We know a lot of people looking for this integration in a long time. We did it.

If you interesting at this plugin, messaging to our contact.

More details:
https://devfuture.pro/grapesjs-development/

Thanks!

**Comment by theSC0RP** [comment]
@GoodPHP Is this a paid plugin?

**Comment by GoodPHP** [comment]
Yeh, each 20% from selling plugin we will send on support GrapesJS.

If you will buy plugin, you will support GrapesJS.
