### ISSUE TITLE
Can style manager always generate IDs instead of using already defined element's class ?

### ISSUE THREAD

**Issue by ahmedderkaoui** [artf/grapesjs#3401]
When we style an element in the editor, if this element doesn't have neither a class or an id, the style manager generate a new id with the css style. However, styling an element with a class makes the style manager use this class to add styles.

**Is there a way to always use IDs for styling and not work with classes ?**

(this helps user make different custom styles on components that have same class attribute)

**Comment by Ju99ernaut** [comment]
```js
window.editor = grapesjs.init({
   // ...
   selectorManager: {
      componentFirst: 1,
   }
   // ...
});
```

**Comment by ahmedderkaoui** [comment]
Thanks a lot!
