### ISSUE TITLE
Multi page manager

### ISSUE THREAD

**Issue by John-Oula** [artf/grapesjs#3403]
How can I create multiple pages?

**Comment by GoodPHP** [comment]
Hey, now it need to build yourself. 

We have done solution: 
https://devfuture.pro/grapesjs-development/

**Comment by Ju99ernaut** [comment]
Working on a plugin for that https://github.com/Ju99ernaut/grapesjs-template-manager, still WIP but it's now in a pretty decent state.

**Comment by echobinod** [comment]
Multipage Manager using VueJS:
https://github.com/echobinod/GrapesJS-Vue.js.git

**Comment by Abhisheknanda1344463** [comment]
@echobinod  @Ju99ernaut  What can we do while exporting the code.?
because, at the time of export we need that website pages too.

**Comment by Ju99ernaut** [comment]
You'll probably need to convert `root` to a function that generates your file structure https://github.com/artf/grapesjs-plugin-export/blob/a0c55a77bfbc583c4d5eec459a3308c0b2192e07/src/index.js#L14

**Comment by artf** [comment]
Subscribe to this issue #3206 I'll post there all the details about the upcoming built-in page manager
