### ISSUE TITLE
FEAT: An event to hook into before a block in dropped into the canvas

### ISSUE THREAD

**Issue by chrisijoyah** [artf/grapesjs#3405]
## WARNING
READ and FOLLOW next 3 steps, then REMOVE them before posting the issue

1. Follow CONTRIBUTING Guidelines https://github.com/artf/grapesjs/blob/master/CONTRIBUTING.md
2. Do a quick SEARCH first, to see if someone else didn't open the same issue
3. All relative statements/questions have to be filled/answered, otherwise, the issue might be CLOSED
4. JSFiddle Starter template https://jsfiddle.net/szLp8h4n
5. CodeSandbox Starter template https://codesandbox.io/s/1r0w2pk1vl

**What are you trying to add to GrapesJS?**

*Describe your feature request **detailed***
There is currently an event to hook into `canvas:drop` which gives you access to the dropped model. Before a block is dropped inside the canvas I would like to carry out some checks before it is mounted and created. So for example something like `canvas:before:drop` would give you access to the `model` before it has been mounted and created and by returning `true` it continues to add and mount the model, but by returning `false` it prevents the block from being added the canvas. This feature would be nice as I can't seem to find any other suitable event to hook into for this.

**Is there an alternative at the latest version?**

 - [ ] Yes (describe the alternative)
 - [x] No

**Is this related to an issue?**

 - [ ] Yes (Give a link to the issue)
 - [x] No

**Comment by artf** [comment]
Hi @chrisijoyah did you try using `canvas:dragdata`? Here an example of usage https://jsfiddle.net/artur_arseniev/87rcb24n/

**Comment by chrisijoyah** [comment]
> Hi @chrisijoyah did you try using `canvas:dragdata`? Here an example of usage https://jsfiddle.net/artur_arseniev/87rcb24n/

Does this mean I can prevent the dropped model from being added to the Canvas. Ideally I want to carry out some checks to determine if the dragged block can be dropped into a section and If it doesn't pass the checks I want to prevent that before its added. Is there a way I can do this. Can I do something like `result.content= ''`

**Comment by artf** [comment]
> Can I do something like result.content= ''

Yeah, you should be able to do that with that trick. Can you tell me more about your use case, what kind of check are you trying to perform?

**Comment by chrisijoyah** [comment]
> > Can I do something like result.content= ''
> 
> Yeah, you should be able to do that with that trick. Can you tell me more about your use case, what kind of check are you trying to perform?

I have some custom blocks and some different sections. Before the user drops the block I want to hook into a function before the block is drop to carry out some checks to see if the block can be added to a certain section and either allow it or prevent it. I need to do it before it is added to canvas to prevent the `component:removed` event from being triggered as I have a listener on the event whenI'm doing some other checks, so I don't really want to trigger that event at this point. I hope that makes sense.

**Comment by artf** [comment]
yeah makes sense, I don't know if it might help you in the future (from the next release I'd say) but I've just merged #3393 which will allow having `droppable` component property as a function, so it'll be possible to have custom checks when it's not possible to accomplish with simple query selector strings.

**Comment by chrisijoyah** [comment]
> yeah makes sense, I don't know if it might help you in the future (from the next release I'd say) but I've just merged #3393 which will allow having `droppable` component property as a function, so it'll be possible to have custom checks when it's not possible to accomplish with simple query selector strings.

Nice this is exactly what I need. So does this mean I can pass a closure to this property and is the return type a boolean?

**Comment by artf** [comment]
> Nice this is exactly what I need. So does this mean I can pass a closure to this property and is the return type a boolean?

Exactly :)
