### ISSUE TITLE
[QUESTIONS] How to changes styles of devices, view code and fullscreen

### ISSUE THREAD

**Issue by marcepoblet** [artf/grapesjs#3408]
Currently we have this GrapesJs style: 
![image](https://user-images.githubusercontent.com/64096863/115547850-24fb6900-a27d-11eb-843f-2bb59fb5cbbc.png)

But, we are looking to have this GrapesJs style:
![image](https://user-images.githubusercontent.com/64096863/115547885-2f1d6780-a27d-11eb-84a5-f7f97e98eecc.png)

My questions are:

1- - how we can change the format in the devices? we would like to have buttons instead of dropdown.
2- is possible move the buttons 'view code' and 'fullscreen' inside the page?

**Comment by Ju99ernaut** [comment]
You'll just need to set the device or run the respective commands on the button's click event eg.
```js
btn.addEventListener('click', function() {
   editor.setDevice('Desktop');
});
```
