### ISSUE TITLE
span disappears on the reopening of a document ?! 

### ISSUE THREAD

**Issue by FlashPapa** [artf/grapesjs#341]
I use mjml preset and once the document is saved with this code:
```
<mj-button>
	YES ! <a data-cke-saved-href="http://toto.com">
		<span style="color:#f39c12;">
		I GOT IT</span>
	</a>
</mj-button>
```

When the document is reopened, the span tag disappears, and we have got 

```
      <mj-button>YES ! 
      	<a data-cke-saved-href="http://toto.com" href="http://toto.com">I GOT IT</a>
      </mj-button>
```
so we can not specify style on part of a text ?

Regards,

**Comment by artf** [comment]
Hi @FlashPapa I think this is where the issue coming from
https://github.com/artf/grapesjs/blob/dev/src/parser/model/ParserHtml.js#L136-L139
actually, all this part is a bit odd and need to be revisited, I'd appreciate any help

**Comment by MichaelKlemersson** [comment]
@artf probably we need to check if the _span_ element has at least one attribute before remove it.

**Comment by artf** [comment]
@MichaelKlemersson honestly I'm not even sure if it's necessary anymore, have to find time to test it. 
If I remember well, the main issue was to make the editor understand if the element should be a 'text component' (all content goes to `model.content`) or just a 'standard component' (with children inside `model.components`)

**Comment by Geczy** [comment]
Looks like it comes from this commit:

https://github.com/artf/grapesjs/commit/d6ae05ea6fd7b0ff365877f2b009fac3346ebd14#diff-f7273f6ad6e02b491c339656bd6fc2ed

Test involved:

https://github.com/artf/grapesjs/blob/d02234cb555994456eeaf75b39680e2a79222e72/test/specs/parser/model/ParserHtml.js#L282

Is there maybe a library we can use instead of a custom html parser?

**Comment by artf** [comment]
@Geczy the problem it's not with the HTML parser but just how the result is transformed (probably not correctly in this case). Obviously, failed tests should be updated

**Comment by Geczy** [comment]
There's been a bounty posted to get this issue resolved [![Bountysource](https://api.bountysource.com/badge/issue?issue_id=49788665)](https://www.bountysource.com/issues/49788665-span-disappears-on-the-reopening-of-a-document?utm_source=49788665&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by artf** [comment]
Should be fixed https://github.com/artf/grapesjs/releases/tag/v0.12.50
