### ISSUE TITLE
BUG: Editor's strange behavior！

### ISSUE THREAD

**Issue by sizhousama** [artf/grapesjs#3410]
When I enter the editor and use setComponents or addComponents to add components in the store, the first class of the first element will be added to the class of a certain element inexplicably. Does anyone know the reason? I need help! ! !
![image](https://user-images.githubusercontent.com/40018231/115696252-14d6ad00-a395-11eb-9bdd-c9a6ffd75627.png)
![image](https://user-images.githubusercontent.com/40018231/115696564-667f3780-a395-11eb-9869-23d3802cb64b.png)

**Comment by sizhousama** [comment]
@artf

**Comment by artf** [comment]
That class is coming from your app so there could be thousands of reasons, we can't help you just by looking at 2 screenshots. If you think there is a bug, open the issue correctly (by following the template) and create a reproducible demo.
