### ISSUE TITLE
QUESTION: Adding inline scripts and updating old events

### ISSUE THREAD

**Issue by theSC0RP** [artf/grapesjs#3413]
In that case, I suggest you access the document of the iframe and to append manually the inline script (to get the document use `editor.Canvas.getDocument()`)

_Originally posted by @artf in https://github.com/artf/grapesjs/issues/2012#issuecomment-496304498_

Hey, @artf, I was going through the issue, #2012 and I have a doubt.
If a change is made to the script e.g. change in alert msg on click. Then multiple events are added. How to remove the old events and add new ones (without saving and reloading).
One way is to refresh the iframe but that leads to the loss of all the events (even the predefined ones).
How would you suggest doing this?

**Comment by theSC0RP** [comment]
I tried to update the inline script using the following steps:
- Get the document of the iframe: `iframeDoc = editor.Canvas.getDocument()`
- Get the innerHTML of the body of the document: `iframeDocBodyHtml = iframeDoc.body.innerHTML`
- Replace the innerHTML of the body: `iframeDoc.body.innerHTML = iframeDocBodyHtml`
- Reattach the inline script

Doing this leads to a loss of the inbuilt grapesjs events like hover or component select (this is obvious as all the events are lost). Is there a way to reattach these grapesjs events? 
I also tried to do `editor.Canvas.toggleFramesEvents(1)` but it did not help.

**Comment by theSC0RP** [comment]
I was trying to attach the events and on the demo page I tried to run the following: 
`editor.runCommand('core:component-select')`. 
It gives me an error t.get is not a function. In the source tab when I checked, it is trying to call get('Editor') on the editor.

![Console Error](https://user-images.githubusercontent.com/30771519/116257273-88abf780-a791-11eb-914a-b6c3896b1e88.png)
![Error Source](https://user-images.githubusercontent.com/30771519/116257309-91043280-a791-11eb-9a0c-04b31f7b45ad.png)

**Comment by theSC0RP** [comment]
I tried to add the select and hover events by running `component-select` command by writing `editor.editor.trigger('core:component-select')` but that didn't help either.
Am I missing something?

**Comment by artf** [comment]
Well, I think it won't be bad to add an easy way to force the rerender of the iframe (not a common case but for sure might be useful in some cases). Unfortunately, right now, you should try to use private methods and check if everything works as expected, then if you confirm, I'll be happy to add a listener for something like `frame.trigger('rerender')`.
For now I'd ask you to try something like this
```js
// Take the actual view of the frame
const frameView = editor.Canvas.getFrame().view;
// Once we remove the frameView, we have to rerender the frame 
// wrapper view (which contains different elements like toolbars and the frame itself).
const frameWrapView = frameView.config.frameWrapView;
// Now, remove the frameView and rerender the wrapper
frameView.remove();
frameWrapView.remove();
```

**Comment by theSC0RP** [comment]
Hey, @artf.  Thanks for the reply. This does not seem to work. I got the following errors after the above code was run.
![Error](https://user-images.githubusercontent.com/30771519/117010389-6161a700-ad0a-11eb-9501-1ae7acbd2b16.png)

It works on the demo page though. If I'm not wrong, the demo uses the **dev** branch so my guess is that it's working there because the **dev** branch has a lot of new code in _src/canvas_.

**Comment by artf** [comment]
Yeah, you have to use the latest version.

**Comment by theSC0RP** [comment]
@artf, Is that version stable? I had doubts regarding the latest version because it has a warning icon along with the text "**POSSIBLY BREAKING CHANGE**".

![Latest Version](https://user-images.githubusercontent.com/30771519/117480576-6aa77980-af7f-11eb-83f9-fb1c82331033.png)

**Comment by artf** [comment]
Hi @theSC0RP you can find [here](https://github.com/artf/grapesjs/pull/3411) a paragraph about possible breaking changes.

**Comment by theSC0RP** [comment]
@artf. Thank you so much.
