### ISSUE TITLE
Component model is not reset when create new drag

### ISSUE THREAD

**Issue by sidh01** [artf/grapesjs#3414]
When dragging a component from right panel component model doesn't set to default value but has value of previously added component
![image](https://user-images.githubusercontent.com/37957105/116101026-1d97ed80-a6cb-11eb-85b5-e2f4d896cdc7.png)

![image](https://user-images.githubusercontent.com/37957105/116100999-17097600-a6cb-11eb-885d-3c09ef3b13c6.png)

**Comment by artf** [comment]
Hi @sidh01 it's definitely something on your side, we can try to help you if you're able to create a reproducible demo.

**Comment by sidh01** [comment]
I have solved this the problem was when we set model property then I need to use deep clone for array or object
