### ISSUE TITLE
QUESTION: Custom Asset Manager. How to set bg image

### ISSUE THREAD

**Issue by mmotov** [artf/grapesjs#3415]
Hi there!
I'm building a custom modal for the Asset Manager and basically, it seems that I need to override ```'open-assets'```command. 
How I can understand if a user wants to set an image src or background-image property?
Thanks in advance!

**Comment by AndyNormore** [comment]
Seconded, just started with GrapeJS and got it operational on my system, looking to set the background image on a header div without having to write css code :/

**Comment by artf** [comment]
Actually, the knowledge of what to do on asset selection should not be part of the command itself as the action should be decided by who runs the command, eg.
```js
editor.runCommand('open-assets', {
    onSelect(asset) {
      const cmp = editor.getSelected();
      cmp && cmp.addStyle({ 'background-image': `url("${asset.get('src')}")` })
    }
});
```
I'd suggest inspecting the current implementation of the [command](https://github.com/artf/grapesjs/blob/dev/src/commands/view/OpenAssets.js), but I have to say that is quite old, so If you'll find anything that might be improved, I'll be happy to hear that.

**Comment by AndyNormore** [comment]
This is not the right solution to our question. 

What I'm looking to do is add this to a component, how would we do this?

![image](https://user-images.githubusercontent.com/1661561/117693092-a57dfd00-b18b-11eb-8537-e4188d99eb40.png)

**Comment by ronaldohoch** [comment]
> Actually, the knowledge of what to do on asset selection should not be part of the command itself as the action should be decided by who runs the command, eg.
> 
> ```js
> editor.runCommand('open-assets', {
>     onSelect(asset) {
>       const cmp = editor.getSelected();
>       cmp && cmp.addStyle({ 'background-image': `url("${asset.get('src')}")` })
>     }
> });
> ```
> 
> I'd suggest inspecting the current implementation of the [command](https://github.com/artf/grapesjs/blob/dev/src/commands/view/OpenAssets.js), but I have to say that is quite old, so If you'll find anything that might be improved, I'll be happy to hear that.


Hello, sorry for comment in here, but it's not working.
But i have made a little change to have it working here..

It's my function, i needed to change all the assets implementation.
Just set the code as: `editor.getSelected().addStyle({ 'background-url': textUrl });`
```javascript
            //Substituir o assets manager
            Commands.add('open-assets', editor => { 
                controlContainer.OpenWindow('/'+controlDina.ProdName+'/send/imagedb', "", function(isForm, jw) {
                    $("#CKEDITOR_btimagedb").click(function() {
                        let listOfImageTags = ["img","mj-image"];
                        let textUrl = $(this).attr('txtUrl');
                        let txtAlt = $(this).attr('txtAlt');
                        if(listOfImageTags.includes(editor.getSelected().attributes.tagName)){
                            editor.getSelected().set({ src: txtUrl, alt: txtAlt });
                        }else{
                            editor.getSelected().addStyle({ 'background-url': textUrl });
                        }
                        jQuery(jw).dialog("close");
                    });
                });
            });
```
