### ISSUE TITLE
BUG: 0.15.10 - setAttribute - is not a valid attribute name

### ISSUE THREAD

**Issue by airtonjr** [artf/grapesjs#3416]
Hello!

I know this is a bug reported here #2029 but now I can not update from `0.15.10` to the version that has the solution.

Would you know any workaround for this issue at the moment that I am setting the component?

I am using VueJS with GrapesJS. 

Here is how I am trying to set the component. 

`this.grapeEditor.setComponents(myHtml);`

But the `setAttribute` would throw `is not a valid attribute name` and it won't show the content.

Thank you in advance.

**Comment by artf** [comment]
No sorry, can't help with such an old version. Why you can't update??
