### ISSUE TITLE
FEAT: How Map component works? How we can create weather components and render it?

### ISSUE THREAD

**Issue by NagarRahul** [artf/grapesjs#3417]
Could you please expain how map components are rendered after draged?
How we can create a new component for weather and how it will render like a map component?
@artf

**Comment by theSC0RP** [comment]
You can take a look at the following (if you haven't) to understand how the map component works:

- [Map Component Model](https://github.com/artf/grapesjs/blob/dev/src/dom_components/model/ComponentMap.js)
- [Map Component View](https://github.com/artf/grapesjs/blob/dev/src/dom_components/view/ComponentMapView.js)
