### ISSUE TITLE
FEAT: Event to hook into after editor.render has been executed

### ISSUE THREAD

**Issue by emyasnikov** [artf/grapesjs#3419]
**What are you trying to add to GrapesJS?**

As described in [BUG: Panels "visible" attribute doesn't prevent panel rendering](https://github.com/artf/grapesjs/issues/3418) I tried to prevent panel rendering on initial start. Since visible attribute didn't work for me I tried some workarounds until I noticed all my changes are gone after render has been called. So best way would be to hook into event, but I found nothing.
I think it would be a good addition to trigger event after rendering, if so I would like to help.

**Is there an alternative at the latest version?**

 - [x] Yes (describe the alternative)
 - [ ] No

I achieved this by calling `editor.trigger('render')` just after `editor.render()` myself, then I was able to correctly render panel using `editor.on('render', () => editor.Panels.getPanel('test').set('visible', false))` inside plugin.

**Is this related to an issue?**

 - [x] Yes (Give a link to the issue)
 - [ ] No

[BUG: Panels "visible" attribute doesn't prevent panel rendering](https://github.com/artf/grapesjs/issues/3418)

**Comment by artf** [comment]
Yeah, I think it's just a matter of adding `this.toggleVisible()` in `PanelView.render`.
If you want to push a PR, I'd be glad to merge it :)

**Comment by artf** [comment]
Thanks @emyasnikov I'll close this and will keep the bug issue open
