### ISSUE TITLE
[QUESTION] How to remove class selector css rule

### ISSUE THREAD

**Issue by ltenti-eventboost** [artf/grapesjs#3421]
I'm using componentFirst set to true to let my users apply needed style to component they selected.

Selecting a component which is applied a css class specific to the component type, and clicking "Sync" button causes the selector change from the component ID to the relevant css class.

Now I can't find a way to go back and throw away the css rule that has the component class as the selector, hence every new instance of that component has the same style.

Thanks for your help!

**Comment by artf** [comment]
Hi @ltenti-eventboost I'm not sure If I understand exactly where is your issue.
When you're editing with `componentFirst` enabled, the editor applies style changes on a component-specific CSS rule (eg. `#cmp-id { color: red }`). 
When you hit the "Sync" button, all the styles are moved to the current class selector and those inside the component-specific rule are removed `.selected-class { color: red } #cmp-id {}`.
So, from what you've described seems legit to me but maybe I'm missing something.

**Comment by ltenti-eventboost** [comment]
Hi @artf, thank for your help! The question is: how can I remove `.selected-class { color: red }` ?

**Comment by Ju99ernaut** [comment]
Using undo should work https://grapesjs.com/docs/api/undo_manager.html

**Comment by ltenti-eventboost** [comment]
Thank you @Ju99ernaut, but what am I supposed to do if I want to revert my css after a while, let say the day after the one I clicked on Sync?

**Comment by Ju99ernaut** [comment]
Looks like at that point you'll have to move the class styles to the component id manually using the cssComposer https://grapesjs.com/docs/api/css_composer.html#csscomposer

**Comment by ltenti-eventboost** [comment]
Is there a way to completely remove a rule using the cssComposer? I'm not able to find one by looking at the API documentation.

**Comment by Ju99ernaut** [comment]
Yes, basically you can get all rules as a backbone collection then remove the rule from the collection, something like:

```js
const cssc = editor.CssComposer;
cssc.getAll().remove(cssc.getRule('.class'));
```

**Comment by ltenti-eventboost** [comment]
It makes sense, now I just have to find a way to add this feature to my builder. Thank you @Ju99ernaut!
