### ISSUE TITLE
How we can remove default text content from text component 'Insert your text here' ?

### ISSUE THREAD

**Issue by Asifislam110** [artf/grapesjs#3422]
I want to remove default text from text component just like placeholder. every time when we drag text component we need to remove default text manually.

**Comment by theSC0RP** [comment]
Hey @Asifislam110, I don't know if this is the best solution but this was one that I could come up with.
```
const allBlocks = editor.BlockManager.getAll().models; // get the array of all the blocks
const textBlock = allBlocks.filter((block) => block.id === "text")[0]; // get the text block
textBlock.attributes.content.content = "";
```

**Comment by Asifislam110** [comment]
@theSC0RP it will remove the text from all the text component when editor get loaded.

but I need to remove the default content when user click on text component for typing.

**Comment by theSC0RP** [comment]
Ohh my bad! I thought you didn't want the text component to have any content when dropped in the canvas.
For your doubt, I guess you can do something like when a component is selected check if it's a text component and in the view, you will find the `el` in which you can change the innerHTML to '' if it is 'Insert your text here'

```
editor.on('component:selected', (comp) => {
    if(comp.attributes.type === "text") {
        if(comp.view.el.innerText === 'Insert your text here') {
            comp.view.el.innerText = "";
        }
    }
})
```

**Comment by Asifislam110** [comment]
@theSC0RP thank you for you reply.
above mention code is worked when user select component. but when user double click on component for typing, component not working properly. because when user select component, then div is set to contenteditable=false.
can you please provide any other workaround.

**Comment by theSC0RP** [comment]
You're welcome @Asifislam110. I'm sorry I can't think of anything else at the moment. If I find something, I'll post it here.

**Comment by artf** [comment]
You might try something like this
```js
// change:editing triggers when RTE is enabled
editor.on('change:editing', (em, editing) => {
    if (editing) {
      const cmp = editor.getSelected();
      const el = cmp && cmp.getEl();
      if (el && el.innerText === 'Insert your text here')
        el.innerText = '';
    }
});
```
