### ISSUE TITLE
BUG: RTE generate tag span after remove `bold`, `italic` etc

### ISSUE THREAD

**Issue by zgeist** [artf/grapesjs#3423]
Place text block

Edit text, apply `bold` or `italic`

Deselect text block

Select again and remove `bold`
Open source code, you should see `span` tags
![1113](https://user-images.githubusercontent.com/6919961/116565445-8e7b1780-a90e-11eb-8534-c28ce49886a1.png)

**Comment by Ju99ernaut** [comment]
Looks like an issue with the underlying browser API ie. `Document.execCommand()` so I'm not sure this can be solved, says here it has been deprecated but there's really no alternative, anyways the `removeFormat` command seems to work without leaving any spans. However you can still use a 3rd party RTE like CKE
