### ISSUE TITLE
BUG: staticRules for CssComposer Non-Functional

### ISSUE THREAD

**Issue by anlumo** [artf/grapesjs#3425]
The [sample config file](https://github.com/artf/grapesjs/blob/c3a49015df45eb49b0beb605e45ead1ea56a3af8/src/css_composer/config/config.js#L6) for the CssComposer references a `staticRules` property. This property name is not used anywhere else in the source code (verified using [GitHub search](https://github.com/artf/grapesjs/search?q=staticRules)) and also doesn't do anything.

**Version:** 0.17.3

**Are you able to reproduce the bug from the demo?**

 - [ ] Yes
 - [X] No

(not really applicable)

**What is the expected behavior?**

Add the css rules to the document.

**What is the current behavior?**

Nothing happens.

**Are you able to attach screenshots, screencasts or a live demo?**

 - [ ] Yes (attach)
 - [X] No

**Comment by artf** [comment]
Thanks @anlumo you're right, that was an old option, I'll remove it. For the purpose of static CSS rules, we have [these options](https://github.com/artf/grapesjs/blob/210f87030d7d1e2aa2e5c427e4347b49ad258134/src/editor/config/config.js#L72-L77)
