### ISSUE TITLE
FEAT: Add lazy loading support for images

### ISSUE THREAD

**Issue by akmittal** [artf/grapesjs#3427]
**What are you trying to add to GrapesJS?**
Lazily loading support for images.

*Describe your feature request **detailed***
Latest Browsers support lazy loading of images using the loading attribute. `<img src="myimg.png" loading="lazy">`. There are two possible values `eager` and `lazy`. If a loading attribute is not provided images loading is eager.
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img

**Is there an alternative at the latest version?**

 - [ ] Yes (describe the alternative)
 - [x] No

**Is this related to an issue?**

 - [ ] Yes (Give a link to the issue)
 - [x] No

**Comment by artf** [comment]
Thanks @akmittal loading is actually really cool and useful but, for now, I'd like to avoid extending core components (this might lead to unexpected behavior if someone creates a new component by extending the image).
For anyone who wants to make use of `loading` attribute can easily extend the image component in this way
```js
editor.DomComponents.addType('image', {
  model: {
    defaults: () => ({
      traits: [
        'alt',
        {
          type: 'select',
          name: 'loading',
          label: 'Loading',
          default: 'eager',
          options: [
            { id: 'lazy', name: 'Lazy' },
            { id: 'eager', name: 'Eager' }
          ]
        }
      ],
    }),
  },
});
```
