### ISSUE TITLE
BUG: there is no display grapesjs-style-bg plugin

### ISSUE THREAD

**Issue by justin3737** [artf/grapesjs#3429]
hi @artf 
thank you for doing everythings here
but I try to use this plugin but I can't

![img](https://i.imgur.com/gaC65t1.png)

Version: 0.17.3

Are you able to reproduce the bug from the demo?
- [x] Yes
- [ ] No

*Describe the bug **detailed***
there in no display plugin

What is the current behavior?
Nothing happens.

Are you able to attach screenshots, screencasts or a live demo?
- [x] Yes
- [ ] No
https://jsfiddle.net/e4pbsgm0/

**Comment by Ju99ernaut** [comment]
Unfortunately the plugin will not automatically replace the original background image input so you'll have to do it manually. You'll need to add this to your style manager config somehow and remove the built in version:

```js
{
   id: 'background-bg',
   property: 'background',
   type: 'bg',
},
```

For more reference check here https://github.com/artf/grapesjs/blob/c136ea722383c0ece710ff3bbab1ce9b30f986ba/demo.html#L1154
