### ISSUE TITLE
Where the id class is automatically add in the code ?

### ISSUE THREAD

**Issue by blackbirdzzz** [artf/grapesjs#343]
Hi artf, where in the code do you transform this exemple
**This** 
```
<a href="test" style="font-weight :bold;">
```
**To this** 
```
 <a href="test" id="#c41"> 
```
Just want to find how you delete the style="" and transform it to an id="#c54" by the model id :p
i want to change the code to disable this Thanks

**Comment by artf** [comment]
Here https://github.com/artf/grapesjs/blob/dev/src/dom_components/model/Component.js
I'm removing the `style` key from `getAttrToHTML()` and adding the `id="..."` in `toHTML()`

**Comment by blackbirdzzz** [comment]
Thanks for your answer i tried to delete getAttrtoHtml() and also this part 
```
    if(!_.isEmpty(m.get('style')) && !idFound)
      attrId = ' id="' + m.getId() + '" ';
```
so i know how to disable the id now but i want that the style don't be delete its not from the getAttrToHtml() func cause when i delete it nothing happen and also when i console.log(attr.style) its seems to be undefined

**Comment by blackbirdzzz** [comment]
up :x

**Comment by artf** [comment]
`model.getStyle()`
