### ISSUE TITLE
BUG: 

### ISSUE THREAD

**Issue by SintoDema** [artf/grapesjs#3432]
Hi @artf,

Can we able to use [Wistia](https://wistia.com/) in GrapesJS editor. I would like to use it as Vimeo used in the editor.

![image](https://user-images.githubusercontent.com/68583645/117104731-4b032c00-ad9a-11eb-9ddd-d7bb8acb41da.png)

**Scenario:**
I have a video in my Wistia domain, let the path be https://mydomain.wistia.com/medias/VIDEO_ID. I have to add that URL or video as we are adding a Youtube video link with Video ID in editor > video settings.

**Expecting screen:**
![Screenshot from 2021-05-05 12 32 25](https://user-images.githubusercontent.com/68583645/117106775-11ccbb00-ad9e-11eb-94a4-4ade6e871858.png)

**Request:**
Is there any way to integrate Wistia in this editor?
Is there any guideline to integrate it or supporting docs?

**Used Version:**
grapesjs - 0.16.18
ckeditor - standard - 4.14.1

It will help if I get support on Wistia in the grapesJS editor.
Thanking you.

**Comment by artf** [comment]
Sure, just check the current implementation of the [ComponentVideo](https://github.com/artf/grapesjs/blob/dev/src/dom_components/model/ComponentVideo.js) and extend it for your needs.

**Comment by SintoDema** [comment]
Thank you for the reply.

It helped me. But I still have an issue. In editor **I'm getting <video> tag** on changing provider in video setting, **it does not work for me in the case of Wistia**. can you let me know **where can I specify that <iframe> needes to be loaded** for provider in Wistia in the Component Video extended file?
