### ISSUE TITLE
BUG: UNDO/REDO ISSUE

### ISSUE THREAD

**Issue by RaresVlaiduc** [artf/grapesjs#3437]
@artf , it's pretty important if u ask me :)

**Version: v0.17.3**

**Are you able to reproduce the bug from the demo?**

 - [x] Yes
 - [ ] No

**What is the expected behavior?**

If I change the device and then I press undo and redo I will get to the last device type. (e.g: Mobile -> Tablet, Undo, Redo)

*Describe the bug *

How to reproduce:
1. Enter the editor
2. Press mobile mode
3. Press undo
4. Press redo
5. Check console

After that, the undo/redo is broken.

**Are you able to attach screenshots, screencasts or a live demo?**

 - [x] Yes (attach)
 - [ ] No

![image](https://user-images.githubusercontent.com/73160095/117284331-62601900-ae6f-11eb-9ca7-1c31b850af5c.png)

**Comment by artf** [comment]
Thanks @RaresVlaiduc I'll prevent tracking device changes in undo manager
