### ISSUE TITLE
Add component to specific point on the cavnas 

### ISSUE THREAD

**Issue by telliott22** [artf/grapesjs#344]
I'm adding a new component to the canvas using `editor.addComponents({ ... });` but it's always added as the last element, to the bottom of the canvas. Is there a way to insert it at a specific point on the canvas?

All my components are rows, so ideally I'd like to insert components by index. 

Thanks,
T

**Comment by telliott22** [comment]
Thanks for the reply, but not sure that helps me.

When I create a new component, it's added to the bottom of the canvas. Like below:

``````
<div class="row"></div>
<div class="row"></div>
<div class="row"></div>
<div class="row"></div>
<div class="row"></div>
 -- Component is inserted here --
``````

I want to be able to insert it between two existing rows, like below:

 ``````
<div class="row"></div>
<div class="row"></div>
<div class="row"></div>
 -- I want to insert component here --
<div class="row"></div>
<div class="row"></div>
``````

Thanks,
T

**Comment by artf** [comment]
This should work
```js
var index = 1;
editor.getComponents().add('<div>Text</div>', {at: index});
```

**Comment by fmr411** [comment]
Hi @artf , how to find out the index based on the selected element, Thanks
