### ISSUE TITLE
BUG: Parser breaks `mj-style` as of 16.30

### ISSUE THREAD

**Issue by emilsedgh** [artf/grapesjs#3441]
**Version:**

All Grapesjs version from 16.30 to now have this issues.

**Are you able to reproduce the bug from the demo?**

 - [x] Yes
 - [ ] No

**What is the expected behavior?**

The following is valid MJML code. It should work fine on grapesjs-mjml.

```
<mjml>
  <mj-head>
    <mj-style>
      @font-face {
        font-family: "foo";src: url('./fonts/foo.otf') format('truetype');
      }
    </mj-style>
  </mj-head>
<mj-body>
```

*Describe the bug **detailed***

Right now, if you use grapesjs-mjml with the code above it will break in 2 ways:

1. It will render the style like this:

```
@font-face {font-family: &quot;foo&quot;;src: url(&#039;./fonts/foo&#039;) format(&#039;truetype&#039;);}
```

2. When you export the code, it exports the MJML code as the following:

```
<mjml>
  <mj-head>
    <mj-style>
      @font-face {
      font-family: &quot;foo&quot;;src: url(&#039;./fonts/foo.otf&#039;) format(&#039;truetype&#039;);
      }
    </mj-style>
  </mj-head>
  <mj-body>
  </mj-body>
</mjml>
```
In both cases, you can see that the style has been html-encoded.

**What is the current behavior?**

`mj-style` is not a textNode and it's content must not be htmlEncoded.

*Describe the bug **detailed***

The reason I'm filing this against this repository and not grapesjs-mjml is this: This regression is a result of commit 8e7f94abb0c4500cebde5a4984eca4215772cb0b.

As of this commit, grapesjs wrongly assumes all textNode's are, well, textNode's. That's not always the case (like mj-style).

**Are you able to attach screenshots, screencasts or a live demo?**

![3](https://user-images.githubusercontent.com/120439/117426929-5315b580-aed9-11eb-93a3-ca61de00ceb2.gif)

**Comment by artf** [comment]
Hi @emilsedgh I apologize for being so late on this issue, but anyway, we can think about how to skip escape in cases like that but probably the fastest way is to simply extend mj-style toHTML method
```js
editor.Components.addType('mj-style', {
  model: {
    toHTML() {
      const content = this.components().map(c => c.get('content')).join('');
      return `<mj-style>${content}</mj-style>`;
    }
    // ...
  }
})
```

**Comment by emilsedgh** [comment]
Hi Artur. Thank you for the great job done on grapesjs. It really is fantastic.

The interim solution works just fine. Feel free to close out if necessary, but providing a way of manipulating the behavior would definitely be pretty nice.

**Comment by artf** [comment]
Thanks Emil, for now, I'll close this one, in case another similar issue will arise, we'll think about adding a new prop for skipping the escape.
