### ISSUE TITLE
BUG: Error after call `editor.destroy()`

### ISSUE THREAD

**Issue by zgeist** [artf/grapesjs#3442]
Create editor instance

Try destroy 
```
const editor = grapesjs.init({
	container: '#gjs',
        height: '100%',
        storageManager: false
});

editor.destroy();
```
Got error

![image](https://user-images.githubusercontent.com/6919961/117447790-9a865b00-af46-11eb-9d2a-6d502be38d47.png)

**Comment by PRTTMPRPHT** [comment]
+1

**Comment by artf** [comment]
Thanks for the report, I'll try to fix it in the next release

@ershadul1 nope, there is a FrameWrapView (stuff around the iframe, like wrappers, tools for selection etc.), and inside there is a FrameView (the iframe itself), but probably for some remove ordering issue, the frame is removed before its wrapper.
