### ISSUE TITLE
BUG: backbone-undo/underscore security advisory

### ISSUE THREAD

**Issue by chilled-capybara** [artf/grapesjs#3443]
**Version:**
`v0.17.3`

**Are you able to reproduce the bug from the demo?**
 - [x] Yes
 - [ ] No

**What is the expected behavior?**
See below

**What is the current behavior?**
There is a known security vulnerability in one of the versions of `underscore` used by a nested dependency.

The current version of `grapejs` utilises `backbone-undo` `^0.2.5`
https://github.com/artf/grapesjs/blob/d7f773202c72710dd787e2ce418c114c9ef81986/package.json#L20

The latest version of which is `0.2.5` via [`npm`](https://www.npmjs.com/package/backbone-undo?activeTab=versions)

Version `0.2.5` of `backbone-undo` has a fixed limit on the [underscore version](https://github.com/osartun/Backbone.Undo.js/blob/d04ee132f4fd00b0f8b3e8b8a5364257f9f3f4c7/package.json#L25);
> `"underscore": "1.4.4 - 1.8.3"`

Which looks to be vulnerable based on this advisory https://github.com/advisories/GHSA-cf4h-3jhx-xvhq

Version `0.2.6` of `backbone-undo` does [update this](https://github.com/osartun/Backbone.Undo.js/blob/48eeb45467c15cee9a1411a7ca9bb7a1d97d198f/package.json#L24), but as mentioned is not available via `npm`

**Are you able to attach screenshots, screencasts or a live demo?**
 - [ ] Yes
 - [x] No

**Comment by emyasnikov** [comment]
I'm also wondering if backbone-undo is needed or can be replaced by something similar. The package hasn't been updated for 6 years

**Comment by artf** [comment]
> The package hasn't been updated for 6 years

Well, except updating its dependencies (like in this case, for security reason) it's a feature-complete library, there is no need to add/update anything else.

Anyway, this [PR](https://github.com/artf/grapesjs/pull/3439) seems to fix the security vulnerability at the .lock level but I'm not sure if are kept on a fresh install. 
I know that yarn has `resolutions` for such cases but not sure about alternatives in npm.

**Comment by chilled-capybara** [comment]
Thanks for your reply

> Anyway, this [PR](https://github.com/artf/grapesjs/pull/3439) seems to fix the security vulnerability at the .lock level but I'm not sure if are kept on a fresh install.

I think that might fix the version in the main `grapejs` repo, but I'm not sure it restricts the one imported via `backbone-undo`.

If you set up a fresh project via
```
yarn init
yarn add grapesjs
```

the new `yarn.lock` will still reference both versions;
```
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


backbone-undo@^0.2.5:
  version "0.2.5"
  resolved "https://registry.yarnpkg.com/backbone-undo/-/backbone-undo-0.2.5.tgz#55b25230f90319ca622465e89a80248b893c2ce2"
  integrity sha1-VbJSMPkDGcpiJGXomoAki4k8LOI=
  dependencies:
    backbone "1.0.0 - 1.2.1"
    underscore "1.4.4 - 1.8.3"

...

grapesjs@^0.17.4:
  version "0.17.4"
  resolved "https://registry.yarnpkg.com/grapesjs/-/grapesjs-0.17.4.tgz#4baf69598b74a2e58c5133d9ab85631cf4de53e1"
  integrity sha512-oBFCg88KpUKly4LCf+FG42f0kbIKBbkilpyBr+2aggnLRpeSYFv3Db+fQIG+H1Y345QVqKbi/IKEUJe5X0wuiw==
  dependencies:
    backbone "1.3.3"
    backbone-undo "^0.2.5"
    cash-dom "^2.3.9"
    codemirror "^5.58.2"
    codemirror-formatting "^1.0.0"
    keymaster "^1.6.2"
    promise-polyfill "^8.1.3"
    spectrum-colorpicker "^1.8.0"
    underscore "^1.9.1"

...

"underscore@1.4.4 - 1.8.3":
  version "1.8.3"
  resolved "https://registry.yarnpkg.com/underscore/-/underscore-1.8.3.tgz#4f3fb53b106e6097fcf9cb4109f2a5e9bdfa5022"
  integrity sha1-Tz+1OxBuYJf8+ctBCfKl6b36UCI=

underscore@>=1.7.0, underscore@>=1.8.3, underscore@^1.9.1:
  version "1.13.1"
  resolved "https://registry.yarnpkg.com/underscore/-/underscore-1.13.1.tgz#0c1c6bd2df54b6b69f2314066d65b6cde6fcf9d1"
  integrity sha512-hzSoAVtJF+3ZtiFX0VgfFPHEDRm7Y/QPjGyNo4TVdnDTdft3tr8hEkD25a1jC+TjTuE7tkHGKkhwCgs9dgBB2g==

```

**Comment by artf** [comment]
In the next release, I'll switch to `yarn` in order to be able to use `resolutions` and fix all other issues I have with `npm` (upgrading dependencies always breaks something 😑).

Anyway, I'd like to point out that even if the package manager downloads the old underscore, that one is never used in GrapesJS build as we're using webpack aliases
https://github.com/artf/grapesjs/blob/614fad12b729c382b2444ca8b5e584f1dafc063a/webpack.config.js#L35

So, that means during the GrapesJS build we generate grapes.min.js containing only the main, upgraded, underscore. When you're adding GrapesJS in your app you always reference the `grapes.min.js`
https://github.com/artf/grapesjs/blob/614fad12b729c382b2444ca8b5e584f1dafc063a/package.json#L8

If you want to keep your app clean from the old underscore version, you can use [`yarn resolutions`](https://classic.yarnpkg.com/en/docs/selective-version-resolutions/)
