### ISSUE TITLE
removeButton() causing error

### ISSUE THREAD

**Issue by mahfuzdiu** [artf/grapesjs#3444]
Hi, 
I'm trying to remove a button from panel using this code `editor.Panels.removeButton('options', 'fullscreen')` . It removes the button but gives me this error.
![Capture](https://user-images.githubusercontent.com/43580524/117531201-3aa1ba00-b003-11eb-8f03-8e74ce3a511a.PNG)
How to solve it?

**Comment by mahfuzdiu** [comment]
I hid it with custom css `editor.Panels.getButton('options', 'fullscreen').attributes.className = 'hide_panel_btn'` btw a proper solution would be nice.

**Comment by artf** [comment]
Hi @mahfuzdiu by doing so on the official demo, it works with no errors, are you able to create a reproducible demo?

**Comment by adiux** [comment]
We still have this issue. But only with the newsletter preset.
