### ISSUE TITLE
BUG: javascripts are not working due to encoding issue

### ISSUE THREAD

**Issue by lbmir** [artf/grapesjs#3447]
1 - I copied **Typed text** components code instead of demo HTML code;
2 - And added allowScripts: 1;

You can see example here: http://bashworld.ru/demo.html
press to **View code** and we see many encoded characters in JS.

How can I fix this issue? I need to decode all &, <, >, ' characters,

please see screenshow below
![wwww](https://user-images.githubusercontent.com/40471188/117637617-6788d500-b19b-11eb-9564-7dc8b12dd797.png)

**Comment by lbmir** [comment]
@artf  Can you help please?

**Comment by Ju99ernaut** [comment]
It's not recommended to use `allowScripts: 1`, anyways in your case why not just drag in the typed block, but if you have to include it in your from element use:
```html
<div id="gjs">
   <div data-gjs-type="typed"></div>
</div>
```

**Comment by lbmir** [comment]
> It's not recommended to use `allowScripts: 1`, anyways in your case why not just drag in the typed block, but if you have to include it in your from element use:
> 
> ```
> <div id="gjs">
>    <div data-gjs-type="typed"></div>
> </div>
> ```

Thanks, I tried just drag it but after saving and reloading there are the same encoded characters in code, and if we edit and save it one more time that code will not work. So the same issue is happening when JS code is loaded from Database too

**Comment by Ju99ernaut** [comment]
You should setup your storage correctly https://grapesjs.com/docs/modules/Storage.html#basic-configuration

**Comment by artf** [comment]
> You should setup your storage correctly https://grapesjs.com/docs/modules/Storage.html#basic-configuration

@lbmir  Yeah you should load back the JSON and not the HTML... follow the link provided by @Ju99ernaut
