### ISSUE TITLE
applying custom class to component doesn't seem to be working

### ISSUE THREAD

**Issue by rcloss** [artf/grapesjs#3448]
I'm adding a class on a component when certain conditions aren't met, in this case when there's no href set. I viewed the source and see the "nolink" class in the source but it's not setting the background color to red and I'm not seeing it when inspecting the element, this is how I'm trying to add it, but when I do cc.getAll() I'm not seeing the nolink class so I'm not sure where things are breaking down

`var cc = editor.CssComposer;`
`var nolink = editor.SelectorManager.add('nolink');`
`var rule = editor.CssComposer.add([nolink]);`
`rule.set('style', {
  'background-color': 'red'
});`

I also tried `editor.CssComposer.setRule('.nolink', {'background-color':'red'});` but that didn't seem to work either

**Comment by artf** [comment]
> I also tried editor.CssComposer.setRule('.nolink', {'background-color':'red'}); but that didn't seem to work either

`setRule` is the right API to use and it works, but it creates only the rule, you have also to add the class to the component if you want to see it in canvas (eg. `editor.getSelected().addClass('nolink')`)
