### ISSUE TITLE
[QUESTION] How to open Materialize modal from my custom command src/commands/index.js ?

### ISSUE THREAD

**Issue by bungambohlah** [artf/grapesjs#345]
Hello @artf , nice to see you again, i have a question, how to initialize materializecss modal from source code commands grapesjs? , let's see the code.

initialize modal :
```javascript
$("#modal1").modal("open");
```

then in the src/commands/index.js :
```javascript
defaultCommands['tlb-show-modal'] = {
    run(ed) {
        var sel = ed.getSelected();

        ed.select(null);
        console.log(this);
        $("#modal1").modal("open");
    },
};
```
Then after run the command, it's not work modal is not a function, can i customize DOM element from your source? or is there any other way?
thank you and have a nice day

**Comment by artf** [comment]
`modal is not a function` seems like you just didn't add the js library of materializecss

> can i customize DOM element from your source? or is there any other way?

You can do it but then you have probably to update the source at any new update, so you should always extend the code with plugins

**Comment by manishkumaruit** [comment]
Hi ARTF,
i want to make a modal popup as like image blocks. when i am making domcomponents and define type to add in block manager component its not working.
Can you help me to make a modal when i drag a component in editor it should open like a modal 

`var comps = editor.DomComponents;

// Get the model and the view from the default Component type
var defaultType = comps.getType('default');
var defaultModel = defaultType.model;
var defaultView = defaultType.view;

var inputTypes = [
  {value: 'text', name: 'Text'},
  {value: 'email', name: 'Email'},
  {value: 'password', name: 'Password'},
  {value: 'number', name: 'Number'},
];

// The `input` will be the Component type ID
comps.addType('input', {
  // Define the Model
  model: defaultModel.extend({
    // Extend default properties
    defaults: Object.assign({}, defaultModel.prototype.defaults, {
      // Can be dropped only inside `form` elements
      draggable: 'form, form *',
      // Can't drop other elements inside it
      droppable: false,
      // Traits (Settings)
      traits: ['name', 'placeholder', {
          // Change the type of the input (text, password, email, etc.)
          type: 'select',
          label: 'Type',
          name: 'type',
          options: inputTypes,
        },{
          // Can make it required for the form
          type: 'checkbox',
          label: 'Required',
          name: 'required',
      }],
    }),
  },
  // The second argument of .extend are static methods and we'll put inside our
  // isComponent() method. As you're putting a new Component type on top of the stack,
  // not declaring isComponent() might probably break stuff, especially if you extend
  // the default one.
  {
    isComponent: function(el) {
      if(el.tagName == 'INPUT'){
        return {type: 'input'};
      }
    },
  }),

  // Define the View
  view: defaultType.view,
});
  b.add('test-block', {
      label: `<svg class="gjs-block-svg" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
      <path class="gjs-block-svg-path" d="M22,9 C22,8.4 21.5,8 20.75,8 L3.25,8 C2.5,8 2,8.4 2,9 L2,15 C2,15.6 2.5,16 3.25,16 L20.75,16 C21.5,16 22,15.6 22,15 L22,9 Z M21,15 L3,15 L3,9 L21,9 L21,15 Z" fill-rule="nonzero"></path>
      <rect class="gjs-block-svg-path" x="15" y="10" width="5" height="1"></rect>
      <rect class="gjs-block-svg-path" x="15" y="13" width="5" height="1"></rect>
      <rect class="gjs-block-svg-path" x="15" y="11.5" width="5" height="1"></rect>
     </svg>`,
      content: {
         type: 'input',
         activeOnRender: 1, // <- this will trigger the active event
      },
     });` 

here is my code
