### ISSUE TITLE
BUG: RTE insert link does not update DOM

### ISSUE THREAD

**Issue by TheDude70** [artf/grapesjs#3454]
**Version:**
"0.17.3"

**Are you able to reproduce the bug from the demo?**

 - [X] Yes
 - [ ] No

**What is the expected behavior?**
After inserting link using default RTE that it is immediately available to be further edited in settings, i.e. setting the HREF and Target

*Describe the bug **detailed***
After selecting text with the default RTE and turning it into a link, the text is correctly wrapped in <a> tags, however it is not available as a link component until after deselecting and then selecting some other text, sometimes having to repeat this twice before it is recognized as a GrapesJS component.

**Are you able to attach screenshots, screencasts or a live demo?**

 - [ ] Yes (attach)
 - [X] No

this is my editor init:
```
this.editor = grapesjs.init({
      container: '#gjs',
      width: 'auto',
      noticeOnUnload: 0,
      components: this.landing_page.components || this.landing_page.html,
      style: this.landing_page.style || this.landing_page.css,
      storageManager: {
        type: null
      },
      styleManager: {
        clearProperties: true,
      },
      fromElement: false,
      assetManager: {
        storageType: '',
        storeOnChange: true,
        storeAfterUpload: true,
        assets: [],
        uploadFile: this.uploadImage,
      },
}
```

Is there a way to force an update of the edited component after the link is inserted?

**Comment by artf** [comment]
Yeah, this is how it works right now (content is parsed and transformed in components only once the editing is finished). Probably we can use an approach like [this](https://github.com/artf/grapesjs/issues/610#issuecomment-768553776) as the default behaviour for links.

**Comment by artf** [comment]
Updated the link creation from this release https://github.com/artf/grapesjs/releases/tag/v0.18.3
