### ISSUE TITLE
BUG: Custom trait input not working

### ISSUE THREAD

**Issue by RaresVlaiduc** [artf/grapesjs#3457]
Hi @artf !

**Version: 0.17.3**

**Are you able to reproduce the bug from the demo?**

 - [ ] Yes
 - [x] No

**What is the expected behavior?**

The input is created correctly

*Describe the bug **detailed***

I am trying to create a custom input (checkbox) and it doesn't work.

**What is the current behavior?**

See attach.

**Are you able to attach screenshots, screencasts or a live demo?**

 - [x] Yes (attach)
 - [ ] No

Code: 
![image](https://user-images.githubusercontent.com/73160095/118131026-af5f6480-b406-11eb-8fca-cac1bfe5de40.png)

Result:
![image](https://user-images.githubusercontent.com/73160095/118131087-bf774400-b406-11eb-8a97-e0f58a5cd74c.png)

The area that should be some kind of "input" is not clickable.

If I am doing something wrong, let me know :)

**Comment by ahmedderkaoui** [comment]
If you want to have a simple checkbox with label, no need to create custom trait, you can just use directly:
```
editor.DomComponents.addType('text', {
            model: {
              defaults: {
                traits: [
                  {type: 'checkbox', label: 'Fix position when scrolling', name: 'position-sticky'}
                ]
              }
            },
});
```

**Comment by RaresVlaiduc** [comment]
@ahmedderkaoui The idea is that I need to create some custom traits, and I just started testing this functionality :)

**Comment by ahmedderkaoui** [comment]
Then, in `createInput()` you should return an `Element`.
So instead of returning a simple `string`, do this:
```
const el = document.createElement('div');
el.innerHTML = `<input type='checkbox'/>`
return el;
```

**Comment by RaresVlaiduc** [comment]
@ahmedderkaoui yup, it worked.

@artf if possible, could you please confirm that the documentation for this part is outdated?
![image](https://user-images.githubusercontent.com/73160095/118496423-cb2b7900-b72c-11eb-9b1d-a2bc716e33ca.png)

**Comment by artf** [comment]
@RaresVlaiduc mmm I'd expect it to work also with an HTML string... I have to check it

**Comment by RaresVlaiduc** [comment]
@artf any updates? :)

**Comment by artf** [comment]
@RaresVlaiduc actually it seems to work even with the string, the issue is the style applied on the checkbox which might be improved
