### ISSUE TITLE
BUG: DomComponents' Config Incorrect

### ISSUE THREAD

**Issue by anlumo** [artf/grapesjs#3459]
**Version:** 0.17.3

**What is the expected behavior?**

The documentation says that I can configure the wrapper element via the configuration:

https://github.com/artf/grapesjs/blob/0027dcd1194715eeaf4b24db878dd7ebac069cc4/src/dom_components/config/config.js#L6-L24

*Describe the bug **detailed***

I don't think that this configuration is used anywhere. A text search through the project for “wrapperName” returns only place I linked above itself. Searching for “wrapper” is not feasible unfortunately due to the high number of false positives.

I am able to configure the wrapper element after initialization using the object returned by `editor.getWrapper()`.

**Comment by artf** [comment]
Yeah, actually the name, by default, is managed via [i18n](https://github.com/artf/grapesjs/blob/d00ccb945c610bf748b2ed36e4b2fddc1c40b5ba/src/i18n/locale/en.js#L23) configuration.
From 0.17.* version even the `wrapper` option is not necessary anymore as now you should extend the `wrapper` component as all others (in previous versions the `wrapper` was initialized before plugins).
I'll remove them in the next release 👍
