### ISSUE TITLE
Refresh/Re-render traits of all components in canvas

### ISSUE THREAD

**Issue by ahmedderkaoui** [artf/grapesjs#3462]
Is there a way to re-render or refresh traits (which are customs, not built-in traits) of all the components existing whithin the canvas?

**Comment by iabhiyaan** [comment]
```js
editor.on('component:selected', component => {
 component.set({
  traits: ['name', 'placeholder']
 })

})
````

**Comment by artf** [comment]
mmm what is the point? Your custom traits should already react to component changes (if you created them properly).
