### ISSUE TITLE
BUG: update breaks some things with css

### ISSUE THREAD

**Issue by anatoli-dp** [artf/grapesjs#3465]
## WARNING
READ and FOLLOW next 3 steps, then REMOVE them before posting the issue

1. Follow CONTRIBUTING Guidelines https://github.com/artf/grapesjs/blob/master/CONTRIBUTING.md
2. Do a quick SEARCH first, to see if someone else didn't open the same issue
3. All relative statements/questions have to be filled/answered, otherwise, the issue might be CLOSED
4. JSFiddle Starter template https://jsfiddle.net/szLp8h4n
5. CodeSandbox Starter template https://codesandbox.io/s/1r0w2pk1vl

**Version:**
Most recent cloned right off github

*You can get the version by typing `grapesjs.version` into the console*

**Are you able to reproduce the bug from the demo?**

 - [ ] Yes
 - [x ] No, this is a custom version

**What is the expected behavior?**
When calling for the selected component and updating it via editor.getSelected().components().reset('html string here') if there is <style></style> tag in the html string it used to be parsed and placed in the page in the gjs-css section in the iframe document.

*Describe the bug **detailed***

**What is the current behavior?**
That is no longer the case. The <style> tags get parsed but never added to the page like the previous version (before the page API update)

*Describe the bug **detailed***

**Are you able to attach screenshots, screencasts or a live demo?**

 - [x ] Yes (attach)
 - [ ] No

Am on mobile atm but will update with screenshots and possibly more info when I get my laptop

**Comment by artf** [comment]
Well, actually the proper API would be `.components('html string here')` which seems to work as expected, but I'll investigate the reset thing because I'd expect to work the same way

**Comment by artf** [comment]
Ok seems like the backbone's reset method injects the `silent` option which prevents the CSS collection to render the added style, so for now, I'd prefer to avoid putting hacky conditions to remove that option and would recommend sticking with the proper API
