### ISSUE TITLE
BUG: Toolbar/actionbar buttons do not work when there are multiple instances present (Even in your demo)

### ISSUE THREAD

**Issue by DodoTrip** [artf/grapesjs#3475]
**Version:** 0.16.44

*You can get the version by typing `grapesjs.version` into the console*

**Are you able to reproduce the bug from the demo?**

 - [x] Yes
 - [ ] No

**What is the expected behavior?**
Every instance has their own toolbar working properly

*Describe the bug **detailed***
So previously i made another issue relating to instances #3354 , in this issue i conclude that it was my fault handling the instances improperly . Here i even stumble upon the bug even in the demo page https://grapesjs.com/docs/getting-started.html#theming. You can see that in every single instance no toolbar works, none of the options provided ( bold,strikethrough, link etc ), except the very last initiated instance. This also is what happening on my case ( toolbar only works on the last initiated instance ).

**Are you able to attach screenshots, screencasts or a live demo?**
You can test this on the getting started demo page https://grapesjs.com/docs/getting-started.html#theming

 - [ ] Yes (attach)
 - [x] No

**Comment by artf** [comment]
Thanks for the report @DodoTrip 
The fix is ready for the next release.
