### ISSUE TITLE
BUG: TypeError: Cannot read property 'querySelector' of null

### ISSUE THREAD

**Issue by krishnaeverestengineering** [artf/grapesjs#3476]
<img width="1172" alt="Screenshot 2021-05-24 at 6 55 23 PM" src="https://user-images.githubusercontent.com/55732888/119354444-b8cbb500-bcc1-11eb-8e67-27e020c879aa.png">

I was getting this error while writing unit tests and I am testing editor instance to be defined. Randomly test case is passing but mostly I am getting this error.

**Comment by YyueeiWY** [comment]
It seems like u are missing the class name or parent element ID.

below is the example of using querySelector.
It's not **Grapesjs** bugs.
you can find more examples from **Stackoverflow**
https://stackoverflow.com/questions/41849264/uncaught-typeerror-cannot-read-property-queryselector-of-null

<pre>
var parentElement = document.getElementById('deviceready');
var listeningElement = parentElement.querySelector('.listening');
console.log(listeningElement);

&lt;div id="deviceready"&gt;
   &lt;div class="listening"&gt;
   &lt;/div&gt;
&lt;/div&gt;

</pre>

**Comment by artf** [comment]
Sorry but this might depend on way too many factors (eg. your environment) and has nothing to do with the core itself.
