### ISSUE TITLE
BUG: setMessages() does not update i18n

### ISSUE THREAD

**Issue by ahmedderkaoui** [artf/grapesjs#3477]
By default, the editor is initiated with english language when the `init` does not contain:
```
i18n: {
        messages: { en: fr }
},
```
However, when I try to change the language using the i18n method: `setMessages` like below:
`editor.I18n.setMessages({ en: tr });`
this happens:
- Opened tabs (like Style Manager which by default gets open at load) do not get updated by the i18n.
- Panels hover titles do not get updated.
- Tabs which are not loaded (let's say Trait Manager) does get updated by the i18n (since it is not loaded before)

**Comment by artf** [comment]
Follow the issue template
