### ISSUE TITLE
BUG: Large images make area of content editor unreachable

### ISSUE THREAD

**Issue by samichamoun** [artf/grapesjs#3490]
Hi,

If you for example add a 3 column block to a page, and try dragging a very wide image into each column, the content stretches and the overflow is hidden.

How do we either add a vertical scrollbar or force the editor to limit the viewable size of images when dragged in. Currently if the content goes outside that area you cant access it (in the editor).

**Comment by artf** [comment]
This is more a layout issue that you can easily fix by adding your CSS to all images, eg. `img { max-width: 100%; }`
