### ISSUE TITLE
BUG: Button trait command doesn't work

### ISSUE THREAD

**Issue by tudor-ooo** [artf/grapesjs#3497]
**Version:** Latest

### *Describe the bug **detailed***
https://jsfiddle.net/cleaver/wgz2jsvq/2/
Nothing happens on:
```js
        traits: [
          {
            text: 'Simple button',
            type: 'button',
            full: true,
            command: () => {
              console.log('Broken button');
              alert('Broken button');
            },
          },
        ]
```

---

On version **0.16.45** the same code worked fine:
https://jsfiddle.net/cleaver/kenvpt50/1/

**Comment by artf** [comment]
Thanks for the report @tudor-ooo will be fixed in the next release
