### ISSUE TITLE
Add new Components to editor   

### ISSUE THREAD

**Issue by piyalmaduranga** [artf/grapesjs#35]
i need to Add new components to editor like Image drag and drop , mynew components contain script like this 
<script src = 'https://www.exsample.net/advert/api/zone/5/invocationcode'></script>
(this script show image) 

![screenshot from 2017-01-26 11 34 59](https://cloud.githubusercontent.com/assets/12907174/22326236/d9cdee7a-e3d7-11e6-9410-dc5b29cb58dc.png)
how to add button to open box toolbar ?
how to add setting that component ?

i tried to this way 

var domComponents = editor.DomComponents;
.......
domComponents: {
    components: '<script src = "https://www.exsample.net/advert/api/zone/5/invocationcode"></script>',
}
.....

how can i add modal pop up after drop component to our template ?
(like image drop component)

**Comment by artf** [comment]
Hi @piyalmaduranga 
those in the image are what I call Blocks, and a Block contains Components.

```js
var blockManager = editor.BlockManager;

// Add new block
blockManager.add('my-block-id', {
  label: 'Simple block',
  content: '<div class="my-block">This string will be parsed and turned into a Component</div>',
});

// Edit
blockManager.get('my-block-id').set({
  label: 'Updated simple block',
  attributes: {title: 'My title'}
});

// Add a block as a Component
blockManager.add('my-map-block', {
  label: 'Simple map block',
  attributes: {
    class:'fa fa-map-o'
  },
  content: {
    // Built-in 'map' component
    type: 'map',
    style: { height: '350px'},
    // Once inserted it can't be removed (just an example)
    removable: false
  }
});
```

> how can I add modal pop up after drop component to our template?

If you want to add custom behavior to your Components (eg. pop up a modal when inserted into the canvas, do something when is double clicked, etc.) you need to define a new Component type but I've not yet added those API to GrapesJS but are coming soon.

**Comment by piyalmaduranga** [comment]
hi @artf 
i tried load the script in side editor,  
........
 blockManager.add('advert-id', {
        label: 'advert',
        content: '<div id="advertDiv"><script src ="https://www.sample.net/advert/api/zone/5/invocationcode"></div>',
    });
 .......

after add component not show that script image (https://www.sample.net/advert/api/zone/5/invocationcode) , only show <div id ="advertDiv"></div> 
missing my external script 
can i add external javascript to inside template?

**Comment by artf** [comment]
@piyalmaduranga I'm still in progress to make templates work properly with javascript so for this reason I simply throw away all `script` tags, I can eventually add a new config property to let it import but not sure about the consequence

**Comment by piyalmaduranga** [comment]
HI @artf 
i added block using block manager it was like <script>block content</script>  then i save my edited template and i tried edit this template again , in this time run script that i added it show image with <a> tag and <script> tag also
my problem was i want to remove html <img> tag in div i defined of my template how can i do it?

**Comment by artf** [comment]
@piyalmaduranga can you show me maybe some screenshot about your problem I don't get it. You were able to import correctly the `<script>` with Block but not with the already saved template?!?

**Comment by sebastianha** [comment]
> If you want to add custom behavior to your Components (eg. pop up a modal when inserted into the canvas, do something when is double clicked, etc.) you need to define a new Component type but I've not yet added those API to GrapesJS but are coming soon.

Do you have any updates on this? I would need this feature, too.

**Comment by andrepeitz** [comment]
I would need the feature to define a new complex Component with custom behavior too and would really appreciate the implementation.

**Comment by artf** [comment]
@sebastianha @andrepeitz working on it. I'll ping you back when it's ready.
In the meantime, can you explain me your cases?

**Comment by sebastianha** [comment]
Hi,

for example I wanted to use the image component but as I store my images in a way that the file names get prefixed with md5 sum etc, the current component is not ideal for me as it shows the full path name in the list (this is very ugly for the user).

I wanted to show only parts of the file name or a different key of the returned object of the asset manager. I am also thinking about organizing my images in folders. Also I wanted to remove the ability to add images via URL, so only upload and the list should be available.

At the end I planned to add my own custom image component type for this (and also for learning how to write them).

BTW: Thanks for the great editor and keep continuing your work!

**Comment by andrepeitz** [comment]
I would like to use it for formulars where I can send the data via AJAX request to my backend.

**Comment by artf** [comment]
@sebastianha For the asset manager you don't need another component. You can pass custom names for image assets in this way:
```js
var editor = grapesjs.init({
  ...
  assetManager: {
    assets: [
      {src: '.../cc4360/fff/image.jpg',} // Here you'll get image.jpg as asset label
      {src: '.../cc4360/fff/image.jpg', name: 'Custom name'}
    ]
  }
  ...
});
```

> Also I wanted to remove the ability to add images via URL, so only upload and the list should be available.

Just hide it with CSS :)

**Comment by sebastianha** [comment]
Thanks for the hint, didn't see that!

But for all other things a component type API would be nice :)

**Comment by artf** [comment]
@sebastianha @andrepeitz @piyalmaduranga
You can check now the new [Component](https://github.com/artf/grapesjs/wiki/Components) doc. Feedbacks are welcome :)
For any bugs open a new issue

**Comment by sebastianha** [comment]
Thank you very much, I will try it and let you know!

**Comment by andrepeitz** [comment]
Looks very good from my side! Thank you very much, I really appreciate that!

**Comment by Gerald-AuZ** [comment]
What are the properties available for the content property of the block?

**Comment by artf** [comment]
@Gerald-AuZ 
eg. HTML string
`content: '<div>...</div>'`
or GrapesJS's Component object
```
content: {
     tagName: 'section'
     attributes: {...}
     components: [{..}, {...}, ...]
}
```
