### ISSUE TITLE
Remove custom trait by its type.

### ISSUE THREAD

**Issue by vijayshukla30** [artf/grapesjs#3500]
I have created a custom trait but the name of that trait will be dynamic which is unknown. 
The problem is that the current removeTrait() only works with name/id. But what if I want to remove all traits from the component with custom-trait.

Ex: I create a trait 'my-custom-trait' and bind it to the component.
component.addTrait({
name: 'some_random',
options:[],
type: 'my-custom-trait'
});

Now, I want to remove it but I don't know the name.

**Comment by artf** [comment]
You can use of the ID
```js
component.addTrait({
  id: 'my-custom-trait', 
  name: 'some_random',
// ...
});
// ...
component.removeTrait('my-custom-trait')
```
