### ISSUE TITLE
BUG: 

### ISSUE THREAD

**Issue by snowballrandom** [artf/grapesjs#3504]
I noticed that an earlier version of font awesome version 4.7  is being used.
I use version 5.2 of fontawesome and it seems to cause issues when loaded alongside the version used with Grapes JS some of the fonts are not loading or class names have changed in the new fontawesome character set. 

How can I use the newer version of fontawesome? 
Do I need to edit the Grapes JS source and compile to make use of newer fontawesome?
![Screenshot from 2021-05-30 21-29-36](https://user-images.githubusercontent.com/2145779/120131485-28441780-c18e-11eb-8064-fbcb754c0104.png)

**Comment by artf** [comment]
You can change this option on init:
https://github.com/artf/grapesjs/blob/88249c38577852dc3c42047356a70a12066ee6ca/src/editor/config/config.js#L165-L168
