### ISSUE TITLE
FEAT: add click event on blocks

### ISSUE THREAD

**Issue by iabhiyaan** [artf/grapesjs#3506]
```js
editor.on('block:click', (block) => {
  console.log(block)
})
```

Or Is there any way to listen for click event in block ?

**Comment by YyueeiWY** [comment]
<pre>
    editor.on('component:selected', (some, argument) => {
      console.log(some, argument);
    })
</pre>

https://grapesjs.com/docs/api/editor.html#available-events

**Comment by artf** [comment]
Well you can actually make use of [custom render](https://grapesjs.com/docs/modules/Blocks.html#custom-render) from blocks to apply custom DOM events.
```js
blockManager.add('some-block-id', {
  // ... block definition
  render: ({ model, el }) => {
   el.addEventListener('click', () => {
     console.log('block', model)
   })
  },
});
```
