### ISSUE TITLE
No Generated ID and No auto select ID

### ISSUE THREAD

**Issue by cedriclajato** [artf/grapesjs#3507]
Hi Guys,

I am using grapesjs-blocks-bootstrap4 and I check how they component it's looks fine.

But when you select block like container it targets the class instead of Unique ID.

![bootstrap-4-element](https://user-images.githubusercontent.com/57404000/120257180-4a3eb680-c2c2-11eb-872a-e7da78e74ff4.PNG)

I was able to setup random ID using this model.set('attributes', { id: randomID() }); but still when you select the block it targets the  class instead of ID

**Comment by artf** [comment]
https://github.com/artf/grapesjs/issues/2936#issuecomment-680322089
