### ISSUE TITLE
BUG: Layer visibility does not work properly

### ISSUE THREAD

**Issue by tranthanhhoa** [artf/grapesjs#3508]
**Version:** 0.17.4

**How to reproduce**

1. Switch to tablet or mobile mode
2. Hide the selected component by toggling the visibility icon of Layer
3. Switch to desktop mode.

**Result**
- The visibility icon is still disabled while the hidden components is showing.

**Expected**
- After switch to desktop the visibility icon is enabled.

**Comment by artf** [comment]
Thanks for the report @tranthanhhoa I'll fix it in the next release, but I think I'll keep the visibility change more like a global condition, so the hidden component won't be visible on all devices.
