### ISSUE TITLE
QUESTION: How to programmatically change componentFirst?

### ISSUE THREAD

**Issue by theSC0RP** [artf/grapesjs#3509]
Hey @artf, I was trying toggle between using ids and classes for styling so I need to change the componentFirst attribute programmatically. But when I try to change the config, the behaviour doesn't change.
This isn't working even in the demo.
Steps to reproduce:
1. Add two text blocks
2. Give them the same class name.
3. In the browser console, change the componentFirst property using 
       `editor.getConfig().selectorManager.componentFirst = false` 
4. Add some color to the text. It is only added to the selected block

P.S. I also tried doing editor.refresh() after changing the config but that did not change anything.

**Comment by artf** [comment]
You have to retrigger the selection after changing that option `editor.trigger('component:toggled')`
