### ISSUE TITLE
Issues with Loading new template after editor has initialized.

### ISSUE THREAD

**Issue by cmcintosh** [artf/grapesjs#351]
I have a use case where I would like to allow users to switch the template they are editing.

On the initial load, the code seems to work fine and loads the template as expected, but on the subsequent loads the canvas is wiped blank.  

```js
load: function(keys, clb) {
        var result = {},
        fd = {},
        params = {
          'entity_type': drupalSettings.wembassy.siteBuilder.entity_type,
          'bundle': drupalSettings.wembassy.siteBuilder.bundle,
          'template': $('#gjs-pn-templates-a select').val(),
          'default': 1,
          'status': 1
        };

        for(var key in params)
          fd[key] = params[key];

        fd.keys = keys;

        let req = $.ajax({
          url: '/js/grapesjs/load',
          data: fd,
          async: false,
          method: 'GET',
        }).done(function(d) {
          var result = {};
          for (var i = 0, len = keys.length; i < len; i++){
            var v = d.data[keys[i]];
            if(v) result[keys[i]] = v;
          }
          console.log(result);
          clb(result);
          return result;
        });
      },
```

**Comment by artf** [comment]
Not sure about why you're loading another template from a load function, but how about just setting a new template by something like this
```js
const newHtml = fetch..
editor.CssComposer.getAll().reset();
editor.setComponents(newHtml);
```

**Comment by cmcintosh** [comment]
The implementation I am doing is for Drupal which has a hierarchy for templates.  Additionally, I am looking to provide a/b testing for site builders.

I am pulling the same data that is sent via store, to the database.   
Basically i get back the values:
gjs-assets, gjs-components, gjs-css, gjs-html, and gjs-styles.

All except HTML are object arrays, what I am looking to do is update the editor with those values and refresh the display.

**Comment by cmcintosh** [comment]
At this stage of my workflow, they are not yet Physical files.

**Comment by cmcintosh** [comment]
setComponents works well for getting the HTML in btw.  Now im just working on getting the stored css and styles in.

**Comment by cmcintosh** [comment]
Following up on this, I can get the css out of the canvas using the editor.getCss() command, is there a way to load that back in?

**Comment by artf** [comment]
@cmcintosh like this `editor.setStyle('.cls{color: red}');`?
