### ISSUE TITLE
Re render traits after certain events (e.g click) 

### ISSUE THREAD

**Issue by iabhiyaan** [artf/grapesjs#3510]
How to re render traits after clicking on buttons ? Note : Re-rendering should not be dom modification.
I have created a function that would render trait by calling the `render()` inside `createInput()`
Is there any way to re-render the traits with the newer and updated dom string which was first created on `createInput()` ?

**Comment by artf** [comment]
createInput is called once, if you want to update the UI of your trait, rely on `onUpdate` which is called every time the selection is changed.

ps. please avoid using Issues for questions, check the Discussions tab
