### ISSUE TITLE
BUG: Command core:component-enter not working in all the cases

### ISSUE THREAD

**Issue by moises-flowize** [artf/grapesjs#3511]
## WARNING
READ and FOLLOW next 3 steps, then REMOVE them before posting the issue

1. Follow CONTRIBUTING Guidelines https://github.com/artf/grapesjs/blob/master/CONTRIBUTING.md
2. Do a quick SEARCH first, to see if someone else didn't open the same issue
3. All relative statements/questions have to be filled/answered, otherwise, the issue might be CLOSED
4. JSFiddle Starter template https://jsfiddle.net/szLp8h4n
5. CodeSandbox Starter template https://codesandbox.io/s/1r0w2pk1vl

**Version:**
0.16.44

*You can get the version by typing `grapesjs.version` into the console*

**Are you able to reproduce the bug from the demo?**

 - [ ] Yes
 - [X ] No

**What is the expected behavior?**
When using the command "core:component-enter" it should select the first child of a container

*Describe the bug **detailed***
If the element selected is a P or H1, the ones that are inline elements it throws an error In the console.
Also, if the element select is a container but the first child is an HTML comment, throws the same error.

**Are you able to attach screenshots, screencasts or a live demo?**

 - [ ] Yes (attach)
 - [ x] No

I fixed creating my own command out of the code of yours at https://github.com/artf/grapesjs/blob/dev/src/commands/view/ComponentEnter.js:

I attach the JS file with the code of my command
[component-enter.txt](https://github.com/artf/grapesjs/files/6584093/component-enter.txt)

**Comment by artf** [comment]
Thanks @moises-flowize that will be fixed in the next release https://github.com/artf/grapesjs/commit/ac96298add119c4f4e000967ab3332f9ad711613
