### ISSUE TITLE
[QUESTION]:How to make a custom block always be at the bottom of the page

### ISSUE THREAD

**Issue by sizhousama** [artf/grapesjs#3513]
How to make a custom block always be at the bottom of the page？

**Comment by YyueeiWY** [comment]
u need display flex
for ur case, align every block at end (  align-content: flex-end; ) 
<pre>
&lt;body class="flex-container flex-end"&gt;
  &lt;div class="flex-item"&gt;1&lt;/div&gt
  &lt;div class="flex-item"&gt;2&lt;/div&gt
  &lt;div class="flex-item"&gt;3&lt;/div&gt
  &lt;div class="flex-item"&gt;4&lt;/div&gt
  &lt;div class="flex-item"&gt;5&lt;/div&gt
  &lt;div class="flex-item"&gt;6&lt;/div&gt
&lt;/body&gt

html, body {
  height: 100%;
}
.flex-container {
  float: left;
  width: 100%;
  height: 100%;
  border: 1px solid silver;
  
  -ms-box-orient: horizontal;
  display: -webkit-box;
  display: -moz-box;
  display: -ms-flexbox;
  display: -moz-flex;
  display: -webkit-flex;
  display: flex;
  
  -webkit-flex-flow: row wrap;
  flex-flow: row wrap;
}

.flex-end { 
  align-content: flex-end; 
}

.flex-item {
  width: 100%;
  background: red;
}
</pre>

**Comment by artf** [comment]
Hi @sizhousama the easiest way probably could be some kind of CSS trick or you can define, by using custom components, a structure with fixed containers (eg. one for the header, for the body and the footer)
