### ISSUE TITLE
Uncompressed version

### ISSUE THREAD

**Issue by martinrios95** [artf/grapesjs#352]
Hi!

¿Have you got an _uncompressed version_ of this framework? As I could see, there's only the minified version on this repo, so I can see the code for development environment.

Best wishes,

Martin

**Comment by cmcintosh** [comment]
You can see the uncompressed versions in the src folder.  not totally sure how to load the unminified ones though.

**Comment by martinrios95** [comment]
It's kinda Backbone.js usage... so I haven't understood that kinda framework so much, yet. I'm just learning Backbone...

**Comment by artf** [comment]
As already mentioned by Chris you'll find everything in the src folder ;)
