### ISSUE TITLE
[QUESTION]: Integrate select2 UI element into traits 

### ISSUE THREAD

**Issue by iteniel** [artf/grapesjs#3524]
I'm new to grapesJS ... Great tool.I have a few questions about traits. 
I followed this tutorial 
**https://grapesjs.com/docs/modules/Traits.html#define-new-trait-type**
 because I have to overwrite how href is generated. The example is great for me with few modifications. I I want to replace ....

`
<select  multiple="multiple">
    <option value="option"></option>
    .......
</select>
`
![Selection_208](https://user-images.githubusercontent.com/25899228/121146044-d65f5980-c83f-11eb-9ae3-99537f0337ff.png)

with select2 tagging. But I need something like `onPostRender/afterRender` to initialize the select2 component when the DOM is present

The available methods by  the example are
`createInput, onEvent, onUpdate` 

Another thing to trigger `onEvent` from select2

`
tagListElement.on('select2:select', function (evt) {
    // trigger trait onEvent method
});
`
Can someone help with this?

**Comment by artf** [comment]
You can do this:
```js
tagListElement.on('select2:select', e => this.onChange(e)); // onChange will trigger the onEvent properly
```

**Comment by iteniel** [comment]
@artf thanks

Can you help with first part of the question
 **I need something like onPostRender/afterRender to initialize the select2 component when the DOM is present**
