### ISSUE TITLE
I wasn't able to unit test grapesjs components

### ISSUE THREAD

**Issue by krishnaeverestengineering** [artf/grapesjs#3528]
Not sure exactly whats happening but this is what I am getting. Sometimes tests are passing and randomly tests are failing due to this. Any help please @artf 

<img width="1474" alt="Screenshot 2021-06-10 at 7 08 14 PM" src="https://user-images.githubusercontent.com/55732888/121535085-71faf080-ca1f-11eb-8e07-aeedf9ab7464.png">

**Comment by artf** [comment]
Same as here https://github.com/artf/grapesjs/issues/3476#issuecomment-848074298
