### ISSUE TITLE
Problems when with grapesjs-present-newsletter plugin

### ISSUE THREAD

**Issue by matiponce91** [artf/grapesjs#353]
Hi All,
I am trying to use GrapesJs with grapesjs-present-newsletter plugin so I can show HTML with inside CSS. So I installed the plugin through npm and then imported the library inside index.html. Finally within "grapes.init ()" I added the following code:

```
plugins: ['gjs-preset-newsletter'],
       pluginsOpts: {
           'gjs-preset-newsletter': {
         		inlineCss: true,
         		modalLabelImport: 'Paste all your code here below and click import',
 			modalLabelExport: 'Copy the code and use it wherever you want',
           }
 }
```

but "inlineCss" (it doesn't matter if its value is true or false ) and "modalLabelExport" don't work, showing the "Export modal" as it is configured on grapes core (two blocks, one for HTML and one for CSS). And for example "modalLabelImport" or any other property, that is not related to export modal, work perfectly fine.

**Comment by artf** [comment]
Fixed and published a new release, thanks for the catch

**Comment by matiponce91** [comment]
can you check this commit https://github.com/artf/grapesjs/pull/356?
