### ISSUE TITLE
FEAT: JSON Object model of the page generated

### ISSUE THREAD

**Issue by marvincd** [artf/grapesjs#3531]
I need to generate the JSON object model of the page designed instead of generating the HTML, CSS, and js code, is there a function that returns the JSON object of the page designed?
Also, I'm implementing the UI builder in angular so the typescript version will be preferred.

**Comment by artf** [comment]
I'd highly recommend reading the documentation pages like [Components](https://grapesjs.com/docs/modules/Components.html) and [Storage Manager
](https://grapesjs.com/docs/modules/Storage.html) where all these parts are covered.
