### ISSUE TITLE
Can we use Grapesjs in commerical software like a drag and drop HTML editor

### ISSUE THREAD

**Issue by Logic-Hamza** [artf/grapesjs#3533]
Can we use grapesjs in html drag and drop editor for commerical software

**Comment by artf** [comment]
Yes you can, check the [LICENSE](https://github.com/artf/grapesjs/blob/dev/LICENSE)

**Comment by bilogic** [comment]
@artf 

So I can host this editor on my own domain correct? https://grapesjs.com/demo-mjml.html

**Comment by artf** [comment]
@bilogic sure thing
