### ISSUE TITLE
grapesjs lory slider

### ISSUE THREAD

**Issue by vuongluc** [artf/grapesjs#3535]
I am using the plugin grapesjs-blocks-bootstrap4 and integrated grapesjs-lory-slider it works the first time I use it but when I load it from the database it loses the slider feature .
Where am I doing wrong?

When pulled in, it still works normally
![image](https://user-images.githubusercontent.com/54711078/121833210-0b632480-ccf6-11eb-8028-735dc0381338.png)

This is when I load them from the database and they turn into box
![image](https://user-images.githubusercontent.com/54711078/121833346-5aa95500-ccf6-11eb-8032-51c3a940e719.png)

this is how to load from my database. Does it have any problem?
![image](https://user-images.githubusercontent.com/54711078/121833440-8debe400-ccf6-11eb-92c8-18708364d808.png)
Thanks!

**Comment by artf** [comment]
Hi @vuongluc yeah, it might be a problem loading back html/css in that way for editing. You should store and load back JSON data, check out [this guide](https://grapesjs.com/docs/modules/Storage.html#store-and-load-templates)
