### ISSUE TITLE
Problem when building grapesjs 

### ISSUE THREAD

**Issue by Owchzzz** [artf/grapesjs#354]
`npm run build`

Test fails. From a fresh installation.

I removed `npm test` and tried to run the webpack generated distributables on an apache server.

Unfortunately the Ui is completely broken...

![image](https://user-images.githubusercontent.com/7088147/31045050-1a1dddfc-a60e-11e7-8290-182e0d5f94b2.png)

Anyone run into this?

p.s. im using Cloud9 IDE if that makes any difference.

**Comment by Owchzzz** [comment]
Here is the specific Error
`1 failing

  1) Main Panels Main No panels inside:

      Error: Expected 2 to equal 3
      + expected - actual

      -2
      +3
      
      at assert (node_modules/expect/lib/assert.js:29:9)
      at Expectation.toEqual (node_modules/expect/lib/Expectation.js:81:30)
      at Context.<anonymous> (test/specs/panels/index.js:28:38)



npm ERR! Test failed.  See above for more details.`

**Comment by artf** [comment]
Hi @Owchzzz 
- Which version of grapesjs? 
- Did you run `npm i`? 
- Why do you run the build? Did you make changes?

**Comment by artf** [comment]
ping @Owchzzz

**Comment by Owchzzz** [comment]
Oh sorry @artf 

I had forgotten about this thread.

Everything's fine now I believe it was just the work of the previous developer he changed a lot of the src to meet our requirements. Both really unnecessary and really bad practice.

Thank you for the followup and I apologize for troubling you with this non existent issue.

Awesome work on the builder.
