### ISSUE TITLE
BUG: Trait Button Command not working on 0.17.4

### ISSUE THREAD

**Issue by maekawataiki** [artf/grapesjs#3544]
**Version:0.17.4**

The trait with type button does not call command on 0.17.4 which is used to work before 0.17.3.

## Expected Behaviour
Clicking button invoke command defined in trait.

## What is happening
Clicking button does nothing

## jsfiddle example

Command working on 0.17.3 -> https://jsfiddle.net/7pmz4u1v/3/
Command not working on 0.17.4 -> https://jsfiddle.net/7pmz4u1v/4/

**Comment by tudor-ooo** [comment]
@maekawataiki This is fixed, but not yet released - https://github.com/artf/grapesjs/issues/3497
