### ISSUE TITLE
BUG: Dragging multiple blocks reverses the order

### ISSUE THREAD

**Issue by japo32** [artf/grapesjs#3547]
### Version:

0.17.4

### Are you able to reproduce the bug from the demo?

YES

### What is the expected behavior?

When dragging the blocks, the order should be preserved.

### **What is the current behavior?**

When dragging to the top or above the set of blocks, it goes in one order.

When dragging to the bottom or below the set of blocks, it goes in another order.

This may become a problem if selecting a lot of blocks or the blocks are tall.

### **Are you able to attach screenshots, screencasts or a live demo?**

![Screen Shot 2021-06-17 at 10 34 58 AM](https://user-images.githubusercontent.com/676680/122303979-904d7880-cf58-11eb-9ae8-3c29e30ac83e.png)

![Screen Shot 2021-06-17 at 10 35 04 AM](https://user-images.githubusercontent.com/676680/122303993-93e0ff80-cf58-11eb-8630-80aff8f4f67b.png)

https://user-images.githubusercontent.com/676680/122304455-5f217800-cf59-11eb-8925-0374deb9b1fb.mov

**Comment by lexoyo** [comment]
Hello
I'm trying to fix this bug
This is more of an exercise for me to dive in grapesjs code, let me know if I'm loosing my time or if it sounds useful
