### ISSUE TITLE
BUG: cann't copy with "control + C" when elements have attribute tabindex = -1

### ISSUE THREAD

**Issue by tannguyen97** [artf/grapesjs#3548]
Hi everyone! 
i have a problem with custom component. i was created a modal component have attribute tabindex = -1 and i can't use key Ctrl + C to copy this component.
Pls helps me. 
thanks very much !!!

**Comment by artf** [comment]
Just remove that attribute in your component view (eg. in onRender method) in that way you'll still get the attribute in your final HTML
