### ISSUE TITLE
BUG: Unable to refresh the iframe 

### ISSUE THREAD

**Issue by theSC0RP** [artf/grapesjs#3564]
**0.17.19**

**Are you able to reproduce the bug from the demo?**
YES

**What is the expected behavior?**
I had asked a question regarding iframe refresh (#3413). The [proposed solution](https://github.com/artf/grapesjs/issues/3413#issuecomment-831892231)  was working for that version (0.17.3) and after running the piece of code the iframe should refresh and the canvas should be seen with the components and styles that were present.

*Describe the bug **detailed***
I get an error in the console which says `Cannot read property 'remove' of undefined` in the file ComponentView.js at line 97

**What is the current behavior?**
The canvas isn't visible after the code was run in the console and the aforementioned error is seen in the console.

**Are you able to attach screenshots, screencasts or a live demo?**
*Screenshot*
![Screenshot from 2021-06-24 15-51-04](https://user-images.githubusercontent.com/30771519/123247031-1000b780-d504-11eb-8b37-54cf89fe3a50.png)

**Comment by artf** [comment]
I would need to check why he is still trying to remove the frame, but for now, just skip this line `frameView.remove()`

**Comment by theSC0RP** [comment]
@artf. Thanks. This works when done once. 
If I do some action like a click inside the canvas and then if I run `frameWrapView.render();` once again, I got another error. The screenshot and a video of this error are attached below.
<hr>

https://user-images.githubusercontent.com/30771519/123492864-5ce5aa80-d638-11eb-984e-1807614a3bfb.mp4

![Screenshot from 2021-06-26 04-37-24](https://user-images.githubusercontent.com/30771519/123492929-8ef70c80-d638-11eb-8dc1-a5b2709ba26d.png)

**Comment by artf** [comment]
I'll try to fix it in the next release, but for now, you have to unselect components before `frameWrapView.render()` and reselect them back post rendering
