### ISSUE TITLE
BUG: Duplicate controls for every component

### ISSUE THREAD

**Issue by jasminder** [artf/grapesjs#3573]
**Version:**
0.17.17

**Are you able to reproduce the bug from the demo?**

 - [ ] Yes
 - [x] No

**What is the expected behavior?**
It shouldn't show duplicate controls. 

**What is the current behavior?**
![db](https://user-images.githubusercontent.com/1322355/123553458-e44a2f80-d798-11eb-8373-af205370e8e8.JPG)

*Describe the bug **detailed***
For some reasons, i am getting duplicate controls with vanila setup of gjs.

**Are you able to attach screenshots, screencasts or a live demo?**

 - [x] Yes (attach)
 - [ ] No

**Comment by artf** [comment]
Add this to your init config in order to remove the default properties `styleManager: { clearProperties: 1 },`
