### ISSUE TITLE
BUG: The UndoManager hasUndo() method returns true when it shouldnt

### ISSUE THREAD

**Issue by alimajed93** [artf/grapesjs#3577]
I am trying to disable the undo button when there are no undo actions to do.

To do so, I am listening to `'change:changesCount'` event, and using `editor?.attributes?.UndoManager?.hasUndo()` to set the undo button disabled state.

`editor.on('change:changesCount', editor => setHasUndo(editor?.attributes?.UndoManager?.hasUndo()));`

It is doing the job for me except in the below scenario:

- I am creating a new template on a blank canvas
- I drag and drop a block
- I undo

The problem here is that even though the undo now should be disabled, it is not, because `editor?.attributes?.UndoManager?.hasUndo()` is returning true, same as `editor?.UndoManager?.hasUndo()`. After doing one extra useless undo, `editor?.UndoManager?.hasUndo()` starts returning false.

I think the problem is that when I hover a block over the canvas, even before dropping it, we have an action added to the queue, and therefore `changesCount` is equal to 1 already. After dropping the block `changesCount` is increased to 2, while it should be 1.
So there is an extra action added to the queue while it shouldn't, which is when I am dragging a block over the canvas.

To note that this doesn't happen with the second block or all the blocks after. It only happens with the first block dragged and dropped.

As a summary, when dragging and dropping the first block into the canvas, there are now 2 undo actions in the UndoManager queue, and not only 1 as expected.

**Comment by artf** [comment]
> So there is an extra action added to the queue while it shouldn't, which is when I am dragging a block over the canvas.

Not really, are you able to create a reproducible demo, as I'm not able to reproduce it?
