### ISSUE TITLE
BUG: version 0.17.4  the components missing when try to add background image to body

### ISSUE THREAD

**Issue by jcsofts** [artf/grapesjs#3578]
I add 
domComponents: { storeWrapper: 1 },
when initialize the webeditor, to enable add background image to body. 

it works fine when use the local storageManager , but all the components lost when use the remote storageManager

below is the data 

{"type":"wrapper","droppable":".container","attributes":{"id":"izmf"},"components":[{"type":"container","classes":[{"name":"container","active":false}],"attributes":{"id":"iboj"},"components":[{"type":"row","classes":[{"name":"row","active":false}],"components":[{"type":"column","classes":[{"name":"col","active":false}],"components":[{"type":"header","content":"Bootstrap heading","attributes":{"id":"iie1"}}]},{"type":"column","classes":[{"name":"col","active":false}]}]}]}]}

below is the screenshot:

1. the background image with components
![image](https://user-images.githubusercontent.com/33087222/123909501-b852c800-d9ab-11eb-86bd-3dc88c4d37b5.png)

2. the screenshot after  reload, you will found that missing the components

![image](https://user-images.githubusercontent.com/33087222/123909715-fd76fa00-d9ab-11eb-9243-d4d39260dae0.png)

**Comment by artf** [comment]
Hi @jcsofts if the local storage works fine and your remote does not, that means you're probably doing something wrong on your endpoint side.
I can't help you here without a reproducible example so I can only suggest following properly this [guide](https://grapesjs.com/docs/modules/Storage.html).
