### ISSUE TITLE
BUG: RTE misplaced when opened right after dropping `activeOnRender` component

### ISSUE THREAD

**Issue by mcottret** [artf/grapesjs#3579]
**Version:** 0.17.4

**Are you able to reproduce the bug from the demo?**

 - [x] Yes
 - [ ] No

**Steps to reproduce:**

- Go to the [demo](https://grapesjs.com/demo.html)
- Drop a "Text" block inside the canvas
- Click on the "Text" component that was just dropped
- The opened RTE is misplaced (cf [attached screenshot](https://user-images.githubusercontent.com/9916749/123977724-89465180-d9bf-11eb-9e99-d1b1f9cb897c.png))

**What is the expected behavior?**

The opened RTE should be positioned correctly

**What is the current behavior?**

The RTE is misplaced, it hides the "Text" component's content & can prevent editing properly (especially when using bigger custom RTE like CKEditor).

This only happens when the RTE is first opened & only if the dropped block is a "Text" component with `activeOnRender` option set to `true`.

This is caused by [a miscalculation of the toolbar's position](https://github.com/artf/grapesjs/blob/dev/src/rich_text_editor/index.js#L278) when [its `offsetHeight` equals 0](https://github.com/artf/grapesjs/blob/8b423fdf093865a6bf55dc8285030ce99c111d6d/src/canvas/index.js#L426). Itself due to its parent ([`CanvasView.toolsEl`](https://github.com/artf/grapesjs/blob/dev/src/canvas/index.js#:~:text=*/-,getToolsEl,-(compView)%20%7B)) being set to `display: none` at this time (because [`rte.enable` is called on drop when `activeOnRender` is `true`](https://github.com/artf/grapesjs/blob/8b423fdf093865a6bf55dc8285030ce99c111d6d/src/dom_components/view/ComponentTextView.js#L48), which happens while the component is [unselected as opposed to normal, hence its `toolsEl` still being set to `display: none`](https://github.com/artf/grapesjs/blob/dev/src/commands/view/SelectComponent.js#L225)) 

**Proposed solution:**

Selecting the component before triggering `activeOnRender`'s `active` event seems to fix the issue.

Concretely, adding `em.setSelected(result);` before `result.trigger('active');` [here](https://github.com/artf/grapesjs/blob/dev/src/block_manager/view/BlockView.js#L104) should do it, unless I'm missing something.

I could take care of the PR if this looks good to you :)

**Are you able to attach screenshots, screencasts or a live demo?**

 - [x] Yes (attach)
 - [ ] No

<img width="803" alt="Screenshot 2021-06-30 at 4 21 11 PM" src="https://user-images.githubusercontent.com/9916749/123977724-89465180-d9bf-11eb-9e99-d1b1f9cb897c.png">

**Comment by artf** [comment]
Yes, I guess you're right. It doesn't actually make sense activating RTE without selecting the component (it probably makes sense with all other "activatable" blocks).

**Comment by ronaldohoch** [comment]
Hello, just updated the file from commit bb4a661, and i think it's so close, i'm using the grapesjs-ckeditor code and the first open of  RTE, i'ts placed right:
![image](https://user-images.githubusercontent.com/2287371/129779602-382fcbd7-2ecb-4c20-8302-d767f52a5066.png)

But at the second time the rte is open, it's misplaced again... :/
![image](https://user-images.githubusercontent.com/2287371/129779718-0737f7ac-3577-4870-8188-8c1d843ca069.png)

I'll keep checking for it :/

**Comment by migokcek** [comment]
I have the same issue. Did anyone find a solution?

**Comment by gustavohleal** [comment]
Hi. Me and @ronaldohoch have found a workaround for this problem.

We trigger the scroll event when the RTE is enabled.
Here's the code:
    
```javascript
    // Trigger scroll event from canvas so that grapesjs
    // fix CKEditor position correctly
    editor.on("rte:enable", () => {
        editor.trigger('canvasScroll');
    });
```

**Comment by migokcek** [comment]
Thank you for your answer, i tried your code after 
`const editor = grapesjs.init({...})`
But it didn't change anything, i thought it's about my grapesjs version and, i upgraded my version but still missplaced when i open the text block for the first time

**Comment by ronaldohoch** [comment]
Can you provide some code in jsfiddle? https://jsfiddle.net/szLp8h4n
