### ISSUE TITLE
Calling updateScript from the script section of a pluging

### ISSUE THREAD

**Issue by daniel-farina** [artf/grapesjs#358]
Hi guys, 

I've been stuck for a few hours trying to figure out how to call updateScript  from the script section of a custom plugin.  So far I was able to create my own plugin which I would like to share once it's stable. I need to refresh it once it connects to an external API and retrieves specific data. 

```
export default function(editor, opt = {}) {
    const c = opt;
    const editr = editor;
    const domc = editor.DomComponents;
...
    domc.addType(COMPONENT_TYPE, {
        model: defaultModel.extend({
            defaults: ....
            script: function()
    {
       // ** ********** HOW DO I CALL IT   FROM HERE**
        this.updateScript

    }
}

    view: defaultView.extend({
        init()
        {
            this.listenTo(this.model, 'change:clienId change:limitImages', this.updateScript);
            const comps = this.model.get('components');

        }

```

any help is appreciated !

Thank you!

**Comment by artf** [comment]
Hi @daniel-farina this is something that might confuse a lot of people, especially when you see the `script` as function. Everything inside `script` is completely out of the scope of GrapesJS, there is nothing to access (model/view/methods) all the transformations should be inside that `script`.  Let's just take as an example some new custom component with js, the editor will generate a code similar to this:
```html
...
<!-- Generated HTML -->
<div id="c123">Your component content...</div>
<script>
     ...
     // Generated JS
     var el = document.getElementById('c123');
     el.updateScript() // <-- This will obviously throw an error
     // This is your final template with JS, there is no GrapesJS, no models/views
</script>
```
Just take a look on how I've made the script part in [Countdown Component](https://github.com/artf/grapesjs-component-countdown/blob/master/src/components.js)
There you can see a trick used to grab a property of the model.

```js
...
script: function() {
     // will be replaced by GrapesJS with `model.get('startfrom')`
     var startfrom = '{[ startfrom ]}';
     ...
```
This is the only way you can pass "stuff" 
I hope this helps

**Comment by artf** [comment]
Amazing work @daniel-farina excited to see it done 😍
