### ISSUE TITLE
how to listen the components change in a component.

### ISSUE THREAD

**Issue by jcsofts** [artf/grapesjs#3586]
init() {
                this.listenTo(this.model,'change:components', this.handleComponentsChange);
 },

I develop a component, I try to listen the child components change, then I add above code to view init, but the function doesn't fired when add/remove component.

how I can listen the components change in a component view?

thanks

**Comment by anlumo** [comment]
The components collection doesn't change, that's why there's no event triggered.

The storage backend is a Backbone collection, see [here](https://backbonejs.org/#Collection). You have to listen to its events, specifically `add` and `remove`.

**Comment by artf** [comment]
As already mentioned by Andreas, you have to add a listener to the collection.
```js
init() {
  const children = this.model.components();
  this.listenTo(children, 'add remove', this.handleComponentsChange);
},
```

**Comment by chaegumi** [comment]
```javascript
view: {
            init() {
                this.listenTo(this.model, 'change:container_is_empty', this.render);
                const children = this.model.components();
                this.listenTo(children, 'add remove', this.hanldeComponentsChange);
                // this.listenTo(children)
            },
            hanldeComponentsChange() {
                console.log('eee')
            },
```
why can't work

**Comment by dm-siegel** [comment]
I know this is old, but i was trying to get this to work as well.  Essentially, the new component is a container for other components and when there is nothing in it, I use the view to el.innerHtml = 'Empty'.  When I drop a component inside, i would like to re-render but can't seem to figure out how to listen for changes to the content inside.  this.model.components() in the init() method generates an error.

**Comment by chaegumi** [comment]
this work for me
```javascript
view: {
            init({ model }) {
                this.listenTo(model.getChildAt(0).components(), 'add remove', this.render);
            },
            onRender({ el, model }) {
                // container-inner下的components
                // console.log(el)
                // console.log(model.getChildAt(0).toHTML())
                const comps = model.getChildAt(0).components();

                // console.log(comps.length)
                // for (const comp of comps) {
                //     console.log(comp.getInnerHTML())
                // }

                if (comps.length > 2) {
                    // 有更多组件，删除jeawin-empty-view
                    const div = el.querySelector('.jeawin-empty-view')
                    if (div) {
                        // div.remove();
                    }
                } else {
                    // 没有更多组件，jeawin-empty-view占位
                    const div = document.createElement('div')

                    div.className = 'jeawin-empty-view';

                    div.innerHTML = `<div class="jeawin-first-add">
                            <div class="jeawin-icon fa fa-plus"></div>
                        </div>`;

                    div.querySelector('.jeawin-icon').addEventListener('click', (e) => {
                        e.stopPropagation();
                        e.preventDefault();
                        editor.Panels.getButton('views', 'open-blocks').set({ active: true });
                    })
                    // 判断有没有子元素
                    const inner = el.querySelector('.container-inner');
                    // if (!inner.innerHTML) {
                    el.querySelector('.container-inner').appendChild(div);
                    // }
                }


            }
        }
```

**Comment by dm-siegel** [comment]
I couldn't get this to work either.  Error reading components() when setting the listenTo.  The tag is empty (no contents inside) on init, so this makes sense.

**Comment by dm-siegel** [comment]
> I couldn't get this to work either. Error reading components() when setting the listenTo. The tag is empty (no contents inside) on init, so this makes sense.

never mind... i was doing this in the init of the model instead of the view.  
```typescript
init() {
  const children = this.model.components();
  this.listenTo(children, 'add remove', this.handleComponentsChange);
},
``` 

this worked after I put it in the correct init :)
