### ISSUE TITLE
QUESTION: How can I create grapesjs service for generating HTML from stored components?

### ISSUE THREAD

**Issue by walking-dev** [artf/grapesjs#3587]
Hello. Is there possibility to create grapesjs instance, without generating whole editor? I had created custom components with async data and I need to create backend service in Node, which generates HTML output from stored components, populated with data from APIs.

Now I am getting error:

> ReferenceError: window is not defined

Thank you.

**Comment by artf** [comment]
I close it as a duplicate of https://github.com/artf/grapesjs/issues/3399
