### ISSUE TITLE
Question: any way to make GrapeJS Mobile Editor usable?

### ISSUE THREAD

**Issue by ap0l0** [artf/grapesjs#3588]
Hello,

Amazing project! however, after checking the plugin for grapejs touch is still very hard to use the editor from a Mobile Device. 

is there a way to simplify the UI to make it easier to customize from a mobile device? This mainly for the "newsletter" option.

Thanks a lot! hope I didn't break any rules

**Comment by artf** [comment]
Unfortunately, the current UI is what it is, the alternative is to build your own UI more mobile-friendly.
