### ISSUE TITLE
Autoload storage is not working on page refresh

### ISSUE THREAD

**Issue by lbmir** [artf/grapesjs#3589]
Hi, firstly I want to say that this project is awesome, thank you!

I used code from GrapeJS Demo example, and added there save and load data from remote files, this is my storageManager code:

```
 storageManager: {
            id: 'gjs-',             // Prefix identifier that will be used on parameters
            type: 'remote',          // Type of the storage
            autosave: false,         // Store data automatically
            autoload: true,         // Autoload stored data on init
            urlStore: 'save_now.php',
            urlLoad: 'load_now.php',
            params: { page_id: 11111 },
            contentTypeJson: true,
            headers: {
            'Content-Type': 'application/json'
            }
        }
```

save_now.php file code:

```
header("Content-Type:application/json");
$data = file_get_contents("php://input");
file_put_contents('test.txt', $data);
```

load_now.php file code:

```
header("Content-Type:application/json");
$response = file_get_contents("test.txt");
echo $response;
```

When I am saving my changes it is working fine, but after that if I am press to **Refresh** page it loads old content which was before my changes.

But if I use **Hard Refresh** page than it is content is fine it is showing my last changes.

How can I keep saved content when user refreshing page?

It seems that it is saving old content somewhere and reloading it after refresh but not using urlLoad from storage manager that I defined. 

May be there is a way to disable loading of old content and only use urlLoad from storage Manager?

**Comment by lbmir** [comment]
Same issue like on [ https://github.com/artf/grapesjs/issues/2963]( https://github.com/artf/grapesjs/issues/2963).
But in my case it is loading content after Hard Refresh

**Comment by artf** [comment]
Sounds more like an issue from your side, web applications do not distinguish Refresh from Hard Refresh, indeed the Hard Refresh is more like a refresh without the browser local cache. Try to check, from the inspector, if your load call is actually returning the correct data (eg. maybe you have a web server with kind of cache enabled)
