### ISSUE TITLE
BUG: Hover on component when parent of editor scrolls, show wrong positioning

### ISSUE THREAD

**Issue by maxtsh** [artf/grapesjs#3594]
Version: 0.17.19

Are you able to reproduce the bug from the demo? No, because its full screen and there is no parent container scroll.

**What is the expected behavior?**
Hover state cadre to see the component changes position 

*Describe the bug **detailed***
When I want to select or hover on specific component, it shows wrong positioning for cadre because of the parent scroll.
this was not a case before 0.17.19 and it was fine.

**Are you able to attach screenshots, screencasts or a live demo? YES

![Screenshot_17](https://user-images.githubusercontent.com/38842256/124558368-c42d0700-de4f-11eb-936f-881fc0cd57ea.png)

**Comment by artf** [comment]
If the scrollable element is not the editor's parent node, you might need this option
https://github.com/artf/grapesjs/blob/dc45604962e4e6a4a075f19d5de67090bac15fa5/src/editor/config/config.js#L157-L163
