### ISSUE TITLE
BUG: Values are not escaped

### ISSUE THREAD

**Issue by aimeos** [artf/grapesjs#3596]
GrapesJS code is open to XSS issues because values are inserted into DOM without escaping, e.g. https://github.com/artf/grapesjs/blob/dev/src/asset_manager/view/AssetImageView.js#L30

If `model.getFilename()` returns `<img src=x onerror=alert(document.cookie)>.jpg`, this can result in an account takeover. Instead the code should be for example:
```
    return `
      <div class="${_.escape(pfx)}name">${_.escape(name)}</div>
      <div class="${_.escape(pfx)}dimensions">${_.escape(dim)}</div>
    `;
```

Similar issue here https://github.com/artf/grapesjs/blob/dev/src/asset_manager/view/AssetImageView.js#L15 and fix would be the same:
```
    return `
      <div class="${_.escape(pfx)}preview" style="background-image: url('${_.escape(src)}');"></div>
      <div class="${_.escape(pfx)}preview-bg ${_.escape(this.ppfx)}checker-bg"></div>
    `;
```

To be one the save side, everything that is injected into HTML code must be escaped.

**Comment by aimeos** [comment]
@artf What are your plans because the vulnerability of GrapesJS to XSS is a pretty big security problem

**Comment by artf** [comment]
Yeah thanks for the report @aimeos I'll fix it in the next version for sure

**Comment by aimeos** [comment]
@artf The documentation also uses `${var}` to insert variables into templates often. This should also be changed to avoid that developers introduce security issues too without knowing that.
