### ISSUE TITLE
@keyframes not adding even after i pass the the keyframes object

### ISSUE THREAD

**Issue by niranjank151** [artf/grapesjs#3599]
Hi @artf,

I have added the 
           `let cc = editor.CssComposer;
           cc.setRule('.fadetop-animate', 
               { opacity: 0, 'animation-name': 'fadeTop' }, 
               {
                atRuleType: 'keyframes',               
                atRuleParams: 'fadeTop',              
                selector: 'to',
                style:{                 
                  opacity: 1
                }
              });`
as per the Document [](https://grapesjs.com/docs/api/css_composer.html#setrule)
however rule for keyframes is not getting added to the component.
how to add keyframes to the component style?

**Comment by artf** [comment]
Use this one
```js
editor. CssComposer.getAll().add(`@keyframes fadeTop { ... }`) // Your CSS string
```
