### ISSUE TITLE
Issue in Text Edit . Text not select agian if it remove 

### ISSUE THREAD

**Issue by NoumanAhmad-Braqsol** [artf/grapesjs#3603]
First of all thanks for the great tool @artf . As i am working on a project . So i have an issue while text editing . if i select a text box and edit a text it works fine' but if i remove all text and click somewhere else and again try to select text box . it not work because empty text go hide and did not select  again. if i check in dom it exist like <p><p> but empty . why it did not select empty <p> again. 

Moreover i want to select only text box on hover . i dont need to click to box then edit it . can we auto open ckeditor on hover a text field.
thanks in advance

**Comment by artf** [comment]
I'd say more a layout issue. As the box doesn't have any text it loses its dimensions so it's hard to enable it again. Anyway, you can extend your text components and add some extra styles to make it easier to select when are empty.
For the hover, you need to extend the text component view and bind the onActive method on hover.
