### ISSUE TITLE
editor.on('component:update:content', model => {  }}) not work in some cause

### ISSUE THREAD

**Issue by NoumanAhmad-Braqsol** [artf/grapesjs#3604]
if the user remove all text from a element and click some where else . then again try to select empty element he is not able to select it again because it is hide and i dont know where it goes. So for this issue I am using this code

```
editor.on('component:update:content', model => {
const val = model.get('content');
if(val && val.length < 1){
model.set('content', '&nbsp');
}
})
```

this code set a space in text if user remove all text from a element . By doing this these is no empty element so i does not hide . and again we can select it . if the user remove text character one by one it works fine . But now issue is that if a user select a text by CTRL + A and remove by BACKSPACE . At this time this above code not work . Can anyone help me .

**Comment by NoumanAhmad-Braqsol** [comment]
I am using this code

**Comment by artf** [comment]
As already suggested here https://github.com/artf/grapesjs/issues/3603#issuecomment-885305546 avoid doing what you're doing now and add a simple default CSS in case the element is empty

**Comment by NoumanAhmad-Braqsol** [comment]
Thank you i got it !
