### ISSUE TITLE
BUG: if I use float from alignment float not clear that's why design issue occur.

### ISSUE THREAD

**Issue by Palash-Mandal** [artf/grapesjs#3606]
Hello @artf ,

There a generic issue when try to create a layout using float form alignment.

The issue is float not clear automatically.

![image](https://user-images.githubusercontent.com/17553816/125087079-d32ee600-e0e9-11eb-8a08-15020c15b8fd.png)

how do I add new class in row when user set flow value float left /right

`<div data-gjs-type="default" draggable="true" data-highlightable="1" class="row" id="iroj"><div data-gjs-type="default" draggable="true" data-highlightable="1" class="cell" id="i3qv"><img data-gjs-type="image" draggable="true" id="iomk" src="https://images.unsplash.com/photo-1544526226-d4568090ffb8?ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8aGQlMjBpbWFnZXxlbnwwfHwwfHw%3D&ixlib=rb-1.2.1&w=1000&q=80" class="gjs-selected" width="300"></div><div data-gjs-type="default" draggable="true" data-highlightable="1" class="cell" id="icg6"><h1 data-gjs-type="HEADER-COMPONENT" draggable="true" data-highlightable="1" id="iea5" contenteditable="false" class="">Insert your heading</h1></div></div>`

I wants to set a new class in **parent div class row** to clear float using css like below image as shown.

![image](https://user-images.githubusercontent.com/17553816/125089996-7ed93580-e0ec-11eb-8d0a-3ac1184cf0ac.png)

**Comment by artf** [comment]
Please follow the issue template
