### ISSUE TITLE
FEAT: Disable Dragging

### ISSUE THREAD

**Issue by anlumo** [artf/grapesjs#3608]
**What are you trying to add to GrapesJS?**

I have implemented an alternative text editing component (not based on RTE). I want people to be able to drag-select text in this component.

*Describe your feature request **detailed***

The problem is that drag-selection also triggers dragging the whole component. I want to be able to move the component on the page only via the move toolbar item, to stop it interfering with text selection.

**Is there an alternative at the latest version?**

I'm currently overriding the drag like this:

```js
element.addEventListener('dragstart', event => {
    event.stopPropagation();
    event.preventDefault();
    return false;
}, true);
```

in the view's `init` function. This kinda works in Chrome, but not always and also causes more issues in Firefox.

**Comment by iabhiyaan** [comment]
```js

editor.on('component:drag:start', props => {
    const { target } = props;
    target.set({
        draggable: false,
        propagate: ['draggable']
      });
  });
```

**Comment by anlumo** [comment]
Wouldn't that disable all dragging, even from the toolbar?

**Comment by anlumo** [comment]
I just tested it, another issue is that the dragging operation still eats the event, it just renders the component disabled.

**Comment by artf** [comment]
Hey @anlumo I think you can extend the view of your custom component and override this [method](https://github.com/artf/grapesjs/blob/7791f69fb4bd7724cb9d1c52cbd22d46a256df72/src/dom_components/view/ComponentView.js#L60) (make it simply return false)
