### ISSUE TITLE
getproperty style manager not working

### ISSUE THREAD

**Issue by aryeharmon** [artf/grapesjs#361]
https://github.com/artf/grapesjs/wiki/API-Style-Manager#getproperty

**Comment by artf** [comment]
Confirmed, thanks for the catch

**Comment by MichaelKlemersson** [comment]
I was looking at the default example page and saw that sectors don't have the **id** attribute that is used
as a parameter of the function _getProperty_

![image](https://user-images.githubusercontent.com/4018735/31651583-a49235c8-b2f2-11e7-919f-28dabb71cd13.png)

After I added the attribute, I can get the property as the image below shows

![image](https://user-images.githubusercontent.com/4018735/31651777-569e2718-b2f3-11e7-807d-838d47be8d31.png)

**Comment by artf** [comment]
oops 😅  thanks @MichaelKlemersson will update the demo soon then
