### ISSUE TITLE
BUG: Inconsistent Image Selection

### ISSUE THREAD

**Issue by anlumo** [artf/grapesjs#3613]
**Version:** 0.17.19

**Are you able to reproduce the bug from the demo?**

 - [X] Yes
 - [ ] No

Reproducible [here](https://grapesjs.com/demo.html).

**What is the expected behavior?**

Selecting images in the asset manager interface by clicking on them.

*Describe the bug **detailed***

**What is the current behavior?**

When you change the asset associated with an image component, it's a single click to change it, then you can close the dialog by clicking on the X icon.

When you want to change the asset associated with a `background-image` style, a single click does not change anything, it only selects the asset in the dialog. You have to double-click it to change the `background-image`, which then also closes the dialog.

These two situations should behave the same.

**Comment by artf** [comment]
Sounds legit, will be updated in the next release
