### ISSUE TITLE
BUG: text in text component cannot update , cannot get final result from toHTML

### ISSUE THREAD

**Issue by onmagic** [artf/grapesjs#3615]
it is text component,

if select body, the text will correct save/apply/store in component toHTML method,

if just updating text, but not leave the text component, just click save

then use "editor.getHTML()", the result is not updated.

![Snap77](https://user-images.githubusercontent.com/6985829/125385798-c8b46b00-e3cd-11eb-99e3-53b7b915672b.jpg)

**Comment by v-pasha2** [comment]
Did you get a solution on this ?

**Comment by v-pasha2** [comment]
We are facing below issue with version "0.17.19" where as on version "0.14.62" its was working fine.

We were trying inline editing experience, So when we check the component.getEl() function it returns the updated text for component where as if we use component.toHTML() it returns old value not the updated value. While focus is still on text component.

reference HTML.


**toHTML() out put**
<div id="i8h4tu"><p id=\"iwcefk\">This website uses sample data for illustration purposes. You can build pages using multiple templates available.</p></div>

**getEl() - OutPut**
<div id="i8h4tu"><p id="iwcefk">This website uses sample data for illustration purposes. You can build pages using multiple templates available. Text Updated</p></div>

**Comment by v-pasha2** [comment]
@artf could you please check on this or any-work around for this ?

**Comment by onmagic** [comment]
I have tried: 0.14.62, it works fine,

I got that the new version is updated (v0.17.22) , but didn't see the above problem is fixed, I hope it could fix soon.

Thanks so much.

**Comment by artf** [comment]
Yeah, it actually worked before but then I had to remove it as it was generating a lot of trouble. I need to find a better place and the right moment when to sync the view with the model without creating those issues I've seen before.
Anyway, when you need to have the model updated, when the RTE is enabled, you have to sync manually.
```js
const textCmp = editor.getEditing(); // Returns the Component enabled in rich text editing mode
textCmp && textCmp.trigger('sync:content', { noCount: true });
// your action, with text component updated...
```

**Comment by mihir-khandekar** [comment]
@artf any suggestions to make this work when RTE is not enabled?
