### ISSUE TITLE
How to create custom link components that prompts users to type link/choose link similar to Images Component Modal

### ISSUE THREAD

**Issue by edwardjiawei** [artf/grapesjs#362]
Image Components have logic to call Modal and prompt user's interaction for options/configuration of image url.

![images](https://user-images.githubusercontent.com/23583324/31067382-2cf5a39c-a785-11e7-986c-bae9c705878f.PNG)

Would like to do similar to link components for link URL.
It might be convenient for other components like Form components for business users to drag and type information in single flow.

How to achieve that, and the related handler in the codebase?

**Comment by daniel-farina** [comment]
I'm also looking in to this trying to get familiar with the code. Once we figure it out we could make some plugins a lot more powerful.  Please let me know if you figure it out.  We should make a little manual for it.

**Comment by artf** [comment]
Hi guys try to check out this #286

**Comment by edwardjiawei** [comment]
Sound good enough for my case. I have similar intention with #286 

```
      var dynamicValue;
      model.set('content', dynamicValue);
```

**Comment by artf** [comment]
Great, I close this then

**Comment by edwardjiawei** [comment]
Actually I having issues for doStuff (#286) not get called if I adding to view in my [placeholders plugins] (src/components.js)(https://github.com/edwardjiawei/grapesjs-plugin-placeholder). 

Can you help me to look into the _design.html_ that wired them up together. But I have trouble to filter out which is the **custom text/TextPlaceHolder (grapes-plugin-placeholder) and which is the text components (grapes-blocks-basic)**. Maybe also guide/code the custom link block and change the dropdown field to text input (For allows users to type their link in one flow).

I guess I doing something wrong in the plugins, can you help?

src/blocks.js
`blocks.js
 editor.on('block:drag:stop', function(model) {
  //if I change the type in block contents: {type: 'custom-type', content: 'text', activeonrender:1}, the text changes according to prompt but only after page refresh (how to initiate refresh manually?)
   if(model.attributes.type == 'custom-type' || model.attributes.type =='text' ){
     model.setContent('promptValue')
     //refresh
`

**Comment by artf** [comment]
I'd avoid doing this with the `block` event listener, custom component is the way to go.
Your doStuff is not working just because you didn't tell when to trigger it. You're missing this in your component view (components.js):
```js
...
view: defaultView.extend({
      events: {
        'click': 'handleClick'
      },
      
     init() { 
       // The 'active' is triggered by the 'activeOnRender' you've used inside your block
       this.listenTo(this.model, 'active', this.doStuff);
     },

     doStuff() {...}
     ...
```

**Comment by krunal039** [comment]
@edwardjiawei  @daniel-farina any luck with  above? I am also looking for sample

**Comment by edwardjiawei** [comment]
@krunal039 
See my plugins and how to use it / create it, no much extra than the how to create components in Wiki. No cleanup and might got some bad practice. 

https://github.com/edwardjiawei/grapesjs-plugin-placeholder/commit/da55a2fad7b8ec757e0512d0f3b61eb8cc324ca0

**Comment by krunal039** [comment]
@edwardjiawei thanks for quick reply but I still struggle can you please point to specific code/line and I can have look?

**Comment by telliott22** [comment]
I've created a modal allows the user to input their href and link text, but how do I update the model?

If I use jQuery it only updates the view, and doesn't save the changes. If I create a new component with the new values, it's inserted outside of the parent element. 

Am I missing a trick here?

Thanks,
T

**Comment by artf** [comment]
@telliott22 
```js
const model = editor.getSelected();
model.setAttributes({href: ...});
...
```
