### ISSUE TITLE
BUG: SetComponent() encodes anything in <script> tags 

### ISSUE THREAD

**Issue by jamesshin5** [artf/grapesjs#3620]
When loading in HTML through setComponent, quotation marks turn into "&quot" and less than signs turn into "&lt".

Any help would be greatly appreciated!

**Comment by artf** [comment]
Thanks @jamesshin5 that will be fixed in the next release.

**Comment by jamesshin5** [comment]
thanks so much for this! when do you think the next release will be? I did a workaround of just adding a component with script to canvas but want to change back asap

**Comment by artf** [comment]
I hope really soon but can't tell the exact day. In case it might be useful, we auto-tweet new releases on our twitter account: https://twitter.com/grapesjs

**Comment by jamesshin5** [comment]
Thanks artf, the script tag content isnt being encoded anymore. 

but when I use setComponent or the import button to import script, it isn't reflected on the canvas ie. if I have a component that requires some script like a tabs view, if i import that html and js with setComponent(), the tabs are not working / switching the view. 

When exporting this html/js it works perfectly fine, is there something I should be doing so that imported script is in effect inside the canvas. acceptScript is already true

**Comment by artf** [comment]
@jamesshin5 that will be fixed in the next release
