### ISSUE TITLE
BUG: I18n functionality

### ISSUE THREAD

**Issue by ronaldohoch** [artf/grapesjs#3622]
**Version:** latest

**Are you able to reproduce the bug from the demo?**

 - [] Yes
 - [X] No

**What is the expected behavior?**
to editor.I18n.setLocale("es") work in runtime.

*Describe the bug **detailed***
I don't know if it's a bug or it's not supposed to work this way, also, i don't know backbone enough to know if it's possible, but, when use editor.I18n.setLocale("es") on run time, it doesn't change the labels.

**What is the current behavior?**
It's just set the locale internally, but not change the labels at runtime.

*Describe the bug **detailed***  
- I created a new plugin to pass the localization files
```
import cookie from './cookie';

import pt from './i18n/pt';
import es from './i18n/es';

export default (editor, opts = {}) => {
  let login_language = cookie.get("login_language");
  let language = "";
  switch(login_language){
    case "en_US": language="en"; break;
    case "es_AR": language="es"; break;
    default: case "pt_BR": language="pt"; break;
  }

  const options = { ...{
    i18n: {},
    // default options
  },  ...opts };

  var I18nManager = editor.I18n;

  // Load i18n files
  I18nManager && I18nManager.addMessages({
    ...options.i18n,
    pt,
    es
  });
  
  //change editor localization
  I18nManager.setLocale(language);
};
```
- On first load, got the current locale, set right on portuguese.
- ![image](https://user-images.githubusercontent.com/2287371/125684313-66080d6a-1c8d-42b0-b75e-55922309eb62.png)
- On set to spanish, it keeps the portuguese on first run:
- ![image](https://user-images.githubusercontent.com/2287371/125684454-4ada8711-f776-4e26-88be-0626eeacf9bb.png)
- If i change the tab, it set the messages to spanish:
- ![image](https://user-images.githubusercontent.com/2287371/125684564-a0ae0629-aaa6-4c20-8d0f-5fee0b9ea11a.png)
- And if i set it to en, we have 3 language set:
- ![image](https://user-images.githubusercontent.com/2287371/125684659-76f3dc80-8811-44bf-a59b-26836fbad456.png)
- Here the 3 languages
- ![image](https://user-images.githubusercontent.com/2287371/125684778-38024354-6931-4d18-b59e-93422c2b239f.png)

Of course, the plugin works, if user is es, pt or en, it's setup properly.
But when we will set up a new editor with plugins, we can't change the labels, or i don't know how 🤔 (This is why i've created this PR: https://github.com/artf/grapesjs-blocks-basic/pull/38)

**Comment by artf** [comment]
Yeah, unfortunately, at the moment the UI is not updating on locale changes, so you would need to rerender the editor.

**Comment by ronaldohoch** [comment]
Well, i don't know if backbone have template binding, so i'll close for a while..

**Comment by leonardolima99** [comment]
> Yeah, unfortunately, at the moment the UI (once rendered) is not updating on locale changes, so you would need to rerender the editor.

Has this not been solved yet? I tried to use editor.render(), it works, but it duplicates the panels...

**Comment by padcom** [comment]
This issue is not solved. It needs to be reopened. Setting the locale only works when initializing the editor.

**Comment by aliozinan** [comment]
The problem still persists and the issue is still closed. When I use `editor.render()` I'm losing the custom plugins that I load during `grapesjs.init(...)`. `editor.refresh()` doesn't help either. I can see that the editor gets the updated language in the browser console, but the changes are not being reflected to the UI.

The issue needs to be re-opened and I'm looking forward to a solution / or I'll try to provide one if I can
