### ISSUE TITLE
How to load dynamic content in the final HTML file?

### ISSUE THREAD

**Issue by anuragk15** [artf/grapesjs#3631]
I looked everywhere, including the issues section and tried a few things. But really unsure how to load dynamic content in my components always(not just when i export or save it via editor).

I want to include a script in my grapejs component that always fetches content from web and updates the components.
For example, when I write  a blog and store them in my database. Now whenever someone visits my landing page(made with Grapesjs) I want them to see my latest blog there.  I don't want to rebuild my grapejs page via the editor manually.

Also, if some end-user comes to site, I will just have to send the Grapejs html and css right? no components?

Sorry if its a noob question or someone already answered it previously.

**Comment by stf1981** [comment]
I think you search for component related javascript -> https://grapesjs.com/docs/modules/Components-js.html#component-related. This js code is embedded in the html output.

**Comment by anuragk15** [comment]
> I think you search for component related javascript -> https://grapesjs.com/docs/modules/Components-js.html#component-related. This js code is embedded in the html output.

So every time the component loads, it will load the data dynamically via the JS script? Also for the end users i just have to return the html+cas generated by the grapesjs right?

**Comment by stf1981** [comment]
> So every time the component loads, it will load the data dynamically via the JS script?

Yes

> Also for the end users i just have to return the html+cas generated by the grapesjs right?

Yes, the JS script from the component is in the html, see `editor.getHtml()`

**Comment by anuragk15** [comment]
Thanks for answering.
I managed to load dynamic data into my components on render in grapesjs editor by reading docs and then following @artf example https://jsfiddle.net/fcsa6z75/7/  which is shared on https://github.com/artf/grapesjs/issues/1731 . 

I still can't find a way to load fresh data into components when the user gets the final HTML+CSS files. I can load the script via the model defaults property(if thats the correct approach) but i dont know how to access the component HTML and inject new content. Perhaps a short example might help.

**Comment by anuragk15** [comment]
Figured it out. I was trying to use props passed down in scripts. But the scripts are bound to the element and isolated so outside variable arent allowed.
