### ISSUE TITLE
Custom block icon

### ISSUE THREAD

**Issue by mingxin-yang** [artf/grapesjs#3637]
I want to custom block icon, I found the code:
```
.gjs-f-text::before {
    content: "o";
}

.gjs-fonts::before {
    display: block;
    font: normal normal normal 14px font3336;
    text-rendering: auto;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
    font-size: 5em;
}
```
how to find the `content` for I want?
![](https://raw.githubusercontent.com/mingxin-yang/images/master/Snipaste_2021-07-23_16-46-52.png)

**Comment by artf** [comment]
Hi @mingxin-yang you can read [here](https://grapesjs.com/docs/modules/Blocks.html) how to create and update Blocks.
In case you need to update an icon/label of the Block, you can do something like this:
```js
editor.Blocks.get('BLOCK-ID').set({ 
 label: 'My block', 
 media: '<svg...', // eg. your svg image
})
```
