### ISSUE TITLE
FEAT: browser unresponsive

### ISSUE THREAD

**Issue by sandeepchandc2c** [artf/grapesjs#3643]
I've converted the 11MB pdf file to Html and then load this html to grapesjs, for small size html it is working fine but for large size it is making my browser unresponsive.
what should I do so, grapesjs can load this complete html without making my browser unresponsive.
![ui](https://user-images.githubusercontent.com/69236359/126950515-025b1f33-bd6a-47c0-a5bb-2928b8953d6c.PNG)

**Comment by artf** [comment]
Share the HTML file to load so we can actually understand what is happening
