### ISSUE TITLE
BUG: link showing as span when getHtml() called

### ISSUE THREAD

**Issue by NoumanAhmad-Braqsol** [artf/grapesjs#3644]
Hi , @artf
I using CKEDITOR for add link into selected text it is working fine . i am using this code to add link
```
            var style = new CKEDITOR.style( { element : 'a', attributes : attributes } );
             style.type = CKEDITOR.STYLE_INLINE;
             style.applyToRange(range,this.linkData.editor)
```
![asdasd](https://user-images.githubusercontent.com/72378934/127009758-7803aa7f-832d-4f2d-ab3f-a84d4bba252a.PNG)

it is showing as the above 
also if i inspect the src it show a link in dom as blow
![sdsd](https://user-images.githubusercontent.com/72378934/127009932-7f3c5a44-d17d-4160-ac94-6445668760f0.PNG)

but when i getHtml() of component is show it as a span tag
![zxc](https://user-images.githubusercontent.com/72378934/127010076-dd0b91cc-d1f7-4e03-8c2c-74229d8a58be.PNG)

Why this happen . And how to resolve this issue . Please let me know . Thank you

**Comment by artf** [comment]
@NoumanAhmad-Braqsol please follow the issue template when you open bug (indeed this is not a bug in the core but might be related to your ckeditor configuration), otherwise open a new Discussion
