### ISSUE TITLE
BUG: The form button name changes are not getting captured in generated html code

### ISSUE THREAD

**Issue by TRIGGEREDcoder** [artf/grapesjs#3655]
**Version:**
Version 0.17.19(grapesjs)
Version 0.1.11(grapesjs-preset-webpage)

**Are you able to reproduce the bug from the demo?**
 - [ ] No

**What is the expected behavior?**
If I change a button name by changing the text in Component Settings for the button. The change should reflect in the Canvas as well as the html code in code view.

*Describe the bug **detailed***
I drag a form component on the canvas.
Select the button tab, go to component settings.
chose the button type and change the text.
The button text changes on the screen and the button type also changes on the view code html but the button name is nowhere reflecting at all.

**What is the current behavior?**
The button label changed is no where reflecting in the html code.

**Are you able to attach screenshots, screencasts or a live demo?**
 - [ ] Yes (attach)
As on codebox, grapesjs-preset-webpage plugin is not getting imported, I am not able to create a demo but I will share some screenshot from the actual grapesjs canvas where I am developing.
In the first, I have shown the component settings.
In the second picture, I have shown the html code generated from view code, where both the buttons are labelled as Send.
![image](https://user-images.githubusercontent.com/43340158/127623675-95fa86d6-6764-4bfc-94d0-7d55fced2295.png)
![image](https://user-images.githubusercontent.com/43340158/127623772-2db763a5-843b-4dca-a0c3-3af426fe07f2.png)

**Comment by artf** [comment]
Hi @TRIGGEREDcoder there is an issue with the preset webpage plugin which references the old form plugin containing the bug. So, I'm closing this one as it's not part of the core and will update the plugin reference soon.
