### ISSUE TITLE
BUG: How to update src of video tag at dynamically?

### ISSUE THREAD

**Issue by san-123** [artf/grapesjs#3657]
Hi @artf ,

     I have drag and drop multiple video tag same page and each one generated random number to ID attributes.
Two things doubt,
 
Frist one is that  I tried updated sample  video path to  src video tag  based on Id attribute but not working for me.
 How to update src to video tag based Id attribute?

Second one is that style manager issues,

 style manager working with image tag,

added inline styles  ex : .rt123{Height:120px;Width:200px;} for image .rt123 is id attribute.

For video tag, Id attribute is randmID , so style manager not applied to video tags. How to change this.

**Comment by artf** [comment]
@san-123 please follow the issue template and create a reproducible demo because it's hard to understand what is wrong here
