### ISSUE TITLE
Responsive content

### ISSUE THREAD

**Issue by dmodules** [artf/grapesjs#366]
Hi @artf , is grapejs suppose to support responsive? 

Thanks!

**Comment by daniel-farina** [comment]
@dmodules dmodules, 

I believe that's completely up to you. You could for example use bootstrap in your templates if you wanted to. I think @artf made it abstract enough for anyone to use it with any css framework. 

Dan

**Comment by artf** [comment]
nothing to add, thanks @daniel-farina

**Comment by dmodules** [comment]
Thanks for this answer!




<https://mailtrack.io/> Sent with Mailtrack
<https://mailtrack.io/install?source=signature&lang=en&referral=mcote@d-modules.com&idSignature=22>

*---*

*Martin Côté, Directeur technologique*
D-Modules.com <http://www.d-modules.com>
Bureau: (418) 613-0825
*Skype: martyman01*



*Agence d'inbound marketing*


2017-10-03 8:21 GMT-04:00 Artur Arseniev <notifications@github.com>:
