### ISSUE TITLE
FEAT: style manager text type

### ISSUE THREAD

**Issue by aliibrahim123** [artf/grapesjs#3662]
grapesjs style manager has so many nice features,
but it does not have a text property type,
so why do not add it

**Comment by aliibrahim123** [comment]
hallo
i made a simple text proporty type
this is the code

styleManager.addType('text', {
   create({ props, change }) {
     const el = document.createElement('div');
     el.innerHTML = '<input type="text" class="my-input" />';
     const inputEl = el.querySelector('.my-input');
     inputEl.addEventListener('change', event => change({ event })); // change will trigger the emit
     inputEl.addEventListener('input', event => change({ event, complete: false }));
     return el;
   },
   emit({ props, updateStyle }, { event, complete }) {
     const { value } = event.target;
     const valueRes = value;
     
     updateStyle(valueRes, { complete });
   },
   update({ value, el }) {
     el.querySelector('.my-input').value = value;
   },
   destroy() {
    
   }
});

**Comment by artf** [comment]
@aliibrahim123 if you don't specify any type, the text one will be created :)
