### ISSUE TITLE
BUG: Default styling properties are not being re-selected when switiching devices 

### ISSUE THREAD

**Issue by MrNikolovski** [artf/grapesjs#3663]
Hi,

Default styling properties are not being selected when switching devices.

Steps to reproduce:
Open [http://grapesjs.com/demo.html]
Select any block and observe the default values. For example, under General, Position is set to "static".
Switch to Mobile.
Change the Position to "relative".
Switch back to Desktop, observe the Position is set to "relative" and not "static".

I expect when we switch the device if nothing was selected to show/select the default value.

I have a short video of the problem.
https://user-images.githubusercontent.com/12418977/127947367-b972400f-85fd-4bfb-a82b-1a3e5b572345.mp4

**Comment by MrNikolovski** [comment]
Hi @artf. Can I get an update on this issue? Do you consider this as a small issue or you didn't have time to work on it? 
Thank you.

**Comment by artf** [comment]
I'm working on the StyleManager improvement at this moment, and probably I will be able to check this soon.

**Comment by Galant96** [comment]
Hi! Great work, @artf! It's handy stuff. Are there any updates on this, or when can we expect them to be done?

**Comment by artf** [comment]
This issue is fixed in https://github.com/artf/grapesjs/releases/tag/v0.18.1
