### ISSUE TITLE
QUESTION:  How to publish layout generated via GrapesJS

### ISSUE THREAD

**Issue by codingmachine16** [artf/grapesjs#3664]
Hi @artf 

Our GrapesJs editor is running on 
http://localhost:5500/editor

![image](https://user-images.githubusercontent.com/87995581/128018584-1ba2bc43-aeca-4e14-90dd-7bb986816072.png)

We want to publish it on front end on 
http://localhost:5500/

But on front end , the panels are showing and edit mode is on. How to disable edit mode and hide panels

![image](https://user-images.githubusercontent.com/87995581/128018838-f0128973-0a49-4092-b91f-1975577c1f1a.png)

**Comment by artf** [comment]
I'm closing this one as you have already opened the discussion here https://github.com/artf/grapesjs/discussions/3666
