### ISSUE TITLE
BUG: Cant Reset Canvas after Moving/scaling it

### ISSUE THREAD

**Issue by anatoli-dp** [artf/grapesjs#3668]
## WARNING
READ and FOLLOW next 3 steps, then REMOVE them before posting the issue

1. Follow CONTRIBUTING Guidelines https://github.com/artf/grapesjs/blob/master/CONTRIBUTING.md
2. Do a quick SEARCH first, to see if someone else didn't open the same issue
3. All relative statements/questions have to be filled/answered, otherwise, the issue might be CLOSED
4. JSFiddle Starter template https://jsfiddle.net/szLp8h4n
5. CodeSandbox Starter template https://codesandbox.io/s/1r0w2pk1vl

**What are you trying to add to GrapesJS?**
a way to reset the canvas back to its default position after it has been scaled and moved.
*Describe your feature request **detailed***
after scaling and then moving the canvas you can create a function that will resize and move the canvas back into position but when u scale/move it again it jumps back to the old position u had before centering it. so if u had it way off screen it would cause the canvas to jump back to the area instead of moving it according to its current location. If there is a way to reset the canvas let me know otherwise please. this is really annoying me and i cant figure it out.
**Is there an alternative at the latest version?**

 - [ ] Yes (describe the alternative)
 - [ x] No

**Is this related to an issue?**

 - [ ] Yes (Give a link to the issue)
 - [ x] No

this is unrelated but is there a function that can be called to zoom the content not the canvas? so like if i want to scale it like if it were on some really high dpi page to be able to do edits better. or should this be done by manually scaling the iframe zoom? cause iframe zoom in would of course enlarge the tools/selection outline

**Comment by artf** [comment]
I'm not sure if I understand your issue, how do you exactly move/scale the canvas? 

> this is unrelated but is there a function that can be called to zoom the content not the canvas? so like if i want to scale it like if it were on some really high dpi page to be able to do edits better. or should this be done by manually scaling the iframe zoom? cause iframe zoom in would of course enlarge the tools/selection outline

[`editor.Canvas.setZoom`](https://grapesjs.com/docs/api/canvas.html#setzoom) doesn't work in your case?

**Comment by anatoli-dp** [comment]
i scale it using the editor.Canvas.setZoom and move it using spacebar. atm i removed what i did but it was something like getting the canvas element and just positioning it with a style update. however this change isnt permanent and as soon as it is slightly moved it jumps back to the original position. is there a function that will reset the canvas position back to the center of the view and rescale it to 100%?

**Comment by artf** [comment]
If you're talking about the moving coordinates, we don't have yet a direct API for that, but you can actually get/update them in this way:
```js
const canvasModel = editor.Canvas.getModel();
// Get values
const { x, y } = canvasModel.attributes;
// Update values
canvasModel.set({ x: x + 50, y: y + 50 })
```

**Comment by anatoli-dp** [comment]
allright that should be good enough for what i want

**Comment by artf** [comment]
Great, I'll add `canvas.getCoords` and `canvas.setCoords` methods in the next release.
