### ISSUE TITLE
Community - Open collective & Discord.

### ISSUE THREAD

**Issue by daniel-farina** [artf/grapesjs#367]
Hi Artur/guys, 

I'm proposing the following ideas: 

1. Open a discord channel or slack (Discord is taking over) to discuss off topic things related to Grapejs. 
2. Contribute to this project via [Open Collective](https://opencollective.com/grapesjs). I just became the first monthly backer, I'm sure other people can contribute a few bucks per month to pay for all the time Artur and fellow developers have invested.

This project has a lot of potential and I see it growing a lot with in the next few months. I was a little confused with the decision of using Backbone instead of other modern alternatives but it turns out Backbone was a great choice if not the best choice.

Grettings from USA!

**Comment by artf** [comment]
WOW 😮  thanks @daniel-farina this is huge, I really appreciate your words and really grateful for your support on Open Collective, this means a lot ❤️ ❤️ ❤️ 
I'll open a Discord channel soon

**Comment by daniel-farina** [comment]
No problem, 
Looking forward having a channel on Discord for GrapeJS.  I really hope more people that will benefit from this code participate on Open Collective. 

Cheers

**Comment by artf** [comment]
Discord channel created :)
[![Chat](https://img.shields.io/badge/chat-discord-7289da.svg)](https://discord.gg/QAbgGXq)

**Comment by daniel-farina** [comment]
Great, 

I just joined. 

Dan

**Comment by adamlc** [comment]
I know a lot of developers use [Gitter](https://gitter.im/) too, might be worth looking at.
