### ISSUE TITLE
BUG: Invisible webcomponents

### ISSUE THREAD

**Issue by sriya-srinivasan** [artf/grapesjs#3674]
**Version:**
0.17.19

**What is the current behavior?**
That the added webcomponent is visible:

When adding web components inside grapesjs container, the component is empty/blank, if the component has elements in the shadow DOM. (If not using shadow dom to create components there is no issue.) It is visible in layer manager, but empty

![Issue1](https://user-images.githubusercontent.com/78800503/128315538-ae05c799-9a0f-402d-a74c-b001fa2ad03c.PNG)

Here we can see the diffrence between the element inside and outside. The shadow root is not visible.

**What is the expected behavior?**
The webcomponent inside grapesjs canvas needs to be rendered and look similar to the one outside, on top of the editor. 

**Are you able to attach screenshots, screencasts or a live demo?**
 - [x] Yes (attach)
 - [ ] No

![Issue2](https://user-images.githubusercontent.com/78800503/128315544-5ccde5a9-b57b-407f-a68a-f8154256f39f.PNG)

This is the error in the console.

**Comment by artf** [comment]
Hey @sriya-srinivasan can you create a reproducible demo, please?

**Comment by sriya-srinivasan** [comment]
Like on js-fiddle or sandbox?

**Comment by artf** [comment]
@sriya-srinivasan any update please?

**Comment by sriya-srinivasan** [comment]
Yeah Im trying but its proprietary code, so it'll take a while to create and include a similar component. But it is related to [this issue](https://github.com/artf/grapesjs/issues/3693). They are using a component created in plain JS, the one we are working on is using lit-element.

**Comment by artf** [comment]
Posted a workaround here https://github.com/artf/grapesjs/issues/3693

**Comment by sriya-srinivasan** [comment]
This is related to lit-element version update.
Link to the issue [here](https://github.com/lit/lit/issues/2068).

**Comment by sriya-srinivasan** [comment]
Here is the [link](https://codesandbox.io/s/musing-grothendieck-9hved?file=/src/components.js) to a reproducible demo.

**Comment by GaikwadShubham** [comment]
@artf do we need to reopen this issue?

**Comment by artf** [comment]
hey guys, from what I see, is more like an issue related to lit 3, which doesn't allow the reuse of web components across same-origin iframes, am I right? In that case, not being a user of the framework I'd ask you to let me know if there is anything I can do.

ps. being an issue with an external framework, I'd keep the issue closed

**Comment by GaikwadShubham** [comment]
Hi @artf , is there any way we can define the element in iframe as the author of lit had [suggested](https://github.com/lit/lit/issues/2068#issuecomment-906671997)

**Comment by artf** [comment]
@GaikwadShubham you might use `canvas.scripts` option to load external scripts in the iframe but as Web Components are supposed to work across same-origin iframes, I'm not sure is the right approach.
