### ISSUE TITLE
POST/GET all the three fields

### ISSUE THREAD

**Issue by mekamleshk** [artf/grapesjs#368]
Hi,

I am trying to store and retrieve data in/from database using below fields :
1) Template Name
2) Template Data
3) Status

The question I have is urlStore/urlLoad is only sending/retrieving Template Data

Is there any way I can POST/GET all the three fields ? @artf  @cmcintosh

**Comment by arthuralmeidap** [comment]
@mekamleshk You have to do in a custom way. Using the GrapesJS Api you can achieve this

**Comment by mekamleshk** [comment]
@arthuralmeidap  Can you throw some lights on it, Like a example or something

**Comment by arthuralmeidap** [comment]
@mekamleshk,
  This (API-Editor)[https://github.com/artf/grapesjs/wiki/API-Editor] has a lot of methods. 
  One of them is getComponents that you can get the data from inside the grapes or getStyle that you can get style data used for the page
  You will need to customize in some how to achieve what you want..

**Comment by daniel-farina** [comment]
Are you sure it's only sending the template?
When I do it its sending all of them. Check your chrome headers, all the way down on Request Payload:

![image](https://user-images.githubusercontent.com/13665117/31160043-52afe5ae-a89b-11e7-89b1-b36465fcc6e8.png)

**Comment by mekamleshk** [comment]
@arthuralmeidap @artf @cmcintosh

I am trying to edit a existing template in the database,

I am unable to send the template data and id to the view 

`  var id = '<?php echo $this->uri->segment(4); ?>';

       var editor = grapesjs.init
           ({
             height: '100%',
              container : '#gjs',
              plugins: ['gjs-preset-newsletter'],
          storageManager:
          {
            type: 'remote',
            autosave: false,
            //urlStore: 'dragdrop/edit/id',
            urlLoad: 'dragdrop/edit/id',
            contentTypeJson: true,
          },
        });

      editor.Panels.addButton
          ('options',
            [{
              id: 'save-db',
              className: 'fa fa-floppy-o',
              command: 'save-db',
              attributes: {title: 'Draft'}
            }]
          );

        // Add the command
      editor.Commands.add
        ('save-db',
        {
          run: function(editor, sender)
          {
            sender && sender.set('active'); // turn off the button
            editor.store();
            alert('Draft');

            //   editor.on('storage:load', function(e) {
            //       console.log('Loaded ', e);
            // });

            // editor.on('storage:store', function(e) {
            //       console.log('Stored ', e);
            // });         
          }
      });
`

I have this structure in my db :

**Comment by mekamleshk** [comment]
`<table style="width:100%">
  <tr>
    <th>Firstname</th>
    <th>Lastname</th> 
    <th>Age</th>
  </tr>
  <tr>
    <td>Jill</td>
    <td>Smith</td> 
    <td>50</td>
  </tr>
  <tr>
    <td>Eve</td>
    <td>Jackson</td> 
    <td>94</td>
  </tr>
</table>`

**Comment by artf** [comment]
I think it's legit you're not able to send if you comment `urlStore`
```js
type: 'remote',
autosave: false,
//urlStore: 'dragdrop/edit/id',
urlLoad: 'dragdrop/edit/id',
contentTypeJson: true,
```
and then fix your url strings
`'dragdrop/edit/id' - > 'dragdrop/edit/' + id`

**Comment by mekamleshk** [comment]
Thanks @artf

**Comment by asadpstu** [comment]
I'm confused why mine is not working.
![Capture](https://user-images.githubusercontent.com/10845009/61646815-5036da00-acde-11e9-9748-072ada2e9fa4.PNG)
