### ISSUE TITLE
BUG: Textable not working with extended text component

### ISSUE THREAD

**Issue by Joshmamroud** [artf/grapesjs#3681]
**Version:**
0.17.22

**Are you able to reproduce the bug from the demo?**

 - [X] Yes
 - [ ] No

**What is the expected behavior?**
Should be able to drop a textable element into a custom component that extends the text component

**What is the current behavior?**
Can't drop a textable component into a custom component that extends a text component

**Are you able to attach screenshots, screencasts or a live demo?**
[Demo](https://codesandbox.io/s/compassionate-andras-8h8m4?file=/index.js)
 - [X] Yes (attach)
 - [ ] No

**Comment by artf** [comment]
Hey @Joshmamroud there is actually a general issue about textable components here #2771

**Comment by Joshmamroud** [comment]
Thanks, @artf. I think my problem here is more so the custom component that extends the Text component. Textable works as expected with the original Text component but when I try to create my own, custom text component that's where I run into issues. It's not just with textable either, I've noticed that an extended text component loses some other functionality as well. I can't think of specifics off the top of my head right now. Is there something that I'm doing wrong in way that I'm extending the text component?

**Comment by artf** [comment]
From your demo, I don't see issues with the extended `text` component, but only those related to textable

**Comment by Joshmamroud** [comment]
@artf when you drag and hover the textable component over the Text component it shows the cursor in the text where the textable component will be placed. In the custom text component it doesn't even give you the Upton to drop. In my implementation (not the demo) I have an extended text component and when I drop a textable component into it, it only always me to drop it in the beginning or end of each line.

**Comment by artf** [comment]
thanks @Joshmamroud but, right now, it doesn't make sense to investigate more about this until the general textable bug is fixed. If you believe there is an issue with extending the text component itself then I'd ask you to create a new issue with a reproducible demo
