### ISSUE TITLE
How to set the component cannot be deleted

### ISSUE THREAD

**Issue by mingxin-yang** [artf/grapesjs#3683]
![image](https://user-images.githubusercontent.com/23076937/128685747-37b8bdf2-16f0-47bc-b5f6-cb96bbbfefdf.png)

**Comment by artf** [comment]
I'd suggest creating a custom Component with `removable` property set to `false`

**Comment by mingxin-yang** [comment]
https://grapesjs.com/docs/modules/Components.html#define-custom-component-type , this ? @artf

**Comment by mingxin-yang** [comment]
Another problem is a text control, how to edit the text when selected, instead of double-clicking to edit it like now? @artf

**Comment by mingxin-yang** [comment]
There is a bug here, https://grapesjs.com/demo-mjml.html, when editing text with only one line of text, the second click, the edit box will cover the text @artf

**Comment by artf** [comment]
> Another problem is a text control, how to edit the text when selected, instead of double-clicking to edit it like now?

You can change component content in this way `editor.getSelected().components('My text')`

> There is a bug here, https://grapesjs.com/demo-mjml.html, when editing text with only one line of text, the second click, the edit box will cover the text

That should be fixed in the next release

**Comment by mingxin-yang** [comment]
![232](https://user-images.githubusercontent.com/23076937/128987782-9080d67d-ec9b-4d7a-a8fc-2024aada16fc.gif)

**Comment by artf** [comment]
To enable rich text editor on one click, you can extend the original text component in this way
```js
editor.Components.addType('text', {
    view: {
      events: {
        input: 'onInput', // Preserve the original on input event which updates RTE toolbar position
        click: 'enableRte',
      },
      enableRte() {
        this.onActive()
      }
    },
});
```

**Comment by mingxin-yang** [comment]
Thank you for your patience. I have another question. How to make the height of the canvas change with the content. Because my block is placed under the canvas, I added `height:'auto'` during initialization. , But it didn't work
```
var editor = grapesjs.init({
          container: '#gjs',
          // Get the content for the canvas directly from the element
          // As an alternative we could use: `components: '<h1>Hello World Component!</h1>'`,
          fromElement: true,
          // Size of the editor
          height:600,
          width: 'auto',
          // Disable the storage manager for the moment
          storageManager: false,
          // Avoid any default panel
          panels: { defaults: [] },

          plugins: ['grapesjs-mjml',],
        
```

@artf

**Comment by mingxin-yang** [comment]
I use gjs-plugin-ckeditor, after selecting the text, after the ckeditor edit box appears, the margin of the text will become larger, but the margin cannot be overwritten in the css. How do I set it?  
@artf

**Comment by mingxin-yang** [comment]
After using the CKEDITOR plugin in the GrapesJS-MJML project, after the box, there is a layer of p tag outside the text, the style has changed, how to set it 

@artf
