### ISSUE TITLE
BUG: Keyboard shortcuts/Keymaps not working

### ISSUE THREAD

**Issue by Joshmamroud** [artf/grapesjs#3687]
**Version:** 
0.17.22

**Are you able to reproduce the bug from the demo?**

 - [ ] Yes
 - [X] No
 
I can't reproduce it in a demo however you can see it for yourself if log into [Documint](https://app.documint.me) using the following credentials:

- **Email:** demo@documint.me
- **PW:** demo

then make a change to the template and try using `ctrl+z`

**What is the expected behavior?**
Should be able to use mapped keyboard shortcuts (ie. ctrl+z) but they don't work.

**What is the current behavior?**
The keymaps are registered but they don't work. When I run `keymaps.getAll()` I get a list of all of the default keymaps. When I listen for a keymap to be emitted I get nothing. When I add a custom keymap (eg. `alt+u`) either through the config or adding it on init it doesn't fire either. 

**I'm really at a loss. Can anyone please help?**

**Are you able to attach screenshots, screencasts or a live demo?**

 - [ ] Yes (attach)
 - [x] No

**Comment by artf** [comment]
Hey @Joshmamroud we have [this code](https://github.com/artf/grapesjs/blob/75be5144a95488e557afabeca8ae50da8e15c60a/src/canvas/view/FrameView.js#L432-L444) that propagates `keydown keyup keypress` events to the parent document, this allows keymaps to work, ensure to not contain any code/component which prevents the propagation of those events.

**Comment by Joshmamroud** [comment]
Hey @artf, I believe it may be blocked by React. Any suggestions on how to re-bind these event listeners? Not even sure if that is the right solution or path.

**Comment by artf** [comment]
Shortcuts should be binded to something like a document/window, so, if you have an element that stops their event propagation, you can't do much.

**Comment by Joshmamroud** [comment]
You were right, it wasn't React or GrapesJS. Event propagation was being stopped by the [rc-drawer](https://github.com/react-component/drawer) component I was using. @artf thanks for your help, this has been an issue from day one.
