### ISSUE TITLE
Usage from source failed

### ISSUE THREAD

**Issue by ateshuseyin** [artf/grapesjs#369]
I tried to use grapesjs from source by using `require('grapesjs/src')` to debug both my source and grapesjs. But could not success because of below issues;

- There is some requires like `require('plugin_manager')`. These can be passed by webpack config but it is not a nice solution.
- '<# VERSION #>' preprocessing should be done by git hooks, not compile time.
- There is no guide about usage from source.

I think this issue is very imported to identify the bugs of grapesjs.

**Comment by ateshuseyin** [comment]
At DevicesView.js:5 there is underscore usage w/o require: `template: _.template(``

**Comment by ateshuseyin** [comment]
I just notice that you are using ProvidePlugin. That is a solution but these kind of configurative solutions are a limitation to grapesjs users which are using from source.

**Comment by artf** [comment]
correct @ateshuseyin I just never configured it to work properly from source, indeed have to move few configurations from webpack to npm. Appreciate your help 👍
