### ISSUE TITLE
BUG: Cell hovering randomly displaces from actual cell

### ISSUE THREAD

**Issue by diegoSenra** [artf/grapesjs#3699]
Hi!

I'm using grapesJs for e-mail editing in a project in my company, with Newsletter plugin.
Everithing works very well, except for this bug i can't solve:

Sometimes, when I drag blocks inside the canvas, the cell hover gets scrambled. The biggest problem is that this behavior is completely random, it can happen or not but it's quite annoying when it does.

The only patterns are:
- Scrambles ONLY AND EXCLUSIVELY right after dropping a block in canvas
- If i resize the canvas for mobile/tablet it gets back to normal (even if turning back to desktop view - but it may happen again upon dropping new blocks)
- The displacement only occurs vertically (randomly up or down - usually up - and can be any displacement size)
- The cell options menu (select parent, move component, erase cell etc) is displaced too, in the same way.

The editor is inserted in a page with some more content (sidebar and header). I had to change the css of some editor classes to fit and look well in this page, unfortunatelly i dont remember exactly what attr i did change (although i dont think this would be the problem as it works well initially and it gets corrected if changing to mobile view).

The problem could be on my side, but I would like to know at least where could i look towards to better investigate this bug.
Any help would be appreciated!

Below, pic of hover and options menu displaced

![grapesJsBug](https://user-images.githubusercontent.com/47437190/129193454-7d4383b6-e897-492d-839e-0217f993802a.jpg)

**Comment by artf** [comment]
Are you using the latest version?

**Comment by diegoSenra** [comment]
Using minified 0.10.7

**Comment by artf** [comment]
Sorry mate, it's a 4-year-old release, can't help you here.
Did you try to update?
