### ISSUE TITLE
remove html tag from template

### ISSUE THREAD

**Issue by piyalmaduranga** [artf/grapesjs#37]
Hi @artf 
In grapesjs editor i want to remove `<img>` tag of template before save template, how can i do that ? (we can delete img tag using editor ui , but i want to remove img tag code side , is it have any function to remove tag?)
In drag and drop blockManager , can i get drop event ?

**Comment by artf** [comment]
So basically you drop the Block inside the canvas but you don't want to see it in the code, right?
About the drop event, in the next release, there will be the possibility to catch when a new component is added to the canvas but anyway, I don't think this gonna help you in this particular case.

**Comment by piyalmaduranga** [comment]
Hi @artf 
i want to remove `<img>` tag from editor.getHtml();

**Comment by artf** [comment]
@piyalmaduranga 
How do you insert that `<img>`? `getHtml()` returns simply a string, if you want you can manipulate before saving it. Anyway, can you explain me your case, because I really don't get the sense of what you're asking. 
If you don't want the `<img>` why do you drop it???

**Comment by artf** [comment]
#35
