### ISSUE TITLE
BUG: setting draggable: 'wrapper' does not drop in wrapper

### ISSUE THREAD

**Issue by anatoli-dp** [artf/grapesjs#3700]
## WARNING
READ and FOLLOW next 3 steps, then REMOVE them before posting the issue

1. Follow CONTRIBUTING Guidelines https://github.com/artf/grapesjs/blob/master/CONTRIBUTING.md
2. Do a quick SEARCH first, to see if someone else didn't open the same issue
3. All relative statements/questions have to be filled/answered, otherwise, the issue might be CLOSED
4. JSFiddle Starter template https://jsfiddle.net/szLp8h4n
5. CodeSandbox Starter template https://codesandbox.io/s/1r0w2pk1vl

**Version:**
current, i update on every release

**Are you able to reproduce the bug from the demo?**
uses custom editor as i need to make own components

 - [ ] Yes
 - [ ] No

**What is the expected behavior?**
setting a component as draggable: 'wrapper' should allow that component to only be dropped on the wrapper or root/body element

*Describe the bug **detailed***
doing so does not allow me to drop the component on anything at all, not even the wrapper as expected. however when setting it to anything but the wrapper will allow the component to be dropped only in the specified element (if i set it to section i can only drop in section components) . . . only setting to wrapper has this issue

**What is the current behavior?**

*Describe the bug **detailed***

**Are you able to attach screenshots, screencasts or a live demo?**

 - [x] Yes (attach)
 - [ ] No
![Screenshot (6)](https://user-images.githubusercontent.com/75029364/129229795-09c81a52-893f-46b5-8951-ada362767691.png)

**Comment by artf** [comment]
The string here is supposed to be a query string so it tries to query a `wrapper` tag, which obviously doesn't exist. The editor attaches `data-gjs-type` attribute to all components in the frame, so the query you can use is `draggable: '[data-gjs-type=wrapper]'`

**Comment by anatoli-dp** [comment]
ah that makes a lot more sense now . . . thanks, that solved the issue
