### ISSUE TITLE
BUG: load blocks closed by default?

### ISSUE THREAD

**Issue by throne1986** [artf/grapesjs#3704]
I am using the following bit of code to collapse all the block categories, unfortunately, this is not working 

```
const categories = editor.BlockManager.getCategories();
categories.each(category => {
	category.set('open', false).on('change:open', opened => {
		opened.get('open') && categories.each(category => {
            category !== opened && category.set('open', false)
        })
	})
})

```

live demo :  https://jsfiddle.net/d4702yoh/2/

What is wrong here?

**Comment by ronaldohoch** [comment]
Hello, i have made it to close all blocks in one plugin, try to adapt to you.:

```javascript
export default (editor, opt = {}) => {
    const Commands = editor.Commands;

    Commands.add("dina:hide-all-blocks",(editor)=>{
        editor.Panels.getButton("views","open-blocks").set("active",1);
        let categories = editor.BlockManager.getCategories().models;
        categories.map(elem=>{
            elem.view.$el.css("display","none");
        });
    })
};
```

**Comment by throne1986** [comment]
> ```js
> const Commands = editor.Commands;
> 
>     Commands.add("dina:hide-all-blocks",(editor)=>{
>         editor.Panels.getButton("views","open-blocks").set("active",1);
>         let categories = editor.BlockManager.getCategories().models;
>         categories.map(elem=>{
>             elem.view.$el.css("display","none");
>         });
>     })
> ```

still the same here jsfidle : https://jsfiddle.net/46mfqeht/

**Comment by ronaldohoch** [comment]
Hello again.
First: My code is a new command, if you want to keep it, you should run the command after all, check the gif bellow:
![runCommand](https://user-images.githubusercontent.com/2287371/129424934-2e535da6-0981-4eaa-a0a3-f6dd1131d8f9.gif)
Here you can see me running the command /\

Second: What the code do:
- Set the panel of the blocks active, so the user will see the blocks;
- - `editor.Panels.getButton("views","open-blocks").set("active",1);`
- Get the models of the category from blockManager;
- - `let categories = editor.BlockManager.getCategories().models;`
- Loop through these categories and set it to display:none;
- - 
``` javascript
        categories.map(elem=>{
            elem.view.$el.css("display","none");
        });
```

**Comment by throne1986** [comment]
> Hello again.
> First: My code is a new command, if you want to keep it, you should run the command after all, check the gif bellow:
> ![runCommand](https://user-images.githubusercontent.com/2287371/129424934-2e535da6-0981-4eaa-a0a3-f6dd1131d8f9.gif)
> Here you can see me running the command /\
> 
> Second: What the code do:
> 
> * Set the panel of the blocks active, so the user will see the blocks;
> * * `editor.Panels.getButton("views","open-blocks").set("active",1);`
> * Get the models of the category from blockManager;
> * * `let categories = editor.BlockManager.getCategories().models;`
> * Loop through these categories and set it to display:none;
> * 
> 
> ```js
>         categories.map(elem=>{
>             elem.view.$el.css("display","none");
>         });
> ```

ok thanks, can you please check also this thread? https://github.com/artf/grapesjs/issues/3702

**Comment by throne1986** [comment]
> Hello again.
> First: My code is a new command, if you want to keep it, you should run the command after all, check the gif bellow:
> ![runCommand](https://user-images.githubusercontent.com/2287371/129424934-2e535da6-0981-4eaa-a0a3-f6dd1131d8f9.gif)
> Here you can see me running the command /\
> 
> Second: What the code do:
> 
> * Set the panel of the blocks active, so the user will see the blocks;
> * * `editor.Panels.getButton("views","open-blocks").set("active",1);`
> * Get the models of the category from blockManager;
> * * `let categories = editor.BlockManager.getCategories().models;`
> * Loop through these categories and set it to display:none;
> * 
> 
> ```js
>         categories.map(elem=>{
>             elem.view.$el.css("display","none");
>         });
> ```

Hi that is not what I want , I just want by default the blocks should be closed not open or not hiding it as you do

**Comment by artf** [comment]
That should be enough `editor.Blocks.getCategories().forEach(ct => ct.set('open', false))` but categories are not created until the render of blocks (which happens, by default, when you click the Blocks tab) so you just need to execute that script once are rendered.

**Comment by throne1986** [comment]
Thanks your right
