### ISSUE TITLE
Enable the default RTE with a custom function

### ISSUE THREAD

**Issue by edwardjiawei** [artf/grapesjs#371]
Do my API call correctly, want to add a RTE with custom function to add a link/open new windows/open modal:

Command work for fontSize but the dropdown are not aligned and show the option value
Command not work for insertHTML.
Function not working (Intended/Not a Features)

![grapes](https://user-images.githubusercontent.com/23583324/31157697-42875abe-a8ef-11e7-8af7-6fdd4d2b1acf.PNG)

http://grapesjs.com/demo.html

```
  editor.RichTextEditor.add('fontSize', {
    command: 'fontSize',
    options: [
      {name: 'Huge', value: '7'},
      {name: 'Normal', value: '5'},
      {value: '1'}
    ]
  });  

```
I think even command not working to add specific hardcoded HTML
```
    editor.RichTextEditor.add('insertHTML', {
    command: 'insertHTML',
    class: 'fa fa-link',
    title: 'test',
    args: '<a class="link" href="">${content}</a>',
  });  

```

```
 editor.Commands.add('tlb', {
    run:  function(editor, sender){
      editor.getSelected().view.enableEditing();
      //sethref for link etc
      alert('Hello world!');
    },
    stop:  function(editor, sender){
    },
  });
    editor.RichTextEditor.add('tlb', {
    command: 'tlb',
    class: 'fa fa-link',
    title: 'test'
 
  });  
```

**Comment by artf** [comment]
Hi @edwardjiawei, it doesn't work because the `command: 'tlb'` in `RichTextEditor.add` it's not GrapesJS's Command but the from `execCommand`'s API (eg. 'fontSize', 'insertHTML', etc.) so currently, you can't attach custom behaviors to RTE.
I close it because I don't plan to support the current RTE anymore, instead, I'll replace it with another one which will support also custom actions (added to Roadmap)

**Comment by edwardjiawei** [comment]
Hopefully support some RTE with more permissive license like MIT or BSD. I guess some companies might even don't choose BSD. CKEditor integration are quite easy, but the license might not be good for some companies. 

Thanks anyway.

**Comment by artf** [comment]
CKEditor it's too much big for being the built-in solution (but you can find it as a plugin if you want to use it) 
I'll probably go with https://github.com/jaredreich/pell this is all its code https://github.com/jaredreich/pell/blob/master/src/pell.js and this is all I need

**Comment by edwardjiawei** [comment]
That really lightweight and permissive license.
 
You know as nowadays the open source world, most people like me always rely on plugins like insertHTML, Emoji, Unicode, PlaceHolder/Token (Server Side Templateing) that will useful for hobby project and work. All that use case are mostly align with grapes.js use case, as most personal and professional project will evaluate how easy to integrate with RTE.
