### ISSUE TITLE
Stored components with script can not be rendered properly

### ISSUE THREAD

**Issue by shkhalid** [artf/grapesjs#3713]
I am facing some problem when try to save some components which includes some scripts and reload the page the components are not rendered properly. It's showing empty boxes.
Example: When i try to save a chart component from `jvas28/grapesjs-echarts`  and reload the page i am getting this
<img width="1438" alt="Screen Shot 2021-08-18 at 4 20 43 PM" src="https://user-images.githubusercontent.com/8138036/129891078-2191094d-d735-4178-9859-588f774120b6.png">
 
Here is the example app
https://codesandbox.io/s/cranky-wescoff-93pxd?file=/src/App.js

```
storageManager: {
      autoSave: 1,
      autoload: 1,
      type: "local"
    }
```

I also tried to setup remote [storage](https://grapesjs.com/docs/modules/Storage.html). But I get the same result. Here is the api output.
<img width="1291" alt="Screen Shot 2021-08-18 at 4 35 53 PM" src="https://user-images.githubusercontent.com/8138036/129891362-534bab14-f1c6-4c58-b061-a895df35921c.png">

I think this is related to 
https://github.com/artf/grapesjs/issues/1487
https://github.com/artf/grapesjs/issues/2069
https://github.com/artf/grapesjs/issues/3535
https://github.com/artf/grapesjs/issues/3141

**Comment by artf** [comment]
Hey @shkhalid thanks for the report, but on this repository, you should open reproducible issues without external plugins as it might be an issue with the plugin itself. At least for what I can tell about the core, I see no issues in Components with JS (if correctly implemented by following this [guide](https://grapesjs.com/docs/modules/Components-js.html))

**Comment by shkhalid** [comment]
Thanks @artf!
Finally i was able to figure it out
The problems was in `tagVarStart` and `tagVarEnd`. After commenting it out it starts working
 ```
return grapesjs.init({
    // tagVarStart: '{{ ',
    // tagVarEnd: ' }}',
    .
    .
    });
```

**Comment by swapnilkhedkar-vb** [comment]
@shkhalid can u link a sandbox code for the working code, that saves script for e-charts

**Comment by swapnilkhedkar-vb** [comment]
> Thanks @artf! Finally i was able to figure it out The problems was in `tagVarStart` and `tagVarEnd`. After commenting it out it starts working
> 
> ```
> return grapesjs.init({
>    // tagVarStart: '{{ ',
>    // tagVarEnd: ' }}',
>    .
>    .
>    });
> ```
