### ISSUE TITLE
Override Drag functions

### ISSUE THREAD

**Issue by Abhisheknanda1344463** [artf/grapesjs#3718]
Hi @artf  I want to override the Drag function of ```dmode "absolute"```.
As, of now we have ability to move freely over the canvas and if move anywhere in the desktop it will not be the same in the other mobile and table device. Also It's is on pixels i want to make it in percentage to make it responsive in all the screen.
Could you please help me in this from where i can start and how could i achieve it.

Thanks

**Comment by artf** [comment]
You have to [extend](https://grapesjs.com/docs/modules/Commands.html#extending) the [ComponentDrag](https://github.com/artf/grapesjs/blob/dev/src/commands/view/ComponentDrag.js) command
