### ISSUE TITLE
Asset Manager not automatically add images to assets after uploading

### ISSUE THREAD

**Issue by deffrin** [artf/grapesjs#372]
The JSON response of an upload is like this 
{"data":["http://url.com/flower.jpg"]}

The response event is working.In the response event response is in the format of string.
Content-type is set to application/json when uploaded file.

Now I manually add image to assets in the response event.
Is there any problem in the response format I get after a file upload?

**Comment by sonnylloyd** [comment]
I have the same problem and like you i added the files manually.

**Comment by artf** [comment]
```js
typeof text === 'text' 
```
LOL
Yeah I'd say it's definitely the reason behind the bug
Would you like to PR it? :)

**Comment by sonnylloyd** [comment]
@artf thanks i have sent a PR

**Comment by artf** [comment]
Merged, soon I'll publish a new release
