### ISSUE TITLE
How to add extensions [help]

### ISSUE THREAD

**Issue by ryprfpryr** [artf/grapesjs#3726]
Please, can anyone explain in clear steps how to add extensions?

Thank you VERY much!

**Comment by artf** [comment]
Hey @ryprfpryr you can check the demo file here https://github.com/artf/grapesjs/blob/gh-pages/demo.html

**Comment by ryprfpryr** [comment]
Thanks @artf I have used the demo.html code as my index.html but the page remains blank.
Do I need to make any additional steps? Thanks again

**Comment by artf** [comment]
No additional steps are required, for sure you've missed something or left some syntax error. Check the inspector for errors.
