### ISSUE TITLE
Color input does not update the element on page

### ISSUE THREAD

**Issue by sonnylloyd** [artf/grapesjs#373]
when using the color picker everything works fine.

however if you add a hex value to the input and press enter the color preview updates but the color is not applied to the element on the page

**Comment by sonnylloyd** [comment]
@art i think the issue here is that 
```
colorEl.spectrum('set', valueClr);
```
inside function setValue(val, opts = {}) of InputColor.js does not call the change event inside spectrum. looks like it needs to be separated out.

**Comment by sonnylloyd** [comment]
@artf i have been looking at this quite a bit and managed to get it working but the way i have done it seems a little hacky.

The issue i found was inside **src\domain_abstract\ui\InputColor.js** inside   **setValue(val, opts = {})**.

 the value **opts.targetUpdate** is undefined after the second loop.

I added these, just above the IF statement and changed the variable **previousСolor** so it can be accessed by all the functions. 

```
model.set('value', valueClr);
colorEl.spectrum('set', valueClr);

if (opts.targetUpdate) {
      self.previousСolor = valueClr;
      this.noneColor = valueClr;
}
```

 again this feels a little hacky im not sure if its the correct approach.

**Comment by artf** [comment]
@sonnylloyd actually the real issue is here
https://github.com/artf/grapesjs/blob/dev/src/domain_abstract/ui/Input.js#L24-L27

should be instead:
```js
  handleChange(e) {
    e.stopPropagation();
    this.model.set('value', this.getInputEl().value);
    this.elementUpdated();
  },
```
I've already made this change in the latest RC, you can see it working here
http://grapesjs.com/demo-no-jq.html

**Comment by sonnylloyd** [comment]
@artf thanks.

**Comment by artf** [comment]
Should be fixed
