### ISSUE TITLE
Script tag not rendering in HTML page

### ISSUE THREAD

**Issue by hrdkzala** [artf/grapesjs#3730]
I created the component as below.

```js
const script = function() {
        const script = document.createElement('script');
        script.src = 'http://localhost:8888/builder/sites/site1/assets/js/jquery-1.12.4.min.js';
        document.body.appendChild(script);
});
```

```js
editor.Components.addType('comp-with-js', {
      model: {
        defaults: {
          script
        }
      }
    });
```

```js
editor.BlockManager.add('site_1', {
      label: 'Template 1',
      category: 'Template',
      content: '<div> HERE is my content </div>'
});
```

site_1 - is my readymade template and it has CSS and javascript.

CSS loads properly with the "content" but javascript doesn't so I created component for javascript.

On the HTML page, It shows the jquery file is added but doesn't work. I checked in view source.

If I made any external javascript file which simply alert("test"), but it doesn't work on html page.

I am using NuxtJS + Grapesjs.

Please advise me about this issue.

**Comment by artf** [comment]
Sorry but I don't understand where is your issue. You have created `comp-with-js` component but then you don't show where you are using it... 
Please, provide a reproducible demo.

**Comment by mingxin-yang** [comment]
script function don't work after drag the block 
@artf

**Comment by mingxin-yang** [comment]
https://grapesjs.com/docs/modules/Components-js.html#basic-scripts

**Comment by hardikcelinel** [comment]
I have already followed it. but my question is that on the frontend where we display the page which is made by grapesjs editor, script/Js not loading.

My page is in NuxtJS.

**Comment by hrdkzala** [comment]
I have already followed it. but my question is that on the frontend where we display the page which is made by grapesjs editor, script/Js not loading.

My page is in NuxtJS.

**Comment by mingxin-yang** [comment]
I face same problem

**Comment by mingxin-yang** [comment]
> https://grapesjs.com/docs/modules/Components-js.html#basic-scripts

this don't work for me

**Comment by artf** [comment]
@hrdkzala please create a proper bug issue with a reproducible demo, at the moment, I don't have enough information to help you, and from what I see, components with js are working properly.

**Comment by ronaldohoch** [comment]
Hello!
I'm doing this right now and, by your code, you forgot to set the type of your block, check the way it work:

```js
editor.BlockManager.add('site_1', {
      label: 'Template 1',
      category: 'Template',
      content: '<div> HERE is my content </div>',
      content: {
          type: 'comp-with-js'
      }
});
```
