### ISSUE TITLE
BUG: Text element not able to be selected twice after extended with events

### ISSUE THREAD

**Issue by gustavohleal** [artf/grapesjs#3731]
Version: 0.17.25

**Are you able to reproduce the bug from the demo?**

 - [ ] Yes
 - [x] No

**What is the expected behavior?**
Update a existing component of type text by adding an event to his view.

*Describe the bug **detailed***
The event is being added, but once I select another component I cannot go back to the first one. It can only be entered one time for edition.

**Are you able to attach screenshots, screencasts or a live demo?**

 - [x] Yes (attach)
 - [ ] No

first, i'm trying to extend the text type component to add an event to listen when something is typed.

```javascript
      export default (editor, opts = {}) => {
        const domc = editor.DomComponents;
        domc.addType('text', {
          view: {
            events: {
              keypress: (e) => {
                console.log("Some code")
              }
            }
          },
        });
      };
```

Even if I leave only a empty `events` property like `events:{}` the bug remains.

When I first add the component, the event works:

![image](https://user-images.githubusercontent.com/22385451/131032469-0dbfb1d8-4358-4c45-ba08-3e5cf446e5de.png)

And then, once I deselect the component and try do select him again:

![image](https://user-images.githubusercontent.com/22385451/131032648-f4e23f46-59a9-468a-a601-a68dbebf49b4.png)

The purpose of this is to generate a roll event everytime someone hits return to break a line. This is a workaround for a bug in CKEditor plugin where the editor toolbar does not roll as the text component gets bigger. I will also open an issue in the CK Editor plugin repository and relate to this one.

**Comment by artf** [comment]
The `events` are not automatically merged with the extended component so, you have to do it manually.
```js
events: {
  ...domc.getType('text').view.prototype.events,
  keypress: (e) => {...}
}
```

**Comment by gustavohleal** [comment]
That actually was the problem. Thanks for replying. I'll be closing the issue.
