### ISSUE TITLE
BUG: (or just general issue) storage manager does not load coorectly?

### ISSUE THREAD

**Issue by anatoli-dp** [artf/grapesjs#3733]
## WARNING
READ and FOLLOW next 3 steps, then REMOVE them before posting the issue

1. Follow CONTRIBUTING Guidelines https://github.com/artf/grapesjs/blob/master/CONTRIBUTING.md
2. Do a quick SEARCH first, to see if someone else didn't open the same issue
3. All relative statements/questions have to be filled/answered, otherwise, the issue might be CLOSED
4. JSFiddle Starter template https://jsfiddle.net/szLp8h4n
5. CodeSandbox Starter template https://codesandbox.io/s/1r0w2pk1vl

**Version:**
current (i use latest builds)
*You can get the version by typing `grapesjs.version` into the console*

**Are you able to reproduce the bug from the demo?**

 - [ ] Yes
 - [x] No

**What is the expected behavior?**
when loading from storage on initial load (first run) it should populate the editor with the components and whatnot but it does not load a
![Screenshot (21)](https://user-images.githubusercontent.com/75029364/131325805-77357f9b-7571-4d17-ab77-c51e6b4c34b5.png)
![Screenshot (22)](https://user-images.githubusercontent.com/75029364/131325811-56c08965-b224-4bf3-bbfb-f8df61c9d470.png)
nything and the page is always blank depsite having content
*Describe the bug **detailed***

**What is the current behavior?**
it doesnt load anything . . . maybe im doing it wrong but from the docs there is no further explantion about the storagemanager. as seen below the first image show storage code to load data and second image shows the data loaded adn ouput to console but as seen by 3rd image nothin actually appears on the page
*Describe the bug **detailed***

**Are you able to attach screenshots, screencasts or a live demo?**

 - [x] Yes (attach)
 - [ ] No
![Screenshot (23)](https://user-images.githubusercontent.com/75029364/131326007-359f0d72-f3f8-4808-83b1-9bd057c66f7c.png)

**Comment by artf** [comment]
You're calling the `clb` outside the fetch, in your load function

```js
load(keys, clb) {
 fetch(...).then(r => r.json())
   .then(res => {
     ...
     clb(result)
   })
}
```
