### ISSUE TITLE
BUG: Select options are not displaying.  Rather displaying as input 

### ISSUE THREAD

**Issue by codingmachine16** [artf/grapesjs#3735]
Hi @artf,

We are using select options as Traits but these are displaying as input. sometimes theese display options and sometimes displaying as input . Our code is below 

        defaults: Object.assign({}, defaultModel.prototype.defaults, {
          traits: [
            {
              label: "Categories",
              name: "noOfCategories",
              id: "noOfCategories",
              type: "select",
              options: [
                {
                  id: "0",
                  name: "None",
                },

                {
                  id: "1",
                  name: "1",
                },
                {
                  id: "2",
                  name: "2",
                },
                {
                  id: "3",
                  name: "3",
                },
                {
                  id: "4",
                  name: "4",
                },
                {
                  id: "5",
                  name: "5",
                },
                {
                  id: "6",
                  name: "6",
                },
                {
                  id: "7",
                  name: "7",
                },
                {
                  id: "8",
                  name: "8",
                },
                {
                  id: "9",
                  name: "9",
                },
                {
                  id: "10",
                  name: "10",
                },
              ],
              changeProp: 1,
            },
            {
              label: "Links",
              name: "noOfLinks",
              id: "noOfLinks",
              type: "select",
              options: [
                {
                  id: "0",
                  name: "none",
                },
                {
                  id: "1",
                  name: "1",
                },
                {
                  id: "2",
                  name: "2",
                },
                {
                  id: "3",
                  name: "3",
                },
                {
                  id: "4",
                  name: "4",
                },
              ],
              changeProp: 1,
            },
          ],
        }),

![image](https://user-images.githubusercontent.com/87995581/131392265-06b86571-3a2f-4245-8039-e975c773baad.png)

**Comment by calazans10** [comment]
I got the same error today.
![Screen Shot 2021-09-01 at 15 30 44](https://user-images.githubusercontent.com/694018/131724770-873636a3-3b75-4821-80ad-96c4e93e4bc2.png)
![Screen Shot 2021-09-01 at 15 32 14](https://user-images.githubusercontent.com/694018/131724899-f883eba2-3405-442a-b244-c1a215b0b64c.png)

**Comment by artf** [comment]
Weird thing, can anybody provide a simple reproducible demo as I'm not able to reproduce?

**Comment by calazans10** [comment]
@artf Here's the demo. light-knee.surge.sh

**Comment by YumiChen** [comment]
@artf Just to add that we bumped into this these 2 days as well. This seems only happen to version `0.17.25`. Following is Jsfiddle for reproducing the issue, if needed please check:
https://jsfiddle.net/a29h7twy/5/

Reproduce step:
1. Drag a component into canvas
2. Select the component and click settings button to check the traits
3. Select trait is displayed as input. In dev tool console some warnings are shown

**Comment by mmotov** [comment]
Same for me in v0.17.22 and 0.17.25
Warning in the console when clicking on trait 
![Screen Shot 2021-09-03 at 3 43 51 PM](https://user-images.githubusercontent.com/25824414/132007235-ef124dd0-cc05-434f-844d-31c14fcd99a9.png)

**Comment by sarelp** [comment]
I have bumped into this same issue.

I think it is due to `this.updatedCollection();` being called in the TraisView component. The result is that the traits aren't initialised.

I managed to fix it by removing the `this.updatedCollection;` and then updatedCollection it in trait_manager/index.js:
```
    render() {
      TraitsViewer && TraitsViewer.remove();
      TraitsViewer = new TraitsView({
        collection: [],
        editor: c.em,
        config: c
      });
      TraitsViewer.itemsView = types;
      TraitsViewer.updatedCollection();
      return TraitsViewer.render().el;
    },
```

Not sure if this is the right way to go about it but does solve the issue for me.

**Comment by artf** [comment]
Yes, you're right @sarelp
It's actually wrong calling updatedCollection on `initialize`, I'll fix it in the next release.

**Comment by codingmachine16** [comment]
When we drag component and click on the element on which traits are set , it show input text instead of select box. On the other hand, after component drag, if we click on any other element and then click on that elemenet which has traits then select box will display.

**Comment by markovic-nikola** [comment]
> When we drag component and click on the element on which traits are set , it shows input text instead of select box. On the other hand, after component drag, if we click on any other element and then click on that element which has traits then select box will display. very strange!

I can confirm this is happening to me on `0.17.25` version also for types: select, number and checkbox.

**Comment by codingmachine16** [comment]
This issue is averting us to deploy our projects . Need a fast solution.

**Comment by markovic-nikola** [comment]
@codingmachine16 If I'm not mistaken, the issue is already fixed, @artf just needs to push the new version.

**Comment by artf** [comment]
@codingmachine16 you have to wait for the release

**Comment by codingmachine16** [comment]
OK . Sure. Thanks. For information, this issue does not exist on 0.17.22

**Comment by markovic-nikola** [comment]
> OK . Sure. Thanks. For information, this issue does not exist on 0.17.22

Good to know, since I need to release it within a project soon.
