### ISSUE TITLE
BUG: When copying a text from anywhere the style manager is not working right. 

### ISSUE THREAD

**Issue by migokcek** [artf/grapesjs#3753]
### GrapesJS version

- [x] I confirm to use the latest version of GrapesJS

### What browser are you using?

Chrome v92

### Reproducible demo link

https://grapesjs.com/demo.html

### Describe the bug

When I take any text from Microsoft Office word or any websites it is coming with it’s own css and font-color, and the font-color attribute is not working for the text.
Second bug is when I try to change font-size, it’s changing the ‘text box’ size, not the font-size. 
I tried to add !Important in StyleManager, but did not work
![grapesjsBug](https://user-images.githubusercontent.com/43312554/132261928-d45e9b1a-7cec-4256-a50f-7ddfcf1e02f3.png)
This photo is from your demo 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
If you paste a text with its own inner style, you have to change it for each pasted component, as their style overrides the parent one.

**Comment by chirag0110** [comment]
@artf , Even We are not able to change any pasted component. I have added lorem ipsum text from the lorem ipsum site. When I paste the text grapesJs wrap text with the <p id="i835ol"></p>

I am not able to change the styling of the <p> tag. I have tried in GrapesJs demo too. Please check the screenshot attached.

![image](https://user-images.githubusercontent.com/20700428/150919741-3bad2eeb-d1fc-470f-adff-95a75e917d04.png)
