### ISSUE TITLE
BUG: v0.17.25 . Trait button in the custom component defining. 

### ISSUE THREAD

**Issue by abolabo** [artf/grapesjs#3763]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Firefox

### Reproducible demo link

https://jsfiddle.net/abolabo/3g7j519h/19/

### Describe the bug

Code works incorrect:
traits: [
                    {
                        type: "button",
                        text: "click me",
                        full: true,
                        command: (editor) => console.log("trait command"),
                    },
                ],
                
I expecting <button> tag  but input type=button  shows instead.
No text inside button. No command run.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
Thanks @abolabo for the report, this issue was actually already fixed here #3735
