### ISSUE TITLE
default newsletter blocks

### ISSUE THREAD

**Issue by suraj740** [artf/grapesjs#377]
can anyone tell how to add default newsletter blocks used in newsletter-demo.
![screen shot 2017-10-04 at 7 09 51 pm](https://user-images.githubusercontent.com/24958883/31178803-c453a546-a937-11e7-82d5-26beb4c988e0.png)

please help @artf 
Thanks in advance

**Comment by artf** [comment]
Just add this plugin https://github.com/artf/grapesjs-preset-newsletter
