### ISSUE TITLE
BUG: Select options are not displaying - new anomaly 

### ISSUE THREAD

**Issue by codingmachine16** [artf/grapesjs#3778]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Chrome

### Reproducible demo link

https://github.com/artf/grapesjs/issues/3735

### Describe the bug

I am have issue related to select box . It is showing issues as in console 

[Traits]: 'select' type not found {level: 'warning'}

When we drag component and click on the element on which traits are set , it shows input text instead of select box. On the other hand, after component drag, if we click on any other element and then click on that element which has traits then select box will display. very strange!

Note: This issue is mentioned here https://github.com/artf/grapesjs/issues/3735 . Author updated two files and reported as fix but it is not fix in accordance with above scenario. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Bran72** [comment]
Hi !
I also have your issue since the v.0.17.25.
I think it will be fixed in the [next release](https://github.com/artf/grapesjs/projects/30).

So the temporary solution is to downgrade to v0.17.22... Hope it will help you !

**Comment by artf** [comment]
Correct, it's been fixed here #3735

**Comment by codingmachine16** [comment]
OK . Sure. Thanks. For information, this issue does not exist on 0.17.22 but it is in 0.17.25
