### ISSUE TITLE
How to change bg colors?

### ISSUE THREAD

**Issue by sambuev** [artf/grapesjs#378]
Can't find any option to change the color of bg? I want to place my own image (how?) and change the bg of the div-layer. Can't find this option yet.

**Comment by sambuev** [comment]
Found it in the demo. I wanted to upload the image, but it only takes it, refreshed thr window and do nothing. Is this limitation of the demo version? I using only demo from the official website.

**Comment by artf** [comment]
Check here about the uploader https://github.com/artf/grapesjs/issues/380
