### ISSUE TITLE
BUG: RTE overlapping text when text component set to 100% height

### ISSUE THREAD

**Issue by mattnoth** [artf/grapesjs#3783]
### GrapesJS version

please help - this may have been solved somewhere but i looked through the issues and found none - there is a doc reference to moving the positioning of the RTE but im not sure where in the init it should go --> what does 'rteToolbarPosUpdate` 
and pos mean? i just want the RTE to go to the bottom of the text box when set to height 100%

```
`editor.on('rteToolbarPosUpdate', (pos) => {
  if (pos.top <= pos.canvasTop) {
    pos.top = pos.elementTop + pos.elementHeight;
  }
});`
```

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Version 93.0.4577.82 (Official Build) (64-bit)

### Reproducible demo link

https://codesandbox.io/s/peaceful-feather-8pz5i

### Describe the bug
When you go to the sand box you must manually set the height and width  of the text box to 100% -- for some reason it doesn't save 
**How to reproduce the bug?**
1. ... Set Dimensions of Text Component -- Height to 100% and Width 100% 
2. ... Click on the text component and  you will see the RTE overlap the text 

**What is the expected behavior?**
... The RTE should go to the bottom of the text componenet 

**What is the current behavior?**
... RTE overlaps text when height of text component is set to 100% 
If is necessary to execute some code in order to reproduce the bug, paste it here below:
```js
// your code here
```

here is another pic of the issue 
![overlapping RTE](https://user-images.githubusercontent.com/6341816/133675372-1b9b0464-0197-4fe0-8cd1-bb87eba04e18.png)

This is where in the docs a piece of code should modify the position for the RTE but only when scrolling 
![toolbar position](https://user-images.githubusercontent.com/6341816/133675515-51a81322-bcc2-49ff-95d1-fa42dbc33890.png)

unsure how to modify for my issue

```
`editor.on('rteToolbarPosUpdate', (pos) => {
  if (pos.top <= pos.canvasTop) {
    pos.top = pos.elementTop + pos.elementHeight;
  }
});`
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
Not a bug, just a weird use case.

**Comment by mingxin-yang** [comment]
@artf I want to change the position of rteToolbar, but pos does not have the parameters mentioned in the document
