### ISSUE TITLE
BUG: RTE Overlapping text In Basic Text Component when Width & Height are 100% of Canvas

### ISSUE THREAD

**Issue by mattnoth** [artf/grapesjs#3794]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Version 93.0.4577.82 (Official Build) (64-bit)

### Reproducible demo link

https://grapesjs.com/demo.html

### Describe the bug

![RTE Clarified](https://user-images.githubusercontent.com/6341816/134036743-d8296cf5-9027-4833-b836-711c37d40f59.png)

**How to reproduce the bug?**
1. ... In the official demo, delete everything / start with Body Only in the layers panel 
2. ... Add a basic Text Component, so the layers are Body > Text
3 ... Set the basic text component's dimensions to 100% Width and 100% Height 
4 ... When you start typing, the RTE has no place to go outside of that element on the canvas, so the editor overlaps the text itself 

**What is the expected behavior?**
... If the width and height of a basic text component are 100%; the RTE should compensate for overlapping with the written text; perhaps automatically moving to opposite the pos top and offsetLeft within the same component (where as when the height and width are NOT set to100%, the RTE has space to go on the canvas outside the text component, which is when the automatic function for moving the RTE fires)

**What is the current behavior?**
... The rich text editor, when the basic text component is the only component on the body, and takes the full height and width of the canvas, sits ontop of the text as user

![RTE Overlap Clarified](https://user-images.githubusercontent.com/6341816/134036766-277ac90c-bb0f-44e5-a459-0e1a35c32e2d.png)

If is necessary to execute some code in order to reproduce the bug, paste it here below:
```js
// your code here -- no code required 
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mattnoth** [comment]
I didn't noticed that you had closed my previous issue -- with the weird use case. Do you have any suggestions for a work around here? I've been using the updateRte event  listener, putting the RTE inside the canvas dynamically is proving a challenge

**Comment by artf** [comment]
@mattnoth I already replied to your discussion [here](https://github.com/artf/grapesjs/discussions/3782#discussioncomment-1350537), please avoid opening the same issue again.
