### ISSUE TITLE
BUG: 

### ISSUE THREAD

**Issue by mihir-khandekar** [artf/grapesjs#3810]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

92.0.4515.131 (Official Build) (64-bit)

### Reproducible demo link

N/A

### Describe the bug

**How to reproduce the bug?**
1. Insert HTML into canvas using the `editor.Canvas.getBody().ownerDocument.execCommand('insertHTML', false, HTMLString)` command.
2. the inserted HTML does show up on the editor canvas.
2. Use the editor's editor.getHtml() function.
3. The returned HTML string by `editor.getHtml()` does not contain the HTML that was inserted using the execCommand command.

**What is the expected behavior?**
The final HTML should return HTML inserted using `execCommand`

**What is the current behavior?**
The final HTML does not contain HTML inserted using `execCommand`

If is necessary to execute some code in order to reproduce the bug, paste it here below:

another issue with the first approach listed below is that `editor.addComponent()` adds the component to the end of the DOM and the insertHTML command inserts the html of that component into the current cursor position.

```
const [varEl] = editor.addComponents(
            '<span class="am-var no-tooltip" data-gjs-editable="false" data-gjs-droppable="false" data-gjs-selectable="false" data-am-var="' +
                key +
                '" style="white-space:nowrap; padding: 1%; font-size: inherit; margin: 1% 2%; cursor: pointer;">' +
                variable +
                '</span>'
        );

editor.Canvas.getBody().ownerDocument.execCommand(
            'insertHTML',
            false,
            `&nbsp;${varEl.toHTML()}&nbsp;`
        );

editor.getHtml()
```

I have also tried adding an HTML string instead of the `component.toHTML()` approach mentioned above like so which doesn't work either:
```
editor.Canvas.getBody().ownerDocument.execCommand(
        'insertHTML',
        false,
        '&nbsp;<span class="am-var no-tooltip" data-gjs-editable="false" data-gjs-droppable="false" data-gjs-selectable="false" data-am-var="' +
                key +
                '" style="white-space:nowrap; padding: 1%; font-size: inherit; margin: 1% 2%; cursor: pointer;">' +
                variable +
                '</span>&nbsp;'
)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
the getHtml has nothing to do with the DOM of the canvas...
Read carefully the documentation https://grapesjs.com/docs/modules/Components.html and try to understand the difference between the model and the view of the component.

**Comment by mihir-khandekar** [comment]
@artf thanks for the prompt response, what is the right way of doing this then?

My requirement is: I want to add a component at the current cursor position. How can I then get it to be part of the editor.getHtml() method?

**Comment by ionutmiftode** [comment]
@mihir-khandekar did you manage to fix this?
