### ISSUE TITLE
BUG: ckeditor wrap and block the text below

### ISSUE THREAD

**Issue by mingxin-yang** [artf/grapesjs#3825]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Chrome

### Reproducible demo link

https://

### Describe the bug

If the width of the text component is not very long, the elements on ckeditor will wrap and block the text below
![image](https://user-images.githubusercontent.com/23076937/134872894-8a9dba2f-9fd8-4026-adcf-df6b98a8d998.png)
But when you click on the lower part of the component, instead of just above the text, there will be no covering problem
![image](https://user-images.githubusercontent.com/23076937/134873155-d3bb89c7-641e-4987-8e7b-bad3623fab4a.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mingxin-yang** [comment]
bugs will also be implemented on this website. https://grapesjs.com/demo-mjml.html
![image](https://user-images.githubusercontent.com/23076937/134886777-86c03c07-b253-4810-9275-05486a852ef6.png)
The toolbar in the upper right corner will also be covered

@artf

**Comment by ronaldohoch** [comment]
Hello!

We used this trick to solve the problem for a while:

```js
            editor.on("rte:enable",()=>{
                editor.trigger('canvasScroll');
            });
```

**Comment by sendpalm** [comment]
@ronaldohoch Thank you, this code worked

**Comment by mingxin-yang** [comment]
@ronaldohoch Thank you, this code work to me
