### ISSUE TITLE
Best way to load element's css into the properties panel.

### ISSUE THREAD

**Issue by daniel-farina** [artf/grapesjs#383]
Hi Again everyone, 

GrapeJS is too much fun once you get deep into it.  I have a simple question:

What's the best way to load the css from a newly created element to the properties panel. 

For example I have the following box which has a black background: 

![image](https://user-images.githubusercontent.com/13665117/31221731-a7b0d566-a992-11e7-808d-7c742a840646.png)

The black background comes from the style in the element

```
...
 content: `
              <div class="col-8" style="background-color: rgba(0,0,0,0.70); padding:40px;" 
...
```

The editor converts the style tag into a class as shown here:

![image](https://user-images.githubusercontent.com/13665117/31221906-300f9712-a993-11e7-9b5f-58238572e885.png)

yet the properties panel does not have a background set:
![image](https://user-images.githubusercontent.com/13665117/31221964-6875d508-a993-11e7-888e-0d89ed33c6ae.png)

Now I change the color to dark orange: 
![image](https://user-images.githubusercontent.com/13665117/31221989-869cab56-a993-11e7-9e3a-8f3bd4737096.png)

it will create a new class for it that will overwrite the previous one: 

![image](https://user-images.githubusercontent.com/13665117/31222043-b2c4deba-a993-11e7-8924-bf5c1c649b16.png)

Thank you in advanced for any thoughts!

**Comment by daniel-farina** [comment]
I discovered that if the div has no class and just style then a single class is created and the background is applied to the properties panel: 

![image](https://user-images.githubusercontent.com/13665117/31222351-ccf0ee72-a994-11e7-93c3-ded04be091e9.png)

![image](https://user-images.githubusercontent.com/13665117/31222284-98b4d010-a994-11e7-96a7-07df42bb8ccc.png)

so that would be a partial solution for now but still looking for a better alternative.

**Comment by artf** [comment]
Hi @daniel-farina you don't see `.c1019`'s background because your component has two classes so, by default, the Style Manager select the CSS rule where the selector is a combination of all its classes, in your case `.col-8.c1019`. If you want to see `.c1019`'s styles you can just deselect `.col-8`
![schermata 2017-10-05 alle 13 11 54](https://user-images.githubusercontent.com/11614725/31224578-ce1dc24a-a9ce-11e7-821a-36c1df0368c6.png)

You can also avoid automatic class generation if you want
```js
grapesjs.init({
     ...
     forceClass: false
})
```

**Comment by daniel-farina** [comment]
@artf  I undertand now
![image](https://user-images.githubusercontent.com/13665117/31252875-a5b4c5de-a9f0-11e7-9f07-0937896fa0f1.png)

I completely missed the checkbox next to each selector. Setting the forceClass to false solves all my problems!  I dont really need that as I'm keeping the source code extremely lean with as little divs as possible. Thank you very much for that!

Dan
