### ISSUE TITLE
BUG: Duplicated video block when re-attaching GrapesJs editor to document

### ISSUE THREAD

**Issue by JGiard** [artf/grapesjs#3873]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Chrome v94

### Reproducible demo link

https://jsfiddle.net/3mrzaqtx/

### Describe the bug

**How to reproduce the bug?**
1. Add a video block to the canvas
2. Remove the GrapesJs editor element from the document (Optional)
3. Re-attach the GrapesJs editor element to the document

**What is the expected behavior?**
GrapesJs canvas should be the same before and after the operation

**What is the current behavior?**
The video is displayed multiple times

**My investigation**
According to the ComponentVideoView, this is caused by the render() function. Unlike the updateProvider() function, render doesn't take care of clearing the container before appending the new iframe/video tag in the block.

We are integrating GrapesJs into another application, and we don't create a new GrapesJs editor when switching back and forth between views, thus the detach/attach behavior. I also don't know what events GrapesJs listens to trigger a re-render on attach.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
No, you should never rely on something like this, or you destroy and reinit, or you simply hide and show the editor.
