### ISSUE TITLE
No CSS ::before & ::after Selectors

### ISSUE THREAD

**Issue by ajaysofto** [artf/grapesjs#388]
how can we add before and after selector for any classes

**Comment by artf** [comment]
You have to change selector states
```js
grapesjs.init({
     ...
    selectorManager: {
        states: [
              { name: 'hover', label: 'Hover' },
              { name: 'nth-of-type(2n)', label: 'Even/Odd' },
              { name: ':before', label: 'Before' }, 
              { name: ':after', label: 'After' }, 
          ],    
    }
})
```

**Comment by parmando** [comment]
Ok, 

> You have to change selector states
> 
> ```js
> grapesjs.init({
>      ...
>     selectorManager: {
>         states: [
>               { name: 'hover', label: 'Hover' },
>               { name: 'nth-of-type(2n)', label: 'Even/Odd' },
>               { name: ':before', label: 'Before' }, 
>               { name: ':after', label: 'After' }, 
>           ],    
>     }
> })
> ```

Ok, but as I change "- State -" and "Selected" I need to translate this ...
![select](https://user-images.githubusercontent.com/2301752/64298237-4219e180-cf4b-11e9-8085-d0c2350b2306.jpg)
