### ISSUE TITLE
Make font-awesome a peerDependency

### ISSUE THREAD

**Issue by Geczy** [artf/grapesjs#390]
Font-awesome is a big library that i'm already loading. If I load grapesjs, it will load FA twice.

If you make FA a peer-dependency then this will fix that problem

**Comment by Geczy** [comment]
I see you kind of have this on the roadmap https://github.com/artf/grapesjs/issues/74 to replace with svg's

**Comment by artf** [comment]
Yeap, I should definitely remove font-awesome from the core
