### ISSUE TITLE
Define selected class.

### ISSUE THREAD

**Issue by daniel-farina** [artf/grapesjs#392]
Hello @artf ,

Is there a way to automatically select the class that is created on elements with custom styles.  

![image](https://user-images.githubusercontent.com/13665117/31314962-0e0f6846-abdb-11e7-8339-84035ae45aca.png)

I'm currently trying to dynamically update classes with a grid system and it's working fine but the auto selection of all classes is creating issues. I've been looking at the code for hours trying to figure this out. 

Any directions to the right file where the magic occurs is appreciated. 

I'm currently looking at: 
[\src\selector_manager\view\ClassTagView.js](https://github.com/artf/grapesjs/blob/ae92898340134ab85ffd6623d681af56cee8fcd3/test/specs/selector_manager/view/ClassTagView.js)

Thanks!

**Comment by daniel-farina** [comment]
Update: 

Ok I figured out that I can make them all unselect by default by changing 
src/selector_manager/model/Selector.js

```
   active: false,
```

![image](https://user-images.githubusercontent.com/13665117/31315033-c8811c82-abdc-11e7-9b79-0c604d1b91cf.png)

and this pretty much solves all my problems as when I change the background color of the block, it will update only c875!.

Closing this as it's now solved.

**Comment by daniel-farina** [comment]
fyi changing this to false will make your build to fail due to this in the test script:

```
       it('Has active property', () => {
          expect(obj.has('active')).toEqual(true);
        });
```

change it to true to pass the test.

**Comment by thecodefish** [comment]
@daniel-farina @artf Any thoughts on how to manage this without modifying the source? I have a situation where I have blocks/components that contain classes that I don't want to modify. If I change the styles for an individual component, it is adding css rules for the combination of all classes (which then apply to all instances of that component) - it's not actually creating a new class for my selected component.

**Comment by artf** [comment]
You can access selectors from the model
```js
model.get('classes').each(selector => selector.set('active', 0))
```
or for example, disable them all from its module

```js
editor.SelectorManager.getAll().each(selector => selector.set('active', 0))
```
