### ISSUE TITLE
BUG: Color trait type not working correctly

### ISSUE THREAD

**Issue by mrobertshaw** [artf/grapesjs#3931]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Chrome Latest

### Reproducible demo link

N/A

### Describe the bug

Firstly, thank you so much for a wonderful piece of software - I absolutely love it !!

I have just updated to the latest GrapesJS (was previously on a v 0.16.x version) and have encountered a new issue with the trait type 'color'.  This was previously working correctly but it seems that following the upgrade I now get the following Javascript error:

KinisiteWysiwyg.js:formatted:24937 Uncaught TypeError: i.getValue is not a function
    at r.getColorEl (KinisiteWysiwyg.js:formatted:24937)
    at render (KinisiteWysiwyg.js:formatted:24982)
    at r.getInputEl (KinisiteWysiwyg.js:formatted:35983)
    at renderField (KinisiteWysiwyg.js:formatted:35805)
    at render (KinisiteWysiwyg.js:formatted:35835)
    at r.add (KinisiteWysiwyg.js:formatted:19514)
    at r.<anonymous> (KinisiteWysiwyg.js:formatted:19522)
    at KinisiteWysiwyg.js:formatted:4046
    at Module.je (KinisiteWysiwyg.js:formatted:4418)
    at r.each (KinisiteWysiwyg.js:formatted:5134)

Which references the getColorEl function as follows ( I have emboldened the offending line) 

 getColorEl: function() {
                    if (!this.colorEl) {
                        var t, e = this.em, n = this, r = this.ppfx, i = this.model, o = p('<div class="'.concat(this.ppfx, 'field-color-picker"></div>')), a = o.get(0).style, s = e && e.config ? e.config.el : "", c = e && e.getConfig && e.getConfig("colorPicker") || {}, l = 0;
                        this.$el.find("[data-colorp-c]").append(o),
                        o.spectrum(d(d(d({
                            color: **i.getValue()** || !1,
                            containerClassName: "".concat(r, "one-bg ").concat(r, "two-color"),
                            appendTo: s || "body",
                            maxSelectionSize: 8,
                            showPalette: !0,
                            showAlpha: !0,
                            chooseText: "Ok",
                            cancelText: "⨯",
                            palette: []
                        }, c), i.get("colorPicker") || {}), {}, {
                            move: function(t) {
                                var e = g(t);
                                a.backgroundColor = e,
                                i.setValueFromInput(e, 0)
                            },
                            change: function(t) {

I am very keen to upgrade to continue some integration work and could probably create an alternative custom trait type if required but if it's a simple fix that would be great.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
Thanks @mrobertshaw for the report. The fix will be available in the next release.

**Comment by miladmeidanshahi** [comment]
@artf many thanks for the fix, please release as asap.

**Comment by miladmeidanshahi** [comment]
still same error after upgrade to latest version. @artf 

![Screenshot from 2022-01-19 17-03-22](https://user-images.githubusercontent.com/11172818/150140879-78509f2b-5e42-4d77-aea5-dc09da10dc28.png)

**Comment by artf** [comment]
@miladmeidanshahi I don't see any issue in the latest version, create a reproducible demo.

**Comment by miladmeidanshahi** [comment]
it was pnpm issue cached the previews version of grapesjs.
