### ISSUE TITLE
BUG: editor.select(model,{scroll:true}) ,scroll don't work

### ISSUE THREAD

**Issue by mingxin-yang** [artf/grapesjs#3938]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Chrome

### Reproducible demo link

https://codepen.io/mingxin-yang/pen/YzxLNay

### Describe the bug

**How to reproduce the bug?**
1. editor.select(model,{scroll:true}) ,scroll don't work
2. ...

**What is the expected behavior?**
Click the block, after adding it to the canvas, you can select, activate, and scroll to the selected position

**What is the current behavior?**
...

If is necessary to execute some code in order to reproduce the bug, paste it here below:
```js
// your code here
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
Thanks @mingxin-yang This will be fixed in the next release.
