### ISSUE TITLE
Text: New div is created every time I hit enter instead of creating a </br>

### ISSUE THREAD

**Issue by daniel-farina** [artf/grapesjs#394]
Hi @artf 

Is there a reason why when inserting text a new div is created for every break instead of a standard </br>

![image](https://user-images.githubusercontent.com/13665117/31329777-adf6ee50-aca9-11e7-9a4d-7cd06b367135.png)

```
<div class="c4840">Insert your text here. I hit enter
  <div data-highlightable="1">a new div is created
  </div>
  <div data-highlightable="1">I hit enter again
  </div>
</div>
```

Is it possible to disable this behavior and make a </br> instead. 

I know this works if I hit the shift + enter but I would like for it to be the default option. 

Thank you

**Comment by artf** [comment]
Hi @daniel-farina this is a default behavior in WebKit browser I here you can find actual solutions
https://stackoverflow.com/questions/18552336/prevent-contenteditable-adding-div-on-enter-chrome

I actually started rewriting the current RTE and will take into account this issue

**Comment by daniel-farina** [comment]
Thank you for the update and information. I'll look into it.
