### ISSUE TITLE
BUG: Issue with updating Button text

### ISSUE THREAD

**Issue by dan-castillo** [artf/grapesjs#3940]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Chrome - Version 95.0.4638.69

### Reproducible demo link

two places: https://grapesjs.com/demo.html and I have a repo here:  https://github.com/dan-castillo/TestingGjsV1729.git

### Describe the bug

**How to reproduce the bug?**
1. Go to the form plugin demo: https://grapesjs.com/demo.html 
2. Scroll to the bottom and try to change the text for the submit button 
3. alternatively I added an angular repo [here](https://github.com/dan-castillo/TestingGjsV1729.git)

**What is the expected behavior?**
when you select a button you should be able to change the text and have it update the code in GJS.

**What is the current behavior?**
the text is not updated

If is necessary to execute some code in order to reproduce the bug, paste it here below:
```js
here is the repo [my test repo](https://github.com/dan-castillo/TestingGjsV1729.git)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
This is just the problem with the webpage preset which has the old reference to the form plugin, not related to the core.
