### ISSUE TITLE
BUG: Events On assetmanager not working

### ISSUE THREAD

**Issue by majidh1** [artf/grapesjs#3951]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

chrome 

### Reproducible demo link

no link

### Describe the bug

editor.on("asset:upload:start",console.log) not working

after versiom 0.17.26 not working assetmanager events **asset:upload:start or asset:upload:end** on editor 

i am debuging code and find this
```js
     // file: src/asset_manager/index.js 
      const { module } = this; // module is undefined
      module && module.__propEv('asset:upload:start');
```

### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
Fixed here https://github.com/artf/grapesjs/pull/3934/files
