### ISSUE TITLE
the scripts should put at bottom in canvasview for better loading speed,isn't it? :)

### ISSUE THREAD

**Issue by vtista** [artf/grapesjs#398]
![default](https://user-images.githubusercontent.com/22438077/31365796-09aa2072-ada0-11e7-9ea7-9b794d8cf73a.png)

**Comment by artf** [comment]
Hi @vtista the purpose of this part is to load scripts before any other component as one of them might need them as a dependency. Basically, it's trying to simulate the `<head>` synchronous loading
