### ISSUE TITLE
BUG: Can't remove border of element

### ISSUE THREAD

**Issue by kuhelbeher** [artf/grapesjs#3997]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Chrome v96

### Reproducible demo link

https://codesandbox.io/s/grapes-border-issue-94lje

### Describe the bug

**How to reproduce the bug?**
1. Select block with top and bottom borders
2. Go to Style panel -> Decorations -> Border
3. Clear border-color input and press Enter

**What is the expected behavior?**
Border should be removed

**What is the current behavior?**
Border remains. Check the css, it will look like `border: 5px solid none;` which is invalid value

I noticed that this issue appears only if border is set via separate border styles, e.g. border-top and border-bottom.
Following question - how to properly remove borders via style panel?

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
Hi @kuhelbeher with the new https://github.com/artf/grapesjs/releases/tag/v0.18.1 release this can be handled.

The main issue here is how the [built-in](https://grapesjs.com/docs/modules/Style-manager.html#built-in-properties) `border` property is configured, which is a [Composite type](https://grapesjs.com/docs/api/property_composite.html) of `border-width`, `border-style` and `border-color`.
That means the editor is able to understand styles like `border: 5px solid red` or even `border-color: red; border-style: solid; border-width: 5px;` but unfortunately, properties like `border-top`, `border-bottom`, etc. are out of the scope as they're seen as totally different ones.

The good news, with the new release you're able to manage built-in properties and update their behavior with props like `toStyle`/`fromStyle` (available for `composite` and `stack` types). So here is an example of how would you force to remove alternative border properties on change.
```js
const extendBorder = (editor) => {
  editor.StyleManager.addBuiltIn('border', {
    toStyle(values, { property }) {
      const propWidth = property.getProperty('border-width');
      const width = `${propWidth.getValue()}${propWidth.getUnit()}`;
      const style = property.getProperty('border-style').getValue();
      const color = property.getProperty('border-color').getValue();
      return {
        'border': `${width} ${style} ${color}`,
        'border-top': '',
        'border-right': '',
        'border-bottom': '',
        'border-left': '',
      }
    }
  });
}
grapesjs.init({
  // ...
  plugins: [extendBorder]
})
``` 

The alternative solution would be to set up a [new UI type](https://grapesjs.com/docs/modules/Style-manager.html#customization) for managing the border property in a more advanced way but that for sure requires more effort.
