### ISSUE TITLE
Hide An element in commands

### ISSUE THREAD

**Issue by sanjeevSavitr** [artf/grapesjs#400]
Hi,

I want to hide a particular element when ever we click a toolbar button 

      commands:     {
          defaults: [{
            id:   'sub_menu_item',
            run: function(editor, senderBtn){
				// I want to hide "photostack-1" element
				????
				????
				????
            },
          }],
      }
	  
	  
	  
	  
	  var domc = editor.DomComponents;
	  domc.addType('banner_gallery_portion',
      {
        model: defaultModel.extend({
            defaults: Object.assign({},
              defaultModel.prototype.defaults,
              {
				...
                toolbar: [{
                           attributes: {class: 'fa fa-arrows'},
                           command: 'tlb-move',
                         },{
                           attributes: {class: 'fa fa-plus'},
                           //command: 'tlb-clone',
                             command:'sub_menu_item',
                        }],
				...
                }
              })
          },
          ),

        view: defaultType.view.extend({
                  init() {
        this.listenTo(this.model, 'change:startfrom change:endText', this.updateScript);
        const comps = this.model.get('components');

        // Add a basic countdown template if it's not yet initialized
        if (!comps.length) {
          comps.reset();
          comps.add(`
      		<div class="container">
				<section id="photostack-1" class="photostack photostack-transition photostack-perspective">
				....
				....
				</section>
			</div>

                `
            );
        }

      },

**Comment by artf** [comment]
You can access the element from the model
```js
const selectedModel = editor.getSelected();
const elem = selectedModel.view.el.querySelector('#photostack-1');
elem.style.display = 'none';
```

**Comment by sanjeevSavitr** [comment]
Thanks..
