### ISSUE TITLE
BUG: Can not hold current unit when the first time input have Auto value

### ISSUE THREAD

**Issue by javadsamiee** [artf/grapesjs#4001]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

96.0.4664.93

### Reproducible demo link

https://grapesjs.com/demo.html

### Describe the bug

**How to reproduce the bug?**
1. Create a new block for example Text Block
2. Navigate Dimension > Width (by default is Auto)
3. Change unit to vw
4. then remove Auto and enter a value, for example, 100
5. After press enter key unit will be changed to 100px not 100vw

**What is the expected behavior?**
after changing the unit and entering a value that is not Auto, it should hold the current unit (vw) not change it to px

**What is the current behavior?**
the unit after enter back to default (px)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
By looking at the current demo, seems to be fixed.
