### ISSUE TITLE
Cannot upload images

### ISSUE THREAD

**Issue by gasserol** [artf/grapesjs#401]
Hi, while uploading an image through asset manager, I get the following error:
![bildschirmfoto 2017-10-10 um 15 44 23](https://user-images.githubusercontent.com/4066878/31389758-52b04026-add2-11e7-9c76-eb4f7cb0a127.png)

Assetmanager configuration at editor init looks like 
![bildschirmfoto 2017-10-10 um 15 45 30](https://user-images.githubusercontent.com/4066878/31389787-65209328-add2-11e7-8f6e-85414b026706.png)

Folder exists and is writable.
Can you please help? Many thanks for this excellent software beside this issue :-)

**Comment by artf** [comment]
Your upload endpoint should return a JSON, seems like your is returning an HTML

**Comment by gasserol** [comment]
OK, many thanks, don't know how to solve this.. I'm using a normal apache server on localhost for tests and believe that this endpoint does not answer at all. I will try to implement your solution to the yii2 framework, there I can handle the json response of the endpoint. Many thanks for the imput and your excellent software!

**Comment by mekamleshk** [comment]
@gasserol  you can refer to my code [Here](https://github.com/artf/grapesjs/issues/393)
I was able to upload and retrieve files.

**Comment by gasserol** [comment]
@mekamleshk many thanks for your precious help. I will try to implement as suggested. BR, Oliver

**Comment by artf** [comment]
I close this @gasserol as it seems to be just a server-side issue
