### ISSUE TITLE
BUG: SVG text textcontent not updated when calling getHtml on editor 

### ISSUE THREAD

**Issue by cunj12** [artf/grapesjs#4020]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Chrome v96

### Reproducible demo link

https://jsfiddle.net/1hrLxdba/30/

### Describe the bug

**How to reproduce the bug?**
1. Drag a svg text block to the canvas.
2. Change it's content via the svg-text trait
3. Click on print html

**What is the expected behavior?**
The editor html should be printed with the text element's text content changed.
**What is the current behavior?**
The editor html is printed without the changes that were applied

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
You have to [update the Component content](https://grapesjs.com/docs/api/component.html#components), not the DOM
