### ISSUE TITLE
BUG: When pasting text into text, the view scrolls and loses focus

### ISSUE THREAD

**Issue by mingxin-yang** [artf/grapesjs#4024]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Chrome

### Reproducible demo link

https://grapesjs.com/demo-newsletter-editor.html

### Describe the bug

**How to reproduce the bug?**
1. https://grapesjs.com/demo-newsletter-editor.html use CKeditor, I don’t know if it’s a configuration problem
2. First enter a long content in the text component and scroll to the middle of the screen
3. Then when you paste a piece of text in the middle, the view will scroll, but it is not the pasted position
![录屏 (1)](https://user-images.githubusercontent.com/23076937/147042883-46b7ff63-a172-4b1d-bb43-a0d05ab9f502.gif)

**What is the expected behavior?**
...

**What is the current behavior?**
..

If is necessary to execute some code in order to reproduce the bug, paste it here below:
```js
// your code here
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mingxin-yang** [comment]
@artf

**Comment by artf** [comment]
This issue comes from CKEditor itself so, if there is a patch to apply, it should be applied on the plugin level (I'm not even sure it's possible) as it's not related to the core.

**Comment by bernhardmiller** [comment]
@mingxin-yang 
I had a similar problem with CKEditor and scrolling. For me, it happened when the user pressed the return key. If the grapes document was too long, the canvas scrolled down way to far.

I had to solve the problem in CKEditor itself, by removing this line from the enterkey plugin:
https://github.com/ckeditor/ckeditor4/blob/f6dd30807a1c7cb585f376a38fb13dffd2213a75/plugins/enterkey/plugin.js#L432

Maybe there is a similar solution for your scrolling problem.
