### ISSUE TITLE
Incorporate juice inliner (or similar) to inline css for html email creation

### ISSUE THREAD

**Issue by danfitz36** [artf/grapesjs#403]
the demo shows a newsletter, but I don't think the css gets inlined, which is really needed for better email support.

https://github.com/Automattic/juice

**Comment by artf** [comment]
Actually it does
![schermata 2017-10-11 alle 14 51 19](https://user-images.githubusercontent.com/11614725/31441513-ad0af07c-ae93-11e7-940d-6b988384aac0.png)

**Comment by danfitz36** [comment]
oh that's great, thanks. i didn't get that far in the demo i guess.
