### ISSUE TITLE
BUG: Wrong link and typo in the documentation

### ISSUE THREAD

**Issue by 0xcrypto** [artf/grapesjs#4033]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

N/A

### Reproducible demo link

https://github.com/artf/grapesjs/blob/849a28757dc8dcd059c5ee6e6ac1bfd8b49a78b2/docs/modules/Blocks.md?plain=1#L138

### Describe the bug

Just a small typo with a localhost link.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
Thanks @0xcrypto will be fixed 👍
