### ISSUE TITLE
BUG: When pasting plain text into text element in Chrome

### ISSUE THREAD

**Issue by denisdal** [artf/grapesjs#4037]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Chrome 96.0.4664.110

### Reproducible demo link

I haven't a public one

### Describe the bug

**How to reproduce the bug?**
1. Use Chrome and Grapes newsletter Editor
2. drag a "Text" element into the page and write something in it.
3. In the same element, press "Enter" so you have a new line and paste some plain text
4. Save the template somewhere in order to have it if you reload the page

**What is the expected behavior?**
Have a "Text" element with all the editable text inserted before

**What is the current behavior?**
Grapes generate a "Box" element with inside the written text that is no longer editable and N "Text" element's for each rows pasted before (editable)

This behavior apply only Chrome but may affect other Webkit's browsers.
Thanks

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
The default exported template in HTML doesn't have any reference of the Text component so, there is no way to know from all the possible tags where the text component should be identified. This is why when you [store and reload templates](https://grapesjs.com/docs/modules/Storage.html#store-and-load-templates) you should always rely on JSON data of the project and not on HTML/CSS.
One option would be to export "re-importable" HTML with `data-gjs-*` attributes.
