### ISSUE TITLE
BUG: When drag and drop block into editor in Chrome, error thrown

### ISSUE THREAD

**Issue by sridhar391** [artf/grapesjs#4039]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Chromw 96.0.4664.45

### Reproducible demo link

https://thanhtunguet.github.io/grapesjs-react/?path=/story/grapesjsreact--primary

### Describe the bug

**How to reproduce the bug?**
1. Drag and drop the basic blocks in editor

**What is the expected behavior?**
1. Drag and drop the basic blocks in editor and it should be shown in the editor

**What is the current behavior?**
Drag and drop the basic blocks in editor, console error thrown

The Drag and Drop of the basic blocks in editor working correctly in firefox browser

https://user-images.githubusercontent.com/17172525/147826024-5ac9ea88-7ea3-4a23-82ea-75762288017e.mp4

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
From your demo, I can see you're using the `0.16.45` version. 
Please open the bug issue only for the latest version.
