### ISSUE TITLE
BUG: Icons are not loading when loading within an angular application

### ISSUE THREAD

**Issue by sanjanaadeshra** [artf/grapesjs#4042]
### GrapesJS version

- [x] I confirm to use the latest version of GrapesJS

### What browser are you using?

Chrome

### Reproducible demo link

https://stackblitz.com/edit/angular-dei45q?file=src%2Fapp%2Fapp.component.ts

### Describe the bug
Added an attached image to give an idea of what the editor looks like

**What is the expected behavior?**
 Need to load the grapejs ediotr

**What is the current behavior?**
Editor loads, but none of the icons are visible. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
![Screenshot 2022-01-02 at 3 48 52 AM (2)](https://user-images.githubusercontent.com/37732345/147861318-769db15d-62f6-4bb7-9819-6c89c022d5be.png)

**Comment by sanjanaadeshra** [comment]
I was able to resolve this issue by adding font awesome icons css directly to the grape.min.css file. 
I am not sure why that had to be done since the CSS was being imported already, its working with that workaround, but it would be better if a cleaner solution can be suggested.

**Comment by artf** [comment]
Your demo doesn't seem to load, and the grapesjs version you're using there is quite outdated (`0.14.15`). 
Please upgrade and next time open the new bug issue relative to the latest version.
