### ISSUE TITLE
Hyphen changed to " by editor messes up modern coding.

### ISSUE THREAD

**Issue by clonefunnels** [artf/grapesjs#4058]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Chrome

### Reproducible demo link

Not necessary - Obvious issue

### Describe the bug

This is what the code needs to be:

data-zanim-lg='{"from":{"opacity":1,"x":70},"to":{"opacity":1,"x":0},"ease":"CubicBezier","duration":0.8,"delay":0.3}' data-zanim-xs='{"from":{"opacity":1,"y":-37},"to":{"opacity":1,"y":0},"ease":"CubicBezier","duration":0.8,"delay":0.3}'

This is what the editor changes it to:

data-zanim-lg="{& quot ; from& quot ;:{& quot ;opacity& quot ;:1,& quot ;x& quot ;:70},& quot ;to& quot ;:{& quot ;opacity& quot ;:1,& quot ;x& quot ;:0},& quot ;ease& quot ;:& quot ;CubicBezier& quot ;,& quot ;duration& quot ;:0.8,& quot ;delay& quot ;:0.3}" data-zanim-xs="{& quot ; from& quot ;:{& quot ;opacity& quot ;:1,& quot ;y& quot ;:-37},& quot ;to& quot ;:{& quot ;opacity& quot ;:1,& quot ;y& quot ;:0},& quot ;ease& quot ;:& quot ;CubicBezier& quot ;,& quot ;duration& quot ;:0.8,& quot ;delay& quot ;:0.3}" 

This would be okay if the editor automatically changed it back when it finished but it doesn't.  

Please fix the editor to allow a hyphen instead of fubarring all modern coding.   

I do see that you allow hyphens after the =" so I see no reason why you can't allow them on the outside.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
This is not a bug, but how attribute escaping works in HTML.
```js
domEl.innerHTML = `<div data-attr='{"key": "value"}'>Text</div>`;
domEl.innerHTML;
// -> '<div data-attr="{&quot;key&quot;: &quot;value&quot;}">Text</div>'
```
