### ISSUE TITLE
BUG: The new version v0.18.1 brokes the script to make !important on styleable:change

### ISSUE THREAD

**Issue by jloguercio** [artf/grapesjs#4079]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Chrome v96

### Reproducible demo link

No demo

### Describe the bug

I use the code below to make all styles to !important 

`// Make all styles important to override element classes
            editor.on('styleable:change', (model, property) => {
                const value = String(model.getStyle()[property]);
                if (value.indexOf('!important') === -1) {
                    model.addStyle({ [property]: value + ' !important' });
                }
            });`

I check this solution in this issue :
            
https://github.com/artf/grapesjs/issues/1041#issuecomment-382545102

but after the 1 hour ago update this script doesn't work anymore

   

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
Hey man, I didn't even finish writing the release 😅  calm down...
Read here please https://github.com/artf/grapesjs/releases/tag/v0.18.1 Style Manager was updated heavily, if something doesn't work, nobody forces you to upgrade...
