### ISSUE TITLE
How to update toolbar of component?

### ISSUE THREAD

**Issue by dong-dev** [artf/grapesjs#408]
![image](https://user-images.githubusercontent.com/21217537/31474879-b2d70e2a-af27-11e7-99a1-c5a982683495.png)
Hi Artf, i was added new command to editable component, update style work well  but i don't know how to update this toolbar after component updated (update align icon for example), do you have any suggetion?
`        defaultCommands['testCommand'] = {   

                run(ed) {   
                    var sel = ed.getSelected();  
                    var styles = sel.get('style');  
                    var tbs = sel.get('toolbar');  
                    var tmpTbs = [];  
                    var tmpStyles = {};  
                    tbs.map((tb) => {  
                        if (tb['command'] == 'testCommand') {  
                            switch (styles['text-align']) {  
                                case 'center':  
                                    tb['attributes'] = { class: 'fa fa-align-right' };  
                                    tmpStyles['text-align'] = "right";  
                                    break;  
                                case 'left':  
                                    tb['attributes'] = { class: 'fa fa-align-center' };  
                                    tmpStyles['text-align'] = "center";  
                                    break;  
                                case 'right':  
                                    tb['attributes'] = { class: 'fa fa-align-left' };  
                                    tmpStyles['text-align'] = "left";  
                                    break;  
                                default:  
                                    tb['attributes'] = { class: 'fa fa-align-center' };  
                                    tmpStyles['text-align'] = "center";  
                                    break;  
                            }  
                        }  
                        tmpTbs.push(tb);  
                    })  
                    sel.set({  
                        'style': tmpStyles,  
                        'toolbar': tmpTbs  
                    });   
                }  
            };`

**Comment by artf** [comment]
You can set a listener on component update
```js
editor.on('component:update', () => {
     editor.runCommand('testCommand');
})
```
Be aware that with `var styles = sel.get('style')`  you get the style of the component and not what is selected in Style Manager (if the component has classes, the css rule will be selected)
