### ISSUE TITLE
Remove some initial styles from frame canvas

### ISSUE THREAD

**Issue by jloguercio** [artf/grapesjs#4082]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Chrome v96

### Reproducible demo link

No demo

### Describe the bug

When i load some template, the editor add some initial styles like the image below, how can i set or remove some or that styles? for example : i need to remove the webkit scrollbar styles because it modify all the inner scrollbars of my template.

![test123](https://user-images.githubusercontent.com/12191804/150230086-60edec9c-c0a8-45dc-a91b-4ec583952266.PNG)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
Check the main editor config options (eg. `baseCss`) https://github.com/artf/grapesjs/blob/dev/src/editor/config/config.js
And please, don't use issue bugs for questions, open a discussion in that case.

**Comment by jloguercio** [comment]
Thank you very much
