### ISSUE TITLE
Can't loaded in storageManager of 0.12

### ISSUE THREAD

**Issue by nhinq** [artf/grapesjs#409]
Im using type: 'remote', but it can't loaded to canvas

**Comment by mekamleshk** [comment]
@nhinq you can refer to my code [Here](https://github.com/artf/grapesjs/issues/393)
I was able to upload and retrieve files.

**Comment by artf** [comment]
follow the issue posted by Kamlesh

**Comment by nhinq** [comment]
Ok Thank you - will try it
