### ISSUE TITLE
BUG: "Using draggableComponents: false" still drag (clone?) some elements if i try to edit text

### ISSUE THREAD

**Issue by jloguercio** [artf/grapesjs#4099]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Chrome v96

### Reproducible demo link

https://jsfiddle.net/809enL2w/1/

### Describe the bug

I use domComponents: { draggableComponents: false }, to avoid to drag components, only when you drag with the arrow in toolbar, but if do a fast select or to edit a text or something it still drag / clone / copy the selected text and other components

https://user-images.githubusercontent.com/12191804/150874942-73b3b714-5a9b-4e87-81b4-56ecd4dfb0b9.mp4

it is a bug? or how can i disable that feature, its very  annyoning if a trying to do a fast select in the text to edit it or if i accidentally drag something inside the canvas

Thanks

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
Yeah seems like the native HTML5 D&D still works with text selection, I'll try to fix it.
