### ISSUE TITLE
PHP CMS  template

### ISSUE THREAD

**Issue by asimakos** [artf/grapesjs#41]
Congrats for your great and promising web template platform! 

I would like to design a PHP template for CMS using this web platform that has got the following structure regarding nested div components:

![body](https://cloud.githubusercontent.com/assets/15226087/22790905/aeb13982-eef8-11e6-9aa3-c51ac34697f8.PNG)

These classes are defined via an external CSS file that is linked by `<link rel="stylesheet" href= `
According to your wikis this could be accomplished with 
![component](https://cloud.githubusercontent.com/assets/15226087/22791084/40db6cba-eef9-11e6-8522-74020721ef30.PNG)  
The real problem that lies to me is how can i set up the Style Manager and when i select a specific component a specific class via external CSS pops up in the class box of Style Manager. In other words i want to appear for the selected external div component only the simple_wrapper class according to the structure and etc.
Afterwards i want inside these div components to place PHP output code for display of content such as: 
![content](https://cloud.githubusercontent.com/assets/15226087/22791111/5dbcc8d8-eef9-11e6-9d4a-7257b0dd2bd3.PNG)
or for modules:
![modules](https://cloud.githubusercontent.com/assets/15226087/22791165/7cd1f7fc-eef9-11e6-8422-cb3a735534a0.PNG)

Is that possible, any code help?

Regards

**Comment by artf** [comment]
Hi @asimakos, great questions.
Unfortunately, GrapesJS is not able to fetch style from an external CSS file, so you'll see it applied but won't be readable by the Style Manager. So you have to make style available at the beginning, eg.
```html
<div id="gjs">
  <div class="txt-red">Hello world!</div>
  <style>.txt-red{color: red}</style>
</div>

<script type="text/javascript">
  var editor = grapesjs.init({
      container : '#gjs',
      fromElement: true,
  });
</script>
```
By the way, If the style is not immediately available, you could add it asynchronously.
To get the idea of how CSS Rules should be, in the way to be accepted by the editor, refer please to #28 

About the PHP code is not a problem, for the editor, it's just a text node. You could also create specific [Blocks](https://github.com/artf/grapesjs/wiki/Blocks) for those:

```js
editor.BlockManager.add('module-one', {
  label: 'Module 1',
  content: '<div class="simple_pad"><?php $eDoc->component(); ?></div>',
});
```

**Comment by asimakos** [comment]
Thanks for your reply! That was for me an easy scenario to build a PHP CMS template, but i would like to ask your help for a more responsive PHP CMS template (difficult scenario).
At the beginning of the template before html tag, i would like to include the following PHP snippet:

![elx1](https://cloud.githubusercontent.com/assets/15226087/22824671/e767937e-ef99-11e6-878a-37e641797227.PNG)
Afterwards via an installed XML file: 
![elx2](https://cloud.githubusercontent.com/assets/15226087/22824968/a32d70f0-ef9b-11e6-8a8d-ddd7aeeb3c63.PNG)
i define the following _auxilliary PHP class_ to XML get value parameters:
![elx3](https://cloud.githubusercontent.com/assets/15226087/22825000/c5dfb7b6-ef9b-11e6-9dce-5afa4a2dfaff.PNG)
In the above PHP class, i define some dynamic css classes and finally extract them to the PHP CMS template:
![elx4](https://cloud.githubusercontent.com/assets/15226087/22825115/64c0422e-ef9c-11e6-8467-ad655b28c6e1.PNG)

Is that scenario possible via Grapesjs, i could email you the PHP CMS template, if there is any problem!

Regards

**Comment by artf** [comment]
@asimakos all you'll need to do is to save your templates in DB

 ID | template_name | html | css
---|---|---|---
1| My Template|`<div ...><?php ... ?>...`|`.cls{...}`
2|...|...|...

Then, all the back-end part is up to you. You'll fetch data from DB and paste them somewhere in page following the CMS-specific rules.

Of course, if you use server-side code inside your templates, like `<?php ... ?>`, you should eval it before rendering (commonly, this is handled by the CMS), otherwise, you can define your own variables, eg. `<div> {{SOME_VAR}} </div>`, and replace them later, before rendering.

**Comment by asimakos** [comment]
I think a json file would be a far better option instead of a table DB by using  heavy SQL code that might not work.

Thanks a lot!

**Comment by nhinq** [comment]
We can write to a new for template like:
index.html, about-us.html, contact.html
