### ISSUE TITLE
example on video component

### ISSUE THREAD

**Issue by mohammad-aqajani** [artf/grapesjs#410]
is there any example for adding video component the same way as adding images which have uploading dialog ??
any code would be appreciated!

`<div controls="" src="http://127.0.0.1:8000/media/PyQt4_Python_GUI_6_File_Browse_Button_H9wtiVE.mp4" onmousedown="return false" class="gjs-comp-selected" style="height:607px;">

<video class="gjs-no-pointer" style="height: 100%; width: 100%;" controls="" src="http://127.0.0.1:8000/media/PyQt4_Python_GUI_6_File_Browse_Button_H9wtiVE.mp4"></video>

</div>`

it puts it in div...

**Comment by artf** [comment]
No, but you can create a new Component by following this
https://github.com/artf/grapesjs/wiki/Components and #286
