### ISSUE TITLE
BUG: AssetManager events not working

### ISSUE THREAD

**Issue by cusmai** [artf/grapesjs#4110]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Chrome

### Reproducible demo link

NA

### Describe the bug

AssetManager events are not fired. The file gets uploaded correctly but events are not notified:

```js
     // Asset Event Listners

    editor.on('asset:upload:start', () => {
      // The upload is started
      console.log('Upload started');
    });

    editor.on('asset:upload:end', () => {
      // The upload is ended (completed or not)
      console.log('Upload ended');
    });

    editor.on('asset:upload:error', (err) => {
      // Error handling
    });

    editor.on('asset:upload:response', (response) => {
      // Do something on response
      console.log(response);
    });
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by timramseyjr** [comment]
@cusmai Did you ever figure this one out? I am getting `asset:open` and `asset:close`, but I am not getting any of the events you listed either. 

I am using the following and the two events I mentioned are the only related `asset` events I am getting.

```
editor.on('asset', (evt) => {
	console.log(evt);
});
```

**Comment by ALTITUDE-DEV-FR** [comment]
Same for me not working :(
