### ISSUE TITLE
Controls drag and drop not working

### ISSUE THREAD

**Issue by ramkumar65** [artf/grapesjs#412]
Hi,
Grapes js html template designer is perfect, but the demo page controls drag and drop incorrectly placed to page. please help me......:)

**Comment by artf** [comment]
Seems to work fine on my side, provide a screencast of the issue, please

**Comment by ramkumar65** [comment]
![controls drog and drop issue](https://user-images.githubusercontent.com/32733822/31494572-7ad75c1a-af71-11e7-9bcb-47e0a0e3942d.png)
here i attach screenshot. reply soon as possible. Thanks for reply

**Comment by artf** [comment]
You should drop inputs/labels only inside form

**Comment by ramkumar65** [comment]
Yes, now working. thanks for your reply. i have another one clarification, How to drag a form element without any controls.

**Comment by ramkumar65** [comment]
artf, i need file upload control, if it is available  in grapes js

**Comment by ramkumar65** [comment]
How to add select drop down options?

**Comment by ramkumar65** [comment]
How can i add options for drop down control... please suggest

**Comment by artf** [comment]
https://github.com/artf/grapesjs/wiki
