### ISSUE TITLE
BUG: component.remove() in 'component:mount' does not remove the rendered view

### ISSUE THREAD

**Issue by m-jojo-s** [artf/grapesjs#4136]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Chrome Version 98.0.4758.80 (Official Build) (arm64)

### Reproducible demo link

https://jsfiddle.net/Lsjhxczp/10/

### Describe the bug

**How to reproduce the bug?**
1. Setup the component:mount hook to remove mounted component
2. Add a new block/component

**What is the expected behavior?**
The new component gets removed, both model and view.

**What is the current behavior?**
Only the model is removed, view stays in place and isn't re-rendered after removal.

If is necessary to execute some code in order to reproduce the bug, paste it here below:
```js
editor.on('component:mount', component => {
    if (component.is('image')) {
      component.remove();
    }
});

// the following has no effect
/* editor.on('component:create', component => {
    if (component.is('image')) {
      component.remove();
    }
}); */
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
Yeah, the problem here is the DOM node is created but not yet appended to the parent. You can defer the removal via setTimeout but that will still trigger the image activation.
Probably I'll move that event once the node is appended.
