### ISSUE TITLE
Unexpected behavior in style manager

### ISSUE THREAD

**Issue by yadavAtIrisdame** [artf/grapesjs#4138]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Version 1.35.101 Chromium: 98.0.4758.87 (Official Build) (64-bit)

![padding](https://user-images.githubusercontent.com/97948548/153704600-39c7336b-4837-444d-8b8c-fd48b9cb6c74.gif)

### Reproducible demo link

https://codesandbox.io/s/strange-sun-qgdcq?file=/index.js

### Describe the bug

**How to reproduce the bug?**
1. drop the component in canvas
2. select the component and apply some margin and padding

**What is the expected behavior?**
...should apply margin and padding when we give some margin and padding.

**What is the current behaviour?**
Sometimes it is working and sometimes it behaves unexpectedly  

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
Thanks for the report @yadavAtIrisdame but I'm not able to reproduce it from your demo or the official one. Can you describe the exact steps?

**Comment by yadavAtIrisdame** [comment]
I'm unable to reproduce this bug. in most cases, The Style Manager works as expected. but, all of a sudden, they start acting like(shown in image). Particularly margin and padding properties.

![](https://user-images.githubusercontent.com/97948548/153704600-39c7336b-4837-444d-8b8c-fd48b9cb6c74.gif)

**Comment by artf** [comment]
Sorry but unfortunately without the proper reproducible demo, I can't do much.
I'll be happy to fix it if anybody is able to provide the reproducible steps.
