### ISSUE TITLE
BUG: 0.18.2 / 0.18.3 removes all on... HTML attributes when block is drag-dropped in the builder

### ISSUE THREAD

**Issue by varadero** [artf/grapesjs#4148]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Chrome v99

### Reproducible demo link
https://jsfiddle.net/jLo3qh7s/10/

### Describe the bug

**How to reproduce the bug?**
1. Create a block with content `<input oninput="alert('123)" />`
2. Put that block into the builder
3. Look at the HTML code

**What is the expected behavior?**
All `on...` HTML attributes are retained

**What is the current behavior?**
All the `on...`  HTML attributes are removed

NOTE:  Grapesjs 0.18.1 does not have this problem - 0.18.2 and 0.18.3 has it.

If is necessary to execute some code in order to reproduce the bug, paste it here below:
```js
// your code here
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Ju99ernaut** [comment]
That is the expected behaviour as stated in the release notes for 0.18.3

**Comment by artf** [comment]
Correct. In case you need to enable unsafe attributes (at your own risk), you can do it via `config.parser.optionsHtml.allowUnsafeAttr` option.
