### ISSUE TITLE
Add Setting button to custom component.

### ISSUE THREAD

**Issue by HarshOB** [artf/grapesjs#417]
Hello, 
 
How can I create a setting or you can say edit button for my custom component? 

LIke 4th option on this image: 

![screenshotfrom2017-10-1316-01-00](https://user-images.githubusercontent.com/28950214/31542567-255f7316-b030-11e7-99d7-b9dfc8001216.jpg)

**Comment by ateshuseyin** [comment]
Hi @HarshOB,

It is simple as in image https://github.com/artf/grapesjs/blob/dev/src/dom_components/model/ComponentImage.js#L32

**Comment by HarshOB** [comment]
Hello @ateshuseyin  

I don't want the same editor as an image I want to build my own. I just want to add that icon to my component and when I click on that icon I want to display area through the user can add text, image, HTML code etc and that will be reflected in that component.

**Comment by ateshuseyin** [comment]
The above link I referenced before is only for adding button to toolbar. I think you should just follow below steps to complete your task;

1. Create/Implement a editor according to your needs. [grapesjs-aviary](https://github.com/artf/grapesjs-aviary) uses aviary editor ([see](https://github.com/artf/grapesjs-aviary/blob/master/src/main.js#L60))
2. Define a command which is capable to open your editor  like grapesjs-aviary [see](https://github.com/artf/grapesjs-aviary/blob/938d61148dc8a160dc412813e47d77cf2e869b7b/src/main.js#L84)
3. Define toolbar button as I referenced before which runs your command 

Thats all.

**Comment by artf** [comment]
@HarshOB Create your [Component](https://github.com/artf/grapesjs/wiki/Components) (or extend one) and add your toolbar buttons (as suggested by @ateshuseyin)

**Comment by sakshigarg9** [comment]
> Hi @HarshOB,
> 
> It is simple as image does https://github.com/artf/grapesjs/blob/dev/src/dom_components/model/ComponentImage.js#L32

Can you please guide me on how this can be incorporated in a grapesjs-preset-webpage, I am unable to get the desired result while using this code in my project.

**Comment by artf** [comment]
@sakshigarg9 https://github.com/artf/grapesjs/issues/266#issuecomment-470329181
