### ISSUE TITLE
BUG: Text element does not work properly

### ISSUE THREAD

**Issue by Ameeko** [artf/grapesjs#4173]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Chrome v98

### Reproducible demo link

https://grapesjs.com/demo.html

### Describe the bug

I opened a notepad (Win11)
I wrote this in the notepad: **test [enter] test [enter] test [enter]**
I selected the entire text and copied it to the clipboard
I created a "Text" element in the GrapesJS editor
I copied the text from the clipboard into the "Text" element
I clicked outside
This will be the result
![image](https://user-images.githubusercontent.com/61547701/156581413-10b9a9f6-946e-4e6c-b291-a917fef5b67d.png)

If I enter this text into a "Text" element manually 
**test [enter] test [enter] test [enter]**
and click outside, the text will be placed in 1 "Text" element. 
This is good.
Unfortunately, people usually paste the text.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
This is not directly related to GrapesJS, this all depends on how the pasted content is stored from the external application and which tags are used for the new lines.

**Comment by Ameeko** [comment]
The text was a plain text, it had no tags.
I tested with \n and \r\n line breaks, it doesn't work well.
Unnecessary tags appear in GrapesJS when inserting plain text.

**Comment by Ameeko** [comment]
Can anyone help me with this?

**Comment by Joshmamroud** [comment]
@Ameeko & @artf I'm also having this issue. Has anyone found a fix for this?
