### ISSUE TITLE
BUG: Refresh page we will lost body/wrapper background color

### ISSUE THREAD

**Issue by javadsamiee** [artf/grapesjs#4174]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Chrome 98.0.4758.109

### Reproducible demo link

https://jsfiddle.net/szLp8h4n

### Describe the bug

**How to reproduce the bug?**
1. "Body (Selected #wrapper) -> Decorations -> Background Color and set a color
2. Save changes then refresh the page

**What is the expected behavior?**
Show background color after refresh page and keep Background Color settings

**What is the current behavior?**
the body has no background and the Background Color setting is none

I checked saved data and found that we saved wrapper id with its styles while after refresh page wrapper get new id every time.

<img width="936" alt="image" src="https://user-images.githubusercontent.com/65819265/156588594-a55fb652-5044-44de-9468-5960e9e38d9f.png">

<img width="886" alt="image" src="https://user-images.githubusercontent.com/65819265/156588892-386065be-1b61-4c48-a0c2-91c61a7cbd20.png">

While other blocks have an id that will not change after refreshing the page.

How we can apply background color to the wrapper and keep background color settings?

I have set these settings in the init as well:
`
storageManager: { type: null },
        avoidInlineStyle: true,
        avoidInlineStyles: 0,
`

The other blocks can save background color without any problem and just have problems with wrapper/body

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
Hi @javadsamiee thanks for the report. This is actually an old issue #2834 which I'm trying to address for the next release (I close this issue in favor of the old one).
