### ISSUE TITLE
BUG: Offset lines are missing when reload frame

### ISSUE THREAD

**Issue by sandeepyerkala** [artf/grapesjs#4175]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Chrome 99.0.4844.51

### Reproducible demo link

https://jsfiddle.net/rakam/5o8te64y/19/

### Describe the bug

**How to reproduce the bug?**
1. Add few components.
2. After adding, reload frame by clicking on the right context menu.
3. Offset lines are missing

Please check the below gif

![GrapesjsFrameReload](https://user-images.githubusercontent.com/47555656/156590895-2f8b094b-4833-459e-8a8e-b03efbe94e01.gif)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
Sorry but I don't see right now any point of supporting/fixing the native reload of the iframe.
