### ISSUE TITLE
Can't replace image if it's inside a link

### ISSUE THREAD

**Issue by justvinz** [artf/grapesjs#418]
Hi, 

If import this code inside the editor:

```
<a href="http://www.google.com">
	<img src="http://via.placeholder.com/350x150">
</a>
```

And double click the image to change it, when I choose a new image from the modal, nothing happens.

**Comment by artf** [comment]
Ok, probably I have to set the Link Component not editable if children nodes are not texts.
At the moment, you have to set it explicitly
```js
<a href="http://www.google.com" data-gjs-editable="false">
	<img src="http://via.placeholder.com/350x150">
</a>
```
