### ISSUE TITLE
Adding New Elements in commands

### ISSUE THREAD

**Issue by sanjeevSavitr** [artf/grapesjs#419]
commands:{
			{
            id:   'sub_menu_item',
            run: function(editor, senderBtn){
                
                const comp = editor.getSelected();
                comp.view.el.querySelector('[data-js=submenu_container]').innerHTML += '<a class="navbar-menu-link">Sub Menu Item</a>';

            },
          },
	}

This can add **Sub Menu Item**  to the container. But I am unable to select it. I tried with AppendChild also. But the result is same. I should be able to edit the newly added component. Pls help me

**Comment by artf** [comment]
Read more about [how components work](https://github.com/artf/grapesjs/wiki/Components#how-components-work)
You have to add components via model (eg. `model.get('components').add('<div>...</div>')`) if you want them to be selectable (you can't select elements without models). Like you did, it's just a static content for the editor
