### ISSUE TITLE
BUG: We are trying to store the data from grapesJS editor in Angular 10 application, getting CORS error, image attached below

### ISSUE THREAD

**Issue by mastercorp-usa** [artf/grapesjs#4191]
### GrapesJS version

- [x] I confirm to use the latest version of GrapesJS

### What browser are you using?

Chrome  99.0.4844.5

### Reproducible demo link

https://jsfiddle.net/ct5r4kvg/

### Describe the bug

**How to reproduce the bug?**
1. Integrated in Angular 10 application with following code
2. while running we are getting CORS error in angular application where postman working fine

**What is the expected behavior?**
We need to add the extra object other than grapesJS properties in API request

**What is the current behavior?**
We are unable to add extra properties also getting CORS error

If is necessary to execute some code in order to reproduce the bug, paste it here below:

var editor = grapesjs.init({
      container: '#gjs',
      style: '.txt-red{color: red}',
      plugins: ['gjs-preset-newsletter', 'gjs-blocks-basic'],
      pluginsOpts: {
        'gjs-blocks-basic': { blocks: ['video'] }
      },
      assetManager: {
        assets: [
          'https://siteurl.edu/uploads/screen-shot-2017-11-29-at-9-17-08-am.png',
          'https://siteurl.edu/uploads/screen-shot-2017-11-16-at-9-21-05-am.png',
        ],
        storeOnChange: true,
        storeAfterUpload: true,
        upload: "/upload-editor-media",
      },
      storageManager: {
        type: 'remote',
        stepsBeforeSave: 2,
        storeComponents: false,
        storeStyles: true,
        storeHtml: true,
        storeCss: true,
        contentTypeJson: true,
        headers: {
          Authorization: `Bearer ${this.currentUser.accessToken}`
        },
        Pragma: 'no-cache',
        Expires: '0',
        urlStore: "https://a8devapi.azurewebsites.net/api/EC_Email_Templates/GrapeJS",
        urlLoad: "/load-template/2",
        params: {},   // For custom values on requests

      }
    });

by using this code getting error CORS, like below

![Screenshot (54)](https://user-images.githubusercontent.com/74088643/157727897-e499b4ca-554e-4578-bda9-2e8f4ef15d83.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mastercorp-usa** [comment]
please anybody help us for this problem, its very urgent for me

**Comment by lalitog** [comment]
My server side script is in PHP so i added this code in my script and it works fine for me - 

header('Access-Control-Allow-Origin: *');
header('Access-Control-Allow-Methods: GET, POST');
header("Access-Control-Allow-Headers: X-Requested-With");

**Comment by artf** [comment]
CORS issues have nothing to do with GrapesJS
