### ISSUE TITLE
Drag boundary issue with dragMode: absolute/translate

### ISSUE THREAD

**Issue by drashtibpatel** [artf/grapesjs#4192]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

chrome, firefox

### Reproducible demo link

https://jsfiddle.net/drashti/9xk5ph8j/1/

### Describe the bug

I am using the Grape JS builder for my client to setup the builder and templates. For that I want the setDragMode "absolute or Translate" so based on that elements can be set beside each other.
But after doing it the element goes out of canvas area. I want to restrict it same like the Normal Drag mode but position should be manage absolute way.
Is there any way to restrict elements to go outside the canvas area?

Please refer below image for the reference.
https://www.awesomescreenshot.com/image/23890163?key=97ac62df006e427f0af7fb82fd005e29
![image](https://user-images.githubusercontent.com/78471147/157850320-434a1239-59f0-45e4-a5bb-e28858b48450.png)

Thanks

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
No, at the moment is not possible. The dragMode is not real public and documented feature so I'm collecting all the issues and features to support here: https://github.com/artf/grapesjs/issues/3770#issuecomment-944915841

**Comment by sathudeva7** [comment]
@artf any update on this
