### ISSUE TITLE
BUG: Text disappears if pasted for a second time in text block

### ISSUE THREAD

**Issue by varadero** [artf/grapesjs#4195]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Chrome 99

### Reproducible demo link

https://grapesjs.com/demo.html

### Describe the bug

**How to reproduce the bug?**
1. Open https://grapesjs.com/demo.html and delete all sample sections
2. Place one "Text section"
3. Open a text editor and type 3 lines of text. Something like this:
```
Line 1
Line 2
Line 3
```
4. Copy the 3 lines from the text editor
5. Go back to GrapesJS demo page and double click the text section just before the word `consecterur` (other word would work too)
6. Press `CTRL+V` to paste the text
7. Click outside to commit the changes
8. Hover your mouse over the `Line 2` and notice it is its own `Text` element
9. Double click on `Line 2` just before the `2`
10. Press `CTRL+V` to paste the same 2 lines text
11. Click outside to commit the changes

**What is the expected behavior?**
The text that was pasted the second time should be kept where it was pasted

**What is the current behavior?**
The text that was pasted the second time disappears

If is necessary to execute some code in order to reproduce the bug, paste it here below:
```js
// your code here
```

Screenshots of the steps:
- Go to https://grapesjs.com/demo.html and delete all sample sections. Put one "Text section":
![image](https://user-images.githubusercontent.com/7610713/158359978-d6d41d23-bd87-4005-a8c4-2d45324599ae.png)
- Open text editor, type 3 lines and copy them. Double click on the text in the text section and move the caret just before the word `consecterur` and press CTRL+V to paste the 3 lines and click outside to commit the changes:
![image](https://user-images.githubusercontent.com/7610713/158360242-44bdb21f-84cf-49f4-915c-183be625d388.png)
- Double click on the second line and press CTRL+V again:
![image](https://user-images.githubusercontent.com/7610713/158360668-fee288b4-cbe0-47a2-92af-f2a398ff4fbd.png)
- Now click outside to commit the second paste - the last pasted lines disappear:
![image](https://user-images.githubusercontent.com/7610713/158360784-6a4d2287-1376-4320-b402-ba023853a6f4.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by varadero** [comment]
I can confirm that this problem occurs only with Grapesjs 0.18.3 - I downgraded to 0.18.2 and the problem does not occur. Older versions are OK too.

**Comment by jmaks1** [comment]
> I can confirm that this problem occurs only with Grapesjs 0.18.3 - I downgraded to 0.18.2 and the problem does not occur. Older versions are OK too.

in version 0.18.2, nested components were not created inside the text.

**Comment by UnlimNET** [comment]
@artf +1

> @artf The problem is relevant to the latest version. (v0.19.4)
> 
> The bug occurs if you copy and paste a nested component while editing text. A regular paste (cmd + v) copies all html, including id, and after removing focus, html with identical id is deleted.
