### ISSUE TITLE
Is it possible to group blocks

### ISSUE THREAD

**Issue by bhoot-biswas** [artf/grapesjs#42]
Hi, I have passion for the fantastic plugin. However, is it possible to group blocks? Will you please give me a hit to do this, I will do the rest? 

Regards,
Bhoot

**Comment by artf** [comment]
If you mean grouping blocks inside the UI, there is still no category yet (maybe soon), but you can actually create groups manually and move blocks via js, all the events will be still attached, so you should be able to drag them inside the canvas.
