### ISSUE TITLE
Problems at the beginning of reading souce code

### ISSUE THREAD

**Issue by momu-smartcoach** [artf/grapesjs#420]
I'm reading the source code from grapesjs,but i can't find the  module cash-dom and `underscore`
`
import $ from 'cash-dom'; 
import { defaults } from 'underscore';

`
anyone can help me? I'm a beginner，thank you!

**Comment by momu-smartcoach** [comment]
i'm try to replace ‘dist/grapes.min.js’  with 'src/index.js' in the dev demo, But it failed，anyone can tell me how to use the souce code，thank you!

**Comment by artf** [comment]
Sorry @momu-smartcoach but before diving in grapesjs's code I'd recommend to start with something more basic, check some of these:
https://github.com/mbeaudru/modern-js-cheatsheet
https://github.com/getify/You-Dont-Know-JS
https://docs.npmjs.com/getting-started/what-is-npm
