### ISSUE TITLE
BUG: Style click state bug in every element

### ISSUE THREAD

**Issue by ronaldohoch** [artf/grapesjs#4208]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Brave Last, tested on chrome last and Safari Last.

### Reproducible demo link

https://grapesjs.com/demo.html

### Describe the bug

**How to reproduce the bug?**
0. I have a video: https://www.loom.com/share/508e91098bf247bd93d525f2efa00a36
1. Go to demo page
2. Select any element...
3. Set the state as `click`
4. Edit any border radius
5. Leave the element clicking in other element
6. First bug: The UI will get the `click` state style and after will turn to normal state
7. Second bug: refresh the page, normal refresh or clear the cache, will you see the styled `click` state before and it don't leave. I need to clear the canvas to get thinks work normally
8. If you inspect the selected element with developer tools as i made in the video, you will see that the element gjs-selected have the styles made before as `click` state

**What is the expected behavior?**
When i change the element, the `click` state didn't goes to all elements when clicked 

**What is the current behavior?**
`click` state set the styles to .gjs-selected element

If is necessary to execute some code in order to reproduce the bug, paste it here below:
No.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ronaldohoch** [comment]
@artf I couldn't run it locally because several tests didn't pass, is it like that with you too? Can I try to fix them?
e.g.: 
![image](https://user-images.githubusercontent.com/2287371/160130276-227ecfa1-e1cf-459c-971d-590ae684f209.png)

**Comment by artf** [comment]
@ronaldohoch update tests on dev

**Comment by ronaldohoch** [comment]
@artf worked! Thank you 😊
