### ISSUE TITLE
BUG: Super large RTE buttons

### ISSUE THREAD

**Issue by confettidc** [artf/grapesjs#4213]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Firefox 98.0.2 (64 bit)

### Reproducible demo link

https://grapesjs.com/demo.html

### Describe the bug

**How to reproduce the bug?**
Just go to demo site using Firefox

**What is the expected behavior?**
Normal sized rte buttons show appear (below in Chrome):
![圖片](https://user-images.githubusercontent.com/5524183/160108524-a92f13ec-f7a6-4fd2-9c1f-ffe4887c788a.png)

**What is the current behavior?**
Super large rte buttons appeared when edit text
![圖片](https://user-images.githubusercontent.com/5524183/160108271-c957b86d-54fe-44ba-9306-551d80a485a0.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
This was already fixed here https://github.com/artf/grapesjs/issues/4176 and will be available in the next release.
