### ISSUE TITLE
Prevent editing some components

### ISSUE THREAD

**Issue by cmcintosh** [artf/grapesjs#422]
I would like to prevent users from editing the internal components of specific components.

IE lets say I have an element called Drupal-Block

```
<div data-block>
... html inside ..
</div>
```

I want to prevent the users from editing the __... html inside...__ bit

**Comment by artf** [comment]
Are aware already of `data-gjs-*` attributes?
eg.
```html
<div data-gjs-editable="false" data-gjs-removable="false" ...>
... html inside ..
</div>
```

**Comment by cmcintosh** [comment]
hmm, Where in the workflow would I add this.  In my case, I am loading the template information via a remote store.  Could I add it during that, or can a add it on a editor.init callback.  

I tried adding it manually, but was still able to edit the inner elements.

**Comment by MichaelKlemersson** [comment]
this attributes  data-gjs-editable="false" data-gjs-removable="false" only works for the current selected element not for their childs, @cmcintosh I also tried put manually but it only works when I set this attributes on every child elements, like this:

![image](https://user-images.githubusercontent.com/4018735/31655464-54c987dc-b2ff-11e7-890d-a8c30ffe72f7.png)

**Comment by artf** [comment]
Yeah, @MichaelKlemersson is right currently you have to set them manually on any element.
Another trick would be to update all children via model
```js
const updateAll = model => {
    model.set({editable: false, ...});
    model.get('components').each(model => updateAll(model));
}
updateAll(component);
```
But what I think would be the best it's some kind of property which `propagates` (suggestions for a better term are welcome) properties from the parent to its children, eg.
```html
<div data-gjs-editable="false" data-gjs-propagate="['editable', ...]">
     <!-- this will be not editable too and the same for its children -->
     <div>...</div>
     
    <!-- possibility to overwrite and 'break' the chain -->
     <div data-gjs-editable="true" data-gjs-propagate=""></div>
</div>
```
what do you think?

**Comment by cmcintosh** [comment]
Yes i think that the propagation idea is great.  To be clear the reason im looking for this is im building out a module for Drupal 8 that will allow creating themes via the GrapeJS tool.  In Drupal you have elements called Blocks, and my thought was to block of editing of those on the Main editor, and instead have a popup editor to edit them and allow reusing those across various pages.

This is due to how Drupal renders content via PHP and thus I need to convert the html to php variables when storing the template into a twig file.

**Comment by Geczy** [comment]
+1 on the propagation idea

**Comment by MichaelKlemersson** [comment]
@cmcintosh It's a great idea, I vote for propagates and this will be really helpful using in a trait, so se could toggle this functionality ;)

**Comment by artf** [comment]
thanks for the feedback guys, I'll put it on the Roadmap

**Comment by cmcintosh** [comment]
@artf can you expand on the first option on your previous comment, 
'''
const updateAll = model => {
    model.set({editable: false, ...});
    model.get('components').each(model => updateAll(model));
}
updateAll(component);
'''

I am not familiar with what framework your using so am still picking up how its supposed to work (actually dont know what framwork you are using and have been leaning mostly on jquery)

**Comment by MichaelKlemersson** [comment]
He is using backbone js, if I'm not wrong.

**Comment by cmcintosh** [comment]
Thanks, looks like time for me to learn a new framework ;)

**Comment by rip747** [comment]
Out of curiosity. What's preventing from looking to see if any parent elements have the "data-gjs-editable" attribute to prevent a the current element from being editable?

**Comment by cmcintosh** [comment]
nothing, I had thought that would be the ideal path.  Not totally sure to implement it yet

**Comment by artf** [comment]
An example you can use in the demo
1. Select an element (eg. some section) 
2. Execute this in console
```js
editor.getSelected().append(`
<div data-gjs-removable="false" data-gjs-draggable="false" data-gjs-propagate='["removable", "draggable"]' style="color:blue">
  <div>Comp01</div>
	<div>
    <div>Comp11</div>
    <div data-gjs-stop="1" data-gjs-removable="true" data-gjs-draggable="true" data-gjs-propagate='["stop"]' style="color:red">
      <div>Comp21</div>
      <div>Comp22</div>
    </div>
    <div>
      <div>Comp31</div>
      <div>Comp32</div>
    </div>
  </div>
  <div>Comp03</div>
</div>
`)
```

**Comment by cmcintosh** [comment]
Thanks, ill look at this tomorrow ;)

**Comment by effectief** [comment]
Hello artf,

How can I prevent move, remove feature on childs (Template_2_content)?
The user may move Template_2, but not their childs.

blockManager.add('Template_2', {
	  label: 'Template 2',
	  content: '<div id="Template_2"><div id="Template_2_content"><br/><br/><span>lorem ipsem</span><br/><br/><br/></div></div>',
	});
	
	const domc = editor.DomComponents;
    const defaultType = domc.getType('default');
    const defaultModel = defaultType.model;
    const defaultView = defaultType.view;
	
	domc.addType('Template_2', {
        model: defaultModel.extend(
		{
			defaults: Object.assign({}, defaultModel.prototype.defaults, 
			{
				// True if the component is removable from the canvas
				removable: true,
				
				// Indicates if it's possible to drag the component inside other
				// Tip: Indicate an array of selectors where it could be dropped inside
				draggable: true,
				
				// Indicates if it's possible to drop other components inside
				// Tip: Indicate an array of selectors which could be dropped inside
				droppable: true,
				
				// Set false if don't want to see the badge (with the name) over the component
				badgable: true,
				
				// True if it's possible to style it
				// Tip:  Indicate an array of CSS properties which is possible to style
				stylable: true,
				
				// Highlightable with 'dotted' style if true
				highlightable: true,
				
				// True if it's possible to clone the component
				copyable: true,
				
				// Indicates if it's possible to resize the component (at the moment implemented only on Image Components)
				resizable: false,
				
				// Allow to edit the content of the component (used on Text components)
				editable: true,
				
				propagate: ['removable','draggable','droppable','editable',]
			}),
		},
		{
			isComponent: function (el)
			{
				
				if (el.tagName == 'DIV')
				{
					return {type: 'Template_2'};
				}
			},
		}),
		view: defaultView,
    });

**Comment by AustinTBiggs** [comment]
@artf - Will there be a propagate html attribute? Like what you detailed below?

`<div data-gjs-editable="false" data-gjs-propagate="['editable', ...]">
     
     <div>...</div>
     
    
     <div data-gjs-editable="true" data-gjs-propagate=""></div>
</div>`

**Comment by Coyote6** [comment]
@cmcintosh How far did you get into your Drupal 8 Module as I am working to do the same in Drupal 7?  Thanks.

**Comment by artf** [comment]
@AustinTBiggs is already there
be careful because `['editable', ...]` is not a valid JSON (you have to use double quotes for keys), therefore `data-gjs-propagate='["editable", ...]`

**Comment by cmcintosh** [comment]
@Coyote6 I am still working on things for this. Was busy on other things, but am now back at it.

**Comment by alfaalex81** [comment]
I have a problem with droppable propagation. I do an example. I drop "3 columns" inside my template (yellow zone on jsfiddle), now, if i want add an image inside one of the columns, the green selector not appear. If I remove all data-gjs the system works correctly

https://jsfiddle.net/7tdkjj6a/

**Comment by Jakobud** [comment]
Sorry this is an old issue, but is it also possible to limit which attributes are editable on any give block or component? I'm having a hard time figuring out if that's possible in the documentation.

**Comment by Jakobud** [comment]
Maybe my terminology is off here. I guess I mean prevent editing of things like padding, margins, font sizes, etc for any given content block. The reason I ask is because in many cases perhaps this tool could be used for making content changes on a website for a company that has strict brand guidelines. Things like, the standard font used is always X size and the padding between something is also Y pixels, etc. So having a tool like this would be very nice for non-developers to be able to edit the content on the site, but it might give them too much power. So restricting the editing of specific attributes/trails/? on a per content block basis would be helpful.

**Comment by artf** [comment]
@Jakobud you should [define the Style Manager](https://grapesjs.com/docs/getting-started.html#style-manager) accordingly to your needs and then you can also restrict styleable properties on components via [`styleable`](https://github.com/artf/grapesjs/blob/dev/src/dom_components/model/Component.js#L62)

**Comment by Jakobud** [comment]
Ah excellent that is what I was looking for. I figured there was a way to do this but couldn't figure it out. Thanks!

**Comment by redeeze** [comment]
did the propagation idea get implemented?

**Comment by hiteshgarg1994** [comment]
**You can extend view of a component and use the onRender function to make child elements unselectable.**

`      view: defaultType.view.extend({
        onRender() {
          this.model.onAll((innerComponent) => {
            if (!innerComponent.is("image"))
              innerComponent.set({editable: false, hoverable: false, selectable: false, highlightable: false});
          });
        }
      })`

**Comment by ColdTuna** [comment]
Yes @redeeze , `propagate` was implemented, [here are all props available](https://grapesjs.com/docs/api/component.html#component).

**Comment by pooriamo** [comment]
@artf Is there a reference for `data-gjs-*` attributes? I couldn't find it in the website.

**Comment by Dhara-Ka-Patel** [comment]
`<div id="short_description"  data-gjs-editable="false" data-gjs-propagate="['editable']"  data-gjs-removable="false">{unit.description} </div>`

I have used _data-gjs-editable=false_ , _data-gjs-propagate="['editable']"_ and  _unit.description_ represents the value of RichTextEditor, Is there any way that I can stop editing the RichTextEditor fields too?

**Comment by artf** [comment]
@pooriamo `data-gjs-*` attributes reflect all the component's available properties (pointed above your comment), so if you even create a custom component with its own custom properties, you can use them in `data-gjs-*`.
