### ISSUE TITLE
BUG: Set name for page doesn't work

### ISSUE THREAD

**Issue by miladmeidanshahi** [artf/grapesjs#4242]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Chrome v100

### Reproducible demo link

https://jsfiddle.net/9rt1xm6p/

### Describe the bug

**How to reproduce the bug?**
Add page in pageManager and set name.

**What is the expected behavior?**
`editor.Pages.getAll()[0].name` should return page name but return `undefined`.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
Properties are not placed directly on the instances. You can use `page.getName()` to get the name property.
