### ISSUE TITLE
BUG: Components disappearing/not being rendered at cloning, moving or adding

### ISSUE THREAD

**Issue by gustavohleal** [artf/grapesjs#4247]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Chromium v96

### Reproducible demo link

https://grapesjs.com/demo-mjml.html

### Describe the bug

**How to reproduce the bug?**
1. Add a one column component
2. Select the column
3. Click the copy button on the toolbar
4. Repeat the steps 2 and 3 with the components two columns, three columns and navbar-link inside the navbar component.
5. Move the component or repeat step 3 with one of the components and the first clone will appear

**What is the expected behavior?**
When clicking the copy button, the clone must appear on the side of the original.

**What is the current behavior?**
The clone is not rendered inside the canvas, but appears on the exported code.

When debugging from the render function of those components, it seems that the component is rendered for a few steps and then disappear inside a function from grapes.js. The video below show a example with de navbar and navbar-link components. As you can see, after returning the rendered component to grapes.js it disappears after a few steps.

https://user-images.githubusercontent.com/22385451/162276077-ca0c7fbf-992a-4e09-91ca-30b2cde1617e.mp4

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
Sorry but demo-mjml is a plugin and not related directly to the core. As I see no issues with the default renderer of components that might be related to the mjml renderer of components and I have no reason to keep this issue open.
Despite that, if anybody is able to identify the issue and it's so how related to the core, I'm open to fix that.
