### ISSUE TITLE
How to render external js file in our custom plugins

### ISSUE THREAD

**Issue by umeshsingh131** [artf/grapesjs#425]
Hello,

I am creating a slider plugins but its not working. because. I am not able to find how i can add or use external scripts and css files in our plugins?
Can you please help me here.

**Comment by artf** [comment]
https://github.com/artf/grapesjs/wiki/Components-&-JS

**Comment by umeshsingh131** [comment]
I used this but this is not working. Can you send me an example regarding this.
In which plugin used some custom javascript function and used external javascript file regarding that plugins

**Comment by artf** [comment]
> I used this but this is not working

Provide a live example (using services like jsfiddle/codesandbox) of what you've done so we can see what is not working

**Comment by umeshsingh131** [comment]
This is my plugin code. Please guide me.
https://jsfiddle.net/umeshsingh/5981qh97/

**Comment by artf** [comment]
Sorry @umeshsingh131 but from what I see you didn't even check https://github.com/artf/grapesjs/wiki/Components-&-JS and your live example doesn't load grapesjs library so it can't start

**Comment by umeshsingh131** [comment]
@artf : I put my html file where i load grapesjs library & add plugin[slider-plugin].
Please check below link: 
https://jsfiddle.net/umeshsingh/5981qh97/2/

**Comment by umeshsingh131** [comment]
Please check my above comment here. So that i can start my project
