### ISSUE TITLE
BUG: init() method typings error

### ISSUE THREAD

**Issue by dinosaurawr** [artf/grapesjs#4250]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Chrome v 100.0.4896.75

### Reproducible demo link

https://stackblitz.com/edit/typescript-ou8qpc?file=index.ts&view=editor

### Describe the bug

**How to reproduce the bug?**
1. Try to init grapesjs with with index.d.ts

**What is the expected behavior?**
Editor initialized without errors

**What is the current behavior?**
`Type'[string, any]' is not assignable to type '[]'.
  Source has 2 element(s) but target allows only 0`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
Thanks @dinosaurawr that was fixed here https://github.com/artf/grapesjs/pull/4216/files
