### ISSUE TITLE
After image Upload immediately show in the asset Manager

### ISSUE THREAD

**Issue by mekamleshk** [artf/grapesjs#426]
@ artf I tried my best, but still it doesn't seem to work
Can you please help me in this.
Once I upload a image I don't want to refresh the page because I will loose the newsletter template I have created.
Is there any way I get load the images into the asset manager immediately after the images are uploaded.

Would appreciate your help.

Thanks

**Comment by artf** [comment]
??? 

we're already talking about this [here](https://github.com/artf/grapesjs/issues/416) and YOU even said that you were able to do so, so... what is the point of opening another ticket?!?

**Comment by mekamleshk** [comment]
Hi @artf , I was able to only upload and delete files from the server, it was not adding images directly to the asset manager.
I rechecked all the asset manager issues and found what I was doing wrong, now it works fine.

Thanks alot :) :+1:
