### ISSUE TITLE
SSL certificate how to?

### ISSUE THREAD

**Issue by omkar111111** [artf/grapesjs#4263]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

-

### Reproducible demo link

-

### Describe the bug

Sorry for asking it here. But I am in a hurry.
I am creating a service in which I host websites for my clients.

So for each new site, does GrapeDrop create a new certificate specifically for that site? Say I point to my domain to "example.com" in GrapeDrop.
Does it create an SSL certificate specifically for "example.com" or does it use a pre-existing one?

Also, if GrapeDrop creates new certificates. How does it dynamically identify which SSL certificate should be served by GrapeDrop Webserver? In case you are using Nginx could you show me an example code block?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
Please avoid using GrapesJS issues for off-topic questions.
