### ISSUE TITLE
rte toolbar is missing

### ISSUE THREAD

**Issue by Geczy** [artf/grapesjs#427]
```html
<div data-role="editor-toolbar" id="gjs-rte-toolbar" style="pointer-events: all;"><a title="Bold" data-edit="bold" class="gjs-rte-btn fa fa-bold"></a><a title="Italic" data-edit="italic" class="gjs-rte-btn fa fa-italic"></a><a title="Underline" data-edit="underline" class="gjs-rte-btn fa fa-underline"></a><a title="Strikethrough" data-edit="strikethrough" class="gjs-rte-btn fa fa-strikethrough"></a><a title="Link" data-edit="insertHTML" data-args="<a class=&quot;link&quot; href=&quot;&quot;>${content}</a>" class="gjs-rte-btn fa fa-link"></a></div>
```

![image](https://user-images.githubusercontent.com/1036968/31624914-3bf11a1e-b272-11e7-8145-f592e7e3c779.png)

I am using this custom CSS:

```css
#gjs-pn-commands, #gjs-pn-options { display: none !important; }
```

Even without my CSS, the RTE toolbar is missing from TEXT 

![image](https://user-images.githubusercontent.com/1036968/31625124-f3181cc4-b272-11e7-91fb-aaf5a29c4000.png)

The toolbar seems to keep adding to the top left as if it has no styling, instead of being added to where my cursor is

**Comment by artf** [comment]
Can you try with the latest version? (your RTE code is the old one)

**Comment by Geczy** [comment]
Thanks sorry
