### ISSUE TITLE
Change the background of the body

### ISSUE THREAD

**Issue by asvine-p** [artf/grapesjs#428]
Hello,

First of all, I want to thank you for this **amazing**  project! 
I have few a questions regarding the editor, and more precisely the newsletter preset:

- I want to add a button in the block manager which can give a quick access to change the background of the body (without going to the component tree).

- Furthermore, how can I reorganize the commands buttons in the panel manager? (I want to change positons and delete some) -> I'm using the newsletter preset

- I don't know if there is a way to resize the preset "button" block after changing its style. Or if I add a custom block "button", how can I make it resizable and add the href property to it?

Thanks for your support!

**Comment by Geczy** [comment]
Here's how I remove buttons

```
          editor.Panels.getButton('views', 'open-sm').set('active', false)
```

**Comment by asvine-p** [comment]
@Geczy, thanks but the set("active", boolean) method only switch the highlight mode of the button. Actually It doesn't remove it.

**Comment by artf** [comment]
Hi @asvine-p
> I want to add a button in the block manager which can give a quick access to change the background of the body (without going to the component tree).

Once the editor is loaded you can add/remove stuff with JS (your button will be binded with some handler)

> Furthermore, how can I reorganize the commands buttons in the panel manager? (I want to change positons and delete some) -> I'm using the newsletter preset

Here is an example from the newsletter preset how I change/remove buttons
https://github.com/artf/grapesjs-preset-newsletter/blob/master/src/buttons.js#L36-L37

> I don't know if there is a way to resize the preset "button" block after changing its style. Or if I add a custom block "button", how can I make it resizable and add the href property to it?

You can't "change" (besides playing with paddings) its size because the built-in "Button" block is a link (inline element), but you can add your custom block and set, for example, in style "display: block" (or inline-block) this will allow editing it size

**Comment by asvine-p** [comment]
Thanks for your reply!

I succeeded changing the background by setting the style of all models inside the wrapper children.
This was a little bit tricky but if it can help someone here is the code:
` let domComponents = this.editor.DomComponents;
        let wrapperChildren = domComponents.getComponents();

        for (let i = 0; i < wrapperChildren.models.length; i++) {
            wrapperChildren.models[i].set({
                style: {"background-color": "#FFFFFF"}
            });
        }`
Beside this, I have two other problems with the editor. 

- Spans are not recognized by the editor during import of an html template. Thus I added this code and it had recognized the span but they are not editable like texts: 
`domc.addType('span', {
            // Define the Model
            model: textType.model.extend({},
                {
                    isComponent(el) {
                    if (el.tagName === 'SPAN') {
                        // as template.children will return an empty array the traverser
                        // will skip all nodes, therefore attach them as a string (they
                        // will be processed later)
                        return {type: 'Span',
                                src: el.src,
                                tagName: el.tagName.toLowerCase(),
                                components: el.innerHTML
                        }
                    }
                }
            }),
            view: textType.view
});;`
How can I make these spans editable and stylable like texts? 
Here is the html I imported
[htmlTemplate.html.zip](https://github.com/artf/grapesjs/files/1428141/htmlTemplate.html.zip)

- My second problem is that I don't want to use classes system (specially when copying a component or when importing html). When I import html texts, some components have the same css class. So I add new class when selecting a component in oder to have different classes inside my components.

`  this.editor.on('component:selected', function(model) {
            // console.log("SELECTED", model);
            if (model && model.length > 2) {
                const uuid = this.s4(); // generate new UUID for selecor

                const selector =  {
                    name: uuid,
                    type: 'class',
                    label: uuid,
                };

                if (model[1].attributes.classes.length === 1) {
                    selectorManager.add(selector);
                    model[1].attributes.classes.push(selectorManager.get(uuid)); // ADD NEW SELECTOR TO MODEL
                }
            }
});`

This add new selector name to the component  but it looses his original style sometimes. Is there a simple way to automatically add different class to all of my components when doing some modifications. I think what I'm currently doing is not the best way to add a class to a component.

Finally I want to save all the current configuration in JSON. I used 
`let jsonConfig = this.editor.getComponents()`
then
`this.editor.setComponents(jsonConfig)`
but this is not working.

Thanks for replying! :)

**Comment by artf** [comment]
@asvine-p please open another issue if your problem is different from the original one
