### ISSUE TITLE
BUG: [Component's toolbar] Toolbar width not resizing correctly

### ISSUE THREAD

**Issue by zauchad** [artf/grapesjs#4285]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Chrome v100.0.4896.127

### Reproducible demo link

No demo link.

### Describe the bug

**How to reproduce the bug?**
1. Just place bigger icons inside toolbar (for example font awesome class: **fa-2x**):
```
toolbar: [
  {
	  attributes: { class: 'fa fa-2x fa-clone' },
	  command: 'tlb-clone',
  }, {
	  attributes: { class: 'fas fa-2x fa-trash-alt' },
	  command: 'tlb-delete',
  }
]
```

**What is the expected behavior?**
Component's action toolbar should correctly resize its width, paddings and its position relative to its component (for now each icon's cell width is hardcoded).

**What is the current behavior?**
Here is visual example how bigger toolbar icons and the toolbar look like:
<img width="1054" alt="Zrzut ekranu 2022-04-25 o 11 08 41" src="https://user-images.githubusercontent.com/36495919/165060163-b10aba84-d672-4869-9008-21d43754676f.png">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
There are a lot of reasons to keep the size of the toolbar item fixed, if you want them bigger, you can simply update the CSS.
