### ISSUE TITLE
BUG: "storage:start:load" event is not being trigged

### ISSUE THREAD

**Issue by candidodmv** [artf/grapesjs#4289]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Chrome latest

### Reproducible demo link

Bind "storage:start:load" to an editor instance and see the console.log output

### Describe the bug

**How to reproduce the bug?**
1. ...
2. ...

**What is the expected behavior?**
... The event has been fired

**What is the current behavior?**
...  The event is being ignored

If is necessary to execute some code in order to reproduce the bug, paste it here below:
```js
// your code here
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
Yeah with the current version you should bind the event in a plugin otherwise the first `start:load` is not captured. This should be fixed in the next release.
