### ISSUE TITLE
BUG: Style Manager is inaccurate when using combined CSS selectors which contains "bout" and componentFirst = true

### ISSUE THREAD

**Issue by barryross** [artf/grapesjs#4310]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Chrome 100

### Reproducible demo link

https://jsfiddle.net/4fmd732c/3/

### Describe the bug

**How to reproduce the bug?**

Given 
a) `componentFirst` is set to `true`
b) An element has multiple classes
c)  CSS rule uses combined selector of multiple classes
d) One of the classes contains the word "bout"
 
Then:
Style Manager does not accurately display current styling

Navigate to linked JS Fiddle
1. Select Div in editor
2. In the Style Manager, expand "Decorations" and take note of background color

**What is the expected behavior?**
- Style manager should indicate background is green

**What is the current behavior?**
Style manager indicates background is white
- If you change class name from ".bout" to ".out", it works fine
- If you change ComponentFirst to "false", ".bout" and ".out" work fine

If is necessary to execute some code in order to reproduce the bug, paste it here below:
```js
// your code here
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
Nice catch, thanks for the report @barryross

**Comment by barryross** [comment]
@artf  Oh, I see now you already made the fix.  I guess I would just need to re-build the library locally with your changes until next release.

**Comment by barryross** [comment]
@artf  when do you foresee the next release going out?

**Comment by artf** [comment]
I'm not sure yet but I was planning for the end of the next week.

**Comment by barryross** [comment]
Gotcha, thanks for letting me know what you're thinking
