### ISSUE TITLE
Unminified grapjes.js file?

### ISSUE THREAD

**Issue by cindygao93** [artf/grapesjs#433]
I downloaded the git repo but was only able to find grapes.min.js. I really want to dig into the code some more and get a better understanding of how all the files are related to each other but I'm not seeing the unminified version anywhere. Could someone point me to where it is in the repo or if not, could the unminified version be made available somewhere?

**Comment by ateshuseyin** [comment]
There is no unminified version of grapesjs. I think this is a necessity. Until @artf add unminified version checkout the project then link grapesjs into your project. See: https://docs.npmjs.com/cli/link

**Comment by artf** [comment]
Hi @cindygao93 if you want to dig into the code you just have to check [`/src`](https://github.com/artf/grapesjs/tree/dev/src) folder

**Comment by z-vr** [comment]
@artf `/src` is a good start, but 
```
  const Editor = require('editor');
  const PluginManager = require('plugin_manager');
```
does not allow to do
```
import grapesjs from 'grapesjs/src'
```

**Comment by artf** [comment]
@z-vr we're already discussing about this here https://github.com/artf/grapesjs/pull/370
