### ISSUE TITLE
BUG: No way to upload background video component in the editor , Please suggest if there is any way to upload background video

### ISSUE THREAD

**Issue by Sudhin35** [artf/grapesjs#4335]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Chrome v9

### Reproducible demo link

Not there

### Describe the bug

**How to reproduce the bug?**
1. Install the grapes js in the react app
2. Open the editor and see the settings menu for the editor body

**What is the expected behavior?**
Need a option to add the background video to the editor ( As of now there is only option to background image )

**What is the current behavior?**
As of now there is only option to background image

If is necessary to execute some code in order to reproduce the bug, paste it here below:
```js
Same sample code is only available
![Upload video option](https://user-images.githubusercontent.com/50030377/169051776-8c74b02d-afce-4c2b-a7d0-c6629fb1fa62.png)

```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Sudhin35** [comment]
@artf  Please suggest me if there is any way for the above mentioned feature

**Comment by artf** [comment]
Please open an issue only in case of bugs, not your personal requests
