### ISSUE TITLE
while adding border style for Html component css json only fetching for border selector not fetching selector of border-width, border-style, border-colorBUG: 

### ISSUE THREAD

**Issue by senthil177cse** [artf/grapesjs#4341]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

chrome v101.0.4951.54

### Reproducible demo link

https://jsfiddle.net/7sn5h91r/7/

### Describe the bug

1. my issue is for style border property width, style and color not updating in json even i have checked in https://grapesjs.com/demo.html. please check the attached screenshot. below is my code JSON response. tell me how to remove that empty properties like border-width, border-style,border-color.

my response JSON:{
  "selectors": "is98i",
  "style": {
    "width": "100%",
    "__p": false,
    "height": "5%",
    "margin-bottom": "15px",
    "border-radius": "5px",
    "border": "1px solid #d6d6d6",
    "border-width": "",
    "border-style": "",
    "border-color": ""
  },
  "mediaText": "(max-width: 480px)",
  "atRuleType": "media"
} 
![168816344-e19cb449-3d01-45e4-a5be-f315d1d749c9](https://user-images.githubusercontent.com/50009624/169486503-a3695e18-69b7-4c42-b1d1-35c722537205.jpg)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aharishsundhar** [comment]
@senthil177cse how to resolve this problem i'm fce the same issues in my side latest version v0.18.4
padding: 0 0 0 0, padding-top: "", padding-bottom: "", padding-right: "", padding-left: "",

**Comment by aharishsundhar** [comment]
@artf how to resolve this problem i'm face the same issues in my side latest version v0.18.4
padding: 0 0 0 0, padding-top: "", padding-bottom: "", padding-right: "", padding-left: "",

**Comment by aharishsundhar** [comment]
@artf how to resolve this problem i'm face the same issues in my side latest version v0.18.4
padding: 0 0 0 0, padding-top: "", padding-bottom: "", padding-right: "", padding-left: "",

**Comment by aharishsundhar** [comment]
> 

@senthil177cse im getting the same issues on padding : 0 0 0 0; created also the padding-top create but empty properties coming how to fix the problem is its issues with grapesjs v0.18.4?

**Comment by senthil177cse** [comment]
no actually how added padding property into your project?
my guessing you have added like below

buildProps: [ 'padding']

instead of this add like below 

buildProps: [ 'padding-top', 'padding-bottom', 'padding-left', 'padding-right']

**Comment by aharishsundhar** [comment]
@senthil177cse i have not adding the customstylemanager for dimension style manager in buildProps so if I not adding so the problem both it store the db? its that right
![Screenshot from 2022-07-20 17-43-35](https://user-images.githubusercontent.com/72383148/179979144-3f02afc7-c9cc-4c8e-a7f8-930663fe4dc1.png)
