### ISSUE TITLE
Add Norwegian language

### ISSUE THREAD

**Issue by rubjo** [artf/grapesjs#4352]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Chrome v101

### Reproducible demo link

NA

### Describe the bug

Not a bug, just an issue for upcoming PR for Norwegian support

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rubjo** [comment]
Someone beat me to it - so recently that it seems that it isn't released yet. :)

**Comment by ZaheerNiazi007** [comment]
@rubjo    i18n: {
      locale: "en",
      detectLocale: false,
      messagesAdd: {
        en: en,
      },
    },
    try this use norweigen lang file
 
    https://github.com/GrapesJS/grapesjs/blob/master/src/i18n/locale/en.js
