### ISSUE TITLE
RemoteStorage - Load Template uses POST

### ISSUE THREAD

**Issue by santiph** [artf/grapesjs#436]
I'm using a custom module to save/load a template with a service like this:

```
module.exports = (grapesjs) => {
    const LOAD_COMMAND = 'external-load';
    const storageManager = grapesjs.StorageManager;

    // Add Save Button
    grapesjs.Panels.addButton(
        'options',
        {
            id: 'open',
            className: 'fa fa-folder-open-o',
            attributes: { title: 'Open Template' },
            command: LOAD_COMMAND,
        },
    );

    // Custom Save Command
    grapesjs.Commands.add(
        LOAD_COMMAND,
        {
            run(editor, sender) {
                storageManager.get('remote').set({
                    urlLoad: 'localhost:8000/templates/5',
                    urlStore: 'localhost:8000/templates'
                });

                editor.load(() => {
                    sender.set('active', 0);
                });
            },
        },
    );
};
```
Save is a different module and works just fine. The problem is with the Load() call. For some reason, Grapes performs a POST action to `localhost:8000/templates/5` getting a 405 - Method not allowed from the backend.

Fetch call in RemoteStorage model is defaulting to POST if no option is specified as Method for the request.
https://github.com/artf/grapesjs/blob/dev/src/storage_manager/model/RemoteStorage.js#L123

And Load doesn't specify any when calling `this.request()`: https://github.com/artf/grapesjs/blob/dev/src/storage_manager/model/RemoteStorage.js#L77

**Comment by santiph** [comment]
Solved

**Comment by suresh5** [comment]
hi can you share me the json when u are sending to load template ?
