### ISSUE TITLE
BUG: LayerManager becomes unresponsive after StorageManager.load()

### ISSUE THREAD

**Issue by Vac1911** [artf/grapesjs#4370]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Chrome 102

### Reproducible demo link

https://codesandbox.io/s/grapesjs-4370-niizlc

### Describe the bug

**How to reproduce the bug?**
1. Enable remote storage
2. Call editor.StorageManager.load (doesn't matter what this actually returns) 
4. Then call editor.loadProjectData (doesn't matter what data is loaded)

**What is the expected behavior?**
The LayerManager becomes works with the new project data.

**What is the current behavior?**
The LayerManager becomes unresponsive.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Vac1911** [comment]
Just kidding it broke again

**Comment by artf** [comment]
Good catch, thanks @Vac1911

**Comment by zhangdongxu-web** [comment]
我也遇到同样的问题，重新加载储存的数据后 LayerManager 变得无响应 只有一个 body  box 怎么办呢
