### ISSUE TITLE
BUG: index.d.ts says that run commands should return void but docs say their return value may be used

### ISSUE THREAD

**Issue by froodian** [artf/grapesjs#4385]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Any

### Reproducible demo link

https://grapesjs.com/docs/modules/Commands.html#stateful-commands

### Describe the bug

**How to reproduce the bug?**

in a typescript setup,

```ts
import grapesjs from "grapesjs";

export const ExportPlugin = (editor: grapesjs.Editor) => {
  editor.Commands.add("render html", (editor) => {
    return "<html><body>example</body></html>";
  }););
};
```

**What is the expected behavior?**

it is allowed, as in the "Let's return something" example at https://grapesjs.com/docs/modules/Commands.html#stateful-commands

**What is the current behavior?**

```
Argument of type '(editor: grapesjs.Editor) => string' is not assignable to parameter of type '(editor: Editor) => void | { run: (editor: Editor, sender?: any) => void; stop: (editor: Editor, sender?: any) => void; }'.
  Type 'string' is not assignable to type 'void | { run: (editor: Editor, sender?: any) => void; stop: (editor: Editor, sender?: any) => void; }'.
```

I'm having difficulty making the example work with the 

```ts
{
  run: (editor: Editor, sender?: any) => void;
  stop: (editor: Editor, sender?: any) => void;
}
```

definitions as well - (in addition to the `(editor: Editor) => void` definition, as described above)

Should all 3 of these `void` declarations in fact be `any`?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
Thanks @froodian I'll update them
