### ISSUE TITLE
Help with new component type

### ISSUE THREAD

**Issue by sebastianha** [artf/grapesjs#44]
Hi,

I need your help with new components again. I tried the following: I want to add a new component which creates a resizable div which is tagged with two HTML attributes. The one is a marker to recognize the div when parsing HTML and the other one is user defined when adding or double-clicking the component.

I followed your tutorial and looked at existing component types and somehow gotten it to work. But somehow I modify the default component type which leads to side effects of my new component.

Every component which is added after I added my custom one, gets the attributes of the new custom component. So I somehow modify the default component type with my code. To reproduce the problem add the "Test" component and then a Text component. Then take a look at the HTML of the Text component which looks like the following:

`<div testmarker="test" class="c574" onmousedown="return false" testvalue="123"><div style="text-align: center;">Test: 123</div></div>`
`<div testmarker="test" testvalue="123" class="c600" contenteditable="true">Insert your text here</div>`

There you see that even the Text component has the testmarker and the testvalue which is obviously wrong.

I created a Gist ( https://gist.github.com/sebastianha/48ed97a33a979945ae0a8b4587076409 ) with the demo.js file, perhaps you could take a look and spot my problem? That would be very nice.

**Comment by artf** [comment]
Thanks @sebastianha your code is ok, seems like there is a bug with extending the *attributes* property. 
Actually try with this, putting your props inside 'attributes' not only will avoid the bug but you have also less to write
```js
comps.addType("test-type", {
  model: defaultModel.extend({
    defaults: Object.assign({}, defaultModel.prototype.defaults, {
      droppable : false,
      resizable : true,
      attributes: {
        testmarker: "test",
        testvalue : "1",
      }
    }),

  },{
    isComponent: function(el) {
      var result = "";
      if(el.tagName == "DIV" && el.getAttribute("testmarker") === "test") {
        result = {type: "test-type"};
      }
      return result;
    }
  }),

  view: defaultView.extend({
    tagName: "div",
    events: {
      "dblclick": "openModal",
      "click": "initResize"
    },

    init: function(o) {
      this.listenTo(this.model, "dblclick active", this.openModal);
    },

    openModal: function(e) {
      var testvalue = parseInt(prompt("Please enter the test value"));
      var attr = this.model.get("attributes");
      if(testvalue > 0) {
        attr.testvalue = testvalue;
      } else {
        attr.testvalue = 1;
      }
      // Have to pass a new object otherwise the model will not see changes
      this.model.set("attributes", Object.assign({}, attr));
      this.render();
    },

    render: function() {
      defaultType.view.prototype.render.apply(this, arguments);
      var sm = this.config.em.get("StyleManager");
      var style = sm.getModelToStyle(this.model).get("style");
      if(!style.width) {
        sm.getModelToStyle(this.model).set("style", {
          "width"           : "320px",
          "height"          : "180px",
          "background-color": "black",
          "color"           : "white"
        });
      }
      this.$el.empty();
      var value = document.createElement("div");
      value.style.textAlign = "center";
      value.innerHTML = "Test: " + this.model.get("attributes").testvalue;
      this.el.appendChild(value);
      this.$el.attr("onmousedown", "return false");
      return this;
    },
  }),

})
```

**Comment by sebastianha** [comment]
Thank you very much, now it works as expected!
