### ISSUE TITLE
Not works with jquery

### ISSUE THREAD

**Issue by ateshuseyin** [artf/grapesjs#440]
I use jquery in my project. After version 0.12.8 it does not work with jquery. 

Prt of my webpack.config is;
``` 
resolve: {
    modules: [
      path.resolve(__dirname, 'node_modules/grapesjs/src'),
      path.resolve(__dirname, 'node_modules')
    ],
    alias: {
      'cash-dom': 'jquery'
    }
  },
  externals: {
    'jquery': 'jQuery'
  },
```

When I try to drop a block it throws;

> ComponentsView.js:76 Uncaught TypeError: Cannot read property 'length' of undefined
    at child.addToCollection (ComponentsView.js:76)
    at child.addTo (ComponentsView.js:22)
    at triggerEvents (backbone.js:371)
    at triggerApi (backbone.js:356)
    at eventsApi (backbone.js:155)
    at child.Events.trigger (backbone.js:346)
    at child._onModelEvent (backbone.js:1187)
    at triggerEvents (backbone.js:372)
    at triggerApi (backbone.js:357)
    at eventsApi (backbone.js:155)

**Comment by artf** [comment]
Do you get the same error with all of your blocks?

**Comment by ateshuseyin** [comment]
Right. I get the same error with all blocks defined in mjml plugin.

**Comment by artf** [comment]
Ok, I'd like to understand if it's something related to jquery. Are you able to reproduce it without the mjml plugin? (latest version)

**Comment by ateshuseyin** [comment]
Ok. I will try without mjml plugin

**Comment by artf** [comment]
Can you reproduce it with http://codesandbox.io please?

**Comment by ateshuseyin** [comment]
@artf This issue is about mjml plugin. This can be closed. I will open an issue to mjml plugin
