### ISSUE TITLE
Ignore/avoid changeCount

### ISSUE THREAD

**Issue by santiph** [artf/grapesjs#441]
Due to https://github.com/artf/grapesjs/issues/436, I cannot rely on StorageManager's Remote Load method to load a template from a REST endpoint, so I'm falling back to alternatives as `editor.setComponents()` and `editor.setStyle()` (being used within a command, so `grapesjs` and `editor` are available).

Unfortunately, those methods make `changesCount` to increase and triggers `onbeforeunload` event when our users try to leave the webpage.
Also, including sentences like `editor.editor.set('changesCount', 0);` in the command are useless, since changesCount gets incremented as soon as the command finishes (even after completing run() and stop() execution).

Is there any workaround this issue? Or any way to override changesCount right after .setComponents()/.setStyles() are used?

Thanks.
PS: As for https://github.com/artf/grapesjs/issues/436, I'll be working on a refactor proposal for fetch library to make it REST-compliant. Hope to push it at some point next week

**Comment by artf** [comment]
Hi @santiph well, if the problem is `onbeforeunload` you can disable it with `noticeOnUnload`
```js
grapesjs.init({
     ...
     noticeOnUnload: false
})
```

**Comment by santiph** [comment]
Hi @artf 
I need to warn the user know of any unsaved changes consistently. And skip it when there's nothing new to be saved: When a new empty template is created, right after saving or right after loading a template, no confirmation message should be displayed.

Saving scenario through StorageManager works as expected. Loading doesn't, unfortunately. At least not when components, styles, html and so on is being loaded through the editor's API, not the StorageManager .load().

**Comment by santiph** [comment]
I could test it with remote storage fully:
`onbeforeunload` is disabled, as expected, on saving.
Unfortunately, it's still being displayed right after loading a new template.

Loading a new template sets `changesCount` to 1

**Comment by artf** [comment]
There is no other way if not to set it directly just after `setComponents()`
```js
editor.setComponents('...');
...
editor.getModel().set('changesCount', 0);
```
but you said it's not working, can you share the command because I'm not able to reproduce

**Comment by santiph** [comment]
Sorry for the misunderstanding. 
Having https://github.com/artf/grapesjs/pull/437 merged allowed me to use StorageManager as is instead of jQuery Ajax + `setComponents()` API to load a template from the backend.

My editor is being set as follows:
```
const editor = grapesjs.init({
    container: '#gjs',
    noticeOnUnload: true, // Warn the user unsaved changes might be lost when leaving the app
    storageManager: {
        id: '',
        autosave: false,
        autoload: false,
        type: 'remote',
        stepsBeforeSave: 1,
        urlStore: '',
        urlLoad: '',
        params: {}, // For custom values on requests,
        contentTypeJson: true,
        storeComponents: true, // Enable/Disable storing of components in JSON format
        storeStyles: true, // Enable/Disable storing of rules/style in JSON format
        storeHtml: true, // Enable/Disable storing of components as HTML string
        storeCss: true, // Enable/Disable storing of rules/style as CSS string
    },
});
```

`urlLoad` & `urlStore` are being generated/overwritten dynamically as the user saves and load a new template. Load and Save operations works perfectly for us.

Now to the problem: `onbeforeunload` is being triggered when the user tries to leave the editor having unsaved changes (Good!). And when trying to leave after loading a template with no changes being made (Bad!).
As I could debug, it's related to `changesCount`. This counter is being increased once per template loaded. So if the user loads three templates consecutively (without changing anything), `changesCount` is being set to 3, when it should be reset back to 0, right?

Am I missing something?

**Comment by artf** [comment]
Ah ok. if I got it right this time, you mean update `changesCount` after the storage load, in this case, try with `storage:end` event
```js
editor.on('storage:end', () => editor.getModel().set('changesCount', 0))
```

**Comment by santiph** [comment]
changesCount is being set constantly to 1 now. (Load -> 1. Load Load -> 1)
There must be something increasing this counter right after storage events

**Comment by artf** [comment]
yeap, actually the `storage:end` is not enough, the editor sets its components once the storage process is ended [editor. load](https://github.com/artf/grapesjs/blob/dev/src/editor/model/Editor.js#L533-L538). As a workaround, you have to override the function. 
I was thinking about adding `this.set('changesCount', 0);` just before the callback but not totally sure if it's a correct behaviour 🤔

ps: if you call `editor.load()` manually, actually, this should work 
`editor.load(() => editor.getModel().set('changesCount', 0))`

**Comment by santiph** [comment]
I'm afraid I'm getting the same result as using `'storage:end'`.  
No matter how many times I load a template, `changesCount` remains set to 1.

Btw, templates are being loaded through a Promise, and `onResponse()` is being called when resolved (triggering `storage:response` event, followed by `storage:end`). I think I've mimic the way RemoteStorage model behaves. Might that be affecting it somehow?

**Comment by artf** [comment]
> Btw, templates are being loaded through a Promise, and onResponse() is being called when resolved (triggering storage:response event, followed by storage:end). I think I've mimic the way RemoteStorage model behaves. Might that be affecting it somehow?

I don't get how you're loading templates, can you give some example?

**Comment by santiph** [comment]
I'm currently using a custom Storage with business specific logic in there. I've tried to mimic RemoteStorage as much as I could (extending RemoteStorage itself triggers a lot of unresolved dependencies errors):

```
module.exports = require('backbone').Model.extend({
    defaults: {
        templateId: '',
    },
    ...
    /**
     * Triggered before the request is started
     * @private
     */
    onStart() {
        this.get('em').trigger('storage:start');
    },

    /**
     * Triggered on request response
     * @param  {string} text Response text
     * @private
     */
    onResponse(responseText, callback) {
        callback(responseText);
        this.get('em')
            .trigger('storage:response', responseText);
        this.onEnd(responseText);
    },

    /**
     * Triggered after the request is ended
     * @param  {Object|string} res End result
     * @private
     */
    onEnd(res) {
        this.get('em').trigger('storage:end', res);
    },

    load(keys, callback) {
        this.onStart();
        this.get('templateService').getTemplateById(this.get('templateId'))
            .then((response) => {
                this.onResponse(response.data, callback);
            })
            .catch((error) => {
                this.onError(error);
            });
    },
});
```

**Comment by artf** [comment]
@santiph what I was asking is if `editor.load()` was triggered by you manually
Have you tried to override [editor. load](https://github.com/artf/grapesjs/blob/dev/src/editor/model/Editor.js#L533-L538)?

**Comment by santiph** [comment]
Oh, yes. We've followed the wiki to create a button to trigger a Load Command.
Within this load command, we're executing `editor.load()` manually, yes.

Why would I override such method? We're implementing a custom Storage, setting it as default and that's being consumed by `editor.load()` and `editor. getCacheLoad()` https://github.com/artf/grapesjs/blob/dev/src/editor/model/Editor.js#L566-L570

**Comment by artf** [comment]
> Within this load command, we're executing editor.load() manually, yes

Ok great, have you tried with the load callback?
```js
editor.load(() => {
     editor.getModel().set('changesCount', 0);
})
```
The callback is called just after the result is applied so from what I see this should work.
