### ISSUE TITLE
Is it possible to include an external stylesheet in the grapesjs canvas?

### ISSUE THREAD

**Issue by roytang** [artf/grapesjs#442]
We want to create some custom components whose style changes according to an external theme css (there can be different themes),  and we want those styles to appear in the canvas while editing.

**Comment by roytang** [comment]
Please ignore. I ended up injecting the stylesheet link using javascript into Grapes' canvas' iframe

// insert external stylesheet into the grapesjs window
var iframes = Utilities_GetElementsByClass("gjs-frame", "IFRAME", document.body);
for (var i=0; i<iframes.length; i++) {
  var iframe = iframes[i];
  var doc = iframe.contentDocument;
  var element = document.createElement("link");
  element.setAttribute("rel", "stylesheet");
  element.setAttribute("type", "text/css");
  element.setAttribute("href", "/CSS/Website.css");
  doc.getElementsByTagName("head")[0].appendChild(element);
}

**Comment by artf** [comment]
You can inject scripts/styles via canvas config option

```js
const editor = grapesjs.init({
  ...
  canvas: {
    styles: ['https://...', '...'],
    scripts: ['https://...'],
  }
});
```

**Comment by roytang** [comment]
Thanks!
