### ISSUE TITLE
Is it possible to restrict that only one of a certain component can be added to the canvas?

### ISSUE THREAD

**Issue by roytang** [artf/grapesjs#443]
We want to define a custom component that may or may not be added into the HTML, but we want to disallow adding more than one of that component. Can this restriction be done in GrapesJS?

**Comment by artf** [comment]
Not something built-in, but definitely achievable by using the GrapesJS's API
Extremely easy would be adding a listener (eg, `change:changesCount`), search your component and then apply your logic
```js
editor.on('change:changesCount', () => {
     editor.getComponents().each(model => ...)
})
```
