### ISSUE TITLE
BUG: Error on resize image.

### ISSUE THREAD

**Issue by ronaldohoch** [artf/grapesjs#4448]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Brave Browser Last version

### Reproducible demo link

https://grapesjs.com/demo.html

### Describe the bug

**How to reproduce the bug?**
1. Opens the demo page.
2. Puts an image.
3. Double click to select image.
4. Set width to 100%.
5. Set height to auto or click on the `x` in height property.
6. Resize image, you will see that width keeps in % and height is calculated in pixels
7. Click on the preview eye
8. See that the image is flattened.

**What is the expected behavior?**
Resize algorithm should calc in pixels instead of mix them

**What is the current behavior?**
Resize function are keeping % as main css unity and calculating the height with pixels, but, when we click in the preview button, the size of column changes, so, the width in % steel working, but the height in pixels is broken.

Check the video with the bug happening:
https://www.loom.com/share/f2ed011b207a4e5fb2ac916c94ab0a5b

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
@gustavohleal 
You can check [here](https://github.com/artf/grapesjs/blob/master/src/utils/Resizer.js) the default resizer options, which you should be able to override from the component `resizable` property.

>Hi Arthur, these configuration didn't make any changes to the image, it keeps setting the height with px instead of auto, as property keepAutoHeight suggest

@ronaldohoch the height, in this case, has to be set to `auto` explicitly

**Comment by ronaldohoch** [comment]
Well, we could make it work with the config and some event.

```js
        editor.DomComponents.addType('image',{
            model:{
                defaults:{
                    resizable: { 
                        ratioDefault: true, 
                        keepAutoHeight: true,
                        currentUnit: 1,
                    },
                }
            }
        })
       //and this
        editor.on("component:add", (model) => {
            if(model.attributes.type == "image"){
                model.setStyle({
                    width:"100%",
                    height:"auto",
                    "max-width":"100%",
                    "max-height":"100%",
                })
            }
        })
```

We also block the other css units this way.:

```js
        const sm = editor.StyleManager;
        sm.addBuiltIn('width', {
            units: ['%', 'px']
        });
        sm.addBuiltIn('height', {
            units: ['%', 'px']
        });

        editor.StyleManager.addSector('dimension', {
            name: 'Dimension',
            open: false,
            buildProps: ['width', 'height', 'max-width', 'min-height', 'margin', 'padding'],
        })
```
