### ISSUE TITLE
BUG: Lists not working with default RTE

### ISSUE THREAD

**Issue by skru** [artf/grapesjs#4449]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Chrome Version 102.0.5005.115 (Official Build) (64-bit)

### Reproducible demo link

https://jsfiddle.net/6Ldn124x/3/

### Describe the bug

**How to reproduce the bug?**
1. Click on text block to open RTE
2. Try and add a list

**What is the expected behavior?**
Lists work

**What is the current behavior?**
Lists do not work

I've been trying to track down the exact issue all day. Between v0.18.2 > v0.18.3 and the issue stems from changes made in src/RichTextEditor/model/RichTextEditor.js but I'm struggling to pin it down for a PR.

Anyone more knowledgeable know what's going on?

All the best

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by skru** [comment]
I've tried to find a fix for this but failing.

Problem occurs with:

    __onKeydown(event) {
    if (event.key === 'Enter') {
      this.doc.execCommand('insertLineBreak');
      event.preventDefault();
    }
  }

Which, when creating a list is not the desired behaviour. Only thing I can think of is adding another property to the RichTextEditor class that holds the current action in use, something like:

    syncActions() {
      this.getActions().forEach(action => {
        if (this.actionbar) {
          if (!action.state || (action.state && action.state(this, this.doc) >= 0)) {
            const event = action.event || 'click';
            action.btn[`on${event}`] = e => {
  
              // add action
              this.currentAction = action
              
              action.result(this, action);
              this.updateActiveActions();
            };
          }
        }
      });
    }

    __onKeydown(event) {
      // check the property for something that we can use to determine if to insert line break
      if (event.key === 'Enter' && this.currentAction !== "something??") {
        this.doc.execCommand('insertLineBreak');
        event.preventDefault();
      }
    }

But then, what could be used in that conditional?

**Comment by artf** [comment]
I'm not sure yet about the best long-term solution but as a workaround, we can prevent that condition but checking the active state of `insertOrderedList`/`insertUnorderedList`. I'll take care of it for the next release.

**Comment by jack2ky** [comment]
Where to find other commands like "insertUnorderedList"?
