### ISSUE TITLE
Collapsed Category in Blocks when Grapes Editor is loaded

### ISSUE THREAD

**Issue by fzs1994** [artf/grapesjs#446]
Hello,
I want all the categories listed in Blocks, must be initially in collapsed condition when the Grapes JS Editor is loaded. How can I do that? Also, if any one category is clicked, all others gets closed just like accordion. Is this possible?

![image](https://user-images.githubusercontent.com/10684213/31940325-5921883e-b8db-11e7-9b81-dab1c1ccf59c.png)

Thanks!

**Comment by artf** [comment]
Try with this
```js
const categories = editor.BlockManager.getCategories();
categories.each(category => {
	category.set('open', false).on('change:open', opened => {
		opened.get('open') && categories.each(category => {
            category !== opened && category.set('open', false)
        })
	})
})
```

**Comment by fzs1994** [comment]
Wow man, Thanks a lot!

Sneak Peak:
![image](https://user-images.githubusercontent.com/10684213/31998481-a539e266-b9ad-11e7-9b61-9272f453899e.png)
:heart_eyes:

**Comment by artf** [comment]
awesome 😍

**Comment by andsnake** [comment]
i know we can add a class for font-awsome etc, but how did you changed it to show previews/custom thumbnails?

**Comment by fsaiyedOB** [comment]
Give your custom class and set styles with the background image
Eg Code:

In bm.add block
```
attributes: {
  class: 'custom-icon flowz-callToAction-style-2',
  title: 'Style 2',
},
```

and in CSS

```
.custom-icon {
  padding:0 !important;
  width:100px !important;
  height:50px !important; 
  min-height: auto !important
}
.flowz-callToAction-style-2{
  background:url(screenshots/callToAction/2.jpg) no-repeat;
  background-size:100% 100%
}
```

**Comment by andsnake** [comment]
Thanks, sometimes the answer's something so simple, you can't just get it on your head hahah :P
