### ISSUE TITLE
BUG: Change in traits does not update html

### ISSUE THREAD

**Issue by capoia** [artf/grapesjs#4466]
### GrapesJS version

- [x] I confirm to use the latest version of GrapesJS

### What browser are you using?

Chrome

### Reproducible demo link

https://jsfiddle.net/weellingtonc/t8hs9f67/2/

### Describe the bug

**How to reproduce the bug?**
1. add 'button-cube' component to workspace
2. click on the created button
3. go to the settings component and change the value of the "texto do botao" property
4. open the option to view the generated html

**What is the expected behavior?**
When updating the trait it would also generate a new html

**What is the current behavior?**
It keeps the initial state of the button, with the old text

Note: this happens when saving too, if you click save (floppy disk) before and after changing the text, you will notice that the text value of the button does not change!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by skru** [comment]
first, you're code needs to go in a plugin [https://grapesjs.com/docs/modules/Components.html#define-custom-component-type](url)

and you're not updating the model of the component, just the html in the canvas...

https://jsfiddle.net/jmweg8u1/4/

**Comment by artf** [comment]
Yeah correct, thanks @skru 
You can also connect the `content` directly to the trait to read also the initial value.
```js
traits: [{ label: 'Texto do botão', type: 'text', name: 'content', changeProp: true }],
```
