### ISSUE TITLE
BUG: v0.19.5 Breaks headless editor.setComponents(): "Uncaught (in promise) ReferenceError: window is not defined"

### ISSUE THREAD

**Issue by skru** [artf/grapesjs#4473]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Chrome 102.0.5005.115 (Official Build) (64-bit)

### Reproducible demo link

-

### Describe the bug

**How to reproduce the bug?**

I'm unable to reproduce this on JSFiddle, but that sort of makes sense.
#4373 has introduced a bug in editor.setComponents():
"Uncaught (in promise) ReferenceError: window is not defined"

This is when converting an svg to base64. Quick fix in src/utils/mixins:

    export const buildBase64UrlFromSvg = (svg: string) => {
      if (svg && svg.substr(0, 4) === '<svg') {
        // remove window.btoa
        return `data:image/svg+xml;base64,${Buffer.from(svg, 'utf8').toString('base64')}`;
      }
      return svg;
    };

Replaces the window.btoa with Buffer.from().

I am unable to create a PR on work machine, will do later but putting this up for any others searching.

All the best!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
Thanks @skru I'll take care of it
