### ISSUE TITLE
BUG: Link Button Not work 

### ISSUE THREAD

**Issue by zithasdev** [artf/grapesjs#4475]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Chrome 103.0.5060.134

### Reproducible demo link

https://www.w3schools.com/html/tryit.asp?filename=tryhtml_links_w3schools

### Describe the bug

**How to reproduce the bug?**
1. .when i work my project related link 
2. ...

**What is the expected behavior?**
1.Drag it properly
2.Link to another Link as we give in refence which we want to open  

**What is the current behavior?**
...its not drag 
its not link to another link 

If is necessary to execute some code in order to reproduce the bug, paste it here below:
```js
// your code here
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
Sorry but you have to open the bug issue properly by following all steps and providing a reproducible demo.
