### ISSUE TITLE
How to remove SelectorManager

### ISSUE THREAD

**Issue by ateshuseyin** [artf/grapesjs#448]
I don't want SelectorManager in my project.

**Comment by artf** [comment]
What do you mean? SelectorManager is necessary to keep the collection of classes, it's a part of the  core, you can't remove it

**Comment by ateshuseyin** [comment]
At the top of style manager UI, there is Classes section. I want to remove it from UI.

**Comment by artf** [comment]
Currently, there is no option to disable it, but you can eventually hide/remove it with css/js for now

**Comment by thecodefish** [comment]
Try this:
``` css
.gjs-editor .gjs-clm-tags { display: none; }
```

Be aware though that by hiding this section, you lose the ability to select individual classes to modify. This means that if you make changes to the styles, you may encounter weird behaviour (for example, you have duplicate components on the page with custom classes, your changes may apply to both). See #404.

**Comment by ateshuseyin** [comment]
@thecodefish It works. Thanks.
@artf This issue can be closed.
