### ISSUE TITLE
BUG: Iframe on a block can't be edited

### ISSUE THREAD

**Issue by ValouZ** [artf/grapesjs#4480]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Firefox v102.0.1

### Reproducible demo link

This is work code i can't..

### Describe the bug

**How to reproduce the bug?**
1. Drag and drop on the page the block Video
2. You'll see that you can't do anything with my iframe

**What is the expected behavior?**
I want the iframe src to be editable

**What is the current behavior?**
Can't do anything with the iframe.
I can see the Iframe on the Layer Manager but if i open the inspector, there is only my section containing the Iframe.
This was woorking very well 2/3 weekd ago, i went on holiday, no one touched it because I'm the only one working on it and now its broken.

If is necessary to execute some code in order to reproduce the bug, paste it here below:
```js
blockManager.add("content-video", {
  label: "Vidéo",
  category: "Contenu",
  content: {
    tagName: "section",
    attributes: { class: "component video" },
    components: {
      draggable: false,
      removable: false,
      copyable: false,
      resizable: false,
      type: "iframe",
    },
  },
});
```

I hope you could help me, thanks a lot !

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
Thanks @ValouZ for the report, there is actually a typo on the iframe view. I'll take care of it for the next release.
