### ISSUE TITLE
BUG: Loading initial project data from a designer-mode project results in wrong canvas size

### ISSUE THREAD

**Issue by contentfree** [artf/grapesjs#4489]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Chrome v103

### Reproducible demo link

https://codesandbox.io/s/laughing-austin-k12mc3?file=/index.js

### Describe the bug

If you view the linked CodeSandbox and find the commented out line providing the projectData to the editor, you will see that the canvas gets resized away from the size specified by the device. In a debugger, it seems that `updateDim` is called multiple times at initialization: the first time with the correct device size and then again with empty width and height which then leads to the gjs-frame-wrapper's sizing getting removed.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by contentfree** [comment]
I can kinda force it back to the correct canvas size by running `editor.Canvas.getModel().updateDevice();` after everything is initialized though it animates from the full width back to device size. 

It seems that loading the project data happens _after_ the default device is rendered (maybe?) and somehow blows out the current frame, rerendering some default. (I don't know what the default is since I'm only providing a single device config, which appears to be ignored on the second render)

**Comment by artf** [comment]
Thanks @contentfree I'll try to fix that for the next release

**Comment by contentfree** [comment]
Thanks @artf. I'll keep my eye open for the next release (looks like your kanban board is empty now … so should be imminent?)

**Comment by artf** [comment]
I'll probably try to monitor and fix some other bugs before releasing a new version but I guess it might be something around the end of the next week.
