### ISSUE TITLE
Can i load editor content dynamically?

### ISSUE THREAD

**Issue by alissonphp** [artf/grapesjs#449]
I have a API rest that receives and supplies the contents of the editor items. The entire store created by the editor is saved: assets, components, css, ... Each item is accessible via route (eg editor / page / 4), when loading the route API returns to the content of the item, however when calling the action editor.storeManager.load (content), I can not load the content to the editor.

What would be the best way to work with this flow?

Thank you for your attention.

**Comment by artf** [comment]
If for content you mean html/css, probably you're looking for `editor.setComponents('<div>...')`
