### ISSUE TITLE
BUG: Seeing Multiple pages on scroll

### ISSUE THREAD

**Issue by ajjuyadav0209** [artf/grapesjs#4498]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

brave

### Reproducible demo link

https://codepen.io/etamity/pen/NWpKYPp

### Describe the bug

how to See multiple pages in onscroll using pageManager ?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
Please use Discussions for questions
