### ISSUE TITLE
Flex support

### ISSUE THREAD

**Issue by desprit** [artf/grapesjs#450]
In the demo I see "flex" tab which gives us all flex styles. But there is no such tab in current "0.12.17" version. Is it a custom build?

p.s. there are many other small differences between demo and available versions. Demo theme looks really amazing.

**Comment by artf** [comment]
Hi @desprit the demo extends the core grapesjs library with its own preset (styles and plugins). Probably soon I'll create its own repo
By the way, here you find the flex configuration: https://github.com/artf/grapesjs/blob/gh-pages/demo.html#L1149
