### ISSUE TITLE
BUG: 

### ISSUE THREAD

**Issue by udayan46** [artf/grapesjs#4501]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Chrome

### Reproducible demo link

no demo link

### Describe the bug

Hello @artf , can you please check these two
1.Cannot add color code manually in grapesjs editor
2. Import modal is not having any save option

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
Please don't open BUG issues if you're not able to provide a reproducible demo.
