### ISSUE TITLE
BUG: Error on drag block with dragmode: absolute 

### ISSUE THREAD

**Issue by tyutony** [artf/grapesjs#4506]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Chrome v103

### Reproducible demo link

https://stackblitz.com/edit/js-1xpo7b

### Describe the bug

**How to reproduce the bug?**
1. use dragMode: absolute (designer mode)
2. drag a block from Block Manager

Can not reproduce on [JSFiddle here](https://jsfiddle.net/g1reyutd/) but i dont know how.

I **guess** is CDNs grapesjs is different with npm version grapesjs.

**What is the expected behavior?**
No error and editor not stuck

**What is the current behavior?**
Console Error : editor is not defined and editor stuck

![1660117887338](https://user-images.githubusercontent.com/30591406/183845842-b3dcf20e-1baa-4896-9f6d-93794df1872e.gif)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
Thanks @tyutony the issue was fixed already (https://github.com/artf/grapesjs/pull/4487). Unfortunately, the only workaround now would be to expose globally the `editor` instance (`window.editor = grapesjs.init({...})`)

**Comment by wunksert** [comment]
@tyutony I'm experiencing this same thing, did you find a workaround? Doesn't seem like the bug is fixed

**Comment by artf** [comment]
@wunksert it's fixed but not yet released (the new release will be published soon)
