### ISSUE TITLE
Make block manager default open panel?

### ISSUE THREAD

**Issue by Geczy** [artf/grapesjs#454]
I tried this code:

```js
// Show blocks by default, not styles
editor.Panels.getButton('views', 'open-sm').set('active', false)
editor.Panels.getButton('views', 'open-blocks').set('active', true)
```

It works but doing this will hide the device selector in the top left for some reason.

**Comment by artf** [comment]
try just with
```js
editor.Panels.getButton('views', 'open-blocks').set('active', true)
```
but put it after the render (if you're using `autorender: false`)

**Comment by Geczy** [comment]
Ah, setting it after render works great. Thanks
