### ISSUE TITLE
BUG: Component disappears when we select all the inner text and use backspace. Link component disappears even when we try to update the text.

### ISSUE THREAD

**Issue by FaisalShaikhHA** [artf/grapesjs#4546]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Version 104.0.5112.101 (Official Build) (arm64)

### Reproducible demo link

https://codepen.io/faisal-praella/pen/rNvOwgR

### Describe the bug

**How to reproduce the bug?**
1. Select a component, double click, and ctrl+a to select the text and click backspace.
2. Notice component disappears, and is not selectable or editable.

**What is the expected behavior?**
The component should not disappear.

**What is the current behavior?**
Component disappears, and is not selectable or editable.

https://user-images.githubusercontent.com/102785785/188111128-9b174ea7-590b-4552-86d2-a93d214a2588.mp4

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
@FaisalShaikhHA are you able to provide a reproducible demo as I'm not able to reproduce it from the official demo?

**Comment by FaisalShaikhHA** [comment]
@artf here is the demo: https://codepen.io/faisal-praella/pen/rNvOwgR
Select a component, double click, and ctrl+a to select the text and click backspace.
Notice component disappears, and is not selectable or editable.
Link component disappears even when we try to update the text.
Please refer above video.

**Comment by FaisalShaikhHA** [comment]
Thanks @artf for your help, it is working.
