### ISSUE TITLE
Ask for user input for text/imageurl/hyperlink

### ISSUE THREAD

**Issue by krunal039** [artf/grapesjs#455]
we are building template where it will render div with background image and on hover it will display some text, also there will be hyper link when someone click on it should redirect user to and also title below image for text.

We have built template but we could not build in such way where once user drop template we show popup for user to provide all necessary information and once user provide it we render template

**Comment by artf** [comment]
check here #286

**Comment by krunal039** [comment]
@artf thanks for reply but still I could not understand how to create block with component as component are building block and block will be made of components. we wants to have single window where user can porvide all information on block drop.

**Comment by artf** [comment]
Check out [Blocks](https://github.com/artf/grapesjs/wiki/Blocks) and [Components](https://github.com/artf/grapesjs/wiki/Components) documentation

**Comment by krunal039** [comment]
@artf I looked at it but could not understand more if you can point to any demo/sample code for same?

**Comment by krunal039** [comment]
@artf  just for more info we want to have simmilar template as below and i looked at issue and reference you suggested but could not find solution

We have Image as background-->mouse link --> href for click and below that we have title.

![sample](https://user-images.githubusercontent.com/11716808/32332931-920690e0-bfde-11e7-8de0-0395f22e3080.png)
