### ISSUE TITLE
RTE actions are not working after the first time

### ISSUE THREAD

**Issue by DhanaDSP1120** [artf/grapesjs#4559]
Hi..!, the RTE actions are not working after the first time , when we try to apply the action on previous applied element its not working

It occurs on version 0.18.3 to till latest , its working fine on below versions

Reproduce links

Working version : 
https://jsfiddle.net/76gnxh4d/35/

Not working version :
https://jsfiddle.net/76gnxh4d/36/

Demo :
![grapesjs version issue](https://user-images.githubusercontent.com/54067384/188276505-70b8ead9-f0e4-4d82-ae31-09ae478ef468.gif)

_Originally posted by @DhanaDSP1120 in https://github.com/artf/grapesjs/discussions/4549_

**Comment by artf** [comment]
Should be fixed in the latest [version](https://github.com/artf/grapesjs/releases/tag/v0.20.1).

**Comment by DhanaDSP1120** [comment]
@artf Font color only working , Font background color not working on second time 

https://jsfiddle.net/a3xgLm7c/3/
![val 5](https://user-images.githubusercontent.com/54067384/199990775-a8a3c5dd-d943-4f6a-b473-0af7d6ebf8ac.gif)

**Comment by gs-sgakula** [comment]
Hi @DhanaDSP1120 , I am also facing the same issue. Do you have a solution for it?

**Comment by Sivaganesh-Akula** [comment]
Hi @DhanaDSP1120 , I am also facing the same issue. Do you have a solution for it?
