### ISSUE TITLE
Combobox cross-browser issues

### ISSUE THREAD

**Issue by leantorres73** [artf/grapesjs#456]
I found that the combobox has different styles on different browsers.

Firefox 56.0.2 (64-bits):
![captura de pantalla 2017-10-27 a las 17 23 49](https://user-images.githubusercontent.com/12806363/32123725-92af301a-bb65-11e7-8029-6d1142692128.png)

Chrome:
![captura de pantalla 2017-10-27 a las 17 26 47](https://user-images.githubusercontent.com/12806363/32123822-fa06f5e0-bb65-11e7-8cce-69b735cb9f91.png)

Safari:
![captura de pantalla 2017-10-27 a las 17 27 57](https://user-images.githubusercontent.com/12806363/32123870-22f599de-bb66-11e7-88a5-4676988927b4.png)

I think the problem is with Firefox. 
Also when opening the select, firefox displays some white borders:
![captura de pantalla 2017-10-27 a las 17 28 27](https://user-images.githubusercontent.com/12806363/32123900-3c61c550-bb66-11e7-9057-f538630ad40c.png)

As Firefox use custom select this gives me issues when changing to a light theme.

**Comment by santiph** [comment]
With the light theme enabled, this is what select boxes look like on Firefox for OSx
<img width="198" alt="screen shot 2017-10-27 at 19 15 28" src="https://user-images.githubusercontent.com/747646/32127161-47023f32-bb4b-11e7-8f55-b0eeab1171e6.png">

@artf for consistency purposes, how should select boxes behave and look like across different browsers? Native or custom?

**Comment by leantorres73** [comment]
@artf I can work on it if you give me the indications, or if you want I can propose something.

**Comment by artf** [comment]
Thanks @leantorres73 a PR would be great.
It's all about CSS and the problem is the `<option>` styling that should be here:
https://github.com/artf/grapesjs/blob/dev/src/styles/scss/_gjs_inputs.scss
(just try to search `option`)
I think it would be best to remove all those stylings
