### ISSUE TITLE
Two Quick Questions

### ISSUE THREAD

**Issue by mekamleshk** [artf/grapesjs#457]
Hi @artf 

1) I have my editor templates like this : 
![1](https://user-images.githubusercontent.com/16983847/32127077-ede6df38-bb91-11e7-819f-e8e805403e3d.JPG)

I want to change the alignment and also add a back button to the corner left like this one :
![2](https://user-images.githubusercontent.com/16983847/32127103-21c5d764-bb92-11e7-824d-072f653e3c23.JPG)

2) Don't know for what reason whenever I select text the ckeditor options always appear at the top :
![capture](https://user-images.githubusercontent.com/16983847/32127135-55352b86-bb92-11e7-8845-8c3755d89cf6.JPG)

I want it to appear besides the selected text like this :
![capture1](https://user-images.githubusercontent.com/16983847/32127147-6e3456ca-bb92-11e7-8862-f4e59fec8cb5.JPG)
 

Thanks

**Comment by artf** [comment]
1. Check the [Panels API](https://github.com/artf/grapesjs/wiki/API-Panels) or you can just append/remove stuff once the editor is loaded
```js
editor.on('load', () => {
     // change your DOM here
})
```
2. Just tried it the demo and works as expected, probably you have multiple nested text components, where in that case the toolbar appears on top of the highest editable component
