### ISSUE TITLE
BUG: TypeError: m.render is not a function

### ISSUE THREAD

**Issue by rahul-singh-bv** [artf/grapesjs#4570]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Chrome Version 105.0.5195.102 (Official Build) (x86_64)

### Reproducible demo link

-

### Describe the bug

**How to reproduce the bug?**
1. Create a new custom code block and add an iframe tag such as `<iframe src="http://localhost:8888/embed/shopping-list"></iframe>

**What is the expected behavior?**
It inserts an iframe in the canvas

**What is the current behavior?**
It errors out and fails

If is necessary to execute some code in order to reproduce the bug, paste it here below:
No 

Error log
```
TypeError: m.render is not a function
    at a.value (ComponentsView.js:86:23)
    at a.value (ComponentsView.js:39:10)
    at y (backbone.js:371:57)
    at m (backbone.js:356:19)
    at h (backbone.js:155:16)
    at u.trigger (backbone.js:346:5)
    at n._onModelEvent (backbone.js:1187:20)
    at y (backbone.js:372:58)
    at m (backbone.js:357:22)
    at h (backbone.js:155:16) {level: 'error'}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
Thanks for the report @rahul-singh-bv
The bug was actually already reported and fixed https://github.com/artf/grapesjs/issues/4480 but unfortunately not yet released 😞
