### ISSUE TITLE
Custom is missing in the AssetManagerConfig

### ISSUE THREAD

**Issue by Aventrue** [artf/grapesjs#4575]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Chrome

### Reproducible demo link

this is a compile error

### Describe the bug

The property custom is missing in the AssetManagerConfig.
It works if I use the untyped grapesjs but I want use it with types. Is there a workaround for this problem?

Id do it like discripted here: https://grapesjs.com/docs/modules/Assets.html#customization
![image](https://user-images.githubusercontent.com/17627637/189477806-df81bcab-9a07-41f6-b886-418972df5d17.png)

index.d.ts
![image](https://user-images.githubusercontent.com/17627637/189477869-acf0b7b7-c846-4527-baba-054a1263343e.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Aventrue** [comment]
My workaround:

let assetConfig: grapesjs.AssetManagerConfig;
    assetConfig["custom"] = {
      open: (props) => {
        console.error(props);
        this.openGalleryDialog(props);
      },
      close: (props) => {
        this.dialog.closeAll();
      },
    };

**Comment by Singwai** [comment]
Feel free to update the type definition, here is an example commit.

https://github.com/artf/grapesjs/commit/49deeeeab74aff3e46f22d0bb06e7f7608955afd
