### ISSUE TITLE
BUG: prevent event using custom plugin 

### ISSUE THREAD

**Issue by joukhar** [artf/grapesjs#4577]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

chrome latest

### Reproducible demo link

there is not demo

### Describe the bug

I want to prevent event but i can't i tried  this
and how to prevent store event please help
```js
    editor.off('asset:upload:error');
    editor.on('asset:upload:error', function (e) {
        // e.preventDefault();
        console.log(e);
    })
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
You can use Discussions if you have questions, Issues are only for reproducible bugs
