### ISSUE TITLE
BUG: Resizer onEnd callback should include the resizer and el object similar to onStart

### ISSUE THREAD

**Issue by Singwai** [artf/grapesjs#4579]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Any

### Reproducible demo link

See screenshot for code

### Describe the bug

Is there anything preventing us from adding the resizer and el in the onEnd callback? Since we are reusing the resizer instance (unless forceNew). I would like to have to clean up the resizer state at the end of resizing

## onStart
https://github.com/artf/grapesjs/blob/dev/src/utils/Resizer.js#L295
![image](https://user-images.githubusercontent.com/5863227/189768636-903f2a1c-e99d-47dd-8f60-7ddbb9e1a61d.png)

## onEnd
https://github.com/artf/grapesjs/blob/dev/src/utils/Resizer.js#L343
![image](https://user-images.githubusercontent.com/5863227/189768827-d6143dab-754d-4de1-8f5c-f21187799ddc.png)

Happy to create a PR for this. Just want to verify this is an acceptable behavior beforehand

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
Sure, I'll add it, thanks for the suggestion.
