### ISSUE TITLE
BUG: Resizer cursor's starting position should also use the `mousePosFetcher` if provided.

### ISSUE THREAD

**Issue by Singwai** [artf/grapesjs#4580]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

any

### Reproducible demo link

any

### Describe the bug

Start Pos should also use the `MosePosFetcher` method if the override is provided right?

## Start Pos

![image](https://user-images.githubusercontent.com/5863227/189769981-c1d875e4-beeb-44b4-9963-f4131f3c3d6f.png)

https://github.com/artf/grapesjs/blob/dev/src/utils/Resizer.js#L278-L281

## Current Pos
![image](https://user-images.githubusercontent.com/5863227/189769786-4b466fd3-1410-4417-b5c5-dfbb92098756.png)
https://github.com/artf/grapesjs/blob/dev/src/utils/Resizer.js#L306-L312

Happy to create a PR for this, just want to make sure that is a desired behavior.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
Yeah, you're right, I'll fix it, thanks for the report.
