### ISSUE TITLE
BUG: API Docs Configuration Object link broken

### ISSUE THREAD

**Issue by wunksert** [artf/grapesjs#4588]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Safari

### Reproducible demo link

https://grapesjs.com/docs/api/editor.html#editor

### Describe the bug

**How to reproduce the bug?**
1. Visit https://grapesjs.com/docs/api/editor.html#editor
2. Click "Configuration Object" on line 2 and 33. 

OR visit this link: https://github.com/artf/grapesjs/blob/master/src/editor/config/config.js
**What is the expected behavior?**
Load configuration object reference

**What is the current behavior?**
404 on Github pages

If is necessary to execute some code in order to reproduce the bug, paste it here below:
```js
// your code here
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
Thanks @wunksert the link is already updated and will be fixed on the next release
