### ISSUE TITLE
Cancel adding a component

### ISSUE THREAD

**Issue by sebastianha** [artf/grapesjs#46]
Is there a way to cancel adding a component, for example to limit the number of components of one type in the canvas or when something went wrong while adding the component (for example when no image has been selected)

**Comment by artf** [comment]
Maybe catching the 'add:component' event might help you

```js
// Triggered when a new component is added to the canvas  
editor.on('add:component', function(model) {
   // Few hints:
   // You can reach the view from the added model
   var view = model.view;
   // You can get the parent model from the collection which model belongs to
   var parentModel = model.collection.parent;
  });
```
