### ISSUE TITLE
After Update to 0.20 from 0.19 the error Cannot assign to read only property 'defaults' of object '[object Object]' occurs

### ISSUE THREAD

**Issue by Aventrue** [artf/grapesjs#4600]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

chrome

### Reproducible demo link

none

### Describe the bug

![image](https://user-images.githubusercontent.com/17627637/191345937-46111515-ce5f-4cb4-a52c-e9300751717f.png)
image.js :
![image](https://user-images.githubusercontent.com/17627637/191346008-51a5519f-0a82-462e-9c00-904dc41602f8.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by collins-lagat** [comment]
The release says that there a breaking change. Try that and see if the problem goes away. I got the same error but haven't tried the fix yet.
https://github.com/artf/grapesjs/releases/tag/v0.20.1

**Comment by artf** [comment]
Yes, as mentioned in the release note you have to switch from the old legacy API for custom component registration.
