### ISSUE TITLE
BUG: Webpage Demo displaying incorrectly on Firefox

### ISSUE THREAD

**Issue by Akira-Kuru** [artf/grapesjs#4603]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Firefox 105.0 (64-bit)

### Reproducible demo link

https://grapesjs.com/demo.html

### Describe the bug

**How to reproduce the bug?**
1. Opening up the demo Page (https://grapesjs.com/demo.html) in Firefox.

**What is the expected behaviour?**
That the toolbar isn't zoomed in to the point you can't see the website.

**What is the current behaviour?**
The toolbar is zoomed in surely 300% more than usual.

Google Chrome Example:
![correct](https://user-images.githubusercontent.com/7903248/191632720-57ebb0fb-6cef-4a31-9fd2-5ec9c4e40ed9.JPG)

Firefox Example:
![error](https://user-images.githubusercontent.com/7903248/191632580-93a5fb40-21a0-4685-8f6c-1a313dea0a84.JPG)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
Yeah thanks @Akira-Kuru fixed the issue here https://github.com/artf/grapesjs-preset-webpage/releases/tag/v1.0.2
