### ISSUE TITLE
A script delcaration mistake at "Commponent & JS" documentation page.

### ISSUE THREAD

**Issue by bit-ocean** [artf/grapesjs#4606]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

irrelevant to the issue

### Reproducible demo link

https://grapesjs.com/docs/modules/Components-js.html#basic-scripts

### Describe the bug

Hey, rather than creating a pull request for such a small change, I share it here.

The introduction code in Basic Scripts at https://grapesjs.com/docs/modules/Components-js.html#basic-scripts misses a keyword, that may confuse or mislead new users as there is no other example of declaring component script on the page:

```js
  model: {
    defaults: {
      script,
```

should be:

```js
  model: {
    defaults: {
      script: script,
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
The `script` is right above
![ccc](https://user-images.githubusercontent.com/11614725/192133350-34390584-4b07-4533-ac1b-15dcf33f1195.png)

ps: you can use Discussions if you're not reporting a bug
