### ISSUE TITLE
BUG: JS error when moving an element with its child

### ISSUE THREAD

**Issue by RomanGlazkov** [artf/grapesjs#4607]
### GrapesJS version

- [x] I confirm to use the latest version of GrapesJS

### What browser are you using?

Chrome v104

### Reproducible demo link

https://grapesjs.com/demo.html

### Describe the bug

**How to reproduce the bug?**
1. Select an element
2. Hold down the CTRL key and select a child element
3. Try moving these elements

**What is the expected behavior?**
Editor does not allow moving

**What is the current behavior?**
Move doesn't happen but there is a js error

![Peek 2022-09-23 15-20](https://user-images.githubusercontent.com/66161402/191958965-85b27a78-9e0d-4598-9324-697d67aef2f2.gif)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
I guess we should avoid selecting children of already selected components in the first place.
