### ISSUE TITLE
BUG: After upgrading from 0.19.4 to latest version 0.20.1, icons under layer manager not visible.

### ISSUE THREAD

**Issue by FaisalShaikhHA** [artf/grapesjs#4608]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Version 104.0.5112.101 (Official Build) (arm64)

### Reproducible demo link

Screenshot: https://d.pr/i/AyHJyL

### Describe the bug

**How to reproduce the bug?**
1. Upgrade to the latest grapesjs version.

**What is the expected behavior?**
Icons under layer manager should be visible.

**What is the current behavior?**
Icons under layer manager are not visible.

<img width="1438" alt="Markup 2022-09-23 at 17 58 43" src="https://user-images.githubusercontent.com/102785785/191963783-7a4295e1-1a97-4837-af6b-72bf648bdbb3.png">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
Is it what you see also here https://grapesjs.com/demo.html? I see those icons properly 🤔

**Comment by FaisalShaikhHA** [comment]
No, on the demo page icons are visible properly.
To update grapesjs I removed the old version by using `npm remove grapesjs` and then `npm install grapesjs` to get the latest version.
I also tried deleting grapesjs folder from node_modules and then used `npm install grapesjs` but no luck still icons are not rendered.

**Comment by FaisalShaikhHA** [comment]
@artf I got the issue this is because of `box-sizing` CSS but when I try to remove or update this my layout gets distorted.
Count and move icon still not visible.

https://user-images.githubusercontent.com/102785785/192205091-b55a1cfa-38d6-4079-9ff0-eb03ff72920f.mp4

**Comment by FaisalShaikhHA** [comment]
@artf this is the css
```
*,
*::before,
*::after {
  box-sizing: border-box;
}

``` which is causing problem when I upgrade from 0.19.4 to any greater version.

**Comment by FaisalShaikhHA** [comment]
After adding above mentioned css on the demo page, icons not visible on the [demo](https://grapesjs.com/demo.html) as well.
<img width="1440" alt="Screenshot on 2022-09-26 at 18-54-45" src="https://user-images.githubusercontent.com/102785785/192288669-00120493-6d93-4d6b-a352-2d6642ac8151.png">

**Comment by artf** [comment]
Thanks @FaisalShaikhHA ok I'll fix that as that rule is quite common.
