### ISSUE TITLE
RTE toolbar appears in the top panel

### ISSUE THREAD

**Issue by roytang** [artf/grapesjs#461]
Hi,

We recently updated GrapesJS from 0.8.8 to 0.12.15. After the upgrade, I found that the rte-toolbar appears in the top panel for some reason. I've tried doing a clean call of grapesjs (copied from the wiki):

```
    var editor = grapesjs.init({
      container : '#gjs',
      components: '<div class="txt-red">Hello world!</div>',
      style: '.txt-red{color: red}',
    });    
```

But the toolbar is still there:
https://i.imgur.com/gcaBti2.png

After I double-click the "Hello world" text, the rte-toolbar appears near it and disappears from the top panel. But it appears there again if reload the page.

Any advice how I can prevent it from appearing there?

**Comment by artf** [comment]
Seems like it's  just not hidden on render, will fix it for the next release
