### ISSUE TITLE
BUG: Cannot Drop MJML Components onto Blank Canvas after version 0.19.4

### ISSUE THREAD

**Issue by Drew-Daniels** [artf/grapesjs#4612]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

105.0.5195.125 (Official Build) (x86_64) 

### Reproducible demo link

https://codesandbox.io/s/grapesjs-grapesjs-mjml-react-bug-w7qtec?file=/src/index.js

### Describe the bug

**How to reproduce the bug?**
1. Start with a blank canvas
2. Try dragging a `grapesjs-mjml` block editor component onto the blank canvas.
3. See that you cannot, and receive this warning logged to console:
![image](https://user-images.githubusercontent.com/62859552/192033463-a0341e69-f305-495f-8b05-ab6110c9e279.png)

### Video:
There's a delay in the logged warning because CodeSandbox is being slow:
[screen-capture (3).webm](https://user-images.githubusercontent.com/62859552/192034676-84ca848d-5c51-48a9-92af-c472bd768221.webm)

### Code:
I've reproduced the code in this repository as it's easier to test with than in CodeSandbox IMO: https://github.com/Drew-Daniels/grapesjs-react-bug 

**What is the expected behavior?**
I would expect to be able to drop components from the `grapesjs-mjml` block editor onto a blank canvas.

**What is the current behavior?**
I am not able to drop components from the `grapesjs-mjml` block editor onto a blank canvas. This only occurs after upgrading `grapesjs` from `0.18.4` to `0.19.4` or above.

If is necessary to execute some code in order to reproduce the bug, paste it here below:
- All necessary code is provided in the CodeSandbox link above.

Notes:
I created a [bug ticket](https://github.com/artf/grapesjs-mjml/issues/297) in the `grapesjs-mjml` repository for this as I originally thought it might have been due to a bug in that plugin. However, after doing some more research I noticed that this problem started occurring after this [commit](https://github.com/artf/grapesjs/commit/981bc7012c90d7b19785414c220b31e2ae7481dc) in `grapesjs`.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
Thanks for the report Drew, this seems to be related to the Standards mode of the iframes. At the moment to fix it, I'd suggest switching to the Quirks mode by removing the doctype:
```js
grapesjs.init({
  // ...
  canvas: {
    frameContent: '', // default is '<!DOCTYPE html>'
  },
})
```
I'm closing the issue as it's not really related to the core, soon I'll update the mjml plugin in order to support properly the Standards mode.
