### ISSUE TITLE
BUG: No Option found for showing multiple pages on a single canvas 

### ISSUE THREAD

**Issue by shelendravashishtha2** [artf/grapesjs#4621]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Chrome

### Reproducible demo link

NO LINK

### Describe the bug

Hi,

I am using grapsjs with react, found it very useful so far but I want to show all the pages created in my application to be previewed on canvas but found no options or alternatives for the same. can you please help me with that ?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stljeff1** [comment]
I believe you have to make your own component to show multiple pages and click between them.

here is an example that I found in these forums which show how to create your own Page Manager component. https://codepen.io/artf/pen/XWpJQoY

**Comment by artf** [comment]
@shelendravashishtha2 use Bug Issues properly please, if you have questions, use Discussions.

**Comment by dali-97** [comment]
hello any one can help i need somthing that allow me to create a multiple custem page like grapesjs i need it for my diplom thanks
