### ISSUE TITLE
Is the video component on the webpage demo working?

### ISSUE THREAD

**Issue by roytang** [artf/grapesjs#463]
I wanted to study how to use the video component but the one on the demo website (http://grapesjs.com/demo.html) doesn't seem to be working? 

Dropping a video component into the canvas shows a still photo with some lights. If I click the edit icon, the photo editor opens with no content and no toolbar and a bunch of JS errors in the console.

**Comment by artf** [comment]
It's not a photo but actually, a video (I just turned off autoplay), if you toggle controls and turn on the preview you should be able to see it play.
About the edit button, I think it's a bug, should not be there, I'll check it later

**Comment by roytang** [comment]
How to toggle controls and turn on the preview?

**Comment by artf** [comment]
![text-edit](https://user-images.githubusercontent.com/11614725/32446045-f2c025aa-c307-11e7-876e-5bbb83c4ef0b.gif)

**Comment by ShubhamProgrammer** [comment]
@artf , i am new to this.  can we customise the video component i.eadding of  id/Src/link  by which the video play after the drag of video component over canvas.
plz help
thnx
