### ISSUE TITLE
Adding class to style?

### ISSUE THREAD

**Issue by jiggyt** [artf/grapesjs#464]
Hello, sorry if this was asked before but i searched and couldnt find anything re this. 

How would i  reference a component (textbox) under content to a default unique class instead of having to type the css attribute one by one?

e.g. (not working) below, input-control is the class. 

	 id: 'email',
            label: 'email',
            category: 'Extra',
            attributes: {class:'fa fa-map-o'},
            content: {
              type: 'input',
		   style: {class: 'input-control'}
            },

tried every possible permutation e.g. style: {'.input-control'}, putting another attributes tag, or class: {'input-control'} but editor doesn't load when any of this is done. Sorry for the trouble and thanks in advance.

**Comment by artf** [comment]
Use `classes` key
```js
...
content: {
     type: 'input',
     classes: ['class1', 'class2', ...],
     // Inside style you put inline styles
     style: {'text-align': 'center', ....}
}
...
```
