### ISSUE TITLE
Disable button

### ISSUE THREAD

**Issue by arthuralmeidap** [artf/grapesjs#466]
Hi,

  I added a new button in Options Panel and now I'm trying to make it disable while a given criteria is not ok.
  For now, I tried to use the myButton.set('active', 1) but this is not I'm looking for. 

  I take a quick look on GrapesJS code and I didn't see an option to disable the button or make it "unclickable". 

  Is there any built-in feature for this? Or do I need to hack the grapes and add this support?

**Comment by artf** [comment]
Hi Arthur, unfortunately, there is no 'disable' feature, but it'd be cool to have

**Comment by arthuralmeidap** [comment]
Hey @artf ,
  This is not related to this issue, but do you know when a next version will be released?
  There is some improvements on dev branch that would be nice to have them.

**Comment by artf** [comment]
`disable` attribute is ok 👍  but be patient because ButtonView is really old and messy (Panels is one of the modules that require huge refactoring)

**Comment by arthuralmeidap** [comment]
@artf , 
  WHere can I create a css class for disable like you created for active?

**Comment by artf** [comment]
Probably I'd just add `.#{$app-prefix}disabled` to this https://github.com/artf/grapesjs/blob/dev/src/styles/scss/main.scss#L120
What do you think?

**Comment by artf** [comment]
I close this as #479 was already merged
