### ISSUE TITLE
Set the focus to some other element

### ISSUE THREAD

**Issue by perfect-coders** [artf/grapesjs#467]
I am opening a pop up on click o some element, but the focus is still on the element on which I click. I want to focus the pop up element. 
Is there any way in grapesjs ?

**Comment by artf** [comment]
Which popup are you talking about? The built-in modal?

**Comment by perfect-coders** [comment]
I have make one custom pop up in grapejs and opening on element click. So I want when user user on the element , a pop up will open and the pop will be selected by default.

**Comment by artf** [comment]
well, if it's your custom popup I think it's up to you managing the focus

**Comment by perfect-coders** [comment]
I have tried a lot of ways but is there any way in grapes which is used to select the another component.

**Comment by artf** [comment]
to select another component you should use https://github.com/artf/grapesjs/wiki/API-Editor#select
