### ISSUE TITLE
BUG: Module not found: Error: Can't resolve 'utils/mixins'

### ISSUE THREAD

**Issue by nabtron** [artf/grapesjs#4682]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

chrome 106

### Reproducible demo link

localhost

### Describe the bug

i updated my project containing grapesjs, however now i get this error:

when i run my project, i get this error: 

```
Failed to compile.

Module not found: Error: Can't resolve 'utils/mixins' in /node_modules/grapesjs/src/common'
ERROR in ./node_modules/grapesjs/src/common/module.js 2:0-58
```

this is what top 2 lines of module.js has:

```
import { isString, isElement } from 'underscore';
import { createId, deepMerge, isDef } from 'utils/mixins';
```

I have tried installing: 
```
npm i utils/mixins
```
but it fails too

how can i solve it please?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
You shouldn't try to compile grapesjs source code as the source could contain bundler-related content (as the one you mention, it's not an external package)

**Comment by nabtron** [comment]
@artf you shouldn't try to close tickets without reading them first. 

If you will read the issue, you will see that i mentioned when i "updated" it, i updated it using npm i by changing grapesjs version in package.json to latest version.

The code breaks from 0.19.4 onwards, since you started using .ts file in modules.ts

**Comment by artf** [comment]
Yeah I understand that you have simply updated the version but it looks like you're trying to read the source of the grapesjs package, which is wrong (probably in the future, the `src` folder will be even removed)
