### ISSUE TITLE
Undo manager - Not working properly, when we try to apply and undo the background color then made click outside the block, then the removed color will appears

### ISSUE THREAD

**Issue by DhanaDSP1120** [artf/grapesjs#4691]
Undo manager - Not working properly, when we try to apply and undo the background color then made click outside the block, then the removed color will appears

It occurs on version 0.19.4 to till latest , its working fine on below versions

Reproduce links

Working version :
https://jsfiddle.net/0vpbLmxy/

Not working version :
https://jsfiddle.net/q3cgwa5m/1/

Demo :
![grapesjs undo issue](https://user-images.githubusercontent.com/54067384/197989568-5b29f18e-cf93-4cd6-a6ad-bec0ddd283ad.gif)

_Originally posted by @DhanaDSP1120 in https://github.com/artf/grapesjs/discussions/4690_

**Comment by artf** [comment]
Seems to be an issue with the color picker itself, I'll try to fix it for the next release.

ps: for bug reports you don't need to create the discussion first, you can open directly the issue by following the template. This will also avoid unnecessary discussion posts.
