### ISSUE TITLE
BUG:  Undo not working properly on InsertHTML in text block

### ISSUE THREAD

**Issue by DhanaDSP1120** [artf/grapesjs#4699]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

chrome v107

### Reproducible demo link

https://jsfiddle.net/4vacxuw2/2/

### Describe the bug

 I added an custom toolbar to insert some value in current position through rte.insertHTML options ,it works good. But when try to undo (ctrl+z) the newly inserted HTML block was not removed 
  
![grapesjs undo issue on insertHTML](https://user-images.githubusercontent.com/54067384/198582651-26c3613a-003d-4907-a761-746d75f8880a.gif)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
Hi @DhanaDSP1120 yeah unfortunately that is expected from `rte.insertHTML` as it uses a custom insertion. If you need to preserve the native editing undo stack you can use this API
```js
rte.exec('insertHTML', `<span ...`)
```
