### ISSUE TITLE
Variable Undefined

### ISSUE THREAD

**Issue by NJseo** [artf/grapesjs#47]
It can't understand grapesjs for some reason. Says can't find variable.

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title><script src="http://code.jquery.com/jquery-2.2.0.min.js"></script>
    <link rel="stylesheet" href="../grapesjs/dist/css/grapes.min.css">
    <script src="../grapesjs/dist/grapes.min.js"></script>
</head>
<body>

<div id="gjs"></div>

<script type="text/javascript">
    document.addEventListener("DOMContentLoaded", function() {
        var editor = grapesjs.init({
            container : '#gjs',
            components: '<div class="txt-red">Hello world!</div>',
            style: '.txt-red{color: red}',
        });
    });

</script>

</body>
</html>

**Comment by NJseo** [comment]
It needs to use DOM ready before executing the javascript

**Comment by artf** [comment]
There is no '#gjs' element in your code?!?
