### ISSUE TITLE
Modal Error

### ISSUE THREAD

**Issue by mekamleshk** [artf/grapesjs#470]
Hi @artf 

When I try to click on the sent-test button it gives me this error, I tried with the updated version of grapesjs-preset-newsletter

![capture](https://user-images.githubusercontent.com/16983847/32224638-52d62c90-be68-11e7-8b5a-89aca14183da.PNG)

**Comment by artf** [comment]
@mekamleshk that button was removed, you can check it also here http://grapesjs.com/demo-newsletter-editor.html

**Comment by mekamleshk** [comment]
@artf 
I know you removed it earlier, but I was using it as pop up box to save my template into database.
Is it that it is completed removed from the framework ?

**Comment by artf** [comment]
It never was part of the framework, it's just a custom panel I used in https://github.com/artf/grapesjs/blob/gh-pages/demo-newsletter-editor.html
