### ISSUE TITLE
BUG: Add images to Asset Manager

### ISSUE THREAD

**Issue by Aar-if** [artf/grapesjs#4700]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Firefox

### Reproducible demo link

NA

### Describe the bug

So as per your previous suggestion on issue #4681, the issue was in the body parser so I used Multer for parsing and uploaded the images on s3 bucket also I am generating a list of all the stored Images from s3 and sending it to my Frontend to diplay them in Asset Manager 

Here is my code, on opening the canvas I have written a axios call to get all the images from Backend and then storing it in awsimages using React useState, the issue is I am getting the images also they are getting stored in useState in the form of an Array,

![image(1)](https://user-images.githubusercontent.com/102529125/199014362-a80eb22d-e31b-43d7-82cb-4ed515e58ae0.png)

  how do I use those images stored in the State and display inside the asset manager, technically we directly use the variable (awsimages) to access the stored data so I directly initialized the same inside Asset Manager like this :

 assetManager: {

        assets : awsimages,
}

where aws images is an Array of Images

  const [awsimages, setAwsimages] = useState([]);

  useEffect(() => {

    async function getAws() {
      try {
        const response = await Axios.get( 
          "http://localhost:5002/api/grapesjs/assets"                           // getting list of Images
        );
        console.log("ASSET RESPONSE");
        console.log(response.data.Contents);       
        console.log(response.data.Contents);     
        var src = [];
        var images = response.data.Contents;
        for (var i = 0, iLen = images.length; i < iLen; i++) {
          src[i] = images[i].Key;
          console.log("ASSET RESPONSE 2");
        }
        console.log(src);
        setAwsimages(src);                                              // setting Images in useState
        
      } catch (error) {
        console.log("The error is", +error);
      }
    }
      getAws();
      
    }, []);

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
Not a bug, you just need to refresh the AssetManager assets (`editor.Assets.clear().add(newAssets)`) as the editor is probably already loaded.
