### ISSUE TITLE
Modal

### ISSUE THREAD

**Issue by mekamleshk** [artf/grapesjs#472]
Hi @artf 
I am trying to save my template in database on click of save I wanted to show a success message in toast.

Can you please help me with some example code.

![untitled](https://user-images.githubusercontent.com/16983847/32262987-af968c0a-befd-11e7-8784-9e54d7baf17c.png)

**Comment by artf** [comment]
Use storage events (you can find the complete list of events here: [API Editor](https://github.com/artf/grapesjs/wiki/API-Editor))
```js
editor.on('storage:store', res => {
     // ...do stuff
})
```
