### ISSUE TITLE
External Style Sheet

### ISSUE THREAD

**Issue by arunBenchamin** [artf/grapesjs#473]
Nice work .Got a little problem if the  styles for the web page  is moved to a stylesheet then most of the css properties in decorations sections not loading from stylesheet.  (eg: background-image property for header)

**Comment by artf** [comment]
This is a correct behavior if you're loading CSS as a remote resource. One workaround, for your case, would be to load CSS via ajax and add the result with `editor.addComponents('<style>${cssText}</style>')`
