### ISSUE TITLE
BUG: Tabs behaviour after HTML import

### ISSUE THREAD

**Issue by Rilvatore** [artf/grapesjs#4732]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Chrome 107 (MacOS)

### Reproducible demo link

https://grapesjs.com/demo.html

### Describe the bug

**How to reproduce the bug?**
1. Drag and drop the Tabs block into the editor content
2. Click on the "import" button on the top
3. Change something in the html content (rename one of the previous tabs created for example)
4. Click on "import"

**What is the expected behavior?**
The tabs have to be editable (add new tab and navigate between them) after html import

**What is the current behavior?**
The tabs have not the "tab" type anymore and can't be edited

Before html import:
![Capture d’écran 2022-11-17 à 10 50 41](https://user-images.githubusercontent.com/8143609/202414876-63cc7578-2639-4bdc-b0f4-74e296b4deaf.png)

After html import:
![Capture d’écran 2022-11-17 à 10 51 04](https://user-images.githubusercontent.com/8143609/202414988-e885a539-27e7-4383-95ff-f415984361f7.png)

Thank you for your help!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
This is not related to the core but more on the Tab plugin which is not re-importable by default.

**Comment by Rilvatore** [comment]
Hey! Thanks a lot for the answer.
In fact, the issues seems to come from the reimport code & store manager, that does not update the JSON part of the code. Would you have a way to take a look? Or should we create the same ticket on the tab plugin branch and/or the re-import plugin branch?

**Comment by artf** [comment]
It's related to the Tab plugin as once you print its HTML there is no way to reimport is back. You can actually extend the [Tab component](https://github.com/artf/grapesjs-tabs/blob/master/src/components/Tab.js) and add the `isComponent` method to allow the parser to identify the component.

**Comment by Rilvatore** [comment]
Would you have a working example of how it could look like, for example on another plugin? or maybe a tabs plugin update to handle this?
Thank you in advance

**Comment by Rilvatore** [comment]
Did you have any chance to take a look? Thanks a lot

**Comment by artf** [comment]
Here you can find how to update components: https://grapesjs.com/docs/modules/Components.html#update-component-type
