### ISSUE TITLE
BUG: resetId types mismatch

### ISSUE THREAD

**Issue by vaneatka** [artf/grapesjs#4735]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

n/a

### Reproducible demo link

n/a

### Describe the bug

**How to reproduce the bug?**
1. . Go to https://github.com/artf/grapesjs/blob/dev/src/dom_components/model/Component.js#L1839
2. .. Go to https://github.com/artf/grapesjs/blob/dev/index.d.ts#L1747

**What is the expected behavior?**
... resetId should be declared as a method

**What is the current behavior?**
...in the types the resetId is a bool nullable property

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
This first one is the component method, the second is the block property ([used here](https://github.com/artf/grapesjs/blob/81295f637aa2542db9ba2aefb3ce34f0d6489d71/src/block_manager/index.ts#L166-L168))

**Comment by vaneatka** [comment]
the reason I opened this issue is that the method is not visible.
maybe there is need to a new entry for the method declaration in the types? like for the setId
    /**
     * Set new id on the component
     */
    setId(id: string): this;
