### ISSUE TITLE
BUG: css class name with '/' converted to '-'

### ISSUE THREAD

**Issue by johnmay1** [artf/grapesjs#4739]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Edge Version 107.0.1418.52 (Official build) (64-bit)

### Reproducible demo link

https://codesandbox.io/s/peaceful-glade-rbfbwt?file=/src/app/app.component.ts

### Describe the bug

**How to reproduce the bug?**
1. Create new app with grapejs
2. call grapejs init with default config.
3. add new class named "test1/2"
4. Inpect the canvas html using developer toool.
5. It's renamed to "test1-2".

**What is the expected behavior?**
Class name should not be renamed. It should keep the name as is. e.g. test1/2
In previous version we were able to pass escapeNames within "selectorManagerConfig" which not available in current version 0.20.1

**What is the current behavior?**
Rename class name with '/' to '-'
e.g. "test1/2" to "test1-2"

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
You should still be able to use the `escapeName` option
```js
selectorManager: {
  escapeName: value => value
},
```
