### ISSUE TITLE
BUG: Transform scale and rotate don't work properly.

### ISSUE THREAD

**Issue by ronaldohoch** [artf/grapesjs#4744]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Brave last version

### Reproducible demo link

https://jsfiddle.net/ptzavm1b/

### Describe the bug

**How to reproduce the bug?**
1. Click on an element
2. Try to add this css style using the StyleManager Ui: `transform:scale(2);`
3. You can't.

**What is the expected behavior?**
1. The transform type stack should have or allow the `scale` and `rotate` from type stack

**What is the current behavior?**
1. The transform type stack don't have `scale` and `rotate` properties.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

This is what i want to achieve with styleManager Ui: https://jsfiddle.net/mr31jkhb/1/ (Hover the button)

**Comment by artf** [comment]
You should already be able to achieve the same effect with the default transform property, your custom one is not complete. 

Try to reference the complete configuration [here](https://github.com/artf/grapesjs/blob/483ab96eff13687c4794a8474c7e8cffd7405912/src/style_manager/model/PropertyFactory.js#L382). In case you want to update properties, you should be able to extend the default built-in one by using [getBuiltIn](https://grapesjs.com/docs/api/style_manager.html#getbuiltin) and [addBuiltIn](https://grapesjs.com/docs/api/style_manager.html#addbuiltin) APIs
