### ISSUE TITLE
open confirm dialog before removing assets

### ISSUE THREAD

**Issue by ateshuseyin** [artf/grapesjs#475]
I want to open a confirm dialog before removing image from assets manager. There is not any feature at the same time there is no appropriate api for it.

**Comment by artf** [comment]
You can use this code from Assets documentation
```js
// Extend the original `image`
editor.AssetManager.addType('image', {
  view: {
    onRemove(e) {
      e.stopPropagation();
      const model = this.model;
      confirm('Are you sure?') && model.collection.remove(model);
    }
  },
})
```
Put it inside a plugin otherwise it won't take effect on already defined images

**Comment by ateshuseyin** [comment]
@artf Thanks
