### ISSUE TITLE
Spans are stripped - unwanted behavior

### ISSUE THREAD

**Issue by Geczy** [artf/grapesjs#476]
For example if I import `<p><span style="font-size:50px;">hi</span></p>` via grapesjs import command, the following is set as the component: `<p data-highlightable="1">hi</p>`. Losing my styles

**Comment by Geczy** [comment]
You can reproduce on http://grapesjs.com/demo-newsletter-editor.html

**Comment by Geczy** [comment]
In my case it is preferable to not strip the `<span>` and leave it in the HTML. Why was it removed?

**Comment by artf** [comment]
I agree with you Matt, indeed, as already mentioned, I'd like to remove it but need to find time to test it, to be sure it's not breaking other stuff.
I close this in favor of #341
