### ISSUE TITLE
BUG: _undoexc status open

### ISSUE THREAD

**Issue by quentin-bettoum** [artf/grapesjs#4763]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Firefox 106

### Reproducible demo link

https://grapesjs.com/demo.html

### Describe the bug

Hello,

When I upgraded from 0.19.5 to 0.20.1, I noticed that the page's JSON that I get using `editor.getProjectData()` is significantly heavier than before.
The difference is that in 0.20.1, every component in the JSON contains this piece of code:
```json
"_undoexc": [
   "status",
   "open"
 ]
```

My guess is that the issue probably started when the [Component got converted into class](https://github.com/artf/grapesjs/blame/143414408e0b6f37645fc07714f142280d88961d/src/dom_components/model/Component.js#L138) but I may be wrong.

**How to reproduce the bug?**
1. Create any page with GrapesJS 0.20.1, then use `JSON.stringify(editor.getProjectData())`

I have the same result on the demo hosted at https://grapesjs.com/demo.html

Here is the `frames` part of the project data of the same page in 0.19.5 and 0.20.1:

**0.19.5**
```JSON
"frames": [
  {
    "component": {
      "type": "wrapper",
      "stylable": [],
      "components": [
        {
          "tagName": "h1",
          "type": "text",
          "components": [
            {
              "type": "textnode",
              "content": "Hello World Component!"
            }
          ]
        }
      ]
    }
  }
]
```

**0.20.1**
```json
"frames": [
  {
    "component": {
      "type": "wrapper",
      "stylable": [],
      "_undoexc": [
        "status",
        "open"
      ],
      "components": [
        {
          "tagName": "h1",
          "type": "text",
          "_undoexc": [
            "status",
            "open"
          ],
          "components": [
            {
              "type": "textnode",
              "content": "Hello World Component!",
              "_undoexc": [
                "status",
                "open"
              ]
            }
          ]
        }
      ]
    }
  }
]
```

Thanks in advance.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
Oh yeah, that should be removed, thanks.
