### ISSUE TITLE
By default disable Traits, On previous change in traits Enable next traits.

### ISSUE THREAD

**Issue by HarshOB** [artf/grapesjs#477]
Hello, 

So, I want to define Two traits in the component settings. First one is CheckBox and another one is TextBox(There can be multiple). I will define First CheckBox the multiple Input fields. When a CheckBox is clicked/checked on the base Next TextBoxes/input fields (That will be disabled by default) will be Enable. How can I achieve something like this? 

Thank You.

**Comment by artf** [comment]
@HarshOB Did you check already the wiki about [Traits](https://github.com/artf/grapesjs/wiki/Traits)? I explain there how to add checkbox inputs and how to react to their changes. If it's not clear can you point me out what should I add?

**Comment by HarshOB** [comment]
Here I explain again with a screenshot. You can see that there are two text fields under one checkbox. So, when I clicked on checkbox/ check that checkbox then that two input fields will be enabled(I want it to disable when it loads for the first time).

![screenshot from 2017-11-09 17-13-33](https://user-images.githubusercontent.com/28950214/32605877-2f792bfe-c579-11e7-8db9-1efec4a6eee5.png)

**Comment by artf** [comment]
No, it's not something you can do with a built-in trait, but you can define your own type (which can even include all your inputs) by extending the [default one](https://github.com/artf/grapesjs/blob/dev/src/trait_manager/view/TraitView.js)
