### ISSUE TITLE
BUG: GrapesJS doesn't understand '@-webkit-keyframe' CSS rules. 

### ISSUE THREAD

**Issue by henry-mmw** [artf/grapesjs#4771]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Chrome v108

### Reproducible demo link

no link

### Describe the bug

Add any '@-webkit-keyframe' CSS rules into the editor. Appears as '@media' instead.

I've added a fair few tools to the builder now and it seems whenever I add any webkit-keyframe css rules. They do not get understood by the editor and appear as '@media'. Just wondering if it supports this and I'm just being silly or if not is there a way i could implement this for you  ?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ronaldohoch** [comment]
I just came here to open the same issue! :(

@artf, you can add this code to check it.

```js
editor.CssComposer.addRules(`
    .animate__animated {
      -webkit-animation-duration: 300ms;
      animation-duration: 300ms;
      -webkit-animation-fill-mode: both;
      animation-fill-mode: both;
    }
    @keyframes fadeIn {
      0% {
        opacity: 0
      }

      to {
        opacity: 1
      }
    }
    .animate__fadeIn {
      -webkit-animation-name: fadeIn;
      animation-name: fadeIn
    }
`);
```

![image](https://user-images.githubusercontent.com/2287371/207124934-3d9bd01a-3cc9-4f00-aa8c-5b7a1759d30f.png)

**Comment by artf** [comment]
Reported and fixed [here](https://github.com/artf/grapesjs/issues/4727)
