### ISSUE TITLE
BUG: Can't set traits in attributes

### ISSUE THREAD

**Issue by edenizk** [artf/grapesjs#4774]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Firefox

### Reproducible demo link

https://jsfiddle.net/9aj630x7/

### Describe the bug

**How to reproduce the bug?**
1. Create a element
2. set data-gjs-traits attribute to any default trait name like `id` or `title`, it will crush the whole thing

**What is the expected behavior?**
I expect the same result as the `data-gjs-traits=''` which is setting traits empty

**What is the current behavior?**
If I will place there something else than empty string it will crush the grapes

If is necessary to execute some code in order to reproduce the bug, paste it here below:
```js
// your code here
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
You should use properly parsable JSON strings eg, `data-gjs-traits='["id"]'`, `data-gjs-traits="[]"`
