### ISSUE TITLE
BUG: Bug resize image

### ISSUE THREAD

**Issue by phamthanhbinh4796** [artf/grapesjs#4784]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

108.0.5359.73

### Reproducible demo link

https://user-images.githubusercontent.com/44830209/56891735-89203380-6a8e-11e9-8d42-c530d5aa0ae2.gif

### Describe the bug

bug resize image
Hi !
I have some issues when i want resize an image.
When i put an image and when i click one resizer handler, the image don't keep his height but expand it to 100% of parent container...
resizable : 1

For context, the image has a absolute position.
Thanks for help !

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MrRainDrop9x** [comment]
I have the same issue, can someone help us?

**Comment by artf** [comment]
I'd say to refer to [this issue](https://github.com/artf/grapesjs/issues/3770) for all bugs related to absolute mode.
