### ISSUE TITLE
BUG: block:drag event not working in touch devices even after including touch plugin

### ISSUE THREAD

**Issue by joukhar** [artf/grapesjs#4791]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

chrome desktop Version 108.0.5359.125 latest

### Reproducible demo link

N/A

### Describe the bug

**How to reproduce the bug?**
when dragging component from block manager, the event is not fired.

If is necessary to execute some code in order to reproduce the bug, paste it here below:
```js
        editor.on('block:drag', function (e, a) {
            editor.Commands.run('hide-panels')
        })
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
Thanks @joukhar there is actually some inconsistency with the `block:drag` event and I'll try to fix it in the next release.
