### ISSUE TITLE
BUG: Issues on setDragMode in version 0.20.2

### ISSUE THREAD

**Issue by AgnRakul** [artf/grapesjs#4799]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Chrome

### Reproducible demo link

https://jsfiddle.net/6c7xw3Lu/2/

### Describe the bug

[Screencast from 23-12-22 12:24:15 PM IST.webm](https://user-images.githubusercontent.com/70213104/209287702-270827d7-57f3-4501-a89b-8b3d51cba2b2.webm)

DragMode Issues on Version 0.20.2 The Dragging visually is not viewed on video kindly check once 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
This is related to [this issue](https://github.com/artf/grapesjs/issues/4792) and it's ready for the next release.
