### ISSUE TITLE
overide upload image event and store to local

### ISSUE THREAD

**Issue by eckyerdhyka** [artf/grapesjs#48]
@artf hi sir,thank for nice builder.but i have litle problem,how overide event upload image or show modal for asset manager in edit image.me use gh-pages branch

**Comment by artf** [comment]
Not sure about what you're asking but you can listen when the Asset Manager is shown

```js
editor.on('run:open-assets', function() {
 console.log('Asset Manager is opened');
})
```

**Comment by eckyerdhyka** [comment]
thanks @artf , how open modal asset manager without drag and drop block manager ?

**Comment by artf** [comment]
@eckyerdhyka 
```js
editor.runCommand('open-assets');
```

**Comment by eckyerdhyka** [comment]
@artf thanks a lot
