### ISSUE TITLE
BUG: Removing or adding component changes other components locations with dragMode translate, any solution please?

### ISSUE THREAD

**Issue by usmanqamar-int** [artf/grapesjs#4800]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Chrome

### Reproducible demo link

https://zmzr3n.csb.app/

### Describe the bug

**How to reproduce the bug?**
 While deleting or adding more than one component, other components have changed their position. 

**What is the expected behavior?**
It should not change their position
 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
This is how translate works, the alternative is to use absolute mode
