### ISSUE TITLE
BUG: Layerable property not working as expected in parent-child scenario.

### ISSUE THREAD

**Issue by FaisalShaikhHA** [artf/grapesjs#4812]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

107.0.5304.110 (Official Build) (arm64)

### Reproducible demo link

https://codepen.io/faisal-praella/pen/rNvOwgR

### Describe the bug

When the parent component is set to `layerable: false` it is not visible & all its child not visible in the layer manager. 
When one of its child components is set to `layerable: true` it should be visible in the layer manager.

**What is the expected behavior?**
The parent component should be hidden along with its children but the child with `layerable: true` should be visible in the layer manager.

**What is the current behavior?**
The child with `layerable: true` is not visible in the layer manager.

```
<section data-gjs-layerable='false'>
    <div>Bar Foo</div>
    <h2 data-gjs-layerable='true'>Lorem ipsum</h2> // not visible in layer manager
    <p>Foo bar</p>
<section>
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
Unfortunately this is how `layerable` currently works so it's not a bug, but I'd be glad to accept a PR to improve this behaviour.
