### ISSUE TITLE
BUG:  Can't edit text node inside div, if div has inside tag p > span. 

### ISSUE THREAD

**Issue by sdimitrenco** [artf/grapesjs#4817]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Chrome Version 108.0.5359.125, Mozilla 107.0

### Reproducible demo link

https://jsfiddle.net/stanislavdimitrenko/d61cm4yg/14/

### Describe the bug

So, that strange behavior of grapes js.   

If you have that struct

```
<div> 
Some text without the wrapper
<p><span>Text</span></p>
</div>
```

"Some text without the wrapper" - you can't edit that text. Grapes don't do it editable... 

If change that, then you can. 
```
<div> 
Some text without the wrapper
<p>Text</p>
</div>
```

Or, if you add a wrapper to the text, the same makes it editable. 

```
<div> 
<span>Some text with wraper</span>
<p><span>Text</span></p>
</div>
```

Maybe need somehow set up grapesjs or that limit of script work? 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
Yeah right now this is an expected behaviour for parsed text nodes without proper wrappers and not textable components as siblings. So in order to make those nodes editable you have to properly wrap them in a tag like span.
