### ISSUE TITLE
Default asset manager in custom component

### ISSUE THREAD

**Issue by krunal039** [artf/grapesjs#482]
I am in process to create custom component for below template and we want to have user enter text,link,hover text and select image and want to use default asset manager to select image but not sure how to get selected image in custom component? below is code I have used
`
view: defaultType.view.extend({
       init() {
          this.listenTo(this.model, 'active', this.doStuff); // listen for active event
        },
        doStuff() {
          editor.runCommand('open-assets', {
            target: editor.getSelected()
          });
        }
});`

![sample](https://user-images.githubusercontent.com/11716808/32366985-61acb146-c078-11e7-86b0-c8f7fd4c5368.png)

**Comment by artf** [comment]
@krunal039 Why do you need a custom component? Your template seems to be pretty simple, what about just a simple block?
```js
editor.BlockManager.add('your-block', {
     label: 'Custom Block',
     content: `<div class="row-class">
          <div class="column-class">
               <img src="..." />
          </div>
           ...
     </div>`
})
```

**Comment by krunal039** [comment]
@artf thanks for reply, we need user input for hover text, background image and text and hyperlink at bottom and thought to use custom component, but if we can prompt user to enter above then happy to create just block, can you pease guide me in correct direction, I am struggling since 4-5 days?

**Comment by artf** [comment]
Try to create a block with your template, drag it inside the canvas and you will be able to change all that stuff

**Comment by krunal039** [comment]
@artf I tried it but way we have template it does not allow, 

We have image and with mouse hover text with absolute div on top of image. when user tried want to change image they cannot unless they remove mouse hover div and then can double click on image to remove it but then they cannot add back hover div for text, if you want I can create jsfiddle

**Comment by artf** [comment]
yes please, create a jsfiddle because I'm not getting your case

**Comment by krunal039** [comment]
@artf  below is codepen for same

[https://codepen.io/kmpdev/full/LORdOM/](url)

**Comment by krunal039** [comment]
@artf  any luck to look at codepen?

**Comment by krunal039** [comment]
@artf any luck?

**Comment by artf** [comment]
Sorry, I was busy with other stuff. Anyway I got your problem and actually, you have to build a custom component (probably playing with traits) or find another way which allows users to select images, can't help you more
