### ISSUE TITLE
BUG: Component content is set to empty string after inline editing

### ISSUE THREAD

**Issue by NicoGGG** [artf/grapesjs#4848]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Firefox v91.4.1

### Reproducible demo link

https://grapesjs.com/demo.html

### Describe the bug

**How to reproduce the bug?**
1. Go to the grapesjs basic demo: https://grapesjs.com/demo.html
2. Clear the canvas
3. Add a component Link
4. Execute `editor.getComponents().models[0].attributes.content` in the browser console. The output is "Link", which is the content of the link component
5. Change the link text by editing it inline
6. Execute `editor.getComponents().models[0].attributes.content` again in the browser console. The output is now "".

**What is the expected behavior?**
When a component is edited inline, the content attribute of the component should be updated accordingly.

**What is the current behavior?**
When a component is edited inline, content is always set to _empty string_

If is necessary to execute some code in order to reproduce the bug, paste it here below:
```js
editor.getComponents().models[0].attributes.content
```
Do this after editing the component inline.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
This is expected due to some logic related to the rich text editor. 
You can use `component.getInnerHTML()` to get the inner HTML or `component.components()` to get inner components.
