### ISSUE TITLE
BUG: Outline disappears after applying loadProjectData

### ISSUE THREAD

**Issue by ronaldohoch** [artf/grapesjs#4855]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Brave last version

### Reproducible demo link

https://grapesjs.com/demo

### Describe the bug

**How to reproduce the bug?**
1. Open the demo page
2. Open the developer tools
3. Run: `let projectData = editor.getProjectData()`
4. Run: `editor.DomComponents.clear()`
5. Run: editor.loadProjectData(projectData);

**What is the expected behavior?**
The outline of component should be shown.

**What is the current behavior?**
The outline of component is not showing after apply the project.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ronaldohoch** [comment]
I also run the command `editor.runCommand("core:component-outline")` and it didn't shows again, i needed to click on the button twice to make it appear

**Comment by allenhwkim** [comment]
@ronaldohoch with Edge browser, it works with the command you provided.

`let projectData = editor.getProjectData();`
`editor.DomComponents.clear();`
`editor.loadProjectData(projectData);`

I don't think GrapesJS support Brave browser, which is not listed in https://github.com/browserslist/caniuse-lite.

<img width="1435" alt="image" src="https://user-images.githubusercontent.com/1437734/213596488-ff30bf4c-128a-4ca7-a0ef-f4fa15e9d19b.png">

**Comment by ronaldohoch** [comment]
Hi @allenhwkim, thanks for the comment. But embarrassing I didn't test it in other browsers.
I believe my customers don't use Brave, so I'm going to drop that part.

However, doing all these tests, I managed to make it work the way I want, applying this code:

```js
            editor.loadProjectData(JSON.parse(sessionStorage.getItem(commandOpts.value)));
            if(editor.Commands.isActive("sw-visibility")){
                editor.Commands.stop("sw-visibility");
            }
            editor.runCommand("sw-visibility");
```

Maybe i was looking the wrong command to run. Worked in all my tests (Chrome, Edge, Firefox and Brave)
