### ISSUE TITLE
BUG: Editing CSS property sets a style to a common class instead of element

### ISSUE THREAD

**Issue by zoilorys** [artf/grapesjs#4859]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Chrome v108

### Reproducible demo link

https://grapesjs.com/demo.html

### Describe the bug

**How to reproduce the bug?**
1. Setup grapesjs editor
2. Import following template  https://pastebin.com/d9S2M0iS
3. At the very bottom of the template you will see wrapped facebook button
4. Select table cell it is in, and try t change its width

**What is the expected behavior?**
When style property of the element is edited - styles should be updated only on selected element.

**What is the current behavior?**
Changing width of the cell for some reason edits common class in this template, which is applied to other elements as well, causing unexpected behavior (see video) . This I couldn't reproduce on the demo setup, and cant provide our exact setup to the public, but maybe you have ideas why this might be happening.

https://user-images.githubusercontent.com/12827614/213744169-cdf4c9cb-0ad0-4d2c-8e19-ef1e6ff1937e.mp4

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
You just need to enable this option:
https://grapesjs.com/docs/modules/Selectors.html#component-first-selectors
