### ISSUE TITLE
BUG: <br/> is adding to single line text, after entering space for the first time in firefox

### ISSUE THREAD

**Issue by edenizk** [artf/grapesjs#4861]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Firefox

### Reproducible demo link

https://jsfiddle.net/8rm5wv2y/1/

### Describe the bug

**How to reproduce the bug?**
1. open example page in firefox (it has no modification)
2. click show code, you will see that there is no `<br/>` element inserted
3. press space after "Hello World!!!" if you want you can add any text
4. click show code again, you will see that after your new added text you will have `<br/>` element added

**What is the expected behavior?**
If the user is not pressing enter or shift+enter, but writing on single line I would like to not to get `<br/>` element. Like in the chrome.

**What is the current behavior?**
when ever user is adding text to existing text, grapes is adding `<br/>` element in firefox.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
Unfortunately this is not related to grapesjs itself but how Firefox handles editable text. I guess one option would be to switch to some custom rich text editor which doesn't rely on the native behaviour.

**Comment by edenizk** [comment]
Thank you for your answer 🙂
