### ISSUE TITLE
BUG: '@' sign in class-attribute value of block content changes to '-' sign when using template literals

### ISSUE THREAD

**Issue by agreif** [artf/grapesjs#4865]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Firefox 108.0.2

### Reproducible demo link

not possible in jsfiddle

### Describe the bug

grapesjs-cli - 3.0.1
grapesjs - 0.20.3

**How to reproduce the bug?**
1. add a newblock with this template literal with a class attribute containing an `@` sign
```js
    bm.add('foo', {
        label: 'Foo',
        content: `                                                                                                                                 
        <div class="uk-width-1-2@m">                                                                                                               
          <div>some text</div>                                                                                                                    
        </div>                                                                                                                                     
    `,
    });
```

2. drag the block into the work area

3. the following `div` element will be created:
```js
<div data-gjs-highlightable="true" id="igof" data-gjs-type="default" draggable="true" class="uk-width-1-2-m">
    <div data-gjs-highlightable="true" id="is7o" data-gjs-type="text" draggable="true" class="">
        some text
    </div>
</div>
``` 

4. other possibility to reproduce:
open the code with `Import` tool and change a `class` attribute to contain an `@` sign.
save it. And then when you repoen the `Import Template` dialog the `@` sign is replaced by a `-` sign

6. PROBLEM: see the `class` in the first `div`...

**What is the expected behavior?**
the attribute value should not change, so it should stay with the `@` sign:
`<div ... class="uk-width-1-2@m">`

**What is the current behavior?**
it changes the `@` sihn to a `-`:
`<div ... class="uk-width-1-2-m">`

If is necessary to execute some code in order to reproduce the bug, paste it here below:
```js
    bm.add('foo', {
        label: 'Foo',
        content: `                                                                                                                                 
        <div class="uk-width-1-2@m">                                                                                                               
          <div>some text@</div>                                                                                                                    
        </div>                                                                                                                                     
    `,
    });
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
I'll update the escape function, for now you can provide your own via [this option](https://github.com/artf/grapesjs/blob/f08b5afe6f79626e734de330fbff3c30824c04a9/src/selector_manager/config/config.ts#L27-L32)
