### ISSUE TITLE
How do you load in templates and change html associated with drag and drop buttons

### ISSUE THREAD

**Issue by NJseo** [artf/grapesjs#49]
I am trying to preload templates and change the drag and drop button html

**Comment by artf** [comment]
What do you mean with **preload templates**?
You can load templates in this way
```html
<div id="gjs">
  <div class="txt-red">Hello world!</div>
  <style>.txt-red{color: red}</style>
</div>

<script type="text/javascript">
  var editor = grapesjs.init({
      container : '#gjs',
      fromElement: true,
  });
</script>
```
About *drag and drop buttons*, have you checked docs about [Blocks](https://github.com/artf/grapesjs/wiki/Blocks)? Seems like exactly what you're asking
