### ISSUE TITLE
Asset Manager replacement

### ISSUE THREAD

**Issue by ryandeba** [artf/grapesjs#491]
Is it possible to replace the asset manager with something completely different (such as CKFinder - https://ckeditor.com/ckeditor-4/ckfinder/)? Alternatively, would it be possible to launch the included asset manager outside the context of grapesjs?

**Comment by artf** [comment]
Well, never tried it before but I think you can achieve it just by replacing the [current command](https://github.com/artf/grapesjs/blob/dev/src/commands/view/OpenAssets.js)
```js
editor.Commands.add('open-assets', {
     run(editor) {
          ...
    }
})
```
This is how the command is called https://github.com/artf/grapesjs/blob/dev/src/dom_components/view/ComponentImageView.js#L49

**Comment by ryandeba** [comment]
Thanks @artf! I was able to get this working very quickly with your suggestion.
