### ISSUE TITLE
[QUESTION] Can i set content dynamically from block API ?

### ISSUE THREAD

**Issue by bungambohlah** [artf/grapesjs#493]
Hi @artf , very great web builder framework and keep it up :+1: 

code :
```javascript
...
blockManager.add('dynamic-nav', {
  label: 'Dynamic Navigation',
  attributes: {
    class: 'fa fa-ellipsis-h',
    title: 'Insert Dynamic Menu of Navigation'
  },
  category: 'Section',
  content: `<ul class="hide-on-med-and-down" data-gjs-type="navigation" data-section-type="navigation">
              <li>
                <a href="page1.html">Page 1</a>
              </li>
              <li>
                <a href="page2.html">Page 2</a>
              </li>
              <li>
                <a href="page3.html">Page 3</a>
              </li>
                ...
            </ul>`,
});
...
```

As you can see, can i make ```<li>``` tag dynamically from my backend?
i use EJS template for my view render engine and can passing data to ejs.

Thank you very much and have a nice day

**Comment by artf** [comment]
You can update the block's content in this way
```js
const dblock = blockManager.get('dynamic-nav');
dblock.set('content', `<ul>...`);
```

**Comment by bungambohlah** [comment]
Oh i see , thank a lot @artf

**Comment by bungambohlah** [comment]
Hi @artf i have a problem, my dynamic-nav's block is works now, but why the content is not editable or selectable?

**Comment by artf** [comment]
@bungambohlah first of all, provide a complete error stack, probably you have some syntax error in your code (and `innerHTML` is not a function).
Anyway, this is not related to your original problem so next time open a new issue, please
