### ISSUE TITLE
Place block as component programmatically

### ISSUE THREAD

**Issue by z-vr** [artf/grapesjs#494]
I've created a custom type, and a block

```js
DomComponents.addType('MyComponent', { ... });
BlockManager.add('Component', { content: { type: 'MyComponent' } });
```
is it possible to insert it into `DomComponents` by name or any other means? I don't want to be drag'n'dropping the block manually each time. Thanks.

**Comment by z-vr** [comment]
Oh I found out how to do it -- via `editor.addComponents({ type: 'MyComponent' })`. Is there a way to insert it into a specific element by a CSS selector?

**Comment by z-vr** [comment]
ok so what i've done is 
```js
export default function iterateChildren(components, fn) {
  components.each((model) => {
    fn(model);
    const childComps = model.get('components');
    iterateChildren(childComps, fn);
  });
}

export function findModels(components, selector) {
  const found = [];
  iterateChildren(components, (model) => {
    const { view } = model;
    if (!view) {
      return;
    }
    const { el } = view;
    const matches = el.matches(selector);
    if (matches) {
      found.push(model);
    }
  });
  return found;
}
```
and then 
```js
const wrapper = DomComponents.getWrapper();
  const models = findModels(wrapper.get('components'), '#hero .text');
  models.forEach((model) => {
    const components = model.get('components');
    components.add({ type: 'ContainerPlugin' }, { at: 0 });
  });
```
I think traversing the model tree would be a very good feature -- I'll work on the PR at some point. Cheers!

**Comment by artf** [comment]
You can actually get the model from the cash element instance with `view.$el.data('model')`, so you might make it work with less code
```js
wrapper.view.$el.find('#hero .text').each((el, i, $el) => 
    console.log($el.data('model'))
)
```

**Comment by z-vr** [comment]
@artf thanks for the snippet, it's good to know about `$el`, do you know how to extend this function to return a Backbone collection of models without importing `Backbone` in the project?

**Comment by artf** [comment]
@z-vr currently you can't but honestly, I don't even see why do you need it here?
