### ISSUE TITLE
Highlighter and toolbar in the wrong place

### ISSUE THREAD

**Issue by telliott22** [artf/grapesjs#495]
Hi,

From time to time, on my canvas the highlighter and toolbar appear in the wrong place. Is this a known bug? Do I have to manually refresh the canvas?

It seems that the `top` css property on `gjs-highlighter` and `gjs-badge` aren't being calculated properly, they still line up horizontally just not vertically. Any ideas?

I've attached screenshots below. 

Thanks,
T

![screen shot 2017-11-08 at 16 44 30](https://user-images.githubusercontent.com/7810707/32561567-7434d44e-c4a4-11e7-972e-431095beb8d2.png)
![screen shot 2017-11-08 at 16 44 51](https://user-images.githubusercontent.com/7810707/32561568-746a09de-c4a4-11e7-9e89-bf83a8f66bf8.png)
![screen shot 2017-11-08 at 16 45 05](https://user-images.githubusercontent.com/7810707/32561569-748ddf6c-c4a4-11e7-83d6-32fd44cb8482.png)

**Comment by artf** [comment]
I'm aware of the toolbar "jump" when the content inside it changes (by adding or removing buttons) but not with the highlighter. Do you use the editor inside a scrolled page?

**Comment by telliott22** [comment]
Any way to stop the jumping when the content changes?

Yes, the page is scrolled. Should I limit the height of the editor to the browsers height?

**Comment by artf** [comment]
Yeah, unfortunately, there is a bug which doesn't get a correct dimension of the scrolled page

**Comment by tomichal** [comment]
Hey @artf, do you have any info on this bug? I would like to help, and just wondering if I need to start from scratch or if you have a good idea what/where the issue is?
