### ISSUE TITLE
Tabs inside Panel

### ISSUE THREAD

**Issue by arthuralmeidap** [artf/grapesjs#499]
Hi @artf,

  As you must know, at my company we are creating a product based on GrapesJS.
  We are trying to keep as close as possible from GrapesJS core. As developers we are trying our best to not create a fork from GrapesJS and keep contributing back to the repo.
  Now, we have a new feature to create and we would like to know if it's interesting for GrapesJS.
  We want to add tabs inside the blocks panel. It's works like the categories, they serve to group a specific set of blocks.
  Something like that 
<img width="253" alt="captura de tela 2017-11-09 as 15 55 03" src="https://user-images.githubusercontent.com/218371/32621280-6efd381e-c566-11e7-9d48-d029bc2c27cb.png">

  Do you think is it good for Grapes? I mean, is there any chance that could be merged back to the grapes core?

  We started to code something like that: (this is the grapesjs.init options)
```
tabManager: {
                defaultTab: 'content',
                tabs: [{
                    id: 'content',
                    label: 'Content',
                    attributes: {class:'gjs-fonts gjs-f-b1'},
                },{
                    id: 'layout',
                    label: 'Layout',
                    attributes: {class:'gjs-fonts gjs-f-b2'},
                }]
            },

            blockManager: {
                blocks: [{
                    id: 'b1',
                    label: '1 Block',
                    category: 'Basic',
                    tab: 'content',
                    attributes: {class:'gjs-fonts gjs-f-b1'},
                    content: `<div>text</div>`
                }
  ```

  Let me know what you think about the idea. We love GrapesJS and we want to keep giving back to the project as possible as we can.

**Comment by arthuralmeidap** [comment]
I need to make some changes into some Models/Views inside GrapesJS.

How can I achieve with plugins? Any ideas?

**Comment by artf** [comment]
Well, besides the UI (which can be a simple `<select>` or even your tabs), all you have to do is to use `render` method
```js
const bm = editor.BlockManager;
const blocks = bm.getAll();

// Show me just column1 and column2 blocks
bm.render(blocks.filter(
  block => ['column1', 'column2'].indexOf(block.get('id')) >= 0
));

// Render all blocks again
bm.render();
```

**Comment by arthuralmeidap** [comment]
owww.. Mind blowing... So simple but never thought about it... Thanks a lot!!!

And about the UI? Any tips how to change it without change grapes itself?

**Comment by artf** [comment]
Once the block manager is rendered you can make use of the container
```js
const blocksEl = bm.getContainer(); 
// The content of the container will change on render, so..
blocksEl.parentNode ... // append/prepand stuff on the parent element
```

**Comment by arthuralmeidap** [comment]
You are the man!!! Thanks a lot!! I will try it !!!!

**Comment by arthuralmeidap** [comment]
@art, I can't found a moment to execute the code.

The BlockManager.onLoad is called after the plugin is executed and then all the blocks are reset.
 
 I tried to use the `editor.on('load')`  and tried to call the code just after the `grapesjs.init` and didn't work any of them.

 I know that my code is working because I was trying first on Chrome DevTools and everything was fine.

**Comment by artf** [comment]
> The BlockManager.onLoad is called after the plugin is executed and then all the blocks are reset

Why do you care about blocks inside your plugin? I mean, I'd define the logic inside your tabs
```js
tabs: [{
                    id: 'content',
                    label: 'Content',
                    attributes: {class:'gjs-fonts gjs-f-b1'},
                    blocks: ['block-id1', 'block-id2', ...],
                },{
                    ...
                }]
            },
```
What exactly do you call inside `editor.on('load')`?

**Comment by matiponce91** [comment]
But even if we put the associate blocks inside the tab definition how can I hide or show them depending on the selected tab? and also how can I hide or show the categories depending of that same factor?

**Comment by arthuralmeidap** [comment]
@artf ,
let me show you what I'm trying:
 I create the blocks like this:
```
blocks: [
                    {
                        id: 'b1',
                        label: '1 Block',
                        category: 'Basic',
                        tab: 'content',
                        attributes: { class: 'gjs-fonts gjs-f-b1' },
                        content: `<div class="row" data-gjs-droppable=".cell" data-gjs-custom-name="Row">
                <div class="cell" data-gjs-draggable=".row" data-gjs-custom-name="Cell"></div>
              </div>`,
                    },
                    {
                        id: 'b2',
                        label: '2 Blocks',
                        category: 'Basic',
                        tab: 'layout',
                        attributes: { class: 'gjs-fonts gjs-f-b2' },
                        content: `<div class="row" data-gjs-droppable=".cell" data-gjs-custom-name="Row">
                    <div class="cell" data-gjs-draggable=".row" data-gjs-custom-name="Cell"></div>
                    <div class="cell" data-gjs-draggable=".row" data-gjs-custom-name="Cell"></div>
                </div>`,
                    },
                ]
```

and inside my plugin I'm using something like 

```
export default grapesjs.plugins.add('navis-block-tabs-handler', (editor) => {
    const blockManager = editor.BlockManager;
    const blocks = blockManager.getAll();
    blockManager.render( blocks.filter((block) => { 
        if (block.get('tab') === 'layout') { 
            return true; 
        } 
     }));
});

```

**Comment by arthuralmeidap** [comment]
Hi @artf ,
  Just leaving some feedback. After reading carefully your comments and take a deeper look at GrapesJS code I've figure ou how to implement those Tabs inside the plugin.

  Basically what I did was override the `OpenBlocks.js` command to work as I expected.

  What you think about this idea? Can you see any drawbacks about this implementation?

  Thanks for all your help. Feel free to close the issue if you want

**Comment by artf** [comment]
I don't see any problem with overriding the command so go ahead with it 👍
