### ISSUE TITLE
PhantomJS warnings when running tests

### ISSUE THREAD

**Issue by timotius02** [artf/grapesjs#5]
This warning was thrown when running tests and caused the test to be aborted. I tried resolving the issue myself by looking over the tests but I'm very inexperienced with them.

![screen shot 2016-02-09 at 3 22 58 pm](https://cloud.githubusercontent.com/assets/5110237/12929510/0e10f864-cf41-11e5-80cd-4270e835b769.png)

**Comment by brandonshowers** [comment]
@timotius02 with this current configuration, you'll want to make sure you're connected to a development server before running the test command. Try running `npm run dev` and then in another tab run `npm run test`. You should be good to go now.

**Comment by artf** [comment]
Thanks @timotius02 for the help, but anyway I'm not totaly sure if it will help 'cause I'm able to run `npm run test` even without `run dev` command :/
Maybe there is some conflict with some dependency. I have updated my node, npm and all dependencies and still can't reproduce it. 
Try, at first, to check if after `npm run dev` you're able to see `localhost:8000/test` without errors. Then, can you show me the output with `npm ls phantomjs`?

**Comment by brandonshowers** [comment]
@artf it looks like this is happening after a fresh clone. After running `npm run build` I was able to run `npm run test` with no issues.

**Comment by artf** [comment]
@brandonshowers oh well sure, without `npm run build` you can't even run the application.
@timotius02 let me know if you've solved

**Comment by timotius02** [comment]
Yep, I had just forgotten to build as well as install sass in my environment. Now I'm able to run the tests without `npm run dev`. 

Also I think mentioning somewhere in the installation that Ruby Sass is a prior dependency might be beneficial.

**Comment by artf** [comment]
@timotius02 great, glad you've solved. Anyway I think it would be better integrate node-sass, in this way to avoid Ruby dependency
