### ISSUE TITLE
command event that is triggered when we click "Hide Preview"

### ISSUE THREAD

**Issue by sanjeevSavitr** [artf/grapesjs#503]
Hi,
editor.on('run:preview', () => { console.log('preview ON') })
This is working fine.

Now I need the command event that is triggered when we click "Hide Preview".

**Comment by artf** [comment]
`stop:preview`

**Comment by theanhmx** [comment]
`editor.on('run:preview', () => {
      console.log('preview ON')
    })

    editor.on('stop:preview', () => {
      console.log('preview OFF')
    })`
i tried this but the stop:preview event didn't fire

**Comment by artf** [comment]
Fixed by https://github.com/artf/grapesjs/pull/592
