### ISSUE TITLE
uploadFile being called twice on drop file?

### ISSUE THREAD

**Issue by roytang** [artf/grapesjs#507]
I have an editor initialized as so:
```
    var editor = grapesjs.init({
      height: '100%',
      container : '#gjs',
      components: '',
      fromElement: true,
      clearOnRender: true,
      style: '.txt-red{color: red}',
      noticeOnUnload: false,
      plugins: ['gjs-blocks-basic'],
      assetManager: {
        upload: "",
        uploadFile: function(e) { console.log("uploadFile"); },
        embedAsBase64: false,
        disableUpload: false
      }    
    });
```

If I add an image to the canvas and try to upload a new image by dragging it into the drop area in the modal, the uploadFile function is called twice. Uploading by clicking on the upload area and selecting a file from the windows dialog works fine, it only calls the function once.

**Comment by artf** [comment]
@roytang can't reproduce it with the current version https://codesandbox.io/s/p554z8yv7j

**Comment by duskhacker** [comment]
Explicitly disabling the full-width editor dropzone (`dropzone: 0`) fixed this for me.

**Comment by kickbk** [comment]
Got the same and @roytang's comment is true, disabling dropzone takes care of it. always using the latest version of course.

**Comment by artf** [comment]
Are you dropping files inside the AssetManager's dropzone or just on canvas?

**Comment by duskhacker** [comment]
@artf For me it was dropping on the dropzone in the assets manager.

**Comment by artf** [comment]
@duskhacker ok, in that case what happens is that `dropzone` is active by default and is showing when someone drags elements inside the editor, so when you drop an image in assets modal, you're also dropping it inside the `dropzone`
I will set it to false by default
