### ISSUE TITLE
If you add a checkbox trait, it does not render correctly in the settings panel unless there is also a text trait

### ISSUE THREAD

**Issue by roytang** [artf/grapesjs#508]
A text trait and a checkbox:

```
        traits: ['test',
          {
            type: 'checkbox',
            label: 'Check',
            name: 'check'
          }],

```

Results in:

![image](https://user-images.githubusercontent.com/4228/32700288-c2e2e976-c7fd-11e7-8b47-ae51a9f7651d.png)

If checkbox only:

```
        traits: [
          {
            type: 'checkbox',
            label: 'Check',
            name: 'check'
          }],
```

The checkbox overlaps the label:
![image](https://user-images.githubusercontent.com/4228/32700304-e6455f98-c7fd-11e7-8e8a-3e89b24cb5f4.png)

**Comment by artf** [comment]
Should be fixed
