### ISSUE TITLE
cat not use jQuary plugin to template 

### ISSUE THREAD

**Issue by piyalmaduranga** [artf/grapesjs#51]
I am using grapejs to load my html template and editing that template.In my template I use jQuery plugin.And also we use jQuery for building up editor using grapejs. In that case there is happen conflict 
between those jQuery loading on time.
 i had error like this
![screenshot from 2017-03-09 12 48 33](https://cloud.githubusercontent.com/assets/12907174/23739821/c3c422ce-04c6-11e7-97ec-d0b007717aee.png)
  
how to void that kind of issue, 
can we use jquary for template ?
if it is , how can i achieve ?

**Comment by artf** [comment]
I think this what happens
```html
<!-- Here you load all the stuff for GrapesJS -->
<script src="path/to/jquery.js"></script>
<script src="path/to/grapes.min.js"></script>

<div id="gjs">
  <div class="txt-red">Hello world!</div>
  <style>.txt-red{color: red}</style>
  <!--
  Before the editor's work this script will be loaded by the main document
  and will overwrite the one you've loaded before (so you'll break deps for GrapesJS)
  -->
  <script src="path/to/some-other-jquery.min.js"></script>
</div>

<script type="text/javascript">
  var editor = grapesjs.init({...});
</script>
```

Honestly I've not played too much with scripts inside templates but I'm working on it in this days.

For now I'd suggest to add scripts after 
```js
var editor = grapesjs.init({...});
var dc = editor.DomComponents.getComponents();
dc.add(`<script>
var execScripts = function(e){
 // ...
};
var script = document.createElement('script');
script.onload = execScripts;
script.src = 'https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js';
document.body.appendChild(script);
</script>`);
```
