### ISSUE TITLE
Add new class programatically

### ISSUE THREAD

**Issue by asvine-p** [artf/grapesjs#510]
Hello Artf,

I want to edit the styles of components (mostly imported html) without modifying all components with the  same class. I tried to add a random named class programmatically  like this:
`
      this.editor.on('component:selected', function(model) {
if (model && model.length > 2) {
                const uuid = this.s4(); // generate new random class name

                const selector =  {
                    name: uuid,
                    type: 'class',
                    label: uuid,
                };

                model[1].attributes.classes.push(selectorManager.get(uuid));
     let mClasees = model[1].attributes.classes;
             const uuid = this.s4();
             const selector =  {
                 name: uuid,
                 type: 'class',
                 label: uuid,
             };
          mClasees.push(selector);

      
}.bind(this));
`

This add a class programmatically to the component but it seem to no let me edit it's style. 

I just want be able to change the style of a single component without having to care which class it belongs to. Event if I copy past a component, I want be able to edit each components individually.
I hope that clear. If you need any further information, don't hesitate to ask me :) 
Thanks your help!

**Comment by artf** [comment]
You mean something like `model.set('style', {...})`? This adds an inline style on the component

**Comment by OverFlow636** [comment]
@asvine-p here i one way i am adding new classes to existing components
```javascript
var componentModel = editor.getComponents().models[0];
var selector = editor.SelectorManager.add('newclass');
var rule = editor.CssComposer.add(selector);
rule.set('style', {
  color: 'red'
})
componentModel .addClass('newclass')
```

**Comment by artf** [comment]
You can now make use of `setClassRule`/`getClassRule` from [CSS Composer API](https://github.com/artf/grapesjs/wiki/API-Css-Composer)

**Comment by asvine-p** [comment]
Cool! I will try this! Thanks :)

**Comment by michaellwatson** [comment]
So how can you remove classes in the same way?

**Comment by IrinaCodixis** [comment]
Hi @asvine-p .
I have the same issue like you did. What was your solution?

**Comment by artf** [comment]
@IrinaCodixis from the https://github.com/artf/grapesjs/releases/tag/v0.14.52 we've added [`setRule`](https://grapesjs.com/docs/api/css_composer.html#setrule)/[`getRule`](https://grapesjs.com/docs/api/css_composer.html#setrule) methods, so to add some CSS rule programatically you should do this:
```js
editor.CssComposer.setRule('.some-class', { color: 'red' })

// Remove
const rule = editor.CssComposer.getRule('.some-class');
editor.CssComposer.getAll().remove(rule);
```

**Comment by wemod123** [comment]
If I just simply want to add a `class-name` to a element, body for example. how to achieve that?

**Comment by artf** [comment]
@wemod123 `editor.getWrapper().addClass('my-class')`

**Comment by wemod123** [comment]
great!
