### ISSUE TITLE
template/ Blocks/ Components

### ISSUE THREAD

**Issue by krunal039** [artf/grapesjs#514]
We have requirement to create custom templates for different areas and all templates has below 4 variables 
anchor link, anchor target, image source, image hover text, title. We want to create one custom component and it will provide mechanism to select variables via traits. Is there way to provide template via block and use that under custom component rather than generation template in component?

We want to decouple component and block so block will provide template(i.e attached image) and component will replace placeholder with user selected values?

![capture](https://user-images.githubusercontent.com/11716808/32724852-cd10682a-c86a-11e7-8579-b9ede4e12a21.PNG)

**Comment by artf** [comment]
Well, with `data-gjs-*` attribute you can even use objects (JSONs)
```js
content: '<div class="cls" data-gjs-attrobj='{"valid":"json"}'></div>',
```
but, for bigger templates, I'd recommend block definition via an object instead
```js
    
    content: {
          // Just model's properties
          draggable: false,
          traits: ...
          ...
          // It's ok also using a string, components: `<div ...>...`
          components: [{
                type: 'text',
                content: 'Text here'
            }, ...
          ]
    },
```
