### ISSUE TITLE
How to embed setting panel into style manager panel.

### ISSUE THREAD

**Issue by ateshuseyin** [artf/grapesjs#516]
In grapesjs.com/demo.html settings panel is embedded into style manager panel. I want the same thing but I could not find how can it be.

**Comment by ateshuseyin** [comment]
I found it inside grapesjs-preset-webpage.js. I think this should be a feature. 
Issue can be closed for now.

**Comment by artf** [comment]
Sure @ateshuseyin The UI management with Panels API will be refactored soon and I'll add `appendTo` option on modules which should indicate where panels should be rendered
