### ISSUE TITLE
change only component body not whole page body.

### ISSUE THREAD

**Issue by HarshOB** [artf/grapesjs#518]
Hello @artf 

As we discussed in issue [#374](https://github.com/artf/grapesjs/issues/374).  **setComponents** will set the body and replace all the contents that are present on the page with a new select page from the list. What if I want to set the body to only that component without changing the whole content of the page?

**Comment by artf** [comment]
You can replace the content of the model
```js
// model could be editor.getSelected()
model.components('<div>Text 1</div><div>Text 2</div>')
```

**Comment by HarshOB** [comment]
How can I replace the content of a component with specific value like "<div>Text 1</div><div>Text 2</div>"?

**Comment by artf** [comment]
Tried with this `model.components('Hello')`?!?

**Comment by HarshOB** [comment]
Yes, But getting error `"model is not defined"`

**Comment by artf** [comment]
@HarshOB well, yeah Harsh... you have obviously to define your model... (eg. `var model = editor.getSelected()`)
