### ISSUE TITLE
No Blocks by default

### ISSUE THREAD

**Issue by enricribas** [artf/grapesjs#519]
Using this code
```
  var editor = grapesjs.init({
      container : '#gjs',
      components: '<div class="txt-red">Hello world!</div>',
      style: '.txt-red{color: red}',
  });
```

I get an editor but there are no blocks. I also do not get the icons for the screen size but other icons are there. As you can see the css is getting loaded as the general layout is correct.

![image](https://user-images.githubusercontent.com/438493/32779136-9e796aac-c90a-11e7-8ee5-59c5bca55f35.png)

What am I missing. I am using Vue but don't think it matters since I am simply running the code in the mounted callback.

**Comment by ryandeba** [comment]
@enricribas As far as I know, there are no default blocks built into the core of grapesjs, however there are plugins available that will add some blocks for you. Check out https://github.com/artf/grapesjs-blocks-basic.

I believe the "screen size" icons have been replaced with the "Device" select in the top-left corner. You might look into what the newsletter preset plugin does to convert those back into buttons - https://github.com/artf/grapesjs-preset-newsletter

**Comment by enricribas** [comment]
I see, thank you. The readme seems to imply that that out of the box, it's more set up but I guess things have been moved to a plugin system, which is nice.

Thanks.
