### ISSUE TITLE
Help in remote storage 

### ISSUE THREAD

**Issue by Eman-Shaaban** [artf/grapesjs#521]
The remote storage part isn't very clear in the wiki, I want to know If I can store templates by name as html files in some folder and retrieve them also by name.

**Comment by artf** [comment]
Hi @Eman-Shaaban, GrapesJS is just a client-side library and doesn't deal with back-end stuff. The remote storage just sends data to some server-side script, then it's up to handle it (you can store it inside a file or maybe in some DB table). This is all the code you need
```js
var editor = grapesjs.init({
    container : '#gjs',
    ...
    storageManager: {
      type: 'remote',
      urlStore: 'http://store/endpoint', // <-- here you have to set up your endpoint
      urlLoad: 'http://load/endpoint', // <-- here you have to set up your endpoint
    }
});
```
