### ISSUE TITLE
[Question/Enhancement] How to Export CSS linked in Canvas Styles properties

### ISSUE THREAD

**Issue by tldrjumps** [artf/grapesjs#523]
How to export the HTML/CSS in the code view / download as zip. With the stylesheets in styles.css referenced in the grapesjs canvas, but not the unused, actually i am fine with all the styles.css stylesheet, for simple API access for export.

If I add the stylesheet in init

```
      canvas: {
      styles: ['./styles.css'] 
      }
```

```
    bm.add('Table', {
      label: 'Table',
      category: 'Table',
      content: {
        type: 'table',
        classes: ['table-components'],
        columns: 2,
        rows: 1, 
        //style: {width: '100%', border: '1px solid black'}
      },
    });
```

Yea, Table 😋 
Thanks for the good work, let us worry about this easy issue and documenting or leave trace in issue list.
Artf should focus more on other amazing features.

**Comment by artf** [comment]
Hi @tldrjumps I'm not sure if I properly got your problem. You can simply get all the CSS with `editor.getCss()`, which also tries to optimize it by removing classes without components.
Styles inserted via `canvas.styles` option are just injected inside the canvas but actually, the editor doesn't see their rules

**Comment by tldrjumps** [comment]
Sorry for non properly explaining, The use case is to allow provide style from user to store the in or use with snippets block dropped.(Before the block drop) Then allow them to export the dropped block design with style.

Basic use case is use grapesjs to load articles then allows user to select particular css file([markdown article style](http://markedstyle.com/)) with markdown css styling, or other further use case that allow the user to defined style of blocks such as table, div.

**Comment by artf** [comment]
Well, if you want, for instance, to export the selected component HTML/CSS you can do this
```js
const model = editor.getSelected();
const html = model.toHTML();
const css = editor.CodeManager.getCode(model, 'css', {cssc: editor.CssComposer});
const final = `${html}<style>${css}</style>`;
```

**Comment by chiqui3d** [comment]
I think, that this should automatically inject the css that have been injected with the canvas option and this one doesn't, why?

**Comment by artf** [comment]
@chiqui3d definitely it shouldn't be added to what is used for storing otherwise you will add those styles twice.

**Comment by Yakito** [comment]
Hello @artf thanks a lot for your time!

I am not sure I follow your answer here:

> ```js
> const model = editor.getSelected();
> const html = model.toHTML();
> const css = editor.CodeManager.getCode(model, 'css', {cssc: editor.CssComposer});
> const final = `${html}<style>${css}</style>`;
> ```

My scenario is simple, I am importing into `GJS` some `HTML`,`CSS`,`JS` files. For everything to look as it was I am using something like this:
```
canvas: {
    scripts: ['https://ajax.googleapis.com/ajax/libs/webfont/1.6.26/webfont.js','https://d3e54v103j8qbb.cloudfront.net/js/jquery-3.4.1.min.220afd743d.js'],
    styles: [
      'css/mycss.css',
    ]
  },
  plugins: ['grapesjs-plugin-export'],
      pluginsOpts: {
        'grapesjs-plugin-export': { /* options */ }
      }
```
The issue I have is that when I try to export the code using the grapesjs export plugin nothing referenced inside `canvas` is exported.

Any tip in the right direction will be appreciated!
Thanks!

**Comment by artf** [comment]
> The issue I have is that when I try to export the code using the grapesjs export plugin nothing referenced inside canvas is exported.

@Yakito For now, those scripts/styles should be included manually, you can use `root` option from the export plugin:
```js
root: {
  ...
  'index.html': ed => `
	<head>
		<link href="${myStyle}" .../>
		<script src="${myScript}" .../>
	</head>
	<body>${ed.getHtml()}</body>
  `
}
```
