### ISSUE TITLE
I can't find undo/redo/remove buttons

### ISSUE THREAD

**Issue by ShepelE** [artf/grapesjs#524]
Hello! Artf, thank you for grapesjs.

I've been trying to google where these buttons should be added - nothing. So I think they should be shown by default. But not in my case ((
Please, help me to figure out where the problem is

I inserted grapesjs into React component - just simply inserted grapesjs init to componentDidMount. Everything works fine except this issue

**Comment by artf** [comment]
Check here https://github.com/artf/grapesjs/blob/gh-pages/js/grapesjs-preset-webpage.js#L198

**Comment by ShepelE** [comment]
Thank you!

**Comment by benvmatheson** [comment]
I'm getting a 404 on the above address.

**Comment by artf** [comment]
@benvmatheson 
https://github.com/artf/grapesjs-preset-webpage/blob/master/src/panels/index.js
