### ISSUE TITLE
New feature

### ISSUE THREAD

**Issue by matiponce91** [artf/grapesjs#526]
Hi Arthur,
I have developed a new feature that is the possibility to add tabs inside blocks panel (this is optional what it means that if you don't add any tab, blocks panel will continue behaving as before) and these tab could have their own categories and blocks. My question is if would be possible to add this feature in core GrapesJs due to I had to develop a brand new manager called TabManager.
In case it would be only possible to add as a plugin, how can I add this new manager?

The idea is that doing 
```javascript
tabManager:{
    default : 'content',
    tabs: [{
        id: 'tab1',
        label: 'Tab 1',
        attributes: { class:'gjs-fonts gjs-f-b1' }
    },{
        id: 'tab2',
        label: 'Tab 2',
        attributes: { class:'gjs-fonts gjs-f-b1' }
    }]
}
```

And adding the tab id inside block definition as below:
```javascript
label: 'Block',
category: 'Basic',
tab: 'tab1',
attributes: { class:'gjs-fonts gjs-f-b1' },
content: `<div style="padding-top:50px; padding-bottom:50px; text-align:center">Test block</div>`
```

We get the following result:
![captura de pantalla 2017-11-15 a la s 10 47 16](https://user-images.githubusercontent.com/5335746/32839231-80c2aa4e-c9f2-11e7-90e7-4656e3082c02.png)

If we switch to the other tab you can see the result:
![captura de pantalla 2017-11-15 a la s 10 56 11](https://user-images.githubusercontent.com/5335746/32839613-bd44f336-c9f3-11e7-9eb8-445dc018ca39.png)

**Comment by artf** [comment]
Just check here https://github.com/artf/grapesjs/issues/499 :)
