### ISSUE TITLE
Possible to apply changes to only one class?

### ISSUE THREAD

**Issue by ehausen** [artf/grapesjs#53]
Hello,

I'm wondering is it possible to apply changes to interface to only one class?

Now I get:
![screen shot 2017-03-11 at 16 44 13](https://cloud.githubusercontent.com/assets/6204129/23824161/353b26c8-067a-11e7-97f4-74c207e08bd3.png)
![screen shot 2017-03-11 at 16 44 30](https://cloud.githubusercontent.com/assets/6204129/23824162/3aa02f14-067a-11e7-8253-68a2a8c81c37.png)

Is it possible via the interface achieve, without the another classes? like so:

.quote-special {
  font-size:20px;
}

**Comment by artf** [comment]
@ehausen you're able to deselect classes by clicking on checkboxes
![classes](https://cloud.githubusercontent.com/assets/11614725/23828214/44b7fb84-06cb-11e7-85b0-42f64076eb7a.gif)
