### ISSUE TITLE
Elements hidden through the layer manager can no longer be brought back after saving the content.

### ISSUE THREAD

**Issue by tomichal** [artf/grapesjs#530]
Steps to reproduce on http://grapesjs.com/demo.html :
1. Click on the Layer Manager.
2. Hide any layer, e.g.: the Header.
3. Save the content - this happens automatically on the demo - which uses browser local storage, with auto-saving every single step.
4. Reload the page.

Result: The hidden layer is not visible on canvas, but still present in the Layer Manager (which is what we expect), however upon clicking on the "eye" button it can no longer be made visible.

**Comment by artf** [comment]
Thanks for the catch @tomichal the fix will be available in the next release
