### ISSUE TITLE
Help wanted : I want to set panels on the left side and editor on the right side

### ISSUE THREAD

**Issue by vishal5033** [artf/grapesjs#531]
Hello,

I want panels to be shown on the left side and editor on the right side of the window.
Can you please help me out

**Comment by JuanTincho** [comment]
Hi! I managed to do it  with a plugin on a project that we are working on. 
I don't know if @artf would like to implement it in grapesjs.

**Comment by vishal5033** [comment]
Hi @JuanTincho , Can you please provide me that plugin.
I also want to implement tabs in the panel menu. If you have some details about that also. Can you please share with me, it would be very helpful.

**Comment by artf** [comment]
Currently, the core comes with a [default set](https://github.com/artf/grapesjs/blob/dev/src/panels/config/config.js) of [Panels](https://github.com/artf/grapesjs/wiki/API-Panels) but likely this will be removed in the future. Grapesjs doesn't care too much about the UI part around the canvas, so if you need something complex, animated panels, etc. just use js/css

**Comment by Geczy** [comment]
@JuanTincho yes please post the plugin

**Comment by punkt2** [comment]
@JuanTincho it would be awesome if you share the code with us

**Comment by JuanTincho** [comment]
Sorry guys, I have done it with a .scss file.
This is my code:

```
.gjs-cv-canvas {
  right: 0;
  left: auto;
}

.gjs-pn-panel {
  &#gjs-pn-commands {
    right: 0;
    left: auto;
  }

  &#gjs-pn-options {
    margin-left: 15%;
    right: auto;
  }

  .gjs-pn-buttons {
    justify-content: center;
  }

  &#gjs-pn-views-container,
  &#gjs-pn-views {
    left: 0;
    right: auto;
  }

  &#gjs-pn-devices-c {
    right: 10em;
  }
}
```

**Comment by artf** [comment]
Be aware that from https://github.com/artf/grapesjs/releases/tag/v0.14.5 `#gjs-pn-*` are now `.gjs-pn-*`
