### ISSUE TITLE
Error when trying to hide some elements from the Layers Manager

### ISSUE THREAD

**Issue by tomichal** [artf/grapesjs#532]
Steps:
1. Go to http://grapesjs.com/demo.html
2. Open Layer Manager.
3. Click on the "Build your templates without coding" text element.
4. Click on the "eye" button in the Layer Manager to hide the element.

Result: 
The following exception is thrown: 
Uncaught TypeError: Cannot create property 'display' on string ''
and the element is not hidden.

I believe I found the cause and will create a pull request with a fix.

**Comment by artf** [comment]
Fixed with the latest version https://github.com/artf/grapesjs/releases/tag/v0.12.37
