### ISSUE TITLE
New section in View Container

### ISSUE THREAD

**Issue by vishal5033** [artf/grapesjs#535]
Hello,

I want to add a new section in view container. Lets say, when we click Style manager it opens style manager.
I want to create similar behaviour. Need to show some pre-defined templates which should be shown under that section.

Can you please help me out?

**Comment by artf** [comment]
To add more buttons there
```js
editor.Panels.addButton('views', {
    id: 'yourBtnId',
    className: 'fa fa-paint-brush yourClass',
    command: 'yourCommand',
    attributes: { title: 'Some title'},
})
```
Then create `yourCommand` [Command](https://github.com/artf/grapesjs/wiki/API-Commands), which might be very similar to 
https://github.com/artf/grapesjs/blob/dev/src/commands/view/OpenBlocks.js

**Comment by Amir2828** [comment]
Hey did you manage to create that new templates view? 
If so I would like some pointers as I try to do something similar
