### ISSUE TITLE
Better Alignment for Block in Block Manager

### ISSUE THREAD

**Issue by edwardjiawei** [artf/grapesjs#536]
For example, Block for 2 Columns and 2 Columns 3/7 's font awesome and label are not aligned

![2 Columns 3/7 Block](https://user-images.githubusercontent.com/23583324/32939391-430e7966-cbba-11e7-8afb-05cd790a2277.PNG)

**Comment by artf** [comment]
If you're creating your editor you can easily tweak some CSS, don't see this as something to "fix" at the core level
