### ISSUE TITLE
Clicking component always opens styles first, even if I override

### ISSUE THREAD

**Issue by Geczy** [artf/grapesjs#538]
When I click the component, I want the traits to open

```
view: defaultType.view.extend({
        events: {
          click: e => {
            editor.Panels.getButton('views', 'open-sm').set('active', false)
            editor.Panels.getButton('views', 'open-tm').set('active', true)
          },
```

Clicking a component opens the styles. Clicking it one more time will finally open `open-tm` the traits manager. 

How do I override opening styles on `click`?

**Comment by artf** [comment]
Hey Matt, probably you're using the code from the demo and therefore you're conflicting with this https://github.com/artf/grapesjs/blob/gh-pages/js/grapesjs-preset-webpage.js#L257-L268
just try to remove that part

**Comment by Geczy** [comment]
Good thinking, thanks ! Overwrote it in my own code
