### ISSUE TITLE
updatesrc on image change

### ISSUE THREAD

**Issue by kickbk** [artf/grapesjs#541]
I must be missing something, but when I change an image, the localstorage html isn't updating, however, changing the text does. So when I refresh the page after changing an image and text, the text remains, but the image not. Is there a setting I need to change to make the localstorage html update the image src?

**Comment by artf** [comment]
Thanks for the catch @kickbk, actually `src` was not listened. The fix will be available in the next release

**Comment by xamdam777** [comment]
I had to solve this using a workaround and it seems like a good solution at the moment.
I created my own localstorage and I'm saving the template on **_$(window).on('unload..._** 
and loading it again on **_$(window).on('load'_**
