### ISSUE TITLE
Add select with optgroup

### ISSUE THREAD

**Issue by mohit5540** [artf/grapesjs#544]
Hello @artf 

I have recently started using grapeJs and found it awesome. 

Can you please help me on How can I add dropdown(select) with optgroup inside trait.
Or is there any custom option available like 'html' where I can add my own html 
traits: [{
                    label: 'PartialName',
                    name: 'selectPartial',
                    type: 'select',
                    changeProp: 1,
                    **html: 'custom html'** // e.g., for custom html 
                }],

Thanks

**Comment by artf** [comment]
Hi @mohit5540, you have to define a new [Trait](https://github.com/artf/grapesjs/wiki/Traits#define-new-trait-type) if you want custom stuff

**Comment by mohit5540** [comment]
@artf yes, I created custom trait and it worked. Thanks.
