### ISSUE TITLE
Buttons in sector

### ISSUE THREAD

**Issue by NorthstarTech** [artf/grapesjs#545]
How to add the custom button while adding a new sector in grapesJS? Is there any property? How should I create a button while making new sector.

Thanks

**Comment by artf** [comment]
@NorthstarTech what is your use case with a button?

**Comment by NorthstarTech** [comment]
It doesn't need to be a button specifically. We want to add the merge tags/placeholders. Since we offer a large library of them, it would be user-friendly to have inside a sector. Essentially, we would like the placeholders to divided into subcategories and be easy to use.

**Comment by NorthstarTech** [comment]
#287 is similar but we are unsure where they are adding the placeholders within the editor.

**Comment by artf** [comment]
Well, if you check http://grapesjs.com/demo.html you'll see there is a `Setting Sector`, just above `General`, which is simply defined here
https://github.com/artf/grapesjs/blob/gh-pages/js/grapesjs-preset-webpage.js#L276-L292
so you can try the same approach
