### ISSUE TITLE
Agnostic protocol on CDN

### ISSUE THREAD

**Issue by kickbk** [artf/grapesjs#548]
Just a thought, but you may want to consider loading fontawesome agnostically in your CDN files. Currently getting "Access to Font at 'https://cdnjs.cloudflare.com/ajax/libs/grapesjs/0.12.37/fonts/fontawesome-webfont.woff2?v=4.7.0' from origin 'http://localhost:3000' has been blocked by CORS policy..." on dev environment.
BTW, not sure I said it before, but this project is absolutely great.

**Comment by artf** [comment]
Thanks @kickbk :)
Anyway, I don't get exactly which is your solution

**Comment by kickbk** [comment]
@artf you're referencing FA in https://cdnjs.cloudflare.com/ajax/libs/grapesjs/0.12.37/css/grapes.min.css with `...'FontAwesome';src:url("../fonts/fontawesome-webfont.eot?v=4.7.0")`
so cloudflare is trying to load the fonts from https://cdnjs.cloudflare.com/ajax/libs/grapesjs/0.12.37/fonts/fontawesome-webfont.woff2?v=4.7.0
which doesn't exist, and if it did, it would be throw CORS errors on localhost dev environments and non-ssl websites.

I'm not sure what the solution should be. Personally, I would load FA separately from grapesjs.css. In many cases we load FA with CDN anyway.

**Comment by artf** [comment]
@kickbk well actually I plan to remove FA (#74)  from core's dependencies and replace the used icons icons with SVGs

**Comment by kickbk** [comment]
@artf Any chance we could keep classes optional so we could either use a CSS class or a SVG as icons? This way we can load whatever lib we want (FA, Ionicons, etc.) and done, instead of designing svg icons ;)

**Comment by artf** [comment]
@kickbk well actually it's not mandatory, for example, I use custom SVGs inside `label` here:
https://github.com/artf/grapesjs-plugin-forms/blob/master/src/blocks.js

**Comment by kickbk** [comment]
@artf Perfect solution.

**Comment by artf** [comment]
@kickbk I close this then and keep the idea of removing FA from the core
