### ISSUE TITLE
How to add select filed in header bar on editor

### ISSUE THREAD

**Issue by desilvaNSP** [artf/grapesjs#55]
How can I add select filed on header bar
![screenshot from 2017-03-15 13 33 30](https://cloud.githubusercontent.com/assets/3749657/23938844/05f67ea0-0984-11e7-9bb6-2cc5a4fea5a2.png)

please give me a solution for my problem

I want to add custom UI element on your header bar in editor,How can i do it?

**Comment by sirsmac** [comment]
Please go thru the demo.js file in detail. Scroll to the bottom and modify the following code to add new desired option. 

,{
      id: 'clean-all',
      className: 'fa fa-trash icon-blank',
      command:  function(editor, sender) {
        if(sender) sender.set('active',false);
        if(confirm('Are you sure to clean the canvas?')){
          var comps = editor.DomComponents.clear();
          localStorage.setItem('gjs-css', '');
          localStorage.setItem('gjs-html', '');
        }
      },
      attributes: { title: 'Empty canvas' }
    }

**Comment by desilvaNSP** [comment]
I have overide grapejs.init in my code.not in the demo.js
```

`    var editor = grapesjs.init({
        container: '#gjs',
        fromElement: true,
        plugins: ['gjs-plugin-export'],
        pluginsOpts: {
            'gjs-plugin-export': {
                btnLabel: 'EXPORT',
                preHtml: '<!doctype><html><head><link rel="stylesheet" href="./css/style.css"></head><body>'
            }
        }
    });
`

How I add new element into this.
```

**Comment by artf** [comment]
@desilvaNSP if the built-in button interface (illustrated also by @sirsmac) doesn't fit your needs just use your UI components.
Quick example
```js
var selectEl = $('<select> <option>Desktop</option> <option>Tablet</option> </select>');
selectEl.appendTo('#gjs-pn-options .gjs-pn-buttons');
selectEl.on('change', function() {
  // Use GrapesJS's API if you need to
  editor.setDevice(this.value);
});
```
