### ISSUE TITLE
Document dirty indicator

### ISSUE THREAD

**Issue by duskhacker** [artf/grapesjs#551]
I'd like to indicate that the document is not saved. What would be the best way to know if the document data has changed from the last load/save? 

Thanks!

**Comment by artf** [comment]
There is an internal counter which you can use like this
```js
editor.on('change:changesCount', () => {
     const editorModel = editor.getModel();
     const changes = editorModel.get('changesCount');
     if (changes) {
          // dirty
     }
});
// same as
editor.on('change:changesCount', (editorModel, changes) => { ... });
```

**Comment by duskhacker** [comment]
Perfect! Thank you so much for the quick reply ... and also this project. Very nice!
