### ISSUE TITLE
BUG: mj-preview is not editable

### ISSUE THREAD

**Issue by driskell** [artf/grapesjs#5549]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Safari 17

### Reproducible demo link

https://grapesjs.com/demo-mjml.html

### Describe the bug

**How to reproduce the bug?**
1. https://grapesjs.com/demo-mjml.html
2. Go to view code - copy the MJML
3. Go to import code - paste in the MJML and add to the top `<mj-head><mj-preview>Some preview text</mj-preview></mj-head>`
4. Now try to edit it

<img width="878" alt="Screenshot 2023-12-06 at 14 23 53" src="https://github.com/GrapesJS/grapesjs/assets/939815/2d6ab784-c6b5-4de4-a522-d6f4ed076eee">

**What is the expected behavior?**

Should be able to edit - or it shouldn't be visible in the editor.

**What is the current behavior?**
It displays top left, with default font, no padding, and is not editable. In previous versions of grapeJS builder it is in fact editable, but if you edit it too short the highlight "BODY" gets in the way and you can never get back to editing it. Further, if you empty it, it seems unreachable in the editor completely but the gap is still there.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by driskell** [comment]
If this is isn't intended to be displayed then maybe the bug here is it shouldn't display at all - and it's up to the template / sender to sort out a preview and add it in

**Comment by artf** [comment]
This is not core related issue and probably not an issue at all as `<mj-preview>` [is not supported](https://github.com/GrapesJS/mjml/tree/master/src/components) by default in mjml plugin

**Comment by driskell** [comment]
@artf Sorry I don't understand. It’s an issue as detailed. Is it something to raise on the other repository? I’m not familiar with the internals here so don’t know what it is that the GrapesJS/mjml needs to support in order for this repository to not display it

**Comment by artf** [comment]
> Is it something to raise on the other repository?

Yes, as this is not related to the core.

> I’m not familiar with the internals here so don’t know what it is that the GrapesJS/mjml needs to support in order for this repository to not display it

You have to register a new custom component similar to [others](https://github.com/GrapesJS/mjml/tree/master/src/components) and apply the logic you want for `<mj-preview>`
