### ISSUE TITLE
Add external script in script while creating new component

### ISSUE THREAD

**Issue by HarshOB** [artf/grapesjs#555]
Hello @artf 

How can I pass external script link while creating a component? like this way,

`
bm.add('test-block2', {
  label: 'Test block2',
  attributes: {class: 'fa fa-text'},
  content: {
    script: '<script src="https://cdn.ckeditor.com/4.6.2/full/ckeditor.js"></script>CKEDITOR.replace( \'editor1\' )',
    content: '<textarea name="editor1"></textarea>'
  }
});`

Right now it shows error like unexpected token '<'

**Comment by arthuralmeidap** [comment]
Move the `script` tag to import CKEditor on the html page and just call the script inside the block.

**Comment by artf** [comment]
@HarshOB https://github.com/artf/grapesjs/wiki/Components-&-JS#template-related

**Comment by rohanreddyg** [comment]
javascript somehow not allowing script end tag ("</script>") with in string. So just change the code to be like:
`script:  '<script>alert("Hi");<' + '/script>'  `
