### ISSUE TITLE
Classes are missing on editor.gethtml()

### ISSUE THREAD

**Issue by krunal039** [artf/grapesjs#557]
I can see classes are added on canvas but when I get html via editor.gethtml(), i so some of classes are not included and it is just divs without any classes. attached screenshot with html on canvas and html via editor.gethtml()

![capture](https://user-images.githubusercontent.com/11716808/33126003-bf41ecca-cf7a-11e7-8b56-3ec57389b9f7.PNG)

**Comment by arthuralmeidap** [comment]
When you use the `editor.getHtml` it returns just the html .  If you need the css too, you can use the `editor.getCss()`.

**Comment by Geczy** [comment]
I use newsletter-plugin and `window.grapesjs.editors[0].runCommand('gjs-get-inlined-html')`

**Comment by krunal039** [comment]
@arthuralmeidap thanks for reply but what I meant by just html, returned html looses all css class reference, if you look at attached picture, you will see all div's class attribute is removed. but i can see class applied in canvas.

**Comment by krunal039** [comment]
@Geczy I tried editor.runCommand('get-inlined-html') but it does not return anything

**Comment by arthuralmeidap** [comment]
As I said, the `editor.getHtml()` does not returns the applied css on the canvas.
You will need a the `editor.getCss()` to get the css

**Comment by Geczy** [comment]
Include the newsletter plugin

**Comment by krunal039** [comment]
@arthuralmeidap I am not after applied class defination(getCss() will return class defination), I am after correct html with class name applied. when I use html.getHtml() it remove some of applied classes from returned html.

I can see class applied in canvas like as I mentioned in image.

example:

canvas: <div class="sample">Text Content</div>
editor.getHtml(): <div>Text Content</div>

Also request you to look at image attached,

**Comment by Geczy** [comment]
Don't think `gjs-` prefixed classes will return

**Comment by krunal039** [comment]
@Geczy correct, it does not return classname start with gjs, I have change class name prefix and it is fine now.

**Comment by ashishmit14** [comment]
@krunal039 Could you please tell me, how did you remove the prefix 'gjs'?
