### ISSUE TITLE
Help: Can you please give an example of Chart.js as a block in grapesjs.

### ISSUE THREAD

**Issue by suchithmahadi** [artf/grapesjs#558]
@artf can you please give one complete example of a chart using chart.js with traits for changing the colour, values & Data Points.?
It would be great if i can get a help.

**Comment by Geczy** [comment]
You can use the sandbox demo here https://github.com/artf/grapesjs/issues/559

It lets you modify traits and updates the dom. Should get you started

**Comment by suchithmahadi** [comment]
@artf Please help me out.

**Comment by artf** [comment]
@suchithmahadi for this kind of question I'd recommend asking on https://stackoverflow.com

**Comment by ionic666** [comment]
@suchithmahadi hi,bro.Have you done this?
