### ISSUE TITLE
Why is my component selected full width? 

### ISSUE THREAD

**Issue by Geczy** [artf/grapesjs#559]
Trying to create a custom component, see [demo here](https://5vo5ppvm8p.codesandbox.io/) and [code here](https://codesandbox.io/s/5vo5ppvm8p)

Drag out two `button`, then drag out two `button + link`
The two buttons are proper width, but the custom component is some weird full width fixed height thing

Why? 

![image](https://user-images.githubusercontent.com/1036968/33134633-4792f4d2-cf6e-11e7-84b1-cd588a3e6d95.png)

**Comment by artf** [comment]
the default `tagName` property is a `div`, change this in your model
```js
 ...
 defaults: Object.assign({}, defaultModel.prototype.defaults, {
              tagName: 'span', //<---
              droppable: false,
...
```

**Comment by Geczy** [comment]
Makes sense now, thanks
