### ISSUE TITLE
How load new html template  into editor

### ISSUE THREAD

**Issue by desilvaNSP** [artf/grapesjs#56]
I have loaded html template into editor initialy

```
<div id="gjs">
<!-- html content-->
</div>
```

script 
```

    var editor = grapesjs.init({
        container: '#gjs',
        fromElement: true,
        plugins: ['gjs-plugin-export'],
        pluginsOpts: {
            'gjs-plugin-export': {
                btnLabel: 'EXPORT',
                preHtml: '<!doctype><html><head><link rel="stylesheet" href="./css/style.css"></head><body>'
            }
        }
    });

```

how I update editor content with new template by replacing existing template. Is there any quick method for that in grapejs.
I use select option to load html template.I want to dyanamically apply html template into this editor content.

Thanks in advance.

we need documentation for this library..this is awesome web editor.

**Comment by artf** [comment]
Sure, you can update the entire content with `setComponents`
```js
editor.setComponents('<div class="test">Hello</div><style>.test{color:red}</style>');
```
or just only the style
```js
editor.setStyle('.test{color:blue}');
```
