### ISSUE TITLE
Table <thead> and <tbody> tag gets Omitted

### ISSUE THREAD

**Issue by fsaiyedOB** [artf/grapesjs#563]
Hello,
There is new issue with GrapesJS (maybe). I've created new component using `bm.add()` in which I've used a table element with `<thead>` and `<tbody>` tags. But when getting html using `editor.getHtml()` method, the `<thead>` and `<tbody>` tags gets ommited. Can you please help?

![screenshot from 2017-11-23 10-16-20](https://user-images.githubusercontent.com/33310500/33159266-5ebd404e-d037-11e7-8699-0f7f4c13935f.png)

![screenshot from 2017-11-23 10-14-28](https://user-images.githubusercontent.com/33310500/33159247-2a354402-d037-11e7-8b85-6816515bd953.png)

**Comment by artf** [comment]
@fsaiyedOB yeah, I've made the [table component](https://github.com/artf/grapesjs/blob/dev/src/dom_components/model/ComponentTable.js) like this because at that moment of writing the sorter was acting differently and it was messy ordering rows with `tbody`-like elements around. Currently, dealing with tables it's not my priority but I'll leave this issue open in case someone else would like to do so

**Comment by ryandeba** [comment]
Hi @artf - I can probably take a look at this at some point. I've started by just removing the "Clean table rows from non rows" section in the [table component](https://github.com/artf/grapesjs/blob/dev/src/dom_components/model/ComponentTable.js) (lines 54-68). Can you point me in the right direction of what problems this causes that need to be addressed?

**Comment by artf** [comment]
@ryandeba right start :) The main problem I was facing initially it was with the sorting so, for the rest, I'd probably update the current `droppable` with just `['tbody', 'thead', 'tfoot'],` and create 3 simple components:
`ComponentTableBody`, `ComponentTableHead`, `ComponentTableFoot` which basically accept only `<tr>`s inside and could be dropped only inside `<table>`s

**Comment by ryandeba** [comment]
Thanks! I'll try to get started on this in the next few days.

**Comment by artf** [comment]
Merged #606
