### ISSUE TITLE
Use external css/fonts for plugin

### ISSUE THREAD

**Issue by paulroberttaylor** [artf/grapesjs#564]
Hi, 

I have an idea for an app that I think the people in my field would find useful.  Essentially, there is a framework that we use for application development but there is no UI builder for it.

It has a fairly large css/icons/svg/fonts asset folder.

What I'd like to do is be able to create a plugin that will include these assets, instead of having to add each component's styles into the markup of the blocks.

How can this be achieved?

Thanks,
Paul

**Comment by artf** [comment]
Hi Paul, you can inject external styles in this way
```js
const editor = grapesjs.init({
  ...
  canvas: {
    styles: ['...file1.css', '...file2.css', '...']
  }
});

```

**Comment by paulroberttaylor** [comment]
Fantastic!  Thanks @artf

**Comment by suraj740** [comment]
Hi @paulroberttaylor  , how you have included fonts inside styles,
i am also doing same but nothing change happens
const editor = grapesjs.init({
  ...
  canvas: {
    styles: ['<link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">']
  }
});

**Comment by paulroberttaylor** [comment]
@suraj740 This is how I did it after @artf 's comment.

```
    <script type="text/javascript">
      var editor = grapesjs.init({
        height: '100%',
        showOffsets: 1,
        noticeOnUnload: 0,
        storageManager: { autoload: 0 },
        container: '#gjs',
        fromElement: true,
        canvas: {
          **styles: ['dist/assets/styles/main.css']**
        },
        showDevices:false      
      });
      
      window.editor = editor;
      editor.Panels.getButton('views', 'open-blocks').set('active', 1);
      
    </script>
```
