### ISSUE TITLE
Custom html elements

### ISSUE THREAD

**Issue by paulroberttaylor** [artf/grapesjs#565]
Is it possible, and if so how to do it, to use a custom html element e.g.

<body>
  <my-custom-tag/>
</body>

Which will render specific html for the preview window, but the source will output the custom tag?

Thanks,
Paul

**Comment by artf** [comment]
Yeah you can use different tag names in your custom component
```js
const dc = editor.DomComponents;
const defaultType = dc.getType('default');

dc.addType('my-custom-type', {

  model: defaultType.model.extend({
    tagName: `custom-tag`
  }, {
    isComponent(el) {
        if(el.tagName == 'CUSTOM-TAG') 
          return {type: 'my-custom-type'}
    },
  }),

  view: defaultType.view.extend({
     tagName: 'div' //<-- in canvas div will be used
  })
});
```

**Comment by paulroberttaylor** [comment]
Thanks @artf, that points me in the right direction.

If I want the anything that needs to be editable in the block to appear in the custom tag code, how would I achieve that?

**Comment by artf** [comment]
You mean something like this?
```js
editor.BlockManager.add('custom-block', {
     label: 'Custom Block'
     content: '<custom-tag>...</custom-tag>',
})
```

**Comment by paulroberttaylor** [comment]
Say for instance I have this custom tag which I need to be in the code panel:

`<custom-tag>
</custom-tag>
`

**Comment by artf** [comment]
@paulroberttaylor sorry but I don't get which is your question. If you use the code above, you create a new block in the **Block Panel**, then you can drag inside the canvas

**Comment by paulroberttaylor** [comment]
@artf hi, I can create the block, I just don't know how the values from the block can be transferred to the component, and therefore the final code

**Comment by artf** [comment]
Once you've defined your custom component all you have to do is to drag stuff inside it.
```html
<div id="gjs">
     <custom-tag your="attributes">
          <div>Text1</div>
          <div>Text2</div>
    </custom-tag>
</div>

<script type="text/javascript">
  var editor = grapesjs.init({
      autorender: 0,
      container : '#gjs',
      fromElement: true,
  });
  // ... Define your custom component and blocks
     
  // Here I explain the reason of `render()`
  // https://github.com/artf/grapesjs/wiki/Components#hints
  editor.render();
</script>
```
