### ISSUE TITLE
Resize blocks with mouse?

### ISSUE THREAD

**Issue by matthewgertner** [artf/grapesjs#568]
I noticed that in the current demo it is only possible to resize most blocks using the property editor, not by dragging anchors on the block (which is possible with the map element for example). Is this by design or is it simply a feature that has not been implemented yet?

**Comment by ryandeba** [comment]
Hi @matthewgertner,

I believe this is can be enabled on individual components via the "resizable" property (`component.set("resizable", true)`). It's probably not going to work very well on elements having `display: inline` style (a <span> for example).

**Comment by artf** [comment]
@matthewgertner Ryan's solution should work, and, yes, I do not apply them by design for reasons already explained by Ryan but you can actually create blocks/components with resizable enabled

**Comment by matthewgertner** [comment]
@ryandeba @artf Great, thanks for the suggestion. We're playing with the codebase now so we'll give that a try.
