### ISSUE TITLE
Text block content duplication

### ISSUE THREAD

**Issue by markbailey** [artf/grapesjs#569]
I have reproduced this on the website demo, so I know it is not due to my coding.
If you set a min-height, width to a text block and then delete all the text so it is empty, when you reenter text the text duplicates.

**Comment by ryandeba** [comment]
Hi @markbailey,

I was able to recreate that issue and submitted a pull request to fix it. The duplicated content only appears to be in the dom, not in component, and forcing the view to render after editing seems to fix it.

**Comment by markbailey** [comment]
Hi @ryandeba , thanks for that info and the work around. I look forward to your changes getting merged.
