### ISSUE TITLE
Get Changes as JSON from edior in grapejs

### ISSUE THREAD

**Issue by desilvaNSP** [artf/grapesjs#57]
Basically I am using json configs to keep attributes of each UI component of the template.Following is the configs that I kept.
```

{
	"registration": {
		"form": "signup-form",
		"fields": [{
			"id": "signup-input-username",
			"name": "input-username",
			"label": "User name",
			"type": "text",
			"placeholder": "This is test username"
		}, {
			"label": "Password",
			"id": "signup-input-password",
			"name": "input-password",
			"type": "password",
			"placeholder": "This is password"
		}],
		"controls": {
			"submit": {
				"id": "btn-signin-form",
				"name": ""
			},
			"cancel": {
				"id": "",
				"name": ""
			}
		}
	}
}
```

In this case, I create my registration form dynamically from that config json.And that form html load into the grapejs editor.and change whatever thing we want through the grapejs editor.
And As example, I want to change label name and save it as html. BTW I want get those changes into my config json. It goes trouble to me becuase I only know to get editing changes as html using getHTML() method in grapejs.

If there any capability to get those changes into (outside as json) my configs without html

Appreciate your help.

Thanks 
sandun.

**Comment by artf** [comment]
Have you tried using `editor.getComponents()`? This method returns JSON representation of components
