### ISSUE TITLE
rich text editor issue 

### ISSUE THREAD

**Issue by NorthstarTech** [artf/grapesjs#572]
How to add the icon of ordered List in rich text editor? Here is my code.

rte.add('insertOrderedList', {
icon: '',//how to add the icon of orderlist here??
attributes: {title: "Ordered List"},
result: (rte, action) => rte.exec('insertOrderedList'),
});

**Comment by ryandeba** [comment]
You can just set the `icon` value to whatever markup you want. Here's an example using font awesome:
```
...
icon: '<i class="fa fa-list-ol"></i>',
...
```

FYI - I've seen some discussion of removing font awesome from grapesjs. I'm not sure what the current plans are for that, but thought it was worth mentioning as this may not work in a future version without including font awesome in your own project.

**Comment by NorthstarTech** [comment]
Thank u so much. working fine now.
