### ISSUE TITLE
Using Grapes with Zeronet.

### ISSUE THREAD

**Issue by Snarkly** [artf/grapesjs#574]
Is there a way to use grapesjs with zeronet? https://zeronet.io/ You can create sites on zeronet but to add headers, banners and other things you have to get into the CSS and HTML to write code. I hate coding with a passion and would like to use grapesjs on zeronet so I can use grapes drag and drop features to create a site on zeronet. Here is zeronet's github page https://github.com/HelloZeroNet If it's possible to use grapes on zeronet please let me know how.

**Comment by duskhacker** [comment]
@Snarkly GrapesJS is not a drop-in turn-key solution. You'll have to understand (and do) Javascript coding just to get the editor working. Its purpose is for adding a fancy HTML editor to an existing web stack.

**Comment by artf** [comment]
Hi Jeffery, unfortunately, Daniel is right, if you want to use GrapesJS in other projects someone (devs) need to integrate it first. 
I think you can try at least to ask ZeroNet's devs if they put GrapesJS integration in their Roadmap
