### ISSUE TITLE
Only allow one component of specific type on editor

### ISSUE THREAD

**Issue by krunal039** [artf/grapesjs#577]
is there way to not allow to drop any specific component more than one time on page? I have custom component and user cannot drop it more than one on page, so if component is already added on page then I want to display specific message and not allow to be dropped in editor

**Comment by ryandeba** [comment]
Hi @krunal039,

My best suggestion would be to listen for the [component:add](https://github.com/artf/grapesjs/wiki/API-Editor#available-events) event. In the event listener function you could check to see if the added component is the type that you are looking for, and if more than one of those components now exist in the canvas then remove the one that was just added and inform the user.

**Comment by artf** [comment]
@krunal039 Ryan's suggestion is the correct way to accomplish your request

**Comment by krunal039** [comment]
@artf @ryandeba  thanks for reply, can you please let me know where can I listen event for component:add

**Comment by bunomonteiro** [comment]
```
editor.on('component:add', model => {
    // ... your logic goes here
    if(remove){
        model.destroy();
    }
  });
