### ISSUE TITLE
disable file upload in asset manager

### ISSUE THREAD

**Issue by krunal039** [artf/grapesjs#578]
is there way to disable asset upload, we want to force user to use approved images only and that to via asset manager dialog.

**Comment by ryandeba** [comment]
Hi @krunal039,

The (docs)[https://github.com/artf/grapesjs/wiki/API-Asset-Manager#assetmanager] indicate that you can pass `upload: false` to disable it (see the comment in the "Examples" section). Have you tried doing that? I don't have time to test it out myself at the moment, but I'd be happy to help out more later if you try that out and are still having trouble.

**Comment by artf** [comment]
@krunal039 as already mentioned by Ryan, `upload: false` is the way to go

**Comment by shareefhiasat** [comment]
How to hide the box of dragging it still appears i use
please advise thanks.

 ```
assetManager: {
          assets: images,
          upload: false/*,
          uploadText: 'Uploading is not available in this demo',*/
        },
```

**Comment by artf** [comment]
@shareefhiasat just use a CSS

**Comment by sakshigarg9** [comment]
@artf where do i change the css? I'm using the grapesjs-preset-webpage

**Comment by artf** [comment]
> where do i change the css?

Wherever you want, just place it after GrapesJS' CSS

**Comment by benvmatheson** [comment]
I'm seeing the same issue as @shareefhiasat. I have `upload: false` set, but if I double click an image on the canvas the modal still opens. Using CSS to hide the modal makes the modal unusable for other situations. Should the modal be disabled from opening in this situation? Or do I just have something misconfigured?

**Comment by ehsantalkhouncheh** [comment]
upload false did not work for me :(
