### ISSUE TITLE
replacing richtexteditor to ckeditor

### ISSUE THREAD

**Issue by NorthstarTech** [artf/grapesjs#579]
I am replacing richtexteditor to ckeditor in grapesjs but its not working. Richtexteditor is still showing. How should I resolve this? My code is:
 editor.setCustomRte({
	 enable: function(el, rte) {
		rte = new CKEDITOR.inline(el, {
			toolbar: [{
		           attributes: { "class": "fa fa-image" },
		           command: "open-dialog"
		        } ]  
		}); 
		return rte; 
     },
   });

I also added these scripts, 
<script src="https://cdn.ckeditor.com/4.7.3/standard/ckeditor.js"></script>
<script src="js/grapesjs-plugin-ckeditor.min.js"></script>

**Comment by ryandeba** [comment]
Hi @NorthstarTech,

I see that your code is including the grapesjs-plugin-ckeditor.js file. Are you also including that plugin when calling `grapesjs.init()` as shown [here](https://github.com/artf/grapesjs-plugin-ckeditor#usage)?

**Comment by NorthstarTech** [comment]
yes I also added the plugin on grapesjs.init() but not working. It gives the error shown below.
![error](https://user-images.githubusercontent.com/33541046/33324406-5b78d432-d471-11e7-9a18-a0e387dec055.png)

**Comment by ryandeba** [comment]
I'm not super familiar with the ckeditor plugin, but it does appear to that it is expecting the sharedspace ckeditor plugin (see [here](https://github.com/artf/grapesjs-plugin-ckeditor/blob/b05ecaba1f63f93757b3cde8a17808212f7ad899/src/main.js)). I think you just need to be sure and include that plugin in your CKEditor configuration. Here's a link to that [plugin](https://ckeditor.com/cke4/addon/sharedspace), but I bet you could also do a custom build of CKEditor through their website and choose to include that from the Available Plugins list.

**Comment by NorthstarTech** [comment]
Thanks alot, I added the sharedspace ckeditor plugins and now it is displaying default toolbar. I want to use my own toolbar, I made a separate file of config.js and add it as a customconfigfile. But its not working. How should I resolve this.  Here is my code.
var editor = grapesjs.init({
    height: '100%',
    noticeOnUnload: 0,
    storageManager:{autoload: 0},
    container : '#gjs',
    fromElement: true,
    plugins: ['gjs-mjml','gjs-plugin-ckeditor'],
    pluginsOpts: {
        'gjs-plugin-ckeditor': {
            position: 'center',
            option: {
            	customConfig: 'config_gjs.js',
            }
        }
    } 
  });

**Comment by artf** [comment]
@NorthstarTech never tried with separate config (check the net console, probably your path is wrong) so I recommend using inline configs
