### ISSUE TITLE
Disable editing html element

### ISSUE THREAD

**Issue by desilvaNSP** [artf/grapesjs#58]
Hi, nice day for you. I have problem with disable editing specific html element in grapejs editor.

I have some labels, those are cannot be editing by user.It should be fixed.

How we do that in grape editor.

Thanks

**Comment by artf** [comment]
Hi @desilvaNSP each component has `editable` property which by default is set to `true` for Text Components (you can check all props are [here](https://github.com/artf/grapesjs/blob/dev/src/dom_components/model/Component.js))

If you want you can set this props also during the parsing using `data-gjs` attribute:
```html
...
<label data-gjs-editable="false">Text here<label>
...
```
