### ISSUE TITLE
[Question] Any/Trigger event when any block is dropped inside canvas?

### ISSUE THREAD

**Issue by fsaiyedOB** [artf/grapesjs#580]
Hey,
How can I trigger some event when any new block or content inside canvas is updated? 
Something like `editor.onCanvasUpdate()`

Thanks!

**Comment by ryandeba** [comment]
Hi @fsaiyedOB,

I've been able to accomplish this with the `component:update` event listed here: https://github.com/artf/grapesjs/wiki/API-Editor#available-events

My code looks something like 
```
editor.on("component:update", function() {
  // do stuff here
});
```

**Comment by duskhacker** [comment]
When I asked to find out when the canvas is dirty to provide an indicator, @artf told me: 

```
editor.on('change:changesCount', (editorModel, changes) => {
  
    if (changes) {
  // do something with changes 
    } else {
     // do something else with no changes 
    }
  });
  
```

**Comment by artf** [comment]
I'd add also a block specific event
```js
editor.on('block:drag:stop', model => console.log('dropped ', model))
```

**Comment by chrisrobbins85kw** [comment]
@artf what about doing this only for specific blocks?

**Comment by artf** [comment]
@chrisrobbins85kw I'd put some check (eg. some attribute/property) inside the callback
