### ISSUE TITLE
Getting "Invalid or unexpected token" error

### ISSUE THREAD

**Issue by kishoreprocessdesign** [artf/grapesjs#584]
In https://unpkg.com/grapesjs

Line: 20837
var previousÐ¡olor = void 0;

Some nonascii character for previousColor. editor doesn't show the non ascii character.

**Comment by ryandeba** [comment]
That's weird. Here's an alternate of the same version that doesn't have that issue: https://cdnjs.cloudflare.com/ajax/libs/grapesjs/0.12.45/grapes.js

**Comment by artf** [comment]
just looking at the source file
https://raw.githubusercontent.com/artf/grapesjs/dev/dist/grapes.js
where the interesting point comes from
https://github.com/artf/grapesjs/blob/dev/src/domain_abstract/ui/InputColor.js#L93
indeed that "C" is not a "real" C 🤔
![schermata 2017-11-30 alle 22 41 27](https://user-images.githubusercontent.com/11614725/33456658-54924454-d620-11e7-80ac-392b0a542e7c.png)
I'll fix it for the next release, thanks for the catch
