### ISSUE TITLE
How to reset the margin and padding input value

### ISSUE THREAD

**Issue by Deepak813** [artf/grapesjs#585]
How to reset the margin and padding input value.

I have reset the input value but when user again click on upper arrow of margin box then it get the previous not the reset value.

Please let me know how to do that.

**Comment by artf** [comment]
Inputs are binded to the target (Components/Css Rules) so it doesn't make sense just changing the input, you have to update the target (eg. `editor.getSelectedToStyle().addStyle({ 'margin-top': 0 })`)
