### ISSUE TITLE
Editor UI changes

### ISSUE THREAD

**Issue by NorthstarTech** [artf/grapesjs#588]
![image](https://user-images.githubusercontent.com/33541046/33379000-87377912-d538-11e7-9079-68dcaf3cd07f.png)

I would like to make the editor like the photo above. However, I can't find the css for the background or the   panels. Any help provided would be fully appreciated.

**Comment by ateshuseyin** [comment]
You can change scss variables and and recompile to css:
https://github.com/artf/grapesjs/blob/dev/src/styles/scss/_gjs_variables.scss#L22
