### ISSUE TITLE
Attributes not being applied to traits

### ISSUE THREAD

**Issue by Geczy** [artf/grapesjs#589]
https://github.com/artf/grapesjs/blob/9bcd9673b10af1bb696181deba6903a68b1b6c3f/src/trait_manager/view/TraitView.js#L86

```js
traits: [
  {
    type: 'url',
    label: 'Link',
    name: 'link-url',
    id: 'hey',
    changeProp: 1,
    placeholder: 'Enter or paste link here',
    attributes: { id: 'hey' },
  },
```

The id is not applied. Only type & placeholder are showing in the HTML of the `<input />`

**Comment by artf** [comment]
Added to the next release
