### ISSUE TITLE
bower install issues, how to properly install grapesjs

### ISSUE THREAD

**Issue by spatsatzis** [artf/grapesjs#59]
Hello, i'm very impressed with your work about this builder

My issue is that i'm struggling to make it work with my current project. When i install the builder with "bower install grapesjs" i can't use it, it seems that some styles are missing and it seems not complete.

For example i can't drag and drop a Hero section, it just draws 4-5 horizontal lines without styling.

When i use it with "git clone" and "npm install" afterwards it works great !

What's the proper way to use grapesjs it if i don't want to use it for development of the source ? is there any way for "bower install grapesjs" do all the work itself ?

thanks !

**Comment by artf** [comment]
Hi @spatsatzis at the moment, I'd suggest to use only `npm`/ `yarn`(faster)
