### ISSUE TITLE
How to overwrite domain_abstract ui Input component? 

### ISSUE THREAD

**Issue by Geczy** [artf/grapesjs#590]
https://github.com/artf/grapesjs/blob/25fdbe14098c7e1a65d3e5527749302174f56a7d/src/domain_abstract/ui/Input.js

I want to change the input class:

https://github.com/artf/grapesjs/blob/25fdbe14098c7e1a65d3e5527749302174f56a7d/src/domain_abstract/ui/Input.js#L15

To something entirely different, ie `form-group`

**Comment by artf** [comment]
Domain abstract stuff are just for internal usage so I don't even plan to let them overwritable, which is you use case?

**Comment by Geczy** [comment]
I want to customize the appearance of the form fields in the settings panel of a component, by using existing classes in bootstrap or another css framework I use. 

So I want to replace  `gjs-field` with `form-group`

**Comment by artf** [comment]
Ok, got the case, but at the moment there is just no easy way to accomplish it :/

**Comment by Geczy** [comment]
Likewise I need to replace `gjs-input-holder` with my own class, `form-control` (bootstrap)
