### ISSUE TITLE
Show hover toottip on block

### ISSUE THREAD

**Issue by krunal039** [artf/grapesjs#591]
I want to add hover preview for block under block manager before user add to canvas. is there way to achieve it?

**Comment by artf** [comment]
@krunal039 definitely is possible, but I'd say you have to make it by yourself as it's totally not an essential feature for the editor

**Comment by krunal039** [comment]
@artf  thanks for reply. is there any event I can use for same? or it has to be out side of editor?

**Comment by artf** [comment]
use native js events
