### ISSUE TITLE
CKEditor Link button Issue

### ISSUE THREAD

**Issue by NorthstarTech** [artf/grapesjs#593]
I successfully replace richtexteditor to ckeditor in grapesjs. but there is a link button issue. The issue is that it is not linking correctly on the position. It moves to the starting position. The picture is shown here.
![linkgrapesjs](https://user-images.githubusercontent.com/33541046/33421947-af1072ac-d5d5-11e7-8d70-aecffc6e0ecb.png)

**Comment by duskhacker** [comment]
I had all kinds of problems with the CKEditor link editor. 

I gave up and disabled the link editor in CKEditor in favor of the link component that is provided by GrapesJS.

**Comment by NorthstarTech** [comment]
so there is no solution of link button in ckeditor?
