### ISSUE TITLE
Help Wanted: make this an angular app to support Angular-Material forms

### ISSUE THREAD

**Issue by absolution54321** [artf/grapesjs#594]
was thinking of converting this into angular app,
I am able to add md- form components but iframe is not rendering any material view,
however exporting it to another html file with angualr enabled understands this

any leads on why angular material is not working inside iframe, even though angular's js files are included using jquery

**Comment by duskhacker** [comment]
Sorry, I can't answer your question, and I'm probably speaking out of turn; It seems to me that your time would be better spent on taking on some of the "help wanted" issues and bugs than forking this into the Angular framework. To me, it seems like a lot of effort for little gain.
