### ISSUE TITLE
Cannot drag with fast actions

### ISSUE THREAD

**Issue by ateshuseyin** [artf/grapesjs#595]
When I move a block on the canvas before showing clone element, editor does nothing. Only move clone of the block symbol. 

![fast_drag_](https://user-images.githubusercontent.com/10994250/33424939-5f9ac0d0-d5ce-11e7-8573-3c7bb1825a4b.gif)

**Comment by ateshuseyin** [comment]
Any one have an idea?

**Comment by artf** [comment]
unfortunately, I didn't find the time yet to investigate this

**Comment by ateshuseyin** [comment]
Is this fixed?

**Comment by artf** [comment]
@ateshuseyin should be fixed in the latest version
