### ISSUE TITLE
storageManager: Loading from remote storage 

### ISSUE THREAD

**Issue by DeathStapler** [artf/grapesjs#597]
Hi,

I'm trying to read the HTML and CSS from my database. When I try to load it into the editor, nothing displays.  I can store the data just, just cannot load it.

Is this the correct format for the data when you are loading it?

Content-type
```
application/json
```

_Preview_
```
{gjs-assets: "", gjs-components: "",…}
   gjs-assets : ""
   gjs-components : ""
   gjs-css : "*{box-sizing: border-box;}body{margin:0;}.c1077{padding:10px;}"
   gjs-html : "<div class="c1077">Insert your text here</div>"
   gjs-styles : ""
```

_Response_
```
{"gjs-assets":"","gjs-components":"","gjs-css":"*{box-sizing: border-box;}body{margin:0;}.c1077{padding:10px;}","gjs-html":"<div class=\"c1077\">Insert your text here<\/div>","gjs-styles":""}
```

**Comment by duskhacker** [comment]
@DeathStapler This is what mine looks like: 

```
{
    "gjs-css":"*{box-sizing: border-box;}body{margin:0;}.c1050{padding:10px;}", 
    "gjs-html":"<div class="c1050">Hi</div>", 
    "gjs-assets":"[]", 
    "gjs-styles":"[]", 
    "gjs-components":"[]"
  }
```

The thing that jumps out at me at first is that assets, components and styles should be arrays, you have empty strings. 

The `Content-Type` is correct.

**Comment by DeathStapler** [comment]
I tried changing them to arrays.  I tried just printing what you are using.  I validated the JSON, just to make sure it checked out.

This is my setup.  Does anything look incorrect?
```
var editor = grapesjs.init({
        container : '#gjs',
        style: '.txt-red{color: red}',
        plugins: ['gjs-preset-newsletter', 'gjs-blocks-basic'],
        pluginsOpts: {
            'gjs-blocks-basic': { blocks: ['video'] }
        },
        assetManager: {
            assets: [
                 'https://siteurl.edu/uploads/screen-shot-2017-11-29-at-9-17-08-am.png',
                 'https://siteurl.edu/uploads/screen-shot-2017-11-16-at-9-21-05-am.png',
            ],
            storeOnChange: true,
            storeAfterUpload: true,
            upload: "/upload-editor-media",
        },
        storageManager: {
            type: 'remote',
            stepsBeforeSave: 1,
            storeComponents: false,
            storeStyles: false,
            storeHtml: true,
            storeCss: true,
            urlStore: "/save-template/2",
            urlLoad: "/load-template/2", 
            params: {},   // For custom values on requests
          }
    });
```

**Comment by artf** [comment]
@DeathStapler first of all, be sure to use the latest release. Check if this helps #159
Otherwise put this `editor.on('storage:load', obj => console.log('Loaded ', obj))` and post here what do you get.
Actually, I do not recommend storing/loading from HTML/CSS, this is your final result, you lose all the information added by the editor (eg. traits, component's properties, etc.), therefore you should rely on 
```js
// are `true` by default
storeComponents: true,
storeStyles: true,
```
but besides this, your code should work. 
In case, does enabling `storeComponents` and `storeStyles` makes the loading works?

**Comment by DeathStapler** [comment]
Never mind.  I will just take the JSON that is sent in the body of the POST and use that.

**Comment by shareefhiasat** [comment]
@DeathStapler do you store each of the following in column in database ?
when you save , and then retrive please advise thanks

```
{
    "gjs-css":"*{box-sizing: border-box;}body{margin:0;}.c1050{padding:10px;}", 
    "gjs-html":"<div class="c1050">Hi</div>", 
    "gjs-assets":"[]", 
    "gjs-styles":"[]", 
    "gjs-components":"[]"
  }
```

**Comment by DeathStapler** [comment]
Hi,

I am storing and retrieving all the of columns.

**Comment by artf** [comment]
@shareefhiasat I explain here how to use them  https://github.com/artf/grapesjs/wiki/Storage#store-and-load-templates
