### ISSUE TITLE
Set Device Height along with Device Width

### ISSUE THREAD

**Issue by attaalive** [artf/grapesjs#599]
Hi I want to add new devices with both width and height, Is there any way I can do this? An other issue is that when I give width of device in inches instead of pixels then its margin property of editor does not work. Please help me on this.
Regards

**Comment by artf** [comment]
Hi @attaalive I'll add the possibility to set the height of devices in the next release. Honestly, I don't get what do you mean by `its margin property of editor does not work`

**Comment by attaalive** [comment]
Hi thanks for your response. I have added a device with width and height. I have given the size of device in inches instead of pixels. Now Margin,Padding and positioning is not working. Please see the screen shot below.
![grapesjs](https://user-images.githubusercontent.com/6896243/33711713-c17eb17e-db66-11e7-85e1-8349ed6b6cf6.png)
 Regards

**Comment by artf** [comment]
@attaalive can you provide a live example (eg. jsfiddel)? Your screenshot is ambiguous on what exactly is not working

**Comment by attaalive** [comment]
@artf  Here is the live example at[]( http://34.210.66.189/grapesJs/)
 Padding and positioning is not working

**Comment by artf** [comment]
works correctly on my side...
![schermata 2017-12-13 alle 13 48 43](https://user-images.githubusercontent.com/11614725/33939621-2e02d7c2-e00c-11e7-81a7-4976b9096aef.png)
