### ISSUE TITLE
How to bind custom upload method? 

### ISSUE THREAD

**Issue by cloudseasail** [artf/grapesjs#60]
This project is awesome,  I would like to use it in my app. 
I  like to use custom file upload engine instead of the build-in uploader,  Could you give me a guide how to bind this?

maybe exposing the select file button?

**Comment by artf** [comment]
Hi @cloudseasail and thanks, would be awesome to see it in your app :)
Anyway, in your case, I'd definitely suggest you to check [this plugin](https://github.com/artf/grapesjs-plugin-filestack/blob/master/src/main.js) where I basically replaced the default uploader.

The most interesting part is how to intercept the asset manager inside the modal:

```js
  editor.on('run:open-assets', () => {
    const modal = editor.Modal;
    const modalBody = modal.getContentEl();
   // here you can add your stuff and remove/style other
```

and how to add new uploaded images inside the asset manager
```js
 editor.AssetManager.add(urls);
```
