### ISSUE TITLE
BUG: unable to hide rte in latest versions

### ISSUE THREAD

**Issue by yashvi2026** [artf/grapesjs#6019]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Chrome

### Reproducible demo link

https://codepen.io/Harshsne/pen/xxoOyXO

### Describe the bug

**How to reproduce the bug?**
1. drop text component
2. edit text component 

**What is the expected behavior?**
rte shouldnt be displayed

**What is the current behavior?**
rte is displayed

this code is working when i change my grapesjs version to 0.20.4,in the latest version only it is not working

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
Yeah `onActive` is now an async method so extending it with `extendFnView` is not enough, your code is executed before the original one.
Anyway, you can achieve the same result with a simple line of CSS
```css
.gjs-rte-toolbar {
  display: none;
}
```

**Comment by yashvi2026** [comment]
but i wanted to hide only some particular type eg:text @artf

**Comment by artf** [comment]
You can still extend the view without using `extendFnView`. Reuse the original component type via prototype, as indicated in [here](https://grapesjs.com/docs/modules/Components.html#extend-parent-functions).
