### ISSUE TITLE
Custom HTML/Javascript

### ISSUE THREAD

**Issue by michaellwatson** [artf/grapesjs#602]
Not technically an issue but I'm looking for a way to replicate the "code editor" feature in Click Funnels, where there is a block that opens an editor.

Don't want to start getting too creative as I think there is a way to do this inside grapesjs (probably).

If not I can start writing one, but thought I should check best implementation first.

Thanks in advance

![image](https://user-images.githubusercontent.com/6263630/33519842-38624814-d7a7-11e7-9522-e8da5edfec42.png)

![image](https://user-images.githubusercontent.com/6263630/33519844-495fb78c-d7a7-11e7-814a-e9650c664e27.png)

**Comment by NorthstarTech** [comment]
https://github.com/ryandeba/grapesjs-html-block.

check out this plugin. It helped us to write our own block that provides a similar function but with HTML.
