### ISSUE TITLE
BUG: unable to hide rte for some particular component type

### ISSUE THREAD

**Issue by yashvi2026** [artf/grapesjs#6024]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Chrome

### Reproducible demo link

https://codepen.io/Harshsne/pen/xxoOyXO

### Describe the bug

https://github.com/GrapesJS/grapesjs/issues/6019
with reference to this,
I wanted to hide rte only for some particular type .
Example: Hide rte when component is of link type

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
https://github.com/GrapesJS/grapesjs/issues/6019#issuecomment-2267466020
Avoid creating duplicate issues, please.
