### ISSUE TITLE
conditional traits 

### ISSUE THREAD

**Issue by krunal039** [artf/grapesjs#603]
is there way to have conditional traits? if is current component is youtube video then have some traits and if video is non-youtube then shows other traits?

**Comment by ryandeba** [comment]
Hi @krunal039,

The video component seems to do this already to some extent - see [here](https://github.com/artf/grapesjs/blob/ea7dca4e5ed486658685bff832e9a5a9561e4d00/src/dom_components/model/ComponentVideo.js#L177). If you want to customize the traits further, you could probably do something like this (untested code, but copied and modified from something similar that I've done):

```
var videoType = editor.DomComponents.getType('video');

editor.DomComponents.addType('video', {
	model: videoType.model.extend({
		getYoutubeTraits() {
			return []; // replace this empty array with your desired traits
		}
	}),
	view: videoType.view
});
```
