### ISSUE TITLE
BUG: Inline event declarations like onclick event on a buttons are getting removed

### ISSUE THREAD

**Issue by dharma-glui** [artf/grapesjs#6038]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Chrome

### Reproducible demo link

https://jsfiddle.net/6bn43a05/

### Describe the bug

**How to reproduce the bug?**
1. Add a onclick event for a html tag

**What is the expected behavior?**
It should not remove the event after getting loaded in to the editor

**What is the current behavior?**
It removes the onclick event from html

If is necessary to execute some code in order to reproduce the bug, paste it here below:
```js
// no need to include extra code
```
Same issue reported here :
https://stackoverflow.com/questions/78496572/grapesjs-removes-onclick-attributes-how-to-prevent-it-to-do-it

![Screenshot (37)](https://github.com/user-attachments/assets/0b998130-f734-4d49-8fa7-d420d1010c43)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
This is intentional for security reasons, but you can disable it with the option `config.parser.optionsHtml.allowUnsafeAttr` (at your own risk): https://github.com/GrapesJS/grapesjs/blob/819bfcf44bb23d51990eba3b4330e9932df59cde/src/parser/config/config.ts#L116
