### ISSUE TITLE
trigger after removing component

### ISSUE THREAD

**Issue by AH1N1** [artf/grapesjs#604]
Guys I need to trigger some action after removing editor's components. Is there any way to do so?  Or have I to write my own trigger?

**Comment by ateshuseyin** [comment]
There is not an event related with your requirement. You can easily override `tlb-delete`command. I created a sandbox for you https://codesandbox.io/s/k2yoxjjr95. 
If you want to handle programatically removed components, I don't know how to do it. You are welcome to create a new sandbox for it.

**Comment by AH1N1** [comment]
That's exactly what I've been looking for :) Thank you!
I wrote 'after' but I should have written 'when' ;)
