### ISSUE TITLE
BUG: Cannot read properties of undefined (reading 'lastComponent')

### ISSUE THREAD

**Issue by Vampire-V** [artf/grapesjs#6040]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Version 127.0.6533.89 (Official Build) (64-bit)

### Reproducible demo link

-

### Describe the bug

Please check this.selected has a value of undefined . I used it in react and got an error exception.    

/**
     * Returns model of the selected component
     * @return {Component|null}
     * @public
     */
    EditorModel.prototype.getSelected = function () {
        return this.selected.lastComponent();
    };
    
    
![image](https://github.com/user-attachments/assets/2eafa64e-a9e7-4c15-a670-aeb70a04105e)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
Hey @Vampire-V please follow properly the bug issue template. We can't help you here without a reproducible demo.

**Comment by Aravinth-2020** [comment]
> ### GrapesJS version
> * [x]  I confirm to use the latest version of GrapesJS
> 
> ### What browser are you using?
> Version 127.0.6533.89 (Official Build) (64-bit)
> 
> ### Reproducible demo link
> 
> ### Describe the bug
> Please check this.selected has a value of undefined . I used it in react and got an error exception.
> 
> /** * Returns model of the selected component * @return {Component|null} * @public */ EditorModel.prototype.getSelected = function () { return this.selected.lastComponent(); };
> 
> ![image](https://private-user-images.githubusercontent.com/25393048/355580698-2eafa64e-a9e7-4c15-a670-aeb70a04105e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQwOTIyNzcsIm5iZiI6MTczNDA5MTk3NywicGF0aCI6Ii8yNTM5MzA0OC8zNTU1ODA2OTgtMmVhZmE2NGUtYTllNy00YzE1LWE2NzAtYWViNzBhMDQxMDVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEzVDEyMTI1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5MmU1YTVlY2QwOTk5ZGY1MWM4NDAzMGZmNzRkYmJmZjFhNDNkNDQyMWFiYzkzYzVjMjVmOTQzODY1NjJiOTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.31vzi0sHXizk5p1xF6PoWh4ZPov7j8yUZnIQz1yinC4)
> 
> ### Code of Conduct
> * [x]  I agree to follow this project's Code of Conduct

Can you please tell me, Is that issue solved? I have a same issue when i select the open layer manager.

**Comment by Aravinth-2020** [comment]
> Hey @Vampire-V please follow properly the bug issue template. We can't help you here without a reproducible demo.

Can you please share the solution for that?
I have a same issue when i select the open layer manager, this issue raises after i selecting  another page in my custom left bar panel.
