### ISSUE TITLE
How we can save HTML

### ISSUE THREAD

**Issue by Deepak813** [artf/grapesjs#605]
How we can save HTML without using editor.getHtml() and replace function.
As, when we are using this in image upload then the existing video element html are removed.

Please help us to do save image and video data dynamically using backbone or some other solution.

**Comment by ateshuseyin** [comment]
You can create your own [storage](https://github.com/artf/grapesjs/wiki/API-Storage-Manager) to handle whole data in the editor (html, css, assets etc)

HTML part only contains links of assets (image, video etc). If you want to get uploaded data you should override uploadFile method of AssetsManager

**Comment by Deepak813** [comment]
Hi @ateshuseyin,

Thanks for the message.

I don't know how to create our own storage.Please elaborate how to do that as i am in the middle of the this tasks and not able to go further.
Please help us to resolve this.

**Comment by artf** [comment]
@Deepak813 this is highly discussed argument, so just make a search in issues (eg. #597)
