### ISSUE TITLE
BUG:Issue in plugin

### ISSUE THREAD

**Issue by SAJAD-CH** [artf/grapesjs#6051]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Chrome

### Reproducible demo link

asdasd

### Describe the bug

 I am having an issue while  installing NPM plugin packages like preset-webpage, preset-newsletter , the css file is missing while installing in both when i check node module folder.I want to integrate grapejs in angularts.  Now it contains pages like index.d.ts, index.ts etc. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
@SAJAD-CH please provide a reproducible live demo (eg. via stackblitz) when you open a bug issue
