### ISSUE TITLE
How to load grapesjs by default preview

### ISSUE THREAD

**Issue by sridharK64** [artf/grapesjs#6063]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

latest

### Reproducible demo link

https://stackblitz.com/edit/grapesjs-react-custom-ui-nrqcgn?file=src%2FApp.tsx

### Describe the bug

**How to reproduce the bug?**
1. ...
2. ...

**What is the expected behavior?**
...

**What is the current behavior?**
...

If is necessary to execute some code in order to reproduce the bug, paste it here below:
```js
// your code here
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danstarns** [comment]
Hi, @sridharK64 thank you for your report, can you elaborate on your issue, please? As we only have: 

1. 'How to load grapesjs by default preview'
2. Your stack blitz

Could you tell us what you're trying to achieve?

**Comment by artf** [comment]
@sridharK64  I got what you mean but the next time try to elaborate a bit better.

To trigger the preview on load, this would be enough
```js
editor.onReady(() => {
   editor.runCommand('core:preview')
});
```
but in your example, you're using `@grapesjs/react` with full custom UI, which means you have to implement your own implementation of how to handle the preview with your react components.
