### ISSUE TITLE
BUG: Setting the text content programmatically clears it in the canvas

### ISSUE THREAD

**Issue by mannyyang** [artf/grapesjs#6064]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

v126

### Reproducible demo link

https://jsfiddle.net/r5062suy/1/

### Describe the bug

**How to reproduce the bug?**
1. Run the demo link (https://jsfiddle.net/r5062suy/1/)
2. See that I try to update the text in the div from "Hello world!!" to "test" through `editor.getWrapper().find('.test-text')[0].set('content', 'test')`.
3. However, it clears out the text instead.

**What is the expected behavior?**
It updates the text content correctly.

**What is the current behavior?**
It clears it out instead.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danstarns** [comment]
Try using the `.getEl` method on the component then setting the element directly. 

```js
const editor = grapesjs.init({
  container: '#gjs',
  fromElement: 1,
  height: '100%',
  storageManager: { type: 0 },
  plugins: ['gjs-blocks-basic']
});

setTimeout(() => {
  const component = editor.getWrapper().find('.test-text')[0]
  const el = component.getEl();
  el.textContent = "test"
}, 1000)
```

**Comment by mannyyang** [comment]
> ```js
>   const component = editor.getWrapper().find('.test-text')[0]
>   const el = component.getEl();
>   el.textContent = "test"
> ```

Problem with this is that when you export the HTML, it returns the old text.

```js
setTimeout(() => {
  const component = editor.getWrapper().find('.test-text')[0]
  const el = component.getEl();
  el.textContent = "test"

  console.log(component.toHTML())
  // <div class="test-text" id="i387">Hello World!!!</div>
}, 1000)
```

**Comment by artf** [comment]
@mannyyang where did you find the usage of `set('content', ...`? It's more like private property and you should never use it.

To update inner components programmatically use `component.components('test')`
