### ISSUE TITLE
New toolbar element

### ISSUE THREAD

**Issue by fabiano-miranda** [artf/grapesjs#607]
Hello. I'm from Brazil and I'm sorry for the bad English. 
How do I create a new button with a custom event on the toolbar relative to the selected element? Igual ao que remove o elemento selecionado.

**Comment by ShepelE** [comment]
I don't understand some words, but if you want to remove selected element, you can use SelectionManager : 
![25](https://user-images.githubusercontent.com/16486717/33655652-55ef9b52-da7c-11e7-8035-1b7555dcdee7.png)

if you need to create a new button, you can use guide https://github.com/artf/grapesjs/wiki here - create panel, then button, then command for this button...

**Comment by fabiano-miranda** [comment]
Thank you very much for responding. I want to create a new button on the toolbar when selecting an element.

**Comment by artf** [comment]
Hi Fabiano, check here please #266

**Comment by fabiano-miranda** [comment]
thank you so much
