### ISSUE TITLE
Desktop version

### ISSUE THREAD

**Issue by niutech** [artf/grapesjs#608]
Would you mind adding a desktop version for Windows, like Pingendo or Pinegrow, with opening and saving files on disk? You could use NW.js for that. Thanks!

**Comment by Areahints** [comment]
supported, as an editor with amazing potenGUI designers, it surprisingly hard to use or "instantiate"

**Comment by artf** [comment]
Currently, not on my priority list but I know that someone else was already working on it https://github.com/Immortalin/Merlot

**Comment by niutech** [comment]
Working on it? That Merlot project is a stub, just one commit 6 months ago. I am talking about a serious work.

**Comment by artf** [comment]
@niutech there are no funds for a serious work...

**Comment by niutech** [comment]
I've just made an initial version of [GrapesJS Desktop](https://github.com/niutech/grapesjs-desktop) using NW.js. Anybody would like to contribute?
