### ISSUE TITLE
BUG: Custom Component not able to visible in grapsJs/studio at first rendering

### ISSUE THREAD

**Issue by MdShadabAhamad** [artf/grapesjs#6081]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

chrome

### Reproducible demo link

https://stackblitz.com/edit/vitejs-vite-4noagg?file=src%2FApp.tsx

### Describe the bug

I am not able to see my custom component at the first time of my react application rendering , when i try to search it on the block section then its appeared and after searching it can be visible in block section.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
Use the plugins when you want to extend something at the GrapesJS API level
```js
<StudioEditor
        ref={editorRef}
        options={{
          plugins: [
            editor => addCustomComponent(editor)
          ],
          // ...
```

**Comment by MdShadabAhamad** [comment]
i also added custom style setupStyleManager but its show blank ,https://stackblitz.com/edit/vitejs-vite-4noagg?file=src%2FApp.tsx
