### ISSUE TITLE
BUG: Undo doesn't work after a Component's innerHTML is changed

### ISSUE THREAD

**Issue by leo-budgetsimple** [artf/grapesjs#6087]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Latest

### Reproducible demo link

https://jsfiddle.net/condsjm1/

### Describe the bug

**How to reproduce the bug?**
1. Change a Component's innerHTML 
2. Press CTRL + Z

**What is the expected behavior?**
To undo the content

**What is the current behavior?**
Doesn't undo the content

Description:

On the fiddle, press the button that says 'Change to Hello Planet' and then select the editor and press CTRL + Z

and the undo won't work (nor the redo), but if you change the 'Hello World' text normally it works fine.

I think I'm changing the content wrong? and if so what's the best way to change a component's content and emulate the native behaviour

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
UndoManager tracks component state changes, not its DOM.
This should work in your case `element.components('Hello Planet')`

**Comment by leo-budgetsimple** [comment]
@artf Thanks!
