### ISSUE TITLE
@artf , I have a question that , can we implement custom js in studio? means is there any embed js code functionality ?

### ISSUE THREAD

**Issue by MdShadabAhamad** [artf/grapesjs#6092]
@artf , I have a question that , can we implement custom js in studio? means is there any embed js code functionality ?

_Originally posted by @MdShadabAhamad in https://github.com/GrapesJS/grapesjs/discussions/6080#discussioncomment-10449335_

**Comment by artf** [comment]
@MdShadabAhamad please avoid opening issues from discussion, thanks

**Comment by icoco** [comment]
looks no studio source code , where you can find the studio?
