### ISSUE TITLE
Enhancement: Save form, reuse it when required

### ISSUE THREAD

**Issue by absolution54321** [artf/grapesjs#611]
#I don't know if this exists or not, is it possible to to create a form, save it and reuse it without pasting it into import screen.
Currently an import screen is present where one can paste a HTML code, which is an unnecessary task
we can provide user with the option to drag n drop previous saved forms and play with it

Basically what I thought was
1. User will create a form
2. He will save it or export
3. after export there should be a scenario where he can drag n drop that existing form, edit it maybe

Any leads?

**Comment by artf** [comment]
Hi @absolution54321 it's something you should be able to implement by yourself, make use of [Blocks API](https://github.com/artf/grapesjs/wiki/API-Block-Manager)
```js
// Just an example, on selected component you click, somewhere... 'Save element', and
const selected = editor.getSelected();
editor.BlockManager.add('new-block-uuid...', {
  label: `Saved ${selected.getName()}`,
  content: selected.toHTML(),
});
```
