### ISSUE TITLE
BUG: asDocument not working as expected

### ISSUE THREAD

**Issue by SamMousa** [artf/grapesjs#6116]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Chrome 128

### Reproducible demo link

https://jsfiddle.net/sammousa/bxgsdc12/11/

### Describe the bug

**How to reproduce the bug?**
1. Load an HTML string with a non empty `<head>`, using the option `{asDocument: true}`.
2. Export the data via `editor.getProjectData()`, see that it contains the `<head>` content
3. Load the exported data from 2 via `editor.loadProjectData()`
5. Export the data via `editor.getProjectData()`, see that it does NOT the `<head>` content

**What is the expected behavior?**
I'd expect that this should always hold, maybe with the exception for some details like autogenerated ids.

```js
const html1 = editor.getHtml();
const html2 = editor.loadProjectData(editor.getProjectData());
html1 === html2
```

**What is the current behavior?**
The head content is not loaded when using `loadProjectData()`.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kanaihyakumar** [comment]
I've made some code changes that might help you achieve the desired behavior. Please check them out here: [JSFiddle Example](https://jsfiddle.net/kanaihyakumar/b76yv2no/6/)

It seems to match what you are looking for.

**Comment by SamMousa** [comment]
Thank you, but that's not really the point. I'm fully able to make a workaround, but that does not fix the bug.

The bug is that an export via `getProjectData()` followed by an import via `loadProjectData()` should result in the same state.

Furthermore the hack you propose actually writes directly to the canvas meaning that there's no guarantee it will remain untouched. (For example there's a `styles` configuration in the editor that will inject styles to the canvas' head)

**Comment by artf** [comment]
> The bug is that an export via getProjectData() followed by an import via loadProjectData() should result in the same state.

Yeah definitely not expected, we'll look into it.

Appreciate the easily reproducible steps on the demo 👍

**Comment by SamMousa** [comment]
I'm just starting to integrate this library.. just a heads up: more issues will follow, I make them as clear as I can and am always happy to implement my proposed fixes, I do often need some direction when several solution directions exist

**Comment by artf** [comment]
Thanks @SamMousa detailed bug reports are always welcome.
If a direction is requested, we're happy to guide you 🙇‍♂️
