### ISSUE TITLE
how customizate assets modal?

### ISSUE THREAD

**Issue by nestor91sanchez** [artf/grapesjs#614]
how can add search field in assets modal?, where i can search images by keyword on a third party api and select images from results.

**Comment by artf** [comment]
Start with checking https://github.com/artf/grapesjs-plugin-filestack/blob/master/src/index.js#L50 there you will find how to customize assets modal. Once you got the result from a third party API make use of [Assets API](https://github.com/artf/grapesjs/wiki/API-Asset-Manager)
