### ISSUE TITLE
BUG: Redo of Pages not working properly

### ISSUE THREAD

**Issue by rhoenerSBS** [artf/grapesjs#6142]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Chrome v128

### Reproducible demo link

https://app.grapesjs.com/studio

### Describe the bug

After adding a Page, removing it with undo and adding back with redo, the page is not working properly. The Layer Manager does not update when selecting the page. It also does not have the content it had before removing it and does not seem to have a body at all since it's not possible to add new components to that page. I noticed this behaviour in my local developement but since it's also happening in the studio version of grapesjs I submitted the link to the studio version for reproduction of  this issue.

**How to reproduce the bug?**
1. Open the GrapesJs Studio Example
2. Add a page
3. Click Undo -> Page gets removed from list
4. Click Redo -> Page is added again
5. Click on the page that was added with redo to see behavior

**What is the expected behavior?**
The page should be added with previous content and the content should still be editable after redo.

**What is the current behavior?**
After adding the Page with Redo the page content is not editable, the layer manager does not update correctly when switching between the pages, the content of the page is lost.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
Thanks for the report @rhoenerSBS
