### ISSUE TITLE
Apply style to child classes

### ISSUE THREAD

**Issue by ajaysofto** [artf/grapesjs#615]
How we can add style to child classes of editorform?
var forminputClass = cssComposer.add([editorform, forminput]);
Above code will apply css to div that have both of these classes like .editorform.forminput 
What we have to do to define space between these class to make editorform as a parent?

**Comment by artf** [comment]
@ajaysofto GrapesJS is a class-based style editor so if you import that kind of selector you will not be able to select it in Style Manager, so I recommend to assign specific classes to your elements
