### ISSUE TITLE
BUG: CSS added via custom code persists after custom code component is removed

### ISSUE THREAD

**Issue by stpp2** [artf/grapesjs#6152]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

any

### Reproducible demo link

https://grapesjs.com/demo

### Describe the bug

**How to reproduce the bug?**
1. Add custom code component with HTML + CSS
2. Delete custom code component.

**What is the expected behavior?**
All code should be removed, including CSS

**What is the current behavior?**
custom CSS is **not** being removed, though the rest is.

[gjs.webm](https://github.com/user-attachments/assets/3fbd9a6d-ad0e-4fc6-add8-7cf31ae9293c)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mosh-tudor** [comment]
@stpp2 This is not really a bug; it's more of a feature. :)

Try using `clearStyles`:

https://github.com/GrapesJS/grapesjs/blob/d48e1e34a9fa363dcb83fdcca53a89563db17063/packages/core/src/editor/config/config.ts#L260-L272

**Comment by stpp2** [comment]
Yeah `clearStyles` is already enabled in my case, but that doesn't seem to work well in many cases.
Either way I'd expect the `Custom Code` component to be somewhat "containerized" so it's not leaving anything in the doc when removed.

**Comment by artf** [comment]
This is not related to the core and should be addressed at the [plugin](https://github.com/GrapesJS/components-custom-code) level. Please create the issue there and we'll try to figure out the right approach.
