### ISSUE TITLE
Expose spectrum color picker options

### ISSUE THREAD

**Issue by ryandeba** [artf/grapesjs#616]
Hi @artf,

I'm wanting to customize some options for the spectrum color picker (specifically the [palette](https://bgrins.github.io/spectrum/#options-showPalette)). I've searched through the code and am not seeing how this is currently possible.

This is what I'd like to do:
```
grapesjs.init({
   colorPicker: {
      showPalette: true,
      palette: [
        ['black', 'white', 'blanchedalmond'],
        ['rgb(255, 128, 0);', 'hsv 100 70 50', 'lightyellow']
      ]
    }
});
```

Is something like this already possible and I missed it? If not, would you consider merging a pull request that adds this functionality?

**Comment by artf** [comment]
> Is something like this already possible and I missed it? If not, would you consider merging a pull request that adds this functionality?

Unfortunately, not yet possible but I'll definitely accept a PR (ok for the option `colorPicker`)
The spectrum is called inside [InputColor](https://github.com/artf/grapesjs/blob/dev/src/domain_abstract/ui/InputColor.js#L70) and used then in [PropertyColorView](https://github.com/artf/grapesjs/blob/dev/src/style_manager/view/PropertyColorView.js) and [TraitColorView](https://github.com/artf/grapesjs/blob/dev/src/trait_manager/view/TraitColorView.js)

**Comment by ryandeba** [comment]
Thanks @artf! Do you have any general thoughts on how to best make this change? I've reviewed the code and am not seeing an easy way to accomplish this, and I'd like to avoid spending time going down the wrong path.

Here's a summary of what the ideas I've considered so far...any of these sound better/worse than the others?
- Add ColorPicker to the [utils object](https://github.com/artf/grapesjs/blob/dev/src/utils/index.js)
  - This would make it easy to pass the config along like this, utilizing the existing [loadModule functionality](https://github.com/artf/grapesjs/blob/049a734b5f3f50b50ef4cdaa2f13e086b55ad5fe/src/editor/model/Editor.js#L145):  `grapesjs.init({ utils: { colorPicker: { ... } } });`
  - I think this would require changing how the InputColor/PropertyColorView/TraitColorView objects reference it - they would need to go through `editor.Utils.ColorPicker` instead of simply requiring the js file dependency. None of those objects appear to currently have any reference to the `editor` object, so this doesn't seem very straightforward. 
- Move the ColorPicker object to be a top-level editor object (kind of like the rich text editor `editor.RichTextEditor`, but this would be `editor.ColorPicker`)
  - I guess the same issues exist here as with moving ColorPicker into the utils object...all referencing code would need to access this through `editor.ColorPicker` rather than requiring the js file dependency...
- Backbone/jQuery implementation
  - Modify `Backbone.$.fn.spectrum.defaults` in the [editor](https://github.com/artf/grapesjs/blob/dev/src/editor/model/Editor.js) if the `colorPicker` config was passed to `grapesjs.init`, and modify the [ColorPicker](https://github.com/artf/grapesjs/blob/dev/src/utils/ColorPicker.js) to use those defaults if they exist.
  - This solution feels very hacky to me :(

Any feedback would be greatly appreciated!

**Comment by artf** [comment]
Honestly, I was thinking about a less invasive approach
> None of those objects appear to currently have any reference to the editor object

Actually, [PropertyColorView](https://github.com/artf/grapesjs/blob/dev/src/style_manager/view/PropertyColorView.js#L14) injects`EditorModel` (which I commonly reference as `em`) as an option via `target` (probably will be best to rename it to `em`) but not in TraitColorView (easy fix, just need to pass `this.config.em`). After we have the `em` inside we can easily update `InputColor` like this
```js
colorEl.spectrum({
         //...
         palette: [],
         ...this.target.getConfig('colorPicker'), // or this.em.getConfig...
         // We need move(), change(), etc. to make the color input work properly
         // so I'd keep them out
         move(color) {...},
         //...
```

What do you think?

**Comment by ryandeba** [comment]
@artf I think your solution is must simpler than what I was thinking 👍 

I'll work on this and open a pull request shortly.
