### ISSUE TITLE
No Wrapper

### ISSUE THREAD

**Issue by michaellwatson** [artf/grapesjs#617]
Is it possible to add elements to the canvas that don't have the automatic wrapper added?

There is always a parent div added to the "content" is there anyway to have only the content added to the canvas without the wrapper?

```
editor.BlockManager.add('test',
    {
        category:'Containers', 
        label: 'Full Width',
        content: '<div>abc</div>',
    });
```
When this gets dragged to the canvas, it will become

```
<div class="generated_class">
<div>abc</div>
</div>
```
Is there anyway to keep it just 
`<div>abc</div>`

Thanks

**Comment by artf** [comment]
@michaellwatson blocks shouldn't be wrapped (just tested it in the demo), indeed if you drop an image block you just get an `img`
