### ISSUE TITLE
BUG: Need dark theme support in editor

### ISSUE THREAD

**Issue by yashvi2026** [artf/grapesjs#6172]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Chrome

### Reproducible demo link

---

### Describe the bug

It would be great if you add theme switching in the editor, allowing me to toggle between dark and light themes based on my preference.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
Please use the discussions instead of bug issues
