### ISSUE TITLE
BUG: Trait's `setValue()` method not called when value changes

### ISSUE THREAD

**Issue by padcom** [artf/grapesjs#6180]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Chrome latest

### Reproducible demo link

https://codesandbox.io/p/sandbox/withered-rgb-xmw8gk

### Describe the bug

**How to reproduce the bug?**
1. Open code sandbox
2. Select "body" (type: 'wrapper') - observe alert about getting value from custom source (trait.getValue() is called)
3. Try to change the value (trait: custom, the only one there) - observe the "setValue()" is not called as no alert is shown

**What is the expected behavior?**
An alert "Setting global value to " + value is shown

**What is the current behavior?**
Alert not shown, the `trait.setValue()` method is not called.

If is necessary to execute some code in order to reproduce the bug, paste it here below:
```js
// your code here
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by padcom** [comment]
From what I can see the `Trait.setValue()` is not called when the value comes from an input. Instead the `setTargetValue()` is called which doesn't check if the `setValue()` method of the trait definition is there. Also, the `Trait.setValue()` checks for the `setValue` key in attributes whereas `Trait.getValue()` gets its custom getter via `this.get('getValue')` (Trait.ts:303)

**Comment by padcom** [comment]
I tried following [this](https://github.com/GrapesJS/grapesjs/discussions/5793) discussion to get it working but as you can see in the sandbox it just doesn't work.

**Comment by mohamedsalem401** [comment]
Hey @padcom ,

I think the value is updating (because the HTML DOM attributes are updated), however, it seems like there might be an issue with the value in the input not being updated. Also, it's not just related to the wrapper component but rather all types being added.

I'll look into it and let you know if it's a bug or something is wrong with the code snippit

**Comment by padcom** [comment]
> Also, it's not just related to the wrapper component but rather all types being added.

That is correct. It's for all component types and for all trait types.

**Comment by padcom** [comment]
That's great news! Thank you!!!

**Comment by padcom** [comment]
@artf Do you have a release date in mind when this fix could be available?

**Comment by artf** [comment]
@padcom https://github.com/GrapesJS/grapesjs/releases/tag/v0.22.1

**Comment by padcom** [comment]
Thank you! I verified and it is working as expected!
