### ISSUE TITLE
How to show Block manager

### ISSUE THREAD

**Issue by narraressan** [artf/grapesjs#62]
Hi, I am new to the world of coding so i am a bit lost here...

I have this setup for the editor 

var editor = grapesjs.init({
			container : "#gjs",
			components: '<div class="txt-red">Hello world!</div>',
			style: '.txt-red{color: blue}',
			panels: {
				defaults: [{
					id: "commands",
					buttons : [{}]
				}, {
					id: "options",
					buttons : [{
						id: "save",
						className: "fa fa-save",
						attributes: { title: "Save" },
						command: "saveTemplate"
					}, {
						id: "home",
						className: "fa fa-home",
						attributes: { title: "Home" }
					}],
				}, {
					id: 'views',
					buttons: [{
						id: 'open-style-manager',
						className: 'fa fa-paint-brush',
						command: 'open-sm',
						active: true
					}, {
						id: 'open-block-manager',
						className: 'fa fa-edit'
					}]
				}]
			},
			commands: {
				defaults: [{
					id: "saveTemplate",
					run: function(editor, senderBtn){
						alert("Save Template!");

						senderBtn.set("active", false);
					},
					stop: function(editor, senderBtn){},
				}]
			},
			styleManager : {
				sectors: [{
					name: 'Position',
					open: false,
					buildProps: ['float', 'border', 'margin', 'padding', 'width', 'height']
				}, {
					name: 'Background',
					open: false,
					buildProps: ['background-image', 'background-color']
				}, {
					name: 'Text',
					open: false,
					buildProps: ['color', 'line-height', 'letter-spacing', 'font-size', 'font-weight', 'font-family']
				}]
			}
		});

and I wanted to add a new block.. so I used this,

`var blockManager = editor.BlockManager;
		blockManager.add('open-block-manager', {
			label: 'Simple block',
			content: '<div class="my-block">This string will be parsed and turned into a Component</div>',
		});`

but I can't see the block I added, I am not sure if the window in for the blocks is enabled in my setting and I can't find how to enable it. Also, the devices on the top left, how do I disable that? 

Thank you.

**Comment by artf** [comment]
For the default devices you can just hide it with CSS or use this option
```js
grapesjs.init({
...
showDevices: false,
})
```
About blocks, you just forgot to add the command for the button :)
```js
...
buttons: [{
  id: 'open-style-manager',
  className: 'fa fa-paint-brush',
  command: 'open-sm',
  active: true
}, {
  id: 'open-block-manager',
  className: 'fa fa-edit',
  command: 'open-blocks' // <-- here
}]
```
