### ISSUE TITLE
BUG: Javascript CDN not working on grapejs canvas

### ISSUE THREAD

**Issue by klipto-inc** [artf/grapesjs#6202]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

129

### Reproducible demo link

https://grapesjs.com/demo

### Describe the bug

const newEditor = grapesjs.init({
      fromElement: true, // Allow components from HTML
      container: "#editor",
      canvas: {
        scripts: [
          "https://cdn.jsdelivr.net/npm/preline@2.5.0/dist/preline.min.js",
        ],
      },
      height: "100vh",
      plugins: [
        gjsPresetWebpage,
        GjsBlockBasic,
        gjsForms,
        pluginTooltip,
        customCodePlugin,
        pluginImageEditor,
        grapesjsClick,
        pluginPreset,
        pluginStyleBg,
        styleFilter,
        pluginStyleFlex,
        pluginStyleGradient,
        pluginnavbar,
        // scriptEditor,
        // pluginEasyStyle,
      ],
      pluginsOpts: {
        gjsPresetWebpage: {},
        grapesjsClick: true,
      },
      pageManager: {
        pages: project.pages, //
      },
      storageManager: {
        type: "", // Set type to empty to disable storage
        autosave: true, // Disable autosave
        autoload: true, // Disable autoload
        stepsBeforeSave: 1,
      },
    });

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
@klipto-inc please create the bug report with a proper reproducible live demo
