### ISSUE TITLE
Image editor is not closed.

### ISSUE THREAD

**Issue by HarshOB** [artf/grapesjs#622]
When I choose image component and don't choose an image for the first time then if I open image editor then It won't close after clicking on a close button.

**Comment by artf** [comment]
@HarshOB I can't reproduce it (with the current demo). Are you able to provide a live demo?

**Comment by HarshOB** [comment]
I'll provide a link to a live demo.

**Comment by artf** [comment]
Ok I close this for now but will reopen once you provide a demo
