### ISSUE TITLE
BUG: showOffsets bug when iframe body has zoom

### ISSUE THREAD

**Issue by Frubl** [artf/grapesjs#6248]
### GrapesJS version

- [x] I confirm to use the latest version of GrapesJS

### What browser are you using?

Chrome

### Reproducible demo link

https://jsfiddle.net/a2hbxg0y/1/

### Describe the bug

**How to reproduce the bug?**
1. Open dev tools and write element style for iframe body - zoom: n; 

**What is the current behavior?**
When hovering over an element, the blue border works correctly, which is not the case with offsets. They are the same size as they would be at zoom: 1;

p.s. i can't share the link with fully reproduced demo because changes with css needed to be done inside canvas.

p.s.s.
There may already be a proper way to reduce content, but I only found zoom for the whole canvas. I would like to make zoom smaller on one of the device types

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
You shouldn't edit the zoom of the iframe, use the [native API](https://grapesjs.com/docs/api/canvas.html#setzoom)
