### ISSUE TITLE
BUG: Intialized custom color picker

### ISSUE THREAD

**Issue by yashvi2026** [artf/grapesjs#6249]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Chrome

### Reproducible demo link

---

### Describe the bug

editor.getModel().initBaseColorPicker(DomElement, { /* spectrum options */ });

after initailization when the palete opens i want to set a color to it ? @artf 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by NeonLexie** [comment]
This looks interesting. I wouldn't mind taking a crack at it.

**Comment by yashvi2026** [comment]
```
I figured it out.



var configEl=editor.getModel().initBaseColorPicker(DomElement, { /* spectrum options */ });
 configEl.spectrum("set", "your color");

```
