### ISSUE TITLE
Placing non-editable HTML around wrapper

### ISSUE THREAD

**Issue by z1lk** [artf/grapesjs#626]
My CMS works like this: sites can have one theme and many templates under that theme. Themes are rendered on every page, and templates are rendered only on specific pages. I have successfully integrated GrapesJS with my existing template editor, but I have a question: is there any way to render a theme around a template in Grapes? That is, is there any way to insert non-editable HTML around the editable HTML? If I place HTML in the canvas between the `body` and the `#wrapper`, I seem to get the result I want.

Is there an existing API for achieving this, and if not, is this desirable functionality or am I better off using JavaScript to inject my theme HTML into the editor? 

P.S. First post here. Great work on this software @artf . I am excited to see how Grapes can help me and how I can contribute to this project.

**Comment by z1lk** [comment]
After looking at the source for the Editor, I think that I need to use the [`el` config option](https://github.com/artf/grapesjs/blob/dev/src/editor/config/config.js#L81), but doing so has no effect. I can't get any further without digging in the source myself. If you could, please shed some light on the state of this config parameter. Thanks!

**Comment by z1lk** [comment]
I've fiddled with the code and made a small patch that fits my needs. A config option `surround` lets you specify an ID, which represents an element in the container. This DOM subtree is plucked out in the main initializer, stored in the Editor config, and picked up by the Canvas. The Canvas then handles rendering of the surround around the wrapper. I am interested to know if anyone else has needs like this and if this seems like a good solution.

Again, if the use case isn't clear: suppose I am using Bootstrap, and I have a Theme with a container, navbar, footer, etc. I then have a page Template which I am editing with Grapes. I want to see the Template inside its Theme's HTML, but I should be able to edit only the Template, and similarly `Editor.getHtml()` should return only the Theme HTML.

**Comment by artf** [comment]
Greate @z1lk I think even something like this will work
```js
const canvas = editor.Canvas;
const surround = document.createElement('div');
surround.innerHTML = '<div>Some text</div>';
canvas.getBody().appendChild(surround);
surround.appendChild(canvas.getWrapperEl());
```
I close this as you've solved your case

**Comment by z1lk** [comment]
I used a solution similar to yours so I don't have to maintain changes to the Grapes source. Sometimes the position of the component "tools" are out of place, as if their vertical offset is computed relative to the body and not the wrapper. I can't reliably reproduce it though. Thanks for your help @artf

**Comment by tristanMatthias** [comment]
@artf Thanks for this code! Very useful.
On my initial test for this I get:
```
Uncaught TypeError: Cannot read property '_cash1550657156611' of undefined
```

Running GrapesJS v: 0.14.52
Chrome: 72.0.3626.109 (Official Build) (64-bit)
Mojave OSX

Any idea on how to move forward?

**Comment by artf** [comment]
@tristanMatthias I think you might want to check this https://jsfiddle.net/5vcc3en6/
