### ISSUE TITLE
default feature just 1 ?

### ISSUE THREAD

**Issue by hatchwald** [artf/grapesjs#627]
![screenshot-2017-12-13 grapesjs](https://user-images.githubusercontent.com/32924664/33921786-c26258a2-dff8-11e7-9fae-65e45ff7fc1a.png)

i am sorry , maybe i am forget to read detail , but default feature just 1 (just block) ?

**Comment by hatchwald** [comment]
I was try to find code that feature but , i am still haven't find it yet

**Comment by hoainam12k** [comment]
You can use basic blocks here: https://github.com/artf/grapesjs-blocks-basic (and other from README file)
