### ISSUE TITLE
BUG: Layer Manager does not allow reordering on same level. only nesting is allowed on top level(right under body) older versions (e.g: 0.21.8

### ISSUE THREAD

**Issue by sumasal** [artf/grapesjs#6281]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

latest chrome, firefox, edge

### Reproducible demo link

https://grapesjs.com/demo

### Describe the bug

**How to reproduce the bug?**
1. drag a acomponent in layer manager and try to put it between other items under body
2. not allowed. nesting is allowed

**What is the expected behavior?**
... both nesting and reordering shall be enabled

**What is the current behavior?**
...only nesting enabled on top level

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sumasal** [comment]
issue title is somehow clipped. what i meant is it seems to work on older versions such as 0.21.8 and below

**Comment by artf** [comment]
Will be fixed in the next release.
Thanks @sumasal for the report and @mohamedsalem401 for the fix 🙇‍♂️
