### ISSUE TITLE
BUG: Data Sources are ignored when loaded from project data

### ISSUE THREAD

**Issue by svex99** [artf/grapesjs#6290]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Firefix v132.0

### Reproducible demo link

https://jsfiddle.net/skdegqun/4/

### Describe the bug

**How to reproduce the bug?**
1. Running the fiddle can be appreciated on the logs that the data sources passed on editor initialization were not loaded.

**What is the expected behavior?**
Load the data sources from the project data into the editor data sources manager (`editor.DataSources`)

**What is the current behavior?**
When the editor loads the project data, the data sources are not being loaded, and instead the data sources list is empty.

This issue happens when passed the project data on editor initialization, but also when loading the project data from a remote storage (a bit harder to reproduce in the fiddle, but hopefully fixing the first case fixes this). Loading the data from a remote storage was how I initially detected the bug.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
You need to wait until the editor is ready.
```js
editor.onReady(() => {
 console.log('Total of data sources should be 1:', editor.DataSources.getAll().length)
 console.log('test-source should exist:', editor.DataSources.get("test-source"));
});
```
