### ISSUE TITLE
BUG: Custom react components gets wrapped inside a div

### ISSUE THREAD

**Issue by maneeshp97** [artf/grapesjs#6296]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Arc v1.61.1

### Reproducible demo link

https://codesandbox.io/s/grapesjs-react-components-n6sff

### Describe the bug

@artf  First of all thank you for this amazing library. I was trying to create custom react components within grapesjs and came across this sandbox link from one of the previously reported issues related to react integration. 
[https://codesandbox.io/s/grapesjs-react-components-n6sff]

I was able to make custom react components work after referring the sandbox, however there is one problem that still remains. Whenever a custom react component is dragged in to the canvas the component equivalent code gets wrapped inside a `div` which has all the gjs data attributes can class names. This extra wrapper div that gets added is kind of a roadblock towards my goal of building a custom dnd UI builder as the final output is going to have lot of extra divs in it. Is there any way to avoid this behaviour of a default `div` getting added as a wrapper ? Checked the documentation and couldn't find any option to achieve the same. Any help is appreciated. 

<img width="641" alt="image" src="https://github.com/user-attachments/assets/9e60ed6b-398d-4851-91b4-06c54003483f">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
Yeah, that's expected from the demo perspective. 
You can play around with the code and find your solution but I'm closing this as it's not a core bug.
