### ISSUE TITLE
(question) Is it possible to set categories dinamically? 

### ISSUE THREAD

**Issue by kkuksin** [artf/grapesjs#630]
Thanks for your component, I like it very much.

I have some dinamic blocks (I have tabs and when I change tab, I add group of blocks and remove the other group of blocks. The issue is that when I remove old blocks, I can't remove their categories.
If I remove their categories with js ( document.querySelectorAll('.gjs-block-category') and then use .remove() for each of them ), that categories don't appear next time when I open the old tab.

Is there a way to change categories dinamically when I switch tabs and change blocks in BlockManager?

**Comment by artf** [comment]
@kkuksin you don't need to remove blocks/categories, we discussed about blocks and tabs here  #499
