### ISSUE TITLE
BUG: sorter.setDragHelper is not a function on block drag

### ISSUE THREAD

**Issue by badiuciprian** [artf/grapesjs#6324]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

131.0.6778.86

### Reproducible demo link

https://jsfiddle.net/badiuciprian/qe28obhr/1/

### Describe the bug

**How to reproduce the bug?**
1. try dragging any block to the canvas

**What is the expected behavior?**
The component is rendered to the canvas

**What is the current behavior?**
Nothing happends, in the browser console an error is shown:

BlockView.ts:103 Uncaught TypeError: a.setDragHelper is not a function
    at o.startDrag (BlockView.ts:103:12)
    at HTMLDivElement.t (cash-dom.ts:765:36)

On my real app I get the error "sorter.setDragHelper is not a function" but i guess is the same issue.
I can confirm that this is not happening on version 0.21.13
https://jsfiddle.net/badiuciprian/0ngb48y6/4/

 i see there are some changes on the sorter in the 0.22.1 release
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
@mohamedsalem401 can you check this one, please?

**Comment by mohamedsalem401** [comment]
I managed to reproduce it. It's only happening on `nativeDnD: false`. Probably this makes the block view use the API of the old sorter. I will try to push a fix for this.

**Comment by badiuciprian** [comment]
Thanks for taking care of this. I will watch for the update.
