### ISSUE TITLE
How can I pass content with script?

### ISSUE THREAD

**Issue by HarshOB** [artf/grapesjs#634]
I made custom component like this way and used script as well

```js
bm.add('test-block', {

    label: 'Test block',
    attributes: {
        class: 'fa fa-text'
    },
    content: {
        script: "console.log('the element', this)",
        content: "<h1>hello 123</h1>",
        // Add some style just to make the component visible
        style: {
            width: '100px',
            height: '100px',
            'background-color': 'red',
        }
    }
});
```

then script is working fine but I am not able to select component. Is there any other way to write content with script?

**Comment by artf** [comment]
change this
`components: "<h1>hello 123</h1>",`

**Comment by HarshOB** [comment]
I didn't get traits if I use script while creating a custom component. Is there any problem with traits?

**Comment by artf** [comment]
well, there are no traits inside your block...
If you're trying instead to use a custom component you have to set the `type`
```js
content: {
        type: 'your-component-type',
        script: "console.log('the element', this)",
        content: "<h1>hello 123</h1>",
```
