### ISSUE TITLE
BUG: It's possible to drag and drop literally anything inside grapesjs canvas

### ISSUE THREAD

**Issue by Frubl** [artf/grapesjs#6348]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Chrome

### Reproducible demo link

https://grapesjs.com/demo.html

### Describe the bug

**How to reproduce the bug?**
1. Try select for example whole sidebar tools/text/everything
2. Grab and drop it on canvas

**What is the expected behavior?**
Probably copy paste just text/sanitized html or it's possible to drag and drop only elements i made to be droppable

**What is the current behavior?**
I can drag and drop literally anything inside canvas.
![Screenshot_14](https://github.com/user-attachments/assets/11627411-14e5-4fda-a202-c6921cf64047)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
You can take control over what is dropped inside the canvas via `canvas:dragdata` event
https://jsfiddle.net/artur_arseniev/87rcb24n/
