### ISSUE TITLE
is there any way to reload grapes editor explicitly? 

### ISSUE THREAD

**Issue by HarshOB** [artf/grapesjs#635]
I want to reload grapes editor to get specific changes, is there any method to reload grapes editor?

**Comment by artf** [comment]
> specific changes
what kind of changes?

**Comment by HarshOB** [comment]
like I pass codes explicitly to grapes. and I got my HTML and CSS while clicking on view code button on the header of grapes editor. but it wasn't shown to the editor. Once I refresh the page or reopen the same page I got the structure in the editor as well.

**Comment by artf** [comment]
@HarshOB I didn't get exactly what do you mean with `I pass codes explicitly to grapes` but if you use correctly the [Editor API](https://github.com/artf/grapesjs/wiki/API-Editor) you should see the canvas update, eg.
```js
editor.setComponents('<div class="cls">New component</div><style>...</style>');
```
