### ISSUE TITLE
Using multiple plugins in the project

### ISSUE THREAD

**Issue by frank-tenzing** [artf/grapesjs#638]
Hi,

I'm using the preset news-letter repo for investigating the Grapes.Js, how can I create multiple and use multiple plugins within the project? Cheers

**Comment by artf** [comment]
@frank-tenzing just pass them in `plugins`
```js
grapesjs.init({
      ...
      plugins: ['plugin1', 'plugin2', ...],
      // options
      pluginsOpts: {
        'plugin1': {...},
        'plugin2': {...},
        ...
      }
  });
```
