### ISSUE TITLE
Problem with undo button and CTRL+Z

### ISSUE THREAD

**Issue by cloudseasail** [artf/grapesjs#64]
tried the demo, looks strange behavior between undo button and CTRL+Z.
I am using latest Chrome in Win10/Win7.

1. Test1: remove some text char in the middle of a text
   undo button didnot work.
   CTRL+Z didnot work.
2. Test2:  remove a box using "BackSpace" or "Delete" key
   undo button works good.
   CTRL+Z didnot work.

**Comment by artf** [comment]
so basically, CTRL+Z never works for you?
In test1, when you try to undo, are you still focused on the text component?

**Comment by cloudseasail** [comment]
Hi, add more comments:
Test1.1: remove some text when still focosed on the text component:
undo button didnot work
CTRL+Z works,

Test2.1: remove a box using the "delete icon"
undo button works
CTRL+Z works

**Comment by artf** [comment]
thanks @cloudseasail I'll investigate more about this

**Comment by vankyy26** [comment]
I've seen some issues with it too. After dragging some text blocks and editing the text when I press ctrl+z nothing happened, then I used the undo button and half of the blocks disappeared. Then I pressed the Redo button and they were back but the text was missing. Works even stranger with imported HTML. I've added custom email template inside, did some corrections and when I used the undo then redo the editor wasn't able to redo the last change - some content was lost. I'm using the newsletter preset. Plus there is another issue related to it. As it is newsletter the whole styling should be inlined but still when I call getHtml() I receive HTML with class attributes. My workaround was to get the CSS and use PreMailer to inline the styles programmatically.

**Comment by artf** [comment]
thanks @vankyy26 for your feedback, unfortunately, I didn't have time check it. There is definitely something to do with the keymaster, undo manager and content-editable elements. About the newsletter, check [here](https://github.com/artf/grapesjs-preset-newsletter/issues/4)

**Comment by artf** [comment]
v0.10.2 should fix this, would be great to hear some feedback from you guys
