### ISSUE TITLE
Media Query

### ISSUE THREAD

**Issue by ajaysofto** [artf/grapesjs#641]
Is there any way to apply css on specific width like (max-width:767px) so that we can make template responsive???

**Comment by hoainam12k** [comment]
Yes, just choose Device from top left 
![device](https://user-images.githubusercontent.com/167746/33984218-6c93aec0-e0e9-11e7-8065-af4306d6a3fa.png) and change the style.

You can add custom breakpoint too, check [API-Device-Manager](https://github.com/artf/grapesjs/wiki/API-Device-Manager) page.

**Comment by ajaysofto** [comment]
Ok thanks for the message
