### ISSUE TITLE
Can't set background color to black

### ISSUE THREAD

**Issue by hoainam12k** [artf/grapesjs#642]
![bgcolor](https://user-images.githubusercontent.com/167746/33984299-aad06ec6-e0e9-11e7-8ae5-537ea33ebfa5.gif)

I can't set background color to black with spectrum color picker. Only work if I type hex value.

Thank you for great framework!

**Comment by artf** [comment]
O.o weird...
I tried this and everything seems ok
https://jsfiddle.net/3bprucnv/2/

**Comment by hoainam12k** [comment]
You must drag new block (text for example) and change background color. It does not happen with blocks already there when you load the page.
Same problem on your demo and code from Github but It's ok on your jsfiddle link (I tried to add new block to jsfiddle and it work well)

**Comment by alemenciones** [comment]
@hoainam12k I have run into the same problem, did you find fix?

**Comment by hoainam12k** [comment]
no, I did not
