### ISSUE TITLE
How hide video block ?

### ISSUE THREAD

**Issue by tranleanhthe** [artf/grapesjs#643]
Hi, 
I'm using [Basic Extensions](https://github.com/artf/grapesjs-blocks-basic) Extensions in Grapesjs.
I want hide "Video Block" in this Extensions.
How I can do it ?
Thanks.

**Comment by hoainam12k** [comment]
1. Open src/blocks.js. Remove line 95 -> 109 (line 95 start with `if (blocks.indexOf('video') >= 0) {`)
2. Open src/index.js, line 7: remove `'video', `

Rebuild package. I guess it will work!

**Comment by artf** [comment]
Actually there is an option for the purpose
```js
var editor = grapesjs.init({
     ...
      container : '#gjs',
      plugins: ['gjs-blocks-basic'],
      pluginsOpts: {
        'gjs-blocks-basic': {
          // Which blocks to add, just omit 'video'
          blocks: ['column1', 'column2', 'column3', 'column3-7', 'text', 'link', 'image', 'map']
        }
      }
  });
```

**Comment by tranleanhthe** [comment]
Thanks you @artf
