### ISSUE TITLE
Prefix .btn class from Buttons in editor with "gjs-"

### ISSUE THREAD

**Issue by luigledr** [artf/grapesjs#645]
.btn is commonly used in Bootstrap and in many themes or templates. The eye buttons of Layer manager, appear wrong because of .btn class name used, as we can see in this screenshot:

<img width="387" alt="screen shot 2017-12-14 at 19 46 25" src="https://user-images.githubusercontent.com/1320235/34016036-8b91bc18-e107-11e7-8545-c2abd4b8e071.png">

**Comment by artf** [comment]
Prefix added, will be available in the next release
