### ISSUE TITLE
Images dropped onto image picker get uploaded twice

### ISSUE THREAD

**Issue by tomichal** [artf/grapesjs#646]
Set the asset manager with the `dropzone` option set to `true` (which is `true` by default), something like that:
```
grapesjs.init({
  ...
  assetManager: {
     dropzone: true
     assets: <list of assets>,
     upload: <upload url>,
     autoAdd: true
  },
})
```
then drop an image onto the dropzone within the asset manager modal (from the 'gjs-blocks-basic' plugin), then the image gets uploaded to the backend twice.

I think this is because the `dropzone` option turns on uploading images by dropping them onto the editor canvas, so when you drop it onto the asset manager dropzone the event gets passed through to editor canvas from the asset manager dropzone (or vice-versa), and so there are two upload triggering events happening, where there should only be one.

**Comment by artf** [comment]
@tomichal correct, but `dropzone` was disabled by default in https://github.com/artf/grapesjs/releases/tag/v0.12.50  we've discussed that here #507
