### ISSUE TITLE
Custom traits value is not set in Code

### ISSUE THREAD

**Issue by HarshOB** [artf/grapesjs#647]
Hello,

Here I used textbox trailt and whatever I write in input box I got the text in Code Viewer.  As you can see `progress= 80`
![screenshotfrom2017-12-1512-31-55_123](https://user-images.githubusercontent.com/28950214/34031006-72d88b46-e195-11e7-923c-365e6c1d2244.jpg)

But when I create Custom traits and select value from dropdown then I didn't get any value in my Code(HTML).

![screenshotfrom2017-12-1512-32-47_123](https://user-images.githubusercontent.com/28950214/34030984-545afcda-e195-11e7-826e-2299a112a48c.jpg)

**Comment by artf** [comment]
@HarshOB show how you create the custom trait

**Comment by HarshOB** [comment]
Here is the code:

`editor.TraitManager.addType('customConent1', {
  getInputEl: function () {
    if (!this.inputEl) {
      var input = document.createElement('select');
      input.setAttribute("id", "Div1");
      input.setAttribute("name", "Div1");
      input.setAttribute("style", "background:#363636");
      $.each(partialOptions, function (key, value) { //partialOptions is an array
        var group = $('<optgroup label="' + key + '" />');
        $.each(value, function () {
            $('<option />').html(this.name).appendTo(group);
        });
        group.appendTo(input);
      });
      input.value = this.target.get('customConent1');
      this.inputEl = input;
    }
    return this.inputEl;
  },
});`

**Comment by artf** [comment]
@HarshOB try to see if the change actually triggers
```js
editor.TraitManager.addType('customConent1', {
  	events:{
    	'change': 'onChange'
 	},

	onChange() {
		console.log('changed');
    	this.model.set('value', this.getInputEl().value);
 	},

  getInputEl: function () {
```

**Comment by HarshOB** [comment]
No, I didn't get any changes.

**Comment by artf** [comment]
I'm not able to reproduce any issue with the current release. In case the issue still persists please provide a live demo
