### ISSUE TITLE
How to get a clean css generated

### ISSUE THREAD

**Issue by blackbirdzzz** [artf/grapesjs#649]
Hi, 

Im looking to correct my css when i open my export editor i got some useless css you can see it in this picture : 

https://www.noelshack.com/2017-50-5-1513332047-screenshot-at-dec-15-11-00-34.png
https://www.noelshack.com/2017-50-5-1513332047-screenshot-at-dec-15-11-00-03.png
https://www.noelshack.com/2017-50-5-1513332047-screenshot-at-dec-15-10-59-52.png

I don't know why there is all of those useless css generated :x if you can help me that will be really great

Great works again ! And thanks  @artf

**Comment by artf** [comment]
@blackbirdzzz we already discussed it here #307
