### ISSUE TITLE
Help Wanted : On Trait update

### ISSUE THREAD

**Issue by vishal5033** [artf/grapesjs#650]
Hello,

I have applied a href trait on image tag. Can you please tell me which event fires when href trait is changed for that.

Thanks,

**Comment by ryandeba** [comment]
Hi @vishal5033,

The [component:update](https://github.com/artf/grapesjs/wiki/API-Editor#components) event should get triggered when a trait changes, but it's also going to fire when _anything_ changes. You could check for the specific trait (href) by inspecting the `changed` property of the component object that's passed to the callback. Maybe something like this:

```
editor.on("component:update", function(component) {
  if (component.changed && component.changed.attributes && component.changed.attributes.href) {
    console.log("href changed!", component);
  };
})
```
