### ISSUE TITLE
defautl class on block

### ISSUE THREAD

**Issue by Gerald-AuZ** [artf/grapesjs#653]
I'm trying to add a custom block
![1](https://user-images.githubusercontent.com/7727225/34062244-312b4adc-e1b1-11e7-9787-824336161e3f.JPG)

and work fine, except that the styles attributes are set to a default class, for example
![2](https://user-images.githubusercontent.com/7727225/34062261-44252cb6-e1b1-11e7-8acf-fc0cd86c0f92.JPG)

i want those css attributes be set to the class i'm setting in the classes attribute ('header-banner')
how can i do that?

**Comment by juanj** [comment]
To achieve this, you need to add the style separated from the block and set the classes to the block.
Look for example how this is done in the basic blocks plugin:
https://github.com/artf/grapesjs-blocks-basic/blob/master/src/index.js#L29

**Comment by artf** [comment]
You can also do this
```js
content: `
	<div class="header-banner">...</div>
	<style>
		.header-banner {
			...
		}
	</style>
`
```
