### ISSUE TITLE
Bootstrap blocks plugin

### ISSUE THREAD

**Issue by z1lk** [artf/grapesjs#655]
It was mentioned in the Roadmap (#74). Has anyone started on this? I could benefit a lot from such a plugin, so I'd be willing be contribute.

**Comment by artf** [comment]
> Has anyone started on this?

From what I know none

> I'd be willing be contribute
It'd be awesome

**Comment by z1lk** [comment]
Yeah, since it seems no one has started the project, I did: https://github.com/z1lk/grapesjs-blocks-bootstrap4.

I'm not a super-experienced JS developer so any comments or help is welcome.

Thanks for the sick boilerplate @artf

**Comment by artf** [comment]
Well done @z1lk let me know when you've done, I'd be glad to put on README
