### ISSUE TITLE
Add and remove classes programmatically

### ISSUE THREAD

**Issue by michaellwatson** [artf/grapesjs#656]
I want to add and remove classes to a selected element, adding classes is working well, but removing them is not

```
var componentModel = editor.getSelected();
componentModel.addClass('form-color');
```

I want to be able to do 

`componentModel.removeClass('form-color');`

But its throwing an error.

I'd be grateful if someone could share the correct syntax

**Comment by juanj** [comment]
Looking at
https://github.com/artf/grapesjs/blob/dev/src/dom_components/model/Component.js#L276

I would say `removeClass` is not implemented.
If you know the other classes I think you can do `setClass` with an array that don't have the class you want to remove

**Comment by michaellwatson** [comment]
That worked great, thanks for your help :)

**Comment by artf** [comment]
I'll add `removeClass` in the next release

**Comment by michaellwatson** [comment]
I think that would be cool 👍
