### ISSUE TITLE
Navbar changes

### ISSUE THREAD

**Issue by Deepak813** [artf/grapesjs#658]
Please let us know what changes has been done in Navbar plugin in grapes.min.js file when mobile view is clicked as we are using older library but Navbar plugin is not working.

Menu view is not clicked during mobile view due to what menus are not displayed.

**Comment by artf** [comment]
@Deepak813 why you don't update to the latest version?

**Comment by Deepak813** [comment]
Hi @artf,

Thanks for the message.

Actually, we have certain customisation in grapes.min.js file due to which we are not in that position to update to the latest version.so please provide solution for changes done in Navbar plugin in grapes.min.js.

Look forward for the prompt reply.

**Comment by artf** [comment]
Currently, each new release ends the support of the previous one, so in your case, you have to figure it out by yourself what is changed.
I highly recommend to update to the latest version and create always plugins for any customization.

**Comment by Deepak813** [comment]
Hi @artf,

Still we are not able to get the navbar changes in grapes.min.js file.please provide this information from your development team as we are stuck in the middle of tasks and not able to continue further.

Look forward for positive response.
