### ISSUE TITLE
Custom button Save in Extensions GrapesJS Aviary

### ISSUE THREAD

**Issue by tranleanhthe** [artf/grapesjs#659]
Hi, Does way to custom Save button in  Extensions GrapesJS Aviary ?
[https://github.com/artf/grapesjs/wiki](url)
![image](https://user-images.githubusercontent.com/13422024/34200173-b3b380d8-e5a2-11e7-9f57-f5d63352378f.png)

**Comment by artf** [comment]
Hi @tranleanhthe it's up to Aviary changing its UI
https://www.adobe.io/apis/creativecloud/creativesdk/docs/websdk.html
