### ISSUE TITLE
How to load external css file on editor

### ISSUE THREAD

**Issue by narraressan** [artf/grapesjs#66]
Hi. Thank you for solving my problems on the editor this past few days,

But while I am finalizing my simple work, I decided to use skeleton css, but I can't figure out how to load css file on the editor? (inside the iframe) is it possible?

**Comment by narraressan** [comment]
Well, I think I found a work around, I am not sure if it works 100% 

I added <link rel="stylesheet" href="css/bhs-skeleton.css"> to editor using setComponent...

**Comment by allmonday** [comment]
Maybe you can append it in head of iframe.
```js
var iframe = editor.Canvas.getFrameEl();
iframe.contentDocument.head.appendChild(/* your link tag here */);
```

**Comment by artf** [comment]
Actually, [setComponents](https://github.com/artf/grapesjs/wiki/API-Editor#setcomponents) is the way to go. The problem is that it overwrites the whole template. I think I'll add `addComponents` on the next release but it'll be basically the same as:
```js
editor.getComponents().add('<link rel="stylesheet" href="...">');
```
@allmonday your snippet actually will add the link tag but the problem it won't update the template state, so when you'll call `editor.getHtml()` you won't see it inside the code.

**Comment by prtjack** [comment]
hey! @artf 
How can i save an existing template with its own external CSS properties? I tried the both options: 
1. By placing entire HTML and CSS under the <div id="gjs"></div>.
2. By using editor.setComponents() i can achieve my purpose but its very complicated to minify the whole CSS and place under editor.setStyle().

So what is the best option to export  an existing template with it's CSS.

**Comment by artf** [comment]
Hi @prtjack can you elaborate why the 1st option is not working? Can you post some code?

**Comment by prtjack** [comment]
Hey! @artf 
Sorry for this  extremely late reply. I wanted to load my existing templates dynamically. So, what is the best workaround for me?

**Comment by likhamahudda** [comment]
@octavebenil 
Thanks very much its working fine.
canvas: {
scripts: ['https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js'],
styles: ['https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css']
}

**Comment by gitwithsarthak** [comment]
> <img alt="@likhamahudda" width="40" height="40" src="https://avatars.githubusercontent.com/u/23294648?s=88&amp;u=ee4fb6cff446fcdfa333724cc5346e6586e44970&amp;v=4">

https://github.com/artf/grapesjs/discussions/3973#discussion-3702451

**Comment by gitwithsarthak** [comment]
> Hey, you can use canvas property like this : var editor = grapesjs.init({ ...... canvas: { scripts: ['https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js'], styles: ['https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css'] } })

https://github.com/artf/grapesjs/discussions/3973#discussioncomment-1703718
