### ISSUE TITLE
Select Parent Function not working when parent element is not selectable

### ISSUE THREAD

**Issue by tommywulove** [artf/grapesjs#660]
Hi @artf, I have a question about select parent function.
Cannot select the parent when parent element is not selectable, suggest to skip the parent element then select parent's parent element until to the div#wrapper.

**Comment by ryandeba** [comment]
I could probably help out here - I'll try to make a pull request later today or tomorrow.

**Comment by tommywulove** [comment]
Hi @ryandeba,
Thanks for your effort.

**Comment by tommywulove** [comment]
Hi @artf, more one question,  can i have a enhancement for select command, when the cursor click or hover the element which is not selectable, then the selection jump to available element. Since the element not available to select, i want the user jump to the parent element.

**Comment by artf** [comment]
@tommywulove I'd say it's another issue, this one is patched by Ryan

**Comment by tommywulove** [comment]
@artf  Noted, i will create a new issue for any new issue, thanks.
