### ISSUE TITLE
Component recognition

### ISSUE THREAD

**Issue by SwithFr** [artf/grapesjs#664]
Hi. Hi,

I created an "img-link" component that as its name indicates is a link that contains an image. 

When I insert my component into the editor everything works perfectly. But when I want to edit my template afterwards. It no longer recognizes my component as an "img-link" but as a simple image, and therefore no longer has the behaviors I defined for it (custom traits).

I tried to use a specific isComponent function :
```
isComponent: function ( el ) {
     if ( el.classList && el.classList.contains( 'img-link' ) ) {
        return { type: 'img-link' };
     }
}
```

But it doesn't work.

Any idea ?

**Comment by artf** [comment]
Hi Jeremy, might this https://github.com/artf/grapesjs/wiki/Components#hints be the case?

**Comment by SwithFr** [comment]
Thank with a plugin it's works !
