### ISSUE TITLE
Question about Asset Manager 

### ISSUE THREAD

**Issue by tlatforlz** [artf/grapesjs#667]
Hi @artf ,
I have two question about Asset Manager. 
1. How I can set a image by select, current logic after I upload image, I must select image in list Asset ? I want after I upload Image, I set it in the component.
2. How I can reload Asset. I write api to save image in Get Image. Image auto save in Asset. I want reload Asset to load image from my database.

Thanks for great framework.
Have nice days.

**Comment by artf** [comment]
Hi @tlatforlz first of all check out the docs page about [Assets](https://github.com/artf/grapesjs/wiki/Assets) which could be helpful

> How I can set a image by select, current logic after I upload image, I must select image in list Asset ? I want after I upload Image, I set it in the component.

You might want to rely on [Assets Events](https://github.com/artf/grapesjs/wiki/API-Editor#assets)

> How I can reload Asset. I write api to save image in Get Image. Image auto save in Asset. I want reload Asset to load image from my database.

Use can make use of [`load`](https://github.com/artf/grapesjs/wiki/API-Asset-Manager#load) method from Assets API
