### ISSUE TITLE
Any approach to use class to control the data-gjs-{property} ? 

### ISSUE THREAD

**Issue by tommywulove** [artf/grapesjs#669]
Hi @artf,  any approach to use class to control the data-gjs-property? Such as i added a class "non-copyable" to element, then the component will auto change the copyable property to false, let the user cannot copy the element in the editor.

**Comment by artf** [comment]
You can make use of [Events](https://github.com/artf/grapesjs/wiki/API-Editor#available-events)
```js
editor.on('component:add', model => {
	const cls = model.getAttributes()['class'];
	cls == 'non-copyable' && model.set('copyable', 0);
})
```
