### ISSUE TITLE
Missing option to erase style options

### ISSUE THREAD

**Issue by mingodad** [artf/grapesjs#672]
Hello !
In several style options there is no way to erase/reset several options like:
- font-family : if we select a font to experiment and decided that we do not want any custom there is no way to reset it.
- dimensions-width: if we experiment with some value and do not want any custom value we can erase the value but we still get a style in the css "width:auto" that in some cases mess up the layout (could we have the property removed completely ?).

The same apply to several other properties we need a default options in all of then to be able to remove/erase then from the generated styles.

Cheers !

**Comment by afotey** [comment]
A SCSS style tutorial would be nice

**Comment by artf** [comment]
Hi @mingodad there is actually an option which enables the possibility to clear values but it's still a work in progress (have to deal better with composite types)
```js
grapesjs.init({
	...
	styleManager: {
		clearProperties: true,
		...
	}
})
```

**Comment by artf** [comment]
`clearProperties` is more stable now

**Comment by benvmatheson** [comment]
Is it possible to enable `clearProperties` from the API after the editor is initialized?

**Comment by artf** [comment]
@benvmatheson 
```js
const sm = editor.StyleManager;
sm.getConfig().clearProperties = 1;
sm.render();
```
