### ISSUE TITLE
how to render block manager outside container?

### ISSUE THREAD

**Issue by crazyxhz** [artf/grapesjs#673]
I'm new to this great library and it seems very neat and clean BUT here is the problem that I have.
I'm having gjs rendered in the middle, and I want to render block manager and other panel and button into third party ui component. How can I do that? 
![image](https://user-images.githubusercontent.com/6551888/34306134-8ae7658a-e77c-11e7-86cd-38eaf305a6ce.png)

**Comment by artf** [comment]
Hi @crazyxhz currently it's not possible to achieve via configuration but it's something I'd like to improve.
Currently, as a workaround, you can move panels via js once are rendered, for the block manager you have to activate it first
```js
const editor = grapesjs.init({
	...
});

editor.on('load', () => {
	// Load blocks and put them in another element
    editor.runCommand('open-blocks'); // this will render blocks
	const blocksEl = document.querySelector('.gjs-blocks-cs');
	yourContainer.appendChild(blocksEl);
})
```

**Comment by lorrandavid** [comment]
@crazyxhz after the new release v0.14.5 it's now possible to render block manager outside of the main editor. You can achieve the desired result like this:

```
grapesjs.init({
  ...
  layerManager: {
    appendTo: 'query-or-element',
    ...
  },
  blockManager: {
    appendTo: 'query-or-element',
    ...
  },
  styleManager: {
    appendTo: 'query-or-element',
    ...
  },
  selectorManager: {
    appendTo: 'query-or-element',
    ...
  },
  traitManager: {
    appendTo: 'query-or-element',
    ...
  }
});
```

I don't know if it's docummented but you can find more about it on @artf explanations on the release https://github.com/artf/grapesjs/releases/tag/v0.14.5

**Comment by artf** [comment]
Thanks @lorrandavid for pointing this out, this issue can be closed now
