### ISSUE TITLE
custom component don't save

### ISSUE THREAD

**Issue by nestor91sanchez** [artf/grapesjs#674]
my custom component don't save in wrapper editor,  when refresh the page the editor load all components less my component.  the web inspector show a empty div.

<img width="531" alt="screen shot 2017-12-22 at 3 14 08 pm" src="https://user-images.githubusercontent.com/2053807/34309887-d8a7a5e8-e72a-11e7-823e-5aeea5197866.png">
<img width="1543" alt="screen shot 2017-12-22 at 3 13 50 pm" src="https://user-images.githubusercontent.com/2053807/34309888-d8bcf0a6-e72a-11e7-8f21-e8a28c60c6fa.png">

**Comment by afotey** [comment]
If you're referring to having your generated content save and persist upon refresh, try this:

`var editor = grapesjs.init({
          container : '#gjs',
          storageManager: {
            // type: 'none'
            id: 'gjs-',             // Prefix identifier that will be used inside storing and loading
            type: 'local',          // Type of the storage
            autosave: true,         // Store data automatically
            autoload: false,         // Autoload stored data on init
            stepsBeforeSave: 1,     // If autosave enabled, indicates how many changes are necessary before store method is triggered
            storeComponents: false, // Enable/Disable storing of components in JSON format
            storeStyles: false,     // Enable/Disable storing of rules/style in JSON format
            storeHtml: true,        // Enable/Disable storing of components as HTML string
            storeCss: true,         // Enable/Disable storing of rules/style as CSS string
          },`
