### ISSUE TITLE
Escape html

### ISSUE THREAD

**Issue by mingodad** [artf/grapesjs#677]
Hello !
I noticed several faults in escaping html through grapesjs some of it can be fixed by this pull request https://github.com/artf/grapesjs/pull/676 , but I still having problems with the html inserted on start.

In the example bellow the first &lt;pre&gt; is not rendered properly and I need to double escape it like on the second &lt;pre&gt; to get it properly rendered and be able to import/export after that properly.

Somehow between the several transformations applied to the initial html it get screwed. 

```html
			<div class="buttons">
				<h1>Buttons</h1>
				<a class="btn smooth btn-a">btn-a</a>
			
				<br><br><pre>&lt;a class="btn btn-b smooth"&gt;btn-b&lt;/a&gt;</pre>
				<br>
				<a class="btn smooth btn-a btn-sm">btn-sm btn-a</a>
				
				<br><br><pre>&amp;lt;a class="btn btn-b btn-sm smooth"&amp;gt;btn-sm&amp;lt;/a&amp;gt;</pre>
			</div>
```

**Comment by artf** [comment]
As already mentioned [here](https://github.com/artf/grapesjs/pull/676) we have to create a new Component for `<pre>` as escaping everything it's not an option
