### ISSUE TITLE
Help Wanted

### ISSUE THREAD

**Issue by suchithmahadi** [artf/grapesjs#678]
Hello,

2 queries : 

1) How to Add a LOGO as in Demo webpage.
![screen shot 2017-12-23 at 6 13 32 pm](https://user-images.githubusercontent.com/10076407/34319690-6a6ef98e-e80e-11e7-8b4b-c6b20cd16922.png)

2) How to move the block manager, Style Manager from Right Side to Left Side.
![screen shot 2017-12-23 at 6 14 05 pm](https://user-images.githubusercontent.com/10076407/34319697-8b2312fa-e80e-11e7-9631-cdf25d920b30.jpg)

Thanks.

**Comment by artf** [comment]
@suchithmahadi GrapesJS just comes with a default UI that you can easily change with JS and CSS

**Comment by suchithmahadi** [comment]
@artf  Thanks for the reply, At least if you can suggest where exactly to change will be helpful.

Thanks.

**Comment by JulyanoF** [comment]
@suchithmahadi something like
`$('.fa-th-large').remove();`
