### ISSUE TITLE
How to modify the component el(not model)  after editor render?

### ISSUE THREAD

**Issue by cloudseasail** [artf/grapesjs#68]
I'd like to add some trick like:
specify the backgroud img after one component initialized (the components are from html string).

1. any event can bind to ComponentView for dom loaded?
2. I can get the component by editor.DomComponents after render. but how to modify the el, not the model?  (because I donot like to show it in the final html code)

**Comment by artf** [comment]
Maybe something like this:
```js
// Triggered when a new component is added to the editor
editor.on('component:add', function(model) {
  // each model has a reference to its view, so...
  var el = model.view.el;
  el.style...
})
```
