### ISSUE TITLE
DOM/Component buginess when editing Classes/Settings

### ISSUE THREAD

**Issue by z1lk** [artf/grapesjs#680]
Encountered this while developing a plugin. I've reproduced it in the official demo via Browserstack on a different OS and browser, so I'm pretty confident there's a bug here. Exact steps to reproduce:

1. Load the [demo](http://grapesjs.com/demo.html), clear the canvas (trash icon), and refresh page to get a fresh demo page
2. Select the "Build your templates without coding" `div` in the canvas
3. Open the Settings section in the Style panel, and in the ID field type `a`, `ENTER`, `b`, `ENTER` (i.e. change the ID twice)
4. Notice that the Component is still selected, but DOM element has lost the `gjs-comp-selected` class, which gives blue border
5. In the classes editor, click X to remove the `lead-title` class
6. Immediately give the component a Title via the setting
7. Notice that the `lead-title` class has returned in the DOM but not in the classes editor
8. You can sync the DOM/Component classes back up by making a change via the classes editor

**Comment by artf** [comment]
Thanks @z1lk I confirm you about the issue in the demo, but the bug behind this was already fixed thanks to #661 The patch will be available in the next release

**Comment by artf** [comment]
Should be fixed now https://github.com/artf/grapesjs/releases/tag/v0.12.58
