### ISSUE TITLE
Toolbar shown again on scroll even if it is hidden in Firefox

### ISSUE THREAD

**Issue by vishal5033** [artf/grapesjs#681]
Hi,

We have hide the toolbar using gjs-data-* properties. It is successfully hidden. But in firefox when you scroll down , it again pops up on the same element.
before scroll.
![image](https://user-images.githubusercontent.com/194415/34339913-c8af1b9e-e9a0-11e7-94a3-7925a8f750b0.png)

after scroll.
![image](https://user-images.githubusercontent.com/194415/34339921-dd314f9c-e9a0-11e7-8da3-4ceaa126205e.png)

Can you please guide us?

Thanks

**Comment by artf** [comment]
Thanks @vishal5033 I found the bug, it should be fixed in the next release.
