### ISSUE TITLE
Creating BLOCKs with Settings like Style Manager

### ISSUE THREAD

**Issue by chiqui3d** [artf/grapesjs#682]
Hello!
I would like to know if you can create BLOCKs with options such like style manager, i. e. not drag, showing options in the same sidebar.

Thanks

**Comment by artf** [comment]
Hi @chiqui3d you can create blocks with an object as a content with all [available properties](https://github.com/artf/grapesjs/blob/dev/src/dom_components/model/Component.js#L17)
```js
blockManager.add('my-block', {
  label: 'Simple block',
  content: {
    // Component properties
    removable: false,
	draggable: false,
	...
  }
})
```

**Comment by chiqui3d** [comment]
Hello @artf , 
Nothing happens, I mean that I have created a block, and clicking doesn't do anything, componets is not the attribute to display the html?

here my code:

```
 bm.add('link-replace', {
        name: 'link-replace',
        category: 'Extra',
        label: 'Link Replace',
        content: {
            removable: false,
            draggable: false,
            droppable: false,
            script: "console.log('the element', this)",
            components: "<h2>Test Block</h2>",
            content: "<h2>Test Block</h2>",
            traits: [{
                label: 'Link Replace',
                name: 'link-eplace',
                changeProp: 1,
            }],
            style: {
                width: '100px',
                height: '100px'
            }
        },
        attributes: {
            title: 'Link Replace',
            class: 'fa fa-external-link'
        }
    });
```

The only thing I want to do, is to show an input URL type, for replace all links of canvas

**Comment by chiqui3d** [comment]
Please @artf , you can tell me solutions?

**Comment by artf** [comment]
@chiqui3d remove this `content: "<h2>Test Block</h2>",`

**Comment by chiqui3d** [comment]
@artf Maybe I'm trying to do it can't be done, i. e. click on "Link Replace" and show options inside the panel?
I've created a https://jsfiddle.net/ccrmoubq/4/

**Comment by artf** [comment]
@chiqui3d, first of all, I had to remove also `draggable: false` otherwise you're not able to drop it inside the canvas, then, honestly, I don't understand what is actually your issue

**Comment by chiqui3d** [comment]
@artf I don't want it to be draggable and I don't want to drag it into the canvas. I just want to click on the Link Replace block button, this show an input to put URL and a submit button (these options as Style Manager does, which shows the options inside the panel).

This can be done with the block?

**Comment by artf** [comment]
> @artf I don't want it to be draggable and I don't want to drag it into the canvas. I just want to click on the Link Replace block button, this show an input to put URL and a submit button (these options as Style Manager does, which shows the options inside the panel).

Ok, this is has nothing to do with [Blocks](https://github.com/artf/grapesjs/wiki/Blocks) then
For your case, I'd suggest adding a new button with a custom command which just opens a Modal with your stuff and executes your logic
