### ISSUE TITLE
Import the zip file exported from grapes js.

### ISSUE THREAD

**Issue by suchithmahadi** [artf/grapesjs#683]
Hello @artf , 
Any possible way to import back the zip file itself, which is generated by grapes js?

Thanks.

**Comment by artf** [comment]
Hi @suchithmahadi first of all, exporting the zip is done by [this plugin](https://github.com/artf/grapesjs-plugin-export) and not inside the grapesjs core. Besides this, there is no such functionality so you have to implement it by yourself (eg. using jszip)
