### ISSUE TITLE
Trait view doesn't update input element when target value changes

### ISSUE THREAD

**Issue by z1lk** [artf/grapesjs#686]
If the target value (i.e. Component attribute/prop) is set manually and not via the trait input element, the input doesn't reflect that change.

Sorry for all the issues--I'm willing to work on this if you want any help.

**Comment by DmitryNek** [comment]
Calling of

`selected.sm.trigger('change:selectedComponent')` 

updates trait input elements with new values of selected component.

**Comment by artf** [comment]
Refactored TraitView for such functionality, will be added in the next release.
Thanks

> Sorry for all the issues

Reporting bugs it's already an aid :)
