### ISSUE TITLE
After update the component attributes using   editor.on('component:add',function(){}); The blue box item is not correct.

### ISSUE THREAD

**Issue by tommywulove** [artf/grapesjs#687]
After update the component attributes using   editor.on('component:add',function(){}); 
The blue box item(it mean the action icon) is not correct. The copy icon should not show.

![image](https://user-images.githubusercontent.com/2859394/34370766-dad79d20-eb01-11e7-82f1-0d0b5346273c.png)

Javascript
`    var hasClass  = function(model, className){
        return model.get('classes').where({name: className}).length;
    }
    var updateProperty = function (model) {
        
        model.set({
            draggable: false,
            droppable: false,
            copyable: false,
            removable: false,
            selectable: false,
            editable: false
        });

        if (hasClass(model,"editable")) {
            model.set('editable', true);
        }
        
        if (hasClass(model,"selectable")) {
            model.set('selectable', true);
        }
        if (hasClass(model,"content-block")) {
            model.set('draggable', '#wrapper');
            model.set('droppable', false);
            model.set('selectable', true);
          
        }
        
        
        console.log(model);
        model.get('components').each(child => updateProperty(child))
  

    }
    editor.on('component:add', function (model) {

        updateProperty(model);
        //console.log($(model).hasClass("editable"));

    })`

**Comment by ryandeba** [comment]
Hi @tommywulove,

I believe the "blue box item" that you're referring to is the [component toolbar](https://github.com/artf/grapesjs/blob/1f4bcfa7f05c464e4bfac59461e0758aad0d18d8/src/dom_components/model/Component.js#L475). All of the toolbar buttons are created for each component as that component is initialized; changing a property (like `copyable`) does not automatically update the toolbar.

You could probably force the toolbar to update by clearing out the `toolbar` property on the component and manually call `initToolbar()`...maybe something like this:
```
model.set("toolbar", "").initToolbar();
```

@artf - would you consider this a bug or is this the desired behavior? If you think it should be changed, I'd be happy to work on a pull request for it.

**Comment by tommywulove** [comment]
Hi @ryandeba , 
Thanks for your reply. I found that the component:add event is not suitable for my case, so i used component type to solve my problem. I updated the component type and added some new component type to control which action can be use in the element.

**Comment by artf** [comment]
@tommywulove ok I close this then

@ryandeba As you already mentioned the toolbar is created when the component is initialized so, honestly, I don't see it as a bug and overall, your snippet should work well. BTW thanks for your willingness to help
