### ISSUE TITLE
Multilanguages

### ISSUE THREAD

**Issue by standus** [artf/grapesjs#688]
Can you change your core to multilanguages from separated localized files?
Can not believe that project like this is hardcoded!

**Comment by artf** [comment]
Hi @standus I explain here #26 why there is no reason to have i18n module

**Comment by standus** [comment]
In your #74 roadmap is nothing about translation and what with other improvements when nothing is possible translate? By me most first improvements is translation possibility over extra files because when as soon as you will do it it will be more easy. Later it will be problem and maybe impossible to do it. I predict without translation project will die in finally!
