### ISSUE TITLE
Change value of attribute that is passed through traits

### ISSUE THREAD

**Issue by HarshOB** [artf/grapesjs#689]
Hello @artf 

Is there any methods to manipulate the input value of an attribute that is passed through traits. 

Like I passed value **Hello** in trails title and it is appended to HTML attribute like **title="hello"** but I want to change the value after like I write **Hello** in traits but it is appended as  **StringHelloString** and in HTML attribute it is visible as title="StringHelloString".

**Comment by artf** [comment]
Hi Harsh, 
> Is there any methods to manipulate the input value of an attribute that is passed through traits.

Nope, probably the best you can do is creating a custom Trait and override [`onValueChange`](https://github.com/artf/grapesjs/blob/dev/src/trait_manager/view/TraitView.js#L44) but take care also on how you will retrieve the value

**Comment by HarshOB** [comment]
Thanks for the reply but as I told you (#647) that custom traits value is not getting in HTML code
