### ISSUE TITLE
Preview Command bug: exit the preview mode will run the sw-visibility command, when the sw-visibility stopped before go to preview mode.

### ISSUE THREAD

**Issue by tommywulove** [artf/grapesjs#690]
Hi @artf ,
The case is "switch-visibility" command stopped, then click the preview button or trigger preview command, it will go to preview mode, when exit the preview mode, the "sw-visibility" command ran, it haven't save the state before go to preview mode and cannot reset the visibility after stop the preview command.

**Comment by tommywulove** [comment]
Hi @artf,
I found that the command running sequence when click the preview button:
![image](https://user-images.githubusercontent.com/2859394/34428348-c3e556e4-ec86-11e7-89fb-3eb8c61b6803.png)

Is it a bug ? this running sequence make me cannot get the correct classname of canvas' body. so cannot store the state before run the preview command. I cannot make a further development.

**Comment by artf** [comment]
@tommywulove I tried this in the demo
```js
editor.on('run:preview', () => console.log('run preview'))
editor.on('stop:preview', () => console.log('stop preview'))
```
and the sequence seems correct

**Comment by tommywulove** [comment]
@artf  but why i click the preview button, it will trigger the stop command once , then run the command ?

**Comment by artf** [comment]
Hey @tommywulove  are you able to provide a live demo of your case cause as I said I can't reproduce it

**Comment by tommywulove** [comment]
Hi @artf, checked on the latest commit and no problem on command running sequence. And i will be available work on this enhancement.

**Comment by artf** [comment]
Hi @tommywulove can you provide a live example? As I said I can't reproduce it so there is no reason  to merge your PR

**Comment by tommywulove** [comment]
![grapesjs preview issue](https://user-images.githubusercontent.com/2859394/34604018-4b589752-f241-11e7-9423-7d21afacdff9.gif)

**Comment by chiqui3d** [comment]
It's the same with me.

**Comment by chiqui3d** [comment]
Solved with:

`editor.on('stop:preview', () => editor.stopCommand('sw-visibility'))
`
