### ISSUE TITLE
After pull the new commit, the grapesjs not working on IE and show following error.

### ISSUE THREAD

**Issue by tommywulove** [artf/grapesjs#692]
Hi @artf ,

After pull the new commit, i get the error on IE, can you please take a look for this? Thanks.
![image](https://user-images.githubusercontent.com/2859394/34408275-d98ca468-ebfd-11e7-918a-4a0d3a80f9d8.png)
![image](https://user-images.githubusercontent.com/2859394/34408318-28360dc0-ebfe-11e7-9395-d44fa7023a59.png)

**Comment by artf** [comment]
This is the code from the webpack dev server and honestly, have no idea why you get CORS issues here. What about another browser?

**Comment by tommywulove** [comment]
![image](https://user-images.githubusercontent.com/2859394/34440075-a325943e-eced-11e7-9572-6c9d54c617e8.png)
Chrome has same result.

**Comment by tommywulove** [comment]
Sorry, my bad, i used the testing script and put into server. I rebuild  the script is fine.
