### ISSUE TITLE
Remove Asset Manager default uploadName suffix '[]' in request.

### ISSUE THREAD

**Issue by luigledr** [artf/grapesjs#693]
In the Asset Manager uploadName in request has a default suffix '[]' in his name.
It shouldn't has a default suffix. If the user needs a fileName with suffix '[]', the user should add it.

**Comment by artf** [comment]
Hi Luiz, `[]` just stands for that `uploadName` is an array as you might need to upload multiple files, so it's added by the browser and not grapesjs
