### ISSUE TITLE
CSS Zoom property is not managed by canvas

### ISSUE THREAD

**Issue by nnnax** [artf/grapesjs#694]
Hello,
I've applied a CSS property on the wrapper as follow
```
div#wrapper{
  zoom: 0.75;
}
```
When I place my mouse on a component, the tools position are not correct and I'm not able to use the toolbar.
After a small investigation, I think the issue is in CanvasView.js when the content is added to the wrapper, it should be interesting to check the zoom property of the wrapper and adapt the position.

Kind Regards,
Benjamin

**Comment by artf** [comment]
Hi Benjamin, thanks for the suggestion but currently I'm not interested in such functionality
