### ISSUE TITLE
Question: Dropping external element into blocks

### ISSUE THREAD

**Issue by vishal5033** [artf/grapesjs#697]
Hello,

I want to drop external elements ( for example, tree view node) into blocks. Can you please help me out to show a way, how to achieve that?

Thanks,

**Comment by artf** [comment]
Hi @vishal5033 currently the canvas is not a droppable element but I've added HTML5 D&D support to the Rodmap (#74)

**Comment by vishal5033** [comment]
Hi @artf , Can you please share, when will HTML5 D&D available?.
By the way thank you very much for such a wonderful project.
Thanks

**Comment by artf** [comment]
@vishal5033 probably in the next release
