### ISSUE TITLE
editor.getSelected().toHTML() is not consistent

### ISSUE THREAD

**Issue by alimajed93** [artf/grapesjs#698]
Hi everyone,

  I created a new component type, 'html-block', which is a component in which you can add your html code. I added an 'Edit' button to the toolbar, to enable the user editing the added html code. In order to show the html code of the component in the modal, I am using the function 'editor.getSelected().toHTML()';

  The problem is that, sometimes the code returned is per example: `<div><h1>h1</h1></div>` (which is what I need, since I need the exact code that the user added at first), and sometimes it returns something like that: `<div id='135'><h1>h1</h1></div>` (with an id added automatically).
  I also tried to use 'editor.getSelected().em.getHtml()' but the same issue occurred.

  How can I solve that and retrieve the exact html code that the user entered ?

Thank you in advance.

**Comment by artf** [comment]
Inside your `html-block` component create a new property (eg. `custom-code`) for user's code and retrieve it with `editor.getSelected().get('custom-code')`

**Comment by alimajed93** [comment]
This solved the problem for me. Thank you.
