### ISSUE TITLE
toolbar and hight light not adjust to window resize

### ISSUE THREAD

**Issue by crazyxhz** [artf/grapesjs#699]
If you resize the winow after grapesjs instance has been initialized. The hight light frame will be shifted:
![image](https://user-images.githubusercontent.com/6551888/34487421-3c30d4da-f00f-11e7-8716-5d076f7c8aa8.png)

**Comment by artf** [comment]
@crazyxhz are you sure you're using the latest version?

**Comment by crazyxhz** [comment]
@artf  I'm using this layout:
![image](https://user-images.githubusercontent.com/6551888/34568253-2cd0e844-f1a0-11e7-858e-10f42f497a45.png)
left part and right part is fixed width while the middle part in which grapesjs is rendered is taking the rest of the space. Maybe it has something to do with this layout.
```stylus
  .leftpart
    float left
    width 310px

  .middlepart
    float left
    width calc(100vw - 670px)
    min-width 300px

  .rightpart
    float right
    width 300px
```

**Comment by artf** [comment]
Not sure, but, again, are you using the latest version?

**Comment by crazyxhz** [comment]
I'm using 0.12.55

**Comment by crazyxhz** [comment]
@artf  check this out. I have updated the package to the lasted 12.60. Problem still exist
![](https://i.loli.net/2018/01/10/5a55d28772c76.jpg)

**Comment by artf** [comment]
@crazyxhz does this helps?
```js
window.addEventListener('resize', () => editor.trigger('change:canvasOffset'))
```

**Comment by crazyxhz** [comment]
@artf nope It doesn't work. By the way I found this issue is reproducible on the offical website:
http://grapesjs.com/demo.html
1, Change Editor to mobile mode.
2, clear canvas add an image
3, resize the window
