### ISSUE TITLE
Looking For Instructions

### ISSUE THREAD

**Issue by kawikaconnell** [artf/grapesjs#70]
Hi, this project looks amazing to me, so I would love to contribute to it. However, I don't really know what needs to be worked on, is there a roadmap/list of sorts for finding what areas need work?

There is this project called AdonisJS, a open-source NodeJS framework, and they have this: https://trello.com/b/yzpqCgdl/adonis-for-humans. Do you have anything similar?

**Comment by artf** [comment]
Thanks @kawikaconnell really glad to see so much interest :)
Roadmap/Todo list is definitely a must, I'll open a new issue about it and later we can actually use Github's 'Projects' as a kanban :)

**Comment by artf** [comment]
#74 ;)
