### ISSUE TITLE
Undomanager and ctrl+z/ctrl+y

### ISSUE THREAD

**Issue by krunal039** [artf/grapesjs#700]
we load content from db once editor page load and if use select undo after any changes it makes editor canvas blank. Is there way to solve it?

**Comment by ryandeba** [comment]
Hi @krunal039,

You probably want to clear out the undo history right after populated your content from the db.

`editor.UndoManager.clear();`

**Comment by krunal039** [comment]
@ryandeba I tried and now undo and redo button does not do anything(not even blank editor canvas) I have below code
`[{
      id: "undo",
      className: "fa fa-undo icon-undo",
      command: function command(editor, sender) {
        sender.set("active", 0);
        editor.UndoManager.undo(1);        
      },
      attributes: {
        title: "Undo (CTRL/CMD + Z)"
      }
    }, {
      id: "redo",
      className: "fa fa-repeat icon-redo",
      command: function command(editor, sender) {
        sender.set("active", 0);
        editor.UndoManager.redo(1);
      },
      attributes: {
        title: "Redo (CTRL/CMD + Y)"
      }
    }`

**Comment by ryandeba** [comment]
@krunal039 Could you create a jsfiddle example that shows the issue? Calling `editor.UndoManager.clear()` shouldn't completely break the undo/redo functionality, so I suspect there is some other issue going on.

**Comment by NorthstarTech** [comment]
I am also facing the same issue, when loading the html from db into the editor. I also clear the undomanager but its not working. here is the code,

editor.DomComponents.clear();
editor.DomComponents.getWrapper().set('content', '');
editor.setComponents(htmlString); //loading the html content
editor.UndoManager.clear(); //clearing the undomanager

Please provide the fix. Hep needed. 
Thanks

**Comment by ryandeba** [comment]
@NorthstarTech I ran the code below (slightly modified version of yours) over at the [demo](http://grapesjs.com/demo.html) and the undo/redo functionality still works for me. My test was pretty basic, but was I able to delete the single component, hit the undo button to bring it back, and then hit the redo button to delete it again - all worked as expected. As I mentioned to krunal039, I suspect there is some other issue going on. Could you provide a jsfiddle showing your issue? That would help me debug it.
```
editor.DomComponents.clear();
editor.DomComponents.getWrapper().set('content', '');
editor.setComponents("<div>some content</div>"); //loading the html content
editor.UndoManager.clear(); //clearing the undomanager
```

**Comment by ryandeba** [comment]
FWIW, the built-in keyboard shortcut for redo is actually `ctrl+shift+z`, not `ctrl+y` - [code](https://github.com/artf/grapesjs/blob/d6ffecf27633bc27632a173998222fea0c041b37/src/keymaps/index.js#L25).

**Comment by krunal039** [comment]
@ryandeba thanks for reply, i am able to resolve issue, was not due to grapesjs. also does grapesjs latest build support ie11 as i have made my local version ie11 compatible but I am sure I must be missing out on all bug fixes and enhancement

**Comment by artf** [comment]
@krunal039 great I close this then, the IE11 support was added in the latest release https://github.com/artf/grapesjs/releases/tag/v0.12.55
Thanks for help Ryan.
For anyone else encountering issues with undo manager clearing be sure to call `editor.UndoManager.clear()` once your async methods are finished

**Comment by NorthstarTech** [comment]
@ryandeba Thank u so much. Fixed the issue.
