### ISSUE TITLE
Restrict draggable elements to parent?

### ISSUE THREAD

**Issue by AustinTBiggs** [artf/grapesjs#704]
I'm not sure if this already exists and I haven't seen it yet (apologies if that's the case). Is there a way to restrict where certain draggable elements are droppable?

Say I have a list:
```
<ul>
<li>one</li>
<li>two</li>
<li>three</li>
</ul>
```

And I want the user to be able to rearrange the list items, but restrict them from dragging outside of the `<ul>`.

similar to http://api.jqueryui.com/draggable/#option-containment

**Comment by artf** [comment]
Sure, you can make use of `data-gjs-*` attributes (eg. `data-gjs-draggable="ul"`)
Check the last example code here https://github.com/artf/grapesjs/wiki/Blocks

**Comment by AustinTBiggs** [comment]
It seems you've thought of everything, you've done such an amazing job w/ GrapesJS! 😄

**Comment by artf** [comment]
Thanks Austin :)

**Comment by sakshigarg9** [comment]
> Sure, you can make use of `data-gjs-*` attributes (eg. `data-gjs-draggable="ul"`)
> Check the last example code here https://github.com/artf/grapesjs/wiki/Blocks

Is it  possible to sepcify a div class name or id in case i have a lot of nested divs?

**Comment by artf** [comment]
@sakshigarg9 you can use any query selector (eg. `div#some-id > .class`)
