### ISSUE TITLE
Using Gridstack.js in Grapesjs

### ISSUE THREAD

**Issue by suchithmahadi** [artf/grapesjs#707]
Hello @artf ,

Came across a plugin which can  be used in grapesjs  for grid resizable and it is complete responsive have a look and please tell us how to integrate this plugin with GrapesJS, so that i can do a PR.

https://github.com/gridstack/gridstack.js#demo-and-examples

**Comment by artf** [comment]
@suchithmahadi you're free to use it inside your project but it's not something we need inside the core of GrapesJS
