### ISSUE TITLE
how to run the project?

### ISSUE THREAD

**Issue by aloksharma1** [artf/grapesjs#71]
hello,

first of all this is a great and promising tool. i wanted to test the stuff and look into your code , but i cannot run it on my local system and i cannot find the documentation on readme regarding setting a local project.
i am trying to run it on iis server, please let me know what type of backend/frontend is involved and what kind of setup is required to run the code and dig deeper.

thanks

**Comment by artf** [comment]
Hi @aloksharma1 GrapesJS is just a frontend library so the backend part is up to you.
You can play with the editor, locally, also without any backend, just download the last release and follow instructions [here](https://github.com/artf/grapesjs#usage)

For the [development environment](https://github.com/artf/grapesjs#development), all you need is Git and NodeJS.

**Comment by aloksharma1** [comment]
ok got it; but i tried the test and src folders they are showing js errors, i need a starting point . i already started on a similar tool to build for our cms but i found yours it looks more complete and we want to integrated it in our system.

![grapejs-test-page](https://cloud.githubusercontent.com/assets/4345706/25093234/efb8a146-23ae-11e7-943b-78256b3dcebf.PNG)


as you can see there are errors in here , i will be looking into your given links but please update a boilerplate to start with minimal code from side, you already have this set on grapejs site.

thanks

**Comment by artf** [comment]
`/index.html` and `/test/index.html` are just for development purpose, to make them work you have to install all dependencies and run them behind a nodejs server

**Comment by johnjunpeng** [comment]
So after building/authoring everything, what's the standard way to retrieve the final HTML output which was hosted in an iframe on your demo site? Thanks!

**Comment by artf** [comment]
@johnjunpeng `editor.getHtml()` and `editor.getCss()`

**Comment by johnjunpeng** [comment]
Thank you @artf !
Obviously there is no need for GrapeJS to output any JavaScript code since it only aims at helping build HTML template for CMS. But I just wonder how easy it would be to incorporate custom-built web components (standard based). Does GrapeJS team envision to expand its framework to support web components  by default? Thanks again.
