### ISSUE TITLE
Open Style Manager when selecting an element 

### ISSUE THREAD

**Issue by michaellwatson** [artf/grapesjs#714]
trying to do this
```
     editor.on('component:selected', (model) => {
          editor.runCommand('open-sm');
    });

```
gives the error 
this.sender.get is not a function

grapesjs.min.js toggleSm

Basically I want to open the style manager when clicking on an element.

Any help or info appreciated, thanks

**Comment by artf** [comment]
Hi Michael, 
there is actually a kind of bug in 'open-sm' which doesn't allow calling the command with `runCommand` but the reason is that it was designed to be called just by its relative button, indeed I'd recommend doing this for your case

```js
editor.on('component:selected', () => {
	const openSmBtn = editor.Panels.getButton('views', 'open-sm');
	openSmBtn.set('active', 1);
});
```
