### ISSUE TITLE
Can we set a class to wrapper

### ISSUE THREAD

**Issue by suchithmahadi** [artf/grapesjs#715]
Hello ,

As per the document ,
// Change background of the wrapper and set some attribute
var wrapper = domComponents.getWrapper();
wrapper.set('style', {'background-color': 'red'});
wrapper.set('attributes', {'title': 'Hello!'});

Can we set a class to wrapper.

Please let us know how to set a class to the root component i.e. wrapper.

Thanks.

**Comment by artf** [comment]
Sure `editor.DomComponents.getWrapper().addClass('wrapper')`

**Comment by suchithmahadi** [comment]
@artf ,
Thanks for the reply.

Can we do
editor.DomComponents.getWrapper().addClass('wrapper')

in the release 0.10.7

Thanks.

**Comment by suchithmahadi** [comment]
Sorry to bother you,

Because when i tried in version 0.10.7
it is giving a error 
[Error] TypeError: wrapper.addClass is not a function. (In 'wrapper.addClass('wrapper')', 'wrapper.addClass' is undefined)
	Global Code (index.html:4474)
And one more request , i do not want to update to latest release, so can you tellme , any possible way to achieve this.

Thanks.

**Comment by artf** [comment]
> I do not want to update to latest release, so can you tellme , any possible way to achieve this

Sorry but GrapesJS is in active development so it doesn't make sense for me supporting older versions
