### ISSUE TITLE
Not allow selective Image resize

### ISSUE THREAD

**Issue by krunal039** [artf/grapesjs#716]
I do not want user to resize image on specific area of template, but want to allow anywhere on canvas.

I want user to just choose image and does not allow to resize for specific class/element.

**Comment by artf** [comment]
```js
```

**Comment by artf** [comment]
You probably need to do something like this on render
```js
const wrapper = editor.DomComponents.getWrapper();
wrapper.view.$el.find('#someid img').each((el, i, $els) => {
   const $el = $els.eq(i);
   const model = $el.data('model');
   model && model.set('resizable', 0);
});
```

**Comment by faruk247** [comment]
If you get any error you can use to fix that error.  each( function(el, i, $els)

complete code:

var wrappers = editor.DomComponents.getWrapper();
    wrappers.view.$el.find('.rm-editable img').each( function(el, i, $els) {
        var $el = $els.eq(i);
    var model = $el.data('model');
    model && model.set('resizable', 0);
    });
