### ISSUE TITLE
Add Description to trait

### ISSUE THREAD

**Issue by krunal039** [artf/grapesjs#718]
Is there way to add description to trait? we have below trait and want to add description so user understand what is purpose of it.

` traits: [{
            type: 'checkbox',
            label: 'Active',
            name: 'isActive',
            changeProp: 1,
            description: 'will make slider available on page'
          }]`

![trait](https://user-images.githubusercontent.com/11716808/34602232-eeaa5c06-f1f6-11e7-9ce9-2dad74ce53b2.png)

**Comment by artf** [comment]
Nope, but you can define custom [Traits](https://github.com/artf/grapesjs/wiki/Traits) and customize [`renderField`](https://github.com/artf/grapesjs/blob/dev/src/trait_manager/view/TraitView.js#L144) method
