### ISSUE TITLE
Respond problem for upload image

### ISSUE THREAD

**Issue by richieteh94** [artf/grapesjs#719]
I know is an old problem but I have an issue for the respond where I tried to return a response by using asp.net to return a response
below is my code(services code to save into directory and return a response):
(code in ashx asp.net)
`           context.Response.ContentType = "text/plain";
            context.Response.Expires = -1;
            try
            {
                HttpPostedFile postedFile = context.Request.Files[0] as HttpPostedFile;
                string tempPath = "/uploadImg";
                string savePath = context.Server.MapPath(tempPath);
                string filename = postedFile.FileName;
                if (!Directory.Exists(savePath))
                {
                    Directory.CreateDirectory(savePath);
                }
                string path = savePath + @"\" + filename;
                postedFile.SaveAs(path);

                Stream s = postedFile.InputStream;
                Image img = System.Drawing.Image.FromStream(s);

                int imgHeight = (int)img.PhysicalDimension.Height;
                int imgWidth = (int)img.PhysicalDimension.Width;

                TempModel tempModel = new TempModel();
                tempModel.type = "image";
                tempModel.src = "http://localhost:2002" + tempPath + "/" + filename;
                tempModel.height = imgHeight.ToString();
                tempModel.width = imgWidth.ToString();

                TempData tempData = new TempData();
                tempData.data = new List<TempModel>();
                tempData.data.Add(tempModel);

                string jsonString = JsonConvert.SerializeObject(tempData);
                string jsonRespond = jsonString.Insert(9,"\"" + "http://localhost:2002" + tempPath + "/\",");

                context.Response.Write(jsonRespond);
                context.Response.StatusCode = 200;

            }catch(Exception ex)
            {
                context.Response.Write("Error: " + ex.Message);
            }`
the code can save image to the directory but there is an error when parsing the response at grapesjs
what I facing is when i dropped my image the image couldn't automatic show in the panel.
I refered to the #138 but still having response problem

**Comment by artf** [comment]
> there is an error when parsing the response at grapesjs

Which error???

From what I see probably you're not posting `Content-Type: application/json` in your server script

**Comment by richieteh94** [comment]
Hi, @artf  I tried change `context.Response.ContentType="application/json"` but not working still have onUploadRespondError.
this is the the respond I pass back from the service is this format correct?
![image](https://user-images.githubusercontent.com/26899725/34656990-9cef622c-f45c-11e7-993d-f49e342a05d8.png)

**Comment by richieteh94** [comment]
hi @artf the error is 
![image](https://user-images.githubusercontent.com/26899725/34657394-9087a7fc-f460-11e7-802a-7ff5f1226ef1.png)
I tried changed the `context.Response.ContentType = "application/json";` but still get the above error
and my response from service is as below
![image](https://user-images.githubusercontent.com/26899725/34657421-c781cba2-f460-11e7-9176-77d35eb6f743.png)
the response get by using Fiddler 4.

**Comment by artf** [comment]
@richieteh94 'Unexpected token E in JSON at position 0' means your response it's not a valid JSON  string (which should start with `{` or `[` not `E`, probably there is an `Error...`). Check the response in your dev tools and you will see it

**Comment by richieteh94** [comment]
ok the respond i debuged is this.
![image](https://user-images.githubusercontent.com/26899725/34706835-e552685a-f544-11e7-9435-201e31a26c15.png)
`"{\"data\":[\"http://localhost:2002/uploadImg/IMG_20102017_102704_0.png\",{\"type\":\"image\",\"src\":\"http://localhost:2002/uploadImg/IMG_20102017_102704_0.png\",\"height\":\"538\",\"width\":\"1132\"}]}"`
and the raw text get from fiddler 4 is this
![image](https://user-images.githubusercontent.com/26899725/34706747-6cb248c0-f544-11e7-8199-1bab06d66946.png)
`{"data":["http://localhost:2002/uploadImg/IMG_20102017_102704_0.png",{"type":"image","src":"http://localhost:2002/uploadImg/IMG_20102017_102704_0.png","height":"538","width":"1132"}]}
`

**Comment by richieteh94** [comment]
I know the issues. It is my directory used by other service therefore it cause Error that catch at the end.
I think i need to change the code in the service to solve the problem.
Thanks @artf  for assisting me in this time.

**Comment by pranzikkin** [comment]
@richieteh94 how did you solve this problem?
