### ISSUE TITLE
Document Dirty Indicator

### ISSUE THREAD

**Issue by krunal039** [artf/grapesjs#720]
I want to display document dirty indicator unless document is saved to database. I have custom button on editor to save html to db I tried below #551 but it only fires while loading html from db to canvas and it does not fire for any changes afterward.

`editor.on('change:changesCount', () => {
      const editorModel = editor.getModel();
      const changes = editorModel.get('changesCount');
      if (changes) {
           //show dirty count
      }`

**Comment by artf** [comment]
Tried this in the demo and works as expected
```js
editor.on('change:changesCount', (model) => { 
	console.log('changed'); 
});
```

**Comment by AustinTBiggs** [comment]
@artf - I tried this in my code an nothing happens. This works for you?

**Comment by artf** [comment]
> This works for you?

Yeah, it works with the demo (which uses the latest version)

> I tried this in my code an nothing happens

Have you tried to change the structure of the template?
