### ISSUE TITLE
adding component script js

### ISSUE THREAD

**Issue by wvaymen** [artf/grapesjs#721]
I have question about injecting script js into GrapesJs.
Can I adding <script> into grapesJS using function editor.getComponents().add() and not injecting using javascript. document.createElement('script')

**Comment by artf** [comment]
@wvaymen sure, but you have to enable script importing before
```js
const editor = grapesjs.init({
	...
	allowScripts: 1,
});
editor.addComponents('<script>alert(1)</script>');
```
