### ISSUE TITLE
how to add sub categories of blocks

### ISSUE THREAD

**Issue by wvaymen** [artf/grapesjs#722]
i would know if there is a method to add blocks into a sub categorie in the panel of blocks?

**Comment by artf** [comment]
no @wvaymen you can only put blocks inside categories

**Comment by wvaymen** [comment]
please can you give me an example
thanks for your help

**Comment by artf** [comment]
```js
blockManager.add('your-block', {
  label: 'Label',
  category: 'Some category',
  content: '<div>Content</div>',
});
```
