### ISSUE TITLE
Changelog between versions

### ISSUE THREAD

**Issue by NicholasGati** [artf/grapesjs#723]
Hey Artur!

I am not sure if "Issues" is the right page to write this because it is more of a suggestion.

A Change Log is needed between GrapesJS versions. We are using GrapesJS in a project and are currently switching from an old version to the most up-to-date version. While we have customized the library for our own internal use by appending additional functionality, it would be great if there was some type of detailed Change Log as to which variables and functions were changed between versions and the additions and subtractions to the library. Newer versions do not seem very backwards compatible to previous versions and any issues from switching versions in a project would be quickly resolved if we knew what needed to be changed.

Thanks!

**Comment by artf** [comment]
Hi @NicholasGati,
you can find the changelog inside github releases https://github.com/artf/grapesjs/releases
