### ISSUE TITLE
CSS Editor

### ISSUE THREAD

**Issue by hesa2020** [artf/grapesjs#725]
Hello, I would like to know what would be the best route to take to extend the Editor.
There is a few features i would like to add for my project:

1. Split view ( Edit / Preview )
2. CSS Editor ( Create classes, animations, etc.. and then i can set my element to use that class )
3. Html editor ( Im sure it could be done easily using the import/export function )
4. Project Explorer ( Basicly select a file and it load it via ajax )

So would it be best to create multiple "plugins" for this, or to modify grapejs core ?
Let me know if any of these features already exist or is already possible.
And where should i start to be in the right path.

Thanks you, this is a very nice framework which i plan to use well :D

**Comment by artf** [comment]
Hi @hesa2020 
you should definitely create plugins to customize the editor and you can start from reading [here](https://github.com/artf/grapesjs/wiki).  Another important resource for customization is [API Reference](https://github.com/artf/grapesjs/wiki/API-Editor), if you have problems try to check first in repo's issues. For the Split view try to check the [Preview Command](https://github.com/artf/grapesjs/blob/dev/src/commands/view/Preview.js), CSS Editor / HTML Editor should not be too much different from [this one](https://github.com/artf/grapesjs-preset-webpage/blob/master/src/commands/openImport.js) (used inside the [demo](http://grapesjs.com/demo.html)).
