### ISSUE TITLE
<body> shouldn't be badgeable / selectable

### ISSUE THREAD

**Issue by AustinTBiggs** [artf/grapesjs#729]
I'm currently trying to remove the badgeable and selectable permissions from the <body> tag. I've tried setting the gjs-editable, gjs-badgeable, etc. permissions and nothing seems to the the trick. How would you suggest approaching this?

![screen shot 2018-01-08 at 3 47 21 pm](https://user-images.githubusercontent.com/930864/34696244-3f73f192-f48b-11e7-8a9f-13a59cdddf32.jpg)

**Comment by ryandeba** [comment]
Hi @AustinTBiggs,

This works for me in the [demo](http://grapesjs.com/demo.html):
`editor.DomComponents.getWrapper().set({badgable: false, selectable: false})`

You may also want to set `hoverable` to false if don't want the blue highlight to appear on hover.

**Comment by AustinTBiggs** [comment]
@ryandeba,

I'm sure you can imagine how silly I feel now. Grade A solution, thanks!

**Comment by ryandeba** [comment]
You're welcome! Glad I was able to help.
