### ISSUE TITLE
Loading a previously saved document has wrong CSS

### ISSUE THREAD

**Issue by jakzal** [artf/grapesjs#73]
I'm trying to save and then load the template with CSS. Everything's fine until I try to reload the page. Each reload keeps adding a group of CSS definitions, not sure where they're coming from:

```
body{
  margin-top:0px;
  margin-right:0px;
  margin-bottom:0px;
  margin-left:0px;
  height:auto;
  background-image:initial;
  background-position-x:initial;
  background-position-y:initial;
  background-size:initial;
  background-repeat-x:initial;
  background-repeat-y:initial;
  background-attachment:initial;
  background-origin:initial;
  background-clip:initial;
  background-color:rgb(255, 255, 255);
}
#wrapper{
  min-height:100%;
  overflow-x:auto;
  overflow-y:auto;
}
*{
  box-sizing:border-box;
}
```

Note that each reload will add these definitions even though they're already there (CSS definitions will grow after each reload). I use chrome.

Here's the minimum amount of code to reproduce this problem:

```
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Fuxrank Editor</title>
    <link rel="stylesheet" href="/grapesjs/dist/css/grapes.min.css">
    <style>
        body, html{ height: 100%; margin: 0;}
        .editor {
            height: 100%;
        }
    </style>
</head>
<body>
<div class="editor">
    <div id="gjs" style="height:0px; overflow:hidden"></div>
</div>
<script src="http://code.jquery.com/jquery-2.2.0.min.js"></script>
<script src="/grapesjs/dist/grapes.min.js"></script>
<script type="text/javascript">
    var editor = grapesjs.init({
        container: '#gjs',
        fromElement: false,
        height: '100%',
        storageManager: {
            id: 'gjs-',
            type: 'local',
            autosave: 1,
            autoload: 1,
            stepsBeforeSave: 1,
            storeComponents: 1,
            storeStyles: 1,
            storeHtml: 1,
            storeCss: 1,
        },
    });
    window.editor = editor;

</script>
</body>
</html>
```

To reproduce:
* load the page
* add few blocks/components
* export the template and review the CSS
* reload the page and review the CSS again
* reload the page and review the CSS again

With local storage CSS definitions are truncated after few reloads. With remote storage they just grow.

<img width="512" alt="1-add-components" src="https://cloud.githubusercontent.com/assets/190447/25151135/ac043970-2484-11e7-8ba4-d5917f18f63c.png">
<img width="512" alt="2-reload" src="https://cloud.githubusercontent.com/assets/190447/25151134/abfed28c-2484-11e7-8b91-a5a908f5354e.png">
<img width="512" alt="3-reload-again" src="https://cloud.githubusercontent.com/assets/190447/25151133/abfaec12-2484-11e7-9ca9-4f1bb2379d47.png">

**Comment by artf** [comment]
Thanks @jakzal I guess I already know where is the problem, so I'll ping you back when it's fixed

**Comment by jakzal** [comment]
That's brilliant, thanks! Let me know if I could do anything to help please.

**Comment by artf** [comment]
eh @jakzal let me know if it fixes the problem (you have to clean previously saved styles)

**Comment by jakzal** [comment]
I quickly gave it a go and unfortunately the problem is still there. What's worse is that components and related stylesheets disappear after few page refreshes. I've tried two approaches - loading html/css vs loading components/styles. Behaves really weird in both cases.

<img width="512" alt="screen shot 2017-04-19 at 22 44 33" src="https://cloud.githubusercontent.com/assets/190447/25201442/0b6d6be8-2552-11e7-9eb3-f0bd20ddded3.png">
<img width="512" alt="screen shot 2017-04-19 at 22 36 28" src="https://cloud.githubusercontent.com/assets/190447/25201443/0b6f7172-2552-11e7-8c6f-f8af48f04b9e.png">

**Comment by artf** [comment]
Thanks @jakzal for all details. I just pushed a new release which should fix disappearing issue.

Anyway, I'd like to point out that those CSS rules are coming from the default 'protectedCss' option which are styles injected inside the template but can't be modified by the user. You can eventually disable this option just by passing an empty string:
```js
grapesjs.init({
...
protectedCss: '',
...
})
```
At the moment, when you just loading html/css you have to empty 'protectedCss' as those rules are already stored inside you template.
Instead with components/styles, I'm just using your code and can't reproduce it :/ Can you please track changes in your localStorage?

**Comment by jakzal** [comment]
The problem seems to be fixed for local storage.

I first created the document:

<img width="512" alt="screen shot 2017-04-20 at 20 40 15" src="https://cloud.githubusercontent.com/assets/190447/25247099/24b5b78c-260a-11e7-83ed-e76ccd0a0fd6.png">

Then I refreshed the page and noticed it's shown as expected. Multiple page refreshes don't duplicate CSS definitions anymore:

<img width="512" alt="screen shot 2017-04-20 at 20 40 38" src="https://cloud.githubusercontent.com/assets/190447/25247098/2494fbb4-260a-11e7-8901-e21e9ced4a20.png">

Creating a new document when `protectedCss: ''` doesn't work as it's not possible to drop any component to canvas. 

Creating a new document when `protectedCss` is set to defaults, and then refreshing the page when it's set to an empty value, results in a messed layout (protectedCss definitions don't seem to be saved with the document):

<img width="512" alt="screen shot 2017-04-20 at 20 42 45" src="https://cloud.githubusercontent.com/assets/190447/25247358/e1a5cb70-260a-11e7-8b41-2e56f6dbf79f.png">

I'll follow up with remote storage.

**Comment by jakzal** [comment]
I can't seem to get the remote storage to work again. I'm getting an empty document after refreshing. Will try tomorrow again.

**Comment by artf** [comment]
thanks @jakzal the issue with `protectedCss` should be fixed. Honestly, I'd expect remote storage to work if it's work with the local one. Please let me know

**Comment by jakzal** [comment]
I have recently updated grapesjs and the problem is no longer there.

Thank you for all your hard work. The project is awesome!

**Comment by artf** [comment]
thanks to you @jakzal for your feedback
