### ISSUE TITLE
Top Border missing on some resizable elements

### ISSUE THREAD

**Issue by AustinTBiggs** [artf/grapesjs#734]
On a few resizable elements, the top outline seems to be missing. Is this a known issue? I can't seem to find any conflicting CSS.

![screen shot 2018-01-09 at 11 41 29 am](https://user-images.githubusercontent.com/930864/34737156-8d032b88-f532-11e7-995a-5ee6fe0522f5.jpg)

**Comment by ryandeba** [comment]
Hi @AustinTBiggs,

I've not seen this issue before, but perhaps others have and could assist. I'd be interested in looking into it if you wouldn't mind providing a bit more info - could you provide a jsfiddle and/or steps to reproduce? Do you see this issue in all browsers?

**Comment by AustinTBiggs** [comment]
This one makes me feel quite silly in hindsight.

The issue was the parent element's overflow property. The strange thing is that the top outline would show when it was only 1px thick, but none of it showed when it was 3px thick (hovering vs selecting). Which is why I thought this may have been a Grapes issue. However, Browsers just handle overflowing outlines strangely.
