### ISSUE TITLE
When resizing images in the same section, they all resize...

### ISSUE THREAD

**Issue by AustinTBiggs** [artf/grapesjs#735]
I'm encountering a strange bug, when resizing a single image, the sibling photo is **also** being resized. My only thought is around how the corresponding image is being resized. Perhaps the selector that Grapes is choosing is too vague?

![screen shot 2018-01-09 at 11 43 05 am](https://user-images.githubusercontent.com/930864/34737461-760849e4-f533-11e7-8f13-c11a741488cd.jpg)

**Comment by ryandeba** [comment]
Hi @AustinTBiggs,

I suspect that grapesjs is applying the height/width styles to a class which is applied to both images. Could you check to see if both images have the same class?

**Comment by artf** [comment]
Hey Austin, as suggested by Ryan, just remove the class

**Comment by AustinTBiggs** [comment]
@artf  - I can do that as a quick fix.

However, it seems counter-intuitive. Classes in CSS are meant to be re-used. If the "fix" is to remove the class, that seems to me that the issue is how Grapes deals w/ classes. I use classes on images (and other elements) for everything from animations to material shadows.

**Comment by artf** [comment]
Well yeah removing was just one of the options. You could for example adding another one or disabling (by clicking the checkbox) the current (without active classes you style a single component)
