### ISSUE TITLE
How to remove class from html

### ISSUE THREAD

**Issue by Deepak813** [artf/grapesjs#740]
Hi @artf,

We are updating the <i> tag class but it adds new class to this but previous class is not remove.please let us know how to remove class.

using this : 
editor.getSelected().set('attributes', {'class': 'newClass'});

Output:
<i class="fa fa-smile-o c2515" class="fa fa-address-book-o">

but "fa fa-smile-o" is not removed.

Look forward for positive response.

**Comment by ryandeba** [comment]
Hi @Deepak813,

Components have a `setClass` method that will remove all existing classes an replace them with the string of classes passed as the first argument. Try this:
`editor.getSelected().setClass('newClass');`

**Comment by Deepak813** [comment]
Hi @ryandeba,

Thanks for the message.

I have already used this but its showing following error:

----------editor.getSelected(...).setClass is not a function------------------

Please let us know how to remove this error to resolve this issue.

Thanks

**Comment by ryandeba** [comment]
@Deepak813 - The code I provided works just fine for me in the [demo](http://grapesjs.com/demo.html), so I suspect that there must be something about your configuration that is causing the issue. Could you make sure you're on the latest version of grapesjs and then create a [jsfiddle](https://jsfiddle.net/) that shows the problem if you're still having issues?

**Comment by artf** [comment]
yeap, `setClass` is available in latest versions
