### ISSUE TITLE
Choose order and visibility of Categories

### ISSUE THREAD

**Issue by JuanTincho** [artf/grapesjs#742]
Hey @artf , we need to be able to change the categories order and  visibility when the application starts. 

I was able to do it changing the model in the Category and this piece of code in BlocksView.js: 

```
if (category && this.categories) {
      if (typeof category.label == 'string') {
        category = {
          id: category.label,
          label: category.label,
          order: category.order,
          open: category.open,
        };
      }
```

...and setting the order in a flexbox property. 

I wanted to know if you think this is a good approach or you have another suggestion.

I'm willing to do a PR.

Thank you!

**Comment by artf** [comment]
I think that change in BlocksView is not necessary (at first look). If you pass the category as an object it will be added as it is with all its properties. If for a change you mean updating the view of the category with an `order` style (if exists) I'm ok with it
