### ISSUE TITLE
editor.getComponents() load multiple times when refreshed.

### ISSUE THREAD

**Issue by suchithmahadi** [artf/grapesjs#743]
Hello,
editor.getComponents().add('<div class="grid-stack" style="height:800px;"></div>'); 

adds multiple times when refreshed, how stop this. it should add only once.

**Comment by artf** [comment]
well if you `add`, the editor stores the template (local/remote), after refresh editor loads it and you still use `add`... well, it's a correct behavior.

**Comment by suchithmahadi** [comment]
is there a way to add only once.

**Comment by suchithmahadi** [comment]
@artf Is there a way to add only once ?

Thanks

**Comment by artf** [comment]
@suchithmahadi you just have to avoid it triggering twice, try to find the way to let you know when the content is new or loaded
```js
if (notYetLoaded) {
	editor.getComponents().add(...);
}
```
