### ISSUE TITLE
Make outer element unselectable

### ISSUE THREAD

**Issue by michaellwatson** [artf/grapesjs#744]
I'm trying to make the outer element not selectable, and the inner one selectable only
```
 editor.BlockManager.add('full-width',
    {
        category:'Sections', 
        label: 'Full Width',
        content: '<section class="row" data-gjs-droppable=".col" data-gjs-custom-name="Row" data-gjs-selectable="false" data-gjs-selectable="false">\n <div class="col col-lg-12 col-md-12 col-sm-12 col-xs-12 text-center" data-gjs-draggable=".row" data-gjs-custom-name="Col"></div>\n</section>',
    });
```
Outer element is the **section** tag and the inner one is the **div**, I need the section to be there for reasons, but I don't want it to be selectable

The data-gjs-selectable=false tag doesn't seem to be working for me, as the outer element is still selectable, I'd be grateful if anyone knew the correct syntax to achieve this, thanks

**Comment by artf** [comment]
Check here: https://jsfiddle.net/wswvuvab/2/
Seems to work properly (check your version), I added `data-gjs-hoverable="false"` property to prevent the highlighting box

**Comment by michaellwatson** [comment]
Must be my version then, because its still selectable/hoverable, but it does accept data-gjs-highlightable="false", thanks for your help again
