### ISSUE TITLE
preview in a dialog box

### ISSUE THREAD

**Issue by NorthstarTech** [artf/grapesjs#746]
@artf @ryandeba  Is that possible to preview(eye icon) the template in a separate dialog box? not in a editor. How can I do it?

**Comment by ryandeba** [comment]
@NorthstarTech 

[Here's](https://jsfiddle.net/j47savv4/) an example of "preview" and "stop preview" buttons outside the editor.

**Comment by artf** [comment]
I think Ryan's example explains everything
