### ISSUE TITLE
component:remove action

### ISSUE THREAD

**Issue by AustinTBiggs** [artf/grapesjs#748]
Going through the available events, I'm curious as to why there is no "component:remove" action?

I've taken the approach of triggering the action by modifying the `tlb-delete` action. I would assume there's a better way, I'm just not sure what that would be quite yet.

```
      defaultCommands['tlb-delete'] = {
        run: function run(ed) {
          var sel = ed.getSelected();

          if (!sel || !sel.get('removable')) {
            console.warn('The element is not removable');
            return;
          }

          ed.select(null);
          sel.destroy();
          
          em && em.trigger('component:remove', null);
        }
      };

```

**Comment by ryandeba** [comment]
I would also be interested in having a `component:remove` event 👍

**Comment by artf** [comment]
Added for the next release
