### ISSUE TITLE
upload image

### ISSUE THREAD

**Issue by BellaliNaoufel** [artf/grapesjs#75]
Hello, I have a problem when I try to download an image

XMLHttpRequest cannot load http://localhost/assets/upload. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:24689' is therefore not allowed access. The response had HTTP status code 405.

**Comment by artf** [comment]
Hi @BellaliNaoufel, seems like you problem is not related to GrapesJS but your server configuration. Try to use CORS with you scripts
