### ISSUE TITLE
How we can set the time and time zone in count down

### ISSUE THREAD

**Issue by Deepak813** [artf/grapesjs#750]
Hi @artf ,

Please let us know that how we can set the time and timezone in count down as it is important in countdown element.Also, we come to know that most of the template builder provide many functionalities with countdown element as compared to us.please find below the attached image for reference

![countdown](https://user-images.githubusercontent.com/33951403/34863162-f5074f58-f793-11e7-9c13-a970f3168637.png)

**Comment by artf** [comment]
Hi @Deepak813 first of all, this had to be open in countdown repository as it strictly related to it. Not by chance I call it `Simple countdown component` if you want something more just extend it or create a new one (the code is there if you want to copy). BTW with [options](https://github.com/artf/grapesjs-component-countdown#options) already available your able to use   [`datetime-local`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime-local)

**Comment by Deepak813** [comment]
Hi @artf ,

Thanks for the message.

Please let us know how we can set the dynamic Timezone so that user select timezone and time will be automatically changed according to selected timezone.

Also, timezone category are not showing in Countdown options.
