### ISSUE TITLE
Traits are in different tab

### ISSUE THREAD

**Issue by Deepak813** [artf/grapesjs#751]
Hi @artf,

We found that when we download the latest grapesJs package in that traits tab are showing in different and online demo shows the traits in same style manager.

Please let us know how to get the same online demo.
Also,find the attached image for reference:

![traits](https://user-images.githubusercontent.com/33951403/34863465-93f1d178-f795-11e7-9019-cff5256decd5.png)

**Comment by artf** [comment]
@Deepak813 You can find the snipper here https://github.com/artf/grapesjs/blob/gh-pages/demo.html#L1366-L1397

**Comment by Deepak813** [comment]
Hi @artf, 

With this reference link, i am not able to display the traits settings in style manager along with css settings.
Please help us to resolve this.
