### ISSUE TITLE
Help wanted : Search child models of domComponent

### ISSUE THREAD

**Issue by vishal5033** [artf/grapesjs#753]
Hello,

I have to change content of nth child model of component available in the editor. 
Lets say there is a table with 3 TR. every TR as TD and every TD has div with some content within in it. I want to replace that content with some other content. 

I have assigned some custom html tags to every div. How do i find that div from models and change the content such a way that model is updated. 

I have done this thing with JS, On the editor it is shown as new content but in Model it is showing old content.

Can you please help me out.

Thanks,

**Comment by artf** [comment]
@vishal5033 you can make use of `model.find('tr > td[something]')[0]`, in this way you get the model (use the [v0.12.60](https://github.com/artf/grapesjs/releases/tag/v0.12.60) as it fixes some stuff related to `find`)
