### ISSUE TITLE
Left and right Panel

### ISSUE THREAD

**Issue by punkt2** [artf/grapesjs#755]
Hi, 

for my project i need two panels, left and right, to show blocks/layers and style simultaneously.
The panel id is hard coded in the command view files (OpenBlocks, OpenLayers). It would be good if this is configurable.
I can do a pull request, but i am not sure, in which files I should put the configuration (panelId). 

@artf Can you give me a hint?

**Comment by artf** [comment]
I'd just add 
```js
attributes() {
    return this.model.get('attributes');
 },
```
in [PanelView](https://github.com/artf/grapesjs/blob/dev/src/panels/view/PanelView.js) and put some checks in `PanelView.render` (to avoid hard coded stuff), then when you create panels you just pass `attributes` key
```js
editor. Panels.addPanel({
	id: '...',
	attributes: { ... }
});
```
