### ISSUE TITLE
Problems trying to load and save

### ISSUE THREAD

**Issue by gordon-matt** [artf/grapesjs#759]
Could someone please let me know the required format of the response from the storage save action? I originally posted an issue under the mjml repo regarding this, but there's been no answer and moreover, I think it's probably more suited to be asked here in the main GrapesJS repo (as it pertains to GrapesJS in general and not just the MJML extension). The original post can be found here: [GrapesJS MJML Issue 54](https://github.com/artf/grapesjs-mjml/issues/54). I have made some progress, but as I said above, I am still confused as to the required response for the save action.

**Comment by gordon-matt** [comment]
I have updated the original issue with a workaround and made a suggestion. Feel free to close either this issue or the original under the MJML repo, as per your preference.

**Comment by artf** [comment]
Hi @gordon-matt and apologize for the late response. As you already get it, the store expects nothing, but [`onResponse`](https://github.com/artf/grapesjs/blob/dev/src/storage_manager/model/RemoteStorage.js#L58) callback is always executed therefore you get that error.
Probably just putting `typeJson && text && typeof text === 'string'` might solve the issue.
