### ISSUE TITLE
Require

### ISSUE THREAD

**Issue by goldengrisha** [artf/grapesjs#762]
Please help, how can I  require or import grapesjs-blocks-basic, not through <script/> tag?

**Comment by AustinTBiggs** [comment]
@goldengrisha - Can you clarify exactly what you're trying to achieve?

**Comment by goldengrisha** [comment]
for example if I want to include this plugin I need to add tag like this <script src="path/to/grapesjs-plugin-export.min.js"></script>
and then  plugins: ['gjs-plugin-export'], can it be achieved by import or require ?

**Comment by artf** [comment]
You mean something like this?!?
```js
import grapesjs from 'grapesjs';
import 'grapesjs-blocks-basic'; // <-- autoloads inside grapesjs instance

const editor = grapesjs.init({
	// ...
	plugins: ['gjs-blocks-basic'],
});
```

**Comment by goldengrisha** [comment]
thanks, found problem)
