### ISSUE TITLE
editor.on('block:drag:stop') event doesn't work

### ISSUE THREAD

**Issue by perfect-coders** [artf/grapesjs#765]
I am using this event many times in the application in the previous library. Now I have updated the library. 
I have updated the following libraries - 
1) Grapesjs Library
2) Grapesjs-Preset-Webpage Library
3) Grapesjs-Basic-Blocks Library

But it stops working now. Let me know if there is any change in this event.

**Comment by artf** [comment]
Hi @perfect-coders, with the latest version https://github.com/artf/grapesjs/releases/tag/v0.13.5 the HTML5 drag and drop is enabled by default (disableable by `nativeDnd` option) and unfortunately I wasn't able to keep such events with this approach. The new d&d module provides [similar functionality](https://github.com/artf/grapesjs/wiki/API-Editor#canvas) but now it's more generic, therefore `canvas:drop` will be triggered with any component drop (from blocks or any other OS source). 
So you have two options:
1. Keep the new d&d module and replace your old `block:drag:stop` events with something this
```js
editor.on('canvas:drop', (DataTransfer, model) => {
	// ... 
})
```
2. Disable the new module
```js
grapesjs.init({
	//...
	nativeDnd: false
})
```
Thanks for pointing this out, actually I'll update the changelog

**Comment by perfect-coders** [comment]
Thanks very much for the quick answer. I always love your quick feedback. 
I have some investment options for you. Hope to hear from you soon.

**Comment by cgatian** [comment]
This stumped me. The documentation is out of date
