### ISSUE TITLE
When clicking elsewhere on canvas, deselect: currently selected

### ISSUE THREAD

**Issue by AustinTBiggs** [artf/grapesjs#766]
Currently, once a user selects any element, there's no way to deselect that element.

For example, if I'm editing a photo, but I want to "stop editing" the photo, there's no way to remove the selection from the photo (clicking on a non-editable element or the page background). 

`editor.select( null );`

**Comment by artf** [comment]
Hi Austin, can you explain which is your issue with a selected component? I've seen a lot of builders with the same behavior so honestly, I don't see it as a problem.
By the way, I think you could implement something on your own, with `editor.select()` you deselect the component
