### ISSUE TITLE
Generate a new grapes.min.js after make changes to grapes.js

### ISSUE THREAD

**Issue by frank-tenzing** [artf/grapesjs#767]
Hi guys - happy new year,

I'm currently doing some investigation of GrapesJs for our further project.

The question is I fellow the https://github.com/artf/grapesjs/issues/196 to minify a new grapes.min.js, but when I deleted the grapes.min.js and tried to make some change in the grapes.js which is in the dist folder, for example, changed the logic in the **removeClass** function:

 `function removeClass(v, c) {
    if (v.classList) {
      v.classList.remove(c);
    } else {
      if (v.className instanceof SVGAnimatedString) {
        // doing something
      } else {
        v.className = v.className.replace(c, "");
      }
    }
  }`

, and then run the command `npm run build` to generate a new grapes.min.js, but the modifications were reverted back to what it was after running that command:
`function removeClass(v, c) {
    if (v.classList) {
      v.classList.remove(c);
    } else {
      v.className = v.className.replace(c, "");
    }
  }`

how can I make the changes come into effect in the grapes.min.js after making changes to **grapes.js** ? Any other config change should I make? Thank you very much!

**Comment by artf** [comment]
@frank-tenzing you shouldn't edit files in the `dist` folder, those are generated every time by `npm run build` You have to edit files inside `src`.
BTW that code seems to come from cash library, not grapesjs itself (about the issue let's keep talking here #768 )
