### ISSUE TITLE
IE browser issue

### ISSUE THREAD

**Issue by frank-tenzing** [artf/grapesjs#768]
Hi @artf ,

Created this issue due to https://github.com/artf/grapesjs/issues/214 has been closed ...

I cloned the latest repo and run it on IE 11, an error: 
`SCRIPT438: Object doesn't support property or method 'replace' - grapes.min.js (15612,7)` 
demonstrates on the console, when I clicked it, it jumped to the line in 'removeClass' function:
`  function removeClass(v, c) {
    if (v.classList) {
      v.classList.remove(c);
    } else {
      v.className = v.className.replace(c, "");
    }
  }`
The 'v.className' was '**SVGAnimatedString**' type when I debug it, but there is no `replace` function for that type. What is supposed to do here and When will this function be called ? Thank you very much!

**Comment by artf** [comment]
@frank-tenzing not sure if it's IE's only error,  are you facing this issue with some kind of template (which probably contains some SVG element)?

**Comment by frank-tenzing** [comment]
Hi @artf , what I have done after cloned the latest repo are 
1). Replaced the start script with `"start": "webpack-dev-server --open --progress --colors & npm run build:css -- -w",;` 
2). Commented the 
**editor.BlockManager.add('testBlock', {
        label: 'Block',
        attributes: { class:'gjs-fonts gjs-f-b1' },
        content: `<div style="padding-top:50px; padding-bottom:50px; text-align:center">Test block</div>`
      })**
in **index.html**; 

Then when I run it on IE 11, `SCRIPT438: Object doesn't support property or method 'replace'`, `grapes.min.js (15612,7)` is showing on the console. 
`  function removeClass(v, c) {
    if (v.classList) {
      v.classList.remove(c);
    } else {
      v.className = v.className.replace(c, "");
    }
  }`

And when I debugged it, `v.className` parsed as **SVGAnimatedString**.

**Comment by artf** [comment]
@frank-tenzing thanks, but what about other browsers?

**Comment by frank-tenzing** [comment]
@artf It is working fine with Chrome, but IE is the primary browser our client prefer to use.

**Comment by artf** [comment]
That snippet is from cash library and I think it's related to https://github.com/kenwheeler/cash/issues/131
BTW we could patch it internally in https://github.com/artf/grapesjs/blob/dev/src/utils/extender.js#L104
probably by doing this https://stackoverflow.com/questions/12588913/svganimatedstring-missing-method-indexof#answer-12592009

**Comment by TheHermitKhan** [comment]
Any progress on this fix?
It seems we are having the same issue, and most of our users use IE11+.

**Comment by TheHermitKhan** [comment]
after using the boilerplate to start my plugin I was able to get GJS to work in all browsers.

**Comment by sagardoke** [comment]
Still failing in IE11 with the latest update (0.14.6)
Not able to add (drag and drop) elements to canvas. Works fine in Chrome/Firefox.

Getting following errors:

![image](https://user-images.githubusercontent.com/19753596/37580729-84204720-2b02-11e8-9071-2713d3f38a98.png)

**Comment by sagardoke** [comment]
Thank you @artf
After latest changes, I'm able to add elements to canvas, works very well.
But now, I'm facing another issue.
As soon as I select element in canvas, my IE 11 hangs with following error:

![screenshot_20180401_120022](https://user-images.githubusercontent.com/19753596/38176507-ff113460-35a4-11e8-8fbb-b3a41d533dd8.png)
