### ISSUE TITLE
Custom attribute

### ISSUE THREAD

**Issue by goldengrisha** [artf/grapesjs#770]
Can it be possible to create a custom attribute ?

**Comment by artf** [comment]
@goldengrisha a little bit more specific?!?

**Comment by goldengrisha** [comment]
I want to have ability to add a few attributes with values like(move='0') and edit after in editor, can it be ?

**Comment by artf** [comment]
@goldengrisha I apologize, but are you talking about adding custom attributes to HTML element or Component models?

**Comment by goldengrisha** [comment]
sorry for my unclearing question, yes

**Comment by artf** [comment]
@goldengrisha `yes` what? 😂  custom attributes to HTML element or Component models?

**Comment by goldengrisha** [comment]
HTML

**Comment by ryandeba** [comment]
I'm a little confused here too, but it sounds like maybe you just need to add a [trait](https://github.com/artf/grapesjs/wiki/Traits). Adding something like this to your component will expose a trait in the component settings that should get set as an HTML property:
```
...
traits: [{
    type: 'number',
    label: 'Move',
    name: 'move'
}],
...
```

**Comment by goldengrisha** [comment]
yes, I've figured out with it, the problem was when I create custom trait it always saves into storage and can't see new traits, that's why I asked about html attrs. Thank you!
