### ISSUE TITLE
Image src is not updating

### ISSUE THREAD

**Issue by Deepak813** [artf/grapesjs#771]
Hi @artf,

I have updated the image src using below code:
editor.getSelected().set('attributes', {'src': image_Url});

but when i set all the html using below code:
editor.setComponents(templateHTML);
then image src not updating in HTMLcomponent.

Please let us know about the same.

**Comment by ryandeba** [comment]
Hi @Deepak813,

I'm not sure where `templateHTML` is coming from in your example...is the `src` on your image set correctly in that variable?

In any case, selecting an image and running this code seems to work fine for me in the [demo](http://grapesjs.com/demo.html): `editor.getSelected().set("src", "http://via.placeholder.com/350x150")`

**Comment by artf** [comment]
@Deepak813 as already mentioned by Ryan you have to use `editor.getSelected().set('src',  src)`

**Comment by AkibDeraiya123** [comment]
@ryandeba @artf 
Is there any possibilities to change other attributes of image like class, id etc?
I had tried with like,
```
// For id
editor.getSelected().set('id',imageId)
// For class
editor.getSelected().set('class',imageClass)
```
But this seems not working in my case.
Can you guys please help me how can i change other attributes of this image tag?

**Comment by artf** [comment]
@AkibDeraiya123 All available methods are here: https://grapesjs.com/docs/api/component.html
