### ISSUE TITLE
trait validation

### ISSUE THREAD

**Issue by krunal039** [artf/grapesjs#772]
Is there way to restrict trait length i.e title cannot be more than 255 chars and if user try to add more than that, should display error message?

**Comment by ryandeba** [comment]
Hi @krunal039,

The only way I know to do something like would be to make a [custom trait](https://github.com/artf/grapesjs/wiki/Traits#define-new-trait-type) and use the `getInputEl` function to either set a `maxlength` property on your input or create a section show whatever errors that you want.

**Comment by artf** [comment]
> The only way I know to do something like would be to make a custom trait 

Correct

**Comment by krunal039** [comment]
@ryandeba @artf , thanks for reply, is there way to pass property(max length, validation error message) to custom traits?

**Comment by artf** [comment]
@krunal039 with custom traits you define the DOM so you can create whatever you want (look at th example there)
