### ISSUE TITLE
Multiple editors in the same window

### ISSUE THREAD

**Issue by kevinalvarez** [artf/grapesjs#773]
Hi all!
I'm trying to initiate several editors in the same window. I think almost everything is working great (edition, saving, adding components, etc), but when I open "view code" modal, I see css duplicated.
Doing a little research, I noted that inside method loadModule, there's a line "if (Mod.onLoad) this.get('toLoad').push(Mod);" where "toLoad" attribute is adding all the modules from every editor initated. These modules are used later to add the styles inside css code.
this.get('toLoad').forEach(function (module) {
      module.onLoad();
    });

![2018-01-17_17-52-56](https://user-images.githubusercontent.com/4283762/35071624-5ae2e976-fbaf-11e7-9aa3-e015458ea0ad.png)

Is there a way to get over this problem? Now, I'm setting the style (editor.setStyle(xxx)) again once all the editors are initiated (and it's working fine, but I think there might be a better solution)

I appreciate any idea.

Thanks!

**Comment by artf** [comment]
Thanks @kevinalvarez probably I get where the issue, I'm gonna push soon a fix.

**Comment by kevinalvarez** [comment]
Thanks @artf ! I made the change and now it's working as expected. We will wait for the release.
