### ISSUE TITLE
Dynamic classes not generated automatically on child divs or span in new library

### ISSUE THREAD

**Issue by ajaysofto** [artf/grapesjs#777]
Hi artf,
 I am using new library of grapes but in newer library dynamic classes are not generated automatically on child cell like "c3130 etc". These classes are only applied to parent div not the inner div under that one. what we have to do to apply these custom classes on every divs that are in an elements.

**Comment by ajaysofto** [comment]
Hi artf,
Its urgent,please reply as soon as possible as we are struck in the middle of the tasks.

Hope for positive response.

**Comment by artf** [comment]
> Its urgent,please reply as soon as possible as we are struck in the middle of the tasks

PRs are welcome...
