### ISSUE TITLE
After setting background color no element is draggable

### ISSUE THREAD

**Issue by Deepak813** [artf/grapesjs#779]
Hi @artf,

We have found that when we set background color of any element then no other element is draggable.

This is the serious issue exists in latest library as well as the new grapes version downloaded.
I am using latest version i.e /*! grapesjs - 0.13.5 */

Thanks

**Comment by ryandeba** [comment]
Hi @Deepak813,

I'm tried recreating this in the [demo](http://grapesjs.com/demo.html) (which currently uses version 0.13.5) but I have not been able to recreate it. Could you test there and provide steps to reproduce the bug? Or could you create a jsfiddle that demonstrates the issue?

**Comment by Deepak813** [comment]
Hi @ryandeba,

Thanks for the message,

Please find below the attached video link of reproducing the bug:
https://vimeo.com/251763933

This error exists in using color picker anywhere in the website.

**Comment by artf** [comment]
@Deepak813 yeap, seems like the [colorpicker](https://github.com/artf/grapesjs/blob/dev/src/utils/ColorPicker.js) breaks the drag event attached to blocks

**Comment by ryandeba** [comment]
@Deepak813 Thanks for the video! I only tried dragging existing components, not blocks.

**Comment by Deepak813** [comment]
Hi @artf, @ryandeba,

Thanks for the message.

Yes,right drag event breaks when colorpicker is selected.

Is this issue in correction process or resolved soon?

**Comment by artf** [comment]
Ok I think I found it
spectrum tries to unbind its custom events with this
https://github.com/artf/grapesjs/blob/dev/src/utils/ColorPicker.js#L1218
but the patched [`unbind `](https://github.com/artf/grapesjs/blob/dev/src/utils/extender.js#L228) is unable to receive objects 😬

**Comment by Deepak813** [comment]
Hi @artf,

Thanks for the message.

We also try to look into this.
