### ISSUE TITLE
[QUESTION] Removing certain css

### ISSUE THREAD

**Issue by RiyaThete** [artf/grapesjs#783]
## QUESTION
My site consists of various webpages like home-page, category-page, results-page etc. The css for all the pages are in a single css file (all.css).
I am trying to load a single webpage (results-page) for editing by using the import plugin.
Without making any changes I exported the html and css by using export plugin.
I noticed that the 'certain' css properties of pages besides results-page are missing in the exported css.

I want to make few css changes in the results-page and replace the exported css file with my existing all.css . But I am unable to do so because certain css properties are deleted.

Someone please help me resolve this issue.

**Comment by JulyanoF** [comment]
You can put your css inline like this:
```
<div id="gjs" class="overflow-y max-height-50vh">
    <style>
        img {
            width:100%;
        }
    </style>
</div>
```
Or import a .css file, like this:
```
grapesjs.init({
container : '#gjs',
canvas: {
        styles: [
            'all.css'
        ]
    }
});
```
