### ISSUE TITLE
Uncompressed Grapesjs code

### ISSUE THREAD

**Issue by lypliuyinping** [artf/grapesjs#784]
Hello, I am a graduate student, I would like to study in detail Grapesjs, if convenient, can I share Grapesjs uncompressed source? I will be very grateful to you!

**Comment by artf** [comment]
Sure

**Comment by lypliuyinping** [comment]
Will you send it to my mailbox? Or share as a link?

**Comment by artf** [comment]
@lypliuyinping everything you need is inside [`src`](https://github.com/artf/grapesjs/tree/dev/src) folder
