### ISSUE TITLE
make a button component

### ISSUE THREAD

**Issue by lypliuyinping** [artf/grapesjs#785]
Hello, I want to do a button component, click on the button, it will pop up a dialog box that contains some text boxes and OK and Cancel button, click OK and Cancel button will perform different functions, may I ask how to achieve this? Thank you for your answer

**Comment by JulyanoF** [comment]
Hello @lypliuyinping 
You can create custom blocks like this:

```
var customBlock = {
            label: 'Button',
            attributes: {
                class: "gjs-fonts gjs-f-button"
            },
            content: "<button class='btn btn-success' >Button</button>",
            id: "myButtonId"
        };
editor.BlockManager.add(customBlock.id, customBlock);
```

**Comment by lypliuyinping** [comment]
@JulyanoF  Firstly, thank you very much for your reply! Then, I would like to ask, how to achieve the button click event? For example: Click the button to bring up the text box.

**Comment by JulyanoF** [comment]
Are you using bootstrap? Or another js lib to create a dialog box?

**Comment by artf** [comment]
Probably you're looking for [Components with JS](https://github.com/artf/grapesjs/wiki/Components-&-JS)

**Comment by VM8198** [comment]
@lypliuyinping  have you solved this...?
I am also stuck on this
