### ISSUE TITLE
How to get the next and previous models/elements of selected element

### ISSUE THREAD

**Issue by perfect-coders** [artf/grapesjs#786]
I am cloning an element.  I want to get the next element or previous element. By this I mean to say that How can I get the model or How should I give some custom attribute to the cloned element. 

Thanks in Advance.

**Comment by JulyanoF** [comment]
When you say "element", you are talking about blocks? Like button, text, section...?

**Comment by perfect-coders** [comment]
yes

**Comment by artf** [comment]
Here is an example of getting a previous model and updating it with new attributes
```js
const sel = editor.getSelected();
const coll = sel.collection;
const index = coll.indexOf(sel);
const prevModel = coll.at(index - 1);
prevModel && prevModel.set({ 
	attributes: { ... }
});
```
