### ISSUE TITLE
html conditional comment

### ISSUE THREAD

**Issue by ghena** [artf/grapesjs#787]
Hi Guys,

I dont understand how save ad load conditionl html comment for e.g:
            
            <table align="center" border="0" cellpadding="0" cellspacing="0" class="full-width" style="max-width: 650px;" width="100%">
                <tr>
                    <td mc:allowdesigner="" mc:allowtext="" mc:edit="date" style="font-family: Arial, Tahoma, sans-serif; color: #000000; font-size: 10px; padding: 20px;">

                    </td>
                </tr>
            </table>
            

when i save using editor.store() html is without comments.
Is possible allow this kind of comments ?
thanks in advance. 
regards.

**Comment by artf** [comment]
You have to create the comment component #208
