### ISSUE TITLE
getComponents doesn't return components

### ISSUE THREAD

**Issue by Geczy** [artf/grapesjs#789]
It's as if it's not parsing down the DOM

Reproduce. View console log
https://codesandbox.io/s/lxl7x2mnq

![image](https://user-images.githubusercontent.com/1036968/35294132-d5108cd8-0043-11e8-9af9-abbd4408f195.png)
You can see there are way more than 5 components / models in this sandbox.

But console log only shows 5
![image](https://user-images.githubusercontent.com/1036968/35294127-d0c84832-0043-11e8-8322-76a85e6c9247.png)

If I add one to the root of the dom tree, it will show 6. But if I add one to a child component, it will not see it.

Try  dragging Link or any other component around in several places until you see the issue

**Comment by artf** [comment]
@Geczy probably I've to update the description, but `getComponents` just returns wrapper's components (with its children), if you want to return an array of all components you can do this:
```js
const getAllComponents = (model, result = []) => {
	result.push(model);
	model.components().each(mod => getAllComponents(mod, result))
	return result;
}
const all = getAllComponents(editor.DomComponents.getWrapper());
```

**Comment by Geczy** [comment]
Works great, thanks
