### ISSUE TITLE
Is it possible to separete text editor from block?

### ISSUE THREAD

**Issue by JulyanoF** [artf/grapesjs#790]
I'm trying to separete a text editor from block, something like it:
![image](https://user-images.githubusercontent.com/17284704/35334428-862385d8-00f9-11e8-8252-006fe10afd55.png)

Is it possible?

**Comment by artf** [comment]
@JulyanoF sure, you can create a custom Trait (eg. textarea which, on render, initializes with some custom RTE) and on update change the component `content`

ps: please, next time, follow the issue template
