### ISSUE TITLE
Adding new button in toolbar

### ISSUE THREAD

**Issue by lauragadea** [artf/grapesjs#791]
Hello,

I am trying to add a new button to the toolbar of all the components. I been able to add for each component separatly, but not for all of them at once.
To note that I want to avoide modifying the file ‘src/grapesjs/dom_components/model/Component.js’

Is there a way to do that?

Thank you in advance for yur help!

**Comment by JulyanoF** [comment]
@lauragadea , please check #266

**Comment by lauragadea** [comment]
Yes @JulyanoF , I already have. And it suggests modifying the files ‘src/grapesjs/dom_components/model/Component.js’. That is exactly what I am trying to avoid.

**Comment by artf** [comment]
@lauragadea probably you should try to [extend](https://github.com/artf/grapesjs/wiki/Components#update-component-type) default component types (eg. `default`, `image`, `text`, etc.)

**Comment by mailtopaul8** [comment]
Hi,

I added a new button in the toolbar for adding new sections successfully but I need to place that tool alone at the bottom of the section (as per attached screenshot). Can you please let us know how to achieve this?
![new_section](https://user-images.githubusercontent.com/46489615/55604573-1de48980-578e-11e9-91de-e524b920228a.png)


Thanks.

**Comment by artf** [comment]
@mailtopaul8 I think it would be better to rely on custom component view #1827

**Comment by umerrinayat** [comment]
@lauragadea Hi, I need to add new element in toolbar whenever it is a anchor tag. Can you please share how did you implemented that for each component separately? Thank you
