### ISSUE TITLE
Script property using function don't work with blocks

### ISSUE THREAD

**Issue by alvimm** [artf/grapesjs#792]
In [Components & JS](https://github.com/artf/grapesjs/wiki/Components-&-JS) docs there's this example:

```
editor.BlockManager.add('test-block', {
  label: 'Test block',
  attributes: {class: 'fa fa-text'},
  content: {
    script: "alert('Hi'); console.log('the element', this)",
    // Add some style just to make the component visible
    style: {
      width: '100px',
      height: '100px',
      'background-color': 'red',
    }
  }
});
```

This works perfectly. But I couldn't use a function instead of a string in `script`, as is said it's supported like this example:
```
editor.BlockManager.add('test-block', {
  ...
  content: {
    script: function () {
      alert('Hi');
      console.log('the element', this);
    },
    ...
  }
});
```

It won't happen anything. The documentation isn't very clear about using scripts in blocks or components.

**Comment by artf** [comment]
Find where is the issue, it will be fixed in the next release

**Comment by chiqui3d** [comment]
@artf These changes when they will be published?

**Comment by artf** [comment]
@chiqui3d should be fixed

**Comment by selcukcura** [comment]
Hi @artf, I'm still having this issue even though I'm using the latest build (0.14.61). 

I know you mentioned it should be fixed, but Is this still a known issue?

**Comment by artf** [comment]
> I know you mentioned it should be fixed, but Is this still a known issue?

@selcukcura not really Selcuk, it should be fixed so probably you're facing some kind of new regression. It'd be great if you could create a new issue with a reproducible demo. Thanks
