### ISSUE TITLE
[QUESTION] How to create a custom option in toolbox?

### ISSUE THREAD

**Issue by JulyanoF** [artf/grapesjs#794]
I would like to know how can I create a custom "option" with custom content in this place:
![image](https://user-images.githubusercontent.com/17284704/35350873-653f77aa-0126-11e8-86ba-78f1ad836791.png)

**Comment by artf** [comment]
This is just a default [Panel](https://github.com/artf/grapesjs/wiki/API-Panels) with 3 buttons where each button triggers its own command
[OpenStyleManager](https://github.com/artf/grapesjs/blob/dev/src/commands/view/OpenStyleManager.js)
[OpenTraitManager](https://github.com/artf/grapesjs/blob/dev/src/commands/view/OpenTraitManager.js)
[OpenBlocks](https://github.com/artf/grapesjs/blob/dev/src/commands/view/OpenBlocks.js) <- being the last modified, use this as a starting point
So if want to add a new button there you can use this
```js
editor.Panels.addButton('views',{ // `views` is the panel's id
    id: 'yourBtnID',
    className: 'someClass',
    command: 'yourCommand',
    attributes: { title: 'Some title'},
})
```
