### ISSUE TITLE
editor.getSelected() in run:open-assets

### ISSUE THREAD

**Issue by chiqui3d** [artf/grapesjs#795]
Hello!
I want without having to create a new block button, and stopping the event associated to the image that this `run:open-assets` get the area created by the editor in the canvas and add there the image that I got with my personalized modal image.
I want to clarify that when I double-click on the image inside the canvas and select the image from my image manager it is updated correctly with `editor.getSelected()`, but when I add it from the block panel, it doesn't get the select object and gives me an error: don't find the `getSelected` function.

```
editor.on('run:open-assets', function(){
	editor.Modal.close();
	window.send_to_editor = function(src) {
		editor.getSelected().set('src',src)
		editor.getSelected().set('srcset',src)
		tb_remove();
	}
});
 ```

Is there any other way to solve this?

**Comment by chiqui3d** [comment]
I'm giving it a lot of thought, and I can't get the component added or selected image added when I use' run: open-assets', because it actually adds a tag image, but it doesn't get it.

**Comment by artf** [comment]
Apologize @chiqui3d but try to elaborate better, because I didn't get a single statement of what you're asking

**Comment by chiqui3d** [comment]
Yes @artf , you're right, I just updated it, I hope it's understood now.

**Comment by artf** [comment]
If you're working with a custom asset manager take a look here #491

**Comment by chiqui3d** [comment]
thanks @artf , but now I have another error:

`Uncaught TypeError: Cannot read property 'set' of null`

And this is the complete code:

```
editor.Commands.add('open-assets', {
     run(editor) {
	editor.getSelected().set('src',"http://via.placeholder.com/350x150");
		}
});
```
It only happens when I drag the image block, editing the image does it well.

**Comment by artf** [comment]
Pay attention to the [current command](https://github.com/artf/grapesjs/blob/dev/src/commands/view/OpenAssets.js) 
Your command should be something like this
```js
editor.Commands.add('open-assets', {
     run(editor, sender, opts = {}) {
		// Here you call your custom asset manager, for example
          someCustomeManager.open({
                 onImageSelect(url) {
                    // update the selected component
                    opts.target.set('src', url);
                    ...
                 } 
          })
     }
});
```
