### ISSUE TITLE
Can't drag component into canvas after styled element is cloned

### ISSUE THREAD

**Issue by kickbk** [artf/grapesjs#796]
Go to any of the demo, select a text box, give it a background color. Clone it. Then try to drag in another text component and it doesn't let you.

**Comment by artf** [comment]
@kickbk I can't reproduce it, but I think I'm doing something wrong, can you provide a screencast/gif of the behavior? (or anyone who faces the same issue)
Thanks

**Comment by kickbk** [comment]
![2018-01-25 09 44 28](https://user-images.githubusercontent.com/31323376/35403505-c4a25314-01b4-11e8-939c-12ab86614813.gif)

**Comment by artf** [comment]
Thanks @kickbk now I get it. It was already fixed here #779 and will be available in the next release
