### ISSUE TITLE
[Bug]: Using postcss-cssnext in webpack results in an error when importing dist/css/grapes.min.css

### ISSUE THREAD

**Issue by larshisken** [artf/grapesjs#800]
Hi

We're using postcss-cssnext plugin in our webpack project. Importing the grapes.min.css results in the following error:

```
ERROR in ./node_modules/grapesjs/dist/css/grapes.min.css
Module build failed: Error: Lexical error on line 1. Unrecognized text.
100% - $canvasTop
-------^
```

**Comment by ericscottmarquez** [comment]
I also get this error trying to compile sass files with references to other files in a react app on rails using the webpager gem. Did you find a solution?
