### ISSUE TITLE
[Question]: What is the first available event?

### ISSUE THREAD

**Issue by AustinTBiggs** [artf/grapesjs#805]
I have a quick question in regards to events. From what I can tell `load` is the first event that triggers when initializing Grapes. Am I correct?

I ask because I'm creating a loading animation for my installation of grapes and need the earliest event that fires during initialization. I've reviewed other events and wasn't sure if there's a command that gets triggered before `load` that would allow me to use `run:{commandName}`

**Comment by artf** [comment]
Yeah, `load` is the event to use for your case
