### ISSUE TITLE
Help with update information in Countdown

### ISSUE THREAD

**Issue by GoodPHP** [artf/grapesjs#807]
I use "grapesjs-component-countdown" and when i chose date in calendar update information in the plugin.

Example:  https://monosnap.com/file/sSOQJ3M4hxVRQgj008Kl302GtXu1ah

Use something like that:

change: function() {
			console.log(editor.trigger('change:startfrom'));
			editor.DomComponents.render();
}

Please help :)

**Comment by artf** [comment]
Try with this
```js
change: function() {
	editor.getSelected().trigger('change:startfrom')
}
```

**Comment by GoodPHP** [comment]
Not, it not help.

**Comment by GoodPHP** [comment]
Do you have any idea?

**Comment by GoodPHP** [comment]
I found:

editor.getSelected().attributes.startfrom = e.sender._oldText;
editor.getSelected().trigger('change:startfrom');
