### ISSUE TITLE
[Question] Create space where component would drop

### ISSUE THREAD

**Issue by AustinTBiggs** [artf/grapesjs#808]
As mentioned in the title (which may be a bit confusing), I'm curious about how to create a space where component would drop. This is very common in implementations of dragging/sorting I've seen. (eg. https://shopify.github.io/draggable/ and jQuery Sortable)

From what I understand of the drop placeholder (green bar in attachment), it's in a separate "Layer" and actually lives outside the canvas. I want to implement a better drop placeholder, I'm just not sure where to start when implementing this.

I have a similar request open regarding the DRAG placeholder, however, I'm speaking about the DROP placeholder in this issue. 

The following code doesn't return what I would expect either...
```
editor.on('sorter:drag:start', (src, srcModel) => {
	console.log( 'src: ', src );
	console.log( 'srcModel: ', srcModel );
})
```

![screen shot 2018-01-26 at 12 03 04 pm](https://user-images.githubusercontent.com/930864/35455971-34cff812-0291-11e8-9cf7-aa6c0b712b82.jpg)

**Comment by artf** [comment]
> From what I understand of the drop placeholder (green bar in attachment), it's in a separate "Layer" and actually lives outside the canvas. I want to implement a better drop placeholder, I'm just not sure where to start when implementing this.

Exactly and the reason behind this approach is better performances (less DOM manipulations) and IMHO less confusing, so I don't have any valid reason to start working on this feature.
If you want to start by yourself I think [onMove](https://github.com/artf/grapesjs/blob/dev/src/utils/Sorter.js#L356) method from the Sorter is a good start

**Comment by alimajed93** [comment]
Hello @austinbiggs ,

I am interested in the feature you mentioned above, so any updates? Did you start and manage to do it?

Thank you.

**Comment by FawadOmerEsk** [comment]
Hello @austinbiggs,

I'm also interested. Did you get it done or you'll be needing some support?

TIA.

**Comment by bogdansmadici** [comment]
Hello @austinbiggs, any updates about this? 

Thank you!
