### ISSUE TITLE
[Bug]: CSS not added when blocks are drag and dropped after core:canvas-clear command invoked

### ISSUE THREAD

**Issue by maxtacco** [artf/grapesjs#809]
I'm using grapesjs-blocks-basic plugin that has a number of column blocks. When I drag and drop these blocs onto the canvas they are displayed correctly for the first time and I can see the associated CSS added in the code viewer. But, once I invoke 'core:canvas-clear' command and drag-and drop the same blocks they are not displayed in canvas correctly anymore and CSS is missing in the code viewer.

It looks like 'e.CssComposer.clear();' call in the 'core:canvas-clear' command causes this issue.

GrapesJS version: 0.13.5/0.13.8

**Comment by artf** [comment]
I just merged https://github.com/artf/grapesjs-blocks-basic/pull/4  which solves the issue. I'll publish soon a new release of the plugin

**Comment by artf** [comment]
Done https://github.com/artf/grapesjs-blocks-basic/releases/tag/v0.1.3

**Comment by maxtacco** [comment]
Thank you!
