### ISSUE TITLE
What Can Go in <div id="gs">?

### ISSUE THREAD

**Issue by craigcecil** [artf/grapesjs#81]
I'm a little confused about what type of elements can go inside of the <div id="gs"> container?

I see the HTML markup elements and embedded style rules can go there, but what about a <body> tag?

Currently, we have a web page template that uses a stylesheet that defines many rules off of a body attribute setting, so I think I would need to add the body element inside the gs container or modify the style rules to somehow eliminate the body selector.

**Comment by artf** [comment]
I think your web page templates will work without any changes. Consider `<div id="gjs">` just as a `<body>` tag, so you can put there whatever you want. I just don't recommend adding `<script>` as it might break stuff
