### ISSUE TITLE
[QUESTION] CSS Gets deleted

### ISSUE THREAD

**Issue by RiyaThete** [artf/grapesjs#811]
I have a website with multiple web pages (results-page, category page, home page) and a common css file for all pages (all.css).Within this css file : webpage (classes used)
Home page ( class A, class B , class C)
Results Page ( class B, class X, class Y )
Category page ( class R, class S , class X)

When I load results-page in grape.js' editor using import plugin, I copy the entire all.css file and place it at the top of results Page in <style> tag. Without making any changes I exported the zip using export plugin and I noticed that the css file within zip has only following classes : A,B,X,Y Which means it has classes combined from all 3 pages but it deleted few classes[ unable to understand why so ] . My expected result was : it will have all the classes of all the webpages (A,B,C,R,S,X,Y).

I want to upload the css of entire website, make few changes in the css of a particular webpage and then replace the original css with downloaded css.

Please help me solve it.

**Comment by JulyanoF** [comment]
@RiyaThete to load css into editor, you need to insert it on grapesjs init, something like that:
```
var editor = grapesjs.init({
   [...]
    container : '#gjs',
    canvas: {
        styles: [
            'http://url.to/file.css'
        ]
    }
});
```
Or if you want to include css inline:
```
<div id="gjs" class="overflow-y max-height-60vh">
    <style>
    my-class{
        color: red;
    }
    </style>
</div>
```

**Comment by artf** [comment]
> deleted few classes[ unable to understand why so ]

Not used classes are not rendered

The suggestion proposed by @JulyanoF is the valid one

> it just loads all of the results page and few classes from other pages

You can use as many styles you need 
```js
styles: [ '..file1.css', '..file2.css', ...]
```
