### ISSUE TITLE
Layers Manager doesn't work with several editors

### ISSUE THREAD

**Issue by kevinalvarez** [artf/grapesjs#812]
Hi again!
As I comment in a previous question, We're working with several editors in the same window. The issue we're facing now is that layer manager doesn't work fine when I go from one editor to another. These are the steps that make this problem happens:
1. Editors initiated
2. Go to Layer Manager inside editor 1 (click on layers icon) - everything ok

![layergrapes1](https://user-images.githubusercontent.com/4283762/35477045-27af79e8-0389-11e8-98b4-3735960ebfca.png)

3. Open editor 2 and click on layers icon - looks like this:
![layergrapes2](https://user-images.githubusercontent.com/4283762/35477055-605ae656-0389-11e8-96d0-fa7e31500406.png)

I saw that the library is adding the prefix "gjs-" on components that already have this prefix:
![layergrapes3](https://user-images.githubusercontent.com/4283762/35477097-27da3e48-038a-11e8-9b18-76cf10b57d74.png)

To fix it provisionaly, I changed this line inside javascript code "config.layers.stylePrefix = config.stylePrefix + lyStylePfx;" to "if (lyStylePfx.substring(0,4) != "gjs-") config.layers.stylePrefix = config.stylePrefix + lyStylePfx;".
With this now it's working fine, but there may be a better solution.

Please, let me know if there is another way. Thanks!

**Comment by artf** [comment]
Thanks Kevin, I've found the issue and the fix will be available in the next release
