### ISSUE TITLE
Image upload in Newsletter Demo

### ISSUE THREAD

**Issue by atuleshK** [artf/grapesjs#82]
Hi there,
I have integrated grapesjs into my project to design newsletter template, When I try to upload an image from my local system it doesn't work at all. Can you please help me out with this. Thanks in advance.

**Comment by artf** [comment]
Did you load the image editor itself?
```html
<script src="//feather.aviary.com/imaging/v3/editor.js"></script>
```
Any error in console?

**Comment by artf** [comment]
any update @atuleshK?

**Comment by madhavbc** [comment]
how to upload image locally. does this post HttpPostedFileBase or string?

**Comment by artf** [comment]
You have to pass the url upload in assetManager
```js
grapesjs.init({
  ...
  assetManager: {
    upload: 'http://path/to/your/server/script',
    uploadText: 'Drop files here',
  }
});
```

**Comment by madhavbc** [comment]
I am doing same but its not posting anything its just posting 'files[] ' but no value

**Comment by artf** [comment]
How do you check it? Because with devtools I don't see the content but the server script actually receives the file

**Comment by atuleshK** [comment]
@artf thnx for the guidelines... I'm sorry, couldn't reply for this issue due to busy schedule. But it worked as u said

**Comment by truongnv169** [comment]
@artf : i don't know how to detect Uploading image complete event in Grapesjs. Could you tell me how to detect it ?
Thanks !

**Comment by artf** [comment]
@truongnv169 using the latest release you can use these listeners 

* `asset:upload:start` - Before the upload is started
* `asset:upload:end` - After the upload is ended (successful or not)
* `asset:upload:error` - On any error in upload, passes the error as an argument
* `asset:upload:response` - On upload response, passes the result as an argument

```js
editor.on('EVENT NAME', () => {...})
```
