### ISSUE TITLE
[QUESTION] Change and get value of editor.getSelected() block

### ISSUE THREAD

**Issue by JulyanoF** [artf/grapesjs#820]
How can I change and get the content of current selected block?

**Comment by JulyanoF** [comment]
To get content:
`editor.getSelected().get('content')`
To set content:
editor.getSelected().set('conten', 'myhtml')

**Comment by artf** [comment]
@JulyanoF be aware that `content` is for static strings (used mainly for custom RTEs) therefore by doing this `editor.getSelected().set('content', '<div>TEXT1</div>...')` you wouldn't be able to edit inner elements.
```js
const selected = editor.getSelected();

// Get the JSON of the Component
JSON.stringify(selected.components());

// Get its HTML
selected.toHTML();

// Set new components
selected.components('<div>Text1</div><div>Text2</div>')
```

**Comment by JulyanoF** [comment]
> selected.components()
@artf I don't want to create a new component into the selected block,. I need only edit the content. When I use this method, it is creating a new div into the previous block. How can I avoid it?

**Comment by JulyanoF** [comment]
@ionic666 Hello. I did something like it:
`editor.getSelected().toHTML().replace(/<div class="c.*?>([\s\S]*?)<\/div>/, '$1')` to get content of selected area and `editor.set('content', myContent)` to set content

**Comment by ionic666** [comment]
@JulyanoF i am sorry.Excuse me,I have done as you said,But it doesn't work.
![qq20180530-094232](https://user-images.githubusercontent.com/36065691/40694209-158e756e-63ee-11e8-9010-afe346498b01.png)
