### ISSUE TITLE
How to set the href attribute

### ISSUE THREAD

**Issue by Deepak813** [artf/grapesjs#821]
Hi @artf,

Please let us know how we can set the href attribute of anchor inside div when element is dragged i.e 

<div class="social_icons rrssb-buttons c3250">
  <a href="https://www.facebook.com/sharer/sharer.php?u=http://starteo.softobiz.com" class="popup rrssb-facebook" id="ibvm"><i aria-hidden="true" class="facebookSocial fa fa-facebook">
    </i></a>
  <a href="https://twitter.com/intent/tweet?text=https://rrssb.netlify.com/" class="popup rrssb-twitter" id="iuhg"><i aria-hidden="true" class="fa fa-twitter" id="iayz">
    </i></a>
  <a href="mailto:?Subject=your%20subject" class="rrssb-email" id="i6ji"><i aria-hidden="true" class="fa fa-envelope" id="icv33">
    </i></a>
  <a href="http://www.linkedin.com/shareArticle?mini=true&url=http://rrssb.ml&title=Ridiculously%20Responsive%20Social%20Sharing%20Buttons&summary=Responsive%20social%20icons%20by%20KNI%20Labs" class="popup rrssb-linkedin" id="ii5ni"><i aria-hidden="true" class="fa fa-linkedin" id="i0ukq">
    </i></a>
</div>

I want to update href of first anchor tag without using editor.getHTML() but using below code it add href on div i.e

**model.set('attributes', {'href': 'https://www.facebook.com/sharer/sharer.php?u='});**

I am using latest library.

**Comment by Deepak813** [comment]
Hi @JulyanoF,

Thanks for the message,

I have used this code when element is dragged but display following error:

Uncaught TypeError: Cannot read property 'set' of null.

I want to update the href of anchor tag inside the div.

**Comment by JulyanoF** [comment]
@Deepak813 Oh, you want to change anchor when is draggin/dropping?

**Comment by JulyanoF** [comment]
It should be better you change the content of block when it is created..
```
const colmBlock = bm.get('c109').set({
    content: '<a class="my-class" href="https://my-url.com">Click here</a>'
})
bm.render([
	colmBlock,
	//...
]);
```

**Comment by Deepak813** [comment]
Hi @JulyanoF,

Thanks for the message,

But this code is not working when element is dragged.

**Comment by Deepak813** [comment]
Yes, we need to change the anchor href value dynamically when element is dragged.

**Comment by JulyanoF** [comment]
Okay, I don't know if you are trying to do it on drag start or stop, but I reproduced something like this:
```
editor.on('block:drag:stop', function(model) {
    model.attributes.attributes = {href:"http://teste.com"}
});
```
Or:
```
editor.on('block:drag:stop', function(model) {
    model.set('attributes', {href:"http://teste.com"})
});
```

**Comment by JulyanoF** [comment]
@Deepak813 post your code to let us help you

**Comment by artf** [comment]
@Deepak813 
```js
const allAnchorModels = model.find('a');
allAnchorModels.forEach(model => model.setAttributes({ href: '...' }))
```

**Comment by Deepak813** [comment]
Hi @artf,

Thanks for the message,

Provide code is correct and update all the href when element is dragged but i want to update all three anchor tag with different href.

**Comment by artf** [comment]
> update all three anchor tag with different href when element is dragged

well... this logic is up to you

**Comment by Deepak813** [comment]
Hi @artf,

Thanks for the message,

If i know then i definitely do this. Please let us know how we can find class and update its attributes in html.
