### ISSUE TITLE
[QUESTION] How to get the html and css code in view code tool?

### ISSUE THREAD

**Issue by pranzikkin** [artf/grapesjs#822]
or how to get all the html code and css so that I could save it in my database.

Or there is already a functionality in the documentation?
your help will be much appreciated :)

**Comment by pranzikkin** [comment]
Sorry for this post. I was only able to look at the Open Issues not knowing that there are closed issues. I was able to know that I could use editor.getHtml() and editor.getCss() which I could just save right away in my database to save my template(the only way I know how to save the codes.). Is there another way for this?

**Comment by artf** [comment]
@pranzikkin you can set up a remote storage #778 which will store your data automatically

**Comment by pranzikkin** [comment]
what do i put in UrlStore?
