### ISSUE TITLE
[BUG] Set selected content is not affecting editor.getHtml() completly

### ISSUE THREAD

**Issue by JulyanoF** [artf/grapesjs#823]
When I use `editor.getSelected().set('content', 'somethig')`, theoretically it changes value correctly as I see in editor, but when I call `editor.getHtml()` or I enable autosave (that probably call `getHtml()`), it is showing `"<div class="c891">somethingInsert your text here</div>"`. It is always incrementing the text. 
Edit:
In fact, only "Insert your text here" is being fixed in every block's change.

**Comment by artf** [comment]
https://github.com/artf/grapesjs/issues/820#issuecomment-361732512
