### ISSUE TITLE
Is it possible to remove "views" of editor Panel

### ISSUE THREAD

**Issue by anand-gopinath** [artf/grapesjs#824]
I wish to remove/hide the below mentioned "view" from the Panel. Is it possible via API or I need to externally hide using css ?

![34](https://user-images.githubusercontent.com/25955939/35626889-1f6dfb7e-06bd-11e8-9db9-f7fd439d47a2.png)

`editor.Panels.getPanel("views").attributes.buttons.models[2].attributes.visible = false;`

**Comment by maxtacco** [comment]
One of the demos does it like this: 
`$('#gjs-pn-views').find('.fa-bars').hide();`

**Comment by anand-gopinath** [comment]
@maxtacco That's fine but, it seems better to do through API because in future there will be a need for rearrangements among the 4 views in that panel

**Comment by ryandeba** [comment]
@anand-gopinath - this code works for me in a plugin: `editor.Panels.removeButton("views", "open-layers");`

**Comment by ryandeba** [comment]
@anand-gopinath In case it's helpful, here's some code that I'm using to reorder those buttons (this also probably needs to run in a plugin):
```
var panelManager = editor.Panels;

// get the buttons
var styleManagerButton = panelManager.getButton("views", "open-sm");
var layersButton = panelManager.getButton("views", "open-layers");
var blocksButton = panelManager.getButton("views", "open-blocks");

// remove the buttons
panelManager.removeButton("views", "open-sm");
panelManager.removeButton("views", "open-layers");
panelManager.removeButton("views", "open-blocks");

// add the buttons back in a custom order
panelManager.addButton("views", blocksButton);
panelManager.addButton("views", styleManagerButton);
panelManager.addButton("views", layersButton);
```

**Comment by artf** [comment]
Thanks Ryan, I'll add a new listener, in the next release, which should fix [the issue](https://github.com/artf/grapesjs/issues/824#issuecomment-362029424)

**Comment by praveenpandey164** [comment]
@ryandeba how to get the options. I want to replace the `view code` button with save button. Can you please tell me how to do that. 
Thanks in advance :*
