### ISSUE TITLE
[QUESTION] Change location of command panel

### ISSUE THREAD

**Issue by hillelcoren** [artf/grapesjs#827]
Amazing library, thank you!!

I have two questions I'm hoping you can help with.

- How can I move the command panel from the top to the left as is shown here: https://github.com/artf/grapesjs/wiki

- I was having trouble getting the block icons to show, I saw individual letters instead. I was able to fix it by copying the main-fonts.woff file, should I need this file?

**Comment by artf** [comment]
Hi @hillelcoren 
> How can I move the command panel from the top to the left as is shown here

Panels are all arranged freely by CSS so you can move them as you want

> I was having trouble getting the block icons to show, I saw individual letters instead. I was able to fix it by copying the main-fonts.woff file, should I need this file?

Yeah, unfortunately, most of the icons are coming from fonts, therefore you have to include them if you want to use the same icon.
BTW we're planning to remove them as a dependency #644

**Comment by hillelcoren** [comment]
Thanks for your help!
