### ISSUE TITLE
[QUESTION] Components 'add' event fires different number of times

### ISSUE THREAD

**Issue by maxtacco** [artf/grapesjs#828]
Hi,
I've noticed that if I add the following code in my custom component the event fires differently depending on whether a new child component is drag and dropped from blocks vs canvas.

```javascript
 ...  
  view: defaultView.extend({  
      init() {  
        this.listenTo(this.model.components(), 'add', this.onComponentAdded);  
      },
      
      onComponentAdded(comp) {
        console.log(comp);
      },
  })  
   ...
```

Only one event is fired when I drag and drop a child component from the blocks section. But, when I drag and drop from canvas I can see this event firing twice and the first time some 'div' component is passed.

I wonder if this relates to https://github.com/artf/grapesjs/pull/202 or not.

Also, I can handle this event the way I want but checking for the avoidStore option of the component:

```js
     onComponentAdded(comp) {
        if (!comp.opt.avoidStore) {
          console.log(comp); // the child component I want
        }
      },
```

Please let me know if this is the desired behavior and it is ok to use the check as in the example above.
Thank you.

**Comment by artf** [comment]
Hi @maxtacco, unfortunately, this is due to how the Sorter works when [moves components](https://github.com/artf/grapesjs/blob/dev/src/utils/Sorter.js#L976-L991) and honestly, at the moment, I can't see better workaround than your one
