### ISSUE TITLE
[QUESTION] "Hidden feature"?

### ISSUE THREAD

**Issue by JulyanoF** [artf/grapesjs#829]
Hello @artf .

I was implementing modal of AssetsManager and I found it:
![image](https://user-images.githubusercontent.com/17284704/35705089-9cfb4364-0788-11e8-80b3-f6d781225f19.png)
Is it some "feature" or something else that wasn't completely implemented yet? Is it working? I really didn't find it in any file. If it is working, how can I activate it?

When I remove the style `display:none` from it and try to use, it is working like a submit button.

I reeeeeeealy would like to use it.

Edit: I found it in code, it is in "template" function in Assets (I guess), but this `display:none` is hard-coded. :(

Best Regards.

**Comment by artf** [comment]
Hi @JulyanoF unfortunately just some legacy part, as [Assets](https://github.com/artf/grapesjs/wiki/Assets) are already highly customizable I'm not gonna implement such a feature in the core
