### ISSUE TITLE
[component setting] select of Target, font color and background are both white.

### ISSUE THREAD

**Issue by allmonday** [artf/grapesjs#83]
![image](https://cloud.githubusercontent.com/assets/2917822/25699067/34b6f354-30f4-11e7-88a3-e3b02b601242.png)
when select the target, there is a little style issue that the option is only visible when hovered on it.

**Comment by artf** [comment]
I don't see any issue in the demo :/
Past here your env info pls

**Comment by allmonday** [comment]
![image](https://cloud.githubusercontent.com/assets/2917822/25787557/093a3e46-33d5-11e7-8d33-2e3f3202aa5d.png)

os: windows 7/windows 10
chrome version: 57.0.2987.110

BTW, it works fine in mac.

**Comment by artf** [comment]
Ok thanks @allmonday I get it It's the same as #19 
just need to update the style. I'll fix it for the next release
