### ISSUE TITLE
[FEATURE] storageManager dynamic url endpoints

### ISSUE THREAD

**Issue by ensemblebd** [artf/grapesjs#831]
## FEATURE REQUEST

SPA approach for dynamically loading and storing utilizing the storageManager urlStore and urlLoad config options. 
It would be GREAT if your code checks if it's a function, not assume it's a string literal defined finitely, explicitly, at time of initial configuration (page load). Changing the config values during runtime has NO effect on the predefined storageManager.

Or perhaps add the params configuration object to the urlLoad as well. Shouldn't params defined in config be passed to BOTH load and store?

**Comment by JulyanoF** [comment]
@ensemblebd you tried to change like it: `editor.StorageManager.getConfig().urlStore = "myUrl"`?

**Comment by ensemblebd** [comment]
I ended up just making second ajax request after calling editor.store(), to store the data I wish to store.
I'll give that a try though, that is not the way in which I changed it.

**Comment by artf** [comment]
The correct way of doing so would be updating the Storage model
```js
editor.StorageManager.get('remote').set({ urlStore: '...', ... })
```
