### ISSUE TITLE
Avoid settings hereditation

### ISSUE THREAD

**Issue by chiqui3d** [artf/grapesjs#832]
Hello,
When I add a column(row) and add a background color, this color is added to everything I had previously and also to the next ones you add.

Is it really its functionality or is it a bug?

**Comment by chiqui3d** [comment]
the same problem with the images:

![demo Image](https://i.imgur.com/CDEPbUP.gifv)

**Comment by ryandeba** [comment]
Hi @chiqui3d,

I bet this is happening because the selected component has the same class as other components. Those images from the demo all have the class `badge-avatar`, so changing one effectively changes them all. I believe it is working as designed.

**Comment by chiqui3d** [comment]
yes exactly, thanks very much

**Comment by artf** [comment]
@chiqui3d indeed I've updated the grid system which enables a more natural editing of rows/columns. 
BTW I still think the example of images is a nice showcase of the "power" of classes and not a "problem"

**Comment by chiqui3d** [comment]
@artf Yes you're right, I didn't think of it that way, now I see the meaning.
