### ISSUE TITLE
[Bug]: on click of links with events Editor loading inside another editor

### ISSUE THREAD

**Issue by rohanreddyg** [artf/grapesjs#833]
I am trying to load an existing Ad content into GrapesJS editor. On dragging new custom components into editor with some script, editor is loading inside the root editor frame. Not sure what is causing this issue.

![editorinsideeditor](https://user-images.githubusercontent.com/240114/35776585-31657b76-09c5-11e8-8bff-a231748ede94.PNG)

**Comment by artf** [comment]
@rohanreddyg can you create a live demo of your case, please
