### ISSUE TITLE
[Question] Is there anyway to edit the final HTML - CSS code with an integrated code editor?

### ISSUE THREAD

**Issue by Praunda** [artf/grapesjs#834]
Hello there! I was wondering if I can edit the final code with a code editor.

**Comment by cjpollard** [comment]
Someone put up a nice bit of code for that here. https://github.com/artf/grapesjs/issues/74#issuecomment-322427387

**Comment by JulyanoF** [comment]
@Praunda to get html to edit:` editor.getHtml();`
to get css to edit: `editor.getCss();`
