### ISSUE TITLE
[QUESTION] Javascript Deletes

### ISSUE THREAD

**Issue by RiyaThete** [artf/grapesjs#837]
Whenever I import, using import plugin, javascript part of the code is deleted.
Is there any way to preserve it?
 I want to used the exported html file directly, but cannot use it now because javascript is missing in it

**Comment by arthuralmeidap** [comment]
What is the name of the plugin?

**Comment by RiyaThete** [comment]
![image](https://user-images.githubusercontent.com/13497961/35861512-f99b936a-0b6d-11e8-931b-808e157a417c.png)

The 3rd last import plugin .It is available on http://grapesjs.com/demo.html

**Comment by arthuralmeidap** [comment]
try to run `editor.getJs()`.  see if it returns the previous imported JS.

**Comment by artf** [comment]
You have set `allowScripts` to true

```j
grapesjs.init({
  ...
  allowScripts: true,
})
```

**Comment by RiyaThete** [comment]
@artf Thank you so much ... you saved me from writing a workaround for it.

**Comment by Deepak813** [comment]
Hello @artf,

How we can get the particular script based on selected element as provided code "editor.getJs()" provides all the script contained in the HTML page.

Thanks in advance.
