### ISSUE TITLE
[QUESTION] Create custom selected component settings

### ISSUE THREAD

**Issue by JulyanoF** [artf/grapesjs#839]
There is a option in panel to change setting of component (For links, there is an option no change link - HREF - and target, for texts, id and title and for images, alt attribute). I would like to know how can I create that inputs and how can I change this attrs in selected component? I created a Panel's view to use as CKEditor to change text components when selected and I would like that these otter settings be at the same view:

```
editor.Panels.addButton('views',{ // `views` is the panel's id
    id: 'editorCK',
    className: 'fa fa-pencil',
    command: 'editorCK',
});
editor.Commands.add('editorCK', {
    run: function(editor, sender){
        const bm = editor.BlockManager;
        const pn = editor.Panels;
        var blocoSelecionado = editor.getSelected();
        if(this.mkeditorCustom){
            $(this.mkeditorCustom).remove();
        }
        if (blocoSelecionado && blocoSelecionado.attributes.type == "text"){
            bm.render();
            const id = 'views-container';
            const mkeditorCustom = document.createElement('div');
            const panels = pn.getPanel(id) || pn.addPanel({ id });
            const textarea = document.createElement('textarea');
            textarea.id = "ckeditor";
            mkeditorCustom.appendChild(textarea);
            panels.set('appendContent', mkeditorCustom).trigger('change:appendContent');
            this.mkeditorCustom = mkeditorCustom;
            $('#ckeditor').html(blocoSelecionado.toHTML().replace(/<div class="c.*?>(.*?)<\/div>/, '$1'));
            if(CKEDITOR.instances.ckeditor) CKEDITOR.instances.ckeditor.destroy();
            if(!CKEDITOR.instances.ckeditor) CKEDITOR.replace('ckeditor', opcoesCKEDITOR);
            CKEDITOR.instances['ckeditor'].on('change', function() {
                blocoSelecionado.set('content', CKEDITOR.instances['ckeditor'].getData().replace(/<div class="c.*?>(.*?)<\/div>/, '$1'));
            });
        }else{
            bm.render();
            const id = 'views-container';
            const mkeditorCustom = document.createElement('div');
            const panels = pn.getPanel(id) || pn.addPanel({ id });
            const conteudo = document.createElement('div');
            conteudo.className = 'gjs-sm-header';
            const texto = document.createTextNode('Selecione um bloco de texto para usar o editor de texto');
            conteudo.appendChild(texto);
            mkeditorCustom.appendChild(conteudo);
            panels.set('appendContent', mkeditorCustom).trigger('change:appendContent');
            this.mkeditorCustom = mkeditorCustom;
        }
        this.mkeditorCustom.style.display = 'block';
    },
    stop: function(editor, sender){
        if(CKEDITOR.instances['ckeditor']) CKEDITOR.instances['ckeditor'].destroy();
        const mkeditorCustom = this.mkeditorCustom;
        mkeditorCustom && (mkeditorCustom.style.display = 'none');
    }
});
```

Other thing I'm trying to is create at this same Panel View is an input (when isn't any component selected) that change max width of html generated and another to change background's color

**Comment by arthuralmeidap** [comment]
Here is what you looking for: https://github.com/artf/grapesjs/wiki/Components

**Comment by JulyanoF** [comment]
@arthuralmeidap ok, but how can I show the component in my current Command?

**Comment by arthuralmeidap** [comment]
If I understood, when you have a text component inside the canvas you can selected it and then clicks on a new button that you have created that opens the CKEditor, right? 

Then every change made on CKEditor you send back to the text component.  Am I missing something here?

Now , when you click on the text component,   do you want to be able to change some custom component settings for this component ,right? Did I understand correctly?

**Comment by JulyanoF** [comment]
@arthuralmeidap almost. when I click in a text component, my button `editorCK` and its command is executed and is setted to active (that have a CKEditor in this Panel's view that in every change, it changes my selected text component). It's working perfectly and it's happening only when text component is clicked because I did it:
```
var domComps = editor.DomComponents;
var textType = editor.DomComponents.getType('text');
domComps.addType('text', {
    model: textType.model,
    view: textType.view.extend({
        events: {
            'click': function(){
                if(selecionado && selecionado == this.model){
                    selecionado = false;
                    selecionadoB = false;
                }else{
                    setTimeout(() => {
                        selecionado = this.model;
                        selecionadoB = 'text';
                        var selected = editor.getSelected();
                        var openSmBtn = editor.Panels.getButton('views', 'editorCK');
                        openSmBtn.set('active', 1);
                    }, 100);
                }
            },
            'mouseenter': function(){
                if(!selecionado)
                    editor.select(this.model);
            },
            'mouseleave': function(){
                if(!selecionado){
                    editor.select(null);
                }
            }
        },
    }),
});
```
What I'm trying to is, when I click in a button, open the same Panel as it shows CKEditor but with a input to change the link of button (href) and his value (e.g.: Button)

**Comment by JulyanoF** [comment]
@arthuralmeidap these button settings are in Settings Panel's view, but I want to create it in my custom Panel's view. Did you understand?

**Comment by arthuralmeidap** [comment]
I got it now. 

Within grapes we have the `TraitManager`. This module shows the Traits options (component settings)

Try to do something like `yourContainer.append(editor.TraitManager.getTraitsViewer.el)`

it gets the whole module and inject within a container, in your case your panel.

**Comment by JulyanoF** [comment]
@arthuralmeidap I'm getting undefined value with `editor.TraitManager.getTraitsViewer.el`

**Comment by arthuralmeidap** [comment]
@JulyanoF ,

  I told you without test.
  Give me a moment to test

**Comment by arthuralmeidap** [comment]
@JulyanoF ,

  Sorry, I missed the parenthesis.
  It is `editor.TraitManager.getTraitsViewer().el`

**Comment by JulyanoF** [comment]
@arthuralmeidap My hero hahaha

**Comment by JulyanoF** [comment]
@arthuralmeidap is it possible, as I mentioned, a fixed input to change background color and width of html content?

**Comment by JulyanoF** [comment]
@arthuralmeidap other thing... there is no input to change button's content, how can I create it manually? I need to get trait of button and recreate?

**Comment by JulyanoF** [comment]
@arthuralmeidap agora que vi, tu é brasileiro também kkkkkkkk

**Comment by arthuralmeidap** [comment]
hahahha... Quando eu vi teu código com `selecionadoB` eu reparei tbm... 

você vai precisar criar uma trait para os botões. To vendo se é possível de só adicionar uma trait em um component já existente

**Comment by JulyanoF** [comment]
@arthuralmeidap sem chance? 😞

**Comment by arthuralmeidap** [comment]
@JulyanoF até agora não consegui adicionar uma trait em um componente já existente, mas, você pode sobrescrever esse componente e somente adicionar as suas customizações nele.

Nesse link mostra como criar um componente: https://github.com/artf/grapesjs/wiki/Components

 A única diferença que ao invés de criar, você vai sobrescrever. 

Aqui  é mostrado onde pegar o componente padrão (default type) 
` var defaultType = comps.getType('default');`

Ao invés disso pega o componente específico e o sobrescreve . Esses são os tipos existentes:
```
cell
row
table
thead
tbody
tfoot
map
link
video
image
script
svg
textnode
text
default
```

Eu estava olhando e não existe um componente botão específico, mas sim um link com uma classe css para o exibir como um botão. 

Você vai precisar criar um tipo botão específico se vc quiser uma tag `<Button>` no seu html.

**Comment by JulyanoF** [comment]
@arthuralmeidap sim, o botão com a tag `<a>` já está feito, o que quero fazer é adicionar um input (na Traits que foi mecionado acima) para a customização do texto dentro da tag `<a>`. Além disso, como mencionado no final do primeiro comentário, estou tentando adicionar também dois inputs (background color do temaplate e o tamanho - width - dele), que serão mostrados enquanto não houver nenhum bloco selecionado (essa parte é a simples, o problema em si está sendo montar esses 3 inputs)

**Comment by arthuralmeidap** [comment]
você não precisa de uma nova trait para alterar o backgroundColor ou width do template.
Se você clicar no body do template e ir no Style Manager (botão de pincel) você consegue alterar essas propriedades facilmente.

**Comment by JulyanoF** [comment]
@arthuralmeidap sim, eu entendo, porém eu gostaria de deixar esses dois "inputs" fixos, independentemente se o body está selecionado ou não

**Comment by JulyanoF** [comment]
@arthuralmeidap e referente ao componente de link (tag a), como eu posso criar uma trait para alterar o conteúdo dentro do componente selecionado? `<a href="http://link.com">Conteúdo</a>`

**Comment by JulyanoF** [comment]
@artf some idea?

**Comment by arthuralmeidap** [comment]
@JulyanoF ,   at our company we faced the same problem of the Button block.. 

You will need to wait or apply some kind of fix OR create a new component called button and use it.

Here you find more details about how to create the a component (sometimes called Type) .

https://github.com/artf/grapesjs/wiki/Components

**Comment by JulyanoF** [comment]
@arthuralmeidap but I already created a new component:
```
domComps.addType('link', {
    model: linkType.model.extend({
        defaults: Object.assign({}, linkType.model.prototype.defaults, {
        traits: [
            {
                label: 'Título',
                name: 'title',
                placeholder: 'Título'
            },
            {
                label: 'Link',
                name: 'href',
                placeholder: 'http://meusite.com.br'
            },
            {
                label: 'Descrição',
                name: 'content',
                placeholder: 'Botão'
            }
        ],
      }),
    }),
    view: linkType.view.extend({
            events: {
            'click': function(){
                if(selecionado && selecionado == this.model){
                    selecionado = false;
                    selecionadoB = false;
                }else{
                    editor.select(this.model);
                    selecionado = this.model;
                    selecionadoB = 'link';
                    var selected = editor.getSelected();
                    var openSmBtn = editor.Panels.getButton('views', 'opcoesBloco');
                    openSmBtn.set('active', 1);
                }
            },
            'mouseenter': function(){
                if(!selecionado)
                    editor.select(this.model);
            },
            'mouseleave': function(){
                if(!selecionado){
                    editor.select(null);
                }else{
                    editor.select(selecionado)
                }
            }
        },
    }),
});
```

**Comment by JulyanoF** [comment]
When I do it (when I create a "content" object), it creates a attribute `content` in my `<a>` (`<a content="test"></a>`) instead change the real content

**Comment by JulyanoF** [comment]
@arthuralmeidap exactly what I was looking for:
[Define new Trait type](https://github.com/artf/grapesjs/wiki/Traits#define-new-trait-type)

**Comment by artf** [comment]
@JulyanoF if the issue is solved please close it

ps. big thanks to @arthuralmeidap for his support ❤️
