### ISSUE TITLE
[Bug]: When dragging an element, misleading drop placeholder

### ISSUE THREAD

**Issue by AustinTBiggs** [artf/grapesjs#840]
GrapeJs Version: 13.8
Local Copy
JSFiddle: https://jsfiddle.net/austinbiggs/tgsykuq4/

This bug is a bit hard to explain, but should be pretty straight forward in recreating.

I have menu links that are restricted to being draggable within the parent `<nav>`, however when dragging, a false drop placeholder appears at the top of the page, even though dropping there does nothing and is not allowed.

The `<nav>` has `droppable` set to only allow the menu links to be dropped within. The links are only draggable within the `<nav>`.

These screenshots demonstrate how this issue appears in my own example.
![screen shot 2018-02-05 at 12 58 26 pm](https://user-images.githubusercontent.com/930864/35825859-4fc9c572-0a74-11e8-838f-711fd5953637.jpg)
![screen shot 2018-02-05 at 12 58 36 pm](https://user-images.githubusercontent.com/930864/35825860-4fdb0ecc-0a74-11e8-9ec7-b89bcbd15725.jpg)

**Comment by artf** [comment]
@AustinTBiggs I don't know if it's just this but your links have `data-gjs-draggable=".menu nav.menu"` which instead should be something like `data-gjs-draggable="nav.menu"`

**Comment by AustinTBiggs** [comment]
@artf 

While I'm confused why that change is necessary (it's a valid selector), I made the change. Unfortunately, I'm still seeing the issue.

**Comment by artf** [comment]
With `.menu nav.menu` you mean that you can drag only inside nested menus, maybe it supposed to be `.menu, nav.menu`?
Here is my version and it works as expected https://jsfiddle.net/wsn33167/
