### ISSUE TITLE
How we can set array using editor.getSelected().set('attributes',array value)

### ISSUE THREAD

**Issue by Deepak813** [artf/grapesjs#842]
Hi @artf,

How we can set array values using editor.getSelected().set('attributes',array value); 
If we try to do so with the same code then it insert NaN to attributes.

**Comment by arthuralmeidap** [comment]
@Deepak813 ,
  
  You should follow one of the following syntaxes:

- `editor.getSelected().set({title: "March 20", content: "In his eyes she eclipses..."});` -> for multiple attributes. You send a object

- `editor.getSelected().set("title", "March 20");` -> for a specific attribute

**Comment by artf** [comment]
> How we can set array values using editor.getSelected().set('attributes',array value);

You can't set array on `attributes` property, it should be an object instead.

I'd recommend using a more specific methods like `model.setAttributes({ title: '' })` or `addAttributes({ ... })`
