### ISSUE TITLE
[QUESTION] - CssComposer - removes unused classes

### ISSUE THREAD

**Issue by arthuralmeidap** [artf/grapesjs#843]
hi @artf ,

  I import a html , using _import_ from _grapesjs-preset-newsletter_, with some css classes inside the `<style>` tag.
  After the import, when I call `editor.getCss()`, some classes that I added before are missing now.
  I checked that those css classes are not been used anywhere.
  QQ: The CssComposer module removes the unused css classes?

**Comment by artf** [comment]
> QQ: The CssComposer module removes the unused css classes?
Yeap

**Comment by arthuralmeidap** [comment]
Nice, thanks!

**Comment by FrciSmrci** [comment]
@artf is there any flag available to leave the unused styles?

**Comment by prosenjit-manna** [comment]
Are there any options to disable the removing unused CSS?
