### ISSUE TITLE
Error when I tried to add rows to a table

### ISSUE THREAD

**Issue by davidherlopgt** [artf/grapesjs#846]
Hi guys
I'm starting to use Grapesjs and I have a problem, I am trying to add 3 new commands to create tables, add rows and cells, the table works fine but when I add a row into the table I get this error: "Invalid target position: Target collection not found, Target is not droppable, accepts [undefined], Component not draggable, acceptable by [undefined] ", could someone help me, this is my code :
I appreciate it the help

`<script type="text/javascript">
            var editor = grapesjs.init({
            height: '100%',
                    showOffsets: 1,
                    noticeOnUnload: 0,
                    storageManager: {autoload: 0},
                    container: '#gjs',
                    fromElement: true,
                    plugins: ['gjs-preset-webpage'],
                    pluginsOpts: {
                    'gjs-preset-webpage': {}
                    }
            });
            

            var bm = editor.BlockManager;
            var comps = editor.DomComponents;
            var defaultType = comps.getType('default');
            var defaultModel = defaultType.model;
            var defaultView = defaultType.view;
            bm.add('table', {
            label: 'Table',
                    content: '<table><thead><th></th></thead><tbody><tr><td>Test</td></tr ></tbody></table>',
                    attributes: {
                    'data-type': 'table',
                    },
            });
            bm.add('tr', {
            label: 'Row',
                    content:  '<tr><td>Test</td></tr>',
                    attributes: {
                    'data-type': 'tr',
                    },
            });
            bm.add('td', {
            label: 'Cell',
                    content: '<td>Test</td>',
                    attributes: {
                    'data-type': 'td',
                    },
            });
            
            
            comps.addType('table', {
              model: defaultModel.extend({
                defaults: Object.assign({}, defaultModel.prototype.defaults, {
                'custom-name': 'Table',
                draggable: true,
                droppable: true,
                accepted: true,
                highlightable: true,
                stylable: [
                     ' height', 'font-style', 'font-size', 'font-weight', 'font-family', 'color',
                     'width'
                ],
                style: {
                     'width': '100%',
                     'font-size': '14px'
                 },
                }),
              },
              {
                isComponent: function(el) {
                  if(el.tagName === 'TABLE'){
                    return {type: 'table'};
                  }
                },
              }),
            view: defaultType.view,
          });
          
            
            comps.addType('tr', {
              model: defaultModel.extend({
                defaults: Object.assign({}, defaultModel.prototype.defaults, {
                  'custom-name': 'Row',
                    draggable: true,
                    droppable: true,
                    highlightable: true,
                    accepted: true,
                }),
              },
              {
                isComponent: function(el) {
                  if(el.tagName === 'TR'){
                    return {type: 'tr'};
                  }
                },
              }),
            view: defaultType.view,
          });
          
            
            comps.addType('td', {
              model: defaultModel.extend({
                defaults: Object.assign({}, defaultModel.prototype.defaults, {
                  'custom-name': 'Td',
                    draggable: true,
                    droppable: true,
                    highlightable: true,
                    accepted: true,                               
                }),
              },
              {
                isComponent: function(el) {
                  if(el.tagName == 'TD'){
                    return {type: 'td'};
                  }
                },
              }),
            view: defaultType.view,
          });          
        </script>`

**Comment by davidherlopgt** [comment]
I forget put what version I am using grapesjs - 0.13.5
        <link rel="stylesheet" href="Config/grapesjs-dev/dist/css/grapes.min.css">
        <link rel="stylesheet" href="Config/grapesjs-preset-webpage-master/dist/grapesjs-preset-webpage.min.css"/>
        <script src="Config/grapesjs-dev/dist/grapes.min.js"></script>
        <script src="Config/grapesjs-preset-webpage-master/dist/grapesjs-preset-webpage.min.js"></script>

**Comment by artf** [comment]
@davidherlopgt Have you tried to use [built-in table components](https://github.com/artf/grapesjs/tree/dev/src/dom_components/model) instead of extending them?
BTW create a live demo please

**Comment by davidherlopgt** [comment]
Hi artf thanks for your answer, I tried to use the table component and I can add the Table with one row and one cell in the header and the body, maybe the disadvantage is that if I change the color of the row to the header the body is changed too, so I have to remove the class from the body row so that it is not affected
I add the live demo like you ask
[grapesjslivedemo.zip](https://github.com/artf/grapesjs/files/1707098/grapesjslivedemo.zip)

**Comment by artf** [comment]
> maybe the disadvantage is that if I change the color of the row to the header the body is changed too, so I have to remove the class from the body row so that it is not affected

Ok... but if you don't put the class you haven't the disadvantage?!?
For a live demo I was referring to something like jsfiddle.net
