### ISSUE TITLE
I need grapesjs-preset-webpage.js file to understand editor options. 

### ISSUE THREAD

**Issue by aman88work** [artf/grapesjs#847]
how to get (grapesjs-preset-webpage.min.js file ) as (grapesjs-preset-webpage.js) file to understand editor options. thanks for this great work and help.

**Comment by arthuralmeidap** [comment]
go to the  grapesjs-preset-webpage repo on github and check the source code.  There you can take a look over all the code and check what you need.

Repo: https://github.com/artf/grapesjs-preset-webpage
