### ISSUE TITLE
Ability to unload and destroy the editor instance or reload the config options?

### ISSUE THREAD

**Issue by ajwootto** [artf/grapesjs#849]
In my use case, I'm trying to change the store and load URLs used by the remote storage manager dynamically. As far as I can tell, the editor does not pick up and use any changes to the config if I change them directly, ie.
```editor.Config.storageManager.storeUrl = 'blah'```
after the editor has already been initialized.

To try and get around it, I was attempting to unload the editor from the page programmatically by removing the target DOM element and recalling init. However, the init function seems to create multiple instances of the editor. I noticed the GrapesJS.editors array keeping track of them, so I tried setting this to empty to hopefully have the instances be garbage collected. Even in this case however, the editor has event handlers that still seem to trigger afterwards, saving erroneous data. 

Ideally, I would like a way to either destroy the editor with some destructor method (if one does not already exist) or force a reloading of the config options without reloading the editor.

**Comment by arthuralmeidap** [comment]
@ajwootto ,

  You can create a custom Remote Storage and inside it apply your custom saving/updating logic.

  Take a look on this link: https://github.com/artf/grapesjs/wiki/API-Storage-Manager

**Comment by maxtacco** [comment]
You can access RemoteStorage and update urls at any time:
```javascript
    const RemoteStorage = editor.StorageManager.get('remote');
    RemoteStorage.set('urlLoad', [urlLoad]);
    RemoteStorage.set('urlStore', [urlStore]);
```

**Comment by ajwootto** [comment]
Both of those options would probably work, however something I forgot to mention is that in some cases, I want to re-initialize the editor with components and styles pre-specified (ie. passing them in the init) rather than loading them from remote storage, but in other cases I want the initial contents to come from remote storage only. This is happening on the same page, with the contents of the editor having to be swapped around. Is there some API I'm missing that can do this?

**Comment by artf** [comment]
Never looked too much at the re-initialization/destroying of the editor and as personally don't see it as a "high priority" feature probably I'd wait for PRs

**Comment by ajwootto** [comment]
gotcha

I ended up solving my own second question above by discovering the
```
editor.setComponents()
editor.setStyle()
```

methods. I think I've got everything I need now, feel free to close this unless you want a record of the feature request :)

Thanks everyone for your help!
