### ISSUE TITLE
Cannot drag and drop blocks into container

### ISSUE THREAD

**Issue by yashvijalan-adl** [artf/grapesjs#85]
Hi. I am using grapesjs with bootstrap. I am also using the filestack, ckeditor and newsletter plugins. The div is inside a form. When I try to drag and drop blocks into the email canvas, I get the following error.
"Invalid target position: target collection not found"

However, code import is working correctly. And once, a basic import layout is ready, I am able to drag and drop and edit elements. 

Any help and/or comments are appreciated :)

[A screenshot is given below]

<img width="1435" alt="screen shot 2017-05-09 at 5 03 44 pm" src="https://cloud.githubusercontent.com/assets/22976387/25848785/7e8e7216-34d9-11e7-8537-37a1b23d38f3.png">

**Comment by artf** [comment]
So you mean it's not working at the beginning (empty canvas)?
Can I see the snippet of how you init the editor?

**Comment by vankyy26** [comment]
I think same thing happened to me when i left the root element without any childs while using fromElement: true. Empty element inside makes it work.

**Comment by artf** [comment]
thanks @vankyy26 will try to fix it then

**Comment by artf** [comment]
@yashvijalan-adl can you update to the last release and check if it's solved?  If the issue is still there I'd like to see your code
