### ISSUE TITLE
[QUESTION] Create Body's trait fixed

### ISSUE THREAD

**Issue by JulyanoF** [artf/grapesjs#853]
I'm trying to create two inputs (width and backgound-color) to template's body and I would like to fix it in Panel's view. When a component is selected, these two inputs must be there. How can I do it?

**Comment by artf** [comment]
@JulyanoF 
so you just need to style the wrapper?

**Comment by JulyanoF** [comment]
I guess its the body and no wrapper I need to style. I would like to use colorpicker too, like style manager

**Comment by JulyanoF** [comment]
@artf For example: actually, I need to click at the backgound, click in style manager, click, in dimension (to change width / max-width) and click in decoration to change backgound color.. I need these two inputs be fixed, independent if the body is the currrent selected block or other
