### ISSUE TITLE
[Question] How to extract html/css code in view code automatically?

### ISSUE THREAD

**Issue by poirin** [artf/grapesjs#858]
I need the function to copy the html/css code in the view code component automatically. Is there a predefined function? or I must implement this directly?

**Comment by muhibbudins** [comment]
Hi @poirin ,

I have some solution, last week i have this problem too i try to save current HTML & CSS without manual copying.

And below is my code .

---

Add custom panel eg. left top button (save button).

```javascript
  /**
   * Create save button
   * @type {String}
   */
  panelManager.addPanel({
    id: 'customPanel',
    visible    : true,
    buttons    : [{
      id          : 'smile',
      className   : 'fa fa-save',
      attributes  : { title: 'Update Promo' },
      command     : 'customCommand'
    }],
  });
  ```

![screen shot 2018-02-12 at 16 41 25](https://user-images.githubusercontent.com/17744043/36090625-a99c1376-1013-11e8-9a71-603c20b7a065.png)

And then create save function

```javascript
  /**
   * Create save function
   */
  commands.add('customCommand', {
    run:  function(editor, sender){
      storageManager.load(['css', 'html'], function(res) {
        // your custom event
        // Note: res variable will return code of css & html
      })
    }
  });
```

Good luck 👍

**Comment by artf** [comment]
If you're talking about storing your templates int DB or any other remote endpoint you can setup the built-in RemoteStorage, take a look here #778
