### ISSUE TITLE
Handle image removal from AssetManager

### ISSUE THREAD

**Issue by vankyy26** [artf/grapesjs#86]
After few hours playing with the manager i finally made it work with ASP.NET handler. Now the issue is how to remove the images i already saved to the server and database. Can't find event that returns image URL on removal. I suppose it's not documented yet and if yes sample code would help.

![aaaaaaa](https://cloud.githubusercontent.com/assets/10697327/25978409/8c3d6ca8-36ca-11e7-881f-8394cbb38e24.PNG)

**Comment by artf** [comment]
You're right @vankyy26, there are no official events for assets yet, but you can actually use Backbone's internal one
```js
var assets = editor.AssetManager.getAll() // <- Backbone collection
assets.on('remove', function(model) {
  console.log(model.get('src'));
})
```

**Comment by vankyy26** [comment]
Oo works like a charm. Thanks man, just made my day! I will implement it right now. Didn't know how to map the internal backbone events but now I know.

**Comment by g41n** [comment]
It worked like a charm for me too with 0.9.8 version.
Now I've upgraded to 0.9.32 and results in firing the function twice...

That's a problem for me: the second time raise an error because the image was deleted the first time. 

Any hint about that?
