### ISSUE TITLE
Can't bootstrap GrapesJS + Material Design Lite integration

### ISSUE THREAD

**Issue by vrudikov** [artf/grapesjs#860]
So i'm trying to bootstrap this integration and i think MDL framework doesn't run, because JS components are not initialized at all

Here is the [plunker](https://plnkr.co/edit/Be2Xcv?p=preview)

I digged into the code of both GrapesJS and MDL and both seems work ok. I tried several ways of initializing MDL JS: canvas init, init script after GJS div content, but no luck

Will appreciate any help

**Comment by artf** [comment]
Hi @vrudikov JS seems to be loading correctly (and you can see that by other JS elements like dialog) but seems like MDL is not auto-initializing. I think you just have to find how to call its init method

**Comment by vrudikov** [comment]
For everyone who want to have Material + GrapesJS integration - just use [material-components-web](https://github.com/material-components/material-components-web/blob/master/docs/getting-started.md)
