### ISSUE TITLE
[Question] Help adding images to the canvas

### ISSUE THREAD

**Issue by hillelcoren** [artf/grapesjs#861]
I've followed the docs and have been able to upload images.

When I drag an image block (using the newsletter preset) and select an image from the assets it adds a blank image to the canvas. I need to double click the image on the canvas and select the image again for it to show.

Is there something I need to do to wire it up? I've tried adding `window.editor = editor;` but it didn't fix it.

Thanks for your help!

**Comment by artf** [comment]
> ... it adds a blank image to the canvas

Can't reproduce it. Any live demo? Or at least a screencast/gif?

**Comment by hillelcoren** [comment]
I put together a basic sample and it works, it must be a problem with my code.

**Comment by hillelcoren** [comment]
Sorry to take up your time!

If anyone else sees this problem in my case it was happening because I was using the canvas:drop event to adjust the HTML (to perform a mail merge). I've fixed it by checking if the user is dropping an image in which case we leave the HTML as is.
