### ISSUE TITLE
[Bug]: Background-image not picked up from styles attribute

### ISSUE THREAD

**Issue by nojacko** [artf/grapesjs#863]
As title + background-image is removed by styles manager when added a background layer.

1. Getting started: https://jsfiddle.net/5upe6myo/
1. Note background-image
1. Click between the text. Should show as "Box".
1. Under Styles > Decorations, the background-image isn't shown.
1. Clicking "+" next to background removes the background-image.

**Comment by artf** [comment]
Actually, this is how style manager works with classes. When you select the "Box" you can see that you have picked ".fluid-container.c318" selector, which doesn't have any bg, but when you uncheck "fluid-container" class, the current selector will be "c318" and now the bg is shown. 
Probably we need to highlight better the inheritance of styles

**Comment by nojacko** [comment]
This seems a little weird. Grapes adding the class `c318` makes my styles unreachable. I'd expect the html and styles provided to be editable.

**Comment by artf** [comment]
What do you mean exactly with `makes my styles unreachable`?

**Comment by nojacko** [comment]
The styles I've defined for my element aren't reachable in the style manager. When I click the box in the canvas I'd really expect to see all the styles it has in the style manager, rather than the the styles of the class Grapes has added.

You said that the background doesn't show because it's using the `.fluid-container.c318` but adding `color: Pink` to the style attribute does show the colour in the typography section. That's a little inconsistent. It's picking up the `color` attribute but not the `background-image` one.

**Comment by softov** [comment]
I'm having a similar problem.

Using forceClass: false, all styles attr predefined work, but when I tried to change some of then, it's all inside a ID style and I cant change nothing.

Using forceClass: true, every time I open the editor, it create a new style class, c1811, c1816, c1820 and going up. The style is always inside the last added class.

So, how can I use with forceClass:false and change style attributes or how can I work with forceClass:true and stop class overflow.

**Comment by softov** [comment]
Have a try.

- Open https://grapesjs.com/demo-newsletter-editor.html
- Select something, like the cell "Build your news...".
- Change background
- Click in "view code" then copy.
- Click in "import code" then paste
- Select the same "cell"
- Try to change the background color

As you can see, the ID style is more "important" over the class style.

I thing for this to work, is need to change the style of the component directly.
Without ID or class styling... If the user/dev wants to be that way, let it be, otherwise be default.

![image](https://user-images.githubusercontent.com/1263495/66803784-b81c4b80-eeee-11e9-9f6f-63e8b20d8d3d.png)

**Comment by artf** [comment]
> As you can see, the ID style is more "important" over the class style.

You can toggle the class to enable editing component's only style

![Schermata 2019-10-19 alle 15 33 45](https://user-images.githubusercontent.com/11614725/67145901-e189fe00-f285-11e9-9825-762e1f59242e.png)

**Comment by softov** [comment]
I did not know that. But was this supposed to work that way?

I say, I created content and exported it. I imported the same content and it is not importing the same, being necessary this trick of disabling the classes.

Wasn't I supposed to edit the style and apply it directly to the ID? So how does the value come by default in import?

What's the point of applying style to a class? If it's inline and the styles are applied to ID.

See, if you have two elements with the same class, the style is being applied to both. I want to apply the style to the selected element only, without applying the style to the class, if anyone guides me I can make direct change to the code.

**Comment by artf** [comment]
Yes, it works exactly as it supposed to work, but I agree that the change should be applied at the component level first, indeed I'd like to add an option for this behavior.

Right now when you import something like this:
```html
<u class="browser-link" style="box-sizing: ...">...</u>
```
A class is created and the `style` content is moved at the component level, but right now when you select it, the StyleManager, by default, updates the class's style

**Comment by artf** [comment]
Added `config.selectorManager.componentFirst` option https://github.com/artf/grapesjs/pull/2474
