### ISSUE TITLE
Symbol.iterator in Internet Explorer doesn't work

### ISSUE THREAD

**Issue by panagulis72** [artf/grapesjs#864]
When I add an Image, in this block:
```
  for (var _iterator = files[Symbol.iterator](), _step; !(_iteratorNormalCompletion = (_step = _iterator.next()).done); _iteratorNormalCompletion = true) {
    var file = _step.value;

    _loop(file);
  }`
```

I get the error: 

> the object does not support the property or the 'jscomp_symbol_iterator0' method

It happens on IE 11.  Is there an alternative to write that loop in another way, supported by IE?

**Comment by ryandeba** [comment]
Hi @panagulis72,

Have you looked into using a polyfill? A quick google search found [this](https://github.com/medikoo/es6-symbol)...I've never used `Symbol.iterator` before, so that's probably as much as I'd be able to help :(

**Comment by artf** [comment]
Hi @panagulis72, unfortunately, that piece of code is generated by the compiler from [this method](https://github.com/artf/grapesjs/blob/dev/src/asset_manager/view/FileUploader.js#L239) (is it intentional your use of embedAsBase64?) if you want to find a way to write it up without generating it I'd be glad to merge your PR

**Comment by panagulis72** [comment]
Hi @artf ! I'm talking about this file: https://raw.githubusercontent.com/artf/grapesjs/dev/dist/grapes.js
try to search the string "  for (var _iterator = files[Symbol.iterator](), _step; !(_iteratorNormalCompletion = (_step = _iterator.next()).done); _iteratorNormalCompletion = true) "
I'm talking about this loop

But I solved this issue replacing with this code:

`    try {
      for(var i = 0; i < files.length; i++){
        var file = files[i];
        _loop(file);
      }
    } catch (err) {
      _didIteratorError = true;
      _iteratorError = err;
    } finally {
      if (_didIteratorError) {
        throw _iteratorError;
      }
    }`


I don't know if it is a good solution, but in Internet Explorer works fine

**Comment by artf** [comment]
I don't think editing a compiled file could be called a "solution"...

**Comment by panagulis72** [comment]
What do you suggest? I'm glad to approach your solution if you have one

**Comment by artf** [comment]
As I said I don't, but editing a compiled file is not a solution, you should never touch them
