### ISSUE TITLE
[QUESTION] How can I set default tagName

### ISSUE THREAD

**Issue by kbg2875** [artf/grapesjs#865]
Hi ! 
I want to set tagName `tr` for all components(or specific component in use). 
Is there any predefined function to set tagName ?

**Comment by artf** [comment]
You can change the `tagName` of any component, at any moment, in this way:
```js
const component = editor.getSelected(); // I use a selected one just as an example
component.set('tagName', 'article');
// or on some group of components
const components = editor.DomComponents.getWrapper().find('div');
components.forEach(component => component.set('tagName', 'article'));
```
You can also change it at the component level, in this way any new one of its type will get it by definition. Read more about [Components](https://github.com/artf/grapesjs/wiki/Components) and how to extend them. Basically, you would create/extend a component with a custom tagName in this way:
```js
comps.addType('you-component', {
	model: defaultModel.extend({
		defaults: { ... 
			tagName: 'tr'
		},
		...
	}),
	view: defaultView,
})
```

**Comment by kbg2875** [comment]
works great!  thanks @artf 

Is there any way to change wrapper's tagName also?
