### ISSUE TITLE
calling of grapesjs.min.js file functions

### ISSUE THREAD

**Issue by NorthstarTech** [artf/grapesjs#866]
I want to use the function spreadUrl(url) of grapesjs.min.js file in my JSP. The grapesjs.min.js file is already included in my jsp. How will I call that spreadurl function in my jsp. I tried something like this but its not working. If anyone helps how I achieve this function??

editor.getSelected.prototype.constructor.prototype....spreadUrl(url) //not working.

**Comment by artf** [comment]
If it's not a public method you can't use it

**Comment by NorthstarTech** [comment]
Ohh Okay. Thanks alot @artf
