### ISSUE TITLE
[BUG]: "component:add" event triggers when components are moved

### ISSUE THREAD

**Issue by nojacko** [artf/grapesjs#868]
Taken from https://github.com/artf/grapesjs/wiki/API-Editor

> component:add - Triggered when a new component is added to the editor, the model is passed as an argument to the callback

My understanding is that the component:add should only be called when the block is dragged in from the blocks panel and dropped into the editor. I don't think this should happen when a block is moved around the editor (that's what component:update is for...)

**Reproduce**

1. https://jsfiddle.net/szLp8h4n/11/
1. Move any of the text components around in the page.
1. An alert will be displayed.

--- 

Great project btw. 👍

**Comment by artf** [comment]
Thanks for the catch James, I'll fix it for the next release

**Comment by lv-alex** [comment]
hi, 
 When is the next release? Is it possible for us to fix it on our end before the release? We are seeing this issue now and our release goes out in 2 weeks.

thank you
ca

**Comment by artf** [comment]
@lv-alex I planned to release for the end of this week

**Comment by lv-alex** [comment]
thank you @artf . We will try it out

**Comment by lv-alex** [comment]
hi @artf,

 We have one issue. If we render email builder inside YUI layout, it still triggers add event twice.

without layout : https://jsfiddle.net/hbg7ujz5/ (no issues)
with layout : https://jsfiddle.net/yLk9Lm9v/ (issue of double rendering)

Any ideas?

*we have the latest code

**Comment by lv-alex** [comment]
It works. Thank you @artf

**Comment by japo32** [comment]
Is this anywhere in the new documentation? I can't seem to find any reference to `component:add`

**Comment by artf** [comment]
@japo32 all available public events are documented here: https://grapesjs.com/docs/api/editor.html#available-events

**Comment by seifelhoseiny** [comment]
Any update on this issue? It still calls component:add event when I simply move a component around.

**Comment by lukjaki** [comment]
It also triggers component:add when selecting different components.
