### ISSUE TITLE
[Question] Should traits be disabled / hidden when no component is selected?

### ISSUE THREAD

**Issue by ryandeba** [artf/grapesjs#869]
The style manager seems to have a nice solution for when no component is selected by showing a "Select an element before using Style Manager" message, but the trait manager does not. This is pretty easily seen in the [newsletter demo](http://grapesjs.com/demo-newsletter-editor.html):
- Select any component
  - Toggling between the style and trait panel works as expected
- Delete the selected component
  - The style panel options are hidden and replaced with a friendly message 👍 
  - The trait panel is still populated with the traits from the (now deleted) component 😕 

I'd be happy to work on a pull request to make this better, but I'm not sure what the desired behavior is... Should there be a message in the traits panel similar to the one in the styles panel?

**Comment by artf** [comment]
> Should there be a message in the traits panel similar to the one in the styles panel?
I'm would be glad to add such a functionality
