### ISSUE TITLE
Know when the editor is Initialized

### ISSUE THREAD

**Issue by panagulis72** [artf/grapesjs#872]
Is there a fallback on var editor = grapesjs.init({  }) ? I need to know when the editor is loaded and initialized

**Comment by cjpollard** [comment]
You can listen for the [event](https://github.com/artf/grapesjs/wiki/API-Editor#available-events) with: 
```
editor.on('load', fn);
```

**Comment by ryandeba** [comment]
Hi @panagulis72,

As @cjpollard pointed out, the `load` event is what you need to listen for. Here's a live example: https://jsfiddle.net/gkcgm6th/5/

**Comment by panagulis72** [comment]
Thank you very very much!
