### ISSUE TITLE
[QUESTION] Different POST params

### ISSUE THREAD

**Issue by AlessandroMagri** [artf/grapesjs#874]
Hi,
we are tring to integrate your grapejs in an existing web application.
We need to load and store data remotely adding some POST params (different in the load call and in the push call).
Is it possible?

In the case that all works well, can you support us for some customization?

**Comment by v8jupiter** [comment]
Please read maybe it wil help -> https://github.com/artf/grapesjs/issues/597

**Comment by artf** [comment]
@AlessandroMagri you basically set custom parameters in the storageManager configuration:
```js
grapesjs.init({
	...
	storageManager: {
            type: 'remote',
			...
            params: {
				// You custom parameters
				_token: '...'
			}, 
   }
});
```
Those are used for both the load and store requests, if you want you can find here #831  how to customize the already initiliazed storage manager
