### ISSUE TITLE
[Question]: Is it possible to customize the editor completely?

### ISSUE THREAD

**Issue by lorrandavid** [artf/grapesjs#875]
I really like GrapesJS functionality but I'm a little disappointed with the lack of options when it comes to the editor, it looks good by itself but sometimes I need something more customized and I couldn't figure it out yet.

Basically I need to hide the top panel, to change between "Blocks" and "Styles", I'd like to use other buttons on my interface, or maybe add tabs to the panel.

Is it possible? If positive, can someone give me tips to get this done? Thanks

Edit: Just saw @artf released v0.14.5 a few days ago, I think that's enough. Does anyone know if it works with the newsletter-preset?

**Comment by ryandeba** [comment]
Hi @lorrandavid 

It's definitely possible to custom the theme of GrapesJS - you just need to write some the appropriate CSS to fit you needs. Here's a quick, hacky jsfiddle that demonstrates a couple of the items you mentioned: https://jsfiddle.net/ntg9cspa/1/

Version 0.14.5 should work fine with the newsletter plugin. In fact, the [newsletter demo](http://grapesjs.com/demo-newsletter-editor.html) appears to be using the latest version at this time.

**Comment by lorrandavid** [comment]
@ryandeba I'm getting an error for TypeError: t.Panels.getButton(...) is null on line 
grapesjs-preset-newsletter:15:54147 which is:

```
t.on('load', function () {
      t.Panels.getButton('options', 'export-template').set('attributes', {
        title: a.expTplBtnTitle
      })
...
```

How can I solve it? I don't have any 'options' panel

**Comment by lorrandavid** [comment]
Currently I solved it like this:

```
editor.on('load', function() {
    var panelManager = editor.Panels;
    editor.Panels.render([
        panelManager.removePanel('options'),
	panelManager.removePanel('views'),
	panelManager.removePanel('devices-c'),
    ]);
});
```

But I think it's not ideal, because it first shows the editor with all the panels them they get removed, is there a way to improve it?
