### ISSUE TITLE
Liquid integration

### ISSUE THREAD

**Issue by eddyjl077** [artf/grapesjs#877]
Would it be possible to include Liquid syntax highlight in the HTML?

**Comment by maxtacco** [comment]
Hi, if you are talking about HTML displayed when exporting a template then unfortunately there is no way to customize it using the default export template command: src/commands/view/ExportTemplate.js. You can see that CodeMirror's theme is hardcoded to 'hopscotch' in there.
But, you can create your own export template command and override the default one and pass desired theme to it in options. 
You can find example of this in the grapesjs-presetnewsletter project: https://github.com/artf/grapesjs-preset-newsletter/blob/master/src/openExportCommand.js. Then just include custom CodeMirror theme css and it should work.

**Comment by maxtacco** [comment]
Sorry, you were talking about the actual language highlighting. I'm not 100% sure about that but probably you need to customize CodeMirror as well.

**Comment by artf** [comment]
@eddyjl077 you can create a new command and initialize another codemirror instance with your options (eg. #209)
