### ISSUE TITLE
[ Question ] Template Language Support

### ISSUE THREAD

**Issue by rathish** [artf/grapesjs#878]
Hi Team,

We started exploring the Grapejs for one of our requirements fitment, is there possibility to introduce template language (like mustache syntax) along with this layout builder ?  

Thanks,
Rathish

**Comment by artf** [comment]
Hi @rathish there is no intention to introduce such a functionality in the core but you definitely might be able to compile your templates just before passing them to grapesjs

**Comment by rathish** [comment]
Thanks artf, in our usecase we are planning to generate templated html from grapejs and then compiled in the runtime to generate required html files. I hope we can introduce custom plugins which can embed templates syntax
