### ISSUE TITLE
SyntaxError: Unexpected token < in JSON at position 0 in storageManager, contentTypeJson: true, 

### ISSUE THREAD

**Issue by rajatkumcom** [artf/grapesjs#879]
## WARNING
READ and FOLLOW next 5 steps, then REMOVE them before posting the issue

1. Follow CONTRIBUTING Guidelines https://github.com/artf/grapesjs/blob/master/CONTRIBUTING.md
2. Use the GitHub Issues EXCLUSIVELY for BUGS, FEATURE REQUESTS or QUESTIONS. Prefix the title of the issue with its context, eg. `[Bug]: ....`
3. Do a quick SEARCH first, to see if someone else didn't open the same issue
4. DON'T ASK to create examples/code for you, read DOCS and APIs first, then you can post what you have tried (we'd like to see your code) and what you're unable to achieve
5. All relative statements/questions have to be filled/answered, otherwise, the issue might be CLOSED

## You're submitting a BUG
  1. Are you using the latest release (older versions are NOT supported)?
      1. If you're not sure, type `grapesjs.version` in console and press ENTER
  1. Are you facing the bug with your local copy of GrapesJS or with the current demo?
  1. If a local copy
      1. Indicate all informations about your OS, browser and GrapesJS version.
      1. Are you able to reproduce the bug from the demo?
  1. What is the expected behavior?
  1. What happens instead?
  1. If you're able to reproduce the bug indicate all the necessary steps
  1. Attach screenshots (using KAP/LICEcap), screencasts or live demo
     1. JSFiddle Starter template https://jsfiddle.net/szLp8h4n
     1. CodeSandbox Starter template https://codesandbox.io/s/1r0w2pk1vl

## You're submitting a FEATURE REQUEST
  1. Be sure to work on the latest version, as the feature might be already there
  1. Keep in mind that the feature should be considered valid to use for everyone, not only for your case

**Comment by rajatkumcom** [comment]
Getting this error when trying to use:-
 storageManager: {
                  type: 'remote',
                  autosave: false,
                  setStepsBeforeSave: 1,
                  contentTypeJson: true,
                  params: {},
                  storeComponents: true,
                  storeStyles: true,
                  storeHtml: true,
                  storeCss: true,
                  urlStore: 'http://localhost/grapesjs/fileUpload.php',
                  urlLoad: 'http://localhost/grapesjs/fileLoad.php',
                }

**Comment by v8jupiter** [comment]
Can you give more details?
1. Your have this error when trying to load template from  'http://localhost/grapesjs/fileLoad.php'?
2. Or you have error in init moment. Can you show full initialization of editor?

I think your problem in this endpoint http://localhost/grapesjs/fileLoad.php.

**Comment by rajatkumcom** [comment]
When I am trying to save, then I got that error. Loading is perfect.

**Comment by rajatkumcom** [comment]
This is my code:-

<body>
    <div id="gjs"></div>
	<div id="my-first-block"></div>
    <script type="text/javascript">

	    var editor = grapesjs.init({
	    	height: '100%',
	    	clearOnRender: true,
	        assetManager: {
	        	upload: 'http://localhost/grapesjs/fileUpload.php',
	        	storeOnChange : true,
	        	storeAfterUpload : true,
	        	assets : [
	        	{ type: 'image', src : './img/bg-gr-v.png', date: '2015-02-01',height:1, width:1728},
	        	]
	        },
	        fromElement: 1,
	    	container : '#gjs',
            plugins: ['gjs-plugin-export', 'gjs-plugin-forms', 'gjs-navbar', 'gjs-component-countdown', 'gjs-style-gradient', 'gjs-blocks-basic', 'gjs-blocks-flexbox', 'gjs-plugin-ckeditor', 'gjs-aviary', 'grapesjs-lory-slider','grapesjs-tabs'],
            pluginsOpts: {
                'gjs-blocks-basic': {/* ...options */},
                'gjs-blocks-flexbox': {/* ...options */},
                'gjs-plugin-export': {/* ...options */},
                'gjs-plugin-forms': {/* ...options */},
                'gjs-navbar': {/* ...options */},
                'gjs-component-countdown': {/* ...options */},
                'gjs-style-gradient': {/* ...options */},
				'grapesjs-tabs': {/* ...options */},
				'gjs-plugin-ckeditor': {
		            position: 'center',
		            options: {
		              language: 'en',
		              //skin: 'moono-dark',
		            },
				},
				'gjs-aviary' : {},
				'grapesjs-lory-slider': {}
              },
              storageManager: {
                  type: 'remote',
                  autosave: false,
                  autoload: true,
                  setStepsBeforeSave: 1,
                  contentTypeJson: true,
                  params: {},
                  storeComponents: true,
                  storeStyles: true,
                  storeHtml: true,
                  storeCss: true,
                  urlStore: 'http://localhost/grapesjs/fileUpload.php',
                  urlLoad: 'http://localhost/grapesjs/fileLoad.php',
                }
	    });

	    editor.on('storage:load', function(e) {
                    console.log('Loaded ', e);
              });

	    editor.Commands.add( 'save-database', {
	    	run: function (editor, sender) {
				sender && sender.set('active'); // turn off the button
			    editor.store();
	
	              editor.on('storage:store', function(e) {
	                    console.log('Stored ', e);
	              });

	    	},
	    });
	    var blockManager = editor.BlockManager;

		 // 'my-first-block' is the ID of the block
		 blockManager.add('my-first-block', {
		   label: 'Simple block',
		   content: '<div class="my-block">This is a simple block</div>',
		 });
		 
		 var pnm = editor.Panels;
		  pnm.addButton('options', [{
		    id: 'undo',
		    className: 'fa fa-undo icon-undo',
		    command: 'undo',
		    attributes: { title: 'Undo (CTRL/CMD + Z)'}
		  },{
		    id: 'redo',
		    className: 'fa fa-repeat icon-redo',
		    command: 'redo',
		    attributes: { title: 'Redo (CTRL/CMD + SHIFT + Z)' }
		  },{
		    id: 'import',
		    className: 'fa fa-download',
		    command: 'html-import',
		    attributes: { title: 'Import' }
		  },{
		    id: 'clean-all',
		    className: 'fa fa-trash icon-blank',
		    command: 'clean-all',
		    attributes: { title: 'Empty canvas' }
		  },{
		    id: 'view-github',
		    className: 'fa fa-github',
		    command: 'open-github',
		    attributes: { title: 'View Github Page' }
		  },
		  { id: 'save-database',
			className: 'fa fa-floppy-o',
			command: 'save-database',
			attributes: {title: 'Save to database'} }
		  ]);

		  (function($) {
			  var iFrame = $('iframe').contents();
			  iFrame.find('.navbar-menu-link').click(function() {
				  if( ( $('.fa-eye-slash').css('display') == 'inline-block' ) || ( $('.fa-eye-slash').length == 0 ) ) {
  					  $('iframe').contents().scrollTop(iFrame.find($(this).attr('href')).offset().top);
 				  }
				});
		  })(jQuery);
    </script>
  </body>

**Comment by rajatkumcom** [comment]
I have done changes in grapes.js file which is not recommended
var typeJson = this.get('contentTypeJson');
var typeJson = false;

Resolved issue.

**Comment by maxtacco** [comment]
No need to modify GrapesJS code. Just set 'contentTypeJson' to false in storeManager config if your endpoint uses application/x-www-form-urlencoded when storing the template.
```javascript
var editor = grapesjs.init({
    ...
    storageManager: {
        ...
        contentTypeJson: false,
        ...
        }
    });
    ....
```

**Comment by rajatkumcom** [comment]
If I will set it as false, So while loading it creates problem.

**Comment by rajatkumcom** [comment]
Loaded  {0: "{", 1: """, 2: "g", 3: "j", 4: "s", 5: "-", 6: "h", 7: "t", 8: "m", 9: "l", 10: """, 11: ":", 12: """, 13: "<", 14: "f", 15: "o", 16: "r", 17: "m", 18: " ", 19: "c", 20: "l", 21: "a", 22: "s", 23: "s", 24: "=", 25: "\", 26: """, 27: "f", 28: "o", 29: "r", 30: "m", 31: "\", 32: """, 33: ">", 34: "<", 35: "d", 36: "i", 37: "v", 38: " ", 39: "c", 40: "l", 41: "a", 42: "s", 43: "s", 44: "=", 45: "\", 46: """, 47: "f", 48: "o", 49: "r", 50: "m", 51: "-", 52: "g", 53: "r", 54: "o", 55: "u", 56: "p", 57: "\", 58: """, 59: ">", 60: "<", 61: "l", 62: "a", 63: "b", 64: "e", 65: "l", 66: " ", 67: "c", 68: "l", 69: "a", 70: "s", 71: "s", 72: "=", 73: "\", 74: """, 75: "l", 76: "a", 77: "b", 78: "e", 79: "l", 80: "\", 81: """, 82: ">", 83: "N", 84: "a", 85: "m", 86: "e", 87: "<", 88: "\", 89: "/", 90: "l", 91: "a", 92: "b", 93: "e", 94: "l", 95: ">", 96: "<", 97: "i", 98: "n", 99: "p", …}

**Comment by artf** [comment]
@rajatkumcom your server have to set a correct header output, eg. in php it should be something like 
```php
header('Content-Type: application/json');
echo json_encode($data);
```

**Comment by rajatkumcom** [comment]
Thank you....
