### ISSUE TITLE
Unable to create link for image block

### ISSUE THREAD

**Issue by satyavanapalli** [artf/grapesjs#88]
I have tried to drop a link on Image block but i'm unable to do that.

**Comment by artf** [comment]
You have to use Link Block for this purpose
![link-block](https://cloud.githubusercontent.com/assets/11614725/26124105/924ad444-3a7d-11e7-91de-c70dfc591d84.png)
Once inserted in canvas you can drop inside any other component

**Comment by rogerbten** [comment]
@artf , Can you add a direct link to the image? Without using the link block

**Comment by artf** [comment]
Have to create another Component for this purpose

**Comment by murphmar** [comment]
@artf It looks like several components that are shown on the demos (ie: this Link Block, Grids) aren't part of project here on GH. Am I missing something obvious here, or is that actually the case? Thanks!

**Comment by artf** [comment]
@murphmar it's correct, some of the blocks are just there for the demo or added via presets.
