### ISSUE TITLE
Custom block with outside plugin in Grapesjs

### ISSUE THREAD

**Issue by ancanot** [artf/grapesjs#880]
I want to integrate Image viewer jquery plugin in grapesjs new custom block.
I have loaded jQuery first.
ImageViewer Plugin url - https://www.jqueryscript.net/gallery/jQuery-Plugin-For-Product-Viewer-with-Image-Hover-Zoom-BZoom.html
The problem is that, when I create component, plugin connected (I give plugin js in init() function - canvas - scripts), but

1.    I can not handle double click event for open modal and changing image (in double click event working ImageViewer click event)
2.    script which is used ImageViewer plugin (in script function) after refreshing page doesn't work again and viewer not created.
Thank you

```
editor.BlockManager.add('image-viewer', {
    category:'Media',
    label: 'Image viewer',
    attributes: {class: 'fa fa-th-large'},
    content: {
        script: function () {
            $("#bzoom").zoom({
                zoom_area_width: 300,
                autoplay_interval :3000,
                small_thumbs : 4,
                autoplay : false
            });
        },
        content: `<div class="bzoom_wrap">
                        <ul id="bzoom">
                            <li>
                                <img class="bzoom_thumb_image" src="https://unsplash.it/375/500?image=201" title="first img" />
                                <img class="bzoom_big_image" src="https://unsplash.it/750/1000?image=201"/>
                            </li>
                            <li>
                                <img class="bzoom_thumb_image" src="https://unsplash.it/375/500?image=203"/>
                                <img class="bzoom_big_image" src="https://unsplash.it/750/1000?image=203"/>
                            </li>
                            <li>
                                <img class="bzoom_thumb_image" src="https://unsplash.it/375/500?image=212"/>
                                <img class="bzoom_big_image" src="https://unsplash.it/750/1000?image=212"/>
                            </li>
                            <li>
                                <img class="bzoom_thumb_image" src="https://unsplash.it/375/500?image=220"/>
                                <img class="bzoom_big_image" src="https://unsplash.it/750/1000?image=220"/>
                            </li>
                            <li>
                                <img class="bzoom_thumb_image" src="https://unsplash.it/375/500?image=223"/>
                                <img class="bzoom_big_image" src="https://unsplash.it/750/1000?image=223"/>
                            </li>		
                        </ul>
                    </div>`
    }
});
```

**Comment by artf** [comment]
> 1. I can not handle double click event for open modal and changing image (in double click event working ImageViewer click event)

This depends on what the plugin does with the DOM. The double-click event is binded to you images but if images are somehow modified/replaced that binding might be broken. It that case I'd suggest reimplementing the [double-click logic](https://github.com/artf/grapesjs/blob/dev/src/dom_components/view/ComponentImageView.js#L8) on you parent `<div class="bzoom_wrap">` element with a new custom component

> 2. script which is used ImageViewer plugin (in script function) after refreshing page doesn't work again and viewer not created.

I think this one is related to #873
