### ISSUE TITLE
[Help Wanted]: Auto Stripping Tags with Variables?

### ISSUE THREAD

**Issue by kundarmah** [artf/grapesjs#885]
When the custom block is added, it will strip HTML tags that contains the curly braces. The anchor link will be removed. Only the div will be rendered on the canvas. Is there a way that it will ignore the variables?
```

blockManager.add('login', {
        label: 'Login Block',
        content:`<div class="forgetpass">
                    <a href="{{forgotpasswordurl}}">{{#str}} forgotten {{/str}}</a>
                </div>`
});
```

**Comment by artf** [comment]
Just tested your code with the public demo, everything works as expected
![schermata 2018-03-01 alle 00 24 42](https://user-images.githubusercontent.com/11614725/36818824-228e52fa-1ce7-11e8-93f0-fb08b7dc394a.png)

Try to check also the block content via the inspector console as it might also be some server-side effect
```js
editor.BlockManager.get('login').get('content')
```
