### ISSUE TITLE
[Help] FAIL on 'npm run build:css -- -w & webpack-dev-server --open --progress --colors'

### ISSUE THREAD

**Issue by bessouat** [artf/grapesjs#887]
Hi,

I can't get running grapesjs. Here my logs :

> # npm start
> 
> > grapesjs@0.14.5 start /var/www/web/server/grapesjs
> > npm run build:css -- -w & webpack-dev-server --open --progress --colors
> 
> 
> > grapesjs@0.14.5 build:css /var/www/web/server/grapesjs
> > node-sass src/styles/scss/main.scss dist/css/grapes.min.css --output-style compressed "-w"
> 
> /var/www/web/server/grapesjs/webpack.config.js:5
> let plugins = [];
> ^^^
> 
> SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
>     at exports.runInThisContext (vm.js:53:16)
>     at Module._compile (module.js:374:25)
>     at Object.Module._extensions..js (module.js:417:10)
>     at Module.load (module.js:344:32)
>     at Function.Module._load (module.js:301:12)
>     at Module.require (module.js:354:17)
>     at require (internal/module.js:12:17)
>     at requireConfig (/var/www/web/server/grapesjs/node_modules/webpack/bin/convert-argv.js:97:18)
>     at /var/www/web/server/grapesjs/node_modules/webpack/bin/convert-argv.js:104:17
>     at Array.forEach (native)
> 
> npm ERR! Linux 4.4.0-112-generic
> npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
> npm ERR! node v4.2.6
> npm ERR! npm  v3.5.2
> npm ERR! code ELIFECYCLE
> npm ERR! grapesjs@0.14.5 start: `npm run build:css -- -w & webpack-dev-server --open --progress --colors`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the grapesjs@0.14.5 start script 'npm run build:css -- -w & webpack-dev-server --open --progress --colors'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the grapesjs package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     npm run build:css -- -w & webpack-dev-server --open --progress --colors
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs grapesjs
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls grapesjs
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /var/www/web/server/grapesjs/npm-debug.log
> 
> 
> # cat /var/www/web/server/grapesjs/npm-debug.log
> 0 info it worked if it ends with ok
> 1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'start' ]
> 2 info using npm@3.5.2
> 3 info using node@v4.2.6
> 4 verbose run-script [ 'prestart', 'start', 'poststart' ]
> 5 info lifecycle grapesjs@0.14.5~prestart: grapesjs@0.14.5
> 6 silly lifecycle grapesjs@0.14.5~prestart: no script for prestart, continuing
> 7 info lifecycle grapesjs@0.14.5~start: grapesjs@0.14.5
> 8 verbose lifecycle grapesjs@0.14.5~start: unsafe-perm in lifecycle true
> 9 verbose lifecycle grapesjs@0.14.5~start: PATH: /usr/share/npm/bin/node-gyp-bin:/var/www/web/server/grapesjs/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
> 10 verbose lifecycle grapesjs@0.14.5~start: CWD: /var/www/web/server/grapesjs
> 11 silly lifecycle grapesjs@0.14.5~start: Args: [ '-c',
> 11 silly lifecycle   'npm run build:css -- -w & webpack-dev-server --open --progress --colors' ]
> 12 silly lifecycle grapesjs@0.14.5~start: Returned: code: 1  signal: null
> 13 info lifecycle grapesjs@0.14.5~start: Failed to exec start script
> 14 verbose stack Error: grapesjs@0.14.5 start: `npm run build:css -- -w & webpack-dev-server --open --progress --colors`
> 14 verbose stack Exit status 1
> 14 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/lib/utils/lifecycle.js:232:16)
> 14 verbose stack     at emitTwo (events.js:87:13)
> 14 verbose stack     at EventEmitter.emit (events.js:172:7)
> 14 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:24:14)
> 14 verbose stack     at emitTwo (events.js:87:13)
> 14 verbose stack     at ChildProcess.emit (events.js:172:7)
> 14 verbose stack     at maybeClose (internal/child_process.js:821:16)
> 14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
> 15 verbose pkgid grapesjs@0.14.5
> 16 verbose cwd /var/www/web/server/grapesjs
> 17 error Linux 4.4.0-112-generic
> 18 error argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
> 19 error node v4.2.6
> 20 error npm  v3.5.2
> 21 error code ELIFECYCLE
> 22 error grapesjs@0.14.5 start: `npm run build:css -- -w & webpack-dev-server --open --progress --colors`
> 22 error Exit status 1
> 23 error Failed at the grapesjs@0.14.5 start script 'npm run build:css -- -w & webpack-dev-server --open --progress --colors'.
> 23 error Make sure you have the latest version of node.js and npm installed.
> 23 error If you do, this is most likely a problem with the grapesjs package,
> 23 error not with npm itself.
> 23 error Tell the author that this fails on your system:
> 23 error     npm run build:css -- -w & webpack-dev-server --open --progress --colors
> 23 error You can get information on how to open an issue for this project with:
> 23 error     npm bugs grapesjs
> 23 error Or if that isn't available, you can get their info via:
> 23 error     npm owner ls grapesjs
> 23 error There is likely additional logging output above.
> 24 verbose exit [ 1, true ]

**Comment by artf** [comment]
Update your node
