### ISSUE TITLE
[Question]: I cannot get the simple example working

### ISSUE THREAD

**Issue by ekennedy80** [artf/grapesjs#890]
I am not new to Javascript but when I try the example:

```
<link rel="stylesheet" href="path/to/grapes.min.css">
<script src="path/to/grapes.min.js"></script>
<div id="gjs"></div>
<script type="text/javascript">
  var editor = grapesjs.init({
      container : '#gjs',
      components: '<div class="txt-red">Hello world!</div>',
      style: '.txt-red{color: red}',
  });
</script>
```

I get a blank page.  That is with adding the CSS and Javascript library.  Any suggestions on getting this up and running?  Looks like an outstanding project!

**Comment by maxtacco** [comment]
I suggest you clone one of the examples using Git and run it using NPM commands included in the project. 
In your example above I would check the paths to grapes.min.css and grapes.min.js files - make sure you do not get 404 - Not found.

**Comment by artf** [comment]
Try with this instead
```html
<link rel="stylesheet" href="https://unpkg.com/grapesjs/dist/css/grapes.min.css
">
<script src="https://unpkg.com/grapesjs"></script>
<div id="gjs"></div>
<script type="text/javascript">
  var editor = grapesjs.init({
      container : '#gjs',
      components: '<div class="txt-red">Hello world!</div>',
      style: '.txt-red{color: red}',
  });
</script>
```

**Comment by ekennedy80** [comment]
Okay, I am building a CMS using JSF 2.2 and I cannot get a simple example working in the web application.  But if I test an example using a simple file and browser I can get it to work.  Has anyone had any experience using grapsejs with JSF?  I cannot get an simple example to work in a JSF environment.  Any advice is very appreciated because grapesjs is an excellent project that I'd love to use.

**Comment by ekennedy80** [comment]
Any and all suggestions are greatly appreciated.

**Comment by artf** [comment]
@ekennedy80 it might be just a wrong path to resources (CSS/JS), check for errors in  console

**Comment by Sridhar-M** [comment]
@ekennedy80 Have you fixed this Error? I am facing this issue in my CMS too. I am eagerly waiting for the solution 😃
