### ISSUE TITLE
[Question]: Can the visibility set in layer manager be exported in getHtml

### ISSUE THREAD

**Issue by arius28** [artf/grapesjs#891]
Perhaps it should be taken into account when using getHtml() and some elements are hidden in the layer manager then they should also be hidden in the exported html. There might of course be plenty of reasons why this should not be done, in which case is there some way to get this functionality without changing the source but by extending through the API or something to that effect?

**Comment by artf** [comment]
Well, this is already as it is
![schermata 2018-03-01 alle 00 42 32](https://user-images.githubusercontent.com/11614725/36819414-b6e0b72a-1ce9-11e8-9a6f-346587f85281.png)
