### ISSUE TITLE
How to get the link value?

### ISSUE THREAD

**Issue by iceverge** [artf/grapesjs#892]
Hi Guys,

How can I get all links value before or upon saving the email template. I want to substitute the links with proxy url. In order to trap the click links. Any help much appreciated. Thanks

**Comment by artf** [comment]
```js
editor.DomComponents.getWrapper().find('a').forEach(aModel => {
	const current = aModel.getAttributes()['href'] || '';
	aModel.addAttributes({ href: `https://proxy?u=${current}`});
})
```

**Comment by iceverge** [comment]
Thanks @artf. It really helps a lot. Thanks again.
