### ISSUE TITLE
Add a custom attribute

### ISSUE THREAD

**Issue by alimajed93** [artf/grapesjs#894]
Hi everyone,

I am creating new blocks, when I use the following method:
` editor.BlockManager.add(blockId, {
       label: blockLabel,
       content: {...blockContent, **"customAttribute": "value"**},
       attributes: blockAttributes})`
I can read the customAttribute using `editor.getSelected().get("customAttribute")`

How to add this attribute and be able to get it in the same way as above, if the block created has the content in HTML format and not JSON? 
Per example: content: `<div></div>`

Thank you in advance!

**Comment by samuelmattos** [comment]
Hi @alimajed93 try it!
editor.BlockManager.get("blockId").attributes.content.customAttribute

**Comment by artf** [comment]
@alimajed93 I think you're referring to this
```html
<div data-gjs-custom-attribute="value"></div>
```
so then `editor.getSelected().get('custom-attribute')`

Be aware that attributes keys in HTML are case insensitive, therefore `data-gjs-customAttribute="value"` is parsed to `customattribute`
