### ISSUE TITLE
How to: find some component at canvas, on event "component:add"

### ISSUE THREAD

**Issue by konstantin55000** [artf/grapesjs#897]
Hi everyone,
let say i've added block <form> on canvas. When i adding next <form> (second time) ,
need to check: if weather this component already present on canvas,
call  function  implodeComponents(presentedComp, recentlyAddedComp){}

But, On event  editor.on('component:add'... i can work only with recently added component.
The question is : how to traverse through all components on canvas, to find special component (example <form>)
Please look at http://prntscr.com/ij8c82
Thank you , for help.

**Comment by konstantin55000** [comment]
For now, i see blunt  solution:, something like
//check if exist already
var nodeList = document.querySelectorAll("#wrapper form");
if (nodeList.length > 0){
         console.log("form already present");
         implodeComponents(presentedComp, nodeList );
} 
Maybe , you have cleaner thoughts..

**Comment by konstantin55000** [comment]
Thanks for your attention. 
I just read the doc.
And ended up with this solution:

   editor.on('component:add', function(currentComp) {          
        if (currentComp.attributes.tagName == "form"){
            var modelList =  (domComps.getComponents()).models;            
            var presentForms = modelList.filter(function(component) {
              return component.attributes.tagName == "form";
            }); 
            
            if (presentForms.length > 1){
                //console.log("canvas have > 2 forms");
                implodeComponents(currentComp, presentForms);
            }
        }
	});

**Comment by ionic666** [comment]
@konstantin55000 hi ,bro ,domComps.getComponents() is getting all models,i just want to get button.how can i do it?thsanks
