### ISSUE TITLE
editor.getHtml() outside the iframe of grapesjs.

### ISSUE THREAD

**Issue by NorthstarTech** [artf/grapesjs#898]
How should I get the getHtml() outside the grapesjs editor. I have a save button outside the iframe of editor. I am not getting the current html when I click the save button. 

Help Needed.

**Comment by alvimm** [comment]
You should get it by `editor.getHtml()`.

If your editor is inside an iFrame and you're executing code in a parent window, you could access it like this:
```
var indexOfIFrame = 0;
window.frames[indexOfIFrame].editor.getHtml()
```

Is this what you're looking for?

**Comment by artf** [comment]
Sorry @NorthstarTech but I totally didn't get what you're talking about

**Comment by JordanTGVG** [comment]
I have a issue in Edge browser, i cannot get the html from the editor  with:

`window.frames[indexOfIFrame].editor.getHtml()`

in chrome and mozzila is working good, any ideas?
