### ISSUE TITLE
[QUESTION]: add button to selected element panel

### ISSUE THREAD

**Issue by sergeysova** [artf/grapesjs#899]
How to add custom button to that panel:

![image](https://user-images.githubusercontent.com/5620073/36669581-67701256-1b06-11e8-96b9-3089555421a7.png)

**Comment by sergeysova** [comment]
@artf ?

**Comment by chiqui3d** [comment]
Check this
https://github.com/artf/grapesjs/issues/266

**Comment by artf** [comment]
@sergeysova follow @chiqui3d suggestion

**Comment by sergeysova** [comment]
@artf How can I get panel to add button?
or I need to modify library source?

**Comment by nitusahu-consta** [comment]
Did you able to add button to selected element panel ? 
If yes, it would be really helpful if you please explain how did you do that.
Thanx

**Comment by artf** [comment]
Toolbar buttons are component-specific, so you can have a different set of buttons for each component. Here you can see how the toolbar is created by default on each component: [`Component.initToolbar`](https://github.com/artf/grapesjs/blob/dev/src/dom_components/model/Component.js#L553)
