### ISSUE TITLE
Install failed

### ISSUE THREAD

**Issue by cubemoon** [artf/grapesjs#9]
.....
> phantomjs@1.9.19 install D:\nodejs\Project\grapesjs\grapesjs\node_modules\grunt-mocha\node_modules
\grunt-lib-phantomjs\node_modules\phantomjs
> node install.js

PhantomJS not found on PATH
Download already available at C:\Users\ADMINI~1\AppData\Local\Temp\phantomjs\phantomjs-1.9.8-windows
.zip
Verified checksum of previously downloaded file
Extracting zip contents
Removing D:\nodejs\Project\grapesjs\grapesjs\node_modules\grunt-mocha\node_modules\grunt-lib-phantom
js\node_modules\phantomjs\lib\phantom
Copying extracted folder C:\Users\ADMINI~1\AppData\Local\Temp\phantomjs\phantomjs-1.9.8-windows.zip-
extract-1455857895368\phantomjs-1.9.8-windows -> D:\nodejs\Project\grapesjs\grapesjs\node_modules\gr
unt-mocha\node_modules\grunt-lib-phantomjs\node_modules\phantomjs\lib\phantom
Writing location.js file
Done. Phantomjs binary available at D:\nodejs\Project\grapesjs\grapesjs\node_modules\grunt-mocha\nod
e_modules\grunt-lib-phantomjs\node_modules\phantomjs\lib\phantom\phantomjs.exe

> grapesjs@0.1.0 postinstall D:\nodejs\Project\grapesjs\grapesjs
> node_modules/.bin/bower install --config.interactive=false

'node_modules' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! weird error 1
npm ERR! not ok code 0

**Comment by artf** [comment]
@cubemoon 
Try to install bower globally first `npm install -g bower`, retry and let me know

**Comment by cubemoon** [comment]
Install failed again

**Comment by artf** [comment]
At first make sure to have npm and node updated. 
Try to run this `node ./node_modules/bower/bin/bower install --config.interactive=false` inside grapesjs folder and in case of errors post the full stack trace

**Comment by cubemoon** [comment]
Installed correctly. thanks

**Comment by artf** [comment]
@cubemoon you're welcome
