### ISSUE TITLE
[QUESTION] gjs-preset-newsletter not found

### ISSUE THREAD

**Issue by isaacnikon** [artf/grapesjs#902]
I am new to posting issues on github,
i am using latest version of both GrapesJS and newsletter preset from npm
i have done
var grapesjs = require('grapesjs');
require('grapesjs-preset-newsletter');
 and

ngOnInit() {
    var editor = grapesjs.init({
      container: '#gjs',
      plugins: ['gjs-preset-newsletter'],
      pluginsOpts: {
        'gjs-preset-newsletter': {}
      }
    });
  }

if i follow the same process for webpage preset it works fine, only newsletter preset i get an error in console saying gjs-preset-newsletter not found. i am trying to create a component in angular
any help would be appreciated thanks :)

**Comment by artf** [comment]
Hi @isaacnikon and welcome on board :)
Btw `grapesjs-preset-newsletter` is not added in a proper way if you want to load it globally, try with this instead
```js
var grapesjs = require('grapesjs');
var nlPlugin = require('grapesjs-preset-newsletter');
grapesjs.plugins.add('gjs-preset-newsletter-2', nlPlugin);
...
plugins: ['gjs-preset-newsletter-2'],
```

**Comment by isaacnikon** [comment]
Hi @artf 
thanks for the pointer 💃 ,
the above code was throwing an error nlPlugin not a function,

doing this helped it run 

```
var grapesjs = require('grapesjs');
var nlPlugin = require('grapesjs-preset-newsletter');
grapesjs.plugins.add('gjs-preset-newsletter-2', nlPlugin.default);
...
      plugins: ['gjs-preset-newsletter-2'],

```
thanks a lot again 👍

**Comment by absyah** [comment]
@isaacnikon Hei, `.default` does the magic. Thanks! 👍 
Also giga thanks to @artf for this awesome plugins ! ! ! 🙌
