### ISSUE TITLE
Questions ...

### ISSUE THREAD

**Issue by g40** [artf/grapesjs#904]
First off, thank you. This is really wonderful stuff. Actually it's better than that. It is astonishingly good. 

Some questions right off. Possibly feature requests, not sure. 

1. The form section has the usual widgets but no 'range' option. How can I add one?
2. More complex perhaps: is there an example of how to wrap (say) a chart.js instance so it appears in the tool palette etc? 
3. Can the tool palette be extended to allow (for example) list/picker content to be set - so it is possible to get a slightly more WYSIWYG view of the design?

I do a lot of stuff on embedded systems with web interfaces. This kind of tooling makes it vastly simpler to get seriously good looking results.

Many thanks.

**Comment by artf** [comment]
> The form section has the usual widgets but no 'range' option. How can I add one?

You should read about [Blocks](https://github.com/artf/grapesjs/wiki/Blocks)

> More complex perhaps: is there an example of how to wrap (say) a chart.js instance so it appears in the tool palette etc?

Just like above, but for a more complex behavior you have to create a new [Component](https://github.com/artf/grapesjs/wiki/Components)

> Can the tool palette be extended to allow (for example) list/picker content to be set - so it is possible to get a slightly more WYSIWYG view of the design?

I think in this case you have to deal with [Traits](https://github.com/artf/grapesjs/wiki/Traits)

**Comment by tommedema** [comment]
@g40 if you ever get to do this would it be open source? would like to have a peek

**Comment by g40** [comment]
@artf thank you for the pointers.
@tommedema yes and any help welcomed. :)

**Comment by ionic666** [comment]
@g40,hi ,have you achieved this yet？I'm looking forward to your advice about using chart

**Comment by g40** [comment]
@ionic666 Hello. Sadly not. I have had zero time. Will be reviewing shortly.

**Comment by ionic666** [comment]
@g40 Yeah, I'm looking forward to your presentation
