### ISSUE TITLE
[Question] need to find nessesary event.

### ISSUE THREAD

**Issue by konstantin55000** [artf/grapesjs#905]
Hello to all!
 
When dragging block into canvas, and drop it: 
... we have an event to detect,  what block we drop in.
```
 editor.on('block:drag:stop', function(currentBlock) {
    console.log('all good, currentBlock);
}
```

?:  but when i drop block text, into form,  (otherwords i nest one block into other) 
how can i detect : *into what specific block * nesting occurs?.
What event is specified to detect such component.
I've tried events canvas:dragenter and canvas:drop, but they dont bubbles , when drop component on canvas.

Thank you to all community , who helping with!

ps:  somehow that events are never occurs

```
 editor.on('canvas:dragenter', function(dt, currentComp) {
        console.log('canvas dragenter', dt, currentComp);
    });
    
    editor.on('canvas:drop', function(dt, currentComp) {
        console.log('canvas drop: ',dt,  currentComp);
    }); 
```

**Comment by konstantin55000** [comment]
If need to explaine more, about situation, please write.
here i've tried to describe on video
https://www.screencast.com/t/V2mGBFXp
so when text dropping into form, i need event, to detect component *form*

**Comment by artf** [comment]
Hi Konstantin, first of all, `canvas:*` events were introduced from the https://github.com/artf/grapesjs/releases/tag/v0.13.5 by using HTML5 D&D and from your screencast seems like you're not using it.
BTW what about checking the parent element from the current one
```js
editor.on('block:drag:stop', comp => {
    console.log('Am I inside the form?', comp.closest('form'));
}
```
