### ISSUE TITLE
[QUESTION] What things should I save in the database with remote storageManager?

### ISSUE THREAD

**Issue by pranzikkin** [artf/grapesjs#907]
What do I do with gjs-assets, gjs-components, gjs-css, gjs-html, and gjs-style? and how do I load these things to my editor?

**Comment by artf** [comment]
`gjs-html` and `gjs-css` are your final results, so probably you would print them on some page for the end user.
`gjs-components` and `gjs-style` contains the JSON data about your template so you have to use those if you need to edit the template in the editor

**Comment by artf** [comment]
@pranzikkin if you use custom elements and you care about the consistency with editing your templates, well yeah, you'll get problems
