### ISSUE TITLE
[FEATURE REQUEST] Add custom classes to panels and other editor elements

### ISSUE THREAD

**Issue by sebastianbarfurth** [artf/grapesjs#908]
When using a UI framework that provides custom classes, it would be nice to be able to use these classes on things like panels, so you wouldn't have to rewrite the CSS.

A possible syntax may be:

```js
panelManager.addPanel({
  id: 'myNewPanel',
  visible    : true,
  buttons    : [...],
  classes: ['myCustomClass', 'so-custom'],
});
```

It would also be useful to be able to do this after the fact for presets, using a setter for example.

```js
panelManager.getPanel('panel').set('classes', ['addedClass']);
```

I could not find a way to do this yet, specifically for panels. Though I would consider this useful for any editor UI element.

**Comment by artf** [comment]
You can set attributes in this way
```js
editor.Panels.addPanel({
	id: 'myNewPanel',
	...
	attributes: {'data-stuff': 'val1', 'classe': 'val2'}
})
```
