### ISSUE TITLE
When you add a CSS class to an element, the class name is converted to lowercase

### ISSUE THREAD

**Issue by roytang** [artf/grapesjs#91]
This happens either when adding a class using the Style Manager, or when you add from a custom block like so:

```
  blockManager.add('input-block', {
    label: 'Input',
    content: '<input type="text" class="MyCustomClass"></input>',
  });

```

Would it be possible to correct this, i.e. retain the specified casing? I am currently attempting to integrate with a project with some scripts that check for class names in a case-sensitive manner.

**Comment by artf** [comment]
yeah, currently it [uses toLowerCase](https://github.com/artf/grapesjs/blob/dev/src/selector_manager/model/Selector.js#L28) on any new class, I think a custom naming strategy might be a good option.

**Comment by roytang** [comment]
While there is no fix yet, is there an easy way for me to override escapeName in my local build? (Sorry, I'm not too familiar with how Backbone works)

**Comment by artf** [comment]
sorry @roytang but at the moment it's not possible :/

**Comment by roytang** [comment]
May I ask why it has to be set to lowercase? Will there be any adverse effects if I just remove the toLowerCase call in my local build?

**Comment by artf** [comment]
@roytang I think that was just a stylistic choice and I removed it indeed

**Comment by roytang** [comment]
thanks!
