### ISSUE TITLE
[Question]: estimation of complexity to support existing html pages without predefined CSS structure?

### ISSUE THREAD

**Issue by tommedema** [artf/grapesjs#910]
I have a large amount of static websites, some which have been developed quite a while ago (using Bootstrap etc.) and some which have been developed more recently (using CSS grid etc.). Some use inline styles, some use class based styling, some style based on component hierarchy (`#id > div > ul > li` for example), some immediately style elements by the html component name (e.g. `form`), and others use a combination of all these.

I believe that Grapes works solely with BEM-like CSS styling. I.e. each component has its own class. Is this correct?

In addition, some of these static sites depend on large CSS libraries like Bootstrap, which I would want to pass into `grapes.init`'s `style` property. Would this be very challenging to achieve?

How complex would it be for me to built in support for arbitrary CSS styling? Is this something that would require a complete overhaul or could it be done relatively easily? Would you be able to provide me with some pointers in the right direction?

**Comment by artf** [comment]
> I believe that Grapes works solely with BEM-like CSS styling. I.e. each component has its own class. Is this correct?

Is the "selector/class viewer" which is only able to let you edit styles of class-based selectors, like `.class1` `.class1.class2` but GrapesJS should import all your rules without any problem

> In addition, some of these static sites depend on large CSS libraries like Bootstrap, which I would want to pass into grapes.init's style property. Would this be very challenging to achieve?

You can load external stuff in this way
```js
const editor = grapesjs.init({
  ...
  canvas: {
    styles: ['...file1.css', '...file2.css', '...']
    scripts: ['...file1.js', '...file2.js', '...']
  }
});
```

> How complex would it be for me to built in support for arbitrary CSS styling?

What do you mean exactly with `arbitrary CSS styling`?

**Comment by tommedema** [comment]
@artf Thanks for the answer! I think I may need to explain my use case more.

It's not always realistic to expect someone importing a template to define what CSS comes from external libraries. The reason for this is that typically CSS is compiled and minified to a single bundle. So, bootstrap rules etc. will be merged together with the rules specific to this HTML page. Therefore it's not possible to define which files should be imported separately.

With arbitrary CSS styling I meant the collection of the different ways to style HTML elements with CSS selectors (classes vs native html elements vs inline etc.)

So far I noticed 3 reasons why my current templates render wrong in Grapes' editor:

1. the doctype of the template is ignored; html4 templates are rendered differently than html5, therefore doctypes should be preserved or defined when importing a template (html + css + doctype instead of html + css)

2. all class and style information defined above the wrapper is ignored, e.g. a template with such structure:

```
<!DOCTYPE html>
<html lang="nl" xmlns:og="http://ogp.me/ns#" xmlns:fb="https://www.facebook.com/2008/fbml" class="js flexbox canvas no-touch hashchange rgba multiplebgs ...">
...
<body class="  m-nl l-nl page-homepage is-loggedout  reboot  index-homepage  ">
```

Will not be rendered as it should because the classes defined in the template's html and body elements are lost.

3. Grapes is injecting CSS into my template that affects the way it renders, some of this CSS is redundant. For example it forces a `margin: 0` even though the original template did not depend on a reset margin. This causes the template to render differently inside the editor than inside a normal browser window. Fortunately this is easily fixed by removing the CSS rules that are not necessary.

I have spent 2 days going through your source code. Really like the documentation, MVC pattern, and structure with Backbone! I would be happy to propose a solution to retaining this "wrapper information" and to create a PR to resolve this.

My current prioritize is to go through the code again to fully understand the CSS parser as to answer my own questions above. I'll probably find one or two issues for which I would be happy to create PRs too.

My ultimate goal is to be able to import static HTML documents (including doctype and all styling without knowing which css rules are part of Bootstrap etc.) and to have them render in Grapes as they would in a normal browser window.

Since you suggest that Grapes should already work out of the box with any kind of CSS styling, would it be an idea that I come back to you with a static HTML + css template that renders wrong inside Grapes? I will also do my own research on why I believe it is not rendering the way it should be (other than the 3 reasons above).

**Comment by tommedema** [comment]
@artf in addition to the above questions, I have a few more questions after digging through the source. Note that I am more than willing to help you with this (I can contribute with PRs). Just need your input to see if I understand things correctly.

If I declare a simple HTML/css structure like so:

<img width="498" alt="screen shot 2018-03-02 at 16 10 13" src="https://user-images.githubusercontent.com/331833/36905675-3aa56498-1e34-11e8-960a-e1b745a8ff2d.png">

And then put a log line at `dom_components/Components.js`'s add function:

<img width="662" alt="screen shot 2018-03-02 at 16 11 18" src="https://user-images.githubusercontent.com/331833/36905741-5f23501e-1e34-11e8-91ff-337689090804.png">

This results in a surprising output of:

<img width="552" alt="screen shot 2018-03-02 at 15 59 48" src="https://user-images.githubusercontent.com/331833/36905752-6ace7de4-1e34-11e8-90a8-a95679fb8e79.png">

This raises a few questions:

1. shouldn't the `.panel` class have `selectors` defined? it's currently an empty string; the `div` css rule does have have a valid selector

2. why is the `#eee` color definition converted to `rgb` notation? wouldn't it be much safer to keep CSS the way it is defined initially? additional parsing may expose you to bugs when the added value is questionable?

3. where do the undefined css rules like `font-variant-east-asian: normal;` come from? it seems likely that such additional grunt work will render inconsistencies with the original when you parse CSS files that are thousands of lines long

**Comment by artf** [comment]
> 1. shouldn't the .panel class have selectors defined? it's currently an empty string; the div css rule does have have a valid selector

Correct, you should see `selectors: ['panel']`... this is strange, I mean without a correct selector parsing I'm not surprised you see all your templates broken, moreover, the main public demo probably would be unstyled with such a bug (and this is not what does happen). Can you please setup a live demo via jsfiddle?

> 2. why is the #eee color definition converted to rgb notation? wouldn't it be much safer to keep CSS the way it is defined initially? additional parsing may expose you to bugs when the added value is questionable?
> 3. where do the undefined css rules like font-variant-east-asian: normal; come from? it seems likely that such additional grunt work will render inconsistencies with the original when you parse CSS files that are thousands of lines long

As you see it's not only about colors but the whole style definition is bloated and this is due to the browser's CSS parser. I've already added to Roadmap the integration with some custom CSS parser (eg. postcss). Unfortunately, this one of the big pain point of **importing** stuff inside grapesjs and without such a plugin I can do nothing

**Comment by tommedema** [comment]
@artf thanks, I see. I actually like that you rely on the browser's CSS parser because I am already noticing performance issues with large templates. If you also rely on something like postcss I fear that performance may further degrade.

I am currently testing Grapes with a large variety of templates. Will compile a list of issues with fiddles.

Most rendering issues come from the fact that doctypes are not applied, but there are some others as well. There are some some functionality issues such as if you duplicate a component, and then change its style, the original component's style is also adjusted. This seems to be because grapes adjusts the original class rather than editing styles inline for the component that you have selected.

I hope I will be able to contribute as well, so first goal would be to get your insights on each issue, and then hopefully I can help out in fixing them.

Will close this issue for now and re-open when I have some examples.
