### ISSUE TITLE
[Question] Using Style tag instead of css

### ISSUE THREAD

**Issue by Owchzzz** [artf/grapesjs#913]
Hi,

I've been taking a look inside of the dom_components, but cant seem to figure out how to manually override the styling aspect.

I need a way for the component to be able to save all new styles into the style tag instead of the actual css class. (Try moving a component that was styled with force css) and it removes all of the style.

Hope you can help,
Best Regards,
Richard

**Comment by Amir2828** [comment]
So did you mange to find any complete solution that leaves the style tags intact with no changes?

**Comment by amenk** [comment]
The solution by @ryandeba seems to influence only the use of inline style attributes like `<div style="...">`. We are having the problem that
```<style>
...
</style>``` is filtered out, not sure if the OP has the same problem
