### ISSUE TITLE
[QUESTION] Enable confirmation box when remove block

### ISSUE THREAD

**Issue by JulyanoF** [artf/grapesjs#915]
Is there any option to activate a confirmation box before delete any block?

**Comment by artf** [comment]
Nope, but you can extend the default `tlb-delete` command
```js
editor.Commands.add('tlb-delete', ed => {
	if (confirm('Sure?')) {
		const selected = ed.getSelected();
		selected && selected.destroy();
	}
});
```

**Comment by Iceweex** [comment]
@artf this works only for toolbar button, but when I hit "delete" on my keyboard it doesn't. How can I override this event?

**Comment by artf** [comment]
Hi @Iceweex, unfortunately, at the moment, you can't. For the next release, I'll centralize those commands and will update also its event lifecycle, so in that case you're able to achieve the task in this way
```js
	const commandName = 'core:component-delete';
    editor.on(`run:${commandName}:before`, (options) => {
	  console.log(`BEFORE ${commandName}`);
      if (!confirm('Are you sure')) {
        options.abort = 1; 
      }
    });
    editor.on(`run:${commandName}`, (deleted, options) => {
      console.log(`AFTER ${commandName}`, deleted);
    });
    editor.on(`abort:${commandName}`, (options) => {
      console.log(`ABORT ${commandName}`);
    });
```

**Comment by rafael-chile** [comment]
Is this already integrated to the last release? This is not triggering any event -> run:${commandName}:before

Thanks a lot

**Comment by artf** [comment]
@rafael-chile 
> Is this already integrated to the last release?

Sure, if it's not working and you think it might be a bug, please create a reproducible demo and create a new issue

**Comment by alexiswbr** [comment]
I confirm that this is not working with the commands beginning by "core" like `core:foo-bar`

```php
// Not working
editor.on('run:core:component-delete:before', options => {
	options.abort = true;
	console.log('Prevent `core:component-delete` from execution');
});

// Is working
editor.on('run:tlb-delete:before', options => {
	options.abort = true;
	console.log('Prevent `tlb-delete` from execution');
});
```

**Comment by vitalik74** [comment]
@alexiswbr `run:tlb-delete:before` working only if you click on delete icon. If press `backspace` on keyboard - no.

`run:core:component-delete:before` - event working for all cases.
