### ISSUE TITLE
[QUESTION] Custom style properties per element

### ISSUE THREAD

**Issue by chthomos** [artf/grapesjs#917]
Is it possible to have custom style property UI per element.

For example, consider that I want the font-size to be shown as textbox for text components and as a radio for a custom component of mine.

The font-size property can be in the same sector.

How can this be achieved?

**Comment by artf** [comment]
Yes, I've used the same trick for the flex grid.
In your Style Manager configuration create a property in this way
```js
properties: [
	...
	{
		id: 'font-size-radio',
        type: 'radio',
        name: 'Font size (Radio)',
        property: 'font-size',
		options: [{...}, {...}],
		// With this option the proprty will be hidden 
		// until someone will not require it
		toRequire: true,
    },
	...
]
```
then in your custom component model require the property

```js
defaults: {
	...,
	'stylable-require': ['font-size-radio'],
	// Probably in your case you might want to hide the original property
	// for this component
	'unstylable': ['font-size'], 
}
```
