### ISSUE TITLE
[Question] How to change trait label?

### ISSUE THREAD

**Issue by lorrandavid** [artf/grapesjs#918]
After searching for a while, I couldn't find how to change only the trait label without overwriting everything.

This is my attempt that didn't work out

```
traitManager: {
	appendTo: '#traits',
	defaults: [
		{ name: 'title', label: 'Test' }
	]
},
```
I saw people overwriting the entire module, is that the way it should be done?
![trait](https://user-images.githubusercontent.com/17368070/36861194-fe3248c8-1d61-11e8-9bb7-757d36974a04.png)

**Comment by artf** [comment]
Currently, to change the trait's label you have to do it on the component level.
```js
// Component model
defaults: {
	...,
	traits: [...]
}
```
