### ISSUE TITLE
[QUESTION] Reinit GrapesJS

### ISSUE THREAD

**Issue by AlessandroMagri** [artf/grapesjs#919]
Hi all,
I'm writing an application that include grapesjs fron an ajax call in a specific div.
Obviusly I'd use an external menu to navigate in the application.
If I reopen the page that init the grapesjs firefox give me an error: "TypeError: this.frame.el.contentDocument is null".
I hope I've explained myself.

Is there some way to do it?

(I've read the #849 #889 and #914 but I can't find a solution)

**Comment by artf** [comment]
Subscribe to #914 probably this will be fixed in the next release
