### ISSUE TITLE
Custom select component with customisable options list

### ISSUE THREAD

**Issue by roytang** [artf/grapesjs#92]
Would it be possible to add a custom component that's a <select> tag where you can specify the <option>s somewhere as name, value pairs? It looks like I can't add them as traits since those just add attributes to the <select> tag itself?

**Comment by artf** [comment]
In #89 I show an example of how to create a basic custom trait, you could create, for example, a textarea which contains the list of options (1 option per row) and reset its components on change:

```js
onValueChange() {
      var options = this.model.get('value').split('\n');
      var optComps = [];
      for (var i = 0; i < options.length; i++) {
        optComps.push({
          tagName: 'option',
          content: options[i]
        });
      }
      var component = this.target;
      component.get('components').reset(optComps);
      component.view.render();
    },
```

**Comment by roytang** [comment]
Thanks! FYI, I had to change the getInputEl example in #89 to get it working:

```
    getInputEl() {
      if(!this.textarea) {
        this.textarea = document.createElement('textarea');
      }
      return this.textarea;
    },

```

Follow-up question: Is there also a way to update the value of the trait in the settings panel from the current options in the select when the settings panel is loaded? Currently I can update the trait to set the options in the select, but if i leave the component and go back to it, the textarea is now empty after the settings panel reloads

**Comment by roytang** [comment]
FYI, I was able to do it by overriding render() and adding the code to read the options and assigning it to the textarea's value. Not sure if this is the best place to put it, but it seems to work haha

**Comment by artf** [comment]
Yeah it's ok but I think it's better to assign value directly in getInputEl
```js
getInputEl() {
    ...
    var traitModel = this.model;
    input.value = traitModel.get('value');
    return input;
},
```
