### ISSUE TITLE
[QUESTION] Select and focus an html element from a panel button

### ISSUE THREAD

**Issue by dmm2018** [artf/grapesjs#921]
Hi everyone,

Is it possible to set focus in a section html with Grapes, like as an anchor? I have a panel button and it just select the section that I want but not focus to element. Here is the code:

       panel.addButton('options', [{
            id: 'link',
            className: 'fa fa-th-list',            
            command: function linkChap(e) {
                editor.DomComponents.getWrapper().find('section').forEach(model => {
                    const current = model.getAttributes()['id'] || '';
                    if(current == "chap10"){
                      editor.select(model);   //Here just select the section, but not set focus
                    }
                  });
            }

Thanks in advance.
Regards.

**Comment by artf** [comment]
If for `focus` you mean scrolling the view to the component, unfortunately, there is no such a method, but you can actually implement it by relying on `editor.Canvas.getBody().scrollTop`

**Comment by Amir2828** [comment]
Did you manage to make it work?
