### ISSUE TITLE
QUESTION: Adding default styling to a component

### ISSUE THREAD

**Issue by mbleverage** [artf/grapesjs#922]
I have been working on integrating grapesjs into a new development I'm working on.  I have had much success with the documentation and wiki forum but am running into a few issues I'm hoping someone out there can help me with.  I am working with a mobile view only, I have set the default device to mobile and hidden the option to change.

When I insert an image, I would like the default css to include max-width: 100% as if I load a large image into the mobile view I will get an image much larger than the screen I'm looking at.  

I have tried:
```
blockManager.get('image').set({
    style:{
        'max-width':'100%'
    }
});
```
But I realize that might be an incorrect use and maybe only width (not max-width) is valid there.  I have also tried using the cssComposer with no success. 
```
var sm = editor.SelectorManager;
var cssComposer = editor.CssComposer;
var sel1 = sm.add('img');
var rule = cssComposer.add([sel1]);
rule.set('style', {'max-width': '100%'});
```

Any help would be greatly appreciated.  Thank you.

**Comment by artf** [comment]
Your change on the block doesn't work because you don't change the actual component (just the block's property)
```js
editor.BlockManager.get('image').get('content').style = { 'max-width':'100%' }
```
With `cssComposer` instead, by default, selectorManager accepts classes
```js
...
var sel1 = sm.add('img'); // here you'r adding `.img` selector and not `img`
```

An easier way to add custom CSS might be this one
```js
editor.addComponents('<style> ... </style>');
```
But be careful, if store your templates and then run this command on any refresh this will continue to create styles. For default CSS I'd recommend:
```js
grapesjs.init({
  // CSS that could only be seen (for instance, inside the code viewer)
  protectedCss: 'img { ... }',
  
  // If have an external file, like for example, some reset CSS
  // you can use this
  canvas: {
	styles: ['https://...file.css']
  }
})
```

**Comment by mbleverage** [comment]
Thank you.  I was able to get that working by adding protectedCss: 'img {max-width:100%;} video {max-width:100%!important;} iframe {max-width:100%!important;}',

**Comment by mbleverage** [comment]
Thank you!  I was able to get that working with:
`protectedCss: 'img {max-width:100%;}',`
I have the same issue with videos and iframes (for youtube) being dropped onto the template larger than the screen size and the protectedCss solution did not work for those.  Any suggestions?

**Comment by artf** [comment]
`protectedCss` is loaded so the CSS is here, if it doesn't work probably your CSS technique is not correct
