### ISSUE TITLE
[Question]: Add a select-option to toolbar

### ISSUE THREAD

**Issue by sura2k** [artf/grapesjs#923]
I have read the code and only I could find out that there is only a list of `ToolbarButton` associated with the toolbar. I have a special trait that I would like to put it into the toolbar because it is very important to see the user which component has this trait and also to change it on the designer/canvas without having many clicks. And this select-option should only be available to some types of blocks. I think I can try to update the trait value via an event, if I can add a select-option to the tool bar. Appreciate any help.

**Comment by sura2k** [comment]
I was able to manage it by modifying `ToolbarButton' and its view. But later I decided to expose them by adding those to `DomComponents` via separate property rather than modifying `ToolBar...`, so I can extend them and since the changes are few lines, I can easily merge it with new versions of the core. I'm not a javascript guy but the way your team designed this is very highly extensible. Thanks.

**Comment by vtsoft** [comment]
Hi @sura2k,
     I also want to add a select option to toolbar. Can you please share your ideas/code/script on how did you implement it? 

     Thanks in advance.
