### ISSUE TITLE
[Bug]: calling 'preview' command not working correctly

### ISSUE THREAD

**Issue by jadebayo** [artf/grapesjs#924]
This is a piece of code that i am an using:

` this.editor = grapesjs.init(this.config)`
 `const commandManager = this.editor.Commands`
 ` commandManager.get('preview').run(this.editor)`

I want the editor to go into preview mode immediately upon loading. It does go into preview mode but the offsets are still displaying. Hovering over components still highlights. Is there some piece that needs to load before the command works properly.  When clicking on the preview button manually it works fine but calling the command from code doesn't. Is there some event  i can attach to to make sure that the editor has fully loaded before calling the command?

**Comment by artf** [comment]
Yeah, you should make use of this
```js
editor.on('load', () => editor.runCommand('preview'))
```
