### ISSUE TITLE
BUGS:Documentation/Clarity 

### ISSUE THREAD

**Issue by NealWalters** [artf/grapesjs#926]
If grapejs requires NodeJS, the doc/wiki should say that clearly upfront somewhere (i.e. list major dependencies and what type of server is needed to run it).  You mention it runs in a CMS, but don't state that it will create a full page and can or cannot run outside of a CMS. 

Question: If it runs with NodeJS - will it run on AWS Lambda (serverless)? 

Thanks
Neal

**Comment by artf** [comment]
> If grapejs requires NodeJS, the doc/wiki should say that clearly upfront somewhere

Indeed it doesn't... you need nodejs just for the [development purpose](https://github.com/artf/grapesjs#development)

> You mention it runs in a CMS, but don't state that it will create a full page and can or cannot run outside of a CMS

I think you should read better that statement...

> Question: If it runs with NodeJS - will it run on AWS Lambda (serverless)?

Sure

**Comment by NealWalters** [comment]
Thanks Art. 

Okay - let's re-read this: 
"GrapesJS was designed to be used inside a CMS to speed up the creation of dynamic templates."

That could mean I need a CMS then I paste GrapeJS into it; or it could mean it was meant for a person to create his or her own CMS.  

Maybe you could just add that "; and it always works fine to build independent HTML pages. 

Now back to NodeJS - so there are Node-JS libraries you use that are needed to design/develop a page; but when I deploy to a server, they are not needed?   Just the two lines on the getting started page: 

<link rel="stylesheet" href="path/to/grapes.min.css">
<script src="path/to/grapes.min.js"></script>

This isn't for work; but I'm new on my current job; and everybody assumes I know what they know - so they get tired of my basic questions.  :)

**Comment by artf** [comment]
Yeah it's not only about CMS but a general purpose use.
Inside grapes.min.js you will get everything you need, NodeJS is just for a correct development server (testing, merging dependencies, etc..)
