### ISSUE TITLE
[Question] Update resizer after asset changed

### ISSUE THREAD

**Issue by alfaalex81** [artf/grapesjs#930]
Hi! I trying to change default assets manager with ours custom manager.

```
    editor.Commands.add('open-assets', {
        run(editorImage,b,target) {
            editorImage.getSelected().set('src', 'http://placehold.it/'+Math.floor((Math.random() * 800) + 400)+'x'+Math.floor((Math.random() * 400) + 200)+'/fff/000/testimage.jpg');
        }
    })
```
On double click the selected image is replaced with a new one with different size. It works, but the resizers element not updating their position. It is possibile to re-initialize it?

![image](https://user-images.githubusercontent.com/37154625/37108936-e7699110-2238-11e8-8b3c-ebddd8dff780.png)

Thanks!

**Comment by artf** [comment]
Try to reselect the component
```js
var selected = editor.getSelected();
editor.select().select(selected);
```

**Comment by alfaalex81** [comment]
Thanks for your reply, I tried your suggestion, but the image is not ready yet when I launch selection update. There are a callback or a listener on loaded image?

**Comment by artf** [comment]
> but the image is not ready yet when I launch selection update

And how do you select if it's not yet ready?

**Comment by alfaalex81** [comment]
Correct, I need to select it after the image is loaded.

**Comment by artf** [comment]
@alfaalex81 mine was a question. How do you select an image if it's not yet loaded???

**Comment by alfaalex81** [comment]
I have an image on canvas, for example 300x200, double click on it and I select a new image from asset manager, now is 600x400. When i launch your suggested code the new image is not ready. I solved with a preloader, 

In Italy we say: "I am lost in a glass of water" :)

Thanks for the support.
