### ISSUE TITLE
[QUESTION] In creating a custom block how do you create it's corresponding settings?

### ISSUE THREAD

**Issue by pranzikkin** [artf/grapesjs#935]
I want to make a link that will let the user enter the url for it or to let him choose a link to another page which he already created.

**Comment by artf** [comment]
Check [Traits](https://github.com/artf/grapesjs/wiki/Traits)

**Comment by pranzikkin** [comment]
@artf can you me in adding a trait to the link block(defined in basic block) to insert a trait that is of type select and the selected value would change the link's href?

**Comment by pranzikkin** [comment]
@artf got it working already! thank youuu. now my problem is when I click the link(in basic blocks). it does not open a new windows and laod the url? it only works if I right click->open new tab.

**Comment by pranzikkin** [comment]
@artf thanks! got it working! When I was looking at the wiki I totally missed the Traits section. sorry for that artf. but now I do have a problem. When I click my link it does not trigger. The html composition is correct. can you help me with this?
