### ISSUE TITLE
[Question] How to integrate handlebars with GrapesJS?

### ISSUE THREAD

**Issue by andre2** [artf/grapesjs#938]
Hi,
How i can integrate `handlebars` or other template engine with `GrapeJS`?
I mean to create eg. dynamic component with product details:

```js
const blockManager = editor.BlockManager;

blockManager.add("product", {
  label: "Product",
  type: "text",
  attributes: { class: "fa fa-columns" },
  content: `
    <div>
      <h2>{{product.name}}</h2>
      <div>{{product.details}}</div>
    </div>
  `
});
```

And show parsed data in `GrapeJS` editor eg.
```html
<div>
  <h2>Sample product</h2>
  <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque tristique molestie mi, a commodo quam cursus eget.</div>
</div>
```

But on export user must get raw data, i mean code with `handlebars` content.
Someone can help?

**Comment by artf** [comment]
You should create a custom [Component](https://github.com/artf/grapesjs/wiki/Components) which implements the template engine inside its view (eg. compile the template inside the render method)

**Comment by ondrejpolach** [comment]
Hi andre2, do you complete this solution for handlebars integration? can you share some code please?
