### ISSUE TITLE
When the editor autoloads from storage after a browser refresh, trait values in the settings panel are not retained.

### ISSUE THREAD

**Issue by roytang** [artf/grapesjs#94]
Not sure if this is intentional, but changes made on the style panel seem to be retained (if I set style text color to green, it's still green after I refresh). Changes made to trait values are not retained.

**Comment by artf** [comment]
I think the problem might be that trait changes are not triggering the storage. Did you try to make some other change after the one with the trait (add new block, change some style property, etc.) and check if it stored?

**Comment by roytang** [comment]
Hmm. Behavior is weird. I tried something like style change, trait change, style change, trait change, style change. On reload, the last trait change and the last style change were retained. I'll test in more detail when I have time.

**Comment by artf** [comment]
This should be fixed by #187
