### ISSUE TITLE
GrapeJS can't load javascript

### ISSUE THREAD

**Issue by phucphanJaneto** [artf/grapesjs#940]
Hi.
I have some script tag in my html code (includes js file and internal javascript tag)
But GrapeJS doesn't load any script and apply this. 

Can I have any way load javascript to grapejs and export html include javascript code?

**Comment by vishal5033** [comment]
Hi @phucphanJaneto 

You can allow script when you init grapesJS instance.

const editor = grapesjs.init({
	...
	allowScripts: 1,
});

Hope that helps you.

**Comment by phucphanJaneto** [comment]
@vishal5033 : many thanks for your helps. it works for me.
The script file and internal js will show when export html.
But I see the error message: 
![image](https://user-images.githubusercontent.com/37202364/37196150-4d1ef64c-23a8-11e8-824f-2ae3d2c83a5a.png)
and
![image](https://user-images.githubusercontent.com/37202364/37196174-64b10e80-23a8-11e8-94d7-64d1248f2e09.png)

can you help me?

**Comment by pranzikkin** [comment]
@phucphanJaneto try to post your code? maybe something is missing or you got the wrong syntax.

**Comment by phucphanJaneto** [comment]
Yes.
```
var newComps = editor.DomComponents;
window.newCom = newComps;
$.get(response.HtmlLink, function (e) {
      newComps.setComponents(e);
   })
})
window.editor.setComponents(newComps);

```
You can test with attach html. 
[b0c0c79f-41e5-437d-aa12-4aa3bfb198df.zip](https://github.com/artf/grapesjs/files/1796738/b0c0c79f-41e5-437d-aa12-4aa3bfb198df.zip)

**Comment by artf** [comment]
@phucphanJaneto you're doing something wrong here
```js
$.get(response.HtmlLink, function (e) {
	  // check the `e`, shoud be an HTML string or Component Object
      newComps.setComponents(e);
   })
})
```

**Comment by phucphanJaneto** [comment]
Yes. this is a HTML string. i load html file which sent to you.

**Comment by phucphanJaneto** [comment]
Heym @artf 

Can you see my comment above?

**Comment by artf** [comment]
Check better the response (it might be a case to escape the string) and if headers are correct
