### ISSUE TITLE
Drag and drop blocks is not working in IE Browser

### ISSUE THREAD

**Issue by suthars** [artf/grapesjs#944]
Hi,

There is some bug related to "Drag and drop functionality is not working in IE Browser ", i have tried to find out the solution regarding this  but as per documentation there is no finite solution of this issue 
Also there is no method to reinitialize the grapes editor.
i think it has few browser compatibility issues ,so please provide better solution for drag and drop blocks using grapes editor  in IE browser.

Thanks

**Comment by artf** [comment]
Follow the issue template please
