### ISSUE TITLE
[QUESTION / FEATURE REQUESTS] : How to translate grapejs

### ISSUE THREAD

**Issue by FoxXav** [artf/grapesjs#945]
Hi,

I check the sources but it didn't seems to have a centralized language file (one per plugins per example) but multiple places where wording must be translated. Am I wrong ?
I would like to be able to use english and french interfaces.

So I would like to know how to translate grapejs (and it's plugins) to other languages. And if possible in a centralized way (this part could be the feature request).

Nevertheless great work.

See you.

**Comment by artf** [comment]
Hi @FoxXav you can check #26 about i18n and why currently I have no plans for it
