### ISSUE TITLE
[Bug]: overflow:hidden on .gjs-block-label clips the text

### ISSUE THREAD

**Issue by mpr32** [artf/grapesjs#946]
Using dev@HEAD (https://github.com/artf/grapesjs/commit/9a71368f43d690405d3c60682c7dfee83fd87a4e) you can see that the Test block has it's label clipped, as shown in both Firefox and Chrome below. NB this doesn't happen on release v0.14.5

![chrome](https://user-images.githubusercontent.com/16925146/37339248-f56976c2-26b1-11e8-8c0a-1b8438299ead.PNG)
![ff](https://user-images.githubusercontent.com/16925146/37339249-f582924c-26b1-11e8-98f4-230c8b7c18c8.PNG)

**Comment by artf** [comment]
I'm not facing it on my side (Mac), probably due to the font size differences the whole content exceeds block's `height: 90px;`. We need `overflow:hidden` to avoid the text overflow with big strings. Probably just by setting `min-height: 90px;` on the block is enough
