### ISSUE TITLE
Editor.setdevice() not working properly on some browsers.

### ISSUE THREAD

**Issue by attaalive** [artf/grapesjs#950]
I am changing the device by using editor.setdevice function by calling it in document.ready function. On most devices it is working fine but on some MacBooks by using Google Chrome browser it is only changing the canvas size not updating the dropdown that is showing the devices name. Please help me to solve this bug. I have attached a screenshot too in which canvas size is for "A8" device but it is displaying "A0" in device dropdown.
![screen shot 2018-03-14 at 5 45 41 pm](https://user-images.githubusercontent.com/6896243/37452428-659fa420-2856-11e8-8de3-988cc65ed79d.png)

**Comment by artf** [comment]
Please follow the issue template
