### ISSUE TITLE
[Question] Drag&drop of button on demo has additional css attributes

### ISSUE THREAD

**Issue by nicolaskern** [artf/grapesjs#954]
Hi,

On the newsletter demo, when drag&dropping a button, some additional css attributes are added to the <a>. It seems like they come from the <style> defined on the same page, but I can't get it working on my implementation.

Is there any special configuration to put?

Thanks,
Nicolas

**Comment by artf** [comment]
The source of the demo is here https://github.com/artf/grapesjs/blob/gh-pages/demo-newsletter-editor.html

**Comment by nicolaskern** [comment]
Hi,

I actually already have spent time analyzing the source code of the page, and there is - for me - no reason not to have the CSS put in the <a> when I drag&drop it.
I couldn't find any override of the component, or anything saying to use that very CSS.

Thanks,
Nicolas
