### ISSUE TITLE
How to Change General look of the grapes js editor

### ISSUE THREAD

**Issue by narraressan** [artf/grapesjs#96]
Hello guys. I am not sure whether this is the right place to ask this question since this is not a bug but just a simple inquiry. 

I was just wondering, is there any way that I can change the editor? I mean can I design another editor and have grapesjs functions attached to it? since I am planning to make forms using this grapesjs in mobile but the editor is just too big for the small screens... 

I hope you can give light to this lost sheep... thank you...

**Comment by artf** [comment]
Hi @narraressan, I think It might be enough some CSS and JS work (you can move panels once they rendered) to make it more mobile friendly :)
