### ISSUE TITLE
Grapesjs not starting

### ISSUE THREAD

**Issue by VCheque** [artf/grapesjs#962]
When I execute **npm start** it shows

$ npm start

> grapesjs@0.14.6 start C:\Users\a233243\grapesjs
> npm run build:css -- -w & webpack-dev-server --open --progress --colors

> grapesjs@0.14.6 build:css C:\Users\a233243\grapesjs
> node-sass src/styles/scss/main.scss dist/css/grapes.min.css --output-style compressed "-w"

Just stop there. Can someone help?

**Comment by beckerc** [comment]
Hi, had same issue, I solved it by  installing webpack-dev-server as global
**npm install webpack-dev-server -g**

and there was double dashes on the **start** script, after  the **build:css**
**"start": "npm run build:css -- -w & webpack-dev-server --open --progress --colors",**

when removed these dashes it worked for me.

**Comment by VCheque** [comment]
Thanks dude

More one thing, I can't find the Start Script. Where is it???

Valter Cheque
Licenciado em Engenharia Informática - UEM
+258 826002027
+258 846370199

**Comment by VCheque** [comment]
Founded
Thanks you..!!

Valter Cheque
Licenciado em Engenharia Informática - UEM
+258 826002027
+258 846370199

On Mar 20, 2018 9:06 AM, valtercheque@gmail.com wrote:

Thanks dude

More one thing, I can't find the Start Script. Where is it???

Valter Cheque
Licenciado em Engenharia Informática - UEM
+258 826002027
+258 846370199

On Mar 19, 2018 8:11 PM, "Becker Chaaban" <notifications@github.com> wrote:

Hi, had same issue, I solved it by installing webpack-dev-server as global
*npm install webpack-dev-server -g*

and there was double dashes on the *start* script, after the *build:css*
*"start": "npm run build:css -- -w & webpack-dev-server --open --progress
--colors",*

when removed these dashes it worked for me.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/artf/grapesjs/issues/962#issuecomment-374312050>, or mute
the thread

**Comment by beckerc** [comment]
Hi, you are welcome

**Comment by artf** [comment]
can't reproduce (without global webpack-dev-server)
I think it might be an issue with your environment, post please your info about **OS**, **npm** and **node** versions

**Comment by tomasz-nowakowski-stx** [comment]
@artf the problem is on windows. `&` does not make a comment to run in background. So `npm start` runs  `node-sass` in watch mode and does not start `webpack-dev-server` because `node-sass` did not finish.

**Comment by Abhisheknanda1344463** [comment]
@beckerc @artf  I also unable to build my css.
#1403
