### ISSUE TITLE
[Question] Create PHP endopoint to remote Storage Manager

### ISSUE THREAD

**Issue by theleoni** [artf/grapesjs#963]
Hello. 
I'm integrating GrapeJS with PHP (CodeIgniter) and I saw that there are others who do this. But I looked in the documentation and checked the bugs and questions and I still do not know how I can create the endopoint (upload and download) for the remote Storage Manager API connection. Is there any example I can follow to create my endopoint correctly?

**Comment by artf** [comment]
There are no rules on "how to create YOUR endpoints" just receive/send data from the server (check the devtool network inspector if you're not sure about the data). About the grapesjs configuration https://github.com/artf/grapesjs/wiki#storeload-data
