### ISSUE TITLE
[QUESTION] How to load external CSS file into Grapes Editor?

### ISSUE THREAD

**Issue by fsaiyedOB** [artf/grapesjs#966]
Hey,
During my editor = grapesjs.init(), I want to load an external CSS file into the canvas using @import url(...). So when I use my custom components which are using those external CSS stylings, should render properly. Also, those URL should include in editor.getCss().
How can I do that?
Thanks in advance.

**Comment by chapterjason** [comment]
https://github.com/artf/grapesjs/issues/195
https://github.com/artf/grapesjs/issues/473
https://github.com/artf/grapesjs/issues/444
https://github.com/artf/grapesjs/issues/66

Here are some solutions, please search next time before open an issue.

**Comment by fsaiyedOB** [comment]
Thanks for the help. This works perfectly. I tried searching issues with '@import' query, my bad.
