### ISSUE TITLE
Traits not showing with reference code: How to show traits along with style manager as in demo

### ISSUE THREAD

**Issue by Deepak813** [artf/grapesjs#968]
Hi @artf,

We found that when we download the latest grapesJs package in that traits tab are showing in different and online demo shows the traits in same style manager.

We have used below reference code but nothing change:
https://github.com/artf/grapesjs/blob/gh-pages/demo.html#L1366-L1397

Main question is why the demo and new release code are different?

Also, traits are working file with 0.13.8 release but changed in 0.14.5 or 6 version.

**Comment by artf** [comment]
> Main question is why the demo and new release code are different?

The demo uses [different plugins](https://github.com/artf/grapesjs/blob/gh-pages/demo.html#L979) and some [other customizations](https://github.com/artf/grapesjs/blob/gh-pages/demo.html#L1384-L1423) so this is why are different

> Also, traits are working file with 0.13.8 release but changed in 0.14.5 or 6 version.

Open a new issue explaining exactly what is wrong with traits (follow the issue template please)
