### ISSUE TITLE
[BUG] Video block - Loop option

### ISSUE THREAD

**Issue by alimajed93** [artf/grapesjs#969]
Hello everyone,

I noticed that when you drag and drop a video block to the canvas, choose youtube, add the correct video ID and check the loop option, it doesn't work as expected. It works well for HTML5 and Vimeo though.

The url changes when checking this option adding `loop=1`: `https://www.youtube.com/embed/5Q80bhJYTII?&autoplay=1&loop=1`, but when the video finishes, it is not repeated, as you see in the following image:
<img width="637" alt="screen shot 2018-03-21 at 3 44 15 pm" src="https://user-images.githubusercontent.com/28840780/37713182-bed52714-2d1e-11e8-9ef5-56556c09f2e3.png">

Regards.

**Comment by artf** [comment]
Seems like the `loop` is broken and works only with `playlist` enabled https://stackoverflow.com/questions/25779966/youtube-iframe-loop-doesnt-work
I'll add it to the loop parameter
