### ISSUE TITLE
Add Grapejs to Packagist

### ISSUE THREAD

**Issue by dedanirungu** [artf/grapesjs#97]
I am a php developer and I use composer to update my components. I can not find this project on packagist (www.packagist.org)

**Comment by artf** [comment]
Hi @dedanirungu, GrapesJS is just a front-end library so there is no reason to have it in Packagist if not for some kind of wrappers

**Comment by dedanirungu** [comment]
Hi @artf We usually use a number of javascript and css files that are hosted on packagist for easy distribution and update. some of this scripts are tinymce, fontawesome, bootstrap etc. 

I am about to start working on a project that will use grapejs. How can I receive update files every time you release an update.

**Comment by Chinese1904** [comment]
Why don't you use GitHub?

**Comment by dedanirungu** [comment]
The best thing with packagist is version control. Take the following example.

I have a project that uses grapejs version 0.5.* and I want to only pull that version until such a time when I will be able to upgrade to a new version. Let assume grapejs upgrades to version 1.0.* and in the process some features and functions are deprecated. With packagist all applications that use 0.5.* will not be affect by the changes and they will have enough time to migrate and update their code to the newer version.

I prefer packagist due to it version control within my application for all dependencies.

To add this project to packagist is an easy process

1. Open packagist.org
2. Copy the link https://github.com/artf/grapesjs and past it in submit input box in https://packagist.org/packages/submit
3. Open the page https://github.com/artf/grapesjs/settings, click the tab "Integration and Service" and and look for button "Add Service"
4. In "Add Service" List select packagist
5. Deploy

**Comment by Chinese1904** [comment]
Sure, I know what packagist is and pulling components from there is pretty easy, even though I never would never use packagist to pull components. 
What you just described can be done just as easily without being on packagist though for the time being it isn't.

**Comment by dedanirungu** [comment]
Would you please add it for me or anyone who would prefer to control dependency version in similiar way.
For example with bootstrap I am able to control the version to be used for the project without worrying about future changes. Currently in all projects I am using version 3 and will only move to version 4 once I complete updating my code.

**Comment by artf** [comment]
@dedanirungu nothing personal, but Packagist is the "PHP Package Repository" so I just see it somehow wrong.
Anyway, I think you can use custom repositories with composer to get what you want:
```json
"require": {
        "php": ">=5.6.4",
        "artf/grapesjs": "dev-master"
    },
"repositories": [{
            "type"    : "package",
            "package" : {
                "name"    : "artf/grapesjs",
                "version" : "dev-master",
                "type"    : "js-library",
                "source"  : {
                    "url"       : "https://github.com/artf/grapesjs.git",
                    "type"      : "git",
                    "reference" : "origin/dev"
                }
     }
}],
```

**Comment by dedanirungu** [comment]
Is ok then. 
but just know even none php project are on packagist and it helps alot. eg bootstrap, fontawesome, jquery, tinymce etc. 

You can close the issue.

**Comment by Chinese1904** [comment]
Anything front-end related you should try yarn and webpack. 👍
