### ISSUE TITLE
[BUG] Video block - Switching providers

### ISSUE THREAD

**Issue by alimajed93** [artf/grapesjs#970]
Hello everyone,

I noticed that when you drag and drop a video block and before adding any url, if you switch providers (choose youtube or vimeo), an error appears in the console while the block is functioning normally.

In case you choose youtube, the error received is:
<img width="1280" alt="screen shot 2018-03-21 at 3 50 55 pm" src="https://user-images.githubusercontent.com/28840780/37713487-c4ecd826-2d1f-11e8-9a88-0f5d0c30be14.png">

And in case you choose Vimeo:
<img width="1278" alt="screen shot 2018-03-21 at 3 52 42 pm" src="https://user-images.githubusercontent.com/28840780/37713550-f0ee6ac0-2d1f-11e8-9712-689111a71402.png">

This might be because the url is blank and the url is pointing for a non existing video, but even if you add a correct video ID, in my case add a correct youtube video ID and then choosing youtube as provider, you will still receive an error:
<img width="643" alt="screen shot 2018-03-21 at 3 53 34 pm" src="https://user-images.githubusercontent.com/28840780/37713666-4752122c-2d20-11e8-82d4-8746aed9118a.png">

Regards.

**Comment by artf** [comment]
Well Vimeo's case is pretty much self-explanatory, about the Youtube, it's a chromium bug https://bugs.chromium.org/p/chromium/issues/detail?id=807304 and you'll see this error on any page with an embedded youtube player, so just need to wait till they'll sort this out
