### ISSUE TITLE
[Question] Removing the deviceManager and ViewCode buttons

### ISSUE THREAD

**Issue by PCPLTodd** [artf/grapesjs#974]
I'm playing with the default init to try and remove the deviceManager and ViewCode buttons...

`        var editor = grapesjs.init({
            showOffsets: 1,
            noticeOnUnload: 0,
            container: '#gjs',
            height: '100%',
            fromElement: true,
            assetManager: { upload: false },
            storageManager: { autoload: 0 },
            styleManager: {
                sectors: [{
                    name: 'General',
                    open: false,
                    buildProps: ['float', 'display', 'position', 'top', 'right', 'left', 'bottom']
                }, {
                    name: 'Dimension',
                    open: false,
                    buildProps: ['width', 'height', 'max-width', 'min-height', 'margin', 'padding'],
                }, {
                    name: 'Typography',
                    open: false,
                    buildProps: ['font-family', 'font-size', 'font-weight', 'letter-spacing', 'color', 'line-height', 'text-shadow'],
                }, {
                    name: 'Decorations',
                    open: false,
                    buildProps: ['border-radius-c', 'background-color', 'border-radius', 'border', 'box-shadow', 'background'],
                }, {
                    name: 'Extra',
                    open: false,
                    buildProps: ['transition', 'perspective', 'transform'],
                }
                ],
            },
        });`

All I can do is remove all the toolbars by inserting a panel:{[]} option. Everything I out in to try and get back the other buttons doesn't work.

Suggestions?

**Comment by ryandeba** [comment]
Hi @PCPLTodd,

Here's an example of how you can remove the device switcher and view code button: https://jsfiddle.net/fjkk8w6k/2/

**Comment by PCPLTodd** [comment]
Thanks Ryan, that worked great! :D

**Comment by labmux** [comment]
> Hi @PCPLTodd,
> 
> Here's an example of how you can remove the device switcher and view code button: https://jsfiddle.net/fjkk8w6k/2/

I dont know if this is the best solution. It looks like this just makes element invisible but it still exists since my cursor goes in hover mode when i hover over where devices wouldve been. Its like an invisible button and I cant have that on a professional project.

I think were supposed to use editor.Panels.removePanel('devices-c') but its not working for me for some reason, even though this function works with all the other panels

**Comment by hlo2109** [comment]
Hi, I know it's late, but this is how I did it right now:
editor.Panels.removeButton('devices-c', 'set-device-desktop');
editor.Panels.removeButton('devices-c', 'set-device-tablet');
editor.Panels.removeButton('devices-c', 'set-device-mobile');
editor.DeviceManager.getAll().reset();
