### ISSUE TITLE
[Question] Default values for traits field

### ISSUE THREAD

**Issue by rajanbharti** [artf/grapesjs#975]
I have created component with certain traits. I am not able to assign default value to traits by passing values. It is coming as undefined for color type, blank for text field.

``` 
traits: [ {
          type: 'text',
          label: 'Placeholder',
          changeProp: 1,
          name: 'placeholder',
          value: 'Type your text here'
        },
        {
          type: 'color',
          label: 'Icon Color',
          changeProp: 1,
          name: 'iconColor',
          value: '#000000'
        }]
```
![sett_gjs](https://user-images.githubusercontent.com/12953200/37754127-3eeb03b8-2dc6-11e8-9ee2-5908f2579d6b.png)

Any changes in field is getting reflected in component

**Comment by artf** [comment]
Traits should read the default directly from their props/attributes, so in your case, it should be something like this:
```js
iconColor: '#000000',
placeholder: 'Type your text here',
traits: [ {
          type: 'text',
          label: 'Placeholder',
          changeProp: 1,
          name: 'placeholder'
        },
        {
          type: 'color',
          label: 'Icon Color',
          changeProp: 1,
          name: 'iconColor'
        }]
```

**Comment by rajanbharti** [comment]
Thanks!

**Comment by rajanbharti** [comment]
in your case, defaults should be like
`  typeid: 0 ` pointing to the first element as default
