### ISSUE TITLE
Cell resizing via drag handle broken

### ISSUE THREAD

**Issue by TimNZ** [artf/grapesjs#976]
Bugs

Add 2 column block, select a Cell, and use resize handle to resize width.

* Realtime width change of cell does not track the mouse pointer.
* Dimensions fields/calculation seem broken, switching between % and px in unexpected ways.
* Resize handle intermittently disappears

Suggest
* Manual Cell resize needs to use a sane method to switch to px with a starting width.
* entering auto/non-numeric into any size field clears unit
* visual resize as expected

https://www.dropbox.com/s/avosmi1k16jgd3f/grapesjs-cell-resizing.mp4?dl=0

**Comment by artf** [comment]
> Realtime width change of cell does not track the mouse pointer

The current grid uses flexbox and as it tries to adapt itself in relation to its sibling nodes what you're asking it's not possible

> Dimensions fields/calculation seem broken, switching between % and px in unexpected ways.

Not broken, there are just no calculations in unit changes

> Resize handle intermittently disappears

This is something I can try to fix

**Comment by TimNZ** [comment]
Thanks for the reply.  I'll have a play as well.

Awesome awesome awesome work with Grapes, greatly appreciated.

I'm using a number of components that have had a huge amount of work put in by many people and will support as soon as I can afford to.

**Comment by TimNZ** [comment]
@artf legend!
