### ISSUE TITLE
[BUG] Video block - Controls option in case of Vimeo provider

### ISSUE THREAD

**Issue by alimajed93** [artf/grapesjs#977]
Hello everyone,

I noticed that when you select Vimeo as a provider in a video block, and uncheck the "Control" option, the controls will still be there and you cannot remove them.
![screen shot 2018-03-22 at 1 17 21 pm](https://user-images.githubusercontent.com/28840780/37767692-aaacf3b0-2dd3-11e8-91d9-c6701f9723ba.png)

Regards.

**Comment by artf** [comment]
Seems like now it's only a feature for Pro accounts...
https://help.vimeo.com/hc/en-us/articles/224969968-Embedding-videos-overview
I'll remove it then
