### ISSUE TITLE
Custom component type's children are not editable, selectable or highlightable 

### ISSUE THREAD

**Issue by anand-gopinath** [artf/grapesjs#978]
@artf I'm creating a custom component of Default type and the code looks like

![saf](https://user-images.githubusercontent.com/25955939/37830429-3023ab2a-2ec8-11e8-84bb-0faccde50839.png)

Even I refereed #260 and implemented as you suggested. Here, the custom `div` tag holds the functionalities of selectable, removable and highlightable etc. I need the child elements as well to be selectable and highlightable. How to do that?

And one more, If do the same thing via BlockManager, it works for all parent and its children
![344](https://user-images.githubusercontent.com/25955939/37831229-be7be340-2eca-11e8-9419-5fc9b6d1d099.png)

**Comment by artf** [comment]
You can't use `data-gjs-*` attributes if you attach them directly to the DOM, those attributes are parsed from the model level, so `model.components('<div data-gjs-*...')`
