### ISSUE TITLE
Not able to align the custom component

### ISSUE THREAD

**Issue by anand-gopinath** [artf/grapesjs#979]
@artf I created my custom component tyep and inserted vai BlockManager and if I'm applying the style  propeties to that, is not working.

![align](https://user-images.githubusercontent.com/25955939/37831869-e1e54b4e-2ecc-11e8-9cf6-824d9cb1b849.png)

**Comment by artf** [comment]
I don't know what your `Align` stands for but 'Text align' should be applied to the parent element
