### ISSUE TITLE
[BUG] Related with task https://github.com/artf/grapesjs/issues/873 

### ISSUE THREAD

**Issue by v8jupiter** [artf/grapesjs#980]
Hello, 
After restoring editor from db still have some part of bug present.
It seems inside of script: function () traits will have old value.
Short explanations:
`        script: function() {
          var startfrom = '{[ startfrom ]}';
          var endTxt = '{[ endText ]}';`
In variable startfrom and endTxt we will have old values

Video explanation: https://youtu.be/buHJcHcpU8s

**Comment by artf** [comment]
Thanks for the catch Vlad, it'll be fixed in the next release
