### ISSUE TITLE
[Question] Set "production" mode

### ISSUE THREAD

**Issue by theleoni** [artf/grapesjs#981]
Hi. Like the "Preview" mode, i'm like to show only the canvas (without bars on the side/top), without the eye icon at corner. Has any "production" mode or something like this? It's the `editor.getHtml()` close to this?

**Comment by artf** [comment]
No, there is no "production" command, but you can create easily one by checking the [Preview](https://github.com/artf/grapesjs/blob/dev/src/commands/view/Preview.js).
```js
editor.Commands('Production', {
	run() {
		// production mode ON
	},
	stop() {
		// production mode OFF
	}
})
```
