### ISSUE TITLE
[BUG]: Exported CSS cannot override body's background-color

### ISSUE THREAD

**Issue by nojacko** [artf/grapesjs#986]
When a body background style is defined in the `style` option of the init function it's not possible to override.

Given the style: 
```
body {
    background-color: #000000;
}
```

After changing the background-color in Grapes, the CSS output is:
```
body {
    background-color:#f80000; /* Colour selected in Grapes */ 
}
body {
    background-color:rgb(0, 0, 0); /* Original colour that should be overwritten */
}
```

Due to the ordering, the original colour will take precedence when used. 

While not necessarily an issue, the repetition  of `body` isn't needed and would probably solve this issue if the `body` css definition was merged. I believe this happens with other CSS selectors too. 

# Steps to reproduce
1. https://jsfiddle.net/jk3g2eu2/
1. Click the wrapper in the canvas
1. Change background color.
1. Click the code icon to see generated CSS.

**Comment by artf** [comment]
Thanks James, we already aware of it #552 but unfortunately not yet provided any fix :/
The main problem is that GrapesJS doesn't handle well body/wrapper styling and so, as a result, we have the `body` coming from 3 different spots:
- from [baseCss](https://github.com/artf/grapesjs/blob/dev/src/editor/config/config.js#L37) option
- from the wrapper's component style (which usually is the body and so [I handle it separately](https://github.com/artf/grapesjs/blob/dev/src/code_manager/model/CssGenerator.js#L27)) 
- and like in your case, also from another CSSRule (created by `style: 'body{background-color:#000000;}'`)
We need to find a correct way to handle all these cases but I didn't yet find time to look at it, so I'd appreciate any advice/help.
I close this and suggest you subscribe to #552 if you want any further updates.
