### ISSUE TITLE
[BUG/Question] Dropdown indicator not displayed for a custom trait

### ISSUE THREAD

**Issue by baxxos** [artf/grapesjs#987]
Hello,

the dropdown (select) element arrow indicator icon is not rendered when adding a custom trait to a component:

![image](https://user-images.githubusercontent.com/17254686/38093011-01d5efb6-336a-11e8-931e-709ad1be009d.png)

I'm using following code to add the custom trait to the link component:
```
editor.TraitManager.addType('internal-link', {
    // A custom option-loading function
    loadOptions: function (inputEl) {
        foo();
    },
    getInputEl: function () {
        if (!this.inputEl) {
            var input = document.createElement('select');
            this.loadOptions(input);

            this.inputEl = input;
        }
        return this.inputEl;
    },
    onValueChange: function () {
        bar();
    }
});

linkModel.prototype.defaults.traits.push({
    type: 'internal-link',
    label: 'Internal link',
    name: 'internal-link'
})
```

Is there anything I'm missing? An extra attribute perhaps? Everything else works fine, except for this detail (which is apparently very important to my customer).

I am currently on release 14.6 and I can't find a way how to force GrapesJS to render the dropdown indicator like it does for all default component traits (e. g. link target).

**Comment by nojacko** [comment]
I think you have to override the CSS. 

```
.gjs-trt-trait .gjs-field .gjs-input-holder select {
    -webkit-appearance: menulist;
    -moz-appearance: menulist;
    appearance: menulist;
}
```

**Comment by baxxos** [comment]
Successfully resolved via a "dirty hack" (overloading the `initialize` method) referenced here: [#972](https://github.com/artf/grapesjs/issues/972)

```
initialize: function () {
    editor.TraitManager.getTraitsViewer().itemView.prototype.initialize.apply(this, arguments);
    this.tmpl = '<div class="' + this.fieldClass + '"><div class="' + this.inputhClass + '"></div>' + '<div class="' + this.ppfx + 'sel-arrow"><div class="' + this.ppfx + 'd-s-arrow"></div></div> </div>';
},
```
