### ISSUE TITLE
How to listen an event for custom component's style update?

### ISSUE THREAD

**Issue by anand-gopinath** [artf/grapesjs#990]
@artf @arthuralmeidap @nojacko 
I have a custom component like, this and i the code looks like [https://jsfiddle.net/nganand/n97g7g43/](url) . 

![bbb](https://user-images.githubusercontent.com/25955939/38173314-f37c8ef8-35d9-11e8-94cd-db9da5c4559e.png)

1. How to listen to an event when custom component's property changed (Ex, when styling padding/margin)? like 
`
  init() {
  this.listenTo(this.model, "component:styleUpdate:text-align", this.handleChange)
  }
`
2. I wish align the button to left, by selecting not parent. Instead by selecting the ancestor. So How to change the custom component's children view when parent selected ? I did something like
   `
      this.model.attributes.components.models[0].attributes.attributes.align = "left"
      this.el.getElementsByClassName("mjmlButton")[0].align = "left";
      this.render()
   `
    But not worked?

**Comment by artf** [comment]
1. For component's properties use `this.listenTo(this.model, "change:prop-name" ...`
2. By doing `...attributes.align = "left"` Component doesn't see your changes, use instead `this.model.components().at(0).addAttributes({ align: 'left' })`, you don't need to update/render the element.
