### ISSUE TITLE
uploading video in the image element

### ISSUE THREAD

**Issue by Belal-Azzam** [artf/grapesjs#991]
hi. i was trying to implement uploading videos using the image element with the asset manager i stopped at the step where i wanted to replace the img tag with a video tag in the updateTarget call back, i am asking if there is an easy way for implementing that?
 thanks in advance.
here is a snippet from my code
```js
	var assets = [];

      var editor = grapesjs.init({
        height: '100%',
        showOffsets: 1,
        noticeOnUnload: 0,
		components: '',
		style: '',
        container: '#gjs',
        fromElement: true,
		
        plugins: ['gjs-preset-webpage'],
        pluginsOpts: {
          'gjs-preset-webpage': {}
        },
		assetManager: {
		 assets: assets,
		 noAssets: '',	
		 upload: '/owner/website_front/media/asset_upload',
		 uploadName:'Media', 
		 headers: {},
		 autoAdd: 1,
		 addBtnText: 'Add image',
		 // Text on upload input
		uploadText: 'Drop files here or click to upload',

		modalTitle: 'Select Image',

		 params: {},
		},

		storageManager: {
			type: 'remote',
			stepsBeforeSave: 1,
			urlStore: '',	
			urlLoad: '',
			params: {},   // For custom values on requests
		}
      });
	  
	 // Get the Asset Manager module first
	const am = editor.AssetManager;
	am.addType('video', {
			  view: {
					updateTarget(target) {
					const src = this.model.get('src');
					// Just to make things bit interesting, if it's an image type
					// I put the svg as a data uri, content otherwise
					if (target.get('type') == 'image') {
					  // Tip: you can also use `data:image/svg+xml;utf8,<svg ...` but you
					  // have to escape few chars
					  
					   
//					  target.set('src', `data:mime/type;base64,${btoa(svg)}`);
					} else {
//					  target.set('content', svg);
					}
				  },

				   getPreview() {
					 const src = this.model.get('src');
					 return `<div>
							<video 
								class="gjs-no-pointer" 
								style="height: 100%; width: 100%;"
								src="${src}">
							</video></div>`;
				   },
				    getInfo() {
                     return '<div>'+ this.model.get('src') +'</div>';
                 }
			   },
			   isType(value) {
						// eg. here you might check/parse/fetch url and try to 
						// understand the type
						
						
						if (typeof value == 'string' ) {
							value_parts = value.split('.');
							ext = value_parts[value_parts.length - 1];
							if(ext == 'mp4'){
								console.log('4444');
							return { type: 'video', src: value  };
							}
						}
			   }
		});
am.add({type:'video',src:'https://oidev.daftra.dev/files/db4715bd/medias/d9717_SampleVideo_1280x720_1mb.mp4'});

am.render(am.getAll().filter(asset => asset.get('type') == 'video'
));```

**Comment by artf** [comment]
You can update the tag name of the component in this way `model.set('tagName', 'new-tag')`

**Comment by ecmascriptguru** [comment]
Hi @artf 
Because the *Video* block doesn't ask to choose any video file, I've used the image block to upload video files. 
Here is my codebase to add video type.`

> editor.AssetManager.addType('video', 
        {
            view: {
                updateTarget(target) {
                    if (target.get('type') == 'image') {
                        this.model.set('tagName', 'video')
                        target.set({
                            type: 'video',
                            tagName: 'video',
                            src: this.model.get('src')
                        })
                    }
                },
                getPreview() {
                    const src = this.model.get('src');
                    return `<div>
                                <video 
                                    class="gjs-no-pointer" 
                                    style="height: 100%; width: 100%;"
                                    src="${src}">
                                </video>
                            </div>`;
                },
                getInfo() {
                    return '<div>'+ this.model.get('src') +'</div>';
                }
            },
            isType(value) {
                if (typeof value == 'string' ) {
                    value_parts = value.split('.');
                    ext = value_parts[value_parts.length - 1];
                    validExtensions = ["mp4", "mov", "avi", "mpg", "flv"]
                    if(validExtensions.indexOf(ext) > -1){
                        return { type: 'video', src: value  };
                    }
                }
            }
        });

It does change the **image** tag into **video** tag and it does work. But the issue is that settings panel is still things for image tag rather than video like `autoplay`, `control`, etc.

![image](https://user-images.githubusercontent.com/26412355/39232161-5e055eea-483a-11e8-8d10-33c38563ef48.png)
The above screenshot will tell you a bit more.
I hope you would like to let me know how to fix this issue.

Thanks,
Alexis

**Comment by artf** [comment]
@ecmascriptguru I would rather suggest to extend the video component and implement the modal ([like in ComponentImageView](https://github.com/artf/grapesjs/blob/dev/src/dom_components/view/ComponentImageView.js#L63-L76))

**Comment by usman-vqode** [comment]
You can just add it to the video by using the asset manager...

   this.editor.on('component:create', model => {
      if (model.get('type') === 'video') {
        this.editor.runCommand('open-assets', {
          target: model
        });
      }
    });

**Comment by throne1986** [comment]
Hi guys I tried the solution but I get the error :  
        
        ` Line 373:11:  'value_parts' is not defined  no-undef 
          Line 374:11:  'ext' is not defined          no-undef 
          Line 374:17:  'value_parts' is not defined  no-undef 
          Line 374:29:  'value_parts' is not defined  no-undef 
          Line 375:15:  'ext' is not defined   `

How do I define these values?

**Comment by gaianraja** [comment]
Hi, 

I am looking for uploading a video similar to Image upload. Can anyone suggest me a snippet? How do I replicate and customize?

Thanks,
Raja K
