### ISSUE TITLE
Didn't display data with remote storageManager

### ISSUE THREAD

**Issue by duccanh0022** [artf/grapesjs#993]
Hi, I have a problem:
When I copy and paste email template (http://www.charlesmudy.com/respmail/ - I used gjs-open-import-webpage plugin). Save to db ...seen everything OK. 
* Editor:
<img width="1277" alt="screen shot 2018-04-03 at 11 16 19" src="https://user-images.githubusercontent.com/4942484/38228973-7cf40f60-3730-11e8-948e-f48dee3d26d6.png">

* Some lines in db:
<img width="1280" alt="screen shot 2018-04-03 at 11 18 56" src="https://user-images.githubusercontent.com/4942484/38229031-d70610a2-3730-11e8-8622-7d76914c4107.png">

* However, when I reload webpage. Editor is empty now
<img width="1192" alt="screen shot 2018-04-03 at 11 15 06" src="https://user-images.githubusercontent.com/4942484/38228955-5e6fb0bc-3730-11e8-81ee-8f3d27079327.png">

* This is my source code
<img width="693" alt="screen shot 2018-04-03 at 11 17 18" src="https://user-images.githubusercontent.com/4942484/38228994-9a146bee-3730-11e8-851d-4e001fccf1bb.png">

** Please help me, Thanks all!!!

**Comment by artf** [comment]
So when you refresh the page the load request is sent, right?
Try to see what you get from these listeners
```js
	editor.on('storage:load', function(e) {
      console.log('LOAD ', e);
    })
    editor.on('storage:store', function(e) {
      console.log('STORE ', e);
    })
```

**Comment by duccanh0022** [comment]
Hi, thanks for reply.
Finally, I have found my bug. Component field in mysql database is TEXT type not enough space. I changed to LONGTEXT. Everything seem OK.

Thanks again!
