### ISSUE TITLE
how to make sure block is dropped only at the top level

### ISSUE THREAD

**Issue by crazyxhz** [artf/grapesjs#994]
For example I have two blocks A and B that I want to drop to the editor canvas. But sometimes the block that dropped later become the child of existing block. That is A>B layout. But I want to force the blocks can only be the sibling level.eg. A+B
How can I do that? Maybe component:add event?

**Comment by anand-gopinath** [comment]
@crazyxhz : You can do it by adding data attributes to the content "data-gjs-droppable='.className'", For ex [https://jsfiddle.net/wswvuvab/2/](url)

**Comment by crazyxhz** [comment]
@anand-gopinath  cool~ work like a charm. Now I found many data attributes usage.... 
It is a very good framework but the doc is lag behind...
