### ISSUE TITLE
[Question ] how to add fields on trait dynamically

### ISSUE THREAD

**Issue by sublimekaushik** [artf/grapesjs#995]
I am building the trait when the application starts.
so getting the below fields at side bar as settings
![trait2](https://user-images.githubusercontent.com/16155284/38231587-cf1a764e-3730-11e8-98a2-08412b20283b.png)

Now I want more field to be loaded (in the below picture 'product' and 'Product Image' ) along with previously loaded field ('Logo Url', 'Redirect Url').  And these two fields('product' and 'Product Image' ) will be coming through an API . I want these two fields ( 'product' and 'Product Image') to be loaded   while clicking on that particular section.
![trait3](https://user-images.githubusercontent.com/16155284/38231796-c81a0fca-3731-11e8-9612-1521bd6a4279.png)

So  in trait_manager exactly where  I have to make the changes (api call for adding fields ) to achieve this. 
Addition of product' and 'Product Image' these two fields should happen while clicking on the section only ;

**Comment by artf** [comment]
In your case, you have to update all those models
`model.get('traits').add([{name: 'product'}, {...}])`
