### ISSUE TITLE
[BUG] Modal is not scrollable

### ISSUE THREAD

**Issue by alimajed93** [artf/grapesjs#997]
Hello everyone,

I noticed that if the size of the screen is smaller than height of modal, the modal is cropped, and the user cannot scroll to the bottom of the modal, in other words, a part of the modal becomes unaccessible.
The following attached image shows how the image block modal is cropped (one small part of the modal is scrollable (the list of images), but I am talking about the whole modal in this case)
<img width="1279" alt="screen shot 2018-04-03 at 12 57 50 pm" src="https://user-images.githubusercontent.com/28840780/38243126-378dc09c-373f-11e8-8347-d5f855ca7924.png">

I think the whole modal should be scrollable when needed.

Thanks

**Comment by artf** [comment]
This behavior was just adapted for the demo (where there is shouldn't be an issue with the size) you can tweak it easily with CSS
