### ISSUE TITLE
[BUG] Asset Manager sends empty request when uploading image

### ISSUE THREAD

**Issue by tonygiang** [artf/grapesjs#998]
Description: GrapesJS editor is initialized in an editor.html file as follows:

```
  var editor = grapesjs.init({
    container: '#gjs',
    height: '100%',
    fromElement: true,
    plugins: ['gjs-preset-newsletter'],
    assetManager: {
      autoAdd: 1,
      upload: 'http://localhost:9001/uploadimage.php',
      uploadName: 'upload',
    },
  });
```
`localhost:9001` is a local IIS server running PHP5. The content of `uploadimage.php` is as follows:
```
<?php
$logfile = fopen("testlog.txt", "a+");
$req_dump = print_r($_FILES, TRUE);
fwrite($logfile, $req_dump . PHP_EOL);
fclose($logfile);
```
Since images uploaded from GrapesJS is expected to be in the `$_FILES` array, I dump all of its content to a log file everytime a request reaches this page. The `testlog.txt` file always gets
```
Array
(
)
```
each time I upload an image from the Image element found in `gjs-preset-newsletter` plugin, indicating that Asset Manager is sending empty requests to the server. File upload is enabled in my php.ini:
```
file_uploads = On
upload_max_filesize = 2M
max_file_uploads = 20
```
And the test image file is way below PHP's limit. To be exact, I used GitHub_Logo.png found in a package [here](https://github.com/logos) for testing.
Am I doing something wrong?

OS: Windows 10
GrapesJS version: v0.14.6
Browser: Chrome 65

**Comment by artf** [comment]
What about the client-side? Do you see the upload request correctly (eg. from the inspector)?
